### PR TITLE
Create jadavpuruniversity.txt

### PR DESCRIPTION
**Pull request by biswajit-halder-ju**

### CODE REVIEW

**Comment by biswajit-halder-ju** [comment]
Adding Jadavpur University to the list

**Comment by philipto** [comment]
@biswajit-halder-ju Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by biswajit-halder-ju** [comment]
1.   University official website URL:    http://www.jaduniv.edu.in/

2.1    Course offered URL:  Direct URL not visible. Go to
http://www.jaduniv.edu.in/ > Academics > Cources > Select discipline "Engg
and Tech", Level "Any" and Department "Any" > Search  ::: Choose any
computer related course for details.

2.2   Syllabus URL for Computer Science and Engineering :
http://www.jaduniv.edu.in/upload_files/course_file/1333457026-1.04

3.  Domain Proof::  regarding the email domain, it is mentioned at the
bottom of university home page(screenshot attached). A seperate pdf file
link is here that shows the email ids of faculty of Computer Science and
Engineering Department.
*http://www.jaduniv.edu.in/new_upload/new_emaillist/engg/cse.pdf
<http://www.jaduniv.edu.in/new_upload/new_emaillist/engg/cse.pdf>*



Thanks & Regards,

*Biswajit Halder*
Junior Research Fellow
Dept. of Computer Sc. & Engg.
Jadavpur University
M: 9007525499 / 8777062079
Email : biswajithalder.rs@jadavpuruniversity.in
            biswajit_res@yahoo.in

**Comment by philipto** [comment]
@biswajit-halder-ju Pull request merged. Thank you for the update!

**Pull request merged**
