### PR TITLE
Create coding-academy.txt

### PR DESCRIPTION
**Pull request by trubesv**
Added Coding Academy (`@coding-academy.fr`)

### CODE REVIEW

**Comment by philipto** [comment]
@trubesv I am sorry for a delay with processing your request. In general, this repository is for universities which offer at least 1-year-long (or longer) courses, but your academy seems to be very focused on teaching IT-related courses, and 22-weeks course seems to be very dense. Also, the academy is created by well known universities in France, which have very good reputation. This is why we will consider adding the academy to this repository as an exception. Thank you for your patience.

**Comment by philipto** [comment]
@trubesv We considered an option to add the Academy email domain to this repository, and regrettably it was decided that we are not able to make an exception. There are no long-term (> 1 year long) courses offered by the academy, thus we cannot do it. I have to close the request without merging. Please reopen and comment if I am mistaken and you have long-term courses. Thank you for the understanding.

**Comment by trubesv** [comment]
@philipto Hello, thanks for having done your research and getting back to me.

You're right, while most of the courses are short term (< 9 months), there is one new course that spreads across a whole year. It may not have been advertised yet.

Starting in June, it is really intense (9h-21 from Monday to Friday until September) and packs 2 internships : a part-time one until January followed by a full-time one until next June, leading to final examinations and graduations.

This course is really focused on Java as it is part of a partnership with CapGemini, where the reconverting adults will do their internships.

Hence, we advised them to use IntelliJ because of its great and efficient time-saving features, along with a code quality focus. 

Now, we - both the students and the teachers - would like to be able to use the student license across the JetBrains products with a `@coding-academy.fr` mail address.

I hope you will take this new information into account and consider adding the academy to this repository as an exception. Thank you for your understanding!

Vincent

**Comment by philipto** [comment]
@trubesv Thank you for the update! Given that you are affiliated with EPITECH and you have a year-long internship, it was decided that your school is now eligible for requesting free licenses for JetBrains tools on the base of possessing the email in the domain. Pull request merged. Thank you!

**Pull request merged**
