### PR TITLE
Eastside Catholic School

### PR DESCRIPTION
**Pull request by tiecia**
This is a Catholic high school in Sammamish, Washington, USA. It has a strong CS program that is growing rapidly. Over 100 students are taking some form of CS class.

### CODE REVIEW

**Comment by philipto** [comment]
@tiecia Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by tiecia** [comment]
Here is the official school website: https://www.eastsidecatholic.org/

Is this enough? I am a little confused as to what you mean by "an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students." What would be enough proof for you to confirm that .org is the school domain?

**Comment by philipto** [comment]
@tiecia Thank you! The proof is needed because the official website is https://www.eastsidecatholic.org/, and thus official school domain is eastsidecatholic.org. You request to add the domain **eastsidecatholicschool.org** to this repository, however it differs from the official school domain, which is **eastsidecatholic.org** (please notice the difference between the two domain names mentioned).

I did not find eastsidecatholicschool.org domain mentioned anywhere at the official school website as a domain dedicated to teachers and/or students of the school, thus I need some document which confirms that the school considers eastsidecatholicschool.org as the domain for the teachers and/or students of the school. 

I appreciate you effort to provide us with such a proof. Thank you, and have a Happy New Year!

**Comment by tiecia** [comment]
Ah, I understand now. Give me a couple of days until school gets back in session and I should be able to get that information to you.

**Comment by tiecia** [comment]
Hi again, sorry for the delay. What would constitute enough proof for you to approve the eastsidecatholicschool.org domain? Should I point you to the school principal or IT director? Should I have the IT director send you an email from an email with the eastsidecatholic.org domain confirming that the eastsidecatholicschool.org domain is used by the school?

The way they are organized here is all teachers and faculty members are on the eastsidecatholic.org domain and all the students are on the eastsidecatholicschool.org domain.

**Comment by philipto** [comment]
@tiecia Thank you for the clarification. Finally, I managed to find the proof: https://avestia.com/MCM2018_Proceedings/files/paper/HTFF/HTFF_148.pdf

Thus, your pull request merged, and this school's teachers and students can now request their free licenses at https://www.jetbrains.com/shop/eform/students. Thank you.

**Pull request merged**
