### PR TITLE
Create antiquespride.txt

### PR DESCRIPTION
**Pull request by lamerock**
adding the antiquespride.edu.ph domain on the list

### CODE REVIEW

**Comment by philipto** [comment]
@lamerock First stage of verification passed, official domain for **University of Antique** is [antiquespride.edu.ph](https://antiquespride.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@lamerock Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by lamerock** [comment]
@philipto   Good day. I would like to share with you the URLs of the courses offered by the university. These URLs are from our Learning Management System.

Bachelor of Science in Information Technology : https://eskuela.antiquespride.edu.ph/course/index.php?categoryid=934
Bachelor of Science in Computer Science : https://eskuela.antiquespride.edu.ph/course/index.php?categoryid=935
Bachelor of Science in Computer Engineering : https://eskuela.antiquespride.edu.ph/course/index.php?categoryid=964

**Comment by philipto** [comment]
@lamerock  Thank you for the clarifications. Pull request merged.

**Pull request merged**
