### PR TITLE
Add Technical High School of Lodz and ZSP nr 5 Lodz

### PR DESCRIPTION
**Pull request by pk2**
Official websites:
https://zsp5lodz.pl/
https://liceum.p.lodz.pl/

### CODE REVIEW

**Comment by BangVoLe** [comment]
[file.zip](https://github.com/JetBrains/swot/files/8457221/file.zip)
Offcial websites: https://ajc.hcma.vn/
Name school: Học viện Báo chí và Tuyên truyền 
English Name: Academy of Journalism and Communication

**Comment by philipto** [comment]
@pk2 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

@BangVoLe Please make a separate pull request for your domain. Thank you.

**Comment by pk2** [comment]
@philipto Hello. I have confirmation for one school and waiting for another. 
https://zsp5lodz.pl/strona/logowanie-do-uslugi-office-365

**Comment by pk2** [comment]
@philipto Is this section About on FB sufficient?
https://www.facebook.com/PLOPolitechnikiLodzkiej/

**Comment by philipto** [comment]
@pk2 Thank you very much for the clarification. Pull request merged.

Second school has an email domain identical to the official website, thus an additional proof is not necessary. Thank you!

**Pull request merged**
