### PR TITLE
Create embl.txt

### PR DESCRIPTION
**Pull request by YanPYuan**
embl.de

### CODE REVIEW

**Comment by YanPYuan** [comment]
embl.de

**Comment by philipto** [comment]
@YanPYuan Pull request merged. Please notice that the only people eligible for free JetBrains licenses granted for using in education are teachers and students. Researchers shall apply for their regular licenses to sales@jetbrains.com, and it's OK to discuss possible discounts if necessary. Researchers also may benefit from using Open Source contributers license from JetBrains which is also free (for those who maintain open source projects).

**Comment by YanPYuan** [comment]
Thank you for your merging. Does it mean that you'd not consider EMBL as an educational/non-profit/research institution. I'm wondering how DKFZ is handled at your site or University Heidelberg. Actually, our bioinformatic group here  has also 5 PhD students now. They'd apply for the edu license on your site, right? 

Thank 
Yan
PS: I'm asking for other pythion developers; myself is more in the PERL world.

**Comment by philipto** [comment]
@YanPYuan JetBrains grants free licenses to educational institutions for educational purposes. Sometimes we make exceptions for research institutions, if they have long-term IT-related courses for PhD students. In general, this repository, which allows students and teachers to apply on the base of posessing an email address in a university- or college-owned email domain, contains domains of universities and colleges. 

As far as I can see, EMBL is a research institution, which meets the exception conditions. It's important to note, however, that if a person posesses the email address at EMBL, the person shall be a teacher or a student, including PhD students, in order to use free JetBrains licenses for educational purpose. If the person is a reseacher, or a purpose of using the tools is not an education, regular individual non-free license shall be used.

Please do not hesitate to write an email to sales@jetbrains.com if anything is unclear in the type of license one can use. Thank you!

**Comment by YanPYuan** [comment]
Thank you for your explanation. We'll forward your information to our Python programmers who wish to use it.

**Pull request merged**
