### PR TITLE
add seecs email domain

### PR DESCRIPTION
**Pull request by ShehryarShoukat96**
This PR adds SEECS email domain.

### CODE REVIEW

**Comment by philipto** [comment]
@ShehryarShoukat96 Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by ShehryarShoukat96** [comment]
@philipto The thing is SEECS is a School of NUST and has its own email domain (@ seecs.edu.pk). However, here are the details you want

- [Home Page](http://seecs.nust.edu.pk/Departments/Department-of-Computing/)

- [Courses Offered](http://seecs.nust.edu.pk/Departments/Department-of-Computing/Degrees-Offered/)

- They use Seecs.edu.pk domain for their faculty and students emails: [Faculty Page](http://seecs.nust.edu.pk/Departments/Department-of-Computing/Faculty/) (Check email of any faculty member)

**Comment by philipto** [comment]
@ShehryarShoukat96 Thank you for the clarification. Pull request merged.

**Comment by ShehryarShoukat96** [comment]
@philipto Thanks

**Pull request merged**
