### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by emka1981**
Thank you for adding our school

### CODE REVIEW

**Comment by philipto** [comment]
@emka1981 lib/domains/at/bg_porica_spittal_drau.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by emka1981** [comment]
The path is ok, isn't it ? i put it into lib/domain/at ....
The missing informations are:
1.)
https://www.bg-porcia.at/
https://www.brg-spittal.com/
http://www.borg-spittal.at/
https://www.hakspittal.at/
It is a whole school campus with 4 schools.
2.)
https://www.hakspittal.at/index.php/htl-mechatronik
https://www.brg-spittal.com/schwerpunkte/informatik/
on this page for example (not only) you can see the IT courses
3.)
the domain address @bildung.gv.at is from the government in austria. in fute all schools of austria will have it. Then its in austria everywhere the same: vorname.nachname@bildung.gv.at

Greeting Martin Krautgartner

**Comment by emka1981** [comment]
i see the problem, i don't know how to create a directory on github. I wanted to create a gv directory. Nor i can't delete any files.

**Comment by emka1981** [comment]
So i hope this works now in the right way!
Greeting Martin Krautgartner

**Comment by philipto** [comment]
@emka1981 Dear Martin,
I feel there is some misunderstanding:
1) lib/domains/at/gv/borg_porica_spittal_drau.txt file represents a domain borg_porica_spittal_drau.gv.at, which does not exist:
```
$ host borg_porica_spittal_drau.gv.at
Host borg_porica_spittal_drau.gv.at not found: 3(NXDOMAIN)
```
Therefore, I can not satisfy this request immediately.

2) As you say, email addresses at bildung.gv.at are given to all schools in Austria, and we have to perform an investigation to ensure that addresses in this domain are assigned to students and teachers only, and they stop working after the graduation of the students. In general, we avoid including umbrella domains covering many schools at once to this repository for security reasons.

Please send your request to community-support@jetbrains.com, it has to be considered as a special case, because the domains which you mention do not belong to a particular university, nor to a college.

I have to close the request as for now. Thank you for the understanding.

**Pull request closed without merging**
