### PR TITLE
Added sornas.txt

### PR DESCRIPTION
**Pull request by Picasso11**
EDTA Sornas - Paris, France

### CODE REVIEW

**Comment by philipto** [comment]
@Picasso11 Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Picasso11 You might miss my previous comment. Please reply.

**Comment by Picasso11** [comment]
Hi,

Sorry, I didn'thave access to my e-mails for some days.

* http://www.edta-sornas.com/
* http://www.edta-sornas.com/nouvelles-filieres-informatiques_ad31.html
(Bac Pro is 3 years long, BTS 2 years and DEES 3 years)
* Please find attached to this e-mail a screenshot from the headmistress
(Suzanne Debonnaire) asking me to active the e-mails for the IT students.
In case this doesn't match your request, I could ask for another proof but
I will need some more days to get the document.

Regards,

-- 
Jules Aubert
Teacher at Sornas

2017-11-22 18:14 GMT+01:00 Philip Torchinsky <notifications@github.com>:

**Comment by philipto** [comment]
@Picasso11 Thank you for the update. Regrettably, your message did not contain any attachments. Could you please resend the attachment? Thank you!

**Comment by Picasso11** [comment]
Are you sure ? I see the picture attached to the discussion, named
"email_directrice_activation.png". Here is a link to the picture :
http://oi66.tinypic.com/28slcuh.jpg
Thank you.

2017-11-27 10:12 GMT+01:00 Philip Torchinsky <notifications@github.com>:

**Comment by philipto** [comment]
@Picasso11 Thank you for the update. I will check why I did not see it before. Just for the record, I found an additional proof: http://files.sornas.fr/dossier-de-candidature-2016.pdf. Pull request merged. Thank you!

**Pull request merged**
