### PR TITLE
Create dav.txt

### PR DESCRIPTION
**Pull request by Harry-Nguyen90**

### CODE REVIEW

**Comment by philipto** [comment]
@Harry-Nguyen90 First stage of verification passed, official domain is [dav.edu.vn](https://dav.edu.vn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Harry-Nguyen90** [comment]
@philipto thank you very much, look forward your approval

**Comment by philipto** [comment]
@Harry-Nguyen90 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by Harry-Nguyen90** [comment]
hi @philipto 
https://www.dav.edu.vn/du-kien-phuong-thuc-tuyen-sinh-dai-hoc-nam-2024/

**Comment by philipto** [comment]
@Harry-Nguyen90 According to the webpage that you referred to, there are several majors in the school, and they are described in this translation of the page:
```
II. ADMISSION QUOTA

    Total planned admissions: 2200.
    Each major has its own admission quota. In case one major has excess applicants, the quota can be transferred to another major if needed. The quotas are as follows:
        International Relations: 460
        English Language: 200
        Economics: 260
        Law: 200
        International Communications: 460
        Business Administration: 260
        Chinese Language - Thai Binh Dialect: 160
        International Trade Law: 200
```

Which of the majors require do any software development? This question is essential for adding the domain to the trusted list, because we must be sure that the students actually need to use JetBrains tools for their study, and will not give them away to third parties.

**Comment by Harry-Nguyen90** [comment]
Hi @philipto thank you very much for your feedback,
In Economics, we will be learning about basic python, database, business analytic, data analytic....during around 1.5 years

**Comment by philipto** [comment]
@Harry-Nguyen90 Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Comment by philipto** [comment]
@Harry-Nguyen90 Yes. 

The domain **dav.edu.vn** was removed from this trusted domains list because it was abused recently. It means third parties got control over many email inboxes in the domain and received licenses using the email addresses without being enrolled or employed at the university.

From now on, I recommend the students of this school an alternative way to get free licenses: 
1. Enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). 
2. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

The students can also apply with their ISIC cards at the ISIC tab at https://www.jetbrains.com/shop/eform/students.

**Comment by philipto** [comment]
@Harry-Nguyen90 and everybody reading these comments: please notice that we do not promise to read comments to already closed or merged pull requests in this repository. We may do it only occasionally. If you need to ask JetBrains team about student licenses, please send an email to community-support@jetbrains.com.

**Pull request merged**
