### PR TITLE
Create Moderno, Ensino, Educação, Cultura

### PR DESCRIPTION
**Pull request by Notiongirl**
#### Institution/School Name 
Moderno, Ensino, Educação, Cultura 

#### Instiution/School Website
https://www.google.com/url?sa=t&source=web&rct=j&url=https://portalmoderno.com.br/new/&ved=2ahUKEwib8o7NnsP9AhUwqpUCHcw1D0UQFnoECA0QAQ&usg=AOvVaw1_5-85wmqN7qvc013tk26u

#### Email Users

*Please place an x between the square brackets if yes*
- [ x ] Students
- [ ] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [ ] Graduate School
- [ ] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [ ] High School or equivalent
- [ x ] Elementary School or equivalent

### CODE REVIEW

**Comment by philipto** [comment]
@Notiongirl I am sorry, this domain seems to represent an elementary school, not a specific university or a college. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I will review this request later. Reviewing elementary schools takes much more time, because we generally do not recommend using professional software development tools in elementary schools. It is often not necessary for students, at least under 13 of age.

Thank you for your understanding!

**Comment by philipto** [comment]
@Notiongirl Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. [https://portalmoderno.com.br](https://www.google.com/url?sa=t&source=web&rct=j&url=https://portalmoderno.com.br/new/&ved=2ahUKEwib8o7NnsP9AhUwqpUCHcw1D0UQFnoECA0QAQ&usg=AOvVaw1_5-85wmqN7qvc013tk26u) website does not mention the domain positivosolucoes.com.br.

You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@Notiongirl You might miss my previous comment. Please react.

**Comment by Notiongirl** [comment]
https://positivoon.com.br

Em qua., 15 de mar. de 2023 12:48 PM, Philip Torchinsky <
***@***.***> escreveu:

**Comment by philipto** [comment]
@Notiongirl Regrettably, the information you provided about the school is insufficient. The link you shared in your last comment directs me to a login page without any clear indication of what the website is about. 

Without more reliable information about your school, I regret to inform you that I am unable to fulfill your request.
Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.
Thank you for your understanding!

**Pull request closed without merging**
