### PR TITLE
Added @student.mgppu.onmicrosoft.com

### PR DESCRIPTION
**Pull request by monnster**
Primary domain student.mgppu.ru has already been approved, this is alias.
Link to courses page - http://www.it.mgppu.ru/

### CODE REVIEW

**Comment by philipto** [comment]
@monnster Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students. We need some proof that this domain is an alias/redirect to the main email domain.

**Comment by monnster** [comment]
Hi! See the attached docs: screenshots of admin page and invoices from
Microsoft.

ср, 4 дек. 2019 г. в 16:03, Philip Torchinsky <notifications@github.com>:

**Comment by philipto** [comment]
@monnster I am really sorry for that, but GitHub strips out any attachments if they are sent by email. Could you please attach the same files using web interface at https://github.com/JetBrains/swot/pull/7259?

**Comment by monnster** [comment]
My bad... [student.mgppu.ru.zip](https://github.com/JetBrains/swot/files/3926666/student.mgppu.ru.zip)

**Comment by philipto** [comment]
@monnster Thank you for the clarification. Pull request merged.

**Pull request merged**
