### PR TITLE
Create nyjc.txt

### PR DESCRIPTION
**Pull request by recreationx**
Nanyang Junior College
2 year H2 Computing (A-Levels) program

### CODE REVIEW

**Comment by recreationx** [comment]
https://nanyangjc.moe.edu.sg/
https://nanyangjc.moe.edu.sg/staff/academic-departments/mathematics-department
(H2 Computing)

**Comment by philipto** [comment]
@recreationx Please provide us with a proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@recreationx You might miss my previous comment. Please react.

**Comment by recreationx** [comment]
I am unable to find on the official website proof of the usage, as the education ministry uses a different email domain from the school's one.  However, I am able to show you proof of the school recognizing the domain from the student portal and gmail itself.
https://i.imgur.com/GbMvC98.png
https://i.imgur.com/dkUpAzK.png

I censored my personal information, and hope that this would suffice as evidence.

**Comment by recreationx** [comment]
On the school page, https://nanyangjc.moe.edu.sg/, scrolling down, under student portals, you will find that the first student portal has the domain https://portal.nyjc.edu.sg/, thus proving the domain's validity and ownership.

**Comment by philipto** [comment]
@recreationx Thank you for the clarification. Pull request merged.

**Pull request merged**
