### PR TITLE
Add UPEN

### PR DESCRIPTION
**Pull request by CairParavel314**
Añadir Universidad Politécnica del Estado de Nayarit

### CODE REVIEW

**Comment by CairParavel314** [comment]
This is the web page of our university http://www.upnay.edu.mx/

**Comment by philipto** [comment]
@CairParavel314 First stage of verification passed, official domain is [upnay.edu.mx](https://upnay.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@CairParavel314 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by CairParavel314** [comment]
Thank you, how many days I have to wait to request the academic license?

**Pull request merged**
