### PR TITLE
Create cbit.txt

### PR DESCRIPTION
**Pull request by pruthvi51**
url: https://www.cbit.ac.in/academic_post/department-of-computer-science-and-engineering/

### CODE REVIEW

**Comment by philipto** [comment]
@pruthvi51 Please provide us with a proof, which shows that the school recognizes the domain cbit.org.in that you are submitting as an official email domain for the students.

**Comment by pruthvi51** [comment]
Sure, please take a look at http://learning.cbit.org.in/ (LMS) and scroll down to footer for more information.

**Comment by pruthvi51** [comment]
Sure @philipto , please take a look at http://learning.cbit.org.in/ (LMS), scroll down to footer for more information.

**Comment by philipto** [comment]
@pruthvi51 Thank you. There is a link at http://learning.cbit.org.in/ to cbit.ac.in. I need the opposite: a link from the official website to cbit.org.in. It can be not a link, but a copy of an email or printed instructions for students. We have to ensure that the university recognizes the domain cbit.org.in as an official. Thank you.

**Comment by pruthvi51** [comment]
dear @philipto , at https://www.cbit.ac.in/ in the nav bar checkout "Student-Info" which will point to https://erp.cbit.org.in/Login.aspx?ReturnUrl=%2f ,furthermore we were informed of our email by a message of which i'm attaching a  screenshot. Hope this will be sufficient. Thank you!
Screenshot 2020-09-16 175449

**Comment by philipto** [comment]
@pruthvi51 Thank you for the clarification. Pull request merged.

**Pull request merged**
