### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by eliaslothus**
Lothus EAD

### CODE REVIEW

**Comment by philipto** [comment]
@eliaslothus Please provide us with:
* the school full official name in Portuguese
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@eliaslothus You might miss my previous comment. Please react.

**Comment by lothusinfo** [comment]
Nome da Escola: Academia de Mestres Cristãos

Modalidade: EAD

URL: https://academiademestrescristaos.com.br

Endereço: 
Avenida Santos Dumont, 20 B – Anil – São Luís – MA – Brasil CEP 65046-660

A escola tem mais de 12 anos no mercado ministrando curso para Crianças, Adolescente e jovens. E agora estará implantando tencnologia para esses grupos de pessoas.

Os e-mails são criados no domínio 
lothus.app.br que é o domínio específico da escola para a divisa de programação de computadores e apps

**Comment by philipto** [comment]
@eliaslothus Regrettably, I have to close the request without merging, because this organization is a training center, not a college, nor a university. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot).

Please apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses.

Also, there are not enough proof that the domain **lothus.app.br** belongs exclusively to the training center. I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
