### PR TITLE
Inclusão da Unisociesc

### PR DESCRIPTION
**Pull request by levit**

### CODE REVIEW

**Comment by philipto** [comment]
@levit First stage of verification passed, official domain is [unisociesc.com.br](https://unisociesc.com.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@levit Please provide us with:
* the school official full name (**not an abbreviation, not a nickname**).
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. 
Thank you!

**Comment by philipto** [comment]
@levit You might miss my previous comment. Please react. 
Thank you.

**Comment by levit** [comment]
To access information on a course lasting more than 1 year, please visit the website https://www.unisociesc.com.br/graduacao/analise-e-desenvolvimento-de-sistemas/ and choose the face-to-face modality , or ead, any unit and shift and the information will appear as shown in the attachment of this message.
Printscreen

**Comment by philipto** [comment]
@levit Thank you very much for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
