### PR TITLE
Create apps.txt

### PR DESCRIPTION
**Pull request by sindelarken**
District home page URL:
[https://losrios.edu/](https://losrios.edu/)
Computer Information Science program at Cosumnes River College URL:
[https://crc.losrios.edu/academics/programs-and-majors/computer-information-science](https://crc.losrios.edu/academics/programs-and-majors/computer-information-science)
Student information URL link directing student to use email domain:
[https://losrios.edu/student-resources/technology-resources/apps-and-software-for-students/google-apps-and-preferred-email](https://losrios.edu/student-resources/technology-resources/apps-and-software-for-students/google-apps-and-preferred-email)

### CODE REVIEW

**Comment by philipto** [comment]
@sindelarken I am sorry, the domain apps.losrios.edu is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Comment by sindelarken** [comment]
I didn't see 'apps.losrios.edu' in abusted.txt. 
image
Would you please verify that the specific domain 'apps.losrios.edu' was removed from your trusted domains?
If it really was but is not listed in abusted.txt I will enroll in the [GitHub Student Developer Program](https://education.github.com/discount_requests/application).

**Comment by sindelarken** [comment]
@philipto 
I didn't see 'apps.losrios.edu' in abusted.txt.
image
Would you please verify that the specific domain 'apps.losrios.edu' was removed from your trusted domains?
If it really was but is not listed in abusted.txt I will enroll in the [GitHub Student Developer Program](https://education.github.com/discount_requests/application).

**Comment by philipto** [comment]
@sindelarken Yes, it was. There is its parent domain losrios.edu in abused.txt. The domain was abused heavily in 2018-2019. The school might have changed the email policy and made the mail accounts secure since then. If the domain is not abused anymore, please ask someone from the school administration to email us about it community-support@jetbrains.com.

In the meantime, as you said, you can enroll in the [GitHub Student Developer Program](https://education.github.com/discount_requests/application).

**Pull request closed without merging**
