### PR TITLE
feat/itsvc

### PR DESCRIPTION
**Pull request by pedrogzvargas**
itsvc.edu added

### CODE REVIEW

**Comment by philipto** [comment]
@pedrogzvargas First stage of verification passed, official domain is [vcarranza.tecnm.mx](https://vcarranza.tecnm.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.vcarranza.tecnm.mx/content/convocatoria/Convocatoria%20Proceso%20de%20Admisi%C3%B3n%20ITSVC%202021-2022.pdf

**Comment by philipto** [comment]
@pedrogzvargas Please provide us with:
* the school official website URL (I could be mistaken with the verification as shown in the comment above)
* the school street address, including city 
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@pedrogzvargas You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@pedrogzvargas I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by dhlechuga** [comment]
the school official website URL:https://www.vcarranza.tecnm.mx/new_tec/view/inicio/
the school street address, including city:  Av. Tecnológico S/N, Col. El Huasteco, Ciudad Lázaro Cárdenas, Venustiano Carranza, Puebla.
 URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: https://www.vcarranza.tecnm.mx/new_tec/view/carreras/carrera.php?abreviatura=ISIC

**Pull request closed without merging**
