### PR TITLE
Add CEAC.es institute

### PR DESCRIPTION
**Pull request by Vito-Pulls**
https://www.ceac.es/fp-informatica-comunicaciones

### CODE REVIEW

**Comment by Vito-Pulls** [comment]
Institution/School Name
CEAC Official Professional Training Institute

Instiution/School Website
https://www.ceac.es/

Email Users
[victor.suarez@alu.ceacfp.es](mailto:victor.suarez@alu.ceacfp.es)

**Comment by Vito-Pulls** [comment]
Greetings,

Where do i send this info? Does it work by email or do i comment it on
github??

Thank you.

**Comment by Vito-Pulls** [comment]
This is a screenshot from an email sent by the school the first week of
classes.

**Comment by philipto** [comment]
@Vito-Pulls Thank you! Please upload the document with browser at the page https://github.com/JetBrains/swot/pull/24633 as a comment, DO NOT send it by email. GitHub strips out all attachments if sent by email.

**Comment by Vito-Pulls** [comment]
imagen_2024-11-02_010203105

**Comment by philipto** [comment]
@Vito-Pulls  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
