### PR TITLE
Add miftahul khoir

### PR DESCRIPTION
**Pull request by rendy-faqot**
Add my school to access JetBrains student

### CODE REVIEW

**Comment by philipto** [comment]
@rendy-faqot First stage of verification passed, official domain is [smaitmiftahulkhoir.sch.id](https://smaitmiftahulkhoir.sch.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by rendy-faqot** [comment]
> @rendy-faqot First stage of verification passed, official domain is [smaitmiftahulkhoir.sch.id](https://smaitmiftahulkhoir.sch.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Is there any updates related my request?

**Comment by rendy-faqot** [comment]
> @rendy-faqot First stage of verification passed, official domain is [smaitmiftahulkhoir.sch.id](https://smaitmiftahulkhoir.sch.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

@philipto is there any feedback?

**Comment by philipto** [comment]
@rendy-faqot Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
