### PR TITLE
Add UNIMY domain

### PR DESCRIPTION
**Pull request by mkr2x91**
https://www.unimy.edu.my/

https://www.unimy.edu.my/programme/bachelor-of-engineering-honours-in-computer-engineering

UNIMY

### CODE REVIEW

**Comment by philipto** [comment]
@mkr2x91 student.txt I am sorry, I have to close the request without merging, because you made a mistake in a request and did not specify any filepath. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and make a new correct request. Thank you for your understanding!

**Comment by philipto** [comment]
@mkr2x91 What is the student's email address pattern? username@student.unimy.edu.my?

**Comment by mkr2x91** [comment]
The student email address pattern is using the student ID

***@***.***



As per my student ID, my email is:

***@***.***

**Comment by philipto** [comment]
@mkr2x91 I am sorry, you misunderstood my question. What is a typical email address in this school? Is it username@student.unimy.edu.my? I mean, does it end with @student.unimy.edu.my? If not, what it ends with? What do you have after @ sign in your email address?

**Comment by mkr2x91** [comment]
Sorry for the confusion

Yes, the email address pattern is @student.unimy.edu.my

**Comment by philipto** [comment]
@mkr2x91 Thank you for the clarification. I corrected the filename to conform the repository rules. Pull request is now merged.

**Comment by philipto** [comment]
@mkr2x91 Please wait about an hour before start requesting the licenses to let the update to propagate through the system. Thank you!

**Comment by mkr2x91** [comment]
thank you @philipto

**Pull request merged**
