### PR TITLE
Added HES-SO//VS

### PR DESCRIPTION
**Pull request by cm0x4D**

### CODE REVIEW

**Comment by metc** [comment]
@zweizwei Any chance to merge this request ?
I am a student in this school and I really like to have an academic discount :school_satchel:

**Comment by cm0x4D** [comment]
http://www.hevs.ch: Our university page, sorry, only french and german.
http://www.hes-so.ch/en: All schools of western Switzerland union, this time in english too ;-)

If this helps, several of other universities of the HES//SO group are already registered:
lib/domains/ch/hefr.txt
lib/domains/ch/heig-vd.txt
lib/domains/ch/hes-so.txt
lib/domains/ch/hesge.txt

**Comment by zweizwei** [comment]
thanks a lot for the additional info - adding the domain.

**Comment by metc** [comment]
Great ! Thank you :notes:

**Comment by cm0x4D** [comment]
Thank you Elena.

**Comment by zweizwei** [comment]
@metc welcome!

**Pull request merged**
