### PR TITLE
Add Westmount Charter School

### PR DESCRIPTION
**Pull request by Syncinus**

### CODE REVIEW

**Comment by philipto** [comment]
@Syncinus Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Syncinus You might miss my previous comment. Please react.

**Comment by Syncinus** [comment]
School website URL: https://westmountcharter.com
Street address: 2215 Uxbridge Dr NW, Calgary AB T2N 4Y3
IT-related course: https://docs.google.com/document/d/1VObvidfOgEly5ttc-J4GTgY0-4sJel8W80mbX7sdwD0/edit this is the courses document which has an option course on computer programming, the Alberta Education course.
Domain proof: https://www.westmountcharter.com/mid-high-learning-commons/fiction-access-internal/ This blog post mentions usage of the wcs-g.com email. If this isn't good enough what kind of proof would be sufficient? I can't find any proper resources on the website about the usage of the domain for students and the teacher and administrative addresses are under @westmountcharter.com.

On the >1 year thing, are high schools allowed for this? The primary school board for Calgary (and the system I previously went to), the Calgary Board of Education, is on this list and operates only from kindergarten to grade 12 and I believe also only offers the per-semester Alberta computer programming or computer science course.

**Comment by philipto** [comment]
@Syncinus  Thank you for the clarifications. The additional facts you provided are sufficient. Pull request merged.

**Pull request merged**
