### PR TITLE
Create sharif.txt

### PR DESCRIPTION
**Pull request by BehnazHosseini**
example@mehr.sharif.ir
This is how the domain looks like.
Thanks.

### CODE REVIEW

**Comment by zweizwei** [comment]
the university domain is http://www.sharif.ir/home - please somehow confirm that the provided domain also belongs to the university and is used for emails. Thank you!

**Comment by BehnazHosseini** [comment]
How can I do so?
Would showing the login page of the E-mail system with this domain be
enough?

That's the university portal address; the E-mail domains are (the ones that
I know of):
example@sharif.ir
example@mehr.sharif.ir
example@sharif.edu
example@mehr.sharif.edu

Greetings!

On Jul 21, 2015 9:55 PM, "Elena Ganenkova" <notifications@github.com> wrote:
>
> the university domain is http://www.sharif.ir/home - please somehow
confirm that the provided domain also belongs to the university and is used
for emails. Thank you!

**Comment by zweizwei** [comment]
@BehnazHosseini yes, the login page should work fine - you can just send me a screen shot of it. Thank you!

**Comment by BehnazHosseini** [comment]
[image: Inline image 1]

This is it.

**Comment by zweizwei** [comment]
@BehnazHosseini the image didn't attach unfortunately. Please send it to me to classroom@jetbrains.com
Thank you!

**Comment by zweizwei** [comment]
@BehnazHosseini thank you - i've got your email and added the domain

**Comment by BehnazHosseini** [comment]
You're very welcome. :)

**Comment by awatme** [comment]
also please add another subdomain from sharif, mech.sharif.ir

**Comment by KilnOfTheSecondFlame** [comment]
Hi awatme
This pull-request is closed, I don't know if they will see your request.
I think the best thing you can do is open a new one for mech.sharif.ir (with the correct file created under /lib/domains/ir/mech/sharif.txt - I think) and send them proof
I only saw your message because I have it in my notifications =)

**Pull request merged**
