### PR TITLE
Create cu-elbayadh

### PR DESCRIPTION
**Pull request by marwane323**
http://www.cu-elbayadh.dz/en/
http://www.cu-elbayadh.dz/fr/index.php/departement-des-sciences-et-technologie/
http://www.cu-elbayadh.dz/fr/index.php/contact-2/

### CODE REVIEW

**Comment by philipto** [comment]
@marwane323 Please rename lib/domains/dz/cu-elbayadh to lib/domains/dz/cu-elbayadh.txt

**Comment by marwane323** [comment]
@philipto Done! Renamed the file to cu-elbayadh.txt

**Comment by philipto** [comment]
@marwane323 Pull request merged. Thank you!

**Comment by philipto** [comment]
@marwane323 Please let the new info to propagate through JetBrains system, and make a first request of a free license in about 30 minutes, not right now. Thank you! Happy coding!

**Pull request merged**
