### PR TITLE
Add School MydigitalSchool from group 

### PR DESCRIPTION
**Pull request by sylvainpellier**
School of the group EduServices http://www.groupe-eduservices.fr/
https://www.mydigitalschool.com/ecole-multimedia-angers

### CODE REVIEW

**Comment by sylvainpellier** [comment]
Just to explain the domain
MyDigitalSchool is a school of the group eduservices, as you can see on the website : http://www.groupe-eduservices.fr/ecole/my-digital-school

**Comment by sylvainpellier** [comment]
Email Users

[ ] Students
[ ] Academic/Teaching Staff

Education Levels

[ ] Post-graduate research
[ ] Graduate School

**Comment by philipto** [comment]
@sylvainpellier I am sorry for the delay of your request  processing. It required some additional checks. Thank you for your patience.

**Comment by sylvainpellier** [comment]
Can I make something to help ?

**Comment by philipto** [comment]
@sylvainpellier 

> Can I make something to help ?

Yes. Please provide us with a proof, which shows that the school recognizes the domain **eduservices.org** as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
5. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@sylvainpellier You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@sylvainpellier I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
