### PR TITLE
中国社会科学院大学（University of Chinese Academy of Social Sciences）

### PR DESCRIPTION
**Pull request by zxs5673**
中国社会科学院大学（University of Chinese Academy of Social Sciences）
https://www.ucass.edu.cn/
https://se.ucass.edu.cn/info/1053/1004.htm

### CODE REVIEW

**Comment by philipto** [comment]
@zxs5673 Thank you for your patience while waiting for a review and processing your request. 
Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@zxs5673 You might miss my previous comment. Please react.

**Comment by zxs5673** [comment]
hi , please chech this website :https://www.ucass.edu.cn/info/1075/3064.htm
or this contact web: https://www.ucass.edu.cn/info/1053/1698.htm
thanks

----- 原始邮件 -----
发件人：Philip Torchinsky ***@***.***>
收件人：JetBrains/swot ***@***.***>
抄送人：zxs5673 ***@***.***>,  Mention ***@***.***>
主题：Re:_[JetBrains/swot]_中国社会科学院大学（University_of_Chinese_Academy_of_Social_Sciences）_(PR_#14278)
日期：2022年06月14日 00点08分


@zxs5673 Thank you for your patience while waiting for a review and processing your request.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following:

A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
An URL of a page at the official school website that says that students use this email domain
A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
A WHOIS data that link the email domain to the school somehow
A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by zxs5673** [comment]
hi , please chech this website :https://www.ucass.edu.cn/info/1075/3064.htm

or this contact web: https://www.ucass.edu.cn/info/1053/1698.htm

thanks
----- 原始邮件 -----
发件人：Philip Torchinsky ***@***.***>
收件人：JetBrains/swot ***@***.***>
抄送人：zxs5673 ***@***.***>,  Mention ***@***.***>
主题：Re:_[JetBrains/swot]_中国社会科学院大学（University_of_Chinese_Academy_of_Social_Sciences）_(PR_#14278)
日期：2022年06月15日 17点30分


@zxs5673 You might miss my previous comment. Please react.

&mdash;

**Comment by philipto** [comment]
@zxs5673  Thank you for your patience while waiting for a review and processing your request. Pull request merged.

Please notice that the free educational licenses are for students and teachers only. Researchers have to buy regular individual or commercial licenses. Thank you!

**Pull request merged**
