### PR TITLE
Soroti University

### PR DESCRIPTION
**Pull request by Chris-Mwesigwa**
screenshot

### CODE REVIEW

**Comment by philipto** [comment]
@Chris-Mwesigwa file/lib/domains/ug/ac/sun.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Chris-Mwesigwa** [comment]
Am so sorry, had just committed the whole file folder,
missed changing directory to only 'lib/...'
let me re-commit with changes.

Thanks

**Comment by Chris-Mwesigwa** [comment]
PR-16048 **Edited**,`Am hopeful that the file path problem is solved
Thanks

**Comment by philipto** [comment]
@Chris-Mwesigwa file/lib/domains/ug/ac/sun.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Pull request closed without merging**
