### PR TITLE
Universidade Positivo

### PR DESCRIPTION
**Pull request by leosrabello**
https://www.up.edu.br/

### CODE REVIEW

**Comment by philipto** [comment]
@leosrabello lib/domains/br/com/universidadepositivo: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@leosrabello Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.


Besides, please provide us with more info on the email addresses policy. Where the school publishes a policy on whom they give the email addresses in the domain? Do the graduated student retain the email address after graduation? Is it possible to register for a free course, get the email address and do not conduct the course?

**Comment by leosrabello** [comment]
Hello Phillip,

Here's an email the students received a while ago, instructing them to
log-in to Microsoft 365 in order to download the apps, using the college
email.
I'll leave some pictures, along with the links for you guys to check out.
If you follow the first link, on the bottom of the page there's a link to
the second, but I'll send it here too.
After following the instructions, students will find the college email
shown on picture 3.
Let me know if that works for you.

https://www.up.edu.br/detalhe-noticia/?r=microsoft365-gratuito-para-alunos/
(Instruction on how to get Microsoft 365 using the domain provided by them,
shown on picture 2 as well)
https://www.microsoft.com/pt-br/education/products/office?ms.officeurl=getoffice365

Best,

Leonardo Silva

**Comment by philipto** [comment]
@leosrabello Thank you for your message! Would you please upload the pictures with your browser at the page https://github.com/JetBrains/swot/pull/18456? GitHub strips our all attachments if you send them by e mail.

Also, could you please clarify whether students use the email addresses **aluno.up.edu.br**? It was added two years ago: https://github.com/JetBrains/swot/pull/12594.

The same question is with regard to **aluno.positivo.edu.br**, added in https://github.com/JetBrains/swot/pull/9027.

Thank you!

**Comment by philipto** [comment]
@leosrabello You might miss my previous comment. Please react.

**Comment by leosrabello** [comment]
Hello Philip,

Sorry for the late reply, we had a holiday in my country, i was off e-mail
for a while.

As to your first question, absolutely, i’ll send the pictures in the
designed page.

As for the second one, i believe that e-mail was used by the college i am
currently in, however, an organization bought my college a couple years
ago, so i believe they have changed the email address to:
“cs.up.edu.br” after that change.

Best,

Leonardo Rabello

**Comment by leosrabello** [comment]
Here are the pictures i sent the other day: 

picture2


picture3

[UPemail.pdf](https://github.com/JetBrains/swot/files/12575636/UPemail.pdf)

**Comment by leosrabello** [comment]
Here are some of the pictures i sent the other day:
picture3
picture2

**Comment by philipto** [comment]
@leosrabello Thank you for the clarification! The attached screenshot does not contain an address in an email domain universidadepositivo.com.br. Your request is asking to add the domain **universidadepositivo.com.br**

Did I miss something?

**Comment by leosrabello** [comment]
Hello Philip,

The e-mails we use are something like this: ***@***.***"
That's the email I'm requesting. Sorry if there's any confusion.

Best,

Leonardo Rabello

**Comment by philipto** [comment]
Dear Leonardo @leosrabello,

Would you please repeat your last comment at the page https://github.com/JetBrains/swot/pull/18456 using your browser? Regrettably, GitHub removes the email addresses when they are sent in an email message body, thus I don't see the pattern you were referring to.

Thank you!

**Comment by philipto** [comment]
@leosrabello Thank you! I added the domain **cs.up.edu.br** to the trusted list and removed **aluno.up.edu.br** from it as no longer used domain. I close the request without merging because the file in the request represents a domain **universidadepositivo.com.br**, which does not relate to any of the above mentioned schools or domains.

**Pull request closed without merging**
