### PR TITLE
obszeester

### PR DESCRIPTION
**Pull request by directie**

### CODE REVIEW

**Comment by philipto** [comment]
@directie Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by directie** [comment]
> @directie Please provide us with:
> 
> * the school official website URL, if different from the domain you are submitting
> * an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
> * an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

official website:https://www.obszeester.nl
IT-related :https://www.obszeester.nl/MBO-scholen-en-Vavo/school-en-locatie-detail/school-voor-ict-en-mediatechnologie
pic

**Comment by Dandelionss** [comment]
@philipto @philipto

**Comment by philipto** [comment]
@directie I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Pull request merged**
