### PR TITLE
Update stoplist.txt

### PR DESCRIPTION
**Pull request by kawa11**
Alumni mailbox
https://ustcnet.ustc.edu.cn/2015/0323/c33597a592101/page.htm

### CODE REVIEW

**Comment by philipto** [comment]
@kawa11 Thank you very much for your valuable contribution! We have to investigate a case with USTC deeper. The changes that you have suggested were partially applied to the stoplist.txt a few minutes ago.

**Comment by kawa11** [comment]
> @kawa11 Thank you very much for your valuable contribution! We have to investigate a case with USTC deeper. The changes that you have suggested were partially applied to the stoplist.txt a few minutes ago.
But I found someone selling this University of Science and Technology of China alumni mailbox in the forum
image

**Comment by philipto** [comment]
@kawa11 Okay, you are correct. If there is an ongoing breach, we take the measures immediately. Thank you. Pull request merged.

**Comment by kawa11** [comment]
> @kawa11 Okay, you are correct. If there is an ongoing breach, we take the measures immediately. Thank you. Pull request merged.

ok

**Pull request closed without merging**
