### PR TITLE
Add Pacific National University

### PR DESCRIPTION
**Pull request by Krakatuna**
pnu.edu.ru

### CODE REVIEW

**Comment by philipto** [comment]
@Krakatuna First stage of verification passed, official domain is [pnu.edu.ru](https://pnu.edu.ru) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Krakatuna Thank you for your request. It requires some additional checks, thus it may take more time to review and make a decision about it. In the meantime you can apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your patience.

**Comment by andrew95qq** [comment]
Hello. When will the Pacific National University be added?

**Comment by philipto** [comment]
@Krakatuna 
> When will the Pacific National University be added?

It depends on the results of a legal check. It may happen that it's not possible to add the domain at all. Regrettably, I cannot promise an exact time.

As I previously suggested, you can apply right now for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

**Comment by lionsoftware** [comment]
Is there anything I can do to help with this check? Provide some documents

**Comment by philipto** [comment]
@lionsoftware Regrettably, documents will not help. Legal review is still pending. Thank you for your willingness to help!

**Comment by philipto** [comment]
@Krakatuna There are export control restrictions that make it impossible for us to add this domain to the trusted list and grant educational licenses to all the people possessing an email address in this domain.
JetBrains complies with all relevant regulations, including applicable sanctions and export control laws.
We appreciate your understanding and apologise for any inconvenience caused.

**Pull request closed without merging**
