### PR TITLE
add krugerschool

### PR DESCRIPTION
**Pull request by giojavi04**
Add Kruger School to list

### CODE REVIEW

**Comment by sopcommand** [comment]
Hello, Its levan tsotskolauri from georgia 
i'd like to ask you add my school in list ill write information below to prove that im student and my school is real
thanks you!
tsotskolauri.levani@students.gov.ge
ISANI DISTRICT, PUBLIC SCHOOL #216
https://www.facebook.com/სსიპ-ქთბილისის-N216-საჯარო-სკოლა-473256156339558

**Comment by philipto** [comment]
@sopcommand Please DO NOT comment other folk pull request. Please send an email with your request to community-support@jetbrains.com. Please explain why the students have their email addresses in the Government of Georgia domain.

**Comment by philipto** [comment]
@giojavi04 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by giojavi04** [comment]
@philipto Sure, attach the link, image with hois data and the email.

- https://krugerschool.edu.ec/
- javier@krugerschool.edu.ec
Screen Shot 2021-11-15 at 15 23 28

**Comment by philipto** [comment]
@giojavi04 Thank you for the details. Regrettably, they are insufficient for adding this domain to this repository. The school seems to have another official website by the different domain name. The WHOIS data that you provided are with are correct. However they do not refer to a registrant legitimately representing Kruger School in Ecuador. 

I have to close this request without merging. If you are a student or a teacher in this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
