### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Artur-Czepiel**

### CODE REVIEW

**Comment by philipto** [comment]
@Artur-Czepiel First stage of verification passed, official domain is [umw.edu.pl](https://umw.edu.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Artur-Czepiel Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by Artur-Czepiel** [comment]
Dear Mr. Philip
Our University currently provides many courses that include IT-related
topics in their program.

The medical course contains: Bioinformatics, Statistics, Databases and many
others.
https://rekrutacja.umw.edu.pl/oferta-kierunek-lekarski/

There are also purely technical courses like Medical Analytics which show a
wide range of usage of IT in the healthcare industry.
https://rekrutacja.umw.edu.pl/oferta-kierunek-analityka-medyczna/

There is also a science club at the University that I'm a part of - "AI in
medicine"

All courses are between 3 to 6 years.

If this residual info is not enough for JetBrains team I will of course
provide you with another e-mail.
Thank you for allowing us to work with your software.

Artur Czepiel,
Wroclaw Medical Univeristy


pon., 7 sie 2023 o 16:46 Philip Torchinsky ***@***.***>
napisał(a):

**Comment by philipto** [comment]
@Artur-Czepiel Thank you for the clarifications and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
