### PR TITLE
Added Universidad Ricardo Palma

### PR DESCRIPTION
**Pull request by jeancedron**
Universidad Ricardo Palma changed its domain from @urp.edu.pe to @urp.pe

### CODE REVIEW

**Comment by zweizwei** [comment]
@jeancedron unfortunately the website urp.pe doesn't open. Could you please somehow prove it's alive and belongs to the university?

**Comment by jeancedron** [comment]
@zweizwei There's a problem with my University. It used to have @urp.edu.pe as domain in its email, but now it has changed to @urp.pe. You can get into this link: http://www.urp.edu.pe/correolive/index.php?urp=informacion and see that there's a migration of emails. Also, to get into the inbox of @urp.pe, we have to go to https://www.outlook.com/urp.pe. The domain for the website it's still the same www.urp.edu.pe but the domain is not.

**Comment by jeancedron** [comment]
Also, you can see in this image who is the registrator and the administrator of urp.pe domain.

image

Source: www.whois.com

**Comment by zweizwei** [comment]
@jeancedron thank you for the explanation, I'm adding the domain

**Pull request merged**
