### PR TITLE
Jana Adarsha Multiple Campus

### PR DESCRIPTION
**Pull request by Santosh-NPL**
Jana Adarsha Multiple Campus

### CODE REVIEW

**Comment by Santosh-NPL** [comment]
jamc.edu.np Jana Adarsha Multiple Campus

**Comment by philipto** [comment]
@Santosh-NPL First stage of verification passed, official domain is [jamc.edu.np](https://jamc.edu.np) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Santosh-NPL Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by Santosh-NPL** [comment]
https://jamc.edu.np/computer-science

**Comment by philipto** [comment]
@Santosh-NPL Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
