### PR TITLE
Add Turkish Maya Schools

### PR DESCRIPTION
**Pull request by alicanerparmaksiz**
Web Site: https://maya.k12.tr/

### CODE REVIEW

**Comment by philipto** [comment]
@alicanerparmaksiz Please provide us with a proof, which shows that the school recognizes the domain `mayaokullari.k12.tr` that you are submitting as an official email domain for the students.

**Comment by alicanerparmaksiz** [comment]
> @alicanerparmaksiz Please provide us with a proof, which shows that the school recognizes the domain `mayaokullari.k12.tr` that you are submitting as an official email domain for the students.

[](url)

**Comment by alicanerparmaksiz** [comment]
> @alicanerparmaksiz Please provide us with a proof, which shows that the school recognizes the domain `mayaokullari.k12.tr` that you are submitting as an official email domain for the students.

Screen Shot 2021-01-08 at 17 10 43

Hi Philip,
Here is a screenshot of schools' Microsoft Teams.

**Comment by alicanerparmaksiz** [comment]
> @alicanerparmaksiz Please provide us with a proof, which shows that the school recognizes the domain `mayaokullari.k12.tr` that you are submitting as an official email domain for the students.

Screen Shot 2021-01-08 at 18 25 17

Hi Philip,
Here is a screenshot of schools' Microsoft Outlook Mail.

**Comment by philipto** [comment]
@alicanerparmaksiz Thank you for the clarification. Pull request merged.

**Pull request merged**
