### PR TITLE
Added dghe to list

### PR DESCRIPTION
**Pull request by ketanrajpal**

### CODE REVIEW

**Comment by ketanrajpal** [comment]
Added dghe to list

**Comment by ketanrajpal** [comment]
Added dghe to list

**Comment by philipto** [comment]
@ketanrajpal Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@ketanrajpal You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@ketanrajpal I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
