### PR TITLE
Added STT Diakonos Banyumas

### PR DESCRIPTION
**Pull request by sttdiakonos**

### CODE REVIEW

**Comment by philipto** [comment]
@sttdiakonos First stage of verification passed, official domain is [sttdiakonos.ac.id](https://sttdiakonos.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by sttdiakonos** [comment]
Thank You for the first verification. Hope it will merged soon ;)

**Comment by philipto** [comment]
@sttdiakonos Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by sttdiakonos** [comment]
Thank you @philipto and all of JetBrains teams. 🙇‍♂️

**Pull request merged**
