### PR TITLE
I added my ecole to list of JetBrains

### PR DESCRIPTION
**Pull request by lagerdoo**

### CODE REVIEW

**Comment by lagerdoo** [comment]
I added my Ecole to the list of JetBrains

**Comment by philipto** [comment]
@lagerdoo Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by lagerdoo** [comment]
Hello .
Thank you for your response.

	- IRIS (https://ecoleiris.fr/ <https://ecoleiris.fr/> ) (https://ecoleiris.fr/paris <https://ecoleiris.fr/paris> )
	- Address (6-8 Imp. des 2 Cousins, 75017 Paris, France)
	-  (https://ecoleiris.fr/paris <https://ecoleiris.fr/paris> -  https://ecoleiris.fr/paris/formation/sup-4/manager-de-projets-informatiques-4eme-annee <https://ecoleiris.fr/paris/formation/sup-4/manager-de-projets-informatiques-4eme-annee> - ) 
	- A proof ==> 
		
	
Mohsen KARIMI
***@***.***

**Comment by philipto** [comment]
@lagerdoo Thank you for the clarifications! Regrettably, a proof was not attached to your comment because GitHub strips out all attachments send by email. **Please up;load the proof directly from your browser as a comment to this request**. Thank you!

**Comment by lagerdoo** [comment]
Hello. I received your e-mail. I will send it at the best time.
Best regards.


Mohsen KARIMI
***@***.***

**Comment by philipto** [comment]
@lagerdoo Do you have any update on the matter?

**Comment by lagerdoo** [comment]
Hello, I don't think. This is the last update, I just have this university E-mail and I receive my mail from the university by this. could you help me because I need this IDE for my university project. 
Best regards.
Mohsen KARIMI
***@***.***

**Comment by philipto** [comment]
@lagerdoo Thank you for the clarification. The pull request merged. I will monitor the situation and get back to you if any further questions arise. Thank you.

**Pull request merged**
