### PR TITLE
Add Universidad Santo Tomás (USTA)

### PR DESCRIPTION
**Pull request by danielrinconr**

### CODE REVIEW

**Comment by philipto** [comment]
@danielrinconr Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@danielrinconr You might miss my previous comment. Please react.

**Comment by danielrinconr** [comment]
@philipto Thanks for your reply.
- official website URL:
https://www.usta.edu.co/
- IT-related carrers offered: 
1) https://facultadingenieriaelectronica.usta.edu.co/index.php/nuestros-programas/pregrado-en-ingenieria-electronica
2) https://facultadingenieriatelecomunicaciones.usta.edu.co/index.php/nuestros-programas/pregrado-en-ingenieria-telecomunicaciones
3) https://facultadingenieriaelectronica.usta.edu.co/index.php/nuestros-programas/maestria-en-ingenieria-electronica

**Comment by philipto** [comment]
@danielrinconr Thank you very much for the clarification. Pull request merged.

**Pull request merged**
