### PR TITLE
Create Univer.txt

### PR DESCRIPTION
**Pull request by acoterb**
@alumnos.univer-gdl.mx

### CODE REVIEW

**Comment by philipto** [comment]
@acoterb Please clarify which email domain would you like to add to this repository. If it is univer.mx, your request is correct. If it is alumnos.univer-gdl.mx, the file path has to be lib/domains/mx/univer-gdl/alumnos.txt. In any case, please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by acoterb** [comment]
Hello , sorry
i sent the file wrong,
The correct is :
alumnos.univer-gdl.edu.mx

Can you help me how the file would be and the page is:
https://licenciatura.univer.email/

**Comment by philipto** [comment]
@acoterb I am sorry, the website of https://licenciatura.univer.email looks very different from most of universities' websites. Could you please tell us what is the university official title, postal address, and provide us with some proof that the university is known to Mexican Ministry of Public Education?

**Comment by acoterb** [comment]
sorry but I don't know how to get that information, I hope with this other link it may be enough

This link is for career information
https://mextudia.com/universidades/univer/

and this one is from the official government

https://sgg.jalisco.gob.mx/content/universidad-univer

**Comment by philipto** [comment]
@acoterb Thank you for the clarification. I add alumnos.univer-gdl.edu.mx domain to this repository. Please notice that free educational subscription is strictly for students and teachers only, and for educational purpose only. As for this request, I have to close it without merging because it does not have a correct filename for the domain alumnos.univer-gdl.edu.mx. Thank you for the understanding.

**Pull request closed without merging**
