### PR TITLE
Apply to add duc.ac.cn to Chengdu University of the Arts

### PR DESCRIPTION
**Pull request by stu9527**
Domain name: duc.ac.cn
School: Chengdu Vocational University of the Arts
Purpose: Add a new domain name so that teachers and students of our school can use the education email to verify their qualifications.

### CODE REVIEW

**Comment by stu9527** [comment]
Supplement:
School address: No. 115, Baiyun Road, Huayuan Street, Xinjin District, Chengdu, Sichuan Province, China
Supplement:
Documents on the approval of the Education Bureau to change the domain name of our school

**Comment by stu9527** [comment]
image

**Comment by stu9527** [comment]
Supplement:
Documents on changing the domain name within the school
image

**Comment by stu9527** [comment]
Supplement:
Our school postal code is 611433

**Comment by stu9527** [comment]
Also, due to technical reasons, the old official website is inaccessible and the new official website is still under construction, so it may not be possible to find the URL proving the ownership of the school website. However, I have submitted documents from the government approving the change of our school's domain name, and I hope my application can be approved.

**Comment by stu9527** [comment]
Supplement:
Certification of Chinese Top Level Domain Name
image

**Comment by stu9527** [comment]
@philipto Hey bro, how about my requests

**Comment by philipto** [comment]
@stu9527 Regrettably, this request has signs of fraud. I have to close it without merging.

It does not mean that something is wrong with the school. The issue is related to a combination of suspicious factors related to the domain itself.

Please enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).
Thank you for your understanding!

**Pull request closed without merging**
