### PR TITLE
Add student.inda.be domain

### PR DESCRIPTION
**Pull request by Sellig6792**
**The website url:** https://inda.be
**A proof that student.inda.be is the domain name for student emails:** https://inda.be/actu/adresse-mail-eleve#:~:text=Tous%20nos%20%C3%A9tudiants%20recevront%20une,est%20joint%20%C3%A0%20ce%20courrier.
_(the site is in french)_

### CODE REVIEW

**Comment by philipto** [comment]
@Sellig6792 First stage of verification passed, official domain is [inda.be](https://inda.be) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Sellig6792** [comment]
Thanks for the information. Take the time you need, there is no problem.

**Comment by philipto** [comment]
@Sellig6792 Pull request merged. Thank you!

**Comment by Sellig6792** [comment]
Thanks you very much! Can i delete my repository forked from this one? @philipto

**Comment by Sellig6792** [comment]
Sorry @philipto can I delete the repository forked from this one?

**Pull request merged**
