### PR TITLE
Create psych.txt

### PR DESCRIPTION
**Pull request by gpVRLABippas**
adding Institute of Psychology, Polish Academy of Sciences to the list of edu institutions; 
Here is our website: https://psych.pan.pl/en/; here are the pages of the phd program in psychology, in which we have classes on psychophysiological data analysis with varous tools , including python, possibly using pycharm and github: https://psych.pan.pl/doktorat/szkola-doktorska/

### CODE REVIEW

**Comment by philipto** [comment]
@gpVRLABippas First stage of verification passed, official domain for **Instytut Psychologii Polskiej Akademii Nauk** is [psych.pan.pl](https://psych.pan.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@gpVRLABippas Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by gpVRLABippas** [comment]
Dear Philip,
here is the subpage of out phd school, in polish system all phd schools
take 4 years, they include various courses
https://psych.pan.pl/doktorat/szkola-doktorska/
you have some basic information in english there. Let me guide you further:
If you jump down to point III. you will have descriptions of sample
courses. Among them you'll find Advanced statistical analysis
and Programming PsychoPy Experiments with Python which are to my knowledge
the courses that use and teach python. Probably also neurophysiology will
use it, as they analyse EEG signal , but it is just a sample list of core
courses, as they are rather flexible and tailored to the needs of certain
phd projects.
Hope it helps.

best regards,
gp

dr Grzegorz Pochwatko
Zastępca Dyrektora ds. Ogólnych
Instytut Psychologii Polskiej Akademii Nauk
-----------------------------------
Deputy Director for General Affairs
Institute of Psychology Polish Academy of Sciences

+48 22 853 13 86
+48 22 853 13 93
***@***.***

Laboratorium Rzeczywistości Wirtualnej i Psychofizjologii
Instytut Psychologii
Polska Akademia Nauk
------------------------
Virtual Reality and Psychophysiology Lab
Institute of Psychology
Polish Academy of Sciences

***@***.***

**Comment by philipto** [comment]
@gpVRLABippas  Thank you very much for the clarifications and your patience. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by gpVRLABippas** [comment]
Will do, thank you!
dr Grzegorz Pochwatko
Zastępca Dyrektora Instytutu Psychologii PAN

Laboratorium Rzeczywistości Wirtualnej I Psychofizjologii

---‐--------------------‐-------------------------
Deputy Director of the Institute of Psychology PAS

Virtual Reality and Psychophysiology Lab

śr., 2 paź 2024, 17:31 użytkownik Philip Torchinsky <
***@***.***> napisał:

**Pull request merged**
