### PR TITLE
Create taalim.txt

### PR DESCRIPTION
**Pull request by riadloukili**

### CODE REVIEW

**Comment by philipto** [comment]
@riadloukili I am sorry, but the domain does not redirect to an official website, and the institution title suggests that it is a ministry, not a university. This repository is for universities and colleges only. Please let us know why did you decide that this domain should be added to the repository. Thank you!

**Comment by riadloukili** [comment]
@philipto, the @taalim.ma is actually provided by the ministry to all students in Morocco once they're in high school, this is why it seemed to me to be correct to add it to this repo so that @taalim.ma emails will be eligible for "Student discount".
Thanks.

**Comment by philipto** [comment]
@riadloukili We usually do not grant licenses in bulk to such broad audience at once; this repository is for universities and colleges email domains only. Are there any email domains in Morocco, which belong to particular high schools? Anyway, it will take more time than usual to decide on this case. I apologize for the inconvenience that it can cause. Thank you for your understanding!

**Comment by riadloukili** [comment]
Unfortunately, there's only that email for high school students, anyway, thanks for your time. Cheers 😅

**Comment by philipto** [comment]
@riadloukili We are working on resolving the request. It may take some more time, because it is the first time when a domain to be added has such a broad coverage. Thank you for your patience.

**Comment by riadloukili** [comment]
@philipto okay, thanks for your time 😅

**Comment by philipto** [comment]
@riadloukili We emailed Mohamed Loudifa who is responsible for taalim.ma domain, according WHOIS records. Regrettably, he did not respond. Could you please check if he is available for requests and comments? You can find his details at http://www.yatedo.fr/p/mohamed+loudifa/normal/a10468510d034c62942d71e4cd28299b, for example.

We need to contact someone from Morocco Ministry of Education to get more details about taalim.ma domain usage from official point of view. Unfortunately, we'll not be able to add this domain to the repository without discussing it with the officials, because the domain is officially registered as the Ministry of Education domain.

**Comment by riadloukili** [comment]
Sorry but unfortunately, I cannot help with that, so if you do think that the domain taalim.ma<http://taalim.ma> is not eligible, then feel free to ignore this pull request.

Kind regards 😅
- R

On Feb 13, 2017, at 11:17 AM, Philip Torchinsky <notifications@github.com<mailto:notifications@github.com>> wrote:


@riadloukili<https://github.com/riadloukili> We emailed Mohamed Loudifa who is responsible for taalim.ma<http://taalim.ma> domain, according WHOIS records. Regrettably, he did not respond. Could you please check if he is available for requests and comments? You can find his details at http://www.yatedo.fr/p/mohamed+loudifa/normal/a10468510d034c62942d71e4cd28299b, for example.

We need to contact someone from Morocco Ministry of Education to get more details about taalim.ma<http://taalim.ma> domain usage from official point of view. Unfortunately, we'll not be able to add this domain to the repository without discussing it with the officials, because the domain is officially registered as the Ministry of Education domain.

**Comment by philipto** [comment]
@riadloukili You are right. Regrettably, we cannot satisfy this request at the moment because the domain is really not eligible for adding to this repository because the repository is for colleges' and universities' domains only. Shall the circumstances change, or we hear back from the Ministry of Education, we are glad to consider theis case again. Thank you for the understanding!

**Comment by philipto** [comment]
@riadloukili Using taalim.ma became a recognized practice in Morocco in recent years. While in most countries schools' students do not have similar country-wide email system, it seems to be valid and stable in Morocco. Therefore, I reopened this request and merged it. The domain is now eligible for free licenses. It may happen that it will be misused, and if it happens, the merge will be reverted. 

Thank you for your commitment, foreseeing, and patience!

**Pull request merged**
