### PR TITLE
Add JCPSNJ

### PR DESCRIPTION
**Pull request by TheKingOfBel**
Add the Jersey City Public Schools to this.

### CODE REVIEW

**Comment by philipto** [comment]
@TheKingOfBel First stage of verification passed, official domain is [mcnairacademic.com](https://mcnairacademic.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.mcnairacademic.com/anime

**Comment by philipto** [comment]
@TheKingOfBel Please provide us with:
* the school official website URL
* the school street address, including city and country

**Comment by TheKingOfBel** [comment]
School Address: 123 Coles Street, Jersey City, NJ 07302, USA
School Website: https://mhs.jcboe.org/

**Comment by philipto** [comment]
@TheKingOfBel  Thank you for the clarifications and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
