### PR TITLE
Add Prince Alfred College

### PR DESCRIPTION
**Pull request by jackm9367**
pac.edu.au

### CODE REVIEW

**Comment by Kmlyhn42** [comment]
[file.zip](https://github.com/JetBrains/swot/files/7038701/file.zip)
Please add my University

**Comment by jackm9367** [comment]
Hi there,

Unfortunately, I am not affiliated with JetBrains so will be unable to help with this PR. I simply created a PR in order to add a school domain to the JetBrains educational database.

Kind Regards,
Jack Miller

**Comment by philipto** [comment]
@jackm9367 Pull request merged. Thank you!
@Kmlyhn42 I added your university to the repository as an exception. The routine procedure of adding the domain to the repository is to ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with correct information. 

Please start requesting your licenses in about an hour to let the changes to propagate through our systems.
Thank you.

**Comment by jackm9367** [comment]
Awesome - thanks so much!

**Pull request merged**
