### PR TITLE
Create 365.txt

### PR DESCRIPTION
**Pull request by zhengyichuan**
ADD ntsu 365

### CODE REVIEW

**Comment by philipto** [comment]
@zhengyichuan Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@zhengyichuan You might miss my previous comment. Please react.

**Comment by zhengyichuan** [comment]
> @zhengyichuan Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

https://eeclass.ntsu.edu.tw/course/2921/intro

**Comment by zhengyichuan** [comment]
You might miss my previous comment. Please react.

http://192.83.181.141/ntsu/outside.aspx?mainPage=QQBwAHAAbABpAGMAYQB0AGkAbwBuAC8AVABLAEUALwBQAFIARwAvAFAAUgBHADEAMQAwADAAXwAuAGEAcwBwAHgAPwBwAHIAbwBnAGMAZAA9AFAAUgBHADEAMQAwADAA

image
image

**Comment by philipto** [comment]
@zhengyichuan v

**Pull request merged**
