### PR TITLE
Add schoolmail domain

### PR DESCRIPTION
**Pull request by Vector1dev**

### CODE REVIEW

**Comment by Ethea2** [comment]
Please add my school, thank you 
Middle East College
[mec.txt](https://github.com/JetBrains/swot/files/6603048/mec.txt)

**Comment by Ethea2** [comment]
Middle East College
[mec.txt](https://github.com/JetBrains/swot/files/6603067/mec.txt)

**Comment by philipto** [comment]
@Vector1dev This domain does not belong to a university, nor to a college. I have to close the request without merging. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting a new request. 

@Ethea2 Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new **separate** request with correct information. Thank you for the understanding!

**Comment by Vector1dev** [comment]
@philipto It domain of russia schools.

**Pull request closed without merging**
