### PR TITLE
Added "Collège des Mûriers"

### PR DESCRIPTION
**Pull request by Pixfri**

### CODE REVIEW

**Comment by philipto** [comment]
@Pixfri First stage of verification passed, official domain is [clg-lesmuriers.sarthe.e-lyco.fr](https://clg-lesmuriers.sarthe.e-lyco.fr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://clg-lesmuriers.sarthe.e-lyco.fr/page/6/

**Comment by philipto** [comment]
@Pixfri Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@Pixfri You might miss my previous comment. Please react.

**Comment by Pixfri** [comment]
> @Pixfri Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

Hello, my school's website is indeed this one. I'm sorry I couldn't answer as soon as possible because I was not at home.

**Comment by philipto** [comment]
@Pixfri Thank you for the clarification. Could you please not only confirm that this website belongs to your school, but also the fact that the school offers an IT-related long-term (>1 year) course. If the school does not offer such a course, we for sure will not be able to add the school's domain to this repository.

**Comment by philipto** [comment]
@Pixfri I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
