### PR TITLE
feat: management.edu.mn added

### PR DESCRIPTION
**Pull request by amaraad**
Let's add management.edu.mn from mongolia

### CODE REVIEW

**Comment by philipto** [comment]
@amaraad Please provide us with:
* the school official website URL
* the school official name in Mongolian and in English
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you.

**Comment by philipto** [comment]
@amaraad You might miss my previous comment. Please react.

**Comment by amaraad** [comment]
Hello
Official urls :  http://management.edu.mn/, http://tsetsee-goun.edu.mn/
Name in english: Tsetsee Goun Institute of Management
Name in mongolia: Цэцээ Гүн Дээд Сургууль
Address:  Mongolia Ulaanbaatar Bayanzurh, 13 khoroo Tsetsee Goun institude
Course URL: http://management.edu.mn/page/10/
image
Sorry for no translation . 

a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
> server 8.8.8.8
Default Server:  dns.google
Address:  8.8.8.8

> set type=mx
> management.edu.mn
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
management.edu.mn       MX preference = 10, mail exchanger = mx.management.edu.mn
I have only mx records

> tsetsee-goun.edu.mn
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
tsetsee-goun.edu.mn     MX preference = 0, mail exchanger = tsetseegoun-edu-mn01i.mail.protection.outlook.com

And i don't have any other paper.

**Comment by philipto** [comment]
@amaraad  Thank you for the clarifications. Pull request merged.

**Pull request merged**
