### PR TITLE
Add Colegio de Muntinlupa

### PR DESCRIPTION
**Pull request by imxaander**

### CODE REVIEW

**Comment by philipto** [comment]
@imxaander First stage of verification passed, official domain for **Colegio de Muntinlupa** is [cdm.edu.ph](https://cdm.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by imxaander** [comment]
thank you.

**Comment by philipto** [comment]
@imxaander Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by imxaander** [comment]
thanks.

**Pull request merged**
