### PR TITLE
Create sio-mermoz.txt

### PR DESCRIPTION
**Pull request by Gunnerofdoom**

### CODE REVIEW

**Comment by philipto** [comment]
@Gunnerofdoom Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Gunnerofdoom** [comment]
- http://www.lycee-mermoz.net/joomla/index.php
-
http://www.lycee-mermoz.net/joomla/index.php/orientation/formations/enseignement-superieur/technicien-superieur/44-bts-sio

**Comment by philipto** [comment]
@Gunnerofdoom Regrettably, the domain which you are submitting, is not mentioned at the website of this lycee. Please tell us how we can see that the lycee recognizes this email domain as its official domain for the students.

image

**Comment by Gunnerofdoom** [comment]
the domain is not mentioned in the website of the lycee, because only the
BTS SIO have access to a students mail with the Office 365 platform and an
account on Microsoft Imagine, in the followings screens I give you the "my
account" page of Office 365 and Microsoft Imagine

**Comment by philipto** [comment]
@Gunnerofdoom I am sorry, GitHub does not upload attachments which are sent via email. Please upload the screenshot to your comment on GitHub via web interface at https://github.com/JetBrains/swot/pull/5870

Thank you!

**Comment by Gunnerofdoom** [comment]
My bad :/

capture1
capture2

**Comment by philipto** [comment]
@Gunnerofdoom Thank you for the clarification. Pull request merged.

**Pull request merged**
