### PR TITLE
Adding CETIS 15

### PR DESCRIPTION
**Pull request by jmmc39**
Centro de Estudios Tecnológicos Industrial y de Servicios Número 15 Epignemio Gonzalez

### CODE REVIEW

**Comment by philipto** [comment]
@jmmc39 First stage of verification passed, official domain is [m.facebook.com](https://m.facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/385535688662095/photos/a.385937255288605/669380346944293/?type=3

**Comment by philipto** [comment]
@jmmc39 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by jmmc39** [comment]
Okey, in this message I'm going to send the information that you request me.

1.- http://www.cetis15.edu.mx/
2.- Tulipanes 141, Adolfo Ruiz Cortines, 91829 Veracruz, Ver.
(Country: México)
3.- http://www.cetis15.edu.mx/programacion/
4.- 



WHOIS:

**Comment by philipto** [comment]
@jmmc39 First stage of verification passed, official domain is [m.facebook.com](https://m.facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/385535688662095/photos/a.385937255288605/669380346944293/?type=3

**Comment by philipto** [comment]
@jmmc39 I need your help. As far as I understand, many schools use the same **domain uemstis.sems.gob.mx**. Who  have the email addresses there? Teachers of secondary schools in a particular city? Someone else?

**Comment by jmmc39** [comment]
@philipto 
Best regards.
Regarding his unknown, various high schools adopted this domain since it consists of an organization (from Mexico), to which multiple high schools from various states of the country, are part of that link. Regarding the accessibility of the domain, various users (such as teachers and students) have access.

**Comment by philipto** [comment]
@jmmc39  Thank you for the clarifications. Thus, this domain represents an umbrella institution, not a specific single university or a college. Please apply for free educational license with an official document which proves that you are a student or a teacher. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for the understanding!

**Pull request closed without merging**
