### PR TITLE
Add Lycée Clos-Maire

### PR DESCRIPTION
**Pull request by Zeifras**

### CODE REVIEW

**Comment by philipto** [comment]
@Zeifras Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Zeifras** [comment]
For the website of the school this one is the actual website: https://lyc-closmaire-beaune.eclat-bfc.fr/

For the IT course I redirect you on a website that list pratically each school of France and the IT course is the STI2D (in english: Sciences and Technologies of Industry and Sustainable Developement) http://m.onisep.fr/Ressources/Univers-Lycee/Lycees/Bourgogne-Franche-Comte/Cote-d-Or/Lycee-Clos-Maire

And for the proof that the domain belong to my school, does a photo of the IDs the school gave me works as a proof ?

**Comment by philipto** [comment]
@Zeifras Thank you for the details!

> does a photo of the IDs the school gave me works as a proof ?

Yes, if the ID has your email address, and the address has a pattern of username@lyceeclosmaire.onmicrosoft.com. We have to be sure that this email domain officially belongs to your school.

**Comment by Zeifras** [comment]
@philipto here is the picture i just masked my name and my login since this is a public discussion if you want the full picture contact me by email

http://prntscr.com/rdvqy0

**Comment by philipto** [comment]
@Zeifras Thank you for the clarification. Pull request merged.

**Pull request merged**
