### PR TITLE
Add Magdalen College School

### PR DESCRIPTION
**Pull request by GTBebbo**
I currently attend Magdalen College School in Oxford. Please, can this be added so I can get a student licence for the programs. (They now offer Computer Science GCSE)

### CODE REVIEW

**Comment by GTBebbo** [comment]
school's url is http://mcsoxford.org

**Comment by philipto** [comment]
@GTBebbo Please rename lib/domains/org/mcsoxford to lib/domains/org/mcsoxford.txt

**Comment by GTBebbo** [comment]
Renamed :D

**Comment by philipto** [comment]
@GTBebbo Pull request merged. Thank you!

**Pull request merged**
