### PR TITLE
Add STMIK Jabar College Indonesia

### PR DESCRIPTION
**Pull request by mgsolid1234**
STMIK Jabar is one college located in Bandung, West Java, Indonesia focusing on IT Major.
website : 
http://stmikjabar.ac.id/ or
https://www.stmik-jabar.ac.id/

### CODE REVIEW

**Comment by philipto** [comment]
@mgsolid1234 The official university website is stmik-jabar.ac.id. 
Please provide us with a proof, which shows that the school recognizes the domain stmikjabar.ac.id you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@mgsolid1234 You might miss my previous comment. Please react.

**Comment by mgsolid1234** [comment]
Dear Mr. @philipto,

Sorry for my late respon,

Due to the proof, these are Cpanel Screen Capture for the domains:
sshot_stmikjabar_acid
sshots_stmik-jabar_acid

Waiting for your consideration later.

Thank You.

**Comment by philipto** [comment]
@mgsolid1234 I am sorry, the provided materials are not the proof which I would expect. Your ability to access a web panel of a website does not prove that the university assigns email addresses in the domain stmikjabar.ac.id to the students. Could you please find another proof? The official letter from the university administration to the students would be good.

Regrettably, WHOIS and MX records for the two domains are also quite different and cannot be used as such a proof.

If you don't have better proof, I would recommend you to apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
@mgsolid1234 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Comment by mgsolid1234** [comment]
Dear @philipto,

I still need time for preparing required proof documents from the College. 
Is it ok to close for a while. I will update, after the documents are available.

Thank you.

**Pull request closed without merging**
