### PR TITLE
Create simat.txt

### PR DESCRIPTION
**Pull request by Rana-Saud**

### CODE REVIEW

**Comment by Rana-Saud** [comment]
@philipto review and please merge branch

**Comment by philipto** [comment]
@Rana-Saud First stage of verification passed, official domain for **Sindh Institute of Management & Technology (SIMT)** is [simat.edu.pk](https://simat.edu.pk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Rana-Saud Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by Rana-Saud** [comment]
@philipto thanks a lot

**Comment by Rana-Saud** [comment]
@philipto  please tell me what is the next step?

**Pull request merged**
