### PR TITLE
City and Guilds Art School

### PR DESCRIPTION
**Pull request by sebing**

### CODE REVIEW

**Comment by philipto** [comment]
@sebing First stage of verification passed, official domain is [cityandguildsartschool.ac.uk](https://cityandguildsartschool.ac.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.cityandguildsartschool.ac.uk/art-material-histories-ma-student-reflects-on-how-survivors-of-domestic-abuse-can-benefit-from-working-with-glass/

**Comment by tenthreee** [comment]
Hello @sebing, Please provide us with the URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@sebing You might miss my previous comment. Please react.

**Comment by sebing** [comment]
@philipto and @tenthreee  
City and Guilds Art School doesn't offer any long-term IT courses. I thought that was not a constraint.

**Comment by philipto** [comment]
@sebing Regrettably, it is a constraint. Please read the repository rules at https://github.com/JetBrains/swot#which-educational-institutions-can-be-added-to-the-repository

I am sorry, this domain seems to represent an institution, that is not eligible for adding to this repository. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
