### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by PopovDev**
Please add school.
Site:http://gymnasium47.edu.kh.ua/
Domain Mail: admin@hg47.org

### CODE REVIEW

**Comment by philipto** [comment]
@PopovDev Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@PopovDev You might miss my previous comment. Please react.

**Comment by PopovDev** [comment]
> Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

I'm sorry for the delay. At the moment, since the hg47.org domain was registered by informatics teachers, and gymnasium47.edu.kh.ua was created by the organization a long time ago, from the proofs I can suggest that there are constant references to our gymnasium in the google classroom, the name of the organization registered through the google suite for education coincides with the name of the school, as well as constant school activity goes to the Google classroom



image
image


image
image
image

**Comment by philipto** [comment]
@PopovDev Thank you for the clarification. Pull request merged.

**Pull request merged**
