### PR TITLE
Added TUC Sweden to se

### PR DESCRIPTION
**Pull request by Jesperson**

### CODE REVIEW

**Comment by philipto** [comment]
@Jesperson Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by Jesperson** [comment]
> 
> 
> @Jesperson Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

https://www.tucsweden.se/utbildning/yh-utbildningar/systemutvecklare-net-distans/
This is my current education. There are more available.

**Comment by philipto** [comment]
@Jesperson I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Comment by Jesperson** [comment]
> 
> 
> @Jesperson I am sorry for a delay with processing your request.
> Pull request merged. Thank you!

No problem, I'm happy it got merged!
Looking forward to using Rider!

**Pull request merged**
