### PR TITLE
Mascalls academy

### PR DESCRIPTION
**Pull request by AbbieHenson**
Add mascalls academy

### CODE REVIEW

**Comment by philipto** [comment]
@AbbieHenson Please provide us with an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by AbbieHenson** [comment]
> @AbbieHenson Please provide us with an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.

proof
This picture shows a screenshot of my email screen. The top right hand corner shows its part of the Leigh academy trust which mascalls is a part of as shown on the website below in the left hand corner of the home page.
http://mascallsacademy.org.uk/

**Comment by philipto** [comment]
@AbbieHenson Pull request merged. Thank you for the clarification!

**Comment by AbbieHenson** [comment]
@philipto Thank you! How long will it take for me to be able to login with the email?

**Comment by philipto** [comment]
@AbbieHenson It usually takes about an hour to propagate changes through the system, thus you can try now. Thank you!

**Pull request merged**
