### PR TITLE
ADD nkud file

### PR DESCRIPTION
**Pull request by wuda1989**
university website: https://www.nkut.edu.tw/

technical course website: https://nkei.nkut.edu.tw/front/Department_Intr/Electrical_and_/pages.php?ID=bmt1dF9laSZFbGVjdHJpY2FsX2FuZF8=

Taiwan Government Ministry of Education：
https://ulist.moe.gov.tw/Browse/UniversityDetail?UniversityKey=00001C80B9E6

Email:wuda1989@nkut.edu.tw
phone:049-2563489*1206
fax:049-2563788
address:54243南投縣草屯鎮中正路568號

### CODE REVIEW

**Comment by philipto** [comment]
@wuda1989 First stage of verification passed, official domain is [nkut.edu.tw](https://nkut.edu.tw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by wuda1989** [comment]
thanks

**Comment by philipto** [comment]
@wuda1989 I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by wuda1989** [comment]
please request https://www.nkut.edu.tw <= **This domain is nkut.edu.tw**

don't request https://webmail.nkut.edu.tw/cgi-bin/login?index=1

**Comment by wuda1989** [comment]
> @wuda1989 I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

please tell me
"connection timed out; no servers could be reached" is it Because of "nkut.edu.tw" this domain request time out?

**Pull request closed without merging**
