### PR TITLE
Create berufsschulebt1

### PR DESCRIPTION
**Pull request by markusscherg**

### CODE REVIEW

**Comment by philipto** [comment]
@markusscherg lib/domains/com/onmicrosoft/berufsschulebt1: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@markusscherg Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by markusscherg** [comment]
Hello.

Maybe this is sufficient:

https://www.bs1-bt.de/service-download/support-microsoft-365-teams

on this page you can request a new password for the mantioned onmicrosoft-address. Therefore you may not enter this email in the field. You can see the domain in the placeholder.

If you try to login to the microsoft-account you can see the schools logo applied to the background:

image

Thank you so far, plz let me know if you need further information.

**Comment by philipto** [comment]
@markusscherg  Thank you for the clarifications. Pull request merged.

**Pull request merged**
