### PR TITLE
Add MCCCD to the college list

### PR DESCRIPTION
**Pull request by saites**
The Maricopa County Community College District (https://www.maricopa.edu/) is one of the largest community college district in the United States, serving more than 128,000 students each year in Maricopa County, Arizona.

### CODE REVIEW

**Comment by philipto** [comment]
@saites This domain is not to be accepted, I am sorry. Please see #1673 for more details. Thank you for your understanding.

**Comment by saites** [comment]
Wow. I don't blame you, but that sucks. Another thing to be "proud" of Phoenix/Arizona for.

Can I recommend adding the domain to your blacklist?

**Comment by philipto** [comment]
@saites Thank you for sharing my feeling. To be honest, the domain is already in the blacklist.

**Comment by saites** [comment]
Huh, I don't know how I missed that.

**Pull request closed without merging**
