### PR TITLE
Add Locust Valley High School/Middle School

### PR DESCRIPTION
**Pull request by KingTryHard1**

### CODE REVIEW

**Comment by philipto** [comment]
@KingTryHard1 First stage of verification passed, official domain is [locustvalleyschools.org](https://locustvalleyschools.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by KingTryHard1** [comment]
Domain was actually changed from lvcsd.k12.ny.us to locustvalleyschools.org

**Comment by KingTryHard1** [comment]
Added new pull request to delete lvcsd.k12.ny.us domain

**Comment by philipto** [comment]
@KingTryHard1 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
