### PR TITLE
Added glbimr

### PR DESCRIPTION
**Pull request by 29karan**
Added university named Chaudhary Charan singh

### CODE REVIEW

**Comment by philipto** [comment]
@29karan Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@29karan You might miss my previous comment. Please react.

**Comment by 29karan** [comment]
> @29karan Please provide us with:
> 
>     * the school official website URL
> 
>     * the school street address, including city and country
> 
>     * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> 
>     * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Sir this is the address Plot No. 2, Knowledge Park III, G. Noida Distt. Gautam Budh Nagar, U.P., India - 201306, 

https://www.glbimr.org/

and the above mentioned address is website of the university

**Comment by 29karan** [comment]
https://aktu.ac.in/nba%20programm.html#

This is the site of the university where my college is also mentioned

**Comment by philipto** [comment]
@29karan I am sorry, glbimr.org is not mentioned anywhere at the official website of Chaudhary Charan Singh University. I cannot independently verify the information that you provided in this request. I have to close the request without merging. Please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
