### PR TITLE
Add Impacta

### PR DESCRIPTION
**Pull request by williamfn**
The university site is different from the student's email domain. The university site is: http://www.impacta.edu.br

Here's an IT-related long-term course offered by the university (B.S. in Information Systems): http://www.impacta.edu.br/#!/cursos/sistemas-de-informacao/77

### CODE REVIEW

**Comment by philipto** [comment]
@williamfn Could you please give us a link to a page or an official document saying that alunoimpacta.com.br domains belongs to students at FIT? It is also important to ensure that only students studying in classrooms have emails in this domain, and the college does not give the email to people studying with distance learning only and short-term courses.

**Comment by williamfn** [comment]
The university don't have distance learning courses, ony presential courses. You can check it on the courses pages:
- http://www.impacta.edu.br/#!/cursos/graduacao - (B.S. level)
- http://www.impacta.edu.br/#!/cursos/pos - (graduate level)
- http://www.impacta.edu.br/#!/cursos/tecnicos (certificate programs level)

All they are long-term courses (minimum duration 18 months).

About the domain belonging to the university, whois's screenshots showing the same owner for both domains prove it? You can check it at the brazilian register provider: https://registro.br/cgi-bin/whois/

impacta edu br-whois
alunoimpacta com br-whois

**Comment by philipto** [comment]
@williamfn Thank you for the details! Pull request merged.

**Comment by williamfn** [comment]
Thank you!
Just one question: when the register with the university e-mail will be available for us?

**Comment by philipto** [comment]
@williamfn Usually updates are available in about a half an hour. If it still does not work, please let us know.

**Comment by williamfn** [comment]
@philipto It still says my email dont belong to a known university domain. Can you check it or I need to reach the support for formal support? :)

**Comment by philipto** [comment]
We'll investigate this in few hours. I am sorry for the inconvenience.

**Comment by philipto** [comment]
Could you please send an email to support-int@jetbrains.com, and write there which email address you use to request a license? Thank you!

**Comment by williamfn** [comment]
Sure I will send now. Thanks for the help.

**Pull request merged**
