### PR TITLE
Create wsm

### PR DESCRIPTION
**Pull request by Luczek5**
Warsaw Management University

### CODE REVIEW

**Comment by philipto** [comment]
@Luczek5 Please rename lib/domains/pl/wsm to lib/domains/pl/wsm.txt

**Comment by Luczek5** [comment]
What now?

**Comment by philipto** [comment]
@Luczek5 I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Comment by Luczek5** [comment]
I can't still download intellij fro students and teachers ???

**Pull request merged**
