### PR TITLE
Added GUSTO University

### PR DESCRIPTION
**Pull request by Infer2**

### CODE REVIEW

**Comment by philipto** [comment]
@Infer2 The first verification stage is complete: the official domain for  **GUSTO University** is [gusto.edu.mm](https://gusto.edu.mm), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.gusto.edu.mm/students-experiences/

**Comment by Infer2** [comment]
Thanks I appreciate it ^^

**Comment by philipto** [comment]
@Infer2 The first verification stage is complete: the official domain for  **GUSTO University** is [gusto.edu.mm](https://gusto.edu.mm), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://gusto.edu.mm/

**Comment by philipto** [comment]
@Infer2 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
