### PR TITLE
Create Lexington Christian Academy domain

### PR DESCRIPTION
**Pull request by ScienceMind11**

### CODE REVIEW

**Comment by philipto** [comment]
@ScienceMind11 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by ScienceMind11** [comment]
[School URL](lexingtonchristian.org)

450 W. Reynolds Road
Lexington, KY 40503

[High School Course Guide (STEM pathway shown on page 6)](https://www.lexingtonchristian.org/editoruploads/files/Academics/High%20School%20NEW/2023-2024%20High%20School%20Course%20Guide(1).pdf)

I'm happy to provide number four, I just don't quite understand what sort of proof you want.

**Comment by philipto** [comment]
@ScienceMind11 Please provide us with any of the following as the proof confirming that **365.lexca.org** belongs to the school:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

Thank you for your cooperation!

**Comment by ScienceMind11** [comment]
Screenshot 2024-11-06 at 08 58 43

This is a screenshot of an email sent to me by the LCA administration regarding email addresses and their formats (black boxes represent personal information that I'd rather not share openly). If this isn't enough, please let me know and I'll see what more proof I can find.

**Comment by philipto** [comment]
@ScienceMind11 Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
