### PR TITLE
added folder structure for  camosun college d2l emails eg. student@onlin...

### PR DESCRIPTION
**Pull request by sheaphillips**
Adding files for the domain structure used for (some?) Camosun College student email accounts.

### CODE REVIEW

**Comment by sheaphillips** [comment]
added file online.txt to ca/camosun and removed incorrect file and folder.

**Comment by sheaphillips** [comment]
hi @Smove - does this look better?

**Comment by Smove** [comment]
Looks good @sheaphillips

**Comment by zweizwei** [comment]
I'm sorry for the delay - adding the domain.

**Pull request merged**
