### PR TITLE
+ EAFC UCCLE

### PR DESCRIPTION
**Pull request by shercase**

### CODE REVIEW

**Comment by philipto** [comment]
@shercase file/lib/domains/be/iepscf-uccle/student.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@shercase Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@shercase You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@shercase I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by shercase** [comment]
Hello,

I apologize for bothering you.

I requested the IT department of the school to change my email address from ***@***.*** to ***@***.***, which is the new school email address. However, I am not receiving the email from your company to set up the educational version. Could you please get back to me regarding this?

Thank you in advance.

Sherley

________________________________
De : Philip Torchinsky ***@***.***>
Envoyé : mercredi 14 juin 2023 05:35
À : JetBrains/swot ***@***.***>
Cc : casera sherley ***@***.***>; Mention ***@***.***>
Objet : Re: [JetBrains/swot] + EAFC UCCLE (PR #17717)


@shercase<https://github.com/shercase> I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by froland** [comment]
Hello @shercase,

When I added the iepscf-uccle.be domain, the student subdomain has been added too.
Your issue should thus be fixed.

See you in the classroom.

**Pull request closed without merging**
