### PR TITLE
added my schools domains

### PR DESCRIPTION
**Pull request by GabXool**
added domain for my schools email addresses like <lastname>.<firstname>@student.gymkatzelsdorf.net

### CODE REVIEW

**Comment by AlessioAttilio** [comment]
[file .zip](https://github.com/JetBrains/swot/files/7789904/file.zip)

**Comment by mustaqeem302** [comment]
added domain for my schools email addresses like MUHAMMAD.3877481@talmeez.pk

**Comment by mustaqeem302** [comment]
[swot-master.zip](https://github.com/JetBrains/swot/files/7790097/swot-master.zip)

**Comment by philipto** [comment]
@GabXool Thank you for your patience while waiting for a review and processing your request.
Pull request merged. Thank you!

@AlessioAttilio Please create a separate pull request or send an email to community-support@jetbrains.com. If you send the email please mention the URL of this request in your message. Thank you.

**Comment by mustaqeem302** [comment]
[swot-master.zip](https://github.com/JetBrains/swot/files/7809227/swot-master.zip)

**Pull request merged**
