### PR TITLE
add INRIA to educational list

### PR DESCRIPTION
**Pull request by fernandoFernandeSantos**
Add the Institut national de recherche en informatique et en automatique (Inria) inria.fr domain

### CODE REVIEW

**Comment by philipto** [comment]
@fernandoFernandeSantos First stage of verification passed, official domain is [inria.fr](https://inria.fr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@fernandoFernandeSantos Thank you for your patience. Regrettably, I have to close this request for the reason mentioned in ##17440.

**Comment by fernandoFernandeSantos** [comment]
Thanks for your response, @philipto. However, I wonder why INRIA couldn't be included in the list of allowed domains. While INRIA is indeed a research institution, it is always affiliated with universities such as the University of Paris, the University of Rennes (where I am currently employed), and the University of Bordeaux, among others. We engage with a diverse range of students, from undergraduates to PhD candidates. This case is similar to IRISA, already listed as an allowed domain (https://github.com/JetBrains/swot/blob/master/lib/domains/fr/irisa.txt).

**Comment by philipto** [comment]
@fernandoFernandeSantos Thank you for your comment. This issue is raised again in #18916. My understanding is that all students and teachers affiliated with INRIA also are affiliated with some other universities. For example, you are employed at the University of Rennes. Therefore, they can get their free licenses using their email addresses in respective universities. Consequently, there is no necessity to add inria.fr to the trusted list. 

Moreover, adding it to the trusted list may provoke (even accidentally) people to get more than one free educational subscription per person using email addresses in several organizations. We would better avoid such educational subscriptions abuse.

Do you think it makes sense? What would you suggest to improve in this approach?

**Comment by fernandoFernandeSantos** [comment]
Your comment makes sense. Indeed, I have an IRISA (from the University of Rennes) and INRIA e-mails, which can create future problems, as you mentioned. I think it's better to leave it as you did and not include Inria on the list.

**Pull request closed without merging**
