### PR TITLE
Villanova College QLD AU

### PR DESCRIPTION
**Pull request by MrDarthVader**
Request for Villanova College

### CODE REVIEW

**Comment by philipto** [comment]
@MrDarthVader First stage of verification passed, official domain is [vnc.qld.edu.au](https://vnc.qld.edu.au) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@MrDarthVader Could you please provide more info on what for exactly you need the professional developers tools?
In general, we recommend Community versions of the tools to students who are younger than 13 of age.

**Comment by MrDarthVader** [comment]
I am 16 years old and I've been using Monodevelop and Visual Code. Friends have told me that Rider is the best as I am on a linux dev box. I could do with Visual Code on linux but I am thinking of installing windows and using the community edition of VS. Would be a pity as i prefer linux environment. Why dont you have a community edition like MS VS?

**Comment by philipto** [comment]
@MrDarthVader Thank you for the clarifications. You are quite right. The best experience is to try different tools and decide what is best, depending on your own experience.

Do I understand right that you are the student of this school, while the website says that the school is for younger children only? I might misunderstand the website.

Pull request merged.

**Pull request merged**
