### PR TITLE
Bank Institute High School in Banská Bystrica

### PR DESCRIPTION
**Pull request by internetovaskola**
Bank Institute High School in Slovakia - Banská Bystrica

### CODE REVIEW

**Comment by internetovaskola** [comment]
School: Bank Institute High School in Banská Bystrica
Institution: High School
State: Slovakia/Germany/Europe
Website: http://www.bivs.sk

**Comment by zweizwei** [comment]
please fix the path to sk/bivs.txt

**Comment by internetovaskola** [comment]
I was creative new FILE on that path. Is IT right?

---
Important: This e-mail, including its contents and attachments, if any, are confidential. If you are not the named recipient please notify the sender and immediately delete it. You may not disseminate, distribute, or forward this e-mail message or disclose its contents to anybody else. Copyright and any other intellectual property rights by the Act no. 618/2003 Slovak statute and by the Directive of the European Parliament and of the Council 2012/28/EU in its contents are the sole property of Mgr. René Klauco, PhD. Contents of this e-mail is also protected by the Act no. 122/2003 Slovak statute and by the Directive of the European Parliament and of the Council 95/46/EHS.

Dna 27.3.2015, o 14:42, Elena Ganenkova <notifications@github.com<mailto:notifications@github.com>> napísal:


please fix the path to sk/bivs.txt

**Comment by zweizwei** [comment]
now the path is ok, thank you

**Pull request merged**
