### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by geormich55**
this is certh's mail addresses and website
certh is a research institute in Thermi,Thessaloniki,Greece which coopartes with universities like Aristotle University of Thessaloniki and else.

https://www.certh.gr/
http://mail.iti.gr/
https://mail.iti.gr/squirrel/src/login.php
and my e-mail is
geormich@iti.gr

### CODE REVIEW

**Comment by geormich55** [comment]
also this is Technological Educational Institute of Western Macedonia domain
Technological Educational Institute of Western Macedonia in Kastoria,Fourka,Greece is a technological educational institute in Greece and i'm student in Technological Educational Institute of Western Macedonia in 
international trade department

teiwm.gr
student@teiwm.gr
https://kastoria.teiwm.gr/intrade/

**Comment by philipto** [comment]
@geormich55 Thank you for your request!
**Regarding the iti.gr domain:**
The research institute in Thermi, Thessaloniki, Greece collaborates with different universities. Do students and teachers associated with this institute have email addresses assigned to them by the universities where they were enrolled initially? 
If yes, why don't they use their initial universities email addresses instead of `iti.gr`?

Why do you want to add both domains to this repository? If you have an email address from one institution, like the Technological Educational Institute of Western Macedonia, you're eligible for a free subscription. Having more than one subscription and sharing it with others violates the license terms. Please avoid this practice.

Please reply and remove `iti.gr` from your request, if you can. If you cannot, I can do it for you, if you wish.

**Comment by philipto** [comment]
@geormich55 You might miss my previous comment. Please react.

**Comment by geormich55** [comment]
The research institute in Thermi, Thessaloniki, Greece collaborates with
different universities. Do students and teachers associated with this
institute have email addresses assigned to them by the universities where
they were enrolled initially?
If yes, why don't they use their initial universities email addresses
instead of iti.gr?

Hello..they don't have email addresses from these universities..


Answer:

This is an organisational topic of bad management..


Why do you want to add both domains to this repository? If you have an
email address from one institution, like the Technological Educational
Institute of Western Macedonia, you're eligible for a free subscription.
Having more than one subscription and sharing it with others violates the
license terms. Please avoid this practice.


Answer:

I didn't do this for sharing it with others..I only did it for using it
myself because the mail server of the technological educational Institutute
of western Macedonia sometimes doesn't connect or something..

This is why I would like to create me a free subscription with the iti
email as a priority..


If this can't be done explain me why..

If it can be done remove the university's mail and keep iti mail if it's
possible..

I can remove it..

Simply would like to have iti as a free subscription mail..


GM

**Comment by philipto** [comment]
@geormich55 Hello!

I am sorry, I have to reject the request. Your reply above does not formatted well, thus it's hard to read. If I understood your point correctly, you want to use the ITI email for a free subscription, because another university where you are enrolled does not have a properly configured mail server.

The same applies to other students who use ITI email addresses instead of email addresses assigned to them by the universities where they are enrolled to.

I see some risks in adding ITI to the trusted list, because it's not an educational organization, first of all. We cannot ensure that only students and teachers will use the free subscriptions.

Also, it would be beneficial for everybody if you and other students and teachers insist that your universities where you are enrolled or employed configure their mail systems properly. It's ridiculous to have misconfigured mail system and bad management at a university. 

At a last resort, you can simply apply for a student license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging. Thank you for your understanding!

**Pull request closed without merging**
