### PR TITLE
Add Thai Nguyen University Of Medicine And Pharmacy in list of universities

### PR DESCRIPTION
**Pull request by TruongGiangLe**

### CODE REVIEW

**Comment by philipto** [comment]
@TruongGiangLe First stage of verification passed, official domain is [tump.edu.vn](https://tump.edu.vn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: http://benhvien.tump.edu.vn/contact

**Comment by philipto** [comment]
@TruongGiangLe Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@TruongGiangLe You might miss my previous comment. Please react.

**Comment by TruongGiangLe** [comment]
I'm sorry, my school currently is not providing any IT courses. My bad,
I have not read the conditions carefully, :( . You can just reject my pull
request, I'm sorry but thank you for being patient
 with me.

**Comment by philipto** [comment]
@TruongGiangLe I have to close the request without merging. Thank you for your understanding and being so patient and kind. Have a very good week!

**Pull request closed without merging**
