### PR TITLE
Add @student.hsdc.ac.uk for HSDC

### PR DESCRIPTION
**Pull request by tobezdev**
Added `uk/ac/hsdc/student` for @student.hsdc.ac.uk email addresses.

### CODE REVIEW

**Comment by tobezdev** [comment]
If someone could figure out how to add @hsdc.ac.uk to this PR too, I would be more than grateful. I couldn't make the `uk/ac/hsdc` file because there was already a `hsdc` directory. TIA.

**Comment by philipto** [comment]
@tobezdev lib/domains/uk/ac/hsdc/student: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by tobezdev** [comment]
@philipto Seems that the malformed file should be fine now due to your changes?

**Comment by philipto** [comment]
@tobezdev First stage of verification passed, official domain for **Havant and South Downs College** is [student.hsdc.ac.uk](https://student.hsdc.ac.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by tobezdev** [comment]
No worries on the wait.
_Technically_ the official domain is `hsdc.ac.uk`, however students are given access to the `student.hsdc.ac.uk` subdomain. Not too sure how to add the root domain too as the file (for the root) and folder (for `student.`) have conflicting names.

**Comment by philipto** [comment]
@tobezdev Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
