### PR TITLE
Tecnológico de Monterrey Virtual Campus

### PR DESCRIPTION
**Pull request by carloskiron**
Adding virtual campus of Tecnológico of Monterrey Institute

### CODE REVIEW

**Comment by philipto** [comment]
@carloskiron Could you please tell us a bit more about the university? Please note that JetBrains does not grant free educational licenses to students of online universities, thus if the university needs to be added to this repository, it must not be an online university. Could you please give us an URL on the official website confirming that:
1) the unversity offers offline IT-related long-term (> 1 year) courses, which are taught in classrooms (not online)
2) only the students use emails in techvirtual.mx domain, not third-party people, university non-educational staff, alumni, etc.
Thank you!

**Comment by carloskiron** [comment]
Hi, I am taking a master degree on IT (MATI) in the Tecnológico de Monterrey. This is an online Master Degree

University website: http://www.itesm.mx/ <http://www.itesm.mx/>

University Email Account:
A01311692@tecvirtual.mx <mailto:A01311692@tecvirtual.mx>
Program description
http://www.itesm.mx/wps/wcm/connect/itesm/tecnologico+de+monterrey/maestrias+y+doctorados/escuelas/escuela+de+ingenieria+y+ciencias/mti-v <http://www.itesm.mx/wps/wcm/connect/itesm/tecnologico+de+monterrey/maestrias+y+doctorados/escuelas/escuela+de+ingenieria+y+ciencias/mti-v>

**Comment by philipto** [comment]
@carloskiron Thank you for the additional information. Unfortunately, I can not add this university to the repository, because JetBrains does not grant free licenses to online universities on the base of posessing an e-mail address from such a university. Readme file at https://github.com/JetBrains/swot explicitly says that:

> Your pull request for adding a new email domain to the repository will be satisfied if all of the conditions below are met:
> 
> 1. The domain is used by an educational institution, which offers at least one long-term course (one year or longer), and the course is somehow related to IT (it is in computer science, software engineering, statistics, bioinformatics, etc.)
> 
> 2. The educational institution has a physically existing location, where students attend classes in the classrooms. In general, we do not include online universities to this repository.

However you can apply for the free license if you have an ISIC card, or email a photo of your student ID card to sales@jetbrains.com. 

I am closing this request without merging. Thank you for your understanding.

**Comment by carloskiron** [comment]
Not a problem. Thank you for taking the time to review it!

**Pull request closed without merging**
