### PR TITLE
iberopuebla.txt

### PR DESCRIPTION
**Pull request by RodrigoIbarraSanchez**

### CODE REVIEW

**Comment by RodrigoIbarraSanchez** [comment]
Adding Ibero Puebla

**Comment by RodrigoIbarraSanchez** [comment]
http://www.iberopuebla.mx/

**Comment by philipto** [comment]
@RodrigoIbarraSanchez 
```
$ host -t mx ibero_puebla.mx
Host ibero_puebla.mx not found: 3(NXDOMAIN)
```
If you wish to add iberopuebla.mx domain, the file path for it has to be `/lib/domains/mx/iberopuebla.txt`. Please note that .txt extension is mandatory.
Please rename the file accordingly, if my guess about what do you wish to add is right. Thank you!

**Comment by RodrigoIbarraSanchez** [comment]
Hello! Thanks for your reply! I have changed the name of the file to iberopuebla.txt. Greetings! 👍

**Comment by philipto** [comment]
@RodrigoIbarraSanchez No, you changed just the title of the request. Please change the FILE PATH in the request. You can create a new request, if it is a problem for you to change the file path. Thank you!

**Comment by philipto** [comment]
@RodrigoIbarraSanchez I am closing this request because the issue is resolved as a request #2303. Thank you!

**Pull request closed without merging**
