### PR TITLE
adding a school

### PR DESCRIPTION
**Pull request by radhe-shyam**

### CODE REVIEW

**Comment by philipto** [comment]
@radhe-shyam File path lib/domains/in/shipsy.txt in your request  corresponds to a domain shipsy.in which does not seem to belong to any school. 

Please make sure that you are familiar with the rules of this repository located at the bottom of [this page](https://github.com/JetBrains/swot), and modify your request accordingly.

**Comment by samlovespider** [comment]
Massey University

**Comment by philipto** [comment]
@radhe-shyam Please make necessary changes, otherwise I have to close this request without merging. Thank you.

**Comment by philipto** [comment]
@radhe-shyam This request remains unanswered for a while. I have to close it without merging. Please reopen if you have an update regarding the issue mentioned above. Thank you for the understanding!

**Pull request closed without merging**
