### PR TITLE
Create tio.txt

### PR DESCRIPTION
**Pull request by causafinalis**

### CODE REVIEW

**Comment by philipto** [comment]
@causafinalis Could you please provide us with a link to a page on the university website where the university offers at least one long-term course (one year or longer), and the course is somehow related to IT? Thank you!

**Comment by causafinalis** [comment]
We don't. We teach a Python programming subject

Sent on the go. Apologies for possible brevity or typo's.

**Comment by philipto** [comment]
@causafinalis Do you have any description of this subject on the website? I failed to find it mentioning at www.tio.nl. I need it to ensure that the course is long-term (> 1 year), because if it is short-term training (few weeks long, for example), we would offer you another type of free license, which can not be obtained via application at jetbrains.com/student.

**Comment by causafinalis** [comment]
It is a 2 semester (so I assume <1 year) course part of International
Business, Hotel & Event and International Tourism Bachelors degree

On Wed, Apr 27, 2016 at 1:01 AM, Philip Torchinsky <notifications@github.com

**Comment by philipto** [comment]
@causafinalis No problem, let's count two semesters as 1 year. Is there any description of it? I found nothing related to Python programming at https://www.tio.nl/internationaal_toeristisch_management/

If you have such a proof, please share it with us. I merge the pull request, because the university certainly fits other requirements to be included into this repository. Thank you!

**Comment by causafinalis** [comment]
Hi,

there is nothing on the site as such. There is a reference to Data
analysis. This used to be a SPSS class but i am changing and expanding it
to Data analysis and Python programming. I work with you program and would
love to have my students do this as well.
Thank you for your time.

On Wed, Apr 27, 2016 at 1:11 PM, Philip Torchinsky <notifications@github.com

**Pull request merged**
