### PR TITLE
Beatitudes of Jesus Christ Academy of Davao, Inc.

### PR DESCRIPTION
**Pull request by chesteralan**
Beatitudes of Jesus Christ Academy of Davao, Inc.

### CODE REVIEW

**Comment by philipto** [comment]
@chesteralan First stage of verification passed, official domain for **Beatitudes of Jesus Christ Academy of Davao, Inc.** is [beatitudesjcad.edu.ph](https://beatitudesjcad.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@chesteralan Please provide more information about the school. What age of students does the school teach? Are they all younger than 13 of age? Which JetBrains tools the school needs and for what? Which classes do you teach? What are your requirements to the IDEs? 

Is this school an online-only school?

**Comment by philipto** [comment]
@chesteralan You might miss my previous comment. Please react.

**Comment by chesteralan** [comment]
@philipto The school is teaching elementary at the moment. Grade 1 to 6. From 8 years old to 13 years old. For Grade 6, we are teaching computer classes, introduction to web which includes creating html pages. They are introduced to different web tools including JetBrains products. I am planning to let them use JetBrains IDE as the primary tool for creating html pages because I like your IDEs especially WebStorm.

**Comment by philipto** [comment]
@chesteralan Thank you for the answer! Did you consider using PyCharm Community Edition or PyCharm for Education tools for this purpose? They also support HTML, and they do not require any subscription, and are free for everyone.

The organization that you described is not qualified to be added to this repository, as of [current rules of the repository](https://github.com/JetBrains/swot?tab=readme-ov-file#which-educational-institutions-can-be-added-to-the-repository). I have to close the request without merging it.

Shall you need specifically WebStorm for a specific reason, please write an email to community-support@jetbrains.com and describe how many licenses you need. Thank you!

**Pull request closed without merging**
