### PR TITLE
Create sjc

### PR DESCRIPTION
**Pull request by dsolutiontechBZ**
Adding my college to the list to use as jetbrains product as a student

### CODE REVIEW

**Comment by dsolutiontechBZ** [comment]
nice

**Comment by philipto** [comment]
@dsolutiontechBZ lib/domains/bz/sjc: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@dsolutiontechBZ Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by philipto** [comment]
@dsolutiontechBZ You might miss my previous comment. Please react.

**Comment by dsolutiontechBZ** [comment]
Good day,

Sorry for the late response.

1. the school official website URL: https://www.sjc.edu.bz/

2. the school street address, including city and country: Princess Margaret Drive, Belize

3. an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: https://www.sjc.edu.bz/bachelor-s-degrees



________________________________

**Comment by philipto** [comment]
@dsolutiontechBZ Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by dsolutiontechBZ** [comment]
Thanks very much

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
