### PR TITLE
Created bizerte.txt for ISET Bizerte Insitute in Tunisia

### PR DESCRIPTION
**Pull request by darkviiolet**

### CODE REVIEW

**Comment by manujsengar** [comment]
[satiengg.txt](https://github.com/JetBrains/swot/files/7807194/satiengg.txt)

**Comment by philipto** [comment]
@darkviiolet Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@darkviiolet You might miss my previous comment. Please react.

**Comment by darkviiolet** [comment]
I received your emails, I will provide those as soon as possible.
thank you for your time and effort

**Comment by philipto** [comment]
@darkviiolet Is everything OK? Do you have any update on the matter? Is this request still actual?

**Comment by darkviiolet** [comment]
My apologies for taking too long to respond, i am currently on vacation
from college and a bit busy with some new projects. I don't have good
access to internet.
Anyways, about my uni. I don't know if i can actually provide all the
documents that you asked right away but i'll send you what i have right now
as proof that this college exists.
If it isn't enough, please let me know so i figure out another way.
In these files you will find proof that i'm studying OOP with python in my
uni, you will also have the uni website, our microsoft teams accounts that
the uni give us and more.

The institut's website: http://www.isetbz.rnu.tn/

**Comment by darkviiolet** [comment]
These are some screenshots
the address of the uni: Menzel Abdelrahman, Bizerte, Tunisia.

**Comment by philipto** [comment]
@darkviiolet Thank you for your response. Regrettably, GitHub strips out all attachments sent by email. Please upload the screenshots with your browser to [this](https://github.com/JetBrains/swot/pull/13269) page.

**Comment by darkviiolet** [comment]
Thank you for your time, much appreciated

**Pull request merged**
