### PR TITLE
Create kfaryarok.txt

### PR DESCRIPTION
**Pull request by rootatkali**
Add HaKfar HaYarok high school in Israel

### CODE REVIEW

**Comment by khanhvo99** [comment]
Add Dong A University in VietNam
[donga.txt](https://github.com/JetBrains/swot/files/5326439/donga.txt)

**Comment by philipto** [comment]
@rootatkali Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@rootatkali You might miss my previous comment. Please react.

**Comment by rootatkali** [comment]
School URL - http://www.kfaryarok.org.il/en

Computer science course - http://www.kfaryarok.org.il/software-engineering

I asked the school administration for confirmation about email addresses and they should respond by next week, as there is a holiday in Israel right now.

**Comment by philipto** [comment]
@rootatkali Thank you!
OK, let's wait for the administration response. Have a good holiday!

**Comment by philipto** [comment]
@rootatkali I am sorry, it there any update from the administration?

**Comment by philipto** [comment]
@rootatkali I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
