### PR TITLE
update for indonesian university sites

### PR DESCRIPTION
**Pull request by 23Pstars**
manually check using [this script](https://github.com/23Pstars/py-utils/blob/master/jetbrains_swot.py)

### CODE REVIEW

**Comment by philipto** [comment]
@23Pstars Thank you for your very good attempt to update the  repository. There is one issue, which seem to be missed from your script: for the universities whose domains you suggest to update (rename), there could be email domains different from their web site domains. Thus, you may wish to update the script to check whether existing domain has an MX record in DNS with
```
host -t mx some-name.ac.id
```
If the record exists it means that you need to check manually if the university actually use this domain as an email domain for the students.

I checked some of the changes that you suggested, and found that at least one of them shall not be implemented because there is an existing email service there, and it belongs to the university:
```
$ host -t mx stan.ac.id
stan.ac.id mail is handled by 10 alt3.aspmx.l.google.com.
stan.ac.id mail is handled by 10 alt4.aspmx.l.google.com.
stan.ac.id mail is handled by 1 aspmx.l.google.com.
stan.ac.id mail is handled by 5 alt1.aspmx.l.google.com.
stan.ac.id mail is handled by 5 alt2.aspmx.l.google.com.
```
```
$ whois stan.ac.id
Domain ID:PANDI-DO226639
Domain Name:STAN.AC.ID
Created On:23-Jul-1999 13:32:23 UTC
Last Updated On:03-Mar-2016 07:33:36 UTC
Expiration Date:31-Oct-2016 23:59:59 UTC
Status:ok
Registrant ID:01270726RFA
Registrant Name:Harris Hariadi
Registrant Organization:Politeknik Keuangan Negara STAN
Registrant Street1:Jl. Bintaro Utama Sektor V
Registrant Street2:Bintaro Jaya
Registrant City:Tangerang Selatan
Registrant State/Province:Banten
Registrant Postal Code:15222
```
Please update the request to rename just the files which refer to universities using new domains.

Thank you!

**Comment by 23Pstars** [comment]
Hi @philipto thank you for the suggestion :)
Just wondering is it OK to have two or more different files (domains) for one universities?

**Comment by philipto** [comment]
@23Pstars Yes, it is absolutely OK to have as many files for a university as necessary to represent all the email domains which university students use. There will be the same university name in each file.

**Comment by philipto** [comment]
@23Pstars I am sorry for a delay with processing the request. It is now merged. Thank you again for your contribution!

**Pull request merged**
