### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by guzmanico23**
Hello! This is for adding my school. Thank you

### CODE REVIEW

**Comment by MarcoFormicola2004** [comment]
Hy, t
[itipacinotti.txt](https://github.com/JetBrains/swot/files/5709548/itipacinotti.txt)
his is for adding my school. Thank you

**Comment by MarcoFormicola2004** [comment]
Hy, this is for adding my school. Thank you

[itipacinotti.txt](https://github.com/JetBrains/swot/files/5709557/itipacinotti.txt)

**Comment by philipto** [comment]
@guzmanico23 Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

@MarcoFormicola2004 Please make a separate pull request. If you cannot do it, please send an email with your request to community-support@jetbrains.com.

**Comment by philipto** [comment]
@guzmanico23 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
