### PR TITLE
Add VDAB Campus

### PR DESCRIPTION
**Pull request by summerinpalma**
#### Institution/School Name 
{VDAB}

#### Instiution/School Website
{https://www.vdab.be}

#### Link to education
{https://www.vdab.be/opleidingen/aanbod/O-AMI-750430/cursus/C-AMI-207566/Full_stack_developer-WEVELGEM}

#### Email Users

*Please place an x between the square brackets if yes*
- [X] Students
- [ ] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [X] Graduate School
- [X] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [ ] High School or equivalent
- [ ] Elementary School or equivalent

VDABCAMPUSDOMAIN

### CODE REVIEW

**Comment by philipto** [comment]
@summerinpalma First stage of verification passed, official domain is [vdab.be](https://vdab.be) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.vdab.be/formulier/helpdesk-cursisten

**Comment by summerinpalma** [comment]
Hey hey,

The official domain is www.vdab.be, that is correct. However, this part of
the organisation helps people to find an actual job.

The domain they give out to students engaged in a course provided by VDAB
is @vdabcampus.be.

Please add the latter, as requested.

Thank you for the very quick review!

Ibo

**Comment by summerinpalma** [comment]
@philipto Link to the student platform: https://portaal.vdabcampus.be/

**Comment by philipto** [comment]
@summerinpalma Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
