### PR TITLE
Added a new school.

### PR DESCRIPTION
**Pull request by karizadias**

### CODE REVIEW

**Comment by philipto** [comment]
@karizadias First stage of verification passed, official domain is [instagram.com](https://instagram.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.instagram.com/caedfoficial/

**Comment by karizadias** [comment]
> 

Hello, @philipto. I didn't understand the proof of domain: https://www.instagram.com/caedfoficial/. I'm a teacher at CEF 214 Sul (https://www.instagram.com/cef214sulgdf/), a public school in Brasilia-DF, Brasil. If you have any doubt, please let me know.

**Comment by karizadias** [comment]
Our government website:

https://www.educacao.df.gov.br/centro-de-ensino-fundamental-214-sul/

**Comment by philipto** [comment]
@karizadias Thank you! 

Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@karizadias You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@karizadias I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
