### PR TITLE
Added Kuzneckiy college

### PR DESCRIPTION
**Pull request by xadminxster**
Please add our college to the list.

### CODE REVIEW

**Comment by philipto** [comment]
@xadminxster Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by xadminxster** [comment]
Site: https://kuzmk.ru/
Address: 442530, Kuzneck, Penzenskaya obl., ul. Lenina, 246 
IT course: https://kuzmk.ru/qualify/id/32
Contacts: https://kuzmk.ru/contacts

**Comment by philipto** [comment]
@xadminxster Thank you for the details. There are two websites, which belongs to the same organization with the same address. One of them has the description of the IT-related course, and the other don't have it:
https://kuzmk.ru/qualify/id/32
http://mcollege.ru/%d1%81%d0%bf%d0%b5%d1%86%d0%b8%d0%b0%d0%bb%d1%8c%d0%bd%d0%be%d1%81%d1%82%d0%b8/

**Comment by xadminxster** [comment]
mcollege.ru is website for a branch of the colledge in Russkiy Kameshkir villadge (address: с. Русский Камешкир,  ул. Техническая д.2).
Students use kuzmk.ru domain.

**Comment by philipto** [comment]
@xadminxster  Thank you for the clarifications. Pull request merged.

**Pull request merged**
