### PR TITLE
Adding moisilbv.ro of NCSC „Grigore Moisil” Brasov

### PR DESCRIPTION
**Pull request by killedBy11**

### CODE REVIEW

**Comment by killedBy11** [comment]
The school website is: https://moisilbrasov.ro/
The website isn't always up to date and the student emails have been introduced since the pandemic as Google organization emails.

**Comment by philipto** [comment]
@killedBy11 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@killedBy11 You might miss my previous comment. Please react.

**Comment by killedBy11** [comment]
Hello,
It took me a while to find it, but the only official document I have regarding this issue is the G suite activation code list, but the domain is not mentioned there.

**Comment by killedBy11** [comment]
@philipto is it sufficient if I provide that?

**Comment by philipto** [comment]
@killedBy11 Yes. Please upload the copy of the document to the comment at https://github.com/JetBrains/swot/pull/11174 with your web browser. Thank you.

**Comment by killedBy11** [comment]
[email.pdf](https://github.com/JetBrains/swot/files/6302600/email.pdf)
[Clasa-a-XI-a-C.pdf](https://github.com/JetBrains/swot/files/6302601/Clasa-a-XI-a-C.pdf)
@philipto here are the requested documents. In the code list, the names and codes of my colleagues were masked for privacy.

**Comment by philipto** [comment]
@killedBy11 Thank you for the clarification. Pull request merged.

**Pull request merged**
