### PR TITLE
wbactc domain

### PR DESCRIPTION
**Pull request by LLethul**

### CODE REVIEW

**Comment by philipto** [comment]
@LLethul First stage of verification passed, official domain is [wbactc.org](https://wbactc.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by LLethul** [comment]
this is still being looked into, right?

**Comment by philipto** [comment]
@LLethul Yes, you are quite right. Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.
Thank you!

**Comment by philipto** [comment]
@LLethul You might miss my previous comment. Please react.

**Comment by LLethul** [comment]
https://wbactc.org/
350 Jumper Rd, Wilkes-Barre, PA 18702
http://www.wbactc.org/CIT.html

**Comment by philipto** [comment]
@LLethul Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
