### PR TITLE
Create it_schule

### PR DESCRIPTION
**Pull request by Daviddo3399**
official website: https://www.its-stuttgart.de
it-related courses: https://www.its-stuttgart.de/its/front_content.php?idcat=2
school domain proof: https://prnt.sc/fix52i

### CODE REVIEW

**Comment by philipto** [comment]
@Daviddo3399 Could you please make sure that you have read the instructions on how to add a domain to this repository at the bottom of this page: https://github.com/JetBrains/swot

Also, please let us know which domain you wish to add. Thank you.

**Comment by philipto** [comment]
@Daviddo3399 lib/domains/edu/it_schule file has wrong filename format, it must have an extension .txt. However, even lib/domains/edu/it_schule.txt corresponds to a domain it_schule.edu, which does not exist. This is why I ask you to tell which domain you wish to add. Please reply. Thank you.

**Comment by Daviddo3399** [comment]
i guess the domain is its-stuttgart.de or isn't that an valid domain?

**Comment by philipto** [comment]
@Daviddo3399 I am sorry, I don't know which email domain students use in your school. If your university email address ends with @its-stuttgart.de, and you wish to add this domain to the repository, please rename the file in your request to lib/domains/de/its-stuttgart.txt. 

Please feel free to check the details on how to add a domain to this repository at the bottom of this page: https://github.com/JetBrains/swot/

Thank you!

**Comment by philipto** [comment]
@Daviddo3399 
It's a bit tricky, I see. Do I understand right that your email which you need a free license for, is something like xxx@its-stuttgart.de? If yes, I'll make the correct request for you, otherwise it takes too much of your time.  The file lib/domains/edu/its-schule.txt which you have in your request now represents a domain its-schule.edu, which does not exist:
```
$ host -t any its-schule.edu
Host its-schule.edu not found: 3(NXDOMAIN)
```

Please clarify which email you need the license for, and I'll arrange the rest. Thank you.

**Comment by Daviddo3399** [comment]
yes the email is like xxx@its-stuttgart.de
Thank you very much!

**Comment by philipto** [comment]
@Daviddo3399 Well, I just double checked and found that the repository entry representing your school already exists in this repository: https://github.com/JetBrains/swot/blob/master/lib/domains/de/its-stuttgart.txt 

Did you try to request a free license using your school email address at https://jetbrains.com/student? What was the result? If you did not receive a confirmation email after applying, please send us an email to support@jetbrains.com, we'll check what happened.

**Comment by philipto** [comment]
@Daviddo3399 As per my previous comment, I close this request without merging due to existence of the record in the repository.

**Pull request closed without merging**
