### PR TITLE
Add maricopa.txt - obtaining non-student addresses through maricopa is no longer possible

### PR DESCRIPTION
**Pull request by phxvyper**
**In reference to #4537, #2393 and #1673:**

**The instructions in the post referenced by #1673 are no longer valid and MCC has completely deprecated any functionality allowing non-students and non-faculty members from obtaining an email under maricopa.edu** - these changes were made years ago, and the instructions afforded in the post referenced by #1673 haven't been valid for nearly 5 years.

### Original PR:

Maricopa Community Colleges encompasses 10 different schools in Maricopa County, Arizona, all of which are listed here: https://www.maricopa.edu/why-maricopa/colleges - all 10 of these schools utilize the maricopa.edu SLD for student email.

Each college has a course catalog available at their respective website, each school offers multi-semester and multi-year courses in CIS and CS. Rio Salado, for example, offers multiple courses for certificates of completion and degrees in Computer Science, such as their Mobile Apps programming course. Rio's catalog can be found here: http://www.riosalado.edu/catalog/Documents/College-Catalog-2017-2018.pdf

Of those 10, Mesa and Glendale both have public pages describing maricopa.edu as the primary email domain for students, with steps for setting it up:

 - https://www.mesacc.edu/enroll/student-email
 - http://www.gccaz.edu/technology-help/student-email

### CODE REVIEW

**Comment by phxvyper** [comment]
Any update on this PR?

**Comment by phxvyper** [comment]
@philipto is there a hold on merging this PR?

**Comment by philipto** [comment]
@phxvyper Yes, this PR requires deeper review, because:
1) It seems that it's not possible to get maricopa.edu address if literally follow the guide mentioned in #1673. 
2) However, if a person gets a fake U.S. electronic ID, which was still possible at the time when this request (#4618) was made, getting the maricopa.edu address was still possible, to the best of my knowledge. I will check this issue again, and will update this PR.

You also can use an option "OFFICIAL DOCUMENT" at https://www.jetbrains.com/shop/eform/students to request your free licenses for JetBrains tools. It works well for many students, and the students at Maricopa are not excluded. We just refrain from adding maricopa.edu to this repository, but actual students of Maricopa are very welcome to use our tools.

**Comment by philipto** [comment]
@phxvyper We carefully reviewed the case, and found out that ID forgery seems no longer working for getting a maricopa.edu email address. Thus, I satisfy this PR, and we'll monitor the situation. If it happens that the domain will again be used to misuse educational licenses, the PR can be reverted. Thank you for bringing this issue to our attention.

**Pull request merged**
