### PR TITLE
add domain numazu.kosen-ac.jp

### PR DESCRIPTION
**Pull request by Nshu**
add lib/domains/jp/kosen-ac/numazu.txt

### CODE REVIEW

**Comment by philipto** [comment]
@Nshu Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Nshu** [comment]
@philipto Thank you for your advice.

>the university official website URL, if different from the domain you are submitting
http://www.numazu-ct.ac.jp/
English ver : http://www.numazu-ct.ac.jp/english/

>an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_m.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_e.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_d.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_s.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_c.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_a.pdf
in http://www.numazu-ct.ac.jp/campuslife/syllabus

>an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.
[mail_information.pdf](https://github.com/JetBrains/swot/files/2255642/mail_information.pdf)

that's all.
Thank you.

**Comment by Nshu** [comment]
@philipto Thank you for your advice.

the university official website URL, if different from the domain you are submitting
http://www.numazu-ct.ac.jp/
English ver : http://www.numazu-ct.ac.jp/english/

an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_m.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_e.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_d.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_s.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_c.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_a.pdf
in http://www.numazu-ct.ac.jp/campuslife/syllabus

an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.
mail_information.pdf

**Comment by Nshu** [comment]
@philipto Thank you for your advice.

the university official website URL, if different from the domain you are submitting
http://www.numazu-ct.ac.jp/
English ver : http://www.numazu-ct.ac.jp/english/

an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_m.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_e.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_d.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_s.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_c.pdf
http://www.numazu-ct.ac.jp/wp-content/uploads/03campuslife/01syllabus/curriculum_a.pdf
in http://www.numazu-ct.ac.jp/campuslife/syllabus

an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.
[mail_information.pdf](https://github.com/JetBrains/swot/files/2255645/mail_information.pdf)

**Comment by philipto** [comment]
@Nshu Thank you for the update! Pull request merged.

**Pull request merged**
