### PR TITLE
Add Paramount School and College

### PR DESCRIPTION
**Pull request by Nawshaduzzaman**
Paramount School and College
www.mypscedu.com

### CODE REVIEW

**Comment by Nawshaduzzaman** [comment]
Add Paramount School and College

**Comment by Nawshaduzzaman** [comment]
Proof
Screenshot(1)

**Comment by Nawshaduzzaman** [comment]
[mypscedu.txt](https://github.com/JetBrains/swot/files/5130584/mypscedu.txt)

**Comment by philipto** [comment]
@Nawshaduzzaman mypscedu: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Pull request closed without merging**
