### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by moh4medAmr**

### CODE REVIEW

**Comment by philipto** [comment]
@moh4medAmr Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@moh4medAmr You might miss my previous comment. Please react.

**Comment by moh4medAmr** [comment]
I am actually at a preparatory school.
And it doesn't have a url. Also it doesn't provide IT. That's it 

But I can replay you the Url where i got my email to chech it. Thanks

**Comment by philipto** [comment]
@moh4medAmr Given the circumstances, I don't think that the school meets the criteria for being added to this repository. 

I have to close the request without merging. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Pull request closed without merging**
