### PR TITLE
Create zsmogilno.txt

### PR DESCRIPTION
**Pull request by HazellOfficial**
Website: https://zs-mogilno.pl

### CODE REVIEW

**Comment by philipto** [comment]
@HazellOfficial Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by HazellOfficial** [comment]
image
This is the official electronic diary of the student at the school.

**Comment by HazellOfficial** [comment]
I have written to the school to see if they have any documentation on the domain/email address. If the photo above is not enough, I will be able to send the school's answer.

**Comment by philipto** [comment]
@HazellOfficial Thank you! Yes, please ask the school to provide you and us with some official confirmation that the domain belongs to the school. Thank you.

**Comment by HazellOfficial** [comment]
Currently, the school is not replying to me, it is possible that it is due to holidays and recruitment. Is there any way I can prove that this email belongs to the school? Maybe some information from the Microsoft panel or other stuff. I don't know if it's possible to check something like this, so I'm asking for small tips

**Comment by HazellOfficial** [comment]
image
I also got this email when activating my account. In general, account activation looked like this:
On the official electronic journal of the student (first photo) I got a login and password generated.
Then I had to enter a second email and a new password.

**Comment by HazellOfficial** [comment]
And how about that?

**Comment by philipto** [comment]
@HazellOfficial  Thank you very much for the clarifications. Pull request merged.

**Pull request merged**
