### PR TITLE
Create sfj

### PR DESCRIPTION
**Pull request by RexTheCapt**

### CODE REVIEW

**Comment by philipto** [comment]
@RexTheCapt Could you please clarify if there is a subdomain of the commune domain dedicated for students, as discussed here - https://github.com/JetBrains/swot/pull/1932#issuecomment-214686395

Also, please notice that the file name in the request must end with an extension .txt. Please rename. Thank you!

**Comment by philipto** [comment]
@RexTheCapt You might miss my previous comment. Please look at the issue described above, fix it, and comment. If you decide not to modify the request, I will have to close it without merging. Thank you!

**Comment by RexTheCapt** [comment]
@philipto Sorry for taking so long to replying. I have been bussy with lots of stuff. Well the domain that is used for this school is @skule.sfj.no

**Comment by philipto** [comment]
@RexTheCapt OK, I am renaming the files and add two domains:
skule.sfj.no
eid.vgs.no
They will be available in the system for free licenses requests in about 30 minutes.

**Pull request merged**
