### PR TITLE
Create pku

### PR DESCRIPTION
**Pull request by smile349**
北京大学
https://www.pku.edu.cn/

### CODE REVIEW

**Comment by smile349** [comment]
https://mail.pku.org.cn/

**Comment by philipto** [comment]
@smile349 lib/domains/cn/org/pku: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by smile349** [comment]
> @smile349 lib/domains/cn/org/pku: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.
The file path I provided is correct. The email suffix of teachers in our school is @pku.edu.cn, while that of students is @pku.org.cn. This is the official website of our school https://www.pku.edu.cn/. This is our students' education login email address https://mail.pku.org.cn/coremail/hxphone/

**Comment by philipto** [comment]
@smile349 lib/domains/cn/org/pku: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by smile349** [comment]
OK

**Pull request closed without merging**
