### PR TITLE
add DSTI school

### PR DESCRIPTION
**Pull request by LaurentBerder**
https://www.datasciencetech.institute/

### CODE REVIEW

**Comment by philipto** [comment]
@LaurentBerder Could you please let us know if your online students (those who study 100% of time online) are given an email in the edu.dsti.institute domain? Thank you!

**Comment by LaurentBerder** [comment]
Hi,

Absolutely, 100% students get an email adress on edu.dsti.institute domain during the time of their studies.

Thanks

[cid:image003.png@01D25492.4AEB2AD0]Laurent Berder

Data ScienceTech Institute
laurent.berder@edu.dsti.institute<mailto:laurent.berder@edu.dsti.institute>
+33 6 71 09 21 16

**Comment by philipto** [comment]
@LaurentBerder Yes, it's what I was afraid of. Unfortunately, JetBrains does not grant free licenses to online universities. Please refer to the rules at the bottom of this page: https://github.com/JetBrains/swot/
Thus, I have to close this request without merging. Thank you for your understanding.

**Comment by LaurentBerder** [comment]
Excuse me, but why do you refer to DSTI as an online university?
The Institute is a physical university, with 2 real campuses in France: one in Paris, and the other in Sophia Antipolis.

Laurent Berder

Le 12 déc. 2016 16:24, Philip Torchinsky <notifications@github.com> a écrit :

@LaurentBerder<https://github.com/LaurentBerder> Yes, it's what I was afraid of. Unfortunately, JetBrains does not grant free licenses to online universities. Please refer to the rules at the bottom of this page: https://github.com/JetBrains/swot/
Thus, I have to close this request without merging. Thank you for your understanding.

**Comment by philipto** [comment]
@LaurentBerder Sometimes the universities combine online and offline courses, and do not provide online-only students with the email addresses in the same domain as the offline students. We need to be sure that licenses are used by offline students only. Do you have a technical mechanism which allows to control it?

**Comment by philipto** [comment]
@LaurentBerder Could you please comment on the issue above? It also can help if you can provide some statistics on how many students study in your institute online only. This request is now reopened, waiting for some more information from you. Thank you!

**Comment by philipto** [comment]
@LaurentBerder I am sorry for not being able to add your university to this repository instantly. However we consider various options for it. Do you think that Classroom license makes sense for the teachers and students at DSTI? Classroom license is also free, and if a teacher decides to request a Classroom license, the teacher then is able to assign the students with the license by sending them an email with invitation link.

**Comment by philipto** [comment]
@LaurentBerder Hello, and Happy New Year! We carefully reviewed this case internally, and decided that your school can be added to this repository. We appreciate if the students of the school will respect our policy and JetBrains license, given that the license is granted for free for educational purpose only to the students who study in offline campuses. Pull request merged. Thank you for your patience.

**Pull request merged**
