### PR TITLE
Create educadventista.txt

### PR DESCRIPTION
**Pull request by V-camp**

### CODE REVIEW

**Comment by philipto** [comment]
@V-camp Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by V-camp** [comment]
Good afternoon

[image: image.png]


Em seg., 13 de jun. de 2022 às 15:02, Philip Torchinsky <
***@***.***> escreveu:

**Comment by philipto** [comment]
@V-camp Thank you! Regrettably, GitHub strips out all attachments send by e-mail. Please upload the document that you have sent in reply to the comment. "Upload" here means upload using a browser, as a comment to this page: https://github.com/JetBrains/swot/pull/14352

Thank you.

**Comment by V-camp** [comment]
Good Morning.
Follow the image link

Thank you.

https://user-images.githubusercontent.com/84048263/174285831-3791eb18-5f5e-4365-bb53-6a8911e9cec5.png

educadventista

**Comment by philipto** [comment]
@V-camp I am sorry, the image seems not to proof anything. Isn't there more official proof, such as a letter from the university saying that you can use the email address in the domain? The WHOIS data are insufficient for this domain, to my regret.

**Comment by philipto** [comment]
@V-camp You might miss my previous comment. Please react.

**Comment by V-camp** [comment]
> @V-camp You might miss my previous comment. Please react.

@philipto 
Apologies for the delay. My college is changing domains, I'll wait to see what the new one will be and I'll send it again.
Thank you very much for your attention and for all your help.

**Pull request closed without merging**
