### PR TITLE
Adding National Centre for Biological Sciences to domain list.

### PR DESCRIPTION
**Pull request by rohitsuratekar**

### CODE REVIEW

**Comment by philipto** [comment]
@rohitsuratekar I am sorry, but National Centre for Biological Sciences seems to be neither university, nor college. If it is a research center with an option to teach some people in computer science, I would suggest a teacher who teach computer science to request a free classroom license by email to classroom@jetbrains.com. Unfortunately, I can not add a research center to this repository, it is for colleges and universities only. I have to close this request without merging. Please reopen and comment with more details if I am mistaken. Thank you!

**Comment by rohitsuratekar** [comment]
It is deemed university under Tata Institute of Fundamental Research (TIFR) and Department of Atomic Energy (DAE), India. It is one of the premier institute in India with huge theoretical and computational biology research going on (https://theory.ncbs.res.in/). You can check scientific publications if you are not aware of work going on in this institute (https://theory.ncbs.res.in/content/publications). Also I can see many research institutes from India has been added to this repository which has overlapping research interests with NCBS (e.g. IISc, IITs etc).

**Comment by philipto** [comment]
@rohitsuratekar Thank you for the details! There is no doubt that National Centre for Biological Sciences is a recognized institution with plenty of scientific publications. It is absolutely clear that the Center makes important research in cutting-edge science and technologies.  The point is that the website of National Centre for Biological Sciences says that this is a research center, not a university. 

This repository lists universities and colleges only. The goal of this repository is to give students of the universities and colleges an easy way to request a free license for JetBrains tools. This is the sole purpose of the repository existence.

Any of National Centre for Biological Sciences professors can send an email to classroom@jetbrains.com and request free classroom licenses for JetBrains tools for his or her students. The difference between requesting licenses using this repository and requesting classroom licenses by email to classroom@jetbrains.com is that the teacher who requested classroom licenses, decides which students to grant them to.  This is a regular procedure for research and community institutions which have an educational department.

As for other research institutions which are listed in this repository, please let us know which of them are not universities or colleges. If their primary function is not an education, we'd have to remove them from this repository. If their primary function is education, they are in the repository on purpose.

I am opening this request and will appreciate your futher comments on the matter. Thank you!

**Comment by rohitsuratekar** [comment]
@philipto Thank you for your kind reply. However from our discussion over here, I think, there is difference in how you are defining college/university and how I understand. In that scenario, I can't point to any other institute which are not university or colleges. Finally it is your company and only it's terms and conditions will matter. I respect those terms and conditions. You can close this request.

One suggestion I would like to give to avoid the further disappointments for students (who thinks they are working in university and are eligible for this license) , please clarify what do you mean by university and college little bit more clearly on the README file. Thank you :)

**Comment by philipto** [comment]
@rohitsuratekar Thank you for your understanding and your suggestion. We'll try and make the terms and conditions clearer: you are right, they can be improved if even few people may misunderstand them. Please let us know if you have any difficulties in getting classroom licenses, if any of them arise. I'll try and help.

**Pull request closed without merging**
