### PR TITLE
Add Pitagoras (from the Kroton group)

### PR DESCRIPTION
**Pull request by campos20**
Website https://www.pitagoras.com.br/

### CODE REVIEW

**Comment by philipto** [comment]
@campos20 You wish to add the whole domain of Kroton group, and it's now unclear for us who exactly can have an email address there. It is quite possible that addresses in email domain kroton.com.br are available for many people, not only for teachers and students who study their long-term (> 1 year) IT-related course in Pitagoras University.

Please describe in more details who can use this email domain.

**Comment by philipto** [comment]
@campos20 You might miss my previous comment. Please react.

**Comment by campos20** [comment]
@kroton is for teacher and some internal workers, students does not have access to that domain.

**Comment by philipto** [comment]
@campos20 Pull request merged. 
Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of this Institute who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.
Thank you!

**Pull request merged**
