### PR TITLE
Added Saint-Louis - Châteaulin

### PR DESCRIPTION
**Pull request by romainOS**

### CODE REVIEW

**Comment by romainOS** [comment]
The school official website URL : https://www.saint-louis29.net/
An URL of a page on the official website where the school offers an IT-related long-term (>1 year) course : http://www2.saint-louis29.net/wp-content/uploads/2020/04/BTS2020-2021.pdf or https://www.saint-louis29.net/nos-formations/
You can see the contact email address that contains the domain name in the menu at the top of the site: https://www.saint-louis29.net/.

**Comment by philipto** [comment]
@romainOS I am sorry, the website lists a contact address at saint-louis29.net, not saint-louis29.fr. Are you sure that you wish to add saint-louis29.fr to this repository?

**Comment by romainOS** [comment]
@philipto No, student addresses end with @saint-louis29.net

**Comment by philipto** [comment]
@romainOS Thank you for the update! Pull request merged.

**Comment by romainOS** [comment]
Thx ^^

**Comment by romainOS** [comment]
@philipto When will saint-louis29.net addresses be available on JetBrains' website?

**Pull request merged**
