### PR TITLE
Liceo Scientifico Statale Alessandro Volta

### PR DESCRIPTION
**Pull request by gianlucapetito**

### CODE REVIEW

**Comment by zweizwei** [comment]
@gianlucapetito http://www.voltaweb.it/ seems to be a personal website - could you confirm with an appropriate document or link that this website also belongs to the school? thank you and sorry for the delay with my reply.

**Comment by gianlucapetito** [comment]
It’s not personal website.
What kind of documentation can I show you?
If you look at the “contacts” page (http://www.liceovolta.it/nuovo/index.php?option=com_content&view=article&id=54&Itemid=60 <http://www.liceovolta.it/nuovo/index.php?option=com_content&view=article&id=54&Itemid=60>) you can see the email address of my boss “dirigente@voltaweb.it <mailto:dirigente@voltaweb.it>”.
We have Google Apps for Education on voltaweb.it <http://voltaweb.it/>, we use it for emails…

Let me know. Thank you.

**Comment by philipto** [comment]
@gianlucapetito I am sorry for not recognizing your website as an official website of Liceo Volta, and thank you for the additional clarification. Actually, the problem is that the official website is at http://www.liceovolta.it, and the domain which you use for email is voltaweb.it. 

However, voltaweb.it domain is officially registered for the  Liceo Scientifico Statale A. Volta, thus this is not an issue.

The issue is that we failed to find an IT-related long-term (>1 year) educational course at your website. Could you please give is a link to description of such a course or other reference to IT-related education on your website? 

We are happy to merge the pull request as soon as you give us the link or other proof. Thank you!

**Comment by philipto** [comment]
@gianlucapetito  Could you please give is a link to description of IT-related long-term (>1 year) educational course or other reference to IT-related education on your website?

We are happy to merge the pull request as soon as you give us the link or other proof. Thank you!

**Comment by philipto** [comment]
@gianlucapetito I am very sorry but this PR remains not commented for a while. I close it without merging. Please reopen as soon as you have the information which we has requested. Your university can be added to this repository, but we clearly need the information prior to add it. Thank you for your understanding.

**Pull request closed without merging**
