### PR TITLE
Create ifa_delorozoy

### PR DESCRIPTION
**Pull request by RhinoBleu**

### CODE REVIEW

**Comment by RhinoBleu** [comment]
Create IFA Delorozoy.txt

**Comment by philipto** [comment]
@RhinoBleu I am sorry, but there are number of issues with your request:

1) If the domain which you meant is **ifa.delorozoy.fr** the file for it has to have path  `lib/domains/fr/delorozoy/ifa.txt` instead of `lib/domains/fr/ifa_delorozoy`. Please modify the path.

2) I did not find an info regarding college or university status of the institute on www.ifa.delorozoy.fr. If it does not offer long-term (>1 year long) IT-related courses to students, it is not eligible for inclusion to this repository. I understood that the institute relates to French Chamber of Commerce, and this is not enough to be recognized as a college or a university. Could you please give us more details on that issue?

3) If both abovementioned conditions are met, please provide us with a proof that the institute has a policy saying that students and teachers only use this email domain, not third party contractors, general stuff of the Chamber of Commerce, alumni, or other people not involved into educational process. An URL of the page where it is said is enough.

Thank you!

**Comment by RhinoBleu** [comment]
My courses is 2 years long, you can find information at : www.ifa.delorozoy.fr/formations/formation-initiale/chef-de-projet-en-informatique-et-robotique-cp-ir-parcours-robotique

Yes Delorozoy is relates to French Chamber of Commerce, but my courses is a partnership with an another school name's Imerir. (www.imerir.com/fr).

Administration staff use simple mail adresse as you can see here : http://www.cfa.uvsq.fr/les-equipes (you can IFA Delorozoy staff mail structure at, Sophie CICALA-SCHMITT).
Me as student, our mail look like this : jonh.smith@edu.ifa.delorozoy.fr
This structure of mail adresse is only use for students and teacher.

Thank you for your quick answer !
I hope, it corrects all my mistakes. I stay free for more information.

**Comment by philipto** [comment]
@RhinoBleu Thank you for the clarification! If the actual email domain is **edu.ifa.delorozoy.fr**, the file to represent this domain in the repository has to be `lib/domains/fr/delorozoy/ifa/edu.txt`. Please note that .txt extension is mandatory and it's **not** added automatically, you have to name the file correctly yourself. Please make the changes.

**Comment by RhinoBleu** [comment]
I've got this error when I try to modify my file to `lib/domains/fr/delorozoy/ifa/edu.txt` : Sorry, a file exists where you’re trying to create a subdirectory. Choose a new path and try again.
How can I do now ? Do I need to re-open a commit ?

**Comment by philipto** [comment]
@RhinoBleu Depending on how do you access GitHub (in a browser or via git command line tool), it can be different. I added the file for you, see #2055. Thus I close this request because it is already satisfied. Please reopen if something does not work with free subscription request. Thank you!

**Pull request closed without merging**
