### PR TITLE
Orbital Education Foundation, Nepal

### PR DESCRIPTION
**Pull request by dineshbajgain**

### CODE REVIEW

**Comment by philipto** [comment]
@dineshbajgain file/lib/domains/np/edu/orbital.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by dineshbajgain** [comment]
> @dineshbajgain file/lib/domains/np/edu/orbital.txt: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.

Updated

**Comment by philipto** [comment]
@dineshbajgain First stage of verification passed, official domain is [orbital.edu.np](https://orbital.edu.np) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@dineshbajgain Regrettably, this request has signs of fraud. I have to close it without merging.

**Pull request closed without merging**
