### PR TITLE
add 辽宁传媒学院

### PR DESCRIPTION
**Pull request by kpsanmao**
add 辽宁传媒学院

### CODE REVIEW

**Comment by philipto** [comment]
@kpsanmao The first verification stage is complete: the official domain for  **辽宁传媒学院** is [www.lncu.edu.cn](https://www.lncu.edu.cn), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.lncu.edu.cn/gjjyxy/22270.html

**Comment by kpsanmao** [comment]
Hello, "lncu.edu.cn" and "lncu.cn" both belong to Liaoning Communication University, because of the historical reason, the mailbox system of Liaoning Communication University uses lncu.cn domain name.

Visiting www.lncu.cn is now a 301 jump to www.lncu.edu.cn<http://www.lncu.edu.cn>.

The following documents are proof of domain ownership：

[cid:8203b548-4ce3-4b1c-b656-15abacd2e620]

[cid:81131ade-b182-4f7e-a175-c884c3dae05a]



________________________________
发件人: Philip Torchinsky ***@***.***>
发送时间: 2024年8月6日 20:23
收件人: JetBrains/swot ***@***.***>
抄送: kpsanmao ***@***.***>; Mention ***@***.***>
主题: Re: [JetBrains/swot] add 辽宁传媒学院 (PR #22299)


@kpsanmao<https://github.com/kpsanmao> The first verification stage is complete: the official domain for 辽宁传媒学院 is www.lncu.edu.cn<https://www.lncu.edu.cn>, to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.lncu.edu.cn/gjjyxy/22270.html

―

**Comment by kpsanmao** [comment]
Hello, "lncu.edu.cn" and "lncu.cn" both belong to Liaoning Communication University, because of the historical reason, the mailbox system of Liaoning Communication University uses lncu.cn domain name.

Visiting www.lncu.cn is now a 301 jump to [www.lncu.edu.cn](http://www.lncu.edu.cn/).

The following documents are proof of domain ownership：

domain
domain2

**Comment by philipto** [comment]
@kpsanmao The first verification stage is complete: the official domain for  **辽宁传媒学院** is [www.lncu.edu.cn](https://www.lncu.edu.cn), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.lncu.edu.cn/gjjyxy/22270.html

**Comment by philipto** [comment]
@kpsanmao Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by kpsanmao** [comment]
Thank you

**Pull request merged**
