### PR TITLE
Yusuf Maitama Sule University Kano Request

### PR DESCRIPTION
**Pull request by amumaruyumsuk**
I will like the students and staff of the Department of Computer Science in my University to benefit from your software development tools. 

The website of my university is www.yumsuk.edu.ng.

Email addresses have the following format: username@yumsuk.edu.ng.

I hope we will be considered for your free tools.

### CODE REVIEW

**Comment by philipto** [comment]
@amumaruyumsuk I am sorry. Your university official website has completely different URL.
I am sorry to tell you but regrettably this request has signs of fraud. I have to close it without merging. If you are a student of this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Comment by amumaruyumsuk** [comment]
Dear Mr.  Philip,

It's good to know from you that you have made some efforts to verify the
status of my university website. However,  I will like to debunk your
perception that it is a fraudulent site for the following reasons:

1. The name of the university was Northwest University Kano (www.nwu.edu.ng),
Nigeria and it was later changed to Yusuf Maitama Sule University Kano (
www.yumsuk.edu.ng).

2. We have been redirecting the new domain name to the old one to maintain
our systems integrity pending when all issues with our web applications
will be resolved and hence move it to the yumsuk.edu.ng domain.

3. Furthermore,  it is worthy to bring to your attention that domain names
ending with .edu.ng are only authorized for educational purposes in
Nigeria.

Hence,  It is on this note that I, Dr.  Abubakar Muhammad Umaru the
Director Management Information Systems (MIS)  of the University  request
that you reconsider  giving access to the staff and students  of the
Department of Computer Science an opportunity to benefit from your software
development tools.

Thank you.
Dr. Abubakar Muhammad Umaru
Director MIS

**Comment by philipto** [comment]
@amumaruyumsuk Thank you for your patience and persistency.

It was not easy to find a formal proof of the domain ownership, but finally here it is: https://scholar.google.com/citations?user=vNRi0BAAAAAJ&hl=en

The pull request merged. Please accept my apologies for the delay with the processing: the case was not obvious.

**Comment by amumaruyumsuk** [comment]
Thank you very much.

Dr. Abubakar Muhammad Umaru

**Pull request merged**
