### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jishnu-ramachandran**
File For Students Licence

### CODE REVIEW

**Comment by philipto** [comment]
@jishnu-ramachandran Please:
1) rename file/lib/domains/com/rvsgroup.txt to lib/domains/com/rvsgroup.txt 
2) provide us with (in a comment here):
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by jishnu-ramachandran** [comment]
@philipto 

1. The Official Website for Our College is http://www.rvsgroup.com/
2. The URL of a official website that offered an IT related longterm cource named MCA - Master Of Computer Applications is http://masterofcomputerapplication.rvscas.ac.in/
And i will rename the file name too

**Comment by philipto** [comment]
@jishnu-ramachandran Thank you for the clarification. Please rename the file in the request. It is now file/lib/domains/com/rvsgroup.txt. If your email pattern is username@rvsgroup.com, the filename has to be  lib/domains/com/rvsgroup.txt
Thank you!

**Comment by philipto** [comment]
@jishnu-ramachandran You might miss my previous comment. Please react.

**Comment by jishnu-ramachandran** [comment]
@philipto Ok. I will do that...

**Comment by philipto** [comment]
@jishnu-ramachandran I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
