### PR TITLE
school website: oasisacademyarena.org

### PR DESCRIPTION
**Pull request by kgraf80**
email domain: oasisarena.org

### CODE REVIEW

**Comment by dmpasa** [comment]
Add Universidade Franciscana
[ufn.txt](https://github.com/JetBrains/swot/files/5163813/ufn.txt)

**Comment by philipto** [comment]
@kgraf80 Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

@dmpasa Please submit a separate new pull request. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting the request.

**Comment by philipto** [comment]
@kgraf80 You might miss my previous comment. Please react.

**Comment by kgraf80** [comment]
@philipto school official website: https://www.oasisacademyarena.org/ and school useing domain oasisarena.org for email as you can see on contact subpage (https://www.oasisacademyarena.org/about-us/contact-us), for example: info@oasisarena.org but this school do not offer IT-related long-term course (at https://www.jetbrains.com/community/education/#students nothing is mentioned that the school must offer IT-related long-term course)

**Comment by philipto** [comment]
@kgraf80 Pull request merged. Thank you!
For high schools it's fine not to mention the IT-specific courses. Don't hesitate to ask for support if necessary: support@jetbrains.com.

**Pull request merged**
