### PR TITLE
acme.edu.np domain for acme engineering college

### PR DESCRIPTION
**Pull request by acmesamir**
acme.edu.np domain added for [Acme Engineering College](https://www.acme.edu.np/)
Official website: https://www.acme.edu.np/
Programs offered: [Bachelors in Computer Engineering, 4 Years](https://www.acme.edu.np/p/bachelor-in-computer-engineering-4-years-63)
Programs offered: [M.Sc. in Information System Engineering, 2 Years](https://www.acme.edu.np/p/m-sc-in-information-system-engineering-2-years-65)

### CODE REVIEW

**Comment by philipto** [comment]
@acmesamir First stage of verification passed, official domain is [acme.edu.np](https://acme.edu.np) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@acmesamir Please explain in more details the usage of different domains in the college. Please see #16110 for the reference: another domain was already approved for this college.

**Comment by acmesamir** [comment]
> @acmesamir Please explain in more details the usage of different domains in the college. Please see #16110 for the reference: another domain was already approved for this college.

#16110 [Acme College of Engineering](https://www.acmecollege.edu.np/) is a separate college which is located at Bagdol, Lalitpur, Nepal and runs diploma level programs. #16233 [Acme Engineering College](https://www.acme.edu.np/) is located at Sitapaila, Kathmandu, Nepal and runs Bachelor and Master level engineering programs.

**Comment by acmesamir** [comment]
Hi @philipto, is there still any issue for registering this domain? It'd be great if it is completed as soon as possible. Thanks.

**Comment by philipto** [comment]
@acmesamir Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Comment by acmesamir** [comment]
@philipto thanks.

**Pull request merged**
