### PR TITLE
Added the domain for students of LMC schools / high school group

### PR DESCRIPTION
**Pull request by DavidHofs**
The LMC group is a non profit organisation that supports a number of high schools in the Netherlands, Rotterdam area. Their website is at https://www.lmc-vo.nl/ . A list of schools is shown here: https://www.lmc-vo.nl/media/27751/lmc-scholen-2020-2021.jpg

### CODE REVIEW

**Comment by philipto** [comment]
@DavidHofs lib/domains/nl/lmc-vo.nl/student.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by DavidHofs** [comment]
I have added the .group at the bottom. I presume that was the problem?

**Comment by DavidHofs** [comment]
Thanks for that...

**Comment by philipto** [comment]
@DavidHofs Thank you for the update! Pull request merged.

**Pull request merged**
