### PR TITLE
Add SIT

### PR DESCRIPTION
**Pull request by ztaye3**

### CODE REVIEW

**Comment by philipto** [comment]
@ztaye3 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@ztaye3 You might miss my previous comment. Please react.

**Comment by ztaye3** [comment]
Dear Torchinsky,

I am requesting a letter from the university officials. I hope I will get
it today and come back to you.

**Comment by philipto** [comment]
@ztaye3 Thank you.

**Comment by ztaye3** [comment]
Dear Philip,

Here it's the official letter

**Comment by philipto** [comment]
@ztaye3 Thank you so much! Could you please attach it to your comment via browser at https://github.com/JetBrains/swot/pull/11851
GitHub strips out all email attachments.

**Comment by ztaye3** [comment]
> @ztaye3 Thank you so much! Could you please attach it to your comment via browser at #11851
> GitHub strips out all email attachments.

[BRN3C2AF420E8B0_007008(1).pdf](https://github.com/JetBrains/swot/files/6749060/BRN3C2AF420E8B0_007008.1.pdf)
Done!

**Comment by ztaye3** [comment]
Done!

**Comment by philipto** [comment]
@ztaye3 I am sorry, there is a kind of misunderstanding.

The document that you uploaded says that the students use the domain `sit.study`. Your request refers to a domain `sit.university`. They are two different domains. 

How many of the students need the free license? If there are just a few of them, it may be much faster to apply for a license with an official document at https://www.jetbrains.com/shop/eform/students instead of asking university officials to create a new correct signed letter. Please consider this option.

As for now, I have to close this request without merging due to lack of domain authenticity proofs.

image

**Pull request closed without merging**
