### PR TITLE
Added files through upload

### PR DESCRIPTION
**Pull request by VarinderBhatti29**

### CODE REVIEW

**Comment by philipto** [comment]
@VarinderBhatti29 Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@VarinderBhatti29 You might miss my previous comment. Please react.

**Comment by VarinderBhatti29** [comment]
School Website - https://www.steppingstoneschd.org
School Address- Stepping Stones Senior Secondary School,  Sector 37-D, Chandigarh, India
I don't think there is an URL where it states a course related to IT as this is a high school and I'm in my senior year studying science and math 
and for the proof of the email as a domain of the school, Our school has stopped using the email facility for that so is there any other way i can use it?

**Comment by philipto** [comment]
@VarinderBhatti29 Thank you for the clarification! Is there anything that confirms that students of the school use the email addresses ending with `@steppingstoneschd.onmicrosoft.com`? Did they give you an instruction to use this address?

**Comment by VarinderBhatti29** [comment]
WhatsApp Image 2021-08-25 at 2 26 22 PM
does this work?

**Comment by philipto** [comment]
@VarinderBhatti29 Thank you for the clarification. Pull request merged.

**Pull request merged**
