### PR TITLE
added SVKMMumbai

### PR DESCRIPTION
**Pull request by junaidgirkar**

### CODE REVIEW

**Comment by philipto** [comment]
@junaidgirkar Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@junaidgirkar You might miss my previous comment. Please react.

**Comment by junaidgirkar** [comment]
Hello,
Sorry for the late reply.

The school official website url : http://djsce.ac.in/

School address : No. U-15, J.V.P.D. Scheme, Bhaktivedanta Swami Rd,
Opp.Cooper Hospital, Vile Parle, Mumbai, Maharashtra 400056

Url of computer engineering program : https://djsce.ac.in/Computer/M__141

Proof:
1. For proof I am attaching a screenshot of the email where I was added to
college team by my professors.
2. My college DJ Sanghvi is a part of SVKM Mumbai. This can be easily
verified on google. I am attaching a screenshot of the same. The link for
this is : https://svkm.ac.in/
3. I am also attaching a picture of my College ID card

Really appreciate your help on this,

Regards,
Junaid Girkar

**Comment by philipto** [comment]
@junaidgirkar Thank you for the clarification. Pull request merged.

**Comment by junaidgirkar** [comment]
Thank you. Really appreciate it

**Pull request merged**
