### PR TITLE
Create um5s.net

### PR DESCRIPTION
**Pull request by lowdias**
Université Mohammed V - Souissi

### CODE REVIEW

**Comment by zweizwei** [comment]
@lowdias  the university's website is www.um5s.ac.ma/ - please somehow confirm that the provided domain also belongs to the university

**Comment by lowdias** [comment]
How?

2015-10-11 18:58 GMT+01:00 Elena Ganenkova <notifications@github.com>:

**Comment by zweizwei** [comment]
@lowdias any official mention of this domain in university documents or on university website, confirming that the domain is used for emails, should work

**Comment by zweizwei** [comment]
Closing the request till the answer comes

**Pull request closed without merging**
