### PR TITLE
add spec.txt school

### PR DESCRIPTION
**Pull request by cinhuei**
please re-check my added the school file。
I used the site(https://www.jetbrains.com/shop/eform/students/contributeUniversity) to generate the file。
The education organization's web site is https://www.spec.kh.edu.tw/.

Thks

### CODE REVIEW

**Comment by philipto** [comment]
@cinhuei First stage of verification passed, official domain is [kh.edu.tw](https://kh.edu.tw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by cinhuei** [comment]
I appreciate your help very much.

**Comment by philipto** [comment]
@cinhuei Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by cinhuei** [comment]
Thanks for your assistance.

**Pull request merged**
