### PR TITLE
Add CCI Formation 49

### PR DESCRIPTION
**Pull request by mflasquin**
https://www.cciformation49.fr/formation/bts-services-informatiques-aux-organisations-sio-option-sisr/

### CODE REVIEW

**Comment by philipto** [comment]
@mflasquin First stage of verification passed, official domain is [cciformation49.fr](https://cciformation49.fr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@mflasquin Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by philipto** [comment]
@mflasquin You might miss my previous comment. Please react.

**Comment by mflasquin** [comment]
Hi @philipto, sorry for the delay. The page is the folowing https://www.cciformation49.fr/formation/bts-services-informatiques-aux-organisations-sio-option-sisr/

**Comment by philipto** [comment]
@mflasquin Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
