### PR TITLE
Create ukfast.txt

### PR DESCRIPTION
**Pull request by JackRyder**
UKFast is my place of learning where i'm currently studying CS as an apprentice.

the university official website URL, if different from the domain you are submitting: ukfast.co.uk

an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university: They've removed it from their careers page because they're stopped taking on apprentices for now, but im here on a 3 year computer science and web development course

an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

I don't understand what you want here, sorry

### CODE REVIEW

**Comment by philipto** [comment]
@JackRyder I am really sorry, but the website you have provided us with is something completely different. I am copying this right now from their frontpage:

> WHY UKFAST
> 
> UKFast is one of the UK's leading managed hosting and colocation providers, supplying dedicated  server hosting, critical application hosting, and cloud hosting solutions. We fully own, manage and operate our ISO-accredited data centre complex, which offers over 30,000 sq ft of enterprise-grade facilities for colocating your IT equipment.

What it has in common with a university or a college?

**Comment by philipto** [comment]
@JackRyder Could you please comment in the issue above? If you can not update us on the problem, we'll have to close the request without merging. Thank you!

**Comment by philipto** [comment]
@JackRyder This request remains with no update from you for a while, I have to close it. Please reopen if you have the update. Thank you for your understanding.

**Comment by JackRyder** [comment]
Sorry didn't see this!

Hey, UKFast IS a hosting company, but they have a huge training side with awards for training ect, we're currently using PHPStorm for some educational projects, but we had to provide our student cards, this way would just be easier :)

**Comment by philipto** [comment]
@JackRyder Thank you for the clarification! We are really glad that you use PhpStorm and like it. 

Do I understand correctly that studentrs which study at UKFast get their student cards from UKFast? If not, they must study in other universities at the same time, mustn't they? Is UKFast registered as an educational institution in the UK? 

In case the company has a training department, the issue shall be considered by our sales team, we have a specific policy regarding training centers and benefits which JetBrains can provide them with.

**Comment by JackRyder** [comment]
We get our student cards through NUS :)

**Comment by philipto** [comment]
@JackRyder What does NUS stand for in this case? I know NUS which is National University of Singapore, and it is in this repository already, so you can use NUS emails if you have ones. Otherwise, I would advise to apply for either Classroom licenses by email to classroom@jetbrains.com, or licenses for training centers by email to sales@jetrbrains.com. The licenses for the training center may not be free, however, thus it's up to you to decide what is best way. We can not add a non-university and a non-college to this repository.

**Comment by JackRyder** [comment]
Hey! NUS stands for nation union of students, their website is here: http://www.nus.org.uk/

It's a card that is granted to authorised students and establishments, and our place is applicable for them so that's what we've been using as proof.

**Pull request closed without merging**
