### PR TITLE
Adding 2 schools

### PR DESCRIPTION
**Pull request by alexfelipe**
http://unifieo.br/ 
https://www.caelum.com.br/

### CODE REVIEW

**Comment by philipto** [comment]
@alexfelipe Please remove lib/domains/br/com/caelum.txt~ file from the request, it is clearly a temporary file, which must not be commited to this repository. Thank you!

**Comment by alexfelipe** [comment]
ready, ty.

**Comment by alexfelipe** [comment]
@philipto, now is ok?

**Comment by philipto** [comment]
@alexfelipe Thank you for the correction. It's a pity, two schools are quite different. CENTRO UNIVERSITÁRIO FIEO is, as far as I understand, a university. Caelum ensino e inovação is a training center, and it does provide short-term courses, not one-year-long or longer IT-related courses. 

Do I understand it correctly?

**Comment by alexfelipe** [comment]
@philipto exactly, this means that only the UNIFIEO will be considered?

**Comment by philipto** [comment]
@alexfelipe Yes, you are quite right. Could you please remove `lib/domains/br/com/caelum.txt` from your request?

**Comment by alexfelipe** [comment]
@philipto ready, ty :+1:

**Comment by philipto** [comment]
@alexfelipe Thank you. Pull request merged!

**Pull request merged**
