### PR TITLE
Create efficom-lille

### PR DESCRIPTION
**Pull request by vasilvestre**
This is my school, here the website : http://www.efficom-lille.fr/

### CODE REVIEW

**Comment by philipto** [comment]
@vasilvestre Please make two changes in your pull request:
1) For efficom-lille.fr domain correct path will be lib/domains/fr/efficom-lille.txt (.txt extension is mandatory)
2) An official name of the university seems to be Efficom Lille, not Efficom-Lille. Could you please check and use correct official name inside lib/domains/fr/efficom-lille.txt file?
Thank you!

**Comment by vasilvestre** [comment]
@philipto did i need to pull another request ? i dont find how to modify..

**Comment by philipto** [comment]
@vasilvestre Thank you! The pull request is merged.

**Comment by vasilvestre** [comment]
@philipto how many time before it's effective to get it for free ? this IDE is awesome to code.. i need it for my school

**Comment by philipto** [comment]
@vasilvestre we update our internal repository from this one frequently; I can not promise exact timing, but usually it takes about 10 minutes to update now. 

By the way, you can remove the file fr/efficom-lille.txt from your fork of this repository and submit the change in the new pull request, if we have to leave just com/efficom-lille.txt to reflect actual situation in your school. Thank you!

**Pull request merged**
