### PR TITLE
daffodil.txt

### PR DESCRIPTION
**Pull request by prokawsar**
@philipto Take a Look please

### CODE REVIEW

**Comment by prokawsar** [comment]
@philipto Take Look

**Comment by prokawsar** [comment]
@philipto Take a Look please

**Comment by philipto** [comment]
@prokawsar Could you please leave just one line in the file which you have submitted in this request;
Daffodil International Academy

You can put other information to a comment, it is not neccessary in the file. Thank you!

**Comment by prokawsar** [comment]
#### Instiution/School Website
http://daffodil.ac/

#### Institution Program link
http://daffodil.ac/admission/programmers/undergraduate/

**Pull request merged**
