### PR TITLE
Created file for all schools in Lahti, Finland

### PR DESCRIPTION
**Pull request by mmalaaksonen**
Emails look like: firstname.lastname@edu.lahti.fi

### CODE REVIEW

**Comment by zweizwei** [comment]
the domain redirects to https://peda.net/lahti - could you please somehow prove that the original domain is used for teachers / students emails?

**Comment by mmalaaksonen** [comment]
I can get the director of my school to verify that, do you need a signed
document or will a video interview with the director do?
The video would be just me asking if the domain belongs to the public
schools of Lahti.

Best regards, Markus Laaksonen.

**Comment by mmalaaksonen** [comment]
Well, the director wasn't able to prove it so I contacted the ICT staff and
got an answer. (sadly in Finnish)
I am going to translate the email(s) that are the proof that you requested.
Circled parts 1, 2 are the content I am translating.

1. "*Hello, *
*I elaborated on Esas message a little below.*
*Sanna Ahtiainen*
*Information Service Designer*"

2. "*I copied the message to the Information Service Designer, Sanna
Ahtiainen. She can complement my answer.*
*In short:*
*- @edu.lahti.fi <http://edu.lahti.fi> ID can only be accessed by basic
education students of the schools of the city of Lahti, high school
students of the schools of the city of Lahti or members of the Culture and
Education Department staff (excluding the staff of the city theater and
orchestra).*
*- IDs are only used by the previously stated groups of people*
*- IDs are created and deleted automatically by the student management
system of the city of Lahti to the previously stated groups of users.
Accounts are not created for outsiders*."

To clarify: members of the Culture and Education Department of Lahti are
teachers, social workers, city theater staff, city orchestra staff and
students.
So *in addition to students & teachers the @edu.lahti.fi
<http://edu.lahti.fi> ID is available to social workers. (I hope that is
ok)*

I translated the text quite quickly but it gets the point across.

Best regards, Markus Laaksonen.

----------------------------------------------------------------------------------------------------------------------------------

**Comment by zweizwei** [comment]
I think this should be fine - although theater and orchestra workers are not included by our policy, I can hardly imagine them using ide in business purposes :) adding the domain

**Pull request merged**
