### PR TITLE
Add CRAG from UAB

### PR DESCRIPTION
**Pull request by FerranLlobetC**
Add cragenomica.es which is the domain for the reserachers of CRAG in UAB a leading in centre in agricultural genomics where lots of Phd, Master and undergraduate stundents use bioinformatics and would fancy the acces to JetBrains tools

### CODE REVIEW

**Comment by philipto** [comment]
@FerranLlobetC Please provide us with the following information for each of the schools you have submitted:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you.

**Comment by FerranLlobetC** [comment]
**_UAB:_**

**Official URL:** https://www.uab.cat/web/universitat-autonoma-de-barcelona-1345467954774.html

**Adress:** Plaça Cívica, 08193 Bellaterra, Barcelona, Spain.

**URL of IT-related courses:** https://www.uab.cat/web/study/undergraduate/undergraduate-offer/all-bachelor-s-degrees-1345667078809.html

**Official domain:** https://www.uab.cat/web/serveis-dtic/correu-i-eines-de-col-laboracio-1345826750494.html?detid=1345844944092 _The webpage is in Catalan, my apologies. I couldn't find a version in English, nonetheless it will be easy to translate_

**Comment by FerranLlobetC** [comment]
_**CRAG:**_

**Official URL:** https://www.cragenomica.es/

**Adress:**  CRAG Building - Campus UAB, 08193 Bellaterra, Barcelona, Spain. 

**URL of IT-related courses:** I just want to point out that technically CRAG is not a university where courses are taught. However, it is a public research center with a strong focus in the application of genomics and bioinformatics which require coding on a daily basis. PhD students (and undergraduates doing internships) would benefit a lot of accessing more professional tools in their arduous research.  

**Official domain:** In the bottom of the previous URL you can see that the official mail to get information is info@**cragenomica.es**

**Comment by philipto** [comment]
@FerranLlobetC Thank you for your patience while waiting for a review and processing your request. Pull request merged.

Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of CRAG who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to [sales@jetbrains.com](mailto:sales@jetbrains.com).
Thank you!

**Pull request merged**
