### PR TITLE
request for triptrapschool.be

### PR DESCRIPTION
**Pull request by stijnhaezebrouck**

### CODE REVIEW

**Comment by philipto** [comment]
@stijnhaezebrouck I am sorry, the school website suggests that the school is a primary school, and JetBrains educational licenses are for high and higher schools only. If you have any high school students, please mention that in the comment. If you don't, I would suggest to use community versions of JetBrains tools, which are free for everyone.

**Comment by philipto** [comment]
@stijnhaezebrouck You might miss my previous comment. Please reply.

**Comment by stijnhaezebrouck** [comment]
Hello, as we do not have any high school students, we understand if you would deny our request. Thank you for your consideration.

**Comment by philipto** [comment]
@stijnhaezebrouck Thank you for the clarification. Yes, I now have to close the request because of the abovementioned rule. If you need a free license, however, for the teaching needs, or community version limits you from doing something significant for the educational process, please email classroom@jetbrains.com to get a free license. Our aim to provide everybody in education with what they need, not to install barriers. This repository is for universities and colleges emails only, other institutions may be eligible for free license too, but using a different channel. Thank you for the uniderstanding.

**Pull request closed without merging**
