### PR TITLE
Create mrl-spl.txt

### PR DESCRIPTION
**Pull request by AliPiry**
Create mrl-spl.txt

### CODE REVIEW

**Comment by philipto** [comment]
@AliPiry Pull request merged. Thank you!

**Comment by AliPiry** [comment]
It doesn't work because our domain hasn't 'ac' but you push it in 'ac'
folder!
If it possible change its path to previous folder, I mean 'ir' folder.
Thank you.

**Comment by AliPiry** [comment]
It doesn't work because our domain has not 'ac' but you pushed it in 'ac'
directory!
If it possible change its path to previous directory, I mean 'ir' directory.
Thank you.

**Comment by philipto** [comment]
@AliPiry Excuse me, I pushed it exactly where you put it. We don't change the file path as we wish, we merge pull requests as they are. The address which you submitted was valid, the website with such an address exists, and it's your job to check if you submit a domain which you have an email address in.

You can check the "files changes" tab of your request and see lib/domains/ir/ac/mrl-spl.txt there.

If your email address is in fact @mrl-spl.ir, please submit a new request with a file path lib/domains/ir/mrl-spl.txt. 

Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with correct information. Thank you for the understanding!

**Comment by AliPiry** [comment]
OK, I'm sorry about my mistake. I'll create a new file.
Thank you.

On Mon, Oct 16, 2017 at 9:20 AM, Philip Torchinsky <notifications@github.com

**Pull request merged**
