### PR TITLE
Create eleve-irup.txt

### PR DESCRIPTION
**Pull request by JavaImplements**
[Irup Ecole](https://www.irup.com/)

### CODE REVIEW

**Comment by JavaImplements** [comment]
Site : https://www.irup.com/
Email : BTSS22PBALEY@eleve-irup.com

**Comment by JavaImplements** [comment]
@philipto

**Comment by philipto** [comment]
@JavaImplements Thank you for the info. However I asked you to provide proves confirming that the school recognizes the domain eleve-irup.com as the official domain for the students. It means that I need to see this info in some independent trusted sources, such as:
*    A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
*    An URL of a page at the official school website that says that students use this email domain
*    A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
*    A WHOIS data that link the email domain to the school somehow
*    A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
*    Anything else that can prove this fact in similar way, i.e. can be verified independently.

If you cannot provide such a source, please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

If you cannot provide the source, I have to close the request without merging.

Thank you for the understanding!

**Comment by philipto** [comment]
@JavaImplements I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
