### PR TITLE
Add alias for Unisa email addresses

### PR DESCRIPTION
**Pull request by chris-steenkamp**
Unisa email addresses can be either student_no@mylife.unisa.ac.za or student_name@mylifeunisaac.onmicrosoft.com

### CODE REVIEW

**Comment by philipto** [comment]
@chris-steenkamp Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by chris-steenkamp** [comment]
University website: https://www.unisa.ac.za/
Login to student specific portion: https://www.unisa.ac.za/sites/myunisa/default/
University email account being used:
unisa-email

**Comment by philipto** [comment]
@chris-steenkamp I am sorry, but the screenshot provided does not contain any easy-to-understand signs that mylifeunisaac.onmicrosoft.com belongs to this university. If you google mylifeunisaac.onmicrosoft.com, you find plenty of claims that this domain has been used in spam messaging in the past.
Could you please provide us with clearer proof that the domain belongs to the university? It can be an instruction which the university sends to the students, or something like that.
Thank you.

**Comment by chris-steenkamp** [comment]
In the below image (taken from the university's Azure Portal page) you can see that the university uses email addresses with domains being either mylife.unisa.ac.za (which is already registered at [JetBrains/swot](https://github.com/JetBrains/swot/blob/master/lib/domains/za/ac/unisa/mylife.txt)), unisa.ac.za, and mylifeunisaac.onmicrosoft.com

unisa-email-additional-proof

**Comment by philipto** [comment]
@chris-steenkamp Thank you for the clarification. Pull request merged.

**Pull request merged**
