### PR TITLE
Add Kiev collage of communications

### PR DESCRIPTION
**Pull request by butsasha**

### CODE REVIEW

**Comment by philipto** [comment]
@butsasha Pull request merged. Thank you!

**Comment by butsasha** [comment]
@philipto thank you!

**Comment by butsasha** [comment]
@philipto but why i still see ```Your email address does not belong to any university that we know. Contribute your university to our list.```

**Comment by philipto** [comment]
@butsasha it takes about half an hour for the changes to propagate through our system. Please try again now.

**Comment by butsasha** [comment]
Yeah, already got license, thx

пт, 3 авг. 2018 г., 14:10 Philip Torchinsky <notifications@github.com>:

**Pull request merged**
