### PR TITLE
Kisii university

### PR DESCRIPTION
**Pull request by Ochieng424**

### CODE REVIEW

**Comment by philipto** [comment]
@Ochieng424 First stage of verification passed, official domain is [kisiiuniversity.ac.ke](https://kisiiuniversity.ac.ke) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Ochieng424 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by Ochieng424** [comment]
@philipto https://elearning.kisiiuniversity.ac.ke/course/index.php?categoryid=10

**Comment by philipto** [comment]
@Ochieng424  Thank you for the clarifications. Pull request merged.

**Pull request merged**
