### PR TITLE
National Academy of Internal Affairs

### PR DESCRIPTION
**Pull request by dzhanaev**
Національна академія внутрішніх справ
National Academy of Internal Affairs

### CODE REVIEW

**Comment by dzhanaev** [comment]
naiau.kiev.ua

**Comment by philipto** [comment]
@dzhanaev Naiu: Your request has an incorrect file path format, please ensure the request follows     the repository rules set out at the bottom of [this page](https://github.com/JetBrains/swot) and change     it accordingly or start a new one.     If you are unable to make a pull request with the instructions provided, please send an email to support@jetbrains.com mentioning the URL of this request in the message.

**Comment by philipto** [comment]
@dzhanaev Naiu: Your request has an incorrect file path format, please ensure the request follows     the repository rules set out at the bottom of [this page](https://github.com/JetBrains/swot) and change     it accordingly or start a new one.     If you are unable to make a pull request with the instructions provided, please send an email to support@jetbrains.com mentioning the URL of this request in the message.

**Comment by philipto** [comment]
@dzhanaev Naiu: Your request has an incorrect file path format, please ensure the request follows     the repository rules set out at the bottom of [this page](https://github.com/JetBrains/swot) and change     it accordingly or start a new one.     If you are unable to make a pull request with the instructions provided, please send an email to support@jetbrains.com mentioning the URL of this request in the message.

**Comment by philipto** [comment]
@dzhanaev Naiu: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@dzhanaev Naiu: Your request has an incorrect file path format, please ensure the request follows     the repository rules set out at the bottom of [this page](https://github.com/JetBrains/swot) and change     it accordingly or start a new one.     If you are unable to make a pull request with the instructions provided, please send an email to support@jetbrains.com mentioning the URL of this request in the message.

**Comment by philipto** [comment]
@dzhanaev Naiu: Your request has an incorrect file path format, please ensure the request follows     the repository rules set out at the bottom of [this page](https://github.com/JetBrains/swot) and change     it accordingly or start a new one.     If you are unable to make a pull request with the instructions provided, please send an email to support@jetbrains.com mentioning the URL of this request in the message.

**Comment by philipto** [comment]
@dzhanaev Naiu: Your request has an incorrect file path format, please ensure the request follows     the repository rules set out at the bottom of [this page](https://github.com/JetBrains/swot) and change     it accordingly or start a new one.     If you are unable to make a pull request with the instructions provided, please send an email to support@jetbrains.com mentioning the URL of this request in the message.

**Comment by philipto** [comment]
@dzhanaev Naiu: Your request has an incorrect file path format, please ensure the request follows     the repository rules set out at the bottom of [this page](https://github.com/JetBrains/swot) and change     it accordingly or start a new one.     If you are unable to make a pull request with the instructions provided, please send an email to support@jetbrains.com mentioning the URL of this request in the message.

**Comment by philipto** [comment]
@dzhanaev I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. 

If you make a new request, please notice that if the students of this school have email addresses like useername@naiau.kiev.ua, the filename in your request has to be lib/domains/ua/kiev/naiau.txt.

Thank you for the understanding!

**Pull request closed without merging**
