### PR TITLE
Add prof.educacao.sp.gov.br and al.educacao.sp.gov.br domains

### PR DESCRIPTION
**Pull request by rogeriodeandradepires**
Official Website:
https://www.educacao.sp.gov.br/

URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university:
https://inova.educacao.sp.gov.br/
https://inova.educacao.sp.gov.br/tecnologia-e-inovacao/

### CODE REVIEW

**Comment by philipto** [comment]
@rogeriodeandradepires Please clarify how many high and higher schools use this email domain. Thank you.

**Comment by rogeriodeandradepires** [comment]
Hi, @philipto.
The "al" subdomain is supposed to be used by the entire State Education network high and higher students, which comprehends about 4 million students.
Meanwhile the "prof" subdomain is supposed to be used by about 206 thousand teachers.
Thank you.

**Comment by philipto** [comment]
@rogeriodeandradepires Could you please advise who I can contact in Brazil State Education network administration to discuss making free JetBrains tools license available for all who have an account in this domain? I wish to reach someone from the officials prior to add this domain to the repository.

**Comment by rogeriodeandradepires** [comment]
Hi, @philipto .
Actually it's only about São Paulo State network. But this procedure needs to be forwared to the regional directorate, first. Then, the official in charge, Priscila de Lourdes Barrionuevo would send the discussion to the official from the State Secretariate of Education, if she finds the request valid.
But the contacts are:
From the regional (Administrative): 
debir@educacao.sp.gov.br

From the officials (Information, Technology, Evidence and Enrollment Coordinator):
marcos.barros@educacao.sp.gov.br

**Comment by philipto** [comment]
@rogeriodeandradepires I contacted few weeks ago the people from the Educational Network by email that you suggested. Regrettably, none of them answered. Feel free to reply to the email because you were copied there. I am now have to close this request without merging. 

Please feel free to continue the communication by email. I hope we can move this forward. 

Shall you need any further support with regard to this request, please send an email to community-support@jetbrains.com and mention the request by the URL: https://github.com/JetBrains/swot/pull/11311. 

Thank you.

**Pull request closed without merging**
