### PR TITLE
Add my school to the JetBrains database

### PR DESCRIPTION
**Pull request by MichelePip**
School Website: https://smc.sa.edu.au

### CODE REVIEW

**Comment by philipto** [comment]
@MichelePip domains/au/edu/sa/smc.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by MichelePip** [comment]
> @MichelePip domains/au/edu/sa/smc.txt: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.

Hey, thanks for the reply.
I'm unsure what you mean by incorrect file format, can you please confirm? I have just checked the rules at the bottom of the page and I am still unsure.

**Comment by philipto** [comment]
@MichelePip It is now fine already :) I added "lib" at the beginning to the filepath. Pull request merged. Thank you!

**Comment by MichelePip** [comment]
Thanks!

**Comment by MichelePip** [comment]
Hey, just trying to apply now, and the E-Mail is still invalid, is there a delay between this?

**Pull request merged**
