### PR TITLE
Create vit-bund.txt

### PR DESCRIPTION
**Pull request by XLeukon**
As you can see at https://vit-bund.de/index.php/impressum it's the official website of this degree course.

### CODE REVIEW

**Comment by XLeukon** [comment]
http://www.fhbund.de/DE/01__Studieninteressierte/20__ZentralerLehrbereich__Fachbereiche/12__Studiengang__VI/studiengang__vi__node.html
http://www.zoll.de/DE/Der-Zoll/Struktur/BWZ/bwz_node.html
https://www.bmi.bund.de/SharedDocs/Kurzmeldungen/DE/2012/08/strg_verwaltungsinformatik.html

**Comment by philipto** [comment]
@XLeukon I am sorry, I failed to understand clearly what kind of educational institution VIT-Bund is. Could you please provide some info on that? Is this a university or a department within the university? Does it have distant learning along with in-class education? Who can own an email from this email domain - students and teachers only, or other people too? Thank you!

**Comment by XLeukon** [comment]
I'm sorry about the bad explanation.

The university is called "Hochschule des Bundes für öffentliche Verwaltung" (english: Federal University of Applied Administrative Sciences), website: http://www.fhbund.de
I'm a student of the bachelor degree course called "Verwaltungsinformatik" (english: administrative information systems). VIT is the short version of "**V**erwaltungs**I**nforma**T**ik" and "bund" means "Federal".
www.vit-bund.de is the official website of this degree course from the university. It's a 36 months in-class study. Only teachers and students get a vit-bund.de email adress.

Thanks in advance

**Comment by XLeukon** [comment]
Every student get a email adress by the matriculation, there is **no** other way to get one.

**Comment by philipto** [comment]
@XLeukon Thank you for the details. Pull request merged. The problem with merging was that the domain is registered not by the university, according whois data, however I managed to find a proper mentioning of the domain at the official university page. Now the problem is resolved.

**Pull request merged**
