### PR TITLE
Add SMK Maarif 5 Kotagajah

### PR DESCRIPTION
**Pull request by khoirulaksara**
https://dapo.kemdikbud.go.id/sekolah/F0150A4EF8E04C2B4F09
https://referensi.data.kemdikbud.go.id/tabs.php?npsn=69889006
https://sekolah.data.kemdikbud.go.id/index.php/Chome/profil/D47003DE-D29D-4A0A-8C30-3D20B73446BB

### CODE REVIEW

**Comment by philipto** [comment]
@khoirulaksara First stage of verification passed, official domain is [smkmaliga.sch.id](https://smkmaliga.sch.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@khoirulaksara Please provide us with an URL of a page on the official website ([smkmaliga.sch.id](https://smkmaliga.sch.id/)) where the school offers an IT-related long-term (>1 year) course. Alternatively, you can explain what is relationship between the school and the pages you have mentioned, specifically these ones:
https://dapo.kemdikbud.go.id/sekolah/F0150A4EF8E04C2B4F09
https://referensi.data.kemdikbud.go.id/tabs.php?npsn=69889006
https://sekolah.data.kemdikbud.go.id/index.php/Chome/profil/D47003DE-D29D-4A0A-8C30-3D20B73446BB

**Comment by khoirulaksara** [comment]
all pages are the same, it shows that our school (smkmaliga.sch.id) is officially a school institution authorized by the government.

**Comment by philipto** [comment]
@khoirulaksara  Thank you for the clarifications. Pull request merged.

**Comment by khoirulaksara** [comment]
Thank you very much

**Comment by khoirulaksara** [comment]
Thank you very much

**Pull request merged**
