### PR TITLE
Add mmhs.co.uk

### PR DESCRIPTION
**Pull request by OblivionNW**
The school removed it's exchange accounts (@mmhs.rochdale.sch.uk) which
were previously accepted and now instead use gmail (@mmhs.co.uk). Proof
of this change here
http://cloud.mmhs.co.uk/cloud-announcments/studentemailupdates

### CODE REVIEW

**Comment by zweizwei** [comment]
@OblivionNW thanks for the additional info. Please fix the path though - it should be uk/co/mmhs.txt

**Comment by OblivionNW** [comment]
@zweizwei I have fixed the path

**Comment by OblivionNW** [comment]
@zweizwei Is it possible to merge this?

**Comment by LordMarkaRagnos** [comment]
Yes. Someone get pull request for me.


Enviado pelo Outlook para Android


Sérgio Silva.



De: OblivionNW

Enviado: sábado, 12 de dezembro 13:50

Assunto: Re: [swot] Add mmhs.co.uk (#1386)

Para: JetBrains/swot



@zweizwei Is it possible to merge this?

**Comment by zweizwei** [comment]
@OblivionNW Sorry for the delay - we've been launching rebranding and I hadn't time to check the repo for a while. I'm adding the domain now.

**Comment by LordMarkaRagnos** [comment]
Yes, i grant youe User for this.


Enviado pelo Outlook para Android


Sérgio Silva.



De: OblivionNW

Enviado: sábado, 12 de dezembro 13:50

Assunto: Re: [swot] Add mmhs.co.uk (#1386)

Para: JetBrains/swot



@zweizwei Is it possible to merge this?

**Pull request merged**
