### PR TITLE
Create Fundação Oswaldo Cruz (Fiocruz)

### PR DESCRIPTION
**Pull request by michaelmeneses**
Add Brazilian Research Foundation in healthcare. It has teaching units throughout Brazil.

### CODE REVIEW

**Comment by zweizwei** [comment]
@michaelmeneses please excuse my delay with replying you. From what i see on Wikipedia https://en.wikipedia.org/wiki/Oswaldo_Cruz_Foundation the foundation is a research institution. Could you please provide a link to a relevant page, describing long-term (>1 year) IT-related courses that the institution provides. Thank you!

**Comment by michaelmeneses** [comment]
Hi,
Offer courses in http://www.ead.fiocruz.br/cursos and http://efg.brasilia.fiocruz.br.
Fiocruz has branch UNA-SUS project (http://unasus.net.br), offers free courses in http://unasus.net.br/cursos.

**Comment by philipto** [comment]
@michaelmeneses I am very sorry but it looks like your institutions **does not have** any course related to software development, computer engineering or something similar (@zweizwei called such courses "IT-related" above). This repository is for colleges and universities which offer courses somehow related to software development. It's because JetBrains uses this repository to grant free liceneses for JetBrains tools to students and teachers. If your institution has no courses in IT, you may wish to add your university domain to another repository, which keeps track of all universities, regardless of which courses they offer: https://github.com/leereilly/swot

**Comment by philipto** [comment]
@michaelmeneses I am closing this PR with no merging because as far as we were able to understand, your foundation aims to work in many fields, including education. If you think that some JetBrains tools are necessary for the education, please ask for a Classroom license by email to classroom@jetbrains.com. The classroom licenses are also free, but they are to be given to a particular professor, and then the professor emails license invitations to the students. It allows to give licenses to students only, not to much broader number of people in the Foundation who may or may not be students and teachers.

**Pull request closed without merging**
