### PR TITLE
Create det.txt (Public School)

### PR DESCRIPTION
**Pull request by EliRickard**
Added Tuggerah Lakes Secondary College

### CODE REVIEW

**Comment by EliRickard** [comment]
https://berkeleyva-h.schools.nsw.gov.au/

**Comment by philipto** [comment]
@EliRickard The first verification stage is complete: the official domain for  **Tuggerah Lakes Secondary College Berkeley Vale Campus** is [berkeleyva-h.schools.nsw.gov.au](https://berkeleyva-h.schools.nsw.gov.au), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://berkeleyva-h.schools.nsw.gov.au/

**Comment by EliRickard** [comment]
> @EliRickard The first verification stage is complete: the official domain for **Tuggerah Lakes Secondary College Berkeley Vale Campus** is [berkeleyva-h.schools.nsw.gov.au](https://berkeleyva-h.schools.nsw.gov.au), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://berkeleyva-h.schools.nsw.gov.au/

DET is the subdomain for the larger group of schools in the area. I can confirm the emails are @det.nsw.edu.au not berkeleyva-h.schools.nsw.gov.au 

You'll find this common in a lot of Australian schools


see sec.nsw.edu.au (another school in the area you have listed) who's official domain is https://www.stedwards.nsw.edu.au/

**Comment by EliRickard** [comment]
@philipto Sorry forgot to tag you with my update. Goodmorning :)

> > @EliRickard The first verification stage is complete: the official domain for **Tuggerah Lakes Secondary College Berkeley Vale Campus** is [berkeleyva-h.schools.nsw.gov.au](https://berkeleyva-h.schools.nsw.gov.au), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://berkeleyva-h.schools.nsw.gov.au/
> 
> DET is the subdomain for the larger group of schools in the area. I can confirm the emails are @det.nsw.edu.au not berkeleyva-h.schools.nsw.gov.au
> 
> You'll find this common in a lot of Australian schools
> 
> see sec.nsw.edu.au (another school in the area **JetBrains already approves and have listed**) who's official domain is https://www.stedwards.nsw.edu.au/

**Comment by EliRickard** [comment]
You can actually also see this email format on the school website. https://berkeleyva-h.schools.nsw.gov.au

The info email is in the header and uses the format.

**Comment by philipto** [comment]
@EliRickard Yes, you are quite right! This is exactly what the last part of my comment was about:
image

Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by EliRickard** [comment]
Thanks for your support!

**Pull request merged**
