### PR TITLE
Add TKA University

### PR DESCRIPTION
**Pull request by vuisme**
Add TKA University

### CODE REVIEW

**Comment by vuisme** [comment]
Create TKA highschool

**Comment by philipto** [comment]
@vuisme The domain registrant for **talentkidsacademy.edu.vn** is Nguyễn Thị Hoàng Quyên (Nguyen Thi Hoang Quyen). This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@vuisme The domain registrant for **tka.edu.vn** is TRẦN NGUYÊN VŨ (Tran Nguyen Vu). This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@vuisme Regrettably, this request has signs of fraud. I have to close it without merging.

It does not mean that something is wrong with the school. The issue is related to a combination of suspicious factors related to the domain itself.

Please enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

Also, if you need WebStorm and Rider for education, please notice that they are free for this purpose, effective October 2024: https://blog.jetbrains.com/blog/2024/10/24/webstorm-and-rider-are-now-free-for-non-commercial-use/

PyCharm Community Edition and IntelliJ IDEA Community are also completely free.

Thank you for your understanding!

**Pull request closed without merging**
