### PR TITLE
The Kunming University of China

### PR DESCRIPTION
**Pull request by zbeboy**
Hi, I'm a student,I hope our university can use your products.Thanks!!

### CODE REVIEW

**Comment by philipto** [comment]
@zbeboy Could you please tell us:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@zbeboy Could you please answer the question above? Thank you.

**Comment by zbeboy** [comment]
Yes,now I having ready some documents.Please give me some time.Thank you.

**Comment by zbeboy** [comment]
@philipto Hi,I'm sorry , I can't get support from school , but thank you.

**Comment by philipto** [comment]
@zbeboy If your email domain is kmust.edu.cn, i.e. your email is something like xxx@kmust.edu.cn, I can add this domain to this repository. You need to create the request with a file name lib/domains/cn/edu/kmust.txt. After I merge the request, all students in your school who have the email address in kmust.edu.cn domain, will be able to request their free licenses at https://jetbrains.com/student. Please tell me if it is what you want. Thank you!

**Comment by zbeboy** [comment]
@philipto En, Our school is new since 2010s . And now It has not school email domain or email system. So we have not email address from school. But I made a project ISY(is free to help student or teacher work) , the email is @zbeboy.top and doamin is https://www.zbeboy.top, unfortunately, this email domain can't make all students use(100 peoples can be use).  Although my teacher encourage me  and she will provide some supporting papers or documentary evidence, I don't think this will be good. The school websit is http://city.kmust.edu.cn/GXGLPT/MHWZ/MHWQTGL/Indexlist.do  .

**Comment by philipto** [comment]
@zbeboy if you make an opensource project, you can ask for a free license for JetBrains tools as an open source developer at https://www.jetbrains.com/support/community/#section=open-source

Unfortunately, I can not add your project email domain to this repository, because ISY is not a university or a college. If you wish to add kmust.edu.cn, please create new request with a file name lib/domains/cn/edu/kmust.txt.  I am closing this request. If you have any comments, please reopen the request and comment. Thank you!

**Pull request closed without merging**
