### PR TITLE
Create primarygoal.txt

### PR DESCRIPTION
**Pull request by danouthwaite**
http://primarygoal.ac.uk/

### CODE REVIEW

**Comment by philipto** [comment]
@danouthwaite I am sorry, Primary Goal looks like a bit unusual school (but definitely useful for the community). Could you please confirm that you do have long-term courses (> 1 year), and you have a classroom(s) where you do conduct the courses? It is not clear from the website, and on the first glance your school looks more like as an initiative, not the educational institution. Thank you!

**Comment by danouthwaite** [comment]
Primary Goal is a registered educational institute in the United Kingdom. The academy is funded by the Skills Funding Agency. We have multiple classrooms and over 80 learners.
The learners work through a Microsoft Apprenticeship Framework with the opportunity to earn UCAS points towards a Degree. These courses can last between 12-18 months.
The academy is globally recognised and works with IT specialists such as the Tablet Academy, Microsoft and RM Education. The academy is supported by the government and the .ac.uk domain can be used as proof of this.

**Comment by danouthwaite** [comment]
@philipto

**Comment by philipto** [comment]
@danouthwaite Thank you for clarification. I am sorry that I was not clear for me from the website. While you are right saying that this school is a recognized educational institution, I don't feel quite certain that it can be recognized as a college or a university, which this repository are for. I looked carefully at the school profiles at https://www.linkedin.com/company/primary-goal-limited and https://beta.companieshouse.gov.uk/company/09655435/, and the school does not look like a college or a university indeed. 

I have no doubt that the school's students are eligible for a free licenses for JetBrains tools, but it seems to me that the scope of the institution suggests to use Classroom license instead of email-based student licenses. Could you please email to classroom@jetbrains.com and ask for as many student licenses as you need? 

This repository makes a lot of sense for quite large educational institutions, such as Cambridge or Oxford, and if your school has less in-classroom students, Classroom licenses will fit their needs better.

I have to close this request without merging. Please reopen it and comment if you have any trouble with getting Classroom licenses via classroom@jetbrains.com. Thank you for the understanding.

**Pull request closed without merging**
