### PR TITLE
add auceonline domain

### PR DESCRIPTION
**Pull request by hashbro14**

### CODE REVIEW

**Comment by philipto** [comment]
@hashbro14 Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by hashbro14** [comment]
> @hashbro14 Please provide us with:
> 
> * the school official website URL
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
This is the official link of the university, please check it out: https://auce.edu.lb/

**Comment by philipto** [comment]
@hashbro14 I am sorry, your reply does not contain any data but my question. Please reply with the response to the question.

**Comment by philipto** [comment]
@hashbro14 I checked out the link. The domain auceonline.com is not mentioned there anywhere. If I am mistaken please tell me exact URL where I can read that this university recognizes the domain auceonline.com that you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@hashbro14 I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue.

As for now, please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.
Thank you for the understanding!

**Comment by hashbro14** [comment]
Sorry I didn't come back to you earlier, was busy with a lot of stuff, preparing for exams. And yes that is the official website of AUCE, but really don't have any idea why they named their domain 'auceonline'. Well what I can say, welcome to Lebanon ... Sorry for any misunderstanding, but I am a student in this University and that is their domain name. Again sorry for any inconvenience...

**Comment by philipto** [comment]
@hashbro14 Thank you for the update! Please try and find any kind of proof: an instruction from the university to use this email address, a book published by the university with the author's email in this domain, anything. I need to see a connection between auce.edu.lb and auceonline.com. Thank you!

**Comment by philipto** [comment]
@hashbro14 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
