### PR TITLE
ADD SCHOOL

### PR DESCRIPTION
**Pull request by gusionmee**
ADD SCHOOL PLEASE
WEBSITE:[https://bachkhoahanoi.edu.vn/](url)

### CODE REVIEW

**Comment by philipto** [comment]
@gusionmee First stage of verification passed, official domain is [bachkhoahanoi.edu.vn](https://bachkhoahanoi.edu.vn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by b-a-d-g-e-r** [comment]
Full Time A Level Computer Science Course - at Bexhill College:
https://www.bexhillcollege.ac.uk/docs2/full_courses/EyFEEEkkZFoBgRpOQn.shtml

**Comment by nataershova** [comment]
Hi @gusionmee, 

Please provide us with:

- the school street address, including city and country
- a URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

I look forward to hearing from you.

**Comment by gusionmee** [comment]
website [https://bachkhoahanoi.edu.vn/](url)
Information Technology [https://bachkhoahanoi.edu.vn/tuyen-sinh-dao-tao/xet-tuyen-som-nganh-cong-nghe-thong-tin-tuong-lai-rong-mo/](url)
my email cd20cuongl410@bachkhoahanoi.edu.vn

**Comment by gusionmee** [comment]
website [https://bachkhoahanoi.edu.vn/](url)
Information Technology [https://bachkhoahanoi.edu.vn/tuyen-sinh-dao-tao/xet-tuyen-som-nganh-cong-nghe-thong-tin-tuong-lai-rong-mo/](url)
my email cd20cuongl410@bachkhoahanoi.edu.vn

**Comment by gusionmee** [comment]
@nataershova

**Pull request merged**
