### PR TITLE
Tohoku High School

### PR DESCRIPTION
**Pull request by Massyu612**
南光学園 東北高等学校 泉キャンパス

### CODE REVIEW

**Comment by philipto** [comment]
@Massyu612 Please provide us with:
* the school official website URL
* the school street address, including city and country
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@Massyu612 Thank you for your prompt reply!

Can you provide proof that **nankotohoku.onmicrosoft.com** is an official school email address for students? Take your time, and upload the necessary document to this request instead of emailing it as an attachment, since GitHub removes all email attachments.

You can provide us with any of the following as the proof:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by Massyu612** [comment]
E43C5903-4411-42F5-BF79-7C8948C6B349

Passwords and IDs are hidden

**Comment by philipto** [comment]
@Massyu612 You might miss my previous comment. Please react.

**Comment by Massyu612** [comment]
Cards containing names, email addresses, IDs and passwords for other services are distributed.I'm reluctant to publish it to GitHub.iPhoneから送信2023/03/18 13:35、Philip Torchinsky ***@***.***>のメール:﻿
@Massyu612 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@Massyu612 Please send us an email to community-support@jetbrains.com and mention the URL of this pull request there. You can attach any documents that cannot be exposed publicly there. Thank you.

**Comment by philipto** [comment]
@Massyu612 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
