### PR TITLE
Add mark Twain school

### PR DESCRIPTION
**Pull request by Arze1**

### CODE REVIEW

**Comment by philipto** [comment]
@Arze1 Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Arze1** [comment]
here you go @philipto
is239.schoolwires.com
proof: http://www.giphy.com/gifs/3o7btVg9hlSkSu1xCM
it is a intermediate school not a college so it is just year by year not courses

**Comment by Arze1** [comment]
oh my bad @philipto i have found real proof of site http://schools.nyc.gov/NR/rdonlyres/42382929-0577-42F0-A336-78641DFD5A4D/0/2017NYCMiddleSchoolDirectoryDistrict1.pdf on page 66 (control+f for "is239") you will see the official website

**Comment by philipto** [comment]
@Arze1 I am not sure that I got the idea of the proves you have submitted, however I found a proof which links the domain which you requested to add and the official school domain which corresponds to the website: http://is239.schoolwires.com/Domain/24. It's OK, and the pull request is merged. Thank you!

**Comment by Arze1** [comment]
Thanks a lot :)

**Pull request merged**
