### PR TITLE
Added Durham College (dcmail.ca) to Canadian Colleges.

### PR DESCRIPTION
**Pull request by ndbeals**
Durham College and UOIT (University of Ontario Institute of Technology) share a campus in on the North end of Oshawa, Ontario.

### CODE REVIEW

**Comment by zweizwei** [comment]
@ndbeals the extension should be .txt not .ca - please fix.

**Comment by ndbeals** [comment]
My apologies, not sure how I missed that. I've updated the pull request (apparently).

**Comment by zweizwei** [comment]
@ndbeals thanks, adding the domain

**Comment by ndbeals** [comment]
Thank you for the student developer tools!

**Pull request merged**
