### PR TITLE
Domains isissacilebrugnera.it and isissacilebrugnera.edu.it

### PR DESCRIPTION
**Pull request by picc09**
Istituto Statale Istruzione Superiore Sacile Brugnera

### CODE REVIEW

**Comment by philipto** [comment]
@picc09 Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain **_isissacilebrugnera.it_** as an official email domain for the students.

**Comment by philipto** [comment]
@picc09 You might miss my previous comment. Please react.

**Comment by picc09** [comment]
@philipto How do I provide the information?

- The official school website is https://www.isissacilebrugnera.edu.it
- [Here](https://www.isissacilebrugnera.edu.it/pvw/app/PNII0002/pvw_sito.php?sede_codice=PNII0002&page=2026075) there is the PDF `PTOF_isissacileebrugnera_2019_2022.pdf` with description of study courses.\
Page 2-3 describe "Sistemi Informativi Aziendali" with "Informatica" (italian for "computer science") for 3 years.
- Finally, if you check [here](https://whois.domaintools.com/isissacilebrugnera.it) you can verify the school is owner of the domain. There is no other public way to proof this. Is that enough?

**Comment by philipto** [comment]
@picc09 Thank you for the clarification. Yes, it is exactly what's necessary. Pull request merged.

**Pull request merged**
