### PR TITLE
TRƯỜNG ĐẠI HỌC SƯ PHẠM THỂ DỤC THỂ THAO HÀ NỘI

### PR DESCRIPTION
**Pull request by lasdc23**
Hanoi University Of Physical Education and Sports

### CODE REVIEW

**Comment by KiraBobyleva** [comment]
Hello @lasdc23,

Thanks for your pull request. Could you please provide us with a URL of a page on the official website where the school offers an IT-related long-term (>1 year) course?

Thanks!

**Comment by philipto** [comment]
@lasdc23 You might miss the comment above. Please reply.

**Comment by philipto** [comment]
@lasdc23 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@lasdc23 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
