### PR TITLE
Domain UTL

### PR DESCRIPTION
**Pull request by 14000662**
https://www.utleon.edu.mx/

Blvd. Universidad Tecnológica #225 Col. San Carlos
CP. 37670 León, Gto. Mex. l Tel (477) 7 10 00 20

### CODE REVIEW

**Comment by philipto** [comment]
@14000662 First stage of verification passed, official domain is [utleon.edu.mx](https://utleon.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@14000662 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by 14000662** [comment]
https://www.utleon.edu.mx/oferta-educativa-ing

**Comment by philipto** [comment]
@14000662  Thank you for the clarifications. Pull request merged.

**Pull request merged**
