### PR TITLE
create dachsberg.at

### PR DESCRIPTION
**Pull request by badgerhill**
see school homepage https://www.dachsberg.at/hp

### CODE REVIEW

**Comment by philipto** [comment]
@badgerhill Could you please give us a link to pages on the official website, which have the following information:
1) a course offered to the gymnasium stundents, which is long-term (> 1 year) and IT-related
2) a policy (or similar proof) saying that the gymnasium students have their emails in dachsberg.at domain.

Also, please change the gymnasium description in lib/domains/at/dachsberg.txt, it should be an official gymnasium name, such as "Gymnasium Dachsberg" or what the the official name is.

**Comment by badgerhill** [comment]
hi,
1.) this page shows the courses and  https://www.dachsberg.at/hp/?page_id=178#ORG and how many lesson per week the students have. It shows that students have at least two years of computer science - most of them have 4 years as it can be elected in the 7th and 8th form (Wahlpflichtgegenstände)
here you see some of the projects that were done https://www.dachsberg.at/hp/?cat=20

2.) i am the it- administrator of dachsberg.at and i can guarantee that only students and teachers have an email address with dachsberg.at. it's just myself who can add/delete new students/teachers.

thanks thomas

**Comment by badgerhill** [comment]
changed name in file to reflect official name

**Comment by philipto** [comment]
@badgerhill Thank you for the clarification! Pull request merged.

**Pull request merged**
