### PR TITLE
Create educem.txt

### PR DESCRIPTION
**Pull request by a-rsc**

### CODE REVIEW

**Comment by philipto** [comment]
@a-rsc Please provide us with a proof, which shows that the school recognizes the domain **educem.es** that you are submitting as an official email domain for the students.

**Comment by a-rsc** [comment]
> @a-rsc Please provide us with a proof, which shows that the school recognizes the domain **educem.es** that you are submitting as an official email domain for the students.

The school recognizes educem.es / educem.net / educem.com. And my school email is arodriguez2021@educem.net

**Comment by philipto** [comment]
@a-rsc Could you please tell me where at the official school website I can read that the school recognizes all of these three domains: educem.es / educem.net / educem.com? If they are not mentioned at the website, please upload an instruction which you have been given by the university. The instruction has to say "you are assigned with the address arodriguez2021@educem.net", or something like that.

I can add only those addresses to the repository that are confirmed by an official source similar to what I suggested above.

Thank you.

**Comment by philipto** [comment]
@a-rsc You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@a-rsc I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
