### PR TITLE
Create easternstudent.txt

### PR DESCRIPTION
**Pull request by Andrey-Yur**
https://www.easterncollege.ca/      College's official site Main Page
https://www.easterncollege.ca/programs-courses/technology/video-game-development/ 
https://www.easterncollege.ca/programs-courses/technology/it-systems-and-security-administrator/

### CODE REVIEW

**Comment by philipto** [comment]
@Andrey-Yur Please provide us with a proof, which shows that the school recognizes the domain easternstudent.ca that you are submitting as an official email domain for the students.

**Comment by Andrey-Yur** [comment]
https://eastern.lifecyclesystems.com/public/StudentWeb/ 
Untitled1
Untitled2

**Comment by Andrey-Yur** [comment]
Hi Philip

I’ve just pulled to the GitHub the screen scans of the login form and my account details.
Could be this back email a proof too?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by philipto** [comment]
@Andrey-Yur Thank you for the clarification. Pull request merged.

**Pull request merged**
