### PR TITLE
Create Poznan University Of Life Sciences

### PR DESCRIPTION
**Pull request by grzadr**
http://skylark.up.poznan.pl/en/

### CODE REVIEW

**Comment by philipto** [comment]
@grzadr Please rename lib/domains/pl/poznan/up to lib/domains/pl/poznan/up.txt
Thank you!

**Comment by grzadr** [comment]
Done!

**Comment by philipto** [comment]
@grzadr I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Comment by grzadr** [comment]
Thanks!

**Pull request merged**
