### PR TITLE
Adding LaSalle College Montreal

### PR DESCRIPTION
**Pull request by trojansam**
1. College URL - https://www.lasallecollege.com/
2. My Course URL(2 years) - https://www.lasallecollege.com/business-and-technologies-school/aec-computer-programmer-analyst
3. Parent institution URL - https://www.lcieducation.com/

### CODE REVIEW

**Comment by trojansam** [comment]
Please review my pull request @philipto

**Comment by philipto** [comment]
@trojansam Please provide us with a proof, which shows that the school recognizes the domain **lcieducation.net** you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by trojansam** [comment]
@philipto 

Here is the email which my institution sent me for my portal and all student activities. 

I am attaching the image of the email 

[email link for image](https://lcieducation-my.sharepoint.com/:b:/g/personal/samiuddin_syed_lcieducation_net/EdPskzBRNj9Jj_1SUVOo3AwBy8lBbwOjPpILR4UebpmMoQ?e=fxc7XQ)

if you want me to send the email to you please provide your email I will forward it to you!

**Comment by philipto** [comment]
@trojansam Thank you for the clarification. Pull request merged.

**Pull request merged**
