### PR TITLE
Added Sunway College

### PR DESCRIPTION
**Pull request by achyutkneupane**
URL: https://sunway.edu.np/
About Sunway: https://sunway.edu.np/about/
Contact Page: https://sunway.edu.np/contact/

Address: Behind Maitidevi Temple, Maitidevi, Kathmandu (https://goo.gl/maps/b6gfLGKm5JfdSm2T9)
College Email: info@sunway.edu.np
Contact Number: [977 01 4431725](tel:+977014423736),  [977 01 4431725](tel:+977014431725), [9823047066](tel:9823047066)

### CODE REVIEW

**Comment by philipto** [comment]
@achyutkneupane lib/domains/np/edu/sunway: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by achyutkneupane** [comment]
> @achyutkneupane lib/domains/np/edu/sunway: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.

Sorry for the mistake. Thank you for pointing it out. 
I have solved the format with the file.

**Comment by achyutkneupane** [comment]
@philipto

Here are the programs Sunway College is offering:
https://sunway.edu.np/program/bsc-hons-computer-and-data-science/
https://sunway.edu.np/program/ba-hons-marketing-digital-communication/

Both are 4 year-long courses.

**Comment by achyutkneupane** [comment]
> @achyutkneupane Thank you for clarifications and your patience while waiting for a review and processing your request. Pull request merged.

@philipto Thank you for the merge

**Pull request merged**
