### PR TITLE
Create uninabuco

### PR DESCRIPTION
**Pull request by RobsonFe**
Hello! 

## Mauricio de Nassau University (UNINASSAU) or University Center Nabucco (UNINABUCO) are the biggest university in the Northeast of the country in Brazil.

Both University are the same college.

- School Official Web : [https://www.uninassau.edu.br](https://www.uninassau.edu.br), [https://vestibular.uninassau.edu.br](https://vestibular.uninassau.edu.br) and [https://aluno.sereduc.com](https://aluno.sereduc.com).

- My College Enrollment: 01266993

- Name: Robson Ferreira da Silva
- Email: [01266993@sempreuninabuco.com.br](01266993@sempreuninabuco.com.br)

- College Addres: Av. Sen. Salgado Filho, s/n - Centro, Paulista - PE, 53401-440

- Part of site about the course [https://vestibular.uninassau.edu.br/curso/85/4700/3/cst-analise-e-desenvolvimento-de-sistemas/Paulista-PE](https://vestibular.uninassau.edu.br/curso/85/4700/3/cst-analise-e-desenvolvimento-de-sistemas/Paulista-PE) in Portuguese. 

# Some images 

- Some proves about my college.

## Ser Educacional Web Site with both. 
websiteOfficial

## My Login on web site 
websiteOfficial2

## My College Address 
localFaculdade

[Link to Google Maps](https://maps.app.goo.gl/EBBBH4t7wc4Pkz5UA)

Thank you in advance for considering my request.

Sincerely,
Robson Ferreira

### CODE REVIEW

**Comment by philipto** [comment]
@RobsonFe lib/domains/br/edu/uninabuco: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@RobsonFe Thank you for the extensive information you have provided! Do I understand correctly that you wish to add the domain @**uninabuco.edu.br** to this repository? There are a lot of different domains mentioned at the screenshots you attached. Thank you!

**Comment by philipto** [comment]
@RobsonFe You might miss my previous comment. Please react.

**Comment by RobsonFe** [comment]
Take it a look (Official Web Site)[https://www.sereducacional.com/]

**Pull request merged**
