### PR TITLE
Battambang Teacher Education College

### PR DESCRIPTION
**Pull request by bondethbtec**
Domain: www.btec.edu.kh

### CODE REVIEW

**Comment by philipto** [comment]
@bondethbtec First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/TEC.Battambang/posts/d41d8cd9/467626271570422/?locale=zh_CN

**Comment by philipto** [comment]
@bondethbtec Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by bondethbtec** [comment]
Dear JetBrains/swot,

Please see below for requested information:

1- Website URL: www.btec.edu.kh
2- Address: Street 211, Romchek 4 Village, Sangkat Ratanak, Battambang
City/Province, Cambodia.
3- https://btec.edu.kh/programs/faculty-science-education/ict-dept (we're
working adding the subjects into the page)

If you have further questions, please let me know.

Best regards.
Bondeth KHON



[image: photo]

Bondeth KHON
Education Staff | ICT Department, Battamang Teacher Education College

+855-78 607 760 <+855-78607760>  |  +855-68 607 760 <+855-68607760>  |
www.btec.edu.kh

***@***.***

Romchek 4 Village, Sangkat Ratanak, Battabang City/Province, Cambodia.
<https://maps.google.com/?q=Romchek%204%20Village,%20Sangkat%20Ratanak,%20Battabang%20City/Province,%20Cambodia.>

[image: facebook] <https://www.facebook.com/TEC.Battambang>

**Comment by philipto** [comment]
@bondethbtec First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/TEC.Battambang/?locale=ja_JP

**Comment by philipto** [comment]
@bondethbtec You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@bondethbtec I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
