### PR TITLE
Escuela publica del Gobierno Vasco en el Pais Vasco

### PR DESCRIPTION
**Pull request by juanbarrenal**
Escuela publica del Gobierno Vasco en el Pais Vasco

### CODE REVIEW

**Comment by philipto** [comment]
@juanbarrenal Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by juanbarrenal** [comment]
It is the public school of the Basque Country (province of Spain):
With the domain euskadi.eus:
http://www.euskadi.eus/informacion/estructura-y-organizacion-de-los-centros-configuracion-de-grupos-y-rpt-en-centros-publicos-de-secundaria-y-fp/web01-a2hlang/es/


If you access http://www.irakasle.eus it forwards you to https://www5.hezkuntza.net/appcont/control_acceso/irakaslegunea/index_cas.html
(hezkuntza y irakasle they are domains of education of the Basque Government)

In this url it explains that it is irakasle.net in eduación of the Basque Government:
https://elearning3.hezkuntza.net/013159/pluginfile.php/1755/mod_resource/content/1/DOKUMENTUAK/Irakasle.net._El_correo_electr_nico_del_profesorado.pdf

**Comment by juanbarrenal** [comment]
It is the public school of the Basque Country (province of Spain):
With the domain euskadi.eus:
http://www.euskadi.eus/informacion/estructura-y-organizacion-de-los-centros-configuracion-de-grupos-y-rpt-en-centros-publicos-de-secundaria-y-fp/web01-a2hlang/es/


If you access http://www.irakasle.eus it forwards you to https://www5.hezkuntza.net/appcont/control_acceso/irakaslegunea/index_cas.html
(hezkuntza y irakasle they are domains of education of the Basque Government)

In this url it explains that it is irakasle.net in eduación of the Basque Government:
https://elearning3.hezkuntza.net/013159/pluginfile.php/1755/mod_resource/content/1/DOKUMENTUAK/Irakasle.net._El_correo_electr_nico_del_profesorado.pdf

Do you need something else?
Sobre 11/04/2019 11:25:41, Philip Torchinsky <notifications@github.com> escribió:
@juanbarrenal [https://github.com/juanbarrenal] Please provide us with:
* the university official website URL, if different from the domain you are submitting
* an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
* an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@juanbarrenal Thank you for the clarification. Pull request merged.

**Pull request merged**
