### PR TITLE
Add Onaizah Private Colleges

### PR DESCRIPTION
**Pull request by Fahad411**
Create oc.txt please faster

### CODE REVIEW

**Comment by philipto** [comment]
@Fahad411 First stage of verification passed, official domain is [oc.edu.sa](https://oc.edu.sa) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Fahad411** [comment]
> @Fahad411 First stage of verification passed, official domain is [oc.edu.sa](https://oc.edu.sa) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

any update's ?

**Comment by s4cript** [comment]
I closed this by mistake

**Comment by s4cript** [comment]
please Open this request again

**Pull request closed without merging**
