### PR TITLE
Add iestplurin

### PR DESCRIPTION
**Pull request by eapaza1**

### CODE REVIEW

**Comment by philipto** [comment]
@eapaza1 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@eapaza1 You might miss my previous comment. Please react.

**Comment by eduar1-code** [comment]
URL: https://iestplurin.edu.pe/ ---pagina en construccion
Faccebook page: https://www.facebook.com/iestplurinOFICIAL/
Direccion: 1ra etapa Mz. k lote 15 AA. HH. villa alejandro lurin - lima -lima
flayer
[correo.pdf](https://github.com/user-attachments/files/16397798/correo.pdf)

**Comment by philipto** [comment]
@eapaza1 Thank you for your response and clarification. Unfortunately, we do not accept requests from schools when a website of a school is under construction. It prevents us from the request verification.

Also, this page says that the school has a completely different official website: https://www.gob.pe/iestplurin. I have to close the request without merging.

It does not necessarily mean that something is wrong with the school. 

If you are a student at this school, please enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

Thank you for your understanding!

**Pull request closed without merging**
