### PR TITLE
Request add for Conservatory of Music of Florence

### PR DESCRIPTION
**Pull request by flawerrr**
Master in Electronic Music and Multimedia Medium

### CODE REVIEW

**Comment by philipto** [comment]
@flawerrr First stage of verification passed, official domain is [consfi.it](https://consfi.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@flawerrr Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@flawerrr You might miss my previous comment. Please react.

**Comment by flawerrr** [comment]
@philipto Hi, sorry for the delay. 
https://www.consfi.it/corsi/musica-elettronica/

**Comment by philipto** [comment]
@flawerrr Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
