### PR TITLE
add facimp

### PR DESCRIPTION
**Pull request by agenteph**
Add facimp.edu.br new high school.

### CODE REVIEW

**Comment by philipto** [comment]
@agenteph Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by agenteph** [comment]
> @agenteph Please provide us with:
> 
> * the school official website URL
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

The school url is [www.facimp.edu.br](url)]
The url of offers a IT its [(https://www.wyden.com.br/facimp/cursos/graduacao/tecnologia#views-exposed-form-cursos-panel-pane-1)]

We have insert on the file ?

**Comment by philipto** [comment]
@agenteph Thank you for the details! Could you please explain what is wyden.com.br and how it relates to facimp.edu.br?

I am not sure that I understand your question:
> We have insert on the file ?

If you ask whether you can attach a file with a photo or scan of the document to your comment, then yes, you can do it via GitHub web interface. Just click on the line "Attach files..." which is below your comment field and attach the file.

**Comment by philipto** [comment]
@agenteph I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
