### PR TITLE
Add MS447

### PR DESCRIPTION
**Pull request by l-7777777**

### CODE REVIEW

**Comment by philipto** [comment]
@l-7777777 Please provide us with:
- the school full name (it is unlikely to be called officially just "MS447")
- the school official website URL
- the school street address, including the city and the country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by l-7777777** [comment]
The full name is The Math and Science Exploratory School.
The URL is ms447.org.
The address is 345 Dean St, Brooklyn, NY, NY, US 11217
It's a middle school, and so it doesn't have pages for specific courses. It does have a computer class, in which we are learning HTML.

**Comment by philipto** [comment]
@l-7777777 Thank you for the clarification. Pull request merged.

**Comment by l-7777777** [comment]
It still doesn't let me apply, do I have to wait?

**Comment by l-7777777** [comment]
image

**Comment by l-7777777** [comment]
Nevermind, I just had to wait a little while.

**Comment by philipto** [comment]
> 
@l-7777777 
 
> @philipto It still doesn't let me apply, do I have to wait?

Yes, you are quite right. Have a great coding time! :)

**Pull request merged**
