### PR TITLE
added university of the cumberlands

### PR DESCRIPTION
**Pull request by chintu2017**
Domain: https://www.ucumberlands.edu/
https://www.ucumberlands.edu/academics/graduate/programs/doctorate-philosophy-information-technology/accreditation

### CODE REVIEW

**Comment by philipto** [comment]
@chintu2017 You have requested to add a non-existent domain:
```
$ host ucumberlands.edu.us
Host ucumberlands.edu.us not found: 3(NXDOMAIN)
```
Did you mean ucumberlands.edu? If yes, let's rename lib/domains/us/edu/ucumberlands.txt to lib/domains/edu/ucumberlands.txt. Thank you!

**Comment by chintu2017** [comment]
@philipto Thanks for the information, i'll rename it.
And also i found out this message "Sorry, we had to truncate this directory to 1,000 files. 1,058 entries were omitted from the list" in this directory lib/domains/edu/ , Do you still accept a new entry for this directory?
https://github.com/JetBrains/swot/tree/master/lib/domains/edu

**Comment by chintu2017** [comment]
@philipto updated as per the comment. Thank you.

**Comment by philipto** [comment]
@chintu2017 Thank you for the update! Pull request merged.

**Pull request merged**
