### PR TITLE
Create sji.txt

### PR DESCRIPTION
**Pull request by wimglasseesjibe**

### CODE REVIEW

**Comment by zweizwei** [comment]
@wimglasseesjibe unfortunately i can't check the page http://prntscr.com/9ieddq - please somehow confirm that the domain committed belongs to educational institution. Thanks!

**Comment by wimglasseesjibe** [comment]
RU blacklisted? Interesting. I'll try to figure out why. In the meanwhile,
here's a screenshot of our webpage. Is this sufficient?

Thanks a lot for your help

**Comment by wimglasseesjibe** [comment]
And another one WITH the address bar in the picture

**Comment by wimglasseesjibe** [comment]
I noticed that the attachments don't get added to the github thread.

Here's a screenshot in the cloud:

http://prntscr.com/9maiq0

**Comment by wimglasseesjibe** [comment]
Don't mean to be pushy, but has anyone had the chance to have a look at
this yet?

Thanks in advance,

Wim

**Comment by philipto** [comment]
Pull request merged. We are sorry for the delay. Thank you for the update!
Philip

**Pull request merged**
