### PR TITLE
Added Novi Hogeschool second domain

### PR DESCRIPTION
**Pull request by nstuivenbergnovi**
Added Novi Hogeschool second domain

First domain is: novi-education.nl

**Website:** https://www.novi.nl/
**Software development course (undergraduate) in dutch:** https://www.novi.nl/software-development/

### CODE REVIEW

**Comment by philipto** [comment]
@nstuivenbergnovi Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by nstuivenbergnovi** [comment]
Hi @philipto ,

Thank you for your response. Would an e-mail from my @novi.nl be enough proof?

Kind regards,

Nick Stuivenberg
Hogeschool Novi teacher

**Comment by philipto** [comment]
@nstuivenbergnovi Yes, please. Send it to community-support@jetbrains.com. Thank you!

**Comment by philipto** [comment]
@nstuivenbergnovi Pull request merged. Thank you!

**Pull request merged**
