### PR TITLE
Add City, University of London

### PR DESCRIPTION
**Pull request by kccheung**

### CODE REVIEW

**Comment by philipto** [comment]
@kccheung Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by kccheung** [comment]
> @kccheung Please provide us with:
> 
> * the school official website URL
> * the school street address, including city and country
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Is that I provide the info here or through separate channel (like jetbrain email address)?

**Comment by philipto** [comment]
@kccheung Please comment here with the info I asked you about. If there is anything you cannot share publicly here, please send an email with the info to community-support@jetbrains.com. Thank you!

**Comment by kccheung** [comment]
I found that I provided a wrong email address.

**Pull request closed without merging**
