### PR TITLE
Create sv.txt

### PR DESCRIPTION
**Pull request by huynhthang9697**

### CODE REVIEW

**Comment by huynhthang9697** [comment]
Website: https://daihoclongan.edu.vn/

**Comment by philipto** [comment]
@huynhthang9697 Please provide us with an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by huynhthang9697** [comment]
Hi @philipto,
- The university official website URL: https://daihoclongan.edu.vn/
- IT course URL: https://tuyensinh.daihoclongan.edu.vn/dao-tao/44-khoa-hoc-may-tinh.html
- Proof mail domain is recognized by DLA: https://imgur.com/BmESGM3

**Comment by philipto** [comment]
@huynhthang9697 Pull request merged. 
Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. It is intended solely for individual use.
Thank you!

**Pull request merged**
