### PR TITLE
Add NIT, Tokyo College

### PR DESCRIPTION
**Pull request by wentmomori**
Please add the domain of National Institute of Technology, Tokyo College.

### CODE REVIEW

**Comment by philipto** [comment]
@wentmomori Could you please provide us with an official website address of the college where we can ensure that the domain belongs to the college and is used by students?

**Comment by wentmomori** [comment]
http://www.tokyo-ct.ac.jp/
This is National Institute of Technology,Tokyo College  official website.

National Institute of Technology has an agreement with Microsoft.
http://www.kosen-k.go.jp/news/news20091224-2.html
Thanks to that,We are using the domain of office365.

Already the same as National Institute of Technology, Fukushima College
and National Institute of Technology, Hachinohe College that have been added.

**Comment by wentmomori** [comment]
This collage is affiliated with the National Institude of Technology.
So, Whois Infomation is the same of Hachinohe Collage.

**Comment by philipto** [comment]
@wentmomori Thank you for the details! Pull request merged.

**Pull request merged**
