### PR TITLE
Create Stanislas Paris

### PR DESCRIPTION
**Pull request by Timo064**
https://www.stanislas.fr/
https://www.stanislas.fr/presentation-des-filieres-de-la-prepa-de-stanislas

### CODE REVIEW

**Comment by philipto** [comment]
@Timo064 lib/domains/fr/Stanislas: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Timo064 What is your school email address pattern? Is it username@stanislas.fr?

**Comment by Timo064** [comment]
Hello!
My school email address pattern is username@stanislas-paris.fr

**Comment by philipto** [comment]
@Timo064 lib/domains/fr/Stanislas: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Timo064 Thank you for the clarification. I corrected the request and merged it. Thank you. You can start requesting free licenses in an hour.

**Pull request merged**
