### PR TITLE
Include Kyunghee University global campus

### PR DESCRIPTION
**Pull request by koosco**
khu.ac.kr

Request a full request for use on Kyung Hee University's global campus.
The existing Kyung Hee University email is currently approved on swot and I don't know if that email domain is still used that was registered in the past, but the university is using khu.ac.kr domain.
So, I would like to request additional approval for that domain.

### CODE REVIEW

**Comment by philipto** [comment]
@koosco First stage of verification passed, official domain is [khu.ac.kr](https://khu.ac.kr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.khu.ac.kr/eng/sub/tab.do?MENU_SEQ=1000680

**Comment by philipto** [comment]
@koosco Your request contains a file that represents **khu.ac** domain, not **khu.ac.kr**. Please clarify:
1. What is "The existing Kyung Hee University email is currently approved on swot"?
2. What is the domain that you wish to add to this repository?

Thank you!

**Comment by koosco** [comment]
@philipto I think I made a mistake. domain is khu.ac.kr

1. The existing Kyung Hee university email domain is **kyunghee.ac.kr** and the path is **kr/ac/kyunghee.txt**
2. And the domain I wish to add is **khu.ac.kr**

Should I send a full request again?

Thank you

**Comment by philipto** [comment]
@koosco  Thank you for the clarifications. You don't need to submit a new request. I updated your pull request and merged it. Thank you!

**Pull request merged**
