### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by F-Stasi**

### CODE REVIEW

**Comment by philipto** [comment]
@F-Stasi Please provide us with:
* the school official website URL
* the school official name
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@F-Stasi You might miss my previous comment. Please react.

**Comment by F-Stasi** [comment]
Sorry @philipto, here is the information you required:

https://www.sekolahciputra.sch.id/
Sekolah Ciputra
Jl. Puri Widya Kencana, Surabaya, Indonesia
https://www.sekolahciputra.sch.id/wp-content/uploads/2023/05/DP-Handbook-2023-2024.pdf

The DP-Handbook-2023-2024 on pdf page 12 (or handbook 22) after Physics has Computer Science which I teach in Grades 11 and 12.

**Comment by philipto** [comment]
@F-Stasi Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
