### PR TITLE
Add bsg

### PR DESCRIPTION
**Pull request by Tiremisu**
Add bsg to JetBrains

### CODE REVIEW

**Comment by philipto** [comment]
@Tiremisu First stage of verification passed, official domain is [nordangliaeducation.com](https://nordangliaeducation.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.nordangliaeducation.com/bsg-guangzhou/contact-us

**Comment by philipto** [comment]
@Tiremisu You might miss my previous comment. Please react.

**Comment by Tiremisu** [comment]
@philipto Here is the info:

- the school official website URL -- bsg.org.cn

- the school street address, including city and country
The British School of Guangzhou- South Lake Campus
983-3 Tonghe Road
Baiyun District
Guangzhou 510515
China

- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
https://www.nordangliaeducation.com/cn/bsg-guangzhou/academic-excellence/curricula-guide/a-levels

- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
bsg

**Comment by philipto** [comment]
@Tiremisu Thank you very much for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
