### PR TITLE
Add Cowen Hamilton

### PR DESCRIPTION
**Pull request by deprecatedchris**

### CODE REVIEW

**Comment by philipto** [comment]
@deprecatedchris First stage of verification passed, official domain is [m.facebook.com](https://m.facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/NALISMorugaTT/posts/131276045167422/

**Comment by philipto** [comment]
@deprecatedchris Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by deprecatedchris** [comment]
School official website: https://cowenhamilton.edu.tt/
School address: 559 Moruga Road, Indian Walk ,Princes Town, 850842 ,Trinidad 
Url of long term IT course: https://cowenhamilton.edu.tt/Sciences-and-Mathematics.html (listed under sciences, teacher is Mr. Dhanraj Ramsingh). Proof that this teacher teaches IT: https://tt.linkedin.com/in/dhanraj-ramsingh-89982143
Email proof: https://pasteboard.co/xikyOqX1xG1C.png

**Comment by philipto** [comment]
@deprecatedchris First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/372457509502949/posts/dear-parents-and-pupils-of-form-1at-this-time-many-of-you-have-accessed-your-g-s/3439924826089520/

**Comment by philipto** [comment]
@deprecatedchris You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@deprecatedchris Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
