### PR TITLE
Added new school

### PR DESCRIPTION
**Pull request by gark6654**

### CODE REVIEW

**Comment by philipto** [comment]
@gark6654 First stage of verification passed, official domain is [tumo.org](https://tumo.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@gark6654 Could you please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course?

**Comment by gark6654** [comment]
> @gark6654 Could you please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course?

https://tumo.org/

**Comment by philipto** [comment]
@gark6654 Thank you. I feel I might not be clear enough with my question. TUMO seems to be a training center, not a college, nor a university. Therefore, if you don't have a year-long course, you need to apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses.

I don't see a description of the year-long course at the home page at https://tumo.org/

**Comment by gark6654** [comment]
> @gark6654 Thank you. I feel I might not be clear enough with my question. TUMO seems to be a training center, not a college, nor a university. Therefore, if you don't have a year-long course, you need to apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses.
> 
> I don't see a description of the year-long course at the home page at https://tumo.org/

ok thank you

**Pull request closed without merging**
