### PR TITLE
Added new domain for Liceo Leonardo da vinci casalecchio di reno , Bologna

### PR DESCRIPTION
**Pull request by MarcelloModica**
Added new domain for Liceo Leonardo da vinci casalecchio di reno , Bologna.
The Liceo changed domain for studens, now is 
@davinciliceo.edu.it

### CODE REVIEW

**Comment by philipto** [comment]
@MarcelloModica Thank you for the update. Could you please provide us with a link to the change official confirmation?

**Comment by philipto** [comment]
@MarcelloModica You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@MarcelloModica You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@MarcelloModica I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by MarcelloModica** [comment]
Philippe i made another pull request because i messed our message. Could you please merge it?
This is the new PR https://github.com/JetBrains/swot/pull/14100.

**Pull request closed without merging**
