### PR TITLE
Adding faculty of sciences of Tunis

### PR DESCRIPTION
**Pull request by kh3dr0n**

### CODE REVIEW

**Comment by philipto** [comment]
@kh3dr0n Please give us a link to the school official website and rename the file to have .txt entension, such as lib/domains/tn/utm/etudiant-fst.txt, if you wish to add @etudiant-fst.utm.tn email domain. Thank you!

**Comment by kh3dr0n** [comment]
@philipto the university official website : http://www.fst.rnu.tn

**Comment by philipto** [comment]
@kh3dr0n Thank you for the reuqest modification. I found the website at http://www.fst.rnu.tn, but I cannot find any info on using @etudiant-fst.utm.tn for students' email addresses. Please provide us with a link to some kind of official proof. Thank you.

**Comment by kh3dr0n** [comment]
@philipto  On site you will find nothing, the website is old and rarely updated.
But Faculty is under regional management department called UTM ( university Tunis Manar ) you can confirm that in faculty of the website.
Here is a post in the UTM official website about getting student email http://www.utm.rnu.tn/utm/fr/index.php?id=aff_act&id_actualite=505
If you open the first google form link you will see that email address end with @etudiant-UNVERCITY.utm.tn , given I'm student in FST the address will be @etudiant-fst.tn.
Thank you.

**Comment by philipto** [comment]
@kh3dr0n Thank you for the clarification! Pull request merged.

**Pull request merged**
