### PR TITLE
Create Kuben.txt

### PR DESCRIPTION
**Pull request by supergrecko**
Kuben Vidregående Skole in Norway is a secondary school in Oslo in Norway.

https://kuben.vgs.no/ (There's an english description if you scroll down a bit)

They provide a course in robotics in which the students do a bit of programming.

Info site about that here:
https://kuben.vgs.no/fagtilbud/yrkes--og-studiekompetanse-ysk/robotikklinja-nyhet/ (Norwegian)

### CODE REVIEW

**Comment by supergrecko** [comment]
The robotics course is a 3-year long course.

**Comment by supergrecko** [comment]
The email for students and teachers is @osloskolen.no

**Comment by philipto** [comment]
@supergrecko Thank you for the details. If the email address pattern is username@osloskolen.no, the filepath in the pull request has to be lib/domains/no/osloskolen.txt
Please rename the file.

**Comment by supergrecko** [comment]
Done

**Comment by philipto** [comment]
@supergrecko Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Pull request merged**
