### PR TITLE
School license file

### PR DESCRIPTION
**Pull request by nisalavira**

### CODE REVIEW

**Comment by philipto** [comment]
@nisalavira Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@nisalavira You might miss my previous comment. Please react.

**Comment by nisalavira** [comment]
Okay, I missed this

**Comment by philipto** [comment]
@nisalavira Yes, you did. Still, do you have any update? Please open the page at https://github.com/JetBrains/swot/pull/10780 and check if you have anything to answer. If not, I have to close the request without merging.

**Comment by philipto** [comment]
@nisalavira I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
