### PR TITLE
Create vitbstudent

### PR DESCRIPTION
**Pull request by itzshivam1999**
VIT University, Bangalore
VIT Bangalore
.group
The official website of VIT Bangalore: https://vitbangalore.in/

### CODE REVIEW

**Comment by philipto** [comment]
@itzshivam1999 lib/domains/in/vitbstudent: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@itzshivam1999 Please provide us with a proof, which shows that the school recognizes the domain **vitbstudent.in** that you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by itzshivam1999** [comment]
proof attached in this email

**Comment by itzshivam1999** [comment]
proof here ignore previous email

**Comment by itzshivam1999** [comment]
[Gmail - VITB Official Email ID and Password.pdf](https://github.com/user-attachments/files/17718921/Gmail.-.VITB.Official.Email.ID.and.Password.pdf)

**Comment by philipto** [comment]
@itzshivam1999 Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
