### PR TITLE
Add Hawthorn High School (Pontypridd, Wales, UK)

### PR DESCRIPTION
**Pull request by gitKaii**
Hi,

Just found out about this. My school's not on the list yet and would love to get it added. It's Hawthorn High School in Pontypridd (Wales, UK).

Thanks!
:shipit:

### CODE REVIEW

**Comment by philipto** [comment]
@SerenityYT Please provide us with:
- the school official website URL
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by SerenityYT** [comment]
@philipto Is there a way that I could send this to you privately?

**Comment by philipto** [comment]
@gitKaii Yes, absolutely. Please send an email to community-support@jetbrains.com with a subject "ATTN: Philip Torchinsky". Thank you.

**Comment by philipto** [comment]
@gitKaii I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
