### PR TITLE
Create us

### PR DESCRIPTION
**Pull request by tohirjanakhrarov**

### CODE REVIEW

**Comment by philipto** [comment]
@tohirjanakhrarov lib/domains/uz/us: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@tohirjanakhrarov lib/domains/uz/us: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by tohirjanakhrarov** [comment]
here JETBRAINS gave me this file can you add this file to gitlab?

вс, 23 февр. 2020 г. в 09:02, Philip Torchinsky <notifications@github.com>:

**Comment by philipto** [comment]
@tohirjanakhrarov lib/domains/uz/us: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@tohirjanakhrarov I am sorry, we did not find an educational organization with this name. As far as I understand, this domain does not belong to a university, nor to a college. I have to close the request without merging. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting a new request. 

If you have any questions or concerns, please email us to community-support@jetbrains.com.

**Pull request closed without merging**
