### PR TITLE
IISS Paciolo D'Annunzio School

### PR DESCRIPTION
**Pull request by Davoleo**

### CODE REVIEW

**Comment by Davoleo** [comment]
Should I create the file in school's e-mail domain or school's website domain?

**Comment by philipto** [comment]
@Davoleo For <last_name>.<first_name>@paciunzio.istruzioneer.it email address pattern the filename has to be lib/domains/it/istruzioneer/paciunzio.txt.

Also, as the email domain and the official website domain are different, please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Davoleo** [comment]
I looked for the proof of the e-mail domain in the site, but I can't seem to find it,
Should I ask it the school staff for it?

**Comment by philipto** [comment]
@Davoleo Yes, please. The proof also can be an article in a recognized journal, or a book which can be found via Google Books or Google Scholar, or the conference proceedings, where the email address is mentioned together with an affilation with the school.

**Comment by Davoleo** [comment]
I found them together in the school's communiques intestation
image

**Comment by Davoleo** [comment]
so is this good? @philipto

**Comment by philipto** [comment]
@Davoleo Yes, it is. Thank you. Pull request merged.

**Pull request merged**
