### PR TITLE
educagri.txt

### PR DESCRIPTION
**Pull request by votredsi**
Create file for educagri.fr

### CODE REVIEW

**Comment by philipto** [comment]
@votredsi Could you please tell us a bit more about this institution? It looks like a government agency, not a university or a college.

**Comment by votredsi** [comment]
We are a public school, we depend of French gouvernement. We have 2 years
after bacalaureat.

[image: photo]
*Sylvain FAVRE*
Votre DSI
+33.6.46.67.15.89 | s.favre@votre-dsi.fr | http://www.votre-dsi.fr | 17 rue
du Berry
<http://www.facebook.com/VotreDsi>  <http://fr.linkedin.com/in/sfavre>
<http://twitter.com/votre_dsi>

2016-07-22 12:09 GMT+02:00 Philip Torchinsky <notifications@github.com>:

**Comment by philipto** [comment]
@votredsi Could you please confirm somehow that Educagri is a university or a college? The website says that Educagri is a number of public educational institutions. In this case, it will be correct to add each of the institutuions to this repository, **not** Educagri itself.

"Ministère de l'agriculture, Enseignement public" means "Ministry of Agriculture, Public Education", and it does not clearly refer to a particular university or college. It refers to a type of activity, doesn't it? The website shows a big number of various institutions around France, which all somehow belong to public education in agricultire.

This repository contains universities and colleges only, not their unions or umbrella organizations. I am afraid that I cannot add this institution to the repository if you don't confirm that Educagri is a single school, not a union of many independent schools (which may have their own email domains).

**Comment by philipto** [comment]
@votredsi Given that this request remains unanswered for a while, could you please email to classroom@jetbrains.com in order to get a classroom license for the particular students, teachers, or courses who need the licenses now? It's also free. I have to close this request without merging because Educagri is not a university or a college indeed. I am sorry for the inconvenience. Thank you for your understanding!

**Pull request closed without merging**
