### PR TITLE
Create ofppt-edu.txt

### PR DESCRIPTION
**Pull request by MERZAK-X**
>Link to the organization and to the PDF proof from the official website

https://www.ofppt.ma/en/
https://www.ofppt.ma/sites/default/files/documents/formation_stagiaires.pdf

### CODE REVIEW

**Comment by philipto** [comment]
@MERZAK-X Thank you for making the request! Could you please tell me an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school. Thank you!

**Comment by MERZAK-X** [comment]
>@philipto read under "Organisation de formation" in the first link

https://www.ofppt.ma/index.php/fr/filieres-de-formations/techniques-de-developpement-informatique
https://www.ofppt.ma/index.php/en/branches/it-development-techniques

**Comment by philipto** [comment]
@MERZAK-X Thanks a lot for the clarification. Pull request merged.

**Comment by MERZAK-X** [comment]
>@philipto the pleasure is mine :D 

(I wanted to ask please, how/where can those domains be added as they benefice from the [GitHub Education pack](https://education.github.com/pack) ?

**Pull request merged**
