### PR TITLE
Added Far Eastern University Alabang

### PR DESCRIPTION
**Pull request by kazunya14**
### **-------Details-------**
**Official Name:** Far Eastern University

**Branch Name:** Far Eastern University Alabang / FEU Alabang 
-> This is the university I'm adding, it is under the official branch and it has a different domain Website: https://feualabang.edu.ph

**IT Related Courses Offered Link:** https://feualabang.edu.ph/academics/ccsma 
-> Courses take 4 years to complete with the exception of IT related courses which take 5 years to complete.

**Student Portal Link:** https://students.feualabang.edu.ph
-> This is the student portal link with the domain (I don't know if this serves as proof though)

Let me know if you have questions :)

**Screenshot:**
image

### CODE REVIEW

**Comment by kazunya14** [comment]
Upon checking with other PRs, I found out that what I posted wasn't proof at all haha... sorry folks 😥

**Comment by philipto** [comment]
@kazunya14 First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://ms-my.facebook.com/FEUAlabang/photos/a.1304249696289861/4317087285006072/

**Comment by kazunya14** [comment]
Hi @philipto, much appreciated
I would like to add that Far Eastern University uses different domain names for different usages/branches and it can get kind of confusing.
feualabang.edu.ph - This is for general use / unique to the Far Eastern University Alabang students
feucanvas.edu.ph - This is only for canvas / Microsoft 365
other branches use a different domain name as well:
feudiliman.edu.ph, feu.edu.ph, feutech.edu.ph, etc.

let me know if there's anything you'd like to know or if there's anything I can do to make the verification easier :)

**Comment by philipto** [comment]
@kazunya14  Thank you for the clarifications. Pull request merged.

**Pull request merged**
