### PR TITLE
Added The Graphic Design School

### PR DESCRIPTION
**Pull request by tjands**

### CODE REVIEW

**Comment by philipto** [comment]
@tjands Could you please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school.

**Comment by philipto** [comment]
@tjands You might miss my previous comment. Please react.

**Comment by tjands** [comment]
Hey @philipto, sorry I missed this response earlier.

Many of our students in our primary graphic design course https://www.thegraphicdesignschool.com/courses/graphic-design-courses, go on to do our 6 month web design course https://www.thegraphicdesignschool.com/courses/web-design-courses.

thanks :)

**Comment by philipto** [comment]
@tjands I am sorry for a delay with processing your request. The issue is that according to the repository rules, 
> Your pull request for adding a new email domain to the repository will be satisfied if all of the conditions below are met:
> 1. The domain is used by an educational institution, which offers at least one long-term course (one year or longer), and the course is somehow related to IT (it is in computer science, software engineering, statistics, bioinformatics, etc.)
> 2. The educational institution is a physical entity with student attendance and recognized as providing a learning curriculum for the educational system, or the institution is an accredited online educational organization providing their students with: (1) online courses with a curriculum at least one year long, (2) a dedicated email address which is provided to students only until their graduation.

Your school offers a 6-month course, which is not a long-term one. I have to close this request without merging. Please apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/buy/classroom/#commercial
Thank you for the understanding!

**Pull request closed without merging**
