### PR TITLE
Adding AuM to JetBrains educational institues

### PR DESCRIPTION
**Pull request by carlcamilleri**
Identifying AuM as an educational institute (https://aum.edu.mt/)

### CODE REVIEW

**Comment by philipto** [comment]
@carlcamilleri Please provide us with:
* the school full official name (**not an abbreviation**)
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by carlcamilleri** [comment]
@philipto  please find details below:
1. American University of Malta
2. https://aum.edu.mt/
3. Triq Dom Mintoff, Bormla, BML 1013, Malta 
4. Computer Science course: https://aum.edu.mt/programs/graduate-program/computer-science/
5. Would appreciate a clarification on what could be sufficient proof of this please? I have an @aum.edu.mt account if that helps?

Thank you

**Comment by philipto** [comment]
@carlcamilleri First stage of verification passed, official domain is [aum.edu.mt](https://aum.edu.mt) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@carlcamilleri Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
