### PR TITLE
Create academiadoprofessor.txt

### PR DESCRIPTION
**Pull request by lflima**

### CODE REVIEW

**Comment by lflima** [comment]
Please add this education academy

**Comment by philipto** [comment]
@lflima Could you please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school? Thank you!

**Comment by lflima** [comment]
Hello, they do not have courses that long. They are a teaching academy for teachers, and sometimes they have IT courses for IT teachers, but they are always short, a couple of weeks max.

**Comment by philipto** [comment]
@lflima Thank you for the clarification! In that case, I cannot add this school to this repository. Please take a look at the repository rules at the bottom of this page: https://github.com/JetBrains/swot/

I would suggest to the students to use free trial versions of JetBrains tools (which are good for at least 30 days, and you can ask for longer trial by email to sales@jetbrains.com if it's really necessary). If the school needs to install JetBrains tools for free on the school's lab computers, please email to classroom@jetbrains.com.

I have to close this request without merging. Thank you for the understanding. Feel free to reopen the request if you think that I misunderstood your request. Thank you!

**Pull request closed without merging**
