### PR TITLE
Add Toyo University

### PR DESCRIPTION
**Pull request by kazukioishi**

### CODE REVIEW

**Comment by philipto** [comment]
@kazukioishi Are you sure that the domain which you wish to add is toyo.jp, not toyo.ac.jp?  The domain toyo.jp is registered by Tojo-Kaikan Co.,Ltd., which is a commercial company, not the university.

**Comment by philipto** [comment]
@kazukioishi Please reopen and correct the request, if necessary, Thank you!

**Comment by kazukioishi** [comment]
@philipto 
Thank you for your reply. The domain I wish to add is toyo.jp not toyo.ac.jp.
Our university doesn't provide mail service on ac.jp domain.
I recheck the whois information of toyo.jp but it shows the registrant is "Toyo University".
```
Domain Information: [ドメイン情報]
[Domain Name]                   TOYO.JP

[登録者名]                      東洋大学
[Registrant]                    Toyo University

[Name Server]                   ns2.toyo.jp
[Name Server]                   naiobe.toyo.jp
[Name Server]                   ns2.toyo.ac.jp
[Name Server]                   naiobe.toyo.ac.jp
[Name Server]                   dns-x.sinet.ad.jp
[Signing Key]                   

[登録年月日]                    2001/03/26
[有効期限]                      2017/03/31
[状態]                          Active
[最終更新]                      2016/04/01 01:05:13 (JST)

Contact Information: [公開連絡窓口]
[名前]                          鈴木　浩充
[Name]                          Hiromitsu SUZUKI
[Email]                         netadmin@hakusrv.toyo.ac.jp
[Web Page]                       
[郵便番号]                      112-8606
[住所]                          東京都文京区白山５−２８−２０
[Postal Address]                Hakusan 5-28-20, Bunkyo, Tokyo, Japan
[電話番号]                      03-3945-7680
[FAX番号]                       
```

**Comment by philipto** [comment]
@kazukioishi You are right. I have been mistaken, thus I repoen the request and merge it. Thank you!

**Pull request merged**
