### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by JohnLikesCodes**

### CODE REVIEW

**Comment by philipto** [comment]
@JohnLikesCodes Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@JohnLikesCodes You might miss my previous comment. Please react.

**Comment by JohnLikesCodes** [comment]
*the school official website URL: *https://www.uwcsea.edu.sg/
*the school street address, including city and country:   *1 Tampines
Street 73, Singapore
*an URL of a page on the official website where the school offers an
IT-related long-term (>1 year) course: *
https://issuu.com/uwcsea/docs/1920-dover-east-ib-academic-subject-factsheet-7sep?fr=sM2MyZDI1MjY0MA.
Recognition of IB diploma Computer Science Course (2 years).
*a proof, which shows that the school recognizes the domain you are
submitting as an official email domain for the students: *I'm not too sure
how to prove this, but the name of the school is within the email domain.

**Comment by philipto** [comment]
@JohnLikesCodes Thank you for the clarification. Pull request merged.

**Pull request merged**
