### PR TITLE
Add Woodrush High School

### PR DESCRIPTION
**Pull request by aws281**
Added Woodrush High School to the repository.
School website: woodrushhigh.worcs.sch.uk (however the student email pattern follows studentname@woodrushhigh.email)

Course list: http://woodrushhigh.worcs.sch.uk/index.phtml?d=554632 (here you can see the BTECT ICT course listed.

Thanks!

### CODE REVIEW

**Comment by philipto** [comment]
@aws281 Could you please give us an URL at the school website where @woodrushhigh.email is mentioned as a school email? The official website contacts page gives another pattern: "Email: office@woodrushhigh.worcs.sch.uk", thus we need some proof. Thank you for the understanding!

**Comment by aws281** [comment]
Hi, thanks for your response.

The email patterns differ because the "real" domain is reserved for school staff and administration/contact addresses, whereas students use the @woodrushhigh.email domain.

Unfortunately I do not believe there is a page on the official website referencing the student email pattern, however I can provide an image of myself logged into my personal account. As you can see, the image shows the school's logo in the top-left hand corner, and you can see that I am logged in to an email being managed by woodrushhigh.email.

Image: http://m.imgur.com/YslHj4w

Thank you for understanding, if more proof is still needed before this can be merged, just say and I will happily find more evidence.

Thanks once again.

**Comment by philipto** [comment]
@aws281 Thank you for the clarification! This proof is enough. Pull request merged. Thank you!

**Comment by aws281** [comment]
Thanks, I really appreciate it!

**Pull request merged**
