### PR TITLE
Add files in domain for Aformac Limoges

### PR DESCRIPTION
**Pull request by Silv3rgr3g**

### CODE REVIEW

**Comment by philipto** [comment]
@Silv3rgr3g Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Silv3rgr3g You might miss my previous comment. Please react.

**Comment by Silv3rgr3g** [comment]
Hello! I answered by mail, sorry about that. 

I added some elements to my application and made another pull request. 
Hope it would be sufficient. 

Kind regards

**Comment by philipto** [comment]
@Silv3rgr3g Thank you for the clarification. There are two issues:
1) You say that 
> Our students aren't provided any email address by our group. They usually create a gmail address dedicated to the course. Only coaches are provided an email on aformac.fr domain.

If you do not have addresses like username@aformac-limoges.fr, why do you wish to add aformac-limoges.fr domain to this repository? Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting a request. 

You can apply for free license at jetbrains.com/shop/eform/students with your official student ID (please use tab "OFFICIAL DOCUMENT" for it). It is fine if you don't have an email provided by the university, but do have an account at gmail.com.

2) If you think that you need to add @aformac-limoges.fr to this repository, please explain why, and move the request clarification from the file to the comments here. The file in the repository has to contain just a university name.

Thank you!

**Comment by Silv3rgr3g** [comment]
Sorry for the misunderstanding i corrected the .txt to have just the domain and if i correctly understood your comment, then the domain to authorize should probably be aformac.fr.  

I'm not a student but a coach/teacher so i have an email for this domain which is g.fourmaux@aformac.fr. So i could ask a license if the domain is added. But what about my students? Can i share it with them? As they only use gmail addresses? 

Thanks again for your time

**Comment by Silv3rgr3g** [comment]
Ok i understand now, you wonder the point to add the domain aformac.fr if only coaches have addresses from that domain.
I agree it may not be the right way to do what i want to do then. 
I just wanted to be able to use your product with my students during the course which last less than a year but way more than the 30 days trial (8 months actually). 

Maybe there is another way to do that ?

**Comment by philipto** [comment]
@Silv3rgr3g Pull request merged. You can now request your free license. Please start requesting the licenses in about an hour, to let the changes to propagate through our system.

It's totally fine to use free educational license for JetBrains tools if you are a teacher. Please share a link to jetbrains.com/shop/eform/students with students, they can apply there for their free licenses. They have email in gmail.com domain, thus they can use OFFICIAL DOCUMENT tab at the request page, and submit their requests with a photo of their student ID. It takes a bit longer, but they are eligible for the free licenses and will get them as soon as possible.

Thank you!

**Pull request merged**
