### PR TITLE
Add Glenpool Public Schools

### PR DESCRIPTION
**Pull request by wright1703**
@philipto, I have removed file.zip. Sorry, I did not realize I had erroneously uploaded it to the repository as a whole, instead of adding its contents to the proper directory. This pull request should be correct.

### CODE REVIEW

**Comment by philipto** [comment]
@wright1703 First stage of verification passed, official domain is [glenpool.k12.ok.us](https://glenpool.k12.ok.us) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by wright1703** [comment]
Alright, thanks a ton.

**Comment by philipto** [comment]
@wright1703 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by wright1703** [comment]
No worries about the wait. Thank you for your help!

**Pull request merged**
