### PR TITLE
Create School Birklehof

### PR DESCRIPTION
**Pull request by KlaroYT**
Created school Birklehof file

### CODE REVIEW

**Comment by philipto** [comment]
@KlaroYT Please rename lib/domains/de/Birklehof to lib/domains/de/Birklehof.txt

**Comment by philipto** [comment]
@KlaroYT You might miss my previous comment. Please react.

**Comment by KlaroYT** [comment]
Sry, I missed your comment :(

**Comment by philipto** [comment]
@KlaroYT Pull request merged. Thank you!

**Pull request merged**
