### PR TITLE
Create rcdeveloper.txt

### PR DESCRIPTION
**Pull request by rahulchaudharydeveloper**

### CODE REVIEW

**Comment by rahulchaudharydeveloper** [comment]
Please Add

**Comment by philipto** [comment]
@rahulchaudharydeveloper Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by rahulchaudhary-research** [comment]
https://www.sce.org.in/

**Comment by philipto** [comment]
@rahulchaudharydeveloper I am sorry, you might misunderstand me. Please, consider the following:
1) There is no @rcdeveloper.onmicrosoft.com contacts mentioned at www.sce.org.in
2) You did not provide an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students
3) The University name which you wrote in the file in the request is "rcdeveloper", which is not the name of the university at https://www.sce.org.in

Please correct the issues I explained above. Otherwise, I have to close the request without merging. Thank you.

**Comment by philipto** [comment]
@rahulchaudharydeveloper I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
