### PR TITLE
added nusta.txt

### PR DESCRIPTION
**Pull request by ViktorBizbiz**

### CODE REVIEW

**Comment by philipto** [comment]
@ViktorBizbiz First stage of verification passed, official domain is [nusta.edu.ua](https://nusta.edu.ua) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by ViktorBizbiz** [comment]
@philipto I have a question. After the ending of verification, I will need just to write an email address of the university in the application to get a free access to the soft, isn't it?

**Comment by philipto** [comment]
Yes, at  https://www.jetbrains.com/shop/eform/students

Thank you!

**Comment by philipto** [comment]
@ViktorBizbiz Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
