### PR TITLE
Add IGIB

### PR DESCRIPTION
**Pull request by parashardhapola**
CSIR-IGIB is a public research institution which trains Graduate students in field of Genomics
http://www.igib.res.in/

### CODE REVIEW

**Comment by zweizwei** [comment]
as the university domain is www.igib.res.in please somehow prove that the provided domain also belongs to the university and is used for emails

**Comment by parashardhapola** [comment]
Domain igib.in is owned by IGIB. You can follow any of scientists' profile on this page(http://igib.res.in/?q=node/22) as see that igib.in domain being used by them for email. For example, my PhD supervisor's page (http://igib.res.in/?q=ShantanuChowdhury) shows his email address as shantanuc@igib.in 

You can also visit my lab webpage to confirm my affiliation to the institute: http://www.igib.res.in/sites/default/files/sclab/people.html 

I hope this will resolve the confusion.

**Comment by parashardhapola** [comment]
Some screenshots supporting my claim. Hope this will be good enough. 

pd
rsg
sc1

**Comment by parashardhapola** [comment]
Moreover I just found out that, my institute also uses this web address:

www.igib.in

I should have given this address earlier. Hope this settles any confusion related to domain names.

**Comment by zweizwei** [comment]
@parashardhapola thanks a lot for the thorough explanation, i'm adding the domain

**Comment by parashardhapola** [comment]
@zweizwei Thank you so much

**Pull request merged**
