### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AttaUlMustafa**

### CODE REVIEW

**Comment by AttaUlMustafa** [comment]
oxford college kamalia

**Comment by akram-Qbh** [comment]
Please add my institute .
[file.zip](https://github.com/JetBrains/swot/files/10562012/file.zip)
http://www.isetjb.rnu.tn/

**Comment by philipto** [comment]
@AttaUlMustafa Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@cicese-education Please make a separate pull request or send an email with your .zip file to community-support@jetbrains.com.

**Comment by philipto** [comment]
@akram-Qbh Please make a separate pull request or send an email with your .zip file to community-support@jetbrains.com.

**Comment by philipto** [comment]
@AttaUlMustafa You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@AttaUlMustafa I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
