### PR TITLE
Create ecccomp.txt

### PR DESCRIPTION
**Pull request by flysaki**
add ecccomp.com for ECC College of Computer & Multimedia (Japan)

### CODE REVIEW

**Comment by philipto** [comment]
@flysaki The official website says that this school uses an email domain of @ecc.ac.jp, not ecccomp.com. Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by flysaki** [comment]
image

**Comment by flysaki** [comment]
@philipto maybe @ecc.ac.jp is used by departments of school.

**Comment by philipto** [comment]
@flysaki Pull request merged. Thank you!

**Pull request merged**
