### PR TITLE
Add Campus Numerique In The Alps

### PR DESCRIPTION
**Pull request by AlpenYeti**
Campus Numerique In The Alps is a new French school for web developers based in Grenoble. If you need any additionnal information, feel free to ask me at josselin.perez@campus-numerique-in-the-alps.com !

### CODE REVIEW

**Comment by philipto** [comment]
@AlpenYeti Could you please provide us with the link to the official school's website?

**Comment by AlpenYeti** [comment]
As it is a new school (the first year began in September 2016), the official website has yet to be built (by some of us students) and will be hosted at http://campus-numerique-in-the-alps.com.

What I can already provide you is [this](http://digital-grenoble.com/2016/03/le-campus-numerique-in-the-alps/) (If any translation is needed, feel free !)

We are 31 students learning everything from the bases of web development like HTML5 and CSS3 to "higher" grounds like JS/JQuery, PHP with Laravel and Symfony, server management, Java, etc. The idea behind it all is to answer to the high demand in web developers in Grenoble, France 's area by teaching everything from scratch to people who are really motivated !

The strongest point in all this is that the students all have tight links with Grenoble IT/dev companies that are willing to hire them, guaranteeing them a job after the formation comes to an end.

**Comment by philipto** [comment]
@AlpenYeti I am sorry, processing your request requires a bit more time than usual because you don't have an official website yet, and your school is actually neither a university, nor a college. We'll back to you as soon as possible. Thank you for your patience!

**Comment by AlpenYeti** [comment]
@philipto OK thank you for answering so fast ! I'll look forward for further information.

**Comment by philipto** [comment]
@AlpenYeti Pull request merged. Please notice that the free licenses which JetBrains grants to students for free are for educational purpose only. Also, your students may wish to benefit from a graduation discount: when they graduated from your school, they are eligible for 25% discount for their next year subscription for JetBrains tools. Feel free to contact sales@jetbrains.com for details. Thank you, and Happy New Year!

**Pull request merged**
