### PR TITLE
Add UIN Walisongo Semarang with fixed domain name

### PR DESCRIPTION
**Pull request by ahdyt**

### CODE REVIEW

**Comment by ahdyt** [comment]
So the domain is at walisongo.ac.id, but the student email is at student.walisongo.ac.id, the lecturers or staffs use walisongo.ac.id as their email address.
I've added both in case missing link.

**Comment by ahdyt** [comment]
When you visit student.walisongo.ac.id you may encountered with non index html but it's truly the address for student email, because walisongo is associate with google student mail as server.

**Comment by ahdyt** [comment]
Please review my pull request @philipto

**Comment by philipto** [comment]
@ahdyt Pull request merged. Thank you!

**Pull request merged**
