### PR TITLE
42 Luxembourg

### PR DESCRIPTION
**Pull request by LegendPhoenix66**
new school in the 42 network 
https://42luxembourg.lu/
https://www.42network.org/42-schools/

### CODE REVIEW

**Comment by philipto** [comment]
@LegendPhoenix66 file/lib/domains/lu/42luxembourg.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by LegendPhoenix66** [comment]
sorry, I uploaded the file with the path that the contributeUniversity website gave me, did not notice the "file" folder was there. Should be the correct path now

**Comment by philipto** [comment]
@LegendPhoenix66 First stage of verification passed, official domain is [42luxembourg.lu](https://42luxembourg.lu) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@LegendPhoenix66 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
