### PR TITLE
Create demokritos.gr

### PR DESCRIPTION
**Pull request by harisk74**
Please add NCSR Demokritos in Greece. Demokritos is a public research organization of the Greek Ministry of Education.

### CODE REVIEW

**Comment by zweizwei** [comment]
the organization website is http://www.demokritos.gr/ - so please provide some proof that the provided email also belongs to the university. Also please provide the page, describing long term (>1year) educational programs that the organization provides. We only grant access to educational entities providing graduate programs.

**Comment by harisk74** [comment]
High Elena,
    You are right I have created the github account with my personal
email. Now I am replying from my organizations email.
In terms of educational programs we do have Joint  post-graduate and PHD
programes. I am pretty sure that PHD programs are multi-year. The
post-graduate programs can be 1 year or more, 2 year programs are common
in Greece.
You can find information on the above at the following links, but I can
further look into it and come back to you if you wish.
https://www.iit.demokritos.gr/edu/joint_programs_gr
https://www.iit.demokritos.gr/edu/joint_phd_research_collaborations

Thanks in advance

Charis

On 21/7/2015 9:01 μμ, Elena Ganenkova wrote:
>
> the organization website is http://www.demokritos.gr/ - so please
> provide some proof that the provided email also belongs to the
> university. Also please provide the page, describing long term
> (>1year) educational programs that the organization provides. We only
> grant access to educational entities providing graduate programs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JetBrains/swot/pull/1186#issuecomment-123416750>.
>


-- 
----------------------------------------------------      
Koutsouris Charalampos, MSc, CISA,CISSP
Institute of Informatics and Telecommunications,
NCSR "Demokritos",
153-10 Agia Paraskevi , Athens, GREECE
Tel: +30 - 210 - 6503125
Fax: +30 - 210 - 6543615
E-mail: harisk@iit.demokritos.gr
mobile : 0030 6981013265
Skype : koutsourish
---------------------------------------------------- 



---
Αυτό το e-mail ελέγχθηκε για ιούς από το πρόγραμμα Avast antivirus.
https://www.avast.com/antivirus

**Comment by harisk74** [comment]
I have now added my demokritos.gr email to github.

**Comment by zweizwei** [comment]
@harisk74 thanks a lot for the thorough explanation, I'm adding the domain now

**Comment by harisk74** [comment]
Don't mention it.

Thanks

**Pull request merged**
