### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ahmadzoul87**
Adding CIS - Cedar International School

### CODE REVIEW

**Comment by philipto** [comment]
@ahmadzoul87 First stage of verification passed, official domain is [cedarinternationalschools.com](https://cedarinternationalschools.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://cedarinternationalschools.com/career/

**Comment by ahmadzoul87** [comment]
مدارس سدر العالمية 
the above is the arabic name of cedar international school

**Comment by philipto** [comment]
@ahmadzoul87  Thank you for the clarifications. Pull request merged.

**Comment by ahmadzoul87** [comment]
well noted thanks

**Pull request merged**
