### PR TITLE
Adds Nazarbayev University (nu.edu.kz)

### PR DESCRIPTION
**Pull request by ac130kz**

### CODE REVIEW

**Comment by philipto** [comment]
@ac130kz lib/domains/kz/edu/nu: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by ac130kz** [comment]
@philipto Done!

**Comment by philipto** [comment]
@ac130kz First stage of verification passed, official domain is [nu.edu.kz](https://nu.edu.kz) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@ac130kz Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
