### PR TITLE
Added - IQRA ENGLISH MEDIUM HIGH SCHOOL

### PR DESCRIPTION
**Pull request by tanveerdotnet**

### CODE REVIEW

**Comment by philipto** [comment]
@tanveerdotnet Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by tanveerdotnet** [comment]
Hi Philip,

Please find my comments inline - 

- the school official website URL
  >> http://iqraeducation.org
 
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
  >>We are still building the website, we are yet to add the details of the courses offered by school. 

- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
  >> I am part of school management coming for a programming background helping school to automate their process. We are building a portal and we then plan to bring all the students into the portal with their official email domain.

Hope my answers will give you the trust that we are a genuine school helping children to be well educated and grow in their life, please check the website for more information.

Thanks,
Tanveer

**Comment by tanveerdotnet** [comment]
Hi @philipto,

I'm attaching proof for point 3 "a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students."

image

Thanks,
Tanveer

**Comment by philipto** [comment]
@tanveerdotnet Thank you for the clarification. Pull request merged.

**Pull request merged**
