### PR TITLE
Added Poltair School, Chethams School, UK.

### PR DESCRIPTION
**Pull request by tomdbarker**
Added Poltair School, St Austell, Cornwall, UK.
Added Chethams School, Manchester, UK.

### CODE REVIEW

**Comment by philipto** [comment]
@tomdbarker Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by tomdbarker** [comment]
Poltair School:
https://www.poltairschool.co.uk/index.html
https://www.poltairschool.co.uk/Parent/Subjects.html (Computer Science GCSE Bacc.)
https://www.poltairschool.co.uk/ContactUs.html (Please see secretary and Head of school email addresses)

**Comment by tomdbarker** [comment]
I have now removed the Chethams entry. They don't offer any courses > 1yr in Computer Science, only course add-ons etc.

**Comment by philipto** [comment]
@tomdbarker Thank you for the clarification and the update. Pull request merged.

**Comment by tomdbarker** [comment]
Thanks :)

**Pull request merged**
