### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Kuba2741**
my school

### CODE REVIEW

**Comment by jahnaf** [comment]
my school
[file.zip](https://github.com/JetBrains/swot/files/10490667/file.zip)

**Comment by jahnaf** [comment]
my school
[file.zip](https://github.com/JetBrains/swot/files/10490690/file.zip)

**Comment by Kuba2741** [comment]
> my school [file.zip](https://github.com/JetBrains/swot/files/10490690/file.zip)

hello?

**Comment by philipto** [comment]
@Kuba2741 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Pull request closed without merging**
