### PR TITLE
Added Staatliches Museum für Naturkunde Stuttgart

### PR DESCRIPTION
**Pull request by Velaya**
#### Institution/School Name 
Staatliches Museum für Naturkunde Stuttgart

#### Instiution/School Website
https://www.naturkundemuseum-bw.de/

#### Email Users
firstname.lastname[at]smns-bw.org

*Please place an x between the square brackets if yes*
- [x] Students
- [x] Academic/Teaching Staff
- [x] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*
- [x] Post-graduate research
- [x] Graduate School
- [x] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [ ] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by philipto** [comment]
@Velaya lib/domains/de/naturkundemuseum-bw: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Velaya** [comment]
@philipto I'm so sorry, I've corrected the issues! I've tried to commit twice to make pull request to leereilly first before realizing that it's closed and then went out of time in the end and made mistakes.

**Comment by Velaya** [comment]
> @Velaya Please provide us with:
> 
> * the school official website URL
https://www.naturkundemuseum-bw.de/
> * the school street address, including city and country
Staatliches Museum für Naturkunde
Rosenstein 1, 70191 Stuttgart
Germany
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
The courses are offered through pages that are only visible to students when logged in so I provide a screenshot of the course "Research data management and Biodiversityinformatics" I give every winter term: https://media.smns-bw.org/everywinterterm.JPG
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
Well I don't know which proof I could give but all of our students receive a firstname.lastname[at]smns-bw.de email address. For example the entomology is a huge team, every student there has their own smns-bw.de address as you can check here: https://www.naturkundemuseum-bw.de/en/research/entomology

**Comment by philipto** [comment]
@Velaya  Thank you for the clarifications. Pull request merged.

Please notice that the educational license is for educational use only. If the employees of the institution, who are neither students nor teachers, need the license, please ask them to send a message to [sales@jetbrains.com](mailto:sales@jetbrains.com) to get an academic discount for a paid license.

**Comment by Velaya** [comment]
I'm already using a paid license of PyCharm for a few years now, I want this swot entry for an educational license of SmartGit :) Thank you very much!

**Pull request merged**
