### PR TITLE
Added eduge.ch

### PR DESCRIPTION
**Pull request by Cormoran96**
Added eduge.ch, aka the Département de l'Instruction Publique du Can…

### CODE REVIEW

**Comment by philipto** [comment]
@Cormoran96 I am sorry, this organization seems to be a government agency, neither a university, nor a college. If I am not mistaken, it can not be added to this repository because the repository contains domains of universities and colleges only. Please comment on this issue. Thank you!

**Comment by philipto** [comment]
@Cormoran96 Please comment or close the request. Thank you!

**Comment by Cormoran96** [comment]
This is not a government agency. This is a computer science school.

**Comment by philipto** [comment]
@Cormoran96 Thank you for the clarification. In fact, it is not clear from the title of the organization and the website content. Could you please provide us with links to official school webpages where:
1) the school offers an IT-related long-term (> 1 year) course to its students, and describes the course?
2) the school physical location and postal address are published?

Please note that JetBrains does not grant free licenses to students of online universities, the licenses are for students of the universities where students study in classrooms.

This page (http://edu.ge.ch/sem/usages/outils/regles-dusage-et-conditions-dutilisation-dedugech-google-apps-1310) says that EDUGE.CH is not a school, but an educational platform, which is quite different from being a university or a college.

If the school is actually an online school, we'll have to close the request without merging. Please comment on the issue. Thank you!

**Comment by philipto** [comment]
@Cormoran96 I am sorry for the trouble happened with this domain. We received an official request from the school teacher, and he confirmed that this domain belongs to the school, and we were able to find a proof of that. The eduge.ch domain is added to the repository. The cause of the issue is that eduge.ch website does not look like a typical school website, and we failed to find a proof of ownership for this domain before. I apologise for the inconvenience.

**Comment by Cormoran96** [comment]
Ok really thanks for added. Which teacher is?

Le mar. 13 sept. 2016 15:50, Philip Torchinsky <notifications@github.com> a
écrit :

**Comment by philipto** [comment]
@Cormoran96 Luc Chetelat.

**Pull request closed without merging**
