### PR TITLE
Erasmus College

### PR DESCRIPTION
**Pull request by Nowaha**
My high school.

### CODE REVIEW

**Comment by philipto** [comment]
@Nowaha Could you please tell us a bit more about the school? How long do students study there? Are there any long-term (>1 year) courses?

**Comment by Nowaha** [comment]
This is a high school. In the Netherlands they work like this:
There's 3 levels of education.
MAVO, which is the easiest for less smart people (easy) (less good jobs, not allowed to go to uni) -> 4 years
HAVO, which is average (still not uni) -> 5 years
VWO, which is above average (smarter people, difficult) -> 6 years

These are the final years of standard education and then you can go to an university, get a job or follow a HBO course.

**Comment by philipto** [comment]
@Nowaha Thank you for the clarification. Thus, Erasmus College is VWO? 
Pull request merged.

**Comment by Nowaha** [comment]
You can choose from all three, based on how good you are. The first 3 years at the school are the same for everyone and then based on your grades there you can choose to follow MAVO/HAVO/VWO.

**Comment by philipto** [comment]
@Nowaha Now I got it, thank you for the details!

**Pull request merged**
