### PR TITLE
Centro Universitário Adventista de São Paulo

### PR DESCRIPTION
**Pull request by 01matheus10**
Add university

### CODE REVIEW

**Comment by philipto** [comment]
@01matheus10 First stage of verification passed, official domain is [querobolsa.com.br](https://querobolsa.com.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://querobolsa.com.br/escolas/colegio-adventista-de-araucaria

**Comment by 01matheus10** [comment]
Hi Philip,

This domain is from a high school and from another state, I believe that
the university I attend and its domain is not the same as that school.
This is my college and campus website that I study if it helps:
Home - UNASP - Campus Hortolandia <https://unasp.br/ht/>

Thanks,
Matheus

Em seg., 17 de jul. de 2023 às 13:09, Philip Torchinsky <
***@***.***> escreveu:

**Comment by philipto** [comment]
@01matheus10 Thank you! Yes, it is important to make clear which of the schools with similar names owns your email domain. Therefore, could you please provide us with:
* the school official website URL
* the school street address, including city and country
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by 01matheus10** [comment]
Hi Philip,

Here are the responses to the topics:

   - the school official website URL: Home - UNASP - Centro Universitário
   Adventista de São Paulo <https://unasp.br/>

   - the school street address, including city and country:
   Full address: Rua Pastor Hugo Gegembauer, 265, Hortolândia - SP,
   13184-010
   Street: Rua Pastor Hugo Gegembauer
   City: Hortolândia
   Country: Brazil

   - a proof, which shows that the school recognizes the domain you are
   submitting as an official email domain for the students:
   As for this topic I do not know exactly what to send, we have access to
   OneDrive and the office package with this email, for example, follows a
   print that shows OneDrive recognizing the domain and changing the
   background of the site, adding an image with the college logo:
   [image: image.png]

   And another print already logged in:
   [image: image.png]

   If that's not enough and there's some other way to prove the domain let
   me know.

   Thanks,
   Matheus


Em sex., 21 de jul. de 2023 às 07:34, Philip Torchinsky <
***@***.***> escreveu:

**Comment by philipto** [comment]
@01matheus10  Thank you for the clarifications. Pull request merged.

**Comment by 01matheus10** [comment]
Hi @philipto, i believe you forgot to merge the PR, thanks in advance.

**Comment by philipto** [comment]
@01matheus10 Yes, you are right. Please accept my apologies for the mistake and the delay. Pull request is now merged. You can start requesting free subscriptions in an hour. Thank you!

**Comment by 01matheus10** [comment]
Hi Philip,

Alright, thank you very much.

Em qua., 26 de jul. de 2023 às 09:23, Philip Torchinsky <
***@***.***> escreveu:

**Pull request merged**
