### PR TITLE
Added Panimalar Engineering Collage Student Email Domain

### PR DESCRIPTION
**Pull request by Prasanth-Programmer**
Description:
Panimalar Engineering Collage **Student email domain** is not present in the JetBrains list. So I added the domain. 
Collage website: https://panimalar.ac.in/
Collage email domains supported by GitHub: panimalarengg.onmicrosoft.com (For Students)
Email Domain Accepted by GitHub:

Screenshot 2024-01-26 082305

### CODE REVIEW

**Comment by Prasanth-Programmer** [comment]
@philipto Please take a look at this PR and let me know any changes required.

**Comment by Prasanth-Programmer** [comment]
@philipto Is anything wrong in this PR? Could you please confirm.

**Comment by philipto** [comment]
@Prasanth-Programmer Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by Prasanth-Programmer** [comment]
@philipto Thanks a Lot!

**Pull request merged**
