### PR TITLE
Loreto Kirribilli

### PR DESCRIPTION
**Pull request by missyevelyn**
School website: https://www.loreto.nsw.edu.au/

### CODE REVIEW

**Comment by philipto** [comment]
@missyevelyn lib/domains/au/edu/nsw/loreto: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by missyevelyn** [comment]
Hi @philipto - sorry for missing the file extension and thank you for pushing the update to this PR.

My understanding is that everything else is in order? Can this PR be merged now?

**Comment by philipto** [comment]
@missyevelyn Yes, it's all fine now. Pull request merged. Thank you!

**Comment by philipto** [comment]
Please wait for about 1 hour before requesting free license to let the changes to propagate through the system. Thank you.

**Pull request merged**
