### PR TITLE
Add ISET KELIBIA

### PR DESCRIPTION
**Pull request by MedAli20**
Let's make PhpStrom Better together!

### CODE REVIEW

**Comment by philipto** [comment]
@MedAli20 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by MedAli20** [comment]
@philipto Of course, you can check the school website: http://www.isetkl.rnu.tn
and this my education email from our school:
mohamedalibouzidi@kelibia.r-iset.tn

**Comment by philipto** [comment]
@MedAli20 Thank you for the clarification!
Could you please tell me where exactly at http://www.isetkl.rnu.tn I can see that this university assigns (or instructs students to use) email addresses such as `<username>@kelibia.r-iset.tn`?

**Comment by MedAli20** [comment]
here the login page:
http://www.isetkl.rnu.tn/fra/intranet/auth

**Comment by philipto** [comment]
@MedAli20 Yes, you are right, this is the login page. However I need some instruction that asks students to use the domain kelibia.r-iset.tn. Do you have any? You can upload a copy of the instruction here as a comment, please.

**Comment by MedAli20** [comment]
@philipto Sorry no, this accounts are pre-build by the school.

**Comment by philipto** [comment]
@MedAli20 I found an independent proof of the domain ownership. Everything is correct. Pull request merged. Thank you.

**Comment by MedAli20** [comment]
@philipto Thank you.

**Pull request merged**
