### PR TITLE
added unugiri

### PR DESCRIPTION
**Pull request by isnaayu**

### CODE REVIEW

**Comment by talhatariq7** [comment]
[duet.txt](https://github.com/JetBrains/swot/files/13940601/duet.txt)

kindly include this university name also

**Comment by philipto** [comment]
@isnaayu First stage of verification passed, official domain is [unugiri.ac.id](https://unugiri.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@isnaayu Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by philipto** [comment]
@talhatariq7 Please create a separate pull request. Please don't comment others' requests if you need to add another university.

**Pull request merged**
