### PR TITLE
Create Prakticum.txt

### PR DESCRIPTION
**Pull request by tomclindstrom**
www.prakticum.fi

Kontakta

Tom.lindstrom Teacher computer science

### CODE REVIEW

**Comment by philipto** [comment]
@tomclindstrom Anteeksi,
Why did you close the request? Do you need free licenses for your students?

**Comment by tomclindstrom** [comment]
Hello

Yes it would be nice, I accidentally pressed wrong button on my mobile.

Best regards
Tom Lindström

**Comment by tomclindstrom** [comment]
Thank you in  advanced ,

Regards 
Tom Lindström

**Comment by philipto** [comment]
@tomclindstrom Pull request merged. Thank you!

**Pull request merged**
