### PR TITLE
Create seu.txt to add Southeast University

### PR DESCRIPTION
**Pull request by shang-huan**

### CODE REVIEW

**Comment by philipto** [comment]
@shang-huan Thank you for the request. You submitted the file lib/domains/cn/deu/seu.txt. It corresponds the domain **seu.deu.cn**. Did you make a typo? If you meant to add the domain seu.edu.cn, the file name has to be lib/domains/cn/**edu**/seu.txt

**Comment by philipto** [comment]
@shang-huan You might miss my previous comment. Please react.

**Comment by shang-huan** [comment]
I'm sorry I missed the reminder. Now I see that it has been modified

**Comment by philipto** [comment]
@shang-huan Could you please specify the domain you'd like to add to the trusted list? Is it **seu.edu.cn**?

**Comment by shang-huan** [comment]
Yes, the website of the southeast university is https://www.seu.edu.cn/.

**Comment by philipto** [comment]
@shang-huan seu.edu.cn is already in our trusted list. There were some issues related to it, and I just fixed it. **Please start requesting licenses in an hour.** 

I close the request as it does not specify correct domain name.

**Pull request closed without merging**
