### PR TITLE
Create kma.txt

### PR DESCRIPTION
**Pull request by JaiunL**

### CODE REVIEW

**Comment by philipto** [comment]
@JaiunL Please rename lib/domains/ac/kma to lib/domains/kr/ac/kma.txt if this school email address pattern is username@kma.ac.kr
Thank you!

**Comment by philipto** [comment]
@JaiunL You might miss my previous comment. Please react.

**Comment by JaiunL** [comment]
Oh oh sorry my bad. I cant access my latop right now and I will have it fixed when I do. Sorry once again

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by philipto** [comment]
@JaiunL I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
