### PR TITLE
Instituto Tecnológico Sanmiguelense de Estudios Superiores

### PR DESCRIPTION
**Pull request by altariamx**
Instituto Tecnológico Sanmiguelense de Estudios Superiores
https://www.itses.edu.mx

### CODE REVIEW

**Comment by philipto** [comment]
@altariamx I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host itses.mx not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by altariamx** [comment]
Damn, that was a mistake

The domain is https://www.itses.edu.mx

I work in itses.edu.mx has a programmer teacher in Instituto Tecnológico
Sanmiguelense de Estudios Superiores

Can I do the fork again?

**Comment by philipto** [comment]
@altariamx No problem. You can remove this file from your fork and add a correct file, lib/domains/mx/edu/itses.txt. Then you can make a pull request again. You disabled an option to edit this pull request, thus I cannot do it on your behalf. Therefore, I have to close it without merging. Thank you.

**Comment by altariamx** [comment]
I did the fork again, I hope its ok

**Pull request closed without merging**
