### PR TITLE
Adding Kungsbacka

### PR DESCRIPTION
**Pull request by AkeSve**

### CODE REVIEW

**Comment by philipto** [comment]
@AkeSve First stage of verification passed, official domain for **Elof Lindälvs gymnasium** is [kungsbacka.se](https://kungsbacka.se) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@AkeSve Could you please clarify whether the domain [kungsbacka.se](https://kungsbacka.se/) belongs to the municipality or commune, or it belongs exclusively to the school?

**Comment by AkeSve** [comment]
> @AkeSve Could you please clarify whether the domain [kungsbacka.se](https://kungsbacka.se/) belongs to the municipality or commune, or it belongs exclusively to the school?

It belongs to the municipality, both teachers and students of this school and others in the municipality uses the domain.

**Comment by philipto** [comment]
@AkeSve It looks like all municipal employees (in addition to teachers and student) also can use the domain. Do I understand it correctly?

**Comment by philipto** [comment]
@AkeSve Regrettably, the domain represents an umbrella institution (municipality), not a specific single university or a college exclusively. I cannot add it to this trusted list. It's against the rules.

Please consider two options for the students of this school:
1. Enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with the GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).
2. If you are a teacher, you can apply with your official documents for the free license at https://www.jetbrains.com/shop/eform/students ("Official document" tag).
3. For both teachers and students a classroom license would work: https://www.jetbrains.com/shop/eform/classroom/faculty
If you are a teacher, please consider applying for the classroom license for the entire school.

If you have any questions or feedback, please send us an email to community-support@jetbrains.com.

I have to close this request without merging.
Thank you for your understanding!

**Pull request closed without merging**
