### PR TITLE
added Orange Coast College

### PR DESCRIPTION
**Pull request by rserra43**

### CODE REVIEW

**Comment by rserra43** [comment]
added a new college to list

**Comment by philipto** [comment]
@rserra43 lib/domains/lib/abicheck.sh: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@rserra43 lib/domains/lib/abicheck.sh: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@rserra43 I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host student.cccd not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by rserra43** [comment]
Hello Philipto, 
OCC’s official means of communication with students is through their student email account.  Your student email (eg. name@student.cccd.edu) can be accessed through your MyCoast Account. 

Below is the official link to the above statement from Orange Coast College:

http://www.orangecoastcollege.edu/about_occ/Technology/student-computing/Pages/Student-Email-(Gmail).aspx

Thank you

**Comment by rserra43** [comment]
Hello Philipto,
OCC’s official means of communication with students is through their
student email account. Your student email (eg. name@student.cccd.edu) can
be accessed through your MyCoast Account.

Below is the official link to the above statement from Orange Coast College:

http://www.orangecoastcollege.edu/about_occ/Technology/student-computing/Pages/Student-Email-(Gmail).aspx

Thank you

**Pull request closed without merging**
