### PR TITLE
feat: add Ecole-IT school

### PR DESCRIPTION
**Pull request by henri9813**
Hello,

Students emails are  firstname.lastname@ecole-it.com

It deliver a master degree in computer sciences.

best regards,

### CODE REVIEW

**Comment by philipto** [comment]
@henri9813 Please clarify if the school's students retain their email addresses after their graduation. Thank you.

**Comment by henri9813** [comment]
Hello,

Thanks for your reply,

Students will not keep their email address if the leave the school (after graduation or give-up ).

Best regard

**Comment by philipto** [comment]
@henri9813 Thank you for the clarification. Pull request merged.

**Comment by henri9813** [comment]
Hello,

I seen you put our domain in "abused.txt".

I gave a wrong arguments in my previous post.

Historically, students may keep their address if they continue to **Teach** in the school as an external teacher, that's the case of some students.

Also, for now, a new regulation in France require student to keep their mail because the school may reach them after graduation to following the "after graduation" life-cycle ( to retrieve data about wages, where they lives etc... ).

It's also the case of other schools such as:
- supinfo.com
- epitech.eu
- cesi.com
- epsi.com
- ecole-ipssi.com

etc...

Can you unban our domain please ? 

Best regards

**Pull request merged**
