### PR TITLE
added high school

### PR DESCRIPTION
**Pull request by Ascaped**

### CODE REVIEW

**Comment by philipto** [comment]
@Ascaped Please provide us with:
- the school official website URL, if different from the domain you are submitting,
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Ascaped You might miss my previous comment. Please react.

**Comment by Ascaped** [comment]
http://www.hpregional.org/ is the website hprmail.org is for student emails

**Comment by philipto** [comment]
@Ascaped Pull request merged. Thank you!

For the record: domain ownership proof is at http://www.hpregional.org/students/student_g_suite_information

**Pull request merged**
