### PR TITLE
add Ministry of Education - Oman

### PR DESCRIPTION
**Pull request by maz1987in**

### CODE REVIEW

**Comment by philipto** [comment]
@maz1987in This domain does not belong to a university, nor to a college. I have to close the request without merging. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting a new request.

**Comment by maz1987in** [comment]
@philipto The domain belonging to the Ministry of Education in Oman and all teachers in the country is having this domain.
So could you please consider this request again?

**Comment by maz1987in** [comment]
@philipto Thanks,
Do I have to submit anything more to approve this request?

**Comment by philipto** [comment]
@maz1987in We reconsidered the request and decided that the domain can be added to the repository as an exception. 

Please spread the word about the free license availability among teachers. We expect many of them registering and teaching students using the tools that are convenient for them. Shall you have any questions, please feel free to email us at community-support@jetbrains.com.

Pull request merged.
Thank you!

**Pull request merged**
