### PR TITLE
Add my school

### PR DESCRIPTION
**Pull request by pietrodev07**

### CODE REVIEW

**Comment by AJD254** [comment]
[students.txt](https://github.com/JetBrains/swot/files/12643575/students.txt)

**Comment by pietrodev07** [comment]
> [students.txt](https://github.com/JetBrains/swot/files/12643575/students.txt)
> 

I didn't understand

**Comment by AJD254** [comment]
can you add my school

**Comment by pietrodev07** [comment]
> can you add my school

No, I can't. 

I asked if they can add my school.

You have to follow the initial README.

**Comment by AJD254** [comment]
Ok may I know the procedure of adding a university to jetbrains Sent from Mail for Windows From: pietrodev07Sent: Sunday, 17 September 2023 22:54To: JetBrains/swotCc: john Bradley; CommentSubject: Re: [JetBrains/swot] Add my school (PR #18724) can you add my schoolNo, I can't.I asked if they can add my school.You have to follow the initial README.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Pull request closed without merging**
