### PR TITLE
Create connect

### PR DESCRIPTION
**Pull request by AlphaDivided**
Added new institution

### CODE REVIEW

**Comment by philipto** [comment]
@AlphaDivided lib/domains/za/edu/connect: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@AlphaDivided Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by AlphaDivided** [comment]
URL: https://www.southdownscollege.co.za/
Address: 1297 John Vorster Drive Ext, Southdowns, Irene, 0123
Subjects: https://irp.cdn-website.com/c109a13b/files/uploaded/2024%20Subjects%20on%20offer%20Southdowns%20College_High%20School.pdf
Domain prooF: (attached)

https://github.com/user-attachments/assets/fed62303-8c11-423a-94e4-7b6a1a881609

**Comment by philipto** [comment]
@AlphaDivided Thank you for the clarification. It looks like connect.edu.za is for many schools in the country, is it correct? 

The domain use proof: https://irp.cdn-website.com/f1c72268/files/uploaded/ADvLEARN%20-%20Parent%20Infographic%20v1%20(Dec%2022)%20-%20Reduced%20Size.pdf

**Comment by AlphaDivided** [comment]
Yes that is correct, the domain is used by multiple schools under the ADvTECH school group

**Comment by philipto** [comment]
@AlphaDivided  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
