### PR TITLE
Ajout école MBway

### PR DESCRIPTION
**Pull request by dbourse**
Ajout de l'école MBway d'Angers

### CODE REVIEW

**Comment by dbourse** [comment]
Hello,
Here is the website: https://www.mbway.com/mba-angers

**Comment by philipto** [comment]
@dbourse Please provide us with:
* the school official full name, **not an abbreviation**
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by dbourse** [comment]
@philipto , sorry for my late answer
School official full name: École MBway
Address: 299 Av. du Général Patton, 49000 Angers, FRANCE
URL: https://www.mbway.com/formations/mba-communication-et-digital/programme
What type of proof do you need for example ? A received or sent mail ?
Thank you in advance

**Comment by philipto** [comment]
@dbourse Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
