### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by bpsnh28**
New student license domain

### CODE REVIEW

**Comment by philipto** [comment]
@bpsnh28 First stage of verification passed, official domain is [sites.google.com](https://sites.google.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://sites.google.com/bedfordnhk12.net/rossalurgio/home

**Comment by bpsnh28** [comment]
Is it verified yet?
JetBrains verification does not work for me right now.
Thanks!

**Comment by bpsnh28** [comment]
Has it gone through yet? Thanks!

From: Philip Torchinsky ***@***.***>
Date: Tuesday, February 7, 2023 at 11:33 PM
To: JetBrains/swot ***@***.***>
Cc: BPS ***@***.***>, Mention ***@***.***>
Subject: Re: [JetBrains/swot] Add files via upload (PR #16500)

@bpsnh28<https://github.com/bpsnh28> First stage of verification passed, official domain is sites.google.com<https://sites.google.com> as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://sites.google.com/bedfordnhk12.net/rossalurgio/home

**Comment by philipto** [comment]
@bpsnh28 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Now**, the email domain has verified. Please wait for another 30-60 minutes to allow the changes to propagate through our systems. Thank you!

**Comment by bpsnh28** [comment]
THANK YOU SO MUCH!!!!!!!
________________________________

**Pull request merged**
