### PR TITLE
Create cambridge.txt

### PR DESCRIPTION
**Pull request by mpirnazarovciu**
Cambridge International University in Tashkent
Original website: cambridge.uz
Main domain used by staff and teachers
Subdomain student.cambridge.uz used by students and separate pull request has been created

### CODE REVIEW

**Comment by philipto** [comment]
@mpirnazarovciu First stage of verification passed, official domain is [cambridge.uz](https://cambridge.uz) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@mpirnazarovciu You might miss my previous comment. Please react.

**Comment by mpirnazarovciu** [comment]
> @mpirnazarovciu Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

Sure,
https://university.cambridge.uz/en/program-detail/2/

We have 2 paths now, Computer Science and Software Engineering each 4 years of education in BSc
We are planning to start a new path of Artificial Intelligence starting from A.Y. 2023-2024

**Comment by philipto** [comment]
@mpirnazarovciu  Thank you for the clarifications. Pull request merged.

**Pull request merged**
