### PR TITLE
Add Faculdade Pitagoras

### PR DESCRIPTION
**Pull request by prentecejunior**
This is the email used by Pitagoras College students in Ipatinga

### CODE REVIEW

**Comment by Carm01** [comment]
Here is some additional info regarding the college:
Home Page: https://www.cincinnatistate.edu/
Computer Programing related degrees: http://catalog.cincinnatistate.edu/academicdivisionsanddegreeampcertificateprograms/engineeringandinformationtechnologiesdivision/computerprogramminganddatabasemanagement/
Entire catalog of degrees: https://www.cincinnatistate.edu/sites/default/files/asset/document/CS-Catalog-%28Revised%29-2020-21.pdf
Official document by IT that shows that domain is used for students(setting email on mobile): https://web4.cincinnatistate.edu/files/its/bbhelp/supplemental/help/pdfs/Outlook_on_Android_Students.pdf
Other info that could help here: https://web3.cincinnatistate.edu/its/TechTips
[cincinnatistate.txt](https://github.com/JetBrains/swot/files/5644041/cincinnatistate.txt)

**Comment by prentecejunior** [comment]
Home Page: Do not access page edumail.com.br because it is a domain only for college email, 
this is the institution's official website https://www.pitagoras.com.br/
Computer Programing related degrees:https://www.pitagoras.com.br/curso/engenharia-da-computacao/
Official document by IT that shows that domain is used for students(setting email on mobile):https://sites.google.com/view/engpitagoraspc/aulas-remotas or https://www.direitopitagorasslz.com/post/aulas-disciplinas-interativas

**Comment by philipto** [comment]
@prentecejunior Could you please clarify the following:
1) Is this email used by this university only, or is it shared among several schools?
2) How do the websites where the suggested materials are located relate to the official university website? They are in different domains, and may not have any relation to the university. Do you have any other proof that the university recognizes the domain?

**Comment by prentecejunior** [comment]
1.Is probably shared, the edumail domain is owned by Kroton Educacional. Pitagora, Kroton belongs to a large education group called Cogna Education.
2.I have prints and docs that were sent by the college in my personal email.

All of these domains are from the same institution.
https://registro.br/tecnologia/ferramentas/whois/?search=edumail.com.br.
https://registro.br/tecnologia/ferramentas/whois/?search=pitagoras.com.br
https://registro.br/tecnologia/ferramentas/whois/?search=avaeduc.com.br
https://registro.br/tecnologia/ferramentas/whois/?search=kroton.com.br
https://registro.br/tecnologia/ferramentas/whois/?search=cogna.com.br

**Comment by philipto** [comment]
@prentecejunior Thank you for the clarification. Pull request merged.

**Pull request merged**
