### PR TITLE
Add itis fermi

### PR DESCRIPTION
**Pull request by infopz**

### CODE REVIEW

**Comment by philipto** [comment]
@infopz Could you please provide us with:
- the university official website URL
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by infopz** [comment]
hi,
[this](http://www.fermi-mo.gov.it) is the school offial website 
the page of the IT course is [this](http://www.fermi-mo.gov.it/piano-dei-corsi/)
and the attached pdf is a comunication when the prof gave us the email address.
Our email address ends with fermi.mo.it, but the school site is fermi-mo.gov.it, i must put the file in /it/gov or in /it/mo?

[EmailAccountStudenti.pdf](https://github.com/JetBrains/swot/files/807192/IndicazioniAccountStudenti.pdf)

**Comment by philipto** [comment]
@infopz If your email addresses end with @fermi.mo.it, then the correct file name is lib/domains/it/mo/fermi.txt

**Comment by infopz** [comment]
ok, i renamed the file and i changed his location

**Comment by philipto** [comment]
@infopz Pull request merged. Thank you!

**Pull request merged**
