### PR TITLE
Al Nafi E Learning

### PR DESCRIPTION
**Pull request by shaheer-haider**
alnafi.edu.pk for Al Nafi E Learning

### CODE REVIEW

**Comment by philipto** [comment]
@shaheer-haider First stage of verification passed, official domain is [alnafi.com](https://alnafi.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://stage.alnafi.com/live-schedule

**Comment by shaheer-haider** [comment]
@philipto Thank you so much. In addition to your information about us,
alnafi.com
alnafi.edu.pk
Both are our production domains but we provide alnafi.edu.pk email addresses to students, Due to various reasons we do not want to have .pk on our production domain as our institute in on just in pk(Pakistan) anymore.

stage.alnafi.com is our staging server. stage.alnafi.com is a sub domain of alnafi.com which is owned by us.
But as I mentioned, our students will use emails with alnafi.edu.pk domains.

**Comment by philipto** [comment]
@shaheer-haider I am sorry, this organization seems to be a e-earning platform, not a university or a college. I had to revert the merged request. 

This domain seems to represent an umbrella institution, not a specific single university or a college. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Comment by shaheer-haider** [comment]
> @shaheer-haider I am sorry, this organization seems to be a e-earning platform, not a university or a college. I had to revert the merged request.
> 
> This domain seems to represent an umbrella institution, not a specific single university or a college. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.
> 
> Thank you for your understanding!

@philipto We are an E-Learning Institute but we provide diplomas also that are accredited by EduQual.
We provide email addresses to Diploma enrolled students only.

**Pull request merged**
