### PR TITLE
Add collegecanada

### PR DESCRIPTION
**Pull request by collegecanada**

### CODE REVIEW

**Comment by philipto** [comment]
@collegecanada Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

Please also let us know how do you enroll students from outside Canada, and what the terms of enrollment are. As far as I understand this college's official website, it offers distance learning for international students. Do graduates from the college retain their email addresses in the official email domain? Is it possible to stop studying in the college in a week after enrollment, and continue using the official email address?

**Comment by philipto** [comment]
@collegecanada You might miss my previous comment. Please react.

**Comment by collegecanada** [comment]
Sorry about it, I was busy.


Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.


Answer:

https://collegecanada.com/dba/

Also, our other website is coded with Laravel using PHPStorm.

www.ccsrs.ca<http://www.ccsrs.ca>, www.ccsl.ca<http://www.ccsl.ca>, www.ccielts.ca<http://www.ccielts.ca>




Please also let us know how do you enroll students from outside Canada, and what the terms of enrollment are. As far as I understand this college's official website, it offers distance learning for international students. Do graduates from the college retain their email addresses in the official email domain?

Answer:

We usually ask our potential students to register program in www.ccsrs.ca<http://www.ccsrs.ca> for all programs. Only when their information  are all satified and accepted by college, we will send them the letter of admission.

Once they come in Canada and register in our college and start to study in our College, his student status will be activated and we may grant them our college email account.

We do not offer distance learning. However, during this pandemic , we do offer the distance learning.

Do graduates from the college retain their email addresses in the official email domain?
When students permanently left from college, or inactive in certain period of  time, his email account will be cancelled.



Is it possible to stop studying in the college in a week after enrollment, and continue using the official email address?

Answer:  The same as above.


If have any questions, feel free to contact me: genming.zhao@collegecanada.com




Best Regards.


Genming Zhao


CTO, IT Manager
IT department

________________________________

**Comment by philipto** [comment]
@collegecanada Thank you very much for the details!
Pull request merged. Thank you!

**Pull request merged**
