### PR TITLE
Please add Chuo University to your list

### PR DESCRIPTION
**Pull request by Saggitarie**
Please add Chuo University to your list

### CODE REVIEW

**Comment by philipto** [comment]
@Saggitarie Could you please clarify what is email address pattern in this university? Is it  username@g.chuo-u-ac.jp or g.chuo-u.ac.jp? Please note the difference ("-" or "." before "ac").

**Comment by philipto** [comment]
@Saggitarie You might miss my previous comment. Please react.

**Comment by Saggitarie** [comment]
@philipto 
Sorry for the late reply.
Email pattern for our university is  [username@g.chuo-u.ac.jp]("." before "ac").

**Comment by Saggitarie** [comment]
The username part is rather unique for each student.

**Comment by philipto** [comment]
@Saggitarie I just created a correct file to represent your university in this repository: https://github.com/JetBrains/swot/blob/master/lib/domains/jp/ac/chuo-u/g.txt
I remove this request now as obsoleted, and you can start requesting your free licenses in about an hour. Thank you!

**Pull request closed without merging**
