### PR TITLE
Instituto de educação Carmela Dutra

### PR DESCRIPTION
**Pull request by ffresco**

### CODE REVIEW

**Comment by philipto** [comment]
@ffresco First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/Ciep376ClaudioCoutinho/photos/a.936335673124891/3743139499111147/?type=3

**Comment by philipto** [comment]
@ffresco Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by ffresco** [comment]
Hi Below i pass the information required!


   - the school official website URL: The school has not have his own site,
   but is in the site of the Education Secretary of Rio de Janeiro
      -
      https://www.seeduc.rj.gov.br/cidad%C3%A3o/educa%C3%A7%C3%A3o-integral
   - the school street address, including city and country:
      - Dirección
      <https://www.google.com/search?client=ms-android-motorola-rvo3&sxsrf=APwXEddczlIuj_X67qVFt6apCOJEIM8Bmw:1684952500438&q=instituto+de+educa%C3%A7%C3%A3o+carmela+dutra+direcci%C3%B3n&ludocid=9005007487347453069&sa=X&ved=2ahUKEwiQy4GayY7_AhUBu5UCHQDiBbQQ6BN6BAhFEAI>
      : Av. Min. Edgard Romero, 491 - Madureira, Rio de Janeiro - RJ,
      21360-201
      -  https://g.co/kgs/h7a81P
      - an URL of a page on the official website where the school offers an
   IT-related long-term (>1 year) course: This is a public high school. It has
   not offer of commercial courses, but there is a Subject of Information
   Technology and programming
   - a proof, which shows that the school recognizes the domain you are
   submitting as an official email domain for the students: Here is the link
   of the official site of Education Secretary of Rio de Janeiro, where you
   can see the domain
      - https://sites.google.com/educa.rj.gov.br/educador/
      - https://www.seeduc.rj.gov.br/professor

**Comment by philipto** [comment]
@ffresco First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/Ciep376ClaudioCoutinho/photos/a.936335673124891/3743139499111147/?type=3

**Pull request merged**
