### PR TITLE
Create rb.txt

### PR DESCRIPTION
**Pull request by MohanadI**
Adding Alasra Althanwy tLlbnat Snjl

### CODE REVIEW

**Comment by philipto** [comment]
@MohanadI Please provide us with:
- the school official website URL
- the school street address, including city and country

**Comment by philipto** [comment]
@MohanadI You might miss my previous comment. Please react.

**Comment by MohanadI** [comment]
> @MohanadI Please provide us with:
> 
> * the school official website URL
> * the school street address, including city and country

Thanks Philipto 

should I mintion this here or update the request

**Comment by MohanadI** [comment]
however these are the information you asked for :D 

1- http://www.moehe.gov.ps/
2- Palestine , Ramallah , Sinjil - main street

**Comment by philipto** [comment]
@MohanadI Thank you for the details. Your pull request merged successfully. Could you please clarify few details?

1) Do I understand correctly that the city of Sinjil is not big? How many students study in the school? We need this information to ensure that a third party does not hack and use your school email domain instead of you :)

2) Do I understand correctly that the website http://www.moehe.gov.ps/ does not belong to this particular school? Is it about the school system in Palestine in general?

3) Do we need to modify the file content in your request a little bit? It now reads "Alasra Althanwyt Llbnat Snjl School". Shall Snjl be spelled as "Sinjil"? What about "Llbnat", is it correct? I did not find a translation for this word.

Thank you!

**Comment by MohanadI** [comment]
Thanks again  @philipto 

yes sure I will clearify everything , 

I will starts with point 2, so all schools at Palestine are connected with the same email server which is owned by the goverment ( The Ministry of Education ) not by schools itself.
So now the first point is more clear, Sinjil is a small town inside Ramallah governorate and the school serves around 1000 students.
For the final point, 
- Alasra ( school name )
- Althanwyt ( high school ) 
- Llbnat ( for girsl ) 
- Snjl ( Sinjil )

please feel free to ask me for any other questions.

Thanks again

**Comment by philipto** [comment]
@MohanadI Thank you very much! Have a happy coding and school experience!

**Pull request merged**
