### PR TITLE
EICPN add

### PR DESCRIPTION
**Pull request by Moins-helha**
[jetbrains - G Moins.pdf](https://github.com/JetBrains/swot/files/12812444/jetbrains.-.G.Moins.pdf)

URL : https://eicpn.be

Studies : 
1) Bachelier en informatique et systèmes – orientation : technologie de l'informatique (bachelor in IT) 
2) Technicien en programmation (programming tech)

### CODE REVIEW

**Comment by philipto** [comment]
@Moins-helha lib/domains/be/namur/province/eicpn.be: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Moins-helha** [comment]
Updated format

**Comment by philipto** [comment]
@Moins-helha lib/domains/be/namur/province/eicpn/jetbrains: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Moins-helha First stage of verification passed, official domain is [province.namur.be](https://province.namur.be) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Moins-helha Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
