### PR TITLE
add City Colleges of Chicago

### PR DESCRIPTION
**Pull request by houxiufeng**
add City Colleges of Chicago, we can work better.

### CODE REVIEW

**Comment by houxiufeng** [comment]
anybody who can approve this pull request?

**Comment by houxiufeng** [comment]
The school official website URL: https://www.ccc.edu/Pages/default.aspx

**Comment by houxiufeng** [comment]
hi @philipto, can you review this PR and merge it?

**Comment by philipto** [comment]
@houxiufeng This domain is blacklisted because the college allows to register an email address there even if you are not a student of the college. If you are the student of this college, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
