### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by bielosheikin**

### CODE REVIEW

**Comment by bielosheikin** [comment]
[Deutsche Film- und Fernsehakademie Berlin](https://www.dffb.de/)

**Comment by philipto** [comment]
@bielosheikin Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by bielosheikin** [comment]
Dear Philip,

Unfortunately there are no courses like that in my school. Since my studies
in the DFFB are quite long in the meanwhile as a student I wanted to use
the opportunity to get the license for PyCharm and learn Python myself with
the purpose to be able to apply for part-time or mini-jobs requiring
relevant skills.

Or is it only possible for the students learning IT-related subjects in
corresponding Universities?

Best regards,
Daniil Bielosheikin

**Comment by philipto** [comment]
@bielosheikin Dear Daniil,

Yes, you are right. Regrettably, the year-long free educational licenses are granted to the students studying in the relevant programs, i.e. long-term courses conducted by an officially recognized school. Thus, I have to close your request without merging.

**If you self-learn Python, I suggest using PyCharm Community Edition, which is free for everybody and does not require any subscription.**

You also can enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
