### PR TITLE
Create imie.txt

### PR DESCRIPTION
**Pull request by erwanf**
Add the IMIE school

### CODE REVIEW

**Comment by erwanf** [comment]
You can discover the web site at http://www.imie-ecole-informatique.fr/

**Comment by erwanf** [comment]
Students are registered with firstname.lastname@imie.fr
Teachers are registerd with firstname.lastname@imie.fr

**Comment by philipto** [comment]
@erwanf I am sorry for the delay with processing your pull request. Could you please remove "Since 1994, IMIE has delivered a professional education to hundreds of students each year." from the institute description? There shall be just name of the college or university in the .txt file. Please, close the ticket and create new one with proper .txt content. Thank you!

**Comment by erwanf** [comment]
Hello,
I deleted the information requested.
thank you

**Comment by philipto** [comment]
@erwanf Thank you! Pull request merged.

**Pull request merged**
