### PR TITLE
a URL of a page on the official website where a long-term (>1 year) I…

### PR DESCRIPTION
**Pull request by serhatkosif**
…T related course is offered by the university, https://constructor.university/programs/graduate-education/computer-science-software-engineering

### CODE REVIEW

**Comment by philipto** [comment]
@serhatkosif file/lib/domains/university/constructor.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by serhatkosif** [comment]
@philipto thank you for the feedback!
I have made the relevant corrections in my pull request, for your info.

**Comment by philipto** [comment]
@serhatkosif First stage of verification passed, official domain is [constructor.university](https://constructor.university) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@serhatkosif Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by serhatkosif** [comment]
@philipto Thank you!

**Pull request merged**
