### PR TITLE
Add Gonzaga Campus - Palermo

### PR DESCRIPTION
**Pull request by ingmarcospina**

### CODE REVIEW

**Comment by ingmarcospina** [comment]
This school in Italy, Palermo, has a STEAM address where different aspects of computer science are studied.

The teachers' emails are: [cognome.nome@gonzagapalermo.it](mailto:cognome.nome@gonzagapalermo.it)

Those of the students: [cognome.nome@studenti.gonzagapalermo.it](mailto:cognome.nome@studenti.gonzagapalermo.it)

**Comment by ingmarcospina** [comment]
Here you can find the main page of the STEAM address for high-shool student in Gonzaga Campus Palermo: https://gonzagascuola.it/licei/liceo-scientifico-stem/

Let me know if anything else is needed.

**Comment by philipto** [comment]
@ingmarcospina First stage of verification passed, official domain for **Gonzaga Campus - Palermo** is [gonzagacampus.it](https://gonzagacampus.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@ingmarcospina Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by ingmarcospina** [comment]
@philipto there was a mistake because gonzagacampus.it is the official web-site but the e-mails for student and teachers are: 
The teachers' emails are: [cognome.nome@gonzagapalermo.it](mailto:cognome.nome@gonzagapalermo.it)

Those of the students: [cognome.nome@studenti.gonzagapalermo.it](mailto:cognome.nome@studenti.gonzagapalermo.it)

How can i solve it? Do you wanna me to make a new PR? Let me know

**Pull request merged**
