### PR TITLE
Create C2KNI.txt

### PR DESCRIPTION
**Pull request by DelxHQ**

### CODE REVIEW

**Comment by philipto** [comment]
@DelxHQ Could you please tell a bit more about C2KNI? How many schools it includes? How many of them are high schools? Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by DelxHQ** [comment]
C2k is a domain network for all schools in Northern Ireland. It has High schools and Primary schools
it is managed by the Education Authority on behalf of the Department of Education. I dont know how many schools are in the domain network. You can find their website here: http://www.c2kni.org.uk/index.htm

**Comment by philipto** [comment]
@DelxHQ Thank you! Do the high schools in Northern Ireland have their own websites? It's quite unusual for this repository to list a domain for the whole country or a large part of a country. We sometimes include district scools domains here, but avoid adding too general domains.

May I ask how many people from your school would like to have a free license? If there are just few of them, it can be solved differently, and still efficient and convenient. Thank you!

**Comment by DelxHQ** [comment]
Yes, all the schools have their own websites but all schools in Northern Ireland use @c2kni.net for their emails.  It is just me looking a free licence as far as i know.

**Comment by philipto** [comment]
@DelxHQ Pull request merged. Thank you!

**Pull request merged**
