### PR TITLE
Added LMUSD (Fixed)

### PR DESCRIPTION
**Pull request by Tylers31**

### CODE REVIEW

**Comment by philipto** [comment]
@Tylers31 First stage of verification passed, official domain is [aghseagles.org](https://aghseagles.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.aghseagles.org/apps/pages/index.jsp?uREC_ID=2108242&type=d&pREC_ID=2150294

**Comment by Tylers31** [comment]
Thanks!

**Comment by Tylers31** [comment]
Is this still under review?

**Comment by philipto** [comment]
@Tylers31 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
