### PR TITLE
Add Catolica SC

### PR DESCRIPTION
**Pull request by joaoneto147**

### CODE REVIEW

**Comment by joaoneto147** [comment]
The university official website URL is https://www.catolicasc.org.br/ however, the academics' emails are created with the catolicasc.edu.br domain

**Comment by philipto** [comment]
@joaoneto147 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@joaoneto147 You might miss my previous comment. Please react.

**Comment by joaoneto147** [comment]
> @ joaoneto147 Você pode perder meu comentário anterior. Por favor, reaja.

Hello how are you ? The domains are linked to the same person/institution, queries can be obtained in

https://registro.br/tecnologia/ferramentas/whois/?search=catolicasc.org.br

and
 https://registro.br/tecnologia/ferramentas/whois/?search=catolicasc.edu.br

Both are registered under the name of the institution FERJ - Fundação Educacional Regional Jaraguaense

Is this information from WHOIS br sufficient?

**Comment by philipto** [comment]
@joaoneto147 Thank you for the clarification. Pull request merged. I checked the profile of Fernando Cesar Rezende da Silva, and he is the person in the university in charge of the IT matters. Thank you.

**Pull request merged**
