### PR TITLE
Added Obafemi Awolowo University Domain

### PR DESCRIPTION
**Pull request by goke-epapa**
Addition of Obafemi Awolowo University Ile-Ife, Nigeria. Domain

### CODE REVIEW

**Comment by goke-epapa** [comment]
School Website - http://www.oauife.edu.ng
Emails are of the form - username@student.oauife.edu.ng

Thanks in advance

**Comment by goke-epapa** [comment]
@zweizwei Please merge this. 

Thanks

**Comment by zweizwei** [comment]
@goke-epapa sorry for the delay, merging the request

**Comment by goke-epapa** [comment]
Thanks @zweizwei  :)

**Pull request merged**
