### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ALIERIS-corp**

### CODE REVIEW

**Comment by philipto** [comment]
@ALIERIS-corp 
Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@ALIERIS-corp You might miss my previous comment. Please react.

**Comment by ALIERIS-corp** [comment]
I have looked it up but sadly I can't find any real proof that my school recognizes that domain, the third level domain is the same, but that's all, for the other two:

This is their website:
[http://www.pictorius.de/](url)

This is a link to the course
[https://www.pictorius.de/wp-content/uploads/2018/08/Berufliches-Gymnasium-Informatik.pdf](url)

**Comment by philipto** [comment]
@ALIERIS-corp Thank you for the clarification. Could you please find any kind of paper or online page which says that students can use this email domain? Regrettably, it's against our rules to add domains to the repository without any evidence that they really belong to the school. Please give it a try and find some.

**Comment by philipto** [comment]
@ALIERIS-corp You might miss my previous comment. Please react.

**Comment by ALIERIS-corp** [comment]
Yeah so I looked around some more and even asked a teacher at my school but still nothing...

**Comment by philipto** [comment]
@ALIERIS-corp Please ask any of your teacher or administrative staff member to write a notice saying that this domain belongs to the school and upload a photo of this notice to GitHub via web interface. It has to have a name of the person, a date and a signature. 

Alternatively, you can make a photo/screenshot of any document which contains this email address. If the school provides the students with the email addresses there must be some proof of any kind: internal guide, instruction, a notification to students, a message which was sent to a student by email, etc.

**Comment by philipto** [comment]
@ALIERIS-corp Pull request merged. I'll monitor the domain usage to ensure that no suspicious issues happened. I hope that everything will be fine. Thank you!

**Pull request merged**
