### PR TITLE
Rename ac-orleans-tous.txt to ac-orleans-tours.txt

### PR DESCRIPTION
**Pull request by Technowix**
Typo :)

### CODE REVIEW

**Comment by Uneo7** [comment]
http://www.ac-orleans-tours.fr/

**Comment by Technowix** [comment]
http://www.ac-orleans-tours.fr/

**Comment by philipto** [comment]
@Technowix Thank you, and sorry for the delay with the request processing! Pull request is now merged.

**Comment by Technowix** [comment]
Thanks @philipto ! :)

**Pull request merged**
