### PR TITLE
Add SFCC domain

### PR DESCRIPTION
**Pull request by ericspetersen**
https://www.sfcc.edu/
https://sfccssb.sfcc.edu/PROD/pw_pub_sched.p_listthislist?term_in=202430&subj_in=ISCS

### CODE REVIEW

**Comment by philipto** [comment]
@ericspetersen I have to close this request without merging, because you requested to add a non-existent domain to this repository: `` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by ericspetersen** [comment]
I don't understand why this is considered a non existent domain.  My school email address is eric.petersen@sfcc.edu and there is a DNS mapping for sfcc.edu.

**Comment by afdaniele** [comment]
@ericspetersen these checks seem to be automated and not very well done either. I have been trying to add ttic.edu to the list but got the same message twice, i.e., "non-existent domain". I don't know if we can trust the process here. If you find another way to add your school, please do share, and I'll do the same.

**Comment by philipto** [comment]
@ericspetersen I reopened the request, reviewed it, and it is certainly valid. I am sorry for a technical error that led to incorrect decision on the review. 

Thank you again @afdaniele for bringing the issue to my attention. 

Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
