### PR TITLE
Add Whitireiaweltec

### PR DESCRIPTION
**Pull request by gamespy24hr**
https://www.whitireiaweltec.ac.nz/

### CODE REVIEW

**Comment by philipto** [comment]
@gamespy24hr First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/PacificYouthNZ/

**Comment by gamespy24hr** [comment]
my school homepage is    https://www.whitireiaweltec.ac.nz/     It is a merger of two colleges.

and student's email format is   FirstName.LastName@whitireianz.ac.nz

**Comment by philipto** [comment]
@gamespy24hr Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by gamespy24hr** [comment]
please visit this Url , Thank you.

https://moodle.whitireia.ac.nz/mod/forum/discuss.php?d=26929

**Comment by philipto** [comment]
@gamespy24hr  Thank you for the clarifications. Pull request merged.

**Comment by gamespy24hr** [comment]
Thank you for your help.

**Pull request merged**
