### PR TITLE
NamSU add

### PR DESCRIPTION
**Pull request by mrmelhay**

### CODE REVIEW

**Comment by philipto** [comment]
@mrmelhay .github/workflows/blank.yml: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@mrmelhay .github/workflows/blank.yml: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@mrmelhay I removed unneeded files from your request and merged it. Everything is OK, you can request your free license in an hour. Thank you.

**Comment by mrmelhay** [comment]
Thank you @philipto.

**Pull request merged**
