### PR TITLE
Create ecoles-wis.txt

### PR DESCRIPTION
**Pull request by erredius**
Add french web School (WIS)

[http://www.wis-ecoles.com/](http://www.wis-ecoles.com/)

### CODE REVIEW

**Comment by philipto** [comment]
@erredius Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@erredius You might miss my previous comment. Please reply.

**Comment by erredius** [comment]
> @erredius You might miss my previous comment. Please reply.

Hi, I saw your response and I asked the direction of my school, but the they took much time to answere me.
I'm waiting for their proof to send it.

But if you want a proof, my school is in the same school group as [http://www.epsi.fr/](http://www.epsi.fr/) that you have already authorised.
All students have this email extension for Web International School.

Thank you for the interest

**Comment by Apautrizel** [comment]
domaine 2

Hi, 
I'm currently working for WIS school and to complete the demand of erredius, here is a proof of the domain. 
Our website & IT program : http://www.wis-ecoles.com/programme/le-bachelor/

Thanks,

**Comment by philipto** [comment]
@erredius @Apautrizel Thank you for the update! Pull request merged.

**Pull request merged**
