### PR TITLE
Add daepyong elementary school

### PR DESCRIPTION
**Pull request by minjunoreo**

### CODE REVIEW

**Comment by philipto** [comment]
@minjunoreo JetBrains does not generally recommend using professional software development tools in elementary school. Instead, you can use free community versions available to everyone - PyCharm Community Edition and IntelliJ IDEA Community. 

Could you please tell me why do you need the professional IDEs for elementary school? Children under 13 of age usually do not benefit from using more complex development tools. Community edition of the tools may be more than enough for them.

**Comment by cutiecys** [comment]
Four relatives from elementary, middle and high school gathered to form a website development project meeting.
There are 2 middle school students and 2 elementary school students, and although the main activities are 2 middle school students, elementary school 2 also has some work to do, so a student license is required.

1. School Web site URL : https://daepyong-e.goesw.kr/
2. Address : (16333) 111, Daepyeong-ro, Jangan-gu, Suwon-si, Gyeonggi-do, Republic of Korea
3. email domain : daepyonge.goe.go.kr

**Comment by qudansdl** [comment]
Four relatives from elementary, middle and high school gathered to form a website development project meeting.
There are 2 middle school students and 2 elementary school students, and although the main activities are 2 middle school students, elementary school 2 also has some work to do, so a student license is required.

1. School Web site URL : https://daepyong-e.goesw.kr/
2. Address : (16333) 111, Daepyeong-ro, Jangan-gu, Suwon-si, Gyeonggi-do, Republic of Korea
3. email domain : daepyonge.goe.go.kr

**Comment by philipto** [comment]
@minjunoreo Thank you for the clarification. Pull request merged.

**Pull request merged**
