### PR TITLE
Create acischools.txt

### PR DESCRIPTION
**Pull request by simitbey**
ACI Student Secondary Domain

### CODE REVIEW

**Comment by simitbey** [comment]
Açı High School uses 2 types of domains for different students.
stu.acischools.k12.tr for students enrolled after 2020
acischools.k12.tr for students enrolled pre 2020

**Comment by simitbey** [comment]
Açı High School uses 2 types of domains for different students.
stu.acischools.k12.tr for students enrolled after 2020
acischools.k12.tr for students enrolled after 2020

**Comment by philipto** [comment]
@simitbey First stage of verification passed, official domain is [acischools.k12.tr](https://acischools.k12.tr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@simitbey Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by simitbey** [comment]
thanks :)

**Pull request merged**
