### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by Alexander8490**
Please, add my University
[file.zip](https://github.com/user-attachments/files/17557757/file.zip)

### CODE REVIEW

**Comment by philipto** [comment]
@Alexander8490 docs/pull_request_template.md: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Alexander8490 Do you need to add the domain lajm.lt? Does your email address ends with @lajm.lt?
If yes, please create the file named `lib/domains/lt/lajm.txt` and containing the only name of the school, like this:
```
Lithuanian Maritime Academy
```
Thank you!

**Comment by philipto** [comment]
@Alexander8490 I have to close this request as not following [the rules](https://github.com/JetBrains/swot#swot) at all.

**Comment by Alexander8490** [comment]
Hello, yes, but I don't know how to create it.

joi, 31 oct. 2024, 13:30 Philip Torchinsky ***@***.***> a
scris:

**Pull request closed without merging**
