### PR TITLE
added jyoti nivas college bangalore

### PR DESCRIPTION
**Pull request by ChrolloKryber**

### CODE REVIEW

**Comment by philipto** [comment]
@ChrolloKryber Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by ChrolloKryber** [comment]
- official website : https://www.jyotinivas.org 
- school address : KHB Colony, 5th Block, Koramangala, Bengaluru, Karnataka, India
- IT Related course : https://www.jyotinivas.org/dep_computer_science_applications.php (3 year long Bachelors of Computer Applications)

I'm not really sure what i can provide as a proof for domain recognization

**Comment by ChrolloKryber** [comment]
image
I hope this works as a proof

**Comment by ChrolloKryber** [comment]
Hi @philipto can you go through the info I provided

**Comment by philipto** [comment]
@ChrolloKryber Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Comment by ChrolloKryber** [comment]
thanks for the help!

**Pull request merged**
