### PR TITLE
Add MLS

### PR DESCRIPTION
**Pull request by aquestry**

### CODE REVIEW

**Comment by philipto** [comment]
@aquestry The first verification stage is complete: the official domain for  **Martin Luther Schule Rimbach** is [mls-rimbach.de](https://mls-rimbach.de), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://mls-rimbach.de/office365/

**Comment by aquestry** [comment]
Yes that ist corret, but the E-Mails are with the Domain MLS.kbs.schule

**Comment by aquestry** [comment]
mls.kbs.schule will redirect to mls-rimbach.de in a Browser

**Comment by philipto** [comment]
@aquestry The first verification stage is complete: the official domain for  **Martin Luther Schule Rimbach** is [mls-rimbach.de](https://mls-rimbach.de), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://mls-rimbach.de/office365/

**Pull request merged**
