### PR TITLE
American International School of Budapest

### PR DESCRIPTION
**Pull request by Arthurgallaxy**
#### Institution/School Name 
American International School of Budapest

#### Instiution/School Website
https://www.aisb.hu/

#### Email Users
@student.aisb.hu
@aisb.hu
*Please place an x between the square brackets if yes*
- [x] Students
- [x] Academic/Teaching Staff

- [x] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [ ] Graduate School
- [ ] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [x] High School or equivalent
- [x] Elementary School or equivalent

Screenshot 2022-10-04 093220

### CODE REVIEW

**Comment by philipto** [comment]
@Arthurgallaxy lib/domains/hu/aisb/Screenshot: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Arthurgallaxy** [comment]
@philipto I can just remove the screen shot that not an issue, its just on the instructions, under the "How to add the domain quicker" it said a pdf or screenshot was ok, although I suppose that should be in the comment rather than the actual commit so I will edit that real quick

**Comment by philipto** [comment]
@Arthurgallaxy First stage of verification passed, official domain is [aisb.hu](https://aisb.hu) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Arthurgallaxy Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
