### PR TITLE
Added McDaniel College Budapest

### PR DESCRIPTION
**Pull request by omegion**
## Institution/School Name
McDaniel College Budapest

## Instiution/School Website
https://mcdaniel.hu/

## Email Users
- [x] Students
- [x] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

## Education Levels
- [ ] Post-graduate research
- [ ] Graduate School
- [x] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [ ] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by omegion** [comment]
@philipto Can you please check this college 🙏🏼

**Comment by philipto** [comment]
@omegion First stage of verification passed, official domain is [mcdaniel.hu](https://mcdaniel.hu) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by nataershova** [comment]
Hi @omegion, could you please send us the URL of a page on the official website where the school offers an IT-related long-term (>1 year) course?

Thank you.

**Comment by omegion** [comment]
Hi @nataershova,

Thanks for your reply. [McDaniel College's Economics major](https://mcdaniel.hu/majors/business-administration-economics/) offers financial markets courses and statistics. We study international financial market simulations and create projects around stock markets. The projects require coding and we would like to use IntelliJ products for this purpose.

We also create R projects for statistical computing for our Statistics courses. We heavily depend on R language for plotting as well. We already use `R Language Plugin` which we find pretty useful.

Please find the following courses which involve projects that require coding and simulations:
- ECO 4310 Money and Financial Markets
- STA 2215 Elementary Statistics for Social Science

Bests,
Balint

**Pull request merged**
