### PR TITLE
Create mt.txt

### PR DESCRIPTION
**Pull request by CarlosFreitasR**

### CODE REVIEW

**Comment by philipto** [comment]
@CarlosFreitasR Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@CarlosFreitasR You might miss my previous comment. Please react.

**Comment by CarlosFreitasR** [comment]
https://www.fatecsenaimt.ind.br/
Av. XV de Novembro, 303 - Porto, Cuiabá - MT, Brasil, 78020-300
https://www.fatecsenaimt.ind.br/nossos-cursos?c=analise-e-desenvolvimento-de-sistemas
image

**Comment by philipto** [comment]
@CarlosFreitasR Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
