### PR TITLE
Added iu-akademie.txt

### PR DESCRIPTION
**Pull request by ChristophKronberger**
Some ohter Email from the IU Internationale Hochschule GmbH are already in the repository.
The Email i have added is for persons who make a courses instead of complete Bachelor degree.

### CODE REVIEW

**Comment by ChristophKronberger** [comment]
Official website: https://www.iu-akademie.de/

**Comment by philipto** [comment]
@ChristophKronberger This page (https://www.iu.de/en/news/premiere-subsidised-online-further-training-at-the-university-level/) says that the courses last 4,5 months. Is it correct? If yes, the course attendants are not eligible for one year license because the course is shorter than 1 year.

Please clarify.

**Comment by ChristophKronberger** [comment]
It depends on the course, as an example https://www.iu-akademie.de/weiterbildungen/software-development-expert/ this course last at least 8 Month

**Comment by philipto** [comment]
@ChristophKronberger  Thank you for the clarifications. Pull request merged. Please notice that the free educational license is for educational purpose only. It means that after completing the course you are no longer eligible for a free license, unless you are taking another course. Also, you are eligible for a graduation discount after your free license expires and the courses are completed.

**Pull request merged**
