### PR TITLE
Add EDHEC Business School

### PR DESCRIPTION
**Pull request by fidelio314**
Add EDHEC Business School (https://www.edhec.edu)

### CODE REVIEW

**Comment by philipto** [comment]
@fidelio314 Please provide us with a proof, which shows that the school recognizes the domain edhec.fr that you are submitting as an official email domain for the students.

You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@fidelio314 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@fidelio314 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by fidelio314** [comment]
hello @philipto sorry for the waiting? i didn't saw you messages.
this is one of the pages indexing the publications of the school: https://www.edhec.edu/fr/recherche-et-faculte/centres-et-chaires/chaire-prevision-innovation-et-transformation/publications

here is one the articles : https://www.tandfonline.com/doi/abs/10.1080/13675567.2022.2088707
on "Exploration of barriers and enablers of blockchain adoption for sustainable performance: implications for e-enabled agriculture supply chains"

the author is: Sachin S. Kamble with the email: Sachin.kamble@edhec.edu

**Pull request closed without merging**
