### PR TITLE
Create loznickagimnazija.txt

### PR DESCRIPTION
**Pull request by dragiceviccv**
https://www.loznickagimnazija.edu.rs/

### CODE REVIEW

**Comment by philipto** [comment]
@dragiceviccv Please provide us with:
- the school official website URL
- the school street address, including city and country

**Comment by philipto** [comment]
@dragiceviccv You might miss my previous comment. Please react.

**Comment by dragiceviccv** [comment]
Hey, sorry, I totally missed it!

https://www.loznickagimnazija.edu.rs
Gimnazijska 5, 15300 Loznica, Serbia

**Comment by philipto** [comment]
@dragiceviccv Thank you for the update! Pull request merged.

**Pull request merged**
