### PR TITLE
Add Temasek Polytechnic (TP)

### PR DESCRIPTION
**Pull request by KenKwek**
Adding Temasek Polytechnic, an Institute of Higher Learning in Singapore

### CODE REVIEW

**Comment by JvP631** [comment]
Hi @philipto 

Below is the detail for Temasek Polytechnic in Singapore:
Official website: https://www.tp.edu.sg
Street Address: 21 Tampines Avenue 1, Singapore 529757
IT-related long-term courses: https://www.tp.edu.sg/courses/full-time-courses/diplomas-by-schools#school-of-informatics--it
Proof of the official email domain for the student: https://www.tp.edu.sg/student-life/smart-campus/byod#tab8

For your review, please. Thank you~

Regards,
JvP

**Comment by KenKwek** [comment]
Dear @JvP631,

Thank you for helping to find and provide the details for Temasek Polytechnic.

With Regards,
KenKwek

**Comment by philipto** [comment]
@KenKwek @JvP631 Pull request merged. Thank you!

**Comment by JvP631** [comment]
No problem, @KenKwek.
Thanks @philipto.

**Pull request merged**
