### PR TITLE
Add Egypt Minstiry of Education Sohag schools

### PR DESCRIPTION
**Pull request by KyriakosMilad**

### CODE REVIEW

**Comment by philipto** [comment]
@KyriakosMilad You might miss my previous comment. Please react.

**Comment by KyriakosMilad** [comment]
Hi @philipto 

let me first describe the online educational system in Egypt:
There is no email nor domain for every school but for every region in the country, For example, the email I provided is for the north Sohag schools
You can check in the same directory [eg/edu/moe] that other students have added other regions.

Please check this page, [https://office365.emis.gov.eg/] it's not available in English, but you can translate it into English using Google Translate.

- the school official website URL: https://moe.gov.eg/en/
- the school street address, including city and country: Tahrir ST, Tahta, Sohag, Egypt
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: They didn't list the subjects we take on their website.
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
- You can provide us with any of the following as the proof: https://office365.emis.gov.eg/

- A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain: I wasn't provided with such a thing.
- An URL of a page on the official school website that says that students use this email domain: https://office365.emis.gov.eg/

**Comment by KyriakosMilad** [comment]
Hi @philipto 
Any updates?

**Comment by philipto** [comment]
@KyriakosMilad Thank you for your patience! This is a serious issue, and we have to consider all aspects of it. In general we do not add any umbrella institutions domains to this repository, such as Ministry of Education or similar government bodies. We'll have to discuss your case specifically as soon as possible. We must weight risks of some email addresses leaking to third parties, and importance of making the tools accessible for a wide audience of teenage students.

Could you please tell us what is your estimation of total number of students who will request JetBrains tools with their email addresses ended with @sohag2.moe.edu.eg?

**Comment by KyriakosMilad** [comment]
@philipto Thanks for your response. Total students using this domain for email addresses about 30K based on my calculations about 20 schools multiplied by average students count per school (1500), I don't know how many exactly would apply for Intilij idea education pack, I don't think many students will apply since its been a long time and no one even made PR to add this email domain. Maybe 100 per year or even less.

**Comment by philipto** [comment]
@KyriakosMilad Thank you for the clarification and your patience while waiting for a review and processing your request! Pull request merged. We'll monitor the usage and if something suspicious appears, we'll contact you as soon as we can.

Please start requesting the licenses in an hour from now to let the changes to propagate through the systems.

**Comment by KyriakosMilad** [comment]
Thanks @philipto

**Comment by KyriakosMilad** [comment]
If there are any questions just let me know, not just this, but with any Egyptian school/university I will be happy to help and contribute to this repo.

**Pull request merged**
