### PR TITLE
Adding Universidad Politécnica de Sinaloa

### PR DESCRIPTION
**Pull request by ffigueroa0212**

### CODE REVIEW

**Comment by philipto** [comment]
@ffigueroa0212 First stage of verification passed, official domain is [upsin.edu.mx](https://upsin.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by ffigueroa0212** [comment]
Some update for this?

**Comment by philipto** [comment]
@ffigueroa0212 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by ffigueroa0212** [comment]
Thanks!

**Pull request merged**
