### PR TITLE
Add Shih Chien University new domain

### PR DESCRIPTION
**Pull request by joe94113**
#### Institution/School Name 
Shih Chien University

#### Instiution/School Website
[https://www.usc.edu.tw/](https://www.usc.edu.tw/)

#### Email Users

*Please place an x between the square brackets if yes*
- [x] Students
- [ ] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [ ] Graduate School
- [x] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [ ] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by philipto** [comment]
@joe94113 First stage of verification passed, official domain is [usc.edu.tw](https://usc.edu.tw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@joe94113 Pull request merged. Thank you.

**Comment by EEIT10204** [comment]
@joe94113 您好! 我的學校信箱domain是@gm.usc.edu.tw , 想申請JetBrains的學生帳號
我做了pull request -> https://github.com/JetBrains/swot/pull/16128
想了解現在是不是等待官方合併就可以? 
謝謝!

**Comment by joe94113** [comment]
@EEIT10204 對沒錯，等待官方合併即可，大約一至兩天的時間

**Comment by EEIT10204** [comment]
@joe94113 謝謝回覆!!

**Pull request merged**
