### PR TITLE
Create hedmark

### PR DESCRIPTION
**Pull request by GisliNielsen**

### CODE REVIEW

**Comment by philipto** [comment]
@GisliNielsen Could you please: 1) confirm that your commune does not have dedicated email for schools, such as edu.hedmark.org or similar, and 2) rename lib/domains/org/hedmark to lib/domains/org/hedmark.txt. Thank you.

**Comment by philipto** [comment]
@GisliNielsen You might miss my previous comment. Please reply.

**Comment by GisliNielsen** [comment]
Currently on vacation, there is no dedicated emails for the schools.

**Comment by philipto** [comment]
@GisliNielsen Thank you for the clarification. OK, I'll merge the request and rename the file for you, it'll take a bit more time than usual, but tomorrow it shall work normally, feel free to request the license. Please note that the free license is for educational purpose, for teachers and students only.

**Pull request merged**
