### PR TITLE
add alunocea.txt

### PR DESCRIPTION
**Pull request by joseferrao**

### CODE REVIEW

**Comment by joseferrao** [comment]
add alunocea.txt

**Comment by philipto** [comment]
@joseferrao You might miss my previous comment. Please react.

**Comment by joseferrao** [comment]
Hello


   - the school official website URL: https://www.espacoaberto.com.br
   - the school street address, including city and country: Rua Bento
   Albuquerque, 1671 - Cocó, Fortaleza / Ceará
   - an URL of a page on the official website where the school offers an
   IT-related long-term (>1 year) course: My children study at this school,
   where in high school, there is an optional science course focused on
   programming. It is used to support students in which career to pursue,
   being able to choose humanities, exact sciences and social sciences.
   - a proof, which shows that the school recognizes the domain you are
   submitting as an official email domain for the students: The email domain
   is separate from the website domain, the email service and all resources
   are provided by Google.

[image: image.png]


José F

**Comment by philipto** [comment]
@joseferrao  Thank you for the clarifications. Pull request merged.

**Pull request merged**
