### PR TITLE
add new institute domain

### PR DESCRIPTION
**Pull request by arellanogonz**
add new institute domain

### CODE REVIEW

**Comment by philipto** [comment]
@arellanogonz First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/iclasalle/posts/conoce-la-colegiatura-y-descubre-el-proceso-de-admisi%C3%B3n-para-preescolar-d-solo-t/2850729131610035/

**Comment by arellanogonz** [comment]
If you need more information about the school, let me know.

Have a nice day.

**Comment by nataershova** [comment]
@arellanogonz Hi, 

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.  You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

Thank you!

**Comment by philipto** [comment]
@arellanogonz Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
