### PR TITLE
Create student.txt

### PR DESCRIPTION
**Pull request by tobitoi**
add Atma Jaya Makassar University

### CODE REVIEW

**Comment by philipto** [comment]
@tobitoi First stage of verification passed, official domain is [uajm.ac.id](https://uajm.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@tobitoi The website of the relevant department - https://fti.uajm.ac.id/index.html - seems to have outdated information, referring to documents dated back to 2015-2020. Is there any updates on the Faculty of Information Technology, which are more recent? Did not the school close the faculty already?

**Comment by philipto** [comment]
@tobitoi You might miss my previous comment. Please react.

**Comment by tobitoi** [comment]
> @tobitoi The website of the relevant department - https://fti.uajm.ac.id/index.html - seems to have outdated information, referring to documents dated back to 2015-2020. Is there any updates on the Faculty of Information Technology, which are more recent? Did not the school close the faculty already? 
> 
> 

The website not up to date yet but you can access https://ssfti.uajm.ac.id

**Comment by philipto** [comment]
@tobitoi The website you have mentioned does not allow to access it without login:

image

Doesn't your school have a publicly accessible website with information on the courses?

Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@tobitoi You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@tobitoi I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
