### PR TITLE
added kpc

### PR DESCRIPTION
**Pull request by dissicisea**

### CODE REVIEW

**Comment by philipto** [comment]
@dissicisea I am sorry, the domain for Khmelnitsky Polytechnic College is hpk.edu.ua, and the file `lib/domains/ua/km/kpc.txt` represents a domain kpc.km.ua, which does not exist. If you wish to add hpk.edu.ua, please rename the file to `lib/domains/ua/edu/hpk.txt`. Thank you!

**Comment by philipto** [comment]
@dissicisea Thank you for the quick change, but the filename has to be `lib/domains/ua/edu/hpk.txt`, not `lib/domains/ua/km/edu/hpk.txt`. Please remove unnecessary subdirectory "km" from there.

**Comment by dissicisea** [comment]
@philipto i've renamed, but i have question about jetbrains student license. is any another way to get license if my college doesn't have own e-mail service for students? answer, if you know

**Comment by philipto** [comment]
@dissicisea Yes, there are three other options. If your college does not provide students with email addresses in hpk.edu.ua domain, adding this domain to this repository does not make any sense. If students of your college don't have emails like xxx@hpk.edu.ua, please DO NOT add this domain to this repository.

Other options to get free licenses from JetBrains are:
1) ask your teacher to request classroom licenses from JetBrains by email to classroom@jetbrains.com
2) request the licenses using your ISIC card at jetbrains.com/student (if you have ISIC card)
3) send an email to sales@jetbrains.com and attach a photo of your student ID ("студенческий билет") where we can see that it is valid (i.e., not expired).

Requesting a license using your student email obtained from the university is the fastest and simplest way.

Please respond whether students at your college have emails in hpk.edu.ua domain, and I'll merge this request if yes.

Thank you!

**Comment by dissicisea** [comment]
@philipto college completely does not provide students with e-mail. so, yes, no reason for creating this domain. excuse for troubling and thank you for help

**Pull request closed without merging**
