### PR TITLE
School verification

### PR DESCRIPTION
**Pull request by stss15**

### CODE REVIEW

**Comment by philipto** [comment]
@stss15 file/lib/domains/com/stgeorgesschool.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@stss15 First stage of verification passed, official domain for **St George's British International Schools (Dusseldorf)** is [stgeorgesschool.com](https://stgeorgesschool.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@stss15 I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host stgeorgesschool.edu not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by stss15** [comment]
Hi can I just double check the domain is stgeorgesschool.com not .edu.

Thanks Steve

**Pull request closed without merging**
