### PR TITLE
Added ostfoldfk (for Østfolk Fylkeskommune school domain name)

### PR DESCRIPTION
**Pull request by DoggyCode**
Added Østfolk Fylkeskommune school domain name.

### CODE REVIEW

**Comment by DoggyCode** [comment]
https://utdanning.ostfoldfk.no/ikbViewer/page/open/forsiden 

Utdanning = education
Forsiden = front page

**Comment by philipto** [comment]
@DoggyCode Could you please clarify which email addresses the students and teachers in the school have? Is their email domain ostfoldfk.no, or there are more specific domains such as stud.ostfoldfk.no, etc.?

**Comment by DoggyCode** [comment]
@philipto A student's would be yourname@ostfoldfk.no, this also accounts for teachers. I should have set it up appropriately. 

yourname could be some of your first name and some of your last name. For example, mine is marius**@ostfold.fk and one of my teacher's is mar***3@ostfoldfk.no . ** is representing last name initials, as i don't want to publish their emails open here :)

**Comment by philipto** [comment]
@DoggyCode I am sorry, I accidentally merged the pull request and then noticed that the file path is incorrect: lib/domains/no/ostfoldfk instead of lib/domains/no/ostfoldfk.txt. Could you please make a new request, and I'll merge it as soon as possible. Thank you!

**Comment by DoggyCode** [comment]
@philipto I have created a new Pull Request: https://github.com/JetBrains/swot/pull/2733

**Pull request merged**
