### PR TITLE
Added my school

### PR DESCRIPTION
**Pull request by johand199**
Website: ostfoldfk.no

### CODE REVIEW

**Comment by philipto** [comment]
@johand199 I am sorry, it looks like the email domain is used by all people working in some civil service at the community, not just the community schools students and teachers. Could you please add more speciifc domain (such as students.ostfoldfk.no, if it exists)? If not, I doubt that we can add the domain to this repository: it is for colleges and universities only. Please clarify the issue in the comment. Thank you!

**Comment by johand199** [comment]
sorry for late responce, here is the subdomain for student login and teachers; utdanning.ostfoldfk.no

The only problem is we dont use that subdomain as an email domain. Example my email is; johanan@ostfoldfk.no

**Comment by johand199** [comment]
If you need further evidence as my student ID card warn me and ill send it to you

**Comment by philipto** [comment]
@johand199 Thank you for the clarification. Still, we can not add the domain to the repository under this circumstances. There are two options for you to get free license: 1) write an email to sales@jetbrains.com and explain the situation - they issue the license for you only. If there are other students who wish to use JetBrains tools, it's better to ask a teacher to apply for classroom license by email to classroom@jetbrains.com; they will be glad to issue one for your school.

I am closing this request without merging, thank you for your understanding.

**Pull request closed without merging**
