### PR TITLE
Create entea.txt

### PR DESCRIPTION
**Pull request by binksxela**

### CODE REVIEW

**Comment by binksxela** [comment]
I forgot to comment the pull request so here it is

### Entea.fr
**School Website URL** : http://www.lyc-pasteur-strasbourg.ac-strasbourg.fr/
Entea.fr is where students of this school can see their results, their homework, and they also have a mail with this format: firstname.lastname@entea.fr
**(entea.fr is down between the 20th and 22th as announced on the site)**
**Proof that the school use entea.fr service for their students: https://i.imgur.com/tqjN1R5.png**

### Proof that its related to IT:

Go on school website then go on "Enseignements" then "Les formations" then "Seconde" then "enseignements d'exploration" then it will redirect you there : **https://prezi.com/hmboly4qikex/enseignements-dexploration/**
Click on **Transcription complète** then you will see all the way down : 

"Informatique
et création numérique
(1h30)
Découvrir la science informatique qui se cache derrière les pratiques numériques quotidiennes, à travers des activités pratiques menées en groupe; utilisation de différents outils tels qu'éditeur de texte, navigateur web, logiciel de retouches d'images, programmation, …"

in English : 

"**Informatics
and digital creation
(1h30)
Discover the computer science behind everyday digital practices, through practical group activities; use of different tools such as text editor, web browser, image editing software, programming,...**"

**Comment by philipto** [comment]
@binksxela If I am not mistaken, entea.fr is the website which provides a broad range of organizations with IT service. Could you please clarify if all of the organizations there are related to your college, or there are many colleges using the email domain? If there are many of them, could you please tell us how many?

**Comment by binksxela** [comment]
@philipto entea.fr is used by many colleges so that students can check their exam results, homework, etc. and they also have an email there, I don't know how many because if I'm right entea.fr is used by several regions but certainly not by just one institution.

**Comment by philipto** [comment]
@binksxela Thank you for the clarification! I am afraid, I can not add this domain to this repository, because for me it is impossible to identify and remain sure which exact institutions (and how many of them) use this domain, what policy is applied with regard to assigning email addresses to people there, etc. 

Please request your free license for students in this domain by email to classroom-support@jetbrains.com. 

I have to close this request without merging.

**Comment by binksxela** [comment]
@philipto classroom-support@jetbrains.com email doesn't exist

**Pull request closed without merging**
