### PR TITLE
add ip.mpg.de - Planck Institute for Innovation and Competition

### PR DESCRIPTION
**Pull request by SbstnErhrdt**
The Max Planck Institute for Innovation and Competition (ip.mpg.de) is a member of the Max Planck Society.

Website: https://www.ip.mpg.de/en/

### CODE REVIEW

**Comment by philipto** [comment]
@SbstnErhrdt First stage of verification passed, official domain is [ip.mpg.de](https://ip.mpg.de) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@SbstnErhrdt The institute looks purely research one. Please notice that the educational license is exclusively intended for educational purposes. Does the institute have any students (such as PhD students, for example) who study in the institute?

**Comment by SbstnErhrdt** [comment]
There are at least 30+

Here u go:
https://www.ip.mpg.de/en/persons.html?tx_epxipmpg_person%5Bsword%5D=&tx_epxipmpg_person%5BpersonFieldOfAction%5D=54&tx_epxipmpg_person%5BresearchArea1%5D=&tx_epxipmpg_person%5BresearchArea2%5D=#form

https://www.ip.mpg.de/en/persons.html?tx_epxipmpg_person%5Bsword%5D=&tx_epxipmpg_person%5BpersonFieldOfAction%5D=2&tx_epxipmpg_person%5BresearchArea1%5D=&tx_epxipmpg_person%5BresearchArea2%5D=#form

**Comment by SbstnErhrdt** [comment]
@philipto

**Comment by SbstnErhrdt** [comment]
Thanks @philipto

**Comment by philipto** [comment]
@SbstnErhrdt Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

Please notice that the educational license is exclusively intended for educational purposes. If any employees of the Institute who are not students or teachers need the license, please kindly instruct them to email [sales@jetbrains.com](mailto:sales@jetbrains.com) to request an academic discount for a paid license.

**Pull request merged**
