### PR TITLE
lInternational University of Kuwait (IUK)

### PR DESCRIPTION
**Pull request by mnboot**
University official website: https://www.iuk.edu.kw/

Location: [Kuwait, Ardiya](https://maps.app.goo.gl/SNZyUoas2UT3j4hy5)

Proof of the university having an IT major: https://www.iuk.edu.kw/computer-and-cyber-department and https://dev-iuk-website.euwest01.umbraco.io/media/1tcnnztr/computer-science-cyber-security-study-plan.pdf

Note: I have already created pull request for AASU university, which is my university, but IUK is my friend's University

### CODE REVIEW

**Comment by mnboot** [comment]
by the way I have accidentally typed "**lInternational** University of Kuwait" instead of "International University of Kuwait" so could you please edit and fix it

**Comment by ScreamMaster1337** [comment]
❤️

**Comment by philipto** [comment]
@mnboot First stage of verification passed, official domain for **International University of Kuwait** is [iuk.edu.kw](https://iuk.edu.kw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@mnboot Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.** Thank you.

**Pull request merged**
