### PR TITLE
add school

### PR DESCRIPTION
**Pull request by jiyegege**
Plese add ChongQing Unversity Of Education,Thankes

### CODE REVIEW

**Comment by philipto** [comment]
@jiyegege Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@jiyegege You might miss my previous comment. Please react.

**Comment by jiyegege** [comment]
hello
sorry,I did not respond in time.
1. Our university official website URL is [http://www.cque.edu.cn/](url)
2.In this page [http://www.cque.edu.cn/sxx/zysz/jsjkxy.htm](url).Introduced training programs related to computer science and technology, including programming (java), database design, etc.
3.In this picture is the main page of our student mail.  Since our school is an educational mailbox established through cooperation with Tencent, the email domain is not the same as the domain name I submitted.  However, the main interface of the email displayed in my screenshot has our school logo, so it should be able to prove it.
[https://drive.google.com/file/d/1h4Y79oZa-HOfmz3XeZfMTNZ6t3nYtIL5/view?usp=sharing](url)
thanks

**Comment by philipto** [comment]
@jiyegege Thank you very much for the clarification! Your screenshot shows an email in a domain stu.cque.edu.cn, not cque.com. If your email ends with @stu.cque.edu.cn, please rename the file in your request to lib/domains/cn/edu/cque/stu.txt

Thank you!

**Pull request merged**
