### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by duzgundogan**

### CODE REVIEW

**Comment by philipto** [comment]
@duzgundogan Please provide us with an URL of a page or another proof showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@duzgundogan You might miss my previous comment. Please react.

**Comment by duzgundogan** [comment]
duzgundogan@ttmail.com

 

This domain doesn’t belong to the university. This is my private mail account.

The faculty which I am studying does not give mail addresses to the students.

I can send you my university ID card and a formal updated digitally signed document by the university that states clearly my position (student certificate). 

You can verify the document from the following link :

https://www.turkiye.gov.tr/belge-dogrulama

 

 

I hope all these information are enough for your procedures.

 

Regards

 

Duzgun DOGAN

**Comment by duzgundogan** [comment]
duzgundogan@ttmail.com

 

This domain doesn’t belong to the university. This is my private mail account.

The faculty which I am studying does not give mail addresses to the students.

I can send you my university ID card and a formal updated digitally signed document by the university that states clearly my position (student certificate). 

You can verify the document from the following link :

https://www.turkiye.gov.tr/belge-dogrulama

 

 

I hope all these information are enough for your procedures.

 

Regards

 

Duzgun DOGAN

**Comment by philipto** [comment]
@duzgundogan Thank you for the details! 

You don't need to add your private email account domain to this repository. This domain does not belong to a university, nor to a college. I have to close this request without merging. 

Please apply at https://www.jetbrains.com/shop/eform/students with official document ("OFFICIAL DOCUMENT" tab).

**Pull request closed without merging**
