### PR TITLE
Add IGTI (XP Educacao) domain

### PR DESCRIPTION
**Pull request by ghdeassis**

### CODE REVIEW

**Comment by philipto** [comment]
@ghdeassis First stage of verification passed, official domain is [br.linkedin.com](https://br.linkedin.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://br.linkedin.com/in/marcosfc

**Comment by philipto** [comment]
@ghdeassis Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by ghdeassis** [comment]
@philipto IGTI was bought by "XP Educação", the old url (https://igti.com.br/) is now redirected to:
- https://www.xpeducacao.com.br/ 
- Address: R. Roma, 561 - Santa Lúcia, Belo Horizonte - MG, 30360-680, Brazil
- The college offers bachelor degrees' courses and MBA courses as well, for example:
- https://www.xpeducacao.com.br/graduacao/sistemas-de-informacao
- https://www.xpeducacao.com.br/graduacao/analise-e-desenvolvimento-de-sistemas
- One article showing the process of acquirement: 
- https://www.moneytimes.com.br/xp-inc-compra-igti-e-entra-no-mercado-de-ensino-superior/

**Comment by philipto** [comment]
@ghdeassis First stage of verification passed, official domain is [xpeducacao.com.br](https://xpeducacao.com.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.xpeducacao.com.br/cpa

**Comment by philipto** [comment]
@ghdeassis Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
