### PR TITLE
Add Colégio Vitória Régia from file

### PR DESCRIPTION
**Pull request by marcosvieirajr**

### CODE REVIEW

**Comment by philipto** [comment]
@marcosvieirajr lib/domains/net/colegiovitoriaregia.net: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by marcosvieirajr** [comment]
> @marcosvieirajr lib/domains/net/colegiovitoriaregia.net: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.

The fix was made. Thank you, @philipto !

**Comment by philipto** [comment]
@marcosvieirajr The first verification stage is complete: the official domain for  **Colégio Vitória Régia** is [www.vitoriaregia.net](https://www.vitoriaregia.net), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.vitoriaregia.net/equipe-pedagogica/

**Comment by philipto** [comment]
@marcosvieirajr Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
