### PR TITLE
Create schulen-hannover

### PR DESCRIPTION
**Pull request by xRealNeon**
Association of several schools from [Hanover](https://de.wikipedia.org/wiki/Hannover) which are at high school level. https://www.schulen-hannover.de

### CODE REVIEW

**Comment by philipto** [comment]
@xRealNeon lib/domains/de/schulen-hannover: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by xRealNeon** [comment]
Sorry my bad.

**Comment by philipto** [comment]
@xRealNeon First stage of verification passed, official domain is [schulen-hannover.de](https://schulen-hannover.de) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@xRealNeon Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
