### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sayantaniojha**
https://www.geomar.de

### CODE REVIEW

**Comment by sayantaniojha** [comment]
https://www.geomar.de

**Review by sayantaniojha — COMMENTED** [review]
https://www.geomar.de

**Comment by philipto** [comment]
@sayantaniojha First stage of verification passed, official domain is [geomar.de](https://geomar.de) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@sayantaniojha JetBrains does not provide free licenses to research centers. The free educational licenses are for teachers and students only. Could you please confirm that the center has a significant number of students, and provides some IT-related long-term courses (one year or longer)? If yes, please reply with an URL of the course page.

Thank you!

**Comment by philipto** [comment]
@sayantaniojha I have to close the request without merging. If you have an update, please reopen the request or send an email to community-support@jetbrains.com.

**Pull request closed without merging**
