### PR TITLE
Add BORG Eisenerz

### PR DESCRIPTION
**Pull request by MaxiHuHe04**
High school in Eisenerz, Austria

### CODE REVIEW

**Comment by philipto** [comment]
@MaxiHuHe04 First stage of verification passed, official domain is [borg-eisenerz.at](https://borg-eisenerz.at) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@MaxiHuHe04 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. The school seems to be a sport school, not an IT college.

**Comment by MaxiHuHe04** [comment]
Oh, I'm sorry. I did this for my sister and thought the IT course would be longer, but apparently it is just for one year.

**Comment by philipto** [comment]
@MaxiHuHe04 Yes, one year course is also fine. What is the URL of the course page?

**Comment by MaxiHuHe04** [comment]
It's right that it is not the main focus of the school. That's why it is not advertised much and you can only find it on this table which shows the lessons per week: https://borg-eisenerz.at/index.php/bildungsangebot/kreativzweig/stundentafel. _Informatik_ is IT.

**Comment by philipto** [comment]
@MaxiHuHe04 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
