### PR TITLE
Add Templemore College of Further Education, https://www.tcfe.ie

### PR DESCRIPTION
**Pull request by cj-kennedy-tcfe**

### CODE REVIEW

**Comment by philipto** [comment]
@cj-kennedy-tcfe Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by cj-kennedy-tcfe** [comment]
Hi,

1 ) The schools official website url is https://www.tcfe.ie
2) Templemore College of Further Education
    Richmond,
   Templemore,
   Co. Tipperary
   E41 FF98

________________________________

**Comment by cj-kennedy-tcfe** [comment]
Hi,

1 ) The school's official website url is https://www.tcfe.ie<https://www.tcfe.ie/>
2) Templemore College of Further Education
    Richmond,
   Templemore,
   Co. Tipperary
   E41 FF98
    Ireland
    Contact Us – Templemore College (tcfe.ie)<https://www.tcfe.ie/contact-us/>

3 ) Software Development 5M0529 – Templemore College (tcfe.ie)<https://www.tcfe.ie/software-development/>
4 ) I am sending this message via my school email ***@***.*** - We log in via office 365, but it uses @student.tcfe.ie as you can see in this reply.

Regards

________________________________

**Comment by philipto** [comment]
@cj-kennedy-tcfe  Thank you for the clarifications. Pull request merged.

**Pull request merged**
