### PR TITLE
Prendiville Catholic College

### PR DESCRIPTION
**Pull request by Jamaitland**

### CODE REVIEW

**Comment by philipto** [comment]
@Jamaitland First stage of verification passed, official domain is [prendiville.wa.edu.au](https://prendiville.wa.edu.au) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://prendiville.wa.edu.au/

**Comment by Jamaitland** [comment]
Thanks Philip,

Our students use a different email

Staff = ***@***.******@***.***>

Students = ***@***.******@***.***>

Will we need to register that domain

Also as a complicating factor there are 64 Highschools in CEWA (Catholic Education Western Australia) all staff and students have the same address ending this is not unique to Prendiville


James Maitland (Prendiville Catholic College - Ocean Reef)
Director of Learning Technology
Prendiville Ave Ocean Reef WA 6027
08 9307 2000
***@***.***
prendiville.wa.edu.au

This message contains confidential information and is intended only for the intended recipients. If you are not an intended recipient you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version..

From: Philip Torchinsky ***@***.***>
Date: Tuesday, 22 November 2022 at 7:16 pm
To: JetBrains/swot ***@***.***>
Cc: James Maitland (Prendiville Catholic College - Ocean Reef) ***@***.***>, Mention ***@***.***>
Subject: Re: [JetBrains/swot] Prendiville Catholic College (PR #15790)

@Jamaitland<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJamaitland&data=05%7C01%7Cjames.maitland%40cewa.edu.au%7C1618266f67c14cba743408dacc7b0a0c%7Cc5852f2336334f29b38651da53e35e23%7C0%7C0%7C638047126074876594%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SqWtmPTedVN89zMmF58V5pweYZD82JD0FWymGYBzYt4%3D&reserved=0> First stage of verification passed, official domain is prendiville.wa.edu.au<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprendiville.wa.edu.au%2F&data=05%7C01%7Cjames.maitland%40cewa.edu.au%7C1618266f67c14cba743408dacc7b0a0c%7Cc5852f2336334f29b38651da53e35e23%7C0%7C0%7C638047126074876594%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q10uUDkSkAsqWNx00PvIBSkUVS9%2FTAIIrEYjBJgNKlY%3D&reserved=0> as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://prendiville.wa.edu.au/<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprendiville.wa.edu.au%2F&data=05%7C01%7Cjames.maitland%40cewa.edu.au%7C1618266f67c14cba743408dacc7b0a0c%7Cc5852f2336334f29b38651da53e35e23%7C0%7C0%7C638047126074876594%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q10uUDkSkAsqWNx00PvIBSkUVS9%2FTAIIrEYjBJgNKlY%3D&reserved=0>

**Comment by philipto** [comment]
@Jamaitland Would you please re-upload your comment? You sent it by email and GitHub stripped out valuable information from it. Please open the request in your browser at https://github.com/JetBrains/swot/pull/15790 and comment there. Thank you.

**Comment by Jamaitland** [comment]
> 

Thanks Philip,
 
Our students use a different email
 
Staff = [firstname.surname@cewa.edu.au](mailto:firstname.surname@cewa.edu.au)
 
Students = [fsurname@student.cewa.edu.au](mailto:fsurname@student.cewa.edu.au)
 
Will we need to register that domain
 
Also as a complicating factor there are 64 Highschools in CEWA (Catholic Education Western Australia) all staff and students have the same address ending this is not unique to Prendiville

**Comment by philipto** [comment]
@Jamaitland  Thank you for the clarifications. Pull request merged.

**Pull request merged**
