### PR TITLE
Add University of Darussalam Gontor domain

### PR DESCRIPTION
**Pull request by kangsoekme**

### CODE REVIEW

**Comment by philipto** [comment]
@kangsoekme First stage of verification passed, official domain for **Universitas Darussalam Gontor** is [student.cs.unida.gontor.ac.id](https://student.cs.unida.gontor.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@kangsoekme Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by kangsoekme** [comment]
Dear JetBrains,

So, is my email domain already registered i the JetBrains list?. i hope you
assist me until i get it

Your regards,
Abdullah Sukma Jati

Pada Sel, 2 Jul 2024 pukul 19.56 Philip Torchinsky ***@***.***>
menulis:

**Comment by philipto** [comment]
@kangsoekme Please request your free license at https://www.jetbrains.com/shop/eform/students with your school email address. Thank you!

**Comment by kangsoekme** [comment]
Dear JetBrains,

Thanks for your supports until now, but i still cant register with my
email. please help me..
[image: image.png]

Your regards,
Abdullah Sukma Jati


Pada Sel, 2 Jul 2024 pukul 21.25 Philip Torchinsky ***@***.***>
menulis:

**Comment by philipto** [comment]
@kangsoekme Dear Abdullah, please send an email with the screenshot to community-support@jetbrains.com and mention this issue URL https://github.com/JetBrains/swot/pull/21222 in your message. Comments to merged requests are not monitored, and also GitHub strips out all images sent by email. I cannot verify your issue now. 

Looking forward to your reply to community-support@jetbrains.com,
@philipto

**Pull request merged**
