### PR TITLE
Add doz-provadis-hochschule.de

### PR DESCRIPTION
**Pull request by koopmann**
see also https://github.com/JetBrains/swot/pull/3056

Teachers at:

Provadis School of International Management & Technology AG

https://www.provadis-hochschule.de/

### CODE REVIEW

**Comment by philipto** [comment]
@koopmann lib/domains/de/doz-provadis-hochschule.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by koopmann** [comment]
Dear @philipto ,

i extracted the zip file from Jetbrains and got this structure:

Screenshot 2021-03-02 um 20 08 09

so if i got it right, as there is only one .(dot) in the domain: lib/domains/de/doz-provadis-hochschule.txt should be fine?
or because of the dashes, shall i better go for:
../lib/domains/de/doz/provadis/hochschule.txt ??

Thanks for helping!

**Comment by philipto** [comment]
@koopmann lib/domains/de/doz-provadis-hochschule.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@koopmann I am sorry, please disregard my messages above. The filename is correct. 

However, I did not find the domain name doz-provadis-hochschule.de mentioned anywhere at the website. Could you please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students?
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by koopmann** [comment]
Screenshot 2021-03-03 um 12 11 18

@philipto  in the screenshot you see the mail, where someone from the university created a Teacher(Dozenten)-Email-Account for me

**Comment by philipto** [comment]
@koopmann Thank you very much for the clarification. Pull request merged. Please start applying for the free license at https://www.jetbrains.com/shop/eform/students in about an hour to let the changes to propagate through our configuration settings.

Thank you!

**Pull request merged**
