### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by 3rekse**

### CODE REVIEW

**Comment by philipto** [comment]
@3rekse First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/ITIOMAR/about/

**Comment by philipto** [comment]
@3rekse Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@3rekse You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@3rekse I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by 3rekse** [comment]
The school official website URL is : https://www.itiomar.it/

the school street address, including city and country :
B.do Lamarmora, n° 12 - 
28100 Novara (NO)  
ITALY 
- Tel 0321/670611
-  - Mail: NOTF03000B@istruzione.it - PEC: NOTF03000B@pec.istruzione.it

an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course  : 
https://www.itiomar.it/scuola/pof/2023/NOTF03000B-202225-202223-20230224.pdf

a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students:
For the access at the students reserved area ( home page: https://www.itiomar.it  top right button "Accedi" ) you can see:  "Da qui puoi accedere ai diversi servizi della scuola che richiedono un'autenticazione personale (email@itiomar.net)".

"From here you can access the different school services that require personal authentication (email@itiomar.net)".

**Pull request closed without merging**
