### PR TITLE
Added St. James Lutheran College

### PR DESCRIPTION
**Pull request by Brhsoftco**
*For Educational Licensing

### CODE REVIEW

**Comment by philipto** [comment]
@Brhsoftco There are several St. James Lutheran College, including ones on Australia and the U.S. 

Thus, please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Brhsoftco You might miss my previous comment. Please react.

**Comment by Brhsoftco** [comment]
I do apologise for the late reply. We are a high school in Australia, and I'm not sure if I can pull up records from our website. relating to ICT, as the subject is not publicised as well as it should be. I have our official URL: https://www.stjameslc.qld.edu.au/, and I'm not too certain how to send you the rest of the details?

**Comment by philipto** [comment]
@Brhsoftco No problem, thank you! Thank you for the update! Pull request merged. You can start requesting free licenses at https://www.jetbrains.com/shop/eform/students in an hour.

For the record: domain ownership proof is at https://www.stjameslc.qld.edu.au/community/parents-and-friends

**Comment by Brhsoftco** [comment]
@philipto Thankyou for the help! On another note, student email domains are set to internal only. The @stjameslc.net domain only lets students communicate with other @stjameslc.net emails. Will you need other information like a student ID card?

**Pull request merged**
