### PR TITLE
Add Städtisches Gymnasium Eschweiler

### PR DESCRIPTION
**Pull request by davidpolkirn**
Institution/School Name
Städtisches Gymnasium Eschweiler

Instiution/School Website
www.gymnasiumeschweiler.de

Email Users
Please place an x between the square brackets if yes

- [x]  Students
- [x]  Academic/Teaching Staff
- [ ]  Other/Support Staff
- [ ]  Alumni
- [ ] Education Levels

Please place an x between the square brackets if yes

- [ ]  Post-graduate research
- [ ]  Graduate School
- [ ]  College (University) or Undergraduate School or equivalent
- [ ]  Community College or equivalent
- [x]  High School or equivalent
- [ ]  Elementary School or equivalent

[sge.txt](https://github.com/JetBrains/swot/files/5787347/sge.txt)

### CODE REVIEW

**Comment by philipto** [comment]
@davidpolkirn Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by davidpolkirn** [comment]
@philipto Can I send you a photo by email ?

**Comment by philipto** [comment]
@davidpolkirn Yes. Please send it to community-support@jetbrains.com with subject "ATTN: Philip Torchinsky". Thank you!

**Comment by davidpolkirn** [comment]
@philipto Email is sent! :)

**Comment by philipto** [comment]
@davidpolkirn Thank you for the clarification. Pull request merged.

**Pull request merged**
