### PR TITLE
Add lisoft.edu.pe

### PR DESCRIPTION
**Pull request by rickhufer**
website: [https://lisoft.edu.pe](https://lisoft.edu.pe)

Lima International School of Tomorrow

### CODE REVIEW

**Comment by Bilalkurt1** [comment]
[Marmara Universty.zip](https://github.com/user-attachments/files/17131175/Marmara.Universty.zip)
please add my school 
Marmara university
istanbul turkey

**Comment by philipto** [comment]
@Bilalkurt1 The domain marun.edu.tr has been abused. It cannot be added to the trusted list.
Please enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
@rickhufer Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by Bilalkurt1** [comment]
as you said, I have become a member, but he still says that I need to register the school, I registered with my student certificate, the mail came and github global campus, but still https://www.jetbrains.com/shop/eform/students
he says that I need to add my university to his address, can you help please

**Pull request merged**
