### PR TITLE
Städtisches Gymnasium Olpe

### PR DESCRIPTION
**Pull request by dj-schulze**
Städtisches Gymnasium Olpe
https://gymnasium-olpe.de

### CODE REVIEW

**Comment by dj-schulze** [comment]
Städtisches Gymnasium Olpe
https://gymnasium-olpe.de

**Comment by dj-schulze** [comment]
Städtisches Gymnasium Olpe
https://gymnasium-olpe.de

**Comment by philipto** [comment]
@dj-schulze Please provide us with:
- the school official website URL
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

The proof can be a copy (.pdf, .jpg) of an instruction that advises you to use an address from this email domain.

**Comment by philipto** [comment]
@dj-schulze You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@dj-schulze I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
