### PR TITLE
Add Aoyama Gakuin University

### PR DESCRIPTION
**Pull request by shotana**
I am a student of Aoyama Gakuin University.(http://www.aoyama.ac.jp)
Students in this university are given their own email address which are like xxxxxxx@aoyama.jp.

### CODE REVIEW

**Comment by zweizwei** [comment]
The university's domain seems to be www.aoyama.ac.jp - please provide some proof of the fact, the domain also belongs to the university. Thanks!

**Comment by shotana** [comment]
Thanks for your response.

http://www.cc.aoyama.ac.jp/mail/newext_index.html
Would this be okay?

**Comment by zweizwei** [comment]
Sorry for the delay and thanks for the info - i'm adding the domain.

**Comment by shotana** [comment]
Thank you.

**Pull request merged**
