### PR TITLE
Fixes manditory .txt extensions

### PR DESCRIPTION
**Pull request by jmsmkn**
If the file does not end with .txt it will not be picked up by `findSchoolNames`, this fixes the source files. See https://github.com/JetBrains/swot#how-to-add-a-domain-to-this-repository, point 1.

Files were missing the .txt extension so were renamed:
```
  renamed:    ../ci/ita-education -> ../ci/ita-education.txt
  renamed:    ../com/emlyon/edu -> ../com/emlyon/edu.txt
```

Renamed .text extension to .txt:
```
  renamed:    ../in/edu/cet.text -> ../in/edu/cet.txt
```

Corrected uri part in files:
```
  renamed:    ../edu/laccd.edu -> ../edu/laccd.txt
  renamed:    ../eus/doloresibarruribhi.eus -> ../eus/doloresibarruribhi.txt
```

Removed duplicate entry (nl/horizoncollege.txt already exists):
```
  deleted:    horizoncollege.nl
```

Fixed a malformed url subpart, see 5bbae11ddefc7f8506d573debb6d1497bcc832e6 where the intended domain is whg-rie.lernsax.de:
```
  renamed:    ../de/whg-rie.lernsax -> ../de/lernsax/whg-rie.txt
```

### CODE REVIEW

**Comment by philipto** [comment]
@jmsmkn I am sorry, I have to close the request without merging, because you made a mistake in a request and requested to merge too many files, most of them do not relate to the organization which you would like to add to this repository. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by jmsmkn** [comment]
I would like you to take a look at this again - this does not add any new organizations, merely fixes existing ones that have already been merged.

**Comment by philipto** [comment]
@jmsmkn Thank you for the fix. This fix requires more detailed review, because some of the domains look a bit suspicious.

**Comment by philipto** [comment]
@jmsmkn Pull request merged. Thank you again! Please accept my apologies with regard to the initial reject. Your contribution is important, and we appreciate your help very much!

**Comment by jmsmkn** [comment]
No problem, thank you!

**Pull request merged**
