### PR TITLE
 add university ITC at cambodia

### PR DESCRIPTION
**Pull request by oengmengthong**
ITC = Institute of Technology of Cambodia

### CODE REVIEW

**Comment by philipto** [comment]
@oengmengthong First stage of verification passed, official domain is [itc.edu.kh](https://itc.edu.kh) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by oengmengthong** [comment]
Hi @philipto , in my university have too many department. and I study under GIC department. so that why my mail is: oengmengthong@gic.itc.edu.kh

but I can't use for request Student Lisence.

**Comment by philipto** [comment]
@oengmengthong Thank you for your patience while waiting for a review and processing your request. Pull request merged.

You don't need to add subdomains. When a parent domain is added, all subdomains are considered trusted by default. Thank you.

**Comment by oengmengthong** [comment]
image
Hi @philipto i can't use my mail yet

**Pull request merged**
