### PR TITLE
added esad-valenciennes.txt to fr folder

### PR DESCRIPTION
**Pull request by Yachar**
Added  "esad-valenciennes.fr" to the domain pool.

### CODE REVIEW

**Comment by philipto** [comment]
@Yachar First stage of verification passed, official domain is [esad-valenciennes.fr](https://esad-valenciennes.fr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Yachar** [comment]
Thanks for keeping me informed! Best regards!

**Comment by philipto** [comment]
@Yachar Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@Yachar You might miss my previous comment. Please react.

**Comment by Yachar** [comment]
Hello,
The school provides a 5 year long (3 years of under-graduate plus 2 years of graduate level) curriculum that englobes many design and artistic practices that are IT related like interactive arts (JS, C, C++, Arduino) + VR lab and and 3-4 artist workshops per year that calls for programming skills.
Here are the links:
https://www.esad-valenciennes.fr/recherche/hyper-local
https://www.esad-valenciennes.fr/recherche/les-arc

Yashar Valakjie
Chief of Digital Workshop
Higher School of Arts and Design Valenciennes

**Comment by philipto** [comment]
@Yachar  Thank you for the clarifications. Pull request merged.

**Comment by Yachar** [comment]
Much appreciated! It's great to be a part of JetBrains community!

**Pull request merged**
