### PR TITLE
Create tptlive.txt

### PR DESCRIPTION
**Pull request by krisavi**
File for Tallinn Polytechnic school. E-mail creation is done by school administrators so random person can not register for it.

### CODE REVIEW

**Comment by krisavi** [comment]
The best description of different studies is defined at http://www.tptlive.ee/sisseastujale/ Probably goolge translate would be the best to get it translated since after the webpage update the language selector does nothing. Also http://www.tptlive.ee/erialad/ shows the specialities. Hope it makes it a bit easier to verify it.

**Comment by krisavi** [comment]
Comment about school e-mail addresses, only reference I found on web page was on http://www.tptlive.ee/kool/kontakt/ "Õpetajate ja töötajate e-posti aadressid on kujul: eesnimi.perekonnanimi (ät) tptlive.ee (täpitähtedeta)" translates to "Teachers and staff e-mail addresses are in the form: firstname.lastname (at) tptlive.ee (w/o accented characters)" 

This also applies for the students and they are created when student has been studying for about a month to avoid creating accounts for students who only come to "test, if the school is right".

**Comment by krisavi** [comment]
School used to use page www.tpt.edu.ee but has not been using it for a while now. Even though that also redirects to tptlive.ee. 

For the whole whois on that domain you probably have to use the site provided in most of the foreign whois lookups "internet.ee" A quick link for that whois checkup without hassle of estonian language: http://rwhois.internet.ee/v1/tptlive.ee

**Comment by philipto** [comment]
@krisavi Thank you for the request and detailed information! Pull request merged.

**Pull request merged**
