### PR TITLE
Add school: Dwight Global

### PR DESCRIPTION
**Pull request by felivalencia3**
School's website: [https://www.dwight.edu/dwight-global-online-school](url)
Address: 291 Central Park West, New York, NY 10024, United States
Page showing IB Computer Science HL (two-year course): [https://www.dwight.edu/academics/introduction-to-the-ib/curriculum-guide/diploma-program](url)

You'll find the computer science course if you scroll down and open the "Technology" dropdown.

I can show proof that I was given an email ending in @dwight.global by the school through an email that the school's registrar sent to me and my family when I was first admitted.

You'll find a PDF of the email below.

[Gmail - Fwd: Felipe - Preparing for Next Year at Dwight Global.pdf](https://github.com/JetBrains/swot/files/6942821/Gmail.-.Fwd.Felipe.-.Preparing.for.Next.Year.at.Dwight.Global.pdf)

### CODE REVIEW

**Comment by felivalencia3** [comment]
I hope this is enough information, please let me know if you need anything more.

**Comment by thibgod** [comment]
School website : https://www.arpb.be/
adresse : Rue Fourneau 40, 4570 Marchin Belgium
I can show proof that I was given an email ending in @arpb-ac.be  I did not receive an email with my address but a paper from school
[lib.zip](https://github.com/JetBrains/swot/files/6944445/lib.zip)
﻿
[Athénée Royal Prince Baudouin.pdf](https://github.com/JetBrains/swot/files/6944492/Athenee.Royal.Prince.Baudouin.pdf)

**Comment by felivalencia3** [comment]
@thibgod please open your own pull request.

**Comment by thibgod** [comment]
@felivalencia3 oh sorry since I'm french I do not understand everything about github 😂

**Comment by philipto** [comment]
@felivalencia3 Pull request merged. Thank you!

@thibgod Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting a new separate request.

**Pull request merged**
