### PR TITLE
Create sman2sukabumi.txt

### PR DESCRIPTION
**Pull request by indrabudi1**
Add Domain sman2sukabumi.txt

### CODE REVIEW

**Comment by philipto** [comment]
Please kindly provide the full name of your school on the first line of the file in your request

**Comment by philipto** [comment]
@indrabudi1 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by indrabudi1** [comment]
Website school : https://sman2sukabumi.sch.id/
School street address : Jl. Karamat No.93, Karamat, Kec. Gunungpuyuh, Kota Sukabumi, Jawa Barat 43122
Im Administrator IT of SMAN 2 SUKABUMI. Im Attach screenshoot cloudflare dashboard domain sman2sukabumi.sch.id
panel dashboard cyberpanel

**Comment by philipto** [comment]
@indrabudi1 Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
