### PR TITLE
Create zjnu.txt

### PR DESCRIPTION
**Pull request by kawa11**
email address:http://mail.zjnu.cn/

### CODE REVIEW

**Comment by philipto** [comment]
@kawa11 First stage of verification passed, official domain is [zjnu.edu.cn](https://zjnu.edu.cn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.zjnu.edu.cn/

**Comment by philipto** [comment]
@kawa11 Are you sure that this domain is not abused? The official domain of this university zjnu.edu.cn has been abused recently, and we had to put it to the stoplist. I doubt we can add this domain to the trusted list without prior interaction with the university administration.

**Comment by kawa11** [comment]
@philipto This is the old domain name of the previous school. It is only open to teachers who have opened it before. It is completely independent from zjnu.edu.cn.
image

**Comment by philipto** [comment]
@kawa11  Thank you for the clarifications. Pull request merged.

**Pull request merged**
