### PR TITLE
Add sp341.edu.pl

### PR DESCRIPTION
**Pull request by mumaguma**
Hi,
Please add sp341.edu.pl domain.
As proof, whois entry for the domain:
https://dns.pl/en/whois?domainName=sp341.edu.pl

### CODE REVIEW

**Comment by philipto** [comment]
@mumaguma Thank you for your request. In general, we do not recommend our professional tools to children under 13. Your school seems to be a primary school. Do you have any programming courses for the students where IntelliJ IDEA Community and PyCharm Community Edition are not enough for the students? The Community editions are free for everyone and have no restriction on how you use them.

**Comment by mumaguma** [comment]
Yes, I confirm this is elementary school. 
My kid, as some other kids attend extracurricular, free and open online course led by Olympic Club of IT - https://oki.org.pl/ and in 90% it is in C++

**Comment by mumaguma** [comment]
@philipto: Yes, I confirm this is elementary school.
My kid, as some other kids attend extracurricular, free and open online course led by Olympic Club of IT - https://oki.org.pl/ and in 90% it is in C++
Currently they are using notepad + ideone, which leads to frustration I know could be avoided with good IDE.
Also, in Polish educational system, elementary school includes students up to age of 15 (assuming start at 7)

**Comment by philipto** [comment]
@mumaguma Thank you for the clarification. Pull request merged.
I believe that JetBrains' CLion will be a good IDE for development in C++. May your kid have a great coding experience :)
Have a great weekend!

**Pull request merged**
