### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by 1rdsk1**

### CODE REVIEW

**Comment by 1rdsk1** [comment]
its been 4 days, please why has the school been added?

**Comment by philipto** [comment]
@1rdsk1 HARRISDULWICHGIRLS.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by 1rdsk1** [comment]
[](url)

**Comment by philipto** [comment]
@1rdsk1 I am closing this request as a duplicate to successfully merged #10405.

**Pull request closed without merging**
