### PR TITLE
add it academy

### PR DESCRIPTION
**Pull request by dartblack**

### CODE REVIEW

**Comment by philipto** [comment]
@dartblack I am sorry, this request has signs of fraud. I have to close it without merging. If you are a student of this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Comment by dartblack** [comment]
> @dartblack I am sorry, this request has signs of fraud. I have to close it without merging. If you are a student of this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

What are you doing? You deprive students of the right to study with a good product.

**Comment by philipto** [comment]
@dartblack Please notice that JetBrains **never** deprived students of using the products. If the email domain is not in JetBrains' allow list, the students of the school are always able to apply with the official student ID (a student card or similar document) at the "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students. 

We cannot check the eligibility of it.edu.ge domain for this repository because: 
1) The website it.edu.ge does not have any relevant information about the school.
2) The name "IT Academy" does not indicate any specific institution accredited by the respective country Ministry of Education.

Thank you for your understanding.

**Comment by dartblack** [comment]
Maintenance mode is enabled on the site right now. It will be released soon and hopefully you will check again.

**Pull request closed without merging**
