### PR TITLE
Create uniacc.txt

### PR DESCRIPTION
**Pull request by matyplaza**
Uniacc University Santiago of Chile. Students mails use EDU domain.

### CODE REVIEW

**Comment by philipto** [comment]
@matyplaza First stage of verification passed, official domain is [instagram.com](https://instagram.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.instagram.com/flosuau/

**Comment by matyplaza** [comment]
@philipto The university domain is uniacc.cl, but students mails use "uniacc.edu". Only administrative personnel use "uniacc.cl" in their mails.

**Comment by matyplaza** [comment]
@philipto Here it is the URL: https://www.uniacc.cl/facultad-de-administracion/ingenieria-informatica-multimedia/

**Comment by philipto** [comment]
@matyplaza  Thank you for the clarifications. Pull request merged.

**Pull request merged**
