### PR TITLE
Added Mobyus school from Leuven

### PR DESCRIPTION
**Pull request by Warsaalk**

### CODE REVIEW

**Comment by zweizwei** [comment]
@Warsaalk please provide the link to the page, describing long-term (>1 year) educational courses, that the school provides.

**Comment by Warsaalk** [comment]
Hi,

The long-term courses are not available in English yet. Mobyus is a school
that provides adult education and language courses. Our goal is to get
people who want to do something different as a job ready for employment.

The courses I teach are IT tools (front-end webdevelopment) & databases for
student who are in their first year. It's for the IT course.

The website doesn't provide these courses in English yet but here's a link
to the Dutch page for the IT course:
https://www.mobyus.be/nl/graduaten/informatica/programma
It describes the course program which takes 3 years to complete.

Here is also a link to the English page for the language courses:
https://www.mobyus.be/en/language-courses

Kind regards,
Klaas Van Parys

**Comment by Warsaalk** [comment]
@zweizwei Did I provide enough information or do you need anything else?

**Comment by philipto** [comment]
@Warsaalk Sorry for the delay with your request processing. You have provided all the info required, and I merge your pull request. Thank you!

**Comment by Warsaalk** [comment]
Thanks :)

**Pull request merged**
