### PR TITLE
Add School according to HK gov open data

### PR DESCRIPTION
**Pull request by tonyhhyip**

### CODE REVIEW

**Comment by philipto** [comment]
@tonyhhyip Could you please provide us with the link to the open government data?

**Comment by tonyhhyip** [comment]
Of course, it is here.
https://data.gov.hk/en-data/dataset/hk-edb-schinfo-registration-info
http://applications.edb.gov.hk/datagovhk/data/SchoolBasicInfo.xml

**Comment by philipto** [comment]
@tonyhhyip Thank you for the clarification! I am sorry but at this moment I feel that I can not merge this request because:
1) We usually check all the submitted domains manually. Checking 503 domains takes a lot of time, and will result in suspension of processing other requests, depriving other users. 
2) Some of the schools listed in the request are not high school or colleges, but secondary and primary schools instead. According this repository rules, we do not include them into the repository because they usually do not need professional versions of JetBrains tools, and can be satisfied with community versions of the tools (which are free for everybody and do not need licenses).
3) Some of the schools do not have long-term IT-related courses, and they shall not be added to the repository too.

Therefore, let us postpone the final decison on this request. For now I would suggest adding the schools which really need the licenses individually, one or few ones per request.

**Comment by philipto** [comment]
@tonyhhyip I am sorry, I have to close this request without merging. Regrettably, we can not make such bulk additions mainly because of different nature of the list which you suggested as a source. I specified particular differences in my comment earlier. I am really sorry we can not make this request. Thank you for your understanding.

**Pull request closed without merging**
