### PR TITLE
Added several schools in Tegal City, Central Java, Indonesia.

### PR DESCRIPTION
**Pull request by alfinauzikri**
- SMAN 2 Tegal - https://sman2tegal.sch.id/
- SMAN 5 Tegal - https://sman5kotategal.sch.id/html/index.php
- SMK Negeri 1 Tegal - https://www.smkn1tegal.sch.id/
- SMK Negeri 3 Tegal - https://www.smkn3tegal.sch.id/
- MAN Kota Tegal - https://mankotategal.sch.id/
- SMK Ihsaniyah Tegal - https://smkihsaniyahtegal.sch.id/

### CODE REVIEW

**Comment by philipto** [comment]
@alfinauzikri I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by philipto** [comment]
@alfinauzikri I reopen the pull request and it will take longer than usual to check it because there are many schools in the request. Thank you for your understanding.

**Comment by alfinauzikri** [comment]
I have removed one school domain from the list above.

After I tested again by accessing the main school page, all the above domains were normal.

However, there is one domain, namely **sman2tegal.sch.id** which failed to test when pinging. Returns "Request timed out."

pingresult

**Comment by philipto** [comment]
@alfinauzikri I removed SMK Negeri 3 Tegal from the list because it's official website redirects to an online shop. Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by alfinauzikri** [comment]
Thank You @philipto

**Comment by philipto** [comment]
@alfinauzikri Also, I had to remove SMK Negeri 1 Tegal just now, because the website does not look credible. If you think that we need to reinstate it, please send an email to community-support@jetbrains.com. Thank you.

**Pull request merged**
