### PR TITLE
Midlands Technical College

### PR DESCRIPTION
**Pull request by TheBrownBadger**
#### Institution/School Name 
{Midlands Technical College}

#### Instiution/School Website
{https://www.midlandstech.edu}

#### Email Users

*Please place an x between the square brackets if yes*
- [X] Students
- [ ] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*
[student.txt](https://github.com/user-attachments/files/16709413/student.txt)

- [ ] Post-graduate research
- [ ] Graduate School
- [ ] College (University) or Undergraduate School or equivalent
- [X] Community College or equivalent
- [ ] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by philipto** [comment]
@TheBrownBadger lib/student.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@TheBrownBadger What is the email domain in your email address? In other words, what is after @ sign in your email address?

**Comment by TheBrownBadger** [comment]
dajuanseabrooks@student.midlandstech.edu

**Comment by philipto** [comment]
@TheBrownBadger Thank you for the update. Pull request corrected and merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.** Thank you.

**Comment by TheBrownBadger** [comment]
Thank you Philip for your patience.

**Pull request merged**
