### PR TITLE
Added for upnm

### PR DESCRIPTION
**Pull request by nooreffa**
My 4th attempt, tq

Main Page
http://www.upnm.edu.my/en/index.php

IT Related Course
http://www.upnm.edu.my/en/index.php?req=26

Enrollment Form
http://www.upnm.edu.my/en/index.php?req=36

### CODE REVIEW

**Comment by philipto** [comment]
@nooreffa I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by nooreffa** [comment]
@philipto can you help me? I'd tried as per rules.
I had send fews PR for

lib/domains/my/edu/upnm.txt
lib/domains/my/edu/upnm/www.txt 

our website domain is www.upnm.edu.my, while our email address is upnm.edu.my,
please guide.

thanks

**Comment by nooreffa** [comment]
@philipto can you help me? I'd tried as per rules.
I had send fews PR for

lib/domains/my/edu/upnm.txt
lib/domains/my/edu/upnm/www.txt

our website domain is www.upnm.edu.my, while our email address is upnm.edu.my,
please guide.

thanks

**Comment by nooreffa** [comment]
@philipto can you help me? I'd tried as per rules.
I had send fews PR for

lib/domains/my/edu/upnm.txt
lib/domains/my/edu/upnm/www.txt

our website domain is www.upnm.edu.my, while our email address is upnm.edu.my,
please guide.

thanks

**Comment by nooreffa** [comment]
@philipto can you help me? I'd tried as per rules.
I had send fews PR for

lib/domains/my/edu/upnm.txt
lib/domains/my/edu/upnm/www.txt

our website domain is www.upnm.edu.my, while our email address is upnm.edu.my,
please guide.

thanks

**Comment by nooreffa** [comment]
@philipto can you help me? I'd tried as per rules.
I had send fews PR for

lib/domains/my/edu/upnm.txt
lib/domains/my/edu/upnm/www.txt

our website domain is www.upnm.edu.my, while our email address is upnm.edu.my,
please guide.

thanks

**Comment by nooreffa** [comment]
@philipto can you help me? I'd tried as per rules.
I had send fews PR for

lib/domains/my/edu/upnm.txt
lib/domains/my/edu/upnm/www.txt

our website domain is www.upnm.edu.my, while our email address is upnm.edu.my,
please guide.

thanks

**Comment by nooreffa** [comment]
@philipto can you help me? I'd tried as per rules.
I had send fews PR for

lib/domains/my/edu/upnm.txt
lib/domains/my/edu/upnm/www.txt

our website domain is www.upnm.edu.my, while our email address is upnm.edu.my,
please guide.

thanks

**Comment by nooreffa** [comment]
@philipto can you help me? I'd tried as per rules.
I had send fews PR for

lib/domains/my/edu/upnm.txt
lib/domains/my/edu/upnm/www.txt

our website domain is www.upnm.edu.my, while our email address is upnm.edu.my,
please guide.

thanks

**Comment by nooreffa** [comment]
@philipto can you help me? I'd tried as per rules.
I had send fews PR for

lib/domains/my/edu/upnm.txt
lib/domains/my/edu/upnm/www.txt

our website domain is www.upnm.edu.my, while our email address is upnm.edu.my,
please guide.

thanks

**Comment by nooreffa** [comment]
@philipto can you help me? I'd tried as per rules.
I had send fews PR for

lib/domains/my/edu/upnm.txt
lib/domains/my/edu/upnm/www.txt

our website domain is www.upnm.edu.my, while our email address is upnm.edu.my,
please guide.

thanks

**Comment by philipto** [comment]
@nooreffa I just added the domain upnm.edu.my and all its subdomains to the repository. Please start requesting free licenses at https://www.jetbrains.com/shop/eform/students in an hour. The pause is necessary for the changes to propagate through our systems. Thank you!

**Pull request closed without merging**
