### PR TITLE
Add epse.be

### PR DESCRIPTION
**Pull request by GentileFabio**

### CODE REVIEW

**Comment by GentileFabio** [comment]
official website: https://www.epse.be/
IT related course is offered: https://www.epse.be/Formation/BES-Web-Developer

**Comment by GentileFabio** [comment]
Any news ?

**Comment by philipto** [comment]
@GentileFabio Thank you for your patience while waiting for a review and processing your request. 

Please prove the school recognizes the domain **myepse.be** as official student email domain. Provide us with:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by GentileFabio** [comment]
Hello, here is a 

- A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students.

I have hidden my name and address

[jetbrains.pdf](https://github.com/JetBrains/swot/files/11004027/jetbrains.pdf)

**Comment by philipto** [comment]
@GentileFabio Thank you very much for the document. I noticed that the domain name that you were assigned with, according to the document, is mye**sp**e.be, not mye**ps**e.be. However I think this document can be accepted as a proof. The issue in the letter looks like a typo.

Pull request accepted. Please start requesting free licenses in about an hour to let the changes to propagate through the systems. Thank you.

**Pull request merged**
