### PR TITLE
Added colegio irlandesas

### PR DESCRIPTION
**Pull request by andonisan**

### CODE REVIEW

**Comment by andonisan** [comment]
url of the school

http://www.colegioirlandesas.com/es/

**Comment by philipto** [comment]
@andonisan I am sorry, it looks like the school is a primary school, and you do not have high school students at all. Are you sure that community versions of our tools, such as PyCharm Community Edition and IntelliJ IDEA Community Edition are not enough for your students? The community versions are free for everybody, and do not require any specific licensing for any purpose.

Do you really need commercial versions of the tools?

**Comment by andonisan** [comment]
Hello,

The school is from 3 years old to "bachiller" that is until 18 years old, after that they have to go a university


http://www.colegioirlandesas.com/es/educamos/oferta-educativa/bachiller.html

https://es.m.wikipedia.org/wiki/Sistema_educativo_de_Espa%C3%B1a

Regards


Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by philipto** [comment]
@andonisan Thank you for the clarification. Pull request merged.

**Pull request merged**
