### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RomuloHe4rt**
Adding my university

### CODE REVIEW

**Comment by SalaDarius** [comment]
Adding my high school (Website: https://www.cnavramiancu.ro/)
[cnavramiancu.txt](https://github.com/JetBrains/swot/files/6096135/cnavramiancu.txt)

**Comment by philipto** [comment]
@RomuloHe4rt Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by RomuloHe4rt** [comment]
https://www.uva.br/
https://www.uva.br/areas-de-estudio/engenharias-e-tecnologias

**Comment by philipto** [comment]
@RomuloHe4rt I am sorry, could you please provide us a proof of the domain recognition? Where I can see that the school recognizes the domain you are submitting as an official email domain for the students?

**Pull request closed without merging**
