### PR TITLE
Add School of Design and Computers

### PR DESCRIPTION
**Pull request by farismecinovic**

### CODE REVIEW

**Comment by philipto** [comment]
@farismecinovic Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@farismecinovic You might miss my previous comment. Please react.

**Comment by farismecinovic** [comment]
Hi,
Sorry  for the late reply. I couldn't find that course on their site, they
didint update it..

**Comment by philipto** [comment]
@farismecinovic Thank you! Regrettably I cannot verify the domain eligibility for the trusted list without access to up-to-date information about the schools and the courses. Thus, I have to close the request without merging.

If you are the student of this school, please enroll to GitHub Student Developer Pack at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

Thank you for your understanding.

**Pull request closed without merging**
