### PR TITLE
Create cairo3.txt

### PR DESCRIPTION
**Pull request by Omar0Gamal**
there was A cairo6 you need to add them all i think they are from 1 to 6

### CODE REVIEW

**Comment by philipto** [comment]
@Omar0Gamal You are probably right. However, how  is St. Fatima Language School related to Cairo3?

Could you please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot)? Then I appreciate if you submit a clarification of the request. 

We need all the information mentioned in the rules to add a domain to this repository. Thank you.

**Comment by Omar0Gamal** [comment]
St. Fatima Language School is the school and they sent us a ministry of education email so we can use it as our email for exams and to study with the government resources so the domain I sent is not for the school it is for the entire ministry of edu

**Comment by philipto** [comment]
@Omar0Gamal Thank you for the explanation. I am not a bit confused. Which email domain you wish us to add to the repository?

**Comment by Omar0Gamal** [comment]
If possible I would be better to add the *.moe.edu.eg so every one who is a student any where in the country can ask this but if it is not possible cairo3.moe.edu.eg would do the job

**Comment by philipto** [comment]
@Omar0Gamal Thank you for the clarification. Pull request merged.

**Comment by Omar0Gamal** [comment]
@philipto thank you so much

**Comment by Omar0Gamal** [comment]
@philipto hey I have a question how long does it take for the website to recognize new domain name so I can apply for the free student license?

**Pull request merged**
