### PR TITLE
adds Hillside Public Schools to  Domain List

### PR DESCRIPTION
**Pull request by AuroraRpg**
makes hillsidek12.net and .org as recognized educational domains

### CODE REVIEW

**Comment by philipto** [comment]
@AuroraRpg The first verification stage is complete: the official domain for  **Hillside Public Schools** is [www.hillsidek12.org](https://www.hillsidek12.org), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.hillsidek12.org/live-feed?page_no=5

**Comment by AuroraRpg** [comment]
While hillsidek12.org is the official domain, the students use
hillsidek12.net while teachers uses .org

**Comment by philipto** [comment]
@AuroraRpg The first verification stage is complete: the official domain for  **Hillside Public Schools** is [www.hillsidek12.org](https://www.hillsidek12.org), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.hillsidek12.org/live-feed?page_no=5

**Comment by philipto** [comment]
@AuroraRpg Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.** Thank you.

**Pull request merged**
