### PR TITLE
Add Minas Gerais Department of Education

### PR DESCRIPTION
**Pull request by dimarluiz**
Please add Secretaria de Educação de Minas Gerais to the repository.

https://www.educacao.mg.gov.br

### CODE REVIEW

**Comment by philipto** [comment]
@dimarluiz First stage of verification passed, official domain is [educacao.mg.gov.br](https://educacao.mg.gov.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@dimarluiz Please clarify who (students, teachers, of which schools) has an access to the inboxes in the email domain of [educacao.mg.gov.br](https://www.educacao.mg.gov.br/). Thank you!

**Comment by dimarluiz** [comment]
Good Morning,
The inbox of the educacao.mg.gov.br domain is accessed by students and teachers from the public school system in the state of Minas Gerais. The service is offered by google.
I'm a professor at this institution, so I don't have access to all the details. The school unit where I work is in the poorest region of the state of Minas Gerais, called Vale do Jequitinhonha.
Our desire is to be part of the Jetbrains project for students so that we can continue the school's scientific initiation projects, which include initiation into the world of programming.
I hope this information is enough.
Grateful,
Professor Dimar Luiz

**Comment by dimarluiz** [comment]
> @dimarluiz Please clarify who (students, teachers, of which schools) has an access to the inboxes in the email domain of [educacao.mg.gov.br](https://www.educacao.mg.gov.br/). Thank you!

Good Morning,
The inbox of the educacao.mg.gov.br domain is accessed by students and teachers from the public school system in the state of Minas Gerais. The service is offered by google.
I'm a professor at this institution, so I don't have access to all the details. The school unit where I work is in the poorest region of the state of Minas Gerais, called Vale do Jequitinhonha.
Our desire is to be part of the Jetbrains project for students so that we can continue the school's scientific initiation projects, which include initiation into the world of programming.
I hope this information is enough.
Grateful,
Professor Dimar Luiz

**Comment by philipto** [comment]
@dimarluiz  Thank you for the clarifications. Pull request merged.

**Pull request merged**
