### PR TITLE
UKM domain

### PR DESCRIPTION
**Pull request by chunhoong**
Added Universiti Kebangsaan Malaysia, aka The National University of Malaysia to the recognized domain.

### CODE REVIEW

**Comment by chunhoong** [comment]
To ease the verification, here is the link to the undergraduate programme from Faculty of Information Science & Technology:

http://www.ftsm.ukm.my/undergraduate-programme.php

**Comment by philipto** [comment]
@chunhoong I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by chunhoong** [comment]
@philipto I am still able to login into my @siswa.ukm.edu.my email using this domain. Can you please verify again?

**Comment by philipto** [comment]
@chunhoong I am sorry, the university email domain NS server has failed to answer our request previously. Everything is fine now, and your pull request is merged.

**Pull request merged**
