### PR TITLE
Create fecaf.txt

### PR DESCRIPTION
**Pull request by Dianna-coder**

### CODE REVIEW

**Comment by philipto** [comment]
@Dianna-coder Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by Dianna-coder** [comment]
@philipto:

Official website: https://www.fecaf.com.br/
URL of official website where IT course is offered: https://www.fecaf.com.br/cursos/analise-e-desenvolvimento-de-sistemas/
My institutional account: https://drive.google.com/file/d/1Wgi_dEj2StVbM0S1ZDicKaM1YqTxKErv/view?usp=sharing
Proof: https://drive.google.com/file/d/1Y_wO5z5uoCOJnALpAf7CanseN90QhuAJ/view?usp=sharing

**Comment by philipto** [comment]
@Dianna-coder I am sorry, but you have submitted a request with filename lib/domains/br/fecaf.txt. It corresponds the email domain fecaf.br, not fecaf.com.br. What is your actual email domain? Is it `fecaf.com.br`?

**Comment by Dianna-coder** [comment]
Sorry @philipto, the correct one is 'fecaf.com.br', I fixed the location of the file, could you check again please?

**Comment by Dianna-coder** [comment]
Sorry @philipto, the correct one is 'fecaf.com.br', I fixed the location of the file, could you check again please?

**Comment by philipto** [comment]
@Dianna-coder Pull request merged. Thank you!

**Pull request merged**
