### PR TITLE
added ischoolvirtual

### PR DESCRIPTION
**Pull request by minsin56**

### CODE REVIEW

**Comment by philipto** [comment]
@minsin56 Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@minsin56 You might miss my previous comment. Please react.

**Comment by minsin56** [comment]
@philipto 
website -> https://ischoolvirtual.com/
address -> its an online school, but here is their office -> 1800 Lakeway Dr # 118, Lewisville, TX 75057
IT page -> i can't find it on their website, but they do have some programming classes for extra credit, you sign up at the beginning of the school year, not sure what I could provide to show this

**Comment by philipto** [comment]
@minsin56 If the school does not have a publicly announced major somehow related to IT, I think that very few students from there need JetBrains tools. Therefore I have to close this request without merging. If you are the student of this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
