### PR TITLE
Adding ITE

### PR DESCRIPTION
**Pull request by SalvadorReGar**

### CODE REVIEW

**Comment by philipto** [comment]
@SalvadorReGar First stage of verification passed, official domain is [ensenada.tecnm.mx](https://ensenada.tecnm.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.ensenada.tecnm.mx/organigrama/

**Comment by philipto** [comment]
@SalvadorReGar Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by SalvadorReGar** [comment]
> @SalvadorReGar Please provide us with:
> 
> * the school official website URL
> * the school street address, including city and country
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.


Hi @philipto , here is the info

* https://www.ensenada.tecnm.mx/
* Boulevard Tecnológico No. 150, Ex-ejido Chapultepec, 22780 Ensenada, Baja California, México.
* https://www.ensenada.tecnm.mx/ing-sistemas-computacionales/
* I'm not sure how I can prove that. Here I shared an image of an email. The pattern of the students email is something like that **^(al)[0-9]{8}(@ite.edu.mx)$**
image

**Comment by SalvadorReGar** [comment]
The Ensenada Institute of Technology/Insituto Tecnológico de Ensenada(**ITE**) is part of the [ National Technological Institute of Mexico](https://en.wikipedia.org/wiki/National_Technological_Institute_of_Mexico)/Tecnológico Nacional de México(**TecNM**), so it might be known as the National Technological Institute of Mexico Ensenada campus/Tecnológico Nacional de México campus Ensenada(**TecNM campus Ensenada**).

**Comment by philipto** [comment]
@SalvadorReGar  Thank you for the clarifications. Pull request merged.

**Pull request merged**
