### PR TITLE
Add National Taiwan University of Arts

### PR DESCRIPTION
**Pull request by thekdesign**
Official school website URL:
No. 59, Sec. 1, Daguan Rd., Banqiao Dist., New Taipei City 220, Taiwan (R.O.C.)

### CODE REVIEW

**Comment by philipto** [comment]
@thekdesign I am sorry, you did not commented here, as you promised.  Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

URL is **NOT the street address**, it is the address in the internet, something like https://www.ntua.edu.tw/

I ask you to add a comment here. Please write in the comment, where I can see that this school offers courses, which are related to information technology and are long-term (1 year or longer). Such courses can be math, physics, computer science, software engineering, etc.

**Comment by philipto** [comment]
@thekdesign You might miss my previous comment. Please react.

**Comment by thekdesign** [comment]
sorry for the late reply

Official school website URL:
http://maa.ntua.edu.tw/en/

**Comment by philipto** [comment]
@thekdesign Thank you. Where at the official website I can see a course that requires using JetBrains tools? If you wish to add this domain to this repository, the school has to have a course which is related to informational technologies. If there is no such course, you still can apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
@thekdesign I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
