### PR TITLE
Create Gymnázium Mimoň

### PR DESCRIPTION
**Pull request by MiloslavMaixner**
Trying to add my org to the list. Thanks.

### CODE REVIEW

**Comment by MiloslavMaixner** [comment]
Thank you.

**Comment by AdamFiser** [comment]
Hello @MiloslavMaixner, your filename is not valid. You have to use the domain name as filename. I guess that for you the correct filename is **gymi.txt** Content is ok

**Comment by MiloslavMaixner** [comment]
Repaired, thanks.

**Comment by MiloslavMaixner** [comment]
Good day,
I tried to fix it, thank you for your time.

**Comment by philipto** [comment]
@MiloslavMaixner Pull request merged. Thank you!

**Pull request merged**
