### PR TITLE
Create mdis.txt

### PR DESCRIPTION
**Pull request by lieweden**

### CODE REVIEW

**Comment by philipto** [comment]
@lieweden First stage of verification passed, official domain is [mdis.edu.my](https://mdis.edu.my) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by lieweden** [comment]
> @lieweden First stage of verification passed, official domain is [mdis.edu.my](https://mdis.edu.my) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Sir,may I know why this domain still unable to be recognised when I apply a educational license?

**Comment by lieweden** [comment]
@philipto may I know how long for  the processing time

**Comment by philipto** [comment]
@lieweden Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by lieweden** [comment]
Noted,Thank you

**Pull request merged**
