### PR TITLE
Add files via Lokman Hekim Üniversitesi

### PR DESCRIPTION
**Pull request by alperkirmizigul**

### CODE REVIEW

**Comment by alperkirmizigul** [comment]
Add files via Lokman Hekim Üniversitesi

**Comment by philipto** [comment]
@alperkirmizigul First stage of verification passed, official domain for **Lokman Hekim Üniversitesi** is [lokmanhekim.edu.tr](https://lokmanhekim.edu.tr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@alperkirmizigul Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@alperkirmizigul You might miss my previous comment. Please react.

**Comment by alperkirmizigul** [comment]
Hello, unfortunately, the university does not offer such a course. The
university primarily focuses on training students in the field of health
sciences. However, academically, I would like to conduct software
experiments to innovate in the field of health sciences, particularly by
using artificial intelligence technologies.

I apologize for the delayed response.

Alper KIRMIZIGÜL
Software Developer
#JAVA #PHP #MySQL #Oracle #Codeigniter #Yii #jQuery
#Javascript  #Hibernate #HTML # CSS #OpenLayers
www.alperkirmizigul.com


Philip Torchinsky ***@***.***>, 2 Haz 2024 Paz, 06:33
tarihinde şunu yazdı:

**Comment by philipto** [comment]
@alperkirmizigul Thank you for the clarification! I am sorry, this domain doesn't qualify for being added to this repository. However you can request your individual free license for your educational needs. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
