### PR TITLE
Added Berufskolleg für Technik Moers

### PR DESCRIPTION
**Pull request by Marormur**
German school
https://www.bk-technik-moers.de/

They teach programming
https://www.bk-technik-moers.de/bigas/berufsschule/fachinformatiker-in-ihk

### CODE REVIEW

**Comment by philipto** [comment]
@Marormur lib/domains/de/bk-technik-moers.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Marormur lib/domains/de/bk-technik-moers.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Marormur** [comment]
I'm sorry, but could you point out to me what exactly is wrong with the file path? I got the file and instructions on how to add it from this site: https://www.jetbrains.com/shop/eform/students/contributeUniversity

**Comment by philipto** [comment]
@Marormur lib/domains/de/bk-technik-moers.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Marormur lib/domains/de/bk-technik-moers.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Marormur Please disregard the message above. The filepath is actually correct. Pull request merged. Thank you!

**Pull request merged**
