### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by cuntu**
the university official website URL: http://www.fyvtc.edu.cn/
the official email domain: mail.hfyvtc.cn

### CODE REVIEW

**Comment by philipto** [comment]
@cuntu I am sorry, there is a discrepancy here: you write that the official email domain is mail.hfyvtc.cn, but you submit a file lib/domains/cn/fyvtc.txt which corresponds to a domain fyvtc.cn. Which domain you wish to submit?

**Comment by cuntu** [comment]
> @cuntu I am sorry, there is a discrepancy here: you write that the official email domain is mail.hfyvtc.cn, but you submit a file lib/domains/cn/fyvtc.txt which corresponds to a domain fyvtc.cn. Which domain you wish to submit?

Our teachers use email domain: hfyvtc.cn and students use: mail.hfyvtc.cn
I am a teacher，please submit the domain hfyvtc.cn for me.Do I still need to submit the domain for the student again？

**Comment by philipto** [comment]
@cuntu Please provide us with a proof that shows that the school recognizes the domain hfyvtc.cn as an official email domain for the teachers. It can be any of the following:
1) An internal instruction sent to the teachers. It can be in Chinese, no translation needed. 
2) A copy of an article published in an international journal and signed by a teacher, with name of the university and email address. 
3) A link to an official website page where the email address is mentioned.
We need to ensure that the university uses hfyvtc.cn as an official email domain. Thank you.

**Comment by philipto** [comment]
@cuntu I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host fyvtc.cn not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Pull request closed without merging**
