### PR TITLE
New University

### PR DESCRIPTION
**Pull request by alfredo-cesee**
* Centro de Estudios Superiores en Educacion Especializada
* Av, Tecnologico S/N Esq Pespuntadores
* Leon Gto Mexico

### CODE REVIEW

**Comment by philipto** [comment]
Please kindly provide the full name of your school on the first line of the file in your request

**Comment by philipto** [comment]
@alfredo-cesee Also, please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@alfredo-cesee You might miss my previous comment. Please react.

**Comment by alfredo-cesee** [comment]
http://www.cesee.edu.mx
Av. Tecnológico S/N esq Pespuntadores, Fracc. Ind. Julian de Obregon, Leon
Gto, C.P. 37290
http://www.cesee.edu.mx/oferta-educativa.html

**Comment by philipto** [comment]
@alfredo-cesee First stage of verification passed, official domain for **Centro de Estudio Superiores de Educación Especializada** is [cesee.edu.mx](https://cesee.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@alfredo-cesee I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
