### PR TITLE
Rename khk.ee to khk.txt

### PR DESCRIPTION
**Pull request by phoenix913**

### CODE REVIEW

**Comment by zweizwei** [comment]
@phoenix913 the domain http://khk.ee/en doesn't look like educational one - could you please somehow confirm that it also belongs to educational institution?

**Comment by phoenix913** [comment]
I'm sorry, but it seems that our school, Tartu Vocational School hasn't really developed the english site as much as the estonian, so please see khk.ee without the /en in the end. If you need more verification, then feel free to ask me.

**Comment by zweizwei** [comment]
@phoenix913  then, please provide the link to the page, describing long-term (>1year) educational programs that the school provides. Thank you!

**Comment by phoenix913** [comment]
I hope these are enough, but be sure to let me know if they are not, also siseveeb.ee/tkhk is KHK's subdomain.

http://khk.ee/osakonnad - The departments available to choose from, 

http://khk.ee/osakonnad/ikt - Description of the department I'm learning at (Information and Communication Department) aka teachers, general information etc.

https://siseveeb.ee/tkhk/veebivormid/oppekavad/?vaade=struktuuriuksused&struktuuriuksus=11 - Detailed descriptions of the available professions,

http://khk.ee/osakonnad/ikt/erialad - Less detailed version for simpler overview. 

http://khk.ee/osakonnad/ikt/erialad/multimeedium - Description of the profession I'm learning aka information specialist? or something along those lines. 

P.S. - Sorry for the late reply, and happy new year!

**Comment by mikhailvink** [comment]
Merged. Thank you!

**Pull request merged**
