### PR TITLE
Added support for student email. As old emails @langara.ca only avail…

### PR DESCRIPTION
**Pull request by jaiminmoslake7020**
Added support for student email. As old emails @langara.ca only available to employees.  Example jpandya00@mylangara.ca

### CODE REVIEW

**Comment by philipto** [comment]
@jaiminmoslake7020 Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by jaiminmoslake7020** [comment]
[](https://langara.ca/information-technology/accounts-passwords/student-accounts.html  )

This page explains that student will access all their emails through Email Address having domain mylangara.ca 
Screenshot 2020-06-09 at 7 52 52 AM

**Comment by jaiminmoslake7020** [comment]
@philipto Please take a look at it and let me know if you need any additional information.

**Comment by philipto** [comment]
@jaiminmoslake7020 Pull request merged. Thank you!

**Pull request merged**
