### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AllanChilongo**

### CODE REVIEW

**Comment by Sailingjulia** [comment]
[bbwsoest.txt](https://github.com/JetBrains/swot/files/8531230/bbwsoest.txt)

**Comment by philipto** [comment]
@Sailingjulia Please file a separate pull request for another school.

**Comment by AllanChilongo** [comment]
@philipto You right. The official website of the school is opening with a blank page. I don't know why. Please note that the school used to be a constituent college of University of Malawi and was dis-linked from that University. Now it is an independent University and is called Kamuzu University of Health Sciences (KUHes). Probably they must be migrating to a new website (https://www.kuhes.ac.mw/).

**Comment by philipto** [comment]
@AllanChilongo Thank you very much for the clarification. Pull request merged.

**Pull request merged**
