### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by bsze2tespet**

### CODE REVIEW

**Comment by philipto** [comment]
@bsze2tespet First stage of verification passed, official domain is [vasvari.hu](https://vasvari.hu) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.vasvari.hu/

**Comment by tenthreee** [comment]
@bsze2tespet Pull request merged. Thank you!

**Comment by bsze2tespet** [comment]
Thank you. Is there any update on this?

**Comment by bsze2tespet** [comment]
@tenthreee Hello Lena, is there any update on this? Thank You!

**Pull request merged**
