### PR TITLE
Young Capital Academy added to the list

### PR DESCRIPTION
**Pull request by DarwinCheese**
New school in the Netherlands, based on Novi Hogeschool stuff.

### CODE REVIEW

**Comment by philipto** [comment]
@DarwinCheese Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@DarwinCheese You might miss my previous comment. Please react.

**Comment by DarwinCheese** [comment]
Hey @philipto,

Sorry for the late reply. Here are the 2 links you were looking for.

1. https://academy.youngcapital.nl/en/ 
2. https://academy.youngcapital.nl/en/studieprogramma/hbo-bachelor-ict/
3. I don't really know how to show that the university recognizes this domain,do you have anything you are specifically looking for?

**Comment by philipto** [comment]
@DarwinCheese Thank you for the update. There are two issues with this domain:

1) Young Capital Academy is an educational institution, but also it says that 
> YoungCapital is the largest employment agency for young people.

(at the bottom of this page, for example: https://academy.youngcapital.nl/en/faq/algemeen/)
Please notice that free JetBrains educational license is for educational purpose only; it is illegal to use it for any work which is not a part of education, including commercial work for companies, even if a company employs a user as an intern.

2) I found only one page mentioning youngcapitalacademy.nl as a domain related to Young Capital Academy in the internet, https://www.linkedin.com/in/anouar-azzouz-6b98a4154/. It is not enough to ensure that this domain actually belongs to Young Capital Academy. Is there any page or internal instruction for students which says that Young Capital Academy provides its students with an email address in this domain?

**Comment by philipto** [comment]
@DarwinCheese You might miss my previous comment. Please react. If the organization is not actually a university, nor a college, I have to close the request without merging.

**Comment by philipto** [comment]
I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. 

You also can apply for the free license by email to community-support@jetbrains.com even if this school is not a college, nor a university. Feel free to communicate with us, we really wish to offer you the best licensing option, which fits your needs and follow this repository rules.

Thank you for the understanding!

**Comment by DarwinCheese** [comment]
Hi @philipto ,

I talked to my teachers and organizers, they told me that the school is sort of unique. You go to school (boot camp style) for the first 4 months and then you work 4 days a week and have school 1 day a week. This study takes 3-4 years to complete and you get your bachelor's at the end of the study. So, I guess it's kind of an internship. The school offering the courses is called Novi Hogeschool, this school offers the courses while the Young Capital Academy offers you the workplaces. I don't know if this falls under an internship or something like that, though.

**Comment by philipto** [comment]
@DarwinCheese Thank you for the clarification. I reopened the request, and we'll reconsider it once again. I am sorry for the delay: this is a special case indeed. Thank you!

**Comment by philipto** [comment]
@DarwinCheese We carefully considered your request again. Regrettably, this school does not qualify to be added to this repository. However, the academy teachers can request free coupons for the initial four months boot camp at https://www.jetbrains.com/shop/eform/training, and the students can use the IDEs for free at the boot camp, and then buy a license with a 25% discount. This license will not limit them in using it for education only, they can continue using it at work.

**Pull request closed without merging**
