### PR TITLE
Added VIIT Pune

### PR DESCRIPTION
**Pull request by prashantluhar**
- The university official website URL → https://www.viit.ac.in
- a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university → https://www.viit.ac.in/departments/computer/department-profile-comp

### CODE REVIEW

**Comment by philipto** [comment]
@prashantluhar lib/domains/in/ac/viit: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@prashantluhar First stage of verification passed, official domain for **VIIT, Pune** is [viit.ac.in](https://viit.ac.in) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@prashantluhar Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by prashantluhar** [comment]
Thanks @philipto

**Pull request merged**
