### PR TITLE
Add Summer Fields School

### PR DESCRIPTION
**Pull request by Max4W**
This fork adds Summer Fields School to Jetbrains/Swot.

### CODE REVIEW

**Comment by philipto** [comment]
@Max4W lib/domains/summerfields.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Max4W lib/domains/summerfields.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Max4W lib/domains/summerfields.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Max4W** [comment]
I don’t think there are any more errors in my branch. Can you tell me what I can do to fix them if they are still there?

**Comment by philipto** [comment]
@Max4W It's all set now. Pull request merged. Thank you.

**Pull request merged**
