### PR TITLE
Create aegmail.txt

### PR DESCRIPTION
**Pull request by K0XI**
Added the mail domain for students and Teachers.
School Homepage: https://aeg-duisburg.de
Only Mail Domain redirecting to I-Serv.

### CODE REVIEW

**Comment by philipto** [comment]
@K0XI Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. If I click on IServ link at the homepage, it redirects me to another domain, not aegmail.de.

**Comment by K0XI** [comment]
Yes, I already saied that it's only the domain of the mail from I-Serv. What's an example of an proof?

**Comment by philipto** [comment]
Yes, I agree. Any kind of instruction for students, any document mentioning this email domain works.
Thank you!

**Comment by philipto** [comment]
@K0XI You might miss my previous comment. Please react.

**Comment by K0XI** [comment]
Hi. Please provide me an email to send the proof to.

**Comment by philipto** [comment]
You can add it to this request as a comment (please use web interface to upload anything here), or send it to community-support@jetbrains.com with Subj: ATTN Philip Torchinsky

**Comment by K0XI** [comment]
I have sended the Proof to you by email.

**Comment by philipto** [comment]
@K0XI Thank you for the clarification. I received your message. Pull request merged.

**Pull request merged**
