### PR TITLE
Adding Green Village School

### PR DESCRIPTION
**Pull request by michronin**
Adding Green Village School (Ha-Kfar Ha-Yarok School) in Ramat Ha-Sharon, Israel.
Some info about the school: https://en.wikipedia.org/wiki/HaKfar_HaYarok#Junior_High_School.
The school site in Hebrew: https://kfaryarok.org.il/.

### CODE REVIEW

**Comment by philipto** [comment]
@michronin Please provide us with a proof, which shows that the school recognizes the domain **kfaryarok.eduil.org** that you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by michronin** [comment]
Hi, there are two pictures that prove this e-mail is given to me by the school:

Eduil.org, is Israeli schools portal site:
image


This is personal details page in students portal of my school, you can see the logo of my school in the top right corner, and my e-mail under the title "Username":
image

This is school home page of my account. In the middle of the screen you can see my school e-mail next to my School and my classroom. As well, you can see the logo of my school in the top right corner:
image

**Comment by philipto** [comment]
@michronin Thank you for the clarification. Pull request merged.

**Comment by michronin** [comment]
Thanks!

**Pull request merged**
