### PR TITLE
Added "British Gymnasium of Technology"

### PR DESCRIPTION
**Pull request by ErdajtSopjani**
Added my school. 

British Gymnasium of Technology (BGT)
https://bgt.school

### CODE REVIEW

**Comment by philipto** [comment]
@ErdajtSopjani First stage of verification passed, official domain is [bgt.school](https://bgt.school) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by ErdajtSopjani** [comment]
Yep, [bgt.school](https://bgt.school) is the official domain and website.

**Comment by nataershova** [comment]
Pull request merged. Thank you! @ErdajtSopjani

**Comment by ErdajtSopjani** [comment]
[like]  Erdajt Sopjani reacted to your message:
________________________________

**Comment by ErdajtSopjani** [comment]
[like]  Erdajt Sopjani reacted to your message:
________________________________

**Pull request merged**
