### PR TITLE
Odorheiu Secuiesc - computer science joint program

### PR DESCRIPTION
**Pull request by kolixx**
Educational license request for the joint junior mentor program for the computer science students of the 5 mentioned institutions.

### CODE REVIEW

**Comment by philipto** [comment]
@kolixx Thank you for the request! Could you please specify what is the subject at Liceul de Arte Dr. Palló Imre, which requires some programming? 

Other schools clearly have some courses related to software development, thus it's clear why they need JetBrains tools. We are fine with granting free licenses for the tools to students at Liceul de Arte Dr. Palló Imre, we just need to ensure that the students really need them there.

Thank you!

**Comment by kolixx** [comment]
@philipto The Liceul de Arte Dr. Palló Imre is an art school and they are teaching UI and UX design to their students as well. The reason we would like to have licenses for them as well is that their students participate in joint projects with students from the other schools and it would help allot if they could also build and run the projects we are developing with them.

**Comment by philipto** [comment]
@kolixx Thank you for the clarification. Pull request merged.

**Comment by kolixx** [comment]
@philipto Thank you. I wish you a happy new year.

**Pull request merged**
