### PR TITLE
Add University

### PR DESCRIPTION
**Pull request by samandareo**
Hello, I am Samandar(Sam). I am currently studying at PDP University. It is located in Tashkent, Uzbekistan. PDP University is a university fully adapted to the IT field. So, I added my university above the repo and hope you accept it.

### CODE REVIEW

**Comment by samandareo** [comment]
Hello, Dear Jetbrains team. I tried to add my university but it was not approved. university.pdp.uz

**Comment by philipto** [comment]
@samandareo Thank you for your request! I found enough evidence of eligibility of `pdp.uz` domain, but not `pdp.university` domain.

Please provide us with a proof, which shows that the school recognizes the domain `pdp.university` as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@samandareo You might miss my previous comment. Please react.

**Comment by samandareo** [comment]
@philipto Hello, I saw your response. University has a website university.pdp.uz. If you enter pdp.university, will redirect to university.pdp.uz

**Comment by philipto** [comment]
@samandareo Thank you for replying. Regrettably, this does not prove anything:
> If you enter pdp.university, will redirect to university.pdp.uz

Anybody can setup a redirect from any URL to any other URL. Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@samandareo I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
