### PR TITLE
Create woonsocketschools.txt

### PR DESCRIPTION
**Pull request by cjmcdonald42**
Add Woonsocket Vocational and High Schools to the JetBrains index for educational institutions.

### CODE REVIEW

**Comment by philipto** [comment]
@cjmcdonald42 The first verification stage is complete: the official domain for  **Woonsocket Area Career and Technical Center** is [woonsocketschools.ss16.sharpschool.com](https://woonsocketschools.ss16.sharpschool.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://woonsocketschools.ss16.sharpschool.com/departments/office_of_curriculum_and_instruction

**Comment by cjmcdonald42** [comment]
Thank you @philipto -- I can confirm that is the correct domain.
I am the new lead of the Information Technology Vocational program at WACTC (which I delightfully pronounce as "WackTech")

I and my 15 Frosh are currently using the Community edition of PyCharm but I would like to explore the professional versions of both PyCharm and IntelliJ. (My students will be learning Java next school year with future plans to bring PHP and web development into our program.)

We are currently preparing lessons to model a helpdesk and would like to explore YouTrack and other JetBrains tools, if the pro license will extend that far. Thank you for making this generous license available to me and my students!

**Comment by philipto** [comment]
@cjmcdonald42 The first verification stage is complete: the official domain for  **Woonsocket Area Career and Technical Center** is [woonsocketschools.ss16.sharpschool.com](https://woonsocketschools.ss16.sharpschool.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://woonsocketschools.ss16.sharpschool.com/departments/office_of_curriculum_and_instruction

**Comment by philipto** [comment]
@cjmcdonald42 Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
