### PR TITLE
21 school added

### PR DESCRIPTION
**Pull request by chacha-42**
http://www.21-school.ru/en

### CODE REVIEW

**Comment by philipto** [comment]
@chacha-42 Could you please confirm that this school's program is a long-term, i.e. at least one course lasts for at least 1 year? This is essential for adding this domain to the repository, to follow the rules located at the bottom of [this page](https://github.com/JetBrains/swot).

**Comment by philipto** [comment]
@chacha-42 Thank you for the update! Pull request merged.

**Comment by chacha-42** [comment]
Thank you very much ! 
When will be able to apply for student licenses ?

**Comment by chacha-42** [comment]
It’s all good thx !

**Pull request merged**
