### PR TITLE
Add ISTEA to the list

### PR DESCRIPTION
**Pull request by sminutoli**
We're using google accounts linked to @istea.com.ar for both teacher and students. It would be nice to have students licenses so we'll encourage them to use JetBrains on the Fullstack Path.

Our main site is http://www.istea.edu.ar/

### CODE REVIEW

**Comment by philipto** [comment]
@sminutoli Could you please provide us with a link to an official page or another document where istea.com.ar is declared an email domain for the unversity students? The istea.com.ar is owned by Sebastian Divinsky, according to WHOIS, and I did not find any info at www.istea.edu.ar website to verify that istea.com.ar belongs to the university.

**Comment by sminutoli** [comment]
Of course, you can verify "edu.ar" domains here: http://www.riu.edu.ar/registro.html (site of the institution that management argentinian educational'domains).
The page is in spanish so I'll try to help you:

1. Click on "Consultas por un dominio" (domain query)
2. Type "istea" in the input box and click "Enviar" (submit)

This will show you a page with the domain information. If you check the point "Incumbencia principal" you'll see this message "Educacion Terciaria. La url temporaria es www.istea.com.ar" ("temporal url").
Also is mentioned Sebastián Divinsky as technical and management contact and his address info@istea.com.ar

Thank you very much in advance

**Comment by philipto** [comment]
@sminutoli Thank you! Actually, I needed a bit different type of verification to show some logical connection between istea.edu.ar and istea.com.ar. However it appeared that the respective servers have the same IP address, thus the issue is resolved anyway. Pull request merged.
Just for the record:
`$ host istea.edu.ar`
`istea.edu.ar has address 166.62.45.246`
[...]
`$ host  istea.com.ar`
`istea.com.ar has address 166.62.45.246`

**Comment by sminutoli** [comment]
Thanks a lot @philipto for your patience!

**Pull request merged**
