### PR TITLE
add file education/adachi-gr.txt

### PR DESCRIPTION
**Pull request by UbiquitousD**

### CODE REVIEW

**Comment by K0NST-hacker** [comment]
### Hello
please add my school

Tbilisi, N187 school "pesvebi"
https://www.fesvebi.edu.ge/
[file.zip](https://github.com/JetBrains/swot/files/7446129/file.zip)

I am looking forward your feedback

**Comment by philipto** [comment]
@K0NST-hacker There are three issues with your request:
1) The school website is now offline with an odd error message:
image

2) The school correct name in English seems to be "Georgian-Austrian School Pesvebi".

3) The request for adding the school must be separate. 

Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with correct information. Thank you for the understanding!

**Comment by philipto** [comment]
@UbiquitousD Please reply. I need the document that you mentioned to be either uploaded here, or sent to community-support@jetbrains.com. If you are not able to provide the document in a few days, please close this request and reopen it (or create a new one) when you have the document. 

Thank you!

**Comment by UbiquitousD** [comment]
@philipto I apologize for not replying to your message.

> If you are not able to provide the document in a few days, please close this request and reopen it (or create a new one) when you have the document.

I understand this matter.

**Comment by K0NST-hacker** [comment]
> @K0NST-hacker There are three issues with your request:
> 
>     1. The school website is now offline with an odd error message:
>        image
> 
>     2. The school correct name in English seems to be "Georgian-Austrian School Pesvebi".
> 
>     3. The request for adding the school must be separate.
> 
> 
> Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with correct information. Thank you for the understanding!

what should i do to add "Georgian-Austrian School Pesvebi" ?  official site is https://www.fesvebi.edu.ge/ 
can you tell me what else can i do?

**Comment by philipto** [comment]
@K0NST-hacker Your school is added already. Please open https://www.jetbrains.com/shop/eform/students and get your license immediately.

**Comment by philipto** [comment]
@UbiquitousD Thank you very much for the clarification that you have sent to our support email address. Pull request merged.
Have a great coding experience! Thank you.

**Pull request merged**
