### PR TITLE
add "alwadischool.com" domain

### PR DESCRIPTION
**Pull request by AliMark71**
this domain is for "Alwadi International School" in Jeddah, Saudi Arabia

### CODE REVIEW

**Comment by philipto** [comment]
@AliMark71 lib/domains/com/alwadischool: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by AliMark71** [comment]
uhh sorry for that :>
I've forgot to add the extension, I think now the issue has been resolved

**Comment by philipto** [comment]
@AliMark71 First stage of verification passed, official domain for **مدارس الوادي العالمية** is [alwadischool.com](https://alwadischool.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@AliMark71 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by AliMark71** [comment]
thanks

**Pull request merged**
