### PR TITLE
Add Kaliningrad State Technical University

### PR DESCRIPTION
**Pull request by denis-samalus**
https://klgtu.ru/, https://i-klgtu.ru/
https://klgtu.ru/abitur/bachelor/

### CODE REVIEW

**Comment by SerhatCanpolatDev** [comment]
https://www.atlas.edu.tr/lib/domains/tr/edu/atlas.txt

**Comment by philipto** [comment]
@denis-samalus Official website and the domain of the university is klgtu.ru.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@SerhatCanpolatDev Please submit a separate request, not a comment to someone's else request. Thank you.

**Comment by philipto** [comment]
@denis-samalus You might miss my previous comment. Please react.

**Comment by denis-samalus** [comment]
@philipto sorry for making you wait. The i-klgtu.ru domain is used for educational purposes. Mail in the klgtu.ru domain is used for teachers and university staff. (https://disk.yandex.ru/i/nn2glsedHTFjQg)

**Comment by philipto** [comment]
@denis-samalus  Thank you for the clarifications. Pull request merged.

**Pull request merged**
