### PR TITLE
Create aemm.txt

### PR DESCRIPTION
**Pull request by rodrigovalentim**

### CODE REVIEW

**Comment by philipto** [comment]
@rodrigovalentim First stage of verification passed, official domain for **Agrupamento de Escolas Morgado de Mateus** is [aemm.pt](https://aemm.pt) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@rodrigovalentim Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by rodrigovalentim** [comment]
Thank you for your response. What are the next steps?

Rodrigo Valentim



Em seg., 20 de mai. de 2024 às 17:15, Philip Torchinsky <
***@***.***> escreveu:

**Comment by philipto** [comment]
@rodrigovalentim Please open the page https://www.jetbrains.com/shop/eform/students, fill in the form there and get your free license. Thank you!

**Pull request merged**
