### PR TITLE
Uptown International School 

### PR DESCRIPTION
**Pull request by sandwihc**
Hello, I would like to add my school to the domains verified schools.

### CODE REVIEW

**Comment by philipto** [comment]
@sandwihc The first verification stage is complete: the official domain for  **Uptown International School** is [www.tes.com](https://www.tes.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.tes.com/jobs/vacancy/head-of-secondary-august-2024-start-dubai-2028056

**Comment by philipto** [comment]
@sandwihc Please provide us with:
* the school official website URL
* the school street address, including city and country.

**Comment by sandwihc** [comment]
Hello Phillip,

*The school website URL: *
https://uischool.ae/
*The school address:  *
Dubai United Arab Emirates - Mirdif Area - Tripoli Street - Algeria St
https://maps.app.goo.gl/iznNAGCkzhn8ASEb8


Best regards,
Zayed Al Nahyan

**Comment by philipto** [comment]
@sandwihc Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
