### PR TITLE
Add file for khwopa college of engineering

### PR DESCRIPTION
**Pull request by NabinKawan**
Request for adding khwopa college of engineering
website of the college:  https://khwopa.edu.np/

### CODE REVIEW

**Comment by philipto** [comment]
@NabinKawan file/lib/domains/np/edu/khowpa.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by NabinKawan** [comment]
@philipto I have updated the file path according to the rules. -> `lib/domains/np/edu/khwopa.txt`. 

Can you verify this and let me know?

**Comment by philipto** [comment]
@NabinKawan First stage of verification passed, official domain is [khwopa.edu.np](https://khwopa.edu.np) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@NabinKawan Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by NabinKawan** [comment]
You're welcome, @philipto ! I truly appreciate your patience during the review and processing of my request.

**Pull request merged**
