### PR TITLE
Create wayland

### PR DESCRIPTION
**Pull request by mikehopps**

### CODE REVIEW

**Comment by mikehopps** [comment]
I'm a CS teacher at Wayland HS in Wayland, MA, USA.  We have ben using the CE versions of IntelliJ and PyCharm for years.  A group of students in an advanced elective want to make a web app, and would love to use WebStorm.
Note, teacher emails use name@wayland.k12.ma.us, and students use name@student.wayland.k12.ma.us.  
Thanks!

**Comment by philipto** [comment]
@mikehopps Thank you for using our tools! Could you please rename `lib/domains/us/ma/k12/wayland` to `lib/domains/us/ma/k12/wayland.txt` to reflect this repository rules? Thank you!

**Comment by mikehopps** [comment]
Done!  Sorry about that.

On Wed, Sep 21, 2016 at 5:17 PM, Philip Torchinsky <notifications@github.com

**Comment by philipto** [comment]
@mikehopps Pull request merged. Thank you!

**Pull request merged**
