### PR TITLE
add my middle school mail

### PR DESCRIPTION
**Pull request by hooss-only**

### CODE REVIEW

**Comment by philipto** [comment]
Please provide us with:
- the school official website URL
- the school street address, including the city and the country

**Comment by philipto** [comment]
@hooss-only You might miss my previous comment. Please react.

**Comment by hooss-only** [comment]
sorry im late

keisung.ms.kr

35, Dalseong-ro, Jung-gu, Daegu, Republic of Korea

**Comment by hooss-only** [comment]
@philipto knock knock

**Comment by philipto** [comment]
@hooss-only Thank you for the clarification and for the reminder! 
Regrettably, I cannot add this domain to the repository, because it belongs to a city administration, not to the school. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.
Thank you for your understanding!

**Comment by kms0219kms** [comment]
@philipto As I mentioned 2 years ago, the mail services are provided by our government, not school.
If you got some request from Korean students, please remember that the domain could be government's domain and approve it.

@nooss-only This PR should be approved. Please reopen it if you still need this domain.

**Pull request closed without merging**
