### PR TITLE
Added tel-ran.de by Tel-Ran.de GmbH

### PR DESCRIPTION
**Pull request by aliaskov**
Added Tel-Ran.de of Tel-Ran.de GmbH

### CODE REVIEW

**Comment by philipto** [comment]
@aliaskov Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school

**Comment by philipto** [comment]
@aliaskov You might miss my previous comment. Please react.

**Comment by aliaskov** [comment]
Thank you for reminding. 
Here is our certificate: [https://www.tel-ran.de/?lang=en&lightbox=dataItem-jxuz87pb](url)
Here are our courses: 
[https://www.tel-ran.de/?lang=en](url)
3 modules, more than 12 months long

**Comment by philipto** [comment]
@aliaskov Thank you for the clarification. Pull request merged.

**Pull request merged**
