### PR TITLE
add toba-kosen

### PR DESCRIPTION
**Pull request by JUNNETWORKS**
Add toba.txt

[Toba-kosen site](http://www.toba-cmt.ac.jp/english/)

### CODE REVIEW

**Comment by philipto** [comment]
@JUNNETWORKS Could you please provide us with the proof (a link, a .pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@JUNNETWORKS You might miss my previous comment. Please reply.

**Comment by JUNNETWORKS** [comment]
Sorry for the late reply.

I heard from the teacher that there seems to be a problem with this e-mail address, and I am told that I can not prepare certification documents because I am changing the domain of e-mail address now.

**Comment by philipto** [comment]
@JUNNETWORKS Well, in that case I have to close the request without merging. Please create a new request with correct information about the student domain as soon as all the documents are ready. It's fine if you give us a link to an official page with an instruction for students which domain they have to use, or provide us with appropriate screenshot or a document in .pdf. Thank you!

**Pull request closed without merging**
