### PR TITLE
Add iscod school

### PR DESCRIPTION
**Pull request by wa2l-99**

### CODE REVIEW

**Comment by philipto** [comment]
@wa2l-99 First stage of verification passed, official domain for **ISCOD (Institut Supérieur des Compétences de Demain)** is [iscod.fr](https://iscod.fr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by wa2l-99** [comment]
@philipto merci pour votre réponse.

**Comment by philipto** [comment]
@wa2l-99 Please give us a link to the page where one can learn about fees and charges for the study in this school. It is purely online, thus we must ensure you don't enroll random people for free without any obligations from the student's side.

**Comment by philipto** [comment]
@wa2l-99 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@wa2l-99 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
