### PR TITLE
Add St. Anthony's College Kandy

### PR DESCRIPTION
**Pull request by sathsarabandaraj**

### CODE REVIEW

**Comment by philipto** [comment]
@sathsarabandaraj First stage of verification passed, official domain is [sack.edu.lk](https://sack.edu.lk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@sathsarabandaraj Pull request merged. Thank you.

**Comment by sathsarabandaraj** [comment]
Hi @philipto, 
When can use my email to apply for education package.

**Comment by philipto** [comment]
Hi!
It takes about 30-60 minutes for tge changes to become effective.
Thank you!

**Comment by sathsarabandaraj** [comment]
Thank you for your support @philipto

**Comment by philipto** [comment]
You can renew it every year, until you graduate.

**Pull request merged**
