### PR TITLE
Create cellini.txt

### PR DESCRIPTION
**Pull request by mecubeme**
http://www.cellini.fi.it/

http://www.cellini.fi.it/IndirizzidiStudio/ISTITUTOTECNICO/Informatica/tabid/178/Default.aspx

### CODE REVIEW

**Comment by philipto** [comment]
@mecubeme Unfortunately, your school website does not answer, and we cannot check if the school fits the eligibility criteria. I'll check the website in few days, and if it will still be unavailable, I have to close the request. You will receive a separate notification about the issue as soon as the check is made.

**Comment by mecubeme** [comment]
@philipto Hi, site now is reachable. It's a high school.
Links are to the school website and to the informatics area of the school.
Thanks a lot

**Comment by mecubeme** [comment]
@philipto I've Just contact site administrators. Server has some geographic filter. Can I know the country where your request come?
Thanks a lot

**Comment by philipto** [comment]
@mecubeme Thank you for the clarification! Pull request merged. Thank you!

**Comment by mecubeme** [comment]
@philipto Thanks a lot to you for merge

**Pull request merged**
