### PR TITLE
Northeast Forestry University

### PR DESCRIPTION
**Pull request by Code0401**
https://www.nefu.edu.cn/
东北林业大学

### CODE REVIEW

**Comment by Code0401** [comment]
Please add my college email，@nefueducn.onmicrosoft.com，as you know，This domain is provided by office 365.thanks，my english is poor.

**Comment by philipto** [comment]
@Code0401 Please provide us with an URL of a page or another proof which shows that the school recognizes the domain which you are submitting as an official email domain for the students. Usually universities in China do not use onmicrosoft.com domain for their email correspondence.

**Comment by Code0401** [comment]
> @Code0401 Please provide us with an URL of a page or another proof which shows that the school recognizes the domain which you are submitting as an official email domain for the students. Usually universities in China do not use onmicrosoft.com domain for their email correspondence.

Thanks，You know a lot about China，This is a screenshot of the office 365 management center，Please tell me what else you need，I'm sorry I used Google translation
image

**Comment by Code0401** [comment]
image

**Comment by Code0401** [comment]
image

**Comment by philipto** [comment]
@Code0401 I am sorry, but the proof which you have provided us with do not confirm that the university recognizes the domain which you are submitting as an official email domain for the students. Your ability to access some admin panel does not show that the university actually assign the addresses from this email domain to its students. 

Still, the students of the university can apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students). 

I am sorry, I have to close this request without merging.

**Comment by Code0401** [comment]
> @Code0401 I am sorry, but the proof which you have provided us with do not confirm that the university recognizes the domain which you are submitting as an official email domain for the students. Your ability to access some admin panel does not show that the university actually assign the addresses from this email domain to its students.
> 
> Still, the students of the university can apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).
> 
> I am sorry, I have to close this request without merging.

Please tell me how to get your approval，We are recognized by the Ministry of Education，So please help me

**Pull request closed without merging**
