### PR TITLE
Create uwr.txt

### PR DESCRIPTION
**Pull request by mkowalski**
Add "University of Wroclaw" second domain (uwr.edu.pl)

### CODE REVIEW

**Comment by philipto** [comment]
@mkowalski Your request contains two identical lines in the file: "University of Wroclaw". Could you please change it to have just one line (or two different lines, if it was your intention to provide the repository with two different names of the university). Thank you!

**Comment by mkowalski** [comment]
@philipto I did it intentionally, as I've seen on the file https://github.com/JetBrains/swot/blob/master/lib/domains/pl/wroc/uni.txt exactly the same case (two times the same line). Of course I'll change it, but I see many files have duplicated entry, why is it so?

**Comment by philipto** [comment]
@mkowalski Thank you! I'll check whether it made any sense before; You can see that majority of files in the repository have just one line. Now it's perfectly OK to have a single line for sure.

**Comment by philipto** [comment]
@mkowalski There is no technical reason to have two identical lines, and it was probably somebody's mistake in the past, which has been occasionnaly repeated many times. However, it is not a error, thus I just merged your request. Thank you!

**Pull request merged**
