### PR TITLE
Create fhwue.txt

### PR DESCRIPTION
**Pull request by mr678**
For trainers at FH Würzburg / Germany

### CODE REVIEW

**Comment by mr678** [comment]
Please add the fhwue domain to your email list. The domain is used for trainers at FHWS

**Comment by philipto** [comment]
@mr678 Could you please provide us with a link to the school official web site, and a page on it where a long-term (> 1 year) IT-related course is offered to students, and a page or document showing that teachers do have their email in fhwue.de domain. [The school contact page](http://www.fhws.de/hochschule/fakultaeten/angewandte_natur_und_geisteswissenschaften.html) shows emails in an encrypted format, and I was not able to decrypt it with my browser and email client.

**Comment by mr678** [comment]
Hi JetBrains,

 

please find below the link to web site of the university and the link of my course:

 

The official page is fhws.de (Fach Hochschule Würzburg Schweinfurt).

The informatics faculty have a own domain with welearn.de where my course is listed.

 

 

Homepage:  <https://www.fhws.de/startseite.html> https://www.fhws.de/startseite.html

Course JavaEE Fullstack for Business Applications:  <http://www.welearn.de/fakultaet-iw/personen/lehrbeauftragte/details/person/matthias-reining.html> http://www.welearn.de/fakultaet-iw/personen/lehrbeauftragte/details/person/matthias-reining.html

 

My email as external teacher is  <mailto:lbreining@fhwue.de> lbreining@fhwue.de.

 

Please let me know if you need further information.

 

Thanks and enjoy your weekend,

 

Matthias

 

--
Matthias Reining
[M] +49.172.9917260
[W]  <http://about.me/matthiasreining> http://about.me/matthiasreining

Von: Philip Torchinsky [mailto:notifications@github.com] 
Gesendet: Freitag, 18. März 2016 17:29
An: JetBrains/swot <swot@noreply.github.com>
Cc: Matthias Reining <matthias.reining@outlook.com>
Betreff: Re: [swot] Create fhwue.txt (#1828)

 

@mr678 <https://github.com/mr678>  Could you please provide us with a link to the school official web site, and a page on it where a long-term (> 1 year) IT-related course is offered to students, and a page or document showing that teachers do have their email in fhwue.de domain. The school contact page <http://www.fhws.de/hochschule/fakultaeten/angewandte_natur_und_geisteswissenschaften.html>  shows emails in an encrypted format, and I was not able to decrypt it with my browser and email client.

**Comment by philipto** [comment]
@mr678 Thank you for the clarification! Pull request is now merged.

**Comment by mr678** [comment]
Thanks a million!

**Pull request merged**
