### PR TITLE
Add Max Planck Institute for Structure and Dynamics of Matter

### PR DESCRIPTION
**Pull request by LecrisUT**
Maybe we should add all max planck institues as a whole? (`*.mpg.de`)

### CODE REVIEW

**Comment by philipto** [comment]
@LecrisUT First stage of verification passed, official domain is [mpsd.mpg.de](https://mpsd.mpg.de) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@LecrisUT Could you please provide us with a link to an educational unit of the Institute? JetBrains does not grant educational licenses to purely research organizations. The latter are eligible for an academic discount that can be received if you send an email to sales@jetbrains.com. Thank you!

**Comment by LecrisUT** [comment]
As just a member I probably do not have the authority or the full picture of the structure. But at the very least MPSD has students and trains them. For example the students are listed in a group's page, e.g. https://www.mpsd.mpg.de/12866/people

**Comment by philipto** [comment]
@LecrisUT  Thank you for the clarifications. Pull request merged.
Please notice that the free educational licenses are for educational purpose only. Shall the researchers in the Institute need them too, please let them know the correct way: get an academic discount by email to [sales@jetbrains.com](mailto:sales@jetbrains.com). Thank you!

**Pull request merged**
