### PR TITLE
Add Sesc Cidadania

### PR DESCRIPTION
**Pull request by Gabriel-Cararo**

### CODE REVIEW

**Comment by philipto** [comment]
@Gabriel-Cararo First stage of verification passed, official domain is [sesccidadania.com.br](https://sesccidadania.com.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.sesccidadania.com.br/public/imagem/gerenciador/comunicados/2021/agosto/Comunicado_N%C2%BA_096_-_2%C2%BA_Plant%C3%A3o_Pedag%C3%B3gico_-_EFAF.pdf

**Comment by philipto** [comment]
@Gabriel-Cararo Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

I found some proofs mentioned above, but your clarification would help for faster verification process. Thank you!

**Comment by philipto** [comment]
@Gabriel-Cararo You might miss my previous comment. Please react.

**Comment by Gabriel-Cararo** [comment]
Just saw this today, as for the official website its https://www.sesccidadania.com.br/, the street address is Av. C-197 c/ Av. C-198, Jardim América, Goiânia - GO, as for the it course, they dont provide one themselves but they do provide one in collaboration with SESI for the students and so they dont have a page disclosing that, i dont know whether that would be eligible, and for the proof of email, there is that document wich you have found and also teams "classrooms" (If sending a screenshot is fine then i can do that), the original document regarding emails is probably from 2020 (When covid started and the school went remote) and i dont know where to find it

**Comment by philipto** [comment]
@Gabriel-Cararo Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
