### PR TITLE
Szkoła Podstawowa Nr 2 im. Jana Pawła II

### PR DESCRIPTION
**Pull request by Serjik85**

### CODE REVIEW

**Comment by philipto** [comment]
@Serjik85 First stage of verification passed, official domain is [sp2kroscienko.pl](https://sp2kroscienko.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Serjik85** [comment]
@philipto Hello! How long will it take to be reviewed? Thank you.

**Comment by philipto** [comment]
@Serjik85 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by Serjik85** [comment]
@philipto Thanks so much!

**Pull request merged**
