### PR TITLE
Add "education.gouv.fr"

### PR DESCRIPTION
**Pull request by ArfNtz**
Education Nationale
France

### CODE REVIEW

**Comment by philipto** [comment]
@ArfNtz This domain does not belong to a particular university, nor to a college. Could you please explain why did you decide to suggest adding it to this repository? 

Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting a request.

**Comment by philipto** [comment]
@ArfNtz You might miss my previous comment. Please react.

**Comment by ArfNtz** [comment]
Hello,
Thank you for looking at my request.
The domain I propose, "education.gouv.fr", is the domain of the french ministry of education.
Some teachers or staff members belong to the central administration, hence they have this domain in their email.
Best regards,
Frantz Epineuse.

**Comment by philipto** [comment]
@ArfNtz Thank you for the clarification. Regrettably, it can not be a reason to add the email domain owned by a ministry to this repository. May I ask you to ask the teachers who need free licenses and do not have email address provided by a university, not the ministry, to email JetBrains to community-support@jetbrains.com and request the license there?

Alternatively, they can request the license with an official document which proves that they are a teacher. They can do it using "OFFICIAL DOCUMENT" tag at https://www.jetbrains.com/shop/eform/students.
As for the request, I have to close it without merging. I am sorry for that. Thank you for the understanding!

**Pull request closed without merging**
