### PR TITLE
I request to add Centro de Estudios Superiores Allende

### PR DESCRIPTION
**Pull request by gerpollo2000**

### CODE REVIEW

**Comment by philipto** [comment]
@gerpollo2000 First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/profile.php?id=100057702030104

**Comment by philipto** [comment]
@gerpollo2000 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@gerpollo2000 You might miss my previous comment. Please react.

**Comment by gerpollo2000** [comment]
Hi @philipto, thanks for your answer, let me get this info, just one doubt for the last point about the email proof, do you need somewere in the facebook page or in the school official website that the email domain is being used? could this work?

**Comment by philipto** [comment]
@gerpollo2000 First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/profile.php?id=100057702030104

**Comment by philipto** [comment]
@gerpollo2000 I managed to find an independent proof of all the above. Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by gerpollo2000** [comment]
Awesome, thanks a lot for your help @philipto , I really apreciate it. 
Have a nice day!!

**Pull request merged**
