### PR TITLE
aivancity.education

### PR DESCRIPTION
**Pull request by MichaelZPi**
Adding aivancity (https://www.aivancity.ai/)

### CODE REVIEW

**Comment by philipto** [comment]
@MichaelZPi Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@MichaelZPi You might miss my previous comment. Please react.

**Comment by MichaelZPi** [comment]
Hi,

Please find the informations below :

•	the school official website URL
https://aivancity.ai/en
•	the school street address, including city and country
57 Av. du Président Wilson, 94230 Cachan
•	an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
https://aivancity.ai/en/student/program/bachelor-science-applied-artificial-intelligence
•	a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
« De : Administrateurs <admins@aivancity.ai> 
Envoyé : vendredi 28 mai 2021 17:45
À : zaoui.michael@free.fr
Objet : Votre compte utilisateur aivancity : michael.zaoui@aivancity.education
Importance : Haute

Bonjour,

Bienvenue chez aivancity !

Voici vos identifiants utilisateur : 
- Utilisateur :  michael.zaoui@aivancity.education
- Mot de passe : ****** (est à modifier lors de la première connexion).

Vous pouvez désormais accéder aux ressources Office365 depuis l'adresse :  https://www.office.com/ (plus de services à suivre à compter de la rentrée).

Bonne réception.
 »
"Return-Path: admins@aivancity.ai
Received: from zimbra50-e8.priv.proxad.net (LHLO
zimbra50-e8.priv.proxad.net) (172.20.243.200) by
zimbra50-e8.priv.proxad.net with LMTP; Fri, 28 May 2021 17:44:43 +0200
(CEST)
Received: from FRA01-PR2-obe.outbound.protection.outlook.com (mx21-g26.priv.proxad.net [172.20.243.91])
                by zimbra50-e8.priv.proxad.net (Postfix) with ESMTP id 768B020CD8
                for <zaoui.michael@free.fr>; Fri, 28 May 2021 17:44:43 +0200 (CEST)
Received: from FRA01-PR2-obe.outbound.protection.outlook.com ([40.107.12.125])
                by mx1-g20.free.fr (MXproxy) with ESMTPS for zaoui.michael@free.fr
                (version=TLSv1.2 cipher=ECDHE-RSA-AES256-GCM-SHA384 bits=256);
                Fri, 28 May 2021 17:44:43 +0200 (CEST)
X-ProXaD-SC: state=HAM score=0
X-ProXaD-Cause: (null)
ARC-Seal: i=1; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=none;
b=irAxqDxASkYbQ6u6Cu3GiwlS2Z6l6e+0NZ5njb++RFPgFzXqs1NOA8g+PeXgg4pQs+v8cZ+W0cLulR63px+g2Z78wLLB81OkZNeTpUN4MlcEffRprMmmGqHXsxQUCeR6maPzABb7mczgXdCUymz1gj7GFxbduD8YbnWb+QpneLUJdaClxEep6UDSMCZqISyEYlTaFDL6K8a5o/T1EaJ1pw/JcnrQwnYzM9RAlWUFBqSTL6kCufkBys6/oKti9EtZfJSfZaWxIrPzUEY7UyEojLyHrPm7dNvStbYdpB91/KPN5stDm7K392E6OSRGzCueUYS61zQExtjDA8L3L2ieRQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
s=arcselector9901;
h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
bh=xqwdNa2tH0NAEVzNKrs0M+hpUQrq3zgqfZjHbyQA0/8=;
b=Hx5GepUTlyBRG3gg6T0BB1TU/TKnpFcbxex1RU8HCCLkF/ZvSFtiNdLo5ylV/9snUO3AwS3N2NZrGwm9JFpt5JEuNrtwXJwYyOOmtqvG4vFHsZk//t250JJH1p7S2ubRE55jdsI5qosTB7t+MdojUWYN4Q10xsdlaUxzzmhvFDdnHmMBzEJGsDT9mSLI+jag4nVcPv25IO3IhwdePubu7i40aaIOpXlktRiYVuSzkgiz10+5E6hSvBRHD/CDmZiYCaKi5gn68fFemXlA0G+nfvn/O4l965kTv+J0MEPf2PX6UuyjrfTAh6+gGw6hs/J7HVOp5DZ/RglHoM6yxm5W3g==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=pass
smtp.mailfrom=aivancity.ai; dmarc=pass action=none header.from=aivancity.ai;
dkim=pass header.d=aivancity.ai; arc=none
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=aivancity.ai;
s=selector1;
h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
bh=xqwdNa2tH0NAEVzNKrs0M+hpUQrq3zgqfZjHbyQA0/8=;
b=nenGs3dcVJ3xOm0oW8oPDe7OMSaYGI3txWVrtAyu52UrZUk45CVWGll0atiCv1MJER3EWP1rV/xdRWGpMO7ZPCav3rzVXnV1mixOp75Je2n8NBT++sysyN9NK7BsCkaJyEpIn6Tul3IQBfMDzUTk61/C4tsdUQw/i6RJQgt8hkTrWW/OZnExrF6yZY3ASnaqUjTANjD7gczc4dhldD59ozpKFKbxPhUtPbBbJEugatJzSCUbwOTDyIx1MP9vyTZzvU9s0TXpzRVoR7PhHScK12QiGKJPKhWJ6mV8VZFjdBOdq8PBn/vqSfYOgWK60jS7ALBt+Ubtmxf8N/qOGj0ubw==
Received: from PR0P264MB0250.FRAP264.PROD.OUTLOOK.COM (2603:10a6:100:5::11) by
PR1P264MB1581.FRAP264.PROD.OUTLOOK.COM (2603:10a6:102:1b2::8) with Microsoft
SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
15.20.4173.20; Fri, 28 May 2021 15:44:42 +0000
Received: from PR0P264MB0250.FRAP264.PROD.OUTLOOK.COM
([fe80::e5f8:10be:13d6:1699]) by PR0P264MB0250.FRAP264.PROD.OUTLOOK.COM
([fe80::e5f8:10be:13d6:1699%3]) with mapi id 15.20.4173.020; Fri, 28 May 2021
15:44:42 +0000
From: Administrateurs <admins@aivancity.ai>
To: "zaoui.michael@free.fr" <zaoui.michael@free.fr>
Subject: Votre compte utilisateur aivancity :
michael.zaoui@aivancity.education
Thread-Topic: Votre compte utilisateur aivancity :
michael.zaoui@aivancity.education
Thread-Index: AQHXU9hgItRn5iwxZ0uTvJI69QHyvA==
Importance: high
X-Priority: 1
Date: Fri, 28 May 2021 15:44:42 +0000
Message-ID:
<PR0P264MB02502CF111F022B8620FBBE6DF229@PR0P264MB0250.FRAP264.PROD.OUTLOOK.COM>
Accept-Language: fr-FR, en-US
Content-Language: en-US
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
x-ms-mail-application: Microsoft Power Automate; User-Agent:
azure-logic-apps/1.0 (workflow fde6fa6dceab47daad7ced0291076e57; version
08585793911431026661) microsoft-flow/1.0
x-ms-mail-operation-type: Send
x-ms-mail-environment-id: default-21e3f437-43d4-4ee7-9670-a6bebd6c9061
authentication-results: free.fr; dkim=none (message not signed)
header.d=none;free.fr; dmarc=none action=none header.from=aivancity.ai;
x-ms-exchange-messagesentrepresentingtype: 1
x-originating-ip: [52.136.133.184]
x-ms-publictraffictype: Email
x-ms-office365-filtering-correlation-id: ef0557c5-ad45-4131-6fcc-08d921ef82f5
x-ms-traffictypediagnostic: PR1P264MB1581:
x-ms-exchange-transport-forked: True
x-microsoft-antispam-prvs:
<PR1P264MB15812A70F98F949FDB86B4BEB6229@PR1P264MB1581.FRAP264.PROD.OUTLOOK.COM>
x-ms-oob-tlc-oobclassifiers: OLM:1728;
x-ms-exchange-senderadcheck: 1
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0
X-OriginatorOrg: aivancity.ai
X-MS-Exchange-CrossTenant-AuthAs: Internal
X-MS-Exchange-CrossTenant-AuthSource: PR0P264MB0250.FRAP264.PROD.OUTLOOK.COM
X-MS-Exchange-CrossTenant-Network-Message-Id: ef0557c5-ad45-4131-6fcc-08d921ef82f5
X-MS-Exchange-CrossTenant-originalarrivaltime: 28 May 2021 15:44:42.6749
(UTC)
X-MS-Exchange-CrossTenant-fromentityheader: Hosted
X-MS-Exchange-CrossTenant-id: 21e3f437-43d4-4ee7-9670-a6bebd6c9061
X-MS-Exchange-CrossTenant-mailboxtype: HOSTED
X-MS-Exchange-CrossTenant-userprincipalname: bjxeTlNGSkZ3qReH8JRn8baAXBrSmP7u0xaDUSCnPPD5/CrCCSlFOenCZq7/C9ko5UH4STWSverxap8JUaPvVA==
X-MS-Exchange-Transport-CrossTenantHeadersStamped: PR1P264MB1581
X-EsetId: 37303A29A9F2A96663746B
"

Sincerely,
Michael

**Comment by philipto** [comment]
@MichaelZPi Thank you for the clarification. Pull request merged.

**Pull request merged**
