### PR TITLE
Added UVM as a valid university

### PR DESCRIPTION
**Pull request by arturomaciaas**
Trying to add UVM (Universidad Del Valle de México) to JetBrains' list of valid universities.

### CODE REVIEW

**Comment by arturomaciaas** [comment]
Forgot to add proof:
https://uvmonline.zendesk.com/hc/es/articles/360023753832-Correo-institucional-my-uvm
E-mail structure: "jetbrains@my.uvm.edu.mx"

**Comment by arturomaciaas** [comment]
Also, this is the official link to my specific 3 year long bachelor's program: https://uvm.mx/oferta-academica/licenciaturas-ejecutivas/ingenierias-uvm-online/licenciatura-en-ingenieria-en-ciencia-de-datos-online

**Comment by philipto** [comment]
@arturomaciaas I am sorry, the domain my.uvm.edu.mx is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Comment by arturomaciaas** [comment]
Thank you, I managed to enroll with the GitHub student developer program. I have a question though, can I still apply for a 40% discount after I graduate using the "former student license holder" option? Thanks!

**Pull request closed without merging**
