### PR TITLE
msijanakpuri.com

### PR DESCRIPTION
**Pull request by MinalDhankar2**
Maharaja Surajmal Institute

### CODE REVIEW

**Review by MinalDhankar2 — COMMENTED** [review]
Domain: msijanakpuri.com
Name: Maharaja Surajmal Institute

**Comment by RaptusBube** [comment]
[file.zip](https://github.com/JetBrains/swot/files/7554903/file.zip)
Pls add this school address to yout repo.

**Comment by MinalDhankar2** [comment]
> [file.zip](https://github.com/JetBrains/swot/files/7554903/file.zip) Pls add this school address to yout repo.

Sorry my school name is already in my repo.

**Comment by MinalDhankar2** [comment]
> [file.zip](https://github.com/JetBrains/swot/files/7554903/file.zip) Pls add this school address to yout repo.

Can you please help me with more detail? thanks

**Comment by philipto** [comment]
@MinalDhankar2 lib/domains/com/msijanakpuri: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@MinalDhankar2 lib/domains/com/msijanakpuri: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@MinalDhankar2 lib/domains/com/msijanakpuri: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@MinalDhankar2 lib/domains/com/msijanakpuri: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by MinalDhankar2** [comment]
wrong request

**Pull request closed without merging**
