### PR TITLE
Add school domain

### PR DESCRIPTION
**Pull request by JonKachNCS**
Add Newark charter school delaware

### CODE REVIEW

**Comment by JonKachNCS** [comment]
school url : https://newarkcharterschool.org/hs-curriculum

**Comment by philipto** [comment]
@JonKachNCS You might miss my previous comment. Please react.

**Comment by JonKachNCS** [comment]
Thanks @philipto.  Since we have been given official chrome books from school, there was no letter specifying our email address. We only use school chrome book to access emails.  But I have reached out to school administrators for an official letter, it may take a few days.  I can see couple of other schools in your repo that use similar k12.de.us domains. I will post the letter as soon as I receive it.

**Comment by philipto** [comment]
@JonKachNCS The issue is that I found a lot of references to email addresses ending with ncs.k12.de.us, but not **ncs.charter.k12.de.us**. Could you please provide us with the document discussed above or explaining the difference between the two domains?

**Comment by philipto** [comment]
@JonKachNCS I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
