### PR TITLE
create new domain @soy.sena.edu.co

### PR DESCRIPTION
**Pull request by hulkike**
create new domain @soy.sena.edu.co for students

### CODE REVIEW

**Comment by philipto** [comment]
@hulkike First stage of verification passed, official domain is [sena.edu.co](https://sena.edu.co) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@hulkike Could you please clarify:
1) What is SENA? Is it a training center? Is it an association of schools?
2) Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

Thank you.

**Comment by hulkike** [comment]
@philipto 

1. What is SENA? Is it a training center? Is it an association of schools?: 
We offer free training to millions of Colombians who benefit from technical, technological and complementary programs that, focused on the economic, scientific and social development of the country, begin to strengthen the productive activities of companies and industry, to obtain better competitiveness and greater results in different markets. [https://en.wikipedia.org/wiki/National_Training_Service_(Colombia)](https://en.wikipedia.org/wiki/National_Training_Service_(Colombia))
3. Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. 
The official page is [https://sena.edu.co](https://sena.edu.co/es-co/Paginas/default.aspx) the domains are @sena.edu.co for teachers, @misena.edu.co and @soy.sena.edu.co for students link to the programs where IT is offered is [http://oferta.senasofiaplus.edu.co/sofia-oferta/detalle-oferta.html?fc=uT-yd4T741g](http://oferta.senasofiaplus.edu.co/sofia-oferta/detalle-oferta.html?fc=uT-yd4T741g) This career lasts 3984 hours(2 years)

**Comment by philipto** [comment]
@hulkike  Thank you for the clarifications. Pull request merged.

**Pull request merged**
