### PR TITLE
Create sbccd.edu

### PR DESCRIPTION
**Pull request by virgiltu**
Please create one for San Bernardino Community College

Thank you

### CODE REVIEW

**Comment by LarryStevens4524** [comment]
Hi!
I'm still getting 'Your email address does not belong to any university that we know. Contribute your university to our list.'

**Comment by LarryStevens4524** [comment]
http://www.sbccd.org/StudentEmail

**Comment by virgiltu** [comment]
Student Email Address Format
 http://www.sbccd.org/StudentEmail/Gmail_FAQs
firstinitial.lastnameXXXX@student.sbccd.edu

**Comment by philipto** [comment]
@virgiltu Thank you for the clarification! Pull request merged. Thank you!

**Pull request merged**
