### PR TITLE
Add woacademy.co.uk

### PR DESCRIPTION
**Pull request by woacademy**
URL|Course|Proof
:-:|:-:|:-:
http://www.woacademy.co.uk/|[KS3 ICT Long Term Plan](http://www.woacademy.co.uk/wp-content/uploads/2018/10/ks3-ltp-ict.pdf)|[GIAS Page](https://get-information-schools.service.gov.uk/Establishments/Establishment/Details/139918)

### CODE REVIEW

**Comment by philipto** [comment]
@woacademy Please rename lib/domains/uk/co/woacademy to lib/domains/uk/co/woacademy.txt
Thank you.

**Comment by woacademy** [comment]
@philipto done, apologies.

**Comment by philipto** [comment]
@woacademy Pull request merged. Thank you for the update!

**Comment by woacademy** [comment]
@philipto thank you :tada:

**Pull request merged**
