### PR TITLE
Add NTUA Domain

### PR DESCRIPTION
**Pull request by acc621**
Add National Taiwan University of Arts Email Domain

and Here's our official website,

I'm studying in the Visual Communication Design , thanks

https://aca.ntua.edu.tw/article.aspx?ca=211&id=140

### CODE REVIEW

**Comment by philipto** [comment]
@acc621 First stage of verification passed, official domain is [ntua.edu.tw](https://ntua.edu.tw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@acc621 Could you please tell us more about why do you need software development at the Visual Communication Design courses? What do you do there at the courses? At the first glance, the subject seems not be related to software development of any kind.

**Comment by acc621** [comment]
@philipto Because there's lots of web design or computer science course in the college (like using html5, css, js, vue.js, laravel, python to build a software or website), but honestly some courses are elective subject.
I don't know if it's ok for the situation, but thank you for your patience anyway.

**Comment by philipto** [comment]
@acc621  Thank you for the clarifications and for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
