### PR TITLE
Please add my middle school to the list.

### PR DESCRIPTION
**Pull request by kms0219kms**
Please add my middle school to the list.
Thank you.

### CODE REVIEW

**Comment by kms0219kms** [comment]
My middle school's NX Domain is two,
1. suwondasan.sXXXXXX@ggm.goe.go.kr
2. XXXXXXXX@suwondasanm.goe.go.kr
It would be better if both NX Domains could be registered.

**Comment by philipto** [comment]
@kms0219kms Please provide us with:
- the school official website URL
- the school street address, including city and country
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@kms0219kms You might miss my previous comment. Please react.

**Comment by kms0219kms** [comment]
> @kms0219kms Please provide us with:
> 
> * the school official website URL
> * the school street address, including city and country
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

URL: swdasan-m.goesw.kr (However, due to the education office's policy, you must register your mail address with the suwondasanm.goe.go.kr domain, not this domain.)
Address: 12, Hyeryeong-ro, Yeongtong-gu, Suwon-si, Gyeonggi-do, Republic of Korea

**Comment by philipto** [comment]
@kms0219kms Thank you for the clarification. Could you please upload a copy of the education office's policy as a comment to this request? The school website does not mention suwondasanm.goe.go.kr, as far as I see.

**Comment by kms0219kms** [comment]
> @kms0219kms Thank you for the clarification. Could you please upload a copy of the education office's policy as a comment to this request? The school website does not mention suwondasanm.goe.go.kr, as far as I see.

Yeah, suwondasanm.goe.go.kr is **only NX Domain**.
My school's official webpage is swdasan-m.goesw.kr.

Since all schools in Korea inherit the domain of their education offices and use it as NX Domain, the official website and domain are bound to be different. I ask for your understanding on this matter.

@philipto

**Comment by philipto** [comment]
@kms0219kms **Could you please upload a copy of the education office's policy as a comment to this request?**

I mean a copy of a document that you were given. It probably says that students have to use email addresses ending with @suwondasanm.goe.go.kr. There has to be some instruction that says "use suwondasanm.goe.go.kr as your email domain". It can be a printed paper or an email to you from the school.

**Comment by kms0219kms** [comment]
> @kms0219kms **Could you please upload a copy of the education office's policy as a comment to this request?**
> 
> I mean a copy of a document that you were given. It probably says that students have to use email addresses ending with @suwondasanm.goe.go.kr. There has to be some instruction that says "use suwondasanm.goe.go.kr as your email domain". It can be a printed paper or an email to you from the school.

Although the suwonasanm subdomain is not specified exactly, I will talk to the person in charge about the school email commercial cloud support policy and upload a copy soon.
The reason for consulting with the person in charge is that when you enter the school information when you sign up for a membership, it is automatically generated by mail containing the school name suwondasanm, and it is difficult to send a separate document.
Please wait a little longer.

**Comment by kms0219kms** [comment]
@philipto Thank you for waiting.
I'll translate and send you the phone conversation with the relevant email address management company.

"For such services, it is a state-sponsored service for the convenience of students' online classes and other student services, and schools cannot intervene, so schools and NX domains are bound to differ. If the NX domains are to be identical, the school itself must contract Microsoft to provide mail services."

He told me like this and explained that there is no policy that can be disclosed separately. In other words, it is provided as the government's own service, but it is not related to the school domain, so it should be handled in connection with the education office that provides the service. The official site of the local education office where I live is https://www.goe.go.kr and available in Korean.

**Comment by philipto** [comment]
@kms0219kms Thank you for the clarification. Pull request merged.

**Pull request merged**
