### PR TITLE
To add my educational institution 

### PR DESCRIPTION
**Pull request by stopidlearner**
Website : https://gci.edu.np/

### CODE REVIEW

**Comment by philipto** [comment]
@stopidlearner First stage of verification passed, official domain for **Global collage international** is [gci.edu.np](https://gci.edu.np) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@stopidlearner Please provide us with: an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by stopidlearner** [comment]
A levels : https://alevel.globalcollege.edu.np/  Computer science faculty
members:
https://web.globalcollege.edu.np/ContentManagement/TeamSetup/Index?Parameters=TeamType=;FacultyId=25c3671f-e346-45c3-838e-de6d463d6862&Component=Faculty

**Comment by philipto** [comment]
@stopidlearner Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
