### PR TITLE
Create tac.txt

### PR DESCRIPTION
**Pull request by Fuzzy0111**
The American Campus

### CODE REVIEW

**Comment by philipto** [comment]
@Fuzzy0111 Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Fuzzy0111 You might miss my previous comment. Please react.

**Comment by Fuzzy0111** [comment]
Hi Philip,

You asked for
1. the school official website URL
2. an URL of a page on the official website where the school offers an
IT-related long-term (>1 year) course
3. a proof, which shows that the school recognizes the domain you are
submitting as an official email domain for the students.

1.
official URL of The American Campus: http://tac.education/

2.
https://tac.education/bachelor-of-science-in-computer-science/
https://tac.education/us-degrees/

3.
I am looping in the following persons who will be able to provide the
required evidence (replying to this email).

   - Spalding Jugganaikloo, President and Founder
   - Pooja Ramyead, Marketing manager
   - Emma Celou Jugganaikloo, Business Development Consultant
   - Navish Nunkoo, IT Manager & Business Development Associate

@Spalding, @Pooja, @Emma, @Navish:
Jetbrains creates best-in-class software development tools which can be
beneficial for our students to code with.
There is a free offer of JetBrains Products for Learning and I have taken
the lead to register the email domain of The American Campus to JetBrains'
list.
You can find more information here:
https://www.jetbrains.com/community/education/#students
Our students can get a renewable educational license granting free access
to all developer tools from JetBrains for the ultimate learning experience
This is the final step.
Please kindly intervene and provide Jetbrains c/o Philip Torchinsky with
any form of evidence that the The American Campus recognizes the domain
"tac.education" as an official email domain for our students.

Thanks you and best regards,


*Gerald Ladouceur*
Lately I been, I been losing sleep
Dreaming 'bout the things that we could be
Baby I been, I been prayin' hard
Said no more counting dollars
We'll be, we'll be counting stars

*Save a tree. Do not print this email unless you really need to.*

**Comment by Fuzzy0111** [comment]
Hi Philip,

It is great meeting you!

Following up to mail from Gerald, we are authorising this to go forward with the official tac.education email domain.

Kind regards,

***@***.***D72D39.73DE6720]

**Comment by Fuzzy0111** [comment]
@Philip: if you need any other information please do not hesitate to
contact me.
Your assistance is greatly appreciated.
Thank you.

Kind regards,


*Gerald Ladouceur*
Lately I been, I been losing sleep
Dreaming 'bout the things that we could be
Baby I been, I been prayin' hard
Said no more counting dollars
We'll be, we'll be counting stars

*Save a tree. Do not print this email unless you really need to.*

**Comment by philipto** [comment]
@Fuzzy0111 Thank you very much for the clarification and your warm words! Pull request merged.

**Pull request merged**
