### PR TITLE
Added KLW

### PR DESCRIPTION
**Pull request by koflin**

### CODE REVIEW

**Comment by koflin** [comment]
Name: Kantonsschule Im Lee Winterthur
Site: https://www.ksimlee.ch/
Email: firstname.secondname@stud.ksimlee.ch

**Comment by philipto** [comment]
@koflin For the email pattern which you mentioned, firstname.lastname@stud.ksimlee.ch, the correct file name has to be lib/domains/ch/ksimlee.stud.txt
Please rename. Please notice that .txt extension is compulsory.

**Comment by koflin** [comment]
@philipto Done

**Comment by philipto** [comment]
@koflin I am sorry, but the filename is now lib/domains/ch/ksimlee.stud.txt.
I made a typo, the correct filename has to be lib/domains/ch/ksimlee/stud.txt. I apologize for my mistake, merge the pull request and rename the file myself.

**Pull request merged**
