### PR TITLE
Add new domain of University of Science and Technology of China

### PR DESCRIPTION
**Pull request by bestgu**
> University website：[https://www.ustc.edu.cn/](https://www.ustc.edu.cn/)
> Certificate website：[http://home.ustc.edu.cn/~sa515079/](http://home.ustc.edu.cn/~sa515079/)

### CODE REVIEW

**Comment by philipto** [comment]
@bestgu I have to close this request without merging, because you requested to add a non-existent domain to this repository: `` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by cuntu** [comment]
It's not a non-existent domain.

**Comment by bestgu** [comment]
It's not a non-existent domain.It's a domain have MX record of email service but have no http service.

**Comment by bestgu** [comment]
> @bestgu I have to close this request without merging, because you requested to add a non-existent domain to this repository: `` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

It's not a non-existent domain.It's a domain have MX record of email service but have no http service.

**Pull request closed without merging**
