### PR TITLE
Add school to the domain repository

### PR DESCRIPTION
**Pull request by pantaleonFerrer**

### CODE REVIEW

**Comment by philipto** [comment]
@pantaleonFerrer The first verification stage is complete: the official domain for  **Sant Nicolau** is [santnicolau.com](https://santnicolau.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://ciclesformatius.santnicolau.com/

**Comment by philipto** [comment]
@pantaleonFerrer Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by pantaleonFerrer** [comment]
Hi, there is the information you asked for:

- Website: https://santnicolau.com/
- Address: Calle del Jardí, 72-80. 08202 Sabadell, Barcelona, Spain
- https://ciclesformatius.santnicolau.com/es/inicio/ -> You can the that they do DAM and SMX (CFGM and CFGS) that are official and have a duration of 2 years
- I don't know how to prove it more than having the domain so every student and teacher email is xxxxxxx@stnicolau.com

**Comment by philipto** [comment]
@pantaleonFerrer  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
