### PR TITLE
Adding hwbcymru domain

### PR DESCRIPTION
**Pull request by uhCHS**
https://www.cardiffhigh.cardiff.sch.uk/
https://i.imgur.com/XQofrpK.png

### CODE REVIEW

**Comment by philipto** [comment]
@uhCHS Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. I am sorry, the screenshot of a mailbox is not enough. The screenshot shows that you probably has an access to the mailbox there, but it says nothing about recognition of the domain by the school.

**Comment by uhCHS** [comment]
@philipto Thanks for getting back to me, You can see this link which is from the government that the domain hwbcymru has been setup for 85% of Wales schools. This has been something that was enforced with the government and not with the the school its self. Thanks

**Comment by uhCHS** [comment]
forgot to provide the link https://gov.wales/wales-leads-way-microsoft-schools

**Comment by philipto** [comment]
@uhCHS Pull request merged. Thank you!

FTR: additional proof of the domain validity is at https://hwb.gov.wales/news/articles/dc715915-79e3-4582-8789-5ea9f664c908

**Comment by uhCHS** [comment]
@philipto Does it take time to activate?
https://i.imgur.com/XOsnS0q.png

**Comment by uhCHS** [comment]
working now thanks :+1:

**Pull request merged**
