### PR TITLE
add domain :  xingjian.gxu.edu.cn

### PR DESCRIPTION
**Pull request by klskeleton**
Please add Guangxi University Xingjian College of Science and Liberal Arts

webside:
http://xingjian.gxu.edu.cn/index.htm
IT Department  course:
http://xjlg.gxu.edu.cn/zyjs.htm
email:
xjwlxy@163.com

### CODE REVIEW

**Comment by klskeleton** [comment]
Our school has no  page to proof this email, but you can see this email at the bottom of the school website

**Comment by philipto** [comment]
@klskeleton Pull request merged. Thank you!

**Comment by klskeleton** [comment]
it's my pleasure

**Comment by klskeleton** [comment]
> @klskeleton Pull request merged. Thank you!
it's my pleasure

**Comment by klskeleton** [comment]
> @klskeleton Pull request merged. Thank you!

did i do something wrang ?  I want to apply for your product and say:
```
Your email address does not belong to any university that we know. You can apply with another method (see tabs above) or add your school to JetBrains' list.
```

**Pull request merged**
