### PR TITLE
Pull request to add the domain of Stanislascollege

### PR DESCRIPTION
**Pull request by TheKnight1993**

### CODE REVIEW

**Comment by philipto** [comment]
@TheKnight1993 This school official website and domain is `stanislascollege.nl`. Please provide us with a proof that the school recognizes the domain `stanislascollege.net` which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@TheKnight1993 You might miss my previous comment. Please react.

**Comment by TheKnight1993** [comment]
I am sorry, but the it department has recently decided that they are going to normalize the domains for the mail to stanislascollege.net and the old mails associated with one person (stanislasscw.net, stanislascollege.nl).
The site still is stanislascollege.nl cause it is hosted and is originally meant for the Netherlands.

https://imgur.com/a/xt5mbHb Here is a link for proof that I use this mail. I shall try and see if I can find again where the forwarded mails are.

**Comment by TheKnight1993** [comment]
https://imgur.com/a/1BpH2UY Here is a link for the forwarding of domains. The stanislascollege.nl domain is primarily used by teachers. To be honest if I recall correctly there was a time where I used a stanislascollege.net/nl domain but I don’t remember exactly what it was.

**Comment by philipto** [comment]
@TheKnight1993 Thank you for the clarification. Pull request merged.

**Pull request merged**
