### PR TITLE
Added fitstic mail info

### PR DESCRIPTION
**Pull request by PicchiSeba**

### CODE REVIEW

**Comment by philipto** [comment]
@PicchiSeba Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@PicchiSeba I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host fitstic-edu.edu not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by PicchiSeba** [comment]
I know this issue has closed but i tried to submit again because i realized that i made a mistake while inserting the data in the public repository. In the meantime i fixed it
    1. https://www.fitstic.it/        My school's official website    2. https://www.fitstic.it/it/b/154/tecnicosuperioreperlosvilupposoftwarecontecnologiesmarteiot        My school offers several courses, this is the one i'm currently attending (its name could be translated as "Higher Technician for Software Development and IOT and smart technologies") which is focused on software development; specifically we cover subjects such as networking and operating systems, web develpment, programming with Java, C# and Python and others. This course lasts 2 years, we have a total of 1060 hours of lessons and then another 800 hours of internship in the local companies.
At the end of this course i will have a Level 5 EQF Diploma, which qualifies as an expert technician focused on software develpment. This course is sponsored and (partially) payed by the local and italian government (https://www.fitstic.it/it/chi-siamo/gli-its)    3. What kind of proof do you need? Something like a document or my tutor's contact info?
   Il lunedì 1 marzo 2021, 18:50:29 CET, Philip Torchinsky <notifications@github.com> ha scritto:  
 
 


@PicchiSeba Please provide us with:
   
   - the school official website URL
   - an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
   - a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@PicchiSeba The issue seems to be resolved in #10897. Please send an email to community-support@jetbrains.com if you need any further help or have a feedback. Thank you!

**Pull request closed without merging**
