### PR TITLE
Added Magnus Åberg (school)

### PR DESCRIPTION
**Pull request by RealDebugg**

### CODE REVIEW

**Comment by philipto** [comment]
@RealDebugg Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@RealDebugg You might miss my previous comment. Please react.

**Comment by RealDebugg** [comment]
Adress: Karlstorpsvägen 159, Trollhättan, Sweden
Website: https://kunskapsforbundet.se/magnus-abergsgymnasiet/
Courses: https://kunskapsforbundet.se/app/uploads/2020/10/KFV_gykatalog_2021-2022_ver02_WEBB.pdf (the highschool I go to offers web development as a "side course" which you're allowed to chose in 2nd and 3rd grade, listed under "Tekniska programmet")
Proof part 1: https://drive.google.com/file/d/1QLUNxAYaNtmnVw72vWr2xvltkymPl9dh/view?usp=drivesdk
Proof part 2: https://drive.google.com/file/d/1pRp6Pl0PWoXYCDP5NlBwL9PQoc4TPnQk/view?usp=drivesdk

(Split into 2 parts to hide my password)

**Comment by philipto** [comment]
@RealDebugg Thank you for your patience while waiting for a review and processing your request. Pull request merged. Thank you!

**Pull request merged**
