### PR TITLE
add MASI

### PR DESCRIPTION
**Pull request by kvintskem**

### CODE REVIEW

**Comment by philipto** [comment]
@kvintskem Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by kvintskem** [comment]
@philipto this is a university.

- https://mitu-masi.ru/
- https://mitu-masi.ru/courses/vychislitelnye-mashiny-kompleksy-sistemy-i-seti/
- https://portal.mitu-masi.ru/       ->  button "СТУДЕНТАМ"    
domain to choose @s.masi.ru     this is a portal for students

**Comment by kvintskem** [comment]
@philipto why the process stopped? :(

**Comment by philipto** [comment]
@kvintskem I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Pull request merged**
