### PR TITLE
Add OpenCampus university

### PR DESCRIPTION
**Pull request by yonjukyu**
Hello, here i am again with the certificat i've been asking for

Here are the informations you asked

Respectfully

the school official website URL : [https://globalopencampus.com/open-campus-angers/](https://globalopencampus.com/open-campus-angers/)

the school street address, including city and country : 2 rue de la Martinellerie, Trélazé, 49800 Angers

an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course : [https://globalopencampus.com/learn-it-ecole-ingenierie-informatique/](https://globalopencampus.com/learn-it-ecole-ingenierie-informatique/)

a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. : 
image

### CODE REVIEW

**Comment by yonjukyu** [comment]
mail address pattern is [firstname.lastname@angers.globalopencampus.com](firstname.lastname@angers.globalopencampus.com)

**Comment by philipto** [comment]
@yonjukyu I have to close this request without merging, because you requested to add a non-existent domain to this repository: `` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by yonjukyu** [comment]
I think that this domain is correct, what is the error you got while trying to reach it ? it is not mentioned in the reason this merge request has been closed.

**Comment by yonjukyu** [comment]
This domain is a subdomain from globalopencampus.com, is it an issue ?

**Pull request closed without merging**
