### PR TITLE
"Escola Profissional do Infante"

### PR DESCRIPTION
**Pull request by NunoD87**

### CODE REVIEW

**Comment by philipto** [comment]
@NunoD87 Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@NunoD87 You might miss my previous comment. Please react.

**Comment by NunoD87** [comment]
Official website URL: http://epinfante.pt/
Offical website URL (IT): http://epinfante.pt/html/prof-curso-informatica.html

**Comment by philipto** [comment]
@NunoD87 Pull request merged. Thank you!

**Pull request merged**
