### PR TITLE
senaifatesg.txt

### PR DESCRIPTION
**Pull request by fabricioLeonard**

### CODE REVIEW

**Comment by philipto** [comment]
@fabricioLeonard Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@fabricioLeonard You might miss my previous comment. Please react.

**Comment by fabricioLeonard** [comment]
Sorry, I ended up using my personal email to register. I am passing on to the person in charge of the institution, the suggestion to register for the students. Thanks!

**Comment by philipto** [comment]
@fabricioLeonard Thank you for the update! Pull request closed.

**Pull request closed without merging**
