### PR TITLE
Add souclaretiano.edu.br

### PR DESCRIPTION
**Pull request by denisvba**
Add student e-mail domain souclaretiano.edu.br.
Homepage: claretiano.edu.br

### CODE REVIEW

**Comment by philipto** [comment]
@denisvba Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@denisvba You might miss my previous comment. Please react.

**Comment by denisvba** [comment]
Hello @philipto !
Thanks for taking the time to analyze my request!

First, I'm sorry for sending an incomplete request and for the delay to answer your questions.
I'm trying to contact my college and get some of the information.

Meanwhile, here is what I already know:
Claretiano, my current college, is an educational institution in Brazil since 1970. 
The official website of the institutions is: https://claretiano.edu.br
- There is a filter to see only IT-related courses. In _Área de Estudo_, select _Tecnologia e Sistemas_ or _Engenharia_.
- There are Undergraduate and Graduate options, both in-person and remote learning.
This is my course: https://claretiano.edu.br/graduacao/computacao
- Computing and Education

I did not find any officially translated website.
There is a domain already allowed, claretiano.edu.br, used by staff, professors, teachers, tutors, employees, and staff in general.

I will ask you for a few days to discuss with my college staff to check if the domain is the correct one and how to prove it.

Thanks so much!

**Comment by philipto** [comment]
@denisvba Thank you very much for the clarification. Pull request merged.

**Pull request merged**
