### PR TITLE
Added domain CMC University

### PR DESCRIPTION
**Pull request by NightBlad**

### CODE REVIEW

**Comment by philipto** [comment]
@NightBlad lib/domains/vn/edu/CMC: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@NightBlad This is a medical college, am I correct? If yes, please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by NightBlad** [comment]
> @NightBlad This is a medical college, am I correct? If yes, please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

@philipto Thanks for your attention. CMC Uni is digital university. Here is the link:
https://cmc-u.edu.vn/nganh-khoa-hoc-may-tinh/

**Comment by philipto** [comment]
@NightBlad  Thank you for the clarifications. Pull request merged.

**Pull request merged**
