### PR TITLE
Added Colégio Santa Dorotéia

### PR DESCRIPTION
**Pull request by gabriel-20210099-aluno-dorotheus**

### CODE REVIEW

**Comment by gabriel-20210099-aluno-dorotheus** [comment]
Could you please validate the PR? If possible, can you give me the status of the request?

**Comment by philipto** [comment]
@gabriel-20210099-aluno-dorotheus Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@gabriel-20210099-aluno-dorotheus You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@gabriel-20210099-aluno-dorotheus I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
