### PR TITLE
Added Government College of Engineering and Research, Avasari Khurd

### PR DESCRIPTION
**Pull request by DTan13**
Website [gcoeara.ac.in](https://gcoeara.ac.in)

### CODE REVIEW

**Comment by philipto** [comment]
@DTan13 lib/domains/in/ac/gcoeara: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by DTan13** [comment]
@philipto I have renamed the file gcoeara to gcoeara.txt

**Comment by philipto** [comment]
@DTan13 First stage of verification passed, official domain is [gcoeara.ac.in](https://gcoeara.ac.in) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@DTan13 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
