### PR TITLE
Add N Middle School (n-jr.jp)

### PR DESCRIPTION
**Pull request by arutaka1220**

### CODE REVIEW

**Comment by arutaka1220** [comment]
website: https://n-jr.jp

**Comment by arutaka1220** [comment]
Corporate Address:
    224 Ike Yonagusuku, Uruma City, Okinawa 904-2421, Japan

N Middle School is a separate school where students study while remaining enrolled in their own junior high school.

**Comment by philipto** [comment]
@arutaka1220 First stage of verification passed, official domain is [n-jr.jp](https://n-jr.jp) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@arutaka1220 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
