### PR TITLE
Create kingsolomonhigh.txt

### PR DESCRIPTION
**Pull request by CiaranDev**

### CODE REVIEW

**Comment by philipto** [comment]
@CiaranDev Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students. Also, please notice that the filename must end with .txt extension, thus please rename lib/domains/uk/co/kingsolomonhigh to lib/domains/uk/co/kingsolomonhigh.txt. Thank you!

**Comment by CiaranDev** [comment]
@philipto Thanks for the response, however is there a secondary way for me to contact you as due to Security restrictions within the school an Admin within the school is required to give you proof preferably via Email.

**Comment by philipto** [comment]
@CiaranDev Yes, no problem. Feel free to send an email to support@jetbrains.com mentioning that it's about adding a domain to SWOT repository on GitHub.

**Comment by philipto** [comment]
@CiaranDev Pull request merged. Thank you!

**Pull request merged**
