### PR TITLE
Add biu.txt

### PR DESCRIPTION
**Pull request by jaimesilvabiu**
Broward International University
URL: https://www.biu.us/
Address: 801 Brickell Ave Office 736 - 7th Floor, Miami, FL 33131, United States URL Program IT: https://www.biu.us/en/program/masters-of-science-in-virtual-software-engineering

### CODE REVIEW

**Comment by philipto** [comment]
@jaimesilvabiu First stage of verification passed, official domain for **Broward International University** is [biu.us](https://biu.us) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by jaimesilvabiu** [comment]
Thank you, you and your software are nice

I appreciate your time to attend my pull request.

**Comment by philipto** [comment]
@jaimesilvabiu Thank you for your warm words. Given that the university is 100% online and offers the courses internationally, this domain has higher risk of abuse than usual. 

1. Does the university charge any fee for the study prior to assign an email address to the student?
2. Could you please clarify whether only students currently enrolled to the university can use the email addresses ended with @biu.us?

**Comment by jaimesilvabiu** [comment]
1. The University offers scholarships to Latin america people but I paid for enrollment before I received my institutional email.
2. Students only can use @student.biu.us, the teachers use @faculty.biu.us

Do you need any further information?

**Comment by jaimesilvabiu** [comment]
I forget something, administration are only authorized to use @biu.us

**Comment by philipto** [comment]
@jaimesilvabiu  Thank you for the clarifications. Pull request merged.

**Pull request merged**
