### PR TITLE
Add Caraga State University Cabadbaran City

### PR DESCRIPTION
**Pull request by dollarsign143**
Added by Jaymark Caton

### CODE REVIEW

**Comment by dollarsign143** [comment]
Please review and approve my pull request. Thanks.

**Comment by dollarsign143** [comment]
Official university website is [https://www.csucc.edu.ph](https://www.csucc.edu.ph). 
Proof of affiliation [https://www.csucc.edu.ph/management-information-system-office/](https://www.csucc.edu.ph/management-information-system-office/)

**Comment by philipto** [comment]
@dollarsign143 Pull request merged. Thank you.

**Comment by dollarsign143** [comment]
Thanks.

**Pull request merged**
