### PR TITLE
Add Universitas Putra Indonesia

### PR DESCRIPTION
**Pull request by zaininijar**

### CODE REVIEW

**Comment by philipto** [comment]
@zaininijar First stage of verification passed, official domain for **Universitas Putra Indonesia** is [upiyptk.ac.id](https://upiyptk.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by zaininijar** [comment]
thanks sir...

Pada Sen, 1 Jul 2024 20.15, Philip Torchinsky ***@***.***>
menulis:

**Comment by philipto** [comment]
@zaininijar Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by zaininijar** [comment]
No problem, thank you for the update.

Pada Kam, 4 Jul 2024, 12.42, Philip Torchinsky ***@***.***>
menulis:

**Pull request merged**
