### PR TITLE
Fixes non-utf8 institution names

### PR DESCRIPTION
**Pull request by jmsmkn**
This PR does not add any new institutions but standardises the encoding for files that contained non-utf8 characters.

### CODE REVIEW

**Comment by philipto** [comment]
@jmsmkn I am sorry, I have to close the request without merging, because you made a mistake in a request and requested to merge too many files, most of them do not relate to the organization which you would like to add to this repository. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by jmsmkn** [comment]
This PR does not add any new organizations! Please look at the changes and you can see that this is fixing their names. Would be great if you could take the time to read the changes rather than sending out these automated messages after I put in the effort to fix this.

**Comment by jmsmkn** [comment]
Would you like me to make 35 new PRs, one for each file?

**Comment by philipto** [comment]
@jmsmkn I am very sorry, I was mistaken. This is a PR to correct spelling, not to add anything to the repository. I am merging it now. Thank you for the update.

**Pull request merged**
