### PR TITLE
Added two new domains for Colegiul National Roman Voda

### PR DESCRIPTION
**Pull request by RomanVoda**

### CODE REVIEW

**Comment by philipto** [comment]
@RomanVoda Please provide us with a proof, which shows that the school recognizes the domain romanvoda.ro that you are submitting as an official email domain for the students.

You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by RomanVoda** [comment]
@philipto 
image
https://www.rotld.ro/whois/?domain=romanvoda.ro
I added a link and o photo to the WHOIS you asked for.

**Comment by RomanVoda** [comment]
@philipto 
image
https://www.rotld.ro/whois/?domain=romanvoda.ro
I added a link and a photo to the WHOIS you asked for.
http://cnrv.ro/
I also added a link to our official site where you can find information about us.

**Comment by philipto** [comment]
@RomanVoda Thank you for the clarification. Pull request merged.

**Pull request merged**
