### PR TITLE
Arcplex formations

### PR DESCRIPTION
**Pull request by gravity-zero**
#### Institution/School Name 
ARCPLEX

#### Instiution/School Website
https://www.arcplex.fr/formation/

#### Email Users
@arcplex.fr

*Please place an x between the square brackets if yes*
- [x ] Students
- [x ] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [ ] Graduate School
- [x ] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [ ] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by philipto** [comment]
@gravity-zero First stage of verification passed, official domain is [arcplex.fr](https://arcplex.fr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@gravity-zero Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by gravity-zero** [comment]
@philipto Sorry, I think I misunderstood. Arcplex is a training company that provides courses in universities and within companies. No long training courses for the moment.

**Comment by philipto** [comment]
@gravity-zero  Thank you for the clarifications. 

Regrettably, I have to close the request without merging, because this organization is a training center, neither a college, nor a university. 

Please apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses.

Thank you for your understanding!

**Pull request closed without merging**
