### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MahadQorane**
Harris academy east Dulwich sixth form

### CODE REVIEW

**Comment by philipto** [comment]
@MahadQorane First stage of verification passed, official domain is [harrisdulwichboys.org.uk](https://harrisdulwichboys.org.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.harrisdulwichboys.org.uk/1478/east-dulwich-campus

**Comment by MahadQorane** [comment]
> @MahadQorane First stage of verification passed, official domain is [harrisdulwichboys.org.uk](https://harrisdulwichboys.org.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.harrisdulwichboys.org.uk/1478/east-dulwich-campus

@philipto Correction domain should be harrissixthform.org.uk. Thank you for your quick response

**Comment by MahadQorane** [comment]
> > @MahadQorane First stage of verification passed, official domain is [harrisdulwichboys.org.uk](https://harrisdulwichboys.org.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.harrisdulwichboys.org.uk/1478/east-dulwich-campus
> 
> @philipto Correction domain should be harrissixthform.org.uk. Thank you for your quick response

following is the official domain url https://www.harrissixthform.org.uk/

**Comment by philipto** [comment]
@MahadQorane Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
