### PR TITLE
add new city and school

### PR DESCRIPTION
**Pull request by MaisterOfDeath**
russia moscow 1580
lycu1580.mskobr.ru

### CODE REVIEW

**Comment by philipto** [comment]
@MaisterOfDeath Please provide us with a proof, which shows that the school recognizes the domain 1580.mos.ru that you are submitting as an official email domain for the students.

**Comment by MaisterOfDeath** [comment]
1580.mos.ru это не мой домен, вот мой домен lycu1580.mskobr.ru

**Comment by MaisterOfDeath** [comment]
1580.mos.ru is not my domain, here is my domain lycu1580.mskobr.ru

**Comment by philipto** [comment]
@MaisterOfDeath I am sorry, I am a bit confused now. What is an email pattern for teachers and students of your school? Is it username@lycu1580.mskobr.ru? If yes, I can rename the file in your request to lib/domains/ru/mskobr/lycu1580.txt, and merge the request.

**Comment by philipto** [comment]
@MaisterOfDeath I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
