### PR TITLE
Add Iscod

### PR DESCRIPTION
**Pull request by Dupy007**

### CODE REVIEW

**Comment by philipto** [comment]
@Dupy007 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Dupy007 You might miss my previous comment. Please react.

**Comment by Dupy007** [comment]
https://www.iscod.fr/

ISCOD PARIS
7 rue Henri Bocquillon
75015 Paris
01 88 24 66 99

**Comment by philipto** [comment]
@Dupy007 Thank you for the clarification! For the record: the domain **iscod.school** that you are submitting is registered to https://www.oktogone.com/, an educational group in France.

Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
