### PR TITLE
Add mintcollege to list of PH schools

### PR DESCRIPTION
**Pull request by mintcollege**
Add MINT College to list of schools.

### CODE REVIEW

**Comment by philipto** [comment]
@mintcollege Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by enchance** [comment]
> @mintcollege Please provide us with:
> 
> * the school official website URL
https://mintcollege.com/

> * the school street address, including city and country
We have 2 campuses. Here are both their addresses:

1. **MINT College McKinley Hill Campus**, 1030 Campus Avenue 2F CIP Bldg., McKinley Hill, Taguig City Philippines 1634
2. **MINT College Ortigas East Campus**, Silver City 1A, 4F, Central Avenue (formerly Frontera Dr.), Ortigas East, Pasig City Philippines 1604

> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
4-yr Bachelor of Science: https://mintcollege.com/computer-science

> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
I'm assuming you want written proof so I went ahead and emailed our admin to supply you with one. I'll follow it up within the next few days. I can understand the possible confusion since we're using a .com domain instead of the usual .edu.ph.

**Comment by philipto** [comment]
@mintcollege Thank you! Yes, you are quite right. I'll wait for the update from you. Thank you again for your understanding!

**Comment by philipto** [comment]
@mintcollege You might miss my previous comment. Please react.

**Comment by enchance** [comment]
> @mintcollege You might miss my previous comment. Please react.

I read it. It's still the weekend so I should be able to get back to you in the coming days.

**Comment by enchance** [comment]
@philipto Just checked this but it seems the http://mintcollege.edu.ph/ already redirects to our .com domain (https://mintcollege.com/). Is this enough proof or would you still rather wait for the d document?

**Comment by philipto** [comment]
@mintcollege Regrettably, a redirect from a domain which does not seem official to the official domain does not count. Let's wait for the document please.

**Comment by philipto** [comment]
@mintcollege I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
