### PR TITLE
Add Clovis School District

### PR DESCRIPTION
**Pull request by TheAwesomeAtom**
Clovis Unified School District in Clovis, California, USA

### CODE REVIEW

**Comment by TheAwesomeAtom** [comment]
Testing because I do not see tis pull request in the list of open pull requests.

**Comment by philipto** [comment]
@TheAwesomeAtom Please provide us with:
- the school official website URL
- the school street address, including city and state
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by TheAwesomeAtom** [comment]
The clovis unified school (cusd) district is the district that contains my specific school. 
-    Website: https://www.cusd.com/
-     Mailing Address: 1450 Herndon Ave, Clovis, CA 93611
My specific school within cusd is Clovis North High. 
-    Website: https://cnec.cusd.com/ClovisNorth_home.aspx
-     2770 East International Avenue Fresno, CA 93730
Its not easy to find an official webpage that mentions the student email address but I found one that explains it. 
Screenshot (285)
I put a box around the part that explains that students all have email addresses at cusdstudent.com . Also this is the webpage so that you can see for yourself. https://sites.google.com/a/clovisusd.k12.ca.us/swearengen-english10/

The only other thing that I can think of is that I receive lots of email from school to my email address. This is an email that was sent to me at my email address from my computer science teacher from his cusd account getting me in trouble with my dad because I left his zoom class 5 minutes early!
Screenshot (284)

The one thing that I'm worried about is that the school email sometimes blocks outside email so I don't know if the email will get through or if it will be bounced back. The school doesn't let students decide what gets through and what gets bounced back. So I don't know.

**Comment by philipto** [comment]
@TheAwesomeAtom Thank you very much for the clarification. Pull request merged. 
If you experience any trouble with emails going through, please send an email to JetBrains support: community-support@jetbrains.com.

**Pull request merged**
