### PR TITLE
fizmat

### PR DESCRIPTION
**Pull request by 9ag0**

### CODE REVIEW

**Comment by alehandrolima** [comment]
[faex.zip](https://github.com/JetBrains/swot/files/6697582/faex.zip)

**Comment by philipto** [comment]
@9ag0 Please provide us with:
- the school official website URL
- the school street address, including city and country

**Comment by 9ag0** [comment]
http://physmath.am/

**Comment by 9ag0** [comment]
Azatutyan Backstreet, Yerevan

**Comment by philipto** [comment]
@9ag0 Thank you for the clarification. Pull request merged.

**Pull request merged**
