### PR TITLE
Create jhncc.txt

### PR DESCRIPTION
**Pull request by danouthwaite**
http://www.johnhenrynewmancatholiccollege.org.uk/

### CODE REVIEW

**Comment by philipto** [comment]
@danouthwaite Could you please provide us with a proof that this email domain belongs to John Henry Newman Catholic College? according to WHOIS it is registered for a private person, Sean Gilligan, and I found no required proof. Thank you!

**Comment by danouthwaite** [comment]
http://www.johnhenrynewmancatholiccollege.org.uk/contact-us/

Email addresses for staff and main office located on the registered web domain.

**Comment by danouthwaite** [comment]
@philipto

**Comment by philipto** [comment]
@danouthwaite Thank you! Pull request merged.

**Pull request merged**
