### PR TITLE
https://projecao.br/Faculdade

### PR DESCRIPTION
**Pull request by fabiomuniz01**
https://projecao.br/faculdade/curso/23678/tecnologia-em-analise-e-desenvolvimento-de-sistemas-presencial-e-ead
https://projecao.br/Faculdade
https://projecao.br/faculdade/curso/conteudo/23678/modalidade/2/unidade/

### CODE REVIEW

**Comment by philipto** [comment]
@fabiomuniz01 According to #9791 and #9758, correct domain is projecao.edu.br.
Please explain what is wrong with #9791 and #9758 before applying.

**Comment by philipto** [comment]
@fabiomuniz01 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@fabiomuniz01 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by fabiomuniz01** [comment]
hi philipto i'm sorry for my delay, can i reopen the pull request?

**Pull request closed without merging**
