### PR TITLE
Add Piksi Ganesha Polytechnique | Indonesia

### PR DESCRIPTION
**Pull request by euclife**

### CODE REVIEW

**Comment by euclife** [comment]
Official Website : https://www.piksi.ac.id/
Address : Jl. Gatot Subroto No.301, Maleer, Kec. Batununggal, Kota Bandung, Jawa Barat 40274
Phone : (022) 87340030

**Comment by philipto** [comment]
@euclife First stage of verification passed, official domain is [piksi.ac.id](https://piksi.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@euclife Pull request merged. Thank you.

**Comment by euclife** [comment]
@philipto Thank you

**Pull request merged**
