### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Palaeocortex**
Added FZI Forschungszentrum Informatik

### CODE REVIEW

**Comment by Palaeocortex** [comment]
Website: https://www.fzi.de/en/

Thanks for considering my request.

**Comment by philipto** [comment]
@Palaeocortex Excuse me for possible misunderstanding: does this organization teach students? If not, it is clearly not eligible for being added to this repository. If it does, please provide us with  an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by Palaeocortex** [comment]
@philipto No problem. The institute does offer BA and MA thesis positions. Here is the website with available projects:
https://www.fzi.de/en/jobs-and-talents/theses/ 
https://karriere.fzi.de/Jobs/1?lang=ger&searchLink=1&searchPosition=20000014%20&ContentOnly= 

There are also PhD positions, with the professors who are involved in the research labs: 
https://www.fzi.de/en/the-fzi/who-we-are/board-of-scientific-directors/

**Comment by philipto** [comment]
@Palaeocortex Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

Please notice that the educational license is exclusively intended for educational purposes. If any employees of the Institute who are not students or teachers need the license, please kindly instruct them to email [sales@jetbrains.com](mailto:sales@jetbrains.com) to request an academic discount for a paid license.

**Pull request merged**
