### PR TITLE
Added student.tudelft.nl

### PR DESCRIPTION
**Pull request by jopenmolles**
The website: http://www.tudelft.nl/en/

Computer science course page: http://www.tudelft.nl/en/study/undergraduates-bachelors/undergraduate-programmes/computer-science/

### CODE REVIEW

**Comment by philipto** [comment]
@jopenmolles The upper-level domain tudelft.nl is in this repository for a long time already. Do you have any troubles in getting a license to an email in the @student.tudelft.nl domain? Please comment here or submit a request with more details on what happens when you request the license via jetbrains.com/student to support@jetbrains.com. Please double check if you filled in the email field with no typos before that, it happens to everybody, you know. Thank you!

**Comment by philipto** [comment]
@jopenmolles could you please comment on the issue above? I have to close the request without merging if you provide no updates on the issue. Thank you for the understanding!

**Comment by philipto** [comment]
@jopenmolles This request remains unanswered for a while. I have to close it without merging. Please reopen if you have an update. Thank you!

**Comment by jopenmolles** [comment]
Sorry for the late response, I was ill for a while.
I could now successfully use my @student.tudelft.nl email to apply for a license, so it was probably a typo.
Thank you!

**Pull request closed without merging**
