### PR TITLE
Create tifrh.res

### PR DESCRIPTION
**Pull request by sphCow**
add TIFR Hyderabad campus, TCIS

### CODE REVIEW

**Comment by zweizwei** [comment]
@sphCow the path should be in/res/tifrh.txt - please fix. Also please send me the link to the page, describing long-term educational programs (>1 year) that the center provides. Thank you!

**Comment by sphCow** [comment]
Yes, I've created a pull request (sphCow-patch-1) with the changes that you
suggested.

Here is the link to the page: http://www.tifrh.res.in/tcis/

Quoting from the official site itself:

"The most exciting areas of scientific research today are interdisciplinary
in character. The problems they are concerned with have diverse origins:
laboratories, hospitals, industry, and the natural world around us. What
unifies them is the intellectual challenge of new frontiers in basic
science.At the TIFR Centre for Interdisciplinary Sciences (TCIS) we will
explore these new vistas, creating a culture that transcends the divisions
of pure and applied, engineering and science, experiment and theory,
education and research. This pioneering centre will be the leading edge of
the Tata Institute of Fundamental Research's ambitious new presence in
Hyderabad, TIFR-H"

PS: I'm a research fellow of this institute.

Parswa Nath
Junior Research Fellow
TIFR Centre for Interdisciplinary Sciences
কবিতার খাতা -> https://dhulomegh.wordpress.com/

**Comment by zweizwei** [comment]
@sphCow unfortunately i do not see any information regarding courses schedule on the page, that you've provided - only regarding research activities. Please advise.

**Comment by zweizwei** [comment]
@sphCow i'm closing the request due to having no answer from you. Please reply to reopen.

**Pull request closed without merging**
