### PR TITLE
RPN added

### PR DESCRIPTION
**Pull request by StEvUgnIn**
RPN is the network of all Neuchâtel schools : CPLN and CIFOM technical schools included.

### CODE REVIEW

**Comment by StEvUgnIn** [comment]
Is it sufficient for you ?

All our email adresses are located in a common subdomain named s2.rpn.ch and end with rpn.ch though.

Here is a list of the schools related to this domain :
http://edus2.rpn.ch/Pages/Default.aspx

**Comment by StEvUgnIn** [comment]
Here is a traduction of some mail from the IT Department manager :
We teach formations in computer science indicated on this page : http://www.cifom.ch/index.php/les-ecoles/ecole-technique/formations
E-mail adresses are related to the domain @rpn.ch as indicated on that page : http://www.cifom.ch/index.php/les-ecoles/ecole-technique

**Comment by zweizwei** [comment]
Thanks for the info, I'm adding the domain.

**Comment by StEvUgnIn** [comment]
Thanks. You have just allowed more than 3000 people to have access to these softwares.

Students will get very happy !

**Pull request merged**
