### PR TITLE
Add School 1015

### PR DESCRIPTION
**Pull request by Vya4ik003**

### CODE REVIEW

**Comment by philipto** [comment]
@Vya4ik003 I am sirry, the official address of the school is different: sch1015z.mskobr.ru 
Please give us a proof that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Vya4ik003** [comment]
All screenshots were taken from the site https://sch1015z.mskobr.ru/info_edu/staff/.31.03.2020, 15:15, "Philip Torchinsky" <notifications@github.com>:
@Vya4ik003 I am sorry, the official address of the school is different: sch1015z.mskobr.ru
Please give us a proof that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Vya4ik003 I am sorry, GitHub strips out attachments if you send them by email. Please comment at https://github.com/JetBrains/swot/pull/7982, and attach the screenshots there. Thank you!

**Comment by Vya4ik003** [comment]
@philipto I am sorry. Here are the screenshots.

image

image

image

I hope the images are displayed now!

**Comment by philipto** [comment]
@Vya4ik003 Thank you very much for the clarification. Everything is visible now. Pull request merged.

**Comment by Vya4ik003** [comment]
Thank you!01.04.2020, 12:54, "Philip Torchinsky" <notifications@github.com>:
@Vya4ik003 Thank you very much for the clarification. Everything is visible now. Pull request merged.

**Pull request merged**
