### PR TITLE
Create obs-sottrum.txt

### PR DESCRIPTION
**Pull request by RonMeyer1007**

### CODE REVIEW

**Comment by philipto** [comment]
@RonMeyer1007 Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by RonMeyer1007** [comment]
Hey,
My School E-Mail is ron.schluseneck@obs-sottrum.eu and the Website is
obs-sottrum.de

The School Website has a different Domain end.

Philip Torchinsky <notifications@github.com> schrieb am Do., 12. Apr. 2018,
15:33:

**Comment by philipto** [comment]
@RonMeyer1007 Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by RonMeyer1007** [comment]
Hey,
Can i apply me now fOR a Free License?
When i Type ron.schluseneck@obs-sottrum.eu in the E-Mail Field says to me:
"Your Email Adress does not belong to any University that we know."

But you merged it. Please Help.

Philip Torchinsky <notifications@github.com> schrieb am Do., 12. Apr. 2018,
15:41:

**Pull request merged**
