### PR TITLE
University Nangui Abrogoua

### PR DESCRIPTION
**Pull request by Assamoi-Intelligence**

### CODE REVIEW

**Comment by Assamoi-Intelligence** [comment]
add una

**Comment by philipto** [comment]
@Assamoi-Intelligence I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host univ-una.ci not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by Assamoi-Intelligence** [comment]
Hi @philipto  this is the university official website URL https://www.univ-na.ci/

**Comment by philipto** [comment]
@Assamoi-Intelligence I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host univ-una.ci not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Pull request closed without merging**
