### PR TITLE
Instituto Tecnológico Popular Igualitario Andrés Ibáñez

### PR DESCRIPTION
**Pull request by JFGP-GH**

### CODE REVIEW

**Review by JFGP-GH — COMMENTED** [review]
https://www.tecnologicoandresibanez.edu.bo/index.html

**Comment by JFGP-GH** [comment]
https://www.tecnologicoandresibanez.edu.bo/index.html

**Comment by philipto** [comment]
@JFGP-GH First stage of verification passed, official domain is [tecnologicoandresibanez.edu.bo](https://tecnologicoandresibanez.edu.bo) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@JFGP-GH Thank you for the request. The official university website lacks a significant information about the educative offer. We cannot verify the school's eligibility for this repository without this information at the website. Thus, I have to close the request without merging.

Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Pull request closed without merging**
