### PR TITLE
Institut TIC de Barcelona added

### PR DESCRIPTION
**Pull request by Juanma-san**
Please add the high school "Institut TIC de Barcelona" to the accepted entities

### CODE REVIEW

**Comment by philipto** [comment]
@Juanma-san The first verification stage is complete: the official domain for  **Institut TIC de Barcelona** is [agora.xtec.cat](https://agora.xtec.cat), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://agora.xtec.cat/iticbcn/categoria/cicles-formatius/

**Comment by philipto** [comment]
@Juanma-san Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by Juanma-san** [comment]
Hello,

The "Institut TIC de Barcelona" offers courses of 2000h/each, where the
total hours are distributed in 2 year courses. One of them is Web developer
specialist and its description can be found here:
https://agora.xtec.cat/iticbcn/cfgs-desenvolupament-daplicacions-web-daw-icc0/

Greetings
__________________

Juan Manuel Sánchez Bel

Tutor DAW2A

Tutor de pràctiques DAW2A

**Comment by philipto** [comment]
@Juanma-san The first verification stage is complete: the official domain for  **Institut TIC de Barcelona** is [agora.xtec.cat](https://agora.xtec.cat), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://agora.xtec.cat/iticbcn/categoria/cicles-formatius/

**Comment by philipto** [comment]
@Juanma-san You might miss my previous comment. Please react.

**Comment by Juanma-san** [comment]
Hi I replied to the mail of the course duration in april the 26 at 14:54h
with the following content:

__________________
Hello,

The "Institut TIC de Barcelona" offers courses of 2000h/each, where the
total hours are distributed in 2 year courses. One of them is Web developer
specialist and its description can be found here:
https://agora.xtec.cat/iticbcn/cfgs-desenvolupament-daplicacions-web-daw-icc0/

Greetings
__________________

Juan Manuel Sánchez Bel

Tutor DAW2A

Tutor de pràctiques DAW2A

**Comment by philipto** [comment]
@Juanma-san The first verification stage is complete: the official domain for  **Institut TIC de Barcelona** is [agora.xtec.cat](https://agora.xtec.cat), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://agora.xtec.cat/iticbcn/categoria/cicles-formatius/

**Comment by philipto** [comment]
@Juanma-san I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
