### PR TITLE
create mode83

### PR DESCRIPTION
**Pull request by sergeMode83**
create mode83 developement scool

### CODE REVIEW

**Comment by philipto** [comment]
@sergeMode83 Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university

**Comment by sergeMode83** [comment]
https://mode83.net/site/presentation-du-centre-de-formation/#presentation

thank's

**Comment by sergeMode83** [comment]
Hello Philip,

here is an official document that state our valid agreement with the Nice french university.
Thank's
[MODE agrément éducation nationale 2015.pdf](https://github.com/JetBrains/swot/files/2748929/MODE.agreement.education.nationale.2015.pdf)

**Comment by philipto** [comment]
@sergeMode83 Thank you for providing an additional information regarding your school. According the agreement which you kindly submitted, as far as I understand, your school is accredited by the Academy of Nice as follows:
"ARTICLE 1: Accreditation to provide assistance to Public Education, under Article D.551-1 of the Education Code, in the form:
of interventions during school time in support of teaching activities, 
workshops and multimedia digital animations,
complementary educational activities outside school time,
multimedia workshops and digital entertainment, 
digital image education, 
internet risk awareness, 
fight against illiteracy"

All of the activities above do not seem to be a long-term IT-related course which make the school qualifying for being added to this repository. I still strongly advise you to request a free license by email to community-support@jetbrains.com.

**Comment by philipto** [comment]
@sergeMode83 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
