### PR TITLE
Create jecrc

### PR DESCRIPTION
**Pull request by r-singhal**
Jaipur Engineering College & Research Centre

### CODE REVIEW

**Comment by philipto** [comment]
@r-singhal lib/domains/in/ac/jecrc: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@r-singhal The first verification stage is complete: the official domain for  **Jaipur Engineering College & Research Centre** is [jecrcfoundation.com](https://jecrcfoundation.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://jecrcfoundation.com/fee/

**Comment by r-singhal** [comment]
Yes, you are correct that "jecrcfoundation.com" is the website domain name but the email address created by JECRC College for all their students ends with "@jecrc.ac.in"

rishabhsinghal.cse19@jecrc.ac.in this is my complete college e-mail id.

**Comment by philipto** [comment]
@r-singhal Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.** Thank you.

**Pull request merged**
