### PR TITLE
Create rouenbs

### PR DESCRIPTION
**Pull request by hprasadraj**

### CODE REVIEW

**Comment by hprasadraj** [comment]
www.rouenbs.fr

https://www.neoma-bs.com/en/

**Comment by philipto** [comment]
@hprasadraj Please rename lib/domains/fr/rouenbs to lib/domains/fr/rouenbs.txt
Thank you.

**Comment by philipto** [comment]
@hprasadraj You might miss my previous comment. Please react.

**Comment by hprasadraj** [comment]
Apologies @philipto , I tried to change the file format but not sure why i am not able to do it. 
Can you cancel this pull request. I will create a new pull request.

**Comment by hprasadraj** [comment]
Apologies for the late action. 
renamed, please review and approve the commit. 
Thank you.

**Comment by hprasadraj** [comment]
@philipto  Thank you very much!!

**Pull request merged**
