### PR TITLE
adding university official website URL: https://www.jinnah.edu/ and .txt file

### PR DESCRIPTION
**Pull request by uddinislam46**
Adding the university official website URL: https://www.jinnah.edu/ and .txt file
University Full Name
**Mohammad Ali Jinnah University Karachi Pakistan**

### CODE REVIEW

**Comment by philipto** [comment]
@uddinislam46 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@uddinislam46 You might miss my previous comment. Please react.

**Comment by uddinislam46** [comment]
Hi @philipto ,

Thank you for contacting me. You can verify maju.edu.pk domain that I am submitting as an official email domain for the students of Muhammad Ali Jinnah University (MAJU) by contacting on the following email:
info@jinnah.edu (Source: https://www.jinnah.edu/contact/)

Thanks & Regards,
Isalamuddin
fa14ms0014@maju.edu.pk

**Comment by philipto** [comment]
@uddinislam46 Pull request merged. Thank you!

FTR: proof of the domain ownership is at https://scholar.google.com/citations?user=UqgsZc4AAAAJ&hl=en

**Comment by uddinislam46** [comment]
Great. Thanks, Sir @philipto 👍 💯 :)

**Pull request merged**
