### PR TITLE
Create archapprentices.txt

### PR DESCRIPTION
**Pull request by UnacceptableUse**
Site URL: https://www.archapprentices.co.uk/

### CODE REVIEW

**Comment by philipto** [comment]
@UnacceptableUse I am sorry, your organization does not look like typical university nor a college. Could you please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by UnacceptableUse** [comment]
- The URL is the only URL they have
 - 18 month data programs for [Data Analyst](https://www.archapprentices.co.uk/apprentices/apprenticeship-programmes/data-analyst/), [Web Developer](https://www.archapprentices.co.uk/apprentices/apprenticeship-programmes/it-web-developer/), [Software Developer](https://www.archapprentices.co.uk/apprentices/apprenticeship-programmes/software-developer/)
- Not sure how to prove that, I could screenshot an email I got from them, at my @archapprentices.co.uk email address about the course? Would that suffice?

**Comment by philipto** [comment]
@UnacceptableUse Could you please confirm that this school is NOT an online-only school, and the students attends classes in the school physical classrooms?

**Comment by UnacceptableUse** [comment]
Yes there are physical classrooms. Would you like me to provide proof?

**Comment by philipto** [comment]
@UnacceptableUse Yes, it would be nice if you post a comment with the proof. As for now, I am merging this reuqest, and you can start requesting the licenses in an hour. I appreciate if you comment this requerst with a proof. Thank you.

**Pull request merged**
