### PR TITLE
Adding DPS Newtown

### PR DESCRIPTION
**Pull request by adityaukil**

### CODE REVIEW

**Comment by philipto** [comment]
@adityaukil Please provide us with:
- the school official website URL
- the school street address, including city and country

**Comment by adityaukil** [comment]
School website: https://www.dpsnewtownkolkata.com/
School address: Delhi Public School Newtown
Block- DG/3, Action Area-I, Newtown, Rajarhat,
Kolkata, INDIA. 
Postal code: 700 156
School contact us page: https://www.dpsnewtownkolkata.com/contact-us/index.php

**Comment by philipto** [comment]
@adityaukil The contact page that you advised me says that the email domain of the school is dpsnewtownkolkata.com.
You request to add dpsn.org.in as the school domain. 

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by adityaukil** [comment]
Whois link: https://www.whois.com/whois/dpsn.org.in
The whois data shows the company name as the school name. Also visiting the domain shifts the visitor to the main school website. 
The email account was provided to us at the start of the pandemic by the school and the login details provided in an email so that we can use Google Classroom and Google Meet as the email account is on Google platform. The school do not allow change of password of the email account and as such I have hidden the password from the screenshot attachment. 
Screenshot 2021-09-04 at 12 12 13 PM

**Comment by philipto** [comment]
@adityaukil Thank you very much for the clarification. Pull request merged.

**Pull request merged**
