### PR TITLE
Update stoplist.txt

### PR DESCRIPTION
**Pull request by LeoColman**

### CODE REVIEW

**Comment by philipto** [comment]
@LeoColman lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by LeoColman** [comment]
@philipto Could you please enlighten  me on what is wrong with this pull request?
I'm adding University of São Paulo's alumni domain to the stop list, and I believe it's on the right filepath and format.

**Comment by philipto** [comment]
@LeoColman Thank you for the request. The contributors of this repository are not generally supposed to modify a stoplist.txt. Could you please explain why would you like to include this domain to the stoplist?

**Comment by LeoColman** [comment]
Absolutely!

Students at the University of São Paulo are usually assigned a `student_name@usp.br` email when they enroll (already supported by this repository). After gratuation, this email is disabled, and the student keeps a `student_name@alumni.usp.br` email instead.

The alumni email isn't for current students, that's why I'm suggesting it gets removed.

**Comment by philipto** [comment]
@LeoColman lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by LeoColman** [comment]
Ok, @philipto, this doesn't seem the kind of contribution you want for swot.
I'm closing this.

**Comment by philipto** [comment]
@LeoColman I am sorry, I just was not fast enough in merging your pull request. While the format is not expected, your idea of excluding the subdomain for already graduated students is 100% correct. I really appreciate your feedback. Regrettably, I cannot reopen your pull request, because you closed it yourself. Thus, I just make the same change to stoplist.txt, you can check it in few minutes.

Thank you for the clarification and contribution.

**Pull request closed without merging**
