### PR TITLE
Adding Bsacet.org

### PR DESCRIPTION
**Pull request by Anujkrsh**
#### Institution/School Name 
B.S.A. College of Engineering and Technology

#### Instiution/School Website
{[B.S.A. College of Engineering and Technology](https://www.bsacet.org/)}

#### Email Users  xyz@bsacet.org

*Please place an x between the square brackets if yes*
- [x] Students
- [x] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [ ] Graduate School
- [x] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [ ] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by Anujkrsh** [comment]
If any Doubt/Question while reviewing this PR please mention in comments will be happy to help you instead of rejecting

**Comment by philipto** [comment]
@Anujkrsh First stage of verification passed, official domain is [bsacet.org](https://bsacet.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Anujkrsh** [comment]
Dear @philipto,
Thanks for the update regarding the status just wanted to have your attention regarding the repository PR merge as we have few students who are eagerly waiting for this PR to merge.

Thanks

**Comment by philipto** [comment]
@Anujkrsh Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
