### PR TITLE
add file educadventista

### PR DESCRIPTION
**Pull request by Mathwesm**
Url: https://unasp.br/quem-somos/,  I hope it’s correct now. Thank you very much!

### CODE REVIEW

**Comment by Mathwesm** [comment]
Sorry for the wrong domain. Thank you very much for explaining the information in more detail. I will wait for the final response, thank you again.

**Comment by philipto** [comment]
@Mathwesm Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by Mathwesm** [comment]
Good afternoon, I’ve been waiting for 5 hours as instructed, but I still haven’t been able to activate my license. It’s showing that my university is not listed

**Comment by philipto** [comment]
@Mathwesm Would you please write here in the comment which domain you would like to add?

I’ll double check it tomorrow. Thank you.

**Comment by Mathwesm** [comment]
Centro universitário adventista de São Paulo is unasp.br

**Pull request merged**
