### PR TITLE
Create candortci.txt

### PR DESCRIPTION
**Pull request by nenek2023**
Website: https://candortci.edu.ph/

### CODE REVIEW

**Comment by philipto** [comment]
@nenek2023 First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/candortci/

**Comment by philipto** [comment]
@nenek2023 Please provide us with the school street address, including the city. Thank you.

**Comment by philipto** [comment]
@nenek2023 You might miss my previous comment. Please react.

**Comment by nenek2023** [comment]
@philipto  Hello Philip, Sorry I missed you previous reply, But here’s the address
Kamagong Street, Barangay Sainz, Mati City, Davao Oriental, Philippines 8200

**Comment by philipto** [comment]
@nenek2023 First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/candortci/?locale=ms_MY

**Comment by philipto** [comment]
@nenek2023 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
