### PR TITLE
Create aluno.txt

### PR DESCRIPTION
**Pull request by Zuruckt**

### CODE REVIEW

**Comment by Zuruckt** [comment]
Offical article from the Education Department:
https://www.seduc.ce.gov.br/2020/04/02/parceria-entre-seduc-e-google-permite-acesso-de-estudantes-e-professores-a-ferramentas-educacionais-online/

**Comment by philipto** [comment]
@Zuruckt I am sorry, it is unclear to me what is the school name, where it is located, and why the students use email addresses in this domain.

Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Zuruckt** [comment]
Actually the domain is used by professional schools that are both a high school and have integrated technical courses all over the state of Ceará, Brazil, I was not sure about what to put in school name so I put the school I study on. I read something about .group in the tutorial but I didn't fully understand how it is supposed to work, if you could provide some info on that I would be glad.

- Website that we check our current information with the provided domain: https://aluno.seduc.ce.gov.br/
- Proof that we have IT related courses: https://educacaoprofissional.seduc.ce.gov.br/index.php?option=com_content&view=article&id=183&Itemid=247
- Proof that the schools recognize the domain: https://www.ceara.gov.br/2020/04/02/parceria-entre-seduc-e-google-permite-acesso-de-estudantes-e-professores-a-ferramentas-educacionais-online/ 
https://www.seduc.ce.gov.br/2016/04/27/seduc-disponibiliza-plataforma-virtual-para-estudantes-da-rede-estadual/ ( this one is older and it has a typo where they added www to the start of the URL so it leads to the wrong page)

**Comment by philipto** [comment]
@Zuruckt I am sorry. I have to close the request without merging. This repository is for email domains of universities and colleges only. We do not add email domains of large umbrella institutions, such as ministries of education, state-level school unions, etc. 

Please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students). When you apply with your official document, you can use any email, including your private email.

**Pull request closed without merging**
