### PR TITLE
Create lspu.txt

### PR DESCRIPTION
**Pull request by Nikoru14**
adding our school domain

### CODE REVIEW

**Comment by philipto** [comment]
@Nikoru14 First stage of verification passed, official domain is [lspu.edu.ph](https://lspu.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Nikoru14 Thank you for the request. However the program descriptions do not exist at the official website: https://lspu.edu.ph/college_profile/spc/ccs

What kind of program/course do you study?

**Comment by philipto** [comment]
@Nikoru14 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@Nikoru14 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by Nikoru14** [comment]
> @Nikoru14 Thank you for the request. However the program descriptions do not exist at the official website: https://lspu.edu.ph/college_profile/spc/ccs
> 
> What kind of program/course do you study?
Im sorry for the late reply but i do study Computer Science Major in Intelligent Systems

Our LSPU Siniloan Campus offers that
https://lspu.edu.ph/college_profile/sc/ccs

I dont know why the official website doesn't have details of the course/program

Would you kindly merge it I really need access to professional version of PyCharm for my project/thesis

**Pull request closed without merging**
