### PR TITLE
Added Addis Ababa Institute of Technology (AAiT)

### PR DESCRIPTION
**Pull request by yaredgdb123**

### CODE REVIEW

**Comment by philipto** [comment]
@yaredgdb123 First stage of verification passed, official domain is [m.facebook.com](https://m.facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/arce.aait.aau/photos/msc-and-phd-in-railway-engineering-scholarship-announcement-2018application-dead/185605042028721/

**Comment by yaredgdb123** [comment]
Thanks for the update on the process. if it helps in the review process, our student portal is also on the same domain.
Here is the link: https://portal.aait.edu.et

**Comment by yaredgdb123** [comment]
Hey @philipto, I couldn't access the portal as well so I'll try notifying the administrators and get back to you when it is up if it is okay with you.

**Comment by philipto** [comment]
@yaredgdb123 First stage of verification passed, official domain is [arifchereta.com](https://arifchereta.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://arifchereta.com/tenders/addis-ababa-university-addis-ababa-institute-of-technology-invites-consulting/

**Comment by yaredgdb123** [comment]
Hey @philipto, I'm unaware of the domain arifchereta.com but the portal https://portal.aait.edu.et/ seems to be working again as of me writing this comment.

**Comment by philipto** [comment]
@yaredgdb123 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
