### PR TITLE
Create ogvo

### PR DESCRIPTION
**Pull request by BLX-S**
Added ogvo

### CODE REVIEW

**Comment by philipto** [comment]
@BLX-S Please rename lib/domains/nl/ogvo to lib/domains/nl/ogvo.txt, .txt extension is mandatory.

**Comment by philipto** [comment]
@BLX-S Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by BLX-S** [comment]
@philipto Yes, our schools qualify as higher education. We also offer a specific programming curriculum.

**Comment by philipto** [comment]
@BLX-S Pull request merged. Thank you for the clarification!

**Pull request merged**
