### PR TITLE
Create chuoko.txt

### PR DESCRIPTION
**Pull request by lbqtchp**
add Chuo College of Technology

### CODE REVIEW

**Comment by philipto** [comment]
@lbqtchp Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@lbqtchp You might miss my previous comment. Please react.

**Comment by lbqtchp** [comment]
@philipto 
thank you for review my commit.
①　an IT-related long-term (2 year) course:情報ビジネス科（Department of Information Business）
https://chuoko.ac.jp/course-index/international-course-information/
This course including Information processing technology.
②　a screenshot proof 　with brief translation explanation.
https://www.dropbox.com/s/x9e9727gyuxbljf/1565692036%281%29.jpg

**Comment by philipto** [comment]
@lbqtchp Thank you for the clarification. Pull request merged.

**Pull request merged**
