### PR TITLE
Added Domain for Ahmadu Bello University, Zaria

### PR DESCRIPTION
**Pull request by aimamisa**
1. Ahmadu Bello University, Zaria aka ABU Zaria is located in Kaduna (Northern) state of Nigeria.
2. ABU Zaria is the largest Sub-Saharan University in Africa.
3. The link to the official website is: https://abu.edu.ng

### CODE REVIEW

**Comment by aimamisa** [comment]
22 hours and no response already, common.

**Comment by philipto** [comment]
@aimamisa 
You requested to add a non-existent domain:
```
$ host abu.abu-zx.edu.ng
Host abu.abu-zx.edu.ng not found: 3(NXDOMAIN)
```
Please make sure that you are familiar with the repository rules located at the bottom of [this page](https://github.com/JetBrains/swot), and modify your request accordingly. Please notice that we usually process a pull request within three business days.

**Comment by aimamisa** [comment]
Resolved the file issue.
Thanks.

//cc: @philipto

**Comment by philipto** [comment]
@aimamisa Thank you! Pull request is now merged.

**Pull request merged**
