### PR TITLE
add Brest Business School domain

### PR DESCRIPTION
**Pull request by manalelaji**

### CODE REVIEW

**Comment by philipto** [comment]
@manalelaji First stage of verification passed, official domain is [brest-bs.com](https://brest-bs.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by manalelaji** [comment]
Hello @philipto, Could you please tell me how much does the verification process take ?
Thank you for the efforts.

**Comment by philipto** [comment]
@manalelaji Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. We need to ensure that your school provides courses where JetBrains tools are useful.

Regrettably, we receive many requests from people who pretend to be students in need of free licenses, but some of them redistribute the free licenses for a fee. We condemn free license abuse and have to conduct security checks.

**Comment by philipto** [comment]
@manalelaji You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@manalelaji I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
