### PR TITLE
Adding First Moscow State Medical University

### PR DESCRIPTION
**Pull request by manmitya**
First Moscow State Medical University
http://old.1msmu.ru
https://sechenov.ru/

### CODE REVIEW

**Comment by philipto** [comment]
@manmitya Could you please provide us with a link to an IT-related long-term (> 1 year) course which your  university offers to the students? Thank you!

**Comment by philipto** [comment]
@manmitya You might miss my previous comment. Please reply.

**Comment by manmitya** [comment]
There is IT department in our University. It is the first IT medical department in Russian public healthcare.
Articles about it:
https://riaami.ru/2016/06/pervaya-v-rossii-kafedra-it-tehnologij-v-zdravoohranenii-sozdana-v-mgmu-im-i-m-sechenova/
https://www.medvestnik.ru/content/news/Otkrylas-pervaya-v-Rossii-kafedra-informacionnyh-i-internet-tehnologii-v-medicine.html
For example there is course "Use of IT in medicine" for students of 4 and 5 course: https://sechenov.ru/univers/structure/institute/institut-personalizirovannoy-meditsiny/kafit/

**Comment by philipto** [comment]
@manmitya Thank you for the update! Pull request merged.

**Pull request merged**
