### PR TITLE
Add Hill College 

### PR DESCRIPTION
**Pull request by mischievous-snek**
Website is https://www.hillcollege.edu/ and the email format is First.Last@student.hillcollege.edu

### CODE REVIEW

**Comment by philipto** [comment]
@mischievous-snek file/lib/domains/edu/hillcollege/student.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@mischievous-snek I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by mischievous-snek** [comment]
Hey Philip, I emailed support a few days ago because I am very unfamiliar with github, but I haven't received a response yet.


________________________________

**Comment by philipto** [comment]
@mischievous-snek Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
