### PR TITLE
Added a new school

### PR DESCRIPTION
**Pull request by Hypee3238**
Official website URL: [https://elektronik.edu.pl/](elektronik.edu.pl)

### CODE REVIEW

**Comment by philipto** [comment]
@Hypee3238 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@Hypee3238 You might miss my previous comment. Please react.

**Comment by Hypee3238** [comment]
> @Hypee3238 You might miss my previous comment. Please react.

Yes, sorry for that.
The only proof that I have is the message I got from my school when they gave me the credentials to my account but since the messages get deleted every year I do not have access to it as it already got deleted 2 years ago. On the school's website there isn't any information about what email addresses the school uses too, so I think I am out of options here...
I'm very sorry for confusion.

**Comment by philipto** [comment]
@Hypee3238 There is still one good option for you. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
