### PR TITLE
Karlfeldtgymnasiet

### PR DESCRIPTION
**Pull request by gabmar0908**
Add the Swedish gymnasium Karlfeldtgymnasiet

### CODE REVIEW

**Comment by gabmar0908** [comment]
https://translate.google.com/translate?sl=sv&tl=en&js=y&prev=_t&hl=sv&ie=UTF-8&u=http%3A%2F%2Fwww.avesta.se%2FBarn--Utbildning%2FGymnasieskola%2FVara-gymnasieprogram-hosten-2011%2FTeknikprogrammet%2FVara-inriktningar%2F&edit-text=&act=url

**Comment by philipto** [comment]
@gabmar0908 Thank you for your request. Could you please confirm that the email domain is owned solely by the school, and respective email addresses will be given to the school's teachers and students only (not alumni or just community members)? 

Also, is the spelling of the school name correct? You put "Avesta Karlfeldtgymnasium" in the .txt file, and the official website calls it Avesta Karlfeldtgymnasiet. It can be just a grammatical case, I am sorry, I do not speak Swedish.

**Comment by gabmar0908** [comment]
Not sure on how to confirm it. But the @edu.avesta.se is only given to students and teachers. Non-school related personel may use the @avesta.se.

It's just a grammatical case. You may call it Avesta Karlfeldtgymnasiet and Avesta Karlfeldtgymnasium, depending on the context.

**Comment by philipto** [comment]
@gabmar0908 Thank you for the clarification. Pull request merged.

**Pull request merged**
