### PR TITLE
added avh.txt

### PR DESCRIPTION
**Pull request by Lergin**
domain is only in use for the school server and emails
webpage is at http://avh.schulhomepages.hamburg.de/
proof of use: http://avh.schulhomepages.hamburg.de/?page_id=36 email of
the "Betreuer der Homepage"

### CODE REVIEW

**Comment by zweizwei** [comment]
@Lergin the path should be /de/hamburg/avh.txt

**Comment by Lergin** [comment]
@zweizwei really? the domain is avh.hamburg and not avh.hamburg.de ...

**Comment by zweizwei** [comment]
@Lergin is there any way to confirm this information? who.is doesn't give any details on avh.hambugr and the website itself doensn't open. Thanks in advance for your help.

**Comment by Lergin** [comment]
@zweizwei hamburg and not hambugr ;)

**Comment by zweizwei** [comment]
@Lergin oh, indeed, sorry for the typo :) I'm adding the domain then

**Pull request merged**
