### PR TITLE
adding Folkwang-uni

### PR DESCRIPTION
**Pull request by Leon-Focker**
added Folkwang University of the arts to the repo

### CODE REVIEW

**Comment by philipto** [comment]
@Leon-Focker First stage of verification passed, official domain is [folkwang-uni.de](https://folkwang-uni.de) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Leon-Focker Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by Leon-Focker** [comment]
Hey, sure! This is the schedule for my institute (institute for Computermusic and eletronic media):
https://icem-www.folkwang-uni.de/icem-web/stundenplan/
You can find courses like Musikinformatik 1 and 2, or Partitursynthese there. Sadly there is no website for the individual courses.

**Comment by philipto** [comment]
@Leon-Focker  Thank you for the clarifications. Pull request merged.

**Pull request merged**
