### PR TITLE
Adding ICM UW in Warsaw

### PR DESCRIPTION
**Pull request by dami95**
https://icm.edu.pl/en/

### CODE REVIEW

**Comment by philipto** [comment]
@dami95 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by dami95** [comment]
Screenshot of my profile on our university OpenOLAT system. Zrzut ekranu 2020-10-5 o 22 22 41

**Comment by philipto** [comment]
@dami95 I am sorry, a screenshot without a browser address bar cannot be accepted as a proof. If you have an instruction which was sent or given to the students, where an email domain is mentioned, such a document is much better proof than a screenshot.

Also, the screenshot, which you have attached shows that the email is in icm.edu.pl domain, and you submit the domain **icm.pl**. If the email domain is in fact icm.edu.pl, no additional proofs are needed, because the email domain is the same as the official university website domain. However, the file has to be renamed to lib/domains/pl/edu/icm.txt.

**Comment by dami95** [comment]
I'm sorry, I added #9513 :)

**Pull request closed without merging**
