### PR TITLE
Add some perks

### PR DESCRIPTION
**Pull request by bzntm**
AMIK Mahaputra, Yasop, SMAN 2 Balige, SMAN 1 Serang Baru, and Belajar.ID

### CODE REVIEW

**Comment by philipto** [comment]
@bzntm Please provide us with a proof, which confirms that Indonesian Ministry of Education and Culture assign students and teachers with email addresses in a domain belajar.id. Thank you.

**Comment by philipto** [comment]
@bzntm First stage of verification passed, official domain is amikmahaputra.ac.id as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@bzntm You probably missed my comment yesterday. Please react:

Please provide us with a proof, which confirms that Indonesian Ministry of Education and Culture assign students and teachers with email addresses in a domain **belajar.id**. Thank you.

**Comment by bzntm** [comment]
> @bzntm Please provide us with a proof, which confirms that Indonesian Ministry of Education and Culture assign students and teachers with email addresses in a domain belajar.id. Thank you.

Let me translate it to English, since the official Belajar.ID webpage is in Bahasa:

_Akun Pembelajaran_ (further called as belajar.id) are assigned to students, teachers, and school administrators from ALL schools, starting from playgroup, primary school, junior high school, senior high school, school for special needs (_SLB_), and equivalency programme (_Kesetaraan/Kejar Paket_).
By using belajar.id, you can access anything you need to support learning activites, starting from accessing _Kemendikbudristekdikti_ (Indonesian Ministry of Education, Culture, Research, and Higher Education) up to accessing apps for supporting learning activities

Government's Statement:
belajar.id is a governmental programme through Indonesian Ministry of Education, Culture, Research, and Higher Education to help and support learning activities

Here's attached screenshots in Bahasa:
Screenshot (237)
Screenshot (238)
Screenshot (236)
Screenshot (239)

**Comment by bzntm** [comment]
> @bzntm You probably missed my comment yesterday. Please react:
> 
> Please provide us with a proof, which confirms that Indonesian Ministry of Education and Culture assign students and teachers with email addresses in a domain **belajar.id**. Thank you.

See above reply by me, thank you

**Comment by philipto** [comment]
@bzntm First stage of verification passed, official domain is amikmahaputra.ac.id as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@bzntm Thank you for the clarification. Pull request merged.

**Pull request merged**
