### PR TITLE
Create stanborough

### PR DESCRIPTION
**Pull request by agreenherts**

### CODE REVIEW

**Comment by philipto** [comment]
@agreenherts lib/domains/uk/sch/herts/stanborough: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by agreenherts** [comment]
Good morning
Am trying to add @stanborough.herts.sch.uk as a domain and struggling.  Can you help?
Thanks
Adam Green

Mr A Green
Assistant Headteacher

Stanborough School
Lemsford Lane
Welwyn Garden City
Hertfordshire
AL8 6YR
T: 01707 321755

Please consider the environment before printing this email

**Comment by philipto** [comment]
@agreenherts lib/domains/uk/sch/herts/stanborough: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@agreenherts I corrected and merged the request. However it was a duplicate, and the school was in our trusted list earlier. Please send an email to community-support@jetbrains.com if you need further assistance.

**Pull request merged**
