### PR TITLE
Add unindra in the list

### PR DESCRIPTION
**Pull request by mousearts**
Adding Universitas Indraprasta 

University url: https://unindra.ac.id/
Informatics education program: https://unindra.ac.id/page/program-studi-informatika

### CODE REVIEW

**Comment by WinkeyCheng** [comment]
School request. Thx!
[file.zip](https://github.com/JetBrains/swot/files/5879715/file.zip)

**Comment by mousearts** [comment]
Can you please review it @philipto ? Thank you.

**Comment by philipto** [comment]
@mousearts Pull request merged. Thank you!

@WinkeyCheng Please create a separate pull request. Don't upload file.zip. It was expected that you unzip file.zip file, fork SWOT repository, add unzipped file to your forked SWOT repository to an appropriate folder (lib/domains/hk/edu/), and make a new pull request.

**Comment by WinkeyCheng** [comment]
Ok received thx

2D-08 CHENG WAN KIU WINKEY

________________________________

**Pull request merged**
