### PR TITLE
Add Salford City College

### PR DESCRIPTION
**Pull request by lukewain**

### CODE REVIEW

**Comment by philipto** [comment]
@lukewain First stage of verification passed, official domain is [salfordcc.ac.uk](https://salfordcc.ac.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by hhamad007** [comment]
@philipto Hello, I want my college email to be verified. I dont understand how can I create a pull request.

**Comment by philipto** [comment]
@lukewain Thank you for your patience while waiting for a review and processing your request. Pull request merged. Thank you!

@hhamad007 Please send an email to community-support@jetbrains.com from your school email, and mention your school's full name.

**Comment by hhamad007** [comment]
@philipto Is there any YT video which can help me to make a pull request?

**Pull request merged**
