### PR TITLE
Add Nangui Abrogoua University

### PR DESCRIPTION
**Pull request by tuxbedev**

### CODE REVIEW

**Comment by philipto** [comment]
@tuxbedev First stage of verification passed, official domain is [univ-na.ci](https://univ-na.ci) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@tuxbedev Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@tuxbedev You might miss my previous comment. Please react.

**Comment by tuxbedev** [comment]
The official website of University https://www.univ-na.ci/ and http://www.una-ufrsfa.ci/ the officiel website  SFA ("Sciences fondamentales appliquées"), department of IT.

**Comment by philipto** [comment]
@tuxbedev  Thank you for the clarifications. Pull request merged.

**Pull request merged**
