### PR TITLE
Add Century High School

### PR DESCRIPTION
**Pull request by one-and-only**

### CODE REVIEW

**Comment by one-and-only** [comment]
Official school website: https://chs.rochesterschools.org/
School address: 2525 Viola Rd NE, Rochester, MN 55906, USA

**Comment by one-and-only** [comment]
> @one-and-only Please provide us with:
> 
> * the school official website URL
> * the school street address, including city and country

Official school website: https://chs.rochesterschools.org/
School address: 2525 Viola Rd NE, Rochester, MN 55906, USA

**Comment by philipto** [comment]
@one-and-only Thank you very much for the clarification. Pull request merged.

**Comment by one-and-only** [comment]
Is there an ETA on it being updated on the JetBrains site? It currently still says that it's an invalid school domain email. Thank you.

**Comment by philipto** [comment]
@one-and-only An update usually propagates through the system within an hour. Thus, you can try right now, it should work. Thank you.

**Comment by one-and-only** [comment]
It works. Thank you very much!

**Pull request merged**
