### PR TITLE
Add University

### PR DESCRIPTION
**Pull request by haivt-tnn**

### CODE REVIEW

**Comment by TonKunGzlab** [comment]
[file (1).zip](https://github.com/user-attachments/files/16478096/file.1.zip)

**Comment by TonKunGzlab** [comment]
[g.txt](https://github.com/user-attachments/files/16478100/g.txt)

**Comment by haivt-tnn** [comment]
[file.zip](https://github.com/user-attachments/files/16478354/file.zip)

**Comment by philipto** [comment]
@haivt-tnn I am sorry, the domain ictu.edu.vn is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
