### PR TITLE
Create fukui.txt

### PR DESCRIPTION
**Pull request by nomunomu0504**

### CODE REVIEW

**Comment by nomunomu0504** [comment]
please add my school.
website is http://www.fukui-nct.ac.jp/

**Comment by philipto** [comment]
@nomunomu0504 The website says that the official email contact is in @fukui-nct.ac.jp domain. Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by nomunomu0504** [comment]
@philipto please check this url. (http://www.fukui-nct.ac.jp/~ip/O365_ProPlus.pdf)
my school student often use @fukui.kosen-ac.jp domain, but teacher use both domain.
thank you

**Comment by philipto** [comment]
@nomunomu0504 Thank you for the clarification! Pull request merged. Thank you!

**Pull request merged**
