### PR TITLE
Mongolia International University

### PR DESCRIPTION
**Pull request by sinclaireo**

### CODE REVIEW

**Comment by philipto** [comment]
@sinclaireo First stage of verification passed, official domain is [instagram.com](https://instagram.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.instagram.com/2002_miukorea/

**Comment by sinclaireo** [comment]
When I try to apply and put 2020068@miu.edu.mn on the email address it says "Your email address does not belong to any university that we know. You can apply with another method (see tabs above) or [add your school](https://www.jetbrains.com/shop/eform/students/contributeUniversity?email=2020068%40miu.edu.mn) to JetBrains' list." 
How can I resolve this?

**Comment by sinclaireo** [comment]
Can you please help me?

**Comment by philipto** [comment]
@sinclaireo Pull request merged. Thank you.

Please wait at least 60 minutes after you received this message. Then please apply again. Thank you.

**Pull request merged**
