### PR TITLE
Add Technology University

### PR DESCRIPTION
**Pull request by chanmratekoko**
Add Computer University and Technology University

Technological University (Pakokku): [https://tupku.edu.mm/](https://tupku.edu.mm/)

### CODE REVIEW

**Comment by philipto** [comment]
@chanmratekoko I am sorry, I cannot merge the request yet, because the University of Computer Studies website is now unavailable, answering:
>  The requested service is temporarily unavailable. It is either overloaded or under maintenance. Please try later.

I'll get back to this request later. Thank you for your understanding.

**Comment by philipto** [comment]
@chanmratekoko The website remains not accessible.

**Comment by chanmratekoko** [comment]
@philipto 

Hello,
Sorry for the inconvenience,
The website and server are under maintenance by the gov server.
Computer University (Sittway): http://www.ucssittway.edu.mm/

**Comment by philipto** [comment]
@chanmratekoko Thank you for the update! Pull request merged.

**Pull request merged**
