### PR TITLE
Create bztgoldenburgde.txt

### PR DESCRIPTION
**Pull request by mirrorhot**

### CODE REVIEW

**Comment by philipto** [comment]
@mirrorhot Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. The official website does not mention this address. The proof can be an email sent to you from the school administration or something like that.

**Comment by philipto** [comment]
@mirrorhot You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@mirrorhot I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Comment by mirrorhot** [comment]
If you only had waited 10 minutes longer: https://imgur.com/a/aRP9rSo

**Pull request closed without merging**
