### PR TITLE
Update and rename materdei.txt to unimater.txt

### PR DESCRIPTION
**Pull request by JGattringer**
Faculdade Mater Dei changed its name and now is operating by the name of UNIMATER - Universidade Mater Dei

### CODE REVIEW

**Comment by philipto** [comment]
@JGattringer First stage of verification passed, official domain for **Faculdade Mater Dei** is [materdei.edu.br](https://materdei.edu.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@JGattringer Thank you for the update. I did not find the update announcement at the official website. Could you please provide us with the URL of the official update announcement?

**Comment by JGattringer** [comment]
@philipto hello mate hopes you are doing well!
so the Faculdade Mater Dei now is called UNIMATER, here is the current website https://www.materdei.edu.br/
you can see the the domain still the same but the change their name of institution and before they used to have a email for students finishing as @materdei.edu.com but now all emails are generate as @unimater.com.br
here is a link were the university say to open public tha the change to UNIMATER was accepted and from there on the Faculdade Mater Dei is now called UNIMATER

**Comment by philipto** [comment]
@JGattringer I am terribly sorry but I do not see what I need there.

> here is a link were the university say to open public tha the change to UNIMATER was accepted and from there on the Faculdade Mater Dei is now called UNIMATER

Where exactly is it? Could you please provide a screenshot? Please upload it as a comment to https://github.com/JetBrains/swot/pull/20558, because if you send it by email, GitHub strips it: it does not allow attachments in comments sent by email.

Also, I have no doubt that you are right, and the school is renamed. I need the proof the new email domain is now recognized as official. It is the rule of this repository: add only officially recognized domains to the trusted list.

Please provide us with a proof, which shows that the school recognizes the domain **unimater.edu.br** that you are submitting as an official email domain for the students.
You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@JGattringer You might miss my previous comment. Please react.

**Comment by JGattringer** [comment]
Hey Philip hope u are doing well !
I just got busy with work and university tests that started!
Philip I appreciate your time and effort but I decided that I will leave this behind, I tried to provide proof of what I’m saying but I need now to ask for a lot of other docs etc so I decided that I will leave this behind and go with eclipse IDE that is free, I know that IntelliJ is a better one but I can’t be bothered now with this !
Really appreciate your time and effort replying to me!
Have a great Sunday !
Regards
Joao


Sent from my iPhone

On 14 Apr 2024, at 00:34, Philip Torchinsky ***@***.***> wrote:

﻿

@JGattringer<https://github.com/JGattringer> You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@JGattringer Thank you for your efforts! Please send an email to community-support@jetbrains.com if you will need further assistance. I have to close this request as for now.

**Pull request closed without merging**
