### PR TITLE
Create uni-nke.txt

### PR DESCRIPTION
**Pull request by lazloz92**
University name: National University of Public Service
Website: http://en.uni-nke.hu/

### CODE REVIEW

**Comment by philipto** [comment]
@lazloz92 Could you please provide us with a link to an IT-related course which the university is offering to students? Thank you!

**Comment by philipto** [comment]
@lazloz92 This request remains unanswered for a while. I am closing it. Please reopen if you have an update for it. Thank you!

**Comment by lazloz92** [comment]
@philipto I did not find the english version of this page but at this link you can see the IT-related courses: http://hhk.uni-nke.hu/oktatasi-egysegek/katonai-uzemelteto-intezet/informatikai-tanszek/kepzes

**Comment by philipto** [comment]
@lazloz92 Thank you! I am now ready to merge your pull request, but you need to reopen it first. GitHub allows reopening to the initial contributor only. Please reopen, and I'll merge it.

**Comment by philipto** [comment]
@lazloz92 Pull request merged. Thank you!

**Comment by lazloz92** [comment]
Thank you!

**Pull request merged**
