### PR TITLE
Add NAKKKIM

### PR DESCRIPTION
**Pull request by t-tiana**
Add NAKKKIM to UA domains

https://en.wikipedia.org/wiki/National_Academy_of_Government_Managerial_Staff_of_Culture_and_Arts

https://nakkkim.edu.ua/

@philipto
@nataershova

### CODE REVIEW

**Comment by philipto** [comment]
@t-tiana Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. I did not find any course at the website of the Academy that might include some software development tasks.

Thank you!

**Comment by philipto** [comment]
@t-tiana You might miss my previous comment. Please react.

**Comment by sw-is** [comment]
@philipto You are right and the Academy does not offer a matching course, but the It department would be happy to get the license to develop a modern website and the IT infrastructure for the academy. We are planning to develop an internal software product for the art expertise center. https://nakkkim.edu.ua/instituti/instituti-institut-praktichnoji-kulturologiji-ta-art-menedzhmentu/tsentr-ekspertizi-kulturnikh-tsinnostej

**Comment by t-tiana** [comment]
@philipto You are right and the Academy does not offer a matching course, but the IT department would be happy to get the license to develop a modern website and the IT infrastructure for the Academy. We are planning to develop an internal software product for the Art Expertise Center. https://nakkkim.edu.ua/instituti/instituti-institut-praktichnoji-kulturologiji-ta-art-menedzhmentu/tsentr-ekspertizi-kulturnikh-tsinnostej

**Comment by philipto** [comment]
@t-tiana Thank you for the explanation! Educational licenses are for educational purpose only. Please send an email to sales@jetbrains.com and discuss the matter with them. You will at least get an academic discount, and they probably will be able to offer more to support you.

I have to close the request.

Thank you for your work and using JetBrains tools!

**Pull request closed without merging**
