### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by IrmaYanti0202**
Add nurulfikri.sch.id

### CODE REVIEW

**Comment by philipto** [comment]
@IrmaYanti0202 First stage of verification passed, official domain is [nurulfikri.sch.id](https://nurulfikri.sch.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by IrmaYanti0202** [comment]
Thank you @philipto

**Comment by philipto** [comment]
@IrmaYanti0202 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@IrmaYanti0202 You might miss my previous comment. Please react.

**Comment by IrmaYanti0202** [comment]
Hi @philipto, sorry  for late response.
https://smait.nurulfikri.sch.id/ here in Activities tab, we have Information and Communication Technology class for 10th - 12nd grade

**Comment by philipto** [comment]
@IrmaYanti0202  Thank you for the clarifications. Pull request merged.

**Pull request merged**
