### PR TITLE
added tccd.edu for Tarrant County College

### PR DESCRIPTION
**Pull request by eric-d-brown**

### CODE REVIEW

**Comment by eric-d-brown** [comment]
I just seen this on the blacklist.  They just restructured and changed their emailing system July 10th of this year.  Not sure what put it on that list, but from my understanding only students and staff can use it.  Could somebody please shed some light on this?

**Comment by eric-d-brown** [comment]
Yeah, I found your response here:

https://github.com/JetBrains/swot/pull/6419

I want to challenge this.  Their contact number is provided:
817-515-6411

I just spoke to a Chris in their support department and inquired about this (which I want you to do directly, so you don't have to take my work for it) and he confirmed that nobody can just request and email and get one.  They have to be either staff or be a student (assigned a Student ID).  Even their new email system they implemented, requires the default password to be 'Tcc + 7-digit Student ID + 6-digit DOB' as the initial temporary password to log in.

I don't mind (like others) sending documentation; however, the process is long and definitely not optimal.

**Comment by philipto** [comment]
@eric-d-brown Thank you for your update and the suggestion. 

While thousands of schools from all around the world are in SWOT repository, there are also many schools which are not. It is absolutely fine for many people studying in these schools to apply with their school-issued IDs at jetbrains.com/shop/eform/students. 

I understand that it is a bit less convenient than applying with an email. Regrettably, JetBrains experiences a storm of requests from fake student accounts, thus it is unlikely that we will remove tccd.edu from the blacklist soon.  Certainly, it can be reconsidered in future.

Also, as you can imagine, many people possess their tccd.edu accounts illegally now, unless TCCD administration decided to cancel the accounts, and JetBrains has no resources to check if they were cancelled indeed.

I am sorry, I have to close this request without merging. Thank you for the understanding!

**Comment by eric-d-brown** [comment]
@philipto Appreciate your feedback, and understandable.  It will take some collaboration w/ the college itself... which from my experiences they seem to be willing to help with.  Definitely understand the position of JetBrains on this.  Thank you, again, for the feedback and appreciate your time.

**Pull request closed without merging**
