### PR TITLE
Add Westminster school

### PR DESCRIPTION
**Pull request by Jbithell**
https://www.westminster.org.uk/

### CODE REVIEW

**Comment by vogon101** [comment]
+1

**Comment by philipto** [comment]
@Jbithell Thank you for your request. You might actually wish to submit a request for `lib/domains/uk/org/westminster.txt` instead of `lib/domains/org/uk/westminster.txt`, if the domain which you have an email in is **westminster.org.uk**. If so, please change your request accordingly.
Thank you!

**Comment by Jbithell** [comment]
_Corrected as requested_

**Comment by philipto** [comment]
@Jbithell Thank you! Pull request merged.

**Pull request merged**
