### PR TITLE
add undergraduate institute

### PR DESCRIPTION
**Pull request by cybermaique**
add senairs - brazil

### CODE REVIEW

**Comment by cybermaique** [comment]
Does my registration certificate serve as a document? Attached is the same

Em qua., 13 de out. de 2021 às 13:16, Philip Torchinsky <
***@***.***> escreveu:

**Comment by philipto** [comment]
@cybermaique Regrettably, GitHub strips out the attachments sent by email. Please upload your certificate with your browser and I can check if it can be a proof of the domain recognition. If it's an official enrollment certificate on a letterhead it most probably fits.

**Comment by philipto** [comment]
I reopen the pull request. It was closed automatically because the email domain mentioned in the request became unreachable. It is still necessary to upload a proof of the domain recognition by the university. Thank you!

**Comment by cybermaique** [comment]
Hello

In anex the comprovant

Em sex., 5 de nov. de 2021 às 08:20, Philip Torchinsky <
***@***.***> escreveu:

**Comment by philipto** [comment]
@cybermaique I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by cybermaique** [comment]
what do you mean non-existent domain? I would like more information,
so I could not understand! The domain exists, it's the one used by the
university I study! I had a great effort to get the receipt, and after
sending it to you, you just inform me that the domain does not exist
?? I really didn't understand

**Comment by cybermaique** [comment]
What do you mean non-existent domain? I would like more information, so I
could not understand! The domain exists, it's the one used by the
university I study! I had a great effort to get the receipt, and after
sending it to you, you just inform me that the domain does not exist ?? I
really didn't understand

Em sáb., 6 de nov. de 2021 às 19:14, Philip Torchinsky <
***@***.***> escreveu:

**Pull request closed without merging**
