### PR TITLE
Create kunskapsforbundet.txt

### PR DESCRIPTION
**Pull request by daande01**

### CODE REVIEW

**Comment by philipto** [comment]
@daande01 Could you please describe your school in a bit more details? In particular, do students under 13 of age study in the school? Also, I appreciate if you capitalize the words in the school title in the file in this request, like this: "Kunskapsförbundet Väst". It reflects the name of the school at the official website.

**Comment by philipto** [comment]
@daande01 You might miss my previous comment on the issue with your request. Could you please answer it? Thank you!

**Comment by daande01** [comment]
sorry for  late replay. the students are 16-19

 Daniel Andersson

Den 25 dec 2016 02:44 skrev "Philip Torchinsky" <notifications@github.com>:

**Comment by philipto** [comment]
@daande01 Pull request merged. Thank you!

**Pull request merged**
