### PR TITLE
Added STIE Ekuitas Bandung

### PR DESCRIPTION
**Pull request by igun997**
Added STIE Ekuitas Bandung

### CODE REVIEW

**Comment by philipto** [comment]
@igun997 First stage of verification passed, official domain is [ekuitas.ac.id](https://ekuitas.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@igun997 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by igun997** [comment]
@philipto this university not focus on IT, but accounting course https://ekuitas.ac.id/page/s1akuntasi
But on real life ( after graduate ) we needed to build  apps for accounting.

**Comment by philipto** [comment]
@igun997 Thank you for the clarification. Could you please specify what kind of apps you are to build for accounting after your graduation? Which programming language you will use for it? I appreciate further clarification, because it is not obvious that a person specialized in accounting is expected to build software for the accounting. 

Is it just your choice of your career, or all students who study the same subject as you in your school, are expected to build software after the graduation?

Thank you!

**Comment by igun997** [comment]
Yes it should be a choice after graduation, but you know programming is exotic career for now, so university give us some skill to create a apps, you know like. We have a knowledge of accounting + knowledge to create apps. So that sound good right ? ( sry for my bad english )

**Comment by philipto** [comment]
@igun997 Regrettably, it looks like a very few of the students and graduates of your school actually need software development tools. It means that the domain cannot be added to this repository.

You can, however, apply individually for a free license with documents proving your student status. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.
Thank you for your understanding!

**Pull request closed without merging**
