### PR TITLE
Add greta-formations.txt

### PR DESCRIPTION
**Pull request by greta-formations**

### CODE REVIEW

**Comment by philipto** [comment]
@greta-formations Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by greta-formations** [comment]
Hello,
Sorry, I ask this document to my hierarchy.
I am waiting for the answer.

Thank you for your understanding

**Comment by greta-formations** [comment]
[HPSCAN_20220912145219741_2022-09-12_145307511.pdf](https://github.com/JetBrains/swot/files/9549204/HPSCAN_20220912145219741_2022-09-12_145307511.pdf)

Hello,

sorry for the delay. I have the official request for adding the domain for educational licences.

Thanks you,

Best regards

**Comment by greta-formations** [comment]
Hello,

I am available if you need some informations.

Thanks

Best Regards

**Comment by greta-formations** [comment]
Hello @philipto

I add the requested document. The official website is : https://www.greta-lorraine.fr/reseau/greta-cfa-lorraine-nord/
We offer to our student a lot of IT formation and we would like to integrate the jetbrains tools in our program.
The domain greta-formations.fr is a technical domain used to map our e-mail services.

If you need something else, don't hesitate.
Thanks

Best regards

**Comment by philipto** [comment]
@greta-formations Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
