### PR TITLE
Add it-akademy new domain "it-students"

### PR DESCRIPTION
**Pull request by QuentinBouvier**
Please aknowledge the domain name given to the new it-akademy students after `@it-akademy.fr` discontinuation: `@it-student.fr`

### CODE REVIEW

**Comment by philipto** [comment]
@QuentinBouvier Thank you for the request!
Would you please tell us what is a URL of the page at the official website that confirms this new domain to be given to the students?

Also please notice that https://www.it-akademy.fr/infos/avantages-etudiants says that all the students in this school can get a GitHub Student Developer Pack that includes a free access to all desktop JetBrains tools. In order to use this benefit, one needs to apply for JetBrains free license using **GitHub tab** at https://www.jetbrains.com/shop/eform/students.

**Comment by philipto** [comment]
@QuentinBouvier You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@QuentinBouvier I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by QuentinBouvier** [comment]
@philipto Sorry, I must've disabled my notifications. You're right about the github student pack. I did not think through it :D
I'm not sure there's any page that displays the student's email address domain.

Anyways, I think this PR can remain closed. Have a good one.

**Pull request closed without merging**
