### PR TITLE
Add AMC College

### PR DESCRIPTION
**Pull request by amccollegemy**
AMC College
Domain website : www.amccollege.org

Please review our website and go to Programmes > Certificates Programmes > Certificate in Information Technology, this is our course details.

### CODE REVIEW

**Comment by philipto** [comment]
@amccollegemy Please provide us with the school street address, including city and country. There are many schools with this name worldwide.

**Comment by amccollegemy** [comment]
AMC COLLEGE

Lot 43-44, 1st Floor, Likas Square Commercial Centre, Jalan Istiadat Likas,
88400 Kota Kinabalu, Sabah, Malaysia.

**Comment by amccollegemy** [comment]
> @amccollegemy Please provide us with the school street address, including city and country. There are many schools with this name worldwide.

AMC COLLEGE

Lot 43-44, 1st Floor, Likas Square Commercial Centre, Jalan Istiadat Likas, 88400 Kota Kinabalu, Sabah, Malaysia.

**Comment by philipto** [comment]
@amccollegemy Thank you for the details. Regrettably, I cannot find any link between AMC COLLEGE located at Lot 43-44, 1st Floor, Likas Square Commercial Centre, Jalan Istiadat Likas, 88400 Kota Kinabalu, Sabah, Malaysia, and the domain amccollege.org. This college has absolutely different domain. 

I have to close the request without merging. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting a new request.

**Comment by philipto** [comment]
@amccollegemy Thank you for the clarification that you submitted by email. It is sufficient to merge the pull request. It is now merged.

**Pull request merged**
