### PR TITLE
Create tnfsh

### PR DESCRIPTION
**Pull request by tinf1213**

### CODE REVIEW

**Comment by tinf1213** [comment]
add tnfsh to tn

**Comment by tinf1213** [comment]
add
[gm.txt](https://github.com/JetBrains/swot/files/6898625/gm.txt)
into
tnfsh

**Comment by philipto** [comment]
@tinf1213 lib/domains/tw/edu/tn/tnfsh: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@tinf1213 lib/domains/tw/edu/tn/tnfsh: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by tinf1213** [comment]
I think it is the right path for my school's mail format which is. "@
gm.tnfsh.tn.edu.tw"
Shouldn't it goes to
"lib/domaims/tw/edu/tn/tnfsh"
And create a
"gm.txt"
in it ?
Is that anything goes wrong with my fork?

Philip Torchinsky ***@***.***> 於 2021年7月31日 週六 20:57 寫道：

**Comment by philipto** [comment]
@tinf1213 I updated your request. It is now merged. Please wait for an hour before requesting a free license at https://www.jetbrains.com/shop/eform/students. Thank you.

**Pull request merged**
