### PR TITLE
adding request for bpp

### PR DESCRIPTION
**Pull request by SibghaIlyas**
Add a new university named as BPP University in the list of universities. It is situated in London, UK

### CODE REVIEW

**Comment by philipto** [comment]
@SibghaIlyas Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@SibghaIlyas You might miss my previous comment. Please react.

**Comment by SibghaIlyas** [comment]
https://www.bpp.com/courses/data-and-technology @philipto here you go!!

**Comment by philipto** [comment]
@SibghaIlyas  Thank you for the clarifications. Pull request merged.

**Pull request merged**
