### PR TITLE
Add Igensia file

### PR DESCRIPTION
**Pull request by Fyleek**

### CODE REVIEW

**Comment by philipto** [comment]
@Fyleek The first verification stage is complete: the official domain for  **Campus Igensia Toulouse - Ecole en Informatique IPI** is [www.ipi-ecoles.com](https://www.ipi-ecoles.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.ipi-ecoles.com/espace-entreprises/recruter-a-lipi/

**Comment by Fyleek** [comment]
image


The group to which the school belongs change their name from IGS to IGENSIA

In fact its more about the global domain for all the campus with multiple school (like IPI which is in IT)

**Comment by Fyleek** [comment]
I just asked the school, there is a sub before igensia.com. According to the documentation the igensia.txt file is therefore in the correct format

**Comment by philipto** [comment]
@Fyleek  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
