### PR TITLE
Added Polish Naval Academy in Gdynia, Poland

### PR DESCRIPTION
**Pull request by zacniewski**

### CODE REVIEW

**Comment by zacniewski** [comment]
Added Polish Naval Academy in Gdynia, Poland

**Comment by philipto** [comment]
@zacniewski I am sorry, could you please clarify if the email domain to add is amw.gdynia.pl or PolishNavalAcademy.gdynia.pl? Thank you!

**Comment by zacniewski** [comment]
@philipto Email domain to add is amw.gdynia.pl
Polish Naval Academy is the name of my University.
Best regards :)

**Comment by philipto** [comment]
@zacniewski OK, thak you for the clarification. If the email domain you wish to add is amw.gdynia.pl, the file path in the request has to be lib/domains/pl/gdynia/amw.txt. Please change it. Thank you.

**Comment by zacniewski** [comment]
@philipto Thanks for explanation. I've changed the name as you wished.
Best regards :)

**Comment by philipto** [comment]
@zacniewski Pull request merged. Thank you!

**Pull request merged**
