### PR TITLE
Add Bangkok Patana School

### PR DESCRIPTION
**Pull request by whalev**

### CODE REVIEW

**Comment by whalev** [comment]
Bankgog School School is best school in the Bangkok.

**Comment by whalev** [comment]
please

**Comment by philipto** [comment]
@whalev First stage of verification passed, official domain for **Bangkok Patana School** is [patana.ac.th](https://patana.ac.th) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@whalev Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
