### PR TITLE
add pembangunan jaya university

### PR DESCRIPTION
**Pull request by Febriansz**

### CODE REVIEW

**Comment by philipto** [comment]
@Febriansz First stage of verification passed, official domain is [upj.ac.id](https://upj.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Febriansz** [comment]
Thanks philip, hope that can be verified. Fyi, you can find a list of my university faculties here: https://upj.ac.id/static-page/87/fakultas-teknologi-dan-desain

and of course there are IT related course there 😉

**Comment by philipto** [comment]
@Febriansz Could you please give me a direct link to an IT-related course description? It would be better if a curriculum is listed there.

It can be due to a language barrier, but I did not find any IT-related course description at the page that you have mentioned. Thank you!

**Comment by Febriansz** [comment]
Sorry, i've ask my university to update their content for english language, but they say it need some time to be updated. But, maybe you can understand that condition (I hope). For the study program that IT-related are Information System and Informatics, you can find the curriculum here:

Information System: http://www.sif.upj.ac.id/static-page/44/susunan-mata-kuliah-per-semester
Informatics: http://www.tif.upj.ac.id/static-page/44/susunan-mata-kuliah-per-semester

**Comment by philipto** [comment]
@Febriansz  Thank you for the clarifications. Pull request merged.

**Pull request merged**
