### PR TITLE
Add Instituto Consorcio Clavijero

### PR DESCRIPTION
**Pull request by franx87**
https://www.clavijero.edu.mx/
https://www.clavijero.edu.mx/tsu-licenciatura/ingenieria-en-sistemas-computacionales-tsu-licenciatura/
https://cursos.clavijero.edu.mx/cursos/TIE-2015/modulo3/contenidos/32_correo_electrnico_institucional.html

### CODE REVIEW

**Comment by philipto** [comment]
@franx87 First stage of verification passed, official domain is [clavijero.edu.mx](https://clavijero.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by franx87** [comment]
Thank you Philip, I'm waiting...

**Comment by philipto** [comment]
@franx87 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by franx87** [comment]
Thankyou for your time. "Hasta luego amigo"

**Pull request merged**
