### PR TITLE
Add NTUA Domain

### PR DESCRIPTION
**Pull request by acc621**
Add National Taiwan University of Arts Email Domain

### CODE REVIEW

**Comment by acc621** [comment]
Add National Taiwan University of Arts Email Domain

**Comment by philipto** [comment]
@acc621 First stage of verification passed, official domain is [ntua.edu.tw](https://ntua.edu.tw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by acc621** [comment]
Got it. Thank you again.

**Comment by philipto** [comment]
@acc621 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@acc621 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
