### PR TITLE
Create student

### PR DESCRIPTION
**Pull request by Acyric**

### CODE REVIEW

**Comment by philipto** [comment]
@Acyric Could you please rename lib/domains/us/ca/k12/murrieta/student to lib/domains/us/ca/k12/murrieta/student.txt
Thank you.

**Comment by philipto** [comment]
@Acyric You might miss my previous comment. Please react.

**Comment by Acyric** [comment]
What was the previous comment?

**Comment by philipto** [comment]
@Acyric 
> What was the previous comment?

Could you please rename lib/domains/us/ca/k12/murrieta/student to lib/domains/us/ca/k12/murrieta/student.txt
Thank you.

**Comment by philipto** [comment]
@Acyric Actually, there was an entry for this domain already. I merged the request but deleted the file because it had wrong filename, and the domain is already represented in this repository.

**Pull request merged**
