### PR TITLE
Add SMK Raden Umar Said Kudus to lists

### PR DESCRIPTION
**Pull request by NevanAPH**

### CODE REVIEW

**Comment by philipto** [comment]
@NevanAPH First stage of verification passed, official domain for **SMK Raden Umar Said Kudus** is [smkrus.sch.id](https://smkrus.sch.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by NevanAPH** [comment]
Alright, thanks!

**Comment by NevanAPH** [comment]
But, our student are primarily use email with domain [smkradenumarsaidkudus.sch.id](https://smkradenumarsaidkudus.sch.id). should i also add this to the lists? Thanks.

**Comment by philipto** [comment]
@NevanAPH Yes, please. If the school needs to have two domains added, please add both of them. Thank you.

**Comment by NevanAPH** [comment]
Add another domain, thanks for the information!

**Comment by philipto** [comment]
@NevanAPH Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
