### PR TITLE
Create BKB-Borken

### PR DESCRIPTION
**Pull request by Yolika1**
Website:
https://www.berufskolleg-borken.de/bildungsgange/berufliches-gymnasium/technikgymnasium/

Student Email:
@students.berufskolleg-borken.de

### CODE REVIEW

**Comment by philipto** [comment]
@Yolika1 lib/domains/de/BKB-Borken: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Yolika1** [comment]
@philipto Thank you for your response. I am sorry for the mistake, it should be fixed.

**Comment by philipto** [comment]
@Yolika1 First stage of verification passed, official domain is [berufskolleg-borken.de](https://berufskolleg-borken.de) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Yolika1 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
