### PR TITLE
Create stdmail.txt

### PR DESCRIPTION
**Pull request by a211489**
This is the Private Nan Shan High School located in New Taipei City, Taiwan. The website can be found at https://www.nssh.ntpc.edu.tw/app/home.php.

### CODE REVIEW

**Comment by philipto** [comment]
@a211489 First stage of verification passed, official domain is [nssh.ntpc.edu.tw](https://nssh.ntpc.edu.tw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by a211489** [comment]
Thank you for the update on the first verification.

**Comment by philipto** [comment]
@a211489 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by philipto** [comment]
@a211489 The request has not been merged yesterday, I am sorry about it. Now it merged successfully. Please wait about an hour before requesting the free licenses, to allow the changes to fully propagate through our systems. Thank you!

**Pull request merged**
