### PR TITLE
I request the addition of the educational domain: centrogeo.edu.mx

### PR DESCRIPTION
**Pull request by iscamr**
The official page: https://www.centrogeo.org.mx/ 
The courses taught can be found at the following URL: https://www.centrogeo.org.mx/posgrado 
Within it we handle the course of computational geointelligence, which involves programming with different languages such as .NET, R, Java, PHP, Python among others. 
In the same way you can notice that the page uses the domains centrogeo.edu.mx, for researchers, teachers and students. https://www.centrogeo.org.mx/areas-profile/emartinez

### CODE REVIEW

**Comment by iscamr** [comment]
The contact for the area of administrative technologies is made to the emails: amilcar@centrogeo.edu.mx amoreno@centrogeo.edu.mx mledesma@centrogeo.edu.mx

**Comment by philipto** [comment]
@iscamr First stage of verification passed, official domain is [centrogeo.org.mx](https://centrogeo.org.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.centrogeo.org.mx/quienes-somos/donde-estamos

**Comment by philipto** [comment]
@iscamr Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by iscamr** [comment]
Thank you very much @philipto, sorry when it will be possible to register students

**Comment by iscamr** [comment]
We received the following message when trying to apply to the program: "Your email address does not belong to any university we know of. You can apply using another method (see tabs above) or add your university to the JetBrains list."

**Pull request merged**
