### PR TITLE
Add stfx to list

### PR DESCRIPTION
**Pull request by IshanKBG**

### CODE REVIEW

**Comment by philipto** [comment]
@IshanKBG Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@IshanKBG You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@IshanKBG I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by IshanKBG** [comment]
> @IshanKBG Please provide us with:
> 
> * the school official website URL
> * the school street address, including city and country
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Sorry for the late reply
Here are the required details-
1) https://www.stfxonline.com
2)Address- St. Francis Xavier School, GA-Block, Purbachal, Phase-I, Sector-III, Salt Lake City, Kolkata – 700097
Country- India
3)It does not have a page for that but Computer Science is a part of our school's curriculum for high school students.
My school is affiliated to CISCE board of India which is with my school is affiliated and it provides computer science course to every school affiliated with it. https://www.cisce.org/
One more proof that my school has a CS course is that they have computer labs
Here is the proof.
4)https://www.stfxonline.com/contact/(Check this pqge to get the proof that my school recognizes the domain. Here at bottom they tell to email at info@stfxonline.com thus proving that this domain is recognised)

**Comment by IshanKBG** [comment]
@philipto can you please check the details and reopen the PR.
I am not getting  option to reopen this PR.
Thanks!

**Pull request closed without merging**
