### PR TITLE
Added Wenzao Ursuline University

### PR DESCRIPTION
**Pull request by rollingseaweed**
Added Wenzao Ursuline University

### CODE REVIEW

**Comment by philipto** [comment]
@rollingseaweed First stage of verification passed, official domain is [wzu.edu.tw](https://wzu.edu.tw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@rollingseaweed Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by rollingseaweed** [comment]
> We got Digital Content Application & Management faculty (https://c028.wzu.edu.tw/). It's not fully IT-related since the school's main focus is on linguistics. By the way, I am a self-taught programmer currently building a python crawler case study app. Hope provided information helps.

**Comment by philipto** [comment]
@rollingseaweed Thank you very much for the clarification. Pull request merged.

**Pull request merged**
