### PR TITLE
Create chungil-m

### PR DESCRIPTION
**Pull request by repryty**

### CODE REVIEW

**Comment by repryty** [comment]
https://school.cbe.go.kr/chungil-m

**Comment by philipto** [comment]
@repryty lib/domains/kr/go/cbe/chungil-m: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by repryty** [comment]
@philipto I'm registering it in this format because my school uses a subdomain for email only. The school site address is "school.cbe.go.kr/chungil-m", but for the email address, it's registered as "username@chungil-m.cbe.go.kr".

**Comment by philipto** [comment]
@repryty lib/domains/kr/go/cbe/chungil-m: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Pull request closed without merging**
