### PR TITLE
Added my university

### PR DESCRIPTION
**Pull request by malcozui**
I've added my university to the relevant section so that I can apply for the free educational licence for Jetbrains Ryder

### CODE REVIEW

**Comment by philipto** [comment]
@malcozui Please provide us with:
* the school official website URL
* the school official full name
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@malcozui You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@malcozui I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by malcozui** [comment]
> @malcozui Please provide us with:
> 
> * the school official website URL
> * the school official full name
> * the school street address, including city and country
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

Should I place this information somewhere in the pull request or just attach it as a comment like this?
I also assume I'll have to reopen a pull request with this information attached there and  attaching here would be redundant. Apologies for the late reply.

**Pull request closed without merging**
