### PR TITLE
add University of Macau

### PR DESCRIPTION
**Pull request by bswaterb**

### CODE REVIEW

**Comment by philipto** [comment]
@bswaterb Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by bswaterb** [comment]
https://www.um.edu.mo
It's the school official website URL.

> @bswaterb Please provide us with:
> 
> * the school official website URL, if different from the domain you are submitting
> * an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
> * an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

https://www.um.edu.mo
It's the school official website URL.

**Comment by bswaterb** [comment]
> @bswaterb Please provide us with:
> 
> * the school official website URL, if different from the domain you are submitting
> * an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
> * an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

Ok, thanks.
https://www.um.edu.mo
It's the school official website URL.

**Comment by philipto** [comment]
@bswaterb Thank you! Please let me know where I can see a proof, which confirms that the school recognizes the domain `um.edu.moi` which you are submitting as an official email domain for the students.

If you wish to attach a document, please DO NOT SEND it by email, attach it at github.com as a comment to this request via web interface please.

**Comment by bswaterb** [comment]
> @bswaterb Thank you! Please let me know where I can see a proof, which confirms that the school recognizes the domain `um.edu.moi` which you are submitting as an official email domain for the students.
> 
> If you wish to attach a document, please DO NOT SEND it by email, attach it at github.com as a comment to this request via web interface please.

Actually I don't no how to prove it with official documents, I got edu email from my teacher.
You can visit the official website www.um.edu.mo by um.edu.moi URL. Can it be used as evidence?

**Comment by philipto** [comment]
@bswaterb I am sorry, this cannot be considered as a proof. An address um.edu.moi is not mentioned anywhere at www.um.edu.mo. Therefore, I have a feeling that um.edu.moi is not officially recognized by the university.

**Comment by bswaterb** [comment]
> @bswaterb I am sorry, this cannot be considered as a proof. An address um.edu.moi is not mentioned anywhere at [www.um.edu.mo](http://www.um.edu.mo). Therefore, I have a feeling that um.edu.moi is not officially recognized by the university.

Well, that's a shame, but thanks anyway.

**Pull request closed without merging**
