### PR TITLE
add NDMC domain

### PR DESCRIPTION
**Pull request by AlyionO3O3**
https://wwwndmc.ndmctsgh.edu.tw/uniten/100011/3320

### CODE REVIEW

**Comment by philipto** [comment]
@AlyionO3O3 First stage of verification passed, official domain is [ndmctsgh.edu.tw](https://ndmctsgh.edu.tw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@AlyionO3O3 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by AlyionO3O3** [comment]
Hi @philipto ,
The first link below and the uploaded picture is the description for our graduate student program, where Group C of Epidemiology Group (Health Science Technology Group) in School of Public Health offers bioinformatic-related courses. Although the English website doesn't provide the length of the courses, the Chinese website in the second link does mention "進修碩士 2 年、博士 4 年" meaning 2 years Master program and 4 year Ph. D. program.
https://wwwndmc.ndmctsgh.edu.tw/uniten/100011/3318
https://wwwndmc.ndmctsgh.edu.tw/unit/100011/3106
簡報31

**Comment by philipto** [comment]
@AlyionO3O3  Thank you for the clarifications. Pull request merged.

**Pull request merged**
