### PR TITLE
Add Domain for IFHE(Icfai Foundation For Higher Education)

### PR DESCRIPTION
**Pull request by bhanureddy2105**
1. Official Website https://www.ifheindia.org/

Address:-
The ICFAI Foundation for Higher Education (IFHE), Hyderabad
IFHE Campus
Donthanapally, Shankarapalli Road
Hyderabad - 501203, Telangana, India.

3. https://icfaitech.admissions.ifheindia.org/

image

### CODE REVIEW

**Comment by philipto** [comment]
@bhanureddy2105 lib/domains/org/ifheindia: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@bhanureddy2105 lib/domains/org/ifheindia: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by bhanureddy2105** [comment]
Thank You for making change instead of me. Can You merge this pull request

**Comment by philipto** [comment]
@bhanureddy2105 Pull request merged. Thank you!

**Comment by bhanureddy2105** [comment]
@philipto Usually how much time does it take for this domain to be reflected in the live website as I am not able to create an account with my email id

**Pull request merged**
