### PR TITLE
Create sit.txt

### PR DESCRIPTION
**Pull request by nateshmbhat**
Have added our engineering college .

Location : India 
State : Karnataka

### CODE REVIEW

**Comment by nateshmbhat** [comment]
College website is :- [Siddaganga institute of Technology](https://sit.ac.in)
City : Tumkur

**Comment by philipto** [comment]
@nateshmbhat Pull request merged. Thank you!

**Comment by nateshmbhat** [comment]
Our college hasn't given Gmails to students with the above mentioned domain name. How can I register then?

**Comment by philipto** [comment]
@nateshmbhat Does the college give the students email in another domain? If yes, you need to register it here. If not, you need to request your free license for JetBrains tools at https://jetbrains.com/student with your ISIC card or with a photo ID which confirms that you are the student.

**Comment by nateshmbhat** [comment]
No the college doesn't provide us with any other email domain as such. I
have sent the request in the jetbrains site with a pic of the ID card. Let
me know if u need more documents to verify. I have college certificates,
github repositories, passport to verify my age etc.

**Comment by nateshmbhat** [comment]
Youth4workHi ,Natesh M Bhat, your contact & who has this profileSuggests you to try a quick, 5 min, Online Skill test to know your own skillshttps://www.youth4work.com/onlinetalenttestIt’s a fun test that helps you know where you stand for your skills across the globe. It also helps you get professional opportunities.Regards,Youth4workUnsubscribe

**Pull request merged**
