### PR TITLE
Create klaraopp.txt

### PR DESCRIPTION
**Pull request by wolf-w**
Adding student account domain

### CODE REVIEW

**Comment by philipto** [comment]
@wolf-w Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@wolf-w This request remains unanswered for a while. I have to close it without merging. Please reopen if you have an update regarding the issue mentioned above. Thank you for the understanding!

**Comment by wolf-w** [comment]
@philipto here are the requested points:
It's a german professional school including training as a [specialist in application development (3 years)](http://www.klara-oppenheimer-schule.de/node/22)

* official website: http://www.klara-oppenheimer-schule.de/
* IT courses (including the one above) http://www.klara-oppenheimer-schule.de/node/23
* proof student domain: [klaroppenheimerschule-onmicrosoft-domain.pdf](https://github.com/JetBrains/swot/files/1405964/klaroppenheimerschule-onmicrosoft-domain.pdf)

**Comment by philipto** [comment]
@wolf-w Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Pull request merged**
