### PR TITLE
add uit University

### PR DESCRIPTION
**Pull request by ahmed-kw-commerce**

### CODE REVIEW

**Comment by philipto** [comment]
@ahmed-kw-commerce Could you please confirm that student emails of this university end with @uit.university? If not, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. Thank you for the understanding!

**Comment by philipto** [comment]
@ahmed-kw-commerce You might miss my previous comment. Please react.

**Comment by ahmed-kw-commerce** [comment]
@philioto 

I confirm that the student emails of the UIT university end with @uit.university.

I‘m a student at this university.

**Comment by philipto** [comment]
@ahmed-kw-commerce Pull request merged. Thank you!

**Pull request merged**
