### PR TITLE
Add 1lobochnia.onmicrosoft.com emails to licence

### PR DESCRIPTION
**Pull request by maxszymczyk**
School domain is https://1lo.bochnia.pl/ but email domain is 1lobochnia.onmicrosoft.com

### CODE REVIEW

**Comment by bozgi** [comment]
@philipto there is a problem with this as this school gives emails in diffrent domains to students. I found a post on this schools official facebook that uses email with this domain: https://www.facebook.com/1lobochnia/posts/pfbid0k6d1CzfoMSumojpnaninf1vsM1kpGeVFYwCMeDtLMSSPfKKbVtGNUN7drZRnhTZ1l

To prove that this facebook page is owned by this school you can go to https://1lo.bochnia.pl/ and on the bottom of the page there is a redirection to this exact facebook page.

**Comment by bozgi** [comment]
@philipto There is currently a holiday break. I talked with him and he will ask one of the teachers to post on schools website how emails are assigned. Is it possible to put this pull request on hold for around a week?

**Comment by philipto** [comment]
@maxszymczyk Yes, certainly. In the meantime feel free to apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Comment by philipto** [comment]
@maxszymczyk You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@maxszymczyk I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
