### PR TITLE
Add Municipal educational institution secondary school No. 6 of the Tutaevsky municipal district

### PR DESCRIPTION
**Pull request by Pacmard**
web: https://sh6-tmr.edu.yar.ru/
e-mail: school-6@bk.ru

### CODE REVIEW

**Comment by philipto** [comment]
@Pacmard I am sorry, your request looks very odd. You request to add a domain nb.amalnet.k12.il represented by the file lib/domains/il/k12/amalnet/nb.txt. This domain belongs to a school in Israel. In the comment and the title of your request you refer to a school in Yaroslavl, Russia. You mention, however, that your email address is on public mail service in Russia, not related to any of the schools.

If you are unsure how to make a pull request, or how to get a free educational license for a student, please send an email to community-support@jetbrains.com and ask for help. 

As for now, I have to close the request without merging. Thank you.

**Comment by Pacmard** [comment]
Yes, I’ve screwed up a little with the creation of PR, but unfortunately, my school uses a public service of email

**Comment by philipto** [comment]
@Pacmard In this case we can not add the public service to this repository anyway. Please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students). It can be a student card, or a notice ("Справка") which the school administration gives to you to prove that you are a student of the school. The document in Russian is sufficient.

**Comment by Pacmard** [comment]
Thank you with helping!

**Pull request closed without merging**
