### PR TITLE
Quest International College

### PR DESCRIPTION
**Pull request by vashukarn**

### CODE REVIEW

**Comment by philipto** [comment]
@vashukarn First stage of verification passed, official domain is [quest.edu.np](https://quest.edu.np) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by vashukarn** [comment]
Hey JetBrains Team. Can you check it? How long do I have to wait?

**Comment by philipto** [comment]
@vashukarn Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by vashukarn** [comment]
https://quest.edu.np/

**Comment by philipto** [comment]
@vashukarn I am sorry, I am not able to find any course at the website even remotely related to software development. I have to close the request because the school does not qualify for being added to this repository.

**Pull request closed without merging**
