### PR TITLE
Create 3betavane8

### PR DESCRIPTION
**Pull request by poyynt**

### CODE REVIEW

**Comment by poyynt** [comment]
Hello there?

**Comment by philipto** [comment]
@poyynt 
Could you please confirm that your school teaches some students who are over 13 of age? Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age.

If you have students who are over 13 of age, please rename lib/domains/ir/3betavane8 to lib/domains/ir/3betavane8.txt to reflect this repository rules. Thank you!

**Comment by philipto** [comment]
@poyynt I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Comment by poyynt** [comment]
Yes, I am 14.

**Pull request closed without merging**
