### PR TITLE
Create powiat.txt

### PR DESCRIPTION
**Pull request by Myster987**
II Liceum Ogólnokształcące im. Mikołaja Kopernika
website: http://kopernik.mielec.pl/
facebook: https://www.facebook.com/IILOwMielcu/

### CODE REVIEW

**Comment by philipto** [comment]
@Myster987 First stage of verification passed, official domain is [kopernik.mielec.pl](https://kopernik.mielec.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: http://kopernik.mielec.pl/sfinansowe

**Comment by philipto** [comment]
@Myster987 Thank you for the request. Please tell us who uses the email domain **powiat.mielec.pl**. It looks like there are not only school students and teachers using it. Please clarify.

**Comment by Myster987** [comment]
> @Myster987 Thank you for the request. Please tell us who uses the email domain **powiat.mielec.pl**. It looks like there are not only school students and teachers using it. Please clarify.

@philipto powiat.mielec.pl is the domain of the entire area in which the school is located, a powiat in Poland is something like a county in the USA. The school has a separate domain only for students and teachers it's kopernik.mielec.pl, and powiat.mielec.pl is the school's administrative domain.

**Comment by philipto** [comment]
@Myster987 Thank you for the clarification! According to it, your request contains the file lib/domains/pl/mielec/powiat.txt representing the domain powiat.mielec.pl. It does not belong exclusively to the students and teachers of the school, thus we cannot add it to the repository. However, if students and teachers have their email addresses ending with @kopernik.mielec.pl, I can modify your request to include the domain `kopernik.mielec.pl` to the repository.

Would you like me to add `kopernik.mielec.pl` or not? Thank you!

**Comment by Myster987** [comment]
@philipto Yes, I would like to add kopernik.mielec.pl to the repository. 

Thank you for your time and best regards

**Comment by philipto** [comment]
@Myster987  Thank you for the clarifications. Pull request modified and merged.

**Comment by Myster987** [comment]
@philipto is it possible to change domain from kopernik.mielec.pl to kopernikmielec.onmicrosoft.com because most students use this domain and Microsoft teams and it would be easier to include your tools right away. Please let me know if this is possible and thank you for your time.

**Pull request merged**
