### PR TITLE
Request addition of school.

### PR DESCRIPTION
**Pull request by actorpus**
At lib\domains\uk\sch\oxon\warriner.txt

### CODE REVIEW

**Comment by philipto** [comment]
@actorpus First stage of verification passed, official domain is [thewarrinerschool.co.uk](https://thewarrinerschool.co.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.thewarrinerschool.co.uk/contactus

**Comment by actorpus** [comment]
Good morning Phillip,Thanks for your update, do you need any form of verification from the school?Many thanks, Alex.On 1 Apr 2023, at 4:33 am, Philip Torchinsky ***@***.***> wrote:﻿
@actorpus First stage of verification passed, official domain is thewarrinerschool.co.uk as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.thewarrinerschool.co.uk/contactus

**Comment by actorpus** [comment]
@philipto thanks for the update,
Do you need any extra information from the school?

**Comment by philipto** [comment]
@actorpus Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
