### PR TITLE
Add UPAM university.

### PR DESCRIPTION
**Pull request by alexventuraio**

### CODE REVIEW

**Comment by philipto** [comment]
@alexventuraio First stage of verification passed, official domain is [upamozoc.edu.mx](https://upamozoc.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: http://descargas.upamozoc.edu.mx/Documentos_pagina/SERV_ESC/upam.pdf

**Comment by alexventuraio** [comment]
> [upamozoc.edu.mx](https://upamozoc.edu.mx)



> First stage of verification passed, official domain is [upamozoc.edu.mx](https://upamozoc.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: http://descargas.upamozoc.edu.mx/Documentos_pagina/SERV_ESC/upam.pdf

@philipto thanks for following up on this, that's right, so do you think I should include [upamozoc.edu.mx](https://upamozoc.edu.mx/) in this repo?

**Comment by philipto** [comment]
@alexventuraio 
> do you think I should include [upamozoc.edu.mx](https://upamozoc.edu.mx/) in this repo?

No, thank you. 
Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by alexventuraio** [comment]
> @alexventuraio
> 
> > do you think I should include [upamozoc.edu.mx](https://upamozoc.edu.mx/) in this repo?
> 
> No, thank you. Thank you for your patience while waiting for a review and processing your request. Pull request merged.

Sweet, when do you think it should be ready to apply for students and teachers license? @philipto

**Pull request merged**
