### PR TITLE
Adding a new domain from CETIS 15

### PR DESCRIPTION
**Pull request by emmc316**
CETIS 15 has new domain uemstis and dgeti

### CODE REVIEW

**Comment by philipto** [comment]
@emmc316 First stage of verification passed, official domain is [m.facebook.com](https://m.facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/dgetijalisco/about/

**Comment by philipto** [comment]
@emmc316 Please answer the question that I asked about the similar domain in #16202, and provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@emmc316 You might miss my previous comment. Please react.

**Comment by emmc316** [comment]
Yes, Sorry. Apologies me, what a shame!
I send in this moment the WHOIS that shows that the domain is registered 
image

The another points I'm working to get them and send you. I need 2 day more to get the full information. 

I'm in the unviersity now, I don't study in that school now, so I'm talking directly with the school to get that information. 

And sorry for answer in this moment

**Comment by philipto** [comment]
@emmc316 First stage of verification passed, official domain is [m.facebook.com](https://m.facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/dgetijalisco/about/

**Comment by philipto** [comment]
@emmc316 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
