### PR TITLE
Create sempreceub.txt

### PR DESCRIPTION
**Pull request by XchgBxBx**
Official website: https://www.uniceub.br/
Computer Science page: https://www.uniceub.br/cursos/tecnologia/graduacao/ciencia-da-computacao/disciplinas-e-professores.aspx#c

### CODE REVIEW

**Comment by KilnOfTheSecondFlame** [comment]
Hey XchgBxBx, your TLD is wrong. Move your file to /lib/domains/br to be in the correct directory

**Comment by XchgBxBx** [comment]
@KilnOfTheSecondFlame, it's our new email domain (person@sempreceub.com), I'll attach an image about.

**Comment by XchgBxBx** [comment]
Couldn't find a public page with this information, but I think this would be enough.
image 5

**Comment by philipto** [comment]
@KilnOfTheSecondFlame Thank you for your comments and suggestions!
@XchgBxBx Thank you for the clarification.
Pull request merged. Thank you!

**Pull request merged**
