### PR TITLE
add The Open University of Japan

### PR DESCRIPTION
**Pull request by arakim**
Students of OUJ have email @campus.ouj.ac.jp.

### CODE REVIEW

**Comment by philipto** [comment]
@arakim Do I understand right that this university is an online university, and the students take the classes not in the classrooms of the university?

**Comment by arakim** [comment]
@philipto The students need to earn 124+ credits for graduate; 94+ credits by TV/radio/Internet broadcast classes, 20+ credits by schooling (classes in the classrooms) or online classes, and 10+ credits by broadcast/schooling/online classes.

http://www.ouj.ac.jp/eng/faculty/
...English page seems to have little old information. 20+ credits by schooling "or online classes" since 2016.
http://www.ouj.ac.jp/hp/purpose/gakusi.html (correct information written in Japanese)

**Comment by philipto** [comment]
@arakim The problem is in JetBrains Student Program eligibility requirements. JetBrains does not grant free licenses to students of online universities, and I cannot add your university email domain to this repository. I leave this request open for now, and will be back to you with the final decision in about a week.

In the meantime, I recommend to request free licenses at https://jetbrains.com/student using an official document (if your university provides student IDs to the students), use Community Editions of JetBrains tools, or use the tools trial versions (valid for 30 days).

Thank you for the understanding.

**Comment by arakim** [comment]
@philipto I apologize you, I misunderstood the meaning of your question. OUJ has physically existing locations, the students attend classes in the classrooms on some courses, so I think it is not fully online university.
I respect your judgment and thank you for advice.

**Comment by philipto** [comment]
@arakim We carefully reviewed your request and decided that your university is eligible for being added to this repository. Pull request merged. Thank you!

**Pull request merged**
