### PR TITLE
create stmik-time.txt

### PR DESCRIPTION
**Pull request by octarapribadi**
Indonesia education data verification: https://pddikti.kemdikbud.go.id/data_pt/Q0IyRDA0MTYtODEwNS00MDA2LUFGRjAtNDI0RkM3MEI5RDVG

Institution it support : it@stmik-time.ac.id

Institution website : www.stmik-time.ac.id

### CODE REVIEW

**Comment by philipto** [comment]
@octarapribadi First stage of verification passed, official domain is [stmik-time.ac.id](https://stmik-time.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@octarapribadi Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by octarapribadi** [comment]
My apology, our web is under new construction by IT team. do we have another option? something like brochure, perhaps?

**Comment by philipto** [comment]
@octarapribadi Yes, a link to a brochure or a photo of the brochure page that outlines an IT-related course also works.
Please upload the photo as a comment here via your browser, DO NOT send it as an email attachment.

**Comment by philipto** [comment]
@octarapribadi You might miss my previous comment. Please react.

**Comment by octarapribadi** [comment]
da622494-179e-4a37-b8bf-bfba0ccfa21c

**Comment by philipto** [comment]
@octarapribadi  Thank you for the clarifications. Pull request merged.

**Pull request merged**
