### PR TITLE
Add Liberton High School Edinburgh

### PR DESCRIPTION
**Pull request by gcsepregi**

### CODE REVIEW

**Comment by gcsepregi** [comment]
https://libertonhighschool.org

**Comment by philipto** [comment]
@gcsepregi First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/boroughmuirSchoolFPA/about/

**Comment by philipto** [comment]
@gcsepregi Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by gcsepregi** [comment]
Hi @philipto! I've been trying to find a document but this is the closest I could get. This is a screenshot from inside O365, showing documents belonging to Liberton High School and in the top right corner the user box showing the domain without the sensitive part.

The domain directly belongs to the Edinburgh Council, and is used by all high schools since the pandemic as the central o365 domain.

proof_of_domain

**Comment by philipto** [comment]
@gcsepregi Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
