### PR TITLE
Add bs-tnk1.c.sn.schule.de

### PR DESCRIPTION
**Pull request by Smove**
Homepage is http://industrieschule.de/

The domain bs-tnk1.c.sn.schule.de is for mails.
A student mail look like this:
sXXXXX@bs-tnk1.c.sn.schule.de

The mail is a part of a big network of schools, so that there have to be different mail & homepage urls

### CODE REVIEW

**Comment by zweizwei** [comment]
Could you please somehow confirm, that the domain is used by the school? (by providing relevant page or document).Thanks!

**Comment by Smove** [comment]
I've got asked my teacher via mail for any document or something other. I would provide a document or a page if i got an answer from him.

I don't know if it's enough as a confirmation, but on http://ies.c.sn.schule.de/ you got an entry "BSZ Technik 1 " at "Zentrale". This is the short version of "Berufliches Schulzentrum für Technik 1".

When i got any other confirmation, i will send it to you :)

**Comment by Smove** [comment]
Some other documents/pages:
http://www.industrieschule.de/page/07_Organisatorisches/Blockplaene/blockplan2010.pdf
In the bottom right corner you can find some e-mails with "l<number>@bs-tnk1.c.sn.schule.de". These are for teachers(l = Lehrer(german)). s is for students(Schüler). 

Some sections of our school got a tutorial how to login into our school server. This is available here:
http://www.industrieschule.de/page/09_Fachbereichsinfos/Fahrzeugtechnik/intranetzugang.pdf

After the login tutorial, there is a screen with the main menu. Next to this there is a text "Die E-Mail-Adresse wäre:". That is the syntax for the e-mail from user s70164.

**Comment by zweizwei** [comment]
Thank you and sorry for the delay - i'm adding the domain

**Comment by Smove** [comment]
Thank you very much :) 
Is there any way to help with the lot of work to make these steps processing faster for others?

**Pull request merged**
