### PR TITLE
Add ITET Leonardo da Vinci (Milazzo)

### PR DESCRIPTION
**Pull request by kinderp**
- Official website: https://www.davincimilazzo.edu.it/
- Long term IT course: https://www.davincimilazzo.edu.it/index.php/2014-04-24-10-22-02/settore-tecnologico

### CODE REVIEW

**Comment by philipto** [comment]
@kinderp First stage of verification passed, official domain is [davincimilazzo.edu.it](https://davincimilazzo.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by nataershova** [comment]
@kinderp Hi, 

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.  You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@kinderp Would you please also provide us with  an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course? Thank you!

**Comment by philipto** [comment]
@kinderp You might miss my previous comment. Please react.

**Comment by kinderp** [comment]
> @kinderp Hi,
> 
> Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.  You can provide us with any of the following:
> 
> * A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain

@nataershova 

You can email me at `antonio dot caristia at davincimilazzo dot edu dot it` and i will reply to you to verify that i'm using this email domain as teacher.

I can forward you instructions that I received in my inbox once it was enabled but I need an email address to contact you.

> * An URL of a page at the official school website that says that students use this email domain
> * A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
> * A WHOIS data that link the email domain to the school somehow

email domain `davincimilazzo.edu.it` is the same used to host official school website and if you whois it you'll get "Istituto Tecnico L. Da Vinci Economico Tecnologico" as value under Registrant Organization field.


> * A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
> * Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by kinderp** [comment]
> @kinderp Would you please also provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course? Thank you!

@philipto sorry, i missed that.

As you can see [in this page](https://www.davincimilazzo.edu.it/index.php/2014-04-24-10-22-02/settore-tecnologico) "Informatica" (Computer Science in English) in the Technology Sector has been taught in the last 3 years (six hours at week) at III, IV  and V year.

CS

**Comment by nataershova** [comment]
hi @kinderp Pull request merged. Thank you!

**Pull request merged**
