### PR TITLE
Add unifacisa.edu.br and cesed.br

### PR DESCRIPTION
**Pull request by felladrin**
Add email domains for students of **Faculdade de Ciências Sociais Aplicadas** (Facisa - <http://unifacisa.edu.br>) which is part of **Centro de Ensino Superior e Desenvolvimento** (CESED - <http://www.cesed.br>).

Facisa has two IT-related long-term courses which would benefit from JetBrains products:
- Information Systems ("Sistemas de Informação"): <http://www.cesed.br/portal/?page_id=21423>
- Digital Games ("Jogos Digitais"): <http://www.cesed.br/portal/?page_id=21359>

Through WHOIS information you can see the two domains belongs to the same intuition.

### unifacisa.edu.br

```
% Copyright (c) Nic.br
%  The use of the data below is only permitted as described in
%  full by the terms of use at http://registro.br/termo/en.html ,
%  being prohibited its distribution, commercialization or
%  reproduction, in particular, to use it for advertising or
%  any similar purpose.
%  2016-06-11 14:46:10 (BRT -03:00)

domain:      unifacisa.edu.br
owner:       Centro de Ensino Superior e Desenvolvimento
ownerid:     002.108.023/0001-40
responsible: Gisele Gadelha
country:     BR
owner-c:     HEPRI6
admin-c:     HEPRI6
tech-c:      HEPRI6
billing-c:   HEPRI6
nserver:     ns1.cesed.br  
nsstat:      20160610 AA
nslastaa:    20160610
nserver:     ns2.cesed.br  
nsstat:      20160610 AA
nslastaa:    20160610
saci:        yes
created:     20150911 #14615941
changed:     20160105
status:      published

nic-hdl-br:  HEPRI6
person:      Henrique de Pontes Ribeiro
e-mail:      henrique@itline.com.br
created:     20110621
changed:     20120731

% Security and mail abuse issues should also be addressed to
% cert.br, http://www.cert.br/ , respectivelly to cert@cert.br
% and mail-abuse@cert.br
%
% whois.registro.br accepts only direct match queries. Types
% of queries are: domain (.br), registrant (tax ID), ticket,
% provider, contact handle (ID), CIDR block, IP and ASN.
```

### cesed.br

```
% Copyright (c) Nic.br
%  The use of the data below is only permitted as described in
%  full by the terms of use at http://registro.br/termo/en.html ,
%  being prohibited its distribution, commercialization or
%  reproduction, in particular, to use it for advertising or
%  any similar purpose.
%  2016-06-11 14:48:18 (BRT -03:00)

domain:      cesed.br
owner:       Centro de Ensino Superior e Desenvolvimento
ownerid:     002.108.023/0001-40
responsible: Gisele Gadelha
country:     BR
owner-c:     HEPRI6
admin-c:     JMNSE
tech-c:      HEPRI6
billing-c:   JMNSE
nserver:     ns1.itline.com.br  
nsstat:      20160608 AA
nslastaa:    20160608
nserver:     ns2.itline.com.br  
nsstat:      20160608 AA
nslastaa:    20160608
created:     19990720 #175913
changed:     20160105
status:      published

nic-hdl-br:  HEPRI6
person:      Henrique de Pontes Ribeiro
e-mail:      henrique@itline.com.br
created:     20110621
changed:     20120731

nic-hdl-br:  JMNSE
person:      JOSE MATHIAS NETTO SEGUNDO
e-mail:      netto@tvitarare.com.br
created:     20101201
changed:     20121221

% Security and mail abuse issues should also be addressed to
% cert.br, http://www.cert.br/ , respectivelly to cert@cert.br
% and mail-abuse@cert.br
%
% whois.registro.br accepts only direct match queries. Types
% of queries are: domain (.br), registrant (tax ID), ticket,
% provider, contact handle (ID), CIDR block, IP and ASN.
```

### CODE REVIEW

**Comment by philipto** [comment]
@felladrin Pull request merged. Thank you!

**Comment by daniel-abella** [comment]
:+1

**Comment by mateusrodrigueslti** [comment]
:+1:

**Comment by mateusrodrigueslti** [comment]
:+1

**Comment by rayanasouza** [comment]
:+1

**Comment by JoelOliveira15** [comment]
:+1

**Comment by guimaraesneto17** [comment]
+1

**Comment by guimaraesneto17** [comment]
:+1:

**Comment by marcioferreirap** [comment]
:+1:

**Comment by ClaudiaMelocg** [comment]
:+1:

**Pull request merged**
