### PR TITLE
Institute URLs

### PR DESCRIPTION
**Pull request by Abbas212**
https://www.iipsindia.ac.in/

https://www.iipsindia.ac.in/msc-biostat

### CODE REVIEW

**Comment by philipto** [comment]
@Abbas212 Please provide us with a proof, which shows that the school recognizes the domain `iipsindia.in` that you are submitting as an official email domain for the students.

**Comment by Abbas212** [comment]
Hi.
The official domain is "iips.ac.in".
What proof is required for the same?

**Comment by philipto** [comment]
@Abbas212 You may have an instruction given to you at the enrollment time, which tells you to use an address <username>@iipsindia.in. Please upload a copy of this instruction as a comment to this discussion on GitHub.

**Comment by philipto** [comment]
@Abbas212 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@Abbas212 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
