### PR TITLE
GSO-BK-Cologne

### PR DESCRIPTION
**Pull request by BadWinniePooh**
Added the Georg-Simon-Ohm Berufskolleg in Cologne.

### CODE REVIEW

**Comment by BadWinniePooh** [comment]
Website: https://www.gso-koeln.de/
Long-term IT related courses: https://www.gso-koeln.de/index.php/bildungsgaenge/berufsschule/fachinformatiker

**Comment by philipto** [comment]
@BadWinniePooh Please clarify what is a pattern of student email addresses in this school: username@gso-koeln.de or  username@schule.koeln. If the latter, please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by BadWinniePooh** [comment]
@philipto Hi, recently the school changed from gso-koeln.de to schule.koeln, but not all addresses are changed jet. The whole domain now works with office 365 and the portal to enter our license is: https://portal.schule.koeln

We use for everything different services, so I am sorry that I can't really supply a real prrof. Even our Website is so outdated, that there is the news that we "will be" switching the mailingsystem at the years transitional of 2013 to 2014...

In the Attachment are two files, one Screenshot of our Office365 A1 Plus for students and one for validation, that the address it is registered to is username@schule.koeln. I hope they will help.
Have a nice day.

> 
> Subscription
> Email

**Comment by philipto** [comment]
@BadWinniePooh Thank you for the clarification. Pull request merged.

**Pull request merged**
