### PR TITLE
Add idm

### PR DESCRIPTION
**Pull request by jstnceronio**
Corrected domain

### CODE REVIEW

**Comment by philipto** [comment]
@jstnceronio First stage of verification passed, official domain is [idm.ch](https://idm.ch) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@jstnceronio Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by jstnceronio** [comment]
Under  [this url](https://www.idm.ch/kurse/) one can find an overview of open courses. Please navigate toward the bottom of the page where you'll be able to find the technical vocational baccalaureate or "Berufsmaturität" which can be completed full- or part-time (4 years).
@philipto Thank you very much.

**Comment by philipto** [comment]
@jstnceronio Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
