### PR TITLE
Add school2120.txt

### PR DESCRIPTION
**Pull request by KMusorin**
Hi. Please add this Moscow located school to your base. The official email 2120@edu.mos.ru 
Also here is the extended information - https://sch2120tn.mskobr.ru/info_edu/basics/
Thx

### CODE REVIEW

**Comment by philipto** [comment]
@KMusorin Please provide us with a proof which shows that the school recognizes the domain which you are submitting as an official email domain for the students. Thank you.

**Comment by KMusorin** [comment]
@philipto The official domain of the school sch2120tn.mskobr.ru, but the email differs from the latter. This information was taken from the official school's web site https://sch2120tn.mskobr.ru/info_edu/basics/.  Please follow the link and check the information provided. You can find the details at the bottom of the site. Thanks

**Comment by philipto** [comment]
@KMusorin I am sorry, it seems to me that there is some misunderstanding. Your request contains a file `lib/domains/ru/school2120.txt` which, according to this repository rules, represents an email domain `school2120.ru`. It means that teachers and students at your school are assigned with an email address which has a pattern `username@school2120.ru`. 

If teachers and students at your school do not have their personal email addresses, which are assigned to them by the school in a form of `username@school2120.ru`, they do not need to apply for free educational licenses at https://www.jetbrains.com/shop/eform/students#official with their email addresses. Instead, they can apply there with their official documents, which prove that they are the students of the school.

If they don't have official documents, please send an email to community-support@jetbrains.com to discuss which kind of free licensing is appropriate for your school's students and teachers.

Please let me know how you wish me to proceed: close this request, or modify it somehow? Thank you.

**Comment by KMusorin** [comment]
Unfortunately, they haven't emails at this domain. Which official documents can be applied as an evidence by the pupils?

**Comment by philipto** [comment]
@KMusorin Thank you for the clarification! Thus, I can manually add the domain sch2120.yaconnect.com to this repository, if the school teachers wish to get a free educational subscription JetBrains tools. Please let me know if it is needed.

As for your son, is it enough for him to use IntelliJ IDEA Community (which supports Java, Scala and Kotlin) and PyCharm Community Edition (which supports Python) for now? Depending on which tasks he wishes to solve, these versions may be a good start for him, and they all are absolutely free for everybody, for any purpose.

As for official documents, a student ID ("ученический билет") or a note from the school administration ("справка") - with a signature and seal - which says that he is a student of this school is enough. If you decide to request a license with official document, please don't submit anything to GitHub, just apply for free license at https://www.jetbrains.com/shop/eform/students#official (using the tab OFFICIAL DOCUMENT there).

Shall you have any further questions, feel free to email us at community-support@jetbrains.com. Thank you!

**Comment by philipto** [comment]
@KMusorin I am sorry, this request remains unanswered for a while. I have to close it without merging. Please send an email to community-support@jetbrains.com if you have any comments, questions, feedback, or suggestions regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
