### PR TITLE
IRUP

### PR DESCRIPTION
**Pull request by JavaImplements**

### CODE REVIEW

**Comment by philipto** [comment]
@JavaImplements Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@JavaImplements You might miss my previous comment. Please react.

**Comment by JavaImplements** [comment]
Hello !

site : https://www.irup.com/
Adresse : Irup: Regional Institute University Polytechnique Krumpien Saint etienne 42000 France 
BTSS22PBALEY@eleve-irup.com

**Comment by JavaImplements** [comment]
@philipto en attente de votre réponse cordialement

**Comment by philipto** [comment]
@JavaImplements Regrettably, there are no pages at the website of [irup.com/](https://www.irup.com/) mentioning [@eleve-irup.com](mailto:BTSS22PBALEY@eleve-irup.com) email domain as officially recognized one.

Also, the page https://www.irup.com/etudiants/par-filieres-d-expertise/informatique/ does not have a curriculum description, thus I cannot ensure that the school actually offers any courses where using JetBrains tools can be useful.

Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

Also, please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. It can be any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@JavaImplements I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
