### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by whisper-a**
I don't know that such a famous academic research institution as the Chinese Academy of Sciences has not been added to JetBrains in advance, please approve it, thank you very much!

### CODE REVIEW

**Comment by philipto** [comment]
@whisper-a First stage of verification passed, official domain is [iee.cas.cn](https://iee.cas.cn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: http://english.iee.cas.cn/intro/

**Comment by whisper-a** [comment]
@philipto thank you very much, I'll wait for the good news

**Comment by philipto** [comment]
@whisper-a Thank you for your patience while waiting for a review and processing your request. Pull request merged.

Please notice that the educational license is for educational use only. If the employees of the Institute, who are neither students nor teachers, need the license, please ask them to send a message to [sales@jetbrains.com](mailto:sales@jetbrains.com) to get an academic discount for paid license.

**Comment by whisper-a** [comment]
I get it, thank you, my bro.

**Pull request merged**
