### PR TITLE
Create ccastudents.txt

### PR DESCRIPTION
**Pull request by Maximusyt1**
Added a new school

### CODE REVIEW

**Comment by philipto** [comment]
@Maximusyt1 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Maximusyt1 You might miss my previous comment. Please react.

**Comment by Maximusyt1** [comment]
Hey. I will get to this in the morning as it as midnight now.

**Comment by Maximusyt1** [comment]
the school official website URL: https://ccaeducate.me/
the school street address, including city and country: 1 Innovation Way, Harrisburg, PA 17110, USA
an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: I can't find out how to link the course, but if you go to https://ccaeducate.me/course-catalog/2023-24/ and filter with the name "Computer" then it will show.
a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students: The image below shows me logged into my CCA outlook account (I crossed out my name in white, so thats why its blank in some places):
image

**Comment by philipto** [comment]
@Maximusyt1 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
