### PR TITLE
.txt file, to add unijuazeiro university

### PR DESCRIPTION
**Pull request by gabriell-silva**

### CODE REVIEW

**Comment by philipto** [comment]
@gabriell-silva Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by gabriell-silva** [comment]
- o URL do site oficial da escola: https://unijuazeiro.edu.br/
   - o endereço da escola, incluindo cidade e país: *Rua São Francisco,
   1224 - São Miguel, Juazeiro do Norte - CE, 63010-475, Brasil*
   - um URL de uma página no site oficial onde a escola oferece um curso de
   longo prazo (> 1 ano) relacionado a TI:
   https://unijuazeiro.edu.br/graduacoes/sistemas-de-informacao/
   - uma prova, que mostra que a escola reconhece o domínio que você está
   enviando como um domínio de e-mail oficial para os alunos. : *Segue
   anexo da declaração no e-mail.*
   -


Em qui., 19 de jan. de 2023 às 04:48, Philip Torchinsky <
***@***.***> escreveu:

**Comment by philipto** [comment]
@gabriell-silva  Thank you for the clarifications. Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. If you attach a screenshot or a file as a proof, please do it in your browser. DO NOT send the attachment by email, GitHub strips it out.

You can provide us with any of the following as the proof:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by gabriell-silva** [comment]
Bom dia,

Segue link do WHOIS, com informações sobre o domínio sempreunijuazeiro.:
https://registro.br/tecnologia/ferramentas/whois/?search=sempreunijuazeiro.com.br
Link com declaração do curso existente na universidade.:
https://drive.google.com/file/d/1K8jAyfdR9Iwi6pqi4BSQ-5ydmZR3znyN/view?usp=share_link
Link do portal, que solicita o e-mail institucional sempreunijuazeiro.:
https://fs-educ.sempreser.com.br/adfs/ls/

Desde já agradeço a atenção

Em ter., 24 de jan. de 2023 às 05:43, Philip Torchinsky <
***@***.***> escreveu:

**Comment by philipto** [comment]
@gabriell-silva Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
