### PR TITLE
Add Kings College Schools

### PR DESCRIPTION
**Pull request by FelixKLG**

### CODE REVIEW

**Comment by NattyNatt** [comment]
[alumnos.txt](https://github.com/JetBrains/swot/files/6761298/alumnos.txt)

Solicitud para agregar Instituto Profesional Los Leones

En caso de no leerse el archivo, a continuación redacto contenido:

Instituto Profesional Los Leones
https://ipleones.cl/

**Comment by coolGi2007** [comment]
[aphs.txt](https://github.com/JetBrains/swot/files/6762330/aphs.txt)
goes in `lib\domains\au\edu\sa`

Aberfoyle Park High School student

**Comment by philipto** [comment]
@FelixKLG lib/domains/org/kcpupils: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@FelixKLG Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.


@NattyNatt @coolGi2007 Please submit a separate pull request, not a comment to a someone's else request.

**Comment by FelixKLG** [comment]
image

**Comment by FelixKLG** [comment]
would this suffuce?

**Comment by philipto** [comment]
@FelixKLG Not really, regrettably. I don't see kcpupils.org mentioned anywhere at the screenshot or the official website. Weren't you given a printed instruction saying to use an email address in this domain? A copy of the instruction would work well. Thank you.

**Comment by FelixKLG** [comment]
A lot of schools don't provide such means anymore
though in combination with the previous screenshot could this work?
image

**Comment by philipto** [comment]
@FelixKLG Thank you for the clarification. Your request needs an extra check because the domain kcpupils.org is registered by an entity in Barcelona, Spain, according to WHOIS data. It seems to be different from actual location of the King's College official headquarters.

Please comment if you know why the domain was registered by non-British organization. I'll be back to this request as soon as possible.

**Comment by FelixKLG** [comment]
King's group has multiple locations, multiple of which are in Spain.
https://www.kingscollegeschools.org/
at the lower end of this site, it has the locations.

**Comment by felixlosada** [comment]
@philipto My friend might not be on so any further question you might need to ask today can go through me 👍

**Comment by felixlosada** [comment]
😢

**Comment by felixlosada** [comment]
@philipto Can I inquire on the status of this request?

**Comment by philipto** [comment]
@FelixKLG I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Pull request merged**
