### PR TITLE
Create ptd.txt

### PR DESCRIPTION
**Pull request by phanhiep2603**
Du Học Quốc Tế PTD
International Education PTD

### CODE REVIEW

**Comment by philipto** [comment]
@phanhiep2603 Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@phanhiep2603 You might miss my previous comment. Please react.

**Comment by phanhiep2603** [comment]
I’m so sorry, i had a vacation with my family three-day ago.
This is my website of my school: http://pdt.edu.vn/
Can u support for me ??
If you want anymore, repply email for me
Thanks guys. Have a nice day!

Được gửi từ iPhone của tôi

**Comment by philipto** [comment]
@phanhiep2603 Thank you for the clarification. We investigated the issue further, and found out that this organization is an intermediary which helps and connects domestic students to study in Germany and other Schengen countries. 

Thus, this domain does not belong to a university, nor to a college. I have to close the request without merging. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting a new request.

**Pull request closed without merging**
