### PR TITLE
Create it-neec.txt

### PR DESCRIPTION
**Pull request by 4ka8ne**

### CODE REVIEW

**Comment by philipto** [comment]
@4ka8ne Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by 4ka8ne** [comment]
Sorry…

- http://www.neec.ac.jp/kamata/

- http://www.neec.ac.jp/department/it/specialist/
（4Years）

- 
jetbrains

**Comment by 4ka8ne** [comment]
Supplement.
How does that look?

- whois[it-neec.jp]
whois

- pdf[www.neec.ac.jp]
http://www.neec.ac.jp/common/pdf/announcement/17073/28_opendata_kmt.pdf
Page(58/62),7th row, 2nd column.
pdf

**Comment by philipto** [comment]
@4ka8ne I am sorry for a delay with processing your request. It is now merged. Thank you!

**Pull request merged**
