### PR TITLE
Create muzickaskolapancevo.txt

### PR DESCRIPTION
**Pull request by BojRad**

### CODE REVIEW

**Comment by philipto** [comment]
@BojRad First stage of verification passed, official domain for **muzickaskolapancevo** is [muzickaskolapancevo.edu.rs](https://muzickaskolapancevo.edu.rs) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@BojRad Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by BojRad** [comment]
Here's the url to the page:
https://muzickaskolapancevo.edu.rs/srednja-skola/

**Comment by philipto** [comment]
@BojRad Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
