### PR TITLE
JetBrains Generated File For adding the Institution

### PR DESCRIPTION
**Pull request by NOCNP**
[dcc.txt](https://github.com/JetBrains/swot/files/5037540/dcc.txt)
#### Institution/School Name
{ Dhaka City College }

#### Instiution/School Website
{ https://dcc.netpoint.com.bd }
{ https://dhakacitycollege.edu.bd }

#### Email Server
{ dcc.netpoint.com.bd }

#### CSE Section URL
{ https://www.dhakacitycollege.edu.bd/index.php?request=dept&dept=CSE }
{ https://cse.dhakacitycollege.edu.bd }

#### Email Users
Please place an x between the square brackets if yes
[x] Students
[x] Academic/Teaching Staff
[ ] Other/Support Staff
[ ] Alumni

#### Education Levels
Please place an x between the square brackets if yes
[  ] Post-graduate research
[x] Graduate School
[x] College (University) or Undergraduate School or equivalent
[  ] Community College or equivalent
[  ] High School or equivalent
[  ] Elementary School or equivalent

#### Recognition Document
DCC Confirmation

### CODE REVIEW

**Comment by philipto** [comment]
@NOCNP Thank you for the detailed request!

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by NOCNP** [comment]
Sorry For the previous document. Both of them are in the same location that's why it's misplaced.

The document attached below: 

DCC Confirmation

**Comment by philipto** [comment]
@NOCNP Thank you very much! I am sorry, the document was not shown to me at the first time for some reason. Now I see both copies. Pull request merged.

**Comment by NOCNP** [comment]
Thank you so much for your co-operation. I'm very much pleased.

**Pull request merged**
