### PR TITLE
Add LinkiaFP new domain

### PR DESCRIPTION
**Pull request by Marckiie**
**Institution/School Name**
Linkia FP 

**Official Website**
Website: https://linkiafp.es/

Currently studying: https://linkiafp.es/fp-grado-superior-desarrollo-de-aplicaciones-web-a-distancia/   which is a IT-related long-term course (2 years)

I think they changed the domain for their emails from linkiafp.es to linkiafp.online for this semester, since the domain used to end with "@linkiafp.es" last semester. The one I'm using right now is marccabanapinlac7393@linkiafp.online.

### CODE REVIEW

**Comment by philipto** [comment]
@Marckiie Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

> I think they changed the domain for their emails from linkiafp.es to linkiafp.online for this semester, since the domain used to end with "@linkiafp.es" last semester. 

It would be easy if the email domain remains linkiafp.es. They do not mention linkiafp.online anywhere at the official website, thus we have to get a proof from you. Thank you.

**Comment by Marckiie** [comment]
Hi @philipto, thank you for answering. Here's an screenshot of my profile in our online campus:
image
Also a gif logging into our campus using my email as the username:
https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDZiM2FkODVlOGFiNjJiODk4MGU3YmZiNjMxNzMwYjAwMmZiNWE3ZiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/FnmibfGY3MLzHnvKBL/giphy.gif

**Comment by philipto** [comment]
@Marckiie  Thank you for the clarifications. Pull request merged. Would you please explain whether the school has a all-remote learning option? Are there students who study online only? If yes, could you please direct me to a page at the Ministry of Education website that certifies that the school is registered as an online-learning school?

Online-only schools pose higher risk of violations, thus I have to double-check.

**Comment by philipto** [comment]
@Marckiie  Thank you very much for the clarifications. Pull request merged.

**Comment by Marckiie** [comment]
Thank you very much!

**Pull request merged**
