### PR TITLE
Added neuefische 

### PR DESCRIPTION
**Pull request by terezaif**
Added neuefische - School and Pool for Digital Talent

[neuefische](https://www.neuefische.de/en)

### CODE REVIEW

**Comment by philipto** [comment]
@terezaif First stage of verification passed, official domain is [neuefische.de](https://neuefische.de) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by terezaif** [comment]
Hi @philipto thanks for letting me know, that is correct regarding the official domain. We also have official accreditation in case you need the proof let me know.

**Comment by philipto** [comment]
@terezaif Could you please clarify whether you offer courses that take 1 year or longer? If you do not offer such courses, please apply with a different form for the cooperation specific to training centers and bootcamps: https://www.jetbrains.com/community/education/#courses

**Comment by philipto** [comment]
@terezaif Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by terezaif** [comment]
Hi, we only have 3 and 6 months courses at the moment. The neuefische domain is though reserve for teachers who do courses throughout a year

**Comment by philipto** [comment]
@terezaif  Thank you for the clarifications. Pull request merged.

**Pull request merged**
