### PR TITLE
Northeast Forestry University

### PR DESCRIPTION
**Pull request by Code0401**
**I'm an it manager**，I can prove everything about my school，So why do Chinese universities seem to be treated differently?
What proof do you need, please tell me, I think it is impolite to close my pull request.
**_What kind of proof is valid, please tell me by example_**
image
**This is an alias for nefu.edu.cn.**
**I don't know if it's impolite to speak like this in your country**
Thank you.

### CODE REVIEW

**Comment by philipto** [comment]
@Code0401 Could you please send an email with your request to community-support@jetbrains.com. You are an official representative of the university, and it will be much easier to continue the conversation by email. I am sorry for the inconvenience, but a large amount of fraud enforces us to protect our honest customers, including students, from unauthorized use of their email domains.

I am sorry again for the inconvenience.

**Comment by Code0401** [comment]
> @Code0401 Could you please send an email with your request to [community-support@jetbrains.com](mailto:community-support@jetbrains.com). You are an official representative of the university, and it will be much easier to continue the conversation by email. I am sorry for the inconvenience, but a large amount of fraud enforces us to protect our honest customers, including students, from unauthorized use of their email domains.
> 
> I am sorry again for the inconvenience.

I know that the actions of some people have caused losses to your company, and I deeply regret it. You are a serious and responsible person, thank you for your help

**Comment by Code0401** [comment]
> @Code0401 Could you please send an email with your request to [community-support@jetbrains.com](mailto:community-support@jetbrains.com). You are an official representative of the university, and it will be much easier to continue the conversation by email. I am sorry for the inconvenience, but a large amount of fraud enforces us to protect our honest customers, including students, from unauthorized use of their email domains.
> 
> I am sorry again for the inconvenience.

Today is the Chinese Lantern Festival, best wishes for you

**Comment by philipto** [comment]
@Code0401 Thank you very much for the understanding! Have a very happy Lantern Festival!

**Comment by Code0401** [comment]
Please tell me what to prepare to contact community-support@jetbrains.com
请告诉我要准备什么联系community-support@jetbrains.com
thank you

**Comment by philipto** [comment]
@Code0401 Please send the email message from your university email address, and mention that you are an IT manager at Northeast Forestry University. 

If you have an internal instruction for students in Chinese, which tells them that they can use their university email address at nefueducn.onmicrosoft.com, please attach the copy of this instruction to the email, it will make things much simpler.

Thank you very much!

**Comment by Code0401** [comment]
I have sent an email, please check, **I sent it twice**, using **nefu.edu.cn** and **nefueducn.onmicrosoft.com**.
thank you.

**Comment by philipto** [comment]
@Code0401 Thank you for sending the email to JetBrains support. As you might notice, we had to hold on your request until you update the website and provide appropriate documents in Chinese. Please feel free to continue your communication with JetBrains support if you have any questions or concerns. 

As for now, I have to close your request without merging. We'll reopen the request if there will be sufficient evidence that this domain is an official domain of the university. Thank you for your patience and understanding.

**Pull request closed without merging**
