### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by iivanabm**

### CODE REVIEW

**Comment by sam2909** [comment]
[file.zip](https://github.com/JetBrains/swot/files/5532219/file.zip)

**Comment by moadHB** [comment]
[swot-master.zip](https://github.com/JetBrains/swot/files/5533753/swot-master.zip)
education license

**Comment by sam2909** [comment]
> [swot-master.zip](https://github.com/JetBrains/swot/files/5533753/swot-master.zip)
> education license
How can I use this file?
Thank you.

**Comment by philipto** [comment]
@iivanabm I am sorry, I have to close the request without merging, because you made a mistake in a request and did not specify any filepath. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and make a new correct request. Thank you for your understanding!

**Pull request closed without merging**
