### PR TITLE
add domain hluv.edu.vn

### PR DESCRIPTION
**Pull request by docbohanh**

### CODE REVIEW

**Comment by philipto** [comment]
@docbohanh First stage of verification passed, official domain is [hluv.edu.vn](https://hluv.edu.vn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by KiraBobyleva** [comment]
Hi @docbohanh, 

Could you please let me know what ms. means in the beginning of the domain hluv.edu.vn you're submitting?

Thanks!

**Comment by docbohanh** [comment]
> Hi @docbohanh,
> 
> Could you please let me know what ms. means in the beginning of the domain hluv.edu.vn you're submitting?
> 
> Thanks!

Maybe `microsoft`, I have been given an email account `@ms.hluv.edu.vn` for online learning via Microsoft Teams

**Comment by KiraBobyleva** [comment]
@docbohanh, thank you. Could you please also provide a URL of a page on the official website where the school offers an IT-related long-term (>1 year) course?

**Comment by philipto** [comment]
@docbohanh You might miss our last comment. Please react.

**Comment by docbohanh** [comment]
> @docbohanh You might miss our last comment. Please react.

Sorry @KiraBobyleva, @philipto,
The URL seem to be [http://hluv.edu.vn/vi/page/knnth](http://hluv.edu.vn/vi/page/knnth), but I don't find reference for IT-related long-term!

**Comment by philipto** [comment]
@docbohanh Thank you for the clarification. I cannot add the domain without being sure that the school has a long-term IT-related course. Please let me know why the university does not publish the course curriculum. Thank you.

**Comment by docbohanh** [comment]
I am asking the university for more information, I will re-open this pull request when it becomes available.
Thank you!

**Pull request closed without merging**
