### PR TITLE
Create takeerbergen

### PR DESCRIPTION
**Pull request by TakJGE**
Add extra domain of Technisch Atheneum Keerbergen
www.takeerbergen.be
Technical Atheneum Keerbergen

### CODE REVIEW

**Comment by philipto** [comment]
@TakJGE lib/domains/be/takeerbergen: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@TakJGE The first verification stage is complete: the official domain for  **Technisch Atheneum Keerbergen** is [www.technischatheneumkeerbergen.be](https://www.technischatheneumkeerbergen.be), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.technischatheneumkeerbergen.be/inschrijvingen/

**Comment by TakJGE** [comment]
Dear Philip

 

Thank you for your assistance. 

 

The main domain currently is www.technischatheneumkeerbergen.be <http://www.technischatheneumkeerbergen.be> . However, our school has created a secondary domain, www.takeerbergen.be <http://www.takeerbergen.be> , which is easier to type. All student mail addresses have already been transferred to this new domain. However, www.takeerbergen.be <http://www.takeerbergen.be>  has not yet been linked as an alias to www.technischatheneumkeerbergen.be <http://www.technischatheneumkeerbergen.be> . I will ask our IT department to create this alias.

 

That is why I tried to add the domain takeerbergen.be to our school. Students have no longer access to a @technischatheneumkeerbergen.be mail box (teachers still have).

 

Thank you.

 

Kind regards

 

Joris

 

 

Van: Philip Torchinsky ***@***.***> 
Verzonden: dinsdag 19 maart 2024 8:42
Aan: JetBrains/swot ***@***.***>
CC: TakJGE ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [JetBrains/swot] Create takeerbergen (PR #20319)

 

 <https://github.com/TakJGE> @TakJGE The first verification stage is complete: the official domain for Technisch Atheneum Keerbergen is  <https://www.technischatheneumkeerbergen.be> www.technischatheneumkeerbergen.be, to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership:  <https://www.technischatheneumkeerbergen.be/inschrijvingen/> https://www.technischatheneumkeerbergen.be/inschrijvingen/

**Comment by philipto** [comment]
@TakJGE The first verification stage is complete: the official domain for  **Technisch Atheneum Keerbergen** is [www.technischatheneumkeerbergen.be](https://www.technischatheneumkeerbergen.be), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.technischatheneumkeerbergen.be/inschrijvingen/

**Comment by philipto** [comment]
@TakJGE Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
