### PR TITLE
Add Aldini Valeriani School

### PR DESCRIPTION
**Pull request by xFedeT**

### CODE REVIEW

**Comment by xFedeT** [comment]
Note this is the Students Domain

**Comment by philipto** [comment]
@xFedeT Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by xFedeT** [comment]
Scholl Site: www.avbo.it
Street Adress  Via Bassanelli 9/11 – 40129 Bologna
Course Link: http://avbo.it/index.php/informatica-e-telecomunicazioni/
Proof of Official Email for Students:
http://avbo.it/index.php/contatti/posta-elettronica/



Il giorno lun 17 gen 2022 alle ore 16:45 Philip Torchinsky <
***@***.***> ha scritto:

**Comment by philipto** [comment]
@xFedeT Thank you for the clarification. Pull request merged.

**Comment by xFedeT** [comment]
> @xFedeT Thank you for the clarification. Pull request merged.

How long should it take to update the list?

**Pull request merged**
