### PR TITLE
add stu.scau.edu.cn

### PR DESCRIPTION
**Pull request by zhangboyi**

### CODE REVIEW

**Comment by zhangboyi** [comment]
add South China Agricultural University, GuangZhou China

**Comment by zhangboyi** [comment]
https://www.scau.edu.cn/_t78/main.htm
image
https://metc.scau.edu.cn/2017/1017/c145a59660/page.htm
image

https://metc.scau.edu.cn/2017/1101/c126a63356/page.htm
image


**#### Please check and approve it. Thank you very much**

**Comment by zhangboyi** [comment]
@philipto May I ask whether the information I submitted meets the standards of the audit?

**Comment by philipto** [comment]
@zhangboyi I am sorry, the domain stu.scau.edu.cn is removed from our trusted domains list because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
