### PR TITLE
Add Fundacion Kinal

### PR DESCRIPTION
**Pull request by DaMVgt**

### CODE REVIEW

**Comment by DaMVgt** [comment]
Official domain is https://www.kinal.org.gt/ and emails with domain kinal.edu.gt. Example: dmonterroso-i004m@kinal.edu.gt.
Thank you.

**Comment by IOabsolutes** [comment]
Official domain is http://www.zse.boleslawiec.pl/strona/index.php and emails with domain kinal.edu.gt. Example: zse@poczta.internetdsl.pl.
Thank you.

**Comment by philipto** [comment]
@DaMVgt First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/kinal.gt/photos/a.10153781337239740/10158342620074740/

**Comment by DaMVgt** [comment]
how is the process going? If you have any questions about the domain or the use of the license, you can contact alvarocalderon@kinal.org.gt or the instructor edwintumax@kinal.edu.gt. Thank you.

**Comment by philipto** [comment]
@DaMVgt Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
