### PR TITLE
Create sharif.txt

### PR DESCRIPTION
**Pull request by hnikaein**
CE department: http://ce.sharif.edu

### CODE REVIEW

**Comment by hnikaein** [comment]
CE department: http://ce.sharif.edu

**Comment by ishto7** [comment]
EE department: [http://ee.sharif.edu](http://ee.sharif.edu)

**Comment by rezaep** [comment]
IE department: [http://ie.sharif.edu](url)

**Comment by NightMachinary** [comment]
General department (used for CS): https://mail.sharif.edu/ (uses `@student.sharif.edu`)

**Comment by philipto** [comment]
Unfortunately, your request cannot be processed further because JetBrains doesn’t provide products or services to territories subject to applicable EU, UN, or US sanctions or under comprehensive export control restrictions due to legal, compliance, and other commercial risks.

I have to close the request. I appreciate your understanding.

**Pull request closed without merging**
