### PR TITLE
 add domain

### PR DESCRIPTION
**Pull request by cleitonMigliorinii**
We are an educational institution that started the technology course in 2022. We made the release for the students' domain, I would like the release for the teachers as well.

the school official website URL :

https://cesul.br/
the school street address, including city and country :

Brazil, Francisco Beltrão - Parana - Av. Antônio de Paiva Cantelmo, 1222 - Centro. an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

https://cesul.br/graduacao/presencial/analise-e-desenvolvimento-de-sistemas/sobre-o-curso/ https://www.cesul.br/cesul-inicia-o-curso-de-analise-e-desenvolvimento-de-sistemas/ https://jornaldebeltrao.com.br/geral/cesul-inicia-o-curso-de-analise-e-desenvolvimento-de-sistemas/ a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Each student who is enrolled gains access to the student portal which is used in the domain @alunocesul.com https://cesul.jacad.com.br/academico/aluno-v2/login

### CODE REVIEW

**Comment by philipto** [comment]
@cleitonMigliorinii First stage of verification passed, official domain is [cesul.br](https://cesul.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@cleitonMigliorinii Please clarify this:
> Each student who is enrolled gains access to the student portal which is used in the domain @alunocesul.com 

Do you need to add a domain alunocesul.com or cesul.br (the latter is represented by the file in your request)?

**Comment by cleitonMigliorinii** [comment]
Hello, I need for @cesul.br the domain @alunocesul.com has already been released previously, as I reported this domain @cesul.br and another domain of the institution.

**Comment by philipto** [comment]
@cleitonMigliorinii Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
