### PR TITLE
Create uabc.txt

### PR DESCRIPTION
**Pull request by arhuertah**
Please add Universidad Autonoma de Baja California to be valid email domain: @uabc.edu.com.mx

### CODE REVIEW

**Comment by philipto** [comment]
@arhuertah Could you please give us a link to a page on the official university page which says that @uabc.edu.com.mx domain is actually an official email domain for the unversity students?

Also, could you please provide us with a link to a page where the university offers a long-term (> 1 year) IT-related course?

**Comment by arhuertah** [comment]
Sure, here is the official link for Universidad Autonoma de Baja California: http://www.uabc.mx/

Into the official page is the following link to access email
UABC email: http://correo.uabc.edu.mx/

UABC has a an engineering faculty with following link: http://fiad.ens.uabc.mx/
Here offers Computer Engineering career with following path: http://fiad.ens.uabc.mx/images/formatos/2016-1/aanuevos/COMPUTACION.pdf

**Comment by philipto** [comment]
@arhuertah Thank you! It's now clear that the university offers a Computer Engineering course.

As for the @uabc.edu.com.mx domain, I see the problem: I can not find this domain mentioned at uabc.mx website at all. Is there any webpage, document or another proof that this domain is available for the students and teachers only?

**Comment by arhuertah** [comment]
Actually I did recently a merge to be valid the domain : @uabc.edu.mx and if you review http://www.uabc.mx/ at bottom of the page is the email domain: 
uabcemail

**Comment by philipto** [comment]
@arhuertah Yes, thank you for the update. With this change, it is absolutely valid and working. Pull request merged.

**Pull request merged**
