### PR TITLE
Added gim-bp.txt

### PR DESCRIPTION
**Pull request by r0pe-12**

### CODE REVIEW

**Comment by philipto** [comment]
@r0pe-12 Please kindly provide the full name of your school on the first line of the file in your request

**Comment by philipto** [comment]
@r0pe-12 You might miss my previous comment. Please react. 

You can reply with the name of the school in the comment.

**Comment by r0pe-12** [comment]
Name of my school in serbian is JU Gimnazija "Miloje Dobrašinović"

**Comment by philipto** [comment]
@r0pe-12 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
