### PR TITLE
Create coet

### PR DESCRIPTION
**Pull request by utkarshns**
Added MGM CoET, Noida.

### CODE REVIEW

**Comment by philipto** [comment]
@utkarshns Could you please provide us with a link to a page on the official website where it's said that students use @coet.in domain for their emails? [Contacts page of the university](http://www.coet.in/contact.asp) shows another email domain as a university contact.

**Comment by utkarshns** [comment]
Goto mail login on http://coet.in/

You would be directed to this URL, its used by students:

https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ltmpl=default&service=mail&sacu=1&rip=1&hd=coet.in#identifier



The general format of the students' email is:

Roll_number@coet.in

like mine is 1209510077@coet.in

**Comment by philipto** [comment]
@utkarshns Thank you. Unfortunately, it's impossible to check, because neither Google, nor coet.in website show anything saying that coet.in is for the students. Problem is that *coet.in* domain is registered by *Centre for Development of Advanced Computing (C-DAC)*, according to WHOIS data, not the university of the college. Could you please give us some proof of the fact that this domain is actually used by students? A webpage on the official website, or a policy in the form of .pdf document available for university students would work.

**Comment by utkarshns** [comment]
Can you give me your personal email ID as this isn't private?

**Comment by utkarshns** [comment]
CDAC is Indian government's organization. It helped our college to build the website. They didn't do a good job. That's pretty evident.
And coet.in is used by both staff and students. I can show u screenshots, if that would work.

**Comment by krisavi** [comment]
I believe also when you try to navigate to mgmnoida.org you end up in coet.in, most likely I see them as being connected in some way. It is CDAC is at least Indian govermental organization like he already told. https://en.wikipedia.org/wiki/Centre_for_Development_of_Advanced_Computing 

Also according to that page these 2 pages are both for the same school. http://www.themgmgroup.com/noida.html 

Unfortunately I was not able to find any information about student having the e-mails. But it seems the person who is requesting it is a student in this school and has a e-mail address with the coet.in ending. The principal mail seems to be with other domain, but teachers ones are in the coet.in as well. So in my conclusion it could be accepted, but final say is on @philipto still. 

Not sure if it helps, but some of the teachers have also the e-mails listed at http://coet.in/cs.asp

I just tried to be maybe a bit of assistance and gather some information that may help.

**Comment by utkarshns** [comment]
Thanks a lot Kris.

BTW, if u google "1209510077 utkarsh"
<https://www.google.co.in/search?q=1209510077+utkarsh>

The only result is a pdf hosted on coet.in, the pdf contains some practical
examination related information along with the students' roll numbers.
Like mine is 1209510077, so my email is 1209510077@coet.in and even google
mail shows my name like "Utkarsh Narain Srivastava". So you could pick any
roll number and try to mail them like roll_number@coet.in after emailing,
the name would appear (cross check it from the practical examination pdf
found at coet.in) as it is under google apps (the education program).
They even give us free unlim. storage under that program.

I believe also when you try to navigate to mgmnoida.org you end up in
coet.in, most likely I see them as being connected in some way. It is CDAC
is at least Indian govermental organization like he already told.
https://en.wikipedia.org/wiki/Centre_for_Development_of_Advanced_Computing

Also according to that page these 2 pages are both for the same school.
http://www.themgmgroup.com/noida.html

Unfortunately I was not able to find any information about student having
the e-mails. But it seems the person who is requesting it is a student in
this school and has a e-mail address with the coet.in ending. The principal
mail seems to be with other domain, but teachers ones are in the coet.in as
well. So in my conclusion it could be accepted, but final say is on
@philipto <https://github.com/philipto> still.

Not sure if it helps, but some of the teachers have also the e-mails listed
at http://coet.in/cs.asp

I just tried to be maybe a bit of assistance and gather some information
that may help.

—
Reply to this email directly or view it on GitHub
<https://github.com/JetBrains/swot/pull/1772#issuecomment-193382560>.

**Comment by philipto** [comment]
@utkarshns @krisavi Thank you for your kind and detailed explanation! Now it seems to be clear, and I merge the pull request.

**Comment by utkarshns** [comment]
Thanks a lot!

**Pull request merged**
