### PR TITLE
CIFP Pere de Son Gall

### PR DESCRIPTION
**Pull request by IFCPSG**
adding college to apply for license "Centre integrat Formació Profesional Pere de Son Gall"
https://cifpperedesongall.org
Higher degree of development applications
domain teachers: @cifpperedesongall.org
domain students: @a.cifpperedesongall.org

### CODE REVIEW

**Comment by IFCPSG** [comment]
adding college "Centre integrat Formació Profesional Pere de Son Gall"
https://cifpperedesongall.org/oferta-educativa/cfgs/cfgs-ifc32/ 
Higher degree of development  applications

**Review by IFCPSG — COMMENTED** [review]
adding college "Centre integrat Formació Profesional Pere de Son Gall"
https://cifpperedesongall.org/oferta-educativa/cfgs/cfgs-ifc32/
Higher degree of development applications

**Comment by philipto** [comment]
@IFCPSG First stage of verification passed, official domain for **CIFP Pere de Son Gall** is [cifpperedesongall.org](https://cifpperedesongall.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@IFCPSG Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
