### PR TITLE
add online school

### PR DESCRIPTION
**Pull request by xman213**
Developer UNI is a school for python devs.

### CODE REVIEW

**Comment by HelmutJony** [comment]
high school with a bilingual IT profile
[file (2).zip](https://github.com/JetBrains/swot/files/9812854/file.2.zip)

**Comment by philipto** [comment]
@xman213 Please provide us with:
* the school official website URL
* the school full name
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@HelmutJony Please make a separate pull request, or apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

**Comment by philipto** [comment]
@xman213 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@xman213 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
