### PR TITLE
Adding Liceu Santista

### PR DESCRIPTION
**Pull request by gustavoper**
Website; https://www.liceusantista.com.br/
Name: Liceu Santista (Maintained by philanthropic institution Sociedade Visconde de S Leopoldo)

### CODE REVIEW

**Comment by gustavoper** [comment]
More info about the Philantropic institution which mantain us can be found here: https://www.unisantos.br/universidade/informacoes-de-servico/mantenedora-sociedade-visconde-de-sao-leopoldo/
(Unfortunately we don't have an English description)

**Comment by gustavoper** [comment]
More info about the Systems Developer course can also be found here: 
https://www.liceusantista.com.br/ensino-tecnico/

**Comment by philipto** [comment]
@gustavoper First stage of verification passed, official domain for **Liceu Santista** is [liceusantista.com.br](https://liceusantista.com.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@gustavoper Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
