### PR TITLE
Create eps-marche.txt

### PR DESCRIPTION
**Pull request by romu242**

### CODE REVIEW

**Comment by philipto** [comment]
@romu242 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@romu242 You might miss my previous comment. Please react.

**Comment by romu242** [comment]
Good morning,

 

*	the school official website URL
*	the school street address, including city and country
*	an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
*	a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

 

1.	URL of website : https://ieps-marche.be/
2.	6900 MARCHE-EN-FAMENNE (Belgique)
Avenue de la Toison d’Or, 71 
Téléphone : 084/32.16.46
De lundi à jeudi de 9h00 à 12h00, et de 17h00 à 20h00. 
Vendredi fermé
3.	URL of computer science section : https://ieps-marche.be/bachelier-informatique/
4.	My professionnal mail adress : ***@***.***

Best regards

 

 

De : Philip Torchinsky ***@***.***> 
Envoyé : mercredi 31 août 2022 05:34
À : JetBrains/swot ***@***.***>
Cc : romu242 ***@***.***>; Mention ***@***.***>
Objet : Re: [JetBrains/swot] Create eps-marche.txt (PR #14912)

 

@romu242 <https://github.com/romu242>  You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@romu242  Thank you for the clarifications. Pull request merged.

**Comment by romu242** [comment]
Good morning,

@romu242<https://github.com/romu242> Please provide us with:

  *   the school official website URL
  *   the school street address, including city and country
  *   an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
  *   a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.



  1.  https://ieps-marche.be/
  2.  MARCHE-EN-FAMENNE
Avenue de la Toison d'Or, 71
084/32.16.46
De lundi à jeudi de 9h00 à 12h00, et de 17h00 à 20h00.
Vendredi fermé
  3.  https://ieps-marche.be/bachelier-informatique/
  4.  You have my professionnal mail adress

Best regards
[Formations chez IEPSCF de Marche-en-Famenne Institut d ...]



LAMEUSE Romuald
IEPSCF Jemelle
Enseignant
Bac en informatique

**Pull request merged**
