### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RejectModderss**
Added Moberly High School

### CODE REVIEW

**Comment by philipto** [comment]
@RejectModderss The first verification stage is complete: the official domain for  **Moberly High School** is [www.moberly.k12.mo.us](https://www.moberly.k12.mo.us), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.moberly.k12.mo.us/staff?page_no=2

**Comment by RejectModderss** [comment]
Yeah, that is correct, but all schools in that district go under that email! So I put the High School only because it will be mainly High Schoolers who need it! Thank you for looking into it, I should have added a website, that is my bad!

**Comment by philipto** [comment]
@RejectModderss The first verification stage is complete: the official domain for  **Moberly High School** is [www.moberly.k12.mo.us](https://www.moberly.k12.mo.us), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.moberly.k12.mo.us/staff?page_no=2

**Comment by philipto** [comment]
@RejectModderss Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
