### PR TITLE
Add obs-hilter.de

### PR DESCRIPTION
**Pull request by dev-zer**
[Homepage](http://oberschule-hilter.de/)
[Email System](https://obs-hilter.de/iserv/login)

### CODE REVIEW

**Comment by philipto** [comment]
@dev-zer First stage of verification passed, official domain is [hilter.de](https://hilter.de) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.hilter.de/de/Wohnen_in_Hilter/schulen

**Comment by dev-zer** [comment]
Thanks!

**Comment by dev-zer** [comment]
hilter.de is the domain of our city

**Comment by philipto** [comment]
@dev-zer Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
