### PR TITLE
Added Kendriya Vidyalaya Namrup to the list

### PR DESCRIPTION
**Pull request by zoid-anurag**
Kindly Add my school name to the list of schools.

### CODE REVIEW

**Comment by philipto** [comment]
@zoid-anurag Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@zoid-anurag You might miss my previous comment. Please react.

**Comment by zoid-anurag** [comment]
lipto thanks for your response. 
The url to the institute with information regarding student enrollment and courses offered are below. 

namrupbvfcl.kvs.ac.in

**Comment by zoid-anurag** [comment]
The address for the school 
KENDRIYA VIDYALAYA NAMRUP, PO PARBATPUR DISTRICT DIBRUGARH, NAMRUP , ASSAM, PIN CODE- 786623

**Comment by zoid-anurag** [comment]
Due to the ongoing covid situation, there might be some delay arranging for the proof for official student email domain.

**Pull request merged**
