### PR TITLE
Domain for International academy of civil aviation Casablanca

### PR DESCRIPTION
**Pull request by helodev-helux**
Adding aiac domain

### CODE REVIEW

**Comment by philipto** [comment]
@helodev-helux Please provide us with a proof, which shows that the school recognizes the domain aiacingenieur.ma that you are submitting as an official email domain for the students.

**Comment by helodev-helux** [comment]
Well i don't know how i am supposed to do that, but you can check the SSL Certificate on the school website, you will find both domains aiac.ma and aiacingenieur.ma in the registered domains, teachers and students mail address are all on aiacingenieur.ma domain even though the website redirects to aiac.ma 

And you can also find the school's phone number from the school's website aiac.ma in the homepage footer or even the mail address of all the school's board staff in the contact section. so you can ask either the director Mr Menou or Mr Hakim ABDESLEM any other person from the school board by mailing them

Screenshot 2020-10-22 at 03 45 41
Screenshot 2020-10-22 at 03 48 25

**Comment by philipto** [comment]
@helodev-helux Thank you for the clarification. Pull request merged. SSL certificate is quite sufficient.

**Comment by helodev-helux** [comment]
Please i have created another pull request with the other school domain aiac.ma since they finally switched our mails to it .
Please check it

**Pull request merged**
