### PR TITLE
Add Hector-Seminar

### PR DESCRIPTION
**Pull request by fredpi**

### CODE REVIEW

**Comment by philipto** [comment]
@fredpi I am sorry, do I understand right that your institution is not a university, nor a college? It is rather a provider of additional education, is it correct?

**Comment by fredpi** [comment]
@philipto Indeed, it isn't a university or college right away, but it's a supplementary education to secondary school for highly-gifted students. Since it runs over the course of 6 years and in the last years, projects are mostly done in cooperation with universities (as can be seen ob the website) that partially require pro tools, I consider it suitable nonetheless.

**Comment by philipto** [comment]
@fredpi Could you please give us a link to a page on the official website where an IT-related long-term (>1 year) course is offered by the school?

**Comment by fredpi** [comment]
@philipto Here's a page describing the concept of a one-year cooperation project with universities: https://hector-seminar.de/wie-wir-foerdern/kooperationsphase/

Here's a list of some of last year's projects and their results: https://hector-seminar.de/aktuelles/seite-meldungen/meldungen-201718/abschlusskolloquium-hdma11/

**Comment by philipto** [comment]
@fredpi I am sorry, it looks like your organization can not be considered as a university, a school, or a college. Please email your request for free license to community-support@jetbrains.com, and they will offer you the most appropriate licensing scheme. Regrettably, I have to close this request without merging. Thank you for the understanding!

**Pull request closed without merging**
