### PR TITLE
Add EAFC Sud Luxembourg School

### PR DESCRIPTION
**Pull request by ThibautGobert**

### CODE REVIEW

**Comment by ThibautGobert** [comment]
Hello,

Our emails can be : 
- name@student.eafc-sudlux.be
- name@staff.eafc-sudlux.be

I don't know if I did it correctly.

Thank you

**Comment by philipto** [comment]
@ThibautGobert First stage of verification passed, official domain is [eafc-sudlux.be](https://eafc-sudlux.be) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@ThibautGobert Thank you. I modified the file in your request to add both students and staff email domains. Pull request merged.

**Comment by ThibautGobert** [comment]
@philipto  Thank you very much

**Pull request merged**
