### PR TITLE
Create ACWHCC and Ashland City Schools

### PR DESCRIPTION
**Pull request by ahadley1124**
https://www.acwhcc.org/high-school/campus-programs/cybersecurity-and-networking-technology
ACWHCC gives you a domain that forwards to our ashland-city.k12.oh.us email.

### CODE REVIEW

**Comment by philipto** [comment]
@ahadley1124 Could you please let us know a little bit more details: who have email addresses ending with @acwhcc.org, and who - with @ashland-city.k12.oh.us? Thank you.

**Comment by ahadley1124** [comment]
Every student has an **@ashland-city.k12.oh.us** but every message sent to this email is automatically forwarded to **@acwhcc.org**. We use **@acwhcc.org** so that we can login to google to use it with all the google apps. Please let me know if you have any other questions.

**Comment by ahadley1124** [comment]
> @ahadley1124 Could you please let us know a little bit more details: who have email addresses ending with @acwhcc.org, and who - with @ashland-city.k12.oh.us? Thank you.

Every student has an **@ashland-city.k12.oh.us** but every message sent to this email is automatically forwarded to **@acwhcc.org**. We use **@acwhcc.org** so that we can login to google to use it with all the google apps. Please let me know if you have any other questions.

**Comment by philipto** [comment]
@ahadley1124 Thank you for the clarification. Pull request merged.

**Pull request merged**
