### PR TITLE
Added The Altamont School

### PR DESCRIPTION
**Pull request by DJN1**
Emails have the format:
student@altamontschool.org

Computer science courses can be found in the official Science Curriculum Guide:
https://www.altamontschool.org/uploaded/1-Altamont_School/Academics/2018-19_Science_Curriculum_Guide.pdf

### CODE REVIEW

**Comment by philipto** [comment]
@DJN1 For student@altamontschool.org email address pattern matching filename has to be lib/domains/org/altamontschool.txt. Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and modify your request accordingly.

**Comment by DJN1** [comment]
Sorry about that. I couldn't figure out how to change the path of the first commit so I created a new one.

**Comment by philipto** [comment]
@DJN1 Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by DJN1** [comment]
Thank you very much!

**Pull request merged**
