### PR TITLE
JetBrains student program

### PR DESCRIPTION
**Pull request by ChristianHohn**
I have 2 more years to go, so it would be nice if i could continue to use your software for my lessons.

### CODE REVIEW

**Comment by philipto** [comment]
@ChristianHohn Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@ChristianHohn You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@ChristianHohn You might miss my previous comment. Please react.

**Comment by ChristianHohn** [comment]
@philipto Sorry for only awnsering just now. I don't have a document from my school saying anything about the email they provided since they gave us our Microsoft 360 login data during a lesson. All i have is a document about me attending the school. Thank you for your help

**Comment by philipto** [comment]
@ChristianHohn A photo of a typed or hand-written notice from your teacher with the teacher's name and signature would be enough. Could you please try and upload such a photo?

**Comment by ChristianHohn** [comment]
@philipto ok, i will contact one of my Teachers. This could take a few days, since they are not that fast responding to emails on the weekend. The email will most likely be in german but i can add a translated version for you.

**Comment by ChristianHohn** [comment]
@philipto Hi, my techer gave me the document today. He provided me with both the german and the english verison

[JetBrains.pdf](https://github.com/JetBrains/swot/files/7516231/JetBrains.pdf)

I hope that is enough to confirm the email used.
Thank you for your help

**Comment by philipto** [comment]
@ChristianHohn Thank you very much for the clarification. Pull request merged.

**Pull request merged**
