### PR TITLE
Add University of Computer Studies, Sittway

### PR DESCRIPTION
**Pull request by OoThan**

### CODE REVIEW

**Comment by philipto** [comment]
@OoThan I am sorry, does this university have an official website? Does it work? I don't see both this university's website and email server working :(

**Comment by OoThan** [comment]
http://www.ucssittway.edu.mm

**Comment by philipto** [comment]
@OoThan I does not work for me :(

**Comment by philipto** [comment]
@OoThan I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
