### PR TITLE
unifil.txt

### PR DESCRIPTION
**Pull request by renatojava**
UniFil - Centro Universitário Filadélfia

### CODE REVIEW

**Comment by renatojava** [comment]
swot/lib/domains/br/unifil/edu/

**Comment by philipto** [comment]
@renatojava for edu.unifil.br domain the file path has to be `lib/domains/br/unifil/edu.txt`, **NOT** `lib/domains/br/unifil/edu/unifil.txt`. Please  rename or suggest another domain, if you meant different one.

Could you please also give us a link to a page where it's said that students of the university use edu.unifil.br as their email domain?

**Comment by renatojava** [comment]
Hello,

The website is http://www.unifil.br/, for the student unifil use the google account, when you enter website there will be link "WebMail" that redirect to google email.
For you see, I printed the my account and commited in the repository where there the link to create email Edu.Unifil.br, but only students authenticated has access

**Comment by renatojava** [comment]
The unifil use the google email service.
Thank you.

**Comment by philipto** [comment]
@renatojava Thank you for the details. I merged the pull request and removed the .png from the repository because repository can contain just .txt files. Thank you!

**Pull request merged**
