### PR TITLE
 Werner-von-Siemens-Schule

### PR DESCRIPTION
**Pull request by Olitrax99**
Werner-von-Siemens-Schule

### CODE REVIEW

**Comment by philipto** [comment]
@Olitrax99 Please provide us with:
* the school official website URL
* the school street address, including city and country
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Olitrax99 You might miss my previous comment. Please react.

**Comment by Olitrax99** [comment]
@philipto

The website: https://www2.wvs-ffm.de/
Schools address: Gutleutstraße 333-335, D-60327 Frankfurt am Main

I dont really know how a proof should look like. The domain wvsi.de is used for the students azure accounts. Can you give examples of what you expect?
grafik

**Comment by philipto** [comment]
@Olitrax99 Thank you very much for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
