### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Kulkarni-mohit**

### CODE REVIEW

**Comment by Kulkarni-mohit** [comment]
Added file as mentioned on website

**Comment by Tarneem2022** [comment]
please, add this university (uop)
[file (1).zip](https://github.com/JetBrains/swot/files/10333961/file.1.zip)

**Comment by Tarneem2022** [comment]
[uopstd.txt](https://github.com/JetBrains/swot/files/10333964/uopstd.txt)

**Comment by philipto** [comment]
@Kulkarni-mohit First stage of verification passed, official domain is [aissmsioit.org](https://aissmsioit.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Kulkarni-mohit Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
