### PR TITLE
Added a new college/school

### PR DESCRIPTION
**Pull request by bijankundu**
Added Future Institute of Engineering and Management, Sonarpur

### CODE REVIEW

**Comment by philipto** [comment]
@bijankundu Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school. Thank you!

**Comment by philipto** [comment]
@bijankundu You might miss my previous comment. Please react.

**Comment by bijankundu** [comment]
Here is the URL you requested for [https://futureengineering.in/]. Apologies for the late reply.

**Comment by bijankundu** [comment]
[](https://futureengineering.in/)[](url)

**Comment by bijankundu** [comment]
[](https://futureengineering.in/)

**Comment by bijankundu** [comment]
Here is the URL you requested for [Link](https://futureengineering.in/) Apologies for the late reply.

**Comment by philipto** [comment]
@bijankundu Thank you for the update! Pull request merged.

**Pull request merged**
