### PR TITLE
Adds Eagles Landing Christian Academy

### PR DESCRIPTION
**Pull request by xxShadowRingxx**
Eagles Landing Christian Academy

### CODE REVIEW

**Comment by philipto** [comment]
@xxShadowRingxx Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@xxShadowRingxx You might miss my previous comment. Please react.

**Comment by xxShadowRingxx** [comment]
I cant find an IT-related long-term course, and how could I prove that the school uses the domain I provided
Other than that I can give you the rest
elcaonline.org
2400 Highway 42 N, McDonough, GA 30253

**Comment by philipto** [comment]
@xxShadowRingxx Thank you for the clarification. Yes, the school is eligible for being added to the trusted list. 

Please provide us with a proof, which shows that the school recognizes the domain elcachargers.org that you are submitting, as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by xxShadowRingxx** [comment]
Would this work, I can’t find any proof, only email domain I have found on the website are Faculty domains.
IMG_1891
IMG_1890
IMG_1889
IMG_1888

**Comment by xxShadowRingxx** [comment]
You still there @philipto

**Comment by philipto** [comment]
@xxShadowRingxx  Thank you for the clarifications. Pull request merged.

FTR: another proof of the domain ownership is at https://www.instantcheckmate.com/people/ruby-calhoun/

**Pull request merged**
