### PR TITLE
Added IT-Schule Berufsakademie Passau

### PR DESCRIPTION
**Pull request by Chris92de**

### CODE REVIEW

**Comment by philipto** [comment]
@Chris92de Please give us an URL of the school official website. Thank you.

**Comment by philipto** [comment]
@Chris92de You might miss my previous comment. Please reply.

**Comment by Chris92de** [comment]
Sorry, I indeed missed your previous comment.
http://berufsakademie-passau.de for the overarching school and
http://it-schule-passau.de for the IT division.

Emails starting with fi_ and ending in @bappassau.onmicrosoft.com are
assigned to students in the IT school. (FI stands for Fachinformatiker)

**Comment by philipto** [comment]
@Chris92de Thank you for the update. Regrettably, I failed to find any mention of @bappassau.onmicrosoft.com at the website. Could you please give me a link to any page or document confirming that this domain is belonged to your school?

**Comment by Chris92de** [comment]
Hello Philip,
short update, I've talked to the principal of the school and they're in the process of updating the school's website with a notice that the students will receive an @bappassau.onmicrosoft.com email.
Once done, I'll post a link to the specific page.

**Comment by philipto** [comment]
@Chris92de Thank you very much! I am looking forward to hearing from you soon.

**Comment by philipto** [comment]
@Chris92de I am sorry, don't you have any update?

**Comment by philipto** [comment]
@Chris92de I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
