### PR TITLE
add Technifutur job seeker training center

### PR DESCRIPTION
**Pull request by YannickBoogaerts**
I am a trainer for this training at Technifutur: http://www.technifutur.be/formations-informatique-formations-pour-demandeurs-d-emploi-formation-developpeur-java-angular

### CODE REVIEW

**Comment by philipto** [comment]
@YannickBoogaerts Thank you for the request. How long this course takes (in days)?

**Comment by philipto** [comment]
@YannickBoogaerts You might miss my previous comment. Please react.

**Comment by YannickBoogaerts** [comment]
I am currently on leave I recontact you on Monday


Yannick Boogaerts
Formateur informatique

yannick.boogaerts@technifutur.be<mailto:yannick.boogaerts@technifutur.be>
Tél. direct : + 32(0)4 382 44 96

TECHNIFUTUR® asbl
Liège Science Park
Rue du Bois St-Jean, 15-17
B 4102 Seraing
Tél. : +32(0)4 382 45 00
Fax : +32(0)4 382 45 46
www.technifutur.be<http://www.technifutur.be>


De : Philip Torchinsky [mailto:notifications@github.com]
Envoyé : mardi 13 août 2019 10:49
À : JetBrains/swot
Cc : Yannick Boogaerts; Mention
Objet : Re: [JetBrains/swot] add Technifutur job seeker training center (#6597)


@YannickBoogaerts<https://github.com/YannickBoogaerts> You might miss my previous comment. Please react.

**Comment by YannickBoogaerts** [comment]
Mr. Torchinsky,

 

Technifutur organizes training for job seekers of more or less 8 months.

 

Participants use a computer provided by us during class and their personal computer to work at home.

 

Yannick Boogaerts
Formateur informatique

 <mailto:yannick.boogaerts@technifutur.be> yannick.boogaerts@technifutur.be
Tél. direct : + 32(0)4 382 44 96

TECHNIFUTUR® asbl
Liège Science Park
Rue du Bois St-Jean, 15-17 
B 4102 Seraing
Tél. : +32(0)4 382 45 00
Fax : +32(0)4 382 45 46
 <http://www.technifutur.be> www.technifutur.be

 

 

 

De : Philip Torchinsky [mailto:notifications@github.com] 
Envoyé : vendredi 9 août 2019 14:49
À : JetBrains/swot
Cc : Yannick Boogaerts; Mention
Objet : Re: [JetBrains/swot] add Technifutur job seeker training center (#6597)

 

@YannickBoogaerts <https://github.com/YannickBoogaerts>  Thank you for the request. How long this course takes (in days)?

**Comment by philipto** [comment]
@YannickBoogaerts Thank you for the clarification! According to the rules of this repository located at the bottom of [this page](https://github.com/JetBrains/swot),
"Your pull request for adding a new email domain to the repository will be satisfied if **all of the conditions below are met**:
* The domain is used by an educational institution, which offers **at least one long-term course (one year or longer)**, and the course is somehow related to IT (it is in computer science, software engineering, statistics, bioinformatics, etc.)
* The educational institution is a physical entity with student attendance and recognized as providing a learning curriculum for the educational system, or the institution is an accredited online educational organization providing their students with: (1) online courses with a curriculum at least one year long, (2) a dedicated email address which is provided to students only until their graduation."

Thus, your school does not qualify for being added to this repository. Please use another option to provide your students with free licenses for JetBrains tools. Please send an email to community-support@jetbrains.com and request free licenses there. JetBrains will be glad to suggest you best possible licensing option, suitable for your school. 

I have to close this request without merging. 
Thank you!

**Pull request closed without merging**
