### PR TITLE
submit educational license for Liceo Scientifico Statale Leon Battist…

### PR DESCRIPTION
**Pull request by daaddo**
Liceo Scientifico Statale Leon Battista Alberti

### CODE REVIEW

**Comment by philipto** [comment]
@daaddo lib/domains/it/edu/liceoalbertinapoli: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by daaddo** [comment]
Hello, I believe the path was correct, but I failed to check if the file was saved as a .txt format.

**Comment by philipto** [comment]
@daaddo First stage of verification passed, official domain is [liceoalbertinapoli.edu.it](https://liceoalbertinapoli.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@daaddo Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
