### PR TITLE
Create otw.txt

### PR DESCRIPTION
**Pull request by KeelanV**
Adding Ottawa Herzing school domain

### CODE REVIEW

**Comment by philipto** [comment]
@KeelanV Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@KeelanV You might miss my previous comment. Please react.

**Comment by KeelanV** [comment]
My apologies, am I supposed to provide the information via github?

**Comment by philipto** [comment]
@KeelanV First stage of verification passed, official domain is [herzing.ca](https://herzing.ca) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@KeelanV I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by KeelanV** [comment]
Here is the information you requested.

https://www.herzing.ca/
West - McArthur, 1200 St. Laurent Blvd, Ottawa, ON K1K 3B8
https://www.herzing.ca/programs/cybersecurity-ottawa?campus=otw&group=ottawa
[Proof of email.docx](https://github.com/JetBrains/swot/files/9594204/Proof.of.email.docx)

**Comment by KeelanV** [comment]
https://www.herzing.ca/
West - McArthur, 1200 St. Laurent Blvd, Ottawa, ON K1K 3B8
https://www.herzing.ca/programs/cybersecurity-ottawa?campus=otw&group=ottawa
[Proof of email.docx](https://github.com/JetBrains/swot/files/9594220/Proof.of.email.docx)

**Comment by KeelanV** [comment]
Hello JetBrains/swot,

Here is the information you requested.

https://www.herzing.ca
West - McArthur, 1200 St. Laurent Blvd, Ottawa, ON K1K 3B8
https://www.herzing.ca/programs/cybersecurity-ottawa?campus=otw&group=ottawa
[image: image.png]
(Email between myself and an employee at the college.)

**Pull request closed without merging**
