### PR TITLE
Create krasnobrod.txt

### PR DESCRIPTION
**Pull request by sb84**

### CODE REVIEW

**Comment by philipto** [comment]
@sb84 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by sb84** [comment]
Proof for pio.edu.pl - https://pio.edu.pl/kontakt/ - email to the secretary's office 
Proof for krasnobrod.edu.pl - https://i.vgy.me/W9GyRP.png - screen from account of the electronic diary

**Comment by philipto** [comment]
@sb84 Thank you for your patience while waiting for the request review. Could you please provide us for each of the schools with:

- the school official website URL
- the school street address, including city and country
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proofs:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

Thank you!

**Comment by philipto** [comment]
@sb84 You might miss my previous comment. Please react.

**Comment by sb84** [comment]
@philipto I am waiting for relevant documents from the school management

**Comment by philipto** [comment]
@sb84 Thank you for your prompt reply! Please upload the document in a comment to this request via your browser as soon as you have the document. Thank you!

**Comment by sb84** [comment]
OK, I have the information I need.
Krasnobród (krasnobrod.edu.pl) on the moment withdraws (does not comment on the management's decisions).
However, Director Pio (pio.edu.pl) sent the relevant document with confirmation (attached).

[20220104121150869.pdf](https://github.com/JetBrains/swot/files/7807282/20220104121150869.pdf)

**Comment by sb84** [comment]
@philipto Is the attached document sufficient for pio.edu.pl?

**Comment by philipto** [comment]
@sb84 I edited your pull request and merged it. Thank you.

**Pull request merged**
