### PR TITLE
Added tvtc.gov.sa

### PR DESCRIPTION
**Pull request by moboody**
this is our vocational training colleges and institutes.

### CODE REVIEW

**Comment by moboody** [comment]
School name: Technical and Vocational Training Corporation
School website: http://www.tvtc.gov.sa

**Comment by philipto** [comment]
@moboody Do I understand correctly that students of all the colleges listed at http://www.tvtc.gov.sa/english/trainingunits/collegesoftechnology/Pages/default.aspx have their email addresses in @tvtc.gov.sa domain? We do not grant free licenses to employees of government agencies, we usually add just universities and colleges email domains to this list (and provide them with free licenses).

**Comment by moboody** [comment]
Actually, the students of all the colleges have their emails addresses in @MT.tvtc.edu.sa domain.

it is only the teachers and employees that share the same domain @tvtc.edu.sa for their emails.

**Comment by philipto** [comment]
@moboody Thank you for the clarification! In this case we can add the domain to the list. Please notice that free educational licenses for JetBrains tools are for educational purpose only, and they are for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Pull request merged**
