### PR TITLE
Create obspm.txt

### PR DESCRIPTION
**Pull request by nono031**
We are a french governemental research institute : http://www.obspm.fr/?lang=en

Founded in 1667, the Observatoire de Paris is the largest national research center for astronomy. 30 % of all French astronomers are working in it five laboratories and its institute. Situated on the Paris, Meudon and Nançay campuses, they are all "Unités Mixtes de Recherche (UMR)" associated with the CNRS and, in many cases, with the major scientific universities in the Paris area. The work of the Observatoire is also carried out in two major scientific services. The Observatoire de Paris is an academic centre (Grand établissement) under the aegis of the Ministère de l’Enseignement supérieur et de la Recherche

### CODE REVIEW

**Comment by nono031** [comment]
Hi , there is any issue on me request ? Do you need more information ?

Best regards,

Arnaud

**Comment by zweizwei** [comment]
@nono031 please excuse my delay with replying you. Could you please provide the link to the page, describing long-term educational programs, that the Observatory provides? thank you!

**Comment by nono031** [comment]
No worries ;)

http://www.obspm.fr/-enseignement-.html?lang=en

On the left, you have a menu where you can found all teaching banches :
* Doctoral School
* Master
* University degrees
* Teacher training
* Distance learning
* Continued education

Is it enought ?

**Comment by zweizwei** [comment]
@nono031 that's exactly the information i needed, thank you! I'm adding the domain

**Pull request merged**
