### PR TITLE
Add Wuhan Institute of Physics and Mathematics Chinese Academy of Science

### PR DESCRIPTION
**Pull request by Rivsen**
Wuhan Institute of Physics and Mathematics Chinese Academy of Science

### CODE REVIEW

**Comment by philipto** [comment]
@Rivsen lib/domains/cn/ac/wipm: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Rivsen lib/domains/cn/ac/wipm: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Rivsen lib/domains/cn/ac/wipm: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Rivsen** [comment]
Sorry for that, I renamed that file in correct format.

**Comment by philipto** [comment]
@Rivsen Pull request merged. 
Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of this Institute who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.
Thank you!

For the record, a proof of the domain ownership: http://english.wipm.cas.cn/rh/rd/yzfzsys/yzfz1/yzfz1_gro/

**Pull request merged**
