### PR TITLE
Add ukrainian university to list

### PR DESCRIPTION
**Pull request by Poprop**
Adding Poltava State Agrarian University ( Ukraine) into university list . Thx for this opportunity for students

### CODE REVIEW

**Comment by Poprop** [comment]
Adding poltava agrarian university

**Comment by philipto** [comment]
@Poprop First stage of verification passed, official domain is [pdau.edu.ua](https://pdau.edu.ua) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Poprop Please provide us with a proof, which shows that the school recognizes the domain **pdau.poltava.ua**, that you are submitting as an official email domain for the students.
You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by Poprop** [comment]
Sorry i made mistake in domain , it must be - @st.pdau.edu.ua
1.Page of university - https://www.pdau.edu.ua/
2.Page with instruction how to use corporative university mail domain   -
https://moodle.pdau.edu.ua/
video instruction page -https://youtu.be/qhMuSlfgnbs
3.Screen shot of my university domain mail box with invitations to online
lessons in google meet
[image: image.png]

ср, 22 нояб. 2023 г. в 18:33, Philip Torchinsky ***@***.***>:

**Comment by philipto** [comment]
@Poprop No problem, thank you for the update. Pull request merged. Feel free to request free licenses with emails ending with @st.pdau.edu.ua. **Please start requesting licenses in an hour**, to let the changes to propagate through our systems. Thank you!

**Comment by Poprop** [comment]
Thank you for your help!

пт, 24 лист. 2023, 09:19 користувач Philip Torchinsky <
***@***.***> пише:

**Pull request merged**
