### PR TITLE
Add CDCSIT TU

### PR DESCRIPTION
**Pull request by otsab19**
Add TU cdcsit.

### CODE REVIEW

**Comment by philipto** [comment]
@otsab19 Please provide us with:
* the school official website URL
* the school street address, including city and country; please explain what is relation between [Tribhuvan University](http://www.tu.edu.np/) and this school.
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@otsab19 You might miss my previous comment. Please react.

**Comment by otsab19** [comment]
@philipto 

- Official site: [CDCSIT](https://cdcsit.edu.np/)
- It is located inside Tribhuwan University: Kirtipur, Nepal. map location: [Location](https://www.google.com/maps/place/Central+Department+of+Computer+Science+%26+Information+Technology/@27.6822214,85.2840737,17z/data=!3m1!4b1!4m5!3m4!1s0x39eb186cc1b853ff:0xb81ccb86db29c848!8m2!3d27.6822395!4d85.2862648)
- Central Department of Computer Science & Information Technology(CDCSIT) takes care of Department of Computer under Tribhuwan University.
-  Courses: [](https://cdcsit.edu.np/academics/?msc-csit)
- The school's domain is [](https://cdcsit.edu.np). Email address is under TU: @cdcsit.tu.edu.np

**Comment by philipto** [comment]
@otsab19  Thank you for the clarifications. Pull request merged.

**Pull request merged**
