### PR TITLE
Add University of Computer Studies ( Pakokku ) - Myanmar

### PR DESCRIPTION
**Pull request by lwinmoehein**

### CODE REVIEW

**Comment by philipto** [comment]
@lwinmoehein First stage of verification passed, official domain is [ucspkku.edu.mm](https://ucspkku.edu.mm) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by lwinmoehein** [comment]
@philipto Thanks for verifying our university domain.Domain you mentioned is official and it is a right one.Thanks for taking time to review my pull request.

**Comment by philipto** [comment]
@lwinmoehein Pull request merged. Thank you.

**Comment by lwinmoehein** [comment]
@philipto Thank you too 😊

**Pull request merged**
