### PR TITLE
Add Higher Institute of Computer Science and Mathematics of Monastir

### PR DESCRIPTION
**Pull request by riadh26**
The university official website URL : http://www.isimm.rnu.tn/

### CODE REVIEW

**Comment by philipto** [comment]
@riadh26 Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by riadh26** [comment]
Hi, this screenshot is from the official website of application in the
university, as we apply, an email is given to us automatically.
Thanks

**Comment by philipto** [comment]
@riadh26 I am sorry, GitHub strips out screenshots if you send them by email. Could you please add the screenshot to a comment via GitHub web interface? Thank you!

**Comment by riadh26** [comment]
Screenshot_20200226-091819

**Comment by philipto** [comment]
@riadh26 Thank you for the clarification. Pull request merged.

**Pull request merged**
