### PR TITLE
Please add Gavilan College,. Thank you!

### PR DESCRIPTION
**Pull request by Natalia-crypto**
https://gavilan.edu/
https://www.gavilan.edu/academic/csis/index.php

### CODE REVIEW

**Comment by philipto** [comment]
@Natalia-crypto lib I am sorry, I have to close the request without merging, because you made a mistake in a request and did not specify any filepath. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and make a new correct request. Thank you for your understanding!

**Comment by Natalia-crypto** [comment]
I'm confused as to why I even have to add this school. It is a requirement
for my class and this teacher has been traching this class for quite some
time. How do I do this? I am extremely frustrated.

**Comment by philipto** [comment]
@Natalia-crypto I added

**Comment by philipto** [comment]
@Natalia-crypto I added **gavilan.edu** domain and all its subdomains for you, including my.gavilan.edu. The request is closed, but the domain is in the trusted list.

**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by Natalia-crypto** [comment]
Awesome, thank you so much!

**Pull request closed without merging**
