### PR TITLE
Create uteg

### PR DESCRIPTION
**Pull request by ekontiki89**

### CODE REVIEW

**Comment by zweizwei** [comment]
@ekontiki89 could you please check that the website is available? unfortunately i can't open uteg.edu
Also please add .txt extension to the committed website.

**Comment by philipto** [comment]
@ekontiki89 It looks like you wish to add and entry for Centro Universitario UTEG Héroes Ferrocarrileros 1325, Col. La Aurora, C.P. 44460 Guadalajara, Jalisco, México. Its website is http://www.uteg.edu.mx/. Please make sure its e-mail domain is uteg.edu indeed. If it is not, please close this pull request and create a new one, under lib/domains/mx/edu with the name uteg.txt and the name of the university in the .txt file. I am looking forward to having the clarification from you. 

Thank you!

**Comment by zweizwei** [comment]
I'm closing the request due to being obsolete. @ekontiki89 please reply to reopen.

**Comment by ekontiki89** [comment]
@zweizwei Sorry I can not respond in time, but in this pull me wrong, in fact already agregre college https://github.com/JetBrains/swot/blob/master/lib/domains/mx/edu/uteg.txt

**Pull request closed without merging**
