### PR TITLE
remove alunos.estacio.br from block list

### PR DESCRIPTION
**Pull request by renanlido**
PLEASE remove alunos.estacio.br from the stoplist.txt

This is a valid student email managed by Universidade Estácio de Sá, provided by Microsoft and made available to students to access their virtual classrooms and their respective campuses. Student email is an important tool for academic and professional communication, in addition to offering benefits such as unlimited storage, security and integration with other Microsoft services.

image

The official site of the university is https://estacio.br/

The official portal dor students is https://estudante.estacio.br/

Any questions, please contact me.

### CODE REVIEW

**Comment by philipto** [comment]
@renanlido lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by renanlido** [comment]
> @renanlido lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.

Shure @philipto, I've sent an email to support so they can help me.

Thank you!

**Comment by philipto** [comment]
@renanlido lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@renanlido 

Thank you for your request. Regrettably, the domain **alunos.estacio.br** was removed from our trusted domains list because one of the following happened:
1) the school allows to register an email address there even if you are not a student of the school.
2) someone from the school shared their account details publicly or sold it, and it led to broad account misuse and license terms violation.

Therefore, we are not able to identify if the people with addresses in these email domain are actual students or not.
Under no circumstances we can remove the domain from the stoplist. The domain mail system seems to have severe vulnerabilities as we have observed a very serious domain abuse.

Please apply with official document ("OFFICIAL DOCUMENT" tab at [https://www.jetbrains.com/shop/eform/students).](https://www.jetbrains.com/shop/eform/students).*)

**Pull request closed without merging**
