### PR TITLE
Create ar.txt

### PR DESCRIPTION
**Pull request by WhereIsMySnake**
Add Agricultural University of Wroclaw to database

### CODE REVIEW

**Comment by philipto** [comment]
@WhereIsMySnake Could you please give us a link to a page saying that ar.wroclaw.pl domain is for students email only? All contact emails at the official website are in up.wroc.pl domain, which is different, see for example http://www.rekrutacja.up.wroc.pl/studia/71628/bioinformatyka.html and http://www.rekrutacja.up.wroc.pl/kontakt/

Official website also redirects from ar.wroc.pl to up.wroc.pl.

**Comment by WhereIsMySnake** [comment]
@philipto yes, official web is up.wroc.pl and students mail is *poczta.student.up.wroc.pl as you can see here: https://www.student.up.wroc.pl/instrukcja.html. Unfortunately there is no english version.

**Comment by philipto** [comment]
@WhereIsMySnake If student email domain is **poczta.student.up.wroc.pl**, the file representing it in this repository shall be `lib/domains/pl/wroc/up/student/poczta.txt`, not `lib/domains/pl/wroclaw/ar.txt`. Could you please double check the email domain and change the file path accordingly?

**Comment by WhereIsMySnake** [comment]
Thanks for clarification. I will change it to right repo.

**Comment by philipto** [comment]
@WhereIsMySnake I have to close this request without merging because it remains unanswered for a while, and I see no new requests or changes for the domain which we discussed in this conversation. Thank you for your understanding!

**Pull request closed without merging**
