### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by HaokunHe**

### CODE REVIEW

**Comment by philipto** [comment]
@HaokunHe lib/domains/com/student[1].txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@HaokunHe I am sorry, what is your school student email pattern? Is it username@student.com?
Please answer. Thank you.

**Comment by HaokunHe** [comment]
K.he@student.saintkentigern.com
________________________________________

**Comment by philipto** [comment]
@HaokunHe lib/domains/com/student[1].txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@HaokunHe OK, I renamed the file to make its filepath correct, and merged the request. You can apply for your free license at https://www.jetbrains.com/shop/eform/students in an hour. Happy coding!

**Pull request merged**
