### PR TITLE
Added thcs-nguyentrai.edu.vn

### PR DESCRIPTION
**Pull request by thcs-nguyentrai**
**CHANGES**

- Added domain thcs-nguyentrai.edu.vn

### CODE REVIEW

**Comment by philipto** [comment]
@thcs-nguyentrai There are too many organizations with names similar to THCS Nguyễn Trãi.
Thus, please provide us with:
- the school official website URL
- the school street address, including the city 
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you!

**Comment by philipto** [comment]
@thcs-nguyentrai You might miss my previous comment. Please react.

**Comment by thcs-nguyentrai** [comment]
@philipto sorry because i reply late

1. The school official website URL: `https://www.thcs-nguyentrai.edu.vn/`. The old website here `http://nguyentraint.edu.vn/`. But we are doing migrate to new website. 
2. The school street address, including the city: `Phu Quy 3 village, Tam My Dong commune, Nui Thanh district, Quang Nam province`. The school is far away from city and locates at the poverty district.
3. an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: currently, we had the course for student, but we did not update on this website yet. We always organize the IT test for students and want they learn programming languages. Then we have plan to extend these courses.
4. a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students: im asking the President to give you the certification/confirmation about this is the official domain ASAP since he's in the business trip.

Thanks for reviewing

**Comment by philipto** [comment]
@thcs-nguyentrai Thank you very much for the details and clarification! You submitted enough proofs, we don't need any additional information from you anymore. The pull request merged. Thanks a lot for your contribution!

**Pull request merged**
