### PR TITLE
Dav.txt

### PR DESCRIPTION
**Pull request by tuananhbuii**

### CODE REVIEW

**Comment by philipto** [comment]
@tuananhbuii First stage of verification passed, official domain is [dav.edu.vn](https://dav.edu.vn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@tuananhbuii Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by anhbt2868** [comment]
@philipto My uni doesn't have any IT related courses, but I research them myself so I need an IDE account. So can you help me browse? Thank you !

**Comment by tuananhbuii** [comment]
@philipto My uni doesn't have any IT related courses, but I research them myself so I need an IDE account. So can you help me browse? Thank you !

**Comment by philipto** [comment]
@tuananhbuii I am sorry, in this circumstances I cannot add the domain to the trusted list. Please apply for free educational license individually, with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
