### PR TITLE
TCMIT

### PR DESCRIPTION
**Pull request by Manish12356789**

### CODE REVIEW

**Comment by Manish12356789** [comment]
I am from Texas college of Management and IT. It is located in Kathmandu, Nepal. Please approve my request.

**Comment by philipto** [comment]
@Manish12356789 What is your university email pattern? Is it username@tcmid.edu.np? 

Also, please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by Manish12356789** [comment]
*Texas College of Management and IT *
*College Website:* http://texascollege.edu.np/
*College Provided IT Programme:* http://texascollege.edu.np/programs/bit/
*College Provided Id:* manish.parajuli@tcmit.edu.np

**Comment by philipto** [comment]
@Manish12356789 tcmit.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Manish12356789 I am sorry, I might be not clear enough. A proof is a page at the official website, where it is explicitly said that  `tcmit.edu.np` is a university email domain. It can also be a copy of a paper document which the university gives to the students upon enrollment, or a link to an article published in a reputable international scientific journal, where the email of a person clearly affiliated with the university is mentioned. 

An ability to show that you possess the email in this domain does not mean that the university recognizes it. Please find the proof which confirm that **the university** recognizes the domain as official.

**Comment by philipto** [comment]
@Manish12356789 tcmit.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Manish12356789 tcmit.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Manish12356789 tcmit.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Manish12356789 tcmit.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Manish12356789 tcmit.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Manish12356789 tcmit.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Manish12356789 I completed the investigation. The pull request corrected and merged. Please apply for your free license.

**Pull request merged**
