### PR TITLE
Add Arish University

### PR DESCRIPTION
**Pull request by HeshamMo96**

### CODE REVIEW

**Comment by sjt888** [comment]
[Uploading file.zip…]()

**Comment by HeshamMo96** [comment]
> Uploading file.zip…

should i upload the zip file or the university folder ?!

**Comment by sjt888** [comment]
I do not know!

**Comment by philipto** [comment]
@HeshamMo96 I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host aru.aru.edu.eg not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Pull request closed without merging**
