### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ronron555**

### CODE REVIEW

**Comment by philipto** [comment]
@ronron555 Please provide us with an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by ronron555** [comment]
Hey, the school website is https://www.beit-yerach.com/ <https://www.beit-yerach.com/> but for some reason they use another domain for the mail addresses.
byerach.org is just a short for Beit Yerach, the name of the school.
I don’t know what else can I give you in-terms of proof because the domain situation in this school is so weird.
If this helps, the school had another domain for the old website http://yerach.org.il <http://yerach.org.il/> but this website is inactive and the domain just go to the hosting company of the old website.

**Comment by philipto** [comment]
@ronron555 Thank you for the clarification! Yes, the problem is that byerach.org is not mentioned anywhere at the official website of your school as a domain available for the students. Do you have any instruction which the school provided you with? They had to let you know somehow, which email address you are to use. Please upload a copy of the paper/email or whatever else they used to tell you about it.

**Comment by ronron555** [comment]
**Hey, this is the whatsapp message we got in the first day of the year:**
תלמידים יקרים,
אנו יודעים שלחלק מהתלמידים אין כתובות מייל ובגלל זה אנחנו בצוות בית הספר החלטנו לחלק לכם כתובות מייל משלכם.
אם אתם רוצים להיכנס לכתובת המייל שלכם, היכנסו לגוגל ולחצו על כפתור הכניסה מצד שמאל למעלה, לאחר מכן כתבו את השם הפרטי שלכם באנגלית, את האות הראשונה של שם המשפחה ואת המספר הראשון בתאריך הלידה שלכם. 
לדוגמה: niras3@byerach.org
•	מייל זה אינו פעיל, אנא לא לשלוח אליו מיילים!


**Here is translation via google translate:**
Dear students,
We know that some students do not have any email addresses and that is why we on the school team have decided to give you your own email addresses.
If you want to enter your email address, log in to Google and hit the sign-in button from the top right, then enter your first name in English, the first letter of the surname and the first number on your date of birth.
For example: niras3@byerach.org
• This email is inactive, please do not send it emails!

**Comment by philipto** [comment]
@ronron555 Thank you for the update. Pull request merged.

**Pull request merged**
