### PR TITLE
add DLUFL

### PR DESCRIPTION
**Pull request by rieonke**
[Dalian University of Foreign Languages](http://www.dlufl.edu.cn/en/) has a lot of IT students.
[The Department of Computer Science](http://www.dlufl.edu.cn/en/Schools-Departments/2014-11-10/42354.html)
[`dlufl.edu.cn`](http://mail.dlufl.edu.cn) for teachers.
[`student.dlufl.edu.cn`](http://mail.student.dlufl.edu.cn) for students.
[`dwlxs.cn`](http://mail.dwlxs.cn) for preppy and other students.

### CODE REVIEW

**Comment by philipto** [comment]
@rieonke Could you please give us a proof that dwlxs.cn domain is recognized as an official email domain for the students? I did not find this address anywhere at the university website.

**Comment by rieonke** [comment]
@philipto Hello, This [notice](http://ge.dlufl.edu.cn/xsgz/tzgg/2013-10-08/25419.htm) may be able to confirm. Thanks!

**Comment by philipto** [comment]
@rieonke Thank you for the clarification. Could you please explain who are "preppy and other students"? In most universities the students can be undegraduate, graduate and postgraduate students. They also can be called "bachelor", "master" and "doctorate" students. If "other" and "preppy" mean the students who are not enrolled to the university yet, I would advise to avoid adding `dwlxs.cn` to the repository.

**Comment by rieonke** [comment]
I am very sorry for the misleading words.
In fact most of our students are normal  "bachelor", "master" and "doctorate" students. all of those students can use our main portal system and campus network (intranet).
but there are also some "non-degree" students who takes courses at university but will not get a certificate of "degree" but a certificate of "graduation". For example the exchange students, language students who learns foreign language in school for two years and then will study abroad("preppy" or "preppie") and other kinds of students. they can't access the main portal system but a separate portal system and use separate account to access campus network and the account will be disabled after graduating. obviously "dwlxs" is the abbreviation in Chinese Pinyin of them.
So may dwlxs.cn is not, strictly speaking, so official. but I hope this can be added, cause some of them will study at this university for a long time, I know some students love programming and even work as a part time job in IT Dept. of university.
Thanks!

**Comment by philipto** [comment]
@rieonke Thank you for the clarification. You are right, the students of this kind match the educational license criteria. Pull request merged. Thanks again for the details!

**Pull request merged**
