### PR TITLE
Add Industrial University of Ho Chi Minh City to JetBrains Edu

### PR DESCRIPTION
**Pull request by ductoanvo**

### CODE REVIEW

**Comment by ductoanvo** [comment]
[Industrial University of Ho Chi Minh City (IUH)](http://iuh.edu.vn/en)

**Comment by ductoanvo** [comment]
Industrial University of Ho Chi Minh City (Đại học Công nghiệp thành phố Hồ Chí Minh)

- Website: [iuh.edu.vn](http://iuh.edu.vn/en)
- Address: [12 Nguyen Van Bao, Ward 4, Go Vap District, Ho Chi Minh City, Vietnam](https://goo.gl/maps/E2peeT9P48G8tgTJ6)
- Undergraduate programs that related to IT: [Falculty of Information Technology Undergraduate programs landing page](http://fit.iuh.edu.vn/news.html@188@Undergraduate-programs) includes: Computer Science, Software Engineer, Information Technology, Information Systems that takes more than 4 years to complete.
- An instruction of how to register email from IUH System Administration Center: [Link](https://csm.iuh.edu.vn/upload/files/huongdan/huongdansudungemail010421.pdf) in Vietnamese.
- Official announcement from Rector Dr. Phan Hong Hai about using Email system promulgated at 01/04/2021: [Link](https://csm.iuh.edu.vn/upload/files/huongdan/QD432_QuyDinhEmailIUH.pdf) in Vietnamese.
- An instruction of how to activate Office365 using IUH email for student: [Link](https://csm.iuh.edu.vn/upload/files/huongdan/huongdancaidatvakichhoatbooffice365bangtaikhoanemailsinhvien-iuh_final.pdf)
- As mentioned in Official announcement, IUH students when signing up for an email will have the form of email like studentID.name@student.iuh.edu.vn. Login in mail.iuh.edu.vn

**Comment by ductoanvo** [comment]
Hi @philipto, 

Just in case you miss my pull request, I requested around 3 days ago from now and haven't yet received any comments or notices about my university case valid or not.

If you're reviewing my case and still not have any decision, please notice me.

Thank you!

**Comment by ductoanvo** [comment]
Hi @philipto, 

Just in case you missed my pull request, I requested around 3 days ago from now and haven't yet to receive any comments or notices about my university case valid or not.

If you're reviewing my case and still not have any decision, please notice me.

Thank you!

**Comment by ductoanvo** [comment]
Hi @philipto, please take a look at my pull request! Thanks!

**Comment by philipto** [comment]
@ductoanvo Pull request merged. Thank you!

**Pull request merged**
