### PR TITLE
CEMS

### PR DESCRIPTION
**Pull request by josuamittels**

### CODE REVIEW

**Comment by philipto** [comment]
@josuamittels The first verification stage is complete: the official domain for  **CEMS – The Global Alliance in Management Education** is [www.cems.org](https://www.cems.org), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.cems.org/faq

**Comment by josuamittels** [comment]
@philipto yes the domain is cems.org, however the email services go through a separate domain @cemsmail.org

**Comment by philipto** [comment]
@josuamittels Thank you for the clarification. Could you please tell us more about the school? I see that this is a network of schools. Which one do you represent? The school does not seem to be a conventional university or provide software development courses, thus we need some additional details.

Please provide us with:
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

Thank you!

**Comment by philipto** [comment]
@josuamittels You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@josuamittels I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
