### PR TITLE
Create hrzedu.txt

### PR DESCRIPTION
**Pull request by TheAmazingCodeGuru**
District domain of Herzliya city schools. Herzliya, Israel.

### CODE REVIEW

**Comment by philipto** [comment]
@TheAmazingCodeGuru Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by TheAmazingCodeGuru** [comment]
I need to provide every school website URL? Isn't the district domain URL enough?

**Comment by philipto** [comment]
@TheAmazingCodeGuru We need an URL of an official website which says that students of Herzliya city schools use @hrzedu.org.il as their email domain.  It is not necessary to give us the URLs of many schools, it will be absolutely enough to give us URLs of your school website, and the website of the city district, if it confirms that all the schools share the same email domain.

Please make sure that you are familiar with the rules of this repository located at the bottom of [this page](https://github.com/JetBrains/swot), and provide necessary information in comments to your request accordingly. 

Thank you!

**Comment by philipto** [comment]
@TheAmazingCodeGuru This request remains unanswered for a while. I will have to close it without merging unless you answer the question above. We really need the additional information about your email domain before accepting the request. Thank you for the understanding.

**Comment by philipto** [comment]
@TheAmazingCodeGuru I am very sorry to close your request without merging. We sometimes add school district email domains to this repository, if the schools in a district share the same email domain. However we never do it without looking at the district website, and checking which kind of schools the domain serves. There are many different school systems around the world, and we cannot be familiar with all of them without being told about them. Shall you have any update regarding the issues mentioned above, please reopen your request and comment. Thank you for your understanding.

**Pull request closed without merging**
