### PR TITLE
Create cns.txt

### PR DESCRIPTION
**Pull request by rajeshgsoni**
Hello!

Please find below details:
Added cns.ac.in (Chatrabhuj Narsee School)

1) the university official website URL, if it is different from the domain you are submitting
Website: https://cns.ac.in

2) a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
https://www.cns.ac.in/cambridge-upper-secondary-igcse-grade-9-to-10/

a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
3) https://www.cambridgeinternational.org/why-choose-us/find-a-cambridge-school/?Location=India&City=Maharashtra

### CODE REVIEW

**Comment by Wochozka** [comment]
Please add sour school to your repository :-)

Thanks,

David.

**Comment by rajeshgsoni** [comment]
> 

Hello David,

Is that message for me?
Is there anything that I need to do?

I have tried to follow the guidelines set for the Pull Request.

Do let me know if there's anything that I can help with.

Thanks
Rajesh

**Comment by philipto** [comment]
@rajeshgsoni First stage of verification passed, official domain is [cns.ac.in](https://cns.ac.in) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Wochozka** [comment]
Hallo Rajesh,
I\m so sorry, I\m stupid. I post the message about pull request to add our school into Jetbrains to wrong window - yours. I see it is already solved as right request, so now I just wait to complete.

Thank you and have a nice day,

David.

**Comment by philipto** [comment]
@rajeshgsoni Pull request merged. Thank you.

**Pull request merged**
