### PR TITLE
Institute of Applied Technology

### PR DESCRIPTION
**Pull request by beba4434**

### CODE REVIEW

**Comment by philipto** [comment]
@beba4434 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@beba4434 You might miss my previous comment. Please react.

**Comment by beba4434** [comment]
1. https://www.iat.ac.ae
2. 8 16 A St - Al Qusais Industrial Area - Al Qusais Industrial Area 2 - Dubai, United Arabic Emirates
3. https://www.iat.ac.ae/component/simplefilemanager?task=download&id=59 (Page 46)
4.  https://www.iat.ac.ae/schools/admission/contact-us

**Comment by beba4434** [comment]
@philipto [philipto](https://github.com/philipto)

**Comment by beba4434** [comment]
@philipto

**Comment by philipto** [comment]
@beba4434 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
