### PR TITLE
add tolosaldealh to eus schools

### PR DESCRIPTION
**Pull request by hruiz-dev**
the schools website is this: [website](https://tolosaldea.hezkuntza.net/web/guest_english)

### CODE REVIEW

**Comment by philipto** [comment]
@hruiz-dev The first verification stage is complete: the official domain for  **Tolosaldealh** is [ikasgela.tolosaldealh.eus](https://ikasgela.tolosaldealh.eus), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://ikasgela.tolosaldealh.eus/

**Comment by hruiz-dev** [comment]
@philipto What I wanted to say is that in the domain of ikasgela.tolosaldealh.eus is the domain where all the educational material and the emails that students use are located and in the domain https://tolosaldea.hezkuntza.net/web/guest_english is the information about the institution

**Comment by philipto** [comment]
@hruiz-dev The first verification stage is complete: the official domain for  **Tolosaldealh** is [ikasgela.tolosaldealh.eus](https://ikasgela.tolosaldealh.eus), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://ikasgela.tolosaldealh.eus/

**Comment by philipto** [comment]
@hruiz-dev Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
