### PR TITLE
cz penui

### PR DESCRIPTION
**Pull request by tatyalien**

### CODE REVIEW

**Comment by tatyalien** [comment]
Url: https://www.peuni.cz/

**Comment by philipto** [comment]
@tatyalien First stage of verification passed, official domain is [peuni.cz](https://peuni.cz) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@tatyalien Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@tatyalien You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@tatyalien I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by tatyalien** [comment]
@philipto  I'm sorry, after the merger of the universities, the university stopped offering IT courses, they are just finishing their last studies :(

**Pull request closed without merging**
