### PR TITLE
add Faculdade Senai Fatesg to repo

### PR DESCRIPTION
**Pull request by luizmlpascoal**

### CODE REVIEW

**Comment by philipto** [comment]
@luizmlpascoal First stage of verification passed, official domain is [senaigoias.com.br](https://senaigoias.com.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://senaigoias.com.br/transparencia/#!/sesi/unidades-nos-estados

**Comment by philipto** [comment]
@luizmlpascoal Did you mean fieg.com.br, NOT fieg.com?

In any case please also provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by luizmlpascoal** [comment]
Hello Philipto!
Thanks for your response. Yes, our domain for e-mails are fieg.com.br, mine (for example) currently is luizpascoal.senai@fieg.com.br
Here are the other information requested:
1. Official website: https://senaigoias.com.br/faculdade-fatesg
2. Faculdade Senai Fatesg
Rua 227-A, n° 95, Setor Leste Universitário
CEP 74610-155 - Goiânia-GO
Fone: (62) 3269-1210 
WhatsApp: (62)996528495
e-mail: [fatesg.senai@fieg.com.br]

3. Website for the Software Engineering course: https://senaigoias.com.br/vestibular-engenharia-software

4. In 1. I sent the official website for our university, in the end of the page there is an institutional e-mail, which is [fatesg.senai@fieg.com.br], which is the same domain that i am requesting.

If you have any other doubt, please let me know. I am one of the professors in the Software Engineering course focusing on System Development, and I want to be able to share Students keys for my students, since most of the don't have money to be able to afford on their own. So your help is so much apprettied

Thanks in advance.

**Comment by philipto** [comment]
@luizmlpascoal Thank you for the clarifications and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
