### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by asdirc**
This is old site https://www.pedagogic.ro/istoric-3/ in case that you are redirected to new domain, emails are still on old domain

### CODE REVIEW

**Comment by philipto** [comment]
@asdirc First stage of verification passed, official domain is [pedagogic.ro](https://pedagogic.ro) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@asdirc Please provide us with:
* the school official website URL
* the school street address, including city and country
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by asdirc** [comment]
@philipto if you search on google for liceul pedagogic ploiesti you can find all these official details:
url: https://www.pedagogic.ro/   and in button right you can see the rerefence to the old layout which is on the pedagogigc.ro domain , Title is : [WEBSITE VECHI](https://www.pedagogic.ro/istoric-3/)
Address:
Strada Nicolae Iorga Nr. 7, Ploiești 100537


Phone:
[0244 519 688](tel:+40244519688)
For point 3 i dont know what proof i can give you

**Comment by philipto** [comment]
@asdirc  Thank you for the clarifications. Pull request merged.

**Pull request merged**
