### PR TITLE
Add LO Żyrardów

### PR DESCRIPTION
**Pull request by nnaem**
School website: http://lo.zyrardow.edu.pl
School name: Liceum Ogólnokształcące im. Stefana Żeromskiego w Żyrardowie

### CODE REVIEW

**Comment by philipto** [comment]
@nnaem First stage of verification passed, official domain is [zyrardow.edu.pl](https://zyrardow.edu.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by nnaem** [comment]
> @nnaem First stage of verification passed, official domain is [zyrardow.edu.pl](https://zyrardow.edu.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

@philipto Hey yes, it's the domain of my city and the high school I'm in is the only one being managed by the city, the website of my school I provided was right, however zyrardow.edu.pl is the domain for education stuff like my high school website, Microsoft accounts and so on. Thank you and have a good day

**Comment by philipto** [comment]
@nnaem Pull request merged. Thank you.

**Comment by nnaem** [comment]
> @nnaem Pull request merged. Thank you.

@philipto Hey, when I try to apply for the student benefits with my school email, it says that it's not added, how long does it take to get added?

**Pull request merged**
