### PR TITLE
feat: add Madre Alix college

### PR DESCRIPTION
**Pull request by synterrr**

### CODE REVIEW

**Comment by felixlosada** [comment]
[kcpupils.txt](https://github.com/JetBrains/swot/files/6759181/kcpupils.txt)

**Comment by philipto** [comment]
@synterrr Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@synterrr You might miss my previous comment. Please react.

**Comment by felixlosada** [comment]
@philipto Im sorry for not making it correctly, a friend made it for me https://github.com/JetBrains/swot/pull/11973

**Comment by philipto** [comment]
@synterrr Perfect, thank you. Thus, I close this request and will review just #11973.

**Pull request closed without merging**
