### PR TITLE
Added bgbrgwels email to the repository.

### PR DESCRIPTION
**Pull request by LAUCHGeorge**

### CODE REVIEW

**Comment by philipto** [comment]
@LAUCHGeorge The first verification stage is complete: the official domain for  **BG/BRG Wels Dr. Schauerstraße** is [schauergym.at](https://schauergym.at), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://schauergym.at/

**Comment by LAUCHGeorge** [comment]
That is the correct domain, yes.

**Comment by philipto** [comment]
@LAUCHGeorge The first verification stage is complete: the official domain for  **BG/BRG Wels Dr. Schauerstraße** is [schauergym.at](https://schauergym.at), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://schauergym.at/

**Comment by philipto** [comment]
@LAUCHGeorge Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by LAUCHGeorge** [comment]
Thank you so much.

**Pull request merged**
