### PR TITLE
zsziok

### PR DESCRIPTION
**Pull request by L3CT**

### CODE REVIEW

**Comment by philipto** [comment]
@L3CT First stage of verification passed, official domain is [zsziok.edu.pl](https://zsziok.edu.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@L3CT Please provide us with:
- the school official name
- the school official website URL
- the school street address, including city and country
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by L3CT** [comment]
Should I send it here? Or should i send it somewhere else?

**Comment by philipto** [comment]
@L3CT Please upload them here, as a comment to this request. Please do not send anything by email as attachments. Instead, upload it using your browser at https://github.com/JetBrains/swot/pull/14101

**Comment by philipto** [comment]
@L3CT You might miss my previous comment. Please react.

**Comment by L3CT** [comment]
Hi, i have lot of things now, i will send proofs at the one of week.

**Comment by philipto** [comment]
@L3CT I am sorry, this request remains unanswered for too long. Please reopen it if you have any update. Thank you.

**Pull request closed without merging**
