### PR TITLE
Create orizont.txt

### PR DESCRIPTION
**Pull request by N1cus0r**

### CODE REVIEW

**Comment by philipto** [comment]
@N1cus0r First stage of verification passed, official domain is [orizont.md](https://orizont.md) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by N1cus0r** [comment]
> @N1cus0r First stage of verification passed, official domain is [orizont.md](https://orizont.md) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Hello, is there an update on the review of the pull request ?

**Comment by philipto** [comment]
@N1cus0r Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by N1cus0r** [comment]
> @N1cus0r Thank you for your patience while waiting for a review and processing your request. Pull request merged.

Thank you very much, i appreciate your work !

**Comment by N1cus0r** [comment]
> @N1cus0r Thank you for your patience while waiting for a review and processing your request. Pull request merged.

I am not being able to request my student license !

**Pull request merged**
