### PR TITLE
Create kadikoyanadolulisesi.txt

### PR DESCRIPTION
**Pull request by onderbayraktar**

### CODE REVIEW

**Comment by philipto** [comment]
@onderbayraktar I am sorry, the official domain of the school is kadikoyanadolulisesi.meb.k12.tr, and you ask to add a domain kadikoyanadolulisesi.k12.tr.

If you were correct, please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@onderbayraktar You might miss my previous comment. Please react.

**Comment by onderbayraktar** [comment]
The official email domain for the students is "kadikoyanadolulisesi.k12.tr".

I will ask the administration of the school for a paper in English as a
proof.

I will post the paper whenever I receive it.

Thanks for your attention.

Best regards.

**Comment by philipto** [comment]
@onderbayraktar Thank you!

**Comment by philipto** [comment]
@onderbayraktar I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
