### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by tfppx**

### CODE REVIEW

**Comment by philipto** [comment]
@tfppx Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@tfppx You might miss my previous comment. Please react.

**Comment by tfppx** [comment]
school website:https://www.tfswufe.ac.cn
https://www.tfswufe.edu.cn/zyjs/znkjzyq.htm Undergraduate is 4 years course,Specialist is 3 years course
https://ae01.alicdn.com/kf/UTB898ysNNHEXKJk43Je761eeXXaj.png  screenshot pic address

**Comment by philipto** [comment]
@tfppx Thank you for the clarification. Pull request merged.

**Pull request merged**
