### PR TITLE
Create educastur.txt

### PR DESCRIPTION
**Pull request by ayalgues**
educastur.es is for students and educastur.org for teachers

### CODE REVIEW

**Comment by philipto** [comment]
@ayalgues First stage of verification passed, official domain is [livingasturias.com](https://livingasturias.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://livingasturias.com/learning-spanish-asturias/

**Comment by ayalgues** [comment]
Hi @philipto, thanks for reviwing the PR, just one remark, the official domian is https://www.educastur.es/
It is the web of the Asturias Education Counseling

**Comment by philipto** [comment]
@ayalgues Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by ayalgues** [comment]
Hello Philip, in this web there are a couple of IT courses, both of them
with a duration of two years

https://alojaweb.educastur.es/web/cifplalaboral/informatica-y-comunicaciones

Thank you
María.

**Comment by philipto** [comment]
@ayalgues  Thank you for the clarifications. Pull request merged.

**Comment by ayalgues** [comment]
Thanks to you!

**Pull request merged**
