### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MaxMiddendorp**

### CODE REVIEW

**Comment by MaxMiddendorp** [comment]
this is the contact page of the school with shows the email addresses that they use
https://dewillem.nl/contact

**Comment by philipto** [comment]
@MaxMiddendorp Pull request merged. Thank you!

**Comment by MaxMiddendorp** [comment]
@philipto its not merged yet, is that right?

**Comment by philipto** [comment]
@MaxMiddendorp Thank you for the reminder, it was my mistake. It is now merged.

**Pull request merged**
