### PR TITLE
Add Effat university

### PR DESCRIPTION
**Pull request by AbdallahSabban**
1-https://www.effatuniversity.edu.sa/english/pages/default.aspx 
2-https://www.effatuniversity.edu.sa/english/academics/undergraduate/coe/pages/cs.aspx

### CODE REVIEW

**Comment by philipto** [comment]
@AbdallahSabban The first verification stage is complete: the official domain for  **Effat University** is [www.effatuniversity.edu.sa](https://www.effatuniversity.edu.sa), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.effatuniversity.edu.sa/English/Admissions/Undergraduate/Pages/Tuition_Fees.aspx

**Comment by philipto** [comment]
@AbdallahSabban Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@AbdallahSabban You might miss my previous comment. Please react.

**Comment by AbdallahSabban** [comment]
Hi Philip,

the thing is, all faculty and staff use emails that end with @effatuniversity.edu.sa however all students have @effat.edu.sa.
so the domain that we students use is different.

I'm communicating with the University and searching, I will get you the proof as soon as I can

**Comment by AbdallahSabban** [comment]
here is one from ieeeexplore

https://ieeexplore.ieee.org/abstract/document/9216613/authors#authors

if you scroll and expand the authors, the first author is a student and you can see her email

**Comment by AbdallahSabban** [comment]
@philipto

**Comment by philipto** [comment]
@AbdallahSabban The first verification stage is complete: the official domain for  **Effat University** is [www.effatuniversity.edu.sa](https://www.effatuniversity.edu.sa), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.effatuniversity.edu.sa/English/Admissions/Undergraduate/Pages/Tuition_Fees.aspx

**Comment by philipto** [comment]
@AbdallahSabban Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Comment by AbdallahSabban** [comment]
Thank you very much

**Pull request merged**
