### PR TITLE
Add domain Hanoi University Of Physical Education and Sports

### PR DESCRIPTION
**Pull request by cuongtaquoc**

### CODE REVIEW

**Comment by philipto** [comment]
@cuongtaquoc Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@cuongtaquoc You might miss my previous comment. Please react.

**Comment by cuongtaquoc** [comment]
@philipto https://hupes.edu.vn/danh-muc-tin/khoa-hoc-cong-nghe.html

I would like to submit the school's technology courses and technology studies. If you need a detailed teaching plan, please give me your email address and I will send it via email, because teaching plans cannot be published online.

**Comment by philipto** [comment]
@cuongtaquoc I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
