### PR TITLE
Create uniopet.txt

### PR DESCRIPTION
**Pull request by 86agsilva**

### CODE REVIEW

**Comment by 86agsilva** [comment]
the university web site is: www.uniopet.edu.br

**Comment by philipto** [comment]
@86agsilva First stage of verification passed, official domain is [opet.com.br](https://opet.com.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.opet.com.br/blog/interna/1-ciclo-de-palestras-e-oficinas-de-neurociencia-clinica-uniopet

**Comment by 86agsilva** [comment]
Hello Phillip,

Yes, but the emails are @uniopet.edu.br
If you need some document to show it, just let me know.

Best regards


Em sex., 28 de abr. de 2023 às 00:33, Philip Torchinsky <
***@***.***> escreveu:

**Comment by philipto** [comment]
@86agsilva Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
