### PR TITLE
Added CNITV

### PR DESCRIPTION
**Pull request by tudurom**

### CODE REVIEW

**Comment by philipto** [comment]
@tudurom 
Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by tudurom** [comment]
>the school official website URL, if different from the domain you are submitting

http://portal.lbi.ro/

>an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school

Right on the landing page it says "Specializare Matematica-Informatica" which means maths and computer science specialization, so http://portal.lbi.ro/

>an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students

The school has not publicly announced this address, we have been informed by our class teachers.

**Comment by philipto** [comment]
@tudurom Thank you for the details!
> The school has not publicly announced this address, we have been informed by our class teachers.

Regrettably, anyone can register a domain at onmicrosoft.com. Therefore, we need a proof that the domain `lbiro.onmicrosoft.com` was registered by the school. Could you please ask the teachers to give you a printed copy of a school instruction citing this domain name? Please attach a copy of it to a comment here via **web interface**, do not send it to GitHub by email. 

Thank you.

**Comment by philipto** [comment]
@tudurom I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
