### PR TITLE
add VSUET

### PR DESCRIPTION
**Pull request by RyDVi**
add VSUET

### CODE REVIEW

**Comment by RyDVi** [comment]
add VSUET

**Comment by philipto** [comment]
@RyDVi Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting (**vsuet.vrn.ru**) as an official email domain for the students.

**Comment by philipto** [comment]
@RyDVi You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@RyDVi I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
