### PR TITLE
Create q3academy.txt

### PR DESCRIPTION
**Pull request by AW1534**
https://en.wikipedia.org/wiki/Q3_Academy_Great_Barr
https://www.q3academy.org.uk/

provides education for year 7-11, and also 2 years of further education (sixth form).

### CODE REVIEW

**Comment by philipto** [comment]
@AW1534 First stage of verification passed, official domain is [q3academy.org.uk](https://q3academy.org.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.q3academy.org.uk/studentemail/

**Comment by philipto** [comment]
@AW1534 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by AW1534** [comment]
> @AW1534 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

Thank you for accepting. 

I just tried to apply using my school email and it says "Your email address does not belong to any university that we know."

Is this in error? Or should i wait a while and try again.

**Comment by philipto** [comment]
Yes,Please wait for 30 minutes and try again. Thank you!On 4. Jul 2023, at 21.10, Andrew Wiltshire ***@***.***> wrote:﻿

@AW1534 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

Thank you for accepting.
I just tried to apply using my school email and it says "Your email address does not belong to any university that we know."
Is this in error? Or should i wait a while and try again.

**Pull request merged**
