### PR TITLE
new 

### PR DESCRIPTION
**Pull request by sillyconvicted**

### CODE REVIEW

**Comment by sillyconvicted** [comment]
added a Romanian school

**Comment by philipto** [comment]
@sillyconvicted Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by sillyconvicted** [comment]
thanks for answering,
1. https://www.cni-hd.ro/
2. Romania, Hunedoara, Str. VICTORIEI NR.23
3. not sure what you mean, us in romania most of us do IT courses from grade 5, I attached a photo that proves this school has such courses (can be found on the main page)
4. contact email can be found on the main page, which proves it uses the same domain

lmk if it helps
Screenshot_20241009_163744_Chrome
Screenshot_20241009_164001_Chrome

**Comment by philipto** [comment]
@sillyconvicted Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
