### PR TITLE
Jxshed patch 1

### PR DESCRIPTION
**Pull request by Jxshed**
cccs.edu is already part of the master branch, but new student emails have student.cccs.edu instead of just cccs.edu
although it is mentioned in the readme that sub-domains work with the same upper-level domain, I am still unable to use my student.cccs.edu email

Reformatted from #20769

### CODE REVIEW

**Comment by Jxshed** [comment]
The Community College System
https://www.cccs.edu/about-cccs/cccs-colleges/
IT Programs they cover
https://www.cccs.edu/explore-college-programs/programs/information-technology/
The specific college being added (though they all use the same domain)
https://cccs.edu/college/front-range-community-college/

**Comment by philipto** [comment]
@Jxshed lib/domains/edu/cccs/student: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Jxshed** [comment]
reformatted

**Comment by Jxshed** [comment]
fixed, reformatted @philipto

**Comment by philipto** [comment]
@Jxshed I am sorry, `cccs.edu` and all its subdomains are now in the stoplist.
It means that the domain has been severely abused in the past. **I am removing the domain from stoplist today, and you can try applying for the license in an hour.**

Pull request merged.

However if we detect any further abuse of the domain such as using it by unauthorized third parties, we'll have to ban it again.

**Pull request merged**
