### PR TITLE
Add mum.edu.pl

### PR DESCRIPTION
**Pull request by BuniiAnastasiia**

### CODE REVIEW

**Comment by philipto** [comment]
@BuniiAnastasiia The first verification stage is complete: the official domain for  **Warszawska Akademia Medyczna Nauk Stosowanych** is [wam.edu.pl](https://wam.edu.pl), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://wam.edu.pl/

**Comment by BuniiAnastasiia** [comment]
> @BuniiAnastasiia The first verification stage is complete: the official domain for **Warszawska Akademia Medyczna Nauk Stosowanych** is [wam.edu.pl](https://wam.edu.pl), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://wam.edu.pl/

Yes, you are right. The school changed name and domain a few years ago but student emails were not migrated to new domain, there is only redirect from old website (https://mum.edu.pl) to new one.

**Comment by philipto** [comment]
@BuniiAnastasiia The first verification stage is complete: the official domain for  **Warszawska Akademia Medyczna Nauk Stosowanych** is [wam.edu.pl](https://wam.edu.pl), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://wam.edu.pl/

**Comment by philipto** [comment]
@BuniiAnastasiia Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
