### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by moukh-tari**
Added my school "L’école supérieure d’Ingénierie et de Management".

### CODE REVIEW

**Comment by philipto** [comment]
@moukh-tari Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@moukh-tari You might miss my previous comment. Please react.

**Comment by moukh-tari** [comment]
- the school official website URL

                 https://iga.ac.ma

   - the school street address, including city and country

   279 Bd Bir Anzarane, Casablanca Maroc.

   - an URL of a page on the official website where the school offers an
   IT-related long-term (>1 year) course

   https://iga.ac.ma/ingenierie/licencesmasters

**Comment by moukh-tari** [comment]
- a proof, which shows that the school recognizes the domain you are
   submitting as an official email domain for the students.

   ***@***.***

**Comment by moukh-tari** [comment]
am really sorry for the late response

**Comment by philipto** [comment]
@moukh-tari Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
