### PR TITLE
Create unizkm

### PR DESCRIPTION
**Pull request by kgorica**

### CODE REVIEW

**Comment by philipto** [comment]
@kgorica Please rename lib/domains/al/unizkm to lib/domains/al/unizkm.txt

**Comment by philipto** [comment]
@kgorica You might miss my previous comment. Please react.

**Comment by kgorica** [comment]
@philipto Thanks! Sorry for the late reply. Committed.

**Comment by philipto** [comment]
@kgorica Pull request merged. Thank you!

**Pull request merged**
