### PR TITLE
Added domain for Box Elder School District

### PR DESCRIPTION
**Pull request by Pi-way**
the university official website URL, if it is different from the domain you are submitting:

https://www.besd.net/

a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university:

https://www.besd.net/page/cte-pathways#:~:text=Programming%20and%20Software%20Development

a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.

Here's one: https://www.besd.net/page/report-a-concern#:~:text=Email%3A%20audit%40besd.net

### CODE REVIEW

**Comment by Pi-way** [comment]
I have been searching in https://www.besd.net/documents for a document showing that the [school district] recognizes the domain that I'm submitting... Haven't found anything explicitly saying this, but If it's anywhere, it is probably in there.

**Comment by Pi-way** [comment]
Not explicit... but Here's something:

https://www.besd.net/page/human-resources#:~:text=Email%3A%20mark.taylor%40besd.net

**Comment by philipto** [comment]
@Pi-way First stage of verification passed, official domain is [besd.net](https://besd.net) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Pi-way Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by Pi-way** [comment]
Thank y'all for making awesome software.

**Pull request merged**
