### PR TITLE
Added  my school, I.I.S. "Galilei-Vetrone"

### PR DESCRIPTION
**Pull request by nick747**
I attend an IT course at this school. The website is iisgalileivetrone.edu.it

### CODE REVIEW

**Comment by philipto** [comment]
@nick747 lib/domains/it/iisgalileivetrone.edu.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by nick747** [comment]
@philipto I requested yesterday with the name iisgalileivetrone.it but got refused because iisgalileivetrone.it doesn't exist, and I know that. I retried adding ".edu" which is in my school website but obviously you can't accept it.

I will try again without ".edu", the school website is iisgalileivetrone.edu.it .

Thanks

**Comment by nick747** [comment]
@philipto renamed. Check if this works. The school website is [this](https://iisgalileivetrone.edu.it/)

**Comment by nick747** [comment]
found error in the path, I've moved my file in it/edu because of _.edu_ . It should all be good now

**Comment by philipto** [comment]
@nick747 First stage of verification passed, official domain is [iisgalileivetrone.edu.it](https://iisgalileivetrone.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@nick747 Pull request merged. Thank you.

**Pull request merged**
