### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ProfCasellato**
IT High School in Turin. Site: https://www.istitutoprimolevi.edu.it/

### CODE REVIEW

**Comment by philipto** [comment]
@ProfCasellato The first verification stage is complete: the official domain for  **IIS Primo Levi** is [www.istitutoprimolevi.edu.it](https://www.istitutoprimolevi.edu.it), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.istitutoprimolevi.edu.it/info-generali/direttore-dei-servizi-generali-e-amministrativi-dsga/

**Comment by ProfCasellato** [comment]
Good morning.
I'm Happy to hear you.
For every question, I'm here.

Prof. Casellato Fabrizio

Il Mer 27 Mar 2024, 05:33 Philip Torchinsky ***@***.***> ha
scritto:

**Comment by philipto** [comment]
@ProfCasellato The first verification stage is complete: the official domain for  **IIS Primo Levi** is [www.istitutoprimolevi.edu.it](https://www.istitutoprimolevi.edu.it), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.istitutoprimolevi.edu.it/info-generali/direttore-dei-servizi-generali-e-amministrativi-dsga/

**Comment by philipto** [comment]
@ProfCasellato Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
