### PR TITLE
Added The Indian Public School

### PR DESCRIPTION
**Pull request by srivatsav-kannan**

### CODE REVIEW

**Comment by philipto** [comment]
@srivatsav-kannan The first verification stage is complete: the official domain for  **The Indian Public School** is [tipschennai.com](https://tipschennai.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://tipschennai.com/contact-us/

**Comment by srivatsav-kannan** [comment]
> @srivatsav-kannan The first verification stage is complete: the official domain for **The Indian Public School** is [tipschennai.com](https://tipschennai.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://tipschennai.com/contact-us/

That is the domain, however emails end with @tipsglobal.net

**Comment by philipto** [comment]
@srivatsav-kannan The first verification stage is complete: the official domain for  **The Indian Public School** is [tipschennai.com](https://tipschennai.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://tipschennai.com/contact-us/

**Comment by philipto** [comment]
@srivatsav-kannan Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
