### PR TITLE
File Subject | School

### PR DESCRIPTION
**Pull request by NiekMSoftware**

### CODE REVIEW

**Comment by philipto** [comment]
@NiekMSoftware file/lib/domains/com/meletstudios.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@NiekMSoftware Please provide us with:
* the school official website URL
* the school full official name (in original language, and in English, if possible)
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by NiekMSoftware** [comment]
Within the repository or just in here as a comment?
Apologies I haven't changed the file path yet, didn't had my laptop with me for the past weeks.

**Comment by philipto** [comment]
@NiekMSoftware No problem, I changed the file path, it's OK now. Please comment here and in the comment please provide us with:
* the school official website URL
* the school full official name (in original language, and in English, if possible)
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you!

**Comment by NiekMSoftware** [comment]
Here is the website:
https://noorderpoort.nl/voor-studenten/opleidingen/software-developer-games-bol#:~:text=Je%20volgt%20een%20programma%20met,of%20implementeert%20in%20andermans%20code.

Full official name:
Noorderpoort, Software Development Games

School address:
Muntinglaan 3, Groningen, the Netherlands.

Proof for domain:
nmelet@st.noorderpoort.nl

**Comment by philipto** [comment]
@NiekMSoftware Thank you! Everything is fine but the proof.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by NiekMSoftware** [comment]
I think this image would be enough? We use these cards for equipment. Can't really find any other documentation of the domain usages.

**Comment by philipto** [comment]
@NiekMSoftware Thank you! It would work well, but the domain that you request to add is `meletstudios.com`. It is not mentioned anywhere at the school's website or your badge. Why do you wish to add it to the trusted list?

**Comment by NiekMSoftware** [comment]
This is correct, the issue was that I subscribed to your AI assistant with the wrong account. Therefore I wanted to make my domain trusted with the school domain. Is that even possible?

**Comment by philipto** [comment]
@NiekMSoftware Thank you for your response. I am really puzzled now. Would you please send me a message to community-support@jetbrains.com and explain what is your school's email address that you need to be added to the trusted list, and what is `meletstudios.com`, and also what is incorrect with your JetBrains account?

As for this pull request here, I have to close it without merging. As soon as we discuss all the matters by email, I certainly correct your accounts settings and make sure you can get a free educational subscription to JetBrains tools (excluding JetBrains AI, which is a paid feature) as a student.

**Pull request closed without merging**
