### PR TITLE
Create stud.hfwu.txt

### PR DESCRIPTION
**Pull request by knollraf**

### CODE REVIEW

**Comment by knollraf** [comment]
I see my mistake now - The university has only IT-related programs in the seconde place and not at first ...

**Comment by philipto** [comment]
@knollraf There is another problem. If students in Nuertingen-Geislingen University have e-mail like @stud.hfwu.de, you need to submit a file lib/domains/de/hfwu/stud.txt, and there should be one line in the file:
Hochschule für Wirtschaft und Umwelt Nürtingen-Geislingen

However, if students can have e-mail from other subdomains of hfwu.de, or email in the domain @hfwu.de itself, you'd better make a pull request for the file lib/domains/de/hfwu.txt with the same content instead.

Please, make the appropriate change to the pull request.

**Comment by knollraf** [comment]
OK I renamed the 'stud.hfwu.txt' to 'htwu.txt' with the same content like you wrote in your second suggestion.

**Comment by philipto** [comment]
@knollraf Thank you! Email domain hfwu.de is now in the repository, your pull request merged.

**Comment by knollraf** [comment]
Thank you for merging.
 And thank you for your fast replies.

**Pull request merged**
