### PR TITLE
Add PDP UNIVERSITY

### PR DESCRIPTION
**Pull request by samandareo**
Hello, I am Samandar(Sam). I am currently studying at PDP University. It is located in Tashkent, Uzbekistan. PDP University is a university fully adapted to the IT field. So, I added my university above the repo and hope you accept it.

### CODE REVIEW

**Comment by philipto** [comment]
@samandareo First stage of verification passed, official domain is [instagram.com](https://instagram.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.instagram.com/pdp.university/

**Comment by samandareo** [comment]
@philipto Hello there! Understandable,  Thank you very much)

**Comment by philipto** [comment]
@samandareo This is a duplicated issue. Therefore, I have to ask you to answer the question that was not answered in your original request:

I found enough evidence of eligibility of **pdp.uz** domain, but not **pdp.university** domain.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by samandareo** [comment]
@philipto I will send documents

**Comment by samandareo** [comment]
@philipto Hello, Can I send picture of my id card?

**Comment by samandareo** [comment]
Hello @philipto . I sent my ID card. But I don't recieve response

**Comment by philipto** [comment]
@samandareo Thank you for the confirmation and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
