### PR TITLE
Create inscaparrella

### PR DESCRIPTION
**Pull request by davidhub4**

### CODE REVIEW

**Comment by davidhub4** [comment]
Site: http://iescaparrella.cat/
IT Course: http://iescaparrella.cat/ca/educacio/iescaparrella/cfgs-desenvolupament-daplicacions-web-dual/r-88186
The domain is: @inscaparrella.cat

**Comment by philipto** [comment]
@davidhub4 lib/domains/cat/inscaparrella: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by davidhub4** [comment]
I rename inscaparrella to inscaparrella.txt Is now correct?

**Comment by philipto** [comment]
@davidhub4 Yes, you edited the request correctly. Could you please also provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by davidhub4** [comment]
@philipto I attach the link with my student email and the corporate email at official web
URL Student : https://postimg.cc/nsKWQRyc
URL Official : https://postimg.cc/FkGmgFwz

**Comment by philipto** [comment]
Dear @davidhub4,

Thank you for the clarification. I found out that:
1) According your LinkedIn, you graduated from this school in May 2022, and therefore you are not eligible for free educational license for JetBrains tools.
2) The domain inscaparrella.cat WHOIS data are incomplete, and the domain might be registered to a private person, not to the school.
3) The domain inscaparrella.cat is not mentioned anywhere at the  school's official website.

I have to close your request without merging. If you are still a student of this school, please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Pull request closed without merging**
