### PR TITLE
Create austin.utexas.txt

### PR DESCRIPTION
**Pull request by piggjf**
The austin subdomain is restricted to current students and employees at the University of Texas at Austin.  Hopefully, this will allow you to unblock the university.

This flyer talks about it:  https://office365.utexas.edu/sites/default/files/Student%20Email%20%40%20UT.pdf
This knowledge base post gives additional details:  https://ut.service-now.com/sp?id=kb_article&number=KB0013944

### CODE REVIEW

**Comment by philipto** [comment]
@piggjf lib/domains/edu/austin.utexas.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by piggjf** [comment]
@philipto I think this is the proper format now.

**Comment by philipto** [comment]
@piggjf I am sorry, the domain utexas.edu is removed from our trusted domains list because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Comment by piggjf** [comment]
But the subdomain is restricted to current students and faculty as outlined in the documents shared. Is it not possible to allow list the specific subdomain while blocking the rest of the domain? Surely that would be more favorable than manually approving hundreds of applications?

**Pull request closed without merging**
