### PR TITLE
added Max Planck School of Cognition

### PR DESCRIPTION
**Pull request by oliver-contier**
email domain @maxplanckschools.de. Find info on the program [here](https://www.maxplanckschools.de/en/cognition).

### CODE REVIEW

**Comment by philipto** [comment]
@oliver-contier Could you please clarify why the school needs to add the domain to the list of schools domains known to JetBrains? As far as I can see, the school is a kind of umbrella institution, which is a cooperation platform for many reputable universities that already are in our list of known institutions.

Who are the students and the teachers of this school, who cannot get a free JetBrains educational license via their alma-mater? Do you have some of the students who are not students of other universities?

**Comment by oliver-contier** [comment]
Of course! 

The Max Planck School of Cognition is a structured PhD program that indeed involves several research institutes and universities in Germany. The first year of the school however consists of lab rotations and e-learning courses. During this first year, the students are not enrolled at a specific university or official members of an institute yet and hence cannot use the respective institutional access. 

Scientific programming (e.g. in python) is part of several of the e-learning courses (more specifically: Methods in Cognitive Neuroscience, Statistics, and Artificial Intelligence). The tasks we have to solve in the lab rotations also very often involve programming. Also, we quite often have to deploy our code on computing clusters, which is where the advanced features of PyCharm come in very handy in my experience.

You can find the contact info of people involved in coordination of lab rotations and e-learning [here](https://www.maxplanckschools.de/en/schools/cognition/people).

**Comment by philipto** [comment]
@oliver-contier Thank you very much for the details and the clarification! Pull request merged.

**Comment by oliver-contier** [comment]
Thank you!

**Pull request merged**
