### PR TITLE
Create orif.txt

### PR DESCRIPTION
**Pull request by namaio**

### CODE REVIEW

**Comment by philipto** [comment]
@namaio Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school. Thank you!

**Comment by namaio** [comment]
Our URL:

https://www.orif.ch/fr/prestations/toutes-nos-prestations/.

Our role is to help apprentices graduate from vocational school and integrate them into the professional world.

If you look at the formations list, you will find among them the CFC computer scientist.

Thank you in advance

**Comment by philipto** [comment]
@namaio I am sorry, I cannot understand your educational model as of now. If you help students who attend other schools to integrate better to the industry, why do the students need an email address in orif.ch domain? They have to have their respective vocational schools email addresses, haven't they? 

Also, I saw on your website that the students spend 3-4 days per week working in companies, and it's a good educational model. The issue is that it may contradict with educational license terms: if the students use JetBrains tools for their work, not just education, they are not eligible for using the tools with educational licenses. I understand that the work can be a part of education, but we'd better avoid situations when an employer fails to provide their employees with an appropriate license because the employees have student licenses. 

Please clarify the issue. Thank you!

**Comment by philipto** [comment]
@namaio The clarification was given by a student of the school to community-support@jetbrains.com. Thank you for the info. Pull request merged.

**Pull request merged**
