### PR TITLE
Create didatec.txt

### PR DESCRIPTION
**Pull request by elizad**
UTC
TECHNICAL UNIVERSITY CLUJ

### CODE REVIEW

**Comment by philipto** [comment]
@elizad Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by elizad** [comment]
https://www.utcluj.ro/  
https://www.utcluj.ro/en/university/education/
and didatec.onmicrosoft.com is UTC microsoft UNI domain

**Comment by philipto** [comment]
@elizad Thank you for the details! Please attach a copy of an official document from the university, which confirms that didatec.onmicrosoft.com is UTC microsoft UNI domain. It can be a copy of email or printed instruction that you have received from the university administration. Regrettably, the official website does not have any information about this domain.

**Comment by elizad** [comment]
is an other domain registered student.utcluj.ro

**Comment by philipto** [comment]
@elizad Yes, both student.utcluj.ro and utcluj.didatec.ro are registered in SWOT already. However, we need a proof, which confirms that didatec.onmicrosoft.com is UTC microsoft UNI domain to add didatec.onmicrosoft.com. Please provide the proof or close the request.

**Comment by philipto** [comment]
@elizad I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. 

You also can send an email with more details regarding the issue to community-support@jetbrains.com.

Thank you for the understanding!

**Pull request closed without merging**
