### PR TITLE
add kosen college

### PR DESCRIPTION
**Pull request by ckinako**
#### Institution/School Name 
National Institute of Technology, Ashahikawa College

#### Instiution/School Website
http://www.asahikawa-nct.ac.jp/en/

#### Email Users

*Please place an x between the square brackets if yes*
- [x] Students
- [x] Academic/Teaching Staff
- [x] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [ ] Graduate School
- [x] College (University) or Undergraduate School or equivalent
- [x] Community College or equivalent
- [x] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by philipto** [comment]
@ckinako Please provide us with a proof which shows that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by ckinako** [comment]
Sorry.I'm Japanese student ,so I can't write English well.But I try it. These screenshot are  Ashahikawa College official website and whois infomation .Can it be  proof ?
kosen
whois

**Comment by philipto** [comment]
@ckinako I am sorry, there is a little misunderstanding. The screenshots which you attached show that the domain of the school is asahikawa-nct.ac.jp. If you would have similar screenshots for asahikawa.kosen-ac.jp, it is enough to add asahikawa.kosen-ac.jp to this repository.

Your request shows that you wish to add a domain asahikawa.kosen-ac.jp. It means that students of your school use email addresses such as username@asahikawa.kosen-ac.jp. I need to have a proof, which shows that the school recognizes asahikawa.kosen-ac.jp as an official email domain for the school's students. 

Do you have any proof that the school assigns email addresses such as username@asahikawa.kosen-ac.jp to the students?

**Comment by ckinako** [comment]
I'm sorry.I I misunderstood the domain between asahikawa.kosen-ac.jp  and asahikawa.kosen-ac.jp ,so I want to withdraw pull request.

**Pull request closed without merging**
