### PR TITLE
Create al.txt

### PR DESCRIPTION
**Pull request by isantolin**
Added Faculdade Casper Libero

### CODE REVIEW

**Comment by philipto** [comment]
@isantolin First stage of verification passed, official domain is [casperlibero.edu.br](https://casperlibero.edu.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@isantolin Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by isantolin** [comment]
@philipto 

https://casperlibero.edu.br/graduacao/cursos/publicidade-e-propaganda/

https://casperlibero.edu.br/graduacao/cursos/jornalismo/

https://casperlibero.edu.br/graduacao/cursos/radio-tv-e-internet/

https://casperlibero.edu.br/graduacao/cursos/relacoes-publicas/

**Comment by isantolin** [comment]
I Studying Advertising, but we have many subjects related to Data Analisys, Business Intelligence, Analytics, Statistics and Python programming (Take a look on Program Structure) 


Screenshot from 2022-12-19 10-35-38
Screenshot from 2022-12-19 10-36-18
Screenshot from 2022-12-19 10-36-00

**Comment by philipto** [comment]
@isantolin  Thank you for the clarifications. Pull request merged.

**Pull request merged**
