### PR TITLE
Added Ibn Haldun University

### PR DESCRIPTION
**Pull request by alikadir**

### CODE REVIEW

**Comment by WDev665** [comment]
[school23lutsk.txt](https://github.com/JetBrains/swot/files/6870574/school23lutsk.txt)

**Comment by philipto** [comment]
@alikadir Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.


@WDev665 Please submit a separate pull request. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting a request.

**Comment by philipto** [comment]
@alikadir You might miss my previous comment. Please react.

**Comment by alikadir** [comment]
@philipto 
Official web site address is https://www.ihu.edu.tr and student e-mail domain is @ibnhaldun.edu.tr.

for more information about the student e-mail domain you can see the Information Services topic on following page
https://oidb.ihu.edu.tr/en/registration-guide/undergraduate-programs-registration-guide/

**Comment by philipto** [comment]
@alikadir Thank you for the clarification. Pull request merged.

**Pull request merged**
