### PR TITLE
Add jerichoapps.org

### PR DESCRIPTION
**Pull request by hundredbottlesojuice**
Domain for [Jericho High School](http://hs.jerichoschools.org/). 

Offers three programming-related courses, listed [here](http://hs.jerichoschools.org/academics/mathematics_16-17)

Includes
 - Introduction to Computer Science
 - Advanced Placement Computer Science A
 - Advanced Computer Programming

### CODE REVIEW

**Comment by philipto** [comment]
@hundredbottlesojuice Unfortunately, I can not access the website.
image

**Comment by hundredbottlesojuice** [comment]
Ah, shoot. Is there anything that can be done?

**Comment by hundredbottlesojuice** [comment]
If you can't view the website, have you tried to view it with an archiving service to get around the block? It seems like your issue should be taken up with your IT admins.

Here's some links
[Home 1](https://archive.is/Pt931)
[Home 2](https://web.archive.org/web/20160304204504/http://hs.jerichoschools.org/)
[Courses 1](https://archive.is/dUAbX#58%)
[Courses 2](https://web.archive.org/web/20160421085837/http://hs.jerichoschools.org/academics/mathematics_16-17/)

**Comment by philipto** [comment]
@hundredbottlesojuice Well, now I can see it. Unfortunately, I can not trace the problem back and see which administrator has blocked the content at that time. It could be a problem on our side, but given that other websites were accessible, I thought that the problem is on your side. 

Anyway, the problem is resolved, and I am merging the pull request. Sorry for the inconvenience.

**Comment by hundredbottlesojuice** [comment]
Great, thanks!

**Pull request merged**
