### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by tkhelfiki**
The Knowledge Hub Universities

### CODE REVIEW

**Comment by tkhelfiki** [comment]
www.tkh.edu.eg

**Comment by tkhelfiki** [comment]
https://tkh.edu.eg/programmes/coventry-computer-science/

**Comment by malikwaqar009** [comment]
[file.zip](https://github.com/JetBrains/swot/files/13690439/file.zip)
please verify my university email.

**Comment by philipto** [comment]
@tkhelfiki First stage of verification passed, official domain is [tkh.edu.eg](https://tkh.edu.eg) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@tkhelfiki Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
