### PR TITLE
add my school

### PR DESCRIPTION
**Pull request by Gage-Morgan**
add CTU to the list of schools

### CODE REVIEW

**Comment by AnthonyMLewis** [comment]
[acad.txt](https://github.com/user-attachments/files/16489745/acad.txt)

**Comment by philipto** [comment]
@Gage-Morgan Thank you for your patience while waiting for a review and processing your request. Pull request merged. Please start applying for JetBrains educational subscription at https://www.jetbrains.com/shop/eform/students **in an hour, to allow the changes to propagate through JetBrains systems**.

**Comment by adigitalmindllc** [comment]
Will do as soon as I get off of work, thank you

**Comment by AnthonyMLewis** [comment]
the system is still telling me the same thing, my school is not listed

**Pull request merged**
