### PR TITLE
Create lakelandcollege.txt

### PR DESCRIPTION
**Pull request by dmason59**
Adding my community college to the repo ability to use SmartGit.

### CODE REVIEW

**Comment by philipto** [comment]
@dmason59 First stage of verification passed, official domain is [lakelandcollege.edu](https://lakelandcollege.edu) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by dmason59** [comment]
Thank you @philipto!

**Comment by philipto** [comment]
@dmason59 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by dmason59** [comment]
Thanks again! :)

**Pull request merged**
