### PR TITLE
Create mybac.txt

### PR DESCRIPTION
**Pull request by the-mastermind**
This adds Botswana Accountancy College mybac.ac.bw students email domain to the repository

### CODE REVIEW

**Comment by philipto** [comment]
@the-mastermind Could you please provide us with:

- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by the-mastermind** [comment]
Good day Philip

xxxxx-xxx@mybac.ac.bw<mailto:xxxxx-xxx@mybac.ac.bw> is the email format for Botswana Accountancy College students, staff’s email address format is xxxxxxxx@bac.ac.bw<mailto:xxxxxxxx@bac.ac.bw> and the staff email domain has already been added, we are therefore trying to add students emails.

Students can only use this email when they are still studying, after their final year students’ domain user account get disabled together with the email.


The URL for the official website of the college is www.bac.ac.bw<http://www.bac.ac.bw/>

School of Computing and information Systems offers several four year degree courses in which students are taught programming and database administration
This is a link to one of our four year degree - Computer Systems Engineering in which we have partnered with University of Sunderland, UK.

http://www.bac.ac.bw/bsc-hons-computer-systems-engineering

This is a link to another of our four year degree - Mobile Technologies

http://www.bac.ac.bw/bsc-hons-mobile-technologies



To verify that mybac.ac.bw domain is owned by bac.ac.bw please visit https://www.whois.net and enter www.mybac.ac.bw<http://www.mybac.ac.bw>, the registrant name and email are the same for both bac.ac.bw and mybac.ac.bw, Please don’t hesitate to contact the gentleman in the given contact numbers to verify the information above, he is the college network administrator.


Regards

Sylvester Mokgwe
School of Computing and Information Systems
Botswana Accountancy College
Private Bag 00319
Gaborone Botswana
Tel: (+267)3953062  Ext: 1626
Email: sylvesterm@bac.ac.bw<mailto:sylvesterm@bac.ac.bw>
From my Mac Book Pro i7

On 15 Mar 2017, at 1:53 PM, Philip Torchinsky <notifications@github.com<mailto:notifications@github.com>> wrote:


@the-mastermind<https://github.com/the-mastermind> Could you please provide us with:

  *   the university official website URL, if different from the domain you are submitting
  *   an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
  *   an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by the-mastermind** [comment]
Good day Philip

You can also find information explaining to students on how to access their mybac.ac.bw email in Botswana Accountancy College website at this page http://www.bac.ac.bw/ict-services


Regards

Sylvester Mokgwe
School of Computing and Information Systems
Botswana Accountancy College
Private Bag 00319
Gaborone Botswana
Tel: (+267)3953062  Ext: 1626
Email: sylvesterm@bac.ac.bw<mailto:sylvesterm@bac.ac.bw>
From my Mac Book Pro i7

On 16 Mar 2017, at 8:41 PM, Sylvester Mokgwe <sylvesterm@bac.ac.bw<mailto:sylvesterm@bac.ac.bw>> wrote:

Good day Philip

xxxxx-xxx@mybac.ac.bw<mailto:xxxxx-xxx@mybac.ac.bw> is the email format for Botswana Accountancy College students, staff’s email address format is xxxxxxxx@bac.ac.bw<mailto:xxxxxxxx@bac.ac.bw> and the staff email domain has already been added, we are therefore trying to add students emails.

Students can only use this email when they are still studying, after their final year students’ domain user account get disabled together with the email.


The URL for the official website of the college is www.bac.ac.bw<http://www.bac.ac.bw/>

School of Computing and information Systems offers several four year degree courses in which students are taught programming and database administration
This is a link to one of our four year degree - Computer Systems Engineering in which we have partnered with University of Sunderland, UK.

http://www.bac.ac.bw/bsc-hons-computer-systems-engineering

This is a link to another of our four year degree - Mobile Technologies

http://www.bac.ac.bw/bsc-hons-mobile-technologies



To verify that mybac.ac.bw domain is owned by bac.ac.bw please visit https://www.whois.net<https://www.whois.net/> and enter www.mybac.ac.bw<http://www.mybac.ac.bw/>, the registrant name and email are the same for both bac.ac.bw and mybac.ac.bw, Please don’t hesitate to contact the gentleman in the given contact numbers to verify the information above, he is the college network administrator.


Regards

Sylvester Mokgwe
School of Computing and Information Systems
Botswana Accountancy College
Private Bag 00319
Gaborone Botswana
Tel: (+267)3953062  Ext: 1626
Email: sylvesterm@bac.ac.bw<mailto:sylvesterm@bac.ac.bw>
From my Mac Book Pro i7

On 15 Mar 2017, at 1:53 PM, Philip Torchinsky <notifications@github.com<mailto:notifications@github.com>> wrote:


@the-mastermind<https://github.com/the-mastermind> Could you please provide us with:

  *   the university official website URL, if different from the domain you are submitting
  *   an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
  *   an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@the-mastermind Thank you very much for the detailed clarification! Pull request is now merged.

**Comment by the-mastermind** [comment]
Much appreciated Phillip


Regards

Sylvester Mokgwe
School of Computing and Information Systems
Botswana Accountancy College
Private Bag 00319
Gaborone Botswana
Tel: (+267)3953062  Ext: 1626
Email: sylvesterm@bac.ac.bw<mailto:sylvesterm@bac.ac.bw>
From my Mac Book Pro i7

On 17 Mar 2017, at 5:17 PM, Philip Torchinsky <notifications@github.com<mailto:notifications@github.com>> wrote:


@the-mastermind<https://github.com/the-mastermind> Thank you very much for the detailed clarification! Pull request is now merged.

**Pull request merged**
