### PR TITLE
add domain mercatorum.it

### PR DESCRIPTION
**Pull request by nbattista89**
University Mercatorum Italy.

### CODE REVIEW

**Comment by philipto** [comment]
@nbattista89 First stage of verification passed, official domain is [unimercatorum.it](https://unimercatorum.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@nbattista89 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by nbattista89** [comment]
Hi,
Below all informations that you need:

https://www.unimercatorum.it/
Piazza Mattei, 10, 00186 Rome RM Italy

Link of courses of degree (three or five years) :
https://www.unimercatorum.it/corsi-di-laurea

My course of degree (Big data) :
https://www.unimercatorum.it/corsi-di-laurea/statistica-e-big-data

My email of student university: ***@***.***

Thanks,
Best regards
Nicola Battista



Il Gio 16 Feb 2023, 21:51 Philip Torchinsky ***@***.***> ha
scritto:

**Comment by philipto** [comment]
@nbattista89 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
