### PR TITLE
Add HCMC University of Food Industry in Viet Nam

### PR DESCRIPTION
**Pull request by nguyenquangsang160596**
#### Institution/School Name 
HCMC University of Food Industry

#### Instiution/School Website
https://hufi.edu.vn
#### IT related-website
http://www.ittc.edu.vn
https://its.hufi.edu.vn
http://fit.hufi.edu.vn

#### Email Users
2001140213@ittc.edu.vn

*Please place an x between the square brackets if yes*
- [x] Students
- [ ] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [x] Graduate School
- [x] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [x] High School or equivalent
- [ ] Elementary School or equivalent

[ittc.zip](https://github.com/JetBrains/swot/files/5393335/ittc.zip)

### CODE REVIEW

**Comment by philipto** [comment]
@nguyenquangsang160596 Could you please clarify what is the relationship between HCMC University of Food Industry and ITTC? Is ITTC a part of the university?

**Comment by nguyenquangsang160596** [comment]
Screen Shot 2020-10-21 at 15 12 54
Screen Shot 2020-10-21 at 15 16 11

Hi Philip,

Footer of this site is address and faculty of the university. Is that OK? If you need any more information, please let me know.

Thanks

**Comment by philipto** [comment]
@nguyenquangsang160596 Thank you! Yes, I saw the footer, I just don't understand what is the relation between the two organizations. Is ITTC a part of the university? Is it a faculty, a department of the university? Or is it a separate organization, such as a training center, which is located in the same building where the Faculty of Information technology is located?

**Comment by nguyenquangsang160596** [comment]
Oh, I see

ITTC is an IT faculty of the HCMC University of Food Industry. I study Information Technology at here, and I'm provided the email with extension @ittc.edu.vn with my student ID: 2001140213. So shall I verify more information with you?

Thanks a lot, Philip.

**Comment by philipto** [comment]
@nguyenquangsang160596 Thank you very much for the clarification. Pull request merged. Please wait a bit before requesting the free license, it takes about 30 minutes for the changes to propagate.

**Comment by nguyenquangsang160596** [comment]
Thank you very much for your support, Philip. Have a nice day!

**Pull request merged**
