### PR TITLE
Add Nile Uiversity

### PR DESCRIPTION
**Pull request by Mohamed243**
The university official website URL : https://nu.edu.eg/
Long-term (>1 year) IT related course is offered by the university: https://nu.edu.eg/graduate-programs/

### CODE REVIEW

**Comment by Mohamed243** [comment]
Capture

**Comment by philipto** [comment]
@Mohamed243 nu.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Mohamed243 I renamed the file for you to have it correctly named. Pull request merged. Thank you!

**Comment by Mohamed243** [comment]
@philipto | I received my educational license. I couldn't have done it without you. I appreciate you time and support.

**Pull request merged**
