### PR TITLE
Add Diocese of Broken Bay

### PR DESCRIPTION
**Pull request by homemadestea58**

### CODE REVIEW

**Comment by homemadestea58** [comment]
Please review ASAP.

**Comment by philipto** [comment]
@homemadestea58 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by homemadestea58** [comment]
@philipto I am happy to provide those, but I was wondering, why do I have to validate my school again? I could use it the last time that I activated my GitHub Student Pack, but this time it isn't working.

**Comment by philipto** [comment]
@homemadestea58 You can try and authenticate at https://www.jetbrains.com/shop/eform/students with GitHub, if you have GitHub Student Pack. Just try "GitHub"tab there. If GitHub does not authenticate you, feel free to check what happens with GitHub support.

Both GitHub and JetBrains may introduce some specific measures with regard to free licenses because there are a log of frauds in the world who pretend to be students without actually being the students. Thus, there are some protective measures that might affect your experience.

If you need more assistance, please send an email to community-support@jetbrains.com. Thank you!

**Comment by philipto** [comment]
@homemadestea58 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
