### PR TITLE
Adding Universidad de Matanzas

### PR DESCRIPTION
**Pull request by cuza**
Adding Universidad de Matanzas from Cuba

### CODE REVIEW

**Comment by Jcmaty** [comment]
njucm.edu.cn

**Comment by Jcmaty** [comment]
you should  add  njucm.edu.cn ,thanks.

**Comment by philipto** [comment]
@Jcmaty for adding njucm.edu.cn please create a separate pull request. If you have an email address ening with @njucm.edu.cn you can request a free license at https://www.jetbrains.com/shop/eform/students now.

**Comment by santiagoalmeidabolannos** [comment]
there is a particular reason why this does not get merged?

**Comment by andygonzalez2010** [comment]
Why this pull request isn't approved?

**Comment by santiagoalmeidabolannos** [comment]
@philipto can you help?

**Comment by ste7e0** [comment]
please can anyone aprove this pull request??

**Comment by 3nriqu390** [comment]
why is this pull not approved??

**Comment by AlejandroYanes** [comment]
hi @philipto, can you review this PR and merge it? or tell us what's wrong?

**Pull request closed without merging**
