### PR TITLE
Add Roslyn Schools

### PR DESCRIPTION
**Pull request by wilburcoding**

### CODE REVIEW

**Comment by wilburcoding** [comment]
Didn't read README whoops

**Comment by wilburcoding** [comment]
School website: https://roslynschools.org
Course offerings (With full year computer science courses): https://drive.google.com/file/d/1rj9j-uKciafrYNXVciYJNLtyyHwL4P7T/view
School email example: wwei26@roslynschools.org

**Comment by philipto** [comment]
@wilburcoding First stage of verification passed, official domain is [roslynschools.org](https://roslynschools.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@wilburcoding Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
