### PR TITLE
Northeast Forestry University

### PR DESCRIPTION
**Pull request by Code0401**
Please tell me how to get your approval，We are recognized by the Ministry of Education，So please help me.Can a screenshot of an Outlook web page prove？
image

### CODE REVIEW

**Comment by philipto** [comment]
@Code0401 I am sorry, I feel that there is some misunderstanding.

1. I do not doubt that you have an email address ending with @nefueducn.onmicrosoft.com. 
2. I do not doubt that Northeast Forestry University is a recognized Chinese university.
3. The problem is that official internet domain of Northeast Forestry University is nefu.edu.cn, and the domain which you wish to add is nefueducn.onmicrosoft.com.
4. I need the proof which shows that Northeast Forestry University officially recognizes nefueducn.onmicrosoft.com as an email domain where Northeast Forestry University assigns email addresses from to Northeast Forestry University students.
5. The proof which you have submitted shows that you have an access to the email at nefueducn.onmicrosoft.com. It does not proof that addresses in nefueducn.onmicrosoft.com domain are assigned to students by the university. It also does not proof that the university recognizes this email domain as an official domain for the students.

**And the most important**: If you are the student of this university, you do not need to have the university added to SWOT repository. Please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Comment by Code0401** [comment]
I'm an it manager，I can prove everything about my school，So why do Chinese universities seem to be treated differently?
What proof do you need, please tell me, I think it is impolite to close.
Thank you.

**Comment by Code0401** [comment]
What kind of proof is possible, please tell me by example.
emmm,I don't know if it's impolite to speak like this in your country，thank you

**Comment by Code0401** [comment]
image
This is an alias for nefu.edu.cn，I don't know how to express in English, I hope you can understand

**Pull request closed without merging**
