### PR TITLE
Add afpa.training to domains

### PR DESCRIPTION
**Pull request by ludovic-esperce**
Hello,
Our organization "Afpa" has a new official domain name "afpa.training".
You'll find information about the school here : https://www.afpa.fr/

Afpa offers multiple long-terme trainings about computer science (both development and networking) :
- [https://www.afpa.fr/formation-qualifiante/concepteur-developpeur-d-applications](https://www.afpa.fr/formation-qualifiante/concepteur-developpeur-d-applications)
- [https://www.afpa.fr/formation-qualifiante/concepteur-developpeur-d-applications](https://www.afpa.fr/formation-qualifiante/concepteur-developpeur-d-applications)
- [https://www.afpa.fr/formation-qualifiante/administrateur-systeme-devops-3](https://www.afpa.fr/formation-qualifiante/administrateur-systeme-devops-3)

### CODE REVIEW

**Comment by philipto** [comment]
@ludovic-esperce Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@ludovic-esperce You might miss my previous comment. Please react.

**Comment by ludovic-esperce** [comment]
Hello @philipto,
Thanks for your reply, I've seen your message and asked for an official document.
I'm waiting for it and send it as soon as possible (hopefully next week).

**Comment by philipto** [comment]
@ludovic-esperce I am sorry, it looks like the proof is harder to get than it was expected. I have to close the request because it remains abandoned for too long. 

Please reopen it or create a new one if you have an update.

You also can enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

Thank you for your understanding!

**Pull request closed without merging**
