### PR TITLE
IISS Giulio Cesare

### PR DESCRIPTION
**Pull request by VitantonioS**
training offer: https://iissgiuliocesare.edu.it/wp-content/uploads/2022/10/GC_Brochure-SitoWeb-light.pdf
web site: https://iissgiuliocesare.edu.it/
study plan: https://iissgiuliocesare.edu.it/sistemi-informativi-aziendali/

### CODE REVIEW

**Comment by philipto** [comment]
@VitantonioS lib/domains/it/edu/iissgiuliocesare: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@VitantonioS First stage of verification passed, official domain is [iissgiuliocesare.edu.it](https://iissgiuliocesare.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@VitantonioS Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by VitantonioS** [comment]
Hi @philipto on this website https://iissgiuliocesare.edu.it/sistemi-informativi-aziendali/ is the school's curriculum offering 5h weekly in computer science. The curriculum provides acquisition of various skills example: in the IT management of information, in the evaluation, selection and adaptation of application software. 
you can also view the plan at the following url page 11 https://iissgiuliocesare.edu.it/wp-content/uploads/2022/10/GC_Brochure-SitoWeb-light.pdf

**Comment by philipto** [comment]
@VitantonioS  Thank you for the clarifications. Pull request merged.

**Pull request merged**
