### PR TITLE
Add new university

### PR DESCRIPTION
**Pull request by duongkhoangiam**

### CODE REVIEW

**Comment by philipto** [comment]
@duongkhoangiam Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by duongkhoangiam** [comment]
This is a school belonging to the department of education
School official website URL: https://blu.edu.vn/
Official IT-related url : https://cntt.blu.edu.vn/
The email domain of department is sobaclieu.edu.vn . this is manager and provider email domain to all teacher and students

**Comment by philipto** [comment]
@duongkhoangiam 
> The email domain of department is sobaclieu.edu.vn . this is manager and provider email domain to all teacher and students

I am sorry, this is not a proof, this is just an explanation. Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. The proof can be an official webpage, a copy of instruction, which the university sent to students upon enrollment, etc.

**Comment by philipto** [comment]
@duongkhoangiam You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@duongkhoangiam I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
