### PR TITLE
Add SMME, National University of Sciences & Technology, Pakistan

### PR DESCRIPTION
**Pull request by notadilnaqvi**

### CODE REVIEW

**Comment by notadilnaqvi** [comment]
School website: http://www.nust.edu.pk/INSTITUTIONS/Schools/SMME/Pages/default.aspx

IT related course: http://www.nust.edu.pk/INSTITUTIONS/Schools/SMME/ap/pg/MS-PhD-MRIME/Pages/Course-Description.aspx

**Comment by philipto** [comment]
@notadilnaqvi Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by notadilnaqvi** [comment]
I can't find an explicit statement that says said domain is official. Do I have any alternative?

**Comment by notadilnaqvi** [comment]
The same domain (smme.edu.pk) is used by our faculty as can be seen from their contact webpages (like [here](http://www.nust.edu.pk/INSTITUTIONS/Schools/SMME/Departments/DME/Faculty/Pages/Dr-Waqas-Hassan-Tanveer.aspx) & [here](http://www.nust.edu.pk/INSTITUTIONS/Schools/SMME/Departments/DME/Faculty/Pages/Muhammad-Kashif-Farooq.aspx)). Can that potentially serve as a proof?
image

**Comment by philipto** [comment]
@notadilnaqvi Yes, certainly! Pull request merged. Thank you!

**Comment by notadilnaqvi** [comment]
Best.

**Pull request merged**
