### PR TITLE
Feat: Add new Lumina Academy School

### PR DESCRIPTION
**Pull request by VietChaien**
Hello JetBrains Team,

I would like to add Lumina Academy to the JetBrains/swot repository. Lumina Academy is a dedicated educational institution specializing in 3D programming for film production, advertising, and video games.

Our academy equips students with essential programming skills aimed at creating cutting-edge 3D content across various industries. We delve into the creative and technical aspects of 3D production, equipping our students with practical knowledge on game engines, visual effects, computer graphics, virtual reality, and more. Our students extensively use JetBrains tools in their curriculum.

Here's the official website for further verification: [[Lumina Academy Website]](https://www.lumina.edu.vn/)

Thank you for considering this request. Looking forward to our students benefiting from the JetBrains student package.

Best Regards,
Viet

### CODE REVIEW

**Comment by VietChaien** [comment]
To make it easier to accept, I have attached an image of using the domain lumina.edu.vn with google workspace
Screenshot 2023-12-28 at 17 20 41

**Comment by philipto** [comment]
@VietChaien First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/groups/hockyxaodungphim/?locale=el_GR

**Comment by VietChaien** [comment]
Thank you for reply,

I don't know https://www.facebook.com/groups/hockyxaodungphim/?locale=el_GR
This's fanpage of Lumina Academy on Facebook 
https://www.facebook.com/lumina.edu.vn

Best Regards,
Viet

**Comment by philipto** [comment]
@VietChaien Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
