### PR TITLE
Create aastustudent.txt.

### PR DESCRIPTION
**Pull request by Bela-Jash**
It has the same information as the file "aastu.txt". However, the domain name "aastu" is for teachers, whereas "aastustudent" is for students.

### CODE REVIEW

**Comment by philipto** [comment]
@Bela-Jash The first verification stage is complete: the official domain for  **አዲስ አበባ ሳይንስና ቴክኖሎጂ ዩኒቨርሲቲ** is [t.me](https://t.me), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://t.me/s/aastusu2012?before=3166

**Comment by Bela-Jash** [comment]
@philipto Thank you for your quick reply.
Actually, t.me is the domain of Telegram, not that of Addis Ababa Science and Technology University (AASTU). Moreover, the link you provided (https://t.me/s/aastusu2012?before=3166) is for the university's student union's Telegram channel.

The university's official website is: http://aastu.edu.et. But it doesn't work on most browsers (since it doesn't use HTTPS, I think). And it hasn't been maintained for many years.

For the teachers, the domain used is "aastu.edu.et". For instance, john.doe@aastu.edu.et.
For the students, it is "aastustudent.edu.et". For example, jane.doe@aastustudent.edu.et.

Please let me know how I could help you with this in any way.

**Comment by philipto** [comment]
@Bela-Jash The first verification stage is complete: the official domain for  **አዲስ አበባ ሳይንስና ቴክኖሎጂ ዩኒቨርሲቲ** is [t.me](https://t.me), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://t.me/s/aastusu2012?before=3166

**Comment by Bela-Jash** [comment]
An automated response, I see.
Alright then, I'll be patient.

**Comment by philipto** [comment]
@Bela-Jash The first verification stage is complete: the official domain for  **አዲስ አበባ ሳይንስና ቴክኖሎጂ ዩኒቨርሲቲ** is [t.me](https://t.me), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://t.me/s/aastusu2012?before=3166

**Pull request merged**
