### PR TITLE
Create Alfa-college.txt

### PR DESCRIPTION
**Pull request by robsieljes**

### CODE REVIEW

**Comment by philipto** [comment]
@robsieljes There is similar domain which is already listed, students.alfa-college.nl. Please let us know why it's essential to add the upper-level domain. 
Also, please rename the file path, there is no necessity to have uppercase letters there, it can lead to a confusion (`lib/domains/nl/Alfa-college.txt` -> `lib/domains/nl/alfa-college.txt`)
Thank you!

**Comment by robsieljes** [comment]
Hello,

Thanks for the fast reply.

The student.alfa-college.nl <http://student.alfa-college.nl/> is only for students. The alfa-college domain is for teachers.

Is it possible to add that one to?

-- 
Met vriendelijke groet,
Rob Sieljes

Tel. 06-15215269
Mail. robsieljes@gmail.com <mailto:robsieljes@gmail.com>

**Comment by philipto** [comment]
@robsieljes Thank you. Absolutely. Pull request merged.

**Comment by robsieljes** [comment]
Thanks!

-- 
Met vriendelijke groet,
Rob Sieljes

Tel. 06-15215269
Mail. robsieljes@gmail.com <mailto:robsieljes@gmail.com>

**Pull request merged**
