### PR TITLE
adding the ottawa Catholic school board domain for student

### PR DESCRIPTION
**Pull request by nassimabenchernine**
Hi , Thank you for adding the Ottawa Catholic School domain for student . (ocsbconted.ca)

### CODE REVIEW

**Comment by philipto** [comment]
@nassimabenchernine Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@nassimabenchernine You might miss my previous comment. Please react.

**Comment by nassimabenchernine** [comment]
Hello Philip,
Sorry for my late response.
our Adult High school web site is  :
https://www.eslottawa.com/eslcomputers.html
Google Search :  https://www.google.com/search?q=st+patrick+adult+high+school+ottawa&rlz=1C1AVFC_enCA846CA846&oq=st+patrick+adult+high&aqs=chrome.1.69i57j69i59.15309j0j7&sourceid=chrome&ie=UTF-8

where Im taking Computer Classe (Wed development and ESL -  this is my second year) .
because of covid-19 we stady from home so the school give us the google based email:  na.benchernine@ocsbconted.ca and the domain name is the Ottawa Catholic school bord domain which can be verified from here : http://conted.ocsb.ca/  .
Thank you




________________________________
De : Philip Torchinsky <notifications@github.com>
Envoyé : lundi 2 novembre 2020 03:17
À : JetBrains/swot <swot@noreply.github.com>
Cc : nassimabenchernine <bench_nas@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [JetBrains/swot] adding the ottawa Catholic school board domain for student (#9700)


@nassimabenchernine<https://github.com/nassimabenchernine> You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@nassimabenchernine Thank you! We also got a confirmation from independent sources that the domain is recognized by the school. Pull request merged.

**Pull request merged**
