### PR TITLE
Add Sharjah English School to School List

### PR DESCRIPTION
**Pull request by koiboi-dev**

### CODE REVIEW

**Comment by philipto** [comment]
@koiboi-dev Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@koiboi-dev You might miss my previous comment. Please react.

**Comment by koiboi-dev** [comment]
https://www.sharjahenglishschool.org/

Meliha Rd,Industrial Area 17 Near National Paints, Opposite - Sharjah

https://www.sharjahenglishschool.org/fs/resource-manager/view/265aeae4-9ebb-410c-9006-b2131b14c7cc

I'm unsure how to prove the @ses-students address, how can I show its used?

**Comment by philipto** [comment]
@koiboi-dev  Thank you for the clarifications. The problem is that ses-students.org is registered for an organization in Canada, and your school is in United Arab Emirates.

Please provide us with a proof, which shows that the school recognizes the domain ses-students.org that you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@koiboi-dev I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
