### PR TITLE
cityInstitute

### PR DESCRIPTION
**Pull request by danilopiovani**

### CODE REVIEW

**Comment by philipto** [comment]
@danilopiovani Please provide us with:
* the school official website URL
* the school street address, including the city
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by danilopiovani** [comment]
Sent from my iPhone

> On 1 Sep 2022, at 7:31 pm, Philip Torchinsky ***@***.***> wrote:
> ﻿
> @danilopiovani Please provide us with:
> 
> the school official website URL

https://www.nortwest.edu.au/


> the school street address, including the city
GEORGE STREET CAMPUS
LEVEL 2, 531 GEORGE STREET
SYDNEY NSW 2000 AUSTRALIA

> an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
https://www.nortwest.edu.au/college-courses/it-courses/

> a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

If you access http://cityinstitute.com.au will be redirected to the new name nortwest.edu.au which recently bought the school city institute.



Thank you!

**Comment by philipto** [comment]
@danilopiovani  Thank you for the clarifications. Regrettably, this information cannot be considered as a proof:
> If you access http://cityinstitute.com.au/ will be redirected to the new name nortwest.edu.au which recently bought the school city institute.

Anyone can redirect a URL to anywhere, thus redirect to a certain website is never a proof. Please forgive us for being not too naive: we have a lot of fraudulent requests and must protect our honest users from being abused.

You can provide us with any of the following as the proof:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@danilopiovani It's even worse: the domain registration details have a sign of being registered for another entity. If you have a slightest doubt that the domain is officially recognized by the school, please close the request and apply with official documents at the "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Comment by philipto** [comment]
@danilopiovani You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@danilopiovani I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by danilopiovani** [comment]
Sorry... for some reason your email was in my junk.

I will try to find some other email or even ask the school to provide some
info to me.

Anyway... thank you.

[image: image.png]


[image: image.png]

[image: image.png]



<http://about.me/danilo.piovani>


[image: Danilo Piovani on about.me]

Danilo Piovani
about.me/danilo.piovani
*+61  458 887 674*

**Pull request closed without merging**
