### PR TITLE
Create zgia

### PR DESCRIPTION
**Pull request by malyarevich**
ZSEA but domain zgia.zp.ua.

### CODE REVIEW

**Comment by malyarevich** [comment]
For more information:
academy:
admin@zgia.zp.ua
or
Software Engineering
anatoliy.bezverkhyi@hotmail.com

**Comment by philipto** [comment]
@malyarevich Could you please rename lib/domains/ua/zp/zgia to lib/domains/ua/zp/zgia.txt to reflect this repository rules?

**Comment by malyarevich** [comment]
It's done.

**Comment by philipto** [comment]
@malyarevich Pull request merged. Thank you!

**Pull request merged**
