### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Jaranwala308**

### CODE REVIEW

**Comment by philipto** [comment]
@Jaranwala308 First stage of verification passed, official domain is [acecollege.edu.pk](https://acecollege.edu.pk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Jaranwala308 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by Jaranwala308** [comment]
All the courses are available at the following URL

https://acecollege.edu.pk/courses.php

**Comment by philipto** [comment]
@Jaranwala308  Thank you for the clarifications. Pull request merged.
I believe the course that fits the requirements of this trusted list is https://acecollege.edu.pk/icom.php.

**Pull request merged**
