### PR TITLE
Create tajamar365.txt

### PR DESCRIPTION
**Pull request by luisgiltajamar**

### CODE REVIEW

**Comment by luisgiltajamar** [comment]
Hello Elena, I put in copy to Juan Bou, Head of training in Formación Tajamar.

I also include a certificate of the school, where you can see that I am professor on it.

**Comment by luisgiltajamar** [comment]
Hello Elena
My name is Juan Bou and I am the IT Head Trainer Director of Tajamar (
www.formaciontajamar.com / www.tajamar.es)
Luis Gil is our Developer Trainer and he is handling this request.
We would like to offer the JetBrain´s products to our students.
It is possible?
Thank you very much
Regards and Happy New Year.


-- 

Juan Bou Bustamante
*Jefe de Formación *


*Formación Tajamar*
*C/ Pío Felipe 12 *



*28038  MadridTel.: 91 478 34 98 <91%20478%2034%2098> Fax.: 91 478 27 59
<91%20478%2027%2059> jbou@tajamar.es <jaruiz@tajamar.es>*
www.formaciontajamar.com

   - es.linkedin.com/in/juanboubustamante/




2015-01-02 10:45 GMT+01:00 Luis Felipe Gil Lamaignere <
luis.gil@tajamar365.com>:

>  Hello Elena, I put in copy to Juan Bou, Head of training in Formación
> Tajamar.
>
>  I also include a certificate of the school, where you can see that I am
> professor on it.
>
>
>

**Comment by luisgiltajamar** [comment]
Dear Luis,

 

Thanks for your reply. Please excuse my delay with replying you due to my being on New Year Holidays.

 

I’m adding the domain now – the school staff will be able to apply within half an hour. 

 

Kind regards,
Elena Ganenkova
Community Support Coordinator
JetBrains
 <http://www.jetbrains.com/> http://www.jetbrains.com
"Develop with pleasure!"

**Comment by luisgiltajamar** [comment]
Hola, JetBrains/swot:

Me gustaría añadirte a mi red profesional en LinkedIn.

Juan

Confirma que conoces a Juan: https://www.linkedin.com/e/v2?e=0-ir69nmm3-xy&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=z2epMbIB&invitationId=6164398167585550337








Has recibido una invitación a conectar. LinkedIn utilizará tu dirección de correo electrónico para enviar sugerencias a nuestros miembros en funcionalidades como Gente que podrías conocer. Date de baja aquí: https://www.linkedin.com/e/v2?e=0-ir69nmm3-xy&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGWoG9nrGeBAgAAAVYxXosREriZxK0xyeOk-6mIc1QATuHdji0UxAMEf8yt3mFHfjVyvvFXnhjlCFGNzvEiy78Y9vXfCkamtAS4ClX4wBXmccBjI-590wYlK-vZfuOI47LO6JX8cudI1d_YWZNPtKot-OBHFvnFusxA2QQqtH8VszYDfbnmRCKLqMbC9lmiXykI&eid=0-ir69nmm3-xy


Este mensaje se ha enviado a reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ir69nmm3-xy&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn y el logotipo de LinkedIn son marcas registradas de LinkedIn.

**Comment by luisgiltajamar** [comment]
Juan Bou Bustamante would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=rz9dww-iremvkj5-ab&t=ssuw&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=z2epMbIB&invitationId=6164398167585550337

View Juan Bou Bustamante&#39;s profile: https://www.linkedin.com/e/v2?e=rz9dww-iremvkj5-ab&t=ssuw&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=z2epMbIB&invitationId=6164398167585550337

Me gustaría añadirte a mi red profesional en LinkedIn.





Has recibido una invitación a conectar. LinkedIn utilizará tu dirección de correo electrónico para enviar sugerencias a nuestros miembros en funcionalidades como Gente que podrías conocer. Puedes darte de baja aquí: https://www.linkedin.com/e/v2?e=rz9dww-iremvkj5-ab&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=rz9dww-iremvkj5-ab&loid=AQEJ29RQT5-PqgAAAVZQHHKxXgXtgqX16cSRcAhAtjvjhMQ6Kpf5Sk3CTMedjr85Zdg4LahElDAfX7ZjRJqZpDZFGYC29m_Q144ZsH--fFakOuP9XZ7VaGbn5JlGyCH9_XWlxfU1joVut8gut1FcLYz-GkrGP1OzYFAWmqiVkgyyhhff2T2JzHx_mbOIzGNJZnQy

Este mensaje se ha enviado a reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=rz9dww-iremvkj5-ab&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn y el logotipo de LinkedIn son marcas registradas de LinkedIn.

**Comment by philipto** [comment]
@luisgiltajamar Could you please stop inviting this repository to LinkedIn? It is not a person, it is the repository managed by JetBrains. Thank you!

**Comment by luisgiltajamar** [comment]
Hi JetBrains/swot,

Juan Bou Bustamante would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=rz9dww-irovl36w-ml&t=ssuw&ek=second_guest_reminder_01&li=70&m=hero&ts=accept_text&sharedKey=z2epMbIB&invitationId=6164398167585550337

View Juan Bou Bustamante&#39;s profile: https://www.linkedin.com/e/v2?e=rz9dww-irovl36w-ml&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=z2epMbIB&invitationId=6164398167585550337

Me gustaría añadirte a mi red profesional en LinkedIn.





Has recibido una invitación a conectar. LinkedIn utilizará tu dirección de correo electrónico para enviar sugerencias a nuestros miembros en funcionalidades como Gente que podrías conocer. Puedes darte de baja aquí: https://www.linkedin.com/e/v2?e=rz9dww-irovl36w-ml&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=72&m=unsub&ts=HTML&eid=rz9dww-irovl36w-ml&loid=AQH5iodBQzVIxQAAAVZ1ZlLRsHpn7xMGvEESgUIoTcaMfEnxUIF4OJU1BJ_HQnmA0-LSyh13RZ6EJG6vbWQzOW_RMLdyek4CC6KVr-1lPw9QwZkx6LjeJdvj19VoB3f7Sa5sPz7kWYT3WxQHYcbFtjsQYGKxRKdsaXqCU41emGNPsRJZ6Seq_qAJBWHr7FYA8g1S

Este mensaje se ha enviado a reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=rz9dww-irovl36w-ml&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn y el logotipo de LinkedIn son marcas registradas de LinkedIn.

**Pull request merged**
