### PR TITLE
Add ewspa.edu.pl

### PR DESCRIPTION
**Pull request by JanekJaran**
As part of its courses, the university conducts the subject "Information technologies"

### CODE REVIEW

**Comment by philipto** [comment]
@JanekJaran Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by JanekJaran** [comment]
@philipto I am not able to provide you with one. If you accept that I can provide you with sylabus for IT subject.

**Comment by philipto** [comment]
@JanekJaran Yes, it would be sufficient. Please do not send it by email in reply to GitHub notification. Instead please upload it directly in the browser as a comment to this request. Thank you.

**Comment by philipto** [comment]
@JanekJaran You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@JanekJaran I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
