### PR TITLE
racchettidavinci.txt

### PR DESCRIPTION
**Pull request by giorgio71**

### CODE REVIEW

**Comment by philipto** [comment]
@giorgio71 Could you please tell us more about the school? Is it a college? Is it a vocational school? 
Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school.

**Comment by giorgio71** [comment]
Thank you for your answer. The school is an High school not informatics oriented. We have 2 courses: "modeling and problem solving" and "programmation and application development" and we use python with PyCharm community. In the next year we try to introduce Django but PyCharme community not support this framework. We need only Python and Django support. If you have another  solution other than using full license, (limited license, upgrade download or other) please tell me.

The link below is about our courses (I'm sorry but it is in Italian...). If you see at PTOF 3,4,9 (plain of formation 3,4,9) you can see the two courses. 
 
Thank for your patience  

https://www.racchettidavinci.gov.it/files/albo_pretorio/3._allegato_tabella_progetti_17-18_0.pdf

**Comment by giorgio71** [comment]
Only a clarification: the reference professor is Bonaventura Raffaella  
raffaella.bonaventura@racchettidavinci.gov.it

Thank you

**Comment by philipto** [comment]
@giorgio71 Thank you for the clarification! Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Pull request merged**
