### PR TITLE
Add Singapore International School to domain list 

### PR DESCRIPTION
**Pull request by Thson12**

### CODE REVIEW

**Comment by philipto** [comment]
@Thson12 Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Thson12 You might miss my previous comment. Please react.

**Comment by Thson12** [comment]
@philipto Do I provide you in the comment or in the gmail?

**Comment by philipto** [comment]
@Thson12 I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Pull request closed without merging**
