### PR TITLE
Add PSL and Telecom Nancy

### PR DESCRIPTION
**Pull request by benjisympa**

### CODE REVIEW

**Comment by philipto** [comment]
@benjisympa Could you please give us official website URLs for both schools which you wish to add to this repository? Thank you.

**Comment by benjisympa** [comment]
Sure : 
https://www.univ-psl.fr/en
http://telecomnancy.univ-lorraine.fr/en

And for explanations : 
https://en.wikipedia.org/wiki/PSL_Research_University
https://en.wikipedia.org/wiki/Telecom_Nancy

Thank you.

**Comment by philipto** [comment]
@benjisympa There are few issues with your request:

1) Paris Sciences et Lettres is an association of the universities, and each of them has its own email domain. We try and avoid unnecessary generalisation by adding unions and associations to this repository if the students can use their specific university's email domain when requesting a license. Thus it seems to be not a good idea to add this association to the repository, unless the students are not able to use other university email domain. Please let us know can they, or can not.

2) Telecom Nancy can be added to the respository, however its official website lists other email domain, *telecomnancy.eu*, as a university domain: http://telecomnancy.univ-lorraine.fr/fr/ecole/contacts. Please give us a link to a page or an official document which proves that the students there use telecom-nancy.fr as their email domain.

Thank you!

**Comment by benjisympa** [comment]
Thank you for your answer.

I understand, PSL is an association of universities, but typically, I have only an address mail "@etu.univ-psl.fr" because I've done PSL-ITI this year and I have never done an universities belonging to PSL.

For Telecom, the email domain "telecomnancy.eu" is the official email domain. I haven't official document, but we can ask to the direction.

**Comment by philipto** [comment]
@benjisympa 
1) Regarding PSL - do I understand you right - does PSL offer courses or programs, which are not taught in any of the universities, participating in the association? Does it mean that PSL not just an umbrella for the universities, but a separate educational institution, founded by the universities which participate in the association? If yes, it can be added to this respository.
2) Regarding Telecom Nancy - any sort of document is sufficient. It can be a login page where the university name is shown, or a web page at the official website where the email domain is mentioned, or a conference paper (or a page from Goolge Scholar or Google Books) where an article/book authors are from the university and have an email @telecom-nancy.fr. 

I am looking to more info from you, will merge the request as soon as you provide us with the update. Thank you!

**Comment by philipto** [comment]
@benjisympa I am sorry, this request remains unanswered for too long, could you please answer the questions above, provide an update or close the request without merging? Thank you!

**Comment by philipto** [comment]
@benjisympa I am sorry, this request remains unanswered for a while, and I have to close it. Please make new separate requests for the universities which you wish to add to this repository, or reopen this request and update it with the information which I requested above. Thank you for the understanding.

**Pull request closed without merging**
