### PR TITLE
physical and mathematical lyceum №366, Saint-Petersburg, Russia

### PR DESCRIPTION
**Pull request by sergdolgopolov**
school site: http://www.fml366.org/

### CODE REVIEW

**Comment by philipto** [comment]
@sergdolgopolov Do I get correctly, that the school's email address pattern is username@obr.gov.spb.ru?

**Comment by sergdolgopolov** [comment]
School email is school366msk@obr.gov.spb.ru, but students do not have such emails

**Comment by philipto** [comment]
@sergdolgopolov Do I understand right, that all school have their official email addresses in a domain of obr.gov.spb.ru? We need  to understand the scope of users who can be assigned with the email addresses from this domain. Are they all school teachers in St Petersburg, Russia?

**Comment by philipto** [comment]
@sergdolgopolov You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@sergdolgopolov You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@sergdolgopolov I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. 

You can also send an email to community-support@jetbrains.com if it is simpler for you to clarify the details in an email.

Thank you for the understanding!

**Pull request closed without merging**
