### PR TITLE
Please add our school Sinology Institute

### PR DESCRIPTION
**Pull request by staneslevski**
We're a Chinese language school in Beijing.

Thank you

### CODE REVIEW

**Comment by xeu100** [comment]
Don't forget to include the homepage so its easier for the people who review to review.

**Comment by philipto** [comment]
@staneslevski Could you please give us an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school. You also may wish to familiarize with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot)

**Comment by philipto** [comment]
@staneslevski I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Comment by staneslevski** [comment]
Hi Phillip, 

 

Thanks for your message. I’m afraid I don’t think I fully understood the criteria before I opened the PR. We’re a Chinese language school and we don’t have IT related courses. We’re developing a new site using Django and I thought this would be a way to give our developers access to Pycharm (a great piece of kit).

 

Let me know if anyone in the office wants Chinese lessons though. 😊 (or wants to swap them for user licenses 😉 ).

 

Best regards, 

 

Tom Stanley

 

CEO

Sinology Institute and mmMandarin

 

+86 13126823715

 <mailto:tomstanley@sinologyinstitute.com> tomstanley@sinologyinstitute.com

 <https://www.linkedin.com/in/tstanleyuk/> 

Skype: tom_stanley_uk

 

 

                            <https://www.facebook.com/mmMandarinNow/>    <https://twitter.com/mmmandarinNow> 

 

Websites:

 <https://sinologyinstitute.com/>              <https://mmmandarin.com/>

**Pull request closed without merging**
