### PR TITLE
Create ICN-ARTEM

### PR DESCRIPTION
**Pull request by WorldWillWeb**
Add ICN-ARTEM

### CODE REVIEW

**Comment by philipto** [comment]
@WorldWillWeb First stage of verification passed, official domain is [icn-artem.com](https://icn-artem.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@WorldWillWeb Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@WorldWillWeb You might miss my previous comment. Please react.

**Comment by WorldWillWeb** [comment]
> @WorldWillWeb Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

Hello,

We don't exactly have 1-year courses, but rather computer courses (modules lasting a few hours only).

Would it still be eligible in this case?

**Comment by philipto** [comment]
@WorldWillWeb Regrettably, no. There are other options suitable for such courses. If you need a license just for few days, a trial version would work (it expires in 30 days). If it does not fit, please apply for another licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses.

I have to close the request.

Thank you for your understanding!

**Pull request closed without merging**
