### PR TITLE
Adding TJHS/HCPS to swot

### PR DESCRIPTION
**Pull request by Skiller9090**
Adding HCPS to swot

### CODE REVIEW

**Comment by Skiller9090** [comment]
School Website: https://www.mysdhc.org/jefferson

**Comment by philipto** [comment]
@Skiller9090 lib/domains/net/hcps.net: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Skiller9090 lib/domains/net/hcps.net: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
FTR: domain ownership proof is at https://www.sdhc.k12.fl.us/doc/1323

**Comment by philipto** [comment]
@Skiller9090 Pull request merged. I renamed the file for you. It has to have a `.txt` extension, not `.net`. Thank you!

**Comment by Skiller9090** [comment]
Thanks man

**Pull request merged**
