### PR TITLE
Added my school

### PR DESCRIPTION
**Pull request by NicholasGrey1**
https://longfieldacademy.org.uk/ - School Website

### CODE REVIEW

**Comment by philipto** [comment]
@NicholasGrey1 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by NicholasGrey1** [comment]
Internally within the school the email is used, [this ](https://leighacademiestrust.org.uk/2017/06/07/the-leigh-utc-students-assist-in-creating-lat16-promotional-videos/)is one of the cases I could find of this being used. The school is apart of the Leigh Academies Trust which can be seen [here:](http://latlive.wpengine.com/our-academies/)

**Comment by philipto** [comment]
@NicholasGrey1 I am sorry, I did not find any mentioning of **lgflearner.org.uk** by the links you provided us with. Could you please upload a screenshot to your next comment? Thank you!

**Comment by NicholasGrey1** [comment]
> @NicholasGrey1 I am sorry, I did not find any mentioning of **lgflearner.org.uk** by the links you provided us with. Could you please upload a screenshot to your next comment? Thank you!

I am sorry there appears to be a mistake, the domain I meant to submit was lat16.org.uk not lgflearner.org.uk. I made this mistake as I only switched to this domain recently

**Comment by philipto** [comment]
@NicholasGrey1 I renamed the file to add lat16.org.uk. Thank you for the clarification. Pull request merged.

**Pull request merged**
