### PR TITLE
add manipal university jaipur

### PR DESCRIPTION
**Pull request by kadariyaujwal**
University's Link: https://www.onlinemanipal.com/np
It Course Link: https://www.onlinemanipal.com/np/bachelor-of-computer-applications
Domain recognition: https://ibb.co/D9HYZPN

### CODE REVIEW

**Comment by philipto** [comment]
@kadariyaujwal Please provide us with the school street address, including city and country. 

Also, the screenshot that you have attached does not prove that the university recognizes the domain as official.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

Thank you!

**Comment by philipto** [comment]
@kadariyaujwal You might miss my previous comment. Please react.

**Comment by kadariyaujwal** [comment]
@philipto Hi, seems like there is not enough information to prove that the school recognizes the domain that i am submitting. 
I have an welcome email from domain mujonline.edu.in (this is the domain i want to get approved) that instructs me to login to domain onlinemanipal.com (this is university's domain). Does this work as a proof of linking these domains? 

University Address:
Manipal University Jaipur , 
Dehmi Kalan, Off Jaipur-Ajmer Expressway,Jaipur, (Raj.)
Rajasthan 303007.
Phone: +91 141-3999100
Country: India

**Comment by philipto** [comment]
@kadariyaujwal  Thank you for the clarifications. Pull request merged.

I found some independent materials confirming that the domain you are submitting is recognized by the university. Thank you!

**Pull request merged**
