### PR TITLE
added energy-generation

### PR DESCRIPTION
**Pull request by ebenjs**
Energy Generation is a university created since 2016 and present in Togo and Ghana.

### CODE REVIEW

**Comment by philipto** [comment]
@ebenjs Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by ebenjs** [comment]
Thank you @philipto 

- Official website: https://www.energy-generation.org/
- Rue 251 HDN, Lomé-TOGO
- No matter which branch you choose, there are courses like Arduino IoT and Web development in the syllabus.
- A proof of the school recognizes the domain is the file attached to this comment which shows invitation mails from the administration for modules.

Capture d’écran 2022-04-21 à 20 28 21

**Comment by philipto** [comment]
@ebenjs You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@ebenjs I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
