### PR TITLE
Added Trust Academy

### PR DESCRIPTION
**Pull request by PrinceTirah**

### CODE REVIEW

**Comment by philipto** [comment]
@PrinceTirah First stage of verification passed, official domain is [trustacademy.ac.zw](https://trustacademy.ac.zw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by PrinceTirah** [comment]
> @PrinceTirah First stage of verification passed, official domain is [trustacademy.ac.zw](https://trustacademy.ac.zw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

noted with thanks.

**Comment by PrinceTirah** [comment]
@philipto noted with thanks.

**Comment by philipto** [comment]
@PrinceTirah Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
