### PR TITLE
add myhss

### PR DESCRIPTION
**Pull request by TodesRitter**
Hubert-Sternberg-Schule Wiesloch

### CODE REVIEW

**Comment by philipto** [comment]
@TodesRitter please provide us with:

- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

Thank you!

**Comment by TodesRitter** [comment]
school website : https://www.hss-wiesloch.de/

it related : https://www.hss-wiesloch.de/schularten-2/ausbildung/ausbildung-elektrotechnik/
it is a apprenticeship as a Software Developer which goes 3 years in germany 

i hope this is enough for a proof:
https://puu.sh/w9sTq/cc0c0a3233.PNG
https://puu.sh/w9sTv/ca63818e01.PNG
https://puu.sh/w9sTp/7a4d212c54.PNG

**Comment by philipto** [comment]
@TodesRitter Thank you for the clarification! Actually, you have an address info@myhss.de from the very same domain listed at https://www.hss-wiesloch.de, your official website, thus it's the proof. My problem was to find out what your official website is. Pull request merged now. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by TodesRitter** [comment]
thank you!

**Pull request merged**
