### PR TITLE
Create uss.txt

### PR DESCRIPTION
**Pull request by jmugikewito**

### CODE REVIEW

**Comment by philipto** [comment]
@jmugikewito Please provide us with:
* the school official full name, including word "University" if it is a part of the official name, **NOT an abbreviation**
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@jmugikewito This request is read-only for me, and I cannot edit the file content. Please update it yourself to "Universidad Señor de Sipan", according to  #20395.

**Comment by jmugikewito** [comment]
Hello good evening

1. official full name  = Universidad Señor de Sipan
2. School official website URL = https://www.uss.edu.pe/uss/Inicio
3. School street address =  Km 5 Carretera a Pimentel , Chiclayo, Perú, Phone (074) 481610
4. URL of a page on the official website where the school offers an IT = https://www.uss.edu.pe/uss/Escuela-ingenieria-sistemas
5. 
Captura de pantalla 2024-03-20 215439
Captura de pantalla 2024-03-20 215816
Captura de pantalla 2024-03-20 215948
Captura de pantalla 2024-03-20 220053

**Comment by philipto** [comment]
@jmugikewito Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
