### PR TITLE
Add school

### PR DESCRIPTION
**Pull request by theo-uimm**

### CODE REVIEW

**Comment by philipto** [comment]
@theo-uimm First stage of verification passed, official domain for **Pôle Formation UIMM Franche-Comté - Site de Dole** is [formation-industries-fc.fr](https://formation-industries-fc.fr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@theo-uimm Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by theo-uimm** [comment]
Hello, see if the link https://formation-industries-fc.fr/nos-centres/dole/

**Comment by philipto** [comment]
@theo-uimm Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
