### PR TITLE
Create SUSTech

### PR DESCRIPTION
**Pull request by ZZR0**

### CODE REVIEW

**Comment by philipto** [comment]
@ZZR0 Please rename lib/domains/edu/SUSTech to lib/domains/edu/sustech.txt and correct a typo in the university description: SOUTHERN UNIVERSITY OF S_**EI**_ENCE AND TECHNOLOGY

**Comment by philipto** [comment]
@ZZR0 You might miss my previous comment. Please reply.

**Comment by ZZR0** [comment]
I have canceled this create action.------------------ Original ------------------

**Comment by philipto** [comment]
@ZZR0 OK, I close this request without merging as per your comment. Just in case you decide to submit a new request, please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit the request with correct information. Thank you for the understanding and your contribution!

**Pull request closed without merging**
