### PR TITLE
Create Universidad de O'Higgins.txt

### PR DESCRIPTION
**Pull request by gusanoc**

### CODE REVIEW

**Comment by philipto** [comment]
@gusanoc You probably meant to add an email domain @uoh.cl, didn't you?
If yes, please rename the file to lib/domains/cl/uoh.txt.
If not, please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with correct information.

**Comment by philipto** [comment]
@gusanoc You might miss my previous comment. Please reply.

**Comment by gusanoc** [comment]
Hi,

I just renamed the file. Thanks.

**Comment by philipto** [comment]
I am sorry, but you actually did not (or did not submit your changes to GitHub):
image

Please rename. Thank you!

**Comment by philipto** [comment]
@gusanoc Pull request merged. Thank you!

**Pull request merged**
