### PR TITLE
add simplonco.text

### PR DESCRIPTION
**Pull request by ramas69**

### CODE REVIEW

**Comment by ramas69** [comment]
Add simplon

**Comment by philipto** [comment]
@ramas69 First stage of verification passed, official domain is [simplon.co](https://simplon.co) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@ramas69 This domain seems to represent an umbrella institution, not a specific single university or a college. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Besides, this organization is a training center, not a college or a university. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot).

Please apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses.

I have to close the request without merging.

Thank you for your understanding!

**Comment by ramas69** [comment]
Thank you for your answer,
I am not a student, I am a teacher at the training center Simplon. A such I would like to know the proper way to ask for the appropriate license so that our student can use it.

Looking forward to hearing from you .

Rama SOUMARE
Certified trainer & Web development trainer 
***@***.***

**Pull request closed without merging**
