### PR TITLE
Create vntu.txt

### PR DESCRIPTION
**Pull request by siloenix**
Please, create the right file vNtu.txt instead of vStu.txt for the domain vntu.net for Vinnytsia National Technical University

### CODE REVIEW

**Comment by philipto** [comment]
@siloenix A domain for this university seems to be vntu.edu.ua, not vntu.vinnica.ua. Could you please change the path to lib/domains/ua/edu/vntu.txt, if I am right regarding the domain?

**Comment by siloenix** [comment]
Yes, you are right. But our university has 2 domains. Second is vntu.net, and a lot of students' emails are created on this domain, me too.
I'll create 2 files in 2 directories: edu and net – am I right?

**Comment by philipto** [comment]
@siloenix Yes, you did it right, but I see nothing in this request but lib/domains/ua/vinnica/vntu.txt. A domain vntu.vinnica.ua does not exist, thus you probably need to make a new request and submit both files for vntu.edu.ua and vntu.net there. Please ask for help here in comments if you have troubles with submitting the request.

**Comment by philipto** [comment]
@siloenix I am closing this request because you have created two new ones, which are correct. Thank you!

**Pull request closed without merging**
