### PR TITLE
Create khk.txt

### PR DESCRIPTION
**Pull request by phoenix913**

### CODE REVIEW

**Comment by zweizwei** [comment]
@phoenix913 please provide the link to the page, describing long-term educational programs, that the school provides

**Comment by henno** [comment]
@zweizwei the curriculums of ICT department are available here: http://khk.ee/osakonnad/ikt/oppekavad
(Translated page: http://www.microsofttranslator.com/bv.aspx?from=et&to=en&a=http%3A%2F%2Fkhk.ee%2Fosakonnad%2Fikt)

**Comment by henno** [comment]
@zweizwei There is a more concise page describing all of the long-term educational programs that the scool provides. It is located in Siseveeb which is a national information system for Estonian vocational schools.

List of schools participating in Siseveeb: https://siseveeb.ee
Tartu Vocational School's (Tartu Kutsehariduskeskus in Estonian) educational programs: https://translate.google.com/translate?sl=et&tl=en&js=y&prev=_t&hl=et&ie=UTF-8&u=https%3A%2F%2Fsiseveeb.ee%2Ftkhk%2Fveebivormid%2Foppekavad%2F%3Fvaade%3Dstruktuuriuksused%26struktuuriuksus%3D11&edit-text=&act=url

**Comment by henno** [comment]
@zweizwei Here's a recent newspaper article about the school opening new majors in this autumn:
https://translate.google.com/translate?sl=et&tl=en&js=y&prev=_t&hl=et&ie=UTF-8&u=http%3A%2F%2Ftartu.postimees.ee%2F3235525%2Ftartu-kutsehariduskeskus-avab-mitu-uut-eriala&edit-text=&act=url

**Comment by zweizwei** [comment]
@phoenix913 Sorry for the delay - we've been launching rebranding and I hadn't time to check the repo for a while. I'll add the domain now - thanks a lot for the confirmation!

**Pull request merged**
