### PR TITLE
Add ibb.waw.pl domain (Institute of Biochemistry and Biophysics Polis…

### PR DESCRIPTION
**Pull request by fogcity**
…h Academy of Sciences)

### CODE REVIEW

**Comment by zweizwei** [comment]
@fogcity could you please provide the link to the page, describing the educational programs the institute provides? thanks!

**Comment by zweizwei** [comment]
obsolete request, please reply to reopen

**Comment by fogcity** [comment]
http://www.ibb.waw.pl/pl/struktura/szkola-biologii-molekularnej

**Comment by zweizwei** [comment]
@fogcity thanks for the link - i'm adding the domain

**Pull request merged**
