### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by christiasv**
Add file ulcb.txt

### CODE REVIEW

**Comment by philipto** [comment]
@christiasv First stage of verification passed, official domain is [ulcb.edu.pe](https://ulcb.edu.pe) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by liymntnai** [comment]
Added files citechitm.txt
[file.zip](https://github.com/JetBrains/swot/files/11713839/file.zip)

**Comment by philipto** [comment]
@christiasv Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

@liymntnai Please make a separate pull request.

**Comment by philipto** [comment]
@christiasv You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@christiasv I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
