### PR TITLE
added realdolmen.com

### PR DESCRIPTION
**Pull request by tiled0203**

### CODE REVIEW

**Comment by philipto** [comment]
@tiled0203 Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@tiled0203 You might miss my previous comment. Please react.

**Comment by tiled0203** [comment]
Hello Philip,
Yes sorry i missed it.

For your information:
We're not really a school instance but an organization that provides trainings to different customers throughout the year.
We provide internal and external course trajects for maximum 6 month's to 1 customers (which contains courses like Java, Spring, Angular, React, SQL, JPA, JEE, Docker, etc.....)
But we already managed to get vouchers for our organization.
But if you still want to approve the pull request: here's some more information about our courses.

- website of Realdolmen Education is  https://education.realdolmen.com/nl
- courses we provide are Java, Spring, Angular, JPA, XML, SQL and more. 
- **Some examples of courses we provide**
- https://education.realdolmen.com/nl/course/JAV810 (for Java)
- https://education.realdolmen.com/nl/course/SPR410 and https://education.realdolmen.com/nl/course/SPR420 (for spring)
- https://education.realdolmen.com/nl/course/ABA001 and https://education.realdolmen.com/nl/course/ACA001(for Angular)
- My email address is Timothy.Leduc@inetum-realdolmen.world

**Comment by philipto** [comment]
Dear Timothy @tiled0203! Thank you very much for the clarification. I am glad that you already got the vouchers: they are the most appropriate form of the support JetBrains could offer to you. 

As for the request, I have to close it without merging, because your organization does not qualify for this repository according to this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot). Thank you for your understanding!

**Pull request closed without merging**
