### PR TITLE
add a new branch

### PR DESCRIPTION
**Pull request by L049**
www.shjgu.edu.cn

### CODE REVIEW

**Comment by L049** [comment]
- [ ] ？

**Comment by philipto** [comment]
@L049 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@L049 You might miss my previous comment. Please react.

**Comment by L049** [comment]
1. www.shjgu.edu.cn （ offical website URL）
2. 2859 Shuichan Road, Baoshan District, Shanghai, China {post code:201901}(address)
3. [Home page of Mechanical and Electrical Department of Shanghai JiGuang Polytechnic College](https://jdx.shjgu.edu.cn/2017/0510/c506a5123/page.htm)
[Picture Class Schedule of Grade 21 in the Second Semester of Mechanical and Electrical Department in 2021-2022 Academic Year](https://mp.weixin.qq.com/s/ogvgNGEeC2Zif9qFU1a-BQ)
[Class Schedule of Grade 21 computer network technology class 1 curriculum](https://mmbiz.qpic.cn/mmbiz_png/1uyohj1ibTicBzicoBwO6gWeTn5M2LVY8JaHiaWHYnZZ7uw9NQG3VyoTKW4qVINLY5Wa0FbnJWnIJiciaOApVuqrpTOw/640?wx_fmt=png&wxfrom=5&wx_lazy=1&wx_co=1)
4. The official email portal is located directly above the [school's homepage](https://www.shjgu.edu.cn), and the [image ](https://i.postimg.cc/B6vgkc57/2022-09-30-205500.png)I have provided illustrates this entrance. This is the [official email home page](http://mail.shjgu.edu.cn/).

**Comment by philipto** [comment]
@L049 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
