### PR TITLE
Create veckavali

### PR DESCRIPTION
**Pull request by anveshmupparaju**
Visvodaya Engineering College

### CODE REVIEW

**Comment by philipto** [comment]
@anveshmupparaju could you please rename lib/domains/in/veckavali to lib/domains/in/veckavali.txt as explained at the bottom of this page: https://github.com/JetBrains/swot

**Comment by philipto** [comment]
@anveshmupparaju You might miss my previous comment. Could you please modify your request as described above in order to have it satisfied? Thank you!

**Comment by philipto** [comment]
@anveshmupparaju Could you please rename the file in the reuqest as described above?

**Comment by philipto** [comment]
@anveshmupparaju I merged this request and will rename the file to .txt myself, but in general it is a bad practice to disrespect the repository rules and refuse to answer comments.

**Comment by anveshmupparaju** [comment]
@philipto Sorry Philip, I'm not available due to some health issues.

**Pull request merged**
