### PR TITLE
Add CANDOR TCI

### PR DESCRIPTION
**Pull request by jimb6**
Added Christian Academy in Davao Oriental Colleges Inc., to edu domain ph

### CODE REVIEW

**Comment by philipto** [comment]
@jimb6 First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/candortci/

**Comment by philipto** [comment]
@jimb6 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by jimb6** [comment]
Official Website Domain: candortci.edu.ph
Address: Kamagong-Tindalo Sts. Barangay Sainz, City of Mati, Davao Oriental
Page URL for IT related Courses:

candortci.edu.ph/about-web-development-nciii

candortci.edu.ph/hybrid-apps-development-ntr-program

candortci.edu.ph/android-apps-development-ntr-program

Official Email Address: ***@***.***

**Comment by jimb6** [comment]
Official Website Domain: candortci.edu.ph
Address: Kamagong-Tindalo Sts. Barangay Sainz, City of Mati, Davao Oriental
Page URL for IT-related Courses:

https://candortci.edu.ph/web-development-nc-iii/

https://candortci.edu.ph/hybrid-apps-development-ntr-program/

https://candortci.edu.ph/android-apps-development-ntr-program/

Official Email Address: ***@***.***

**Comment by philipto** [comment]
@jimb6 Could you please send an email to community-support@jetbrains.com and include this pull request's link to the email message? The issue is that there is not enough information about the school in the internet. Also, the domain's registration details are unclear.

In similar situations we usually reject the request because of lack of verifiability. However your request looks legitimate, and we need to clarify few details regarding the school by email. Thank you for your understanding!

I appreciate it if you tell us your full name and your position at the school in the email message. Thank you!

**Comment by philipto** [comment]
@jimb6 As we agreed in the email conversation, I close this request. Feel free to ask the support by email if you have any other questions or concerns. Thank you!

**Pull request closed without merging**
