### PR TITLE
add my teachers domain

### PR DESCRIPTION
**Pull request by khouilid**

### CODE REVIEW

**Comment by philipto** [comment]
@khouilid Please provide us with:
- the school official website URL
- the school street address, including the city and the country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@khouilid You might miss my previous comment. Please react.

**Comment by khouilid** [comment]
Hello sir,

Sorry i can reply before that.

The reason that i can't provide the information is that my school provide an email with different domain name of it website.

Thank you sir to be kind with me.

KHOUILID Abdelkbir

________________________________

**Comment by philipto** [comment]
@khouilid It is fine. Many schools do the same. Thus, if you can comment with the information that I asked for, please do. If it is impossible, you can still apply for a free license with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
@khouilid I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
