### PR TITLE
Add new students email Florida Universitaria

### PR DESCRIPTION
**Pull request by fdiaz-alonso**
Add new students email Florida Universitaria
- https://www.floridauniversitaria.es/
- https://www.floridauniversitaria.es/titulacion/desarrollo-de-aplicaciones-multiplataforma/
- https://www.floridauniversitaria.es/titulacion/desarrollo-de-aplicaciones-web/

### CODE REVIEW

**Comment by philipto** [comment]
@fdiaz-alonso Please provide us with a proof, which shows that the school recognizes the domain **alumnatflorida.es** you are submitting as an official email domain for the students.

You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@fdiaz-alonso You might miss my previous comment. Please react.

**Comment by fdiaz-alonso** [comment]
Hello @philipto
[carta_jet_brain.pdf](https://github.com/user-attachments/files/17121179/carta_jet_brain.pdf)

I am sending you an official letter signed and stamped by me, certifying that the new domain is used by students.
Is this ok?

**Comment by philipto** [comment]
@fdiaz-alonso  Thank you very much for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
