### PR TITLE
Adding Samuel Whitbread as a registered domain

### PR DESCRIPTION
**Pull request by DuncanLewis07**
Added my school as a registered email

### CODE REVIEW

**Comment by philipto** [comment]
@DuncanLewis07 Please provide us with a proof, which shows that the school recognizes the domain **mybest.org.uk** that you are submitting as an official email domain for the students.
You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by DuncanLewis07** [comment]
Does screenshots of a few other emails under the same organisation work as
proof ?

**Comment by philipto** [comment]
@DuncanLewis07 Regrettably, no. The official domain of the school is **samuelwhitbread.org.uk**.

Actual proof of using the domain **mybest.org.uk** by the school is here: https://www.samuelwhitbread.org.uk/_site/data/files/transition/Communication-at-SWA-AY-1819.pdf

However it's clear that the domain **mybest.org.uk** is used by multiple schools in the U.K. Could you please check with your teacher or the school IT department, what is the scope of **mybest.org.uk** use? How many schools use it? Is it used by schools only, or it's available to people other than school students?

I appreciate your clarification very much.

**Comment by DuncanLewis07** [comment]
I can’t check with them for a few weeks as they most likely won’t check
emails in summer

However to my knowledge I believe it’s only accessible to the students and
teachers of the schools inside the trust (BEST)

**Comment by philipto** [comment]
@DuncanLewis07 OK, got it. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.** Thank you.

**Pull request merged**
