### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by NotZelvin1**

### CODE REVIEW

**Comment by philipto** [comment]
@NotZelvin1 file/lib/domains/id/sch/smasantamaria1.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@NotZelvin1 The first verification stage is complete: the official domain for  **SMA Santa Maria 1 Bandung** is [sites.google.com](https://sites.google.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://sites.google.com/smasantamaria1.sch.id/aloysius/halaman-muka

**Comment by NotZelvin1** [comment]
My bad I thought it was the school email domain, the official
domain/website for the school is
https://sites.google.com/smasantamaria1.sch.id/ppdb2021-2022/home

**Comment by philipto** [comment]
@NotZelvin1 Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
