### PR TITLE
Add alumini HEIA-FR

### PR DESCRIPTION
**Pull request by sven-hash**
## Website

https://eia-fr.ch

### CODE REVIEW

**Comment by philipto** [comment]
@sven-hash First stage of verification passed, official domain is [heia-fr.ch](https://heia-fr.ch) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.heia-fr.ch/fr/haute-ecole/campus-haute-ecole-fribourg-heiafr/associations/alumni/organisation/

**Comment by sven-hash** [comment]
> @sven-hash First stage of verification passed, official domain is [heia-fr.ch](https://heia-fr.ch) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.heia-fr.ch/fr/haute-ecole/campus-haute-ecole-fribourg-heiafr/associations/alumni/organisation/


Thanks for your quick answer, let me know if you need anything
Yes the official domain is heia-fr.ch but the alumni email addresses still pointing to the old domain

**Comment by philipto** [comment]
@sven-hash Could you please clarify what the word "alumni" means in your comment? Regrettably, depending on the context it may mean "people who already graduated the university" and "the people who are studying at the university now". It is a significant difference if we are talking about free license eligibility.

Thank you!

**Comment by sven-hash** [comment]
> @sven-hash Could you please clarify what the word "alumni" means in your comment? Regrettably, depending on the context it may mean "people who already graduated the university" and "the people who are studying at the university now". It is a significant difference if we are talking about free license eligibility.
> 
> Thank you!

This "people who already graduated the university"

**Comment by philipto** [comment]
@sven-hash Thank you for the instant clarification! Regrettably, I cannot add the domain to this repository because people who already graduated a university are not eligible for free licenses for JetBrains tools. If you continue your study (for example, doing your PhD), you can apply for free educational license with an official document which proves that you are a PhD student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
