### PR TITLE
Add Velammal Institute of Technology

### PR DESCRIPTION
**Pull request by jasonBrom**
Velammal Institute of Technology

### CODE REVIEW

**Comment by philipto** [comment]
@jasonBrom Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by jasonBrom** [comment]
> @jasonBrom Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
> You can provide us with any of the following:
> 
> 1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
> 2. An URL of a page at the official school website that says that students use this email domain
> 3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
> 4. A WHOIS data that link the email domain to the school somehow
> 5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
> 6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

[https://en.wikipedia.org/wiki/Velammal_Institute_of_Technology](https://en.wikipedia.org/wiki/Velammal_Institute_of_Technology)

**Comment by jasonBrom** [comment]
> @jasonBrom Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
> You can provide us with any of the following:
> 
> 1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
> 2. An URL of a page at the official school website that says that students use this email domain
> 3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
> 4. A WHOIS data that link the email domain to the school somehow
> 5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
> 6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

[vit-mandatory-disclosure.pdf](https://github.com/JetBrains/swot/files/6488114/vit-mandatory-disclosure.pdf)

**Comment by philipto** [comment]
@jasonBrom There is a discrepancy between WHOIS data and the document that you have provided. The document is dated back to the year of 2018, and the domain edrexacademy.com WHOIS data indicates that is was registered in 2021. It is suspicious. The domain edrexacademy.com is not mentioned at the official university website. 

I have to close the request without merging. If you are a student of this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
