### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by zaidlr**
https://ccndpr.com

### CODE REVIEW

**Comment by viazoyt** [comment]
Emails are hosted at ccndpr.com, but the website is hosted at ccnd.org. If you visit ccndpr.com it will redirect you to the website at ccnd.org. If proof is needed that the emails are hosted there, you can verify via the contact information for the technology department.("Información de contacto") in ccnd.org.

**Comment by philipto** [comment]
@zaidlr If you wish to add an email domain ccndpr.com please rename lib/domains/com/ccnd.txt to lib/domains/com/ccndpr.txt
Please clarify which domain you wish to add.

**Comment by philipto** [comment]
@zaidlr You might miss my previous comment. Please react.

**Comment by zaidlr** [comment]
@philipto I changed the file to the according name. Please get back to me, if there is anything else needed.

**Comment by zaidlr** [comment]
@philipto I changed the file to the according name. Please get back to me, if there is anything else needed.

**Comment by philipto** [comment]
@zaidlr Pull request merged. Thank you!

**Pull request merged**
