### PR TITLE
Mercury Colleges Australia

### PR DESCRIPTION
**Pull request by widlok**

### CODE REVIEW

**Comment by philipto** [comment]
@widlok Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@widlok You might miss my previous comment. Please react.

**Comment by widlok** [comment]
website: https://www.mercurycolleges.nsw.edu.au/
my course: https://www.mercurycolleges.nsw.edu.au/advanceddiplomalandm/

**Comment by philipto** [comment]
@widlok Pull request merged. Thank you!

**Pull request merged**
