### PR TITLE
Added csuglobal.txt via upload

### PR DESCRIPTION
**Pull request by whatisbyandby**
Hi, Please Add Colorado State University Global Campus for their Computer Science students

### CODE REVIEW

**Comment by philipto** [comment]
@whatisbyandby I am sorry, where can I check that CSU Global recognizes csuglobal.com as their official email domain for students? Thank you.

**Comment by philipto** [comment]
@whatisbyandby You might miss my previous comment. Please react.

**Comment by whatisbyandby** [comment]
I'm sorry I botched this, It's csuglobal.edu. I just took a look to make sure it wasn't already added. Should I just make an update and recommit? What sort of thing do you need to verify?

**Comment by philipto** [comment]
@whatisbyandby If you wish to add csuglobal.edu, I can do it momentarily, no problem. Shall I proceed with it?

**Comment by whatisbyandby** [comment]
Yes Please, I'm sorry for the silly mistake, I really appreciate your time sorting it out.

**Comment by philipto** [comment]
@whatisbyandby No problem, thank you for the clarification. The domain csuglobal.edu added.

**Pull request merged**
