### PR TITLE
Remove Zhejiang University from stoplist.txt

### PR DESCRIPTION
**Pull request by Bill0412**
1. the university official website URL, if it is different from the domain you are submitting
The domain is the same
2. a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
http://www.en.cs.zju.edu.cn/22145/list.htm
3. a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
https://mail.zju.edu.cn/

### CODE REVIEW

**Comment by philipto** [comment]
@Bill0412 lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Bill0412** [comment]
Zhejiang University is a world-famous educational institute and should not be in the stoplist. 

As a student of Zhejiang University, I hope you can consider removing it from the stoplist. I really have passion in Computer Science and have been used your products including CLion and Pycharm for 2 years with the educational license. And I do consider buying a license after graduation, since there no other product I've used is better than yours.

I don't know if someone had taken advantage of the educational email, but I use the product myself with gratitude and I think most of us do. Hope you can reconsider it and remove it from the stoplist.

Wish your products better and better!

**Comment by Bill0412** [comment]
> @Bill0412 lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.

The university is already in the list, but it is later added to the stoplist, so I think it is different from a regular procedure. I'll try to send an email.

**Comment by Dayrker** [comment]
As a ZJU post-graduate student, with your educational license, Jetbrains' compliers like Pycharm & InteliJ IDEA really helps me a lot.
Sincerely hope that you can remove zju.edu.cn out from stoplist, cause we do need it and only a little bad guys break the rules.

**Comment by WaveLong** [comment]
> @Bill0412 lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.

I have submitted my application for a long time, but no reply

**Comment by philipto** [comment]
@Bill0412 lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Bill0412 @Dayrker @WaveLong @seekerzz  @gentle1999 @LianShuobin @zjusheldon 
Thank you for your request. Regrettably someone from the college shared their account details publicly, or sold it, and it led to broad account misuse and license terms violation.

Therefore, we are not able to identify if the people with @zju.edu.cn addresses are actual students or not.
If you are the student of this college, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Comment by Bill0412** [comment]
Yes, someone sold it and we have feedbacked to our university email team. There should have been a huge leak of emails and we hope the university could solve the problem and communicate with your team to regain the access to educational license.

**Pull request closed without merging**
