### PR TITLE
Added Faculdade Dom Bosco

### PR DESCRIPTION
**Pull request by AndrewsSouz**
to add Dom Bosco College

### CODE REVIEW

**Comment by Akhat-cpp** [comment]
[file.zip](https://github.com/JetBrains/swot/files/5816176/file.zip)

**Comment by AndrewsSouz** [comment]
@Akhat-cpp what you mean?

**Comment by philipto** [comment]
@AndrewsSouz I am sorry, a university with this name has a lot of different internet domains.
Please provide us with:
- the school official website URL
- the school street address
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

@Akhat-cpp Please create a separate pull request to add your school. Your school name in the file is too short and non-descriptive. If the school name is so short, please add some more details about the school, such as _Prywatne Technikum AWANS w Kielcach_. If you don't know how to make a separate pull request, please send the request to community-support@jetbrains.com.

**Comment by AndrewsSouz** [comment]
Where can I provide this informations to you?

**Comment by AndrewsSouz** [comment]
@philipto I will answer here.

- The oficial website: [https://faculdadedombosco.net/](url)

- Address: R. Mal. José Inácio da Silva, 355 - Passo d'Areia, Porto Alegre - RS, 90520-280, Brasil

- My graduation course 4 years: [https://faculdadedombosco.net/curso/sistemas-de-informacao/](url)

- Email proof: 
email-proof

**Comment by philipto** [comment]
@AndrewsSouz I am really sorry, I cannot approve the request yet. The domain faculdadedombosco.edu.br is not mentioned at the official website. Please upload a copy of some instruction from the university that says that you can use this email domain as a student.

**Comment by AndrewsSouz** [comment]
> @AndrewsSouz I am really sorry, I cannot approve the request yet. The domain faculdadedombosco.edu.br is not mentioned at the official website. Please upload a copy of some instruction from the university that says that you can use this email domain as a student.

The official website domain is .net, but the email don't  comes from college college domain, is from the Microsoft plataform. I will ask for a authorization.

**Comment by philipto** [comment]
@AndrewsSouz Excuse me, do you have any update on the matter?

**Comment by AndrewsSouz** [comment]
@philipto no, not yet.
I was just trying to add the domain for make my colleagues subscriptions easy, but the college response is very slow for this type of issue.

I already got my subscription with a official document, I think you can close this pull request.

**Comment by philipto** [comment]
@AndrewsSouz Thank you for the update. I close the request. Shall you have any further update, feel free to reopen it. Thank you!

**Pull request closed without merging**
