### PR TITLE
Create dronacharya

### PR DESCRIPTION
**Pull request by iamdhruv**

### CODE REVIEW

**Comment by philipto** [comment]
@iamdhruv Please rename `lib/domains/info/dronacharya` to `lib/domains/info/dronacharya.txt` to reflect this repository rules. Thank you!

**Comment by iamdhruv** [comment]
Done.. Thanks:)

**Comment by philipto** [comment]
@iamdhruv Pull request merged. Thank you!

**Comment by philipto** [comment]
@iamdhruv Pull request merged. Thank you!

**Pull request merged**
