### PR TITLE
added Uninove - Universidade Nove de Julho

### PR DESCRIPTION
**Pull request by profgrassi**

### CODE REVIEW

**Comment by philipto** [comment]
@profgrassi Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by profgrassi** [comment]
Dear Philip,

Please find the answers to your questions below in* blue*:

   - the university official website URL, if different from the domain you
   are submitting: *https://www.uninove.br/* <https://www.uninove.br/>
   - an URL of a page on the official website where an IT-related long-term
   (>1 year) course is offered by the university:
*https://www.uninove.br/graduacao/ciencia-da-computacao/o-que-e/
   <https://www.uninove.br/graduacao/ciencia-da-computacao/o-que-e/>*
   - an URL of a page or another proof (.pdf or a screenshot are OK)
   showing that the university recognizes the domain which you are submitting
   as an official email domain for the students:
*https://www.uninove.br/mestrado-e-doutorado/informatica-e-gestao-do-conhecimento/corpo-docente/
   <https://www.uninove.br/mestrado-e-doutorado/informatica-e-gestao-do-conhecimento/corpo-docente/>*

Please let me know if you need anything else.

Regards,

Flávio Grassi
Professor de Ensino Superior | Diretoria dos Cursos de Informática
Universidade Nove de Julho - UNINOVE
flavio.grassi@uni9.pro.br
www.uninove.br




Em qui, 6 de jun de 2019 às 10:41, Philip Torchinsky <
notifications@github.com> escreveu:

**Comment by philipto** [comment]
@profgrassi Thank you for your contribution and for using JetBrains tools! I am sorry, I am not sure that I understand you correctly:
1) The filepath in your request is lib/domains/br/pro/uninove.txt, and it represents an email domain of uninove.pro.br. 
2) The page which you suggested as a proof of the domain recognition shows many people with addresses in an email domain uni9.pro.br.

Which domain would you like to add to this repository?

**Comment by profgrassi** [comment]
Dear Philip,

It's different indeed, depending upon your "rule":

   - *University *domain is now *uninove.br <http://uninove.br> <*
   https://www.uninove.br/*>*
   - *Students *have an e-mail ending as *@uni9.edu.br <http://uni9.edu.br>*
   - *Teachers* - myself included - have an e-mail ending as *@uni9.pro.br*
   - Finnaly, *Admin* staff have an e-mail ending as *@uninove.br
   <http://uninove.br>*

Please let me know if you need anything else.

Flávio Grassi
Professor de Ensino Superior | Diretoria dos Cursos de Informática
Universidade Nove de Julho - UNINOVE
flavio.grassi@uni9.pro.br
www.uninove.br




Em dom, 9 de jun de 2019 às 17:43, Philip Torchinsky <
notifications@github.com> escreveu:

**Comment by philipto** [comment]
@profgrassi I have to close this request without merging because it is in fact for a domain of uninove.pro.br, not uni9.pro.br. I added the files representing uni9.pro.br and uni9.edu.br. You don't need to do anything else. Please wait at least two hours after this message is sent, before start requesting the licenses at https://jetbrains.com/student, it is necessary to propagate the changes through our system.

**Pull request closed without merging**
