### PR TITLE
Add Associação Educacional Dom Bosco

### PR DESCRIPTION
**Pull request by fabriciodsr**
- Institution/School Name

Associação Educacional Dom Bosco

- Institution/School Website

Website: http://www.aedb.br/
IT Course Page: http://www.aedb.br/graduacao/sistemas-de-informacao/

- Email Users

[X] Students
[X] Academic/Teaching Staff
[ ] Other/Support Staff

- Education Levels

[X] Post-graduate research
[X] Graduate School
[X] College (University) or Undergraduate School or equivalent
[ ] Community College or equivalent
[ ] High School or equivalent
[ ] Elementary School or equivalent

- Webmail page screenshot

Webmail

### CODE REVIEW

**Comment by philipto** [comment]
@fabriciodsr The screenshot shows that students have emails in the domain of inf.aedb.br. Is it correct, or you wish to add the whole email domain, aedb.br? Thank you!

**Comment by fabriciodsr** [comment]
@philipto 

image

That's all the domains included on the biggest one called **aedb.b**r.

The IT Students have emails from **inf**.aedb.br, but if it's possible to add the whole domain it would be great too.

**Comment by philipto** [comment]
@fabriciodsr Thank you for the clarification! Pull request merged.

**Comment by fabriciodsr** [comment]
@philipto Thanks, mate!

**Pull request merged**
