### PR TITLE
Create htl-shkoder.com

### PR DESCRIPTION
**Pull request by philipmichel**
Please add our vocational school. Webpage: htl-shkoder.com

### CODE REVIEW

**Comment by philipmichel** [comment]
Please add our vocational school. Webpage: htl-shkoder.com

**Comment by philipto** [comment]
@philipmichel Could you please put official name of the school in English or school native language (Österreichische Schule "Peter Mahringer") to the file which you have submitted with this request? 

Also, please rename the file from `lib/domains/com/htl-shkoder.com` to `lib/domains/com/htl-shkoder.txt` to reflect this repository rules.

Thank you!

**Comment by philipmichel** [comment]
Thanks for your reply to the issue. File is renamed and text ist also updated.

Best regards,
Philip

**Comment by philipto** [comment]
@philipmichel Pull request is now merged! Thank you!

**Pull request merged**
