### PR TITLE
https://edupia.vn/

### PR DESCRIPTION
**Pull request by edupia**

### CODE REVIEW

**Comment by philipto** [comment]
@edupia Please provide us with
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain `edupia.edu.vn` that you are submitting as an official email domain for the students.

**Comment by icovn** [comment]
@philipto 

- This is an URL of a page on the official website where we offers an IT-related long-term (>1 year) course [https://edupia.vn/bang-gia-khoa-hoc-tieng-anh-online](Gói Đặc Biệt Trọn Đời)
- Please give me an example of the proof! Should I submit the domain edupia.vn instead of edupia.edu.vn?

**Comment by philipto** [comment]
@edupia Thank you! As for the domain which you need to submit it depends on what is a pattern of your school's student email address. If it is username@edupia.edu.vn, you have to submit edupia.edu.vn, as you did already.

However this domain needs to be mentioned somewhere at edupia.vn, the official school's website, or in some internal documents which you were given at the time of enrollment. They are to be best proof for this domain's eligibility. Thank you!

**Comment by philipto** [comment]
@edupia I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
