### PR TITLE
Please add my school

### PR DESCRIPTION
**Pull request by graulr88**

### CODE REVIEW

**Comment by philipto** [comment]
@graulr88 file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@graulr88 file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by graulr88** [comment]
I believe I have uploaded the txt file into the correct folder and
requested a pull request. I am new at this, hence me being in school.

Thanks
Robert

**Comment by philipto** [comment]
@graulr88 file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Pull request closed without merging**
