### PR TITLE
add senac minas

### PR DESCRIPTION
**Pull request by cleberleao**

### CODE REVIEW

**Comment by cleberleao** [comment]
request new university

**Comment by philipto** [comment]
@cleberleao Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@cleberleao You might miss my previous comment. Please react.

**Comment by cleberleao** [comment]
> @cleberleao You might miss my previous comment. Please react.

@philipto send register students to my class and Whois.
[Aula sexta dia 11-03-2022 - UC3 - Relatório de Presença 11-03-22.csv](https://github.com/JetBrains/swot/files/8799192/Aula.sexta.dia.11-03-2022.-.UC3.-.Relatorio.de.Presenca.11-03-22.csv)
[Whois - Registro.br.pdf](https://github.com/JetBrains/swot/files/8799193/Whois.-.Registro.br.pdf)

**Comment by philipto** [comment]
@cleberleao  Thank you for the clarifications. Pull request merged.

**Pull request merged**
