### PR TITLE
Nanjing No.29 High School

### PR DESCRIPTION
**Pull request by qqice233**

### CODE REVIEW

**Comment by philipto** [comment]
@qqice233 Please tell us why @29zx.net is recognized by the school as official email domain for their students. Do you have any proof of it?

**Comment by qqice233** [comment]
The domain is verified by Microsoft Office 365 and we use Outlook to distribute email accounts to our students. The screenshot has been uploaded to prove the  the truth of this remark.
Screenshot

**Comment by philipto** [comment]
@qqice233 I am sorry, this proof is not enough. @29zx.net is registered with another, non-Chinese registrar, does not have own website, and I see no documents which instruct students to use this domain. If you don't have any internal instructions or other papers which confirm that this domain is recognized by the school, I will not be able to satisfy your request.

Please find a document which shows that the domain is owned by the school, or is recommended by the school for its students.

**Comment by qqice233** [comment]
I am one of the IT administrators. I know the domain is registered on Godaddy much later than the main domain, then can I transfer the domain to a Chinese registrar (Real name system required) to prove it?

**Comment by philipto** [comment]
@qqice233 
> can I transfer the domain to a Chinese registrar (Real name system required) to prove it?

Please, don't do it! We are not in a position to insist on changing anything with the domain. Any official paper from the school is much better as a proof. If it is in Chinese, it is OK.

**Comment by qqice233** [comment]
OK. But due to 2019-nCoV, it will take a few days(15 days or longer) for us to get back to school and sign the official paper. Will that be OK?

**Comment by philipto** [comment]
@qqice233 No problem. This request will remain open until you finally submit the proof. Hopefully, you will not be affected by 2019-nCoV more than you already are. Have a good and healthy week ahead!

**Comment by philipto** [comment]
@qqice233 I am sorry, do you have any update on the matter?

**Comment by qqice233** [comment]
Not really. Our school won't open until Apr 7th. I will apply for the paper as soon as possible once the school is open. Could you please wait for another 3 weeks? Thanks for your patience.

**Comment by philipto** [comment]
@qqice233 Absolutely! Stay healthy, don't worry. Thanks for the update.

**Comment by philipto** [comment]
@qqice233 I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Pull request closed without merging**
