### PR TITLE
Create KBW

### PR DESCRIPTION
**Pull request by Calculable**
Hi, I'd like to add my school to this repository.
Email Pattern: lastname_firstname@kbw.ch
URL: http://www.kbw.ch

Thank you

### CODE REVIEW

**Comment by philipto** [comment]
@Calculable Could you please rename `lib/domains/ch/kbw` to `lib/domains/ch/kbw.txt` to reflect the repository rules? The .txt extension is mandatory. Thank you!

**Comment by philipto** [comment]
@Calculable You probably missed my previous comment. Could you please make the change required in order to allow me to merge your request? Thank you!

**Comment by Calculable** [comment]
@philipto Hello, thank you for the reminder. I've just added the file extension.

**Comment by philipto** [comment]
@Calculable pull request merged. Thank you!

**Pull request merged**
