### PR TITLE
Added domain vathorstcollege.nl

### PR DESCRIPTION
**Pull request by Nebula83**
Added vathorstcollege.nl a public school in the Netherlands where programming courses are organized as an extra curricular activity. http://www.vathorstcollege.nl/

### CODE REVIEW

**Comment by Nebula83** [comment]
Do you need extra info to merge this?

**Comment by Nebula83** [comment]
@zweizwei Could you please merge this?

**Comment by zweizwei** [comment]
@Nebula83 merged, sorry for the delay

**Comment by Nebula83** [comment]
Thanks much!

**Pull request merged**
