### PR TITLE
Add new school to JetBrains

### PR DESCRIPTION
**Pull request by ntviet0124**

### CODE REVIEW

**Comment by philipto** [comment]
@ntviet0124 Please provide us with:
- the school official website URL, 
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school,
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by ntviet0124** [comment]
> @ntviet0124 Please provide us with:
> 
> * the school official website URL,
> * an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school,
> * an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

This is url: http://ntu.edu.vn/kcntt/vi-vn/home.aspx
Thank you.

**Comment by philipto** [comment]
@ntviet0124 I am sorry, the page  http://ntu.edu.vn/kcntt/vi-vn/home.aspx does not say that the university assigns email addresses in the domain khanhhoa.edu.vn to their students. How can we check that the domain khanhhoa.edu.vn which you are submitting, is an official domain for students of Nguyen Du High school?

**Comment by philipto** [comment]
@ntviet0124 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@ntviet0124 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
