### PR TITLE
Add ENSIT

### PR DESCRIPTION
**Pull request by OussemaBenAbdallah**

### CODE REVIEW

**Comment by philipto** [comment]
@OussemaBenAbdallah Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by OussemaBenAbdallah** [comment]
1- this is the official website of our school: http://www.ensit.tn/
2- In this page you'll find all the courses offered by our school including computer science or in french: "Génie Informatique":  http://www.ensit.tn/formation/diplome-dingenieur/
3- the students in our school were given this domain as an official email this domain to register in microsoft competitions, take microsoft's MTA certifications exams in fact this domain was offered by microsoft to our school and many other schools in Tunisia along with microsoft 365 student pack
maybe this URL might help:  https://www.ensit.tn/2019/05/14/nouvelle-session-de-certification-microsoft-jeudi-16-mai-2019/ 
It shows a list of competing students and their emails with the domain **ensit.u-tunis.tn**
I hope that would i am just a student at this school i don't have any reliable documents proving that this is our school's official email but I can assure that all the students use their personal emails or email with this domain as their educational email

**Comment by philipto** [comment]
@OussemaBenAbdallah Thank you for the clarification. Pull request merged. You also may wish to configure now a read-only access to the list of students which you mentioned in the comment. Please take care of security and privacy when commenting publicly. Your comment is visible to everybody who browse this repository on GitHub.

**Comment by OussemaBenAbdallah** [comment]
Hi Philip, 
Thank you very much for merging! Well i don't have access to the school official website and i can't change the list to read-only, so can i have your permission to delete my comment ?

**Comment by philipto** [comment]
Hi OussemaBenAbdallah,
Yes, certainly!
Thank you!
Best,
Philip

**Pull request merged**
