### PR TITLE
add simec institute domain

### PR DESCRIPTION
**Pull request by itsmohiful**

### CODE REVIEW

**Comment by philipto** [comment]
Please kindly provide the full name of your school on the first line of the file in your request

**Comment by itsmohiful** [comment]
Removed first line white space, Please Proceed with my PR.

**Comment by itsmohiful** [comment]
> Please kindly provide the full name of your school on the first line of the file in your request

Removed first line white space, Please Proceed with my PR.

**Comment by philipto** [comment]
@itsmohiful Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
