### PR TITLE
Create lvjusd.txt

### PR DESCRIPTION
**Pull request by xPolar**

### CODE REVIEW

**Comment by zeus0621** [comment]
add national penghu university of science and technology (npu)
[file.zip](https://github.com/JetBrains/swot/files/6783000/file.zip)
[gms.txt](https://github.com/JetBrains/swot/files/6783001/gms.txt)

**Comment by vietthang197** [comment]
I update my school

**Comment by dtthao** [comment]
I update my school

**Comment by zeixq** [comment]
[file (1).zip](https://github.com/JetBrains/swot/files/6783950/file.1.zip)
can you guys add my school?

**Comment by philipto** [comment]
@xPolar Pull request merged. 
Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of this school district who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.
Thank you!

@zeus0621 @dtthao @zeixq Please create a separate request. If you have any trouble, please send a message to community-support@jetbrains.com.

**Comment by zeus0621** [comment]
Dear Philip

Thanks for your help

S.C. Wu

Philip Torchinsky ***@***.***> 於 2021年7月12日 週一 上午3:29寫道：

**Comment by xPolar** [comment]
Thanks for the help @philipto, after you merged the pull request I had realized I could just authenticate my education status through authorizing with GitHub, at least any future students or teachers that need to use any JetBrains tools from my district won't have to create their own pull request.

**Pull request merged**
