### PR TITLE
add ar.edu.unlam.alumno

### PR DESCRIPTION
**Pull request by spizzirri**

### CODE REVIEW

**Comment by philipto** [comment]
@spizzirri Could you please confirm what is the email domain which you wish to add? lib/domains/ar/edu/unlam/unlam.txt corresponds to @unlam.unlam.edu.ar, and if you wish to add @unlam.edu.ar the file path has to be lib/domains/ar/edu/unlam.txt. Please rename if necessary. Thank you.

**Comment by spizzirri** [comment]
@philipto Thank you. I read again the FAQ and I made a mistake. I need to add @alumno.unlam.edu.ar because @unlam.edu.ar is also used by alumni. My email is dspizzirri@alumno.unlam.edu.ar.

**Comment by philipto** [comment]
@spizzirri Thank you! Pull request merged.

**Comment by spizzirri** [comment]
@philipto I have registered many times, but I don't have received the email. What do you think that is the issue? My email is dspizzirri@alumno.unlam.edu.ar.

**Comment by philipto** [comment]
@spizzirri It can be that your university mail server silently blocks messages from no_reply@jetbrains.com and sales@jetbrains.com, or the messages end up in your spam folder.

I've sent a copy of the confirmation message to your university email. Feel free to check your inbox and send a message to support@jetbrains.com if there is no email confirmation. You need to click on a link in the email in order to accept license terms and add the license to your account.

**Comment by spizzirri** [comment]
@philipto Thank you, I received the email.

**Pull request merged**
