### PR TITLE
Add NAE Schools in Vietnam

### PR DESCRIPTION
**Pull request by kms0219kms**
British International School, Hanoi

School Official Website : https://www.nordangliaeducation.com/bis-hanoi
Address : Hoa Lan Road, Vinhomes Riverside, Long Bien District, Hanoi, Vietnam
Student email : @bishanoi.net or @bishanoi.com

British International School, Ho Chi Minh City

School Official Website : https://www.nordangliaeducation.com/bis-hcmc
Address : 246 Nguyen Van Huong Street, Thao Dien Ward, Thu Duc City, Ho Chi Minh City, Vietnam
Student email : @bisvietnam.com or @bisvietnam.net

British Vietnamese International School, Hanoi

School Official Website : https://www.nordangliaeducation.com/bvis-hanoi
Address : 72A Nguyen Trai Street, Thanh Xuan District, Hanoi, Vietnam
Student email : @bvishanoi.com or @bvishanoi.net

British Vietnamese International School, Ho Chi Minh City

School Official Website : https://www.nordangliaeducation.com/bvis-hcmc
Address : Street 1, Binh Hung, Binh Chanh, Ho Chi Minh City, Vietnam
Student email : @bvisvietnam.com or @bvisvietnam.net

### CODE REVIEW

**Comment by kms0219kms** [comment]
These schools are doing Computer Science classes as course of IGCSE, which means 2-year course.
You can check this in curricula menu in each school's website.

**Comment by philipto** [comment]
@kms0219kms Thank you for your request and detailed explanations. Regrettably, the request will be reviewed slower than usual because it's necessary to review eight different schools and email domains.

**Comment by kms0219kms** [comment]
Yes, I agree. Thank you for your reply.
Anyways my re-verification will be in January so I can wait for you.

**Comment by philipto** [comment]
@kms0219kms Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
