### PR TITLE
Added Al Faisal government school

### PR DESCRIPTION
**Pull request by StarlkYT**

### CODE REVIEW

**Comment by ahadley1124** [comment]
@StarlkYT Please provide us with:

- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:

1 .A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
5. A WHOIS data that link the email domain to the school somehow
6. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
7. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by StarlkYT** [comment]
Hi, @ahadley1124 😊 

### the school official website URL
They don have one AFAIK. But they do have a [Twitter ](https://twitter.com/moe_ryh_21_0063?lang=ar) account.

### an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
I'm afraid there is not.

### a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
Here's a [screenshot ](https://imgur.com/a/f3ghtOt) of my Madrasati page. And a [screenshot ](https://imgur.com/a/wJMFDzi)of my profile in Noor.

**Comment by philipto** [comment]
@StarlkYT Pull request merged. Thank you!

**Comment by StarlkYT** [comment]
Hi, I have tried to renew my eductional license but it failed to recognize my e-mail. I applied from the JetBrains website again and used the official document tab. Please let me know if there is anything I should do.

cc: @ahadley1124  @ahadley1124

**Comment by StarlkYT** [comment]
Apparently there has been a commit that blacklisted my e-mail's domain for some reason, those e-mails are provided by the MOE and we use it in our governmental apps, I'm confused why did JetBrains accuse it to be fraud.

**Pull request merged**
