### PR TITLE
Add the school URI São Luiz Gonzaga.

### PR DESCRIPTION
**Pull request by vkhypado-dev**

### CODE REVIEW

**Comment by philipto** [comment]
@vkhypado-dev The first verification stage is complete: the official domain for  **URI São Luiz Gonzaga** is [urisaoluiz.com.br](https://urisaoluiz.com.br), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://urisaoluiz.com.br/site/ricadi/condicoes-para-submissao/

**Comment by vkhypado-dev** [comment]
Oh yes, this is the school's official domain, but the student domain in which they make it available to us and which I made the request for, they make the student domain available: saoluiz.uri.edu.br

**Comment by philipto** [comment]
@vkhypado-dev Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by vkhypado-dev** [comment]
Okay, but then, I'm at school now and I can only apply in the afternoon

**Pull request merged**
