### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by PasqualeMainolfi**
Add school

### CODE REVIEW

**Comment by philipto** [comment]
@PasqualeMainolfi Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by PasqualeMainolfi** [comment]
https://www.consalerno.it/

**Comment by philipto** [comment]
@PasqualeMainolfi Thank you! You might misunderstand the question. 
This school is not a technical school, but a musical school. Thus, we have to ensure that students of this school will use the free licenses for educational purpose, not for giving them out to their friends outside of the school. Thus, I have to check what are IT-related courses you study.

Please send me the link to the IT-related long-term course description, not to a homepage of the school.

Thank  you for your understanding.

**Comment by PasqualeMainolfi** [comment]
I teach computer science apply to music, you can find my courses under the acronym COME/05 at https://www.consalerno.it/didattica/corsi 

Thank you!

**Comment by philipto** [comment]
@PasqualeMainolfi Thank you for the clarification. Pull request merged.

**Pull request merged**
