### PR TITLE
ADD Uthermosillo domain

### PR DESCRIPTION
**Pull request by alonsolopezr**
Add of UTHermosillo domain, so our students and teachers can benefit from edu products 👍🏼

Signed-off-by: JOSE ALONSO LOPEZ ROMO <alonso.lopez.r@gmail.com>

### CODE REVIEW

**Comment by philipto** [comment]
@alonsolopezr First stage of verification passed, official domain is [uthermosillo.edu.mx](https://uthermosillo.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by alonsolopezr** [comment]
Thanks Philip... have a great day, hope to get our institution on the list soon

**Comment by philipto** [comment]
@alonsolopezr Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by alonsolopezr** [comment]
Thanks again, and have a great day 🎉😎

**Pull request merged**
