### PR TITLE
Adding wisdomhouse.edu.pk to list of domains

### PR DESCRIPTION
**Pull request by mdibraheem**
Wisdom House is a school and degree college working for women education in rural Pakistan.

### CODE REVIEW

**Comment by mdibraheem** [comment]
It offers 2 Year Degree College Program in CS.

**Comment by philipto** [comment]
@mdibraheem Please rename lib/domains/pk/edu/wisdomhouse to lib/domains/pk/edu/wisdomhouse.txt

**Comment by philipto** [comment]
@mdibraheem You might miss my previous comment. Please reply.

**Comment by mdibraheem** [comment]
Hi. Sorry for not being able to respond earlier. I have renamed the file. Kindly check.

**Comment by philipto** [comment]
@mdibraheem Pull request merged. Thank you!

**Pull request merged**
