### PR TITLE
LYCEE PROFESSIONNEL GUTENBERG

### PR DESCRIPTION
**Pull request by 2Fl00rian6**
**LYCEE PROFESSIONNEL GUTENBERG**

http://www.lyceegutenberg.net/

Please add my school, i need this IDE for school work, Thanks ^^

### CODE REVIEW

**Comment by philipto** [comment]
@2Fl00rian6 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@2Fl00rian6 You might miss my previous comment. Please react.

**Comment by 2Fl00rian6** [comment]
I am gathering all the information for you.

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Philip Torchinsky ***@***.***>
Envoyé : Sunday, July 31, 2022 11:34:07 AM
À : JetBrains/swot ***@***.***>
Cc : Florian Warther ***@***.***>; Mention ***@***.***>
Objet : Re: [JetBrains/swot] LYCEE PROFESSIONNEL GUTENBERG (PR #14641)


@2Fl00rian6<https://github.com/2Fl00rian6> You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@2Fl00rian6 Regrettably, this request remains not updated for a while. I have to close it without merging. Please create a new request if you have an update for the matter. Thank you.

**Pull request closed without merging**
