### PR TITLE
Add ehou

### PR DESCRIPTION
**Pull request by tungjohn**
https://hou.edu.vn/
http://ehou.edu.vn/
https://tuyensinh.ehou.edu.vn/thong-bao-tuyen-sinh-dai-hoc/
http://ehou.edu.vn/lien-he-2/

### CODE REVIEW

**Comment by philipto** [comment]
@tungjohn The first verification stage is complete: the official domain for  **Trường đại học mở Hà Nội** is [hou.edu.vn](https://hou.edu.vn), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://tuyensinh.hou.edu.vn/tintucchitiet/BT424/

**Comment by philipto** [comment]
@tungjohn Please tell us more about the rules at Hanoi Open University:
1. What are degrees offered by the university?
2. How long it takes to get a degree in the university?
3. Is there any fee for the study? How much does the study cost?
4. Is there an official accreditation of the university, i.e. does Ministry of Education recognize it as an educational organization that issues a diploma recognized by the state of Vietnam?

**Comment by philipto** [comment]
@tungjohn The first verification stage is complete: the official domain for  **Trường đại học mở Hà Nội** is [hou.edu.vn](https://hou.edu.vn), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://tuyensinh.hou.edu.vn/tintucchitiet/BT424/

**Comment by philipto** [comment]
@tungjohn Thank you very much for the clarifications and your patience while waiting for a review and processing your request. Pull request merged.

**Comment by clemencesithole8** [comment]
Dear Mr Philip Torchinsky [@philipto](https://github.com/philipto)
Zimbabwe Open University (www.zou.ac.zw) offers a wide range of Degree programs and Diplomas for students who wish to learn while working. 
I am a student doing Information Technology and I am in my forth year. My student pin is p2089444c@students.ac.zw, I look forward to working with you

**Pull request merged**
