### PR TITLE
Added Richmond Hill High School

### PR DESCRIPTION
**Pull request by Zenuts1**

### CODE REVIEW

**Comment by philipto** [comment]
@Zenuts1 First stage of verification passed, official domain is [bryan.k12.ga.us](https://bryan.k12.ga.us) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Zenuts1 Your school website is not accessible now. I need to see the website to verify the school eligibility for this repository. I will get back to this request shortly, and approve it if the verification of the school goes without problem.

In the meantime please feel free to apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Comment by Zenuts1** [comment]
The website is up as of posting this. I know that one of our local ISP's was having issues late last night which may have continued into this morning. Here's our districts full url: https://www.bryan.k12.ga.us/

**Comment by Zenuts1** [comment]
It could also potentially be that our network admin has the firewall blocking connections from other countries. If it still isn't working when you try and check it, I would bet connecting to a US vpn server would solve the problem.

**Comment by philipto** [comment]
@Zenuts1 You are right. The website is up now. Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
