### PR TITLE
Add wb-hochschule

### PR DESCRIPTION
**Pull request by LukasGerm**

### CODE REVIEW

**Comment by philipto** [comment]
@LukasGerm Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by LukasGerm** [comment]
- The URL is https://www.wb-fernstudium.de/
- The Adress is:
Street: Hilpertstr. 31 
City: 64295 Darmstadt
Country: Germany
- https://www.wb-fernstudium.de/kursseite/bachelor-studiengang-angewandte-informatik-bsc.html when you scroll a bit down you can see that its a Bachelor Degree with 7 semesters
- I don't actually know what you mean with that. Thats the official website with a german impressum etc.

**Comment by philipto** [comment]
@LukasGerm Thank you very much for the clarification. Would you please provide us with a proof, which shows that the school recognizes the domain **student.wb-hochschule.com** that you are submitting as an official email domain for the students?

You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by LukasGerm** [comment]
Okay so basically to get an e-mail address we go to [here](https://bildung365.de/index.htm?entityID=https%3A%2F%2Fbildung365.de%2Fshibboleth&return=https%3A%2F%2Fbildung365.de%2FShibboleth.sso%2FLogin%3FSAMLDS%3D1%26target%3Dss%253Amem%253A387edf2d563c5f45a4fe251e1566463a47e7a707d2d583d2d40fa3b33f94d411), search for `Wilhelm Büchner Hochschule` and get redirected to our website for single sign on. 
Also [here](https://www.wb-online-campus.de/infoseiten/public/downloads/Kurzbeschreibung_Office365.pdf) are the instructions to do so.

**Comment by philipto** [comment]
@LukasGerm Thank you very much for the clarification. Pull request merged.

**Pull request merged**
