### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Cloud11665**
Vlo krakow

### CODE REVIEW

**Comment by philipto** [comment]
@Cloud11665 Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Cloud11665** [comment]
Im very sorry. i thought that when applying with documents, the school
email isn't necessary.
Here is the school email: bsabat@vlokrk.onmicrosoft.com
To why its different: our school provided us with emails on the
".onmicrosoft" domain, and we dont really know why they didn't use their
main domain, https://www.v-lo.krakow.pl/ . But here is the proof with a
message in our digital-diary.
[image: 2020-05-06 11_05_51-Portal LIBRUS Rodzina.png]
<translation>
<title>
Your personal login to Microsoft Teams
</title>
Good morning,
under this message im providing you with your login info for the Microsoft
Teams platform.
Link to the platform:
login: (my email)
temporary password: (blurred out for obvious reasons)

You'll need to change your password on your first login.
It is possible to login via your PC or your mobile phone.

great regards,
Joanna Janik
</translation>

https://www.v-lo.krakow.pl/ is the official website of my high school.

Sincerely,
Bartłomiej

**Comment by philipto** [comment]
Dear @Cloud11665, 

You are quite right:
> i thought that when applying with documents, the school email isn't necessary.

It is not necessary exactly as you thought.

Also, if you apply with documents at https://www.jetbrains.com/shop/eform/students#official, it is absolutely not necessary to add a school email domain to this repository.

Therefore, you probably don't need to have me adding this domain to this repository. If you still need it for some reason, please attach the proof in the form of screenshot or .pdf via GitHub web interface, because GitHub strips out the attachments if they are sent by email in response to a comment to your pull request.

Please let me know how to proceed. If in doubt, feel free to email us JetBrains to community-support@jetbrains.com.

Thank you!

**Comment by philipto** [comment]
@Cloud11665 As we discussed above, I think the request must not me merged. You have not updated the request in last five days, thus I assume that you can request the license with a copy of your official student ID at https://www.jetbrains.com/shop/eform/students#official

I have to close the request as of now. Feel free to reopen and comment if necessary.

**Pull request closed without merging**
