### PR TITLE
pimunn

### PR DESCRIPTION
**Pull request by AlhonGelios**

### CODE REVIEW

**Comment by philipto** [comment]
@AlhonGelios First stage of verification passed, official domain is [nniito.ru](https://nniito.ru) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: http://nniito.ru/?id=2447

**Comment by AlhonGelios** [comment]
official domain - https://pimunn.ru/

**Comment by philipto** [comment]
@AlhonGelios Thank you for the details. 

Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by AlhonGelios** [comment]
https://pimunn.ru/magistratura/informatsionnye-sistemy-i-tekhnologii-v-zdravookhranenii/

**Comment by philipto** [comment]
@AlhonGelios  Thank you for the clarifications. Pull request merged.

**Pull request merged**
