### PR TITLE
Create flss.txt

### PR DESCRIPTION
**Pull request by hainam872011**
Website: http://flss.vnu.edu.vn/

### CODE REVIEW

**Comment by philipto** [comment]
@hainam872011 Thank you for the request! Please provide us with:
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by hainam872011** [comment]
Address: Pham Van Dong Street, Cau Giay District, Ha Noi City, Viet Nam
URL: http://flss.vnu.edu.vn/thong-bao/thong-bao-ve-viec-dang-ky-hoc-ngoai-ngu-2-danh-cho-hoc-sinh-khoi-10-k53-nam-hoc-2021-2022

**Comment by philipto** [comment]
@hainam872011 Thank you for the clarification. Pull request merged.

**Comment by hainam872011** [comment]
thank you @philipto

**Pull request merged**
