### PR TITLE
Create fedpolyado.txt

### PR DESCRIPTION
**Pull request by Behordeun**
Added The Federal Polytechnic, Ado-Ekiti to the list of institutions in the Nigerian domain

### CODE REVIEW

**Comment by philipto** [comment]
@Behordeun First stage of verification passed, official domain is [fedpolyado.edu.ng](https://fedpolyado.edu.ng) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Behordeun** [comment]
Thanks @philipto, we're patiently waiting for a successful enrollment of our institution.

**Comment by philipto** [comment]
@Behordeun Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by Behordeun** [comment]
@philipto, thanks. When can we start to access academic benefits?

**Pull request merged**
