### PR TITLE
ofppt-edu.ma

### PR DESCRIPTION
**Pull request by sorakannie**
Add ofppt-edu.txt

### CODE REVIEW

**Comment by sorakannie** [comment]
The school uses another website domain :
https://www.ofppt.ma/

**Comment by philipto** [comment]
@sorakannie file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@sorakannie There are several problems with your request:

1) The email domain which you mention, ofppt-edu.ma, is not listed anywhere at the official website https://www.ofppt.ma. Therefore, we need a proof from you that the school recognizes the domain which you are submitting as an official email domain for the students. It can be some kind of official paper (scan or photo is OK) which the school gave to you as an instruction on how to use the university webmail system, or something similar.
2) Your request contains file.zip file, which you don't need to include into request, the request has to have a text file only.

Please fix this issues: give us the proof and remove file.zip from the request. Thank you.

**Comment by philipto** [comment]
@sorakannie file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@sorakannie file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@sorakannie file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@sorakannie file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@sorakannie file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@sorakannie I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
