### PR TITLE
Create entry for Covenant university

### PR DESCRIPTION
**Pull request by pr0-ph3t**
Create a file for Covenant University, domain is @stu.cu.edu.ng provided by Gmail

### CODE REVIEW

**Comment by philipto** [comment]
@pr0-ph3t Could you please point out to a page on the official Covenant University website where they make clear that emails from stu.cu.edu.ng domain are actually belong to students of Covenant University  only? The problem is that official university email domain is covenantuniversity.edu.ng, which is different from stu.cu.edu.ng.

**Comment by pr0-ph3t** [comment]
There isn't any webpage that explicitly states that the emails from stu.cu.edu.ng domain belong to students of Covenant University, is the any other way to prove that the domain name belongs to covenant university?

The following are the domain names belonging to Covenant University:
**Staff** - @covenantuniversity.edu.ng
**Student** - @stu.cu.edu.ng

**Comment by philipto** [comment]
@pr0-ph3t According whois database and few documents at covenantuniversity.edu.ng the domain cu.edu.ng belongs to the university, thus we can assume that its subdomain stu.cu.edu.ng also belongs to the university. 

However before I merge the pull request, please rename Covenant to covenant.txt (lowercase and .txt extension are mandatory). Thank you!

**Comment by pr0-ph3t** [comment]
Hi @philipto thank you very much.

I have updated the files as requested.

Kindly merge.

Thanks.

**Comment by philipto** [comment]
@pr0-ph3t Thank you! Pull request merged.

**Comment by pr0-ph3t** [comment]
@philipto thank you very much!!!

**Comment by azueze** [comment]
stu.cu.edu.ng and covenantuniversity.edu.ng are both official email domains of the university. Like reference earlier older students had the covenantuniversity.edu.ng domain while more recently student's email domain is stu.cu.edu.ng. However, the entire staff of the university uses the covenantuniversity.edu.ng email domain.

**Pull request merged**
