### PR TITLE
Add Toutle Lake School District

### PR DESCRIPTION
**Pull request by MasonGrose**

### CODE REVIEW

**Comment by MasonGrose** [comment]
Website: https://toutlesd.org
Proof of IT related programs: https://jrhs.toutlesd.org/clubs/metal_mallards

**Comment by philipto** [comment]
@MasonGrose First stage of verification passed, official domain is [toutlesd.org](https://toutlesd.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by MasonGrose** [comment]
> @MasonGrose First stage of verification passed, official domain is [toutlesd.org](https://toutlesd.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Alright!

**Comment by philipto** [comment]
@MasonGrose First stage of verification passed, official domain is [toutlesd.org](https://toutlesd.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@MasonGrose Thank you for your patience while waiting for a review and processing your request. Pull request merged. Thank you!

**Pull request merged**
