### PR TITLE
cordillera

### PR DESCRIPTION
**Pull request by Santiagoalq2502**
cordillera register

### CODE REVIEW

**Comment by philipto** [comment]
@Santiagoalq2502 lib/domains/ec/edu/estudiantes: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Santiagoalq2502 Could you please tell us what is the student email address pattern at this university? It has to be 
username@cordillera.edu.ec, is it? If yes, the file path in your request has to be lib/domains/ec/edu/cordillera.txt, not lib/domains/ec/edu/estudiantes. 

Please reply.

**Comment by Santiagoalq2502** [comment]
No, the email is with the domain username@estudiantes.cordillera.edu.ec

**Comment by philipto** [comment]
@Santiagoalq2502 Pull request corrected and merged. Please start requesting your free licenses in an hour. Happy coding! Thank you!

**Pull request merged**
