### PR TITLE
Create plus4u.txt

### PR DESCRIPTION
**Pull request by molotowitz**
Unicorn College, V Kapslovně 2767/2, 130 00 Praha 3 - Žižkov

### CODE REVIEW

**Comment by philipto** [comment]
@molotowitz Excuse me, your pull request contains a file for @plus4u.net domain, which seems to be not dedicated for Unicorn College students. Could you please provide a link to a page on the official website where plus4u.net domains listed as an official students' email domain? The page http://www.unicorncollege.cz/o-nas/kontakt.html has different email domain as an official one for Unicorn College, and plus4u.net is registered for Plus4U Net a.s., according to WHOIS database.

**Comment by molotowitz** [comment]
Hello,
thank you for your fast response, digging into it further:
Unicorn College is owned and financed by the Unicorn software company 
(http://www.unicorn.eu/index.html). This company also owns and develops 
the Unicorn universe system, which has a web user interface called 
Plus4U.net (https://unicornuniverse.eu/en/index.html). Plus4U.net web 
serves mainly all study materials, schedules, ratings etc. for the whole 
school ecosystem. Every student gets an email in the form of 
12-9434-1@plus4u.net, where the number refers to a Plus4U unique 
student's identifier. I can't find any -public- page where this is 
explicitly explained, maybe some note about study introduction, which at 
least refers to it 
(http://unicorncollege.cz/studijni-obory/sylaby/uvod-do-studia.html).

unicorncollege.cz is domain dedicated only for lectors and staff of the 
college. Students do not get emails with this domain, they get the 
plus4u.net and also other domains automatically (plus4u.eu, 
unicornuniverse.cz, unicornuniverse.eu, unicornuniverse.net etc.)

Thinking about it again - It can happen, that ex-students and possibly 
other employess of Unicorn can have this domain in their email. It is 
currently rare, that someone would be using it, but it can happen.

Ian

Dne 25.02.2016 v 14:21 Philip Torchinsky napsal(a):

**Comment by philipto** [comment]
@molotowitz Thank you very much for such a detailed explanation! In this case I would recommend to apply for Classroom license by email to classroom@jetbrains.com. With Classroom licenses (which are also free for students and teachers) the teachers will be able to invite particular students to get the free licenses. Does it satisfy the students' needs? If yes, I suggest to close this request with no merge.

**Comment by molotowitz** [comment]
Ok, thank you very much. I am closing this request.

**Pull request closed without merging**
