### PR TITLE
Created hallamcitycampus.txt

### PR DESCRIPTION
**Pull request by ajhar**

### CODE REVIEW

**Comment by philipto** [comment]
@ajhar lib/domains/com/hallamcitycampus: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by ajhar** [comment]
Closed and reopened because the incorrect file name

**Comment by philipto** [comment]
@ajhar First stage of verification passed, official domain is [hallamcitycampus.com](https://hallamcitycampus.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by ajhar** [comment]
We are accredited study center of University of Colombo School Of Computing which offers Bachelor of Information Technology which is 3 academic years
Official site :
https://www.bit.lk/index.php/about-bit/

**Comment by philipto** [comment]
@ajhar Regrettably, this request has signs of fraud. I have to close it without merging.

Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

**Comment by philipto** [comment]
@ajhar The request has been reconsidered and approved. Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
