### PR TITLE
Create kipu-rc.txt

### PR DESCRIPTION
**Pull request by abdurayimov**
Please add this domain in yours lib.

### CODE REVIEW

**Comment by philipto** [comment]
@abdurayimov Please rename lib/domains/ru/kipu-rc to lib/domains/ru/kipu-rc.txt
Thank you!

**Comment by philipto** [comment]
@abdurayimov You might miss my previous comment. Please react.

**Comment by abdurayimov** [comment]
> @abdurayimov You might miss my previous comment. Please react.

Thanks for reviewing!

**Comment by philipto** [comment]
@abdurayimov Pull request merged. Thank you!

**Pull request merged**
