### PR TITLE
Adding the alumni.mioti.es domain

### PR DESCRIPTION
**Pull request by lemartinez2245**
This the domain for the students from MIOTI Tech & Business School

### CODE REVIEW

**Comment by philipto** [comment]
@lemartinez2245 First stage of verification passed, official domain is [mioti.es](https://mioti.es) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@lemartinez2245 Could you please upload here via the browser, or provide an URL of a document that confirm an official recognition of your organization as an educational? It does not look like a university or a college. It looks more like a training center.

If this organization is a training center please apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses.

**Comment by philipto** [comment]
@lemartinez2245 You might miss my previous comment. Please react.

**Comment by lemartinez2245** [comment]
> 

I'm actually a student at this Institute, they give post-graduated degrees courses, masters. What do you mean with an URL or document that confirms official recognition? Sorry if I misunderstood this but I don't know what you call a training center. I might better go the the link you gave me.

**Comment by philipto** [comment]
@lemartinez2245 Thank you for the reply. 

> they give post-graduated degrees courses, masters.

Please reply this comment with an URL of the page that says it. I did not find an information regarding masters there. Are these masters in subjects related to the informational technologies or software development?

> What do you mean with an URL or document that confirms official recognition

The domain alumni.mioti.es is not mentioned anywhere at the website mioti.es. I need to see something that proves that the school provides the students there with email addresses in this domain.

You can prove it with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

Thank you!

**Comment by philipto** [comment]
@lemartinez2245 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
