### PR TITLE
Add kocaeli university Turkey

### PR DESCRIPTION
**Pull request by nazimisik**
Adding Kocaeli University of Turkey

I've seen other pull requests closed due to a claim that the domain is abused, but I think you should provide further information for this. Kocaeli University is a reputable university with more than 30 years of history. 

Also I see that there is a private instituon given access in the repo, I'm very surprised that it has gotten approved but yet an official university is being hold off from here. This doesn't make sense for me.

### CODE REVIEW

**Comment by nazimisik** [comment]
also subdomain of the domain is merged but the main is rejected? https://github.com/JetBrains/swot/pull/16079

**Comment by nazimisik** [comment]
I think it should be reconsidered 

but if we are making things open some questions should be answered without closing the MR directly in my opinion:

- How and When it was abused?
- Until when are you planning to hold off an entire university?

**Comment by philipto** [comment]
@nazimisik I am sorry, the domain kocaeli.edu.tr is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Comment by nazimisik** [comment]
only a generic response, pity @philipto

**Comment by philipto** [comment]
@nazimisik I will check all the details again and get back to this request tomorrow. I reopen it for now. Thank you!

**Comment by nazimisik** [comment]
thank you for the consideration

**Comment by philipto** [comment]
@nazimisik Thank you for telling us about the issue. Regrettably, Kocaeli University email domain has been abused in the past, in 2023. It means that some students' passwords were stolen, sold, guessed, or leaked. In result, third parties who weren't students or teachers of the school, obtained free licenses pretending to be the students.

Thus, we had to stop issuing licenses directly for people possessing @kocaeli.edu.tr email addresses. Instead, the students can enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then they apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students). 

It makes a request a little bit more complicated, but allows to keep the process honest and transparent.

Also, I checked the domain **uzem.education**, and found out that it was also abused. Therefore, we suspended the licenses issued for third parties in this domain due to their fraudulent activities. Also, I removed the domain uzem.education from trusted list. Thank you for bringing this issue to my attention.

I have to close this request without merging.

**Pull request closed without merging**
