### PR TITLE
Added edupro.cl domain

### PR DESCRIPTION
**Pull request by Vice-Manci**

### CODE REVIEW

**Comment by philipto** [comment]
@Vice-Manci The first verification stage is complete: the official domain for  **Liceo José Victorino Lastarria** is [www.liceolastarria.cl](https://www.liceolastarria.cl), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.liceolastarria.cl/images/2022/PDF/Tutorial_acceso_a_correo_alumnos.pdf

**Comment by Vice-Manci** [comment]
As the PDF suggests, the domain for **Liceo José Victorino Lastarria's** students and teachers is _edupro.cl_, then the students use the subdomain _estudiante_, while the teachers use the subdomain _docente_ (Spanish for docent or teacher). The domain [_liceolastarria.cl_](www.liceolastarria.cl) is for administrative use only, students don't have access to an email with that domain.

**Comment by philipto** [comment]
@Vice-Manci The domain edupro.cl belongs to Corporación de Desarrollo Social de Providencia.
Is it exclusively used by your school or by a number of organizations in your region? 
How many people have an access to this domain? Are they all only teachers and students?

**Comment by Vice-Manci** [comment]
To my knowledge, it's used by some schools that are being run by the Corporación de Desarrollo Social de Providencia.
I don't know how many people have access to the domain, but I know that is used exclusively by students and teachers.

**Comment by philipto** [comment]
@Vice-Manci Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
