### PR TITLE
Nederlandse Academie voor Beeldcreatie

### PR DESCRIPTION
**Pull request by rivaros**

### CODE REVIEW

**Comment by philipto** [comment]
@rivaros First stage of verification passed, official domain is [navb.nl](https://navb.nl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by rivaros** [comment]
@philipto thx. pls check `Faculteiten` menu information which will lead to faculties. We have foto, film, VR. In Fotovakschool faculty for e.x. you'll find many professional photography courses, some of them spanning for 4 years. https://fotovakschool.nl/home/opleidingen

**Comment by philipto** [comment]
@rivaros Thank you for the details! Could you please explain **what is the course that requires to use professional software development tools**? I found no courses implying any software developing. The reason to ask is to ensure that the free subscriptions given to the student of this school will be used according to the license terms and do not provoke transferring them to professional software developers outside of the school.

**Comment by philipto** [comment]
@rivaros You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@rivaros I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by rivaros** [comment]
@philipto sorry it took a while, as approval processes in bigger organization takes some time for approval. NAVB will be opening ICT courses this year, i'll get back to this thread when we are ready. Lets freeze it for now. Somebody from education administrative stuff will apply for normal university & e-ducation organizations license

**Pull request closed without merging**
