### PR TITLE
Add IESTP - Argentina

### PR DESCRIPTION
**Pull request by leonelhv**
Official website of the institute: [http://www.istpargentina.edu.pe/](url)
Official Facebook: [https://www.facebook.com/instituto.argentina](url)

### CODE REVIEW

**Comment by philipto** [comment]
@leonelhv First stage of verification passed, official domain is [istpargentina.edu.pe](https://istpargentina.edu.pe) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@leonelhv Please provide us with
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

Thank you!

**Comment by leonelhv** [comment]
@philipto Thank you for your response. Here is the information you requested:
Address: Av. Alfonso Ugarte Cdra. 9 S/N
City: Lima
Country: Peru
Computing and Information Technology career curriculum (3 years): [ http://www.istpargentina.edu.pe/wp-content/uploads/2018/01/Computacion.pdf](url)

**Comment by philipto** [comment]
@leonelhv Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
