### PR TITLE
lemonnier

### PR DESCRIPTION
**Pull request by haiwaCase**

### CODE REVIEW

**Comment by philipto** [comment]
@haiwaCase Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@haiwaCase You might miss my previous comment. Please react.

**Comment by haiwaCase** [comment]
@philipto how i van proof that ?

**Comment by philipto** [comment]
@haiwaCase You can provide us with any of the following:

1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@haiwaCase I am sorry, do you have any update?

**Pull request closed without merging**
