### PR TITLE
Register university Sao Paulo Tech School

### PR DESCRIPTION
**Pull request by gabrieldasilvadev**
I want to register my college to use the benefits of the Pack Github Studants.

### CODE REVIEW

**Comment by philipto** [comment]
@gabrieldasilvadev I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host sptech.school.br not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by gabrieldasilvadev** [comment]
does not have the .br at the end

**Comment by gabrieldasilvadev** [comment]
only sptech.school

**Comment by philipto** [comment]
@gabrieldasilvadev I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host sptech.br not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by gabrieldasilvadev** [comment]
example host: "example@sptech.school".
does not have .br

**Pull request closed without merging**
