### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sadmanrajad**
Hi, 
I am engineering student in Cloud&iot field.
I want to add my school to jetbrains to have a free acces to your products, also give the access to all the students of my institut.

thank you.

### CODE REVIEW

**Comment by sadmanrajad** [comment]
The official website of the institut :
www.inpt.ac.ma

**Comment by philipto** [comment]
@sadmanrajad Please ensure that the official websites are safe for browsing, because both www.inpt.ac.ma and www.ceitin.inpt.ma are said to be infected with malware, thus I am not sure if one can trust their content. Google warns me about the malware infection, thus it may also be a problem for the university. Please inform the university system administrators about the issue.

**Comment by sadmanrajad** [comment]
The website is safe try https://fr.m.wikipedia.org/wiki/Institut_national_des_postes_et_t%C3%A9l%C3%A9communications

**Comment by sadmanrajad** [comment]
The website is safe. I asked the administration and they told me to try http://www.inpt.ac.ma/ (don’t use https)

Or you can find more informations here : 
https://fr.wikipedia.org/wiki/Institut_national_des_postes_et_t%C3%A9l%C3%A9communications

**Comment by philipto** [comment]
@sadmanrajad Proof of a safety issue with the website: image

Also, please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students. I did not find any mention of an email address pattern like username@ine.inpt.ma at the website www.inpt.ac.ma.

Thank you.

**Comment by sadmanrajad** [comment]
IMG_0262
email inpt

**Comment by philipto** [comment]
@sadmanrajad Thank you for the clarification. Pull request merged.

**Comment by sadmanrajad** [comment]
Thank you.

**Pull request merged**
