### PR TITLE
Create Politecnico Internacional.txt

### PR DESCRIPTION
**Pull request by Dev-David-Herrera**
[pi.txt](https://github.com/JetBrains/swot/files/9003723/pi.txt)

### CODE REVIEW

**Comment by philipto** [comment]
@Dev-David-Herrera lib/domains/co/edu/PolitecnicoInternacional: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by KiraBobyleva** [comment]
Hello @Dev-David-Herrera,

Please provide us with:
- the school street address, including city and country
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Dev-David-Herrera lib/domains/co/edu/PolitecnicoInternacional: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Dev-David-Herrera You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@Dev-David-Herrera I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
