### PR TITLE
Added Internal Center for Academics for Jetbrains

### PR DESCRIPTION
**Pull request by opensworup**

### CODE REVIEW

**Comment by philipto** [comment]
@opensworup First stage of verification passed, official domain is [ica.edu.np](https://ica.edu.np) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by opensworup** [comment]
@philipto yes the official domain is ica.edu.np . But I have got the login as follows:
 username@s.ica.edu.np 
will it work as it as s.ica.edu.np at the end of email domain?

**Comment by opensworup** [comment]
@philipto any progress on the final verification?

**Comment by philipto** [comment]
@opensworup Thank you for your patience while waiting for a review and processing your request. Pull request merged.

Yes, everybody with an email like username@s.ica.edu.np are eligible for the free licenses. Thank you!

**Comment by opensworup** [comment]
@philipto Thank you.

**Pull request merged**
