### PR TITLE
Add Aden Formations

### PR DESCRIPTION
**Pull request by PABessero**
School Website: https://aden-formations.fr
IT Formation: https://aden-formations.fr/formations/bts-service-informatique-aux-organisations/

### CODE REVIEW

**Comment by philipto** [comment]
@PABessero Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain adenformations.school, which you are submitting as an official email domain for the students.

**Comment by PABessero** [comment]
Only thing i have with the domain is this:
https://adenformations.school (which doesnt have a proper SSL certificate) since the only other way we've had the .school is from mails they sent us

**Comment by philipto** [comment]
@PABessero I am sorry, it is not enough. There has to be some solid proof such as mentioning the email domain at the official school website, in a printed instruction sent to you after the enrollment, or in the email message to you from your school administration. Please let me know if it requires additional clarification. Thank you.

**Comment by philipto** [comment]
@PABessero You might miss my previous comment. Please react.

**Comment by PABessero** [comment]
Sorry, was in exams. I'll try getting an official document from them as soon as the exam period ends, not sure if you want to close this request and that i create a new one after, or if i should just post the document whenever i get it

**Comment by philipto** [comment]
@PABessero Please post the document as soon as you can. It can wait. 
Please add the document via web interface on GitHub, because GitHub strips attachments out if you reply to the comment by email. Have a good luck with exams!

**Comment by PABessero** [comment]
Will do, and thanks!

**Comment by philipto** [comment]
@PABessero Do you have any updates?

**Comment by PABessero** [comment]
Indeed, i received a mail a few hours ago and hadnt updated here yet, my school is being a pain and apparently we "arent allowed to use that email adress for this year" be it for any student related website or as a mail service with our teachers, we are only supposed to use if for Teams. Hence i think i'll close it for now, and hope they give us a proper address next year

**Pull request closed without merging**
