### PR TITLE
Added Marti Pous

### PR DESCRIPTION
**Pull request by victoralan2**
Added "Instituto Marti Pous", from Barcelona, Spain

Mail: ...@martipous.cat

### CODE REVIEW

**Comment by philipto** [comment]
@victoralan2 The first verification stage is complete: the official domain for  **Instituto Martí Pous** is [agora.xtec.cat](https://agora.xtec.cat), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://agora.xtec.cat/insmartipous/curs-2019-2020/equip-huma/

**Comment by victoralan2** [comment]
agora.xtec.cat is not the domain of the actual school, that is a different domain that all public schools in Catalonia use. The actual domain is @martipous.cat, You can verify this in the same link you sent me as all the teachers mails are in their info page.

image

**Comment by philipto** [comment]
@victoralan2 The first verification stage is complete: the official domain for  **Instituto Martí Pous** is [agora.xtec.cat](https://agora.xtec.cat), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://agora.xtec.cat/insmartipous/curs-2019-2020/equip-huma/

**Comment by philipto** [comment]
@victoralan2  Thank you for the clarifications. Pull request merged.

**Pull request merged**
