### PR TITLE
Create isbm.txt

### PR DESCRIPTION
**Pull request by Sfax2024**

### CODE REVIEW

**Review by imxaander — COMMENTED** [review]
The .txt file is empty. please read [How to add a domain to this repository](https://github.com/JetBrains/swot?tab=readme-ov-file#how-to-add-a-domain-to-this-repository).

**Comment by philipto** [comment]
Please kindly provide the full name of your school on the first line of the file in your request

**Review by Sfax2024 — COMMENTED** [review]
[isbm.txt](https://github.com/JetBrains/swot/files/15289622/isbm.txt)

**Comment by philipto** [comment]
@Sfax2024 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
