### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by octolet88**

### CODE REVIEW

**Comment by philipto** [comment]
@octolet88 I am sorry, the domain share.epsb.ca is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Comment by octolet88** [comment]
Hello,

I have attempted to resolve this issue by utilizing my GitHub account,
which is currently active with my student developer benefits. However,
whenever I submit the form after  authorizing GitHub and inputting my info
in, it reloads and then resets the form without providing any confirmation
of my request.

I would appreciate your assistance in resolving this matter.

**Comment by philipto** [comment]
@octolet88 Please send us a message to community-support@jetbrains.com. We need to know at least your email address to check what was the issue with your request. We need to investigate the issue, because sometimes the problem can be somewhere between GitHib and JetBrains, and we must identify its root cause.

**Comment by octolet88** [comment]
that i shall, thank you

**Pull request closed without merging**
