### PR TITLE
Added Liceum Fundacja Szkolna

### PR DESCRIPTION
**Pull request by Astened**

### CODE REVIEW

**Comment by philipto** [comment]
@Astened Please provide us with more details about your school. How old the students are? What is the course that you need JetBrains tools for? Thank you.

**Comment by Astened** [comment]
We are 14-15, we have extra computer science classes focused on making a game.

**Comment by Astened** [comment]
14 to 15, we have computer science classes focused on making a game.

**Comment by philipto** [comment]
@Astened Thank you for the clarification. Pull request merged.

**Pull request merged**
