### PR TITLE
Create basised.txt

### PR DESCRIPTION
**Pull request by VivaLaRoy**
Add Basised.txt

### CODE REVIEW

**Comment by philipto** [comment]
@VivaLaRoy Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by VivaLaRoy** [comment]
Hi,

School Website: https://enrollbasistx.com/shavano/

Address:  4114 Lockhill Selma Rd, San Antonio, TX 78230

<https://enrollbasistx.com/wp-content/uploads/2022/09/22BEDTX-Curriculum-Sequence-Map-Blue_DIGITAL.pdf>
[preview.png]
22BEDTX-Curriculum-Sequence-Map-Blue_DIGITAL<https://enrollbasistx.com/wp-content/uploads/2022/09/22BEDTX-Curriculum-Sequence-Map-Blue_DIGITAL.pdf>
PDF Document · 239 KB<https://enrollbasistx.com/wp-content/uploads/2022/09/22BEDTX-Curriculum-Sequence-Map-Blue_DIGITAL.pdf>



I'm a teacher not a student.
Their student domain is the sane as mine.

Thank you!

On Aug 29, 2024, at 9:08 AM, Philip Torchinsky ***@***.***> wrote:

﻿

@VivaLaRoy<https://github.com/VivaLaRoy> Please provide us with:

  *   the school official website URL
  *   the school street address, including city and country
  *   an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
  *   a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@VivaLaRoy  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by 0x32-l3git** [comment]
yes

**Pull request merged**
