### PR TITLE
Added Carmel college (ccg-leerling)

### PR DESCRIPTION
**Pull request by mardax007**
Carmel College is an overreaching organization that oversees multiple colleges.

### CODE REVIEW

**Comment by philipto** [comment]
@mardax007 lib/domains/nl/ccg-leerling[1].txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@mardax007 Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by mardax007** [comment]
Dear Jetbrains

You can just forget about my request, I already moved on because after I submitted my school I re-read the requirements and found that my school probably can’t comply to them. I already found another solution. Sorry for possibly wasting your time.

Best regards,
Mardax007

**Comment by philipto** [comment]
@mardax007 Thank you! I close the request.

**Pull request closed without merging**
