### PR TITLE
Create FondazioneJAC.txt

### PR DESCRIPTION
**Pull request by samuele794**
Add new School 

School WebSite:
http://www.fondazioneits.org
http://www.fondazionejac.org/
http://www.itsexperience.org

Software Course: http://www.fondazioneits.org/percorso/progettazione-e-sviluppo-di-applicazioni-informatiche/

### CODE REVIEW

**Comment by philipto** [comment]
@samuele794 Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain of fondazionejac.edu as an official email domain for the students.

**Comment by philipto** [comment]
@samuele794 You might miss my previous comment. Please reply.

**Comment by samuele794** [comment]
@philipto we are currently proceeding with the creation of an official school certificate in which we specify the mail domains used by the school.

**Comment by samuele794** [comment]
I would like to inform you that I just received the certificate from the  school for your reference .
[Certificato per rilascio licenza[677].pdf](https://github.com/JetBrains/swot/files/1743544/Certificato.per.rilascio.licenza.677.pdf)

**Comment by philipto** [comment]
@samuele794 Thank you very much for the clarification! I appreciate your effort in obtaining such a paper. Pull request merged.

**Comment by samuele794** [comment]
After carefully reading the procedure to add the school again we realized that we made a mistake in adding the new brenches.
We should have created them in this way: lib/domanis/org/fondazioneits/stu.txt and lib/domanis/org/fondazionejac/stu.txt
I'll personally strive to recreate them as indicated in the certificate. 
Thank you for your patience.

**Pull request merged**
