### PR TITLE
Create fsgf

### PR DESCRIPTION
**Pull request by fares-git**
**The university official website URL:**
https://fsgf.rnu.tn/

**a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university**
https://fsgf.rnu.tn/fra/s1269/departements/INFO/6/

**a URL of a page showing that the university recognizes the domain which I am submitting as an official email domain for the enrolled students**
https://fsgf.rnu.tn/fra/profil/mouez_gouasmia

### CODE REVIEW

**Comment by philipto** [comment]
@fares-git The first verification stage is complete: the official domain for  **Faculté des Sciences de Gafsa** is [fsgf.rnu.tn](https://fsgf.rnu.tn), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://fsgf.rnu.tn/fra/profil/mouez_gouasmia

**Comment by fares-git** [comment]
@philipto Thank you for your response. While the domain for email addresses differs from the one for the school's website, I can provide you with some links indicating that the students and teachers of **Faculté des Sciences de Gafsa** use the provided domain for their official email addresses.
https://www.researchgate.net/publication/343268036_Drone_of_Gafsa_A_Wind-powered_UAV_as_Flying_RSU_in_VANET
https://scholar.google.com/citations?user=QLxo2AUAAAAJ&hl=fr
https://arxiv.org/pdf/2212.13600
https://www.researchgate.net/publication/360482718_Kupershmidt_operators_on_Hom-Malcev_algebras_and_their_deformation

**Comment by philipto** [comment]
@fares-git The first verification stage is complete: the official domain for  **Faculté des Sciences de Gafsa** is [fsgf.rnu.tn](https://fsgf.rnu.tn), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://fsgf.rnu.tn/fra/profil/mouez_gouasmia

**Comment by philipto** [comment]
@fares-git Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
