### PR TITLE
Upload College

### PR DESCRIPTION
**Pull request by HelloSeaNation**

### CODE REVIEW

**Comment by philipto** [comment]
@HelloSeaNation Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@HelloSeaNation You might miss my previous comment. Please react.

**Comment by HelloSeaNation** [comment]
email proof

**Comment by philipto** [comment]
@HelloSeaNation Thank you for your reply. Regrettably, situation became even worse. There are three domains now:
1) yoobee.ac.nz - the official College domain;
2) yoobeestudent.ac.nz - the domain that you wish to add to the repository;
3) yoobeecolleges.com - the domain that corresponds to a website hosted on Microsoft Azure and responds with very suspicious message now. The latter was used to send you a message that you intend to prove the eligibility of the second domain for the trusted list.

I'd suggest you to provide us with better verifiable proof, or just apply for free educational license with an official document which proves that you are a student. **You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.**

Please close the request if you don't plan to update it with better proof of the domain recognition.

**Comment by HelloSeaNation** [comment]
Wow, I didn't know it can cause that such trouble issues now. Don't worry, I'll close this request for now as I found another way to use Jetbrains already. Thanks for your time

**Pull request closed without merging**
