### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by EmpyreanDaemon**
Office Moshe Sharet Israel

### CODE REVIEW

**Comment by EmpyreanDaemon** [comment]
Similar to #12465 

school website - 
https://sharet.tik-tak.net/

New school email for Computer Science.

**Comment by philipto** [comment]
@EmpyreanDaemon Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@EmpyreanDaemon You might miss my previous comment. Please react.

**Comment by EmpyreanDaemon** [comment]
@philipto 

School URL - https://sharet.tik-tak.net/
Address - Pierre Gilbert St 4, Netanya, Israel.

image

image

image

You can see the School's logo, and the Email Address associated with it.


The Computer Science Page
https://sharet.tik-tak.net/%d7%9e%d7%a7%d7%a6%d7%95%d7%a2%d7%95%d7%aa/%d7%9e%d7%92%d7%9e%d7%95%d7%aa/%d7%9e%d7%92%d7%9e%d7%95%d7%aa-%d7%90%d7%a9%d7%9b%d7%95%d7%9c-%d7%92/%d7%9e%d7%92%d7%9e%d7%aa-%d7%9e%d7%93%d7%a2%d7%99-%d7%94%d7%9e%d7%97%d7%a9%d7%91/

The Data Analysis Page 
https://sharet.tik-tak.net/%d7%9e%d7%a7%d7%a6%d7%95%d7%a2%d7%95%d7%aa/%d7%9e%d7%92%d7%9e%d7%95%d7%aa/%d7%9e%d7%92%d7%9e%d7%95%d7%aa-%d7%90%d7%a9%d7%9b%d7%95%d7%9c-%d7%92/%d7%9e%d7%99%d7%93%d7%a2-%d7%95%d7%a0%d7%aa%d7%95%d7%a0%d7%99%d7%9d-data-analysis/

You can use Google Translate to better view it.

**Comment by philipto** [comment]
@EmpyreanDaemon Thank you for the clarifications. I am sorry, this domain **eduil.org** seems to represent an umbrella institution, not a specific single university or a college. It cannot be added to this repository. 

Instead of adding the domain here, please enroll to **GitHub Student Developer Program** at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

I have to close this request without merging.
Thank you for your understanding!

**Pull request closed without merging**
