### PR TITLE
Interlochen Arts Academy

### PR DESCRIPTION
**Pull request by SebastianPardoDev**
https://www.interlochen.org

### CODE REVIEW

**Comment by philipto** [comment]
@SebastianPardoDev First stage of verification passed, official domain is [interlochen.org](https://interlochen.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@SebastianPardoDev Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by SebastianPardoDev** [comment]
Course Catalog 2022-2023 - Google Docs
<https://docs.google.com/document/d/1J8Usdv931Q4BHP7OBdnbKl9GD0F8jMptbGqLJMcIt7o/edit#bookmark=kix.h1xydjwrbkw2>

Under the Math Curriculum section the CS class can be found :)

[image: image.png]

**Comment by philipto** [comment]
@SebastianPardoDev  Thank you for the clarifications. Pull request merged.

**Pull request merged**
