### PR TITLE
Add e.txt file in lib/domains/cn/edu/gzhu to add GuangZhou University

### PR DESCRIPTION
**Pull request by Linncharm**
Add e.txt file in lib/domains/cn/edu/gzhu to add GuangZhou University

### CODE REVIEW

**Comment by philipto** [comment]
@Linncharm I am sorry, the domain e.gzhu.edu.cn is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account  (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
@Linncharm I am sorry, the domain e.gzhu.edu.cn is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Comment by Linncharm** [comment]
> @Linncharm I am sorry, the domain e.gzhu.edu.cn is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

I tried , but it still block me for the email reason,although I authorize with github education
image

**Comment by Linncharm** [comment]
@philipto

**Pull request closed without merging**
