### PR TITLE
Add Berufskolleg Essen Mitte

### PR DESCRIPTION
**Pull request by Flo082002**
Hi,
please add Berufskolleg Essen Mitte
[https://www.bkmitte-essen.de/](url)

### CODE REVIEW

**Comment by philipto** [comment]
@Flo082002 First stage of verification passed, official domain is [bkmitte-essen.de](https://bkmitte-essen.de) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Flo082002 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@Flo082002 You might miss my previous comment. Please react.

**Comment by Flo082002** [comment]
Halo,

Berufskolleg Essen Mitte doesn't have It courses. I thought that I could get Jetbrains-Student, because I am a Student.
I planned to use Clion for my hobby projects.
I didn't know that you have to be an IT Student to get Jetbrains-Student.

Is there another way to get CLion as a non-IT-Student for free?

Best Regards
Florian

**Comment by philipto** [comment]
@Flo082002 Yes, please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students. If the decision on the matter will not satisfy you, please send an email to community-support@jetbrains.com with more detailed explanation on why you need CLion. 

Please notice that you also can use trial versions and EAP versions. They are free for everybody. You can ask to prolong a trial version by email to sales@jetbrains.com.

I have to close the request without merging.
Thank you for your understanding!

**Pull request closed without merging**
