### PR TITLE
nabeul

### PR DESCRIPTION
**Pull request by amoryassine**
Higher Institute of Technological Studies of Nabeul

### CODE REVIEW

**Comment by philipto** [comment]
@amoryassine Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by amoryassine** [comment]
The school official website URL is: http://www.isetn.rnu.tn/

URL of a page where a long-term (>1 year) IT related course is offered:  http://www.isetn.rnu.tn/fra/pages/254/D%C3%A9veloppement-des-Syst%C3%A8mes-d-informationD%C3%A9veloppement-des-Syst%C3%A8mes-d-information

URL of a page showing that the university recognizes the domain as an official email domain for the enrolled students: http://www.isetn.rnu.tn/fra/pages/163/Organigramme-de-formationOrganigramme-de-Formation This is the page of the student organization, look email addresses on the left section.

**Comment by philipto** [comment]
@amoryassine Thank you for the clarification!

Could you please upload a screenshot of what do you mean at http://www.isetn.rnu.tn/fra/pages/163/Organigramme-de-formationOrganigramme-de-Formation. I don't see any email there. It may be because I am not logged in there.

Thank you!

**Comment by philipto** [comment]
@amoryassine You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@amoryassine I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
