### PR TITLE
added school info file

### PR DESCRIPTION
**Pull request by ArielSegal1**
[amit365.txt](https://github.com/JetBrains/swot/files/10837565/amit365.txt)

### CODE REVIEW

**Comment by ArielSegal1** [comment]
added school info file

**Comment by philipto** [comment]
@ArielSegal1 file/lib/domains/il/org/amit365.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@ArielSegal1 First stage of verification passed, official domain is [amit.org.il](https://amit.org.il) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://mea.amit.org.il/

**Comment by philipto** [comment]
@ArielSegal1 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
