### PR TITLE
test-pr

### PR DESCRIPTION
**Pull request by ncaps**
add Yakutsk College of Innovative Technologies

School official website: https://www.yakitschool.ru/
school address: 677000, Republic of Sakha (Yakutia), Yakutsk, 203rd microdistrict, st. Larionova, 4
School IT course URL: https://www.yakitschool.ru/sveden/education
Domain mailbox: https://www.yakitschool.ru/sveden/struct

### CODE REVIEW

**Comment by philipto** [comment]
@ncaps Thank you for the request. Could you please explain why the college registered a new domain while it has an old one with a website looking like a full copy? The names are pretty similar. Could you please provide us with a copy of a document that officially confirms that this domain belongs to the college?

**Comment by 67440** [comment]
Hello, this domain is for students of our college. It was a domain name registered by an institution at that time. Please check whios. I can’t provide supporting documents.

**Comment by philipto** [comment]
@ncaps Please provide the supporting documents. The names of the registrant in WHOIS are different for this domain and the domain that seems to be the official one, at least previously. You can ask your school administration for a document and upload the copy of it as the comment to this request. Thank you!

**Comment by ncaps** [comment]
I can't provide it, please close this request

**Comment by philipto** [comment]
@ncaps Yes, I close the request. Please apply for a free educational license with an official document that proves that you are a student. You can do it using the "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding.

**Pull request closed without merging**
