### PR TITLE
szkolaprogramowania.cybertree.pl

### PR DESCRIPTION
**Pull request by fenomenologia**

### CODE REVIEW

**Comment by philipto** [comment]
@fenomenologia First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/szkola.programowania.cybertree/

**Comment by philipto** [comment]
@fenomenologia Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by fenomenologia** [comment]
*Official school website:*

*https://szkolaprogramowania.cybertree.pl/
<https://szkolaprogramowania.cybertree.pl/>*
*School address:*
*Szkoła Programowania Cybertree*
*ul. św. Heleny 10*
*33-300 Nowy Sacz*
*Poland*
URL with courses
*https://szkolaprogramowania.cybertree.pl/programista-aplikacji-internetowych-web-developer/
<https://szkolaprogramowania.cybertree.pl/programista-aplikacji-internetowych-web-developer/>*

Kind regards,
Leszek Skocki


pon., 15 maj 2023 o 11:18 Philip Torchinsky ***@***.***>
napisał(a):

**Comment by philipto** [comment]
@fenomenologia First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/szkola.programowania.cybertree/

**Comment by philipto** [comment]
@fenomenologia Thank you for providing the details!

Regrettably, I have to close the request without merging, because this organization is a training center, not a college, nor a university. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot).

Please apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses.

Thank you for your understanding!

**Pull request closed without merging**
