### PR TITLE
Create iae-toulouse

### PR DESCRIPTION
**Pull request by FHSpam2**
This is the school of management of Toulouse 1 Capitole university
http://www.iae-toulouse.fr/

### CODE REVIEW

**Comment by zweizwei** [comment]
@FHSpam2 please add .txt extension to the committed file and i'll add the domain

**Comment by FHSpam2** [comment]
Done!
Thanks (and sorry for not being thorough)

**Comment by philipto** [comment]
@FHSpam2 I am sorry for processing your pull request for a long time. Could you please clarify whether the name of the university is correct in your pull request? Iae-toulouse.com website says that the official name of the university is Université Toulouse 1 Capitole (Ecole de management). I am ready to merge the pull request as soon as you confirm the name. Thank you!

**Comment by philipto** [comment]
@FHSpam2 I merged the pull request because it fits formal requirements anyway. Please feel free to change the name of the university if necessary by opening another pull request. Thank you!

**Pull request merged**
