### PR TITLE
Add ICBT Campus

### PR DESCRIPTION
**Pull request by Kithru**

### CODE REVIEW

**Comment by philipto** [comment]
@Kithru Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Kithru Thank you for the details!
Your request contains a file `lib/domains/lk/icbtcampus.txt`
It represents a domain **icbtcampus.lk**.
You say your school email address template is username@icbtcampus.**edu**.lk
Which domain you wish to add, **icbtcampus.lk** or **icbtcampus.edu.lk**?

**Comment by Kithru** [comment]
'icbtcampus.edu.lk' this one.

**Comment by philipto** [comment]
@Kithru Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
