### PR TITLE
Create alumno.txt

### PR DESCRIPTION
**Pull request by lafuented**
Alumni domain Montemorelos University

### CODE REVIEW

**Comment by philipto** [comment]
@lafuented First stage of verification passed, official domain is [um.edu.mx](https://um.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@lafuented Please clarify who receive the email addresses in this domain: those who study in the university currently, or those who already graduated from the university?

**Comment by lafuented** [comment]
Hi, in this domain have active students and for one year more from graduated

**Comment by philipto** [comment]
@lafuented Thank you for the clarification! I am closing this request in favor to the request #15658, which covers all subdomains of um.edu.mx. The newer request will be reviewed soon. Thank you.

**Pull request closed without merging**
