### PR TITLE
Update emsi-edu.txt

### PR DESCRIPTION
**Pull request by MERZAK-X**
>Added name in English and Abbreviation name (Abkürzung) :octocat:

### CODE REVIEW

**Comment by philipto** [comment]
@MERZAK-X Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain emsi-edu.ma which you are submitting as an official email domain for the students.

**Comment by MERZAK-X** [comment]
>@philipto the domain is already added, I'm just updating the file for alternative names

image

image

**Comment by MERZAK-X** [comment]
>@philipto here's the initial commit #2240

**Comment by philipto** [comment]
@MERZAK-X Thank you for the clarification and update. Pull request merged.
I am sorry, I did not notice at the first glance that this is just an update. Thank you for using the tools, and have a happy coding!

**Comment by MERZAK-X** [comment]
Thank you @philipto it's always my pleasure to collaborate.

**Pull request merged**
