### PR TITLE
Create erasmusmc.txt

### PR DESCRIPTION
**Pull request by roshchupkin**

### CODE REVIEW

**Comment by zweizwei** [comment]
I'm sorry for the delay. Please provide the link to the page, describing long term (>1year) IT related programs, the school provides. Thanks.

**Comment by roshchupkin** [comment]
Dear Elena,

I am PhD student at Erasmus Medical Center (http://www.erasmusmc.nl/). Here
is the link to our research group http://bigr.nl/.
I would like to use your software products during my research project,
therefore I decided to apply for "free for students" option.
But I didn't find our university in the list on github.

Please, let me know, if such option doesn't work for me.

Thank you in advance,
Best,
Gennady.

2015-03-02 15:46 GMT+01:00 Elena Ganenkova <notifications@github.com>:

**Comment by zweizwei** [comment]
The school itself doesn't seem to qualify for student access (i don't see any full-term courses there), however we can require an individual access for you through sales team, please let me know your email and I'll forward your request to them. Thanks!

**Comment by roshchupkin** [comment]
My email: g.roshchupkin@erasmusmc.nl

Thank you very much!
Best,
Gennady.

**Pull request closed without merging**
