### PR TITLE
Add DK roskildegymnasium.txt

### PR DESCRIPTION
**Pull request by Seba244c**
The official website of the gymnassium / school: [https://www.roskilde-gymnasium.dk/](https://www.roskilde-gymnasium.dk/)

### CODE REVIEW

**Comment by Seba244c** [comment]
For reference email format for student: rg<first-2-letters-of-name><3-numbers>@roskildegymnasium.dk
For reference email format for student: rg<first name first letter><last name first letter>@roskildegymnasium.dk

**Comment by Seba244c** [comment]
Example course with informatics & programming classes [https://www.roskilde-gymnasium.dk/bliv-elev/stx/politik-og-samfund/12-politik-og-samfund/](https://www.roskilde-gymnasium.dk/bliv-elev/stx/politik-og-samfund/12-politik-og-samfund/)

**Comment by Seba244c** [comment]
Hi, turns out we have another mail domain: roskilde-gym.dk
Example rgsse@roskilde-gym.dk

**Comment by philipto** [comment]
@Seba244c lib/domains/dk/roskilde-gym.dk: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Seba244c** [comment]
@philipto ups, that was a mistake. It matches the format now.

**Pull request closed without merging**
