### PR TITLE
Added UUST

### PR DESCRIPTION
**Pull request by Waljunye**
Hello JetBrains, My name is Matvey. I'am from Russia, please, help me, i need your products! I'm trying to avoid mobilization and saving money to move from Russia. Your products will help me a lot. With their help, I will gain the necessary knowledge and finally go to a place where they won’t give me a rifle and tell me “shoot your brother.”

### CODE REVIEW

**Comment by philipto** [comment]
@Waljunye First stage of verification passed, official domain is [uust.ru](https://uust.ru) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Waljunye** [comment]
URL: https://uust.ru/
Street: Volga Federal District, Republic of Bashkortostan, Ufa, st. Zaki Validi, house 32, Russian Federation
Course: https://uust.ru/vmk/vmk_bib/#bib

**Comment by ilmirinze** [comment]
Hello! I am in the same university as well. Are there any updates? When the pull request will be merged?

**Comment by philipto** [comment]
@Waljunye @ilmirinze Unfortunately, your request cannot be processed further because JetBrains doesn’t provide products or services to territories subject to applicable EU, UN, or US sanctions or under comprehensive export control restrictions due to legal, compliance, and other commercial risks.

**Pull request closed without merging**
