### PR TITLE
Create leerling.txt

### PR DESCRIPTION
**Pull request by ljavanbeek**
Website, nsg-groenewoud.nl
Mail domain, leerling.groenewoud.nl

### CODE REVIEW

**Comment by philipto** [comment]
@ljavanbeek Could you please give us an URL of a page (or a documnent/screenshot) saying that leerling.groenewoud.nl domain is owned by your school? The school website says that contact email is in another domain - @nsg-groenewoud.nl

**Comment by philipto** [comment]
@ljavanbeek You might miss my previous comment. Please reply.

**Comment by ljavanbeek** [comment]
https://www.sidn.nl/whois?q=Groenewoud.nl

Sidn is the Dutch company who handles the domain names. At that URL you can see that the domain is owned by Scholengroep Rijk van Nijmegen, the company that owns my school.
I hope this is enough.

**Comment by philipto** [comment]
@ljavanbeek Things look a bit odd from my point of view. Could you please explain the whole picture?
1) Your school is owned by the company, Scholengroep Rijk van Nijmegen, right? Is it mentioned somewhere at the official website - https://nsg-groenewoud.nl? 
2) As far as I understand it from Google translation of this page: https://nsg-groenewoud.nl/schoolorganisatie/wie-is-wie/, the school is more or less usual school, combining secondary and high education. 
Why the school is owned by a company? Is it typical for a school in Netherlands to be owned by a company, instead of being owned by a municipality, community, university, etc.?
3) Is there any document (page, .pdf, screenshot, etc.) which confirms that students use groenewoud.nl as an email domain? Whois data are fine, but for some reason I cannot get an info for nsg-groenewoud.nl at sidn.nl. If you can, please attach a screenshot to your comment.

**Pull request closed without merging**
