### PR TITLE
INTECAP

### PR DESCRIPTION
**Pull request by Reginaldo08**
Please add my School

School website URL
https://intecap.edu.gt/

School street address
Street Doroteo Guamuch Flores 8-79, zona 5, Guatemala

URL of an IT-related long-term course page on the website https://formacion.intecap.edu.gt/dashboard/detalles/32

Proof of official email domain recognition.
2021-081810@intecap.edu.gt

### CODE REVIEW

**Comment by Reginaldo08** [comment]
School website URL
https://intecap.edu.gt/

School street address
Street Doroteo Guamuch Flores 8-79, zona 5, Guatemala

URL of an IT-related long-term course page on the website
https://formacion.intecap.edu.gt/dashboard/detalles/32

Proof of official email domain recognition.
2021-081810@intecap.edu.gt

**Comment by Reginaldo08** [comment]
[INTECAP.zip](https://github.com/JetBrains/swot/files/10984336/INTECAP.zip)

**Comment by philipto** [comment]
@Reginaldo08 I corrected and merged the request. Thank you.

**Comment by Reginaldo08** [comment]
Thanks Philip

**Pull request merged**
