### PR TITLE
Create skolers.txt

### PR DESCRIPTION
**Pull request by deyyanl**
Ministarstvo prosvjete i kulture Republike Srpske
Ministry of Education and Culture of Republic of Srpska

https://skolers.org
Trg Republike Srpske 1, 78 000 Banja Luka, Republic of Srpska, Bosnia and Herzegovina.

All emails originating from **skolers.org** and ***.skolers.org** are associated with:
- Students (Elementary school and high-schools only, universities have their own domain)
- Teachers and professors 
- Associate co-workers related in the field of education

### CODE REVIEW

**Comment by deyyanl** [comment]
Elektrotehnička škola "Nikola Tesla" Banja Luka
Electrotechnical school "Nikola Tesla" Banja Luka

https://ets.rs.ba
Jevrejska 48, 78 000 Banja Luka, Republic of Srpska, Bosnia and Herzegovina

**Comment by philipto** [comment]
@deyyanl lib/domains/ba/rs/ets: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by deyyanl** [comment]
@philipto Sorry, didn't catch the missing extension. Now it should be fine.

**Comment by philipto** [comment]
@deyyanl Pull request corrected and merged. Just one of the two domains were added.

The domain of the ministry does not belong to a particular school. It belongs to an umbrella institution (such as Ministry of Education or similar government body). We cannot add umbrella institutions domain to this repository. If you have an email address from the ministry only, please apply for free educational license with an official document that proves your student status. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students. Thank you for your understanding!

**Pull request merged**
