### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by imharryz**

### CODE REVIEW

**Comment by philipto** [comment]
@imharryz The first verification stage is complete: the official domain for  **Lancing College** is [www.lancingcollege.co.uk](https://www.lancingcollege.co.uk), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.lancingcollege.co.uk/lancing-society-ol-club/contact-us

**Comment by imharryz** [comment]
@philipto
Proof of a course related to computer science thats more than 1 year long below - Page 9
https://www.lancingcollege.co.uk/sites/default/files/inline-files/SixthFormChoice/Lancing_College_Sixth_Form_Choices_2024_WEB.pdf

**Comment by philipto** [comment]
@imharryz The first verification stage is complete: the official domain for  **Lancing College** is [www.lancingcollege.co.uk](https://www.lancingcollege.co.uk), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.lancingcollege.co.uk/lancing-society-ol-club/contact-us

**Comment by philipto** [comment]
@imharryz Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
