### PR TITLE
Create tvu-onschool.txt

### PR DESCRIPTION
**Pull request by kiennta**
Add my school to JetBrain

### CODE REVIEW

**Comment by kiennta** [comment]
Thanks you

**Comment by philipto** [comment]
@kiennta Please describe this school in more details. Is it purely online? If yes, what is the education cost at the school? How much does the school charge for the education there? How many courses you must take to finish the education at the school? Is it possible to take just one course and then leave the school? How long it takes to complete one course?

**Comment by kiennta** [comment]
Certainly! Let me provide you with more details about *Tra Vinh
University* (TVU)
based on the information available:

   1.

   *Overview*:
   - Tra Vinh University (TVU) is a *public university* located in Tra Vinh
      Province, Vietnam.
      - TVU is part of the *international university and college
      association in Canada* and is also a member of the *CDIO organization*
      . It ranks among the top 200 green and sustainable universities
      globally according to UI Greenmetric World University Rankings and is
      recognized for its positive contributions to society
      <https://www.tvu.edu.vn/>
   2.

   *Academic Programs*:
   - TVU offers a diverse range of programs across various fields. These
      include *39 postgraduate programs*, *55 undergraduate programs*, and *1
      college-level program*. The university focuses on areas such as
      agriculture, technology, healthcare, foreign languages, and more
      <https://www.tvu.edu.vn/>
      - The programs cover disciplines like Agriculture and Aquatic
      Resources, Engineering and Technology, Medicine and Pharmacy, Foreign
      Languages, Culture and Arts (Khmer culture), Economics and Law, Applied
      Chemistry, Education, Public Administration, Political Science, Basic
      Sciences, and Dentistry.
   3.

   *Education Cost*:
   - The tuition fees at TVU vary depending on the program and level of
      study. For the academic year 2022-2023, the fees ranged from *16,400,000
      VND to 40,000,000 VND* per year, depending on the specific field of
      study <https://www.tvu.edu.vn/>
      - Please note that these figures are subject to change, so it’s
      advisable to check the official TVU website or contact the university
      directly for the most up-to-date information.
   4.

   *Number of Courses*:
   - TVU offers a variety of courses, but the exact number of courses
      required to complete a degree depends on the specific program. Generally,
      students need to complete a set number of credits (or courses)
to graduate.
      - If you’re interested in a specific program, I recommend checking
      the official TVU website or contacting the university’s admissions office
      for detailed information on the curriculum and course requirements.
   5.

   *Taking Individual Courses*:
   - While TVU primarily follows a structured program, it’s essential to
      inquire directly with the university about the possibility of taking
      individual courses without pursuing a full degree.
      - Some universities allow students to take individual courses as
      non-degree-seeking students, but policies may vary. TVU’s
guidelines would
      provide clarity on this matter.
   6.

   *Course Duration*:
   - The duration of each course at TVU can vary. Typically, undergraduate
      courses last for one semester (approximately 15 weeks), while
postgraduate
      courses may span multiple semesters.
      - For precise information on course duration, refer to the specific
      program’s curriculum or contact the university.

**Comment by philipto** [comment]
@kiennta  Thank you for the clarifications. Pull request merged.

**Pull request merged**
