### PR TITLE
Create lakehead

### PR DESCRIPTION
**Pull request by priyank-carpe-noctem**

### CODE REVIEW

**Comment by philipto** [comment]
@priyank-carpe-noctem Could you please rename the file to `lib/domains/ca/lakehead.txt` to reflect this repository rules? Thank you!

**Comment by philipto** [comment]
@priyank-carpe-noctem I am sorry, didn't you miss my previous message? Do you still need the email domain to be added to this repository?

**Comment by priyank-carpe-noctem** [comment]
I see there is no lakehead.txt

**Comment by philipto** [comment]
@priyank-carpe-noctem Lakehead University is listed in the repository as **lakeheadu.ca**. It is already represented by the file `lib/domains/ca/lakeheadu.txt`. As for lakehead.ca, there is no mail server accepting emails for this domain. I mistakenly merged your pull request, but then removed `lakehead` file. Please comment if you still can not get your free license using your university email address. Thank you.

**Pull request merged**
