### PR TITLE
Add University of the Chinese Academy of Sciences

### PR DESCRIPTION
**Pull request by Alex1989Wang**
- Home Page: https://english.ucas.ac.cn/ 
- School of Computer Science and Technology: https://scce.ucas.ac.cn/index.php/en/
- Email Proof: any "Contacts Us" section in either one of the websites listed above

### CODE REVIEW

**Comment by Alex1989Wang** [comment]
@philipto This pull request was submitted 6 days ago. Anything more need to be provided?

**Comment by philipto** [comment]
@Alex1989Wang Thank you for the reminder. We are performing some additional checks regarding the current number of students and educational courses available at the Institute. This is not a university, thus we have to check if there are ongoing educational courses there indeed with substantial number of students. The webpage at https://scce.ucas.ac.cn/index.php/en/ contains announcements as old as dated back to 2012 (7 years ago!) and courses description valid for 2015 (4 years ago). Thank you for your patience and understanding.

**Comment by Alex1989Wang** [comment]
The website [https://scce.ucas.ac.cn/index.php/en/]( https://scce.ucas.ac.cn/index.php/en/) in English seems to be outdated. The [Chinese version](https://scce.ucas.ac.cn/index.php/zh-CN/) of it has some up-to-date information. But the courses description hasn't been updated for 5 years ... that's true.

**Comment by philipto** [comment]
@Alex1989Wang I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Pull request merged**
