### PR TITLE
Create vcconnect.txt

### PR DESCRIPTION
**Pull request by greg00139**
Added Varsity College

### CODE REVIEW

**Comment by zweizwei** [comment]
the college website seems to be www.varsitycollege.co.za - could you please provide some confirmation that vcconnect.co.za also belongs to college? thanks!

**Comment by greg00139** [comment]
Good Morning

What specific details do you require for the confirmation? Will a simple
letter from Varsity College with their letter head a signature suffice?

Thanks

Greg Wright

**Comment by greg00139** [comment]
Good Afternoon

I have still not heard from you in regard to what particular information is required to prove that vcconnect.co.za belongs to varsity college.

Please can you advise me in this.

Thanks

Greg Wright

**Comment by zweizwei** [comment]
I'm very sorry for the delay. Yes a confirmation letter should do fine - please send one to classroom@jetbrains.com and i'll add the domain. Thanks for your help!

**Comment by zweizwei** [comment]
I've got the letter, thank you - I'm adding the domain then.

**Pull request merged**
