### PR TITLE
abafr.txt

### PR DESCRIPTION
**Pull request by marpag**

### CODE REVIEW

**Comment by philipto** [comment]
@marpag Could you please clarify which domain you wish to add, and what is the official website URL of the school which owns the domain?

**Comment by philipto** [comment]
@marpag You might miss my previous comment. Please reply.

**Comment by marpag** [comment]
Oh, sorry.
domain: accademiabellearti.fr.it
website: http://www.accademiabellearti.fr.it

**Comment by philipto** [comment]
@marpag Thank you for the update! The website seems to belong to an art academy. Could you please give us a link to a long-term (>1 year) IT-related course which the Academia offers to the students? If such a course exists, please rename lib/domains/it/fr/accademiabellearti to lib/domains/it/fr/accademiabellearti.txt. If the course does not exist, we'll need to understand what is the reason for the students to request a free license for professional developers tools. Thank you!

**Comment by marpag** [comment]
Hi,
the most interested course is multimedia design (3+2 years) (http://en.accademiabellearti.fr.it/media-art/). Here we use javascript, python and processing for client side UI, 3D modeling, mobile app and interaction design. We also have a graphic design course (3+2 years) (http://en.accademiabellearti.fr.it/graphic-design) where we use mainly javascript for web design and svg animations. I personally intend to introduce a Java/Net course next year in order to make my students understand the "server side problem" of their projects.
I've renamed accademiabellearti file. Thank you for your time.

**Comment by philipto** [comment]
@marpag Thank you for the clarification!
> I've renamed accademiabellearti file.

No, you actually did not, the file name in the request remained lib/domains/it/fr/accademiabellearti until I just renamed it to lib/domains/it/fr/accademiabellearti.txt. 
Anyway, the pull request merged. Feel free to start requesting licenses.

**Pull request merged**
