### PR TITLE
NEW DOMAIN For ESTICE HIGHSCHOOL

### PR DESCRIPTION
**Pull request by Frenchy62620**
For my project please

### CODE REVIEW

**Comment by philipto** [comment]
@Frenchy62620 Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Frenchy62620** [comment]
Hi Philip, the different URLs i could provide,:
ESTICE is Linked with another School [ESPAS](http://ecole-espas.fr/) and ESTICE uses the domain of this school . All these school make part of [Catholic University of LILLE](https://www.univ-catholille.fr/)

1) URL of School:   [ESTICE](http://estice.fr/)

2) URL showing the different course offered (5 year of course to have the Diplom), in the third year we have course about finance and need to develop application [Program of the third year for example](http://estice.fr/le-programme-estice-3/)

3) URL showing the domain using for Webmail for example [KWARZ mail](http://accueil.etud-espas.fr/owncloud/)   . As you see its the domain of the other school ESPAS linked to ESTICE

regards

**Comment by philipto** [comment]
@Frenchy62620 Thank you for the clarification. Pull request merged.

**Comment by Frenchy62620** [comment]
Thanks Philip, and new happy year!

**Pull request merged**
