### PR TITLE
Add Scalby School

### PR DESCRIPTION
**Pull request by MrShrekThird**

### CODE REVIEW

**Comment by philipto** [comment]
@MrShrekThird You might miss my previous comment. Please react.

**Comment by MrShrekThird** [comment]
School Website: https://www.scalbyschool.org.uk
School Address: Scalby School,
                Fieldstead Crescent,
                Newby,
                Scarborough,
                YO12 6TH,
                England

**Comment by philipto** [comment]
@MrShrekThird Thank you!

The URL you suggested redirects to https://www.scalby.coastandvale.academy, and the contact page https://www.scalby.coastandvale.academy/contact/ says that the email domain for the academy is **sc.coastandvale.academy**. It is different from the domain **sc.academy** you wish to add to the trusted list.

The domain **sc.academy** exists, but I need more proof to ensure that the domain belongs to the school.

Please provide us with a proof, which shows that the school recognizes the domain **sc.academy** you are submitting as an official email domain for the students.

You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

Thank you!

**Comment by MrShrekThird** [comment]
How do I say it's sc.coastandvale.academy?

**Comment by philipto** [comment]
@MrShrekThird If you wish to add the domain `sc.coastandvale.academy` to the trusted list, the filename in this request has to be `lib/domains/academy/coastandvale/sc.txt`

Do you wish me to rename the file?

**Comment by MrShrekThird** [comment]
Yes please, thank you very much

**Comment by philipto** [comment]
@MrShrekThird Pull request corrected and merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.** Thank you.

**Comment by MrShrekThird** [comment]
Thank you

**Pull request merged**
