### PR TITLE
Create infoplus.txt

### PR DESCRIPTION
**Pull request by alakameljebali**

### CODE REVIEW

**Comment by philipto** [comment]
@alakameljebali Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school.

**Comment by alakameljebali** [comment]
Ok so that's the link of the school's website http://infoplus.tn/

**Comment by alakameljebali** [comment]
Sorry for the misunderstand.
These are links that you need:
http://infoplus.tn/details-bts-infor-gestion.php
http://infoplus.tn/details-bts-reseaux.php

**Comment by philipto** [comment]
@alakameljebali Thank you for the clarification. Pull request merged.

**Pull request merged**
