### PR TITLE
Adding business-school.academy

### PR DESCRIPTION
**Pull request by bthouverez**

### CODE REVIEW

**Comment by philipto** [comment]
@bthouverez Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@bthouverez You might miss my previous comment. Please react.

**Comment by bthouverez** [comment]
Hello, here is the missing data : 
* the school official website URL : https://business-school.academy redirects to https://bs-beaujolais.fr which is the official website URL

* the school street address, including city and country : Our school is located at this address:
96 rue Henri Depagneux,
69400 Limas, FRANCE

* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course : following page on official presents the BTS SIO, a 2 years course, mainly about computer science, programming, networks and cybersecurity https://www.bs-beaujolais.fr/bts-sio-i/

* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students: our sysadmin is currently looking for such a proof, i will come back here once he gives it to me

**Comment by philipto** [comment]
@bthouverez Thank you! Yes, please, provide the proof.

You can provide us with any of the following as the proof:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by bthouverez** [comment]
Here are some screenshots of some of our students with their mail used on Microsoft Teams. Will it be enough ?

MicrosoftTeams-image (1)
MicrosoftTeams-image
MicrosoftTeams-image (2)

**Comment by philipto** [comment]
@bthouverez  Thank you for the clarifications. Pull request merged.

I removed your previous comment, because it was a sufficient proof but exposed some personal information publicly. Please start requesting the licenses in about an hour. It is important to give our system time to propagate the changes.

Thank you!

**Comment by bthouverez** [comment]
@philipto Thank you for merging and for deleting previous comment. I am very happy that our students will be able to use your awesome JetBrains IDEs !

**Pull request merged**
