### PR TITLE
Add Holberton School

### PR DESCRIPTION
**Pull request by papamuziko**
The school official website URL: https://www.holbertonschool.com

And access to our Syllabus: https://www.holbertonschool.com/syllabus/download

Thank you!

### CODE REVIEW

**Comment by philipto** [comment]
@papamuziko lib/domains/com/holbertonschool: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by papamuziko** [comment]
> @papamuziko lib/domains/com/holbertonschool: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.

Sorry, my bad. Even in bold, I missed the ".txt extension is mandatory"

Sorry about that - Thank you

**Comment by philipto** [comment]
@papamuziko Thank you for the update! 
Could you please confirm that you do have a long-term (> 1 year) course? If yes, could you please tell me where I can see the one announced publicly (say, on your website)?

Thank you!

**Comment by papamuziko** [comment]
Hi @philipto , 
Sure, we have a 2-year program of Software engineering and you can find all details here:
- Our 2-year pathway: https://www.holbertonschool.com/pathways
- How we are building our first year of Foundations: https://blog.holbertonschool.com/building-a-curriculum-foundations/
- How we are building the second year of Specialization: https://blog.holbertonschool.com/building-a-curriculum-specializations/

Is it good for you?

Thank you

**Comment by philipto** [comment]
@papamuziko Thank you for the clarification. Yes, it's exactly what was necessary. Pull request merged.

**Pull request merged**
