### PR TITLE
Shaheed Zulfikar Ali Bhutto Institute of Science and Technology (SZAB…

### PR DESCRIPTION
**Pull request by MuhammadHamzaRajput**
…IST) islamabad, Pakistan
Here is the university link :
https://www.szabist-isb.edu.pk/Introduction.asp

### CODE REVIEW

**Comment by philipto** [comment]
Official website says that the university domain is szabist.edu.pk. Please provide a proof that the school recognizes a domain which you submit as an official domain for the students.

**Comment by MuhammadHamzaRajput** [comment]
Szabist univerty use [szabist-isb.edu.pk] for teachers and admin staff like
dr.tazeen@szabist-isb.edu.pk . Szabist university use [szabist-isb.pk] for
students like 18101136@szabist-isb.edu.pk

Isb - stand for - Islamabad
pk - stand for - Pakistan
18101136 is the university roll number of the student.

**Comment by MuhammadHamzaRajput** [comment]
Szabist univerty use [szabist-isb.edu.pk] for teachers and admin staff like dr.tazeen@szabist-isb.edu.pk . Szabist university use [szabist-isb.pk] for students like 18101136@szabist-isb.pk

Isb - stand for - Islamabad
pk - stand for - Pakistan
18101136 is the university roll number of the student. 


Sent from Mail for Windows 10

**Comment by philipto** [comment]
@MuhammadHamzaRajput Thank you for the clarification. Could you please provide us with a **proof** which confirms your words? It has to be a .pdf document or better a page at the official website which says that Szabist university uses szabist-isb.edu.pk for teachers and admin staff, and szabist-isb.pk for students.

**Comment by philipto** [comment]
@MuhammadHamzaRajput You might miss my previous comment. Please react.

**Comment by MuhammadHamzaRajput** [comment]
https://zabdesk.szabist-isb.edu.pk/

My university site is down. They are not replying to me due server error. Once they replied, I will send you required thing.

**Comment by MuhammadHamzaRajput** [comment]
I was need an IDE for python development. Someone suggest me JetBrains IDE for development. When i come to your site, you are offering student package so I applied for it and wait for the couples of days  but it taking to much time. Now I'm using [visual studio code](https://code.visualstudio.com/) for development so I don't need JetBrains IDE now.

**Comment by philipto** [comment]
@MuhammadHamzaRajput I am very sorry for a delay with processing your request. 

JetBrains grants free educational subscription for JetBrains tools to students and teachers, and we have to be sure that a person who requests the free subscription is a teacher or a student indeed. This is why we need to check an eligibility of every email domain suggested for this list of educational domains known to JetBrains.

Shall you decide that a JetBrains IDE suits your needs better, feel free to request your free license using "OFFICIAL DOCUMENT" tab at jetbrains.com/shop/eform/students, and email to support@jetbrains.com if you have any troubles.

As far as I understand your last comment, you no longer wish to add a domain in question to this repository, and I have to close the request without merging because it's now impossible to check if the domain qualifies for this repository.

Thank you for the understanding!

**Pull request closed without merging**
