### PR TITLE
adding olas school to domain

### PR DESCRIPTION
**Pull request by mohfalha**

### CODE REVIEW

**Comment by philipto** [comment]
@mohfalha Please provide us with:
* the school full official name
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@mohfalha You might miss my previous comment. Please react.

**Comment by mohfalha** [comment]
Dear Philip

Sorry for the trouble.  in fact the school don't offer IT-related long term
course and i wasn't aware about this rule so kindly ignore my request

Regards

**Comment by philipto** [comment]
@mohfalha  Thank you for the clarifications. If you need a free educational license due to your own specific study subject, please feel free to apply with your official documents.

You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.
Thank you for the understanding!

**Pull request closed without merging**
