### PR TITLE
Create seu.txt

### PR DESCRIPTION
**Pull request by aalshrif90**
Adding a Domain for Saudi Electronic University.

https://www.seu.edu.sa/sites/en/Pages/main.aspx

### CODE REVIEW

**Comment by philipto** [comment]
@aalshrif90 I am sorry, JetBrains does not grant free licenses to online universities. However, I see that SEU has campuses and provides students with offline education too. What is SEU email policy? 
The problem with online students is that they potentially can enroll online, and then don't study but use their student email address. Does SEU prevent such use of their email addresses? 

Does SEU provide all students with email addresses in @seu.edu.sa domain, or online-only students have another email domain?

I appreciate if you clarify this issue, and depending on actual SEU policy we'll re-consider an ability to add SEU to this repository. Thank you for the understanding!

**Comment by philipto** [comment]
@aalshrif90 I am sorry, this request remains unanswered for a while. I have to close it. Please reopen if you have an update regarding the issues which I commented above. Thank you for the understanding!

**Comment by aalshrif90** [comment]
Hi @philipto,

I am sorry about the late reply I was busy with a lot of projects. Regarding your question of what teaching model we use is called blended learning, which means students have to attend campus lectures and online lectures, and their attendance is mandatory. As for the email is is given to students who are enrolled to the 4 year programme, such as CS or IT programmes. We do not provide online-only programmes, only blended.  


As for students who do not attend at least 70% of the on-campus lectures will be forced to drop-out and their email will be de-activated.

Best

p.s. I am a lecturer in this university and I teach programming so I want to explore multiple IDEs and give my students the best options and practices.

**Comment by philipto** [comment]
@aalshrif90 Thank you for clarification! If the university does not provide online-only education, it is no problem to add it to this repository. Your pull request is now merged. Thank you!

**Pull request merged**
