### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by LunaOctavio**

### CODE REVIEW

**Comment by LunaOctavio** [comment]
add the university "Centro Universitario Celsus" so that students and teachers have access to the free GetBrains tools

**Comment by LunaOctavio** [comment]
The page of my institution is https://www.unicuc.mx/inicio/

**Comment by philipto** [comment]
@LunaOctavio First stage of verification passed, official domain is [unicuc.mx](https://unicuc.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@LunaOctavio Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by LunaOctavio** [comment]
Thanks!!!

**Pull request merged**
