### PR TITLE
add Tianjin Bohai Vocational Technical College

### PR DESCRIPTION
**Pull request by longmanj**

### CODE REVIEW

**Comment by philipto** [comment]
@longmanj Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@longmanj You might miss my previous comment. Please react.

**Comment by longmanj** [comment]
> @longmanj You might miss my previous comment. Please react.

Hi. @philipto

**1. the school official website URL:**
http://www.tjbhzy.com/ (Note: access to this site is not very stable at this time.)
**2. the school street address, including city and country**
No. 508, Jinyu Road, Xiditou Town, Beichen District, Tianjin, China
**3. an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course**
Additional resources for the college's information:
https://baike.sogou.com/v272284.htm (a wikipedia like site)
**4. a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.**
 This email domain is for teaching staff.

**Comment by philipto** [comment]
@longmanj Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
