### PR TITLE
add IUA(Abidjan, Côte d'ivoire) to the request

### PR DESCRIPTION
**Pull request by bakidev**

### CODE REVIEW

**Comment by philipto** [comment]
@bakidev Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by bakidev** [comment]
> @bakidev Please provide us with:
> 
>     * the school official website URL
> 
>     * the school street address, including city and country
> 
>     * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> 
>     * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

@philipto 
1- School official website https://www.iuaci.org/
2 - School street adress: II Plateaux, 7ème Tranche, Rue L40,
Carrefour Cascades, Abidjan, Côte d’ivoire
3  -the official website where the school offers an IT-related long-term (>1 year) course: https://www.iuaci.org/faculte-des-sciences-et-technologiques/
4 - This is my own student email, kibafori.traore@iua.ci . Let me know if you want some additional informations

**Comment by philipto** [comment]
@bakidev  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by bakidev** [comment]
> @bakidev Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

@philipto thank you very much

**Comment by bakidev** [comment]
> @bakidev Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

@philipto thank you very much

**Pull request merged**
