### PR TITLE
Adding Scheiber Sándor Jewish School

### PR DESCRIPTION
**Pull request by bedomarci**
scheiber.hu - Primary domain of Scheiber Jewish school, Budapest.
somer.hu - Secondary domain for the school's youth club.
Both teachers and youth club is planning to use YouTrack to increase their performance, efficiency, accountability.
For further consultation please contact info@scheiber.hu and titkar@somer.hu

### CODE REVIEW

**Comment by philipto** [comment]
@bedomarci First stage of verification passed, official domain is [scheiber.hu](https://scheiber.hu) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@bedomarci Thank you for your request. I can add [scheiber.hu](https://scheiber.hu/) immediately. However there is no publicly available indication that somer.hu is owned by the school.

Moreover, if the purpose of adding the domains to the repository is using YouTrack, it's not what you need. To use YouTrack for free to plan activities at school, please send an email to community-support@jetbrains.com and explain your needs. 

A free educational subscription that is easier to get with the email domain registered in this repository **does not cover** YouTrack, it is for desktop tools only, such as PyCharm, IntelliJ IDEA and similar ones.

Please comment here whether you still need to add scheiber.hu to the repository. Thank you!

**Comment by bedomarci** [comment]
**Relation**
You are absolutely right. This is where things get complicated. Let me explain.
The Jewish school (Scheiber) is run by Budapest Jewish Federation (BZSH). It is even in its name. BZSH is member of The Federation of Hungarian Jewish Communities (MAZSIHISZ)
Hasomer Hacair is run by MAZSIHISZ too. 
Since there is only one public Jewish school and there is only one Jewish scout, they are bound together. This is how the scout is the youth club of the school. Due to bureaucratic organizational pathways, it takes a million years to update the website accordingly. Therefore I suggest you validate the entities via their offices: info@scheiber.hu and titkar@somer.hu

You can find the relation on the umbrella organizations website:
Formal institutions - https://mazsihisz.hu/kozossegeink/magyar-zsido-adatbazis/magyar-zsido-oktatasi-intezmenyek
Informal institutions - https://mazsihisz.hu/kozossegeink/magyar-zsido-adatbazis/magyar-zsido-civil-elet

Yes, please add scheiber.hu, JetBrains products will be needed in future IT education. (and somer.hu too once you validated).

**YouTrack**
YouTrack is the primary use for Scheiber and Somer, but not exclusively. Therefore I'll send a request to the given mail too.

**+1 school:**
In the process of registering, an other school of MAZSIHISZ would like to attach their domain. They have IT courses already.
Subpage of their IT courses: https://kulkertechnikum.hu/kepzes/szoftverfejleszto-es-tesztelo-technikus-szakma

Name: BZSH Külkereskedelmi Technikum 
Office e-mail: titkarsag@kulkergimi.hu 
Website: www.kulkertechnikum.hu
Domains: kulkergimi.hu, kulkertechnikum.hu


Thank you :)

**Comment by philipto** [comment]
@bedomarci  Thank you very much for the clarifications. Pull request merged.
The domains kulkergimi.hu, kulkertechnikum.hu are also added.

Please wait for an hour from this message sending time before requesting free licenses. It is necessary to have the changes propagated through our systems. Thank you!

**Pull request merged**
