### PR TITLE
Create usma.txt

### PR DESCRIPTION
**Pull request by evgusma**

### CODE REVIEW

**Comment by evgusma** [comment]
ФГБОУ ВО УГМУ Минздрава России
Ural State Medical University

**Comment by philipto** [comment]
@evgusma First stage of verification passed, official domain is [usma.ru](https://usma.ru) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@evgusma Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by evgusma** [comment]
Dear Sir.
Thank you for contacting us.
Computer science courses are offered on the official website edu.usma.ru. Sorry, you need to login to view. I send a screen with a course of medical informatics. If you need to log in directly to the site, I will send a temporary account.

***@***.***

Sincerely, @evgusma

**Comment by philipto** [comment]
@evgusma Thank you very much! Could you please upload a screenshot of a page with the course description with your browser as a comment at https://github.com/JetBrains/swot/pull/18196? You probably attached it to a reply by email, and GitHub strips out all attachments sent by email for security reasons. The screenshot is enough, no temporary account is necessary.

**Comment by evgusma** [comment]
Screen with a course of medical informatics
Page

**Comment by philipto** [comment]
@evgusma  Thank you for the clarifications. Pull request merged.

**Pull request merged**
