### PR TITLE
Create bthft.txt

### PR DESCRIPTION
**Pull request by yhcr-samrelins**

### CODE REVIEW

**Comment by philipto** [comment]
@yhcr-samrelins Please provide us with:
* the school official website URL
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you.

**Comment by philipto** [comment]
@yhcr-samrelins You might miss my previous comment. Please react.

**Comment by yhcr-samrelins** [comment]
I don't think I can provide you with what you need.

I'm a Senior Reserch Fellow with the NHS so the email domain I use for work isn't associated with the schools I teach for (University of Leeds "@leeds.ac.uk" and University of Bradford "@bradford.ac.uk"). The schools will have all the material you need (hence I believe they're already approved), but the NHS itself isn't a "public facing" teaching institution - all of the students we teach are referred via one or other of the universities that teach public health or medicine courses.

I don't know if you have any other suggestions - otherwise I'll just have to convert all my course materials to jupyterlab I guess!

**Comment by philipto** [comment]
@yhcr-samrelins Thank you for your patience while waiting for a review and processing your request. May I suggest you to apply for the free teacher license at https://www.jetbrains.com/shop/eform/students with your official dosuments confirming that you are a teacher. There is an OFFICIAL DOCUMENT tab at the page.

Regrettably, I cannot add the domain of a non-educational organization to this repository. 

I know universities of Leeds and Bradford very well, and their students for sure deserve to be taught with the best tools available. Therefore, if you have any difficulties with getting free license for JetBrains tools, please let me know by email to community-support@jetbrains.com. I will expeditiously assist you if anything goes wrong.

Thank you very much for your patience and understanding!

**Comment by philipto** [comment]
@yhcr-samrelins I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
