### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by goby22**
official website URL
- www.frateraureliosbo.cw (written in dutch) 
URL of a page on the official website with IT related course (written in dutch) 
- http://www.frateraureliosbo.cw/index.php/nl/ict-beheerder

### CODE REVIEW

**Comment by philipto** [comment]
@goby22 Could you please clarify if the students study more than 1 year in this school. Thank you!

**Comment by goby22** [comment]
> @goby22 Could you please clarify if the students study more than 1 year in this school. Thank you!

Yes they study 4 years.

**Comment by philipto** [comment]
@goby22 Thank you for the clarification. Pull request merged.

**Comment by goby22** [comment]
> 
> 
> @goby22 Thank you for the clarification. Pull request merged.

Thank you

**Pull request merged**
