### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by parasrawat007**

### CODE REVIEW

**Comment by philipto** [comment]
@parasrawat007 Please provide us with:
* the school official full name
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@parasrawat007 You might miss my previous comment. Please react.

**Comment by parasrawat007** [comment]
- the school official full name :  St. Andrews Institute of Technology &
   Management
   - the school official website URL :https://saitm.ac.in/
   - the school street address, including city and country  :9th Avenue,
   I.P.Extension, Patparganj, Delhi, 110092 , India
   - an URL of a page on the official website where the school offers an
   IT-related long-term (>1 year) course : https://saitm.ac.in/admission/
   - a proof, which shows that the school recognizes the domain you are
   submitting as an official email domain for the students : Official
   mail address ***@***.***

**Comment by philipto** [comment]
@parasrawat007  Thank you for the clarifications. Pull request merged.

**Pull request merged**
