### PR TITLE
Create wartburg

### PR DESCRIPTION
**Pull request by martinj2001**
This is a school in Rotterdam, and I think it' s really important that we should also have free access to PyCharm etc

### CODE REVIEW

**Comment by philipto** [comment]
@martinj2001 Thank you for the request! I am totally agree with you. Please rename lib/domains/nl/wartburg to lib/domains/nl/wartburg.txt in order to comply with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot). Thank you!

**Comment by philipto** [comment]
@martinj2001 You might miss my previous comment. Please reply.

**Comment by martinj2001** [comment]
Hi,

I did, but now i changed it, so it should work. 

Can I use it now, to login on Pycharm?

**Comment by philipto** [comment]
@martinj2001 I am sorry, you actually did not (at least in this request). However I just did it for you, just to make thinks a bit faster. Your pull request is merged and corrected.

Yes, you can request your free license for JetBrains tools at https://www.jetbrains.com/shop/eform/students in 30 minutes from now on, and use your license with PyCharm and any other desktop JetBrains tool. When you request a license, you'll receive several messages from JetBrains team, please read them, follow the links in them, and feel free to ask for support by email to support@jetbrains.com if you have any troubles. Thank you!

**Pull request merged**
