### PR TITLE
lsdonegani

### PR DESCRIPTION
**Pull request by mmoltoni**

### CODE REVIEW

**Comment by mmoltoni** [comment]
https://www.pololicealesondrio.edu.it/

Liceo Scientifico Donegani: Via Carlo Donegani, 3 - 23100 Sondrio ; Liceo Piazzi – Lena Perpenti: Via Samaden, 2 - 23100 Sondrio

https://www.pololicealesondrio.edu.it/pagine/scienze-applicate

**Comment by philipto** [comment]
@mmoltoni lib/domains/lsdonegani.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by mmoltoni** [comment]
@philipto i updated the request

**Comment by philipto** [comment]
@mmoltoni First stage of verification passed, official domain is [pololicealesondrio.edu.it](https://pololicealesondrio.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.pololicealesondrio.edu.it/pagine/progetto-liber-a-mente-1

**Comment by philipto** [comment]
@mmoltoni Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
