### PR TITLE
Request to add Citipointe Christian College

### PR DESCRIPTION
**Pull request by sadaramk**
College website address is https://citipointe.qld.edu.au/

### CODE REVIEW

**Comment by philipto** [comment]
@sadaramk Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@sadaramk You might miss my previous comment. Please react.

**Comment by sadaramk** [comment]
@philipto - thank you for your comments. I checked with my students and I believe Citipointe has 2 domains and both are valid. If you visit http://brisbane.coc.edu.au it redirects to https://citipointe.qld.edu.au. Technically both are valid as school uses COC.edu.au for primary and Qld.edu.au for secondary.

I am curious if I should raise another PR with second domain as well.

**Comment by sadaramk** [comment]
will be raising a new request

**Pull request closed without merging**
