### PR TITLE
Create univ-montpellier

### PR DESCRIPTION
**Pull request by JonathanMAS**

### CODE REVIEW

**Comment by JonathanMAS** [comment]
Montpellier University has changed their mail, here one of the new ones

**Comment by philipto** [comment]
@JonathanMAS Could you please tell us what is the new email domain? If it is univ-montpellier.fr (emails ends with @univ-montpellier.fr) , please rename lib/domains/fr/univ-montpellier to lib/domains/fr/univ-montpellier.txt in your request.

**Comment by philipto** [comment]
@JonathanMAS You might miss my previous comment. Please reply.

**Comment by philipto** [comment]
@JonathanMAS You might miss my previous comment. Please reply.

**Comment by JonathanMAS** [comment]
Sorry for the answer time. 
By the way, I had learn that the previous mails are still in use, so don't need to delete them. (The university of montpellier have 3 differents sections, and subsections. Teachers say me that the university network has a chaotic refactoring ^^' )

**Comment by philipto** [comment]
@JonathanMAS Thank you for the update! Pull request merged. Thank you!

**Pull request merged**
