### PR TITLE
Create calvijn.txt

### PR DESCRIPTION
**Pull request by kennysinkeler**

### CODE REVIEW

**Comment by kennysinkeler** [comment]
Email of teacher is xxxx@calvijn.nl
And of students is xxxxx@edu.calvijn.nl

**Comment by philipto** [comment]
@kennysinkeler Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by kennysinkeler** [comment]
Yes it is. Thuis school is 13+

**Comment by kennysinkeler** [comment]
This•

**Pull request merged**
