### PR TITLE
Add Schools of City Itumbiara - Go Brazil.

### PR DESCRIPTION
**Pull request by mauriliofilho**

### CODE REVIEW

**Comment by philipto** [comment]
@mauriliofilho First stage of verification passed, official domain is [itumbiara.go.gov.br](https://itumbiara.go.gov.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@mauriliofilho Do I understand correctly that the domain itumbiara.go.gov.br is for all schools in the province?

**Comment by mauriliofilho** [comment]
initialy yes! probably in final year this change! thus is for public school of city!

**Comment by philipto** [comment]
@mauriliofilho Pull request merged. 
Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of this Institute who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.
Thank you!

**Pull request merged**
