### PR TITLE
Create seu.txt

### PR DESCRIPTION
**Pull request by raselhossen125**
Please add my university. Southeast University

### CODE REVIEW

**Comment by raselhossen125** [comment]
Please add my university. Southeast University

**Comment by philipto** [comment]
@raselhossen125 First stage of verification passed, official domain for **Southeast University** is [seu.edu.bd](https://seu.edu.bd) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by raselhossen125** [comment]
> @raselhossen125 First stage of verification passed, official domain for **Southeast University** is [seu.edu.bd](https://seu.edu.bd) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Thank you.

**Comment by philipto** [comment]
@raselhossen125 Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by raselhossen125** [comment]
> @raselhossen125 Thank you for your patience while waiting for a review and processing your request. Pull request merged.
> **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

Ok. Thanks

**Pull request merged**
