### PR TITLE
Create liceocavour.txt

### PR DESCRIPTION
**Pull request by LIUKRAST**

### CODE REVIEW

**Comment by philipto** [comment]
@LIUKRAST First stage of verification passed, official domain is [liceocavour.edu.it](https://liceocavour.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@LIUKRAST Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by LIUKRAST** [comment]
I'm sorry for opening again this pull req. I tried to add my email address but it says it's not valid
image

**Comment by philipto** [comment]
Hello!Please wait an hour and try again.Changes take time to propagate. Thank you!On 16. Jan 2024, at 21.38, LIUKRAST ***@***.***> wrote:﻿
I'm sorry for opening again this pull req. I tried to add my email address but it says it's not valid
image.png (view on web)

**Pull request merged**
