### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by UlanbekSadybakasov**
Dear Support

The URL: ucentralasia.org

As per the Email Use Policy, we are opening emails for each student.

Email accounts for all users are created upon information/authorization received from Human Resources or Student Affairs Department/Registrar/Head of SPCE respectively.

Sincerely yours

Ulanbek Sadybakasov

Senior Manager, Information Technology
University of Central Asia |Tajikistan | Kyrgyz Republic | Kazakhstan
Mobile: +996 770 822 196
Tel.:   +996 312 910 822 (ext. 454)
Fax:    +996 312 910 835
138 Toktogul Street, 720001, Bishkek, Kyrgyz Republic
www.ucentralasia.org

### CODE REVIEW

**Comment by philipto** [comment]
@UlanbekSadybakasov file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by UlanbekSadybakasov** [comment]
Looping @Nurlan Shaidullaev<mailto:nurlan.shaidullaev@ucentralasia.org>

**Comment by philipto** [comment]
@UlanbekSadybakasov file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by UlanbekSadybakasov** [comment]
Dear Support

Could you please support us (University of Central Asia) to be registered to the JetJetBrains? Attached the lib.rar file.


Sincerely yours

Ulanbek Sadybakasov

Senior Manager, Information Technology
University of Central Asia |Tajikistan | Kyrgyz Republic | Kazakhstan
Mobile: +996 770 822 196
Tel.:   +996 312 910 822 (ext. 454)
Fax:    +996 312 910 835
138 Toktogul Street, 720001, Bishkek, Kyrgyz Republic
www.ucentralasia.org<http://www.ucentralasia.org/>

**Comment by philipto** [comment]
@UlanbekSadybakasov The only file which was necessary to add was lib/domains/org/ucentralasia.txt. I removed other files from the request. Pull request merged. You can start requesting your free licenses in one hour. Thank you.

**Comment by UlanbekSadybakasov** [comment]
Dear Philip

Thank you very much for your support.

@Nurlan Shaidullaev<mailto:nurlan.shaidullaev@ucentralasia.org> could you please apply for the license and let’s know the status.


Sincerely yours

Ulanbek Sadybakasov

Senior Manager, Information Technology
University of Central Asia |Tajikistan | Kyrgyz Republic | Kazakhstan
Mobile: +996 770 822 196
Tel.:   +996 312 910 822 (ext. 454)
Fax:    +996 312 910 835
138 Toktogul Street, 720001, Bishkek, Kyrgyz Republic
www.ucentralasia.org<http://www.ucentralasia.org/>

**Comment by UlanbekSadybakasov** [comment]
Dear Philip

It is resolved. Thank you very much.


Sincerely yours

Ulanbek Sadybakasov

Senior Manager, Information Technology
University of Central Asia |Tajikistan | Kyrgyz Republic | Kazakhstan
Mobile: +996 770 822 196
Tel.:   +996 312 910 822 (ext. 454)
Fax:    +996 312 910 835
138 Toktogul Street, 720001, Bishkek, Kyrgyz Republic
www.ucentralasia.org<http://www.ucentralasia.org/>



From: Ulanbek Sadybakasov
Sent: Tuesday, September 8, 2020 11:56 AM
To: JetBrains/swot <reply@reply.github.com>; JetBrains/swot <swot@noreply.github.com>; Nurlan Shaidullaev <nurlan.shaidullaev@ucentralasia.org>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [JetBrains/swot] Add files via upload (#9175)

Dear Philip

Thank you very much for your support.

@Nurlan Shaidullaev<mailto:nurlan.shaidullaev@ucentralasia.org> could you please apply for the license and let’s know the status.


Sincerely yours

Ulanbek Sadybakasov

Senior Manager, Information Technology
University of Central Asia |Tajikistan | Kyrgyz Republic | Kazakhstan
Mobile: +996 770 822 196
Tel.:   +996 312 910 822 (ext. 454)
Fax:    +996 312 910 835
138 Toktogul Street, 720001, Bishkek, Kyrgyz Republic
www.ucentralasia.org<http://www.ucentralasia.org/>

**Pull request merged**
