### PR TITLE
Create studentfr

### PR DESCRIPTION
**Pull request by Deezxs**
...@studentfr.ch is used by students in many schools in my region but the one I go to is the one specified on the text file.

_Edit_ : Website: http://www.edufr.ch/

### CODE REVIEW

**Comment by philipto** [comment]
@Deezxs Please indicate actual domain ownership in the file in the request. You can look at #1589 for an example. Also, please rename the file to lib/domains/ch/studentfr.txt (.txt extension is mandatory), and provide us with a link to a page on the official website confirming that @studentfr.ch is really in use by the students at the canton de Fribourg. 

Also, please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by Deezxs** [comment]
@philipto Hello and thank you for your quick reply. Here is the actual situation : Students in the secondary and tertiary schools (professionnalé schools) in the Canton de Fribourg ("State" or "Region" of Fribourg) are using mails with two format types  "...@studentfr.ch" and "...@edufr.ch". Those mail servicse are provided by the platform http://www.edufr.ch/ that was made by Fri-Tic, _the Service of integration of IT projects in the State of Fribourg_ . 

My school which is the "École des Métiers de Fribourg" ( http://emf.ch/ ) provides 3 to 4 years educational programs in IT, Electronic and more technology-related courses and we use @studentfr.ch for students and @edufr.ch for professors.

Since many schools and universities in the state are using that system, should I choose "Education et formation dans le canton de Fribourg" as the domain ownership ?

**Comment by philipto** [comment]
@Deezxs Yes, you are right. 
You can have two files in the request, lib/domains/ch/studentfr.txt and lib/domains/ch/edufr.txt with the same description in the files, 
Education et formation dans le canton de Fribourg
Please modify your request accordingly, and then I merge it.
If you are in doubt how to add second file to the request, no problem, you can make another request with lib/domains/ch/edufr.txt.
Thank you!

**Comment by philipto** [comment]
@Deezxs Thank you for the update. Pull request merged.

**Pull request merged**
