### PR TITLE
Create jax.txt

### PR DESCRIPTION
**Pull request by rizkaz**

### CODE REVIEW

**Comment by philipto** [comment]
@rizkaz While Jax Center's work is clearly very important for the humanity, I failed to find year-long IT-related courses at your website, as described in the rules of this repository: https://github.com/JetBrains/swot#which-educational-institutions-can-be-added-to-the-repository

Could you please give us a link to a page describing the corresponding course? Thank you!

**Comment by rizkaz** [comment]
We are running workshops year-round (mostly two day workshops), every month with unix/R/Python/HPC. Some of the links for this year are:

https://smcclatchy.github.io/2017-04-06-farmington/
https://thejacksonlaboratory.github.io/python-ecology-lesson/

https://thejacksonlaboratory.github.io/introduction-to-hpc/

https://thejacksonlaboratory.github.io/2016-12-16-jgm/
https://smcclatchy.github.io/2016-04-14-jackson/
https://smcclatchy.github.io/2017-02-09-farmington/
https://smcclatchy.github.io/2017-04-06-farmington/

Thanks

**Comment by philipto** [comment]
@rizkaz Thank you for the clarification. If the workshops are just two days long, why the students cannot use trial versions of the tools, which do not require any authorization for 30 days?

**Comment by rizkaz** [comment]
I guess that could work. Would they be able to download again if they took more than one class?

**Comment by philipto** [comment]
@rizkaz Trial version works for 30 days, if they take any number of the classes within 30 days, it works. If they decide to use it after that, they can ask a trial extension by email to sales@jetbrains.com, our Sales team is often able to prolong trial period in such cases. Thus, I close this request without merging. Thank you for cooperation!

**Pull request closed without merging**
