### PR TITLE
Added eu/ensiie.txt

### PR DESCRIPTION
**Pull request by cscmieu**
Added French school ENSIIE https://www.ensiie.fr/

### CODE REVIEW

**Comment by philipto** [comment]
@cscmieu Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@cscmieu You might miss my previous comment. Please react.

**Comment by cscmieu** [comment]
Hi,
Sorry for replying so late...

**Comment by philipto** [comment]
@cscmieu No problem. Thank you for answering. However you did not reply the question in my previous comment. Would you please reply the question? If you don't have the proof, you may close the ticket and reopen it when you have the proof.

**Comment by philipto** [comment]
@cscmieu You might miss my previous comment. Please react.

**Comment by cscmieu** [comment]
Sorry, but I don't understand, I added a proof as attachment... Need I to
translate it ? Because it was sent in french.

**Comment by philipto** [comment]
@cscmieu Regrettably, the attachment was not actually attached. Could you please upload the proof using your browser, nit by email? Please open the page https://github.com/JetBrains/swot/pull/18786 and upload the proof as a comment there. Translation is not necessary. 

GitHub strips out attachments if they are sent by email, thus it might not appear on the request page. Thank you!

**Comment by cscmieu** [comment]
[Modification_messagerie.pdf](https://github.com/JetBrains/swot/files/12832351/Modification_messagerie.pdf)

**Pull request merged**
