### PR TITLE
Add a new domain of my school

### PR DESCRIPTION
**Pull request by f2xx**
website URL:https://iccordenons.it
NAME: ISTITUTO COMPRENSIVO F. e P. CORDENONS

### CODE REVIEW

**Comment by philipto** [comment]
@f2xx 

Please provide us with a proof, which shows that the school recognizes the domain iccordenons.it that you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@f2xx You might miss my previous comment. Please react.

**Comment by f2xx** [comment]
https://iccordenons.it/contatti-sede-istituto-comprensivo
The mailbox related fields are shown here

**Comment by philipto** [comment]
@f2xx I am sorry, there is not enough evidence that the domain belongs to the university. I have to close the request without merging. If you are the student of this college, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
