### PR TITLE
Add the CMB

### PR DESCRIPTION
**Pull request by BumseBine**

### CODE REVIEW

**Comment by philipto** [comment]
@BumseBine Please provide us with: a proof showing that the school recognizes the domain `cmb-portal.de`, which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@BumseBine You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@BumseBine I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Comment by BumseBine** [comment]
Sorry for the late answer. My email program didn't display that I got
messages. Can you send a email to mauritz.funke@cmb-portal.de which is my
student email or is there any other method to confirm the email?
Sincerely
Mauritz Funke

Philip Torchinsky <notifications@github.com> schrieb am Mo., 2. Dez. 2019,
10:21:

**Pull request closed without merging**
