### PR TITLE
feat: added BINUS University

### PR DESCRIPTION
**Pull request by pramahaditamaputra-sicepat**
added BINUS University Information

Student email pattern : [*]@binus.ac.id

Website : https://binus.ac.id/

### CODE REVIEW

**Comment by philipto** [comment]
@pramahaditamaputra-sicepat I am sorry, the domain binus.ac.id is removed from our trusted domains list because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Comment by pramahaditamaputra-sicepat** [comment]
Hi @philipto , email with domain @binus.ac.id its only exclusive for registered student because we use it to login to our student web portal ( https://binusmaya.binus.ac.id/newDefault/login.html ) , could you tell me which "the school domain allows to register an email address there even if you are not a student of the school" ?

**Comment by pramahaditamaputra-sicepat** [comment]
if the domain you mean its https://binus.edu/admissions/ , that domain its only for admission purpose only and we don't get email with domain @binus.ac.id after submitted the registration form because the email @binus.ac.id its only for verified student in this university.

**Comment by pramahaditamaputra-sicepat** [comment]
@philipto so is it still possible to re-open this pull request and merge it so email with domain @binus.ac.id will be registered again 🙏 ?

**Pull request closed without merging**
