### PR TITLE
Added Semper Student Mail Domain

### PR DESCRIPTION
**Pull request by BreadCatV1**

### CODE REVIEW

**Comment by BreadCatV2** [comment]
Sorry didn't mean to close

**Comment by philipto** [comment]
@BreadCatV1 Could you please ensure that you did not make a typo? 
Schulkonzept - Semper Fachoberschule Dresden domain seems to be semper-schule**n**.de, and you ask to add semper-schule**r**.de. If the latter is correct, please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by BreadCatV1** [comment]
Schule means School and Schueler means Student, they use one for offical channels and one to assign student accounts

https://portal.semper-schulen.de/ticket/
"Die Nutzung ist nur für Semper-Accounts (semper-schulen.de bzw. semper-schueler.de) möglich."
"Usage is only Possible for Semper-Accounts (semper-schulen.de or semper-schueler.de)"

**Comment by philipto** [comment]
@BreadCatV1 Thank you for your patience while waiting for a review and processing your request. I appreciate your detailed explanation very much. Pull request merged.

**Pull request merged**
