### PR TITLE
Add files of High School Simone de Beauvoir in lib/domains/education

### PR DESCRIPTION
**Pull request by JRicard**
- the university official website URL, if it is different from the domain you are submitting : https://lycee-gragnague.mon-ent-occitanie.fr/

-  a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university : https://lycee-gragnague.mon-ent-occitanie.fr/l-etablissement/formations/bts-ciel/

-  a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students : https://drive.google.com/file/d/1UJVdSizzUsP5lD11p6YVAiC2YrOUZ1Wt/view?usp=sharing

### CODE REVIEW

**Comment by philipto** [comment]
@JRicard Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@JRicard You might miss my previous comment. Please react.

**Comment by JRicard** [comment]
@philipto Here is the requested document : https://drive.google.com/file/d/1UJVdSizzUsP5lD11p6YVAiC2YrOUZ1Wt/view?usp=sharing

**Comment by philipto** [comment]
@JRicard  Thank you very much for the clarification. Pull request merged.

**Pull request merged**
