### PR TITLE
Added ESDACSF

### PR DESCRIPTION
**Pull request by afonsosantos**
**School URL:** [https://www.esdacsf.pt/](https://www.esdacsf.pt/)
**IT Course Page:** https://www.esdacsf.pt/oferta-educativa (slideshow with various courses, the IT course is named "Técnico de Informárica - Sistemas" - IT Technician- Systems)

### CODE REVIEW

**Comment by philipto** [comment]
@afonsosantos Please provide us with a proof which shows that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by afonsosantos** [comment]
What can I submit to proof that? I have an email account on that domain, is that OK?

**Comment by philipto** [comment]
@afonsosantos It depends. Usually, the best proof is if the email address in this domain is mentioned at the official website, or you have a copy of some instruction which the school has provided you with, where something like this is said:
> All students have their university email addresses in the form of username@esdacsf.alunos.pt

We need to be sure that this email domain and your school are officially related.

**Comment by afonsosantos** [comment]
I forgot I had instructions to activate the student's email, here it is:
[Instructions.pdf](https://github.com/JetBrains/swot/files/4622125/E-Mail.Alunos.pdf)

**Comment by philipto** [comment]
@afonsosantos Thank you for the clarification! It changes things, actually. The instruction says that your email domain is alunos.esdacsf.pt, not esdacsf.alunos.pt. What is correct? If the former is correct, I will need to rename a file in your request from lib/domains/pt/alunos/esdacsf.txt to lib/domains/pt/esdacsf/alunos.txt.

**Comment by afonsosantos** [comment]
You are right, sorry for the typo...

**Comment by afonsosantos** [comment]
Thank you for the help, will delete this branch.

**Comment by philipto** [comment]
@afonsosantos No problem, I renamed the file and merged the pull request. Please start requesting your free licenses in about an hour from now, to let the changes to propagate through our system.

**Pull request merged**
