### PR TITLE
Create wg.txt

### PR DESCRIPTION
**Pull request by samynos**
create wg.txt file for my school Willstätter-Gymnasium Nürnberg

### CODE REVIEW

**Comment by philipto** [comment]
@samynos Please provide us with:
* the school official website URL
* the school street address, including city and country
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@samynos You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@samynos I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by samynos** [comment]
@philipto 

- School-URL: http://www.willstaetter-gymnasium.de/ 
- School-Address: Innerer Laufer Platz 11  90403 Nürnberg 
- my email is an official email domain but only for regitration or as login email (e.g. microsoft office, webuntis) and not for receiving emails outside the school

**Review by samynos — COMMENTED** [review]
@philipto

- School-URL: http://www.willstaetter-gymnasium.de/
- School-Address: Innerer Laufer Platz 11 90403 Nürnberg
- My email is an official email domain but only for regitration or as login email (e.g. microsoft office, webuntis) and not for receiving emails outside the school

**Pull request closed without merging**
