### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MsRussellKGS**

### CODE REVIEW

**Comment by philipto** [comment]
@MsRussellKGS lib/domains/uk/file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@MsRussellKGS lib/domains/uk/file.zip: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@MsRussellKGS Pull request closed. You were expected to add a content of file.zip archive, not the archive itself, thus I'll add the correct file manually for you. Please wait an hour after this message is sent, before start requesting the licenses at https://jetbrains.com/student.

**Comment by MsRussellKGS** [comment]
Sorry I misread the requirements. Thankyou for sorting it out for me.

Much appreciated

Theresa Russell
Teacher of Computer Science
Kirkham Grammar School

**Pull request closed without merging**
