### PR TITLE
Add Liceo Fermi Bologna request file

### PR DESCRIPTION
**Pull request by bgzlri**

### CODE REVIEW

**Comment by bgzlri** [comment]
https://www.liceofermibo.edu.it/

**Comment by bgzlri** [comment]
https://www.liceofermibo.edu.it/indirizzo-di-studio/liceo-scientifico-opzione-scienze-applicate-2/

**Comment by philipto** [comment]
@bgzlri First stage of verification passed, official domain is [liceofermibo.edu.it](https://liceofermibo.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by bgzlri** [comment]
liceofermi.edu.it is the official domain, but is only for teachers. For students, we have stu.liceofermibo.edu.it

**Comment by philipto** [comment]
@bgzlri Thank you very much for the clarification. Pull request merged.

**Pull request merged**
