### PR TITLE
Create dhcnhn.txt

### PR DESCRIPTION
**Pull request by tungnv107**
Apply domain dhcnhn.edu.vn

### CODE REVIEW

**Comment by philipto** [comment]
@tungnv107 Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@tungnv107 You might miss my previous comment. Please react.

**Comment by tungnv107** [comment]
the school official website URL: https://www.haui.edu.vn
but domain  official email domain for the students is http://dhcnhn.edu.vn/ to register by Google for Education

**Comment by philipto** [comment]
@tungnv107 Thank you for the clarification! Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. The proof can be a page at the official website which mentions dhcnhn.edu.vn, or an official instruction to use the email in the domain dhcnhn.edu.vn which you were given at the enrollment time.

**Comment by philipto** [comment]
@tungnv107 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@tungnv107 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Comment by davidpaf-MSFT** [comment]
@philipto 
Here is the proof that Hanoi University of Industry has 2 emails address:

image

https://khoadien.haui.edu.vn/vn

**Pull request closed without merging**
