### PR TITLE
Add Duy Tan University

### PR DESCRIPTION
**Pull request by duy-lee**
Dear JetBrains Admin,

I want to add my university to get support from JetBrains for us. We are from Duy Tan University located in central Vietnam. We have IT students who want to use developer applications from JetBrains.

**university domain is https://duytan.edu.vn**
**university email domain is example@dtu.edu.vn**

Thank you very much.

Best regards,
Le Van Duy

### CODE REVIEW

**Comment by philipto** [comment]
@duy-lee The domain registrant for **dtu.vn** is Trường Đại Học Duy Tân (Duy Tan University). This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@duy-lee Thank you for the request. You say in the comment that the email domain for students at the university is @dtu.edu.vn, but the request is for @dtu.vn. What is the email domain that you wish to add to the trusted list?

**Comment by duy-lee** [comment]
> @duy-lee Thank you for the request. You say in the comment that the email domain for students at the university is @dtu.edu.vn, but the request is for @dtu.vn. What is the email domain that you wish to add to the trusted list?

Thank you for your feedback. The exact email domain of our school is @dtu.edu.vn, @philipto

**Comment by philipto** [comment]
@duy-lee I am sorry, the domain dtu.edu.vn is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
