### PR TITLE
Add institute

### PR DESCRIPTION
**Pull request by ZituzZ34**

### CODE REVIEW

**Comment by ZituzZ34** [comment]
THe domain is apps.hhdc.net, How do I reflect that apps in the file name is it necessary?

**Comment by philipto** [comment]
@ZituzZ34 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by ZituzZ34** [comment]
The official website:
https://nsd.hhdc.net/oferta-educativa/

Calle del Pal, 6, 03501 Benidorm, Alicante

If you see the link, there are a optative called IT 

A proof is that I got my email of student 
image

**Comment by philipto** [comment]
@ZituzZ34  Thank you for the clarifications. Pull request merged.

**Comment by ZituzZ34** [comment]
@philipto in the page doesnt work my email
Captura de pantalla de 2022-08-25 13-38-26

**Comment by ZituzZ34** [comment]
Captura de pantalla de 2022-08-25 13-54-27

The email doesn't appear in my inbox, I see in spam and in other places and don't see the email

**Comment by ZituzZ34** [comment]
I have seen and what happens is that I only receive the emails from the same educational center, that is, the emails that have the domain of the institute, What I can do?

**Comment by ZituzZ34** [comment]
I tried to send myself an email from my personal email and this happened:and this is what comes ou
Captura de pantalla de 2022-08-25 14-04-03
t

**Pull request merged**
