### PR TITLE
Add ucc.edu.hk

### PR DESCRIPTION
**Pull request by 210Anyone**

### CODE REVIEW

**Comment by philipto** [comment]
@210Anyone Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@210Anyone You might miss my previous comment. Please react.

**Comment by 210Anyone** [comment]
the school official website URL : ucc.edu.hk
the school address : 11 Tong Yam St, Kowloon Tong, Kowloon, Hong Kong


https://www.ucc.edu.hk/page_uccnews.php?news_id=188
Screenshot 2022-03-30 080444

**Comment by philipto** [comment]
@210Anyone Thank you very much for the clarification. Pull request merged.

**Pull request merged**
