### PR TITLE
Add School

### PR DESCRIPTION
**Pull request by QCNX**
Sydney Institute of Business and Technology (SIBT)
SIBT Official Website: https://www.sibt.nsw.edu.au/
SIBT IT Course: https://www.sibt.nsw.edu.au/courses/diploma/information-technology

### CODE REVIEW

**Comment by Shubbin** [comment]
Lagos state polytechnic(LASPOTECH)
Laspotech website 
https://mylaspotech.edu.ng/
Email 
registrar@mylaspotech.edu.ng

**Comment by QCNX** [comment]
> Lagos state polytechnic(LASPOTECH) Laspotech website https://mylaspotech.edu.ng/ Email [registrar@mylaspotech.edu.ng](mailto:registrar@mylaspotech.edu.ng)

Please create your own pull request. Read the README.md of this repository.

**Comment by philipto** [comment]
@QCNX First stage of verification passed, official domain is [sibt.nsw.edu.au](https://sibt.nsw.edu.au) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@QCNX Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
