### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by oakdag44**
Please add my school which is Internatio
[islqatar.txt](https://github.com/JetBrains/swot/files/10055861/islqatar.txt)
nal School of London Qatar

### CODE REVIEW

**Comment by philipto** [comment]
@oakdag44 islqatar.txt I am sorry, I have to close the request without merging, because you made a mistake in a request and did not specify any filepath. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and make a new correct request. Thank you for your understanding!

**Comment by oakdag44** [comment]
Dear Philip

Thank you very much for your care but I really am not familiar with github. Will you please help us and add our school

Please find attached the file that I downloaded from the jetbrains web page

Thanks
Dr. Ozhan Akdag

**Comment by philipto** [comment]
@oakdag44 Please re-send your email with the attached file.zip to community-support@jetbrains.com. GitHub strips out all attachments if they are sent by email. Also, we generally don't monitor already closed requests on GitHub.

Thank you for your understanding!

**Comment by philipto** [comment]
@oakdag44 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
