### PR TITLE
Add domain : vn - edu - nttu

### PR DESCRIPTION
**Pull request by khanhnguyen234**
nttu.edu.vn

### CODE REVIEW

**Comment by philipto** [comment]
@khanhnguyen234 You might miss my previous comment. Please react.

**Comment by khanhnguyen234** [comment]
> @khanhnguyen234 You might miss my previous comment. Please react.

- Website: https://ntt.edu.vn/
- Address: 300A – Nguyễn Tất Thành, Phường 13, Quận 4, TP. Hồ Chí Minh, Việt Nam
- IT url: http://cntt.ntt.edu.vn/
- Recognizes the domain: can see email at header on website (ex: ntt@ntt.edu.vn)

@philipto Please help me check

**Comment by khanhnguyen234** [comment]
> @khanhnguyen234 Thank you for the details! You are quite right: this university has a domain ntt.edu.vn. However you requested to add a domain ntt**u**.edu.vn (please notice extra "u" after "ntt").
> 
> If you need to add a domain ntt.edu.vn, I can do it immediately. Please confirm. Thank you!

Sorry I don't know why student e-mail in the format `mssv@nttu.edu.vn` (http://phongdaotao2.ntt.edu.vn/NewsDetail.aspx?NewsID=1988). How can I do to get support?

**Comment by philipto** [comment]
@khanhnguyen234 Thank you for the clarification. Pull request merged. The page http://phongdaotao2.ntt.edu.vn/NewsDetail.aspx?NewsID=1988 was exactly what I needed. Thank you!

**Pull request merged**
