### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by bhodhos**
Basis International Shenzhen, https://bisz.basischina.com/#/home?lang=en

### CODE REVIEW

**Comment by MAxd78** [comment]
[sch-integral.txt](https://github.com/JetBrains/swot/files/11107869/sch-integral.txt)

url - https://integral.mskobr.ru/

**Comment by MikeKate666** [comment]
山东大学
Shandong University
sdu.edu.cn

**Comment by philipto** [comment]
@bhodhos Pull request merged. Thank you.

**Comment by philipto** [comment]
@MAxd78 @MikeKate666 Please make separate pull requests, do not comment other's requests. Thank you.

**Comment by MAxd78** [comment]
> @MAxd78 @MikeKate666 Please make separate pull requests, do not comment other's requests. Thank you.

 I can't get it, I can't understand the interface

**Pull request merged**
