### PR TITLE
Create lyceefrancais

### PR DESCRIPTION
**Pull request by MineJames800**

### CODE REVIEW

**Comment by philipto** [comment]
@MineJames800 Please rename lib/domains/be/lyceefrancais to lib/domains/be/lyceefrancais.txt. 
Also, please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by philipto** [comment]
@MineJames800 You might miss my previous comment. Please reply.

**Comment by MineJames800** [comment]
I do it now ! Thanks for your replies ! For your information, there's an IT option for advanced developers who are 16 years old or more

**Comment by philipto** [comment]
@MineJames800 Thank you! I am closing this request becasue I already satisfied #3492, which is about the same domain.

**Pull request closed without merging**
