### PR TITLE
Add Domain University UPEC

### PR DESCRIPTION
**Pull request by AcirDeveloper**

### CODE REVIEW

**Comment by AcirDeveloper** [comment]
Please, I am a student at the Carchi State Polytechnic University in Ecuador and I would like to know if my institution applies to have its Jetbrains educational plan. Beforehand thank you very much.

**Comment by philipto** [comment]
@AcirDeveloper First stage of verification passed, official domain is [upec.edu.ec](https://upec.edu.ec) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by AcirDeveloper** [comment]
@philipto Thank you very much for the information, I will be waiting for the final decision. 😁

**Comment by philipto** [comment]
@AcirDeveloper Pull request merged. Thank you.

**Pull request merged**
