### PR TITLE
Create SQPH Edu.txt

### PR DESCRIPTION
**Pull request by hungnm1518**

### CODE REVIEW

**Comment by philipto** [comment]
@hungnm1518 Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school

**Comment by hungnm1518** [comment]
This is URLs on our official website in 2020. Our website is published in Vietnamese. Thank you very much! 
[http://siquanphonghoa.edu.vn/tin-tuc-truong-sqph/huong-dan-xet-tuyen-thang-uu-tien-xet-tuyen-xet-tuyen-hoc-sinh-gioi-bac-thpt-vao-dao-tao-dai-hoc-quan-su-tai-truong-si-quan-phong-hoa-nam-2020.html](2020)
[http://siquanphonghoa.edu.vn/tin-hoat-dong-don-vi/thong-tin-tuyen-sinh-nam-2019-cua-truong-si-quan-phong-hoa.html](From 2019)
[http://siquanphonghoa.edu.vn/tuyen-sinh/thong-tin-tuyen-sinh-nam-2017.html](From 2017)

**Comment by philipto** [comment]
@hungnm1518 I am sorry, but I did not find a course description by the links which you advised to me.
I need a description of software development course which this school offers. The pages which you recommended me to visit are about admission rules. As far as I can see the school is a military academy, and I don't see any software development course at the website. Please help me to find it.

**Comment by hungnm1518** [comment]
Yes, Our school is a military academy. Do jetbrains only support schools for information technology?

**Comment by philipto** [comment]
@hungnm1518 JetBrains supports all students and teachers. However, **this repository** rules says that:
> Your pull request for adding a new email domain to the repository will be satisfied if **all of the conditions below are met**:
>1) The domain is used by an educational institution, which offers at least one long-term course (one year or longer), and the course is somehow related to IT (it is in computer science, software engineering, statistics, bioinformatics, etc.)
>2) The educational institution is a physical entity with student attendance and recognized as providing a learning curriculum for the educational system, or the institution is an accredited online educational organization providing their students with: (1) online courses with a curriculum at least one year long, (2) a dedicated email address which is provided to students only until their graduation.

Thus, if your academy does not offer long-term IT-related courses, you are eligible for a free license if request it with your official academy-issued document (use https://www.jetbrains.com/shop/eform/students, OFFICIAL DOCUMENT tab at the page). 

If your academy does not offer long-term IT-related courses, its email domain cannot be added to this repository. Please let me know if it does not, and then I close the request.

This repository's rules are located at the bottom of [this page](https://github.com/JetBrains/swot)

Thank you for the understanding.

**Comment by hungnm1518** [comment]
Thanks for the reply! Our academy does not offer long-term IT-related courses. I use the products of jetbrains (only PhpStorm) because I'm the IT administrator. Please close this request. Thanks!

**Pull request closed without merging**
