### PR TITLE
Add Universidad del Valle de Mexico

### PR DESCRIPTION
**Pull request by Angel-850**

### CODE REVIEW

**Comment by Angel-850** [comment]
Hi,
I share email example and Elibro site link.
Email: a010143035@my.uvm.edu.mx
Link: https://elibro.net/es/lc/uvm/login_usuario/

Captura de Pantalla 2022-10-27 a la(s) 16 33 39

**Comment by Angel-850** [comment]
> @Angel-850 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. You can provide us with any of the following:
> 
> * A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
> * An URL of a page at the official school website that says that students use this email domain
> * A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
> * A WHOIS data that link the email domain to the school somehow
> * A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
> * Anything else that can prove this fact in similar way, i.e. can be verified independently.



> @Angel-850 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. You can provide us with any of the following:
> 
> * A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
> * An URL of a page at the official school website that says that students use this email domain
> * A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
> * A WHOIS data that link the email domain to the school somehow
> * A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
> * Anything else that can prove this fact in similar way, i.e. can be verified independently.

Added Info

**Comment by philipto** [comment]
@Angel-850  Thank you for the clarifications. Pull request merged.

FTR: I also found an independent resource confirming the domain ownership: https://scholar.google.com/citations?user=3HGXwvcAAAAJ&hl=ja

**Comment by charlymaciass** [comment]
Hello Philipto why this domain was added to the stoplist if it was correctly verified ?

https://github.com/JetBrains/swot/blob/a718ed3b403640984d0c235466e8bf29fcc98cd3/lib/domains/stoplist.txt#L1243

**Pull request merged**
