### PR TITLE
Added mubs.ac.ug

### PR DESCRIPTION
**Pull request by realnsleo**
Added Makerere University Business School

### CODE REVIEW

**Comment by realnsleo** [comment]
Information about the University:

URL: https://mubs.ac.ug
URL which recognizes .ac.ug : https://mubsep.mubs.ac.ug/ (check header)

**Comment by philipto** [comment]
@realnsleo I cannot verify your request yet because this school's website is down. I'll get back to this request later.
image

**Comment by philipto** [comment]
@realnsleo This school has permanent problem with the website. I have to close this request without merging. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.
Thank you for the understanding!

image

**Comment by realnsleo** [comment]
Hi @philipto, I understand. I am part of the University staff who wants the students in the computing department to benefit from this. Let me see what I can compile to confirm the University status. Thank you.

**Pull request closed without merging**
