### PR TITLE
Create liceulsaligny-tr.txt

### PR DESCRIPTION
**Pull request by Jake-0001**
Added Liceul Tehnologic "Anghel Saligny" Roșiori de Vede to the list.

### CODE REVIEW

**Comment by philipto** [comment]
@Jake-0001 Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by Jake-0001** [comment]
Hey @philipto, thanks for the response. I'll be closing this pull since my high-school does not have an official website. 

The domain **liceulsaligny-tr** was provided to my high-school by https://edu.adma.ro/ with the program Google Workspace for Education so we can use Google Classroom, Google Meet and other features during the pandemic.

The high-school is located at Romania, District Teleorman, City Roșiori de Vede, Street Unirii, Postal Code 145100.

As mentioned above, I can not provide proof that my high-school recognizes the domain as an official email domain for the students.

I will try to get the GitHub Student Pack and verify from there.

Thank you.

**Comment by philipto** [comment]
@Jake-0001 Thank you for the clarification. I found an independent proof of the domain ownership. Pull request merged.

**Comment by Jake-0001** [comment]
@philipto Thank you so much! I really appreciate it!

**Pull request merged**
