### PR TITLE
Create Salpaus.txt

### PR DESCRIPTION
**Pull request by Gigaika**
http://www.salpaus.fi/english/Sivut/default.aspx

### CODE REVIEW

**Comment by philipto** [comment]
@Gigaika Terve! 
For salpaus.fi domain the file name has to be lib/domains/fi/salpaus.txt, not  lib/domains/fi/edu/salpaus.txt. Please rename. Kiitos!

**Comment by philipto** [comment]
@Gigaika You might miss my previous comment. Please reply.

**Comment by Gigaika** [comment]
Thanks, I made a new request.

**Comment by philipto** [comment]
@Gigaika Thank you! I am closing this request as duplicating #3554, which is already satified.

**Pull request closed without merging**
