### PR TITLE
Added Universidad Politécnica de Aguascalientes.

### PR DESCRIPTION
**Pull request by pabpalac**

### CODE REVIEW

**Comment by pabpalac** [comment]
Please allow UPA's students https://upa.edu.mx/

**Comment by forlorn** [comment]
[https://hnu.edu.ph/](url)
[https://hnu.edu.ph/academics-holynameuniversity/engineering-computer-studies](url)
thirdstep
[hnu.txt](https://github.com/JetBrains/swot/files/10338553/hnu.txt)

**Comment by forlorn** [comment]
[hnu.txt](https://github.com/JetBrains/swot/files/10338578/hnu.txt)

[https://hnu.edu.ph/](url)
[https://hnu.edu.ph/academics-holynameuniversity/engineering-computer-studies](url)
[thirdstep.pdf](https://github.com/JetBrains/swot/files/10338580/thirdstep.pdf)

**Comment by philipto** [comment]
@pabpalac I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host alumnos.upa.edu not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Pull request closed without merging**
