### PR TITLE
Add Dai Nam university

### PR DESCRIPTION
**Pull request by trisduong**
Thank you for review. Please add my school.

### CODE REVIEW

**Comment by philipto** [comment]
@trisduong Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by trisduong** [comment]
@philipto 
- My school official website URL: http://dainam.edu.vn/en
- An URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: http://dainam.edu.vn/en/introduction-to-faculty-of-information-technology
- A proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students: I don't really know how to prove. my email school form is: *@dnu.edu.vn. DNU is abbreviation of my school name. I also have office 365 licensed related to.
Thank you very much for review.

**Comment by philipto** [comment]
@trisduong Thank you for the clarifications. As I mentioned above, there are several ways to prove the domain recognition by the school:

You can provide us with any of the following as the proof:

1)    A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2)    An URL of a page at the official school website that says that students use this email domain
3)    A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4)    A WHOIS data that link the email domain to the school somehow
5)    A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6)    Anything else that can prove this fact in similar way, i.e. can be verified independently.

Please let me know which of the methods is easier for you, and I can help with arranging it. In the meantime you can use trial version of any JetBrains tool that you need, or apply for a year-long free license with your official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
@trisduong I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
