### PR TITLE
Create alkawthar.txt

### PR DESCRIPTION
**Pull request by rlubdi**
alkawthar

### CODE REVIEW

**Comment by philipto** [comment]
@rlubdi First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/DaReference/

**Comment by rlubdi** [comment]
I'm waiting, Thank u.

**Comment by philipto** [comment]
@rlubdi Please provide us with:
* the school full official name, not an abbreviation, not a nickname. Please write it in the native language of the school. The name in English is optional.
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you!

**Comment by rlubdi** [comment]
مدارس الكوثر العالمية - AlKawthar International Schools

http://www.alkawtharfrenchschool.com/
[7983 King Abdul Aziz Road, حي المحمدية, Jeddah, Saudi Arabia](https://www.google.com/maps/dir/?daddr=21.659622,39.111586)

**Comment by philipto** [comment]
@rlubdi First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/DaReference/

**Comment by philipto** [comment]
@rlubdi You might miss my previous comment. Please react.

**Comment by rlubdi** [comment]
The information provided has been answered. Please confirm, as I am in dire need and waiting for approval and use of phpsrotm.

**Comment by philipto** [comment]
@rlubdi First stage of verification passed, official domain is [twitter.com](https://twitter.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://twitter.com/ImAlkawthar/status/1483747819487956993

**Comment by philipto** [comment]
@rlubdi Thank you very much for the clarifications and your patience during the review and processing of your request. The pull request has been successfully merged. I apologize for the confusion in the comments related to this request; there were some misunderstandings on my part. I initially overlooked your response, but the review has now been completed successfully.

Please wait about an hour before requesting the free licenses, to allow the changes to fully propagate through our systems. Thank you!

**Pull request merged**
