### PR TITLE
osvukknjazevac

### PR DESCRIPTION
**Pull request by viktorciric**
Website: www.osvukknjazevac.edu.rs

Student Email: @osvukknjazevac.edu.rs

Hello, please add my domain "osvukknjazevac.edu.rs" to your repository.

If you have any other requests, feel free to ask me!
Feel free to reach out if you need further assistance! 😊

### CODE REVIEW

**Comment by viktorciric** [comment]
@philipto I am writing in regard to my verification request that was submitted seven days ago. I would like to check on the status of my request and see if there is any additional information needed from my side.

Thank you for your time and understanding.

**Comment by viktorciric** [comment]
@philipto Hello! It’s been two weeks and I haven’t received a response, I’m interested in whether my request is still in the verification process and if so, how much longer could it take because my trial version of your software lasts until 23.03.2024 and after that I no longer have the right to extend it, so I’m wondering if I can help with some school information and possibly speed up the verification process?

**Comment by viktorciric** [comment]
@philipto Hello! It’s been two weeks and I haven’t received a response, I’m interested in how much time my request is still in the verification process and if so, how much longer could it take because my trial version of your software lasts until 23.03.2024 and after that I no longer have the right to extend it, so I’m wondering if I can help with some school information and possibly speed up the verification process?

**Comment by viktorciric** [comment]
@philipto Hello! It’s been two weeks and I haven’t received a response, I’m interested in how much time my request is still in the verification process and if so, how much longer could it take because my trial version of your software lasts until 23.03.2024 and after that I no longer have the right to extend it, so I’m wondering if I can help with some school information and possibly speed up the verification process?

**Comment by philipto** [comment]
@viktorciric Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
