### PR TITLE
add support for all domains

### PR DESCRIPTION
**Pull request by macarron**

### CODE REVIEW

**Comment by philipto** [comment]
@macarron First stage of verification passed, official domain is [linkedin.com](https://linkedin.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.linkedin.com/posts/jeremyforveille_characterdesign-portfolioupdate-gameart-activity-7074312514238328832-exMm?trk=public_profile_like_view

**Comment by philipto** [comment]
@macarron Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Please explain whether the domain belongs to several school, and if yes, how many of them. Also, please tell us how many students study there.

**Comment by macarron** [comment]
Hi,
here you can find the requested information :
official website URL : https://www.esma-artistique.com
school street address : 1 place Niki de Saint Phalle, 34070 Montpellier FRANCE
Game design course (4 years) : https://www.esma-artistique.com/formations/cycle-pro-jeu-video/
Here you can see that ESMA is a part of ecolescreatives : https://www.ecolescreatives.com/des-marques-fortes/
Ecoles créatives is shared by : ESMA, ETPA, IPESAA, IFFDEC, Ecoles Pivot, Collège Salette, Marsan and Ciné Créatis. There is around 250 students in game design spread over 3 cities and 2500 students if I add all courses and campus.

Regards.

**Comment by philipto** [comment]
@macarron First stage of verification passed, official domain is [ecolescreatives.com](https://ecolescreatives.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@macarron  Thank you very much for the clarifications. Pull request merged.

**Pull request merged**
