### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by babakri**
verify my school

### CODE REVIEW

**Comment by philipto** [comment]
@babakri lib/domains/net/aden-univ/University: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@babakri lib/domains/net/aden-univ/University: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@babakri I am sorry, I have to close the request without merging, because you made a mistake in a request and specified incorrect filepath. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and make a new correct request. 

If you have any troubles with following the rules please send an email to community-support@jetbrains.com.

Thank you for the understanding!

**Comment by babakri** [comment]
*I'm not **familiar **with** this repository rules , all **I** want is to *
*approve** me university domain so that i can get a free license , can you
guide me please  *

‫في الأربعاء، 3 مارس 2021 في 12:19 م تمت كتابة ما يلي بواسطة ‪Philip
Torchinsky‬‏ <‪notifications@github.com‬‏>:‬

**Pull request closed without merging**
