### PR TITLE
Create markrutherford

### PR DESCRIPTION
**Pull request by TheInfiniteWin**

### CODE REVIEW

**Comment by lkaae2018** [comment]
[file.zip](https://github.com/JetBrains/swot/files/6912619/file.zip)
I will like have my school on your list, thank you!

**Comment by TheInfiniteWin** [comment]
> [file.zip](https://github.com/JetBrains/swot/files/6912619/file.zip)
> I will like have my school on your list, thank you!

You need to create your own pull request

**Comment by philipto** [comment]
@TheInfiniteWin lib/domains/com/bbvle/mrus/markrutherford: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@TheInfiniteWin Please create a new pull request and provide us with:
- the school official website URL
- the school street address, including city and country
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Please notice that if the domain name is markrutherford.mrus.bbvle.com, the file name has to be lib/domains/com/bbvle/mrus/markrutherford.txt. Please note **.txt** extension at the end.

**Pull request closed without merging**
