### PR TITLE
Request to add Antoni Kocjan School Complex

### PR DESCRIPTION
**Pull request by DamianKocjan**

### CODE REVIEW

**Comment by sopcommand** [comment]
Hello, Its levan tsotskolauri from georgia 
i'd like to ask you add my school in list ill write information below to prove that im student and my school is real
thanks you!
tsotskolauri.levani@students.gov.ge
ISANI DISTRICT, PUBLIC SCHOOL #216
https://www.facebook.com/სსიპ-ქთბილისის-N216-საჯარო-სკოლა-473256156339558

**Comment by philipto** [comment]
@DamianKocjan Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by DamianKocjan** [comment]
URL of a page of official school website: https://zskocjan.pl/

**Comment by mstawinoga** [comment]
School website: https://zskocjan.pl/
Thank You
Marcin Stawinoga (ZS Kocjan's teacher)

**Comment by philipto** [comment]
@mstawinoga Could you please send an email to community-support@jetbrains.com from your school's email address? Please mention this request URL in your message: https://github.com/JetBrains/swot/pull/12934

We need to verify that you are the teacher of this school indeed to process the request. Thank you!

**Comment by philipto** [comment]
@mstawinoga @DamianKocjan Thank you for the clarification. Pull request merged.

**Comment by DamianKocjan** [comment]
Thank you, have a nice day!

**Pull request merged**
