### PR TITLE
Add The Federal Polytechnic, Ede, Osun State, Nigeria

### PR DESCRIPTION
**Pull request by samueladekunle**
Please add the domain for The Federal Polytechnic, Ede, Osun State, Nigeria. The website is https://federalpolyede.edu.ng

### CODE REVIEW

**Comment by philipto** [comment]
@samueladekunle lib/domains/ng/edu/federalpolyede: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by samueladekunle** [comment]
@philipto  I have made the correction.

Kindly take a look at it. Regards.

**Comment by philipto** [comment]
@samueladekunle First stage of verification passed, official domain for **The Federal Polytechnic Ede, Osun State.** is [federalpolyede.edu.ng](https://federalpolyede.edu.ng) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@samueladekunle  Thank you for the update. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
