### PR TITLE
Horizon school of digital technologies

### PR DESCRIPTION
**Pull request by rdouda**
https://horizon-university.tn/

### CODE REVIEW

**Comment by rdouda** [comment]
https://horizon-university.tn/

**Comment by philipto** [comment]
@rdouda Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@rdouda You might miss my previous comment. Please react.

**Comment by rdouda** [comment]
@philipto I’ll get back to you on that ASAP. Thank you for your patience.

**Comment by rdouda** [comment]
The school already provided us with an invitation link.

**Pull request closed without merging**
