### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by dinstamaly**
Add Final International University

### CODE REVIEW

**Comment by dinstamaly** [comment]
add final international university

**Comment by philipto** [comment]
@dinstamaly Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by dinstamaly** [comment]
@philipto

1) the school url - "https://www.final.edu.tr/"
2) the school address - Toroslar Caddesi, No: 6, Çatalköy, Girne, KKTC
3) an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course - "https://www.final.edu.tr/tum-programlar"
4) a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students - "a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students."

**Comment by philipto** [comment]
@dinstamaly Thank you for the details! Could you please provide us with any of the following as the proof of the domain recognition by the school:

1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@dinstamaly I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host final.ac.cy not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Pull request closed without merging**
