### PR TITLE
added student.kbm-du.de

### PR DESCRIPTION
**Pull request by MoweME**
This pull request contains the student domain of: kbm-duisburg.org

The school offers multiple IT trainings and courses: https://www.kbm-duisburg.org/ausbildung/it-berufe/#FachinformatikerAnwendungsentwicklung

### CODE REVIEW

**Comment by philipto** [comment]
@MoweME What is the student email address pattern? Is it username@kbm-duisburg.org? If yes, please rename the file in your request from lib/domains/de/kbm-du/student.txt to lib/domains/org/kbm-duisburg.txt.

Also, please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by MoweME** [comment]
Hi @philipto,

student.kbm-du.de is the mail server of the student mails.
The e-mail addresses are named like username@student.kbm-du.de

I think it isn't linked at the main page of the school (https://kbm-duisburg.org) due to spam reasons.

**Comment by philipto** [comment]
@MoweME The problem is that the addresses like "someone@student.kbm-du.de" are not mentioned anywhere in the internet. Do you have any instruction (printed or digital), which says that you can use the addresses? Please attach the copy of it in the comment at GitHub via web interface.

**Comment by MoweME** [comment]
@philipto Does this help?
You can verify the phone number and see that it belongs to the school.

image
image

**Comment by philipto** [comment]
@MoweME Yes, thank you! Pull request merged.

**Pull request merged**
