### PR TITLE
add lib/domains/cn/edu/sysu/mail.txt

### PR DESCRIPTION
**Pull request by lhb8859138**
Add mail.sysu.edu.cn for the staff in Sun Yat-sen University.
URL:https://www.sysu.edu.cn/.
About Sun Yat-sen University: https://www.sysu.edu.cn/sysuen/aboutSYSU/SYSU_Today.htm

### CODE REVIEW

**Comment by lhb8859138** [comment]
As I mentioned, the mail2.txt and mail3.txt are already under the /lib/domains/cn/edu/sysu folder, I just add the mail.txt via this PR. Thanks in advance

**Comment by lhb8859138** [comment]
image
@philipto I can access mail.sysu.edu.cn

**Comment by philipto** [comment]
@lhb8859138 Pull request merged. 

Would you please explain how the university decides which email subdomain - mail, mail2, or mail3.sysu.edu.cn - has to be assigned to a particular student? Do different departments in the university have different subdomains? 

Thank you.

**Comment by lhb8859138** [comment]
> 

Thanks for your help. For the reason why so many email subdomains in SYSU, I will contact the IT department, then share the information with you. Thanks again.

**Comment by lhb8859138** [comment]
@philipto I got the message from IT, the mail.sysu.edu.cn is for school staff, mail2.sysu.edu.cn for the students in school, and mail3.sysu.edu.cn for the students who have graduated. Thanks

**Pull request merged**
