### PR TITLE
Create nuit.txt

### PR DESCRIPTION
**Pull request by Willert98**
add @s.nuit.edu.cn

### CODE REVIEW

**Comment by Willert98** [comment]
University Web:http://www.nuit.edu.cn/
Mail Web ：http://mail.s.nuit.edu.cn/

**Comment by philipto** [comment]
@Willert98 If your email addresses end with @nuit.edu.cn, please rename the file in this request from lib/domains/edu/nuit.txt to lib/domains/cn/edu/nuit.txt (please notice extra "cn" subdirectory in the filepath). Thank you.

**Comment by Willert98** [comment]
thanks

**Comment by Willert98** [comment]
My email addresses end with @s.nuit.edu.cn

**Comment by philipto** [comment]
@Willert98 Pull request merged. All subdomains of nuit.edu.cn are now automatically included. Thus, s.nuit.edu.cn also included. Please wait 30 minutes from now before requesting the license to allow the changes to propagate through our system. Thank you!

**Comment by Willert98** [comment]
My file submission path is wrong. Please delete it. I'm sorry

**Comment by frankwei98** [comment]
I have new a Pull Request #4936 to fix this problem

**Pull request merged**
