### PR TITLE
Added Aastha College Of Business Studies , Nepal

### PR DESCRIPTION
**Pull request by rubiin**

### CODE REVIEW

**Comment by philipto** [comment]
@rubiin I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host aasthcollege.edu.np not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by rubiin** [comment]
http://www.aasthacollege.edu.np/ is the domain . @philipto  you mispelled it

**Comment by awebisam** [comment]
@philipto You misspelled it. It's https://www.aasthacollege.edu.np

**Comment by philipto** [comment]
@rubiin @awebisam  I am sorry, I cannot edit your request, it's uneditable. Please create a new one. Thank you.

**Comment by rubiin** [comment]
let me create a fresh one

**Comment by rubiin** [comment]
I have opened up a new pr @philipto  https://github.com/JetBrains/swot/pull/11946

**Pull request closed without merging**
