### PR TITLE
Cinel

### PR DESCRIPTION
**Pull request by andreitudos**

### CODE REVIEW

**Comment by philipto** [comment]
@andreitudos Could you please:
1) Rename lib/domains/pt/cinel to lib/domains/pt/cinel.txt
2) Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school

**Comment by philipto** [comment]
@andreitudos You might miss my previous comment. Please reply.

**Comment by philipto** [comment]
@andreitudos You might miss my previous comment. Please reply.

**Comment by andreitudos** [comment]
1. Done
2. http://www.cinel.pt/appv2/Oferta-Formativa/Plano-de-Formacao

**Comment by philipto** [comment]
@andreitudos You have closed this request. Does it mean that you do not wish to add CINEL to this repository now?

**Comment by andreitudos** [comment]
hi Philip, 
I made a mistake,  instead of putting pt/cinel/formandos.txt, I placed pt/formandos/cinel/formandos.txt.
Then I decided to close this request and open another request #4056.

**Comment by philipto** [comment]
@andreitudos Thank you for the clarification. I am closing this request as not needed because #4056 was just merged.

**Pull request closed without merging**
