### PR TITLE
Khadija University

### PR DESCRIPTION
**Pull request by hasibbd**

### CODE REVIEW

**Comment by philipto** [comment]
@hasibbd First stage of verification passed, official domain is [kum.edu.ng](https://kum.edu.ng) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@hasibbd Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by hasibbd** [comment]
@philipto https://kum.edu.ng/faculty-of-science-and-computing

**Comment by philipto** [comment]
@hasibbd Thank you. I saw that page. However when I click at any of "More details" buttons, I see just nothing new.
Thus, this is either incomplete program description, or a website that does not belong to the actual university.

In other words, I cannot verify if the university has the IT-related course in reality, because there is no detailed course description. Do you have the university curricula displayed somewhere else?

Thank you.

**Comment by philipto** [comment]
@hasibbd You might miss my previous comment. Please react.

**Comment by hasibbd** [comment]
let me talk with my University about this issues.

**Comment by philipto** [comment]
@hasibbd I am sorry, I have to close the request without merging. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Pull request closed without merging**
