### PR TITLE
Create student.romerocollege

### PR DESCRIPTION
**Pull request by JensYvanDeCraecker**

### CODE REVIEW

**Comment by philipto** [comment]
@JensYvanDeCraecker Please make sure that you are familiar with the rules of this repository located at the bottom of [this page](https://github.com/JetBrains/swot), and modify your request accordingly. 

The file path for student.romerocollege.be should be lib/domains/be/romerocollege/student.txt.

**Comment by JensYvanDeCraecker** [comment]
How do i create a folder?

**Comment by philipto** [comment]
@JensYvanDeCraecker If you do it in a GitHub web interface, the folder will be created automatically if you enter a name containing a slash character  /

**Comment by philipto** [comment]
@JensYvanDeCraecker I am closing this request because it is duplicated by #3291. Thank you.

**Pull request closed without merging**
