### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by nickapr77**
Please add Singapore International School @ Saigon South to your repository.

### CODE REVIEW

**Comment by philipto** [comment]
@nickapr77 Please provide us with:
* the school official website URL
* the school street address, including city and country
* more details on who study at the school: what age your students are, what kind of subjects they study?

Thank you.

**Comment by nickapr77** [comment]
Morning Philip,


   - https://saigonsouth.sis.edu.vn/
   - 29 Đường số 3 Khu dân cư Trung Sơn, Đường số 6A, Khu Phố 4, Bình
   Chánh, Thành phố Hồ Chí Minh, 70000
   - The school is made up of K to 12th grade students of different
   nationalities, but mostly Vietnamese. Their ages range from 4 to 18. They
   study S.T.E.A.M. subjects and all have access to iPads. I am the Business
   and ICT teacher for the high school; so I teach grades 9-12. We learn
   about Python, html, css and php mainly.


If you would like proof of my position, you're welcome to email me at the
following address: ***@***.*** or you can
see my details on the staff page of our website:
https://saigonsouth.sis.edu.vn/about-us/academic-staff/

Kind Regards,

Nicholas Payne-Roberts

**Comment by W3b-crawl3r** [comment]
https://esisa.ac.ma
29 bis avenue ibn khatib, route d'imouzzer, fès 30050
city : fes
country : morroco
it's a school of software engineering and computer science
ages are around 18 to 22
for the subject : C / oop / java / sql / assembly / digital electronics /
python / web dev / oracle database ...

**Comment by nickapr77** [comment]
> @nickapr77 Please provide us with:
> 
> * the school official website URL
> * the school street address, including city and country
> * more details on who study at the school: what age your students are, what kind of subjects they study?
> 
> Thank you.

Morning Philip,

Has the school been added yet?

**Comment by philipto** [comment]
@nickapr77 I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by nickapr77** [comment]
I have now folked it again and re-submitted the pull request. Not sure what went wrong with the last one.

**Pull request closed without merging**
