### PR TITLE
Create leerling.kandinskycollege

### PR DESCRIPTION
**Pull request by notcooler**

### CODE REVIEW

**Comment by philipto** [comment]
@notcooler lib/domains/nl/leerling.kandinskycollege: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by notcooler** [comment]
> @notcooler lib/domains/nl/leerling.kandinskycollege: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.    

Hey,

I reae the rules but i still dont get it. Am i supposed to make a directory named leerling than a text file named kandinskycollege?

**Comment by philipto** [comment]
@notcooler lib/domains/nl/leerling.kandinskycollege: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by notcooler** [comment]
thanks i get it now i will create another pull request for it!

**Pull request closed without merging**
