### PR TITLE
Add Universitas Peradaban

### PR DESCRIPTION
**Pull request by natsuki-yasumi**
### University Name
Universitas Peradaban

### Website
https://peradaban.ac.id/

### CODE REVIEW

**Comment by philipto** [comment]
@natsuki-yasumi First stage of verification passed, official domain is [peradaban.ac.id](https://peradaban.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by natsuki-yasumi** [comment]
Ok sir.. Thankyou 😁

**Comment by philipto** [comment]
@natsuki-yasumi Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by natsuki-yasumi** [comment]
Thankyou

**Pull request merged**
