### PR TITLE
trakia-uni.bg

### PR DESCRIPTION
**Pull request by promonad**
trakia-uni.bg

### CODE REVIEW

**Comment by sopcommand** [comment]
tsotskolauri.levani@students.gov.ge

ISANI DISTRICT, PUBLIC SCHOOL #216

 https://www.facebook.com/სსიპ-ქთბილისის-N216-საჯარო-სკოლა-473256156339558

**Comment by philipto** [comment]
@promonad Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@promonad You might miss my previous comment. Please react.

**Comment by promonad** [comment]
1. http://www.uni-sz.bg || http://uni-sz.bg/engl
2. Trakia University, 6000 Stara Zagora, Student's campus, BULGARIA
https://www.google.com/maps/place/%D0%A2%D1%80%D0%B0%D0%BA%D0%B8%D0%B9%D1%81%D0%BA%D0%B8+%D0%A3%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0%B5%D1%82/@42.4007147,25.5711639,15z/data=!4m5!3m4!1s0x0:0x9b28a6a11c26f997!8m2!3d42.4007147!4d25.5711639

3. http://uni-sz.bg/truni7/blog/%d1%80%d0%b0%d0%ba%d0%b8%d0%b9%d1%81%d0%ba%d0%b8-%d1%83%d0%bd%d0%b8%d0%b2%d0%b5%d1%80%d1%81%d0%b8%d1%82%d0%b5%d1%82-%d1%81%d1%82%d0%b0%d1%80%d1%82%d0%b8%d1%80%d0%b0-%d0%bf%d1%80%d0%b8%d0%b5%d0%bc/
4. www.trakia-uni.bg – Google Apps for Education – Trakia university

**Comment by promonad** [comment]
image

**Pull request merged**
