### PR TITLE
Update - Add school SMK Muhammadiyah Tasikmalaya

### PR DESCRIPTION
**Pull request by sapatekno**
Hello JetBrains.

I add our school SMK Muhammadiyah Tasikmalaya.
Our domain is https://www.smkmtsm.sch.id

We use a lot of products from jetbrains to support our teaching at school.

### CODE REVIEW

**Comment by sapatekno** [comment]
- An URL of a page on the official website where the school offers an IT-related long-term (>1 year) course [here](http://www.smkmtsm.sch.id/rpl/)
- Evidence that the school is registered with the ministry of education [here](https://dapo.kemdikbud.go.id/sekolah/87017124879882F8A2B0)

**Comment by philipto** [comment]
@sapatekno First stage of verification passed, official domain is [smkmtsm.sch.id](https://smkmtsm.sch.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@sapatekno Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by sapatekno** [comment]
Thanks @philipto.

**Pull request merged**
