### PR TITLE
Adding STJUDE to the domain

### PR DESCRIPTION
**Pull request by hectordolo**
Active Domain of the School: https://www.stjude.edu.ph/

### CODE REVIEW

**Comment by philipto** [comment]
@hectordolo First stage of verification passed, official domain is [stjude.edu.ph](https://stjude.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@hectordolo Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by hectordolo** [comment]
@philipto Hi, here is the link containing the courses offered including our BS in Computer Science Offering: https://www.stjude.edu.ph/admission.php I have also attached out curriculum for additional reference. Thank You.
[BSCS CURRICULUM.pdf](https://github.com/JetBrains/swot/files/10761468/BSCS.CURRICULUM.pdf)

**Comment by philipto** [comment]
@hectordolo Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by hectordolo** [comment]
@philipto Thanks a lot :) ..

**Pull request merged**
