### PR TITLE
Add online g3

### PR DESCRIPTION
**Pull request by DroneDude1**
Add online G3 to repository. The website is onlineg3.com.

### CODE REVIEW

**Comment by philipto** [comment]
@DroneDude1 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.
Also, please let us see a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by DroneDude1** [comment]
The class link is https://www.onlineg3.com/product/asu-cis-105-computer-applications-and-information-technology/
I am not sure how to get a proof. I will ask my teacher on Monday if she knows anything.

**Comment by philipto** [comment]
Hi @DroneDude1! Do you have any update?

**Comment by DroneDude1** [comment]
Yes. I just received a screenshot from my teacher with the domain in her Azure files, if that helps.
Screen Shot 2022-11-14 at 4 50 46 PM

**Comment by philipto** [comment]
@DroneDude1  Thank you for the clarifications. Pull request merged.

**Pull request merged**
