### PR TITLE
Tbilisi State Academy of Arts

### PR DESCRIPTION
**Pull request by georgegozal**

### CODE REVIEW

**Comment by philipto** [comment]
@georgegozal First stage of verification passed, official domain is [art.edu.ge](https://art.edu.ge) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by tenthreee** [comment]
@georgegozal Please provide us with the URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by philipto** [comment]
@georgegozal You might miss my previous comment. Please react.

**Comment by georgegozal** [comment]
Hello, sorry for not replying before, this is the website :
https://art.edu.ge/aceng/ but i'm not sure about it courses.

ხუთ, 15 თებ. 2024, 12:24-ში Philip Torchinsky-მა ***@***.***>
დაწერა:

**Comment by philipto** [comment]
@georgegozal Thank you! It looks like the school is not eligible for this repository because of lack of long-term IT courses.

Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.
Thank you for your understanding!

**Pull request closed without merging**
