### PR TITLE
Adding Tuttoo community school to the list

### PR DESCRIPTION
**Pull request by tuttoo-admin**
We are a new community service school for vocational learning based out of Delhi India.

### CODE REVIEW

**Comment by tuttoo-admin** [comment]
tuttoo.in

support -  wecare@tuttoo.in

**Comment by tuttoo-admin** [comment]
@philipto i see that this was skipped while you normally go in a sequential manner. Is there any way i can be helpful?

**Comment by tuttoo-admin** [comment]
image

**Comment by tuttoo-admin** [comment]
@philipto

**Comment by philipto** [comment]
@tuttoo-admin Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@tuttoo-admin You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@tuttoo-admin I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
