### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by JahnTeigen**

### CODE REVIEW

**Comment by philipto** [comment]
@JahnTeigen file/lib/domains/no/bfk.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@JahnTeigen Please clarify if @bfk.no addresses are assigned to the school employees and students only, or to the entire commune. Thank you!

**Comment by philipto** [comment]
@JahnTeigen You might miss my previous comment. Please react.

**Comment by JahnTeigen** [comment]
> @JahnTeigen You might miss my previous comment. Please react.

Hello, sorry for my late response. The bfk emails are assigned to students and employees.

**Comment by philipto** [comment]
@JahnTeigen First stage of verification passed, official domain for **Kongsberg Videregående Skole** is [bfk.no](https://bfk.no) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@JahnTeigen Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
