### PR TITLE
added nur.edu.bo domain

### PR DESCRIPTION
**Pull request by jmacboy**

### CODE REVIEW

**Comment by philipto** [comment]
@jmacboy Please provide us with:
- the school official website URL (it is different from nur.edu.bo, according to our findings)
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@jmacboy You might miss my previous comment. Please react.

**Comment by jmacboy** [comment]
Hi Phillip, sorry for the wait,

The school official website URL is nur.edu, but the email they gave us as students and teachers have the domain @nur.edu.bo

[https://www.nur.edu/ingenieria-de-sistemas](https://www.nur.edu/ingenieria-de-sistemas) is the URL for the degree in computer science of the university.

There's no official announcement for this domain outside the internal emails and internal group chats, but the nur.edu.bo domain redirects to nur.edu and if you look at the whois of the domain:
https://whois.domaintools.com/nur.edu.bo you can see that the domain is bought by the university itself.
They mostly use that domain with its outlook and teams accounts, which are the ones we have access to.

**Comment by philipto** [comment]
@jmacboy Thank you for the clarification. Pull request merged.

**Pull request merged**
