### PR TITLE
British School of Marketing International

### PR DESCRIPTION
**Pull request by josebsmi**

### CODE REVIEW

**Comment by philipto** [comment]
@josebsmi Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university. Thank you.

**Comment by netaiko** [comment]
Hi Philip,
https://www.britishschoolofmarketing.com/students/course/digital-marketing
Thank you very much,
Jose

**Comment by netaiko** [comment]
Sorry but the courses of digital marketing there is no longer enough. The long courses are NVQ courses.  https://www.britishschoolofmarketing.com/students/course/nvq-5-leadership
I don't know it is valid or not.
Thank you,
Jose

**Comment by philipto** [comment]
@josebsmi The problem with the course is that it is not explicitly said how long it takes, and also the description does not provide any clue if programming is somehow included into the course. Thus, I don't see a necessity for the students who take this course to use any programming tool. 

It is important for JetBrains to grant an access to the tools to the students who really need them, not to anybody who studies some, even not relevant, subject. May I ask you to describe your case in more details? Why do you think that students of this school need JetBrains tools? Which ones? If a majority of them don't need the tools, but you need it, you can apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students). The latter does not require you to be enrolled for a particular course, it's fine just to be a student.

**Comment by netaiko** [comment]
Hi Philip,

Yes, don't worry about it. It is not absolutely necessary at all for the courses. 

Sorry, I appreciate your help. 

Thank you very much anyway,

Kind Regards,
Jose

**Comment by philipto** [comment]
@josebsmi Thank you for the clarification! I have to close this request without merging due to the issues described above. Shall you have any questions, concerns or feedback, please email JetBrains at community-support@jetbrains.com. Thank you for the understanding!

**Pull request closed without merging**
