### PR TITLE
Faculdade Mater Dei

### PR DESCRIPTION
**Pull request by wolmirgarbin**
Registrer of Faculdade Mater Dei

### CODE REVIEW

**Comment by philipto** [comment]
@wolmirgarbin Pull request merged. Thank you!

**Comment by HugoIso5g** [comment]
Register Uningranrio

**Comment by Jcarlos545** [comment]
unopar

**Comment by rhenanpaixao** [comment]
Registrer of estacio de sa

**Comment by pedrolanten** [comment]
Registrer of Anhanguera Taguatinga FACNET.
https://www.anhanguera.com/graduacao/localidades/taguatinga_facnet.php

**Comment by edivaldodeoliveira** [comment]
Registrer of Instituto Federal de Santa Catarina

**Comment by Joaobosco03** [comment]
Register Cruzeiro Do Sul

**Comment by BrendaEvans28** [comment]
Registrador da Faculdade de Tecnologia Professor hirant Sanazar

**Comment by philipto** [comment]
@BrendaEvans28 @Joaobosco03 @edivaldodeoliveira @pedrolanten @rhenanpaixao @Jcarlos545 @HugoIso5g Please create a separate pull request if you wish me to add domains of your universities to this repository. If you don't know how to do it, please consider an option to learn git and GitHub. If it's urgent matter and you are unable to learn GitHub quick enough, please send an email to community-support@jetbrains.com and explain which email domain of which university you would like to add to SWOT and why. 

Please notice that the request which you comment or answer to, is already merged, and this comments thread is not being monitored, thus email community-support@jetbrains.com instead of replying this email and/or comment. Thank you.

**Comment by Humbertotl** [comment]
Register estudante.sc.senai.br, please

**Comment by ksouza94** [comment]
Register fadergs.com.br, please.

**Comment by profnatal** [comment]
Register https://www.anhanguera.com/unidade/nova-marilandiamt-i15364754a/

Please!!

**Comment by danielleeugeniocosta** [comment]
Registrador da Faculdade de Tecnologia Professor hirant Sanazar

**Comment by ruangja** [comment]
registre Ruan

**Comment by Leobit89** [comment]
Register Universidade Federal Fluminense

**Comment by VitorferrariM** [comment]
Cadastro universidade uninove/nove de julho vila maria

**Comment by tassiomanoel** [comment]
Hi, please register at the college https://ava.faveni.edu.br/ 
BR

**Comment by lucianolelespadilha** [comment]
Por favor, cadastre a https://uniube.br/.

**Comment by MarcosBJJ** [comment]
Cadastre a UCDB - Universidade Católica Dom Bosco por gentileza. Obrigado.

**Comment by joaobuga35** [comment]
Register Faculdade Descomplica

**Comment by ewkekw** [comment]
Register UNDBhttps://www.undb.edu.br/

**Comment by rogildomartins** [comment]
Cadastra a  Faculdade Católica paulista https://www.uca.edu.br/
Essa faculdade usa o email particular da gente, eles não disponibiliza email acadêmico .

**Comment by tassiomanoel** [comment]
Boa noite, podem cadastrar a universidade unifatecie?
 https://unifatecie.edu.br/

Em sáb., 16 de dez. de 2023 21:56, Manoel Rogildo ***@***.***>
escreveu:

**Comment by muelsa0314** [comment]
Register https://us.edu.cv/

**Pull request merged**
