### PR TITLE
Created 42 Urduliz Token

### PR DESCRIPTION
**Pull request by JOKITON**
Created by JOKITON.

Thank you JetBrains!

### CODE REVIEW

**Comment by JOKITON** [comment]
Official Page: https://www.42urduliz.com/

**Comment by philipto** [comment]
@JOKITON First stage of verification passed, official domain is [42urduliz.com](https://42urduliz.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@JOKITON Pull request merged. Thank you.

**Comment by JOKITON** [comment]
Thank you!!

Have a great day man!!

**Pull request merged**
