### PR TITLE
Added kist college domain

### PR DESCRIPTION
**Pull request by sapkotamadhusudan**
Established in 1995, KIST is now a top +2 college in Nepal that offers high standard NEB + 2 Science & Management courses, a range of top quality Bachelor’s degrees – BBA, BIM, BIT, BBS & BSc Microbiology – followed by excellent Master’s degrees – MBS & MSc Microbiology.

Domain: https://kist.edu.np/introduction

### CODE REVIEW

**Comment by philipto** [comment]
@sapkotamadhusudan First stage of verification passed, official domain is [kist.edu.np](https://kist.edu.np) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by sapkotamadhusudan** [comment]
@philipto Thanks for the updates 😊

**Comment by sapkotamadhusudan** [comment]
Hi @philipto any updates on this?

**Comment by philipto** [comment]
@sapkotamadhusudan Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
