### PR TITLE
Add Ifsuldeminas.

### PR DESCRIPTION
**Pull request by leojacondev**
Governamental Institute on Brazil.

### CODE REVIEW

**Comment by leojacondev** [comment]
Website describing IT/Web Development Course:
https://pcs.ifsuldeminas.edu.br/index.php?option=com_content&view=article&id=238&Itemid=214

**Comment by philipto** [comment]
@leojacondev Please rename lib/domains/br/edu/ifsuldeminas to lib/domains/br/edu/ifsuldeminas.txt. Thank you.

**Comment by philipto** [comment]
@leojacondev Pull request merged. Thank you!

**Comment by leojacondev** [comment]
Hey, users who's have email user@alunos.ifsuldeminas.edu.br will have access, or I need to create lib/domains/br/edu/ifsuldeminas/alunos.txt?

**Pull request merged**
