### PR TITLE
add etec

### PR DESCRIPTION
**Pull request by ivamzamorano**
add etec (@etec.sp.gov.br)

### CODE REVIEW

**Comment by ivamzamorano** [comment]
add etec (@etec.sp.gov.br)

**Comment by GustavoAlvesSilva** [comment]
We opened the same PR with a difference of 1 minute lol kkk

**Comment by ivamzamorano** [comment]
Congratulations on your initiative!
I'm from ETECVAV in Jundiaí/SP and you?

Parabéns pela iniciativa!
Eu sou da ETECVAV em Jundiaí/SP e você?

**Comment by philipto** [comment]
@ivamzamorano I am sorry, the domain etec.sp.gov.br is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to GitHub Student Developer Pack at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
