### PR TITLE
Create iitkgp.txt

### PR DESCRIPTION
**Pull request by geremih**
Adding domain of Indian Institute of Technology, Kharagpur

### CODE REVIEW

**Comment by zweizwei** [comment]
the university website seems to be http://www.iitkgp.ac.in/ - please provide some proof of the fact the provided domain also belongs to the university.

**Comment by geremih** [comment]
Link to the [ERP](https://erp.iitkgp.ernet.in)
Also, link to the [faculty page of the dean](http://www.iitkgp.ac.in/fac-profiles/showprofile.php?empcode=abmaT), hosted on iitkgp.ac.in with email address on the subdomain hijli.iitkgp.ernet.in

**Comment by geremih** [comment]
The domain has also been added on the original repo (https://github.com/leereilly/swot/pull/499)

**Comment by zweizwei** [comment]
thanks a lot, I'm adding the domain.

**Pull request merged**
