### PR TITLE
Addition of School 

### PR DESCRIPTION
**Pull request by junaidiqbalturk**

### CODE REVIEW

**Comment by philipto** [comment]
@junaidiqbalturk Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@junaidiqbalturk You might miss my previous comment. Please react.

**Comment by junaidiqbalturk** [comment]
philipto yes, i am going to share the required details

**Comment by junaidiqbalturk** [comment]
https://codelogicsolution.com  the institute is just established here in Pakistan and the website is currently under construction. 
the address of Institute is Building no 195 Street 87 F-10 Islamabad, Pakistan

**Comment by philipto** [comment]
@junaidiqbalturk Thank you for the clarification. For the newly established school there is not enough verifiable information in the net. I cannot add this domain to the trusted list.

Please enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

I have to close this request without merging.
Thank you for your understanding!

**Pull request closed without merging**
