### PR TITLE
Add Adolf-Reichwein-Schule Marburg

### PR DESCRIPTION
**Pull request by zandercodes**

### CODE REVIEW

**Comment by philipto** [comment]
@zandercodes Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@zandercodes You might miss my previous comment. Please react.

**Comment by zandercodes** [comment]
>* the school official website

[this](https://adolf-reichwein-schule.de/)

>* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

[this](https://adolf-reichwein-schule.de/bildungsangebote/hoehere-berufsfachschule/ita/) and [this](https://adolf-reichwein-schule.de/bildungsangebote/berufsschule/it-berufe/)

> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

An original document of my school where the email is called "schueler.ars-mr.de" you can find on the start page on the link "O365" -> Office 365 -> Orientation -> "Outlook=>E-Mail".

**Comment by philipto** [comment]
@zandercodes Thank you for the clarification. Pull request merged.

**Pull request merged**
