### PR TITLE
extension for University of Mannheim

### PR DESCRIPTION
**Pull request by ir2pid**
mbs.education Extension for the University of Mannheim, Deutschland.

### CODE REVIEW

**Comment by ir2pid** [comment]
added domain for University of Mannheim

**Comment by philipto** [comment]
@ir2pid Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@ir2pid You might miss my previous comment. Please reply.

**Comment by philipto** [comment]
@ir2pid You might miss my previous comment. Please reply.

**Comment by philipto** [comment]
@ir2pid I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
