### PR TITLE
Alternative domain

### PR DESCRIPTION
**Pull request by G-Om**
This is an Alternative domain for my college.
Given to many students

**College : https://dypic.in**

Location : India

Closed Pull Request :  #18274

Thankyou!

### CODE REVIEW

**Comment by philipto** [comment]
@G-Om First stage of verification passed, official domain is [adypsoe.in](https://adypsoe.in) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://adypsoe.in/contact.html

**Comment by G-Om** [comment]
Thankyou Philipto, i will be waiting for the merge.

**Comment by G-Om** [comment]
Hello can you please verify this pull request.

**Comment by philipto** [comment]
@G-Om Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
