### PR TITLE
University of Engineering and Technology, Peshawar

### PR DESCRIPTION
**Pull request by DanishKhan1492**
University Website URL:  https://www.uetpeshawar.edu.pk/

### CODE REVIEW

**Comment by philipto** [comment]
@DanishKhan1492 First stage of verification passed, official domain is [uetpeshawar.edu.pk](https://uetpeshawar.edu.pk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@DanishKhan1492 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by DanishKhan1492** [comment]
@philipto Thank you for merging the request when will I be able to renew my license?

**Comment by philipto** [comment]
In about an hour. Thank you!

**Pull request merged**
