### PR TITLE
Create mines-nancy.txt

### PR DESCRIPTION
**Pull request by mborgraeve**

### CODE REVIEW

**Comment by philipto** [comment]
@mborgraeve mines-nancy.org seems to be an official website of Ecole des Mines de Nancy Alumni Association. Could you please provide us with an official website address of the school itself, where we can see some IT-related courses offered by the school? Please be informed that JetBrains grant free licenses to students and teachers only, not to alumni. Thank you!

**Comment by mborgraeve** [comment]
Hi,
You can find all the courses on http://www.mines-nancy.univ-lorraine.fr/content/syllabus-20152016-0
The school has several domains though : univ-lorraine.fr because it is part of a bigger university, and mines-nancy.org, for historic reasons (we were independant at that time).

All Mines Nancy students are given an mines-nancy.org email, but you are right : they keep this address after leaving the school though, and it is used as well for alumnis.

Our IT Department have a non official gmail address if you prefer a different domain http://www.depinfonancy.net/ (link in http://www.mines-nancy.univ-lorraine.fr/content/syllabus-20152016-0 on Information and Systems bloc).

Your call :)

Thanks !
Matthieu

**Comment by philipto** [comment]
@mborgraeve Thank you so much for the clarification! We try and avoid including alumni domains into this repository. There are several possible solutions for this issue:

1) Adding univ-lorraine.fr domain to the repository. It's correct from all points of view: this is the university domain, and it fomally fits the repository rules requirements. However it does not resolve the issue if you do not have an email in univ-lorraine.fr domain.
2) Adding mines-nancy.org domain. It is formally correct, because you have explained that the domain is used  by the students. However this solution requires some good discipline from the alumni: they have to obey the license and stop using JetBrains tools for free as soon as they graduate from the university. A good side of this solution is that JetBrains grants all graduates (who used our tools for free when they were students) with a significant discount for the license upon their graduation.
3) adding depinfonancy.net domain. It is a bit different story, because the domain is owned by the IT department, and there are a lot of people using it, including those who are not students or teachers. In general, we avoid adding such a domain to the repository if understand that there are many non-students using this domain.

I like solutions 1 and 2, because we believe that most of our users are honest and have good intentions. Please let me know which solution you think is best for Mines Nancy students. Thank  you!

**Comment by philipto** [comment]
@mborgraeve I am closing this request without merging because we added depinfonancy.net as per request #2108. Thank you!

**Pull request closed without merging**
