### PR TITLE
Added UNEDL to the list!

### PR DESCRIPTION
**Pull request by Superlasek**
UNEDL Software Engineering community is here!

### CODE REVIEW

**Comment by philipto** [comment]
@Superlasek Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by Superlasek** [comment]
> @Superlasek You might miss my previous comment. Please react.

Hi, thank you very much for the feedback.
I have a question, currently my coordinator is making a document to show as a proof.

Can I upload it to Google Drive and comment the direct link to the PDF in another reply?

Or where do I have to upload the proof to?

**Comment by philipto** [comment]
@Superlasek You can upload it to Google drive and post a link to it here in a comment. You can also upload it directly to here in a comment to this request, it's up to you. Thank you!

**Comment by philipto** [comment]
@Superlasek I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
