### PR TITLE
Add Beaumont School

### PR DESCRIPTION
**Pull request by kivox**

### CODE REVIEW

**Comment by philipto** [comment]
@kivox Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by kivox** [comment]
- the school official website URL
    - 
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by kivox** [comment]
the school official website URL: https://beaumontschool.com/

the school street address, including city and country: Beaumont School, Austen Way, St Albans. Hertfordshire, AL4 0XB, England, United Kingdom

an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: 
https://beaumontschool.com/subjects-offered/
https://beaumontschool.com/wp-content/uploads/2018/01/Computer-Science-2018.pdf

a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
https://beaumontschool.com/contact/
I'm unsure, what other proof I can provide for student emails. beaumont.school, is the domain used for most internal communication between students, teachers and departments.

**Comment by philipto** [comment]
@kivox  Thank you for the clarifications. 
Thank you also for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
