### PR TITLE
Create ekodom.txt

### PR DESCRIPTION
**Pull request by TheSkrypt**
Added my school

### CODE REVIEW

**Comment by TheSkrypt** [comment]
Real website is www.oadomazlice.cz, just our emails are under this domain.

**Comment by philipto** [comment]
@TheSkrypt Pull request merged. Thank you!

**Comment by TheSkrypt** [comment]
Hello, thank you - how long does it usually take for your systems to recognize the change? It still says the school doesn't exist.

**Comment by philipto** [comment]
@TheSkrypt 30 minutes or so. Please try again a bit later and let us know if it still does not work. Thank you!

**Comment by TheSkrypt** [comment]
It worked, thank you very much. :-)

**Pull request merged**
