### PR TITLE
add High School of Mathematics "Acad. Kiril Popov"

### PR DESCRIPTION
**Pull request by Martizong**
- the school official website URL: https://omg-bg.com/
- the school street address, including city and country: https://goo.gl/maps/H4NAtziVnfKw7twV7

Thanks in advance.

### CODE REVIEW

**Comment by philipto** [comment]
@Martizong Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by Martizong** [comment]
Hi @philipto 

Thanks for the quick response.

We were instructed in class that our e-mails must be built the following way:
`<firstname><lastname>_v19@schoolmath.eu`
ex. mine is: `martinnaidenov_v19@schoolmath.eu`
and use them in http://mail.omg-bg.com/

We were not provided with any hard-copy (letter) or electronic instructions or referances.

**Comment by philipto** [comment]
@Martizong Could you please ask your teacher to make such a note, typed, printed, or hand-written, and sign it with the teacher's name? Literally, 

```
I, <FisrtName LastName>, a teacher of High School of Mathematics "Acad. Kiril Popov", 
confirm that students of our school are required to use the school's email addresses 
having a pattern: <firstname><lastname>_v19@schoolmath.eu.

<Date, Signature>
```

Then you can upload this note as a comment to your pull request at https://github.com/JetBrains/swot/pull/12882 using your browser.

**Comment by philipto** [comment]
@Martizong You might miss my previous comment. Please react.

**Comment by Martizong** [comment]
@philipto Apologies, I did see your previous comment and I'm in the process of getting in contact with my teacher whenever she's free.

**Comment by Martizong** [comment]
Hi @philipto this is my teachers response.

image

**Comment by philipto** [comment]
@Martizong Thank you for your patience while there was a delay with processing your request.
Pull request merged. Thank you!

**Pull request merged**
