### PR TITLE
CS2I Lorient update

### PR DESCRIPTION
**Pull request by Giugiu-CS2I**

### CODE REVIEW

**Comment by philipto** [comment]
@Giugiu-CS2I Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Giugiu-CS2I You might miss my previous comment. Please react.

**Comment by Giugiu-CS2I** [comment]
Hello,
Sorry I missed your last comment.

Here is the requested information:
- the school official website URL : [https://www.cci-formation-bretagne.fr/](https://www.cci-formation-bretagne.fr/)

- the school street address, including city and country : 
   Lorient - CCI Formation
   21 quai des Indes
   56100 Lorient 
   
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course :
   [https://www.cci-formation-bretagne.fr/cci-formation-56-lorient/lorient/manager-de-solutions-digitales-et-data-ms2d](https://www.cci-formation-bretagne.fr/cci-formation-56-lorient/lorient/manager-de-solutions-digitales-et-data-ms2d)
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
 What kind of documents do I need to provide you with?

**Comment by Giugiu-CS2I** [comment]
> @Giugiu-CS2I Please provide us with:
> 
> * the school official website URL
> * the school street address, including city and country
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Hello,
Sorry I missed your last comment.

Here is the requested information:

the school official website URL : https://www.cci-formation-bretagne.fr/

the school street address, including city and country :
Lorient - CCI Formation
21 quai des Indes
56100 Lorient

an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course :
https://www.cci-formation-bretagne.fr/cci-formation-56-lorient/lorient/manager-de-solutions-digitales-et-data-ms2d

a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
What kind of documents do I need to provide you with?

**Comment by philipto** [comment]
@Giugiu-CS2I Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged. I found the domain ownership proof material: https://www.cci-formation-bretagne.fr/Formation/pdf?formationId=1714&etablissementId=11&localisationId=49

**Pull request merged**
