### PR TITLE
Business Academy Smilevski - BAS

### PR DESCRIPTION
**Pull request by riste86**

### CODE REVIEW

**Comment by philipto** [comment]
@riste86 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@riste86 You might miss my previous comment. Please react.

**Comment by riste86** [comment]
These are the links for the subjects:

1. Computer science - https://bas.edu.mk/dl/predmetni-programi/biznis-menadzment/01g01s_KOM_PredmetnaPrograma.pdf
2. Information systems - https://bas.edu.mk/wp-content/uploads/2022/08/marketing-menadzment-informacioni-sistemi.pdf

But unfortunately we have the program only in macedonian.

Regards,
Riste

**Comment by philipto** [comment]
@riste86 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
