### PR TITLE
Create mediamatika.sk

### PR DESCRIPTION
**Pull request by sk-juroot**
mediamatika.sk is domain used by Department of Mediamatics and Cultural Heritage as a part of Faculty of Humanities, University of Žilina
accounts are assigned only for students and teachers on this department
official source (faculty website): http://fhv.uniza.sk/web/index.php/katedry/katedra-mediamatiky-a-kulturneho-dedicstva

### CODE REVIEW

**Comment by sk-juroot** [comment]
IT related courses:
- web production (http://vzdelavanie.uniza.sk/vzdelavanie/planinfo.php?kod=197797)
- information networks (http://vzdelavanie.uniza.sk/vzdelavanie/planinfo.php?kod=197802)
- design of web applications (http://vzdelavanie.uniza.sk/vzdelavanie/planinfo.php?kod=197613)
- programming (http://vzdelavanie.uniza.sk/vzdelavanie/planinfo.php?kod=197630)
- Introduction to Al and expert systems (http://vzdelavanie.uniza.sk/vzdelavanie/planinfo.php?kod=197968)

**Comment by philipto** [comment]
@sk-juroot Thank you for the details! Could you please help me to see a connection between mediamatika.sk domain and the university? Whois service says that the domain is registered, but no registrant given:

`$ whois mediamatika.sk`
`Domain-name         mediamatika.sk`
`Admin-id            EXOT-0004`
`Admin-name          EXO TECHNOLOGIES spol. s r.o.`
`Admin-legal-form    s.r.o`
`Admin-org.-ID       36485161`
`Admin-address       Garbiarska 3, Stara Lubovna 06401`
`Admin-email         support@exohosting.sk`
`Tech-id             EXOT-0004`
`Tech-name           EXO TECHNOLOGIES spol. s r.o.`
`Tech-org.-ID        36485161`
`Tech-address        Garbiarska 3, Stara Lubovna 06401`
`Tech-email          support@exohosting.sk`
`dns_name            ns.exohosting.sk`
`dns_name            ns1.exohosting.sk`
`dns_name            ns3.exohosting.sk`
`Last-update         2016-02-19`
`Valid-date          2017-02-21`
`Domain-status       DOM_OK`

The page  http://fhv.uniza.sk/web/index.php/katedry/katedra-mediamatiky-a-kulturneho-dedicstva does not provide an info about mediamatika.sk domain too.

I am happy to add the domain to the repository as soon as you give us a reference saying explicitly that it is used by the students.

**Comment by sk-juroot** [comment]
This gets a little tricky to explain..

Mentioned page http://fhv.uniza.sk/web/index.php/katedry/katedra-mediamatiky-a-kulturneho-dedicstva  is official website of faculty where our department is. Every department got its website on link http://fhv.uniza.sk/<abbr_of_dept>/   Our department decided to try an experiment - offer for students and teachers Google Apps for Education and our internal systems were not capable of that configuration. So we registered mediamatika.sk which is now used as official domain for our department and (finally) is linked from http://fhv.uniza.sk/kmkd/ directly.. (kmkd stands for  department [Katedra] of mediamatics [Mediamatiky] and cultural [Kultúrneho] heritage [Dedičstva])

You can verify that link on faculty website leads to domain mediamatika.sk

**Comment by philipto** [comment]
@sk-juroot Thank you for the explanation. Pull request merged.

**Pull request merged**
