### PR TITLE
Added generated files

### PR DESCRIPTION
**Pull request by AbhinavPWN**

### CODE REVIEW

**Comment by AbhinavPWN** [comment]
education added

**Comment by philipto** [comment]
@AbhinavPWN file/lib/domains/np/edu/nagarjunacollege.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by AbhinavPWN** [comment]
corrected file path format

**Comment by philipto** [comment]
@AbhinavPWN First stage of verification passed, official domain is [nagarjunacollege.edu.np](https://nagarjunacollege.edu.np) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@AbhinavPWN Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
