### PR TITLE
Add this school please

### PR DESCRIPTION
**Pull request by LawyerN**
http://www.iv-lo.tarnow.pl/liceum2/

### CODE REVIEW

**Comment by LawyerN** [comment]
http://www.iv-lo.tarnow.pl/liceum2/

**Comment by philipto** [comment]
@LawyerN Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@LawyerN You might miss my previous comment. Please react.

**Comment by LawyerN** [comment]
> @LawyerN You might miss my previous comment. Please react.

Oh sorry, for now I am not able to provide any evidence or something because of the summer brake but when the school begins I will get necessary papers and I will write a request again

**Comment by philipto** [comment]
@LawyerN Thank you for letting me know. Thud, I have to close the request for now. Please reopen it or create a new one as soon as you have the update on the matter. Thank you!

**Pull request closed without merging**
