### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by darealhamood66**
I applied to add my school to jet brains in order to get jet brains' free products and a school website URL was requested but my school doesn't have one. So all I can provide is the school's address and a document that proves that I am a student in the school.

### CODE REVIEW

**Comment by philipto** [comment]
@darealhamood66 Please provide us with the info that we already requested in a similar request #14568.

Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by darealhamood66** [comment]
My school does not have an official website, so all what I can provide you with will be the school address and a proof that the email domain I am using is an official students' email domain.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by philipto** [comment]
@darealhamood66 Yes, thank you for the clarification. Please provide us with will be the school address and a proof that the email domain you are using is an official students' email domain. It will be enough.

Thank you.

**Comment by darealhamood66** [comment]
For proving that my email domain is an official students' email domain, what type of proof is needed ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by darealhamood66** [comment]
The school’s address: Hod Sakrah WA Abu Hamad, Borg El Arab, Alexandria Governorate 5221250 (30.86905261957053, 29.586700012720147)
The school’s official email: ***@***.******@***.***>
If you have any questions about the validity of the email domain I am using you can leave them on the school’s email.

**Comment by philipto** [comment]
@darealhamood66  Thank you for the clarifications. Pull request merged.

**Pull request merged**
