### PR TITLE
Create kantiwattwil.txt

### PR DESCRIPTION
**Pull request by emilmueller**

### CODE REVIEW

**Comment by philipto** [comment]
@emilmueller I am sorry, it looks like the school does not offer high or higher education to the students. We usually do not include primary and secondary schools to this repository, because secondary schools use community versions of our tools, and they are free for everybody, no special license or subscription is necessary to use them for free. Professional versions, which require paid subscriptions, make sense for colleges and universities. 

Do you really need professional versions of JetBrains tools? If yes, could you please tell us a bit more about the features which our community versions (such as IntelliJ IDEA Communuty) lack, and thus you need professional versions for your educational process?

**Comment by emilmueller** [comment]
@philipto Thank you for your message. My school is a college in Switzerland. We offer course in programming (http://www.kantiwattwil.ch/portrait/fachschaften/informatik.html) for 12th-grade-students. Besides that i manage a group of programming-enthusiasts. we meet once a week for coding, where we try to write programs for the real world - not just solving school problems.
in both classes i would like to use phpstorm to write web-applications with a tool that offers debugging.

I hope these are enough reasons.

thank you. greetings from switzerland.
emil

**Comment by philipto** [comment]
@emilmueller Thank you for the clarification! Pull request merged.

**Comment by emilmueller** [comment]
Thank you very much.

**Pull request merged**
