### PR TITLE
Create st.txt

### PR DESCRIPTION
**Pull request by elio-bteich**

### CODE REVIEW

**Comment by philipto** [comment]
@elio-bteich Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@elio-bteich You might miss my previous comment. Please react.

**Comment by elio-bteich** [comment]
The problem is that my school doesn’t have a website Sent from Mail for Windows 10 From: Philip TorchinskySent: Monday, May 17, 2021 8:59 AMTo: JetBrains/swotCc: elio-bteich; MentionSubject: Re: [JetBrains/swot] Create st.txt ***@***.*** You might miss my previous comment. Please react.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by philipto** [comment]
@elio-bteich Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close this request without merging.

Thank you for your understanding!

**Pull request closed without merging**
