### PR TITLE
Wild code school added

### PR DESCRIPTION
**Pull request by RoYaLSleT**
Adding Wild Code School from Europe !

### CODE REVIEW

**Comment by TheAfnoR** [comment]
[campus-la-chataigneraie.txt](https://github.com/JetBrains/swot/files/6873710/campus-la-chataigneraie.txt)

**Comment by philipto** [comment]
@RoYaLSleT Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by RoYaLSleT** [comment]
Hello & thanks for your reply !
 - https://www.wildcodeschool.com/
 -  17 Rue Delandine, 69002 Lyon, France (https://www.wildcodeschool.com/fr-FR/campus/lyon), they are a lot of campuses
 -  https://www.wildcodeschool.com/fr-FR/formations/formation-developpeur-web-alternance
 Thanks again :-)

**Comment by philipto** [comment]
@RoYaLSleT Thank you for the clarification. I am sorry for a delay with processing your request. Pull request is now merged. Thank you for your patience and cooperation.

**Pull request merged**
