### PR TITLE
Add Faculdade Interamericana de Porto Velho

### PR DESCRIPTION
**Pull request by raphaelheitor**
I would like to add Faculdade Interamericana de Porto Velho at your database.

### CODE REVIEW

**Comment by raphaelheitor** [comment]
Other domain from Faculdade Interamericana de Porto Velho.

**Comment by zweizwei** [comment]
@raphaelheitor the faculty's domain is www.uniron.edu.br/ - could you please somehow confirm that the committed domain also belongs to the school?

**Comment by raphaelheitor** [comment]
My email as a teacher faculty's is: raphael.heitor@infouniron.com.br.
Have a site on sites google: www.infouniron.com (only accessed with email) (like a intranet).
You need more?

**Comment by zweizwei** [comment]
@raphaelheitor thanks for the further explanation - should be enough, i'm adding the domain

**Comment by raphaelheitor** [comment]
thanks @zweizwei.

**Pull request merged**
