### PR TITLE
Scott County Schools

### PR DESCRIPTION
**Pull request by Exehad**

### CODE REVIEW

**Comment by martincangaa** [comment]
[educastur.txt](https://github.com/JetBrains/swot/files/7621470/educastur.txt)

**Comment by martincangaa** [comment]
[educastur.txt](https://github.com/JetBrains/swot/files/7621478/educastur.txt)

**Comment by martincangaa** [comment]
[educastur.txt](https://github.com/JetBrains/swot/files/7621503/educastur.txt)

**Comment by martincangaa** [comment]
[file.zip](https://github.com/JetBrains/swot/files/7621523/file.zip)

**Comment by martincangaa** [comment]
[educastur.txt](https://github.com/JetBrains/swot/files/7621526/educastur.txt)

**Comment by Exehad** [comment]
Main website: https://www.scott.kyschools.us

Can't find a program list however I found our department listing which includes emails and shows we offer a computer science course: https://www.scott.k12.ky.us/25/Content2/careerandtechdept

**Comment by philipto** [comment]
@Exehad Pull request merged. Thank you!

**Pull request merged**
