### PR TITLE
add set.edu.vn

### PR DESCRIPTION
**Pull request by travistran1989**
Viện Điện tử Viễn thông, Đại học Bách Khoa Hà Nội
Institute of Electronics and Telecommunications, Hanoi University of Science and Technology

http://set.edu.vn/

### CODE REVIEW

**Comment by travistran1989** [comment]
Please add my university. Thank you!

**Comment by travistran1989** [comment]
Please add my university. Thank you!

Viện Điện tử Viễn thông, Đại học Bách Khoa Hà Nội
Institute of Electronics and Telecommunications, Hanoi University of Science and Technology

http://set.edu.vn/

**Comment by philipto** [comment]
@travistran1989 I am sorry, this request has signs of fraud. I have to close it without merging. If you are a student of any of these schools, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Comment by hungcrush** [comment]
đúng là người VN, còn chơi Iframe đồ. vãi bác :))

**Comment by hungcrush** [comment]
Chời Iframe đồ :)) Vãi bác

**Comment by travistran1989** [comment]
Sincere apologies everyone. I was too careless, did not verify carefully before submitting this request. This is the domain that our students asking for help. Hope everyone sympathized. Thank @hungcrush for letting me know.

**Pull request closed without merging**
