### PR TITLE
Creating ivobrugge.be

### PR DESCRIPTION
**Pull request by sderdeyn**
CVO IVO Brugge
Link to our IT and programming courses: http://www.ivobrugge.be/hbo_informatica

### CODE REVIEW

**Comment by philipto** [comment]
@sderdeyn Could you please confirm that your programming courses are long-term? Is there any reference to the courses duration?

**Comment by sderdeyn** [comment]
@philipto Absolutely. The following pages display all modules in our programming courses. The average time to complete is 6 semesters (3 years)

- http://www.ivobrugge.be/default.aspx?main=opleidingen&opl=hbo&mnu_itm=hbo_inf_moduletrajecten&cont_type=1
- http://www.ivobrugge.be/default.aspx?main=opleidingen&opl=hbo&mnu_itm=ea8dca43-422d-4d7b-a098-124b742d4d98&cont_type=1

Let me know if you need additional info.

**Comment by philipto** [comment]
@sderdeyn Thank you for the clarification! I am sorry that I did not mention another problem in my previous comment: could you please rename lib/domains/be/ivobrugge to lib/domains/be/ivobrugge.txt to reflect this repository rules? I merge the pull request as soon as you do it. Thank you!

**Comment by sderdeyn** [comment]
@philipto Oops. I corrected the name in a new commit. Thanks!

**Comment by philipto** [comment]
@sderdeyn Thank you! Pull request is now merged.

**Comment by sderdeyn** [comment]
@philipto Thanks Philip!

**Pull request merged**
