### PR TITLE
generated file

### PR DESCRIPTION
**Pull request by jerin-priya**
generated file that contains my university name

### CODE REVIEW

**Comment by philipto** [comment]
@jerin-priya file/lib/domains/edu/sust/student.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by jerin-priya** [comment]
Dear JetBrains Support Team,

I hope this email finds you well.

I attempted to make a pull request with the following file path:
@jerin-priya file/lib/domains/edu/sust/student.txt

However, I received an error indicating that the file path format is
incorrect:
*"This request has an incorrect file path format, please ensure that you
are familiar with this repository rules located at the bottom of this page
and change your request accordingly. If you don't know how to change
request, close it and open a new one. If you are not able to make the pull
request according to the instructions, please send us an email to
***@***.*** ***@***.***>."*

Unfortunately, I am unable to determine how to fix the file path format
based on the repository instructions. I kindly request your assistance in
resolving this issue.

Could you please guide me on the correct file path format or provide any
additional resources or examples? If needed, I can provide further details
regarding the request or the repository.

Thank you for your support, and I look forward to your guidance.

Best regards,
Jerin Hasan Priya
Edu mail: ***@***.***

**Comment by philipto** [comment]
@jerin-priya Hello!

I corrected the request. Could you please send us a message to community-support@jetbrains.com and help us improving the instructions? You say:
> I attempted to make a pull request with the following file path:
> @jerin-priya file/lib/domains/edu/sust/student.txt
> [...]
> Unfortunately, I am unable to determine how to fix the file path format
based on the repository instructions. I kindly request your assistance in
resolving this issue.

In the [instruction](https://github.com/JetBrains/swot?tab=readme-ov-file#how-to-add-a-domain-to-this-repository) it says:

> Each domain is represented by a single .txt file in the repository. If there is a file lib/domains/edu/mit.txt, it means that an email domain mit.edu is included in the repository. Please note that the repository reverses the order of the name components, and also note that .txt extension is mandatory. Example: add file /lib/domains/ng/edu/unaab.txt to add a domain unaab.edu.ng to the repository.

As you can see `lib/domains/ng/edu/unaab.txt` does not contain a prefix "**file**", and ` file/lib/domains/edu/sust/student.txt` contains it.

Please let us know how can we make it better explained that the file path must start with `lib`, not `file/lib`.

We have to make the instructions as clear as possible, and therefore I appreciate your help very much. Thank you!

**Comment by philipto** [comment]
@jerin-priya I am sorry, the domain student.sust.edu is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
