### PR TITLE
Create sp.txt

### PR DESCRIPTION
**Pull request by williamxsp**
www.sp.senai.br

### CODE REVIEW

**Comment by williamxsp** [comment]
More details about SENAI - São Paulo (a Brazilian educational institution based in São Paulo) 

SENAI (National Service for Industrial Apprenticeship)
http://en.wikipedia.org/wiki/SENAI 

Graduation courses that we offer ( Only in portuguese ) 
http://www.sp.senai.br/senaisp/cursos/24/faculdade?menu=32
http://www.sp.senai.br/senaisp/cursos/117/pos-graduacao?menu=33

I hope it's enough

Thanks!

**Comment by zweizwei** [comment]
Please provide the links to the pages, confirming that the entity provides IT related courses longer than 1 year. Thanks!

**Comment by williamxsp** [comment]
Hello,
Here's one of our courses.
It's an Informatics Technician course.

It have the duration of 1500 hours distributed along 4 semesters.

http://www.sp.senai.br/senaisp/cursos/68515/115/tecnico-de-informatica.html

**Comment by zweizwei** [comment]
Thank you, i'm adding the domain

**Pull request merged**
