### PR TITLE
Add WCH Highschool

### PR DESCRIPTION
**Pull request by Jinthium**
add student.wchcs.org

### CODE REVIEW

**Comment by philipto** [comment]
@Jinthium Please provide us with:
* the school official website URL
* the school street address, including city and country
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Jinthium You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@Jinthium I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by Jinthium** [comment]
URL: https://www.wchcs.org/washingtonhighschool_home.aspx
Address: 400 S Elm St, Washington Court House, OH 43160
Proof: proof_of_email

**Pull request closed without merging**
