### PR TITLE
Add SOAS University

### PR DESCRIPTION
**Pull request by felipe0216**
Here is the link if in doubt https://www.soas.ac.uk/

### CODE REVIEW

**Comment by philipto** [comment]
@felipe0216 Please provide us with:
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

Also, please clarify what is the university educational model? Does it provides a lot of remotely studying students worldwide with email addresses while they are enrolled to the online school?

**Comment by philipto** [comment]
@felipe0216 You might miss my previous comment. Please react.

**Comment by felipe0216** [comment]
School address: 10 Thornhaugh St, London WC1H 0XG

City: London

Country: United Kingdom
URL : https://www.soas.ac.uk/

University model: Traditional university like UCL or Kings college London
where you attend on-site classes.

**Comment by philipto** [comment]
@felipe0216 Thank you for the clarification! I reviewed the list of departments, and did not find any where software development is a major: https://www.soas.ac.uk/about/schools-and-departments

Could you please tell us what for would you like to use JetBrains tools in the university? It's important to ensure that students in the university having the right to get a free license will not abuse it (because they in fact don't need the tools).

**Comment by felipe0216** [comment]
Hello Philip,

I can't talk for the university, but I would like to use it to create an
app for the law school and create projects using LLMs for my department. I
have a second passion for technology, so even though they don't have a
software development program, I am sure that there are people who still
like coding and would like to work on projects in their fields where they
can integrate technology.

Kind regards

**Comment by philipto** [comment]
@felipe0216 Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Comment by philipto** [comment]
@felipe0216 It takes about an hour for the changes to propagate through our systems. Please wait an hour from now before applying for the free license. Thank you!

**Pull request merged**
