### PR TITLE
Add Bolyai János Műszaki Technikum és Kollégium

### PR DESCRIPTION
**Pull request by olajos-marton**

### CODE REVIEW

**Comment by philipto** [comment]
@olajos-marton First stage of verification passed, official domain is [bolyai-bp.edu.hu](https://bolyai-bp.edu.hu) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://bolyai-bp.edu.hu/

**Comment by olajos-marton** [comment]
@philipto Thank you so much for looking into the request. [bolyai-bp.edu.hu](https://bolyai-bp.edu.hu/) is the domain the shool uses for its website, but for emailing, we use the domain bolyai-szakkozep.hu. If we are supposed to receive emails from JetBrains for verification, please kindly approve of domain bolyai-szakkozep.hu. If not, either of them is fine with us.

**Comment by olajos-marton** [comment]
A better code example:
```java
ItemStack item = item lekérése
ItemMeta meta = item.getItemMeta();
if(meta.hasEnchant(CustomEnch1)) {
   // Logic for customenchantment 1
}

if(meta.hasEnchant(CustomEnchant2)) {
   // Different logic for custom ench2
}



VAGY
private final ArrayList<CustomEnchantEnum> enumValues = CustomEnchantEnum.getValues();
// Valami eventen belül:

for(Map.Entry<Enchantment, Integer> ench : meta.getEnchants()) {

   if(enumValues.contains(ench.getName())) {
      CustomEnchantEnum.valueOf(ench.getName()).doTheThing(event, ench.getLevel());
   }
}

///// Ench util osztályban:

enum CustomEnchantEnum {

CustomEnch1 {
   public void doTheThing(Event e, int level) {
      // Logic here
   }
},
CustomEnch2 {
   public void doTheThing(Event e, int level) {
      // Other logic here
   }
};

public abstract void doTheThing(Event e, int level);
// Note that level might not always be used
}
```

**Comment by philipto** [comment]
@olajos-marton Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by olajos-marton** [comment]
@philipto Thank you again for your work and the access to the product set. 😊

**Pull request merged**
