### PR TITLE
Create souunit.txt

### PR DESCRIPTION
**Pull request by froesmatheus**
Institution website: https://www.unit.br/

### CODE REVIEW

**Comment by philipto** [comment]
@froesmatheus Could you please explain the relationships between souunit.com.br domain and unit.br? Do they belong to the same instituion? Where can I read about this? Where can I see that the students have their email in souunit.com.br?

**Comment by froesmatheus** [comment]
@philipto unit.br is for employees of the institution and souunit.com.br is for students. They belong to the same institution. souunit.com.br is a new domain which comes from a partnership with Google Classroom. I don't think there's a official document where you can read about this though. 

sem titulo

Here is a picture of the institution website for students where you can see my email on the top right, hope it helps.

**Comment by philipto** [comment]
@froesmatheus Thank you for the clarification. Pull request merged.

**Comment by froesmatheus** [comment]
@philipto Thanks!

**Pull request merged**
