### PR TITLE
Add tggs-bangkok to org

### PR DESCRIPTION
**Pull request by xbklairith**
Add tggs-bangkok to org

### CODE REVIEW

**Comment by zweizwei** [comment]
the school's website seems to be www.tggs.kmutnb.ac.th - could you please somehow confirm that the provided website also belongs to the school?

**Comment by xbklairith** [comment]
www.tggs.kmutnb.ac.th and tggs-bangkok.org will point to same ip address (202.44.44.231),
but email domain is registered under tggs-bangkok.org

**Comment by zweizwei** [comment]
@xbklairith unfortunately somehow I can't verify this information through  who.is - could you please provide some confirmation of the fact? thank you!

**Comment by xbklairith** [comment]
@zweizwei  Exactly, TGGS is a part of KMUTNB . I have no official exhibit.
However ,@tggs-bangkok.org is used in contact and staft's e-mail if you see it in that website.

**Comment by zweizwei** [comment]
@xbklairith "@tggs-bangkok.org is used in contact and staft's e-mail if you see it in that website." - please provide the page where i can see that. Thank you!

**Comment by xbklairith** [comment]
@zweizwei 
http://202.44.44.231/contact
http://202.44.44.231/supporting-staff/penthip-jirapinnusorn
http://202.44.44.231/administration-staff/assoc-prof-dr-h-c-banleng-sornil
http://202.44.44.231/lecturer-staff/rapeephun-dangtungee,

Thank you.

**Comment by zweizwei** [comment]
@xbklairith sorry for the delay - I was on vacation. I'm adding the domain.

**Pull request merged**
