### PR TITLE
Create Oaklandcc

### PR DESCRIPTION
**Pull request by neilfaigenbaum**
Adding OaklandCC

### CODE REVIEW

**Comment by philipto** [comment]
@neilfaigenbaum Please rename lib/domains/edu/Oaklandcc to lib/domains/edu/oaklandcc.txt
Thank you.

**Comment by neilfaigenbaum** [comment]
When I go into github, I don’t see the one I need to change. It always truncates the list

**Comment by neilfaigenbaum** [comment]
Updated per your request

**Comment by philipto** [comment]
@neilfaigenbaum Pull request is merged. I corrected the name on your behalf.

**Pull request merged**
