### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Daaarkov**
School name: Istituto Superiore Statale G. Maironi da Ponte
School website: https://maironidaponte.edu.it
School adress: Via C. Berizzi, 1, 24030 Presezzo (BG), Italy
School offers with IT-related long-term course: https://maironidaponte.edu.it/index.php/scuola/carta-identita-scuola/indirizzi-di-studio/295-la-scuola/carta-d-identita-della-scuola/istituto-tecnico-articolazioni/699-liceo-scientifico-opzione-scienze-applicate
The proof: the domain of the school is the same as the email one

### CODE REVIEW

**Comment by philipto** [comment]
@Daaarkov Please provide us with:
* the school official full name 
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Daaarkov You might miss my previous comment. Please react.

**Comment by Daaarkov** [comment]
School name: Istituto Superiore Statale G. Maironi da Ponte
School website: https://maironidaponte.edu.it/
School adress: Via C. Berizzi, 1, 24030 Presezzo (BG), Italy
School offers with IT-related long-term course: https://maironidaponte.edu.it/index.php/scuola/carta-identita-scuola/indirizzi-di-studio/295-la-scuola/carta-d-identita-della-scuola/istituto-tecnico-articolazioni/699-liceo-scientifico-opzione-scienze-applicate
The proof: the domain of the school is the same as the email one

**Comment by philipto** [comment]
@Daaarkov First stage of verification passed, official domain is [maironidaponte.edu.it](https://maironidaponte.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Daaarkov Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
