### PR TITLE
Add file lfblbv.txt

### PR DESCRIPTION
**Pull request by ousseyni**

### CODE REVIEW

**Comment by philipto** [comment]
@ousseyni First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/LyceeFrancoBritannique.lbv/?locale=fr_FR

**Comment by philipto** [comment]
@ousseyni Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by ousseyni** [comment]
Hi Philip,

   
   - the school official website URL : http://efblbv.org
Here is the official website, we are working to upgrade and change this current website and deploy the new one on the new domain lfblbv.com. For now, we create a redirection from lfblbv.com to efblbv.org and we use the new domain to create teachers's and students's mail account. 

   
   - the school street address, including city and country : 
The school is in Libreville, Gabon near by El Rapha Clinic

   
   - an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
 Since June 2018, the school has been offering courses in the diploma program including computer science at the baccaleaureat. Unfortunately the current site does not allow to see the complete program of courses but the computer is part of the curriculum of students from primary to high school because these are the standards of the International Baccalaureate program


   
   - a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
If you check on the facebook page, you can have a proof which shows that the school recognizes the domain


---------------------------------------------------------------------------------------------

Cordialement 
Ousseyni TIAMA
 

    Le jeudi 27 juillet 2023 à 06:44:32 UTC−4, Philip Torchinsky ***@***.***> a écrit :  
 
 


@ousseyni Please provide us with:
   
   - the school official website URL
   - the school street address, including city and country
   - an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
   - a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@ousseyni First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/LyceeFrancoBritannique.lbv/?locale=fr_FR

**Comment by philipto** [comment]
@ousseyni You might miss my previous comment. Please react.

**Comment by ousseyni** [comment]
Hi Philip,



  *   the school official website URL : http://efblbv.org<http://efblbv.org/>

Here is the official website, we are working to upgrade and change this current website and deploy the new one on the new domain lfblbv.com<http://lfblbv.com/>. For now, we create a redirection from lfblbv.com<http://lfblbv.com/> to efblbv.org<http://efblbv.org/> and we use the new domain to create teachers's and students's mail account.



  *   the school street address, including city and country :

The school is in Libreville, Gabon near by El Rapha Clinic



  *   an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

Since June 2018, the school has been offering courses in the diploma program including computer science at the baccaleaureat. Unfortunately the current site does not allow to see the complete program of courses but the computer is part of the curriculum of students from primary to high school because these are the standards of the International Baccalaureate program



  *   a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

If you check on the facebook page, you can have a proof which shows that the school recognizes the domain



Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ousseyni** [comment]
Hi Philip,

   
   - the school official website URL : http://efblbv.org
Here is the official website, we are working to upgrade and change this current website and deploy the new one on the new domain lfblbv.com. For now, we create a redirection from lfblbv.com to efblbv.org and we use the new domain to create teachers's and students's mail account. 

   
   - the school street address, including city and country : 
The school is in Libreville, Gabon near by El Rapha Clinic

   
   - an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
Since June 2018, the school has been offering courses in the diploma program including computer science at the baccaleaureat. Unfortunately the current site does not allow to see the complete program of courses but the computer is part of the curriculum of students from primary to high school because these are the standards of the International Baccalaureate program


   
   - a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
If you check on the facebook page, you can have a proof which shows that the school recognizes the domain


 ----------------------------------------------------------------------------------------------
Cordialement 
Ousseyni TIAMA
Developpeur Java | AWS
4940 Avenue Borden, Montréal, H4V 2S8
Tel: +1 (438) 467 4585 

    Le samedi 29 juillet 2023 à 23:35:10 UTC−4, Philip Torchinsky ***@***.***> a écrit :  
 
 


@ousseyni You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@ousseyni  Thank you for the clarifications and your patience while waiting for a review and processing your request. Pull request merged.

**Comment by ousseyni** [comment]
Hi,
Thanks. And now, how can i create my teacher's account please ?

 ----------------------------------------------------------------------------------------------
Cordialement 
Ousseyni TIAMA
Developpeur Java, PHP | AWS
4940 Avenue Borden, Montréal, H4V 2S8
Tel: +1 (438) 467 4585 

    Le lundi 7 août 2023 à 05:58:40 UTC−4, Philip Torchinsky ***@***.***> a écrit :  
 
 


@ousseyni Thank you for the clarifications and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
