### PR TITLE
Nepal Commerce Campus

### PR DESCRIPTION
**Pull request by dhirajbadu**
Nepal Commerce Campus

### CODE REVIEW

**Comment by philipto** [comment]
@dhirajbadu First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/ncccampus/posts/2999559937033255/

**Comment by dhirajbadu** [comment]
> @dhirajbadu First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/ncccampus/posts/2999559937033255/

Hi @philipto any update on this?

**Comment by philipto** [comment]
@dhirajbadu Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@dhirajbadu Thank you for your patience while waiting for a review and processing your request. 

Regrettably, there is not enough verifiable information about the school in the internet. The official website is continuously inaccessible.  Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
