### PR TITLE
Adding Universidad Autónoma de Tamaulipas

### PR DESCRIPTION
**Pull request by AASantiago**
Adding Universidad Autónoma de Tamaulipas
Autonomous University of Tamaulipas

For @alumnos.uat.edu.mx
For @uat.edu.mx

### CODE REVIEW

**Comment by AASantiago** [comment]
Adding Universidad Autónoma de Tamaulipas
Autonomous University of Tamaulipas

For @alumnos.uat.edu.mx
For @uat.edu.mx
For @docentes.uat.edu.mx

**Comment by philipto** [comment]
@AASantiago I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by AASantiago** [comment]
Dear Philip Torchinsky,
I am not sure how did you check a domain's existence.
I am now writing from my institutional e-mail. You can consult our 
webpage www.uat.edu.mx.
Our institutional e-mails end as @uat.edu.mx @alumnos.uat.edu.mx 
@docentes.uat.edu.mx
Kind Regards
A. Santiago
-- 
Email Signature
Logo <https://fiuat.mx> 	*Dr. Alejandro Santiago*
*Catedrático - Full Professor*
*Investigador Nacional Nivel Candidato (SNI C)*
***@***.****
*Universidad Autónoma de Tamaulipas*
*Facultad de Ingeniería "Arturo Narro Siller"*
*Centro Universitario Tampico-Madero, Tampico, Tamaulipas, México.*
*www.alejandrosantiago.xyz <http://www.alejandrosantiago.xyz>*

**Comment by AASantiago** [comment]
Dear Philip Torchinsky,
I am unsure how you checked a domain’s existence (I also sent you an e-mail from my institutional address ***@***.*** ***@***.***>). 
I am now writing from my institutional e-mail. You can consult our webpage www.uat.edu.mx <http://www.uat.edu.mx/>.
Our institutional e-mails end as @uat.edu.mx @alumnos.uat.edu.mx @docentes.uat.edu.mx
Kind Regards
A. Santiago

**Comment by philipto** [comment]
Dear @AASantiago,

Thank you for the details. I reopen the pull request. As I noted in my previous comment, the domain name server seemed to be down at the moment of the check. I ran a command
```
host uat.edu.mx
```
and received the answer 
```
connection timed out; no servers could be reached
```
I'll make deeper domain review today and get back to you as soon as possible. Thank you!

**Pull request closed without merging**
