### PR TITLE
Create amitydubai.txt

### PR DESCRIPTION
**Pull request by Wins010**

### CODE REVIEW

**Comment by philipto** [comment]
@Wins010 The first verification stage is complete: the official domain for  **Amity University Dubai** is [amityuniversity.ae](https://amityuniversity.ae), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://amityuniversity.ae/ICCIKE2023/contact.php

**Comment by Wins010** [comment]
@philipto Sir, May I know how long this is going to take?

**Comment by philipto** [comment]
@Wins010 The first verification stage is complete: the official domain for  **Amity University Dubai** is [amityuniversity.ae](https://amityuniversity.ae), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://amityuniversity.ae/ICCIKE2023/contact.php

**Comment by philipto** [comment]
@Wins010 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
