### PR TITLE
Create ipi.igsgroupe

### PR DESCRIPTION
**Pull request by Pwapou**

### CODE REVIEW

**Comment by philipto** [comment]
@Pwapou Could you please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Pwapou** [comment]
Hi thanks for your anwser 

please juste add the email domain : @ ipi.igsgroupe.com

1.http://www.ipi-ecoles.com/decouvrir-ecole-ipi/ (the groupe : http://www.groupe-igs.fr/ )

2.http://www.ipi-ecoles.com/formation/

3. the screen : https://www.noelshack.com/2017-22-1496399378-screen-shot-2017-06-02-at-12-28-59.png  (in french sorry)

**Comment by philipto** [comment]
@Pwapou Thank you for the clarification. For the domain ipi.igsgroupe.com the file name in the request has to be lib/domains/com/igsgroupe/ipi.txt

Please rename lib/domains/fr/ipi.igsgroupe to lib/domains/com/igsgroupe/ipi.txt and I merge your request as soon as possible. Thank you!

**Comment by Pwapou** [comment]
@philipto  i move this here : https://github.com/JetBrains/swot/pull/3094 

thanks for your support

**Comment by philipto** [comment]
@Pwapou I am closing this request because the new one, #3094, was just satisfied.

**Pull request closed without merging**
