### PR TITLE
Add rb.ac.th

### PR DESCRIPTION
**Pull request by wachirawit-m**

### CODE REVIEW

**Comment by philipto** [comment]
@wachirawit-m First stage of verification passed, official domain is [rb.ac.th](https://rb.ac.th) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@wachirawit-m Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by wachirawit-m** [comment]
- School URL: rb.ac.th/mainpage
- Street address: 3 Sanamchai Road, Grand Palace, Phra Nakhon, Bangkok 10200
- IT course (they only have the list of students that qualified for the course): https://drive.google.com/file/d/1o_aBGnHYSLkVHsG2FEbgPL9RiMExjA_s/view (page 2-4)
- Students email proof (it's a manual for students): https://drive.google.com/file/d/1MLEWhmfdQXyfOqVsvLOcm2ufFqkZk_X7/view

**Comment by philipto** [comment]
@wachirawit-m Thank you for the details! Would you be able to provide also evidence that children who are older than 13 years of age are enrolled in the school?

**Comment by philipto** [comment]
@wachirawit-m  Thank you for the clarifications. Pull request merged.

**Pull request merged**
