### PR TITLE
Adding Southville International School and College

### PR DESCRIPTION
**Pull request by SpectreSpammer**
School:
Southville International School and College

Email:
17-0131c@sgen.edu.ph

Domain:
sgen.edu.ph

### CODE REVIEW

**Comment by philipto** [comment]
@SpectreSpammer First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/siscjpia/posts/2312235572402450/

**Comment by philipto** [comment]
@SpectreSpammer Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@SpectreSpammer First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/SISFUStudentCouncil/

**Comment by philipto** [comment]
@SpectreSpammer Hello Nan.

Thank you for the information. However the pages that you mentioned do not contain any links to or mentions of sgen.edu.ph domain. 

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

If you are unable to provide us with the proof, I will close the request without merging. It is not mandatory to add a domain to the trusted list for receiving a free license. **You can also apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.**

**Comment by SpectreSpammer** [comment]
Here is our Facebook Page
https://www.facebook.com/sisc.monarchs?mibextid=ZbWKwL


and here is the screenshot of the website
[image: image.png]

**Comment by philipto** [comment]
@SpectreSpammer First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/SISFUStudentCouncil/

**Comment by philipto** [comment]
@SpectreSpammer You might miss my previous comment. Please react.

**Comment by SpectreSpammer** [comment]
Hi, whats your comment?

**Comment by philipto** [comment]
@SpectreSpammer Thank you for your patience while waiting for a review and processing your request. Pull request merged.

There was a misunderstanding because GitHub strips out all the images if they were sent as attachment to an email sent to comment.

**Pull request merged**
