### PR TITLE
hello GDGoenka university

### PR DESCRIPTION
**Pull request by ashishmangla0**
add new comments as you asked

### CODE REVIEW

**Comment by philipto** [comment]
@ashishmangla0 Are you sure that the email domain which you wish to add is gdgu.gdgu.org ? Double "gdgu"? Which webpage proves that your school recognizes it as a domain for students?

I am sorry, the comments have NOT to be in the file, the comments are what you reply to the email from GitHub, or what you answer on the webpage of your request in the "Conversation" section.

**Comment by ashishmangla0** [comment]
@philipto  yes. i am sure.  want to mention they have multiple domains like http://gdgoenka.ac.in/ only for emails. and for student/ teacher logins they are using "gdgu.org" only for emails.

https://user-images.githubusercontent.com/24789070/43310556-7f04b99c-91a5-11e8-8192-f18c3b8489bc.png

**Comment by ashishmangla0** [comment]
@philipto it not mentioned such as on any webpage. but I mention a  link on which it says "gdgu.org" owned by "Anjani Kumar Goenka"

**Comment by philipto** [comment]
@ashishmangla0 Thank you. Actually, this page proves that this domain is owned by the university: http://www.gdgoenkauniversity.com/iclass2018/conference-venue/

However, I will have to close this request without merging, because it has wrong filename. Please rename lib/domains/org/gdgu/gdgu.txt to lib/domains/org/gdgu.txt , because the domain is gdgu.org, not gdgu.gdgu.org. There is extra gdgu directory in the filename now, it is not necessary. Thank you.

**Comment by ashishmangla0** [comment]
@philipto thanks for confirming this.

**Comment by philipto** [comment]
@ashishmangla0 Pull request merged. Thank you!

**Pull request merged**
