### PR TITLE
Add Macau Polytechnic University

### PR DESCRIPTION
**Pull request by nenniuwufang**
Add Macau Polytechnic University into repo, please review.

### CODE REVIEW

**Comment by philipto** [comment]
@nenniuwufang First stage of verification passed, official domain is [mpu.edu.mo](https://mpu.edu.mo) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by nenniuwufang** [comment]
@philipto So glad to hear that, if anything need, plz let me know!

**Comment by philipto** [comment]
@nenniuwufang Pull request merged. Thank you.

**Comment by nenniuwufang** [comment]
@philipto Thanks so much, I'm so thrilled to hear that!

**Pull request merged**
