### PR TITLE
Add Research Institute for Linguistics of the Hungarian Academy of Sc…

### PR DESCRIPTION
**Pull request by m-ivan**
…iences (URL: [www.nytud.mta.hu/eng/](www.nytud.mta.hu/eng/))

### CODE REVIEW

**Comment by philipto** [comment]
@m-ivan I am afraid that we are unable to add the institute to this repository because it is primarily a research institution, not educational one. Please correct me if I am wrong. 

If you have a significant number of students studying in the institute, please let us know. The students are eligible for the free licenses, however if there are just few of them (say, 20-50), it will be better to ask their teacher to apply for a free classroom license for them by email to classroom@jetbrains.com. Thank you.

**Comment by m-ivan** [comment]
The Research Institute for Linguistics runs the [Theoretical Linguistics Programme](http://www.nytud.mta.hu/tlp/index.html) with MA and PhD studies. The curriculum contains courses on python and human language technology as well (e.g. http://bobac.nytud.hu/courses/python2015/index.html).

**Comment by philipto** [comment]
@m-ivan Thank you for the clarification! Pull request merged.

**Comment by m-ivan** [comment]
@philipto Thank You!

**Pull request merged**
