### PR TITLE
Add Ruđer Bošković Institute domain: irb.hr

### PR DESCRIPTION
**Pull request by alenkovich**
Owing to the large number of potential mentors and qualified researchers, as well as the relatively modern research equipment, the RBI remains an attractive place for the best students from Croatian universities to pursue doctorates, which continue to provide an influx of qualified doctoral candidates.

The RBI has developed collaborations with individual universities in Croatia through a number of doctoral and specialist study programs.  In addition, through basic agreements with various universities in Croatia, the RBI actively participates in teaching at the undergraduate level. By far the strongest collaboration is with the University of Zagreb, with which a formal agreement of collaboration was signed in 2007. The majority of RBI involvement with the University is through teaching at the Faculty of Natural Sciences and Mathematics, followed by the Faculty of Electrical Engineering and Computing (FER), the Faculty of Agronomy and the Faculty of Medicine.

### CODE REVIEW

**Comment by alenkovich** [comment]
Hi! Thanks.. our website is in Croatian by default. Education activities described in English are here: https://www.irb.hr/eng/Education/RBI-Activities

**Comment by philipto** [comment]
@alenkovich Do you teach any students in the Institute? The website suggests that the Institute is purely research organization with no students at all.

**Comment by philipto** [comment]
@alenkovich You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@alenkovich I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by alenkovich** [comment]
Hi!

@philipto .. sorry for the late reply, I missed your comment.

Yes, we do have lectures at the institute (2 lecture halls, 1 computer lab) and our staff is involved in courses and they teach students here. I will post some photos from today's lectures later.

Best,
Alen

> @alenkovich Do you teach any students in the Institute? The website suggests that the Institute is purely research organization with no students at all.

**Pull request closed without merging**
