### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SebbyMortimer**

### CODE REVIEW

**Comment by philipto** [comment]
@SebbyMortimer The first verification stage is complete: the official domain for  **Strathaven Academy** is [strathaven.s-lanark.sch.uk](https://strathaven.s-lanark.sch.uk), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: http://strathaven.s-lanark.sch.uk/wp-content/uploads/2022/01/S3-into-S4-Choices-Information_-Parent_Carer-Presentation_-Jan-2022.pptx.pdf

**Comment by philipto** [comment]
@SebbyMortimer Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by alexanderhiggins** [comment]
hey there @philipto, this pull request is incorrect. glow.sch.uk is not used for Strathaven Academy. it is used for **all eligible learners in Scotland, including all staff directly related to Scottish education - all local authorities, independent schools, teacher education colleges and universities and Scottish education partners. [this includes universities](https://glowconnect.org.uk/docs/rm-unify/accounts-and-passwords/), as seen [here](https://glowconnect.org.uk/wp-content/uploads/2020/07/List-of-organisations-using-Glow-updated-July-2020.pdf).**

this means that the uk/sch/glow.txt file should contain .group, as it contains many organisations.
<details>
<summary>Non-exhaustive list of organisations</summary>
<br>

• Edinburgh Napier University
• Royal Conservatoire of Scotland
• University of Aberdeen
• University of Dundee
• University of Edinburgh
• University of Glasgow
• University of Highlands and Islands
• University of Stirling
• University of Strathclyde
• University of West of Scotland
• Ayrshire College
• Borders College
• City of Glasgow College
• Dumfries and Galloway College
• Dundee and Angus College
• Edinburgh College
• Fife College
• Forth Valley College
• Glasgow Clyde College
• Glasgow Kelvin College
• Inverness College UHI
• Lews Castle College UHI
• Moray College UHI
• New College Lanarkshire
• North East College
• Sabhal Mor Ostaig UHI
• West College Scotland
• West Highland College UHI
• West Lothian College
• Corseford School
• Craihalbert Centre
• Donaldson’s School
• Harmeny School
• Royal Blind School
• Jordanhill School
• Albyn School
• Ardfern Learning Centre
• Aspire Education
• Bachlaw Learning Centre
• Balnacraig School
• Basil Paterson School
• Belhaven Hill School
• Belmont House School
• Cedars School of Excellence
• Clifton Hall School
• Closeburn House School
• Common Thread Group
• Craigclowan Preparatory School
• Craigholme School
• Crossreach Erskine Waterfront Campus
• Daldorch House School, Catrine
• Dollar Academy
• Dunedin School
• Eden Park Academy Ayrshire
• Eden Park Academy Dunfermline
• Edinburgh Montessori Arts School
• Erskine Stewart's Melville Schools
• Fairview International School
• Falkland House School
• Focus School - Millden Campus
• Focus School - Ochil Campus
• George Heriot's School
• George Watson's College
• Glasgow Academy
• Good Shepherd Centre
• Greenleaf School
• Hamilton College
• High School of Dundee
• Hillside School, Aberdour
• Hutchesons' Grammar
• Kelvinside Academy
• Kibble Education and Care Centre
• Kilgraston School
• Lathallan School
• Lewis Independent Christian School
• Lomond School
• Loretto School
• Maben House School
• Mirren Park School (formerly MPS Training)
• Moore House School
• Morrison's Academy
• New Struan School
• Northview House School
• Ochil Tower School
• Queen Victoria School
• Robert Gordon's College
• Rossie Secure Accommodation Services
• Seamab School
• Spark of Genius Learning Centre – Caledonian School
• Spark of Genius Learning Centre – Skypoint School
• Spark of Genius Learning Centre - Harbour Point
• St Aloysius College
• St Columba's School
• St George's School for Girls
• St Leonards School
• St Margaret's School for Girls
• St Mary's Music School
• St Mary's, Kenmure
• St Mary's, Melrose
• St Philip's Open School
• Starley Hall School
• Strathallan School
• The Edinburgh Academy
• The High School of Glasgow
• Wellington School

and all schools within the following Scottish regions:

• Aberdeen City
• Aberdeenshire
• Angus
• Argyll and Bute
• Clackmannanshire
• City of Edinburgh
• Dumfries and Galloway
• Dundee City
• East Ayrshire
• East Dunbartonshire
• East Lothian
• East Renfrewshire
• Falkirk
• Fife
• Glasgow City
• Highland
• Inverclyde
• Midlothian
• Moray
• North Ayrshire
• North Lanarkshire
• Orkney Islands
• Perth and Kinross
• Renfrewshire
• Scottish Borders
• Shetland Islands
• South Ayrshire
• South Lanarkshire
• Stirling
• West Dunbartonshire
• West Lothian
• Western Isles
</details>

more information about glow can be found [on their official website](https://glowconnect.org.uk/about-glow/). they are a part of the Scottish Government as a subsidiary of Education Scotland.

(in addition, re.glow.scot is another domain that, for all intents and purposes, is an alias of @glow.sch.uk)

**Comment by SebbyMortimer** [comment]
Sorry, @alexanderhiggins is correct. I didn’t realise what I had to do if multiple schools had the same email address.

**Pull request merged**
