### PR TITLE
Added "National Institute of Technology Karnataka"

### PR DESCRIPTION
**Pull request by pnpninja**
Added to the list is - National Institute of Technology Karnataka.

Official website address - http://nitk.ac.in
Mail server - http://nitk.edu.in

[This JSON from WHOIS API](https://www.whoisxmlapi.com/whoisserver/WhoisService?domainName=nitk.edu.in&outputFormat=json) from WHOIS shows proof that http://nitk.edu.in is indeed owned by our college.

http://www.nitk.ac.in/webmail proves on our college site that the domain is indeed owned by our college AND is used by the students

Please note that our college is commonly abbreviated as NITK

### CODE REVIEW

**Comment by pnpninja** [comment]
Hey!

Our college has 2 addresses -  [this address](http://nitk.ac.in) is the website , while [this address](http://nitk.edu.in) is our mail server (or not - I actually login through Gmail to access this)

[This JSON](https://www.whoisxmlapi.com/whoisserver/WhoisService?domainName=nitk.edu.in&outputFormat=json) from WHOIS shows proof that nick.edu.in is indeed owned by our college.

Please note that our college is commonly abbreviated as NITK

In case of any doubts, please feel free to comment here or email them to prateeknar@gmail.com

**Comment by philipto** [comment]
@pnpninja Thank you for the detailed comment! Unfortunately, the web and mail servers are not available at the moment because of DNS timeout, I'll check them in a day or two again to ensure that there are no typos in the request. Thank you!

**Comment by pnpninja** [comment]
Just checking - our colleges' web and mail servers are down? Or is it yours?

**Comment by philipto** [comment]
Yes, DNS gives a timeout error instead of an IP address of your server. This is a problem of your college DNS provider or somewhere in between.

**Comment by pnpninja** [comment]
@philipto : Oh.. I had no problem getting the IP address.. Lets give it a day or 2.

**Comment by pnpninja** [comment]
@philipto : It's been 2 days.. Any updates about the DNS checking?

**Comment by philipto** [comment]
@pnpninja Thank you for your patience. Pull request merged.

**Comment by pnpninja** [comment]
@philipto : thank you.. Quite a few ppl in our college were impressed with your IDEs . Its really helpful for rapid development and breakpointing for people not comfortable with vim + terminal

**Pull request merged**
