### PR TITLE
National College of Informatics "Tudor Vianu", Bucharest, Romania

### PR DESCRIPTION
**Pull request by wowvain-dev**
National College of Informatics "Tudor Vianu", Bucharest, Romania http://portal.lbi.ro/

### CODE REVIEW

**Comment by philipto** [comment]
@wowvain-dev Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by wowvain-dev** [comment]
What kind of proof would be needed? A screenshot of multiple students having that email domain name will do?

**Comment by wowvain-dev** [comment]
image
image
image

**Comment by philipto** [comment]
@wowvain-dev Thank you for the clarification. Pull request merged.

**Pull request merged**
