### PR TITLE
Add IESTP María Rosario Araoz Pinto

### PR DESCRIPTION
**Pull request by juancitopacheco**
Add IESTP María Rosario Araoz Pinto

Official website URL:
https://www.gob.pe/iestpmrap

IT related course:
https://www.gob.pe/institucion/iestpmrap/informes-publicaciones/3365275-desarrollo-de-sistemas-de-informacion

Post where we recognize the new domain for our students:
https://www.facebook.com/photo/?fbid=512355554231926&set=a.450093307124818

### CODE REVIEW

**Comment by philipto** [comment]
@juancitopacheco Please provide more info about the school:

1. What kind of the school is it? Is it a vocational school?
2. Who else uses the domain drelm.edu.pe?
3. Where the school's websites are hosted and why, if not in Peru?
4. How many students the school has now?

Given that:
1. The school uses an email domain different than a website
2. The school uses government digital platform shared among many schools instead of having a dedicated domain for the school
3. The school communicates official information via facebook page instead of the own website,

I'd suggest the students applying for free educational license with an official document which proves that they are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Otherwise I expect that verification of the school may take a long time.

Thank you for your  understanding!

**Comment by juancitopacheco** [comment]
Please provide more info about the school:
_Sure, no problem_

1. What kind of school is it? Is it a vocational school?
It is a public school. A state institute that offers _3-year technical careers_ so that people can work.

2. Who else uses the domain drelm.edu.pe?
It belongs to the Regional Direction of Education of Metropolitan Lima, an organ of the Ministry of Education, but I do not know how many other institutions share this domain. I know that there is currently an active virtual campus (https://aulavirtual.drelm.gob.pe/). That is why, as a student, I would only be interested in registering my institute's email domain @iestpmrap.drelm.edu.pe

3. Where are the school websites hosted and why, if not in Peru?
In fact, the website has recently been migrated to the country's official website (https://www.gob.pe/iestpmrap). I must mention that https://gob.pe is the official website of the Peruvian government.

4. How many students does the school have now?
Currently we are approximately 1600 students.

Notes:

1. The school uses a different email domain than a website.
(A decision of our "ingenious" government)

2. The school uses a government digital platform shared among many schools instead of having a dedicated domain for the school.
(Another decision of our "ingenious" government)

3. The school communicates official information through the Facebook page instead of the website itself.
(It's 2022, what can I say? :) students pay more attention to their social networks than to a page "designed to easily find" information. Something related to the "transparency in public information" law.)

I suggest that students apply for a free educational license with an official document proving they are a student. You can do this using the "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.
(Doing it by this way would enable the domain for the entire institution? or just for individual students?)

I appreciate the support you can give me for the registration of our school.

Thank you!

**Comment by philipto** [comment]
@juancitopacheco Thank you very much for your detailed and kind explanation. It's very important for us because we have many requests from Peru. Regrettably, some of them appear to be illegitimate, and thus I have to make the detailed checks.

Your pull request merged. The students who have the email addresses ending with `@iestpmrap.drelm.edu.pe` can request their free licenses at https://www.jetbrains.com/shop/eform/students.

Applying using the "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students works for an individual student only, not for the entire school. Therefore, applying with `@iestpmrap.drelm.edu.pe` will be easier for the students of your school.

Thank you!

**Comment by juancitopacheco** [comment]
Thank you very much. I am sure that making use of your tools will greatly support us in our professional training, and perhaps also in the future in our workplace. On behalf of my institute, my classmates, and I, we greatly appreciate your invaluable support.

My best wishes.

**Pull request merged**
