### PR TITLE
Created shs

### PR DESCRIPTION
**Pull request by ItsEternity**
http://www.southborough.kingston.sch.uk/

### CODE REVIEW

**Comment by philipto** [comment]
@ItsEternity Thank you for the request. There are two issues with it:
1) file must end with ".txt" in this repository, please rename it to `lib/domains/net/lgflmail/shs.txt`.
2) lgflmail.net domain is registered for London Grid for Learning Trust, not this particular school, and the school website says that contact email of the school is in another domain, southborough.kingston.sch.uk (see http://www.southborough.kingston.sch.uk/index.php/Visitors/contact-us.html). Could you please provide us with any proof (a link to the official website is enough) to ensure that shs.lgflmail.net is an official email domain for the school students?
Thank you!

**Comment by ItsEternity** [comment]
1) I've edited the title
2) The "southborough.kingston.sch.uk" is only given to teachers. Students are given "@lgflmai.net" emails instead (http://www.lgfl.net/Pages/default.aspx). To prove it: Go to this link http://www.southborough.kingston.sch.uk/index.php/portal-login.html. Once you're there go to "Student Email Login" (the last circle) and then it will show at the top "London Grid For Learning"(LGFL). Hope that is enough proof.

**Comment by philipto** [comment]
@ItsEternity Thank you for the clarification! Pull request is now merged.

**Comment by ItsEternity** [comment]
@philipto It doesn't seem to work? http://prntscr.com/bdku33

**Comment by philipto** [comment]
@ItsEternity It's correct. Your email is in @lgflmail.net, not in @shs.lgfmail.net. Do I understand right that all students in London can be potentially given an email in @lgflmail.net? We encourage students to limit their requests to their schools, not to broader communities, which they may belong to along with a lot of other people who they have no idea about. Can you use your @shs.lgfmail.net email?

**Comment by ItsEternity** [comment]
LGFL isn't an official organisation in London, it is more of a service that a few school in my borough use. Unfortunately, the email is @lgflmail.net and not @shs.lgflmail.net. It is not a large community, only with a few schools. Can the education service still be redeemed here? Alternatively, can I sent in a request using the "Official Document" proving that my school uses the @lgflmail.net service? @philipto

**Comment by philipto** [comment]
@ItsEternity Thank you for the clarification. In fact, the proof which you already provided us with is enough. The problem is to define a scope: how many schools use the same email domain, and can we include the schools into the domain description in this repository, the file `lib/domains/net/lgflmail.txt`.

Anyway, in order to include the domain in the repository, you shall add the file `lib/domains/net/lgflmail.txt` to it.

**Pull request merged**
