### PR TITLE
Create aedu.txt (Anhanguera University Domain)

### PR DESCRIPTION
**Pull request by lucasbittencurt**
Anhanguera

### CODE REVIEW

**Comment by zweizwei** [comment]
the university domain seems to be www.anhanguera.com - please confirm that committed domain also belongs to university. thanks!

**Comment by lucasbittencurt** [comment]
Hi, yes the university domain is www.anhanguera.com, but e-mails are "aedu.com" like mine: lucas.filipebittencurt@aedu.com. Thanks!

**Comment by zweizwei** [comment]
Thanks, but, could you provide the link to the page / document where this domain is mentioned as university email domain?

**Comment by jonnatha** [comment]
I've been trying to find a page mentioning the email but only had access in the restricted area =/

PS: I'm a student too.

**Comment by lucasbittencurt** [comment]
Hi, that is a document from the university, is a tutorial for students, how to use the e-mail.
Below in the document they mentioned “aedu”.

PS: Document in Portuguese.

Link: http://posgraduacao.aeduvirtual.com.br/2011/guiaaluno/tutoriais/aedu/tutorial_conta_aedu.pdf

**Comment by zweizwei** [comment]
thank you, i'm adding the domain

**Comment by lucasbittencurt** [comment]
Hello Elena, i tried to apply my e-mail, but the system continue to ask that my e-mail don’t belong to a university domain.

My e-mail is: lucas.filipebittencurt@aedu.com



 

De: Elena Ganenkova [mailto:notifications@github.com] 
Enviada em: sexta-feira, 22 de maio de 2015 10:52
Para: JetBrains/swot
Cc: Lucas F. Bittencurt
Assunto: Re: [swot] Create aedu.txt (Anhanguera University Domain) (#961)

 

Merged #961 <https://github.com/JetBrains/swot/pull/961> .

**Comment by jonnatha** [comment]
So, this pull request is on a wrong path:

Actual: lib/domains/**br**/aedu.txt
Please, fix to: lib/domains/**com**/aedu.txt

Or we have to create a new pull request?

**Comment by lucasbittencurt** [comment]
Hi, i created now on ../com directory, this is my commit a7bd794e6a745a6c229f033e41fbf22b69ab824e
Thanks for your time.



 

De: Jonnatha Santos [mailto:notifications@github.com] 
Enviada em: sábado, 23 de maio de 2015 23:53
Para: JetBrains/swot
Cc: Lucas F. Bittencurt
Assunto: Re: [swot] Create aedu.txt (Anhanguera University Domain) (#961)

 

So, this pull request is on a wrong path:

Actual: lib/domains/br/aedu.txt
Please, fix to: lib/domains/com/aedu.txt

Or we have to create a new pull request?

**Comment by zweizwei** [comment]
@lucasbittencurt thanks for adding the domain - who.is says the registrant is university so i'll add it now. Should i delete aedu.br then?

**Comment by lucasbittencurt** [comment]
Hi Elena, yes of course.
Thank you for your attention.

**Pull request merged**
