### PR TITLE
aiu.txt

### PR DESCRIPTION
**Pull request by walataza**
American International University, West Africa, The Gambia

@philipto , file name updated and the url is www.aiu.edu.gm

regards

### CODE REVIEW

**Comment by philipto** [comment]
@walataza 
```
$ host -t mx aiuwa.gm
Host aiuwa.gm not found: 3(NXDOMAIN)
```
If you wish to add aiu.edu.gm domain to the list, please rename the file to lib/domains/gm/edu/aiu.txt
Thank you!

**Comment by philipto** [comment]
@walataza Excuse me, it looks like you misunderstand me. The file path in the request has to be changed, not the title of the request. Please change the file name according to this repository rules (located at the bottom of [this page](https://github.com/JetBrains/swot))

**Comment by walataza** [comment]
@philipto , i have created it to this directory 
https://github.com/JetBrains/swot/tree/master/lib/domains/gm
Please confirm
regards

**Comment by philipto** [comment]
@walataza Could you please tell me what is your email domain? Is it aiuwa.gm?

**Comment by walataza** [comment]
@philipto . Its aiu.edu.gm  .. thank you

**Comment by philipto** [comment]
@walataza I made the request #2999 for you. If you wish to look at how it had to be made, you can take a look. I am closing this request because it looks like you are not very familiar with GitHub (or this repository rules) and it's really difficult for you to add a file with a path which represents your email domain. Please email support@jetbrains.com if you have any problem with getting free licenses now. You need to wait 15-20 minutes from now before requesting your free licenses. Thank you.

**Pull request closed without merging**
