### PR TITLE
Brunts has migrated trusts

### PR DESCRIPTION
**Pull request by halal-beef**
no longer apart of the evolve trust but now the greenwood academy trust

### CODE REVIEW

**Comment by halal-beef** [comment]
By the way please note we are in the midst of a huge it migration, new computers, all that stuff 

AFAIK the website is being completely redone

**Comment by philipto** [comment]
@halal-beef First stage of verification passed, official domain is [bruntsacademy.org](https://bruntsacademy.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@halal-beef Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by halal-beef** [comment]
Thank you

**Pull request merged**
