### PR TITLE
2841842190 patch 1

### PR DESCRIPTION
**Pull request by 2841842190**

### CODE REVIEW

**Comment by philipto** [comment]
@2841842190 I am sorry, the domain hainanu.edu.cn is removed from our trusted domains list because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Comment by 2841842190** [comment]
Dear domain name management expert,
Hello. Thank you for your prompt reply. The old email domain hainanu.adu.cn of Hainan University has been discontinued, and the new email domain hainanu.adu.cn is now enabled. Only faculty, staff, and students of our school can register for email now. The school email registration regulations are consistent with the requirements and objectives of your website. So, now we need to update the school email domain name to hainanu. edu.cn. If there is any further news, please contact me promptly. Thank you. The attached document is a proof of the deactivation of the old domain name.https://its.hainanu.edu.cn/info/1060/1844.htm

**Comment by 2841842190** [comment]
Dear domain name management expert,
Hello. Thank you for your prompt reply. The old email domain hainanu.adu.cn of Hainan University has been discontinued, and the new email domain hainanu.adu.cn is now enabled. Only faculty, staff, and students of our school can register for email now. The school email registration regulations are consistent with the requirements and objectives of your website. So, now we need to update the school email domain name to hainanu. edu.cn. If there is any further news, please contact me promptly. Thank you. The attached document is a proof of the deactivation of the old domain name.https://its.hainanu.edu.cn/info/1060/1844.htm

**Comment by 2841842190** [comment]
> @2841842190 I am sorry, the domain hainanu.edu.cn is removed from our trusted domains list because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

Dear domain name management expert,
Hello. Thank you for your prompt reply. The old email domain hainanu.adu.cn of Hainan University has been discontinued, and the new email domain hainanu.adu.cn is now enabled. Only faculty, staff, and students of our school can register for email now. The school email registration regulations are consistent with the requirements and objectives of your website. So, now we need to update the school email domain name to hainanu. edu.cn. If there is any further news, please contact me promptly. Thank you. The attached document is a proof of the deactivation of the old domain name.https://its.hainanu.edu.cn/info/1060/1844.htm

**Comment by 2841842190** [comment]
> @2841842190 I am sorry, the domain hainanu.edu.cn is removed from our trusted domains list because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

Dear domain name management expert,
Hello. Thank you for your prompt reply. The old email domain hainu.edu.cn of Hainan University has been discontinued, and the new email domain hainanu.edu.cn is now enabled. Only faculty, staff, and students of our school can register for email now. The school email registration regulations are consistent with the requirements and objectives of your website. So, now we need to update the school email domain name to hainanu. edu.cn. If there is any further news, please contact me promptly. Thank you. The attached document is a proof of the deactivation of the old domain name.https://its.hainanu.edu.cn/info/1060/1844.htm

**Pull request closed without merging**
