### PR TITLE
Create atec

### PR DESCRIPTION
**Pull request by mrhenry549**

### CODE REVIEW

**Comment by philipto** [comment]
@mrhenry549 Could you please give us an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the Academy? Also please notice that the file path shall end with .txt extension, `lib/domains/pt/atec.txt`, not just `lib/domains/pt/atec`. Thank you!

**Comment by mrhenry549** [comment]
OK. here's the link: https://www.atec.pt/cursos-formacao-profissional/tecnico-especialista-em-gestao-de-redes-e-sistemas-informaticos.html?l=1

**Comment by philipto** [comment]
@mrhenry549 Thank you! Please rename `lib/domains/pt/atec` to `lib/domains/pt/atec.txt`.

**Comment by mrhenry549** [comment]
It's done @philipto.

**Comment by philipto** [comment]
@mrhenry549 Pull request merged. Thank you!

**Pull request merged**
