### PR TITLE
punjab university new institute added

### PR DESCRIPTION
**Pull request by mehaknasir**
http://pu.edu.pk/home/department/1/Institute-of-Administrative-Sciences

The students here are offered some elective programming courses and may use your help in gaining free license access from jetbrains

### CODE REVIEW

**Comment by philipto** [comment]
@mehaknasir First stage of verification passed, official domain is [pu.edu.pk](https://pu.edu.pk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: http://pu.edu.pk/images/cv/16100765142350.pdf

**Comment by philipto** [comment]
@mehaknasir Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
Dear @mehaknasir! Is there any update on the matter?

**Comment by philipto** [comment]
@mehaknasir You might miss my previous comment. Please react.

**Comment by mehaknasir** [comment]
Hi @philipto, i provided wrong department extension the correct one was ibit. i will close this one for now add new PR when if that is not already in the list.

**Pull request closed without merging**
