### PR TITLE
Create dut.txt

### PR DESCRIPTION
**Pull request by duyle112**

### CODE REVIEW

**Comment by philipto** [comment]
@duyle112 Could you please give us the university official website URL? http://www.dut.edu.vn/ does not look as a university official website at the moment...

**Comment by duyle112** [comment]
Sorry for the mistakes.This is official website http://daotao.dut.udn.vn/
.Can you approve this email for student license?Because i lost my domain
email in my university
Thank you.

On Mon, Aug 21, 2017 at 4:16 PM, Philip Torchinsky <notifications@github.com

**Comment by philipto** [comment]
@duyle112 Thank you for the clarification. I am sorry, I did not understand what happens to your email in your university.  Do you study at Da Nang University of Technology and Science? If not, how it helps you if I add this university domain to this repository?

**Comment by duyle112** [comment]
Yes. I study at Da Nang University of Technology and Science.

**Comment by duyle112** [comment]
You can add this university domain this repository, but it doens't work for me because my university domain was lost.I'd like you to approve this email duyle.bks2014@gmail.com.Thank you

**Comment by philipto** [comment]
@duyle112 Thank you for the clarification. I will check the domain details, and satisfy your request, if everything is correct. If you wish to apply for a free license as a student, but you don't have an access to your university email address, please apply with your university photo ID (a card with your photo which confirms that you are a student of the unviersity). You can do it at "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students
Thank you!

**Comment by duyle112** [comment]
Thank you very much.My student license was activated.
On Aug 21, 2017 5:00 PM, "Philip Torchinsky" <notifications@github.com>
wrote:
>
> @duyle112 Thank you for the clarification. I will check the domain
details, and satisfy your request, if everything is correct. If you wish to
apply for a free license as a student, but you don't have an access to your
university email address, please apply with your university photo ID (a
card with your photo which confirms that you are a student of the
unviersity). You can do it at "OFFICIAL DOCUMENT" tab at
https://www.jetbrains.com/shop/eform/students

**Comment by philipto** [comment]
@duyle112 Pull request merged. Thank you!

**Pull request merged**
