### PR TITLE
request to add Maricopa Community College

### PR DESCRIPTION
**Pull request by FreddyKilo**

### CODE REVIEW

**Comment by philipto** [comment]
@FreddyKilo regrettably, this request cannot be satisfied. Please see #2393 for the details.

**Comment by FreddyKilo** [comment]
No worries, was wanting to try DataGrip, guess I'll have to wait until I transfer to ASU, see you in many months 😄

**Comment by philipto** [comment]
@FreddyKilo If you wish to try it, you can use 30-days free trial version. You can also consider applying with ISIC card or another document which proves that you are a student. There are several options available at jetbrains.com/student. Please let me know if I can help more. Thank you!

**Comment by FreddyKilo** [comment]
Thanks for offering the options :)

**Pull request closed without merging**
