### PR TITLE
Create cbpf.txt

### PR DESCRIPTION
**Pull request by tuliosciotta**
Centro Brasileiro de Pesquisas Físicas
https://portal.cbpf.br/pt-br/

### CODE REVIEW

**Comment by philipto** [comment]
@tuliosciotta Could you please clarify how many sudents study at CBPF? Thank you!

**Comment by philipto** [comment]
@tuliosciotta You might miss my previous comment. Please react.

**Comment by tuliosciotta** [comment]
Sorry, i was not notified about the message! Currently, I believe there are about 500 students in the institution. Thanks!

**Comment by philipto** [comment]
@tuliosciotta Pull request merged. 
Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of this Institute who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.
Thank you!

**Pull request merged**
