### PR TITLE
add college cqepc

### PR DESCRIPTION
**Pull request by Bellatriix**
The official URL of our college is: http://www.cqepc.cn/

The URL of one IT course of my college  is: http://www.cqepc.cn:8887/moodle/course/view.php?id=5

The interactions with our enrolled students in this course are shown in the website : http://www.cqepc.cn:8887/moodle/mod/forum/view.php?id=948

### CODE REVIEW

**Comment by philipto** [comment]
@Bellatriix Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@Bellatriix You might miss my previous comment. Please react.

**Comment by Bellatriix** [comment]
> @Bellatriix You might miss my previous comment. Please react.
Thanks for your reply.  I am so sorry for the delay but it is complicated for our university to handle with the relevant certificate, for which needs to be approved by the president of our university.  Would you mind giving me some time to handle this process?  I will reply to you in the end whether it is successful or not.  Thanks for your consideration!

**Comment by philipto** [comment]
@Bellatriix Yes, certainly. Take your time.

You can also apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

**Comment by philipto** [comment]
@Bellatriix I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
