### PR TITLE
New Domain for  multi media BBS

### PR DESCRIPTION
**Pull request by MarcoHuehne**
Changed from eduplaza to mm-bbs
official website URL: http://www.mmbbs.de/
Link to an IT-related course: http://www.mmbbs.de/zertifikate/java-oracle/

### CODE REVIEW

**Comment by philipto** [comment]
@MarcoHuehne I am sorry, the course which you are referring to usually takes few days, not a year of education: https://education.oracle.com/pls/web_prod-plq-dad/db_pages.getpage?page_id=609&get_params=dc:D67234,clang:EN

If you actually do not offer courses on Java which are one year long or longer, you may wish to use 30-days trial versions of JetBrains tools. Please comment if I am mistaken.

**Comment by MarcoHuehne** [comment]
@philipto Actually that's not the only course we are offering. It was just an example. The multi media BBS is a vocational college for IT specialist as you can see here: http://www.mmbbs.de/bildung/berufsschulen/it/fachinformatikerin/

**Comment by jtuttas** [comment]
We are a vocational school for IT Experts in Hannover, Germany (www.mmbbs.de). We have still a registration for JetBrains Products (under the eduplaza domain), unfortunately our new students in the year 2017 didn't have any more an eduplaza domain email account. All Students at the mmbbs in hannover has an email with @mm-bbs.de account ! So please include the mm-bbs.de domain in your program, so the our students can benefits from your student program and I (as a teacher) can include the jetbrains products into my lessons.

best regards

Dr. Joerg Tuttas
Teamleader for Fachinformatiker f. Anwendungsentwicklung

**Comment by philipto** [comment]
@jtuttas Thank you for the details and the update! Pull request merged.

**Pull request merged**
