### PR TITLE
add stipram

### PR DESCRIPTION
**Pull request by raymundusrendra**

### CODE REVIEW

**Comment by philipto** [comment]
@raymundusrendra First stage of verification passed, official domain is [stipram.ac.id](https://stipram.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@raymundusrendra Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by raymundusrendra** [comment]
https://stipram.ac.id/mahasiswa-23-pkm.html

**Comment by philipto** [comment]
@raymundusrendra I am sorry, this domain seems to represent an tourist industry school, not a specific technical university or a college. The page you have provided us with has no information about long-term (> 1 year of study) course related to software development.

If you individually study an IT-related course in the school, please apply for free educational license with an official document, which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.
Thank you for your understanding!

**Pull request closed without merging**
