### PR TITLE
Create yic.txt

### PR DESCRIPTION
**Pull request by xuerongli**
Please add my school, thank you very much.

### CODE REVIEW

**Comment by xuerongli** [comment]
Please add my school, thank you very much.

**Comment by philipto** [comment]
@xuerongli I am sorry, an official domain of this Institute is yic.cas.cn. What is an email address pattern for the students who study in this Institute? Is it username@yic.cas.cn? Thank you.

**Comment by philipto** [comment]
@xuerongli You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@xuerongli I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
