### PR TITLE
Create stmik-indonesia-banjarmasin.txt

### PR DESCRIPTION
**Pull request by najcardboyz**
add domain stmik-indonesia-banjarmasin.ac.id

### CODE REVIEW

**Comment by philipto** [comment]
@najcardboyz Please tell us more about your organization. It does not look like a university nor a college.

**Comment by najcardboyz** [comment]
hi philipto, this domain is used by STMIK Indonesia Banjarmasin, and is officially registered on the site https://forlap.ristekdikti.go.id/perguruantinggi which handles all private universities in indonesia, and STMIK Indonesia Banjarmasin can be seen on following page https://forlap.ristekdikti.go.id/perguruantinggi/detail/REY3MUQwMDMtMUE3MC00NEM0LTlDOUEtRjVFOUU4MjZGMzlG

**Comment by philipto** [comment]
@najcardboyz Thank you for the additional information. Pull request merged. Thank you!

**Comment by najcardboyz** [comment]
@philipto, thanks for that :+1:  :D

**Pull request merged**
