### PR TITLE
Add cantho.edu.vn

### PR DESCRIPTION
**Pull request by thanhutnguyen**
**Sở GD&ĐT Cần Thơ**
Department of Education and Training of Can Tho City

Website : http://cantho.edu.vn/

### CODE REVIEW

**Comment by philipto** [comment]
@thanhutnguyen Could you please tell us more about the domain? To whom the department of education assigns the email addresses in this domain? Do students and teachers only use them? How many students and teachers have email addresses in this domain? Do the students retain the email address in this domain after graduation?

Thank you.

**Comment by thanhutnguyen** [comment]
Hello @philipto 

To whom the department of education assigns the email addresses in this domain?
- **The "Information Technology Department" of the "Department of Education & Training" is responsible for providing Emails to Teachers.**

Do students and teachers only use them?
- **Email is provided to Teachers only**

How many students and teachers have email addresses in this domain?
- **Email is provided to about 1000-1500 teachers**

Do the students retain the email address in this domain after graduation?
- **Emails are not provided to Students.**
- **Emails are only provided to Teachers (Emails will be deleted when Teachers leave School)**

Thank you.

**Comment by philipto** [comment]
@thanhutnguyen Thank you for the clarification. Pull request merged.

**Comment by thanhutnguyen** [comment]
@philipto Thank you very much!

**Pull request merged**
