### PR TITLE
Create lvrkk

### PR DESCRIPTION
**Pull request by oeding**
Add Lääne-Viru College
http://www.lvrkk.ee/wp2105/?lang=en

### CODE REVIEW

**Comment by philipto** [comment]
@oeding I am sorry for a delay with processing your request. Please, rename lib/domains/ee/edu/lvrkk to lib/domains/ee/edu/lvrkk.txt to reflect this repository's rules. However, please ensure you know the domain exactly: accorrding to DNS records, there is no lvrkk.edu.ee domain, there is lvrkk.ee domain, and this is the address accessible via E-post link on the main page of www.lvrkk.ee.

In case actual domain is lvrkk.ee, the file for this repository should have path lib/domains/ee/lvrkk.txt

**Comment by oeding** [comment]
@philipto Hi, thank you. Email addressses are in format: firstname.lastname@edu.lvrkk.ee, i renamed the file to lvrkk.txt

**Comment by philipto** [comment]
I am sorry, it was a little confusing: if emails are firstname.lastname@edu.lvrkk.ee, the domain is for sure edu.lvrkk.ee, and it has DNS records. In this case, the file has to have name **lib/domains/ee/lvrkk/edu.txt**

Please rename the file to relect the domain name structure.

Thank you!

**Comment by oeding** [comment]
@philipto Sorry about the mess, everything should be fine now. Thank you, Philip!

**Comment by philipto** [comment]
@oeding thank you! The request is now merged. I will delete remaining file lib/domains/ee/edu/lvrkk.txt myslef, to reduce the mess :)

**Pull request merged**
