### PR TITLE
Add Wu-ling Senior High School

### PR DESCRIPTION
**Pull request by xTaiwanPingLord**
`@email.wlsh.tyc.edu.tw`
Thank you 😃

### CODE REVIEW

**Comment by philipto** [comment]
@xTaiwanPingLord First stage of verification passed, official domain is [wlsh.tyc.edu.tw](https://wlsh.tyc.edu.tw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@xTaiwanPingLord Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by xTaiwanPingLord** [comment]
@philipto 

`the school official website URL`
[https://www.wlsh.tyc.edu.tw/](https://www.wlsh.tyc.edu.tw/)

`the school street address, including city and country`
No. 889, Zhongshan Rd, Taoyuan District, Taoyuan City, 330, Republic of China (Taiwan)
中華民國（台灣） 330桃園市桃園區中山路889號

`an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course`
We have two types of IT-related long-term (>1 year) course:
[Wuling High School Course Plan](https://www.wlsh.tyc.edu.tw/p/405-1000-24524,c399.php?Lang=zh-tw) (In the attachments.)

1. For a normal class senior high school student, the class group E stands for Electronic Engineering and Computer science. The two subject is the main focus of this group.
2. For a science class or a mathematics and science gifted student, we have "research class" which we go to [National Central University](https://www.ncu.edu.tw/en/index.html) and have research and college courses in gourp like math, chemistry, and computer science is included, surely.

`a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.`
[Link (Google sites)](https://sites.google.com/email.wlsh.tyc.edu.tw/library/%E8%B3%87%E8%A8%8A%E5%AA%92%E9%AB%94%E7%B5%84/%E8%B3%87%E8%A8%8A%E7%B3%BB%E7%B5%B1%E5%AD%B8%E7%94%9F?authuser=0)
image

**Comment by philipto** [comment]
@xTaiwanPingLord  Thank you for the clarifications. Pull request merged.

**Pull request merged**
