### PR TITLE
Create spydebergskolen.txt

### PR DESCRIPTION
**Pull request by MindBunny**

### CODE REVIEW

**Comment by philipto** [comment]
@MindBunny I am sorry, the website spu.no says that it is under construction. Please provide some info to prove that this domain actually belongs to a school, which fits the requirements described in this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot)

**Comment by philipto** [comment]
@MindBunny You might miss my previous comment. Please reply.

**Comment by MindBunny** [comment]
My school enail is spk-erinil@spydebergskolen.no

The school website is spydeberg.kommune.no

**Comment by MindBunny** [comment]
@philipto http://www.spydeberg.kommune.no/spydeberg-ungdomsskole.377196.no.html

**Comment by philipto** [comment]
@MindBunny Thank you for the update! It means that your email domain is spydebergskolen.no, and the file name to represent the domain in this repository has to be lib/domains/no/spydebergskolen.txt. Please rename the file in your request. If you don't know how to rename the file, you can close this request and make a new one.

**Comment by MindBunny** [comment]
Will do!

**Comment by MindBunny** [comment]
Its now done @philipto

**Comment by philipto** [comment]
@MindBunny Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by philipto** [comment]
@MindBunny Please wait about half an hour from now before requesting free license. It takes about 30 minutes for the new data to propagate through JetBrains licenising system.

**Comment by MindBunny** [comment]
All good, you start at this school when u are 13 so all good

**Pull request merged**
