### PR TITLE
Create eduhouse.txt

### PR DESCRIPTION
**Pull request by quoxsii**
College official website: http://www.tcmc.spb.ru/
List of courses: http://www.tcmc.spb.ru/abiturient/profession

### CODE REVIEW

**Comment by philipto** [comment]
@quoxsii Could you please explain the discrepancy between the name of the organization that you want to register - **St. Petersburg Technical College of Management and Commerce** and the owner of the **eduhouse.ru** domain - **Saint-Petersburg Physicomechanical engineering college**? They are two clearly different names.

**Comment by philipto** [comment]
@quoxsii You might miss my previous comment. Please react.

**Comment by quoxsii** [comment]
This is probably the old name, when I try to search, it gives me the same college, I dont know how did you found this name.

image

image

image

There is a link to the mail on the [do.eduhouse.ru](https://do.eduhouse.ru/) website, which is owned by the **St. Petersburg Technical College of Management and Commerce**.

image

image

**Comment by philipto** [comment]
@quoxsii Thank you for the clarification. Pull request merged.

**Pull request merged**
