### PR TITLE
Add talnet.nl

### PR DESCRIPTION
**Pull request by Mindgamesnl**
Talnet is the email domain students use with theire school account (goes via outlook)

If needed, i can and im willing to verify

### CODE REVIEW

**Comment by ozzfelipe** [comment]
Ok

**Comment by philipto** [comment]
@Mindgamesnl @ozzfelipe Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by ozzfelipe** [comment]
Segue screenshots da universidade e URL oficial.

http://unisociesc.com.br



Em dom, 23 de set de 2018 11:51, Philip Torchinsky <notifications@github.com>
escreveu:

**Comment by philipto** [comment]
@ozzfelipe I am sorry, it looks like you need to make your own pull request. This request is about a domain talnet.nl, and you mentioned http://unisociesc.com.br, which related to completely different university. 

Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with correct information. Thank you for the understanding!

**Comment by philipto** [comment]
@Mindgamesnl Please reply my comment above, I can not find enough information about your school. If you are unable to provide us with more details, I have to close the request without merging.

**Comment by philipto** [comment]
@Mindgamesnl The main issue with adding talnet.nl domain to SWOT is that it's not clear if talnet.nl is used by multiple institutions or not. The contact page https://www.rocva.nl/Contact/Adressen says that most of the official contacts of the school is in rocva.nl domain. talnet.nl domain is not mentioned there. The attached screenshot does not have any instructions saying that students of the school use talnet.nl domain. 

If talnet.nl is not dedicated to your school, I would advise you to close this request and apply for free license at jetbrains.com/student using an "OFFICIAL DOCUMENT" option.

**Comment by Tristandemuijnck** [comment]
@philipto We at ROC hilversum (subdivision of ROC Amsterdam) use the talnet emailaddress but we also have an other school email: username@student.rocva.nl . This email is dedicated to students of ROC Amsterdam which ROC Hilversum is a subdivision of.

**Comment by philipto** [comment]
@Mindgamesnl Thank you for the clarification. Please rename lib/domains/nl/talnet.txt to lib/domains/nl/rocva.txt, and use username@student.rocva.nl to apply for free licenses at https://jetbrains.com/student as soon as the pull request will be merged. It allows to follow this repository rules precisely and avoid confusion.

**Comment by philipto** [comment]
@Mindgamesnl I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
