### PR TITLE
move hbhgkj.txt

### PR DESCRIPTION
**Pull request by xjfnet**
our domain changed from hbhgkj.com to hbhgkj.edu.cn

### CODE REVIEW

**Comment by nicolasngc** [comment]
CFL 404
centro de formacion laboral 404
[abc.txt](https://github.com/JetBrains/swot/files/15027001/abc.txt)

**Comment by philipto** [comment]
@xjfnet First stage of verification passed, official domain for **黄冈科技职业学院** is [hbhgkj.com](https://hbhgkj.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by xjfnet** [comment]
image

image

image

**Comment by philipto** [comment]
@xjfnet  Thank you for the update and clarifications. Pull request merged.

**Pull request merged**
