### PR TITLE
Add pasdphantoms.net

### PR DESCRIPTION
**Pull request by caseif**

### CODE REVIEW

**Comment by zweizwei** [comment]
@caseif Sorry for the delay - we've been launching rebranding and I hadn't time to check the repo for a while. 

The district's website seems to be www.pasd.com/ - please provide the confirmation of the fact that the domain also belongs to the district. Thank you.

**Comment by caseif** [comment]
It doesn't have an assigned A record, but it's used for student email addresses. You should be able to verify ownership via the WHOIS records for the domain.

**Comment by zweizwei** [comment]
@caseif somehow i can't reach Who.is at the moment - could you verify the domain there and send me a screenshot? thanks!

**Comment by zweizwei** [comment]
@caseif i'm closing the request due to having no answer from you. Please reply to reopen.

**Pull request closed without merging**
