### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ytebacninh**

### CODE REVIEW

**Comment by philipto** [comment]
@ytebacninh First stage of verification passed, official domain is [ytebacninh.edu.vn](https://ytebacninh.edu.vn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@ytebacninh Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by philipto** [comment]
@ytebacninh You might miss my previous comment. Please react.

**Comment by ytebacninh** [comment]
> @ytebacninh You might miss my previous comment. Please react.

[philipto](https://github.com/philipto) Thanks for your reminder. I would like to send the link of our information technology course. We hope to receive your company's support so that our students can be comfortable in their studies.
http://ytebacninh.edu.vn/2018/11/26/cao-dang-cong-nghe-thong-tin/

**Comment by philipto** [comment]
@ytebacninh  Thank you for the clarifications. Pull request merged.

**Pull request merged**
