### PR TITLE
Create ua.txt

### PR DESCRIPTION
**Pull request by jeanmarcazzi**
Official Website:  http://www.upa.edu.lb

IT Related Courses:  http://www.upa.edu.lb/unites-universitaires/facultes-et-departements/faculte-d-ingenieurs-en-informatique-multimedia-systemes-telecommunication-et-reseaux/options.html  (System Engineering, Télécommunication Engineering, Software Engineering, Multimedia Engineering)

WebMail: https://webmail.ua.edu.lb/

### CODE REVIEW

**Comment by philipto** [comment]
@jeanmarcazzi Could you please explain what is the relation between @ua.edu.lb and @uantonine.net? Where we can check that @uantonine.net is a student email indeed? Thank you.

**Comment by jeanmarcazzi** [comment]
@philipto Dear, here's my friend's email open being @uantonine.net . For the @ua.edu.lb it was more of a domain change as I was clarified now. So I guess for us students we can go with @uantonine.net only and will let you know later on if we need the ua.edu.lb .
Thank you.
img_3844

**Comment by jeanmarcazzi** [comment]
@philipto do you need me to create a new pull request with only the uantonine.net file ?..

**Comment by philipto** [comment]
@jeanmarcazzi Pull request merged. Actually, it would be enough to give me this URL: http://www.upa.edu.lb/ar/circulaires-administratives/circulaire/article/circulaire-administrative-relative-aux-ecourses-et-aux-mails-universitaires.html, it is at the official university website and says "Tout étudiant est doté d’une adresse e-mail « ..........@uantonine.net », consultable depuis le SIS de l’UA. "

You don't need to make separate pull request for the second domain, your pull request is merged, and both university domains are now added to the repository.

Thank you!

**Comment by jeanmarcazzi** [comment]
@philipto Thank you for your quick response! Now we can enjoy your products!

**Pull request merged**
