### PR TITLE
Add jmu university  - Iraq

### PR DESCRIPTION
**Pull request by TaifRaoof**

### CODE REVIEW

**Comment by philipto** [comment]
@TaifRaoof First stage of verification passed, official domain is [jmu.edu.iq](https://jmu.edu.iq) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@TaifRaoof Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@TaifRaoof You might miss my previous comment. Please react.

**Comment by TaifRaoof** [comment]
we are a medical university and have an IT Department  consist of 15 employees to develop some software used in medical university.

**Comment by philipto** [comment]
@TaifRaoof Thank you for the clarification. JetBrains free educational licenses are for **educational purpose** only, they are only for teachers and students. If you need the tools for the internal university needs, please send an email to sales@jetbrains.com and ask for a special discount for academic institutions. 

I have to close this request without merging. Thank you for your understanding.

**Pull request closed without merging**
