### PR TITLE
Add Chennai Mathematical Institute

### PR DESCRIPTION
**Pull request by meta-coder**
http://www.cmi.ac.in/
https://en.wikipedia.org/wiki/Chennai_Mathematical_Institute

### CODE REVIEW

**Comment by philipto** [comment]
@meta-coder Regrettably, CMI web site does not answer now, please let us know if there is another URL where we can see it. Thank you.

**Comment by meta-coder** [comment]
[Chennai has been hit by a cyclone](http://www.thehindu.com/news/national/tamil-nadu/Chennai-adjacent-districts-grapple-with-cyclone-havoc/article16802182.ece). Power supply, network connectivity has been affected. The website should be up in a few days when the connectivity gets restored.

**Comment by philipto** [comment]
@meta-coder O, I regret that you suffered from natural disaster. I am sorry! We'll wait until the website is up, and merge the request as soon as confirm the information in it. Thank you!

**Comment by meta-coder** [comment]
Hi @philipto, the site is up now.

**Comment by philipto** [comment]
@meta-coder Thank you! Pull request merged.

**Pull request merged**
