### PR TITLE
Create gjust

### PR DESCRIPTION
**Pull request by nishant95**
gjust mail server is http://mail.gjust.org
Its website is http://www.gjust.ac.in

### CODE REVIEW

**Comment by nishant95** [comment]
Please check the link given as "Webmail" in the footer of the University Website (http://www.gjust.ac.in/). It redirects to http://mail.gjust.org where the mail server is hosted.

**Comment by philipto** [comment]
@nishant95 Please rename lib/domains/org/gjust to lib/domains/org/gjust.txt. Thank you!

**Comment by nishant95** [comment]
@philipto Done.

**Comment by philipto** [comment]
@nishant95 Pull request merged. Thank you!

**Pull request merged**
