### PR TITLE
add kientruchanoi.txt

### PR DESCRIPTION
**Pull request by hoangtung56pm**

### CODE REVIEW

**Comment by philipto** [comment]
@hoangtung56pm Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by hoangtung56pm** [comment]
Hi team,

This is my university website: http://hau.edu.vn/

Thank you for your support

Regard,

**Comment by philipto** [comment]
@hoangtung56pm Thank you for the information. Please provide us with an **URL of a page** on the official website where the school **offers an IT-related long-term (>1 year) course**.

I understand that the university website is http://hau.edu.vn. I cannot find a course there that offers any software development study. Therefore, I cannot understand why the students of this school need a software development tools.

Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot). Only schools that provides students with some long-term courses related to the information technologies are eligible to be added to this repository.

**Comment by hoangtung56pm** [comment]
Hi philip

I'm sorry about missing understand. This is my information technology major
website:
https://fit-hau.edu.vn/post/gioi-thieu-khoa-cong-nghe-thong-tin-65581.html.

Best regards,

**Comment by philipto** [comment]
@hoangtung56pm  Thank you for the clarifications. Pull request merged.

**Pull request merged**
