### PR TITLE
Create costachenegri.txt

### PR DESCRIPTION
**Pull request by Serban2003**

### CODE REVIEW

**Comment by philipto** [comment]
@Serban2003 Could you please explain why two websites and two domains exist for the same school: costachenegri.ro and cncn.ro?

**Comment by Serban2003** [comment]
Hi! I'm sorry for the confusion. "cncn.ro" is the old site, and our
highschool management decided to make a new domain for a new one. The main
site is "costachenegri.ro".

**Comment by philipto** [comment]
@Serban2003 Could you please ask your school management to provide a proof of this decision? For example, can I read about at at the old website, cncn.ro?

**Comment by Serban2003** [comment]
Yes, I will, but it will take some time (Monday or Tuesday).

**Comment by philipto** [comment]
@Serban2003 Do you have any update, please?

**Comment by Serban2003** [comment]
Sorry for the late reply. My highschool management had been infected with
COVID-19. I don't t know how and when, but they are in home isolation.
I suggest canceling the application until we pass these trying times. Sorry
for the lost time.

**Comment by philipto** [comment]
@Serban2003 No problem. Please feel free to use trial version for now, and don't hesitate to request a free license with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students). You can use any email address while applying with the docs, including your individual private one. 

You can reopen this request or create a new one at any time. Thank you!

**Pull request closed without merging**
