### PR TITLE
Create s

### PR DESCRIPTION
**Pull request by ymntt**

### CODE REVIEW

**Comment by zweizwei** [comment]
the university domain is it-chiba.ac.jp - therefore the path should be /domains/jp/ac/it-chiba.txt - please fix

**Comment by ymntt** [comment]
Student use ~@s.chibakoudai.jp now
Student cannot use ~@it-chiba.ac.jp from 2013

**Comment by zweizwei** [comment]
@ymntt  Could you please somehow confirm the fact? - a relevant page / document with information would be good. Thank you!

**Comment by ymntt** [comment]
I have attached document(Japanese).

**Comment by zweizwei** [comment]
thanks so much for adding the document. One last thing - could you please add .txt extension to the path and I'll add the domain

**Comment by ymntt** [comment]
rename now.
~@s.chibakoudai.jp → chibakoudai/s.txt 
is it all right?

**Comment by zweizwei** [comment]
Thanks, adding the domain!

**Pull request merged**
