### PR TITLE
add Schaffhausen Institute of Technology to the domains list

### PR DESCRIPTION
**Pull request by AleksTankist111**
Add Schaffhausen Institute of Technology (Switzerland) to the domains list.

### CODE REVIEW

**Comment by heidiz411** [comment]
Add Roi Et Rajabhat University (Thailand) to the domains list.

**Comment by philipto** [comment]
@AleksTankist111 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.


@heidiz411 Please create a separate pull request for your university. Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with correct information. Thank you for the understanding!

**Comment by philipto** [comment]
@AleksTankist111 You might miss my previous comment. Please react.

**Comment by AleksTankist111** [comment]
Hello, Philip!I wrote to my university to get the confirmation. I am waiting for the answer. I hope I'll receive it soon!06.08.2021, 13:43, "Philip Torchinsky" ***@***.***>:
@AleksTankist111 You might miss my previous comment. Please react.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
-- Best wishes, Aleksandr Skakun

**Comment by philipto** [comment]
@AleksTankist111 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
