### PR TITLE
Add Universidad Metropolitana para la Educación y el Trabajo - ARG

### PR DESCRIPTION
**Pull request by ballesterosd**
Official website: https://umet.edu.ar/
Bachelor of Computer Science: https://umet.edu.ar/course/informatica/

### CODE REVIEW

**Comment by ballesterosd** [comment]
image

**Comment by philipto** [comment]
@ballesterosd lib/domains/ar/edu/soflab.umet.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by ballesterosd** [comment]
@philipto 
Hi. I just submit a fix. 
Sorry for this mistake.
Thanks for your atention.

**Comment by philipto** [comment]
@ballesterosd I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host soflab.umet.edu.ar not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Pull request closed without merging**
