### PR TITLE
Create edu.txt for @edu.vlerick.com emails

### PR DESCRIPTION
**Pull request by sushramesh**
Hi, students of Vlerick Business School receive an @edu.vlerick.com email address. 
http://www.vlerick.com/en

Kindly merge this Pull request.

Thanks

### CODE REVIEW

**Comment by philipto** [comment]
@sushramesh I am sorry, I was not able to find a page on the official website where an IT-related long-term (>1 year) course is offered by the university. On the opposite, I found out that many courses at the univrsity are short-term (from few hours to few days), and I saw no IT-related courses at all. Could you please give us a link on the long-term IT-related courses?

**Comment by sushramesh** [comment]
Hi @philipto,

Ours is a business school, hence it will have limited, but important focus on IT-related courses. You can check the following page for examples on the focus:
https://www.vlerick.com/en/management-expertise/digital-transformation

A lot of work in the school relates to IT industry, for example in my current project I am helping a non-profit organisation transition from paper based to Software Workflow management system to streamline their hiring process.

I also worked with an IT consulting company, defining their go-to-market strategy to enter the US market with their services.

Hope this helps, let me know if you need any other information.

**Comment by philipto** [comment]
@sushramesh Thank you! Yes, you are right saying that courses in outher disciplines may have focus on IT-related stuff too. However my concern is whether your short-term course students can have their e-mails from the same e-mail domain as the long-term course students. We DO NOT encourage people who are students for short term period (just few months or even weeks) to get a free student license for a year; the best way for them to use JetBrains tools for free is to ask sales@jetbrains.com for extending their trial period, if they really need it for more than a month, or ask their teacher to apply for classroom license by email to classroom@jetrains.com.

This repository helps students of long-term courses only. Could you please disclose what is a part of long-term courses students in your university? Is it 90%? 10%?

Thank you for your understanding!

**Comment by sushramesh** [comment]
@philipto, I understand the concern. As far as I know none of the students of short term courses get an e-mail address from this domain. It is only meant for 1-year+ management course students. So the students of the 3 to 15 day workshops are not full-time students of the university.

This business school is part of K U Leuven in Belgium and they only provide student ID card and other benefits for full-time students spending a year or more in the university.

From what I can tell in our university, 80%+ students are full-time. The part-time/short-term courses are meant for working professionals in the industry. Those classes are only on weekends normally.

The largest groups of students in our business school are:
1) 1 year Masters in Management students in these specialisations: https://www.vlerick.com/en/programmes/master-programmes
2) 1 year+ full-time MBA students:
https://www.vlerick.com/en/programmes/mba-programmes/full-time-international-mba-programme/programme-structure
3) Executive MBA (normally 18 months on weekends):
https://www.vlerick.com/en/programmes/mba-programmes/executive-mba-belgium

Hope this helps. Let me know if you need any other info.

**Comment by philipto** [comment]
@sushramesh Thank you for the clarification. Pull request is now merged. Thanks!

**Pull request merged**
