### PR TITLE
Added domain

### PR DESCRIPTION
**Pull request by ninalamo**

### CODE REVIEW

**Comment by philipto** [comment]
@ninalamo Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@ninalamo You might miss my previous comment. Please react.

**Comment by ninalamo** [comment]
thanks for the bump. i will revert back to this message with the information needed

**Comment by philipto** [comment]
@ninalamo I am really sorry, but may I ask you for some deadline estimation? When do you plan to submit the necessary information? By the way, you also can enroll to [GitHub Student Developer Program](https://education.github.com/pack) and receive the free JetBrains subscription via GitHub authorization. Please let me know if you choose this way and wish to close this request,

**Comment by philipto** [comment]
@ninalamo I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
