### PR TITLE
Add domain zsl.poznan.pl

### PR DESCRIPTION
**Pull request by Maniues**
Website: https://zsl.poznan.pl/
Emails/contact page: https://zsl.poznan.pl/kontakt/
Time tables: https://zsl.poznan.pl/wp-content/uploads/2024/09/plan2024_09_08.pdf
School year calendar: https://zsl.poznan.pl/wp-content/uploads/2024/09/KALENDARIUM-R.SZK_.-2024_2025.pdf
Fields of study: https://zsl.poznan.pl/zawody/

ZSŁ provides the following programs:
- [Cisco networking academy](https://zsl.poznan.pl/akademia-cisco/)
- [MikroTik Academy](https://zsl.poznan.pl/akademia-mikrotik-2/)
- [Huawei ICT Academy](https://zsl.poznan.pl/akademia-huawei/)
- [ICDL (International Computer Driving Licence) formerly ECDL](https://zsl.poznan.pl/laboratorium-ecdl/): Exams for Digital Skills

### CODE REVIEW

**Comment by philipto** [comment]
@Maniues lib/domains/pl/poznan/zsl: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Maniues First stage of verification passed, official domain for **Zespół Szkół Łączności w Poznaniu im. Mikołaja Kopernika** is [zsl.poznan.pl](https://zsl.poznan.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Maniues Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by humand09** [comment]
Thank you @Maniues for finding out how to do it, and giving a second life to my 3 year old email. You are the hero many of us do not deserve, and yet we shall make use of you sacrifice of time and knowledge with giving no compensation or meaningful praise; for this is the true value of your work: to be the one who improves the wellbeing of all of humanity at the price of oneself.

**Pull request merged**
