### PR TITLE
Add Zst Sopot (Zespol Szkol Technicznych w Sopocie) from Poland

### PR DESCRIPTION
**Pull request by Klubuntu**
**Please add Zespół Szkół Technicznych w Sopocie on Street Wejherowska 1 to school list**
*Official School Domain: http://zstsopot.pl*
*Students & Teacher domain* **zst-sopot.edu.pl**
image
image

### CODE REVIEW

**Comment by philipto** [comment]
@Klubuntu Thank you for the request. Could you please clarify few details regarding your school? There are too many different domains and redirects from one to another. 

Please provide us with:
- the school official website URL
- the school street address, including city 
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by Klubuntu** [comment]
**School Official Website:** *http://zstsopot.pl*, *redirect to: https://zshsopot.edupage.org/*
**School Location:** *Sopot, Street: Wejherowska 1, Poland*
**School offers long-term course (5 years):** *https://zshsopot.edupage.org/a/strefa-kandydata/* or
*https://zshsopot.edupage.org/a/strefa-kandydata?eqa=dGV4dD10ZXh0L3RleHQyNSZzdWJwYWdlPTE%3D*
**Students & Teacher email domain:** *zst-sopot.edu.pl*


*Who.is Data below*
image
image

*My School Email*
image

**Comment by philipto** [comment]
FTR: more proof of the domain recognition:
```
$ host -t any zst-sopot.edu.pl
zst-sopot.edu.pl has address 91.237.52.78
zst-sopot.edu.pl name server ns2.cyberfolks.pl.
zst-sopot.edu.pl name server ns3.cyberfolks.pl.
zst-sopot.edu.pl name server ns1.cyberfolks.pl.
zst-sopot.edu.pl has SOA record ns1.cyberfolks.pl. hostmaster.zst-sopot.edu.pl. 2021082612 14400 3600 1209600 3600
zst-sopot.edu.pl mail is handled by 0 zstsopot-edu-pl0i.mail.protection.outlook.com.
zst-sopot.edu.pl descriptive text "v=spf1 include:spf.protection.outlook.com -all"
zst-sopot.edu.pl descriptive text "MS=ms32590587"

$ host -t any zstsopot.pl
zstsopot.pl has address 91.237.52.78
zstsopot.pl name server dns2.linuxpl.com.
zstsopot.pl name server dns1.linuxpl.com.
zstsopot.pl has SOA record dns1.linuxpl.com. root.zstsopot.pl. 2021081800 14400 3600 1209600 3600
zstsopot.pl mail is handled by 10 mail.zstsopot.pl.
zstsopot.pl descriptive text "v=spf1 a mx include:spf.linuxpl.com ip4:91.237.52.78 ~all"

```

**Comment by philipto** [comment]
@Klubuntu Thank you for the clarification. Pull request merged.

**Comment by Klubuntu** [comment]
**Thanks for merge**

> @Klubuntu Thank you for the clarification. Pull request merged.

**Pull request merged**
