### PR TITLE
Adding Academy of Sciences of Moldova

### PR DESCRIPTION
**Pull request by aidjek**
#### Institution/School Name 
Academy of Sciences of Moldova

#### Instiution/School Website
asm.md

#### Email Users

*Please place an x between the square brackets if yes*
- [x] Students
- [x] Academic/Teaching Staff
- [x] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [x] Post-graduate research
- [x] Graduate School
- [x] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [ ] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by philipto** [comment]
@aidjek I am sorry, this organization is not a university, nor a college. Please email to community-support@jetbrains.com in order to get some free classroom licenses for students, if you have ones. Please note that your organization has to provide the students with long-term (> 1 year long) IT-related courses to be eligible for applying for classroom licenses. You also can ask community-support@jetbrains.com about other free options for your students, and buy commercial license with a discount for academical organization, if necessary. Thank you!

For now, I have to close the request without merging. Thank you for the understanding!

**Comment by aidjek** [comment]
Hello @philipto . 

 forget to make a note that there is an University based on the Academy of Science of Moldova http://edu.asm.md/en but it doesn't have separate email domain for use. 

Can you please review this merge request again using this fact ? 
screenshot 2018-06-26 15 20 53

**Comment by aidjek** [comment]
Also I want to add one more note:

it was already added in leereilly main repo:
https://github.com/leereilly/swot/pull/1466

https://github.com/leereilly/swot/commit/0d6c7bcf9b1fbe5a53e3319691af3ea72e484b56

**Comment by philipto** [comment]
@aidjek Thank you for the additional details. You are right, the problem is exactly what you mentioned: there is an University based on the Academy of Science of Moldova http://edu.asm.md/en **but it doesn't have separate email domain for use**. May I ask you to email community-support@jetbrains.com and discuss possible options available for the students in the university? We often offer other free options for universities in such controversial situations.

**Pull request closed without merging**
