### PR TITLE
Adding Labaki - Technology Center

### PR DESCRIPTION
**Pull request by ioannis-t**
Please add my technology center

### CODE REVIEW

**Comment by philipto** [comment]
@ioannis-t Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@ioannis-t You might miss my previous comment. Please react.

**Comment by ioannis-t** [comment]
Hi all, Labaki is a newly established technology center.
URL: https://www.labaki.gr
Address: Leof. 62 Martiron 150, Iraklio 713 03
Our [last educational course level](https://labaki.gr/courses#inventors), last for for more than 1 year and we are developing various projects, including web applications using PHP, MySQL, JS, CSS etc.
About the proof for the domain, I am using the address giannis@labaki.gr on this account. Could you please be more specific, on what else should I provide?

**Comment by philipto** [comment]
@ioannis-t  Thank you for the clarifications. Pull request merged.

**Pull request merged**
