### PR TITLE
Edit

### PR DESCRIPTION
**Pull request by norepository**

### CODE REVIEW

**Comment by philipto** [comment]
@norepository First stage of verification passed, official domain is [liceoaselli.edu.it](https://liceoaselli.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by norepository** [comment]
> @norepository First stage of verification passed, official domain is [liceoaselli.edu.it](https://liceoaselli.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Thanks for the reply, imma wait for the final decision! 💯

**Comment by philipto** [comment]
@norepository Thank you for your patience while waiting for a review and processing your request. Pull request merged. Thank you!

**Comment by norepository** [comment]
> @norepository Thank you for your patience while waiting for a review and processing your request. Pull request merged. Thank you!

Thanks! When ill be able to see changes on the site? i still have this error: "Your email address does not belong to any university that we know. You can apply with another method (see tabs above) or add your school to JetBrains' list."

**Pull request merged**
