### PR TITLE
Add USSH university

### PR DESCRIPTION
**Pull request by giapnb**
This is my school website:
https://ussh.vnu.edu.vn/
My school is a part of Viet Nam National University (VNU)
This is a wiki website about our school: 
https://vi.wikipedia.org/wiki/Tr%C6%B0%E1%BB%9Dng_%C4%90%E1%BA%A1i_h%E1%BB%8Dc_Khoa_h%E1%BB%8Dc_X%C3%A3_h%E1%BB%99i_v%C3%A0_Nh%C3%A2n_v%C4%83n,_%C4%90%E1%BA%A1i_h%E1%BB%8Dc_Qu%E1%BB%91c_gia_H%C3%A0_N%E1%BB%99i

Please approve for my MR

### CODE REVIEW

**Comment by philipto** [comment]
@giapnb The domain registrant for **sv.edu.vn** is Ông Từ Đình Tuấn (Mr. Tu Dinh Tuan). This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by giapnb** [comment]
> @giapnb The domain registrant for **sv.edu.vn** is Ông Từ Đình Tuấn (Mr. Tu Dinh Tuan). This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Hi @philipto ,
I don't know the domain"sv.edu.vn". I think you are mistaken, our domain is "sv.ussh.edu.vn"
One more thing, my school email is 19032296@sv.ussh.edu.vn
I need your approval as soon as possible to register JetBrains IDE.

**Comment by giapnb** [comment]
@philipto do you need more informations ?

**Comment by philipto** [comment]
@giapnb You submitted a file lib/domains/vn/edu/sv.txt. It corresponds a domain **sv.edu.vn**. I will rename it according to your comment and make a new review. Thank you.

**Comment by philipto** [comment]
@giapnb I am sorry, the domain sv.ussh.edu.vn is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
