### PR TITLE
SDS IT Nur Muria

### PR DESCRIPTION
**Pull request by johndeehisy**
Please approve

### CODE REVIEW

**Comment by philipto** [comment]
@johndeehisy First stage of verification passed, official domain is [dnm.sch.id](https://dnm.sch.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by johndeehisy** [comment]
> @johndeehisy First stage of verification passed, official domain is [dnm.sch.id](https://dnm.sch.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Thank you for your attention. We will always wait for your best decision.

**Comment by johndeehisy** [comment]
Thank for your attention. Please let us know if there are any documents
needed to prove the legitimacy of our institution

**Comment by philipto** [comment]
@johndeehisy Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by johndeehisy** [comment]
thank you so much sir

**Pull request merged**
