### PR TITLE
added fbest to .org.br folders

### PR DESCRIPTION
**Pull request by dfvneto**
Added the Centro Universitário Senai Cimatec to the files, wich is an university center in Salvador, Bahia

### CODE REVIEW

**Comment by philipto** [comment]
@dfvneto According to http://www.senaicimatec.com.br/contato/, SENAI CIMATEC has another official email domain, and email addresses there end with @SENAICIMATEC.COM.BR. Could you please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students?

**Comment by dfvneto** [comment]
@philipto The domain @FBEST.ORG.BR is the domain used by interns that are also students in SENAI CIMATEC. The studens of SENAI CIMATEC dont have a official domain. The @SENAICIMATEC.COM.BR is the domain used only by employee here. I can send my internship contract alongside my college receipt if thats enough.

**Comment by philipto** [comment]
@dfvneto If we understand being an intern (i.e., having an internship) as it's explained in Wikipedia, https://en.wikipedia.org/wiki/Internship, students can apply for free educational subscription for JetBrains tools using their university email, not an email in an organization where they have temporary internship.

Could you please give us a link to a page or a document, which confirms that FBEST.ORG.BR is used by the students, and if yes, which organization these students belong to? What is the name and the official website of this organization?

If you decide to attach any document to your comment, please do not send it by email as attachment, GitHub strips such attachments away. Instead, attach it to your comment via GitHub web interface.

If your school does not provide you with an email, feel free to apply at https://www.jetbrains.com/shop/eform/students with your school ID at the tab "OFFICIAL DOCUMENT".

Thank you!

**Comment by dfvneto** [comment]
@philipto Sorry, but I wasnt authorized to provide such document.
Thanks for your attention :D

**Pull request closed without merging**
