### PR TITLE
Create cqucc.txt

### PR DESCRIPTION
**Pull request by JinkunTian**
Add City College of Science and Technology.Chongqing University ROOT Domain

### CODE REVIEW

**Comment by philipto** [comment]
@JinkunTian Please provide us with a link to the page at the official website, www.cqu.edu.cn, which confirms that cqucc.edu.cn is an official email domain for the students of City College of Science and Technology,Chongqing University.

**Comment by philipto** [comment]
@JinkunTian You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@JinkunTian I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Comment by JinkunTian** [comment]
official website is http://www.cqucc.edu.cn

**Pull request closed without merging**
