### PR TITLE
Add My Uni(ICT UNIVERSITY)

### PR DESCRIPTION
**Pull request by Alfred-Collins-Ayamba**
Uploaded this file following instructions from "[JetBrains Products for Learning]" inorder for my uni to benefit from JetBrains Products for Learning.

### CODE REVIEW

**Comment by philipto** [comment]
@Alfred-Collins-Ayamba Please provide more info on who can use the email addresses with a pattern username@ictuniversity.org. Do students of university attend it offline? If yes, where? If most of them study online, how the university control if a student actually takes courses, instead of just using student benefits because of having an email address issued by the university?

**Comment by Alfred-Collins-Ayamba** [comment]
Hi @philipto below is the information you requested;

All students of the ICT University that are fully enrolled can use the email address with the universities domain. Upon enrollment, students are assigned a school email address with the pattern firstname.lastname@ictuniversity.org.
The university offers both online and onsite studies. With the majority of students doing onsite.
Here's the campus on google map https://goo.gl/maps/Cigm85AQALca31JA. The Uni is located in Cameroon, Yaounde city precisely.
Also the university uses the students email address and a custom password created by the student upon enrollment as a means of authentication to their online study platform.
 The school email addresses is only valid for as long as the student's program would last. Usually the maximum is 4yrs for BSC students except when student had carry overs or something else happens that would interfere with the normal school seasons.
Since some of the lecturers that teach at the uni are foreign, it makes having a school email of utmost importance so students can enroll on these courses online to be able to follow them.
Upon termination of the students contract, all school property is use is also suspended.

Let me know if you have more queries
Kind regards

**Comment by Alfred-Collins-Ayamba** [comment]
Hi here is the google 
https://www.google.com/maps/place/ICT+University/@3.9524874,11.5166106,15z/data=!4m2!3m1!1s0x0:0x42cdb742c77af0f9?sa=X&ved=2ahUKEwjUto_m1JPrAhUFDuwKHdiCB6EQ_BIwCnoECBcQCA

The one above is broken

**Comment by philipto** [comment]
@Alfred-Collins-Ayamba Thank you for the clarification. Pull request merged.

**Pull request merged**
