### PR TITLE
Add Kennett Consolidated School District

### PR DESCRIPTION
**Pull request by kjelstromjr**

### CODE REVIEW

**Comment by TheBotlyNoob** [comment]
@kjelstromjr Please provide us with:

* the school official website URL
* the school street address
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by kjelstromjr** [comment]
What do you mean by a proof?

**Comment by TheBotlyNoob** [comment]
a screenshot mainly. (see https://github.com/JetBrains/swot#how-to-add-the-domain-quicker)

**Comment by philipto** [comment]
@kjelstromjr Please attach a screenshot or any other document via GitHub web interface in a browser, not by replying to an email with attachment. GitHub strips out all attachments sent by email.

You can provide us with any of the following as a proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@kjelstromjr The main issue with your request is that there are many schools with similar names worldwide, and you did not mention any specific city and country where the school is located. We have to be able to verify an information about the school domain independently, not just by visiting a website corresponding the domain.

**Comment by jchernin4** [comment]
WHOIS for bluedemons.org: https://www.godaddy.com/whois/results.aspx?checkAvail=1&domain=bluedemons.org
School address: 100 E South St, Kennett Square, PA 19348

**Comment by philipto** [comment]
@kjelstromjr Thank you for the clarification. Pull request merged.

**Pull request merged**
