### PR TITLE
add new university

### PR DESCRIPTION
**Pull request by mohammed6688**

### CODE REVIEW

**Comment by philipto** [comment]
@mohammed6688 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

Thank you!

**Comment by philipto** [comment]
@mohammed6688 You might miss my previous comment. Please react.

**Comment by mohammed6688** [comment]
@philipto it's not a school it is a university that provides undergraduate degrees
the university URL: https://www.ohi.edu.eg/
the university address on google maps: https://maps.app.goo.gl/JtcuPYCGkgByVctL8
the university address: street 54, alhay al thalith, october, cairo
url include an it related department: https://www.ohi.edu.eg/About.aspx
you can find the third department
Third: Communications and Electronics  Engineering department  ( 5 years)

**Comment by philipto** [comment]
@mohammed6688 Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
