### PR TITLE
refactor: adding new educational institution

### PR DESCRIPTION
**Pull request by BrunoTulio**
adding new educational institution

### CODE REVIEW

**Comment by philipto** [comment]
@BrunoTulio Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@BrunoTulio You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@BrunoTulio I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by BrunoTulio** [comment]
* the school official website URL
http://www.educacao.ba.gov.br
* the school street address, including city and country
 Praça da Abolição - Centro, Macaúbas - BA, 46500-000
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
http://escolas.educacao.ba.gov.br/sites/default/files/private/midiateca/documentos/2018/tecnico-em-informaticaementas2018-2.pdf 
 * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
 http://consultaaluno.educacao.ba.gov.br/ for students and http://consultaenova.educacao.ba.gov.br/ for teachers

**Pull request closed without merging**
