### PR TITLE
Add amityschools.txt

### PR DESCRIPTION
**Pull request by mihirmjog**
School Site: amityregion5.org

### CODE REVIEW

**Comment by philipto** [comment]
@mihirmjog Could you please provide a proof of the fact that amityschools.org is an email domain of the school, which owns a website amityregion5.org? I did not find any references to amityschools.org at the website.

**Comment by mihirmjog** [comment]
@philipto My apologies, I should have provided proof.

Please go to AmityRegion5.org > Search "amityschools.org" within the widget.

I can try getting additional proof if needed.

**Comment by mihirmjog** [comment]
[I can also provide a link to amity's library resource center that instructs students on how to use their "@amityschools.org" account. ](http://arhs-amityregion5.libguides.com/c.php?g=135622&p=888729)

In addition, the "[Education Technology Plan Template](http://www.amityregion5.org/UserFiles/Servers/Server_3030111/File/Staff/Tech_Plan_Template_2015-18-final%20revision%202_3_15.pdf)" - which is a report submitted to the Connecticut State Department of Education to list the uses of technology in schools- has several mentions of amityregion5.org (see page 14, 32 and 34). 

Please let me know if you need anything else.

**Comment by philipto** [comment]
@mihirmjog Thank you for the clarification! Pull request merged.

**Pull request merged**
