### PR TITLE
Entry for thoren innovation school

### PR DESCRIPTION
**Pull request by ShariqMush**

### CODE REVIEW

**Comment by philipto** [comment]
@ShariqMush Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school.

**Comment by ShariqMush** [comment]
@philipto www.innovationsgymnasiet.se
gymnasium study in sweden is over 3 years of period

**Comment by philipto** [comment]
@ShariqMush It can be an incorrect translation issue (I use Google translate for this school website), however it is not clear that this school is a regular gymnasium. [This page](https://innovationsgymnasiet.se/program/it-program/) says that the school is a training center, and one of possible educational program takes just 16 weeks.

Could you please clarify what is actual school status, and how is the education there organized?

**Comment by ShariqMush** [comment]
@philipto It is a regular swedish private gymnasium(would be high school) where after 9th grade of compulsory school education you study for minimum 3 years. for less its IB. After 3 years its university.

**Comment by philipto** [comment]
@ShariqMush Thank you for the clarification. Pull request merged.

**Pull request merged**
