### PR TITLE
istg.txt

### PR DESCRIPTION
**Pull request by ANDYPILAY**
https://istg.edu.ec/
[est.txt](https://github.com/JetBrains/swot/files/9865047/est.txt)

### CODE REVIEW

**Comment by ANDYPILAY** [comment]
gh pr checkout 15532

**Comment by ANDYPILAY** [comment]
https://github.com/JetBrains/swot.git

**Comment by philipto** [comment]
@ANDYPILAY First stage of verification passed, official domain is [istg.edu.ec](https://istg.edu.ec) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@ANDYPILAY Pull request merged. Thank you.

**Pull request merged**
