### PR TITLE
Add TESCH file

### PR DESCRIPTION
**Pull request by DavichoStar**

### CODE REVIEW

**Comment by philipto** [comment]
@DavichoStar You might miss my previous comment. Please react.

**Comment by DavichoStar** [comment]
- https://tescha.edomex.gob.mx/
- Federal Highway Mexico Cuautla s/n, La Candelaria Tlapala, Chalco, Estado de México, Mexico
- https://tescha.edomex.gob.mx/oferta_academica
- On the page: https://tescha.edomex.gob.mx/faqs in the section: "¿Cuáles son los requisitos para publicar las vacantes que hay en mi empresa?" is an email used by the school with that domain

**Comment by philipto** [comment]
@DavichoStar First stage of verification passed, official domain is [tescha.edomex.gob.mx](https://tescha.edomex.gob.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://tescha.edomex.gob.mx/

**Comment by philipto** [comment]
@DavichoStar Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
