### PR TITLE
added nl/amolf.txt

### PR DESCRIPTION
**Pull request by JesseSlim**
Hi there,

I added the domain for AMOLF, a Dutch National Physics Institute.

### CODE REVIEW

**Comment by philipto** [comment]
@JesseSlim This organization seems to be purely research institute. However, if I am mistaken, could you please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school. If there is no such course offered, please close this request and email community-support@jetbrains.com in order to discuss the best possible options for licensing the students and employees of this Institute (which also can be free). Thank you!

**Comment by philipto** [comment]
@JesseSlim You might miss my previous comment. Please react.

**Comment by JesseSlim** [comment]
@philipto Thank you for the quick response! AMOLF is indeed mainly a physics research institute (although one could argue that PhD students receive their PhD education there). I saw some other research institutes in the repository as well, that's why a filed a request. Under these circumstances, does AMOLF qualify?

**Comment by philipto** [comment]
@JesseSlim No, AMOLF is not qualified. There are few research institutes in the repository, but only if they have really significant number of PhD students studying there. 

Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If AMOLF employees who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.

If there are some students and teachers at AMOLF, who are not teaching, nor studying in some universities, and thus they can not get free license using an email address assigned to them by  another educational institution, please ask them to request a free license which they are eligible for via applying with official document option ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

Thank you for the understanding! As for now, I have to close this request without merging.

**Pull request closed without merging**
