### PR TITLE
ocmt domain

### PR DESCRIPTION
**Pull request by aymanalkhalil**

### CODE REVIEW

**Comment by philipto** [comment]
@aymanalkhalil The first verification stage is complete: the official domain for  **Oman College of Management & Technology** is [www.omancollege.edu.om](https://www.omancollege.edu.om), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.omancollege.edu.om/

**Comment by aymanalkhalil** [comment]
yes this is the official domain but the student email of this college is StudentID@ocmt.edu.om

**Comment by philipto** [comment]
@aymanalkhalil The first verification stage is complete: the official domain for  **Oman College of Management & Technology** is [www.omancollege.edu.om](https://www.omancollege.edu.om), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.omancollege.edu.om/

**Comment by philipto** [comment]
@aymanalkhalil Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
