### PR TITLE
Add UNIS domain

### PR DESCRIPTION
**Pull request by AugustoHTPereira**

### CODE REVIEW

**Comment by philipto** [comment]
@AugustoHTPereira There is something odd at the university website: for some reason the admission section tells about the admission in 2018. Did the university stop enrolling in 2018? I am sorry, I can misunderstand something at the website, because I read it with Google Translate.

Also, please clarify whether the institution is a university or a group of universities. If it is a group, where can I read which universities are in the group?

**Comment by AugustoHTPereira** [comment]
@philipto Thanks for the answer.
I realy don't know if the university have some agreement with JetBrains.
The university website it's terrible, but here is the link of [courses page ](https://portal.unis.edu.br/cursos-presenciais), and here is the [computer science course page](https://portal.unis.edu.br/ciencia-da-computacao).

About the university, Unis it's a group of members and they have one university in many cities.

**Comment by philipto** [comment]
@AugustoHTPereira Pull request merged. Thank you!

FTR: more information about the university network: https://www.linkedin.com/school/grupounis/about/

**Comment by AugustoHTPereira** [comment]
@philipto Thank you!

**Pull request merged**
