### PR TITLE
add school info

### PR DESCRIPTION
**Pull request by Ericwise**
website: http://www.lt2006.com

### CODE REVIEW

**Comment by philipto** [comment]
@Ericwise First stage of verification passed, official domain is [lt2006.com](https://lt2006.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Ericwise** [comment]
> @philipto This school doesn't seem to offer more than one year IT related courses?

our school have IT courses, pls check the following book:
IMG_3074
ps://user-images.githubusercontent.com/8111825/168401266-1998374a-b60c-4fba-a33d-568912a9eeb0.jpeg)
:

**Comment by kawa11** [comment]
> > @philipto This school doesn't seem to offer more than one year IT related courses?
> 
> our school have IT courses, pls check the following book: IMG_3074 : IMG_3075

Junior high school students do not need to use the professional version, right? The free community edition suffices.

**Comment by Ericwise** [comment]
fine,that's ok.
I'm a teacher. I want to learn more.
I'll shut thiis pull, anyway.

**Comment by philipto** [comment]
@Ericwise You don't need to close the request. It is still in the review stage. I am waiting for my colleagues' review to make a final decision. As for using IntelliJ IDEA Community Edition and PyCharm Community: yes, you are free to use them without any subscriptions or licenses. If they are enough for your students, you don't need to have your domain added to the trusted list.

**Pull request closed without merging**
