### PR TITLE
Create digitalcampus.txt

### PR DESCRIPTION
**Pull request by drashka**
Can add Digital Campus school please ?
Site : http://www.digital-campus.fr
Email adress : digital-campus.net

### CODE REVIEW

**Comment by philipto** [comment]
@drashka Could you please clarify:
1) Is Digital Campus a university or another type of higher school? If yes, does it have a webpage with an IT-related course description (or at least title)?
2) How can we check that digital-campus.net is related to Digital Campus school? There is a website of Ecole de commerce at www.digital-campus.net, which seems to be a different organization.
Thank you!

**Comment by drashka** [comment]
Hello,
1) In this page http://www.digital-campus.fr/formation/mastere, the details of programs tell about development part of the cursus, particularly front and back web development
2) The file's attach is a screenshot of scholarship certificate which links website .fr and website .net. I can send you this pdf by email.
Thanks for your answer.
Math
screenshot-dc

**Comment by philipto** [comment]
@drashka Thank you for the clarification! Pull request merged.

**Comment by drashka** [comment]
@philipto Thank you :)

**Pull request merged**
