### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ralexrivero**
add named file for uy/edu extension email

### CODE REVIEW

**Comment by ralexrivero** [comment]
https://ceibal.edu.uy/
https://jovenesaprogramar.edu.uy/

**Comment by philipto** [comment]
@ralexrivero First stage of verification passed, official domain is [ceibal.edu.uy](https://ceibal.edu.uy) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by ralexrivero** [comment]
That sounds great! Thanks!

**Comment by philipto** [comment]
@ralexrivero Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by ralexrivero** [comment]
Awesome!

**Pull request merged**
