### PR TITLE
Add Shanghai Astronomical Observatory

### PR DESCRIPTION
**Pull request by jisuoqing**
Add Shanghai Astronomical Observatory, Chinese Academy of Sciences
http://english.shao.cas.cn

### CODE REVIEW

**Comment by philipto** [comment]
@jisuoqing First stage of verification passed, official domain is [shao.ac.cn](https://shao.ac.cn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@jisuoqing I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by jisuoqing** [comment]
@philipto Thanks Philip, however, this domain does exist even if it can not be pinged properly. Actually, all domains under `ac.cn` (where `ac` stands for Chinese Academy of Science, see https://github.com/JetBrains/swot/tree/master/lib/domains/cn/ac) cannot be pinged, while all of these domains have no problem in getting merged.

**Comment by philipto** [comment]
@jisuoqing Thank you for the clarification. Do you have any postgraduate students studying in the observatory? An organization has to study students in order to be eligible for this trusted list.

**Comment by jisuoqing** [comment]
@philipto Thank you Philip for your efforts on this. We do, and for your future reference (which might help), every institution belonging to the Chinese Academy of Sciences (CAS, with websites / emails usually ending with ac.cn or cas.cn) grants degrees of bachelors, master and primarily PhD. 

The name of UCAS (University of Chinese Academy of Sciences) appears on degree certificates, but the actual educating and mentoring students take places in individual institutions of CAS.

**Comment by philipto** [comment]
@jisuoqing I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by philipto** [comment]
@jisuoqing Thank you for the clarifications! I appreciate very much all the details that you described. 

Pull request merged.

Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of this Institute who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to [sales@jetbrains.com](mailto:sales@jetbrains.com).

Thank you!

**Pull request merged**
