### PR TITLE
add universitas 17 agustus 1945 surabaya

### PR DESCRIPTION
**Pull request by hendrorahmat**
official website : http://www.untag-sby.ac.id/
url off page  long-term (>1 year) : http://informatika.untag-sby.ac.id/statis-74-akademik.html
url proof : http://www.untag-sby.ac.id/hubungi-kami.html

### CODE REVIEW

**Comment by philipto** [comment]
@hendrorahmat The page which you have offered as a proof for the domain ownership has contact emails, and all of them end with @untag-sby.ac.id. What is the email domain which you would like to add to this repository? If it is untag.com, where is it mentioned at the website? If it is untag-sby.ac.id, the filename has to be lib/domains/id/ac/untag-sby.txt. 

Please clarify.

**Comment by hendrorahmat** [comment]
what if the file name already exists?

**Comment by philipto** [comment]
@hendrorahmat If it exists already, you can close this request without merging and apply for free JetBrains license at https://www.jetbrains.com/shop/eform/students. If you have any trouble while applying, please send a screenshot with a error message to support@jetbrains.com.

**Comment by hendrorahmat** [comment]
Okay , Thankyou

**Pull request closed without merging**
