### PR TITLE
ST-NICOLAS ( PARIS )

### PR DESCRIPTION
**Pull request by SalvaGhostoff**
ST-NICOLAS.fr , ST-NICOLAS.org

### CODE REVIEW

**Comment by philipto** [comment]
@SalvaGhostoff Please provide us with a proof, which shows that the school recognizes the domain **ST-NICOLAS.fr** that you are submitting as an official email domain for the students.

You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@SalvaGhostoff You might miss my previous comment. Please react.

**Comment by SalvaGhostoff** [comment]
Hello, is there proof of my account connected to Outlook with the screen that shows the name of the school correct?

**Comment by philipto** [comment]
@SalvaGhostoff Thank you for your patience while waiting for a review and processing your request. I found another way to prove the domain ownership.

Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
