### PR TITLE
Added school Future Language School to repo 

### PR DESCRIPTION
**Pull request by AmiirNabil**
added future school email domain to repo.
this school doesn't have a website, however it is very well known in egypt, its registered under the moe.gov.eg domain which is the ministry of education in Egypt.
here is the reference:
https://moe.gov.eg//

### CODE REVIEW

**Comment by AmiirNabil** [comment]
@philipto is there any other steps I should take to this pr?

**Comment by AmiirNabil** [comment]
as I mentioned school doesn't have a domain, however I can provide you with the physical address
which is : 28 Abd Al Sabouar Mohammed Mahdi, Al Amireyah Ash Shamaleyah, Zeitoun, Cairo Governorate 4513111, 
Latitude 30.063602, Longitude 31.323771

school official mail:
1267693@cairo2.moe..edu.eg

**Comment by philipto** [comment]
@AmiirNabil Thank you for your request. The school does not have a website, thus verifying of its eligibility to be added to this repository is difficult. I found the information about the school at https://egyptschools.info/school/%D8%A7%D9%84%D9%85%D8%AF%D8%B1%D8%B3%D8%A9-%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A%D8%A9-%D8%A7%D9%84%D9%85%D8%AA%D9%85%D9%8A%D8%B2%D8%A9-%D9%84%D8%BA%D8%A7%D8%AA-%D8%A7%D9%84%D9%85%D8%B3%D8%AA%D9%82/

The school seems to be for kids aged 5 to 18. They can use PyCharm Community Edition and IntelliJ IDEA Community for their studies. Both are free and don't need a subscription.

Besides, the subdomains of moe.edu.eg  were massively abused in the past, thus I cannot satisfy this request. 

Please try using community versions of the tools. If you need a paid version, please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Comment by AmiirNabil** [comment]
@philipto 
 I have to mention that this license is requested for the school educators (senior teachers educating high school students), I am working on this request on behalf of the school board, is there another way for teachers to request this license using official documents since I really didn't know that unfortunately this domain was massively abused before...

**Pull request closed without merging**
