### PR TITLE
Create ikifp.txt

### PR DESCRIPTION
**Pull request by barbararosa**

### CODE REVIEW

**Comment by philipto** [comment]
@barbararosa Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@barbararosa You might miss my previous comment. Please react.

**Comment by barbararosa** [comment]
Hi, thank you for replay.
below i am providing info you requested

Home page of Institute:
http://www.ik-pan.krakow.pl/

Institut address
ul. Niezapominajek 8 30-239 Kraków, Polska

contacts page with the same domain used
http://www.ik-pan.krakow.pl/Kontakt.43.0.html

the institute's main direction is not IT.

proof of using the email from the official website
http://www.ik-pan.krakow.pl/Szczegoly-profilu.107.0.html?&no_cache=1&tx_profile_pi2[uid]=1428

**Comment by philipto** [comment]
@barbararosa Pull request merged. 
Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of this Institute who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.
Thank you!

**Pull request merged**
