### PR TITLE
Add email domains and university information for current and previous schools

### PR DESCRIPTION
**Pull request by Hetawk**
This pull request adds email domains for students and teachers of the Zhejiang Sci-Tech University and also students of the University of Jinan. It also includes the Chinese and English names of the universities along with their official links in a README file. I am making this pull request because my current and previous universities domains were not added.

### CODE REVIEW

**Comment by Hetawk** [comment]
Title: Add email domains and university information for current and previous schools

This pull request adds email domains for students and teachers from the following universities:

1. University of Jinan (济南大学)
   - Student email domains:
     - `stu.ujn.edu.cn`
     - `stumail.ujn.edu.cn`
     - `mail.stu.ujn.edu.cn`
   - Official website: [https://www.ujn.edu.cn/](https://www.ujn.edu.cn/)

2. **Zhejiang Sci-Tech University (浙江理工大学)**
   - Student email domains:
     - `mails.zstu.edu.cn`
     - `mails.zist.edu.cn`
   - Teacher email domain:
     - `zstu.edu.cn`
   - Official website: [https://www.zstu.edu.cn/](https://www.zstu.edu.cn/)

**Comment by philipto** [comment]
@Hetawk lib/domains/cn/ujn/README.md: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Hetawk Thank you for your request. Regrettably, it contains some items that may not be merged. Others must be grouped.
If the email domains weren't in the stoplist because of being abused in the past, I'd recommend to create a new request for only three domains:
```
ujn.edu.cn
zstu.edu.cn
zist.edu.cn
```
They include all subdomains, thus all domains such as `mails.zist.edu.cn` and `stumail.ujn.edu.cn` will be covered.

The domains mails.zstu.edu.cn and stu.ujn.edu.cn are excluded from trusted list because it has been abused. In order to solve this issue, please send an email to community-support@jetbrains.com.

Before resolving the issue with abused domains we cannot add the domains. Thus, please send an email to community-support@jetbrains.com mentioning this pull request URL `https://github.com/JetBrains/swot/pull/23817`.

I have to close the request without merging.

**Comment by Hetawk** [comment]
Alright, thank you. I'm doing a new pull request using the right format. I also checked the list of abused domains from the [swot](https://github.com/JetBrains/swot/blob/master/lib/domains/abused.txt) repository but I did not see my student domain among the list.

**Pull request closed without merging**
