### PR TITLE
https://graduate.edu.mn/ domain add pull request (GRADUATE UNIVERSITY…

### PR DESCRIPTION
**Pull request by Alex03d**
https://graduate.edu.mn/ GRADUATE UNIVERSITY OF MONGOLIA

Please add the domain of the University.

### CODE REVIEW

**Comment by philipto** [comment]
@Alex03d First stage of verification passed, official domain is [graduate.edu.mn](https://graduate.edu.mn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Alex03d Please provide us with:
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

Thank you.

**Comment by philipto** [comment]
@Alex03d You might miss my previous comment. Please react.

**Comment by Alex03d** [comment]
https://graduate.edu.mn/enrollment/

**Comment by philipto** [comment]
@Alex03d I am sorry, the website looks a stub. Moreover, there are no subjects specified at the website, which imply software development. I have to close this request without merging.

If you need to use JetBrains tools individually as a student, please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Pull request closed without merging**
