### PR TITLE
lib/domains/au/edu/cewa/student.txt

### PR DESCRIPTION
**Pull request by sekiruu**
new domain:
lib/domains/au/edu/cewa/student.txt

### CODE REVIEW

**Comment by eternalapple** [comment]
[file.zip](https://github.com/JetBrains/swot/files/9453927/file.zip)
[ioz.txt](https://github.com/JetBrains/swot/files/9453933/ioz.txt)

**Comment by eternalapple** [comment]
[ioz.txt](https://github.com/JetBrains/swot/files/9454176/ioz.txt)
new domain:
lib/domains/cn/ac/ioz.txt

**Comment by philipto** [comment]
@sekiruu Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

@eternalapple Please create a separate pull request or send an email to community-support@jetbrains.com asking for help.

**Comment by philipto** [comment]
@sekiruu You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@sekiruu I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
