### PR TITLE
Create vanas.txt

### PR DESCRIPTION
**Pull request by pochat**

### CODE REVIEW

**Comment by philipto** [comment]
@pochat Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university

**Comment by pochat** [comment]
Hi Philip,

Here are some links:

Video Game Design
https://www.vanas.ca/career-programs/video-game-design-diploma

FX-TD Program
https://www.vanas.ca/career-programs/effects-animation-diploma

We also have a K12 division where we teach coding in 20+ countries:
https://myfame.org/

Our Educational Partners:
https://myfame.org/fame/educational-partners

Our Accreditations:
https://www.vanas.ca/vanas/accreditation

Thank you.

My work email address is mario@vanas.ca

________________________________________________
*Mario Pochat*  | * Being creative allows us to design better lives.*
www.mariopochat.com  |   Vancouver, Canada

**Comment by philipto** [comment]
@pochat Thank you for the clarification. Pull request merged.

**Comment by pochat** [comment]
Hi Philip,

Do you need anything else from us?  Are we approved as an educational
institution?

thank you.

________________________________________________
*Mario Pochat*  | * Being creative allows us to design better lives.*
www.mariopochat.com  |   Vancouver, Canada

**Comment by philipto** [comment]
@pochat Thank you! No, we don't need anything else. Yes, your institution is approved. Please feel free to request the licenses at jetbrains.com/shop/eform/students.

**Pull request merged**
