### PR TITLE
bisemultan domain

### PR DESCRIPTION
**Pull request by barankhan**

### CODE REVIEW

**Comment by philipto** [comment]
@barankhan First stage of verification passed, official domain is [web.bisemultan.edu.pk](https://web.bisemultan.edu.pk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: http://web.bisemultan.edu.pk/results-10/

**Comment by philipto** [comment]
@barankhan Could you please explain what this organization does? It seems to be a government organization, not an educational one. Why does it need JetBrains licenses?

**Comment by barankhan** [comment]
We are Govt. Educational Non Profit Org. Our Duties are to conduct Examinations and to provide online services to the students. We use JetBrains Licenses to develop the applications to facilitate the students as online service free of cost. We have round about 350k student per year.

**Comment by philipto** [comment]
@barankhan Thank you for the explanation. Regrettably, this kind of use is not considered educational. Please send an email to sales@jetbrains.com and ask for a discount. Your case seems to be somewhat special, because usually similar organization have some kind of financing, such as government grants, etc.

However I have to close this request here without merging. You need to use other type of licensing.
Thank you for your understanding!

**Pull request closed without merging**
