### PR TITLE
Create wyr.txt

### PR DESCRIPTION
**Pull request by wy373226722**
Add University of WaYingKing

### CODE REVIEW

**Comment by zweizwei** [comment]
@wy373226722 the website doesn't seem to belong to any university. If it does, please provide the link to the page, confirming this information. Thanks!

**Comment by wy373226722** [comment]
@zweizwei This is new university. Registration results have just come down.

**Comment by zweizwei** [comment]
@wy373226722 anyway i need some official information that the website belongs to university, otherwise i can't add it. Please provide the relevant page or document. Thanks!

**Comment by wy373226722** [comment]
@zweizwei This is I invests the establishment the new university, also in the construction, very much was now sorry that is unable to provide the information temporarily

**Pull request closed without merging**
