### PR TITLE
Create lsu.txt

### PR DESCRIPTION
**Pull request by liamgluna**
University Official Website: https://www.lsu.edu.ph/
College of Computer Studies, Engineering and Architecture: https://www.lsu.edu.ph/academics/tertiary-education
https://www.lsu.edu.ph/directory

### CODE REVIEW

**Comment by philipto** [comment]
@liamgluna First stage of verification passed, official domain is [lsu.edu.ph](https://lsu.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@liamgluna The official website seems to be not accessible now. I will be back to this request review shortly. I will have to close the request if the website remains not accessible because we need an operation website for eligibility verification.

**Comment by liamgluna** [comment]
@philipto Maybe the server was down. I think due to heavy traffic because we are currently having our enrollment. But the official website is currently working for me.

**Comment by philipto** [comment]
@liamgluna Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
