### PR TITLE
Added Daepyong Middle school

### PR DESCRIPTION
**Pull request by choeminjun**
Middle school website: http://www.daepyong.ms.kr/wah/main/index.htm
Email form: (name goes here)@daepyongm.goe.go.kr
From south korea
Thank you 😄

### CODE REVIEW

**Comment by philipto** [comment]
@choeminjun I am sorry, do you have any high school students who study in the school? Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. 
Also, please give us an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

Thank you!

**Comment by philipto** [comment]
@choeminjun You might miss my previous comment. Please reply.

**Comment by philipto** [comment]
@choeminjun I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Comment by kms0219kms** [comment]
@philipto As I mentioned 2 years ago, the mail services are provided by our government, not school.
If you got some request from Korean students, please remember that the domain could be government's domain and approve it.

@DESECTORCON This PR should be approved. Please reopen it if you still need this domain.

**Pull request closed without merging**
