### PR TITLE
Create manavrachna.txt

### PR DESCRIPTION
**Pull request by sa-gupta**
Please, add Manav Rachna University to the list

### CODE REVIEW

**Comment by DavronovMustafo** [comment]
Please, add Avicenna Tajik State Medical University, to the list

**Comment by philipto** [comment]
@sa-gupta Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@sa-gupta www.ucssittway.edu.mm

**Comment by sa-gupta** [comment]
University official website URL: https://manavrachna.edu.in/university/
University Address: Sector – 43, Aravalli Hills, Delhi – Surajkund Road, Faridabad – 121004, (Haryana), India
B.Tech Computer Science Course URL: https://manavrachna.edu.in/course/b-tech-cse/
Screen Shot of My Account: image

And sorry for replying late

**Comment by philipto** [comment]
@sa-gupta Thank you for your response. Regrettably, the screenshot does not contain any proof as explained above. The domain manavrachna.net WHOIS data do not say that the domain is registered by the university. A contact person for the domain works in a commercial company. 

Thus, I have to close this request without merging. If you are the student of this college, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
