### PR TITLE
Add my school

### PR DESCRIPTION
**Pull request by kbedumn**
Tenger University

### CODE REVIEW

**Comment by philipto** [comment]
@kbedumn First stage of verification passed, official domain is [tenger.edu.mn](https://tenger.edu.mn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@kbedumn Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@kbedumn You might miss my previous comment. Please react.

**Comment by kbedumn** [comment]
> @kbedumn Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

Sorry for late response.
The official website is https://www.tenger.edu.mn.

**Comment by philipto** [comment]
@kbedumn Thank you. Yes, the official website is indeed https://www.tenger.edu.mn.

However I asked you to provide us with **an URL of a page there that shows the university offers an IT-related long-term (>1 year) course.** If the university does not offer any IT-related courses, the domain cannot be added to this repository. 

If the domain is not in this repository, you can still get your free educational subscription. You can do it by applying for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

**Comment by philipto** [comment]
@kbedumn You might miss my previous comment. Please react.

**Comment by kbedumn** [comment]
> @kbedumn Thank you. Yes, the official website is indeed https://www.tenger.edu.mn.
> 
> However I asked you to provide us with **an URL of a page there that shows the university offers an IT-related long-term (>1 year) course.** If the university does not offer any IT-related courses, the domain cannot be added to this repository.
> 
> If the domain is not in this repository, you can still get your free educational subscription. You can do it by applying for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

@philipto 

May I reapply after website is ready? Currently it is under consruction state.

**Comment by philipto** [comment]
@kbedumn Certainly, you can reapply later when the website is ready. In the meantime, please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request now without merging.

Thank you for your understanding!

**Pull request closed without merging**
