### PR TITLE
Add Promeo  and ITII Picardie e-mail addresses. 

### PR DESCRIPTION
**Pull request by N2oo**
Hi, this is a pull resquest to add my school to the ones that you include to your student program.
Here is their website : https://www.itii-picardie.fr/
If you don't understand why does the domain is **Promeo** this is because ITII is undergoing PROMEO as you could see in the footer of their website. Here is the website of promeo. http://www.promeo-formation.fr/nos-centres/beauvais

Thank you for your reading.

### CODE REVIEW

**Comment by philipto** [comment]
@N2oo Could you please:
1. Explain what is PROMEO
2. Provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

Thank you!

**Comment by philipto** [comment]
@N2oo You might miss my previous comment. Please react.

**Comment by N2oo** [comment]
Thank you i just seen it, i'll gather infos you require and tag you as soon as i got it. 😊

**Comment by philipto** [comment]
@N2oo I am sorry, this request remains unanswered for too long. I have to close it. Please reopen or make a new request as soon as you have an update regarding the above-mentioned matter.

**Pull request closed without merging**
