### PR TITLE
Create hunschool

### PR DESCRIPTION
**Pull request by legosail**
Official website url: 
http://hunschool.org

Url with 1 year Ap comp-sci courses: 
https://www.hunschool.org/page/upper-school-course-descriptions?fromId=190301&LevelNum=1204&DepartmentId=23091

Proof email address is used: 
https://imgur.com/a/WIt9wa7
(Found at the bottom of hunschool.org)

### CODE REVIEW

**Comment by philipto** [comment]
@legosail Please rename lib/domains/org/hunschool to lib/domains/org/hunschool.txt. Please notice that .txt extension is mandatory

**Comment by legosail** [comment]
@philipto Done!

**Comment by philipto** [comment]
@legosail Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by legosail** [comment]
@philipto Great! Thank you!

**Pull request merged**
