### PR TITLE
Add @ivey.ca

### PR DESCRIPTION
**Pull request by nobodyrandom**

### CODE REVIEW

**Comment by nobodyrandom** [comment]
https://www.ivey.uwo.ca/

**Comment by philipto** [comment]
@nobodyrandom Could you please rename lib/domains/ca/ivey to lib/domains/ca/ivey.txt? The .txt extension is mandatory in this repository. Also, you may wish to correct spelling in the description of the school, which now says "Ivey Busines School". You can actually keep it untouched if you think that there is no typo there. Thank you!

**Comment by nobodyrandom** [comment]
@philipto The university name is correct

Thanks

**Comment by philipto** [comment]
@nobodyrandom Pull request merged. Thank you!

**Pull request merged**
