### PR TITLE
Added Lion-Feuchtwanger-Gymnasium Munich

### PR DESCRIPTION
**Pull request by chris246**

### CODE REVIEW

**Comment by chris246** [comment]
School's website: http://www.lfg.musin.de/
Please compare to request: https://github.com/JetBrains/swot/pull/153

**Comment by zweizwei** [comment]
@chris246 i see that the website of the school is http://www.lfg.musin.de/ so the path should be 
de/musin/lfg.txt - please fix

**Comment by chris246** [comment]
@zweizwei Yes, but musin uses a different domain for emails: <user>@<school>.muenchen.musin.de
In our case <school> is 'lfg'

**Comment by zweizwei** [comment]
@chris246 thanks, adding the domain

**Pull request merged**
