### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by NimaTorbati**
Hello, dear JetBrains team. I have added the name of my university to the list. Please confirm. All the best.

### CODE REVIEW

**Comment by philipto** [comment]
@NimaTorbati Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@NimaTorbati You might miss my previous comment. Please react.

**Comment by NimaTorbati** [comment]
Dear Philip, thank you for your comment. I have requested the required information from the university and will get back to you as soon as I receive it. Thank you in advance for your patience. All the best.

**Comment by philipto** [comment]
@NimaTorbati Thank you for your patience while waiting for a review and processing your request. Pull request merged. Please start applying for JetBrains educational subscription at https://www.jetbrains.com/shop/eform/students **in an hour, to allow the changes to propagate through JetBrains systems**.

**Comment by NimaTorbati** [comment]
Dear Philip,Thank you for your response and for accepting our request to use the professional version of the Pycharm with our university email addresses. All the best, Nima

**Pull request merged**
