### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by OnBecomingDataScientist**
Here is my email from my university. If there is information needed, please inform me so I can submit it ASAP.
the official university domain is: https://ajc.hcma.vn/ or it can go by: https://ajc.edu.vn/

### CODE REVIEW

**Comment by KiraBobyleva** [comment]
Hi @OnBecomingDataScientist,

Please provide us with:
- the school street address, including city and country
- a URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you!

**Comment by OnBecomingDataScientist** [comment]
- Address: 36 Xuân Thủy, Dịch Vọng Hậu, Cầu Giấy, Hà Nội (36 Xuan Thuy
Street, Dich Vong Hau Ward, Cau Giay District, Hanoi, Vietnam)
- Unfortunately, my school doesn't provide any IT-related-course. This is a
bit disheartening since I'm currently on my self-learning journey, but yea,
thank you guys for a really cool community, I did learn a lot from github.
- Since I can't find official documents in English to prove it, here is
some pictures to prove it:

*google search.jpg*: First result (which is from my school's library
domain) shows that the official domain is ajc.edu.vn
And that text display can be literally translated into:

NOTIFICATION. The digital library only serves readers of the Academy of
Journalism and Communication.
To view full-text documents, an account must be registered. Readers send
personal information (Full name, Faculty (Class), Student ID, phone number,
email @ajc.edu.vn issued by the Academy) via email:
***@***.***

*hoc vien.jpg*: You can see my school's name right above my email
*login to microsoft.jpg*: In the background is my school, if you type
***@***.*** the background will turn out to be like that

Thank you for your time!

**Comment by KiraBobyleva** [comment]
Hi @OnBecomingDataScientist, thank you for reaching out. I'm sorry, but I have to close the pull request without merging as your school doesn't provide any IT-related-courses.

Alternatively, you could use 30-day trial versions or community versions of our tools.

**Comment by OnBecomingDataScientist** [comment]
Thank you1

**Pull request closed without merging**
