### PR TITLE
Added Cork College of Commerce

### PR DESCRIPTION
**Pull request by MeijisIrlnd**
Link to site: https://corkcollegeofcommerce.ie/

### CODE REVIEW

**Comment by asdqwe227** [comment]
Please add my college
[file.zip](https://github.com/JetBrains/swot/files/5268746/file.zip)

**Comment by philipto** [comment]
@MeijisIrlnd Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by MeijisIrlnd** [comment]
@philipto 
120227176_335722454344902_8641497823729524288_n

Apologies for sideways picture, phone cameras be like that sometimes

**Comment by philipto** [comment]
@MeijisIrlnd Thank you for the clarification. Pull request merged.

**Comment by asdqwe227** [comment]
priem@kraskrit.ru - mail college
http://www.kraskrit.ru/index.php - site college

**Pull request merged**
