### PR TITLE
adding the CAU to list of uzb universities

### PR DESCRIPTION
**Pull request by bobir01**
This pull request has been made by CS student/Ex-UTA
For purpose of adding CAU university to list of verified universities
Thank you

### CODE REVIEW

**Comment by philipto** [comment]
@bobir01 First stage of verification passed, official domain is [centralasian.uz](https://centralasian.uz) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by bobir01** [comment]
@philipto Thank you very much.
Just wondering how much would it take for final decision?

**Comment by bobir01** [comment]
@philipto good part of the day
Is there something/document missing for verification?
We are just about to start new semester, it could really help us if we could start it with JetBrains support!

**Comment by philipto** [comment]
@bobir01 This request is a duplicate to #19657. Thus, I have to close it without merging. You already can request your free license at https://www.jetbrains.com/shop/eform/students

Thank you.

**Pull request closed without merging**
