### PR TITLE
Create lnct

### PR DESCRIPTION
**Pull request by amitgcse**
Lakshmi Narain College of Technology (LNCT), Bhopal is a college in Bhopal City of Madhya Pradesh state of India. Now it has been upgraded to LNCT Group of colleges.

### CODE REVIEW

**Comment by philipto** [comment]
@amitgcse lib/domains/in/ac/lnct: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by amitgcse** [comment]
The domain of the college is lnct.ac.in
I have changed the name of the text file from lnct to lnct.txt
Please consider pulling the PR, or guide through if any further change is required.

**Comment by philipto** [comment]
@amitgcse lib/domains/in/ac/lnct: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@amitgcse First stage of verification passed, official domain for **Lakshmi Narain College of Technology (LNCT), Bhopal** is [lnct.ac.in](https://lnct.ac.in) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@amitgcse Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
