### PR TITLE
Create Amolf

### PR DESCRIPTION
**Pull request by SvenNederhoff**
amolf
Institution URL: https://amolf.nl/

### CODE REVIEW

**Comment by philipto** [comment]
@SvenNederhoff Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school.

**Comment by philipto** [comment]
@SvenNederhoff You might miss my previous comment. Please reply.

**Comment by SvenNederhoff** [comment]
@philipto Right excuse me, 
its not directly an IT-related courses but we are a Research facility a part of NWO (The Netherlands Organization for Scientific Research )  which are using python to make scientific calculations.

I didn't know it must be an IT related School. Because Amolf isn't IT related but scientific. Feel free to close, 

more info: https://en.wikipedia.org/wiki/AMOLF

**Comment by philipto** [comment]
@SvenNederhoff Thank you for the update. I have to close the request without merging. You can email sales@jetbrains.com to get an appropriate academic discount, there is a discount system for research organizations. If you teach students in any IT-related areas, including physics, biology and bioinformatics, the student are still eligible for a free license, and they can apply with their photo ID at https://jetbrains.com/student ("Official document" tab). Thank you for the understanding!

**Pull request closed without merging**
