### PR TITLE
Adding kgsu to domain tree

### PR DESCRIPTION
**Pull request by nikonoff16**
http://www.kgsu.ru/ - an official cite of my university. It differs from my university mail domain because the university just created a new way to communicate with students through MS Teams.

### CODE REVIEW

**Comment by philipto** [comment]
@nikonoff16 I am sorry, there is no MS Team dedicated address mentioned at the university website. Could you please provide us with a proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by nikonoff16** [comment]
Thanks for watching my pull request. I have requested the document from my University. When they give it to me (or do not give) I will send their answer to you.

**Comment by DazmaLab** [comment]
Hello, where do you need to send documents?

**Comment by philipto** [comment]
@nikonoff16 @DazmaLab Please attach a copy of a document to your comment here at GitHub via web interface. Do NOT email the copy, please.

**Comment by DazmaLab** [comment]
I am the admin of kgsu.ru, and kgsu.onmicrosoft.com. Microsoft gives free licenses for educational institutions (Office 365 A1). We do not have documents supporting the subdomain of kgsu.onmicrosoft.com. I can provide screenshots and send from the main domain.

**Comment by philipto** [comment]
@nikonoff16 @DazmaLab Thank you very much for the clarification. Pull request merged.

**Comment by nikonoff16** [comment]
Thanks a lot! Learn knew stuff will be much easier and funny now! You're doing great things))

**Pull request merged**
