### PR TITLE
Add Turku schools with edu mail addresses

### PR DESCRIPTION
**Pull request by MikkoPeltonen**
Most higher education schools in Turku have a domain of edu.turku.fi

### CODE REVIEW

**Comment by zweizwei** [comment]
we only add the domains of educational institutions, not governmental domains (due to the further automatic access - we need to make sure that only educational staff / students may get the access). Therefore please provide the domain(s) of the universities you wish to add. Thank you.

**Comment by MikkoPeltonen** [comment]
@zweizwei Only teachers and students have edu.turku.fi email domains.

**Comment by zweizwei** [comment]
@MikkoPeltonen could you please provide a relevant document / page / screenshot, confirming this information?

**Comment by MikkoPeltonen** [comment]
@zweizwei Here is a help page regarding the student email addresses. http://edu.turku.fi/tvt/sahkoposti.html

**Comment by zweizwei** [comment]
@MikkoPeltonen thanks a lot for the provided link - that's exactly the information i needed. I'll now add the domain.

**Pull request merged**
