### PR TITLE
Create gymnasiumkladno

### PR DESCRIPTION
**Pull request by Level3301**

### CODE REVIEW

**Review by CrazyJannis44 — APPROVED** [review]

**Comment by philipto** [comment]
@Level3301 lib/domains/cz/gymnasiumkladno: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Level3301 Pull request merged. I changed it for you to make it correct. Thank you!

**Comment by Level3301** [comment]
> @Level3301 Pull request merged. I changed it for you to make it correct. Thank you!

Thank you!

**Comment by Level3301** [comment]
Hi, I forgot to say thank you. I started using PhpStorm and it worked so I
didn't pay attention to who did it.
It has been an awesome 2 years of programming for me and I learned a lot.
So I just wanted to thank you for what you did for me. :)
Kind regards,
Filip

**Pull request merged**
