### PR TITLE
add isjlalouviere-ac

### PR DESCRIPTION
**Pull request by NextSap**

### CODE REVIEW

**Comment by philipto** [comment]
@NextSap Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@NextSap You might miss my previous comment. Please react.

**Comment by NextSap** [comment]
Hello.
- My school's website : http://www.isjlalouviere.be/
- Here you can see timetables who proofs that my school delivers IT courses http://www.isjlalouviere.be/up/article/6a01459529e4c7f21c49dca7e796b6b6.pdf
- For your last request I'm a bit confused. I don't know how to proof that.

**Comment by philipto** [comment]
@NextSap Thank you for clarification!

Simple request at Google, like this, usually shows that the email domain is mentioned at the official website:
> "isjlalouviere-ac.be" +site:www.isjlalouviere.be

However, in this case isjlalouviere-ac.be email domain is not mentioned at the official website. 
WHOIS database in Belgium does not show that the domain belongs to the school: https://www.dnsbelgium.be/en/whois/info/isjlalouviere-ac.be/details

Please attach a copy of an instruction which you were given by the school, which tells you to use this email address. You can also comment here with a link that instructs the students to use their addresses @isjlalouviere-ac.be.

**Comment by NextSap** [comment]
[Proof.pdf](https://github.com/JetBrains/swot/files/5684539/Proof.pdf)

Here are the instructions my school gave me.
I vonluntary hide some personal informations like my last name (orange), my license code (blue) or my password (gray).

isjlalouviere-**ac**.be -> **ac** because the school uses the plaform "**A**ccès-**C**ible".

Thanks in advance.

**Comment by philipto** [comment]
@NextSap Thank you for the clarification. Pull request merged.

**Pull request merged**
