### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Nay78**
@ua.cl is a domain for students in Antofagasta's University (UA).

http://www.uantof.cl/
http://admision.uantof.cl/carreras.html
https://outlook.office365.com/owa/?realm=ua.cl#vd=webmail

### CODE REVIEW

**Comment by philipto** [comment]
@Nay78 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@Nay78 You might miss my previous comment. Please react.

**Comment by Nay78** [comment]
Hello. Sorry about the delay. I'm currently reaching out to someone in my university to check if there's an official page so that the domain can be checked in the most clear way.

At the moment I have the following links:

Post from the university's press that talks about the new domain.
http://www.comunicacionesua.cl/2015/06/15/ua-implementara-cuentas-de-correo-institucional-para-alumnos-de-primer-ano/

@uantof.cl is for teachers and officials, though some assistants get the @ua.cl domain too, as seen in the following link.
http://gestiondocente.uantof.cl/equipo/

**Comment by philipto** [comment]
@Nay78 Thank you for the clarification. Pull request merged.

**Pull request merged**
