### PR TITLE
Create zstchelm.txt

### PR DESCRIPTION
**Pull request by NoNamedCobble**

### CODE REVIEW

**Comment by philipto** [comment]
@NoNamedCobble The official website of this school is https://zst.chelm.pl/
Could you please tell us what is their students email address pattern? Is it username@zst.chelm.pl?

**Comment by NoNamedCobble** [comment]
> @NoNamedCobble The official website of this school is https://zst.chelm.pl/
> Could you please tell us what is their students email address pattern? Is it username@zst.chelm.pl?


username@zstchelm.pl

**Comment by NoNamedCobble** [comment]
username@zstchelm.pl

pon., 5 paź 2020, 18:00 użytkownik Philip Torchinsky <
notifications@github.com> napisał:

**Comment by philipto** [comment]
@NoNamedCobble Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by NoNamedCobble** [comment]
How can I confirm this? Im only student

pon., 5 paź 2020, 18:08 użytkownik Philip Torchinsky <
notifications@github.com> napisał:

**Comment by philipto** [comment]
@NoNamedCobble You can find a page at the official website which says that the university gives to the students the email addresses in this domain. You can upload a copy of a written instruction where the university says that. You can find an email from university officials from the official address where the university informs you about your new student email address. You can find a paper which is published by a student or a teacher in a peer-reviewed journal with a good reputation, where the email address is mentioned next to the author. Other official proofs also work. Thank you.

**Comment by NoNamedCobble** [comment]
I have a screenshot of a message from the class teacher in which she sent the students' emails

**Comment by philipto** [comment]
@NoNamedCobble Thank you for the clarification. Pull request merged.

**Pull request merged**
