### PR TITLE
Create bs-wangen.txt

### PR DESCRIPTION
**Pull request by ReissBSW**
New School Domain added

### CODE REVIEW

**Comment by philipto** [comment]
@ReissBSW I am sorry for a delay with processing your request. 

In order to be added to this repository a university or a college has to have long-term (> 1 year) courses related to IT. Could you please comment with the address of an official page confirming that Berufliches Schulzentrum Wangen does have long-term courses related to informational technologies? I was not able to find it on the official website.

**Comment by ReissBSW** [comment]
Dear Philip,

 

 

We are a school for job trainings in Germany and more. Our students learn to program Java and C. As a Cisco Networking Academy we also offer courses in computer hardware and networking technology.

 

Last year we merged with a school in our neighborhood. So the Cisco Networking Academy still runs under the former title of the two schools: “Friedrich Schiedel Schule” and “Kaufmännische Schulen Wangen”

 

Perhaps you can find some more information about us at Cisco under these terms. Here is a link with the Cisco Network Academies in our region. In this list the “Friedrich Schiedel Schule” is listed. When you follow the link below this item you will be forwarded to our website.

https://www.google.com/maps/d/viewer?mid=zTiA7gOJEWo0.k_4FTWZY8dQI <https://www.google.com/maps/d/viewer?mid=zTiA7gOJEWo0.k_4FTWZY8dQI&hl=de> &hl=de

 

Due to the fact that we got a new name we also got a new website. This website is still growing and the information about our IT-projects is still missing.

 

On the following site you can see that a part of our students get the general qualification for university entrance. We offer these courses now for many years.

http://www.bs-wangen.de/schularten-detail/technisches-gymnasium/

 

Here is the link to the official curriculum that we have to comply with.

http://www.ls-bw.de/bildungsplaene/beruflschulen/bg/bg_berufsbezogen/Oberstufe/TG/Computertechnik-LPH-1-2011_11_3787_01.pdf

 

 

Up to now we use NetBeans for Java programming and a small editor for C programming. We only use C programming for programming Arduino controller. In future we want to program some Android-Apps with our students. For this project we would like to use PhpStorm. We also want to substitude NetBeans with PhpStorm.

 

I hope I could dispel your doubts.

 

Best regards

 

Horst

 

 

-- 

Berufliches Schulzentrum Wangen

Horst Reiß

Jahnstraße 6

88239 Wangen

 

Tel: 07522 / 7073 - 0

Fax: 07522 / 7073 -118

Mail: reiss@bs-wangen.de

 

Von: Philip Torchinsky [mailto:notifications@github.com] 
Gesendet: Mittwoch, 10. Februar 2016 19:20
An: JetBrains/swot
Cc: ReissBSW
Betreff: Re: [swot] Create bs-wangen.txt (#1609)

 

@ReissBSW <https://github.com/ReissBSW>  I am sorry for a delay with processing your request. 

In order to be added to this repository a university or a college has to have long-term (> 1 year) courses related to IT. Could you please comment with the address of an official page confirming that Berufliches Schulzentrum Wangen does have long-term courses related to informational technologies? I was not able to find it on the official website.

**Comment by philipto** [comment]
@ReissBSW Thank you for the clarification! You pull request is now merged.

**Comment by ReissBSW** [comment]
Dear Philip,

 

thank you for your support.

 

Best regards from Germany

 

Horst

 

-- 

Berufliches Schulzentrum Wangen

Horst Reiß

Jahnstraße 6

88239 Wangen

 

Tel: 07522 / 7073 - 0

Fax: 07522 / 7073 -118

Mail: reiss@bs-wangen.de

 

Von: Philip Torchinsky [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Februar 2016 13:34
An: JetBrains/swot
Cc: ReissBSW
Betreff: Re: [swot] Create bs-wangen.txt (#1609)

 

@ReissBSW <https://github.com/ReissBSW>  Thank you for the clarification! You pull request is now merged.

**Pull request merged**
