### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Uros-Katanic**
Adding file for school required for the educational license.

### CODE REVIEW

**Comment by philipto** [comment]
@Uros-Katanic file/lib/domains/me/edu/ets-pg.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Uros-Katanic Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by Uros-Katanic** [comment]
School website: https://elektropg.online/ets/

School Street: Vasa Raičkovića br 26,city Podgorica 81000

All the users in my class on the excel table with school e mails made by
our ICT coordinator

On our school website there is all years classes courses and everything
that can only be processed with username and password

Hope that's all you need,
Sincerely,
Uroš Katanić

**Comment by philipto** [comment]
@Uros-Katanic Thank you! This domain is already in the trusted list. I close the request as a duplicate.

**Pull request closed without merging**
