### PR TITLE
Create zsek.txt

### PR DESCRIPTION
**Pull request by AnonymousX86**

### CODE REVIEW

**Comment by philipto** [comment]
@AnonymousX86 Please provide us with an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by AnonymousX86** [comment]
I'm not sure if it will do the job, but here's screenshot of my school Gmail. Of course all names are hidden.
Screenshot_2

**Comment by AnonymousX86** [comment]
@philipto is the screenshot sufficent evidence?

**Comment by philipto** [comment]
@AnonymousX86 I am sorry, this is not actually a best proof. If you can find a page or a document made by the school which says that students can use addresses from this domain it is much better. Thank you.

**Comment by philipto** [comment]
@AnonymousX86 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
