### PR TITLE
Verify and supplement VNU University of Social Sciences and Humanities

### PR DESCRIPTION
**Pull request by ATU-Github-PC-AOC**
Verify and supplement VNU University of Social Sciences and Humanities, in order to license JetBrains tool for free to students and teachers of the school.

### CODE REVIEW

**Comment by ATU-Github-PC-AOC** [comment]
@philipto

**Comment by ATU-Github-PC-AOC** [comment]
https://ussh.vnu.edu.vn/

image

**Comment by ATU-Github-PC-AOC** [comment]
For more information, my school's email has the following format XXYYZZZZ@sv.ussh.edu.vn. Example 20032318@sv.ussh.edu.vn

**Comment by philipto** [comment]
@ATU-Github-PC-AOC I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host ussh.vn not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by philipto** [comment]
@ATU-Github-PC-AOC I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host ussh.vn not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Pull request closed without merging**
