### PR TITLE
Add School Name

### PR DESCRIPTION
**Pull request by its-Shubham**

### CODE REVIEW

**Comment by philipto** [comment]
@its-Shubham Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by its-Shubham** [comment]
@philipto  here are the required details, if anything else is required then please do tell me, i will try my best to provide you the required information.
- The official website URL is -> https://vipstc.edu.in/
- Address : Outer Ring Rd, AU Block, Ranikhet, Pitampura, New Delhi, Delhi, 110034, India
- long term course URL :  https://vipstc.edu.in/vsit/Programmes/MCA
- Email Id of my Professor through which it can be verified that the domain i am submitting belongs to the school: deepali_kamthania@vipsedu.in

**Comment by philipto** [comment]
@its-Shubham Thank you for clarifications and your patience while waiting for a review and processing your request. Pull request merged.

I removed personal information from your comment to respect privacy.

**Comment by its-Shubham** [comment]
Thank you @philipto .

**Pull request merged**
