### PR TITLE
Adding in the Education Group Academic email address domain

### PR DESCRIPTION
**Pull request by chasehsbrk**
University Url:
https://www.cti.ac.za/

BScIT 3 year degree:
https://www.cti.ac.za/course/bachelor-of-science-in-information-technology-cti/

Proof of domain use (screenshot): 
https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/209351/3997633/5OveTq25PvYLtnE/Screen%20Shot%202016-08-25%20at%204.17.08%20PM.png

### CODE REVIEW

**Comment by philipto** [comment]
@chasehsbrk If you wish to add @cti.ac.za domain, the file path for it shall be `lib/domains/za/ac/cti.txt`. Please update the path in the request accrodingly. Thank you!

**Comment by philipto** [comment]
@chasehsbrk You might miss my previous comment. Please update the path as described above. Thank you!

**Comment by chasehsbrk** [comment]
@philipto we would want to rather add the @educationgroup.co.za domain as that is the email domain used by the university aforementioned, please refer to the screenshot that has been attached as proof of the use of the educationgroup domain

Kind Regards and thanx for the support

**Comment by philipto** [comment]
@chasehsbrk Thank you for the clarification!. To add educationgroup.co.za domain, please rename the file from `lib/domains/za/co/educationgroup/CTI Education Group.txt ` to `lib/domains/za/co/educationgroup.txt`. Thank you!

**Comment by chasehsbrk** [comment]
@philipto Thank you for the assistance in this regard, the changes have been made as requested

**Comment by philipto** [comment]
@chasehsbrk Thank you! Pull request merged.

**Comment by chasehsbrk** [comment]
@philipto Thanx a million man

**Pull request merged**
