### PR TITLE
Added GWSP

### PR DESCRIPTION
**Pull request by MrChromInSky**
Added file for Górnośląska Wyższa Szkoła Przedsiębiorczości im. Karola Goduli

### CODE REVIEW

**Comment by philipto** [comment]
@MrChromInSky First stage of verification passed, official domain is [gwsp.edu.pl](https://gwsp.edu.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@MrChromInSky Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by philipto** [comment]
@MrChromInSky You might miss my previous comment. Please react.

**Comment by MrChromInSky** [comment]
Apologies for the delay

This may be a slight stretch, but the course is Game Design where nevertheless coding is needed in the development process.
But if you find it insufficient, I will fully understand.

https://www.gwsp.edu.pl/kierunek/gry-i-grafika-interaktywna/

Have a nice day, evening, or a good night

**Pull request merged**
