### PR TITLE
Add al.educacao.sp.gov.br

### PR DESCRIPTION
**Pull request by deudz**
Link: https://www.educacao.sp.gov.br/

### CODE REVIEW

**Comment by philipto** [comment]
@deudz First stage of verification passed, official domain for **E.E. Lúcia de Castro Bueno** is [al.educacao.sp.gov.br](https://al.educacao.sp.gov.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@deudz You might miss my previous comment. Please react.

**Comment by deudz** [comment]
> @deudz Please explain who is the owner of al.educacao.sp.gov.br domain. Does it belong to this school only? If not, how the email addresses in this domain are distributed, and to whom?
> 
> I am looking forward to your reply. Thank you.

Sorry for late reply, but if I'm not mistaken, it belongs to most schools in the São Paulo state.

**Comment by philipto** [comment]
@deudz I am sorry, this domain seems to represent an umbrella institution, not a specific single university or a college. 

If you are the student of this school, please enroll to GitHub Student Developer Pack at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

I have to close the request without merging.

Thank you for the understanding!

**Pull request closed without merging**
