### PR TITLE
Adding Instituto Nuevos Aires (INA)

### PR DESCRIPTION
**Pull request by capellopablo**
Website: https://ina.edu.ar/
Address: Galván 3256, Cdad. Autónoma de Buenos Aires
Tech career: https://ina.edu.ar/tecnicaturas/diseno-y-programacion-web/

INA is the High-Level education of: https://nuevosaires.edu.ar/
We've been using this domain in the past

### CODE REVIEW

**Comment by philipto** [comment]
@capellopablo First stage of verification passed, official domain for **Instituto Nuevos Aires** is [ina.edu.ar](https://ina.edu.ar) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by capellopablo** [comment]
Sure! Thanks

**Comment by philipto** [comment]
@capellopablo Regrettably, I must close the request without merging because this organization is a training center, not a college or university. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot).

Please apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses.

Thank you for your understanding!

**Comment by capellopablo** [comment]
Hey @philipto Sure! I undestard that. Sorry, but that's wrong
I don't know why you think it's a training center, but it's not. It's a college that has all levels: Kindergarten, primary, High School and tertiary. It's a career endorsed by the Ministry of Education of the Argentine Republic. I myself have developed the career plan and have presented it to the Ministry of Education.
In fact, in Argentina, in order to have a .edu domain, you must be a formal educational institution. Training centers are not granted .edu.ar domains.

https://riu.edu.ar/dominios-edu-ar

I would appreciate it if you would review the application because, honestly, the evaluation is not correct.

**Comment by capellopablo** [comment]
@philipto Could you take a look at my last comment, please?

**Pull request closed without merging**
