### PR TITLE
Create novyporg

### PR DESCRIPTION
**Pull request by Mr-Doge**

### CODE REVIEW

**Comment by philipto** [comment]
@Mr-Doge Please rename lib/domains/cz/novyporg to lib/domains/cz/novyporg.txt
Thank you!

**Comment by Mr-Doge** [comment]
@philipto Oh right, fixed by now. Also, noticed porg.txt which is the same, just different place where the school is. (also different email suffix)

**Comment by philipto** [comment]
@Mr-Doge Thank you for the update! Pull request merged.

**Comment by Mr-Doge** [comment]
The apply page still says that the mail is not linked to any school. Does it take some time to refresh or is it something else?

**Comment by Mr-Doge** [comment]
@philipto

**Pull request merged**
