### PR TITLE
Create univ-caen

### PR DESCRIPTION
**Pull request by fredericjurie**
Universite de Caen Normandie
University of Caen Normandy

### CODE REVIEW

**Comment by philipto** [comment]
@fredericjurie lib/domains/fr/univ-caen: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by fredericjurie** [comment]
@philipto I already sent an email to support@jetbrains.com requesting help. Thanks.

**Comment by philipto** [comment]
@fredericjurie lib/domains/fr/univ-caen: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by fredericjurie** [comment]
@philipto Okay I just sent an email with the URL in the message. Thanks.

**Comment by philipto** [comment]
@fredericjurie lib/domains/fr/univ-caen: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by fredericjurie** [comment]
@philipto Any update?

**Comment by philipto** [comment]
@fredericjurie Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by fredericjurie** [comment]
@philipto Attached is a copy of letter from the administration. Thanks.
[lettre-pour-dr-jfurie.pdf](https://github.com/JetBrains/swot/files/9556781/lettre-pour-dr-jfurie.pdf)

**Comment by philipto** [comment]
@fredericjurie Regrettably, this request has signs of fraud. I have to close it without merging.

I do not accept the document that you have attached. It has signs of the official document forgery. Please notice that the forgery may pose a crime in certain jurisdictions.

**Pull request closed without merging**
