### PR TITLE
Create WHS text

### PR DESCRIPTION
**Pull request by Mobkinz78**
Winchester High School
Website: http://www.winchesterps.org
Faculty emails are @winchesterps.org such as teachername@winchesterps.org
Student emails are @wpsstudent.com such as studentname@wpsstudent.com

### CODE REVIEW

**Comment by philipto** [comment]
@Mobkinz78 For the domains which you have mentioned the file path shall be
`lib/domains/org/winchesterps.txt` and `lib/domains/com/wpsstudent.txt` instead of `lib/domains/org/winchesterhs.txt`. Please check the spelling in "winchesterps" - is it "p" before trailing "s", or "h"?
Please modify the request accordingly. One request can contain several files.

**Comment by philipto** [comment]
@Mobkinz78 Also please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by Mobkinz78** [comment]
@philipto Do you mean create multiple files for the two domains separately?

Also, the domain itself is @winchsterps.org, a 'P' before the trailing s (standing for Public Schools). The domains apply to students/teachers at the Public High School, 9th through 12th grade.

**Comment by philipto** [comment]
@Mobkinz78 Yes, you need to have two files with identical content and different file names in this request.
The files are to be: lib/domains/org/winchesterps.txt and lib/domains/com/wpsstudent.txt. If you make it, both domains will become known to our system, and both students and teachers will be able to request free licenses for JetBrains tools.

**Comment by philipto** [comment]
@Mobkinz78 I close this request because I just merged the requests #2572 and #2573 according the discussion above. Thank you!

**Pull request closed without merging**
