### PR TITLE
Create itivoltativoliguidonia.txt

### PR DESCRIPTION
**Pull request by ProfGallo**
[Accr_ENGLISH.pdf](https://github.com/JetBrains/swot/files/4778674/Accr_ENGLISH.pdf)
[diploma_all_Optimized.pdf](https://github.com/JetBrains/swot/files/4778677/diploma_all_Optimized.pdf)

image
image
screenshot_mail_gsupport

### CODE REVIEW

**Comment by ProfGallo** [comment]
G-Suite domain for education itivoltativoliguidonia.net created only for students and teachers mail inside official website https://itivolta.edut.it
Thank you so much for take care our request

**Comment by ProfGallo** [comment]
Any news?

**Comment by philipto** [comment]
@ProfGallo I am sorry, we have to double check the documents which you have provided us with. Doesn't the university mention this email domain somewhere in the official papers or at the official website?

**Comment by ProfGallo** [comment]
I'm sorry,
Follow this link for family information about G-Suite https://www.itivolta.edu.it/g-suite-for-eeducation/
and this link for the teachers https://www.itivolta.edu.it/google-suite-2/
I hope this is enough
Thank you

**Comment by ProfGallo** [comment]
@philipto Are there any other issues to solve??

**Comment by philipto** [comment]
@ProfGallo Thanks a lot for the clarifications! The links 
> Follow this link for family information about G-Suite https://www.itivolta.edu.it/g-suite-for-eeducation and this link for the teachers https://www.itivolta.edu.it/google-suite-2/

has helped a lot. Pull request merged. Teachers and students of your school can request their free license at https://www.jetbrains.com/shop/eform/students from now on. Please start requesting the licenses in about an hour, to let the changes to propagate through JetBrains' system.

**Comment by ProfGallo** [comment]
Thanks, Thanks, Thanks,

I'm very very happy for my students😂😂👍
Il 18/06/2020 15:51:56, Philip Torchinsky <notifications@github.com> ha scritto:
@ProfGallo [https://github.com/ProfGallo] Thanks a lot for the clarifications! The links
Follow this link for family information about G-Suite https://www.itivolta.edu.it/g-suite-for-eeducation [https://www.itivolta.edu.it/g-suite-for-eeducation] and this link for the teachers https://www.itivolta.edu.it/google-suite-2/ [https://www.itivolta.edu.it/google-suite-2/]
has helped a lot. Pull request merged. Teachers and students of your school can request their free license at https://www.jetbrains.com/shop/eform/students [https://www.jetbrains.com/shop/eform/students] from now on. Please start requesting the licenses in about an hour, to let the changes to propagate through JetBrains' system.

**Pull request merged**
