### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by himanshutank2179**
I have added my collage, please review it and approve.

### CODE REVIEW

**Comment by philipto** [comment]
@himanshutank2179 jmpaneracollege.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@himanshutank2179 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@himanshutank2179 jmpaneracollege.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@himanshutank2179 I renamed the file for you to reflect the naming convention for this repository. Pull request merged. Thank you!

**Comment by himanshutank2179** [comment]
Thank you

**Pull request merged**
