### PR TITLE
Create ausbildungswolken

### PR DESCRIPTION
**Pull request by Yuhbee**
Please ask for questions.
Uwe Bauermann

### CODE REVIEW

**Comment by philipto** [comment]
@Yuhbee Please provide us with a proof that:
1) The institution which has an official website https://www.albbw.de recognizes ausbildungswolken.de as an official domain for its students
2) Nobody except the students and teachers of Annedore-Leber-Berufsbildungswerk Berlin possess email with a patter username@ausbildungswolken.de 
It is not obvious from the materials on the website.
Thank you!

**Comment by Yuhbee** [comment]
Hello @philipto 

ok. i understand.
Since 2008 i'm a fulltime teacher/instructor/training supervisor at ALBBW
i have had made a request for https://www.albbw.de, also.
And now i see, i made a mistake, used a wrong branch :-( 
  https://github.com/leereilly/swot/pull/1879

I have to made new request? (on JetBrains/swot),
or can you "extract" my request from there?

sorry my english, its not my native language.
ausbildungswolken de, is our e-learning platform, i went happy if a can use both domains for registering.
- username@ausbildungswolken.de
and 
- username@albbw.de (preferred if only one of them is possible)

i have testet many IDE's for programming in the past.
The JetBrains Suites are good or better as others.
I would use it for, and with my students, and for my lectures.

Im new at using "git", but practice it last 4 days. I'm goin in "love" with it. Its verry interesting and usefull, cool!

Thanks for your time and effort.
Greets from Berlin, sincerely
Uwe Bauermann

**Comment by Yuhbee** [comment]
Hi @philipto 

is this still alive?
sorry if it seems to being on the edge, but im on vacation this week.
I have mind to try this.
Thnx Uwe

**Comment by philipto** [comment]
@Yuhbee Yes, it's alive. I merged the request, corrected the filename and added albbw.de to the list. Please wait at least an hour after this message is sent, before start requesting the licenses at https://jetbrains.com/student. Thank you!

**Pull request merged**
