### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by mirajmv**
Add ptu16 Mala Vyska

### CODE REVIEW

**Comment by philipto** [comment]
@mirajmv Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school

**Comment by philipto** [comment]
@mirajmv You might miss my previous comment. Please react.

**Comment by mirajmv** [comment]
Sorry. We provide general secondary education, this includes 2 years of computer science education.

**Comment by philipto** [comment]
@mirajmv Thank you for the clarification. Pull request merged.

**Pull request merged**
