### PR TITLE
Add files via upload and add my school

### PR DESCRIPTION
**Pull request by epicose**
I hope this works, i just want to add my school.

### CODE REVIEW

**Comment by KidsCanProgram** [comment]
Add my college
[ashadevipolytechnic.txt](https://github.com/JetBrains/swot/files/6603799/ashadevipolytechnic.txt)

**Comment by KidsCanProgram** [comment]
[Uploading ashadevipolytechnic.txt…]()

**Comment by philipto** [comment]
@epicose Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

@KidsCanProgram Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new **separate** request with correct information. Thank you for the understanding!

**Comment by epicose** [comment]
School website: https://www.nordangliaeducation.com/our-schools/malaysia/kuala-lumpur/british-international
School adress: No.1, Changkat Bukit Utama, Bandar Utama, 47800 Petaling Jaya, Selangor, Malaysia
Subject website (course: A level & iGCSE Computer science (2 years)) : https://www.nordangliaeducation.com/our-schools/malaysia/kuala-lumpur/british-international/learning/our-curriculum/sixth-form/subjects

**Pull request closed without merging**
