### PR TITLE
Add new academialuisvives.com

### PR DESCRIPTION
**Pull request by tekbreak**
https://www.academialuisvives.com

Long-term IT Course: https://www.academialuisvives.com/educacion/reactjs/

### CODE REVIEW

**Comment by philipto** [comment]
@tekbreak First stage of verification passed, official domain is [academialuisvives.com](https://academialuisvives.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@tekbreak Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@tekbreak You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@tekbreak I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by tekbreak** [comment]
I am so sorry I have been very busy. Please find a couple of courses in:
https://www.academialuisvives.com/educacion/angular
https://www.academialuisvives.com/educacion/reactjs

Please tell me if you need further information.

Thanks

**Pull request closed without merging**
