### PR TITLE
Create bcs

### PR DESCRIPTION
**Pull request by sahan93knightz**
Create British Computer Society

### CODE REVIEW

**Comment by philipto** [comment]
@sahan93knightz Could you please rename `lib/domains/uk/org/bcs` to `lib/domains/uk/org/bcs.txt` to reflect this repository rules? Thank you!

**Comment by sahan93knightz** [comment]
@philipto I renamed the `lib/domains/uk/org/bcs` file to `lib/domains/uk/org/bcs.txt`

**Comment by philipto** [comment]
@sahan93knightz I am sorry for not bringing this to your attention earlier, however it's essential to note that this repository contains records for universities and colleges only. I carefully read "About" section on BCS website, and Academy subsection as well, and the problem with adding BCS to this repository is that BCS is not a college, nor a university. BCS is rather broad society of IT professionals, and given that we can not include BCS into this repository.

If BCS has some courses which are taught in classrooms, I appreciate if you request the licenses for the students of the courses by email to classroom@jetbrains.com.

I have to close this request without merging. Please reopen if you have any update or comment regarding BCS status or need help. Thank you for the understanding!

**Comment by DiliniU** [comment]
hi, 
I'm also a student of BCS. Although it is not an university , it provides professional qualifications to IT professionals. According to BCS.org when a student of BCS completed Certificate level, Diploma level, Post Graduation Diploma level and final project it is equal to University degree. 

Given below is the proof for that information. 

 **http://www.insidecareers.co.uk/career-advice/bcs-qualifications-exams/

http://www.bcs.org/category/18013**

Please  reconsider the request again.

With Regards,
Dilini

**Comment by philipto** [comment]
@DiliniU @sahan93knightz Hello. The page you advised me to check says that "The Institute has over 175 registered course providers worldwide". This is exactly why we doubt to add BCS to the repository. However, if you say that you actually study at BCS, I think we can add its email domains to this repository if there is at least one long-term IT-related course which BCS offers to the students. It is not quite common that an institution offers third-party courses only to the students, but it's understandable that if you study at BCS only, you have no other email addresses from other universities, event if BCS offers you a course which is developed by third-party course provider. Do I understand you correctly?

**Comment by DiliniU** [comment]
yes. But course providers are the institutes who are  teach the syllabus
BCS has submitted.  Also I don't have any other university emails, that is
true.

**Comment by DiliniU** [comment]
Here are more information about the course.

http://www.bcs.org/category/18011

Please I really value the Intellij IDEA. That's why I'm asking this so
much.

Thank you.

**Comment by philipto** [comment]
@DiliniU Thank you for your warm words. I agree with you that if BCS submit the syllabus and gives emails to the students, it should be included. Thank you for providing us with additional details. I am merging this request as well as #2365.

**Comment by DiliniU** [comment]
Thank you so much for your effort

**Comment by sahan93iit** [comment]
@DiliniU @philipto Thank you for re-considering the request.

**Pull request merged**
