### PR TITLE
Add pnu university

### PR DESCRIPTION
**Pull request by DunaAlsuliman**

### CODE REVIEW

**Comment by philipto** [comment]
@DunaAlsuliman First stage of verification passed, official domain is [pnu.edu.sa](https://pnu.edu.sa) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@DunaAlsuliman Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by DunaAlsuliman** [comment]
@philipto You can find on the following page the programs offered by my college for each department and their details, please let me know if you need further information.
https://www.pnu.edu.sa/en/Faculties/ComputerScience/Programs_Bachelors_Degree_3Semesters/Pages/default.aspx

**Comment by philipto** [comment]
@DunaAlsuliman Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
