### PR TITLE
Add IES MIRALCAMP

### PR DESCRIPTION
**Pull request by AlinGP4**

### CODE REVIEW

**Comment by AlinGP4** [comment]
web info: [https://portal.edu.gva.es/iesmiralcamp/es/portada/centro/ensenanzas/ciclos](url)
domain for e-mails: iesmiralcamp.org
my studen email: @al044068@iesmiralcamp.org

**Comment by philipto** [comment]
@AlinGP4 Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by AlinGP4** [comment]
Official web school: https://portal.edu.gva.es/iesmiralcamp/es/portada/
direction:
  

-  SPAIN
-   Carrer Miralcamp, 126, 12540 Vila-real, Castelló

IT curses: 
    https://portal.edu.gva.es/iesmiralcamp/es/portada/centro/ensenanzas/ciclos/   
-  T. Microinformatics Systems and Networks (LOE) (2 years)

> [Microinformatics Systems and Networks INFO](https://ceice.gva.es/va/web/formacion-profesional/publicador-ciclos/-/asset_publisher/FRACVC0hANWa/content/ciclo-formativo-sistemas-microinformatico-y-redes)

-  TS Web Application Development (LOE) (2 years)
> [Web Application Development INFO](https://ceice.gva.es/va/web/formacion-profesional/publicador-ciclos/-/asset_publisher/FRACVC0hANWa/content/ciclo-formativo-desarrollo-de-aplicaciones-web)

image

**Comment by AlinGP4** [comment]
**DNS**
image

**Comment by philipto** [comment]
@AlinGP4 Thank you for the clarification. Pull request merged.

**Pull request merged**
