### PR TITLE
Create dbp.txt

### PR DESCRIPTION
**Pull request by wizardalfa**
Don Bosco
Don Bosco School

### CODE REVIEW

**Comment by wizardalfa** [comment]
[dbp.txt](https://github.com/JetBrains/swot/files/8460604/dbp.txt)

**Comment by philipto** [comment]
@wizardalfa Please provide us with:
- the school official website URL
- the school street address, including city and country

**Comment by wizardalfa** [comment]
Don Bosco School
www.dbp.edu.bo
La Paz, Bolivia
Av. 16 de Julio #1805

**Comment by philipto** [comment]
@wizardalfa Pull request merged. Thank you!

**Pull request merged**
