### PR TITLE
Add FC College. Here is Website Link : https://www.fccollege.edu.pk

### PR DESCRIPTION
**Pull request by AhmadIrfanAmin**
**Institution/School Name**

Forman Christian College (A Chartered University)

**Institution/School Website**

https://www.fccollege.edu.pk

**Email Users**

{[muhammaddanish@fccollege.edu.pk](mailto:muhammaddanish@fccollege.edu.pk)}
Please place an x between the square brackets if yes

 Students
 Academic/Teaching Staff
 Other/Support Staff
 Alumni
Education Levels

Please place an x between the square brackets if yes

 Post-graduate research
 Graduate School
 College (University) or Undergraduate School or equivalent
 Community College or equivalent
 High School or equivalent
 Elementary School or equivalent

### CODE REVIEW

**Comment by AhmadIrfanAmin** [comment]
Add FC College

**Comment by philipto** [comment]
@AhmadIrfanAmin First stage of verification passed, official domain is [fccollege.edu.pk](https://fccollege.edu.pk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by AhmadIrfanMST** [comment]
@philipto  How much time will it take for you to review? Can you please do it quickly?

**Comment by philipto** [comment]
@AhmadIrfanAmin Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
