### PR TITLE
Added ZŠ na Chodovci

### PR DESCRIPTION
**Pull request by cheyao**
Added my school's email (We all got a email in 2020 cuz covid and we needed online class :D)

School's website: https://www.zsnachodovci.cz/

yes our schools email is long don't juge

### CODE REVIEW

**Comment by cheyao** [comment]
I've been forced to learn github by Jetbrains lol

**Comment by cheyao** [comment]
https://github.com/JetBrains/swot/pull/13685/files#diff-a14a1f7087c9bf52c08b1599895860b7922c920e76790998927a891fcaa2c336

**Comment by philipto** [comment]
@cheyao First stage of verification passed, official domain is [zsnachodovci.cz](https://zsnachodovci.cz) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by cheyao** [comment]
> @cheyao First stage of verification passed, official domain is [zsnachodovci.cz](https://zsnachodovci.cz) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

lol u don't need to appreciate my patience i'm just developing/learning kotlin and making android apps now

btw a android kotlin question:
how do i save multiple values using kotlin?
i have a var "coins" and a var "total_coins", how can i save them so they don't get lost? thx

**Comment by philipto** [comment]
@cheyao First stage of verification passed, official domain is [zsnachodovci.cz](https://zsnachodovci.cz) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@cheyao Pull request merged. Thank you.

As for your question:
>btw a android kotlin question:
>how do i save multiple values using kotlin?
>i have a var "coins" and a var "total_coins", how can i save them so they don't get lost? thx

It's better to search another support option for coding-related answers, such as kotlinlang.org and relevant communities. However if you wish me to answer your question here, please make it a little bit clearer :) What exactly would you like to do with the variables? 
My possible guesses on what you meant are:
1) 
```
total_coins = 0
total_coins = total_coins + coins
```
2) "what is Kotlin equivalent to Python's tuple?" 
3) "how can I save values to sqlite on Android using Kotlin?"

Thank  you!

**Comment by cheyao** [comment]
Thanks for your reply, i have found my answer on google kotlin developer course, but thanks for your reply!

**Pull request merged**
