### PR TITLE
Add Andover Public Schools from Andover, MA

### PR DESCRIPTION
**Pull request by joshardul**
Andover Public Schools Website:
http://www.aps1.net

Email domain to be added:
@k12.andoverma.us

### CODE REVIEW

**Comment by philipto** [comment]
@joshardul The file which you submitted refers to a non-existing domain:
```
~$ host andover.k12.andoverma.us
Host andover.k12.andoverma.us not found: 3(NXDOMAIN)
```
For k12.andoverma.us domain the file name has to be lib/domains/us/andoverma/k12.txt
Please rename.
Also, the website you mentioned http://www.aps1.net have different email contacts at http://www.aps1.net/386/Human-Resources, it's in andoverma.gov domain. Thus please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email.

**Comment by joshardul** [comment]
Oh ok, thank you.

**Comment by philipto** [comment]
@joshardul No problem. Just please rename the file in this request or close the request to let us know that you are to create a new one as soon as you are ready. Thank you!

**Comment by philipto** [comment]
@joshardul I close this request without merging as a duplicate to successfully merged #5080.

**Pull request closed without merging**
