### PR TITLE
Create ba.txt

### PR DESCRIPTION
**Pull request by managai**
Added Italian Nuclear Physics National Institute
subdomain for Section of Bari
for every local section a subdomain should be properly added

### CODE REVIEW

**Comment by philipto** [comment]
@managai Could you please give us a link to a long-term course (one year or longer), somehow related to IT, which this institution offers to students? Also, could you please clarify if the institution is a research institute, or educational one, such as a university or a subsidiary of a university? Thank you!

**Comment by managai** [comment]
INFN website (english version): [http://home.infn.it/en/](http://home.infn.it/en/)
INFN is a national research institute, jointly working with local universities.
INFN offers to students the opportunities to spend their thesis working time on  projects in which INFN is involved. The educational aspect is managed by local universities, so INFN has not a dedicated webpage to list students' opportunities. Several works are related to distributed computing (the argument of both my MSc and PhD thesis) or big data analysis.
INFN email accounts are available only for researchers and students working on INFN projects.

INFN Section of Bari website is: [http://www.ba.infn.it/index.php/en/](http://www.ba.infn.it/index.php/en/)

**Comment by philipto** [comment]
@managai Do I understand right that the students who study at INFN are also always studying in other universities and have email addresses in these other universities email domains?

**Comment by managai** [comment]
Correct

**Comment by philipto** [comment]
@managai Thank you for the clarification. In this case we appreciate if the students will get their free licenses using their email addresses in their other universities, because this repository is for colleges and universities only. We rarely make exceptions for research institutions which offer some PhD programs to their students, but in case if the students cannot use other email domains. Please let us know if it is the case for some of your students, and we reconsider this issue again. Thank you for the understanding!

**Comment by philipto** [comment]
@managai I have to close this request without merging. Please reopen and comment if you have an update regarding the issues described above. Thank you for the understanding!

**Pull request closed without merging**
