### PR TITLE
A13550t patch 2

### PR DESCRIPTION
**Pull request by a13550t**

### CODE REVIEW

**Comment by a13550t** [comment]
I missed directory.
×「reitaku-u」
○「reitaku」

**Comment by philipto** [comment]
@a13550t Do I understand right that you wish to add a domain of Reitaku University, reitaku-u.ac.jp? If the students email domain is different from @reitaku-u.ac.jp, please comment here and tell us what is the correct domain. If it is @reitaku-u.ac.jp, please rename the file to lib/domains/jp/ac/reitaku-u.txt

Thank you!

**Comment by a13550t** [comment]
This domain\@reitaku-u.ac.jp\is official website domain.But the students email domain is @reitaku.jp  ,
I appreciate your help.

Thank you.

**Comment by philipto** [comment]
@a13550t Thank you for the clarification. Pull request is merged.

**Comment by a13550t** [comment]
Thank you .

**Pull request merged**
