### PR TITLE
Add Texas A&M University - Central Texas

### PR DESCRIPTION
**Pull request by packrat888**
Branch of A&M schools located in Killeen, Texas.

### CODE REVIEW

**Comment by packrat888** [comment]
Domain for the email is: @my.tamuct.edu

**Comment by philipto** [comment]
@packrat888 I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host tamuct.taumct.edu not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by philipto** [comment]
@packrat888 Yuu probably meant `taumct.edu`, thus I reopened the request and corrected it. It will be reviewed again shortly.

**Comment by philipto** [comment]
@packrat888 No, `taumct.edu` does not exist either. Please create a new correct request about existing domain. I finally close the request.

**Comment by packrat888** [comment]
The domain for my school is @my.tamuct.edu
________________________________

**Pull request closed without merging**
