### PR TITLE
Added 42network as school (parent org for all 42 schools)

### PR DESCRIPTION
**Pull request by neuromantik33**
42network is the parent organisation which creates all pedago materials for all 42 campuses worldwide (42tokyo, 42seoul, 42lyon, 42paris etc...)

### CODE REVIEW

**Comment by philipto** [comment]
@neuromantik33 Each school of "42 school" network has its own email domain, as far as I know. Could you please clarify who gets the email addresses in 42network.org domain?

**Comment by neuromantik33** [comment]
[42 network](http://www.42.fr/42-network/) is the parent organisation for all 42 campuses, each with their staff and students. However, all of the pedagogical materials, student projects and internal teaching tools are developed by 42 network staff members, and distributed to campuses which contribute to them (git repos) and provide translations and corrections. However there are also staff members which only perform administrative functions which also have 42network.org email addresses. But they won't be the ones evaluating WebStorm or CLion as alternatives to vim/emacs for future back/frontend projects.

I or other staff members are available if you have any more questions.

**Comment by philipto** [comment]
@neuromantik33 Pull request merged. 
Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of this Institute who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.
Thank you!

**Comment by neuromantik33** [comment]
Thanks for the PR and I will inform our pedagogical team of the terms and conditions and instruct them on fair usage. Again thank you :)

**Pull request merged**
