### PR TITLE
Add scamt.txt

### PR DESCRIPTION
**Pull request by zilov**

### CODE REVIEW

**Comment by philipto** [comment]
@zilov Please provide us with a proof, which shows that the school recognizes the domain scamt.spb.ru that you are submitting as an official email domain for the students.

**Comment by zilov** [comment]
@philipto thank you for the quick reply! Email domain for students is @scamt-itmo.ru, the official site of the institute is https://scamt.ifmo.ru/ (link to the site can be found on official ITMO University site here https://en.itmo.ru/en/faculty/110/himiko-biologicheskiy_klaster.htm). Is that enough, or I should find some more proofs?

**Comment by philipto** [comment]
@zilov Thank you! I renamed the file in your request to ensure that a correct domain is added to the repository: scamt-itmo.ru email domain corresponds to a file lib/domains/ru/scamt-itmo.txt, according to the rules. Pull request merged.

**Comment by zilov** [comment]
@philipto thanks a lot!

**Pull request merged**
