### PR TITLE
Create etna.txt

### PR DESCRIPTION
**Pull request by kingluffyxx**

### CODE REVIEW

**Comment by philipto** [comment]
@kingluffyxx etna.fr website redirect to RH Marine Group website. Are you sure that you add this domain to the repository? It does not seem to belong to a university at all...

**Comment by philipto** [comment]
@kingluffyxx Thank you for the clarification! Please rename `lib/domains/fr/etna.txt` to `lib/domains/io/etna.txt` (notice "io" instead of "fr" in the path). Thank you!

**Comment by kingluffyxx** [comment]
i have no license, my address mail is adda_x@etna-alternance.net
how many long before i have access to a license ?

**Comment by philipto** [comment]
@kingluffyxx If your email us adda_x@etna-alternance.net, then you need to add a domain etna-alternance.net to this repository, and therefore the corresponding file path in the request shall be **lib/domains/net/etna-alternance.txt**, not the one which you add now.

After you submitted correct request it usually takes from one to three business days for us to check the validity of the request, and if everything is OK, I add the file to the repository. After the file is added, it takes about an hour to auto-update our system which sends the license request confirmation to you, thus you can wait for an hour and request the license at https://jetbrains.com/student.

**Comment by kingluffyxx** [comment]
@philipto Thank you !

**Comment by philipto** [comment]
No problem. Would you like to add the domain etna-alternance.net or wish to add just a domain etna.io?

**Comment by kingluffyxx** [comment]
It's good, etna-alternance was already add, Thank you for your help i have my "JetBrains Product Pack for Students"

**Comment by philipto** [comment]
@kingluffyxx Very good. Thank you for the update. I am closing this request without merging because actual email domain is already in the repository.

**Pull request closed without merging**
