### PR TITLE
Add Domain

### PR DESCRIPTION
**Pull request by MahmoudAbdullh**
http://csi.edu.eg/dpage.aspx?id=11&facultyId=4

### CODE REVIEW

**Comment by philipto** [comment]
@MahmoudAbdullh I am sorry, as far as I know, Culture & Science City is an association of the universities and institutes. Do the universities and institutes have their own email domains? As a rule, we don't include umbrella institutions to this repository. Please clarify. Thank you.

**Comment by MahmoudAbdullh** [comment]
Greetings,
I hope this mail find you well
This simple clarify about Culture & Science City [ http://csi.edu.eg/ ]
Culture & Science City association of institutes and related to O6U university but each of then have there own domains, I see the university is already listed into the repo.
thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by philipto** [comment]
@MahmoudAbdullh Thank you for your quick response. If each of the universities in the association has their own domain, why do you need to include the domain of csi.edu.eg? According to this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot), umbrella domains, which cover similar association, cannot be added to the repository. I am sorry about it.

**Comment by philipto** [comment]
@MahmoudAbdullh You might miss my previous comment. Please react.

**Comment by MahmoudAbdullh** [comment]
Greetings,
Cluture and sciewnse city have there own domain and there own email systems and it’s own management [  csi.edu.eg ]
and the only thing between it and o6u university is the owner…
best Regards.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by philipto** [comment]
@MahmoudAbdullh Yes, thank you. I am not sure that I was clear enough. Please consider the following:
1) If a university has its own email domain, and the university is a part of Culture & Science City, this university has to be added to this repository separately - with its domain, **not with csi.edu.eg**.
2) If there is an organization which is a part of Culture & Science City, but this organization is not a college, nor a university, it is not qulaifed to be added to this repository.

Therefore, I can add csi.edu.eg to this repository only **if all the following conditions are satisfied**:
1) There is a number of universities which do not their own email domains, 
2) The universities without their own email domains mentioned above are the part of Culture & Science City,
3) The universities mentioned above have long-term (>1 year) IT-related courses, such as software engineering, bioinformatics, math, etc.
4) The universities grant students who study there, and the teachers who teach there, the email addresses in the domain csi.edu.eg, and they cancel the addresses (i.e. make them not valid anymore) upon the graduation of the students.

Please let us know which universities in Culture & Science City meet all the criteria 1-4 listed above. Thank you.

**Comment by MahmoudAbdullh** [comment]
@JetBrains/swot<mailto:swot@noreply.github.com> culture & science city is assossiation of institutes all of them long term  > 1 year
this one of them http://csi.edu.eg/dpage.aspx?id=11&facultyId=4 higher institute of computer science and information systems
http://csi.edu.eg/ display all institutes belongs to CSI [culture & science city] you can check

thanks
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by philipto** [comment]
@MahmoudAbdullh Well, this page http://csi.edu.eg/dpage.aspx?id=11&facultyId=4 describes a CS courses indeed, and it seems to belong to CSI, not to a specific institute having another email domain. Thus, let me thank you for the clarifications. Pull request merged. Please request licenses and have a happy coding!

**Comment by MahmoudAbdullh** [comment]
Thank you 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Pull request merged**
