### PR TITLE
Add mpia.de

### PR DESCRIPTION
**Pull request by SmirnGreg**
Alias to already existing mpia-hd.mpg.de

### CODE REVIEW

**Comment by philipto** [comment]
@SmirnGreg Pull request merged. 
Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of this Institute who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.
Thank you!

**Comment by SmirnGreg** [comment]
@philipto do I understand correctly that people performing academic research and working together with students are eligible for the license, and the institute staff performing IT support and administration are not eligible?

**Comment by philipto** [comment]
@SmirnGreg 
> institute staff performing IT support and administration are not eligible
True.
> people performing academic research and working together with students are eligible
I am not sure because it depends on the research purpose and nature of the work with students.
If the research and work are educational, i.e. are meant to study a subject in the frame of the bachelor, master or PhD program, or to teach students in the frame of the above-mentioned programs - yes, they are eligible.

If the research is a regular scientific job that is not a part of the study or teaching - no, they are not eligible. For example, if a researcher is a student employed to a project and has a salary from the project, it is not an educational purpose.

**Comment by philipto** [comment]
@SmirnGreg Please send an email to sales@jetbrains.com if you are unsure if someone (or a particular research group) at the school needs a specific license, other than educational.

**Pull request merged**
