### PR TITLE
Add Domain sman1brebes.txt

### PR DESCRIPTION
**Pull request by agoessiregar**
Add Domain sman1brebes.txt

### CODE REVIEW

**Comment by philipto** [comment]
Please kindly provide the full name of your school on the first line of the file in your request

**Comment by agoessiregar** [comment]
Sekolah Menengah Atas Negeri 1 Brebes

**Comment by philipto** [comment]
@agoessiregar Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by indrabudi1** [comment]
Adding SMAN 1 BREBES (sman1brebes.sch.id) to the JetBrains Education program.

Official education department references:
https://dapo.kemdikbud.go.id/sekolah/C888B894144FC0D0F986

**Comment by philipto** [comment]
@agoessiregar Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
