### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by 4mm449**

### CODE REVIEW

**Comment by philipto** [comment]
@4mm449 First stage of verification passed, official domain is [psb-academy.edu.sg](https://psb-academy.edu.sg) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.psb-academy.edu.sg/wordpress/wp-content/uploads/2020/11/CU-November-2022-CY-CP-Re-assessment.pdf

**Comment by georgekarlr** [comment]
[sccpag.txt](https://github.com/JetBrains/swot/files/11607486/sccpag.txt)
official domain sccpag.edu.ph

**Comment by philipto** [comment]
@4mm449 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by philipto** [comment]
@georgekarlr Please make a separate pull request. You also can send an email with your request to community-support@jetbrains.com if you absolutely unable to follow the instructions at the bottom of this page: https://github.com/JetBrains/swot. 

Please notice that the email must contain your school's domain (sccpag.edu.ph) and the school's full official name.

Thank you!

**Pull request merged**
