### PR TITLE
added PKG

### PR DESCRIPTION
**Pull request by 15P0seidon**
added my school domain to the repo

### CODE REVIEW

**Comment by philipto** [comment]
@15P0seidon Please provide us with a proof, which shows that the school recognizes the domain `s.pkg.bayern` that you are submitting as an official email domain for the students.

You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by 15P0seidon** [comment]
﻿Here is proof for using @s.pkg.bayern as a school email adress. The text is written in German.On 25. Sep 2024, at 20:28, Philip Torchinsky ***@***.***> wrote:﻿
@15P0seidon You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@15P0seidon I am sorry for not telling you it in advance: please upload the proof using your browser, not by email. GitHub strips out all email attachments and remove all email addresses from the comment if your sent the reply by  email.

I appreciate it if you can upload the proof again using your browser. Thank you!

**Comment by philipto** [comment]
@15P0seidon I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by 15P0seidon** [comment]
Sorry for answering this late. I hope that it is still possible to add this:

Am Mi., 2. Okt. 2024 um 14:10 Uhr schrieb Philip Torchinsky <
***@***.***>:

**Pull request closed without merging**
