### PR TITLE
add isi.ac.id

### PR DESCRIPTION
**Pull request by awankelana**
isi.ac.id

### CODE REVIEW

**Comment by philipto** [comment]
@awankelana Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by awankelana** [comment]
https://isi.ac.id/program/seni-media-rekam/d3-animasi/

Screenshot_3

**Comment by philipto** [comment]
@awankelana Thank you for the update! Pull request merged.

**Comment by awankelana** [comment]
thanks a lot for confirmation

**Pull request merged**
