### PR TITLE
Added dhbw-karlsruhe.txt

### PR DESCRIPTION
**Pull request by dehlen**
All students of DHBW Karlsruhe will get an E-Mail Adress applicable
from 20.07.2015. Therefore it should be possible to access your student program with email adresses of this university.

Email Adresses are of the form: lastname.firstname@student.dhbw-karlsruhe.de

### CODE REVIEW

**Comment by rofrischmann** [comment]
Would be awesome to get that!

**Comment by boomy** [comment]
This Pull Request is missing the proper domain structure as seen here:

https://github.com/JetBrains/swot/blob/master/CONTRIBUTING.md

There should be another subdirectory in lib/domains called de/student/dhbw-karlsruhe.txt

Btw: Would be nice to have ;)

**Comment by dehlen** [comment]
I fixed the domain structure according to your comment.

**Comment by zweizwei** [comment]
@dehlen please remove /student.txt and leave just /dhbw-karlsruhe.txt -  this way we'll cover both students and staff. Thank you.

**Comment by dehlen** [comment]
@zweizwei isn't this the exact same thing I did previously in 5d64870490976d1f3eae4f0eec906b19e7e075ff ?

**Comment by zweizwei** [comment]
@dehlen in this case we don't need /student/ folder - this subdomain is already covered by your previous request. I'm closing this request therefore.

**Pull request closed without merging**
