### PR TITLE
Create sai.txt

### PR DESCRIPTION
**Pull request by Arihant25**
The domain is saicloudschool.net.in
The website is https://saiinternational.edu.in/

### CODE REVIEW

**Comment by Arihant25** [comment]
When are you gonna add this?

**Comment by philipto** [comment]
@Arihant25 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by Arihant25** [comment]
Our school teaches a wide variety of subjects like English, Mathematics, Science, and even Computer Science. While there isn't a page exclusively for the Computer Science subject, here's a page on our school laboratories which describes our Atal Tinkering Lab (Computer Lab) and Robotics Lab: https://saiinternational.edu.in/learning360/academics/labs/

**Comment by philipto** [comment]
@Arihant25 Thank you for the clarification. Pull request merged.

**Comment by Arihant25** [comment]
I'm really sorry, but there seems to be a mistake. Instead of sai.txt, it should be saicloudschool.txt. I've attached the new file. Could you please update it, or do I have to create a separate pull request for it?
[saicloudschool.txt](https://github.com/JetBrains/swot/files/6703404/saicloudschool.txt)

**Pull request merged**
