### PR TITLE
Add TUS - Technical University of the Shannon, Ireland

### PR DESCRIPTION
**Pull request by boardtc**
Add the Technical University of the Shannon. Ireland

### CODE REVIEW

**Comment by boardtc** [comment]
amalgamation of https://ait.ie/ & https://lit.ie/

**Comment by philipto** [comment]
@boardtc First stage of verification passed, official domain is [tus.ie](https://tus.ie) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by boardtc** [comment]
@philipto Thanks very much, What typically is the timeline for a decision?

**Comment by boardtc** [comment]
My license expires in 4 days so definitely keen to get this resolved!

**Comment by philipto** [comment]
@boardtc Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
