### PR TITLE
college domain added Kathmandu institute of science and technology

### PR DESCRIPTION
**Pull request by Andipstha**
https://kist.edu.np/

### CODE REVIEW

**Comment by philipto** [comment]
@Andipstha Please explain why you need to add this domain while the domain of the same organization has been already added to the trusted list as #16537?

**Comment by Andipstha** [comment]
while trying to access the developer tools and being unable to register due to "Your email address is not associated with any university that we are aware of. You can apply in a different way (see the tabs above) or add your school to JetBrains' list."

**Comment by philipto** [comment]
@Andipstha You might miss my previous comment. Please react.

**Comment by Andipstha** [comment]
@philipto, thank you for your response. I added the domain because it wasn't on JetBrains' list. Previously, when I was attempting to apply for JetBrains products.

**Pull request closed without merging**
