### PR TITLE
Northern Bukidnon College

### PR DESCRIPTION
**Pull request by hexedhorizon**
Submitting a pull request to include Northern Bukidnon State College in the JetBrains academic/education library list.

School website:
[](https://nbsc.edu.ph/)

### CODE REVIEW

**Comment by philipto** [comment]
@hexedhorizon First stage of verification passed, official domain is [nbsc.edu.ph](https://nbsc.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by hexedhorizon** [comment]
Thank you for the update on the first verification.

**Comment by philipto** [comment]
@hexedhorizon Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by hexedhorizon** [comment]
@philipto Thanks a lot for considering reviewing and accepting our humble academic institution into the roster. This collaboration would benefit our students, faculty and institution this academic year.

**Pull request merged**
