### PR TITLE
Add kiwi.txt for Kiwi College of New Zealand

### PR DESCRIPTION
**Pull request by joseph-bing-han**
### School Name
**Kiwi College of New Zealand**

### School Official Website
**https://kiwi.ac.nz/**

### Email Users
- [ ] Students
- [x] Academic/Teaching Staff
- [x] Other/Support Staff
- [ ] Alumni

### Education Levels
- [ ] Post-graduate research
- [ ] Graduate School
- [ ] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [x] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by joseph-bing-han** [comment]
Apologies, there was a mistake. 'Email Users' does not include students, as their email addresses are xxx@student.kiwi.ac.nz.

**Comment by philipto** [comment]
@joseph-bing-han First stage of verification passed, official domain for **Kiwi College of New Zealand** is [kiwi.ac.nz](https://kiwi.ac.nz) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by joseph-bing-han** [comment]
@philipto Thank you for your verification. 
Our school's University Foundation Programmes include the courses 'Computer Programming Fundamentals' and 'Foundations of Computer Science'. I have recommended your software series to my boss because it is a top-tier IDE in the industry, and the license is very education-friendly.

**Comment by philipto** [comment]
@joseph-bing-han Pull request merged. Thank you.

**Pull request merged**
