### PR TITLE
Add Domain 

### PR DESCRIPTION
**Pull request by quocthinh212**
Hanoi University of Science & Technology (HUST)
set.edu.vn

### CODE REVIEW

**Comment by philipto** [comment]
@quocthinh212 Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@quocthinh212 You might miss my previous comment. Please react.

**Comment by quocthinh212** [comment]
> @quocthinh212 Please provide us with:
> 
> * the school official website URL
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

1. Official website http://www.set.edu.vn/
2. An URL of a page on the official website where the school offers an IT-related long-term (>1 year) course => https://set.hust.edu.vn/lich-su-phat-trien
3. This official email domain use for student and teacher in our school.

Thanks.

**Comment by philipto** [comment]
@quocthinh212 I am sorry, our records and check indicates that this university has a different official domain. I have to close this request without merging. If you are the student of this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
