### PR TITLE
new university

### PR DESCRIPTION
**Pull request by Isaac-Sousa**

### CODE REVIEW

**Comment by JhonattanAron** [comment]
a new university 
[itsjapon.txt](https://github.com/JetBrains/swot/files/9769598/itsjapon.txt)

**Comment by JhonattanAron** [comment]
[itsjapon.txt](https://github.com/JetBrains/swot/files/9769640/itsjapon.txt)

**Comment by philipto** [comment]
@Isaac-Sousa I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by Isaac-Sousa** [comment]
@philipto, I'll verify my changes, thanks for the feedback.

**Pull request closed without merging**
