### PR TITLE
update

### PR DESCRIPTION
**Pull request by manhnd9293**
add Hanoi University of Science and Technology to college

### CODE REVIEW

**Comment by philipto** [comment]
@manhnd9293 
Please provide us with a proof which shows that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@manhnd9293 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@manhnd9293 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Comment by manhnd9293** [comment]
thanks you for your review, i will provide proof as soon as possible

**Pull request closed without merging**
