### PR TITLE
Create hepsilisans.txt

### PR DESCRIPTION
**Pull request by volkankner**
hepsilisans.edu.pl

### CODE REVIEW

**Comment by volkankner** [comment]
hepsilisans.edu.pl

**Review by sabinm677 — APPROVED** [review]

**Review by sabinm677 — COMMENTED** [review]
Website not found

**Comment by philipto** [comment]
@volkankner Regrettably, this request has signs of fraud. I have to close it without merging.

**Comment by volkankner** [comment]
ok. sorry.

**Pull request closed without merging**
