### PR TITLE
Create vbs.txt

### PR DESCRIPTION
**Pull request by holgerengels**
Professional school in Ulm, Germany ..

### CODE REVIEW

**Comment by philipto** [comment]
@holgerengels Could you please provide us with:
1) the school official website URL, because it is different from the domain you are submitting,
2) an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university,
3) an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.
Thank you!

**Comment by holgerengels** [comment]
Hi Philip,

I could have submitted h.engels@valckenburgschule.de instead, as we have
both domains .. but I saw, there were some more schools in the repository
with the standard school domain pattern in germany:

   de --> schule --> bw (federal state) --> ul (city) --> vbs (abbreviation
of the schoolname)


   - our website is http://www.valckenburgschule.de
   - the curriculum is here: download
   <http://www.ls-bw.de/site/pbs-bw-new/get/documents/KULTUS.Dachmandant/KULTUS/Dienststellen/ls-bw/Bildungspl%C3%A4ne/Berufliche%20Schulen/bg/bg_berufsbezogen/Oberstufe/BG2-AG-EG-SGG-WG_Informatik_08_3574.pdf>
(object
   oriented programming in class 12 and website development in class 13)


kind regards,

holger


On Thu, Sep 29, 2016 at 1:23 PM, Philip Torchinsky <notifications@github.com

**Comment by philipto** [comment]
@holgerengels Thank you for the details! Pull request merged.

**Comment by holgerengels** [comment]
thanks a lot!

Am 03.10.2016 11:25 vorm. schrieb "Philip Torchinsky" <
notifications@github.com>:

**Pull request merged**
