### PR TITLE
Add Omar Bin Al Khattab Private School 

### PR DESCRIPTION
**Pull request by mostafatahaa**

### CODE REVIEW

**Comment by mostafatahaa** [comment]
https://www.omarschool.com/

**Comment by philipto** [comment]
@mostafatahaa Please provide us with a proof, which shows that the school recognizes the domain **dakahliya1.moe.edu.eg** that you are submitting as an official email domain for the students.

You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by mostafatahaa** [comment]
@philipto 
Unfortunately, obtaining proof that the email domain dakahliya1.moe.edu.eg is officially recognized by the school is challenging because the school’s login system does not require students to use email addresses for access.

However, I have attached a screenshot that shows the login process through the Ministry of Education’s website using the email address from the domain, as well as the login via Outlook. I hope this can serve as sufficient proof that the domain is being used by students.

Please let me know if further clarification is needed.

**Comment by philipto** [comment]
@mostafatahaa Hello!
Thank you for providing us with the screenshots. Regrettably, according to an expert in the matter, the screenshots may not be the best proof of official domain recognition, as well as eligibility for being added to the trusted list. 

I have to close the request without merging. Please use alternative way of requesting JetBrains educational license:
1. Please enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. 
2. Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).
3. 
I have to close this request without merging.
Thank you for your understanding!

**Pull request closed without merging**
