### PR TITLE
Create si.txt

### PR DESCRIPTION
**Pull request by edwardmonk**
Smithsonian Institution

### CODE REVIEW

**Comment by edwardmonk** [comment]
More Information About the Smithsonian:
http://si.edu/About/Education

**Comment by philipto** [comment]
@edwardmonk I am really sorry, but the website gives an impression that Smithsonian is a widely recognized institution, but is not a single university or a college. While you actually do a tremendous work educating a lot of people around the United States (and not only States), we have to clarify who are actually use email addresses in @si.edu domain. Are they available for all the stuff, researchers, teachers, alumni and students? If yes, I would suggest to limit the scope of the addresses registered as eligible for free educational license. You may have a subdomain such as students.si.edu, or something like that. Do you?

Could you please tell us a bit more about how email addresses in @si.edu domain are assigned and used? Please notice that free licenses which JetBrains grants to students and teachers are for educational purpose only, and shall not be used in research, commercial projects, etc.

**Comment by edwardmonk** [comment]
The si.edu domain is definitely not for commercial purposes.  It is a domain that is used by the educational branch, all museums, all cultural centers, all archives and libraries and research centers under the Smithsonian Institution. Perhaps this is too broad a domain to qualify in your definition of an educational organization.  We normally qualify under Microsoft, RedHat, and others, but again those are different vendors with different policies.

**Comment by philipto** [comment]
@edwardmonk You are right, Smithsonian Institution is a special case for us. This is why it will take a bit longer than usual. I promise to get back with an update as soon as possible. Thank you for your patience!

**Comment by philipto** [comment]
Dear @edwardmonk! 

Regrettably, we cannot add Smithsonian Institution to this repository, because it is neither a university, nor a college. We noticed that Smithsonian Institution recently bought several JetBrains commercial subscriptions for its projects, and we are glad to assist further. What can we suggest?

1. For students JetBrains tools are free, regardless of formal university status of their school. Thus, Smithsonian Institution's students can use JetBrains tools for free with any of three options:
(a) applying for the free license with their ISIC card at https://www.jetbrains.com/shop/eform/students (I believe, many of them have ISIC cards, and it must not be a problem to get one in Washington D.C.)
(b) asking their teachers to apply for a classroom license, which can be installed on a license server in the university lab rooms in order to have all computers in the labs capable to run JetBrains tools
(c) asking their teachers to request student licenses for them by email to classroom@jetbrains.com; the teachers then can send the invitations to students, and the students will be able to use the license by invitation.

2. Special Academic discount is available for others in Smithsonian Institution, including researchers and IT specialists, thus Smithsonian Institution can purchase licenses for them with 50% discount. Please feel free to email sales@jetbrains.com for details.

I really hope that we can find a good solution for you, feel free to comment here or email one of the addresses mentioned above. For now, I am closing the request without merging. Please reopen if necessary for further discussion. Thank you for your understanding.

Sincerely yours,
Philip Torchinsky
JetBrains

**Pull request closed without merging**
