### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by alvileg**
This is the email for the students.
Website: asvalencia.org
Teacher email: @asvalencia.org

### CODE REVIEW

**Comment by philipto** [comment]
@CrownCrafter25 You might miss my previous comment. Please reply.

**Comment by CrownCrafter25** [comment]
Hello, I'm sorry for replying so late.
this is a screenshot proving that it is indeed a school email.
[image: image.png]

**Comment by philipto** [comment]
@CrownCrafter25 Thank you! Please attach the screenshot directly via GitHub web interface, it is stripped from the email, unfortunately. Thank you.

**Comment by philipto** [comment]
@CrownCrafter25 You might miss my previous comment. Please reattach the screenshot.

**Comment by philipto** [comment]
@alvileg I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
