### PR TITLE
Add La Salle College High School (lschs.org)

### PR DESCRIPTION
**Pull request by frjalex**
An independent college preparatory located in Wyndmoor, PA providing a decent amount of CS-related courses.

Address: www.lschs.org

### CODE REVIEW

**Comment by philipto** [comment]
@frjalex All files in this repository have descriptions of respective schools in them.
Please add this line to the file:
La Salle College High School

**Comment by frjalex** [comment]
@philipto Added.

**Comment by philipto** [comment]
@frjalex Pull request merged. Thank you!

**Comment by frjalex** [comment]
You're welcome!!

**Pull request merged**
