### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by A-freedom**

### CODE REVIEW

**Comment by A-freedom** [comment]
كلية الكنوز الجامعة

**Comment by philipto** [comment]
@A-freedom First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/AL-Kunooze-University-College-%D9%83%D9%84%D9%8A%D8%A9-%D8%A7%D9%84%D9%83%D9%86%D9%88%D8%B2-%D8%A7%D9%84%D8%AC%D8%A7%D9%85%D8%B9%D8%A9-342857229634699/posts/

**Comment by philipto** [comment]
@A-freedom While the facebook page mentioned above seems to be the official one, could you please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@A-freedom You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@A-freedom I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
