### PR TITLE
Add Batumi State University

### PR DESCRIPTION
**Pull request by refreshed-hub**
**University name**
Georgian: ბათუმის შოთა რუსთაველის სახელმწიფო უნივერსიტეტი
English: Batumi Shota Rustaveli State University

**Links**
https://bsu.edu.ge/ (bsu.ge redirects here)
https://bsu.edu.ge/sub-59/news/index.html (Faculty of Exact Sciences and Education)
https://bsu.edu.ge/main/page/313/index.html (Contact information)

### CODE REVIEW

**Comment by EvG01** [comment]
[file.zip](https://github.com/JetBrains/swot/files/6825879/file.zip)

**Comment by philipto** [comment]
@refreshed-hub Could you please highlight where at the contact page I can see an address ending with @bsu.ge? You request to add @bsu.ge, but all contacts at the website are @bsu.edu.ge.

@EvG01 ukr.net does not belong to a university, nor to a college. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

**Comment by refreshed-hub** [comment]
> @refreshed-hub Could you please highlight where at the contact page I can see an address ending with @bsu.ge? You request to add @bsu.ge, but all contacts at the website are @bsu.edu.ge.
The @bsu.edu.ge is typically reserved for the staff of the university, while students, especially newer ones, usually have the @bsu.ge domain. Furthermore:
https://bsu.edu.ge/main/page/2535/bsu.ge/index.html
At the end of this page, the bsu.ge domain is mentioned in:
> ფოსტის შესამოწმებლად სტუდენტები უნდა შევიდნენ უნივერსიტეტის მთავარ ვებგვერდზე (www.bsu.edu.ge ან www.bsu.ge) და ვერტიკალურ მენიუში გახსნან ელ-ფოსტა. ტექნიკური პრობლემების არსებობის შემთხვევაში დახმარებისათვის მიმართეთ საინფორმაციო ტექნოლოგიების და კომუნიკაციის სამსახურს.
Both domains can have e-mails.

**Comment by philipto** [comment]
@refreshed-hub I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Pull request merged**
