### PR TITLE
Create vub

### PR DESCRIPTION
**Pull request by tonnin**

### CODE REVIEW

**Comment by tonnin** [comment]
VUB added

**Comment by philipto** [comment]
@tonnin Please rename lib/domains/be/vub to lib/domains/be/vub.txt in order to reflect this repository rules. Thank you!

**Comment by philipto** [comment]
@tonnin You might miss my comment above. Could you please update the request to reflect the rules? Thank you!

**Comment by philipto** [comment]
@tonnin I am sorry, this request remains unanswered for a while. I have to close it. Please reopen and make the change requested above, if the request is still valid. Thank you!

**Pull request closed without merging**
