### PR TITLE
Create mx edu unidep cul.txt

### PR DESCRIPTION
**Pull request by CesarIgnacioCamposMillan**
cul.unidep.edu.mx add the school unidep

### CODE REVIEW

**Comment by CesarIgnacioCamposMillan** [comment]
how i can send to you the proof? https://unidep.mx/ is the main domain of the school and the email hava a prefix @cul.unidep.edu.mx for example "cul" is the city of the student "unidep" is the school name , "edu" of education and "mx" of the country

**Comment by philipto** [comment]
@CesarIgnacioCamposMillan Yes, you are right. I see that https://unidep.mx/ is the main domain of the school. 

The options to prove that **cul.unidep.edu.mx** is recognized by the school I suggested are:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

There should be something we can look at. The domain **cul.unidep.edu.mx** is not mentioned anywhere at the official website, thus there shall be some material (printed or online) that tells the students that the domain for them is **cul.unidep.edu.mx**. Please attach the copy of this material to this issue as a comment.

Please attach it via browser, not by email, because GitHub strips out all attachments sent by email.

**Comment by philipto** [comment]
@CesarIgnacioCamposMillan You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@CesarIgnacioCamposMillan I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
