### PR TITLE
add tmudaihoctuxa of Thuongmai University

### PR DESCRIPTION
**Pull request by enrio**
I added mail for tmudaihoctuxa of Thuongmai University

### CODE REVIEW

**Comment by enrio** [comment]
Dear Team,
Please add for remote education of Thuongmai University
Thanks

**Comment by philipto** [comment]
@enrio This is not a primary official domain of the Thuongmai University. Please:
1. Prove that the university has some strict rules regarding online education. If the university charge a significant fee to enroll an online student, we can recognize the university domain as qualified for this repository. If the enrollment is free, it's more like courses provider similar to Udemy or Coursera. In such case, I recommend to consider another free licensing option: https://www.jetbrains.com/community/education/#courses.
2. Prove that the university recognizes this domain as official.
You can provide us with any of the following as the proof:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

Thank you for your understanding!

**Comment by philipto** [comment]
@enrio You might miss my previous comment. Please react.

**Comment by enrio** [comment]
Hi Team, 

I add the screenshot of educate-instruction mail and student profile,

All student will be reciece email like xxxxx@tmudaihoctuxa.vn, 
and students have to login to https://dttx.tmu.edu.vn to start learning.

Please check again,
Thanks


image

image

**Comment by philipto** [comment]
@enrio Thank you for the update. Regrettably, it answers to my second question only. Please prove that the university has some strict rules regarding online education. 

If the university charge a significant fee to enroll an online student, we can recognize the university domain as qualified for this repository. 

If the enrollment is free, it's more like courses provider similar to Udemy or Coursera. In such case, I recommend to consider another free licensing option: https://www.jetbrains.com/community/education/#courses.

**Please let us know what is this online university's fee for the education.**

**Comment by enrio** [comment]
This is **not** online university's fee for the education. and it's not an online course.

There are many rule and agreement, which was posted at the [link](https://qldt.tmu.edu.vn/van-ban-quan-ly)

**Comment by philipto** [comment]
@enrio Thank you for the clarifications and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
