### PR TITLE
Create syasi.txt for Syasi Online Arabic Institute

### PR DESCRIPTION
**Pull request by ahmadio**
Syasi Online Arabic Institute

### CODE REVIEW

**Comment by ahmadio** [comment]
This is google for education domain used to manage and run Syasi Online Arabic Institute

**Comment by philipto** [comment]
@ahmadio I am sorry, I can not locate a website for Syasi Online Arabic Institute for any official information from the institute. Also, please notice that JetBrains **does not provide** free licenses for online universities, we grant licenses to universities which have offline classrooms, where students present physically during classes. 

If you do have offline long-term (> 1 year) IT-related courses, please provide us with a link to the official website, the page with the course description, and a proof confirming that syasi.org domain is used by students and teachers of the institute only.

If the email in the domain can be given to online classes attendees, the domain shall **not** be included into this repository. Thank you for your understanding.

**Comment by philipto** [comment]
@ahmadio I am sorry, I have to close this request without merging because the university seems to be an online university, and we do not provide licenses to the online educational institutions. Thank you for your understanding.

**Comment by ahmadio** [comment]
Thanks, understood

**Pull request closed without merging**
