### PR TITLE
Added Raharja mail domain

### PR DESCRIPTION
**Pull request by pdeddy78**
Added Raharja GSuite domain

### CODE REVIEW

**Comment by philipto** [comment]
@pdeddy78 Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@pdeddy78 You might miss my previous comment. Please react.

**Comment by pdeddy78** [comment]
@philipto Sorry, for the late reply. I am confused what can prove that the email domain is the official email of my campus. We use the G-Suite domain service for our official email. One that might prove is that we have the Students iLearning Services+ (http://sisplus.raharja.ac.id) and there requires an Raharja.Info account (or Rinfo we call it) which is our campus official email.
Our official site is raharja.ac.id. Our university only focuses on information technology since it was first established, you can check on the official website or see http://ti.raharja.ac.id. Hope this helps. Thank you.

**Comment by philipto** [comment]
@pdeddy78 The problem is that raharja.info is not mentioned anywhere at your official website: http://ti.raharja.ac.id/?s=raharja.info

Thus, I need a photo or a screenshot of some official paper which says that students can use emails ending with "@raharja.info". Please remove all personal details from there if you upload it to GitHub, and upload it via web interface, because GitHub strips out attachments from emails send in response of the comments

**Comment by pdeddy78** [comment]
Following is the official statement in the form of journal publications, one of the authors is the president director of our campus, http://ejournal.raharja.ac.id/index.php/ccit/article/view/135 (published on google scholar too), about implementing Raharja.info (Rinfo we call it). "Rinfo is an official e-mail used by all members of the University of Raharja to communicate with each other. The Rinfo is Gmail, which is adapted from Google Platform with the characteristics of raharja.info as its domain."
Only with this email account, students can access the Student iLearning Services+(http://sisplus.raharja.ac.id). And you can see the word of "Email Rinfo" or "RinfoApps" in there too. Thank you.

**Comment by philipto** [comment]
@pdeddy78 Thank you for the update! Pull request merged.

**Pull request merged**
