### PR TITLE
Brunswick High School

### PR DESCRIPTION
**Pull request by Furrure**
Maine High School with multiple courses in programming, namely Computer Programming in Python and AP Computer Programming in Java.

https://brunswicksd.org

### CODE REVIEW

**Comment by philipto** [comment]
@Furrure Please provide us with:
- the school official website URL
- the school street address, including city and country

**Comment by Furrure** [comment]
116 Maquoit Rd, Brunswick, ME 04011, USA

**Comment by Furrure** [comment]
Also, here is a link to the course descriptions, on page 11-12 are the computer science courses.

https://core-docs.s3.amazonaws.com/documents/asset/uploaded_file/1981172/2022-23_Course_Book.pdf

**Comment by philipto** [comment]
@Furrure Thank you very much for the clarification. Pull request merged.

**Pull request merged**
