### PR TITLE
Added krishna College

### PR DESCRIPTION
**Pull request by Tusharmalik**
http://www.shrikrishnacollege.com/

http://www.shrikrishnacollege.com/Programme.html
http://www.shrikrishnacollege.com/DELED2023/Minority%20Registration.html

University is having 2 domains, 1 for email purposes and 1 for official website. Added both in this PR.

### CODE REVIEW

**Comment by philipto** [comment]
@Tusharmalik The first verification stage is complete: the official domain for  **Krishna Engineering College** is [www.shiksha.com](https://www.shiksha.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.shiksha.com/college/krishna-engineering-college-ghaziabad-24915/course-b-tech-in-computer-science-and-engineering-artificial-intelligence-896901

**Comment by Tusharmalik** [comment]
@philipto [www.shiksha.com](https://www.shiksha.com/) is a general purpose college searching website(not Krishna Engineering college official website). You can search any college on this website and will get a webpage for that college (e.g. IIT Delhi, https://www.shiksha.com/university/iit-delhi-indian-institute-of-technology-53938/courses). 

Even [www.shiksha.com](https://www.shiksha.com/) website is also providing official domain for **Krishna Engineering College** on this webpage https://www.shiksha.com/college/krishna-engineering-college-ghaziabad-24915/scholarships. i.e. http://www.krishnacollege.ac.in , http://www.shrikrishnacollege.com

I trust that this information will prove beneficial and support your team in steering the review process in the appropriate direction.

**Comment by Tusharmalik** [comment]
@philipto [www.shiksha.com](https://www.shiksha.com/) can't be the official domain for **Krishna Engineering College**, it's a general purpose college searching website. You can search any college on this website and will receive information regarding the same. 

Official domain for **Krishna Engineering College** are http://www.krishnacollege.ac.in/ , http://www.shrikrishnacollege.com/

**Comment by philipto** [comment]
@Tusharmalik The first verification stage is complete: the official domain for  **Krishna Engineering College** is [www.shiksha.com](https://www.shiksha.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.shiksha.com/college/krishna-engineering-college-ghaziabad-24915/course-b-tech-in-computer-science-and-engineering-artificial-intelligence-896901

**Comment by Tusharmalik** [comment]
@Philipto, I am concerned that my comments may not be receiving the necessary attention. Please proceed with the verification as you deem appropriate.

**Comment by philipto** [comment]
@Tusharmalik Thank you for the clarification. I re-reviewed the content and completely agree with you. 
Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
