### PR TITLE
Create gimnazijatvrdjava.txt

### PR DESCRIPTION
**Pull request by milosmirkovic**

### CODE REVIEW

**Comment by philipto** [comment]
@milosmirkovic Could you please tell us how old your students are? The website features courses for children. We do not recommend professional IDEs for children; they can be satisfied with community versions such as PyCharm Community Edition.

**Comment by philipto** [comment]
@milosmirkovic You might miss my previous comment. Please react.

**Comment by milosmirkovic** [comment]
@philipto Students are from 15 to 18 age-old. 

Please check _Secondary School / Gymnasium_: https://en.wikipedia.org/wiki/Education_in_Serbia#School_Stages

Thanks!

**Comment by philipto** [comment]
@milosmirkovic Thank you for the clarification. My impression was based on the page at https://www.tvrdjava.edu.rs/skola/o-skoli/

It says (Google translated):
> THE PROGRAM IS APPROVED BY THE MINISTRY OF EDUCATION
The new verified private primary school "FORTRESS" provides children with a stimulating environment for progress and work. In the elementary school "TVRĐAVA", the program is realized according to the regulations of the Ministry of Education, Science and Technological Development, but in a way that allows children to be creators of teaching, active participants and initiators, and teachers guides through the educational process.

It clearly creates an impression of a primary/elementary school, and given that all photos at the website show children under 12 of age, it's not easy to guess that the school teaches people in their 15-18.

Certainly, the pull request is approved and merged, as per your clarification. Please request the free licenses at https://www.jetbrains.com/shop/eform/students. Please wait for about 30 minutes before start requesting to allow the changes to propagate through our system. Thank you!

**Pull request merged**
