### PR TITLE
add cultura inglesa s/a domain

### PR DESCRIPTION
**Pull request by Yuri-Bartochevis**
…ho provides a different way to teach english focused on student's goals

### CODE REVIEW

**Comment by philipto** [comment]
@Yuri-Bartochevis Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Yuri-Bartochevis You might miss my previous comment. Please react.

**Comment by Yuri-Bartochevis** [comment]
@philipto
Now I got your comment.
I couldn't find proof about the students' domain, you're right, I'm not sure about the main reason but students here have a different domain from the teachers, Teachers have an email Domain similar to the website domain but all students have a different provider named "cooltura".
Anyway. I'll ask for some employee there if I can be supported by the school and I'll contact you.
for now, I only can record accessing the domain via Gmail and show you, all access into Google Class Room.

thank you for reporting me.
Bests,
Yuri.

**Comment by philipto** [comment]
@Yuri-Bartochevis Until you don't have a proof of the domain ownership, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students). I have to close this request without merging. Please reopen the request or make a new one as soon as you have a proof of the official domain recognition by the school. Thank you for understanding!

**Pull request closed without merging**
