### PR TITLE
Create bsg.txt

### PR DESCRIPTION
**Pull request by winer222**

### CODE REVIEW

**Comment by philipto** [comment]
@winer222 Could you please mention the following in your comment to the request:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by winer222** [comment]
http://www.britishschoolgeneva.ch/
http://www.britishschoolgeneva.ch/docs/Curriculum.pdf
I have no written proof, but it is the email that all students get allocated when we join and the domain name shows that as BSG (in **BSG**.email) stands for **B**ritish **S**chool of **G**eneva

**Comment by winer222** [comment]
image
The only other proof is an example of a teacher sending me an email about my submission of an assignment.
I have censored the names of the teachers that are contacting me, but they are the teachers.

**Comment by philipto** [comment]
@winer222 Thank you for the clarification. Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age.

**Pull request merged**
