### PR TITLE
Create igs-rodenberg.txt

### PR DESCRIPTION
**Pull request by lShkipeRl**
IGS Rodenberg
igs Rodenberg
igs
https://www.igs-rodenberg.de
igs-rodenberg.net

### CODE REVIEW

**Comment by philipto** [comment]
@lShkipeRl lib/domain/net/igs-rodenberg.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@lShkipeRl First stage of verification passed, official domain is [igs-rodenberg.de](https://igs-rodenberg.de) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.igs-rodenberg.de/das-sind-wir/foerderverein

**Comment by lShkipeRl** [comment]
Thank you very much. We're really looking forward to it.

**Comment by philipto** [comment]
@lShkipeRl Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
