### PR TITLE
Rename dmu.txt to my365.dmu.txt

### PR DESCRIPTION
**Pull request by Arawn-Davies**
Not sure if this will help, but I went on a placement and would like to renew my student license as I am doing my final year of Comp Sci at DMU, and we use @my365.dmu.ac.uk as an email domain now. Annoyingly it seems my email is blocked for some reason and I would like to know why but not sure who to ask :/ 
 
I can't guarantee we receive emails directed at @dmu.ac.uk anymore

### CODE REVIEW

**Comment by philipto** [comment]
@Arawn-Davies lib/domains/uk/ac/my365.dmu.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Arawn-Davies** [comment]
Hi @philipto , I've updated it to (hopefully) the correct format, hope it's okay 👍🏽 
Thanks :)

**Comment by philipto** [comment]
@Arawn-Davies I am sorry, the domain dmu.ac.uk is removed from our trusted domains list because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Comment by Arawn-Davies** [comment]
The email service is Microsoft 365 and only members of staff/faculty/currently-enrolled students, and it's Microsoft 365 (plus it's a fee-paying UK university), it isn't possible for someone to register an email there if they're not employed/enrolled. 

I've contacted JetBrains numerous times but haven't had a reply yet, despite me uploading the official document and taking a picture of my ID.

**Pull request closed without merging**
