### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Elish9588**
#### Institution/School Name 
{New Cairo Academy CIS}

#### Instiution/School Website
{https://cis.edu.eg/}

#### Email Users

*Please place an x between the square brackets if yes*
- [ x] Students
- [ ] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [ ] Graduate School
- [x ] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [ ] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by philipto** [comment]
@Elish9588 First stage of verification passed, official domain is [cis.edu.eg](https://cis.edu.eg) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Elish9588 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by Elish9588** [comment]
> @Elish9588 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

But it still not working on site " Your email address does not belong to any university that we know. You can apply with another method (see tabs above) or [add your school](https://www.jetbrains.com/shop/eform/students/contributeUniversity?email=C2100054%40cis.edu.eg) to JetBrains' list."

**Comment by Elish9588** [comment]
> @Elish9588 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

@philipto  but it still not working on the site "Your email address does not belong to any university that we know. You can apply with another method (see tabs above) or [add your school](https://www.jetbrains.com/shop/eform/students/contributeUniversity?email=C2100054%40cis.edu.eg) to JetBrains' list."

**Pull request merged**
