### PR TITLE
Yoobee College of Design

### PR DESCRIPTION
**Pull request by Skiviper-AJM**
NZ, Wellington, Has a bachelor of software engineering course

### CODE REVIEW

**Comment by philipto** [comment]
@Skiviper-AJM Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by Skiviper-AJM** [comment]
this was the closest to official instruction i received on the matter,

[image: image.png]

I have forwarded you this email as well.

**Comment by philipto** [comment]
@Skiviper-AJM Thank you for trying to provide us with the proof. Could you please upload it as a comment here using your browser? GitHub strips out all attachments to comments if they are sent by email.

Thank you!

**Comment by Skiviper-AJM** [comment]
image

Apologies for that! Didn't realise github couldn't pull files from email - is that better?

**Comment by philipto** [comment]
@Skiviper-AJM  Thank you for the clarifications. Pull request merged.

**Pull request merged**
