### PR TITLE
Updating Andover Public Schools Email Domain

### PR DESCRIPTION
**Pull request by rishi763**
Our school system has updated email domains from k12.andoverma.us to student.andoverma.us and this pull request reflects that change.

### CODE REVIEW

**Comment by philipto** [comment]
@rishi763 Would you please provide us with a URL of the official website page that confirms the transition?
In particular, it help if you can provide us with:
* the school official website URL
* the school street address, including city and country
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by Blitheness** [comment]
Hey @philipto, this looks like the announcement - https://www.aps1.net/CivicAlerts.aspx?AID=1130

**Comment by rishi763** [comment]
Website: https://aps1.net/
Address: 80 Shawsheen Rd, Andover, MA 01810 USA
@Blitheness  has the announcement for the email domain change.

**Comment by philipto** [comment]
@rishi763  Thank you for the clarifications and the update. Pull request merged.

**Pull request merged**
