### PR TITLE
UNIDESC

### PR DESCRIPTION
**Pull request by LeandroJOA**
CENTRO UNIVERSITÁRIO DE DESENVOLVIMENTO DO CENTRO-OESTE
UNIVERSITY CENTER FOR WEST CENTER DEVELOPMENT

### CODE REVIEW

**Comment by philipto** [comment]
@LeandroJOA Please provide us with:
- the school official website URL
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by LeandroJOA** [comment]
School official website URL:  https://www.unidesc.edu.br/

<https://www.unidesc.edu.br/>
IT-related long-term course:
https://www.unidesc.edu.br/graduacao/sistemas-de-informacao/

Email proof: https://www.instagram.com/p/B3VPXtolAyp/ (*Attached as well*)

*Note: On the right-top of the official site on the first link, you can see
that this instagram account is their official one!*

**Comment by LeandroJOA** [comment]
School official website URL:  https://www.unidesc.edu.br/

IT-related long-term course: https://www.unidesc.edu.br/graduacao/sistemas-de-informacao/

Email proof: https://www.instagram.com/p/B3VPXtolAyp/ (Attached as well)
UNIDESC Email


Note: On the right-top of the official site on the first link, you can see that this instagram account is their official one!

**Comment by LeandroJOA** [comment]
School official website URL:  https://www.unidesc.edu.br/

IT-related long-term course: https://www.unidesc.edu.br/graduacao/sistemas-de-informacao/

Email proof: https://www.instagram.com/p/B3VPXtolAyp/ (**Attached as well**)

**Note: On the right-top of the official site on the first link, you can see that this instagram account is their official one!**

UNIDESC Email

**Comment by philipto** [comment]
@LeandroJOA Thank you for the clarification. Pull request merged.

**Pull request merged**
