### PR TITLE
Add Generated File

### PR DESCRIPTION
**Pull request by sgamb**
42 Yerevan is a branch of a 42.fr
You can contact us with info@42yerevan.am
Have a good day!!

### CODE REVIEW

**Comment by philipto** [comment]
@sgamb First stage of verification passed, official domain is [42yerevan.am](https://42yerevan.am) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by sgamb** [comment]
That's right. Thank you for the update
serge

**Comment by philipto** [comment]
@sgamb Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by sgamb** [comment]
No worries, thanks for the update!
What's next?

**Pull request merged**
