### PR TITLE
Add INSA Lyon engineering school

### PR DESCRIPTION
**Pull request by jbontik**

### CODE REVIEW

**Comment by philipto** [comment]
@jbontik according #2630 the main university domain is already added. Could you please clarify who exactly uses alumni-insa-lyon domain, and what is full domain name (alumni-insa-lyon.org?)
Thank you.

**Comment by philipto** [comment]
@jbontik You might miss my previous comment. Please react.

**Comment by jbontik** [comment]
@philipto "alumni-insa-lyon.org" is used by INSA Lyon alumni.
The full domain name is: alumni-insa-lyon.org.

Thank you.

**Comment by philipto** [comment]
@jbontik Thank you for the clarification! Do I understand you correctly, that "alumni" in your answer means people who already graduated from the university, and they are no longer students?

**Comment by jbontik** [comment]
@philipto Your understanding is 100% correct : )

**Comment by philipto** [comment]
@jbontik Thank you for the clarification. This is what I was afraid of. Regrettably, I can not add this domain to this repository, because we do not provide free educational licenses to alumni. We provide them to teachers and students only. Graduate students (also known as alumni) are eligible for 25% discount when purchasing regular non-educational subscription to any of JetBrains tools.

Thus, I have to close this request without merging. Thank you for the understanding!

**Pull request closed without merging**
