### PR TITLE
poornima.txt

### PR DESCRIPTION
**Pull request by Rohitshrimal**
This is my college official site. You can visit and verify .http://poornima.org

### CODE REVIEW

**Comment by philipto** [comment]
@Rohitshrimal Pull request merged. I appreciate if you change the name of the college to "Poornima College" or another officially recognized name, to make it easy to find it. This is international repository, more detailed name will help people to find it.

**Comment by Rohitshrimal** [comment]
Hello Philip ,

@PhilipTorchinsky   thanks for the update. My college name is "Poornima
Institute of Engineering & Technology". But the domain url is Poornima.org
. So according to this please suggest me what name ,I should put & where.. ?

Thanks
Rohit

**Comment by philipto** [comment]
@Rohitshrimal The filename, lib/domains/org/poornima.txt, is correct, the content of the file would better be "Poornima Institute of Engineering & Technology".

**Comment by Rohitshrimal** [comment]
Sounds cool.

Thanks

**Pull request merged**
