### PR TITLE
Add new domain NUOL

### PR DESCRIPTION
**Pull request by smallnoys**
[fe-nuol.txt](https://github.com/JetBrains/swot/files/10328247/fe-nuol.txt)

### CODE REVIEW

**Comment by philipto** [comment]
@smallnoys First stage of verification passed, official domain is [nuol.edu.la](https://nuol.edu.la) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://fe.nuol.edu.la/en/News

**Comment by smallnoys** [comment]
thank you sir for your review

**Comment by philipto** [comment]
@smallnoys Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by smallnoys** [comment]
thank you @philipto

**Pull request merged**
