### PR TITLE
Create qerdp.txt

### PR DESCRIPTION
**Pull request by jamestan21**
URL: [https://www.qebarnet.co.uk/](https://www.qebarnet.co.uk/)

### CODE REVIEW

**Comment by philipto** [comment]
@jamestan21 Please rename uk/co/qerdp.txt to lib/domain/uk/co/qerdp.txt. Thank you.

**Comment by philipto** [comment]
@jamestan21 You might miss my previous comment. Please check the issue described above and react. Thank you!

**Comment by jamestan21** [comment]
Awfully sorry about the delay. Is this better?

**Comment by philipto** [comment]
@jamestan21 Pull request merged. Thank you!

**Pull request merged**
