### PR TITLE
Adding Akademi Komunitas Negeri Putra Sang Fajar Blitar/State Community Academy Putra Sang Fajar Blitar

### PR DESCRIPTION
**Pull request by ambonxnobody**

### CODE REVIEW

**Comment by philipto** [comment]
@ambonxnobody First stage of verification passed, official domain is [akb.ac.id](https://akb.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by ambonxnobody** [comment]
> @ambonxnobody First stage of verification passed, official domain is [akb.ac.id](https://akb.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Yes, thanks. And if you probably wondering about the reason I did the pull request twice is because official email holder of akb.ac.id told me to use my student email instead, they said that the official email holder is still busy out of town thing.

**Comment by philipto** [comment]
@ambonxnobody  Thank you for the clarifications. Pull request merged.

**Comment by ambonxnobody** [comment]
> @ambonxnobody  Thank you for the clarifications. Pull request merged.

Thanks a lot Sir @philipto

**Comment by ambonxnobody** [comment]
And anyway, I'm sorry if I'm bothering you, what happen after merge? Can I just sign up for student account on Jetbrain? @philipto

**Pull request merged**
