### PR TITLE
Cscapitale establishment, School La camaradière

### PR DESCRIPTION
**Pull request by Abstra208**

### CODE REVIEW

**Comment by philipto** [comment]
@Abstra208 First stage of verification passed, official domain is [cssc.gouv.qc.ca](https://cssc.gouv.qc.ca) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://ecole-secondairerogercomtois.cssc.gouv.qc.ca/wp-content/uploads/2020/06/plan-de-travail-sec-3-du-15-au-23-juin-2020.pdf

**Comment by Abstra208** [comment]
Just to precise:
Students' email ends in
 - @educ.cscapitale.qc.ca

The school website added in this fork is:
 - https://ecole-secondairedelacamaradiere.cssc.gouv.qc.ca/

**Comment by INEI2333** [comment]
Forgive my many interruptions.
[additional notes]
In the Student Guide for the year 2023, on the second page, in the middle of the page, it says: "The domain name of the email sent from the university side is '@vc.ibaraki.ac.jp'."
The student guide as well as related screenshot were sent as an attachment and can also be downloaded from the student affairs page "https://www.ibaraki.ac.jp/student/guidebook/" on the Ibaraki University website.
Screenshot 2024-02-28 121556
[IUguidebook_2023.pdf](https://github.com/JetBrains/swot/files/14428842/IUguidebook_2023.pdf)

**Comment by philipto** [comment]
@Abstra208 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
