### PR TITLE
Added Institute of Nuclear Physics Polish Academy of Sciences

### PR DESCRIPTION
**Pull request by b3rnoulli**

### CODE REVIEW

**Comment by philipto** [comment]
@b3rnoulli Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

Please notice that if your organization is primarily a research institution, you are not eligible for inclusion to this repository list. Instead, please email sales@jetbrains.com in order to receive a discount for academic institution to buy JetBrains All Products Pack subscription with a significant discount.

**Comment by philipto** [comment]
@b3rnoulli You might miss my previous comment. Please reply.

**Comment by b3rnoulli** [comment]
Sorry for late replay.
Institute of Nuclear Physics is primarily a research institution, however it runs International PhD Studies  for around 100 students. Almost every single course offered by the Institute is IT-related which means it requires student to write code to solves equations or simulate behavior of complex system. (e.g Quantum Mechanics and Theory of Relativity , Machine Learning in Physics, Monte Carlo Methods in Physics)

- the URL is the same as domain I submitted
- url to the list of offered courses (unfortunately it is available only in Polish) https://www.ifj.edu.pl/msd/index.php?menu=program
- url to login Institute email portal: https://webmail.ifj.edu.pl

**Comment by philipto** [comment]
@b3rnoulli I am sorry, but:
```
$ host ifj.krakow.pl
Host ifj.krakow.pl not found: 3(NXDOMAIN)
```
Are you sure that you actually wish to submit ifj.krakow.pl domain? It does not exist, and this is why I can not add it here. If you wish me to add ifj.edu.pl, it's fine, you explained the matter, and it makes sense to add this domain for the students. However, filename for this domain has to be lib/domains/pl/edu/ifj.txt.

Please modify or cancel your request. Thank you!

**Comment by philipto** [comment]
@b3rnoulli Pull request merged. Thank you!

**Pull request merged**
