### PR TITLE
Add Georg-Klingenberg-School

### PR DESCRIPTION
**Pull request by Ente**
Adding the Georg-Klingenberg-School with the domain gkbs.berlin

### CODE REVIEW

**Comment by philipto** [comment]
@Ente Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by Ente** [comment]
Hey, sadly it's quite complicated to provide a proof. I could only attach an screenshot, which shows my email account with my schools name.
Otherwise I wouldn't have any other idea on how to provide another proof.

**Comment by philipto** [comment]
@Ente If you received an instruction from the school (at the time of enrollment or later) that tells you to use this email address, it is sufficient. Please attach the copy of such instruction to a comment here. Thank you.

**Comment by Ente** [comment]
@philipto We've luckily got an Instruction email, in which my school explains how to log in to the  school servers and so on.
It is in German and doesn't have any school logo or anything on it, is that a problem?

**Comment by philipto** [comment]
@Ente It is not a problem. You can make a screenshot with an email. If you have it printed you can attach a photo of it. Certainly, you can remove all personal details from there. However it would be nice to leave visible a name and a position of a person who signed the letter.

Thank you!

**Comment by Ente** [comment]
My fault, it also has the school logo on it, there was an PDF attachement aswell
[Einweisung_Schulcloud_und_Email.pdf](https://github.com/JetBrains/swot/files/5789981/Einweisung_Schulcloud_und_Email.pdf)

**Comment by philipto** [comment]
@Ente Thank you for the clarification. Pull request merged.

**Comment by Ente** [comment]
Thanks, and no problem.

**Pull request merged**
