### PR TITLE
mail.txt

### PR DESCRIPTION
**Pull request by nielsotto**

### CODE REVIEW

**Comment by philipto** [comment]
@nielsotto Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university

**Comment by nielsotto** [comment]
@philipto http://www.dmjx.dk/uddannelser/interaktivt-design Sorry it's in Danish. A translate plugin should do the job though

**Comment by philipto** [comment]
@nielsotto Thank you for the clarification! Pull request merged.

**Comment by nielsotto** [comment]
@philipto that's awesome! I still can't create a students account though. The mail domain is mail.dmjx.dk. Did I create it correctly?

**Pull request merged**
