### PR TITLE
Add Pawnee High School

### PR DESCRIPTION
**Pull request by randomdog29328**
The official school website is https://www.pawneeschools.com. pawneeschools.org is only used for Google Workspace and for such reason **will time out.**
To find courses that are offered here (IT related too), see https://www.pawneeschools.com/vimages/shared/vnews/stories/609c1f1b1d62f/2021-2022FINALStudentCoursePlanningBook.pdf.
Once again, pawneeschools.org WILL TIME OUT, https://www.pawneeschools.com is the domain the actual website is hosted on. pawneeschools.org is only used for email, etc.
Thank you.

### CODE REVIEW

**Comment by mirarad** [comment]
The official school website is: http://ssnikolateslaleposavic.edu.rs
[file.zip](https://github.com/JetBrains/swot/files/8863786/file.zip)

**Comment by randomdog29328** [comment]
> The official school website is: http://ssnikolateslaleposavic.edu.rs [file.zip](https://github.com/JetBrains/swot/files/8863786/file.zip)

what?

**Comment by mirarad** [comment]
> > The official school website is: http://ssnikolateslaleposavic.edu.rs 
This is generated zip file: 
(https://github.com/JetBrains/swot/files/8863786/file.zip)
> 
> what?

**Comment by philipto** [comment]
@randomdog29328 Do I understand correctly that the school email address pattern is <username>@pawneeschools.org. Thus, only the domain pawneeschools.org has to be in the repository, not www.pawneeschools.com. Am I right?

**Comment by randomdog29328** [comment]
> @randomdog29328 Do I understand correctly that the school email address pattern is @pawneeschools.org. Thus, only the domain pawneeschools.org has to be in the repository, not [www.pawneeschools.com](http://www.pawneeschools.com). Am I right?

You are correct, and I'll fix that right now.

**Comment by philipto** [comment]
@randomdog29328 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
