### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by murrayi1967**
Add Gordonstoun School to domains

### CODE REVIEW

**Comment by philipto** [comment]
Please kindly provide the full name of your school on the first line of the file in your request

**Comment by murrayi1967** [comment]
Morning,
Sorry I thought I had, now modified.

Thanks,

Iain


Iain Murray
AHP Cumming House | Head of Computing
T: +44 (0)1343 837936
***@***.***

[cid:gordonstoun_logo_2019_secondery-02_aaa2afd6-d79d-4e0e-9929-bd868a2f9241.png]<http://gordonstoun.org.uk/>

[cid:socialicons_fb_2eeef1c5-2342-47a2-b2b0-99292fc17e5d.png]<https://www.facebook.com/GordonstounSchool/>[cid:socialicons_twx_d4147b2d-e3fe-4c28-bae4-dae13432a55d.png]<https://twitter.com/gordonstoun><https://twitter.com/gordonstoun>[cid:socialicons_ig_61b7ccc1-dc40-42b2-958e-71677ea03663.png]<https://www.instagram.com/gordonstounschool/>[cid:socialicons_yt_776b1847-b494-4fb9-914a-dece96f7cc3e.png]<https://www.youtube.com/c/gordonstounschool>[cid:socialicons_li_7eb97b91-590e-447e-8d17-2664f78d5f03.png]<https://www.linkedin.com/company/gordonstoun-school/>

Gordonstoun Schools Limited, Elgin, Moray, Scotland, IV30 5RF
Scottish Charity Number SC037867. Company Registered in England No 288105
Registered Office c/o VWV LLP, 24 King William Street, London EC4R 9AT

Gordonstoun Schools Limited Privacy Policy can be accessed here<http://www.gordonstoun.org.uk/privacy-policy>

**Comment by philipto** [comment]
Please kindly provide the full name of your school on the first line of the file in your request

**Comment by philipto** [comment]
@murrayi1967 I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Pull request closed without merging**
