### PR TITLE
Add Ekotrust

### PR DESCRIPTION
**Pull request by Inar-k**

### CODE REVIEW

**Comment by philipto** [comment]
@Inar-k Could you please provide us with:
* the school official website URL
* the school street address, including city and country
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you!

**Comment by philipto** [comment]
@Inar-k You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@Inar-k I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by Inar-k** [comment]
> @Inar-k I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

I have submitted a updated pull request at

https://github.com/JetBrains/swot/pull/19811

**Pull request closed without merging**
