### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by YoramP**
Added AMIT NAHSHON to education domains

### CODE REVIEW

**Comment by YoramP** [comment]
[nhs.txt](https://github.com/JetBrains/swot/files/7964184/nhs.txt)

**Comment by philipto** [comment]
@YoramP Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by YoramP** [comment]
Hi,

Official school website URL: https://nachshon.tik-tak.net/
School's address: 
Modi'im St 10, Shoham, Israel

Computer science class page on school website:
https://nachshon.tik-tak.net/%d7%9e%d7%a7%d7%a6%d7%95%d7%a2%d7%95%d7%aa-%d7%9c%d7%99%d7%9e%d7%95%d7%93-%d7%97%d7%98%d7%a2/%d7%9e%d7%92%d7%9e%d7%95%d7%aa/%d7%9e%d7%93%d7%a2%d7%99-%d7%94%d7%9e%d7%97%d7%a9%d7%91/

A proof that the email domain is the official domain:
https://i.imagesup.co/images2/549e6d9f64c2493664a749b775622f0d383d9360.png

Thanks,
Yoram

**Comment by philipto** [comment]
@YoramP Thank you for the clarification. Pull request merged.

**Pull request merged**
