### PR TITLE
add new university

### PR DESCRIPTION
**Pull request by ashishmangla0**
gdgoenka university gurgaon

### CODE REVIEW

**Comment by philipto** [comment]
@ashishmangla0 Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by ashishmangla0** [comment]
image

**Comment by ashishmangla0** [comment]
@philipto I uploaded thinks you mentioned.

**Comment by ashishmangla0** [comment]
@philiptoI want to mention they have multiple domains like http://gdgoenka.ac.in/ only for emails. and for student/ teacher logins they are using "gdgu.org" only for emails.

**Comment by philipto** [comment]
@ashishmangla0 Please rename lib/domains/org/gdgu to lib/domains/org/gdgu.txt. 

For the record: the screenshot above is not a proof, it just shows that a person who called themselves "Anjani K Goenka" registered gdgu.org domain with GoDaddy. It does not prove anything, because GoDaddy does not check an identity correctness of a person who pretends to be a domain registrant, and even if they checked it, a name of the person can not prove that the university officially recognizes the domain as the one registered for students and teachers.

Actual proof is, for example, here: https://www.ugc.ac.in/uni_contactinfo.aspx?id=692

**Comment by philipto** [comment]
@ashishmangla0 I am closing this request as already obsoleted. Thank you.

**Pull request closed without merging**
