### PR TITLE
Create livenau.txt

### PR DESCRIPTION
**Pull request by Palaxer**
Please add national aviation university.
nau.edu.ua it is a official site, but livenau.net for the students

### CODE REVIEW

**Comment by zweizwei** [comment]
the university domain is http://nau.edu.ua/en/ - please provide some proof that the domain belongs to the university and is used for email

**Comment by Palaxer** [comment]
dream spark

**Comment by Palaxer** [comment]
dream spark

**Comment by zweizwei** [comment]
@Palaxer thanks a lot, merging

**Pull request merged**
