### PR TITLE
Create edumail.txt

### PR DESCRIPTION
**Pull request by seanmcgaughey**

### CODE REVIEW

**Comment by philipto** [comment]
@seanmcgaughey I am sorry, but on the first glance this email domain looks like the one belonged to a government agency, not a university or college. Why did you decide to add it to this repository? Is there a specific university or college in Victoria state which uses this email domain for its students?

**Comment by seanmcgaughey** [comment]
Hi Philip,

Thank you for getting back to me. My wife is a teacher at Port Philip
Specialist School (http://www.portphillip.vic.edu.au/), but all staff and
students in government schools in Victoria Australia get a generic edumail
address, rather than an email address specific to the particular school.
I'd say This is because the Department of Education centrally manages the
email infrastructure and accounts. This email domain currently services
over 1500 government schools in Victoria, and over 40,000 teachers (
http://www.education.vic.gov.au/Documents/about/department/summarystatssnapshot.docx),
so I'm really hoping it qualifies under your rules around making a license
available to teachers.

Thank you and have a great day!

Regards,
Sean.

**Comment by philipto** [comment]
@seanmcgaughey Thank you for the details. While we are proud to be able to serve such a broad and important community, we must double think before proceed. It may be much better and quicker to apply for classroom licenses in this case. A teacher can e-mail to classroom@jetbrains.com and ask for reasonable number of classroom licenses for her or his students, and this way seems being favorable in your case. 

Thus, you may wish to close this request and email classroom@jetbrains.com and get the licenses instantly. Otherwise we'll back to this issue in approximately one week. Thank you for your understanding!

**Comment by philipto** [comment]
@seanmcgaughey I am sorry for not being able to approve an adding of edumail.vic.gov.au to this repository of colleges' and universities' email domains. The main reason is that the email domain does not belong to a particular university or college. Please, email classroom@jetbrains.com to get free licenses for JetBrains tools for all the students and teachers who actually need them among those 1500 government schools in Victoria. This is a correct way to resolve the issue. Thank you for reaching out, and your patience and understanding!

**Pull request closed without merging**
