### PR TITLE
Debreceni Ady Endre Gimnázium

### PR DESCRIPTION
**Pull request by scallyt**

### CODE REVIEW

**Comment by scallyt** [comment]
This school is located in Debrecen, Hungary
The domain  @adygimi.com
Location: https://maps.app.goo.gl/sk4qLCpxdhKqK9A96

**Comment by philipto** [comment]
@scallyt First stage of verification passed, official domain for **Debreceni Ady Endre Gimnázium** is [adygimi.hu](https://adygimi.hu) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by scallyt** [comment]
@philipto Hi. Yes, [adygimi.hu](https://www.adygimi.hu/) is my school website. I apologize, I thought you needed the email domain.

**Comment by scallyt** [comment]
@philipto Yeah you need to rename the file for `lib/domains/com/adygimi.txt` my becuse school email is adygimi.com

(Sry for my eanglish)

**Comment by philipto** [comment]
@scallyt  Thank you for the clarifications. Pull request merged.

**Pull request merged**
