### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Axcelers**

### CODE REVIEW

**Comment by philipto** [comment]
@Axcelers First stage of verification passed, official domain is [beverlyschools.org](https://beverlyschools.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://bms.beverlyschools.org/apps/news/article/1646016

**Comment by Axcelers** [comment]
@philipto Any update?

**Review by Axcelers — COMMENTED** [review]
good

**Comment by philipto** [comment]
@Axcelers Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
