### PR TITLE
Create bsd405

### PR DESCRIPTION
**Pull request by issyrocks12**
Emails are @bsd405.org (aligns with main domain page) 

Link here should be enough proof for comp sci: http://www.bsd405.org/about/initiatives/k12cs/

### CODE REVIEW

**Comment by philipto** [comment]
@issyrocks12 The file lib/domains/us/wa/k12/bsd405 is to represent a domain bsd405.k12.wa.us. Is it the domain which you wish to add? If yes, please change the name from lib/domains/us/wa/k12/bsd405 to lib/domains/us/wa/k12/bsd405.txt to reflect this repository rules, and I'll satisfy the request as soon as possible.

**Comment by philipto** [comment]
@issyrocks12 You might miss my previous comment (see above). Could you please make the changes requested? If you are unable to update the request, I have to close it without merging. Thank you!

**Comment by issyrocks12** [comment]
@philipto Apologies, I missed that. The domain is actually bsd405.org NOT bsd405.k12.wa.us I have updated it accordingly.

**Comment by philipto** [comment]
@issyrocks12 Pull request merged. Thank you!

**Pull request merged**
