### PR TITLE
Create twain239.txt and delete the folder because I'm dumb

### PR DESCRIPTION
**Pull request by Arze1**

### CODE REVIEW

**Comment by Arze1** [comment]
I'm really dumb didnt fully understand how it works, fixed it though

**Comment by Arze1** [comment]
Thanks

**Comment by philipto** [comment]
@Arze1 No problem, you made it correct. In fact, I already added the file for the upper level domain, but this change does not hurt. Pull request merged. Thank you!

**Comment by philipto** [comment]
@Arze1 Yes, pull request merged.

**Comment by Arze1** [comment]
How long until it becomes available on the website?

**Comment by Arze1** [comment]
@philipto Thanks alot my only question is when will it be available for use on the website? I enter my email and it says it's invalid, Thanks in advance.

**Comment by philipto** [comment]
@Arze1 It typically takes about 15 minutes, sometimes up to 30 minutes. Thank you!

**Comment by Arze1** [comment]
Yeah I got, ty ;)

**Pull request merged**
