### PR TITLE
Create thcsthuanhung.txt and penphy.txt

### PR DESCRIPTION
**Pull request by ncdai3651408**
Add domain **thcsthuanhung.edu.vn** and **penphy.edu.vn**
> We add 2 domains because our school uses 2 domains to provide Email for Teachers and Students (Proof of using 2 domains in **4. An URL of a page at the official school website that says that students use this email domain**).

**1.** The school official website URL
**https://thcsthuanhung.edu.vn/** 

**2.** The school street address, including the city
**Tan Phu Area, Thuan Hung Ward, Thot Not District, Can Tho City, Vietnam**

**3.** An URL of a page on the official website where the school offers an IT-related long-term course
- https://thcsthuanhung.edu.vn/to-toan/introduction-to-php-syllabus-60.html
- https://thcsthuanhung.edu.vn/to-toan/introduction-to-web-design-syllabus-61.html
- https://thcsthuanhung.edu.vn/to-toan/introduction-to-wordpress-syllabus-62.html

Currently, we have courses for students at the beginner level, you can see the syllabus at the 3 links above.

In addition, we always organize and participate in IT contests _(Competitive Programming, Creative Software)_ for students. The school always creates conditions for students to access information technology, teaches them to use programming languages, explores interesting topics based on designed courses _(Ex: Web Design, Wordpress, PHP, Pascal...)_. From the results of these contest, our school will plan to expand the content of these courses.

You can see some pictures of the IT contest that we have organized and participated in here:
- https://thcsthuanhung.edu.vn/photos/cuoc-thi/tin-hoc-tre-2014-3/
- https://thcsthuanhung.edu.vn/photos/cuoc-thi/sang-tao-thanh-thieu-nien-cap-tp-2016-2017-2/
- https://thcsthuanhung.edu.vn/photos/cuoc-thi/tin-hoc-tre-2018-1/

**4.** An URL of a page at the official school website that says that students use this email domain
- https://thcsthuanhung.edu.vn/cong-nghe-thong-tin/google-cung-cap-mien-phi-bo-ung-dung-google-workspace-for-education-ho-tro-viec-day-va-hoc-50.html
- Screenshot :

official school website that says that students use this email domain 2

---
Finally, we hope the Pull Request is accepted.
**Thanks to JetBrains for creating many conditions to support Schools around the world!**

### CODE REVIEW

**Comment by ncdai3651408** [comment]
Hi @philipto,

Please consider Merge Code to help us.

Thank you!

**Comment by ncdai3651408** [comment]
Hi @philipto ,
We are still waiting for good news from you!
Thank you!

**Comment by thanhutnguyen19** [comment]
Hi @philipto 
I'm an IT Teacher at this School, I hope you accept the Pull Request 🎉 
Have a nice day 😄

**Comment by ncdai3651408** [comment]
Hi @philipto 
We are still waiting for good news from you! ❤️

**Comment by ncdai3651408** [comment]
Hello @philipto , We are still waiting for good news from you!

**Comment by ncdai3651408** [comment]
Screen of **Google Admin** showing the two domains used

google-admin

**Comment by ncdai3651408** [comment]
Hi @philipto , we hope the Pull Request is accepted. Thanks.

**Comment by ncdai3651408** [comment]
Hi @philipto , looking forward to hearing from you soon!

**Comment by ncdai3651408** [comment]
Hi @philipto , looking forward to hearing from you soon!

**Comment by ncdai3651408** [comment]
# Whois Information

VNNIC INTERNET RESOURCE WHOIS INFORMATION (https://vnnic.vn/whois-information?lang=en)

Domain : [thcsthuanhung.edu.vn](https://thcsthuanhung.edu.vn/)

whois-thcsthuanhung

**Comment by ncdai3651408** [comment]
Hi @philipto , Have you seen our request?

**Comment by philipto** [comment]
@ncdai3651408 Thank you very much for your patience and all the clarifications. Pull request is now merged.

**Comment by ncdai3651408** [comment]
@philipto Thank you very much for considering our request carefully. Have a nice day.

**Pull request merged**
