### PR TITLE
Add WRDSB (Canada) email domains

### PR DESCRIPTION
**Pull request by lchski**
[Waterloo Region District School Board](http://www.wrdsb.ca/) has three email paths for students and staff: @ins.wrdsb.ca, @googleapps.wrdsb.ca, and @wrdsb.on.ca.

### CODE REVIEW

**Comment by philipto** [comment]
@lchski I am sorry for a delay with processing your pull request. Could you please give us a reference to a page on the official website where we can read the policy/rules regarding the domains mentioned in the request? This repository helps to grant free licenes to students and teachers, but not to alumni or researchers, because the licenses restrict their use to educational purposes.

Please also provide us with a link to a description of the course(s) in the schools of your district which are somehow related to IT: we need to ensure that there are courses in the schools which our tools can be successfully used for.

**Comment by lchski** [comment]
For sure! I appreciate the rigour.

Unfortunately, I can’t find a specific policy that covers *all* the situations, but I’ve got one policy and a few other resources that hopefully shed light on the (admittedly rather complicated) email situation:

* The policy, [Administrative Procedure 4060](http://www.wrdsb.ca/wp-content/uploads/AP4050_Waterworks.pdf). This is from 2007, so it is admittedly somewhat dated, but it provides (in section 7.1.1, on pages 2 and 3) a list of account types—alumni and researchers are not included, only current staff in various capacities of the board. This document doesn’t provide any mention of student accounts, as student email accounts weren’t around in 2007.
* [The online login page](http://waterworks.wrdsb.on.ca) for the school’s @ins.wrdsb.ca email system notes that “All Students’ passwords will be reset as of Wednesday, August 31, 2015.” This is as close as I can find to publicly published policy explaining that user accounts are reset each year—past students lose their accounts.
* For a list of teacher accounts, to verify that they use the domain I expressed, see [here](http://wci.wrdsb.ca/about/staff-list/) and [here](http://bci.wrdsb.ca/about/staff-list/). Note that on the second list, one of the teachers has opted to use the @googleapps.wrdsb.ca account instead of the @wrdsb.on.ca account—it’s at the teacher’s discretion which of the two to use and list.
* As for student accounts, I have documents to validate the two address domains. For @ins.wrdsb.ca, [this document](http://waterworks.wrdsb.on.ca/Getting_Started%20_Using_WaterWorks.pdf) outlines the address format (see the second bullet point under the second page heading “Using WaterWorks”. For @googleapps.wrdsb.ca, [this school’s page](http://sss.wrdsb.ca/library/google-apps-for-education/) provides a link to the Google Apps for Education sign-on portal, as well as a sample of the username format.

I hope that adequately covers the practices surrounding email use at the Board—I know it’s more inferred than explicit, but there are plenty of examples across the Board sites (which are all subdomains of [wrdsb.ca](http://www.wrdsb.ca), as are the email addresses I’ve added in this PR) to back them up.

As for the description of courses, [this PDF](http://www.wrdsb.ca/wp-content/uploads/Common-Course-Calendar-2016_2017WRDSB.pdf) describes all courses offered during a school year at the secondary (grades 9–12) level schools in the district (all schools in the district use the same domain for emails). Pages 75–76 (“Computer Studies”) describe the programming courses that students might take over 3 years, each building on the principles taught during the previous.

Let me know if there’s further documentation you’d like to back this up!

**Comment by philipto** [comment]
@lchski Thank you very much for so detailed explanation! The pull request is now merged.

**Comment by lchski** [comment]
Happy to provide it; thank you!

**Pull request merged**
