### PR TITLE
snets.txt

### PR DESCRIPTION
**Pull request by derAdri4n**
Schulnetz Südtirol

Website: https://www.snets.it/default.aspx
Domain-WHOIS: http://whois.domaintools.com/snets.it

### CODE REVIEW

**Comment by philipto** [comment]
@derAdri4n Please rename lib/domains/it/snets to lib/domains/it/snets.txt

**Comment by derAdri4n** [comment]
Done. I renamed lib/domains/it/snets to lib/domains/it/snets.txt.

**Comment by derAdri4n** [comment]
Nope. Unfortunately it does not work because the .txt was not moved / approved.

**Comment by BjarneRest** [comment]
@derAdri4n Sure, I am not able to merge. I am not asocciated with JetBrains

**Comment by philipto** [comment]
@derAdri4n Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Pull request merged**
