### PR TITLE
Add Christ University 

### PR DESCRIPTION
**Pull request by nithin2e**
Adding Christ  University, Bangalore, India

### CODE REVIEW

**Comment by nithin2e** [comment]
university website : http://www.christuniversity.in/

**Comment by zweizwei** [comment]
@nithin2e could you please somehow that the provided page also belongs to university? also please check if the path is correct - the page chirst.in.in doesn't seem to open

**Comment by nithin2e** [comment]
@zweizwei i'm confused. the university website is http://christuniversity.in , i did not find a path for 'in' domain. That's why i created and added it 'in' folder.

**Comment by zweizwei** [comment]
@nithin2e if the website is http://christuniversity.in should we then add this path? is is used for emails? if so, i'll add in/christuniversity.txt manually. Please let me know.

**Comment by nithin2e** [comment]
@zweizwei yes, it is the domain used for emails. I have committed with this fix

**Comment by zweizwei** [comment]
@nithin2e thanks a lot, i'm adding the domain

**Pull request merged**
