### PR TITLE
Create i2r.txt

### PR DESCRIPTION
**Pull request by skychan**
Add Institute for Infocomm Research

### CODE REVIEW

**Comment by philipto** [comment]
@skychan First stage of verification passed, official domain is [a-star.edu.sg](https://a-star.edu.sg) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@skychan This domain seems to represent an umbrella national research agency, not a specific single university or a college. Would you please provide more details on what the Agency does? Does it have its own teaching facility, does it enroll students to its own courses? If yes, where I can read more about specific courses?

Thank you.

**Comment by philipto** [comment]
@skychan You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@skychan I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by skychan** [comment]
@philipto, sorry for the late response, haven't check the inbox last week. Our institute's website is: https://www.a-star.edu.sg/i2r. I'm not sure why you mentioned that it was 'non-existent' domain, our email address have this kind of form: "xxx@i2r.a-star.edu.sg".
Our institute do have some editional programs, and the major research fields are AI related.

May I know if I need to create a new pull requrest or this domain cannot be added to the list? Thank you.

**Pull request closed without merging**
