### PR TITLE
 Add lib/domains/vn/dntu.txt

### PR DESCRIPTION
**Pull request by HoangAnhKy**
Please allow me to resend the request to confirm the domain name.
URL: https://dntu.edu.vn/
other links: https://sv.dntu.edu.vn/

### CODE REVIEW

**Comment by philipto** [comment]
@HoangAnhKy There is something clearly incorrect with this domain name. 
If you wish to add the domain dntu.edu.vn to the repository, the filepath is incorrect, it has to be `lib/domains/vn/edu/dntu.txt`.
If you wish to add the domain dntu.vn, it's impossible: this domain does not exist.
Please correct the filepath or close the request. Thank you.

**Comment by HoangAnhKy** [comment]
I fixed it, can you please check it again?

**Comment by philipto** [comment]
@HoangAnhKy First stage of verification passed, official domain is [dntu.edu.vn](https://dntu.edu.vn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@HoangAnhKy Thank you for the update! Pull request merged.

**Pull request merged**
