### PR TITLE
Add my new school

### PR DESCRIPTION
**Pull request by vasilvestre**
I'm joining a new french school with a private domain for student

University website : http://www.univ-catholille.fr/
Here's your library address : http://lol.univ-catholille.fr/
Student mail : name.surname@lacatho.fr
"lacatho.fr" "la catho" can be translated to "the catholique" catholique as a proper name

### CODE REVIEW

**Comment by philipto** [comment]
@vasilvestre I am sorry, whois data suggests that the domain does not belong to an educational institution. If you have a strong proof that this domain belongs to Université catholique de Lille, please provide us with the proof.

This is an extract from the whois:
domain:      lacatho.fr
status:      ACTIVE
hold:        NO
holder-c:    HF3927-FRNIC
admin-c:     HF3927-FRNIC
tech-c:      HF3928-FRNIC
zone-c:      NFC1-FRNIC
nsl-id:      NSL5536-FRNIC
registrar:   HOSTING CONCEPTS B.V.
Expiry Date: 27/11/2018
created:     27/11/2017
source:      FRNIC

nic-hdl:     HF3927-FRNIC
type:        PERSON
contact:     Holm Filip
e-mail:      hnbuqloxl79341@163.com

**Comment by vasilvestre** [comment]
When you search www.lacatho.fr on google you get the university as second suggestion.
The domain is not used but our email is still lacatho.fr
I'm trying to contact IT department to know if it is an alias or something like that

**Comment by philipto** [comment]
@vasilvestre I am sorry, when I search "www.lacatho.fr" on Google, I get tons of search spam. 
I attach the screenshot as a proof and close this request without merging. This domain looks completely unrelated to education. Please refrain from adding it to the repository.

image

**Comment by vasilvestre** [comment]
Oh, google is doing a nice work because mine is mostly related to the school. i will ask to IT why this happen.
image

**Comment by vasilvestre** [comment]
I am an idiot, the real domain is lacatholille.fr ....
I open another PR or modify this one ?
https://www.whois.com/whois/lacatholille.fr

**Pull request closed without merging**
