### PR TITLE
state budgetary educational institution of the city of Moscow "Digita…

### PR DESCRIPTION
**Pull request by Andydecard**
#### Institution/School Name 
{state budgetary educational institution of the city of Moscow "Digital school"}

#### Instiution/School Website
{https://digitalschool.mskobr.ru/#/}

#### Email Users
sementkovskyas@mosmetod.ru
sovetovanv@mosmetod.ru 

*Please place an x between the square brackets if yes*
- [ ] Students
- [x] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [ ] Graduate School
- [ ] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [x] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by philipto** [comment]
@Andydecard Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school. Thank you.

**Comment by philipto** [comment]
@Andydecard Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school. Thank you.

**Comment by philipto** [comment]
@Andydecard You might miss my previous comment. Please react.

**Comment by Andydecard** [comment]
Hi! It`s Frontend course (HTML, CSS, JavaScript) at this list.21.10.2019, 14:41, "Philip Torchinsky" <notifications@github.com>:@Andydecard Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school. Thank you.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- С Уважением, Андрей Сергеевич Сементковский.

**Comment by Andydecard** [comment]
https://st.educom.ru/eduoffices/gateways/get_file.php?id={363FA02B-72B2-7A44-659D-7BF598FC1DFD}&name=%D0%A4rontend-razrabotka-(html,-css,-javascript).pdf21.10.2019, 14:41, "Philip Torchinsky" <notifications@github.com>:@Andydecard Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school. Thank you.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- С Уважением, Андрей Сергеевич Сементковский.

**Comment by philipto** [comment]
@Andydecard Thank you for the clarification. Pull request merged.

**Pull request merged**
