### PR TITLE
uam.txt

### PR DESCRIPTION
**Pull request by Gibran-16**
Add Universidad Americana

### CODE REVIEW

**Comment by htoch** [comment]
uamcr.txt should also be created under domains/net/ Because the email accounts of students are created with this domain. e.g: student.name@uamcr.net

**Comment by Gibran-16** [comment]
Hi, thanks
I created uamcr.txt under domains/net/

uamcr.txt #1278

**Comment by htoch** [comment]
Thank you!

**Comment by zweizwei** [comment]
unfortunately uam.net won't open - please somehow confirm that it belongs to university

**Comment by htoch** [comment]
Ok, the official domain for our University is uam.cr also the email addresses of teachers work under that domain. But they are giving us, as students, email addresses under uamcr.net. I assume those addresses are only for students. 

I will ask to the university for a way to offically confirm the domain is real. 

Unfortunately I cant because the domain showed in browser address bar is from Office365.

If you can suggest any other easy way to confirm, would be great!
selection_26d10m2015yyy-001

**Comment by zweizwei** [comment]
@htoch i've added the request 1278, thanks for the explanation

**Comment by htoch** [comment]
@zweizwei Thanks for your help! :)

**Comment by Gibran-16** [comment]
Thanks you both, now it works, thanks for your support.

**Pull request closed without merging**
