### PR TITLE
alhikmah-school.com

### PR DESCRIPTION
**Pull request by hatemdeeb**
This is the page URL where there is description about offered long-term IT courses
http://alhikmah-school.com/%d8%b9%d9%84%d9%88%d9%85-%d8%a7%d9%84%d9%83%d9%85%d8%a8%d9%8a%d9%88%d8%aa%d8%b1/

### CODE REVIEW

**Comment by hatemdeeb** [comment]
Can this domain be added&

**Comment by philipto** [comment]
@hatemdeeb Regrettably, no.

**Comment by hatemdeeb** [comment]
May I know the reason?

**Comment by hatemdeeb** [comment]
Should I include some files?

**Pull request closed without merging**
