### PR TITLE
Domain gim-pg

### PR DESCRIPTION
**Pull request by Pekonije1**
Here is a request for adding Gimnazija Slobodan Škerović email domain to eligible license list

### CODE REVIEW

**Comment by philipto** [comment]
@Pekonije1 First stage of verification passed, official domain is [gimnazijapg.me](https://gimnazijapg.me) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://gimnazijapg.me/

**Comment by Pekonije1** [comment]
@philipto Yes, you are correct. Thanks for the feedback.

**Comment by philipto** [comment]
@Pekonije1 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by Pekonije1** [comment]
@philipto 
Thank you for your response.

**Pull request merged**
