### PR TITLE
Create thmkhai-nuithanh.txt

### PR DESCRIPTION
**Pull request by thmkhai-nuithanh**
1. The school official website URL :
[https://thmkhai-nuithanh.edu.vn ](https://thmkhai-nuithanh.edu.vn) 

2. The school street address, including the city:
 Tam Thanh commune, Nui Thanh district, Quang Nam province, Quang Nam City, Viet Nam 
3. An URL of a page on the official website where the school offers an IT-related long-term course  (>1 year): 
Although we currently offered a course to students, we have not yet updated this webpage. We regularly hold IT competitions for students in an effort to encourage programming language learning. Next, we have plans to make these courses longer. You can view the contest photo below

You can see some pictures of the contest that school have organized here :
https://thmkhai-nuithanh.edu.vn/tin-tuc-su-kien/ioe.html
4. An URL of a page at the official school website:
https://thmkhai-nuithanh.edu.vn/phong-giao-duc
Have nice day!
Thanks supports

### CODE REVIEW

**Comment by thmkhai-nuithanh** [comment]
@philipto 
Please reach out if you have any questions regarding the inclusion of the Nguyen Thi Minh Khai School domain in the JetBrains list.

**Comment by philipto** [comment]
@thmkhai-nuithanh Thank you for your request. It is now in the review. We'll notify you about the result as soon as possible.

**Comment by thmkhai-nuithanh** [comment]
Thank [philipto](https://github.com/philipto),

Because of the long wait, I applied with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

Thank you so much [philipto](https://github.com/philipto)

**Comment by philipto** [comment]
@thmkhai-nuithanh Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
