### PR TITLE
Add Northern Virginia Community College 

### PR DESCRIPTION
**Pull request by songjinhe**
Add Northern Virginia Community College

https://www.nvcc.edu/programs/it/emerging.html

https://www.nvcc.edu/academics/index.html

### CODE REVIEW

**Comment by songjinhe** [comment]
/lib/domains/edu/NVCC.txt

**Comment by songjinhe** [comment]
[lib/domains/cn/ac/qibebt.txt](url)

**Comment by songjinhe** [comment]
[lib/domains/edu/NVCC.txt](url)

**Comment by philipto** [comment]
@songjinhe I am sorry, the domain vccs.edu is blacklisted because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
