### PR TITLE
Create sameyde.txt

### PR DESCRIPTION
**Pull request by NorskFjellGeit**
Add sameyde.vgs.no for Sam Eyde Videregående Skole

### CODE REVIEW

**Comment by NorskFjellGeit** [comment]
Ref #18354

Sam Eyde Videregående Skole is also a part of @agderskolen.no and Agder County in Norway. Sam Eyde VGS is a High School located in Arendal, in Agder County, Norway.

@sameyde.vgs.no is for the teachers. @agderskolen.no is used by the students.

**Comment by NorskFjellGeit** [comment]
[Link to school's educational program](https://sameyde.vgs.no/utdanningstilbud/informasjonsteknologi-og-medieproduksjon/)
[Link to curriculum](https://www.udir.no/lk20/itk02-01)

**Comment by philipto** [comment]
@NorskFjellGeit First stage of verification passed, official domain is [sameyde.vgs.no](https://sameyde.vgs.no) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@NorskFjellGeit Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
