### PR TITLE
Add my University

### PR DESCRIPTION
**Pull request by PhooPwintMaung**
I want to add my school to jetbrain . because i want to get free educational licenses.
University Name - Technological Mawlamyine
Located in Mawlamyine, Myanmar.

### CODE REVIEW

**Comment by kemicky** [comment]
[PIHE.txt](https://github.com/JetBrains/swot/files/7074091/PIHE.txt)

 Hi, Please add my school to JetBrains so that I  and any other student interested at my school may get free educational licenses.
University Name - Pearson Institute for Higher Education (Eduvos), Bedfordview, South Africa
Located in Bedfordview, Ekhuruleni, Gauteng, South Africa.

**Comment by philipto** [comment]
@PhooPwintMaung add I am sorry, I have to close the request without merging, because you made a mistake in a request and did not specify any filepath. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and make a new correct request. Thank you for your understanding!

**Comment by kemicky** [comment]
Hi , I wouldn't have made the mistake because it was archived before that I
wasn't able to access it.

**Comment by kemicky** [comment]
And that was since 28th August 2021 . Even if I dnt make a mistake it been
archived  already.. why not tell people  the truth rather than lying?

**Pull request closed without merging**
