### PR TITLE
svkskole.dk (Denmark) - Add my school... 

### PR DESCRIPTION
**Pull request by LazeSmash**

### CODE REVIEW

**Comment by philipto** [comment]
@LazeSmash Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by LazeSmash** [comment]
Is this a good enough proof? Check the name (Navn) where there stays Svendborg Municipality (Svendborg Kommune).

**Comment by philipto** [comment]
@LazeSmash Thank you for the clarification. Pull request merged.

**Comment by LazeSmash** [comment]
How long do i need to wait for i can use the domain?

**Comment by philipto** [comment]
@LazeSmash It usually takes about an hour for the system to have all new data to propagate through.

**Pull request merged**
