### PR TITLE
stie gici business school

### PR DESCRIPTION
**Pull request by firmansari**

### CODE REVIEW

**Comment by philipto** [comment]
@firmansari First stage of verification passed, official domain is [stiegici.ac.id](https://stiegici.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@firmansari Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by firmansari** [comment]
Here is our campus url https://stiegici.ac.id/
we also provide online learning at https://elearning.stiegici.ac.id/ and there are several IT-related courses

**Comment by philipto** [comment]
@firmansari  Thank you for the clarifications. Pull request merged.

**Pull request merged**
