### PR TITLE
adding mcl & mmdc

### PR DESCRIPTION
**Pull request by eliakimset**

### CODE REVIEW

**Comment by eliakimset** [comment]
MCL is the mother school of MMDC
link for MMDC https://www.mmdc.mcl.edu.ph/
link for MCL https://mcl.edu.ph/

**Comment by philipto** [comment]
@eliakimset Please provide us with a proof, which shows that the school recognizes the domains **mcl.mcl.ph** and **mmdc.mcl.ph**  that you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by eliakimset** [comment]
Screenshot 2024-07-25 at 11 40 28 PM

**Comment by eliakimset** [comment]
kindly check your email, i sent the attachment via email, since it contains confidential informations.

**Comment by philipto** [comment]
@eliakimset Would you please send the attachment to community-support@jetbrains.com mentioning the URL of this request (https://github.com/JetBrains/swot/pull/22077)? I did not receive any email message from you.

**Comment by eliakimset** [comment]
I already sent an email.

**Comment by philipto** [comment]
@eliakimset I corrected your pull request to have it reflecting the desired changes. 

Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.** Thank you.

**Comment by eliakimset** [comment]
Good day I am still not able to register with my given email address. I
would like to raise this issue. Thank you. Regards.

**Pull request merged**
