### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RTDeluna**

### CODE REVIEW

**Comment by Dropead2** [comment]
[cue.txt](https://github.com/JetBrains/swot/files/10515220/cue.txt)
Add please, Thanks

**Comment by RTDeluna** [comment]
Here's the domain website:  bpsu.edu.ph 

File:
lib/domains/ph/edu/bpsu.txt

**Comment by philipto** [comment]
@RTDeluna First stage of verification passed, official domain is [bpsu.edu.ph](https://bpsu.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@RTDeluna Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
