### PR TITLE
Create istspe.txt

### PR DESCRIPTION
**Pull request by patricioeli**
add new institution

### CODE REVIEW

**Comment by philipto** [comment]
@patricioeli First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/ISTSPE/?locale=es_LA

**Comment by patricioeli** [comment]
> @patricioeli First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/ISTSPE/?locale=es_LA

@philipto  Thank you very much for your response and for confirming that the official domain is facebook.com. However, the official domain we are verifying is istspe.edu.ec.

Best regards,
@patricioeli

**Comment by philipto** [comment]
@patricioeli Thank you! You are right, your school's official website is certainly different, and my initial comment was incorrectly worded. In fact, I managed to find a page that seems to be an official school's page on Facebook.

After reviewing the actual official website, I failed to find a page on the official website where the school offers an IT-related long-term (>1 year) course. Could you please provide me with the URL of such course? If there is no one, what is the purpose of using JetBrains free licenses in your school? What subject requires you to do some software development?

Thank you for your patience and cooperation!

**Comment by philipto** [comment]
@patricioeli Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course? Thank you!

**Comment by philipto** [comment]
@patricioeli You might miss my previous comment. Please react.

**Comment by patricioeli** [comment]
@philipto 

I'm sorry for not responding promptly.

The institution doesn't offer such courses lasting more than one year, only short courses in rural areas, as it is a non-profit organization.

**Comment by philipto** [comment]
@patricioeli Thank you for the clarification. If there are only short courses, could you please follow different procedure to get free licenses for the students?

Regrettably, I have to close the request without merging, because this organization is a training center, not a college, nor a university. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot).

Please apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses.

Thank you for your understanding!

**Pull request closed without merging**
