### PR TITLE
add SHJGU domain

### PR DESCRIPTION
**Pull request by L049**
shjgu.edu.cn

### CODE REVIEW

**Comment by philipto** [comment]
@ATOSS12 lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by ATOSS12** [comment]
🥵

**Comment by philipto** [comment]
@ATOSS12 lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by ATOSS12** [comment]
School home page
https://www.shjgu.edu.cn/
Computer Science page
https://jdx.shjgu.edu.cn/2017/0510/c506a5123/page.htm

**Comment by philipto** [comment]
@L049 lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Pull request closed without merging**
