### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by freddycansic**

### CODE REVIEW

**Comment by freddycansic** [comment]
- https://www.isaacnewtonsixthform.org/
- The Old Fire Station, 30 Bethel Street, Norwich, Norfolk, NR2 1NR, United Kingdom
 
image
Sir Isaac is part of the Inspiration Trust therefore their emails are managed by them.
https://www.inspirationtrust.org/10/academies/profile/28/sir-isaac-newton-sixth-form

The emails available on the school website do not refer to the same domain as the student emails. Not sure how I can prove this.

E.g
image
image

**Comment by philipto** [comment]
@freddycansic  Thank you for the clarifications. 

The screenshot attached is hardly can be considered as an independent proof. 

Would you please provide us with an independent proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students?

You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by freddycansic** [comment]
image

**Comment by philipto** [comment]
@freddycansic  Thank you for the clarifications. Pull request merged.

**Pull request merged**
