### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SowetoTerminator**

### CODE REVIEW

**Comment by philipto** [comment]
@SowetoTerminator First stage of verification passed, official domain is [inteluni.ac.ke](https://inteluni.ac.ke) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@SowetoTerminator Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by SowetoTerminator** [comment]
https://inteluni.ac.ke/uk-pearson-btec-hnd-in-computing/

**Comment by SowetoTerminator** [comment]
https://www.sunderland.ac.uk/study/computing/undergraduate-applied-business-computing-sc/
and a degree course in partnership with university of sunderland

**Comment by philipto** [comment]
@SowetoTerminator  Thank you for the clarifications. Pull request merged.

**Pull request merged**
