### PR TITLE
Added Roong Aroon School

### PR DESCRIPTION
**Pull request by wit03**
- Here's our english website: https://www.roong-aroon.ac.th/?page_id=9793

### CODE REVIEW

**Comment by philipto** [comment]
@wit03 Could you please specify why exactly children under 12 of age need professional software development tools? We usually suggest IntelliJ IDEA Community and PyCharm Community Edition for the students of this age. They cover their needs in most cases, and do not require any subscription, and are free for everyone for any kind of use.

**Comment by philipto** [comment]
@wit03 You might miss my previous comment. Please react.

**Comment by wit03** [comment]
@philipto my apologies, Our school is having a secondary education (detailed in this [link](https://www.roong-aroon.ac.th/?page_id=7783)). Right now we are using PhpStorm IDE (trial version) for PHP web development and we hope that we can get the full version as the trial is going to end soon.

**Comment by philipto** [comment]
@wit03 Thank you for the clarification! Pull request merged.

**Pull request merged**
