### PR TITLE
File.zip file has been deleted

### PR DESCRIPTION
**Pull request by MUKULKAUSHIK93**

### CODE REVIEW

**Comment by MUKULKAUSHIK93** [comment]
Hi,
Required changes has been done.

**Comment by philipto** [comment]
@MUKULKAUSHIK93 Thank you for the details. You are right, and there is some incomplete information. Please provide us with:
- the school official website URL
- the school official full name. IIMT is either incomplete, or shortened, or both
- the school street address, including the city 
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by MUKULKAUSHIK93** [comment]
Hi @philipto 

- the school official website URL([iimtindia.net.in](http://iimtindia.net.in) and [iimtindia.net](https://iimtindia.net))
- the school official full name. IIMT is either incomplete, or shortened, or both(IIMT Meerut Campus)
- the school street address, including the city(Address- Ganga Nagar, Mawana Road, Meerut)
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.(https://www.iimtindia.net/programs.php)
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.(you can visit the link [iimtindia.net.in](http://iimtindia.net.in))

**Comment by philipto** [comment]
@MUKULKAUSHIK93 Thank you for the clarification. I found independent sources confirming that the domain is recognized by the university. Visiting a domain website itself is not enough.

Pull request merged.

**Pull request merged**
