### PR TITLE
Add CIFP ZONZAMAS

### PR DESCRIPTION
**Pull request by raulgonzaleztahiche**
Add CIFP ZONZAMAS

### CODE REVIEW

**Comment by philipto** [comment]
@raulgonzaleztahiche Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by raulgonzaleztahiche** [comment]
> @raulgonzaleztahiche Please provide us with:
> 
> * the school official website URL
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

* http://cifpzonzamas.org/ 

* https://www.dropbox.com/s/kmpm3287qo1hzf0/cifp%20zonzamas%20oferta%20educativa%20curso%202020_21.pdf?dl=0

* ???

**Comment by philipto** [comment]
@raulgonzaleztahiche Thank you for the clarifications. Could you please tell us whether the courses on Informatics and communication mentioned in the document which you have shared are full-time courses? If I understand the document correctly, it says that students have to attend courses at least once in a week. It does not look like a full-time study college.

**Comment by raulgonzaleztahiche** [comment]
> @raulgonzaleztahiche Thank you for the clarifications. Could you please tell us whether the courses on Informatics and communication mentioned in the document which you have shared are full-time courses? If I understand the document correctly, it says that students have to attend courses at least once in a week. It does not look like a full-time study college.

Hi , 
These are two-year courses.

1st and 2nd are given in the morning shift from Monday to Friday from 8:00 to 14:00.

Yo can see here official government information about the course.

**Comment by philipto** [comment]
@raulgonzaleztahiche Thank you for the clarification. Pull request merged.

**Pull request merged**
