### PR TITLE
Add Enskede School to domains

### PR DESCRIPTION
**Pull request by InfinityFloof**

### CODE REVIEW

**Comment by philipto** [comment]
@InfinityFloof Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@InfinityFloof You might miss my previous comment. Please react.

**Comment by InfinityFloof** [comment]
Hello! My school only has a general course with an IT centered class. I do not have the information required to respond. Sorry.

**Comment by philipto** [comment]
@InfinityFloof Thank you. I understand that your school is not a university. Still, we need to verify that the domain belongs to a particular school or a district.

Could you please clarify:
1. Does elevmail.stockholm.se belong to your school only? If yes, what is the school's address and full name?
2. If elevmail.stockholm.se belongs to a group of schools, what is the group? Do all the schools in Stockholm use this email domain? If not all, how many school use it?

**Comment by InfinityFloof** [comment]
elevmail.stockholm.se is used by every student in the province of Stockholm

**Comment by InfinityFloof** [comment]
Excuse my amount of edits, I realized my answer lacked information.

**Comment by philipto** [comment]
@InfinityFloof Thank you for all the details and the clarification.
Pull request merged. 

Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of the schools who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.
Thank you!

**Pull request merged**
