### PR TITLE
CDI College

### PR DESCRIPTION
**Pull request by DeeZeeDeez**
CDI College (Official Website) : https://www.cdicollege.ca/
Students e-mails are : @cdi.college

Old pull request : https://github.com/JetBrains/swot/pull/14993

Note :
College was added in 2021 but e-mail domain has changed since for the students.
College students now use Office 365 Pro e-mails.

Old e-mail domain added was  : lib/domains/ca/collegecdi.txt
Teachers still use this domain but not the students.

Thank you !

### CODE REVIEW

**Comment by DeeZeeDeez** [comment]
@philipto All modifications have been done for a couple days now. Wishing you a good day.

**Comment by philipto** [comment]
@DeeZeeDeez Would you please provide us with a proof that confirms that
> Students e-mails are : @cdi.college

There is no @cdi.college addresses mentioned anywhere at the official website and even Google. Do you have any proof?

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by DeeZeeDeez** [comment]
@philipto E-mail sent to the college administration. Waiting the official letter from them.
Thank you.

**Comment by DeeZeeDeez** [comment]
Hi, @philipto !
I have uploaded the college letter as proof.

Have a nice day.
Thank you.

**Comment by philipto** [comment]
@DeeZeeDeez lib/domains/college/CDI_College_Confirmation.pdf: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by DeeZeeDeez** [comment]
@philipto 

Deleted the file from the folder.
Pasted a picture of the letter directly.

Thank you!

image

**Comment by philipto** [comment]
@DeeZeeDeez Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by DeeZeeDeez** [comment]
Thank you @philipto !!
How many time it takes to be synced with the main JetBrains website !?
Just tried to create my student account and it doesn't work.
Have a nice day.

**Pull request merged**
