### PR TITLE
add seciu

### PR DESCRIPTION
**Pull request by agodoyDesp**
add seciu

### CODE REVIEW

**Comment by philipto** [comment]
@agodoyDesp Please provide us with:
- the school official website URL
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by agodoyDesp** [comment]
https://www.seciu.edu.uy/

**Comment by agodoyDesp** [comment]
Captura de pantalla de 2020-08-31 17-46-58

**Comment by philipto** [comment]
@agodoyDesp Thank you for the clarification. I also received an additional proof of the domain recognition from https://www.nic.uy. Pull request merged.

**Pull request merged**
