### PR TITLE
The Mercian Trust

### PR DESCRIPTION
**Pull request by AlexanderEDavis**

### CODE REVIEW

**Comment by philipto** [comment]
@AlexanderEDavis Thank you for your request. It appears worthwhile to add the parent domain of all mentioned domains, **merciantrust.org.uk**, to this repository. I tried to find this domain mentioned at the official website at https://www.themerciantrust.org, but failed. 

Could you please provide us with a proof, which shows that the school's parent organization recognizes the domain **merciantrust.org.uk** that you are submitting as an official email domain for the students.

You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@AlexanderEDavis You might miss my previous comment. Please react.

**Comment by AlexanderEDavis** [comment]
Please see page 4 of this PDF to show that we use the .merciantrust.org.uk domain for emails https://www.q3tipton.org.uk/docs/Parent_Information/Parent_Information_Y7_2023-24.pdf

**Comment by philipto** [comment]
@AlexanderEDavis  Thank you for the clarifications and your patience. Pull request merged.

**Pull request merged**
