### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by theLittleTiger**
Students from Northwestern Polytechnical University, Xi'an, China.

### CODE REVIEW

**Comment by philipto** [comment]
@theLittleTiger file/lib/domains/com/edu/nwpu/mail.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@theLittleTiger file/lib/domains/com/edu/nwpu/mail.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@theLittleTiger Would you like to add nwpu.edu.cn or nwpu.edu.com?

**Comment by theLittleTiger** [comment]
nwpu.edu.cn. Thank you, sir.

**Comment by theLittleTiger** [comment]
> @theLittleTiger Would you like to add nwpu.edu.cn or nwpu.edu.com?

nwpu.edu.cn. Thank you sir.

**Comment by philipto** [comment]
@theLittleTiger I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host mail.nwpu.edu.com not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by theLittleTiger** [comment]
> @theLittleTiger I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host mail.nwpu.edu.com not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

Sir, I have upload new files, and the domain should be mail.nwpu.edu.cn

**Comment by theLittleTiger** [comment]
Sir, nwpu.edu.cn, please.



At 2020-03-04 17:20:00, "Philip Torchinsky" <notifications@github.com> wrote:

@theLittleTiger Would you like to add nwpu.edu.cn or nwpu.edu.com?

**Pull request closed without merging**
