### PR TITLE
added quantum university to list of universities

### PR DESCRIPTION
**Pull request by VatsalyaWE**

### CODE REVIEW

**Comment by VatsalyaWE** [comment]
@philipto

**Comment by philipto** [comment]
@VatsalyaWE Please provide us with:
* the school official website URL
* the school's full official name, without abbreviations and nicknames
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@VatsalyaWE You might miss my previous comment. Please react.

**Comment by VatsalyaWE** [comment]
- https://www.quantumuniversity.edu.in/
- Quantum University
- 22km Mile Stone, Mandawar, Roorkee- Dehradun Highway (NH-73), Roorkee-247667 (Uttarakhand) India
- https://www.quantumuniversity.edu.in/engineering


The first 4 items are listed above. I am not sure what to submit as proof of official domain ownership. please suggest

**Pull request merged**
