### PR TITLE
Create vitapstudent

### PR DESCRIPTION
**Pull request by NewtonChutney**
Add the new Student email domain

### CODE REVIEW

**Comment by philipto** [comment]
@NewtonChutney lib/domains/in/ac/vitapstudent: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by NewtonChutney** [comment]
@philipto here's an example email:
sxxxx.21mic7nnn@vitapstudent.ac.in
Doesn't this correspond to the path I've used?

**Comment by NewtonChutney** [comment]
Ahh I think the extension is malformed, I'll add the txt

**Comment by NewtonChutney** [comment]
Please consider reviewing this now

**Comment by philipto** [comment]
@NewtonChutney Thank you for your patience while waiting for a review and processing your request. Pull request merged. Please start applying for JetBrains educational subscription at https://www.jetbrains.com/shop/eform/students **in an hour, to allow the changes to propagate through JetBrains systems**.

**Pull request merged**
