### PR TITLE
Update net to include alvinisd.net for Shadow Creek High School

### PR DESCRIPTION
**Pull request by dalzoubi**

### CODE REVIEW

**Comment by philipto** [comment]
@dalzoubi First stage of verification passed, official domain is [alvinisd.net](https://alvinisd.net) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by dalzoubi** [comment]
Thank you! Any idea how long it would take to get it merged?

Happy new year!

**Comment by philipto** [comment]
@dalzoubi Thank you! Happy New Year to you, too. 
Regrettably, it's impossible to connect to your website easily. It looks protected from strangers who do not study in your school. Therefore I cannot verify your school's eligibility for JetBrains educational subscription. I will get back to this request soon, and hope to find a way to access the website.

**Comment by dalzoubi** [comment]
You should be able to navigate to https://www.alvinisd.net/ and see that the Staff and all have the same domain address,  is that sufficient? What other details do you require? Schools staff emails: https://www.alvinisd.net/o/schs/staff

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by philipto** [comment]
@dalzoubi Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
