### PR TITLE
Create imsc.txt

### PR DESCRIPTION
**Pull request by chandrashekarka**
I request you to add the institute of mathematical sciences into the list of academic institutes recognised. https://www.imsc.res.in/ is the link to main page of the institute. Thank you

### CODE REVIEW

**Comment by philipto** [comment]
@chandrashekarka Could you please prove that email domain for the students is @imsc.in? If it is *imsc.res.in* as it seems to be from https://webmail.imsc.res.in/login.php page, the file path has to be `lib/domains/in/res/imsc.txt` instead of `lib/domains/in/imsc.txt`. Thank you!

**Comment by chandrashekarka** [comment]
Sorry, it's imsc.res.in

**Comment by philipto** [comment]
@chandrashekarka No problem. Please change the file path to `lib/domains/in/res/imsc.txt`. I'll merge the request as soon as you do it. Thank you!

**Comment by philipto** [comment]
@chandrashekarka I am closing this request because another one, #1909, was merged in order to add actual email domain. Thank you!

**Pull request closed without merging**
