### PR TITLE
Added Juelich Forschungzentrum

### PR DESCRIPTION
**Pull request by jayeshbadwaik**

### CODE REVIEW

**Comment by philipto** [comment]
@jayeshbadwaik lib/domains/de/fz-juelich.de: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by jayeshbadwaik** [comment]
@philipto  Sorry for the error earlier. I think I have fixed the issue now. Thanks. :-)

**Comment by philipto** [comment]
@jayeshbadwaik Thank you for the update! Could you please clarify if the organization teaches any students? It looks like as a purely research organization without any education. Am I mistaken?

**Comment by jayeshbadwaik** [comment]
While the organization itself is a research organization, it does have some courses and hires graduate students as you can see in the links below:
1.  [Master Student Hiring](https://www.fz-juelich.de/portal/EN/Careers/CurrentVacancies/DiplomaMaster/_node.html) 
2.  [Doctoral Student Hiring](https://www.fz-juelich.de/portal/EN/Careers/CurrentVacancies/Dissertations/_node.html)
3. [Bachelor's Course](https://www.fz-juelich.de/ias/jsc/EN/Career/StudyAppMathandCS/StudyAppMathandCS_node.html)
4. [Master's Course](https://www.fz-juelich.de/ias/jsc/DE/Karriere/MATSE_Bachelor/MATSE_Bachelor_node.html) 

There are probably more courses like this in other departments of the research center.

**Comment by philipto** [comment]
@jayeshbadwaik Thank you for the clarification. Pull request merged.

Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of this Institute who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.

Thank you!

**Comment by jayeshbadwaik** [comment]
Thank you!

**Pull request merged**
