### PR TITLE
add school in Normandie, France

### PR DESCRIPTION
**Pull request by ZakinaA**
Add school in Normandie France

### CODE REVIEW

**Comment by ZakinaA** [comment]
Is there something bad in my request or do you need further information in order to add my school and students ?

**Comment by philipto** [comment]
@ZakinaA Thank you for your patience while waiting for a review and processing your request. 

Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@ZakinaA You might miss my previous comment. Please react.

**Comment by ZakinaA** [comment]
Hello,
This is : 
- the school official website URL : https://www.lyceerostandcaen.fr/
- the school street address, including city and country : Lycée J.Rostand, 98 route d'Ifs, 14054 Caen, France
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course : https://www.lyceerostandcaen.fr/project/bts-services-informatiques-aux-organisations/
- but we don't have an official email domain for the students. We communicate by a specific software inside the school. Each student have a different email address.

Regards.

**Comment by philipto** [comment]
@ZakinaA Thank you for the clarifications and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
