### PR TITLE
Create shrewsbury

### PR DESCRIPTION
**Pull request by Tarmk**
Hi, my school takes IGCSE and A level Computer Science and would really benefit from having a professional license of PyCharm.

### CODE REVIEW

**Comment by Tarmk** [comment]
just for more information, this is for Shrewsbury International School Bangkok in Thailand, and our website can be accessed from https://www.shrewsbury.ac.th/riverside/

**Comment by philipto** [comment]
@Tarmk lib/domains/th/in/shrewsbury: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Tarmk** [comment]
okay ive now fixed it, please cheeck now.

**Comment by Tarmk** [comment]
@philipto okay ive fixed it now, please have a check.

**Comment by Tarmk** [comment]
@philipto, anything left that you require? please don't hesitate to request anything else.

**Comment by philipto** [comment]
@Tarmk The first verification stage is complete: the official domain for  **Shrewsbury International School Bangkok** is [www.shrewsbury.ac.th](https://www.shrewsbury.ac.th), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.shrewsbury.ac.th/riverside/parents-association/

**Comment by Tarmk** [comment]
@philipto Thank you so much, I will wait for good news hopefully.

**Comment by Tarmk** [comment]
@philipto Just to clear up some confusion, every email that is used in our school has both a ac.th and in.th domain, but only the "in.th" is able to be accessed from students, and "ac.th" is only for usage in Microsoft application software like onenote and word. therefore, I only applied for .in.th as we only use that. Hope there is no problem with this.

**Comment by philipto** [comment]
@Tarmk The first verification stage is complete: the official domain for  **Shrewsbury International School Bangkok** is [www.shrewsbury.ac.th](https://www.shrewsbury.ac.th), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.shrewsbury.ac.th/riverside/parents-association/

**Comment by philipto** [comment]
@Tarmk Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
