### PR TITLE
add szekai

### PR DESCRIPTION
**Pull request by SzuAllatka**
Add general high school.

### CODE REVIEW

**Comment by philipto** [comment]
@SzuAllatka Please provide us with:
* the school official website URL
* the school street address, including city and country
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@SzuAllatka You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@SzuAllatka I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by SzuAllatka** [comment]
Hello @philipto !
Ssorry for not responding until now. This is a website for my school https://pecel.ekif.hu/ .
My school address is, Hungary, 2119 Pécel, Kossuth tér 7. 
I don't know who can issue such a certificate, I will ask my IT teacher about it.
If I received one, I will reopen this ticket. Thank you for your patience.

**Pull request closed without merging**
