### PR TITLE
Create kitcoek.txt

### PR DESCRIPTION
**Pull request by mssalunkhe**
File for the KITCoEK Engineering College, India

### CODE REVIEW

**Comment by philipto** [comment]
@mssalunkhe First stage of verification passed, official domain is [kitcoek.in](https://kitcoek.in) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by mssalunkhe** [comment]
@philipto Thank  you for the update. Awaiting your final decision.

**Comment by philipto** [comment]
@mssalunkhe Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by mssalunkhe** [comment]
Thank you very much.

**Pull request merged**
