### PR TITLE
Create subu.txt

### PR DESCRIPTION
**Pull request by mehmethanturut**
Created subu.txt file Sakarya University of Applied Sciences

### CODE REVIEW

**Comment by KoliaK** [comment]
[lib.zip](https://github.com/user-attachments/files/17607452/lib.zip)

OFFICIAL URL:
https://portal.uniasselvi.com.br/

My Enrolled Course (System Analysis and Development 5 semesters):
https://portal.uniasselvi.com.br/graduacao/tecnologo/analise-e-desenvolvimento-de-sistemas/ead

Evidence of My Academic Email Domain:
acessoAVA

Thank you!

**Comment by philipto** [comment]
@mehmethanturut I am sorry, the domain subu.edu.tr is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Comment by KoliaK** [comment]
No problem, along the pull request I did applied for github student dev as
well. Just waiting for the activation that might take up to 7 days. Looking
forward to learn how to use pycharm pro and improve my data science skills!
Thank you,
Koliak.

Em dom., 3 de nov. de 2024 14:00, Philip Torchinsky <
***@***.***> escreveu:

**Comment by KoliaK** [comment]
> @mehmethanturut I am sorry, the domain subu.edu.tr is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

Sorry, just noticed the mentioned domain is not related to my school. Were you intending to comment on this other person's request? 

> Created subu.txt file Sakarya University of Applied Sciences

**Comment by mehmethanturut** [comment]
Dear @philipto,

Thank you for the information. I understand the importance of maintaining security and appreciate your guidance. I apologize for any inconvenience my schoolmates may have caused.

I am indeed a student at this school and would like to access the educational subscription. I will enroll in the GitHub Student Developer Program and apply for the JetBrains educational subscription using my GitHub account, as advised.

Thank you for your assistance, and please let me know if there is any additional information I should provide.

Best regards,
Mehmethan Türüt

**Pull request closed without merging**
