### PR TITLE
Create student-topica.txt

### PR DESCRIPTION
**Pull request by Phuong39**
student topica

### CODE REVIEW

**Comment by philipto** [comment]
@Phuong39 Given that this is an online school, I wish to talk to a school representative. I need to ensure that the school's policy aligns with regular schools practice, such as assigning and revoking email addresses, etc. Who can I contact at the school, and what is this person's email address?

**Comment by philipto** [comment]
@Phuong39 You might miss my previous comment. Please react.

**Comment by Phuong39** [comment]
Hi, Topica Viet Nam have approximate 800 students, recently, and this mail  is issued by the  Topica Viet Nam

**Comment by philipto** [comment]
@Phuong39 Please give me an email address of a person from the school administration who is responsible for assigning email addresses to the students. Thank you.

**Comment by philipto** [comment]
@Phuong39 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
