### PR TITLE
Add campus le châtaigneraie

### PR DESCRIPTION
**Pull request by Q300Z**

### CODE REVIEW

**Comment by philipto** [comment]
@Q300Z Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Q300Z You might miss my previous comment. Please react.

**Comment by Q300Z** [comment]
Hello sorry for the delay.

- school website : [https://www.la-chataigneraie.org/](https://www.la-chataigneraie.org/)
- school address : 2 Rue Charles Scherer, 76240 Le Mesnil-Esnard, France
- The url of a page on the official website where the school offers an IT-related long-term (>1 year) course : [https://www.la-chataigneraie.org/bts-service-informatiques-organisations-solutions-logicielles-applications-metiers/](https://www.la-chataigneraie.org/bts-service-informatiques-organisations-solutions-logicielles-applications-metiers/)
- And for the proof, you can find in the school website the contact email of the school.

**Comment by philipto** [comment]
@Q300Z Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
