### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by rihosbr**

### CODE REVIEW

**Comment by rihosbr** [comment]
Pull Request to Faculdade de Timbaúba

**Comment by rihosbr** [comment]
Pull Request to Faculdade de Timbaúba

**Comment by philipto** [comment]
@rihosbr First stage of verification passed, official domain is [faculdadedetimbauba.edu.br](https://faculdadedetimbauba.edu.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@rihosbr Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
