### PR TITLE
Add 'Cuatrovientos centro integrado' to educational institutions

### PR DESCRIPTION
**Pull request by Julen-Junguitu**

### CODE REVIEW

**Comment by Julen-Junguitu** [comment]
Cuatrovientos centro integrado is part of Navarra state educational system and their email address are xxxxxx@education.navarra.es

**Comment by Nekzerd** [comment]
[pradeaulasede.txt](https://github.com/JetBrains/swot/files/6364510/pradeaulasede.txt)

**Comment by philipto** [comment]
@Julen-Junguitu Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

@Nekzerd Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new **separate** request with correct information. Thank you for the understanding!

**Comment by philipto** [comment]
@Julen-Junguitu I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
