### PR TITLE
Add uniklinik-freiburg.txt to domains

### PR DESCRIPTION
**Pull request by Mahelita**

### CODE REVIEW

**Comment by philipto** [comment]
@Mahelita I am sorry, what is the email address pattern for the students of this school? Is it username@uniklinik-freiburg.de? If yes, could you please rename  lib/domains/uniklinik-freiburg.txt to  lib/domains/de/uniklinik-freiburg.txt ? Thank you.

**Comment by Mahelita** [comment]
@philipto I terribly sorry for having put the file in the wrong folder... How stupid of me! The most common pattern is firstname.lastname@uniklinik-freiburg.de. I move the file into the de folder. Thanks!

**Comment by philipto** [comment]
@Mahelita No problem. Thank you for the update! Pull request merged.

**Comment by Mahelita** [comment]
Thank you very much!

**Pull request merged**
