### PR TITLE
Add lo3msz.txt

### PR DESCRIPTION
**Pull request by FilipAdamusss**
Institution/School Name
W. Biegański School Complex in Częstochowa

Instiution/School Website
http://lo3msz.czest.pl/

Email Users
lo3@edukacja.czestochowa.pl
Please place an x between the square brackets if yes

[] Students
[x] Academic/Teaching Staff
[x] Other/Support Staff
[] Alumni

Education Levels
Please place an x between the square brackets if yes

[] Post-graduate research
[] Graduate School
[] College (University) or Undergraduate School or equivalent
[] Community College or equivalent
[x] High School or equivalent
[] Elementary School or equivalent

### CODE REVIEW

**Comment by philipto** [comment]
@FilipAdamusss Would you like to add a domain `edukacja.czestochowa.pl` or `lo3msz.czest.pl`?

**Comment by philipto** [comment]
@FilipAdamusss You might miss my previous comment. Please react.

**Comment by FilipAdamusss** [comment]
> @FilipAdamusss Would you like to add a domain `edukacja.czestochowa.pl` or `lo3msz.czest.pl`?

lo3msz.czest.pl

**Comment by philipto** [comment]
@FilipAdamusss  Thank you for the clarifications. Pull request merged.

**Pull request merged**
