### PR TITLE
Add eartvic.net (Escola Superior de Disseny i d'Arts Plàstiques de Catalunya, ESDAP)

### PR DESCRIPTION
**Pull request by pjover**

### CODE REVIEW

**Comment by philipto** [comment]
@pjover Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by pjover** [comment]
@philipto 

Video games course: https://www.eartvic.net/videojocs/

**Comment by philipto** [comment]
@pjover I am sorry, but I found a different official website address. Do they mention the course at http://www.esdap.cat/, too?

**Comment by pjover** [comment]
EARTVIC is a campus that belongs to ESDAP, in every campus they teach different courses as far I know

**Comment by philipto** [comment]
@pjover Thank you for the clarification. Pull request merged.

**Pull request merged**
