### PR TITLE
Create vuzkunaeva.txt

### PR DESCRIPTION
**Pull request by Nurbekmac**
https://www.vuzkunaeva.kz/

### CODE REVIEW

**Comment by philipto** [comment]
@Nurbekmac First stage of verification passed, official domain for **Евразийская юридическая академия имени Д.А.Кунаева** is [vuzkunaeva.kz](https://vuzkunaeva.kz) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Nurbekmac Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by Nurbekmac** [comment]
https://vuzkunaeva.kz/events/11

пт, 14 июн. 2024 г. в 16:13, Philip Torchinsky ***@***.***>:

**Comment by philipto** [comment]
@Nurbekmac I am sorry, the page you are referring to does not contain any IT-related courses. Also, the page https://vuzkunaeva.kz/academy/majors does not list any majors related to software development.

Thus, the school is considered as not eligible for this repository. Please apply for [GitHub Student Developer Pack](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/github-education-for-students/apply-to-github-education-as-a-student), and then apply for JetBrains free subscription with your GitHub account at https://www.jetbrains.com/shop/eform/students (GitHub tab).

I have to close this request without merging. Thank you for your understanding.

**Pull request closed without merging**
