### PR TITLE
add clet.txt

### PR DESCRIPTION
**Pull request by cletweb**
Lets add a contributing file, so we can work better together!

### CODE REVIEW

**Comment by philipto** [comment]
@cletweb Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@cletweb You might miss my previous comment. Please react.

**Comment by cletweb** [comment]
sorry i did miss it, we are currently no offering IT courses but it is in the scope later on down the track, but I still use phpstorm for our in-house development (student portal, website, and student management system) We are a full online college, i'm currently working on the material for the course, but we won't be ready to launch until the start of next year. Cheers Dan

**Comment by philipto** [comment]
@cletweb Thank you for the clarification! In this case, it will be correct way to get the license for you personally. Please apply for your free license with  official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

I cannot accept the request for the repository at the moment. Thank you for your understanding.

**Pull request closed without merging**
