### PR TITLE
Add Saint Peters domain file

### PR DESCRIPTION
**Pull request by AnmolChachra**
https://www.saintpeters.edu/

### CODE REVIEW

**Comment by AnmolChachra** [comment]
2641 John F. Kennedy Boulevard
Jersey City, NJ 07306

**Comment by AnmolChachra** [comment]
https://www.saintpeters.edu/academics/graduate-programs/master-of-science-in-data-science/

**Comment by AnmolChachra** [comment]
recognition of saintpeters.edu domain https://www.saintpeters.edu/academics/faculty/members/gulhan-bizel/

**Comment by philipto** [comment]
@AnmolChachra Thank you for your patience while waiting for a review and processing your request. Pull request merged. Please start applying for JetBrains educational subscription at https://www.jetbrains.com/shop/eform/students **in an hour, to allow the changes to propagate through JetBrains systems**.

**Pull request merged**
