### PR TITLE
Added UNID (red.unid.mx)

### PR DESCRIPTION
**Pull request by RobertoGongora**
Universidad Interamericana para el Desarrollo

I have an e-mail that looks like my-student-id@red.unid.mx

The main school site is unid.edu.mx though.

### CODE REVIEW

**Comment by EduardoRT** [comment]
+1

**Comment by philipto** [comment]
@RobertoGongora @EduardoRT I am sorry for a delay with processing your request. Could you please give us a reference to a page on the official website or other internal university policy which confirms that the emails from this domain are owned by the teachers and students of this university only?

I failed to find a strong connection between studying in Universidad Interamericana para el Desarrollo and having an email from this domain.

**Comment by RobertoGongora** [comment]
Don't worry, we're all busy!

And okay, give me a second and I will look for the information. If possible, I will talk with the school's administration to see if they can give me an official document stating the validity of the domain.

**Comment by RobertoGongora** [comment]
Here's the official website stating that the @red.unid e-mails are for students only:

http://www.unid.edu.mx/servicios/correoredunid.html

**Comment by philipto** [comment]
@RobertoGongora Thank you very much! The issue is that according to whois service, the domain unid.mx is registered for another organization:
`whois unid.mx`
[...]
`Registrant:`
`   Name:           Grupo Integer`
`   City:           Garza Garcia`
`   State:          Nuevo Leon`
`   Country:        Mexico`

Thus, some proof from the university administration (on the website or in any other form) will definitely clear the issue.

**Comment by RobertoGongora** [comment]
@philipto Yeah... The way they handled their domains is super weird to me, but I can show you a page in the official domain where they use the `unid.mx` domain as their official contact e-mail along with a telephone:

http://www.unid.edu.mx/unidvirtual.html

Scroll down to the footer of the page and you will see:

Contacto
☎ 01800 770 9090
✉ promocionunidvirtual@unid.mx

There they use the unid.mx for their email, so red.unid.mx is just a subdomain for that one.

**Comment by philipto** [comment]
@RobertoGongora Yes, it's now clear. Pull request merged. Thank you!

**Comment by RobertoGongora** [comment]
@philipto Thank you for taking the time to sort out this weirdness :+1:

**Comment by EduardoRT** [comment]
@philipto Idem!

**Pull request merged**
