### PR TITLE
Add Pintar College domain

### PR DESCRIPTION
**Pull request by alvincheang**
Name of Institution : Pintar College
Institution domain : https://www.pintarcollege.org
Contact email to perform verification : alvin@pintarcollege.org

### CODE REVIEW

**Comment by mcdelarosa** [comment]
Name of Institution: Highschool of Biel-Sealand
Institution website: https://www.gbsl.ch/
[file.zip](https://github.com/JetBrains/swot/files/6037342/file.zip)

**Comment by philipto** [comment]
@alvincheang There are several organizations with the similar name in the world.
Please provide us with:
- the school street address, including the city and the country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by philipto** [comment]
@alvincheang You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@alvincheang I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
