### PR TITLE
Add Hillel IT School

### PR DESCRIPTION
**Pull request by fominua**
Hillel IT School is one of the largest programming schools in Ukraine. It was launched in Odessa in 2012 and currently has about 1600 active students in 4 cities: Odessa, Kiev, Dnipro and Kharkiv. 

1. Official website: http://ithillel.ua

2. Hillel IT School provides great variety of diverse training programs and opportunity of long learning cycle from basic level to advanced which lasts for over a year: https://ithillel.ua/courses

3. Student’s domain is  login@student.ithillel.ua
Proof of this is existence of students’ personal cabinets, where you can get at https://lms.ithillel.ua.
Private cabinet is our in-house solution with the use of innovative approach in classroom management. 

4. All students are issued the certificates of course completion. Any certificate can be checked at https://certificate.ithillel.ua/ by inputing the unique number of graduation certificate. 

5. In 2015 we were honored with  IT Education Awards.

6. Our social networks will help you to ensure that we are educational institution https://www.facebook.com/Hillel.IT.School

7. Our YouTube channel has big amount of free high quality lessons https://www.youtube.com/user/HillelITSchool
By the way, this channel is the biggest one in Ukraine among others offline educational institutions.

### CODE REVIEW

**Comment by philipto** [comment]
@fominua I am very sorry, I have to close the request without merging, because this organization is a training center, not a college, nor a university. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot). 
Please apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/buy/classroom/#commercial

Feel free to reopen the request and comment here if I am mistaken in the nature of the organization. 
Thank you for the understanding!

**Comment by fominua** [comment]
@philipto Hello! Similar organizations in our country were given the opportunity to be on this list. For example: https://github.com/JetBrains/swot/pull/2534

I thought that we, too, would be able to get this opportunity, since we provide similar services.

**Comment by philipto** [comment]
@fominua Thank you for the feedback. Could you please tell us which courses of this school are more than a year long?

**Comment by fominua** [comment]
@philipto There are several such directions. For example: Front-End and Java.
We are committed to a modern modular approach, so each module within one course can be explained separately. For example:

The course Front-End consists of the following modules:
1. Front-End Basic: https://ithillel.ua/courses/front-end-basic-kiev (3 months)
2. Front-End Pro: https://ithillel.ua/courses/front-end-pro-kiev (4 months)
3. Front-End Plus: https://ithillel.ua/courses/front-end-pro-plus-kiev (4 months)
4. React: https://ithillel.ua/courses/react-kiev (2 months)

After completing this course, the student is a full-fledged Front-End developer. May apply for this position after the course.

The Java course provides for the development of a student from beginner to high level in 1 year, also consists of several modules.

If necessary, we can provide more detailed information on these courses and others!

**Comment by philipto** [comment]
@fominua Thank you for the details and clarification! I am sorry that the verification will take more time than usual three days in this case. I will update this request as soon as the verification and decision are made. Thank you for the understanding!

**Comment by fominua** [comment]
@philipto Thank you very much! If necessary, I can provide more information from internal sources.

**Comment by philipto** [comment]
@fominua If it is more comfortable for you, please answer the questions below by email to community-support@jetbrains.com. Otherwise, please answer here in the comments:
1) How many students registered for a year-long course (20%, 90%?) complete all modules of the year-long course?
2) How long graduated students have an access to their 'personal cabinets' for?
3) How long graduated students can use their email address in student.ithillel.ua domain after the graduation? Do I understand right that if a student registered for a year-long course, completed a first module, and does not complete other modules, the student possesses the email address for at least a year?

Depending on how do you define the rules for the students, your school may be eligible for different free options for JetBrains tools licensing.

**Comment by philipto** [comment]
@fominua You might miss my previous comment. Please react.

**Comment by fominua** [comment]
@philipto Sorry, I really missed the first notice! I sent you information by e-mail. Thank you!

**Comment by philipto** [comment]
@fominua I am sorry, was the issue resolved? Can I close this request?

**Comment by fominua** [comment]
> @fominua I am sorry, was the issue resolved? Can I close this request?

Yes! Thank you!

**Comment by philipto** [comment]
Pull request closed as per the initiator's comment above. Thank you.

**Pull request closed without merging**
