### PR TITLE
高雄市教育局 (kh.edu.tw)

### PR DESCRIPTION
**Pull request by duckfly-tw**
https://www.kh.edu.tw/
https://www.kh.edu.tw/orgArch/departments_intro/UA/P1

### CODE REVIEW

**Comment by philipto** [comment]
@duckfly-tw lib/domains/tw/edu/kh.edu: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by duckfly-tw** [comment]
thanks for your reply and sorry for my mistake, I have change the filename to the correct one.

**Review by duckfly-tw — COMMENTED** [review]
change filename to lib/doamins/tw/edu/kh.txt

**Comment by philipto** [comment]
@duckfly-tw Could you please tell us how many schools use this email domain?

**Comment by duckfly-tw** [comment]
@philipto thanks for your reply, we now have three 3 different email addresses for this domain:
dove.kh.edu.tw
mail.kh.edu.tw
kclass.kh.edu.tw

should I delete the last line ".group" and the first & second line are sufficient for this condition?

**Comment by philipto** [comment]
@duckfly-tw Thank you for the details. You don't need to change the request. It is merged. 

Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees who have an email address in this domain and are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.

Thank you!

**Comment by duckfly-tw** [comment]
@philipto really a big thanks for your help, we will follow the usage terms and conditions.

**Pull request merged**
