### PR TITLE
ARIP

### PR DESCRIPTION
**Pull request by SCPLEGION**

### CODE REVIEW

**Comment by philipto** [comment]
@SCPLEGION Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by SCPLEGION** [comment]
WEB URL : https://akademiarzemiosla.opole.pl/
ADDRES : Luboszycka 9, 46-020 Opole
(i don't know specifications of courses but i have this i this this is good)
List of fields of education : https://akademiarzemiosla.opole.pl/kierunki-ksztalcenia/
official student email dommain is : name.surname@uczen.akademiarzemiosla.ople.pl
all students what are on it have google account with this domain on the end for more specific i can send some picstures
Zrzut ekranu 2024-12-11 235213

**Comment by philipto** [comment]
@SCPLEGION Thank you!
It looks like you added a file with an incorrect filepath: `lib/domains/pl/akademiarzemiosla/uczen.txt`, and "opole" missed from the filepath.
The screenshot and your comment confirms that the domain for students is `uczen.akademiarzemiosla.opole.pl`, not `uczen.akademiarzemiosla.pl`. 

Please clarify what is actual domain that you wish to add.

**Comment by SCPLEGION** [comment]
domain for student is : uczen.akademiarzemiosla.opole.pl
i changed file path to the correct one

**Comment by philipto** [comment]
@SCPLEGION First stage of verification passed, official domain for **Akademia rzemiosła i przedsiębiorczości** is [uczen.akademiarzemiosla.opole.pl](https://uczen.akademiarzemiosla.opole.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@SCPLEGION You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@SCPLEGION Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
