### PR TITLE
Added CVO Groeipunt

### PR DESCRIPTION
**Pull request by JohnAxae**
CVO Groeipunt
Website: www.groeipunt.be

### CODE REVIEW

**Comment by philipto** [comment]
@JohnAxae The official website of this organization seems to have a different address.
Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@JohnAxae I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Comment by JohnAxae** [comment]
- CVO Groeipunt is 4 schools that merged since September 1st 2020, and are split over 2 parts.
So the official domain is groeipunt.be, that is linked thru cvogroeipunt.be and hetperspectief.net.
But on September 1st 2021, it will use groeipunt.be as the full official address.

- On https://hetperspectief.net/informatica, you will find certain IT-related courses, Like Web-and-App, with courses for 1 to 2 years.

- I don't know which proof you need. But I hope this helps:
image

**Comment by JohnAxae** [comment]
@philipto Can you check this?

**Pull request closed without merging**
