### PR TITLE
Pull of Institute Vidal i Barraquer, ES

### PR DESCRIPTION
**Pull request by daniloro04**

### CODE REVIEW

**Comment by daniloro04** [comment]
Student from Catalonia, Spain

**Comment by philipto** [comment]
@daniloro04 First stage of verification passed, official domain is [vidalibarraquer.net](https://vidalibarraquer.net) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by daniloro04** [comment]
Hello.
This is the official website of the school: https://www.vidalibarraquer.net/
Thus the email ***@***.*** is my school email address.
Thanks!

**Comment by philipto** [comment]
@daniloro04 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
