### PR TITLE
Create art.txt

### PR DESCRIPTION
**Pull request by adonis-lau**
Nanyang Institute of Technology

### CODE REVIEW

**Comment by adonis-lau** [comment]
Nanyang Institute of Technology

**Comment by philipto** [comment]
@adonis-lau please provide us with a link to a page at the official Nanyang Institute of Technology website, which refers to art.edu.kaufen domain as an email domain for the university.

**Comment by philipto** [comment]
@adonis-lau You might miss my previous comment. Please reply.

**Comment by philipto** [comment]
@adonis-lau I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
