### PR TITLE
Add schiller.txt (Schillergymnasium Münster)

### PR DESCRIPTION
**Pull request by benni-2844**
The Schillergymnasium is a public school in 48149 Münster, Germany. The public school website is schillergymnasium-muenster.de.

### CODE REVIEW

**Comment by philipto** [comment]
@benni-2844 lib/domains/de/ms/schiller: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by benni-2844** [comment]
I checked the rules and the file path format seems totally right to me. Email service of this school is provided @schiller.ms.de and I created de/ms/schiller.txt. This school is completely analogous to the othe public schools of the city of Münster that already exist wihtin lib/domains/de/ms/ like kant.txt, annette.txt, pascal.txt and stein.txt.

**Comment by philipto** [comment]
@benni-2844 The first verification stage is complete: the official domain for  **Schillergymnasium Münster** is [schillergymnasium-muenster.de](https://schillergymnasium-muenster.de), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://schillergymnasium-muenster.de/_pages/personen/schulsozialarbeit/

**Comment by philipto** [comment]
@benni-2844 Thank you for your patience while waiting for a review and processing your request. Pull request merged. Please start applying for JetBrains educational subscription at https://www.jetbrains.com/shop/eform/students **in an hour, to allow the changes to propagate through JetBrains systems**.

**Pull request merged**
