### PR TITLE
Added St College for Pull request

### PR DESCRIPTION
**Pull request by kieranheg**
http://stcolumbs.com/

### CODE REVIEW

**Comment by philipto** [comment]
@kieranheg Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@kieranheg You might miss my previous comment. Please reply.

**Comment by kieranheg** [comment]
Hi Philip

I hope the attached email below from my school email account is sufficient.
Note it also has the head of our IT dept D Boast for reference.


Ronan Hegarty <ronanhegarty18@stcolumbscollege.org>
19:03 (3 minutes ago)
to me


Sent from my iPad

Begin forwarded message:

*From:* D Boast <dboast745@stcolumbs.derry.ni.sch.uk>
*Date:* 10 September 2018 at 14:42:28 BST
*To:* "'RonanHegarty18@stcolumbscollege.org'" <
RonanHegarty18@stcolumbscollege.org>
*Subject:* *Important iPad information - please keep*

Please read carefully and keep following important information which is
needed for using an iPad in school.

*Pupil Name:* Ronan Hegarty

*Pupil Gmail Account: *RonanHegarty18@stcolumbscollege.org

*Pupil Gmail Password:*

*Pupil AppleID Account: *RonanHegarty18@id.stcolumbscollege.org

*Pupil AppleID Password: *1611


Cheers
Kieran

**Comment by philipto** [comment]
@kieranheg Pull request merged. Thank you!

**Comment by philipto** [comment]
@kieranheg Pull request merged. Thank you!

**Pull request merged**
