### PR TITLE
Add new TDL .eu for Université Paris-Dauphine

### PR DESCRIPTION
**Pull request by louima**

### CODE REVIEW

**Comment by zweizwei** [comment]
@louima the path should be fr/dauphine.txt - as the university's website is www.dauphine.fr/

**Comment by louima** [comment]
fr/dauphine.txt already exists but they added the dauphine.eu domain for emails instead of campus.dauphine.fr.

**Comment by zweizwei** [comment]
@louima could you provide the link to the page confirming this? I'm sorry but who.is says nothing about the domain so i can't tell if it belongs to the university on spot. Thanks in advance for your help!

**Comment by zweizwei** [comment]
obsolete, please reply to reopen

**Comment by androw** [comment]
"Dès votre inscription administrative, vous obtiendrez votre adresse de messagerie (prénom.nom @dauphine.eu) et aurez accès à Zimbra ! "
http://my.dauphine.fr/la-messagerie

**Comment by zweizwei** [comment]
@androw thanks a lot for the provided link, i'm adding the domain now

**Pull request merged**
