### PR TITLE
http://www.jbdelasalle.com/

### PR DESCRIPTION
**Pull request by medassi**
http://www.jbdelasalle.com/

### CODE REVIEW

**Comment by philipto** [comment]
@medassi Could you please:
1) rename lib/domains/com/jbdelasalle to lib/domains/com/jbdelasalle.txt
2) provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students, instead (or in addition to) of @lasalle63.fr, which is listed at the official website http://www.lycee-godefroy.com/lensemble-scolaire/nos-etablissements/#bansac

Thank you.

**Comment by medassi** [comment]
Ok, so sorry, i forgot the extension *.txt.

**Comment by philipto** [comment]
@medassi Thank you for the update. Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students, instead (or in addition to) of @lasalle63.fr, which is listed at the official website http://www.lycee-godefroy.com/lensemble-scolaire/nos-etablissements/#bansac

**Comment by medassi** [comment]
Is it ok : http://www.lasalle63.fr/  ?

**Comment by philipto** [comment]
@medassi I am sorry, no. 

You requested to add jbdelasalle.com as a domain of Ensemble scolaire Jean-Baptiste de La Salle. I found out that the official website for this school is www.lasalle63.fr, and there is nothing about jbdelasalle.com at the website whatsoever. 

Please indicate how can I establish a link between the school and jbdelasalle.com domain? How can I see that the school recognizes the domain as a domain for its students? Is there any document saying that the school provides the students with email addresses in jbdelasalle.com domain?

Please respond. Thank you.

**Comment by philipto** [comment]
@medassi You might miss my previous comment. Please react.

**Comment by medassi** [comment]
[Courrier Eleves Office 365_Final.pdf](https://github.com/JetBrains/swot/files/2639453/Courrier.Eleves.Office.365_Final.pdf)
So ok, i think that i understood.
This document is sent to students when they arrived in our school. I wiped off the password.
Is it ok?

**Comment by philipto** [comment]
@medassi Yes, you are quite right! Pull request merged. Thank you!

**Pull request merged**
