### PR TITLE
Registering Domain For JetBrains IDE.

### PR DESCRIPTION
**Pull request by Lashvardi**

### CODE REVIEW

**Comment by philipto** [comment]
@Lashvardi First stage of verification passed, official domain is [ge.itstep.org](https://ge.itstep.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://ge.itstep.org/

**Comment by philipto** [comment]
@Lashvardi According the rules of this repository, your pull request for adding a new email domain to the repository will be satisfied if all of the conditions below are met:

1. The domain is used by an educational institution, which offers at least one long-term course (one year or longer), and the course is somehow related to IT (it is in computer science, software engineering, statistics, bioinformatics, etc.)

2. The educational institution is a physical entity with student attendance and recognized as providing a learning curriculum for the educational system, or **the institution is an accredited online educational organization** providing their students with: (1) online courses with a curriculum at least one year long, (2) a dedicated email address which is provided to students only until their graduation.

The word "accredited" in the rules above means a recognition by the respective country's Ministry of Education or similar authorized organization. Therefore, could you please provide us with a link to a page at the official website of Georgia Ministry of Education, which shows that the Ministry accredited IT Step Academy as an online school?

**Comment by Lashvardi** [comment]
Hello, its not fully online school. it can be as an option but yeah it step academy does support online teaching. this is the link for the website: https://itstep.org/en

**Comment by Lashvardi** [comment]
Also it does provide course 2.5 years long

**Comment by philipto** [comment]
@Lashvardi Thank you. I double-checked and ensured that itstep.org is already in this repository. It means that all subdomains including ge.itstep.org are already in the trusted list by default. Thus, you don't need to add ge.itstep.org separately to the repository. You can already request a free license without any additional steps.

I close the request as a duplicate. Please send an email to community-support@jetbrains.com if you need any further help.

**Comment by Lashvardi** [comment]
Hello [image: image.png]

პარ, 23 ივნ. 2023, 11:16-ში Philip Torchinsky-მა ***@***.***>
დაწერა:

**Pull request closed without merging**
