### PR TITLE
Create oucru.txt

### PR DESCRIPTION
**Pull request by thanhleviet**
Add domain oucru.org for research institute license

### CODE REVIEW

**Comment by philipto** [comment]
@thanhleviet I am sorry, it looks like your organization is more dedicated to the research, not to education. If you wish to provide just teachers and student with the license, please confirm that in the comment. If your research staff need to work with JetBrains tools, it would be a good idea to email sales@jetbrains.com and ask for a special price for particular tools for the research institution. I am looking forward for an update from you. Thank you!

**Comment by thanhleviet** [comment]
Thanks for your response. We do have also training for internship/Ph.D. students that sometimes we recommend them using this python IDE. So would it be possible? Thanks

**Comment by philipto** [comment]
@thanhleviet If you have trainings which last for a year or longer, yes, it's the reason to add your organization to this repository. Otherwise, I would suggest the students to use their emails in other universities (if they study in them, too), or use trial versions, or community versions, such as PyCharm Community Edition (which is free for everybody for any kind of use).

Thus, please let us know if you have any year-long IT-related trainings, and if yes, provide us with the URL of their descriptions on your website. Thank you!

**Comment by philipto** [comment]
@thanhleviet This request remains unanswered for a while, and I have to close it. Please reopen if you have an update regarding the issue described above. Thank you for the understanding.

**Pull request closed without merging**
