### PR TITLE
Create budget-edu.txt

### PR DESCRIPTION
**Pull request by de1eted**
add Learning Center Budget

### CODE REVIEW

**Comment by philipto** [comment]
@de1eted please use correct path for the file. What is your email domain? If it's budget.edu, the file path has to be lib/domains/edu/budget.txt. Thank you!

**Comment by philipto** [comment]
@de1eted Could you please update the request according the comment above? Thank you.

**Comment by philipto** [comment]
@de1eted I am sorry, this request remains unanswered for a while, and I have to close it without merging. Thank you for your understanding.

**Comment by de1eted** [comment]
Hello! I was on vacation without internet. Domain of Learning Center is budget-edu.ru. Path was correct.

**Comment by philipto** [comment]
@de1eted 
1) The path was not correct, because the path was `lib/domains/budget-edu.txt`, and for **budget-edu.ru** domain the path must be `lib/domains/ru/budget-edu.txt`.
2) The school which owns this domain is not a college, nor a university. It is a training center. Please apply for free classroom license by email to classroom@jetbrains.com. I can not add a training center domain to this repository, it is for colleges and universities only. Thank you for your understanding.

**Pull request closed without merging**
