### PR TITLE
Create ISTIC.txt

### PR DESCRIPTION
**Pull request by neilabedioui**

### CODE REVIEW

**Comment by philipto** [comment]
@neilabedioui Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@neilabedioui You might miss my previous comment. Please react.

**Comment by neilabedioui** [comment]
HI , In fact  I have a friend who done the same thing like me (fsb.txt)
without any problem.  We are an institut from carthage university.

**Comment by philipto** [comment]
@neilabedioui If you are talking about #10004, the email domain there is different. Is there any document that shows that your university owns ucar.tn email domain?

**Comment by philipto** [comment]
@neilabedioui You might miss my previous comment. Please react.
If you cannot upload a copy of a document in question, I will have to close the request.

**Comment by philipto** [comment]
@neilabedioui Thank you for the details.
I finally found a proof that we need: https://www.scribd.com/document/529490074/INSAT-Votre-Nouveau-Compte-Saiefeddine-elamri-Insat-ucar-Tn-1

Your pull request is merged. You can start requesting free licenses in an hour. Thank you!

**Pull request merged**
