### PR TITLE
ccsf

### PR DESCRIPTION
**Pull request by Abotrix**
City College of San Francisco

### CODE REVIEW

**Comment by Abotrix** [comment]
I want to add City College of San Francisco

**Comment by Abotrix** [comment]
I want to add City College of San Francisco

**Comment by odellsallis93** [comment]
Same

**Comment by philipto** [comment]
@Abotrix I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host mail.edu not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by Abotrix** [comment]
I'm sorry. It was to be mail.ccsf.esu.

**Pull request closed without merging**
