### PR TITLE
adding kahana domain

### PR DESCRIPTION
**Pull request by chenkahana**
to include an Open University student.

### CODE REVIEW

**Comment by philipto** [comment]
@chenkahana Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by chenkahana** [comment]
Hi @philipto,
Sadly, my university won't provide me with any of the required proof.
I am a student at The Open University in Israel and the university isn't providing Email addresses for students.
If nothing else could be done we can unfortunately close this PR.
Thanks

**Comment by philipto** [comment]
@chenkahana Thank you for the response! Yes, you are right. Let's close the request. Please apply for a free educational license with an official document that proves that you are a student. You can do it using the "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

**Comment by philipto** [comment]
@chenkahana Thank you for the response! Yes, you are right. Let's close the request. Please apply for a free educational license with an official document that proves that you are a student. You can do it using the "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

**Pull request closed without merging**
