### PR TITLE
Added Tecnológico Universitario Vida Nueva

### PR DESCRIPTION
**Pull request by devAbreu**
Website: [Tecnológico Universitario Vida Nueva](https://vidanueva.edu.ec)
Facebook Page: [Tecnológico Universitario Vida Nueva ](https://www.facebook.com/VidaNuevaITS/)
[Higher Technology in Software Development (Third Level Career) ](https://vidanueva.edu.ec/desarrollo-de-software/)

### CODE REVIEW

**Comment by philipto** [comment]
@devAbreu First stage of verification passed, official domain is [vidanueva.edu.ec](https://vidanueva.edu.ec) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://vidanueva.edu.ec/

**Comment by devAbreu** [comment]
Hello @philipto, This comment adds more information for the verification process. 
Virtual Classroom for this institution. [Aula Virtual VIDA NUEVA](https://aulavirtual.istvidanueva.edu.ec/)

**Comment by devAbreu** [comment]
> @devAbreu First stage of verification passed, official domain is [vidanueva.edu.ec](https://vidanueva.edu.ec) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://vidanueva.edu.ec/

Hello @philipto, This comment adds more information for the verification process. 
Virtual Classroom for this institution. [Aula Virtual VIDA NUEVA](https://aulavirtual.istvidanueva.edu.ec/)

**Comment by tenthreee** [comment]
@devAbreu Pull request merged. Thank you!

**Comment by devAbreu** [comment]
> @devAbreu Pull request merged. Thank you!

Thank you.

**Pull request merged**
