### PR TITLE
Add Northern Virginia Community College

### PR DESCRIPTION
**Pull request by songjinhe**
https://www.nvcc.edu/programs/it/emerging.html

https://www.nvcc.edu/academics/index.html

### CODE REVIEW

**Comment by philipto** [comment]
@songjinhe vccs.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by songjinhe** [comment]
upload file
[vccs.txt](https://github.com/JetBrains/swot/files/4069411/vccs.txt)

**Comment by songjinhe** [comment]
[vccs.txt](https://github.com/JetBrains/swot/files/4069420/vccs.txt)

**Comment by songjinhe** [comment]
[vccs.txt](https://github.com/JetBrains/swot/files/4069425/vccs.txt)

**Comment by songjinhe** [comment]
Is this right?

**Pull request closed without merging**
