### PR TITLE
Create sj.txt

### PR DESCRIPTION
**Pull request by jafernandes**
Centro Universitário Salesiano de São Paulo - Unidade Campinas São José
http://unisal.br/unidades/campinas-sao-jose/

### CODE REVIEW

**Comment by philipto** [comment]
@jafernandes I am sorry a delay with processing your request. Could you please rename  lib/domains/br/unisal to  lib/domains/br/unisal.txt. I'll merge your pull request as soon as you do it. 

Also, are you sure that you need to mention "- Unidade Campinas São José" in .txt file? Unisal.br seems to cover all campuses, and have the single email domain for all of them, doesn't it?

**Comment by jafernandes** [comment]
@philipto Thanks for reply.
We have some campus, but the main campus is unisal.br, our unit (campus) is sj.unisal.br - in this case the e-mails of our campus are email@sj.unisal.br
Still it is necessary that I rename the file for you?
Thanks
Joel

**Comment by philipto** [comment]
@jafernandes Yes, if you wish to register e-mail domain for your campus only, the path should be lib/domains/br/unisal/sj.txt

**Comment by jafernandes** [comment]
@philipto OK take a look please if that's all right.

Thanks
Joel

**Comment by philipto** [comment]
@jafernandes I am sorry, I do not see any changes in the file path. Did you replace the file in the pull request?

**Comment by jafernandes** [comment]
@philipto Sorry, I'm not familiar with Git, I just create another Pull - https://github.com/JetBrains/swot/pull/1726 - see if it's ok or if I have to fix.

Thanks
Joel

**Comment by philipto** [comment]
@jafernandes Thank you! I merged pull request https://github.com/JetBrains/swot/pull/1726 and close this one as resolved in https://github.com/JetBrains/swot/pull/1726.

**Pull request closed without merging**
