### PR TITLE
Add The Priory Academy

### PR DESCRIPTION
**Pull request by ParaPenguin**
Includes all schools within the academy including the 6th form college

### CODE REVIEW

**Comment by zweizwei** [comment]
@ParaPenguin Sorry for the delay - we've been launching rebranding and I hadn't time to check the repo for a while. The website provided seems to be a website for some social organization, not school. If that's  a school website, please provide the link to the page of the courses that the school provides. Thank you!

**Comment by ParaPenguin** [comment]
The url you are referring to is prioryacademies.co.uk, am I correct? Because that is the school page, http://www.priorylsst.co.uk/page/?title=Curriculum&pid=64 is some of the provided courses for the school I attend. The domain is different, but if you click on one of the 4 links on the prioryacademies.co.uk website, you will be redirected there. Emails for all 4 schools in the academy end in @prioryacademies.co.uk

**Comment by zweizwei** [comment]
@ParaPenguin thanks for the explanation. I also found this resource http://www.prioryacademies.co.uk/page/?pid=10 which helps. Could you please add .txt extension to the file you've committed and i'll add it? thanks!

**Comment by ParaPenguin** [comment]
Sorry it took so long @zweizwei, should be done now.

**Comment by ParaPenguin** [comment]
Any update on this?

**Comment by mikhailvink** [comment]
@ParaPenguin Done, sorry for delay. Thank you!

**Comment by ParaPenguin** [comment]
@mikhailvink How long does it take until I can sign up for a student account? I tested it just now and it wasn't updated. I assume there's some kind of wait for you to update the project?

**Pull request merged**
