### PR TITLE
Create edvw.txt

### PR DESCRIPTION
**Pull request by Hofmann-Simon**

### CODE REVIEW

**Comment by philipto** [comment]
@Hofmann-Simon Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Hofmann-Simon You might miss my previous comment. Please reply.

**Comment by Hofmann-Simon** [comment]
Sorry for missing that. 
Under the "Anmelden" button under https://www.edvw.de/ is written "EDV-Schulen-Wiesau Webmail" is this not proof enough?

**Comment by Hofmann-Simon** [comment]
Yes this is the official website, but the students adresses are not mentioned.

**Comment by philipto** [comment]
@Hofmann-Simon I found no publicly availabele information about edvw.de domain owner. If you can not provide any proof that this domain is recognized as an official email domain for the students by your school, I am not able to add this domain to this repository. 

The proof can be a scan of an instruction to the school students on how to use email, or an appropriate policy of using it, or something else. If you can not find such a document, please apply for your free license with an official document which confirms that you are a school student at https://jetbrains.com/student.

**Comment by philipto** [comment]
@Hofmann-Simon I am sorry, I have to close this request without merging. Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with correct information. Thank you for the understanding!

Meanwhile, you can get your free license for JetBrains tools using "OFFICIAL DOCUMENT" option (and the corresponding tab) at the page at https://www.jetbrains.com/shop/eform/students. Thank you.

**Pull request closed without merging**
