### PR TITLE
add my riohondo edu

### PR DESCRIPTION
**Pull request by fdelbrayelle**

### CODE REVIEW

**Comment by philipto** [comment]
@fdelbrayelle lib/domains/edu/my.riohondo.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by fdelbrayelle** [comment]
Thank you for your feedback! I've changed the file name to match the rules.

**Comment by philipto** [comment]
@fdelbrayelle Pull request merged. Thank you!

**Comment by fdelbrayelle** [comment]
Thank you!

I still have the following message when trying to put my email in "@my.riohondo.edu" : "Your email address does not belong to any university that we know. You can apply with another method (see tabs above) or add your school to JetBrains' list."

Any idea?

**Comment by philipto** [comment]
@fdelbrayelle Thank you for your patience. Regrettably, this domain appeared to be blacklisted because one of the following happened: 
1) the college allows to register an email address there even if you are not a student of the college. 
2) someone from the college shared their account details or activation code publicly, or sold it, and it lead to broad account misuse and license terms violation.
Therefore, we are not able to identify if the people with @my.riohondo.edu addresses are actual students or not.
If you are the student of this college, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Pull request merged**
