### PR TITLE
Add "Institut Badalona VII" institute

### PR DESCRIPTION
**Pull request by akex06**
http://www.institutb7.cat/

### CODE REVIEW

**Comment by akex06** [comment]
Website url: http://www.institutb7.cat/
image

**Comment by philipto** [comment]
@akex06 lib/domains/cat/institutb7: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by akex06** [comment]
I'm sorry, I've just modfied it. Thanks for your time

**Comment by philipto** [comment]
@akex06 First stage of verification passed, official domain is [educaciodigital.cat](https://educaciodigital.cat) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://educaciodigital.cat/iesb7/moodle/

**Comment by philipto** [comment]
@akex06 Pull request merged. Thank you.

**Comment by akex06** [comment]
Should I be able to redeem my license? It appears as my email is not registered
image
The educaciodigital.cat is not the school domain, that's the domain from the Generalitat de Catalunya's  Education Department

**Pull request merged**
