### PR TITLE
Add University Collège de Paris, 75001 Paris, FR

### PR DESCRIPTION
**Pull request by maswee**
Hi, I added the College de Paris university group to the list of domains. Thank you in advance for your approval.

University website: https://www.collegedeparis.com
University official email domain for the students (@e-cdp.com): https://support.collegedeparis.com/hc/fr/articles/5310139595549-Initialiser-mon-e-CDP-ID

### CODE REVIEW

**Comment by maswee** [comment]
@philipto I am coming back to you to specify an URL of a page on the official website where the school offers an IT-related long-term course: https://www.collegedeparis.com/programs/ms-information-technology/

WHOIS data that link the email domain to the school: https://who.is/whois/e-cdp.com
image

**Comment by philipto** [comment]
@maswee Thank you for the update. We'll review the request for a little bit more time because there are several domains that seem to be official, but they are not clearly owned by the college. The college itself has a complex structure.
The domains I am checking now are:
collegedeparis.com
collegedeparis.fr
e-cdp.com.

**Comment by philipto** [comment]
@maswee Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by maswee** [comment]
@philipto Perfect, many thanks!

**Pull request merged**
