### PR TITLE
Added UAI alumnos

### PR DESCRIPTION
**Pull request by amcomaschi**

### CODE REVIEW

**Comment by philipto** [comment]
@amcomaschi Could you please clarify: do the UAI students use this email address, or the graduates, i.e. people who already graduated from the university and are no longer studying there?

**Comment by philipto** [comment]
@amcomaschi You might miss my previous comment. Please react.

**Comment by amcomaschi** [comment]
Hi @philipto, I missed your comment, sorry. This emails are used by students. Thanks !

**Comment by philipto** [comment]
@amcomaschi Pull request merged. Thank you!

**Pull request merged**
