### PR TITLE
Add Lake Oswego School District

### PR DESCRIPTION
**Pull request by nbd9**
https://www.losdschools.org/

Professor domains: https://www.losdschools.org/domain/403
Programming class on pdf page 49 (Should be noted that this is a class for the APCSA exam): https://www.losdschools.org/domain/470

### CODE REVIEW

**Comment by zzzanderw** [comment]
The class is detail on page 47, not 49.

**Comment by philipto** [comment]
@nbd9 I am sorry for a delay with your request processing. Do I get right that the course takes just a semester, thus it is shorter than 1 year? In that case I would suggest using trial version or Community edition of the tool of your choice. Please comment if you find this option not acceptable for some reason. Also please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by nbd9** [comment]
@philipto No problem! The course is offered for both one semester and one year, depending on how dedicated a prospective student is. The course is indeed offered at the high school, where most (if not all) students are above the age of 13. I agree that for most kids the community version is acceptable, but there are a few students here that would benefit from having the professional / educational version.

Hopefully that answered all your questions, but if you have any more feel free to ask.

**Comment by philipto** [comment]
@nbd9 Thank you for the clarification! Pull request merged.

**Pull request merged**
