### PR TITLE
Adding "Open Source School"

### PR DESCRIPTION
**Pull request by John-Loup**

### CODE REVIEW

**Comment by philipto** [comment]
@John-Loup http://oss.fr seems to be a website of some industry-oriented commercial venture, not a university, nor a college. Could you please clarify why you have requested to add this domain to this repository?

**Comment by John-Loup** [comment]
@philipto Hello, OSS means "Open Source School", here is the right website : http://www.opensourceschool.fr/

**Comment by philipto** [comment]
@John-Loup Thank you. Please note that you requested to add a file lib/domains/fr/oss.txt which corresponds a domain of oss.fr. Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and rename the file to correspond to your actual email domain. Thank you!

**Comment by John-Loup** [comment]
Oh, my mistake.
Done !

**Comment by philipto** [comment]
@John-Loup Pull request merged. Thank you!

**Pull request merged**
