### PR TITLE
Merge pull request #1 from JetBrains/master

### PR DESCRIPTION
**Pull request by Jaleleddine**
Mergedbranch

### CODE REVIEW

**Comment by Jaleleddine** [comment]
any comment

**Comment by philipto** [comment]
@Jaleleddine I am sorry, I have to close the request without merging, because you made a mistake in your request and did not specify any file and any filepath. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and make a new correct request. Thank you for the understanding!

**Comment by Jaleleddine** [comment]
ok, thanks

**Comment by Jaleleddine** [comment]
Please, i have uploaded the file, is it ok now!

**Comment by Jaleleddine** [comment]
Please, I have added th file. Is it Ok now?

**Pull request closed without merging**
