### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Leroy-design**

### CODE REVIEW

**Comment by VlassiSokorelos** [comment]
[ist.txt](https://github.com/JetBrains/swot/files/5537905/ist.txt)

**Comment by Leroy-design** [comment]
@VlassiSokorelos ?

**Comment by VlassiSokorelos** [comment]
sorry new user here , I made a mistake

**Comment by Leroy-design** [comment]
No worry :)

**Comment by philipto** [comment]
@Leroy-design I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host sgsdragon.net.k12.wa.us not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Pull request closed without merging**
