### PR TITLE
Create fadu.txt

### PR DESCRIPTION
**Pull request by Frankelycp**
add Facultad de Arquitectura, Diseño y Urbanismo
https://www.fadu.edu.uy/

### CODE REVIEW

**Comment by philipto** [comment]
@Frankelycp First stage of verification passed, official domain is [fadu.edu.uy](https://fadu.edu.uy) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Frankelycp Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by Frankelycp** [comment]
Hi @philipto 
The university does not offer courses in the IT sector, it is needed by a professor who is explaining how to manipulate databases with autocad

**Comment by philipto** [comment]
@Frankelycp  Thank you for the clarifications. Given that the university does not offer courses in the IT sector, the university is not eligible for being added to this repository.

The students and the professor can, however, apply for the free license with an official document which proves that they are a student or a teacher. One can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
