### PR TITLE
Add Paramount School and College

### PR DESCRIPTION
**Pull request by Nawshaduzzaman**
#### Institution/School Name 
Paramount School and College

#### Instiution/School Website
www.mypscedu.com

#### Email Users

- [x] Students
- [x] Academic/Teaching Staff
- [x] Other/Support Staff
- [ ] Alumni

#### Education Levels

- [x] Post-graduate research
- [x] Graduate School
- [x] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [x] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by philipto** [comment]
@Nawshaduzzaman I am very sorry, this request has signs of fraud. I have to close it without merging. If you are a student of this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Comment by Nawshaduzzaman** [comment]
> 
> 
> @Nawshaduzzaman I am very sorry, this request has signs of fraud. I have to close it without merging. If you are a student of this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

what do you mean by fraud?I am a teacher and already done with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).but didnt get any reply!

**Comment by Nawshaduzzaman** [comment]
@philipto can you please reply with detailed information about this?

**Comment by philipto** [comment]
@Nawshaduzzaman I am sorry again, because I seem to have been mistaken. I was unable to recognize if this school is real or not. There are many schools with this name, and we always check if there are independent sources which confirm that the school exists, is recognized by respective national regulator (such as Ministry of Education), and owns the domain. 

Thank you for mentioning your request which you made with the official document. I checked the document, and I can now approve this request to add your domain name to this repository. You are entitled for one educational license only, thus if you request a license with your email address, your request with the official document will have to be rejected.

We usually review requests with official documents in approximately 14 days, and you submitted it yesterday. This is why it was not yet approved.

The pull request is now merged. Thank you.

**Comment by Nawshaduzzaman** [comment]
@philipto Okay.. Thanks..but if its require more documents please let me know..

**Pull request merged**
