### PR TITLE
Create onisep.txt

### PR DESCRIPTION
**Pull request by ptorti**
Office national d'information sur les enseignements et les professions

### CODE REVIEW

**Comment by ptorti** [comment]
http://www.onisep.fr/

thank you

**Comment by philipto** [comment]
@ptorti Could you please tell us more about this institution? The website looks like a college website, but the title "National Office of Information on Teachings and Professions" suggests that this is a government agency.

**Comment by ptorti** [comment]
@philipto We depends of the Ministry of education for teachers and student.
We already have last year free account (by sending education's proof) but would'like to be automaticly recognized by the register sytem instead of asking each year et new license (For education and training FREE)
PS: sorry for my english

**Comment by philipto** [comment]
@ptorti I am sorry, but we carefully reviewed your case, and now we are sure that this institution is neither a college nor a university, thus we cannot add the domain to this repository. If your institution teaches some students who do not have emails in other universities' email domains, please ask them to submit their education proofs as they did it before, or ask the teacher to apply for a classroom license by email to classroom@jetbrains.com. I have to close this request without merging. Thank you for your understanding.

**Comment by ptorti** [comment]
ok, thank you for your answer

**Pull request closed without merging**
