### PR TITLE
Create mydusd.org

### PR DESCRIPTION
**Pull request by suedadam**
Dublin high school! Can high schoolers get educational discounts too?

### CODE REVIEW

**Comment by philipto** [comment]
@suedadam Yes. In order to do that, please rename lib/domains/org/mydusd to lib/domains/org/mydusd.txt to follow this repository rules. Please notice that .txt extension is mandatory. Thank you.

**Comment by philipto** [comment]
@suedadam Could you please make the changes requested above? Thank you!

**Comment by suedadam** [comment]
Done, sorry about that!

**Comment by philipto** [comment]
@suedadam Pull request merged. Thank you!

**Pull request merged**
