### PR TITLE
Add "Universidad del Valle de México"

### PR DESCRIPTION
**Pull request by brunete**
Add the "Universidad del Valle de México" university to the list of domains.

### CODE REVIEW

**Comment by brunete** [comment]
Official university website: https://uvm.mx/
IT-related course URL: https://uvm.mx/oferta-academica/licenciaturas-ejecutivas/ingenierias-uvm-online/licenciatura-ejecutiva-en-ingenieria-en-tecnologias-y-sistemas-de-la-informacion-online

**Comment by brunete** [comment]
I've redacted some sensitive information from the instructions email, like my full name and specific email address.

Untitled

**Comment by philipto** [comment]
@brunete I am sorry, the domain my.uvm.edu.mx is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to GitHub Student Developer Pack at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

**Comment by brunete** [comment]
Wow... that's embarrasing... I'm sorry that happened, I'll take a look at what you shared.

**Pull request closed without merging**
