### PR TITLE
Adding simonsen as an institution

### PR DESCRIPTION
**Pull request by hjemmel**
I have add a new Brazilian educational institution Simonsen (http://simonsen.br) to the swot project.

### CODE REVIEW

**Comment by zweizwei** [comment]
Please excuse my delay with reply. Please provide the link to the page, describing long-term (>1year) IT-related courses the university provide. Thanks.

**Comment by hjemmel** [comment]
There is the wikipedia page about the university and the courses: http://pt.wikipedia.org/wiki/Faculdades_Integradas_Simonsen

The institution also has its own page about the IT-related course: http://www.simonsen.br/cursos/tads/

The both links are in Brazilian Portuguese.

**Comment by hjemmel** [comment]
is it enough ?

**Comment by zweizwei** [comment]
yep, thanks a lot, adding the domain!

**Pull request merged**
