### PR TITLE
Add SMA Muhammadiyah 1 Jakarta to List

### PR DESCRIPTION
**Pull request by samdgea**

### CODE REVIEW

**Comment by philipto** [comment]
@samdgea Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@samdgea You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@samdgea I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by samdgea** [comment]
@philipto hi, sorry i missed your comment, i did not receive the notification

- the school official website URL: https://smamuhammadiyah1jkt.sch.id
- the school street address, including city and country: Jalan Kramat Raya No.49 RT.03/RW.04 Kec. Kramat Kel. Senen - Central Jakarta - Indonesia
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course [Here](https://smamuhammadiyah1jkt.sch.id/ekstrakurikuler/)
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. [Here](https://media.smamuhammadiyah1jkt.sch.id/wp-content/uploads/2022/12/06114728/Screenshot-from-2022-12-06-11-45-55.png)

**Pull request closed without merging**
