### PR TITLE
Create sode-edu.txt

### PR DESCRIPTION
**Pull request by haripriyaaithal**
Shri Madhwa Vadiraja Institute of Technology and Management

### CODE REVIEW

**Comment by haripriyaaithal** [comment]
URL: http://sode-edu.in
http://sode-edu.in/academics/computer-science/

**Comment by shrivishnu15cs092** [comment]
College Name : Shri Madhwa Vadiraja Institute of Technology and Management
Official Site :  http://sode-edu.in
http://sode-edu.in/academics/computer-science/

**Comment by philipto** [comment]
@haripriyaaithal Pull request merged. Thank you!

**Comment by haripriyaaithal** [comment]
Thank you for adding our college.

**Pull request merged**
