### PR TITLE
License Request for IBB Institut für Berufliche Bildung AG

### PR DESCRIPTION
**Pull request by alanifotis**
License Request for IBB Institut für Berufliche Bildung AG
As a student of the course for Software Developer by IBB

### CODE REVIEW

**Comment by philipto** [comment]
@alanifotis Thank you for your request. The school looks more like a training center, thus the eligibility of its domain for this repository is questionable. However there is more important issue:
1. The email domain **viona.rocks** is not mention anywhere at the official website. The page that you advised to check for the proof says the viona.online is the domain that the school uses.
2. The only place in the internet the domain **viona.rocks** mentioned I found is `https://www.phillipbachus.de/viona/stundenplan/`
It says that the domain cannot accept messages from outside the school, and if it's true, it makes adding it to this repository meaningless.

I suggest to use alternative way to get free licenses: please enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

I have to close this request without merging.
Thank you for your understanding!

**Comment by iptoux** [comment]
Hey, i'm also on this school, we all only got this internal mail @viona.rocks. Should now all 80 ppl from the course do a private request on github students?

**Comment by iptoux** [comment]
> @alanifotis Thank you for your request. The school looks more like a training center, thus the eligibility of its domain for this repository is questionable. However there is more important issue:
> 
> 1. The email domain **viona.rocks** is not mention anywhere at the official website. The page that you advised to check for the proof says the viona.online is the domain that the school uses.
> 2. The only place in the internet the domain **viona.rocks** mentioned I found is `https://www.phillipbachus.de/viona/stundenplan/`
>    It says that the domain cannot accept messages from outside the school, and if it's true, it makes adding it to this repository meaningless.
> 
> I suggest to use alternative way to get free licenses: please enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).
> 
> I have to close this request without merging. Thank you for your understanding!

Hey, i'm also on this school, we all only got this internal mail @viona.rocks. Should now all 80 ppl from the course do a private request on github students?

**Comment by alanifotis** [comment]
@philipto Another place where is mentioned that our Institute is using viona.rocks for internal emails: https://www.ibb.com/fileadmin/uploads/MS_Teams_Erste_Schritte_TN.pdf

image

 THe domain cannot accept incoming messages as @iptoux confirmed that's only an internal email.

As for the:  "school looks more like a training center", it can look like it but out course is certified from https://www.ihk.de/ and it has a duration of 2 years.


Can we offer some other proof? What would constitute as a proof so our Institute is enlisted? While we are more then 80 people and each of us opening a separate GitHub Student Developer Account isn't a viable solution.

Thank you in advance @philipto

**Comment by philipto** [comment]
@alanifotis Thank you for the clarification. I merged the pull request. Still, I don't understand how it could help you, if this is correct:
> THe domain cannot accept incoming messages as @iptoux confirmed that's only an internal email.

If you cannot get an email from JetBrains with your free license to @viona.rocks address, please ask your teacher to make a request for a Classroom license here: https://www.jetbrains.com/community/education/#classrooms

Then the teachers will be able either to assign the licenses to each student, or use a [License Vault](https://www.jetbrains.com/help/license-vault-cloud/Classroom_plan.html) to have the licenses assigned to everybody automatically.

If you need further help, please send an email to community-support@jetbrains.com instead of commenting here. Regrettably, we cannot monitor comments to closed issues regularly. Thank you for your cooperation and understanding!

**Pull request merged**
