### PR TITLE
Adding BSPA

### PR DESCRIPTION
**Pull request by HerrGalgen**

### CODE REVIEW

**Comment by Saggio1** [comment]
[iis-silva-ricci.txt](https://github.com/JetBrains/swot/files/7557320/iis-silva-ricci.txt)

**Comment by HerrGalgen** [comment]
Wich Textfile is this?

**Comment by Saggio1** [comment]
Sorry i wrong conversation

**Comment by HerrGalgen** [comment]
Okay, no Problem :D

**Comment by philipto** [comment]
@HerrGalgen Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by HerrGalgen** [comment]
Hi @philipto,

When you type "www.itbspa.de" in Google, you get directed to the offical IT-website of our school, which is an Subpage of our main-school "bspa.de".

If this is not enough, we will talk to our teacher. Please answer me, if it isn´t enough.

Greetings

**Comment by philipto** [comment]
@HerrGalgen Thank you! 
> When you type "www.itbspa.de" in Google, you get directed to the offical IT-website of our school, which is an Subpage of our main-school "bspa.de".
> If this is not enough, we will talk to our teacher. Please answer me, if it isn´t enough.

Regrettably, it's not enough.

> Is ist enough if we have a documente with an official stamp of the school?

Yes, it's enough.

> Does it have to be in German or English?

Either German or English is OK.

**Comment by philipto** [comment]
@HerrGalgen How things are going? Do you have any update on the matter? Thank you!

**Comment by HerrGalgen** [comment]
Hi. We asked our teacher to print a document.
I don't know how long it takes, sorry.
Greetings.

**Comment by philipto** [comment]
@HerrGalgen Hello! Do you have any update on the matter?

**Comment by HerrGalgen** [comment]
Hey, our teacher said yesterday. That he can't creat such a document... I'm so sorry, that ist doesn't work :/

**Comment by philipto** [comment]
@HerrGalgen I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

Please apply for a free educational license with an official document that proves that you are a student. You can do it using the "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

**Pull request closed without merging**
