### PR TITLE
Added Chung Hwa Independent High School

### PR DESCRIPTION
**Pull request by pain2021053**
Official website: https://chhskel.edu.my/

### CODE REVIEW

**Comment by philipto** [comment]
@pain2021053 First stage of verification passed, official domain is [m.facebook.com](https://m.facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/profile.php?id=100078132090514

**Comment by pain2021053** [comment]
Sorry, I think you've mistaken the school's official domain. The official domain was: https://chhskel.edu.my/

**Comment by philipto** [comment]
@pain2021053 You are right. However I cannot yet verify independently the official website and other information about the school.

Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you.

**Comment by philipto** [comment]
@pain2021053 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@pain2021053 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
