### PR TITLE
Create ESPM

### PR DESCRIPTION
**Pull request by thiagoandf**
Escola Superior de Propaganda e Marketing 
São Paulo, SP, Brazil

The university website is www2.espm.br.
It offers a full 4 year graduation in Information Systems.
All the info can be checked here: 
http://www2.espm.br/cursos/espm-sao-paulo/sistemas-de-informacao-em-comunicacao-e-gestao

### CODE REVIEW

**Comment by thiagoandf** [comment]
The university website is www.espm.br.
It offers a full 4 year graduation in Information Systems.
All the info can be checked here: 
http://www2.espm.br/cursos/espm-sao-paulo/sistemas-de-informacao-em-comunicacao-e-gestao

**Comment by philipto** [comment]
@thiagoandf Thank you! Could you please provide us with a document (or a link to a respective page) saying that students use acad.espm.br domain, not espm.br?

**Comment by thiagoandf** [comment]
@philipto Thank you very much! I've requested an official document from the University. I'll send you as soon as I have it.

**Comment by thiagoandf** [comment]
@philipto Hello there,
As requested, there's an official ESPM document attached clarifying the uses of the domain. 
Thanks a lot

[DOC036.pdf](https://github.com/JetBrains/swot/files/273515/DOC036.pdf)

**Comment by philipto** [comment]
@thiagoandf Thank you very much! Pull request is now merged.

**Pull request merged**
