### PR TITLE
Create emek-school.txt

### PR DESCRIPTION
**Pull request by Benshu2007**
please insert my school into the list

### CODE REVIEW

**Comment by philipto** [comment]
@Benshu2007 Pull request merged. Thank you.

**Comment by Benshu2007** [comment]
what do i need to do next to get free license in JetBrains?
the email domain of the schools email is: emek-school.org.il

‫בתאריך יום ד׳, 15 במרץ 2023 ב-22:15 מאת ‪Philip Torchinsky‬‏ <‪
***@***.***‬‏>:‬

**Comment by philipto** [comment]
@Benshu2007 Open a page https://www.jetbrains.com/shop/eform/students, fill in the form, submit it, get an email from JetBrains, click a link in the email, follow instructions. If you have any trouble with it, please email support to community-support@jetbrains.com. Thank you.

**Comment by Benshu2007** [comment]
Done. Thank you so much it worked.

**Pull request merged**
