### PR TITLE
adding roosevelt university to list of universities so students from …

### PR DESCRIPTION
**Pull request by mauller77**
…there can use IntelliJ for free

### CODE REVIEW

**Comment by philipto** [comment]
@mauller77 Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students. Thank you.

**Comment by mauller77** [comment]
Something like this?

Regards,
Joshua Moller
________________________________

**Comment by philipto** [comment]
@mauller77 I am sorry, GitHub strips out an attachment if you send it by email in reply to a notification from GitHub. Please attach the proof which you have sent already via GitHub web interface. Thank you!

**Comment by philipto** [comment]
@mauller77 There must be some mistake, I suppose. The .pdf which you added to your request says that the domain is mail.roosevelt.edu, not mail.roosevelt.com. The original file path in your request is lib/domains/com/roosevelt/mail.txt, and it represents mail.roosevelt.com email domain. Could you please:
1) Remove .pdf file from the request (it's not necessary there, you might wish to attach it to the **comment** (not including the file to the pull request itself), but it has been viewed already, thus we don't need it anymore).
2) Rename lib/domains/com/roosevelt/mail.txt to lib/domains/edu/roosevelt/mail.txt, if you wish to add mail.roosevelt.edu to the list of domains belonging to educational organizations known to JetBrains.

Thank you!

**Comment by mauller77** [comment]
Sorry about that, the initial instructions told me to place the file into the com folder and I did not really look into the reason and purpose behind the com folder so that is my bad. I have moved it from the com folder to the edu folder. Sorry for the confusion.

Regards,
Joshua Moller
________________________________

**Comment by philipto** [comment]
@mauller77 Thank you for the update! Pull request merged.

**Pull request merged**
