### PR TITLE
fixed stoplist.txt because it's excluding University of Catania students

### PR DESCRIPTION
**Pull request by lauralex**
Studium.unict.it is the official domain for the University of Catania students:
image

### CODE REVIEW

**Comment by philipto** [comment]
@lauralex lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by lauralex** [comment]
> @lauralex lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.

The file path is not "incorrect". The pull request is about deleting the "studium.unict.it" entry from the stoplist. You can see from the image that it is the official domain given to University of Catania students

**Comment by philipto** [comment]
@lauralex Thank you for the request and clarifying comment. I will get back to this request shortly, as soon as I collect more info on the matter.

Each stoplist entry has a story behind it, thus it’s impossible to modify it without reviewing the story. Thank you for your patience.

**Comment by philipto** [comment]
@lauralex In December of 2022 we found out that there were users who obtained email addresses in this domain illegitimately. Thus, the domain was excluded from the trusted list. The licenses of the users were canceled.

I just removed `studium.unict.it` from the stoplist manually. It will take about 30-60 minutes for the changes to take effect.

We'll monitor its usage, and if a misuse happens again, it will be blocked. Thank you for your patience and understanding.

**Comment by lauralex** [comment]
> @lauralex In December of 2022 we found out that there were users who obtained email addresses in this domain illegitimately. Thus, the domain was excluded from the trusted list. The licenses of the users were canceled.
> 
> I just removed `studium.unict.it` from the stoplist manually. It will take about 30-60 minutes for the changes to take effect.
> 
> We'll monitor its usage, and if a misuse happens again, it will be blocked. Thank you for your patience and understanding.

@philipto Thank you

**Pull request closed without merging**
