### PR TITLE
Add Grafenberg school

### PR DESCRIPTION
**Pull request by EinfachBeez**
Add Grafenberg school
https://gsso.de/

### CODE REVIEW

**Comment by philipto** [comment]
@EinfachBeez First stage of verification passed, official domain is [gsso.de](https://gsso.de) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@EinfachBeez Thank you for your patience while waiting for a review and processing your request. Pull request merged. Thank you!

**Comment by Likqez** [comment]
Hi, am I mistaken or is this a duplicate of #11964 ?
Why is the root domain needed @EinfachBeez?

**Comment by EinfachBeez** [comment]
It is not necessary, but anyone with a gsso.de domain can create a student account.

**Pull request merged**
