### PR TITLE
Create zsndg

### PR DESCRIPTION
**Pull request by dd2000**
Add Please ;) Technik-Informatyk

### CODE REVIEW

**Comment by philipto** [comment]
@dd2000 Thank you for the request!
Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

Also, please let us know what is the email address pattern for this school's students. Is it **username@zsndg.pl**?   If yes, please rename lib/domains/pl/zsndg to lib/domains/pl/zsndg.txt.

Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot).

**Comment by philipto** [comment]
@dd2000 You might miss my previous comment. Please react.

**Comment by dd2000** [comment]
> 
> 
> @dd2000 You might miss my previous comment. Please react.

Hi!
1) An URL of a page on the official website [where an IT-related long-term (>1 year) course is offered by the school] is : **https://zs2ndg.szkolnastrona.pl**  (the school official website URL is different from the domain I am submitting)
2) I am IT teacher (programing) by this school.
3) The school educates IT technician in cycles of 4 and 5 years (high school). **https://zs2ndg.szkolnastrona.pl/index.php?c=page&id=40**
4) the email address pattern for this school's students is eg. : username@wp.pl

**Comment by philipto** [comment]
@dd2000 The school is eligible to be added to this repository. However wp.pl domain does not belong to this school exclusively, it is a publicly available email domain, everybody can register an email address there, Thus, it is not eligible to be added to the repository. Which email addresses this school provide the students with?

**Comment by philipto** [comment]
@dd2000 Thank you for the clarification! It means that regrettably, we cannot satisfy this request. 

Please let the students know that the best way for them is to apply for free licenses for JetBrains tools via OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students. 

I have to close this request without merging. If you have any further questions or concerns, please email us at community-support@jetbrains.com. Thank you!

**Comment by dd2000** [comment]
Ok.
Thank you.

**Pull request closed without merging**
