### PR TITLE
Create unae.txt

### PR DESCRIPTION
**Pull request by nicoalejo**
URL of Master's degree in Educational Technology and Innovation 
https://unae.edu.ec/oferta/maestria-en-tecnologia-e-innovacion-educativa/

### CODE REVIEW

**Comment by philipto** [comment]
@nicoalejo First stage of verification passed, official domain is [unae.edu.ec](https://unae.edu.ec) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@nicoalejo Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by nicoalejo** [comment]
I did in the first commit, I'll post again the link here, it's a master's degree in Technology and Innovation related to education:
https://unae.edu.ec/oferta/maestria-en-tecnologia-e-innovacion-educativa/

**Comment by philipto** [comment]
@nicoalejo  Thank you for the clarifications and your patience while waiting for a review and processing your request. I apologize for missing the first commit, you are quite right.

Pull request merged.

**Pull request merged**
