### PR TITLE
Universidad Autonoma de San Luis Potosi added

### PR DESCRIPTION
**Pull request by vdcastillo**
* Official website: https://www.uaslp.mx/
* IT career: https://www.ingenieria.uaslp.mx/CienciasComputacion/Paginas/Oferta-Academica/4456#gsc.tab=0

### CODE REVIEW

**Comment by philipto** [comment]
@vdcastillo Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by vdcastillo** [comment]
Hi, 

The official site for students is: https://estudiantes.uaslp.mx/

There you can find the instructions about the subdomain for email addresses.

Hope this can help you.

**Comment by vdcastillo** [comment]
Hi @philipto 
Yes I do, please add **alumnos.uaslp.edu.mx** and then I'll do a second request for alumnos.uaslp.mx.

**Comment by philipto** [comment]
@vdcastillo Thank you for the clarification. Regrettably, I see no proof for alumnos.uaslp.edu.mx to be an officially recognized by the university.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by vdcastillo** [comment]
@philipto 

here is the whois

https://www.whois.com/whois/uaslp.edu.mx

**Comment by philipto** [comment]
@vdcastillo  Thank you for the clarifications and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
