### PR TITLE
Update Berufliche Schulen Gelnhausen

### PR DESCRIPTION
**Pull request by Turbo505**
Our teachers asked to get access to educational licenses as well. But our school gives out different domains to students and teachers so I had to add both separately. 

I also specified the city as we aren't the only school in our district with that name.

Link to our school: https://bs-gelnhausen.de/

### CODE REVIEW

**Comment by geraldinrodriguez** [comment]
add institucion educativa san jose de cucuta
[colsanjoc.txt](https://github.com/JetBrains/swot/files/10462140/colsanjoc.txt)

**Comment by philipto** [comment]
@Turbo505 lib/domains/de/bs-gelnhausen: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Turbo505** [comment]
Oh sorry, my bad.

Thanks for letting me know @philipto 

I updated the file to have the .txt extension as needed. Hope everything is alright now.

**Comment by philipto** [comment]
@Turbo505 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by philipto** [comment]
@geraldinrodriguez Please create a separate pull request.

**Pull request merged**
