### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by migsprof**

### CODE REVIEW

**Comment by philipto** [comment]
@migsprof The first verification stage is complete: the official domain for  **Escola Beit Yaacov** is [www.ibo.org](https://www.ibo.org), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.ibo.org/en/school/002370

**Comment by migsprof** [comment]
Thank you for the update and for the verification of the domain. I would
like to clarify that the official domain for Escola Beit Yaacov is actually
www.beityaacov.com.br. The domain you mentioned, ibo.org, is the official
website of the International Baccalaureate Organization (IBO), with which
our school is affiliated.

Best regards,

Em qui., 12 de set. de 2024 às 07:15, Philip Torchinsky <
***@***.***> escreveu:

**Comment by philipto** [comment]
@migsprof The first verification stage is complete: the official domain for  **Escola Beit Yaacov** is [www.ibo.org](https://www.ibo.org), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.ibo.org/en/school/002370

**Comment by philipto** [comment]
@migsprof Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
