### PR TITLE
Create ac-guyane.txt

### PR DESCRIPTION
**Pull request by bsantiago64**
Académie de la Guyane

### CODE REVIEW

**Comment by philipto** [comment]
@bsantiago64 Could you please provide us with a link to an IT-related long-term (> 1 year) which your school offers to the students? Thank you!

**Comment by philipto** [comment]
@bsantiago64 You might miss my previous comment. Please reply.

**Comment by bsantiago64** [comment]
Sorry Philip, i did indeed miss your previous comment.

This domain is used by teachers in the public school of the Académie de la Guyane, an overseas French department : French Guiana

Our institutional website is http://www.ac-guyane.fr

We also have teacher created websites for different subjetcs like https://sti.dis.ac-guyane.fr for Electrical Engineering and Industrial Computing

29 other similar domains (ac-aix-marseille to ac-versailles in swot/lib/domains/fr) have already been added.

Thank you in advance

B. Santiago

**Comment by philipto** [comment]
@bsantiago64 Thank you for the additional information. I am sorry, I do not understand one important point: does your university have a course, related to infrormation technology, which the university offers to the students? 

It can be a course in programming, in bioinformatics, physics, math, or something else.

If yes, please give me a link to the course description.

**Comment by bsantiago64** [comment]
Hi,

I'm representing the whole governement managed educational system in French Guiana, which is called "Académie" in french (ac-guyane.fr, "ac" stands for "académie").
It includes all the scools, junior high and high schools of the region.

Therefore, the software you offer will serve for all of these entities, for example, this cursus in Physics Chemistry and Engineering Sciences in one of our high schools the Leon Gontran Damas LGT:

https://lgt-leon-gontran-damas.eta.ac-guyane.fr/IMG/pdf/brochure_cpge_lgdamas15_16_428259_.pdf

**Comment by bsantiago64** [comment]
The weekly schedule of the course are on page 11

**Comment by philipto** [comment]
@bsantiago64 Thank you very much for the detailed explanation. Now everything is clear. Pull request merged. Thank you!

**Comment by bsantiago64** [comment]
Great ! Thank you very much !

**Pull request merged**
