### PR TITLE
Add hcm.edu.vn

### PR DESCRIPTION
**Pull request by trietminh**
#### Institution/School Name 
Ngành Giáo Dục và Đào Tạo Thành Phố Hồ Chí Minh
Ho Chi Minh City - Department of Education and Training

#### Instiution/School Website
https://hcm.edu.vn/

#### Email Users
dqminh.hocmon@hcm.edu.vn

*Please place an x between the square brackets if yes*
- [x] Students
- [ ] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [ ] Graduate School
- [x] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [ ] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by philipto** [comment]
@trietminh First stage of verification passed, official domain for **Ngành Giáo Dục và Đào Tạo Thành Phố Hồ Chí Minh** is [hcm.edu.vn](https://hcm.edu.vn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@trietminh Could you please clarify whether the domain hcm.edu.vn is dedicated to a specific school, or all schools in the city use it? Thank you.

**Comment by tim-nguyen-m** [comment]
Thank you @philipto for your review.
hcm.edu.vn is the domain provided for the entire schools/departments/colleges under the Department of Education and Training of Ho Chi Minh City (Viet Nam), which does not have its own domain. Each student and teacher of the schools/departments/colleges is provided with an email address ending in @hcm.edu.vn, including both IT-related and non-IT-related fields of study.

**Comment by trietminh** [comment]
Thank you @philipto for your review.
[hcm.edu.vn](http://hcm.edu.vn/) is the domain for the entire schools/departments/colleges under the Department of Education and Training of Ho Chi Minh City (Viet Nam). Each student and teacher of the schools/departments/colleges is provided with an email address ending in @hcm.edu.vn, including both IT-related and non-IT-related fields of study.

**Comment by philipto** [comment]
@trietminh Thank you for your answer. As you see, this domain represents an umbrella institution, not a specific single university or a college. Regrettably, the rules of this repository prohibits to add the umbrella institutions domains to it. 

There are about 1.000.000 students in the schools of the city. While we would be very glad to serve such a big number of passionate users from Vietnam, we also understand that not all of the students actually need a free JetBrains subscription. Therefore, some of them (who do not need the subscription) may experience temptation to share their free subscription with a third party that need it. While sharing a subscription with a third party is prohibited, it's unquestionable that when the number of students is over a million, it's impossible to ensure that every one of them follows the license terms.

Therefore, please consider different approach. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

If you are a teacher, please send us an email to community-support@jetbrains.com, and we'll suggest other possible options for your school, if the above-mentioned approach does not work for your students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
