### PR TITLE
Create faespi.txt

### PR DESCRIPTION
**Pull request by gwpoliveira**
Dominio faespi.com.br , da  Faculdade de Ensino Superior do Piauí

### CODE REVIEW

**Comment by philipto** [comment]
@gwpoliveira The first verification stage is complete: the official domain for  **Faculdade de Ensino Superior do Piauí** is [fatepifaespi.com.br](https://fatepifaespi.com.br), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://fatepifaespi.com.br/

**Comment by NTIFaespi** [comment]
Olá além do https://fatepifaespi.com.br/ , temos o dominio faespi.com.br e fatepi.com.br, como faço para colocar esses dominios tambem pois tenho alunos e professores nesses dois dominios e o que mais alunos é faespi.com.br.
"Hello, in addition to https://fatepifaespi.com.br/, we have the domain faespi.com.br and fatepi.com.br, how do I add these domains as well because I have students and teachers in these two domains and what more students is faespi.com.br."

**Comment by philipto** [comment]
@gwpoliveira The first verification stage is complete: the official domain for  **Faculdade de Ensino Superior do Piauí** is [fatepifaespi.com.br](https://fatepifaespi.com.br), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://fatepifaespi.com.br/

**Comment by NTIFaespi** [comment]
@philipto , como falei nosso dominio onde todos nossos alunos de Sistemas estão cadastrado é o @faespi.com.br,  quero saber se vai da certo eles terem acesso por esse dominio.

"
@philipto, as I said, our domain where all our Systems students are registered is @faespi.com.br, I want to know if it will work for them to have access through this domain."

**Comment by philipto** [comment]
@gwpoliveira The first verification stage is complete: the official domain for  **Faculdade de Ensino Superior do Piauí** is [fatepifaespi.com.br](https://fatepifaespi.com.br), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://fatepifaespi.com.br/

**Comment by philipto** [comment]
@gwpoliveira 

> Hello, in addition to https://fatepifaespi.com.br/, we have the domain faespi.com.br and fatepi.com.br, how do I add these domains as well because I have students and teachers in these two domains and what more students is faespi.com.br

Yes, this is exactly what I wrote earlier. There is an official website, https://fatepifaespi.com.br/, and at the first page of the website you have a proof that the domain `faespi.com.br` is officially recognized by the university and belongs to the university. Therefore, I merge this pull request.

It means the domain `faespi.com.br` is in the trusted list, effective today. You can start requesting licenses in an hour.

**Pull request merged**
