### PR TITLE
Adding Johannes-Kepler-Gymnasium Ibbenbüren

### PR DESCRIPTION
**Pull request by ImL4rs**

### CODE REVIEW

**Comment by philipto** [comment]
@ImL4rs Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by ImL4rs** [comment]
Hey,
I hope this document is fine for the registration. If not just give me a
short response.

Philip Torchinsky ***@***.***> schrieb am Do., 18. Nov. 2021,
19:11:

**Comment by philipto** [comment]
@ImL4rs I guess you have replied by email with an attachment. Regrettably, GitHub strips out the attachments sent by email. Please upload the document that you have attached via your browser as a comment at this page: https://github.com/JetBrains/swot/pull/12971

Thank you!

**Comment by ImL4rs** [comment]
[school email.pdf](https://github.com/JetBrains/swot/files/7565415/school.email.pdf)

**Comment by whoImT** [comment]
Here also the user agreement https://kepler-gymnasium.de/images/Super_Users/Office365/Nutzungsverinbarung_SuS.pdf Specified under point 2.1 you can find the email domain.

**Comment by philipto** [comment]
@ImL4rs Thank you for the clarification. Pull request merged.

**Pull request merged**
