### PR TITLE
Added SIBSUTIS

### PR DESCRIPTION
**Pull request by toolateitsme**
I studied at this university

### CODE REVIEW

**Comment by toolateitsme** [comment]
I've attached a url proof and e-mail template

**Comment by toolateitsme** [comment]
@philipto Please check my PR

**Comment by toolateitsme** [comment]
Hello, is here someone to approve or reject this PR?

**Comment by philipto** [comment]
@toolateitsme I am sorry, there is a contradiction in what you have submitted:
the file name suggests that the email domain is sibsutis.novosibirsk.ru, and 
the university description (and the website) say that the email domain is sibsutis.ru. What is correct?

**Comment by toolateitsme** [comment]
@philipto Oh , it's my bad. Ill modify my PR later. Exactly, domain name is sibsutis.ru, not novosibirsk.sibsutis.ru

**Comment by philipto** [comment]
@toolateitsme I am sorry, I am a bit confused now. You actually request to remove lib/domains/ru/sibsutis.txt, which exists already, but add lib/domains/ru/novosibisrsk/sibsutis.txt, which corresponds to a wrong domain name. It looks like we need to close this request without merging, and that's all. Do you agree with this? Can I close your request?

**Comment by toolateitsme** [comment]
@philipto Yep, you are quite right, you can close my request. Im sorry for confusing you D:

But here is some fun.  Magic with letter "R", and now it's "Я"

**Comment by philipto** [comment]
@toolateitsme OK, I am closing the request without merging.

**Pull request closed without merging**
