### PR TITLE
vossie.txt

### PR DESCRIPTION
**Pull request by SnowyTheVampire**
#### Institution/School Name 
Eduvos

#### Instiution/School Website
https://www.eduvos.com/

#### Email Users

*Please place an x between the square brackets if yes*
- [x] Students
- [x] Academic/Teaching Staff
- [x] Other/Support Staff
- [x] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [x] Graduate School
- [x] College (University) or Undergraduate School or equivalent
- [x] Community College or equivalent
- [ ] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by ekremkaradeniz** [comment]
[file.zip](https://github.com/JetBrains/swot/files/6624014/file.zip)

**Comment by SnowyTheVampire** [comment]
[file.zip](https://github.com/JetBrains/swot/files/6628202/file.zip)

**Comment by philipto** [comment]
@SnowyTheVampire Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

@ekremkaradeniz Please create a separate pull request.

**Comment by SnowyTheVampire** [comment]
[14 May 2021 - Alumni Letter.pdf](https://github.com/JetBrains/swot/files/6658747/14.May.2021.-.Alumni.Letter.pdf)
ShareX_0FWlmQGvBD

**Pull request merged**
