### PR TITLE
Added International University of Qaiwan - UTM Franchise

### PR DESCRIPTION
**Pull request by rebaz36**

### CODE REVIEW

**Comment by rebaz36** [comment]
Thank you for Supporting Education!

**Comment by sureshcs0524** [comment]
Please add my School
---
Paris School of Business
Major: Digital Marketing Strategy and Data Analytics

[file.zip](https://github.com/JetBrains/swot/files/6528601/file.zip)

**Comment by philipto** [comment]
@rebaz36 Pull request merged. Thank you.

**Comment by philipto** [comment]
@sureshcs0524 Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new separate request with correct information. Thank you for your understanding!

**Pull request merged**
