### PR TITLE
Add Shahid Beheshti University Webmail

### PR DESCRIPTION
**Pull request by tahaeghtesad**

### CODE REVIEW

**Comment by tahaeghtesad** [comment]
@mail.sbu.ac.ir is used for students, @sbu.ac.ir is for instructors and professors.

**Comment by tahaeghtesad** [comment]
Could you please merge it faster? My license is expired.

**Comment by mysaberi** [comment]
My license has expired too, did your license renewed?

**Comment by tahaeghtesad** [comment]
I couldn't. Although it is mentioned that

> If all the domains used for teachers' and students' email are in the same upper-level domain, you can 
add the upper-level domain. For example, if there is a domain joedoe.org owned by a university, and there are subdomains such as stud.joedoe.org and prof.joedoe.org, used by the students and the teachers respectively, you can add joedoe.org domain only, and both students and teachers will be able to request their free licenses.

and, there is _sbu.ac.ir_ domain in the repository, my email address ending with _mail.sbu.ac.ir_ does not work.

**Comment by mysaberi** [comment]
You mean if one of our teachers register sbu domain with their mail it might work?

**Comment by philipto** [comment]
@tahaeghtesad Unfortunately, your request cannot be processed further because JetBrains doesn’t provide products or services to territories subject to applicable EU, UN, or US sanctions or under comprehensive export control restrictions due to legal, compliance, and other commercial risks.

I have to close the request. I appreciate your understanding.

**Pull request closed without merging**
