### PR TITLE
Create istitutoberetta

### PR DESCRIPTION
**Pull request by Propants05**

### CODE REVIEW

**Comment by philipto** [comment]
@Propants05 lib/domains/it/edu/istitutoberetta: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Propants05** [comment]
because my school has 3 different complexes and each complex has its own domain and I would like to register that of the itis which is Istitutoberetta.edu.it

**Comment by philipto** [comment]
@Propants05 lib/domains/it/edu/istitutoberetta: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Propants05 First stage of verification passed, official domain is [iiscberetta.edu.it](https://iiscberetta.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.iiscberetta.edu.it/

**Comment by philipto** [comment]
@Propants05 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
