### PR TITLE
Create icai.txt

### PR DESCRIPTION
**Pull request by MayankSood**

### CODE REVIEW

**Comment by philipto** [comment]
@MayankSood Is this institute a purely online university? Does it have offline classes, where students study in a classroom? If yes, could you please give us a link to the page on the official website where an IT-related long-term (>1 year) course is offered by the university.

**Comment by MayankSood** [comment]
@philipto 
ICAI is The Institute of Chartered Accountants of India.
Students here are studying Charted Accountancy. They might use some programming languages for their personal needs or to automate some accounts related scenarios.
This is one and the only institute in India for Charted Accountancy (Run by Government of India)

Below is the website.
https://www.icai.org/

They provide IT Training (both 100 Hours ITT and Advance ITT) for students (mandatory), and Activities related to ITT Centres set up by ICAI etc., where students can learn and motivate themselves to try IT as well.
below is the Link:
https://www.icai.org/new_post.html?post_id=8577&c_id=355

**Comment by MayankSood** [comment]
@philipto 
Do we have any update on this?

**Comment by philipto** [comment]
@MayankSood Yes. As far as I found out, Institute of Chartered Accountants of India is not just an educational institution, it is a much broader community of Chartered Accountants. You can see https://en.wikipedia.org/wiki/Institute_of_Chartered_Accountants_of_India for the details.

Regrettably, the link to the page, which you have provided us with, does not lead to a course description. As far as I understand you, the students can (but not obliged to) educate themselves in IT. However, JetBrains does not grant free educational licenses for self-education.

Therefore, it is unlikely that Institute of Chartered Accountants of India email domain can be added to this repository, because formally the Institute is not a university, nor a college, and the students there do not study IT as a part of their curriculum.

Also, it remains unclear to me if the Institute has classrooms where students study, or the students study online.

Please leave a comment if you wish to provide some clarification. Thank you.

**Comment by MayankSood** [comment]
No problem @philipto 
I guess I was unclear about the terms and conditions of JetBrains students license.
Thanks for the help and time spent.
I am closing the pull request.
Regards  
Mayank S

**Pull request closed without merging**
