### PR TITLE
Add my School, Lycée Polyvalent Vaucanson 38000 Grenoble France

### PR DESCRIPTION
**Pull request by Legambey**

### CODE REVIEW

**Comment by philipto** [comment]
@Legambey First stage of verification passed, official domain is [lycee-vaucanson-grenoble.web.ac-grenoble.fr](https://lycee-vaucanson-grenoble.web.ac-grenoble.fr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://lycee-vaucanson-grenoble.web.ac-grenoble.fr/contact

**Comment by Legambey** [comment]
> @Legambey First stage of verification passed, official domain is [lycee-vaucanson-grenoble.web.ac-grenoble.fr](https://lycee-vaucanson-grenoble.web.ac-grenoble.fr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://lycee-vaucanson-grenoble.web.ac-grenoble.fr/contact

Hello @philipto , 
thank you for your responsiveness, the domain name you sent is only for teachers, it is the city that gives them.  For the students, they use vaucanson38.com, we have the right to the whole Google suite, Classroom, drive, Colab etc. 
Thank you for your feedback

**Comment by philipto** [comment]
@Legambey Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by Legambey** [comment]
Thank you :)

**Pull request merged**
