### PR TITLE
Add Scholen aan Zee

### PR DESCRIPTION
**Pull request by LazyColgate**
Our school allows students to follow a 2/3 year long computer science course in high school.

### CODE REVIEW

**Comment by philipto** [comment]
@LazyColgate First stage of verification passed, official domain for **Scholen aan Zee** is [ll.scholenaanzee.nl](https://ll.scholenaanzee.nl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by LazyColgate** [comment]
@philipto Thank you for responding! I'm very glad we can continue with this and I hope the pull request gets accepted.

**Comment by philipto** [comment]
@LazyColgate Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by LazyColgate** [comment]
@philipto I've successfully activated my school license and can now log into all JetBrains tools. Thank you for assisting me! :)

**Comment by LazyColgate** [comment]
@philipto I saw the license would expire after only a year, but I'm taking the CS course for 3. Is it possible to renew the license afterwards? Or is it only a one-time thing?

**Pull request merged**
