### PR TITLE
ENSET Mohammedia

### PR DESCRIPTION
**Pull request by YasserElj**
Adding ENSET Mohammedia 

@etu.enset-media.ac.ma

### CODE REVIEW

**Comment by philipto** [comment]
@YasserElj First stage of verification passed, official domain is [enset-media.ac.ma](https://enset-media.ac.ma) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by YasserElj** [comment]
@philipto Ok, thanks for the info!

**Comment by philipto** [comment]
@YasserElj Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by YasserElj** [comment]
@philipto thank you so much for your help. 🙏

**Pull request merged**
