### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by dvnbaas**
www.laurenslyceum.nl

Laurens Lyceum
Voorhout 100, 3055 ES Rotterdam
The Netherlands

### CODE REVIEW

**Comment by philipto** [comment]
@dvnbaas First stage of verification passed, official domain is [laurenslyceum.nl](https://laurenslyceum.nl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by dvnbaas** [comment]
> @dvnbaas First stage of verification passed, official domain is [laurenslyceum.nl](https://laurenslyceum.nl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Thanks for the quick response and informative update. I wait patiently. Good day.

**Comment by philipto** [comment]
@dvnbaas Pull request merged. Thank you!

**Comment by dvnbaas** [comment]
> @dvnbaas Pull request merged. Thank you!

Great, thank you!

**Pull request merged**
