### PR TITLE
Added Kahramanmaras TOBB Fen Lisesi.

### PR DESCRIPTION
**Pull request by M-Enes**

### CODE REVIEW

**Comment by philipto** [comment]
@M-Enes Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@M-Enes You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@M-Enes I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by M-Enes** [comment]
I am sorry for a late answer. I send necessary infos immediately.

27 Nis 2021 Sal 18:23 tarihinde Philip Torchinsky ***@***.***>
şunu yazdı:

**Comment by M-Enes** [comment]
Kahramanmaras Tobb Fen Lisesi is a high school in Kahramanmaras, Turkey.

[Kahramanmaras Tobb Fen Lisesi Website](https://tobbfenlise.meb.k12.tr/)

**Comment by philipto** [comment]
The problem is that the domain kmarastobbfenlisesi.net is not mentioned anywhere at https://tobbfenlise.meb.k12.tr/

**Comment by M-Enes** [comment]
@philipto in Turkey, .meb.k12.tr domain is a necessary for a high school website. So, student e-mail address domains different than .meb.k12.tr. I hope you will understand me.

**Comment by philipto** [comment]
@M-Enes Yes, I understand you. However we cannot add a domain to this repository without any evidence confirming that the school recognizes the domain as valid for their students. If you don't have the evidence, please apply with official document at https://www.jetbrains.com/shop/eform/students (OFFICIAL DOCUMENT tab).

**Comment by M-Enes** [comment]
I understand. I apply my official document. Thanks @philipto. Have a good day.

**Pull request closed without merging**
