### PR TITLE
Please add Virtual OpenHouse Learning

### PR DESCRIPTION
**Pull request by KudakwasheMuranda**
Please add Virtual Openhouse Learning to the Academic school List

### CODE REVIEW

**Comment by philipto** [comment]
@KudakwasheMuranda Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* **an accreditation of the school by the Ministry of Education, clearly indicating that the school is recognized by the Ministry as an official school having the right to teach and issue diplomas of certain level.**

Providing the info stated above does not guarantee adding the domain to this repository. We'll also have to double check the admission criteria. Also, please let us know whether the school has a fee for the study, and if yes, how much is the fee.

**Comment by philipto** [comment]
@KudakwasheMuranda You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@KudakwasheMuranda I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by KudakwasheMuranda** [comment]
Good Day
Sorry for the late reply. We had closed for the Easter Holidays 
 The school details are as follows:
1. official website => https://www.vol.ac.zw/
2. Physical Address => The VOL Centre. 36 Cecil Road, Greendale, Harare, Zimbabwe
3. Programms => http://vol.ac.zw/study-programs
4. Our accreditations is still pending from the ministry so unfortunately I wont be able to provide it now 
Thank you for you consideration. We are still a starting school so some of the docs take some time to get

**Pull request closed without merging**
