### PR TITLE
Added: Atlas College - www.atlascollege.nl

### PR DESCRIPTION
**Pull request by plobachev**
Atlas College, Netherlands - atlascollege.nl

group of colleges in Netherlands:
1. Copernicus SG - www.copernicushoorn.nl
2. OSG West-Friesland - www.osgwestfriesland.nl
3. SG De Dijk - www.sgdedijk.nl
4. SG De Triade - www.detriade.nl
5. SG Newton - www.sgnewton.nl 

Technology track:
1. SG De Dijk: https://www.sgdedijk.nl/onderwijs/talentroutes-plusvakken/techniek-vmbo-mavo-havo-vwo/
2. OSG West-Friesland: https://www.osgwestfriesland.nl/watkiesjij/keuzemogelijkheden/technasium/
3. SG De Triade: https://www.detriade.nl/onderwijs/profielen/media-vormgeving-ict/

All colleges use one domain for emails: atlascollege.nl

https://www.atlascollege.nl/contact/contactgegevens/
https://copernicushoorn.nl/contact/contactgegevens/
https://www.osgwestfriesland.nl/contact/contactgegevens/
https://www.sgdedijk.nl/contact/contactgegevens/
https://www.detriade.nl/contact/kaart-route/
https://sgnewton.nl/contact/contactgegevens/

### CODE REVIEW

**Comment by plobachev** [comment]
All colleges use one domain for emails: atlascollege.nl

https://www.atlascollege.nl/contact/contactgegevens/
https://copernicushoorn.nl/contact/contactgegevens/
https://www.osgwestfriesland.nl/contact/contactgegevens/
https://www.sgdedijk.nl/contact/contactgegevens/
https://www.detriade.nl/contact/kaart-route/
https://sgnewton.nl/contact/contactgegevens/

**Comment by philipto** [comment]
@plobachev lib/domains/atlascollege.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by plobachev** [comment]
@philipto Thank you for fixing my PR. Should I do anything else? Or is it good now? :)

**Comment by philipto** [comment]
@plobachev Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
