### PR TITLE
Add new Amity address 

### PR DESCRIPTION
**Pull request by Nateaaaaaaaaaaaaaaaaaaaa**
The email domain currently registered for Amity Regional High School, amityschools, is old and currently inaccessible. The current email domain is amityregion5

### CODE REVIEW

**Comment by philipto** [comment]
@Nateaaaaaaaaaaaaaaaaaaaa First stage of verification passed, official domain for **Amity Regional High School** is [amityregion5.org](https://amityregion5.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Nateaaaaaaaaaaaaaaaaaaaa** [comment]
Also if this gets approved I would encourage a removal of the amityschools entry as it is currently useless to keep in there

**Comment by philipto** [comment]
@Nateaaaaaaaaaaaaaaaaaaaa Please provide us with:
* the school official website URL.
* the school street address, including city and country.

Thank you.

**Comment by Nateaaaaaaaaaaaaaaaaaaaa** [comment]
1. [https://www.amityregion5.org/arhs](url)
2. 25 Newton Rd, Woodbridge, CT 06525

**Comment by philipto** [comment]
@Nateaaaaaaaaaaaaaaaaaaaa Thank you for the update, the clarifications, and your patience while waiting for a review and processing your request. Pull request merged. 

I also removed amityschools.org from the repository.

**Pull request merged**
