### PR TITLE
added IS INFO

### PR DESCRIPTION
**Pull request by Erickael**

### CODE REVIEW

**Comment by philipto** [comment]
@Erickael First stage of verification passed, official domain for **Institut Supérieur d'Informatique (IS-INFO)** is [isinfo.mg](https://isinfo.mg) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Erickael** [comment]
Thank you very much sir

**Comment by philipto** [comment]
@Erickael Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by Erickael** [comment]
https://www.isinfo.mg/wp-content/uploads/2022/02/arrete_troisieme_vague_2_20140001.pdf

in this pdf, they list some universities that have been validated by the Madagascar state of higher education, it specifies that IS INFO's students can have their diploma (engineering diploma) after 10 semesters of study (5 years).
Hope this will be accepted :')

**Comment by philipto** [comment]
@Erickael Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by Erickael** [comment]
Thank you very much Sir

**Pull request merged**
