### PR TITLE
Tranquillity

### PR DESCRIPTION
**Pull request by MonkeyKiing25**

### CODE REVIEW

**Comment by philipto** [comment]
@MonkeyKiing25 First stage of verification passed, official domain is [tranquillity.ee](https://tranquillity.ee) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by MonkeyKiing25** [comment]
Hi,
Thank you for your email.
Please let me know if you need more information.
Look forward to hearing from you!

**Comment by philipto** [comment]
@MonkeyKiing25 Regrettably, this request has signs of fraud. I have to close it without merging.

**Comment by MonkeyKiing25** [comment]
Hi,
Why you told this is fraud without telling me any information?

**Comment by philipto** [comment]
Hi,I am sorry, I cannot disclose what was specifically suspicious in your request due to security reasons.I did not say that your request was a fraud. I said the request had signs of fraud. It means, the request *might be* a fraud.Also, I recommend to apply for a license with documents that confirm your student or teacher status. It is to grant you the free license without adding the email domain to the trusted list.Thank you for your understanding!On 30. Apr 2023, at 6.11, Monkey King ***@***.***> wrote:﻿
Hi,
Why you told this is fraud without telling me any information?

**Comment by MonkeyKiing25** [comment]
Hi,
I dont know why this request was marked as a fraud. Do I need to use admin
account with domain name to request again?
Looking forward to hearing from you.

**Pull request closed without merging**
