### PR TITLE
Added edu.campusvejle.dk for all CampusVejle Colleges

### PR DESCRIPTION
**Pull request by dnatabar**
Site for the school(s) is aspit.dk but they are all part of CampusVejle, hence the domain.
Proof should be shown on campusvejle.dk with a link to AspIT as part of CampusVejle.

### CODE REVIEW

**Comment by zweizwei** [comment]
@dnatabar please fix the path to dk/edu/campusvejle.txt

**Comment by philipto** [comment]
@dnatabar Thank you. I sent an email to info@campusvejle.dk in order to confirm that addresses in campusvejle.dk domain can be described as "AspIT at CampusVejle", and the emails from the domain are used by students and teachers only. It may make more sense to describe the domain as "CampusVejle". I am waiting from their response.

**Comment by zweizwei** [comment]
I will close the request as being obsolete. @dnatabar please reply to reopen.

**Comment by HackerFinn** [comment]
If a link from campusvejle.dk to aspit.dk confirming their relation, is enough, then this should suffice:
image

The area with the link is a list of schools that are a part Campus Vejle.

**Comment by philipto** [comment]
@HackerFinn @dnatabar Thank you, now it's clear. In this case I suggest you to apply for Classroom license by email to classroom@jetbrains.com. This license is also free and specifically designed for similar cases. If there are any concerns preventing you from requesting Classroom licenses please feel free to comment here. The Classroom license is convenient if you need it for one relatively small school within larger institution. Thank you!

**Pull request closed without merging**
