### PR TITLE
Create hakodate.txt

### PR DESCRIPTION
**Pull request by yoneya1014**

### CODE REVIEW

**Comment by yoneya1014** [comment]
create NIT hakodate college

**Comment by philipto** [comment]
@yoneya1014 Please rename `lib/ domains/ jp/ kosen-ac/hakodate.txt` to lib/domains/jp/kosen-ac/hakodate.txt (no extra spaces necessary). Thank you!

**Comment by philipto** [comment]
@yoneya1014 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@yoneya1014 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
