### PR TITLE
added szkolawchmurze

### PR DESCRIPTION
**Pull request by Amin-Maatallah**

### CODE REVIEW

**Comment by atiliocedeno** [comment]
hi Amin, how am i able to gain access to the repo? i am triying to add my university

**Comment by cesarmayo18** [comment]
> hi Amin, how am i able to gain access to the repo? i am triying to add my university

Could you be doing something wrong? @atiliocedeno

**Comment by Amin-Maatallah** [comment]
> hi Amin, how am i able to gain access to the repo? i am triying to add my university

Fork the repository and add the file you generated (unzipped, following the directory structure) to it. Then create a pull request from the forked repository.

**Comment by philipto** [comment]
@Amin-Maatallah Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
