### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AMFMleader**
University of Solvay in Brussels
University website: https://exed.solvay.edu/
Student email has the following build: name@solvaypostgrad.net

Advanced master that includes machine learning that needs python  https://exed.solvay.edu/en/11-program/542-advanced-master-in-financial-markets-2?utm_source=adwords&utm_medium=ppc&utm_term=solvay%20master%20financial%20markets&utm_campaign=N4.1+-+AM+programs+-+BE+-2019&hsa_cam=8924254275&hsa_mt=e&hsa_ver=3&hsa_src=g&hsa_ad=494615038508&hsa_net=adwords&hsa_tgt=kwd-1646292526038&hsa_acc=2682379331&hsa_grp=89933922476&hsa_kw=solvay%20master%20financial%20markets&gclid=CjwKCAiAoL6eBhA3EiwAXDom5rWTXkcVrSbYTlgUDqxUbQ0SdBOsyvp6Jd9mwbLw6X_tSXXiibys2BoCCSsQAvD_BwE

Jetbrains access would be used for the machine learning and AI courses

### CODE REVIEW

**Comment by CpETraveler** [comment]
[file.zip](https://github.com/JetBrains/swot/files/10497323/file.zip)

**Comment by philipto** [comment]
@AMFMleader Please provide us with:
* some more info on email address retention policy: do graduated students lose access to their email addresses after graduation, or keep the addresses for their lifetime?
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by AMFMleader** [comment]
@philipto 

Graduated Students lose their access to their email addresses and their Microsoft 365 upon the end of the year 

We received an email on our main email address, since I cannot upload a .eml file I converted it to pdf, hope this has the required information to confirm the @solvaypostgrad.net  [Email instructions.pdf](https://github.com/JetBrains/swot/files/10549371/Email.instructions.pdf)

**Comment by philipto** [comment]
@AMFMleader  Thank you for the clarifications. Pull request merged.

**Pull request merged**
