### PR TITLE
Create it_academy_it_park.txt

### PR DESCRIPTION
**Pull request by MATE-Programming**

### CODE REVIEW

**Comment by philipto** [comment]
@MATE-Programming lib/domains/uz/it_academy_it_park.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@MATE-Programming lib/domains/uz/it_academy_it_park.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by MATE-Programming** [comment]
Hi!

I have made some corrections. Can you recheck my request, please?

**Comment by philipto** [comment]
@MATE-Programming I have to close this request as a duplicate to #11697

**Pull request closed without merging**
