### PR TITLE
Links here

### PR DESCRIPTION
**Pull request by brosssh**
https://www.itstechtalentfactory.it/
https://www.itstechtalentfactory.it/i-nostri-corsi/
My last commit contained an email that it's not valid anymore, this is the correct one

### CODE REVIEW

**Comment by philipto** [comment]
@Brosssh 

>  My last commit contained an email that it's not valid anymore, this is the correct one

Please let us know what is an incorrect domain, to let us removing it from the repository.

**Comment by philipto** [comment]
@Brosssh  Thank you for the clarification. Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by Brosssh** [comment]
The thing is that the `itstechtalentfactory` domain cannot receive emails from external domains, while the email sent at `itstalentfactory.onmicrosoft.com` get delivered in the `itstechtalentfactory` inbox. If it's possible, you can sent me an email at `mattia.broch@itstalentfactory.onmicrosoft.com` and i will show you that the message it's actually delivered to the normal `itstechtalentfactory` domain, which is the official email domain of the school.

**Comment by Brosssh** [comment]
image

Thank you! Is this enough as a proof? i'm hovering my email name on outlook

**Comment by philipto** [comment]
@Brosssh  Thank you for the clarifications. Pull request merged.

**Pull request merged**
