### PR TITLE
Add New Domaine and delete file

### PR DESCRIPTION
**Pull request by saharmadroumi**
I removed file.zip thank you

### CODE REVIEW

**Comment by saharmadroumi** [comment]
I removed file.zip thank you

**Comment by saharmadroumi** [comment]
Remove file.zip thank you

**Comment by philipto** [comment]
@saharmadroumi First stage of verification passed, official domain is [um5.ac.ma](https://um5.ac.ma) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: http://www.fsr.um5.ac.ma/page/membres-du-conseil-et-repr%C3%A9sentants-de-la-facult%C3%A9

**Comment by philipto** [comment]
@saharmadroumi Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
