### PR TITLE
Yncrea ouest

### PR DESCRIPTION
**Pull request by sealghul**
Domain: @yncrea-ouest.fr
Name: Yncrea ouest brest (France)

### CODE REVIEW

**Comment by ucefidel** [comment]
[file (1).zip](https://github.com/JetBrains/swot/files/5471482/file.1.zip)

**Comment by ucefidel** [comment]
for Unversité d'Evry from France

**Comment by philipto** [comment]
@sealghul Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@sealghul You might miss my previous comment. Please react.

**Comment by sealghul** [comment]
Hello,
I apologize I didn't see your email.
About the School I made a mistake. I wrote @yncrea-ouest.fr instead of @
isen-ouest.yncrea.fr, which already exists on the root.
Sorry about that, and thank you for your time.


Le dim. 8 nov. 2020 à 20:26, Philip Torchinsky <notifications@github.com> a
écrit :

**Comment by philipto** [comment]
@sealghul Thank you for the clarification. I close the request.

**Pull request closed without merging**
