### PR TITLE
Add bbailigan.com

### PR DESCRIPTION
**Pull request by bkintanar**
bbailigan.com

### CODE REVIEW

**Comment by philipto** [comment]
@bkintanar First stage of verification passed, official domain is [bbailigan.com](https://bbailigan.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by bkintanar** [comment]
Thanks @philipto

**Comment by philipto** [comment]
@bkintanar The official website looks pretty outdated. Is there any reason it's not updated for about a year?

**Comment by bkintanar** [comment]
@philipto actually there's a reason for that, we've started using a school management system and the url is at https://bbailigan.skooltek.co/

**Comment by philipto** [comment]
@bkintanar  Thank you for the clarifications. Pull request merged.

**Comment by bkintanar** [comment]
Thank you very much @philipto 

How long should I wait for the changes to reflect to apply for the free education license?

**Pull request merged**
