### PR TITLE
Add Leseding Computer System domain file

### PR DESCRIPTION
**Pull request by Kgaugelo-Molema**
http://lsdc.co.za/classic/topbar/html/pages/systems-development2.html

### CODE REVIEW

**Comment by philipto** [comment]
@Kgaugelo-Molema Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school

**Comment by Kgaugelo-Molema** [comment]
@philipto Find below our 18 months course offered by our instituion on a full-time basis.
[](http://lsdc.co.za/classic/topbar/html/pages/systems-support.html)

**Comment by Kgaugelo-Molema** [comment]
@philipto Will you kindly give feedback on the progress of the pull-request. Is there anything you need from me?

**Comment by philipto** [comment]
@Kgaugelo-Molema Thank you for the clarification. Pull request merged.

**Pull request merged**
