### PR TITLE
Create mytwu

### PR DESCRIPTION
**Pull request by viccopicco**

### CODE REVIEW

**Comment by philipto** [comment]
@viccopicco You submit a file with a path `lib/domains/ca/bc/mytwu`, and there is no domain mytwu.bc.ca. Did you mean an email domain `mytwu.ca`? If yes, the file path must be `lib/domains/ca/mytwu.txt`. Please note that .txt extension is mandatory. Please rename the file accordingly. Thank you!

**Comment by philipto** [comment]
@viccopicco Could you please update the request according the comment above? Thank you.

**Comment by viccopicco** [comment]
Absolutely! I will make that change right now!

**Comment by philipto** [comment]
@viccopicco I am sorry, I see no changes in this request. I have to close it without merging. Please submit a new request as soon as you decide which domain is to be submitted. Thank you!

**Pull request closed without merging**
