### PR TITLE
Create konradlorenz

### PR DESCRIPTION
**Pull request by alex0520**
domain file name to www.konradlorenz.edu.co

### CODE REVIEW

**Comment by philipto** [comment]
@alex0520 Please rename `lib/domains/co/edu/konradlorenz` to `lib/domains/co/edu/konradlorenz.txt`. Thank you!

**Comment by philipto** [comment]
@alex0520 You might miss my previous message regarding this request. Could you please update it as described above to reflect the repository rules? Thank you!

**Comment by alex0520** [comment]
@philipto I updated the file, as you suggested, sorry about the delay.

**Comment by philipto** [comment]
@alex0520 Thank you! Pull request merged. I am sorry that its processing took a bit more time than it was expected.

**Pull request merged**
