### PR TITLE
ADDED FILES FOR A NEW INSTITUTE

### PR DESCRIPTION
**Pull request by Jesusantiago**
The file “eep-igruop.txt” has been added for the eep-igruop institute, corresponding to the School of Professional Studies. 

Sample email to be accepted : my_name@eep-igroup.com

Thank you very much.

### CODE REVIEW

**Comment by Jesusantiago** [comment]
This is the link: https://eep-igroup.es/

**Comment by philipto** [comment]
@Jesusantiago Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

Thank you!

**Comment by Jesusantiago** [comment]
Hello @philipto, of course: 

- The school official website URL: 
https://eep-igroup.es/

- The school street address, including city and country:
 C. Torrelaguna, 123, Cdad. Lineal, 28043 Madrid. - https://g.co/kgs/rf4546z (Link)

This is the institute where I study, but they have several branches.


- An URL of a page on the official website where the school offers an IT-related long-term (>1 year) course:
https://www.eep-igroup.es/tecnico-superior-doble-titulacion-dam-daw.php


The professional studies that I am doing are those sent, I have seen that they do not have the duration expressed in years, but in hours. Every 1000 hours corresponds to 1 year.


Thank you for your time.

**Comment by philipto** [comment]
@Jesusantiago  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by Jesusantiago** [comment]
Thank you very much for your time, have a nice day 😃.

**Pull request merged**
