### PR TITLE
adding uad - universidad de artes digitales

### PR DESCRIPTION
**Pull request by dPeluChe**
adding uad - universidad de artes digitales

### CODE REVIEW

**Comment by dPeluChe** [comment]
adding uad - universidad de artes digitales

**Comment by dPeluChe** [comment]
School official website URL: https://uartesdigitales.edu.mx/
School official name: UAD - Universidad de Artes Digitales
School official address: Andrés Terán #1106, Col. Mezquitán Country; Guadalajara, Jalisco,
Proof that the school recognizes the domain as an official email domain: jmartinezq@uartesdigitales.edu.mx

The school offers  Software development  and gameplay development  programs for the students.

**Comment by philipto** [comment]
@dPeluChe First stage of verification passed, official domain is [uartesdigitales.edu.mx](https://uartesdigitales.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@dPeluChe Pull request merged. Thank you.

**Pull request merged**
