### PR TITLE
upload files for LIT

### PR DESCRIPTION
**Pull request by SQSeven7**
Luoyang Institute of Science and Technology

### CODE REVIEW

**Comment by SQSeven7** [comment]
the university official website URL, if it is different from the domain you are submitting:

https://www.lit.edu.cn/

a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university:

https://www.lit.edu.cn/jsjxy/xb2022/rcpy/pyfa.htm#:~:text=%E4%BA%BA%E6%89%8D%E5%9F%B9%E5%85%BB%20%3E-,%E5%9F%B9%E5%85%BB%E6%96%B9%E6%A1%88,%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%A7%91%E5%AD%A6%E4%B8%8E%E6%8A%80%E6%9C%AF%E4%B8%93%E4%B8%9A%E5%9F%B9%E5%85%BB%E6%96%B9%E6%A1%88,-2020%2D04%2D22

a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.

a screenshot here:
screenshot

The official website of my university email system is https://mail.lit.edu.cn/Home.  Now the email system is based on Tencent Enterprise Email System (the official website is https://work.weixin.qq.com/mail/), so the domain name of the mail assigned to me is zhll3.wecom.work rather than lit.edu.cn used before.

**Comment by philipto** [comment]
@SQSeven7 Thank you for your patience and clarifications! **Please send an email message** to community-support@jetbrains.com, mentioning this request URL https://github.com/JetBrains/swot/pull/19968. We need to clarify several questions we have with regard the school's policy and your identity, and for your security we wish to avoid publishing the details on GitHub.

**Comment by philipto** [comment]
@SQSeven7 Have a happy New Year! Please send the message I mentioned in the previous comment as soon as you are back to work. Thank you!

**Comment by philipto** [comment]
@SQSeven7 I am sorry, this request remains unanswered for too long. Please send the e-mail message to us if you still need help.

**Pull request closed without merging**
