### PR TITLE
Request to add amrit Campus

### PR DESCRIPTION
**Pull request by geekyarthurs**

### CODE REVIEW

**Comment by philipto** [comment]
@geekyarthurs Please provide us with a proof which shows that the school recognizes the domain ac.tu.edu.np, which you are submitting, as an official email domain for the students.

**Comment by philipto** [comment]
@geekyarthurs You might miss my previous comment. Please react.

**Comment by geekyarthurs** [comment]
I'm an student. Can you tell me what kind of proof it requires so I can tell my college.

**Comment by philipto** [comment]
@geekyarthurs Your school's official website is http://amritcampus.edu.np/

Please give us an URL of the page at the official website where it's said that ac.tu.edu.np is an email domain which the school recognizes as an official email domain for the students. If you have a written instruction from the school which explicitly says that, please attach a copy of this instruction to your comment here.

The proof can also be an email which the schools sent to you upon the enrollment.

Thank you.

**Comment by philipto** [comment]
@geekyarthurs I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
