### PR TITLE
Add IUV txt file

### PR DESCRIPTION
**Pull request by davsaniuv**

### CODE REVIEW

**Comment by philipto** [comment]
@davsaniuv First stage of verification passed, official domain is [iuv.edu.mx](https://iuv.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@davsaniuv Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by wrtisans** [comment]
Hello, here is a software development course 

https://virtual.iuv.edu.mx/oferta-educativa/posgrados/maestria-ingenieria-desarrollo-software/

**Comment by philipto** [comment]
@davsaniuv  Thank you for the clarifications. Pull request merged.

**Pull request merged**
