### PR TITLE
Add files via upload for Yoobee college

### PR DESCRIPTION
**Pull request by ranjurave**

### CODE REVIEW

**Comment by philipto** [comment]
@ranjurave Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@ranjurave You might miss my previous comment. Please react.

**Comment by ranjurave** [comment]
Thank you for the response. Here are the details

- Domian - https://www.yoobee.ac.nz/
- Address - Level 4, 3 City Road, Grafton, Auckland, New Zealand
- Course - https://www.yoobee.ac.nz/courses/technology/bachelor-of-software-engineering
- Email
- ranju.raveendran@yoobeecolleges.com (my email)
- image
 
Hope I was able to provide what is required
Thank you 
Ranju

**Comment by philipto** [comment]
@ranjurave  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
