### PR TITLE
Grand Terrace High School

### PR DESCRIPTION
**Pull request by NotBlackrus**
Hello! As a student at Grand Terrace High School, I am currently taking a AP computer science course that's currently exploring Java programming. I would greatly appreciate it if I could use this service for creating Java code without having to pay for school.

image

On behalf of my school and the entire district, we would GREATly appreciate if you allowed us to be on the list!

### CODE REVIEW

**Comment by philipto** [comment]
@NotBlackrus lib/domains/cjusd/Grand: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@NotBlackrus Please let us know what is your email address template. Is it username@grand.cjusd.org?
I appreciate it very much if you reply this comment or change the filename in your request to the one conforming the [repository rules](https://github.com/JetBrains/swot?tab=readme-ov-file#how-to-add-a-domain-to-this-repository). Thank you!

**Comment by philipto** [comment]
@NotBlackrus I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by NotBlackrus** [comment]
> @NotBlackrus I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

oh! oh! and I had just saw this, I am so so sorry! The answer to that question was simply just @my.cjusd.net

**Pull request closed without merging**
