### PR TITLE
Add Institution

### PR DESCRIPTION
**Pull request by ismaelms97**
Added Ins Baix Camp

### CODE REVIEW

**Comment by philipto** [comment]
@ismaelms97 Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by ismaelms97** [comment]
Official website: [](http://insbaixcamp.org/),
Page where are offered the courses: [](http://insbaixcamp.org/index.php/oferta-d-estudis/cicles-formatius/cf-de-grau-mitja-2)
Proof that I am an student of that institution in the following image: 
MVIMG_20190311_091148_968

**Comment by philipto** [comment]
@ismaelms97 Thank you for the update and the clarification. You submitted enough information to grant a free license to you personally, but not to add your university to this repository. 

We need to ensure that the university recognizes the domain which you are submitting, insbaixcamp.es, as an official email domain for the students. The image which you kindly attached does not prove it.

Do you have any proof the university recognizes insbaixcamp.es as an official email domain for the students? 

Thank you!

**Comment by ismaelms97** [comment]
Hello, the domain name its incorrect, the correcto one is insbaixcamp.cat,
I think i put It in the wrong domain library, i'm sorry, there's any way to replace It to the Cat folder instead of the ES folder?

**Comment by philipto** [comment]
@ismaelms97 Yes, it's no problem at all. Just rename lib/domains/es/insbaixcamp.txt to lib/domains/cat/insbaixcamp.txt

If you don't know how to rename the file, or have any other trouble with the request, please create a new pull request with a single file lib/domains/cat/insbaixcamp.txt

Thank you!

**Comment by philipto** [comment]
@ismaelms97 Thank you for the update! Pull request merged.

**Pull request merged**
