### PR TITLE
Add domain global.educanet2.ch

### PR DESCRIPTION
**Pull request by LucasAymon**
Educanet website : https://educanet2.ch/

### CODE REVIEW

**Comment by philipto** [comment]
@LucasAymon Educanet2 is a Switzerland's country-wide system providing national educational organizations with resources, including email addresses. As far as I know, the system provides individual subdomains to each educational organization, such as bzwu.educanet2.ch (see #1883, for example). This repository hosts email domains belonging to universities and colleges, not umbrella organizations. Could you please specify which university does have an email domain global.educanet2.ch?

**Comment by LucasAymon** [comment]
The domain global is for all university. It's a global domain.

**Comment by philipto** [comment]
@LucasAymon I am sorry, is there a reason why any of the universities in Switzerland may use this domain instead of a domain which belongs to a particular university, such as bzwu.educanet2.ch, for example? How many universities use global domain instead of a domain specific to a particular university? Are there other organizations which use this global domain, apart from colleges and universities?

**Comment by philipto** [comment]
@LucasAymon I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
