### PR TITLE
Add ICT-Scouts / Campus

### PR DESCRIPTION
**Pull request by PReimers**

### CODE REVIEW

**Comment by philipto** [comment]
@PReimers I am sorry, it is not clear from the official website, if ICT-Scouts / Campus is a university or a college. Could you please make it clearer?

**Comment by PReimers** [comment]
Hi @philipto 

It's a Highschool specified on IT education.

IT related courses are:
* Development (web / native / mobile)
* VR
* Robotics
* and more

The courses have different durations from 3 months up to 3 years.

If you want to know more, just ask :wink:

**Comment by philipto** [comment]
@PReimers Could you please tell me what exactly at the website says that it's a high school? Google translate can be wrong, but as far as I can understand the website (which has just very basic and little info on the organization), ICT Campus is a kind of assosiation for both employers and schools, and it does not enroll students for long courses, but rather provide space (virtual? physical? mental?) for schools and employers to meet and study (?) Which page has a description of the course(s)?

**Comment by PReimers** [comment]
Hi @philipto 

1. The Website tells nothing about it. We only provide basic information on the website.
If you want to know us. Visit us!
2. We also provide courses/training for teachers. But teachers don't get an E-Mail address/account from us.
3. The schedule and courses are not publicly visible. If you want to know more, contact us.

I'm closing the PR and contacting the Support because I don't think you're qualified enough.

**Pull request closed without merging**
