### PR TITLE
Added Manche Open School

### PR DESCRIPTION
**Pull request by MyTheValentinus**

### CODE REVIEW

**Comment by MyTheValentinus** [comment]
@fxguidet

**Comment by MyTheValentinus** [comment]
website is http://www.mancheopenschool.fr/
For example my email is: v.deville@mancheopenschool.fr

**Comment by zweizwei** [comment]
@MyTheValentinus Sorry for the delay - we've been launching rebranding and I hadn't time to check the repo for a while. 

Could you please point at the page, that describes long term (>1year) educational courses that the school provides? thank you.

**Comment by MyTheValentinus** [comment]
Yes, this link will help you http://www.mancheopenschool.fr/#progevo .

You may also contact directly the direction's members through the contact form at this address : http://www.mancheopenschool.fr/#contactfaq or with the director's email (yannick@mancheopenschool.fr)

Thank you.

**Comment by zweizwei** [comment]
@MyTheValentinus thanks for the provided links - that's exactly what i needed. I'm adding the domain now.

**Comment by MyTheValentinus** [comment]
Thank a lot !

**Pull request merged**
