### PR TITLE
contribution

### PR DESCRIPTION
**Pull request by mailtoamirjohn**
added college

### CODE REVIEW

**Comment by philipto** [comment]
@mailtoamirjohn I am sorry, the webpage of http://www.madhaengineeringcollege.edu.in does not exist. Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

Also, please notice that the file name must end with an extension .txt. Please rename the file in your request accordingly. Thank you!

**Comment by philipto** [comment]
@mailtoamirjohn You might miss my previous comment. Please reply it, otherwise I will have to close the request withoiut merging. Thank you!

**Comment by mailtoamirjohn** [comment]
Hi,

College webpage link : http://www.madhaengineeringcollege.com/

**Comment by philipto** [comment]
@mailtoamirjohn I am sorry, I need some proof that madhaengineeringcollege.edu.in domain is used by the students of the college. Could you please refer me to a webpage on the website or another proof? Any document which says that students use the email addresses in madhaengineeringcollege.edu.in? Thank you!

**Comment by mailtoamirjohn** [comment]
@philipto Our college does not provide any sudents login page and all

**Comment by philipto** [comment]
@mailtoamirjohn Your request contains a file with a name lib/domains/in/edu/madhaEngineeringCollege. According the rules at the bottom of [this page](https://github.com/JetBrains/swot), it means that you wish to add a domain madhaengineeringcollege.edu.in, which does not exist. 

Please tell me what is an email address pattern in your college? Is it somebody@madhaengineeringcollege.com? If yes, the file path in the request must be lib/domains/com/madhaengineeringcollege.txt (please notice that .txt extension is mandatory).

Please rename the file, if necessary, or make a new request with correct file name and path. Thank you!

**Comment by philipto** [comment]
@mailtoamirjohn This request remains unanswered for a while. I have to close it without merging. Thank you for the understanding.

**Pull request closed without merging**
