### PR TITLE
Adding Barcelona Executive Business School

### PR DESCRIPTION
**Pull request by odetolakehinde**

### CODE REVIEW

**Comment by philipto** [comment]
@odetolakehinde First stage of verification passed, official domain for **Barcelona Executive Business School** is [bebs.org](https://bebs.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by odetolakehinde** [comment]
> @odetolakehinde First stage of verification passed, official domain for **Barcelona Executive Business School** is [bebs.org](https://bebs.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Thanks @philipto 

how long on an average does this take?

**Comment by philipto** [comment]
@odetolakehinde 

> how long on an average does this take?

It depends. Usually it takes one-two days, but if something is unclear it may take more. In case of this school, we need some more information:

Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@odetolakehinde You might miss my previous comment. Please react.

**Comment by odetolakehinde** [comment]
> @odetolakehinde You might miss my previous comment. Please react.

hello. yes, I missed it.

Here's the course I'm currently taking that requires be to write code - https://bebs.org/programs/mba/international-business-management-innovation/

It's just a year though.

**Comment by philipto** [comment]
@odetolakehinde  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by odetolakehinde** [comment]
> @odetolakehinde Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

Successfully applied for it. thanks a lot!

**Pull request merged**
