### PR TITLE
Add new domain for Kiev Politechnical Institute 

### PR DESCRIPTION
**Pull request by andysyr**
Changelog:
* Added kpiapeps.txt

### CODE REVIEW

**Comment by andysyr** [comment]
* Official university web page: https://www.kpi.ua/en

* Unfortunately, I didn't find direct evidences from official university resources that the email domain kpiapeps.onmicrosoft.com is provided by the university, since my cathedra APEPS( https://apeps.kpi.ua/contacts/en) provides separate email domain for its students and doesn't document it in public resources. Instead, I found a Google Scholar profile of KPI APEPS ex-student with same verified domain who was actively publishing science works since 2002: https://scholar.google.com.ua/citations?user=QOEjQJsAAAAJ&hl=en

**Comment by philipto** [comment]
@andysyr Pull request merged. Thank you.

**Comment by andysyr** [comment]
@philipto thank you! when can I expect the JetBrains licence to be available for domain added in this PR?

**Comment by philipto** [comment]
It is usually available in an hour after the pull request merge.On 12. Jun 2024, at 20.45, andysyr ***@***.***> wrote:﻿
@philipto thank you! when can I expect the JetBrains licence to be available for domain added in this PR?

**Pull request merged**
