### PR TITLE
Added Te Wanaga O Aotearoa domain file

### PR DESCRIPTION
**Pull request by jarmez**
Added Te Wanaga O Aotearoa domain file

### CODE REVIEW

**Comment by philipto** [comment]
@jarmez First stage of verification passed, official domain for **Te Wānanga o Aotearoa** is [akonga.twoa.ac.nz](https://akonga.twoa.ac.nz) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@jarmez Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@jarmez You might miss my previous comment. Please react.

**Comment by jarmez** [comment]
Hi, please disregard this request. This university does not offer an IT related course, I am studying something else there. I am also not sure how I would get the email proof you are looking for.

**Comment by philipto** [comment]
@jarmez Thank you! I close the request as you asked.

If you still need JetBrains tools for some reason, please enroll to GitHub Student Developer Pack at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
