### PR TITLE
Add DTU University

### PR DESCRIPTION
**Pull request by linguini16**

### CODE REVIEW

**Comment by philipto** [comment]
@Linguini16 The domain registrant for **dtu.vn** is Trường Đại Học Duy Tân (Duy Tan University). This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Linguini16 Thank you for your request. While the domain seems to be registered by the university, there is no sign at the official university webpage that the university offers the domain to the students.

Please provide us with a proof, which shows that the school recognizes the domain **dtu.vn**, which you are submitting as an official email domain for the students.
You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

Thank you!

**Comment by Linguini16** [comment]
This is the official website address: https://duytan.edu.vn/
This is the email login address: https://mail.dtu.edu.vn/
Please help me confirm it. Thank you very much!

[image: image.png]

--
*Thank & Best Regards,*

*Hung Bui (Mr.)*
📞 +(84) 352893665
✉️ ***@***.***

**Comment by philipto** [comment]
@Linguini16 Thank you! Please re-upload the image via browser, don't send it by email. GitHub strips out all attachments sent by email.

**Comment by Linguini16** [comment]
@philipto 
Screenshot_11

**Comment by Linguini16** [comment]
@philipto 
My email address is: nguyentdieulinh17@dtu.edu.vn
Thankyou!

**Comment by philipto** [comment]
@linguini16 Thank you for the clarifications! The problem is that you submit the file lib/domains/vn/dtu.txt that represents a domain **dtu.vn**, not **dtu.edu.vn**. 

The domain dtu.edu.vn was removed from the repository because of the abuse in the past. Thus, you need to use another licensing option.

Please enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

I have to close this request without merging.
Thank you for your understanding!

**Pull request closed without merging**
