### PR TITLE
Adding Edueptm

### PR DESCRIPTION
**Pull request by Mathieu-Fr**
We are a vocational school in technical fields.

### CODE REVIEW

**Comment by Mathieu-Fr** [comment]
Mail domain : edueptm.ch
Officiel website : http://eptm.ch/

**Comment by philipto** [comment]
@Mathieu-Fr Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Mathieu-Fr** [comment]
@philipto
The whois of domain eptm : http://prntscr.com/hb4vqp
The whois of domain edueptm :
https://prnt.sc/hb4wc2

**Comment by Mathieu-Fr** [comment]
Its the new domain mail of eptsion.ch (domain already accepted but its old domain mai)

**Comment by philipto** [comment]
@Mathieu-Fr Thank you for the clarification! Pull request merged.

**Pull request merged**
