### PR TITLE
Whitelist eanesisd.net

### PR DESCRIPTION
**Pull request by EtherTyper**
It's a public shool district in Austin, Texas.

### CODE REVIEW

**Comment by philipto** [comment]
@EtherTyper Could you please give us a reference to a page on the official website where the school(s) offer long-term (> 1 year) IT-related educational program? Thank you!

**Comment by EtherTyper** [comment]
On page 62 of [course_catalog_16-17.5.pdf](https://github.com/JetBrains/swot/files/143461/course_catalog_16-17.5.pdf), it illustrates the Information Technology courses available to high school students learning there. No single class is greater than one year long, though Computer Science I, Computer Science II ADV, Computer Science Independent Study I, and Computer Science Independent Study II are related, consecutive courses.

The file uploaded is linked in the following chain from the school website:
- http://eanesisd.net/
- Next to the search bar under "Westlake High School", http://whschaps.com/
- Under "Counseling" in the school links section, http://westlakecounseling.weebly.com/
- Under "Course Selection" in the menu bar, http://westlakecounseling.weebly.com/course-selection.html
- Under "Course Guide 2016-17", http://westlakecounseling.weebly.com/uploads/2/7/7/5/27758565/course_catalog_16-17.5.pdf

**Comment by philipto** [comment]
@EtherTyper Thank you very much for the clarification! Pull request is now merged.

**Comment by EtherTyper** [comment]
@larry0618 @arnhav11 eanesisd.net whiltelisted for JetBrains student discounts

**Comment by larry0618** [comment]
Yay

Sent from my Fire

On February 23, 2016, at 6:00 PM, ELI JOSEPH BRADLEY <notifications@github.com> wrote:

@larry0618 @arnhav11 eanesisd.net whiltelisted for JetBrains student discounts

**Pull request merged**
