### PR TITLE
Add florida-uni

### PR DESCRIPTION
**Pull request by Pjorda96**
https://www.floridauniversitaria.es/

### CODE REVIEW

**Comment by philipto** [comment]
Please provide us with:
* a description of the school structure (there are florida-uni.es, florida.es, and floridauniversitaria.es, how do they relate to each other?)
* the school street address, including city and country
* the school full official name (to put in the file, you left it empty, and it contradicts the rules of the repository)
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by Pjorda96** [comment]
- The tree domains are the same but used for different people. Florida is for staff, florida-uni for lecturers and teachers, and floridauniversitaria for students.
- The adress: Carrer del Rei En Jaume I, 2, 46470 Catarroja, Valencia, Spain
- Full official name is "Florida Universitaria"
- The URL: https://www.floridauniversitaria.es/
- One proof could be on the official page (https://www.floridauniversitaria.es/) you can find an advertisement (last of the right column) for language courses that the email ends with @florida-uni.es

**Comment by philipto** [comment]
@Pjorda96  Thank you for the clarifications. Pull request merged.

**Comment by Pjorda96** [comment]
@philipto Thank you very much

**Pull request merged**
