### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jayasuryashaju**
[nandhaengg.txt](https://github.com/JetBrains/swot/files/10018498/nandhaengg.txt)

### CODE REVIEW

**Comment by jayasuryashaju** [comment]
this is the college website  https://nandhaengg.org/

**Comment by philipto** [comment]
@jayasuryashaju First stage of verification passed, official domain is [nandhaengg.org](https://nandhaengg.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@jayasuryashaju Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by jayasuryashaju** [comment]
https://nandhaengg.org/about-the-departmentcse/ this is the link for the 4 year computer science course offered by our college

**Comment by philipto** [comment]
@jayasuryashaju  Thank you for the clarifications. Pull request merged.

**Pull request merged**
