### PR TITLE
Add OpenCampus university

### PR DESCRIPTION
**Pull request by yonjukyu**
Add Open Campus in the list of university

### CODE REVIEW

**Comment by philipto** [comment]
@yonjukyu Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@yonjukyu You might miss my previous comment. Please react.

**Comment by yonjukyu** [comment]
I saw it, i am asking for a proof, i'll reply with all the informations right when after i get it.

**Comment by philipto** [comment]
@yonjukyu This request was not updated for a while. I have to close it without merging. Please reopen it or create a new request when you have an update. Thank you.

**Pull request closed without merging**
