### PR TITLE
Add the new Carmel College domain

### PR DESCRIPTION
**Pull request by ChachyDev**

### CODE REVIEW

**Comment by philipto** [comment]
@ChachyDev Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by ChachyDev** [comment]
> @ChachyDev Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
> 
> You can provide us with any of the following:
> 
> 1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
> 
> 2. An URL of a page at the official school website that says that students use this email domain
> 
> 3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
> 
> 4. A WHOIS data that link the email domain to the school somehow
> 
> 5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
> 
> 6. Anything else that can prove this fact in similar way, i.e. can be verified independently.
> 
> 

https://carmel.bhcet.org.uk

**Comment by philipto** [comment]
@ChachyDev Thank you for your prompt reply! 
Is the school the same as https://www.carmel.ac.uk? If yes, please provide us with the proof as I asked above.
If not, please reply with the school street address, including city and country.

Thank you!

**Comment by ChachyDev** [comment]
> @ChachyDev Thank you for your prompt reply! 
> 
> Is the school the same as https://www.carmel.ac.uk? If yes, please provide us with the proof as I asked above.
> 
> If not, please reply with the school street address, including city and country.
> 
> 
> 
> Thank you!

No the school isn't. 

The address is
The Headlands
Darlington, England
DL3 8RW

**Comment by philipto** [comment]
@ChachyDev Thank you for the clarification. Pull request merged.

**Comment by ChachyDev** [comment]
> @ChachyDev Thank you for the clarification. Pull request merged.
> 
>

**Pull request merged**
