### PR TITLE
Create itivinci.txt

### PR DESCRIPTION
**Pull request by mvignone**

### CODE REVIEW

**Comment by philipto** [comment]
@mvignone Could you please provide some more details about the school? What are typical student's age in the institute? Where can we look at the curricula to identify an IT-related long-term course offered by the institute? Unfortunately, I did not find such an info at the official website.

**Comment by philipto** [comment]
@mvignone You might miss the previous comment. Could you please give us some more details, otherwise I will have to close the request with no merge. Thank you for your understanding.

**Comment by mvignone** [comment]
@philipto Sorry, I missed the first comment. The Industrial Technical Institute "Leonardo Da Vinci" is located in Carpi, near Modena (Italy). It is a public high school that offers courses in computer science, electronics, mechanical engineering and chemistry. The typical age of students is 14-19 years. The course in Computer Science lasts five years and aims to train professionals in software development and management of IT infrastructure.

**Comment by philipto** [comment]
@mvignone Thank you for the details. Pull request merged. Just for the record: courses list is at http://itivinci.mo.it/orario.html

**Pull request merged**
