### PR TITLE
Add IHE Delft Institute for Water Education

### PR DESCRIPTION
**Pull request by corzogac**
IHE Delft Institute for Water Education

### CODE REVIEW

**Comment by corzogac** [comment]
[un-ihe.txt](https://github.com/JetBrains/swot/files/3902463/un-ihe.txt)

**Comment by philipto** [comment]
@corzogac .github/PULL_REQUEST_TEMPLATE.md: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by corzogac** [comment]
Dear jetBrains

I was not able to place the pullrequest as mentioned. I cannot see any
instrucctions below the page where it mentions below. Also, the catalogue
pague redirects and it doesn't say any rules or information, just the git.

**Comment by philipto** [comment]
@corzogac .github/PULL_REQUEST_TEMPLATE.md: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@corzogac .github/PULL_REQUEST_TEMPLATE.md: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@corzogac .github/PULL_REQUEST_TEMPLATE.md: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@corzogac .github/PULL_REQUEST_TEMPLATE.md: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@corzogac I am sorry, I have to close the request without merging, because you made a mistake in a request and requested to merge too many files, most of them do not relate to the organization which you would like to add to this repository. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Comment by philipto** [comment]
@corzogac Please send an email to community-support@jetbrains.com with subject "ATTN: Philip Torchinsky" and let us know which email domain you wish to add to the list of domains known to JetBrains and allowed to request free licenses automatically. Thank you!

**Pull request closed without merging**
