### PR TITLE
Adding Lead University

### PR DESCRIPTION
**Pull request by OneTesseractInMultiverse**
Adding Lead University from Costa Rica

### CODE REVIEW

**Comment by philipto** [comment]
@OneTesseractInMultiverse First stage of verification passed, official domain is [ulead.ac.cr](https://ulead.ac.cr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by OneTesseractInMultiverse** [comment]
Awesome! Thanks!

**Comment by philipto** [comment]
@OneTesseractInMultiverse Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@OneTesseractInMultiverse You might miss my previous comment. Please react.

**Comment by OneTesseractInMultiverse** [comment]
Hi, sorry about that. Here is a link to our Data Science Engineering program: https://ulead.ac.cr/es/carreras/bachilleratos/bachillerato-ingenieria-en-ciencia-de-datos

**Comment by philipto** [comment]
@OneTesseractInMultiverse Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by OneTesseractInMultiverse** [comment]
Thank you very much!

**Pull request merged**
