### PR TITLE
Add MotivPlus.fr

### PR DESCRIPTION
**Pull request by j-catania**
Ceo : marie-anne.xavier@motivplus.fr
HQ : 173-103 rue murette 84120 Pertuis, France

### CODE REVIEW

**Comment by philipto** [comment]
@j-catania Do you have any long-term (longer than 1 year) courses in the school?

**Comment by philipto** [comment]
@j-catania Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@j-catania You might miss my previous comment. Please react.

**Comment by j-catania** [comment]
Hello @philipto !

I'm realy sorry, I asked to the one who can give us the correct informations but it's "vacancy Time" in France.

I will be back to you ASAP.
Thanks,
Julien

**Pull request closed without merging**
