### PR TITLE
Add Creekview High School

### PR DESCRIPTION
**Pull request by phamleduy04**

### CODE REVIEW

**Comment by philipto** [comment]
@phamleduy04 Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@phamleduy04 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@phamleduy04 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by phamleduy04** [comment]
[School Official URL](https://creekview.cfbisd.edu)
Address: 3201 Old Denton Rd Carrollton, TX 75007 USA
[URL offers an IT-related long-term (>1 year) course](https://creekview.cfbisd.edu/campus-information/counseling-office/course-selection)
You can go to cfbmail.com and it will redirect to School District Official URL.

**Pull request closed without merging**
