### PR TITLE
Add Wuxi Taying Middle School

### PR DESCRIPTION
**Pull request by sunxiyi**
The school website: http://www.wxstyzx.com/

### CODE REVIEW

**Comment by mxqnus** [comment]
how do you make a pull request is there a button I can press its so hard I swear

**Comment by yangyangxu1** [comment]
This is a fraud. The real official website of this school is http://wxtyzx.wxlxjy.com/, and the domain www.wxstyzx.com of this website is resolved in Tencent Cloud.别骗了哥们，卖授权不是这么卖的。

**Comment by kawa11** [comment]
image

**Comment by philipto** [comment]
@yangyangxu1 Thank you for the information.
@mxqnus Please apply for a free educational license with an official document that proves that you are a student. You can do it using the "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

There are different official ways of getting free educational license, don't submit an email domain to this repository if you cannot do it for whatever reason.

@sunxiyi Regrettably, this request has signs of fraud. I have to close it without merging. If you are a student of this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
