### PR TITLE
Create clevelandmetroschools

### PR DESCRIPTION
**Pull request by jcostello-cmsd**
Adding Cleveland Metro Schools to the list. CMSD contains over 31 high schools and STEM academies.

### CODE REVIEW

**Comment by jcostello-cmsd** [comment]
Please reach out if you have any questions regarding the inclusion of the Cleveland Metro School District domain in the JetBrains list.

**Comment by philipto** [comment]
@jcostello-cmsd lib/domains/org/clevelandmetroschools: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by jcostello-cmsd** [comment]
Apologies, forgot the file extension. I have added that in a new commit.

**Comment by philipto** [comment]
@jcostello-cmsd First stage of verification passed, official domain is [clevelandmetroschools.org](https://clevelandmetroschools.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@jcostello-cmsd Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
