### PR TITLE
Request to add FPT Aptech

### PR DESCRIPTION
**Pull request by longtt2512**
Please add FPT Aptech education from Vietnam. Thank you so much!

### CODE REVIEW

**Comment by philipto** [comment]
@longtt2512 Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

Thank you!

**Comment by longtt2512** [comment]
Thanks for replying. Unfortunately,  We don't have English website just Vietnamese language, but you can use translation to verify. This is the information of my university:

1. Official website URL: [](http://aptech.fpt.edu.vn)
2. An IT-related long-term course URL: [](http://aptech.fpt.edu.vn/adse2018.php) with 4 semesters, It costs atleast 2 years to finish.
3. an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students. => Sorry, I could not request Web Admin to add the proof into official website, so May I capture the email domain? Many thanks
screen shot 2019-01-28 at 5 05 47 pm

**Comment by philipto** [comment]
@longtt2512 Pull request merged. Thank you!

For the record: a proof of domain ownership is here: http://aptech.fpt.edu.vn/chitiet.php?id=4147

**Comment by longtt2512** [comment]
Wow, 👍 Thank you so much!!

**Pull request merged**
