### PR TITLE
Add "Gayatri Vidya Parishad College for Degree and PG Courses"

### PR DESCRIPTION
**Pull request by paagundu**
Site URL: https://www.gvpcdpgc.edu.in/
Mail Domain: `@gvpcdpgc.edu.in`

### CODE REVIEW

**Comment by philipto** [comment]
@paagundu lib/domains/edu/in/gvpcdpgc: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by paagundu** [comment]
@philipto Thank you for pointing it out, I swapped the `edu` and `in` directories. I have fixed the path now, kindly let me know if there is anything else that is out of place.

**Comment by SifCore** [comment]
> @philipto Thank you for pointing it out, I swapped the `edu` and `in` directories eariler. I have fixed the path now, kindly let me know if there is anything else that is out of place.
bro, the file needs to be in the .txt format

**Comment by philipto** [comment]
@paagundu lib/domains/in/edu/gvpcdpgc: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by paagundu** [comment]
@SifCore thank you!

Renamed with txt extension, should be good now.

**Comment by philipto** [comment]
@paagundu First stage of verification passed, official domain for **Gayatri Vidya Parishad College for Degree and PG Courses** is [gvpcdpgc.edu.in](https://gvpcdpgc.edu.in) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@paagundu Thank you for your adjustments and your patience while waiting for a review and processing your request. Pull request merged.

**Comment by paagundu** [comment]
Thank you for all the help @philipto!

Have a great day ahead.

**Pull request merged**
