### PR TITLE
Create viiipalo.txt

### PR DESCRIPTION
**Pull request by mjapl**
VIII Private Academic High School in Krakow, Poland
Our high school offers an International Baccalaureate Diploma Programme Computer Science course
https://viiipalo.krakow.pl/
part of PACK: https://pack.edu.pl/

### CODE REVIEW

**Comment by philipto** [comment]
@mjapl lib/domains/pl/edu/viiipalo: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by mjapl** [comment]
Thank you. I can see that you have already renamed the file. Everything is now consistent with the rules. Should I do anything else?

**Review by mjapl — COMMENTED** [review]
Everything is now consistent with the rules, thank you.

**Comment by philipto** [comment]
@mjapl Please provide us with a proof, which shows that the school recognizes the domain `viiipalo.edu.pl` that you are submitting as an official email domain for the students.

**Comment by mjapl** [comment]
@philipto Thank you. What kind of proof should I present? I am a teacher at this school (Mateusz Jabłoński, you can find me on the list of teachers here: https://viiipalo.krakow.pl/kadra/nauczyciele-2/) and I have an email account in this domains. I have just added it to my GitHub profile so that anyone can view it by visiting my profile. Would that be sufficient?

**Comment by philipto** [comment]
@mjapl Pull request merged. Thank you!

**Pull request merged**
