### PR TITLE
Create mayor.cl

### PR DESCRIPTION
**Pull request by javierreyesc1**
Universidad Mayor Sede Temuco. Email @mayor.cl (alumnos)

### CODE REVIEW

**Comment by philipto** [comment]
@javierreyesc1 Exuse me, do I get right that mayor.cl email domain is used by the university alumni, not current students and teachers?

**Comment by philipto** [comment]
@javierreyesc1 You might miss my previous comment on the matter. Could you please answer it? Without the clarification I have to close the request without merging. Thank you!

**Comment by javierreyesc1** [comment]
Sorry for not replying before your message, indeed the domain mayor.cl is
used by students of the Mayor university.

El 12/12/2016 1:42 p. m., "Philip Torchinsky" <notifications@github.com>
escribió:

@javierreyesc1 <https://github.com/javierreyesc1> Exuse me, do I get right
that mayor.cl email domain is used by the university alumni, not current
students and teachers?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JetBrains/swot/pull/2557#issuecomment-266481517>, or mute
the thread

**Comment by philipto** [comment]
@javierreyesc1 Thank you. Pull request merged, I also renamed mayor.cl to mayor.txt to reflect the repository rules.

**Pull request merged**
