### PR TITLE
Create bucksgfl.txt

### PR DESCRIPTION
**Pull request by grimm004**

### CODE REVIEW

**Comment by grimm004** [comment]
Site is http://www.bucksgfl.org.uk/

**Comment by zweizwei** [comment]
@grimm004 Sorry for the delay - we've been launching rebranding and I hadn't time to check the repo for a while. Could you please provide the link to the page, describing long-term (>1year) educational programs that the school provides? thank you!

**Comment by grimm004** [comment]
Buckinghamshire Grid for Learning is the place that controls the electronic part of educational sector in Buckinghamshire, England. The address for my school is http://swr.bucks.sch.uk/.

**Comment by zweizwei** [comment]
@grimm004 thanks for additional explanation. But is the domain used for students' and teachers' emails? - for internal development schools should use other types of licenses not educational license. Thank you.

**Comment by grimm004** [comment]
This email domain (username@bucksgfl.org.uk) is used only for students within Buckinghamshire, staff have a different domain (linked and controlled directly by the school).

**Comment by zweizwei** [comment]
@grimm004 thanks for additional information. I'm adding the domain then.

**Pull request merged**
