### PR TITLE
Add domain South China University of Technology

### PR DESCRIPTION
**Pull request by courageface**

### CODE REVIEW

**Comment by philipto** [comment]
@courageface If your university email address pattern is username@mail.scut.edu.cn, please rename lib/domains/com/edu/scut/mail.txt  to lib/domains/cn/edu/scut/mail.txt 

Thank you!

**Comment by philipto** [comment]
@courageface You might miss my previous comment. Please react.

**Comment by courageface** [comment]
> @courageface You might miss my previous comment. Please react.

Sorry, the path is renamed.

**Comment by philipto** [comment]
@courageface Pull request merged. Thank you!

**Pull request merged**
