### PR TITLE
Add ifb.edu.br

### PR DESCRIPTION
**Pull request by jonatasos**
Main page: http://www.ifb.edu.br/
List of Undergraduate courses: http://www.ifb.edu.br/index.php/estude-no-ifb/escolha-o-seu-curso/cursos-superiores
Page of Computer Science graduation: http://www.ifb.edu.br/index.php/estude-no-ifb?id=5576
List of technical courses: http://www.ifb.edu.br/estude-no-ifb/escolha-o-seu-curso/tecnico-subsequente

 IT-related long-term courses: Computer Science graduation, Systems for Internet Development Technologist, Systems Development Technician.

### CODE REVIEW

**Comment by philipto** [comment]
@jonatasos Your university website is not accessible from some parts of the world, I will check it via VPN when it will be possible. I am sorry for this delay.

**Comment by jonatasos** [comment]
Thank you for your response. No worry about the delay.

**Comment by philipto** [comment]
@jonatasos Your university network provider is probably the most paranoid in the world: it blocks any attempt to connect to your website from anywhere outside Brazil. I managed to reach the website, and now the pull request is merged. Thank you.

**Comment by jonatasos** [comment]
Thank you. I'm sorry for the issue.

**Pull request merged**
