### PR TITLE
Istituto comprensivo di San Felice Sul Panaro

### PR DESCRIPTION
**Pull request by GitMadKing**

### CODE REVIEW

**Comment by Yatoyashi** [comment]
[swot-master.zip](https://github.com/JetBrains/swot/files/6216974/swot-master.zip)

**Comment by philipto** [comment]
@GitMadKing Please provide us with:
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Also please clarify what kind of school this organization is. Is it a high school? Is it a training center? Is it a union of schools? It is not quite clear from the website. 

Thank you.

**Comment by philipto** [comment]
@GitMadKing You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@GitMadKing I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
