### PR TITLE
Add my school haklaiph to the list

### PR DESCRIPTION
**Pull request by IdoPeer14**

### CODE REVIEW

**Comment by IdoPeer14** [comment]
https://pardes-hanna.ort.org.il/electronics-and-computers-air-force/

**Comment by philipto** [comment]
@IdoPeer14 Please provide us with a proof, which shows that the school recognizes the domain **haklaiph.org** that you are submitting as an official email domain for the students.

You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by IdoPeer14** [comment]
Hi Philip,
A WhatsApp message from my teacher showing the school domain.
Asking us to fill the form so he can create our emails at that domain.
(The message is in Hebrew so I translate it for you)
Thank you, hope that’s ok :)
C1C18741-F4F8-4A22-A42B-5AF6B6D8372A

**Comment by philipto** [comment]
@IdoPeer14 Thank you for the clarification! Pull request merged.

**Comment by IdoPeer14** [comment]
Thank you!

**Pull request merged**
