### PR TITLE
Created aveyron.txt

### PR DESCRIPTION
**Pull request by Mtpc**
http://www.3il-ingenieurs.fr which is a popular french computer science university.
Students living in the Rodez campus have been assigned a ~~`letter.lastname@aveyron.cci.fr`~~ `letter.lastname@formation.aveyron.cci.fr` upon registration.

### CODE REVIEW

**Comment by zweizwei** [comment]
@Mtpc Sorry for the delay - we've been launching rebranding and I hadn't time to check the repo for a while. 

Regrading the request - could you please point out the page, that describes long-term IT-related (>1year) educational courses, that the school provides? thank you!

**Comment by Mtpc** [comment]
[Here you go!](http://www.3il-ingenieurs.fr/index.php/en/programs/the-engineering-program)

**Comment by zweizwei** [comment]
@Mtpc - yes exactly that's Makoto +)
about the page - i'm sorry i don't understand still - http://www.3il-ingenieurs.fr/index.php/en/programs/the-engineering-program this page is not under aveyron.cci.fr - how can i understand that the school provides this program? thanks!

**Comment by Mtpc** [comment]
True, the school isn't under the mail's domain, because the IT department is managed by the campus, which has its own domain.
You can see however that the school falls under its jurisdiction [here](http://www.aveyron.cci.fr/formations/formations-alternance-apprentissage/formation-niveau-i-bac-5/3il/), which has the right "aveyron.cci.fr" domain.
What should I do to prove it if that's not enough informations?

**Comment by zweizwei** [comment]
@Mtpc it's that i've got troubles translating from French so it's hard to say for me if the information on the first website matches the information on the other one. Anyway, i've managed to find that the course is 3-years long on the original website, so it's ok, i'm adding the domain!

**Pull request merged**
