### PR TITLE
Create mackenzista.txt

### PR DESCRIPTION
**Pull request by vitorruiz**

### CODE REVIEW

**Comment by philipto** [comment]
@vitorruiz Could you please follow the rules emphasized at the bottom of [this page](https://github.com/JetBrains/swot) to add your domain to the list as quick as possible? 

In particular, it says:

> We merge pull requests manually, and check the information which you have provided us with prior to merge. Thus, if you wish to make the verification easier for us and therefore much quicker, please mention the following in your comment to the request:
> -the university official website URL, if different from the domain you are submitting
> -an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
> -an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by vitorruiz** [comment]
@philipto 
The university official website URL: http://portal.mackenzie.br/
URL of an IT-related course: http://up.mackenzie.br/graduacao/sao-paulo/sistemas-de-informacao/
Screenshot showing that the university recognizes the domain as an official email domain for the students. This screenshot represents my account in the university moodle.
image

**Comment by philipto** [comment]
@vitorruiz Thank you for the update! In fact, the screenshot shows the email address in a domain @mackenzista.com.br, and the file lib/domains/br/mackenzista.txt represents a domain @mackenzista.br. If the domain which you wish to add is @mackenzista.com.br, please rename the file to lib/domains/br/com/mackenzista.txt. Thank you!

**Comment by philipto** [comment]
@vitorruiz I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen or create a new one if you have an update regarding the issue described above. Thank you for your understanding!

**Pull request closed without merging**
