### PR TITLE
Create citruscollege

### PR DESCRIPTION
**Pull request by sabo-codes**
Citrus College

Email address for students: @student.citruscollege.edu

Email address template: https://www.citruscollege.edu/tecs/studentemail/Documents/AccessStudentEmail.pdf

Physical Address: 1000 W Foothill Blvd, Glendora, CA 91741

Main URL: https://www.citruscollege.edu/Pages/home.aspx

URL for CS degree track: https://catalog.citruscollege.edu/disciplines/computer-science/computer-science-adt/#curriculummaptext

### CODE REVIEW

**Comment by philipto** [comment]
@sabo-codes lib/domains/citruscollege: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by sabo-codes** [comment]
Thank you for the correction. I have updated the file path.

**Comment by philipto** [comment]
@sabo-codes I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host citrus.edu not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by sabo-codes** [comment]
Apologies and thank you!

**Pull request closed without merging**
