### PR TITLE
adding G. Narayanamma Institute of Technology & Science (for Women) institute (gnits.in)

### PR DESCRIPTION
**Pull request by chandanpasunoori**
adding G. Narayanamma Institute of Technology & Science (for Women) institute (gnits.in)

### CODE REVIEW

**Comment by philipto** [comment]
@chandanpasunoori Please provide us with a proof, which shows that the school recognizes the domain gnits.in that you are submitting as an official email domain for the students.

**Comment by chandanpasunoori** [comment]
@philipto letter head from college will work? I will try to get one.

**Comment by philipto** [comment]
@chandanpasunoori It seems to be even too much. Isn't there an email to you or any other instruction from the university which you have been given regarding using this email address while you are a student? I did not find any official information about the domain at the official website.

**Comment by philipto** [comment]
@chandanpasunoori I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
