### PR TITLE
Please create cust.txt

### PR DESCRIPTION
**Pull request by BilalKamran**
University Website www.cust.edu.pk
Offers Bachelor's in Computer Science (4 year degree)

### CODE REVIEW

**Comment by philipto** [comment]
@BilalKamran Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and rename the file in your request accordingly. What is actual email address pattern for your university emails? Is it  username@cust.edu.pk?

**Comment by BilalKamran** [comment]
I have read the repository rules.
Email address pattern is username@cust.pk
Please consider my request.

On Mon, Feb 26, 2018 at 6:53 PM, Philip Torchinsky <notifications@github.com

**Comment by philipto** [comment]
@BilalKamran Thank you. Please rename lib/domains/pk/cust to lib/domains/pk/cust.txt to follow this repository rules.

**Comment by BilalKamran** [comment]
Done.

**Comment by philipto** [comment]
@BilalKamran Pull request merged. Thank you!

**Pull request merged**
