### PR TITLE
Add First Czech grammar school in Karlovy Vary

### PR DESCRIPTION
**Pull request by Zoedingl**

### CODE REVIEW

**Comment by philipto** [comment]
@Zoedingl Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Zoedingl You might miss my previous comment. Please react.

**Comment by Zoedingl** [comment]
Gymkvary.cz
http://gymkvary.cz/node/8
leonard.oeding@student.gymkvary.eu

**Comment by philipto** [comment]
@Zoedingl Thank you for the clarification. Your request contains a file lib/domains/eu/student.txt  which represents the domain student.eu. If you wish to add a domain student.gymkvary.eu, please make a new request with a file `lib/domains/eu/gymkvary/student.txt`

Thank you.

**Pull request closed without merging**
