### PR TITLE
Gymnasium Mariengarden Domain

### PR DESCRIPTION
**Pull request by CrazyJannis44**
Hello,
I'm a student from Germany and I wanna add my school.
It's name is 'Gymnasium Mariengarden'. It's simmilar to a high school
Here's the homepage:
[Gymnasium Mariengarden homepage](https://www.gymnasium-mariengarden.de/)
Here is a link to the google maps location:
[Gymnasium Mariengarden on Google Maps](https://www.google.com/maps/place/Gymnasium+Mariengarden/@51.9064724,6.7768907,771m/data=!3m2!1e3!4b1!4m5!3m4!1s0x47b8638b87fe3a57:0x40fb96293f2388ba!8m2!3d51.9064724!4d6.7790794)

### CODE REVIEW

**Comment by CrazyJannis44** [comment]
there's no proof that that's the domain of the school but i can proof that i've got an acount with this domain:
jannis.honsel@gymburlo.de

**Comment by philipto** [comment]
@CrazyJannis44 I am sorry, we need to see some proof. I did not find any proof in the internet. 

Could you please provide us with a copy of some instruction which you have from your gymnasium administration? It has to tell you that you are able to use an email address @gymburlo.de, and it is official school-provided student address.

Please upload the copy via GitHub web interface, don't send it by email.

**Comment by CrazyJannis44** [comment]
> 
> 
> @CrazyJannis44 I am sorry, we need to see some proof. I did not find any proof in the internet.
> 
> Could you please provide us with a copy of some instruction which you have from your gymnasium administration? [ Könnten Sie uns bitte eine Kopie einer Anweisung geben, die Sie von Ihrer Turnhallenverwaltung erhalten haben?] It has to tell you that you are able to use an email address @gymburlo.de, and it is official school-provided student address. [ Es muss Ihnen mitteilen, dass Sie eine E-Mail-Adresse @ gymburlo.de verwenden können, und es handelt sich um eine offizielle, von der Schule bereitgestellte Schüleradresse.]
> 
> Please upload the copy via GitHub web interface, don't send it by email.

Yes, here but it is in german:
[instruction.pdf](https://github.com/JetBrains/swot/files/5826509/Serienbrief.Schuler_263.pdf)

**Comment by philipto** [comment]
@CrazyJannis44 Thank you! I removed the attachment because it contained some personal data.
Pull request merged. You can start requesting your free license at https://www.jetbrains.com/shop/eform/students in about 1 hour. Please wait this time to allow the changes to propagate through our system. Thank you!

**Comment by CrazyJannis44** [comment]
Much thanks!

**Pull request merged**
