### PR TITLE
Create @intervenant-sornas.fr

### PR DESCRIPTION
**Pull request by Arys02**
mail for teacher to use.

### CODE REVIEW

**Comment by philipto** [comment]
@Arys02 lib/domains/fr/intervenant-sornas: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Arys02 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the teachers. I did not find the proof at the website. A link to an article in a recognized international journal with an author affiliated with this school and the respective email address is enough.

**Comment by Arys02** [comment]
i'll ask the hierarchy and provide you a document from the school as soon as i can, @intervenant-sornas.fr is the domain i use to connect as a teacher on the intranet, @student-sornas.fr is the domain that use student, i have checked @sornas.fr already exist in your list but it's only used by administration. 
regards

**Comment by philipto** [comment]
@Arys02 Excuse me, do you have any update?

**Comment by philipto** [comment]
@Arys02 You might miss my previous comment. Please react.

**Comment by Arys02** [comment]
Hello Philipto,

I dont have update yet, i have contacted my hierarchy, i am waiting for an answer, i'll tell you as soon as i know. 

thanks

**Comment by philipto** [comment]
@Arys02 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please create a new request or reopen this one and comment if you have an update regarding the aforementioned issue. 

You can add both files to the same single request.

Thank you for your understanding!

**Pull request closed without merging**
