### PR TITLE
Added PNU University

### PR DESCRIPTION
**Pull request by vovawed**
Added PNU University (http://comp-sc.if.ua/)

### CODE REVIEW

**Comment by philipto** [comment]
@vovawed Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@vovawed You might miss my previous comment. Please react.

**Comment by vovawed** [comment]
Hello @philipto unfortunately I don't have any proof of it, site doesn't provide any information about it.

**Comment by philipto** [comment]
@vovawed Pull request merged. The website does provide this information: https://comp-sc.pnu.edu.ua/2018/04/10/itcm-2018/ It does not specify the domain as an email domain for the students, but clearly indicates it as a domain which belongs to the university. Thus, I added this domain to the repository.
Thank you!

**Pull request merged**
