### PR TITLE
Added Studygroup.com

### PR DESCRIPTION
**Pull request by kkaushik90**

### CODE REVIEW

**Comment by philipto** [comment]
@kkaushik90 Could you please explain what is Study Group? The website suggests that it is an umbrella name for a coalition of universities, and each of them has its own email domain. Is it true?

**Comment by philipto** [comment]
@kkaushik90 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Comment by kkaushik90** [comment]
@philipto Studygroup provides campus, lecturers, etc., while universities under it provide courses. In my case, I teach in Charles Sturt University, Sydney. My email domain is @studygroup.com.
Please visit https://corporate.studygroup.com/higher-education-pathways/australia/charles-sturt-university for more details.

**Comment by philipto** [comment]
@kkaushik90 Thank you for the clarification! Do I understand right, that students and teachers of StudyGroup do not have other universities emails other than ones in a domain of @studygroup.com?

**Comment by kkaushik90** [comment]
@philipto I can't say for other universities, but at Charles Sturt University, I have only the studygroup email id. The staff at the regional campuses that are owned by the university itself, have @csu.edu.au email id, but then they won't have @studygroup id.

**Comment by philipto** [comment]
@kkaushik90 Thank you for the details. In this case, it makes sense to add StudyGroup to the repository. Pull request merged.

**Comment by kkaushik90** [comment]
Thank you @philipto

**Pull request merged**
