### PR TITLE
Add mail.dlut.edu.cn.

### PR DESCRIPTION
**Pull request by WangHallO**
Add mail.dlut.edu.cn.

### CODE REVIEW

**Comment by philipto** [comment]
@WangHallO Please rename lib/domains/cn/dlut/mail.txt to lib/domains/cn/edu/dlut/mail.txt
Thank you!

**Comment by WangHallO** [comment]
@philipto 
I'm sorry,but I don't know how to rename it.It's my first time to use GitHub.Maybe you can delete this request.Sorry Again.

**Comment by philipto** [comment]
@WangHallO No problem, I will close it without merging. Also, please notice that lib/domains/cn/edu/dlut.txt file already exists, and it means that if you have an email address in any of subdomains of dlut.edu.cn domain, including mail.dlut.edu.cn, you already can request your free license at https://www.jetbrains.com/shop/eform/students. If you have any troubles with that, please email me to community-support@jetbrains.com.

**Comment by WangHallO** [comment]
Thank you very much!
| |
WangHallO
邮箱：wanghailong8023@163.com
|

签名由 网易邮箱大师 定制

On 05/31/2018 21:47, Philip Torchinsky wrote:

@WangHallO No problem, I will close it without merging. Also, please notice that lib/domains/cn/edu/dlut.txt file already exists, and it means that if you have an email address in any of subdomains of dlut.edu.cn domain, including mail.dlut.edu.cn, you already can request your free license at https://www.jetbrains.com/shop/eform/students. If you have any troubles with that, please email me to community-support@jetbrains.com.

**Pull request closed without merging**
