### PR TITLE
Add files of new school

### PR DESCRIPTION
**Pull request by sarbelaezp**

### CODE REVIEW

**Comment by philipto** [comment]
@sarbelaezp Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by sarbelaezp** [comment]
Hi @philipto 

- http://www.asys.edu.co/
- http://www.asys.edu.co/plataformas/website/auxiliar-desarrollo-analisis-software-nuevo/

**Comment by philipto** [comment]
@sarbelaezp I am sorry, but the file which you submitted in your request contains a domain description reading "Corporación Universitaria Remington". This institution has a different website and email domain, not http://www.asys.edu.co/

Could you please clarify what is the reason? Didn't you make a mistake in the description?

**Comment by sarbelaezp** [comment]
> 
> 
> @sarbelaezp I am sorry, but the file which you submitted in your request contains a domain description reading "Corporación Universitaria Remington". This institution has a different website and email domain, not http://www.asys.edu.co/
> 
> Could you please clarify what is the reason? Didn't you make a mistake in the description?

Yes, of course. The reason is that they have an agreement to offer the program in Asys. Let me show you http://asys.edu.co/plataformas/Matricula_Facil/antiguo/remington/index.php.

Thanks.

**Comment by philipto** [comment]
@sarbelaezp I am sorry, it is still not clear to me. What is Asys? If it is a separate university, why not to call the entry "Asys university"? If it is a platform, why we add an email of a platform? This repository is for email domains which belong to universities and colleges only, not a training centers, nor educational platforms.

Please clarify.

**Comment by sarbelaezp** [comment]
> 
> 
> @sarbelaezp I am sorry, it is still not clear to me. What is Asys? If it is a separate university, why not to call the entry "Asys university"? If it is a platform, why we add an email of a platform? This repository is for email domains which belong to universities and colleges only, not training centers, nor educational platforms.
> 
> Please clarify.

Of course @philipto, Asys offers technical and technological programs, but sometime ago they started an agreement to offer university programs through Remington and I started the educational process since technical program, that is the reason of the domain

**Comment by philipto** [comment]
@sarbelaezp Thank you for the clarification. Pull request merged.

**Comment by sarbelaezp** [comment]
> 
> 
> @sarbelaezp Thank you for the clarification. Pull request merged.

Thanks a lot @philipto. Have a good day.

**Pull request merged**
