### PR TITLE
Rename umontpellier.txt to etu-umontpellier.txt

### PR DESCRIPTION
**Pull request by Isador34**
Because name change this year

### CODE REVIEW

**Comment by philipto** [comment]
@Isador34 Could you please provide some explanation why it is necessary, and some proof that the school uses new email domain for the students?

**Comment by Isador34** [comment]
No my bad, I tried to write etu-umontpellier instead of etu.umontpellier.fr

2017-04-25 17:10 GMT+02:00 Philip Torchinsky <notifications@github.com>:

**Comment by philipto** [comment]
@Isador34 Do I understand right that I can close this request without merging because you do not need to add a domain etu-umontpellier.fr anymore?

**Comment by Isador34** [comment]
Yeah exactly

Le 26 avr. 2017 07:19, "Philip Torchinsky" <notifications@github.com> a
écrit :

**Comment by philipto** [comment]
@Isador34 I am closing the request without merging as you have asked. Thank you!

**Pull request closed without merging**
