### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AlbertoSS29**
https://lasalle.mx/
https://lasalle.mx/oferta-educativa/facultades/facultad-de-ingenieria/licenciatura-en-ingenieria-cibernetica-y-sistemas-computacionales/
www.lasalle.mx/correolasallistas
https://hoy.lasalle.mx/como-activar-correo-lasallistas/#:~:text=1%2D%20Env%C3%ADa%20un%20correo%20a,La%20Salle%20tiene%20para%20ti.

### CODE REVIEW

**Comment by philipto** [comment]
@AlbertoSS29 Thank you for your request.
The page that you are referring to lists a domain @lasallista**s**.org.mx as belonging to the school.
Your request is to add the domain @lasallista.org.mx (without "s" at the end of word "lasallista").
Please explain the discrepancy. Thank you.

**Comment by philipto** [comment]
@AlbertoSS29 You might miss my previous comment. Please react.

**Comment by AlbertoSS29** [comment]
Hello Philip,
I apologize for my mistake. I forgot to put the letter S you mention.
I have already confirmed that lasallistas domain does exist in the list of
educational emails domain

Thank you for the time you take on this issue.

**Comment by philipto** [comment]
@AlbertoSS29 You are right. Thus, I close this request without merging. Thank you!

**Pull request closed without merging**
