### PR TITLE
Create itesa.txt

### PR DESCRIPTION
**Pull request by Diego5160IsSa**
Adding ITESA institute

### CODE REVIEW

**Comment by philipto** [comment]
@Diego5160IsSa First stage of verification passed, official domain is [itesa.edu.mx](https://itesa.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Diego5160IsSa Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by Diego5160IsSa** [comment]
Thx, and one question, how long do I have to wait to renew my student
license, with the domain that I added?

**Comment by Diego5160IsSa** [comment]
Sending photo of my process
[image: photo_2023-02-16_13-39-48.jpg]

**Pull request merged**
