### PR TITLE
Added Carlsbad High School

### PR DESCRIPTION
**Pull request by edwardburns1**

### CODE REVIEW

**Comment by philipto** [comment]
@edwardburns1 I am sorry, the website of carlsbadusd.net is not responding, and I can not find any trustworthy info about the school in the Internet. 
Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school 
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@edwardburns1 Pull request merged. Thank you!

**Comment by philipto** [comment]
@edwardburns1 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@edwardburns1 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Comment by edwardburns1** [comment]
@philipto I am very sorry for not responding to your comment. I'm still getting familiar with github. Yesterday I sent a new pull request with the URL of the official Website and the URL of the page which offers the long term IT related course. Because this is a district email they are different websites. I also added .group as the last line.

**Pull request closed without merging**
