### PR TITLE
Create my txt

### PR DESCRIPTION
**Pull request by Mikomik141**

### CODE REVIEW

**Comment by MarkusTieger** [comment]
You should read the "How to add a domain to this repository" section again. You shouldn't include the zip file and the txt file is in the wrong folder

**Comment by Mikomik141** [comment]
> You should read the "How to add a domain to this repository" section again. You shouldn't include the zip file and the txt file is in the wrong folder

for the first commit that was my first try . Did you see the second commit ? (sorry english is not my first language)

**Comment by MarkusTieger** [comment]
> > You should read the "How to add a domain to this repository" section again. You shouldn't include the zip file and the txt file is in the wrong folder
> 
> for the first commit that was my first try . Did you see the second commit ? (sorry english is not my first language)

Your second commit, did not remove the zip, which you added in the first commit. The txt file from the second commit still isn't in the correct directory.

**Comment by philipto** [comment]
@Mikomik141 file I am sorry, I have to close the request without merging, because you made a mistake in a request and did not specify any filepath. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and make a new correct request. Thank you for your understanding!

**Comment by philipto** [comment]
@Mikomik141 There are several files in the request, along with file.zip. It must not be there. Please remove file.zip and make pull request again.  I have to close this request without merging. Thank you for your understanding.

**Pull request closed without merging**
