### PR TITLE
Add new ECV Digital mail

### PR DESCRIPTION
**Pull request by antoinechassagne**
Add ECV Digital (https://www.ecvdigital.fr/) new email.

### CODE REVIEW

**Comment by philipto** [comment]
@antoinechassagne Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@antoinechassagne I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the above-mentioned issue. Thank you for the understanding!

**Comment by ADEDUC** [comment]
Hi there,

I'm following up the thread with our student.
Could you please comme back to me (by email only ) to know how you want to proceed ?
I'll provide you all the documents you need to recognizes ours domains that we are submitting as an official email domain for student.

best regard

YQ

**Comment by philipto** [comment]
@ADEDUC I am sorry, but you did not provide me with your email neither in the comment, nor in the user profile on GitHub. If you sent this comment from your email application, GutHub hides it for privacy protection and does not display here. Please send an email to support@jetbrains.com with subject: SWOT repository question, and it will be forwarded to appropriate team.

To proceed, we need to have a proof which clearly confirms that mail-ecv.fr email domain is used by students and teachers of the same organization as the one which owns https://www.ecvdigital.fr/ website. It could be a page on the website, but I did not find a page there with emails related to the organization ending with @mail-ecv.fr.

Thank you!

**Comment by philipto** [comment]
@antoinechassagne @ADEDUC You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@antoinechassagne I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
