### PR TITLE
 Creating entry for ITIS Castelli Brescia

### PR DESCRIPTION
**Pull request by alessandro-bugatti**
We recently updated our official email addresses using onmicrosoft.com subdomain.

### CODE REVIEW

**Comment by philipto** [comment]
@alessandro-bugatti Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by alessandro-bugatti** [comment]
This is a screenshot of our administration panel where our admin creates and manages our students. Is it Ok?
itiscastelli

**Comment by philipto** [comment]
@alessandro-bugatti I am sorry, no, it is not a proof, because it does not show that the school recognizes the domain which you are submitting as an official email domain for the students. 

The best proof is mentioning of this domain at the official website, or a copy of instruction which the school gives/sends to the students saying that they are assigned with the address from this domain. 

Other proofs are also OK, if they clearly shows that the university assigns these addresses for the students.

**Comment by philipto** [comment]
@alessandro-bugatti You might miss my previous comment. Please react.

**Comment by alessandro-bugatti** [comment]
Sorry, I got it, I immediately asked to my school IT administrator to add a page in our website to show the proof that we  use @itiscastelli.onmicrosoft.com for our students. He said that he must ask to the principal before to do that, so I'm still waiting for his answer. 
I don't know how long can it takes, if you prefer to close this pull request in the meantime, I hope to have this new page in a couple of days, but I really don't know.

**Comment by philipto** [comment]
@alessandro-bugatti Thank you for the update. No problem, it can wait. Please comment as soon as you have an update. Thank you!

**Comment by alessandro-bugatti** [comment]
@philipto Ok, I'll keep you updated, thanks.

**Comment by philipto** [comment]
@alessandro-bugatti Do you have any update on the matter, please?

**Comment by alessandro-bugatti** [comment]
> 
> 
> @alessandro-bugatti Do you have any update on the matter, please?

Dear @philipto,
this morning I asked to my principal about the official documentation and she said me they prepared it, but they need a physical address or an email address to send this document (Italian burocracy). If you prefer you can send these information to our ICT administrator at this address, infoservizi@itiscastelli.it. 
Let me know if it is OK, thanks.

**Comment by philipto** [comment]
@alessandro-bugatti Yes, absolutely. Please send the copy of the document by email to community-support@jetbrains.com with subject: _ATTN: Philip Torchinsky_

**Comment by philipto** [comment]
@alessandro-bugatti Thank you for the clarification. Pull request merged.

**Comment by alessandro-bugatti** [comment]
@philipto Thank you

**Pull request merged**
