### PR TITLE
Added rogaland fylkeskommune (rogfk.no)

### PR DESCRIPTION
**Pull request by xenocidewiki**

### CODE REVIEW

**Comment by philipto** [comment]
@xenocidewiki Could you please:
1) rename lib/domains/no/rogfk/rogfk.txt to lib/domains/no/rogfk.txt if the domain name to add is acually rogfk.no. Do nothing if the domain name is rogfk.rogfk.no.
2) check request #2089 and answer the same question regarding the specific domain name dedicated to the school students.
Thank you!

**Comment by xenocidewiki** [comment]
@philipto sent a new pull request, my bad. Also yes the student email domain would be @elev.rogfk.no

**Comment by philipto** [comment]
@xenocidewiki Thank you! Sorry for a bit of extra work, but in case the student domain is @elev.rogfk.no, the file path has to be lib/domains/no/rogfk/elev.txt. Please rename. Thank you!

**Comment by xenocidewiki** [comment]
@philipto ahaha np, fixed :)

**Comment by philipto** [comment]
@xenocidewiki Thank you! Pull request merged.

**Pull request merged**
