### PR TITLE
Create adcet

### PR DESCRIPTION
**Pull request by vivek8097**
Please add my college in your list.

### CODE REVIEW

**Comment by philipto** [comment]
@vivek8097 Please rename lib/domains/edu/adcet to lib/domains/edu/adcet.txt to follow this repository rules. Thank you!

**Comment by philipto** [comment]
@vivek8097 Also, please indicate what is the official web site of the school, because it cannot be reached at adcet.edu.

**Comment by vivek8097** [comment]
to where i add my college website.??

On Mon, Apr 17, 2017 at 11:55 PM, Philip Torchinsky <notifications@github.com<mailto:notifications@github.com>> wrote:

@vivek8097<https://github.com/vivek8097> Also, please indicate what is the official web site of the school, because it cannot be reached at adcet.edu<http://adcet.edu>.

**Comment by philipto** [comment]
@vivek8097 You can answer this message by email (if you receive notification emails from GitHub) or in the comment field at the request page (https://github.com/JetBrains/swot/pull/2938). I found the college with the name which you have indicated, and the website does not have emails @adcet.edu at the contact page: http://www.adcet.in/ADCET/ContactUS.php. What is a domain part of your email - adcet.edu or adcet.in? If the latter, please rename the file path in your request from lib/domains/edu/adcet to lib/domains/in/adcet.txt. In any case, the file must have an extension .txt. Thank you!

**Comment by philipto** [comment]
@vivek8097 I am closing this request because it duplicates #2958.

**Comment by vivek8097** [comment]
Dear sir,
My previous pull request to add adcet.txt in lib/domain/edu  is wrong because my college email id end with adcet.in<http://adcet.in> so i need to add my adcet.txt inside lib/domain/in folder.Please sir remove adcet.txt from lib/domain/edu and approve my pull request for lib/domain/in.
Regards,
Vivek singh

On 19-Apr-2017 11:03 pm, "Philip Torchinsky" <notifications@github.com<mailto:notifications@github.com>> wrote:

@vivek8097<https://github.com/vivek8097> I am closing this request because it duplicates #2958<https://github.com/JetBrains/swot/pull/2958>.

**Pull request closed without merging**
