### PR TITLE
Add new (2018) Open University UK academic email accounts

### PR DESCRIPTION
**Pull request by assimilatedgiraffe**

### CODE REVIEW

**Comment by philipto** [comment]
@assimilatedgiraffe JetBrains grants an educational license to online university students if the university offers long-term courses. While we know that Open University provides such courses, could you please let us know who at the university is eligible to get an email address in the domain of ou.ac.uk? 

We do not grant educational license on the base of certain email address possession to students who study few weeks or months, we recommend them other type of licenses, including trial versions of JetBrains tools. Please clarify.

**Comment by philipto** [comment]
@assimilatedgiraffe You might miss my previous comment. Please reply.

**Comment by assimilatedgiraffe** [comment]
@philipto  Thanks for your patience, I had to check with OU.

While the majority of Computing and IT courses are long term, there are two 10 week courses (on this page under modules [](http://www.open.ac.uk/courses/find/computing-and-it))

A student registered on any of these modules is eligible to get an email address in the domain of ou.ac.uk.

**Comment by philipto** [comment]
@assimilatedgiraffe Thank you for the clarification! I am afraid this policy contradicts with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot). 

Thus, please use an option "Official document" at https://www.jetbrains.com/shop/eform/students to apply for the free subscription for JetBrains tools, or email community-support@jetbrains.com. We definitely have to find a way for stuednts on long-term courses to get our licenses. 

If you enrolled to a short-term course, you can use extended free trial, feel free to email sales@jetbrains.com to extend your trial for a time beyond standard 30 days.

As for this request, I have to close the request without merging. Thank you for the understanding!

**Pull request closed without merging**
