### PR TITLE
Add Lornsenschule Schleswig, Germany

### PR DESCRIPTION
**Pull request by MTRNord**
My School has one problem: It has micrsoft emails. So I hope it is still possible to add it to the list. If not please give me a way to be able to have valid emails. (Also note: It is a German school so no edu emails for us)

### CODE REVIEW

**Comment by MTRNord** [comment]
PS: Our main Hompage is on lornsenschule.de and not on zsschleswig.onmicrodoft.com (only our emails are there)

**Comment by philipto** [comment]
@MTRNord It's no problem to host mail with Microsoft, the problem is that none of your school contacts (http://hp.lornsenschule.de/index.php/infos/kontaktdaten) are in the domain zsschleswig.onmicrodoft.com. Could you please provide us with a link to some document or webpage saying that zsschleswig.onmicrodoft.com is related to lornsenschule.de indeed? Thank you!

**Comment by MTRNord** [comment]
I will search/get one to provide you the needed proof

**Comment by MTRNord** [comment]
Would an Document (which is propably wrotten in German) be ok? (Would also be propably some sort of paper from my principal) @philipto

**Comment by philipto** [comment]
@MTRNord Yes, the document will be OK.

**Comment by MTRNord** [comment]
So the response from my school is: we should use lornsenschule.sh.lo-net2.de emails here (I will add an commit later) and I will get an document which proves it after my holidays (they and in january 2017)

**Comment by MTRNord** [comment]
Email domain is corrected now. I will send the Document as soon as I get it

**Comment by MTRNord** [comment]
So here is the Document. On it is written that it proves my personal school address but everyone at our school uses these email (every Student). I hope that this Document is enough.

ls_mail_scan

**Comment by philipto** [comment]
@MTRNord Pull request merged. Thank you!

**Comment by MTRNord** [comment]
Thanks for the merge :D

**Pull request merged**
