### PR TITLE
Add Laksamana College of Business

### PR DESCRIPTION
**Pull request by shazoom**

### CODE REVIEW

**Comment by shazoom** [comment]
The domain for the college is lcb.edu.bn.

**Comment by philipto** [comment]
@shazoom First stage of verification passed, official domain is [lcb.edu.bn](https://lcb.edu.bn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.lcb.edu.bn/new-student-registration

**Comment by shazoom** [comment]
I guess this could be automated on your end but the mail domain used, confusingly, is laksamanacollege.edu.bn

**Comment by philipto** [comment]
@shazoom Yes, certainly:
> the mail domain used, confusingly, is laksamanacollege.edu.bn

It's exactly what is proven at https://www.lcb.edu.bn/new-student-registration.
Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
