### PR TITLE
kenlearning.txt

### PR DESCRIPTION
**Pull request by papu12**
We are from kenlearning.com , we are a charitable education institution , delivering IT education to deprived section of people in free of cost.
http://kenlearning.com/. Our team is 
http://kenlearning.com/#team
JIdea license would help us a lot in teaching.

### CODE REVIEW

**Comment by philipto** [comment]
@papu12 I am sorry: regrettably, we do not grant free license to online universities. As far as I see, your educational institution is an online training center. We value the important role which you play in education, but unfortunately we can not add your email domain to this repository. I close this request without merging. Thank you for your understanding.

**Comment by philipto** [comment]
@papu12 Thank you for the details. It was not clear to me that you offer just offline courses. Could you please send me a URL or another proof to check that you actually offer courses which you conduct in a classroom, and the courses are long-term (> 1 year)? If they are short-term courses, you are eligible for another type of free JetBrains licenses, which you can request by email to classroom@jetbrains.com. Thank you for your work!

**Comment by papu12** [comment]
Hi Philipto,
Thanks for your kind reply. I am training students only in classroom , i have 12 students this year , all are free of cost. If you see the course details  , 
http://kenlearning.com/java.html 
http://kenlearning.com/python.html...
All are classroom based training. Since ,the students are mostly from deprived sections , they come here mostly with zero knowledge and making them capable of doing java/ python etc takes more than 2 year efforts.
In case you are ok , i can show my classroom & students in skype video.
Thanks & best Regards
papu

**Comment by papu12** [comment]
Hi Phipto,
Thanks much for your precious time so far. Would really appreciate if you could please let me know your final decision. Since ,currently since the training are all free and meant for deprived section, i am not able to pay the license cost. But my students are good in document writing / logo design / video preparation,office jobs,website maintenance, customer support etc. By giving you some services , can we pay your license cost? Does that work for you. Thanks much for your kind cooperation so far.Best Regards Papu

**Pull request closed without merging**
