### PR TITLE
add domain akperluwuk, untika and unismuhluwuk

### PR DESCRIPTION
**Pull request by virbo**

### CODE REVIEW

**Comment by philipto** [comment]
@virbo Could you please provide us with URLs of pages on the official websites where each of these universities offers an IT-related long-term (>1 year) course. Thank you.

**Comment by virbo** [comment]
> @virbo Could you please provide us with URLs of pages on the official websites where each of these universities offers an IT-related long-term (>1 year) course. Thank you.

1. Akper Luwuk = http://akper-luwuk.ac.id
2. Universitas Muhammadiyah Luwuk = http://unismuhluwuk.ac.id
3. Universitas Tompotika Luwuk = http://untika.ac.id

**Comment by philipto** [comment]
@virbo I am sorry, I might not be clear enough. I don't need homepages, I need pages of the websites, where the respective universities offer **IT-related long-term (>1 year) courses**. 

For example, Akper Luwuk is LUWUK NURSING ACADEMY, according to Google translate. Nursing academy is not usually a school where students need any IDE for software developers, because they are not software developers at all.

This is why I need to ensure that each of the universities mentioned in your request have courses somehow related to software development. It can be a course in physics, mathematics, bioinformatics, but not childcare, nor nursing in general, unless the course curriculum at the website explicitly says that software development is a part of the course.

**Comment by philipto** [comment]
@virbo You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@virbo I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
