### PR TITLE
Create swot/lib/domains/uk/rcs.txt

### PR DESCRIPTION
**Pull request by delboh**
rcs.ac.uk

https://www.rcs.ac.uk/postgraduate/doctor-of-performing-arts/

https://outlook.com/rcs.ac.uk

### CODE REVIEW

**Comment by philipto** [comment]
@delboh First stage of verification passed, official domain is [rcs.ac.uk](https://rcs.ac.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@delboh 
> https://www.rcs.ac.uk/postgraduate/doctor-of-performing-arts/

**Would you please describe how do you plan to use software development tools in the above mentioned course?**

The issue is that providing a free access to software development tools to students who don't need to develop software within their education is (1) against the educational subscription licensing terms and (2) provoking sharing the licenses with third parties who are not students, but need the tools for their professional work.

**Comment by delboh** [comment]
Hi Philip,

As part of my research I been have exploring algorithmic composition methods with the abjad and mutwo python frameworks using the PyCharm community. I am hoping to expand and develop this part of my studies by looking at the feasibility of including these methods in an online app and Django does not seem to be fully supported in the community edition.

iain

On 20 Nov 2023, at 12:43, Philip Torchinsky ***@***.***> wrote:

﻿

@delboh<https://github.com/delboh>

https://www.rcs.ac.uk/postgraduate/doctor-of-performing-arts/

Would you please describe how do you plan to use software development tools in the above mentioned course?

The issue is that providing a free access to software development tools to students who don't need to develop software within their education is (1) against the educational subscription licensing terms and (2) provoking sharing the licenses with third parties who are not students, but need the tools for their professional work.

**Comment by philipto** [comment]
@delboh Thank you for your clarification and patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
