### PR TITLE
Create bonhoeffer.txt

### PR DESCRIPTION
**Pull request by StephanMeijer**
[Bonhoeffercollege Castricum](http://www.bonhoeffer.nl/)

`<firstname>.<lastname>@bonhoeffer.nl`

### CODE REVIEW

**Comment by philipto** [comment]
@StephanMeijer Could you please rename `lib/domains/nl/bonhoeffer` to `lib/domains/nl/bonhoeffer.txt` to reflect this repository rules? Thank you!

**Comment by philipto** [comment]
@StephanMeijer You might miss the previous message to you. Could you please update the file as we asked you in the comment above?

**Comment by StephanMeijer** [comment]
Yes, I will, I am sorry. I did not see your message.

**Comment by StephanMeijer** [comment]
See #2120

**Pull request closed without merging**
