### PR TITLE
Create epsic.txt

### PR DESCRIPTION
**Pull request by rafi16d**
We are a school training students in the fields of IT.

http://www.epsic.ch/

### CODE REVIEW

**Comment by rafi16d** [comment]
up

**Comment by zweizwei** [comment]
I'm very sorry for the delay. Could you please provide some proof the committed domain belongs to the school? i could only find official epsic.ch in regard to school. Thanks!

**Comment by rafi16d** [comment]
Hi, thank you for the response
The domain for the school is "epsic.ch" but the student e-mail is "exemple@educanet2.epsic.ch"
If you want a proof, you can mail me : gabrielr@epsic.educanet2.ch
Best regard

**Comment by rafi16d** [comment]
Up

**Comment by rafi16d** [comment]
Up

**Comment by zweizwei** [comment]
Sorry for the delay, adding the domain. In case of urgent requests please write to classroom@jetbrains.com

**Pull request merged**
