### PR TITLE
Create eld.txt

### PR DESCRIPTION
**Pull request by hazzy76**

### CODE REVIEW

**Comment by philipto** [comment]
@hazzy76 First stage of verification passed, official domain is [eld.edu.mx](https://eld.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@hazzy76 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by hazzy76** [comment]
https://www.eld.edu.mx/diplomado-en-innovacion-y-tecnologia-juridicas/

**Comment by philipto** [comment]
@hazzy76 Thank you for the details! As far as I see this course has 78 hours of studying, of which some are not related to programming. Even if it was a software development course, it takes 4 hours per week, and 78 / 4 = 19.5 weeks, which cannot be considered long-term. We define long-term course as the course that takes a year or longer.

Therefore, the domain eld.edu.mx is not eligible for this repository. If you need a JetBrains tool for your study, please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

You also can use Community editions of PyCharm and IntelliJ IDEA (they are free for everybody), free trial versions of any JetBrains tools for shorter tasks (up to 30 days), and [EAP versions](https://www.jetbrains.com/resources/eap/).

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
