### PR TITLE
Create SGS Berkeley Green UTC

### PR DESCRIPTION
**Pull request by AlexAndHisScripts**

### CODE REVIEW

**Comment by philipto** [comment]
@AlexAndHisScripts lib/domains/uk/org/SGS: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by AlexAndHisScripts** [comment]
> 
> 
> @AlexAndHisScripts lib/domains/uk/org/SGS: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.

So I just say the name, no email? How will you know what to whitelist?

**Comment by philipto** [comment]
@AlexAndHisScripts Do I understand your request correctly, and you wish to add @berkeleygreenutc.org.uk domain to the list of trusted domains? If yes, the file pathname has to be lib/domains/uk/org/berkeleygreenutc.txt.

Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@AlexAndHisScripts lib/domains/uk/org/SGS: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@AlexAndHisScripts lib/domains/uk/org/SGS: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@AlexAndHisScripts lib/domains/uk/org/SGS: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@AlexAndHisScripts lib/domains/uk/org/SGS: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@AlexAndHisScripts You might miss my previous comments. Please react.

**Comment by philipto** [comment]
@AlexAndHisScripts lib/domains/uk/org/SGS: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@AlexAndHisScripts I corrected the entry for you. Pull request merged. Thank you!

FTR: domain ownership proof is at https://academytrust.sgscol.ac.uk/sgs-berkeley-green-utc/contact

**Comment by AlexAndHisScripts** [comment]
Really sorry for not seeing your responses and thanks for doing it. I didn't get notifications for it and just checked.

**Pull request merged**
