### PR TITLE
Add Natural Learning Academy (nlaschool.com)

### PR DESCRIPTION
**Pull request by jaydotsee**

### CODE REVIEW

**Comment by philipto** [comment]
@jaydotsee Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@jaydotsee You might miss my previous comment. Please react.

**Comment by jaydotsee** [comment]
Hi Philip,

We've decided to evaluate the Komodo IDE for now but will reach out again should we decide to give the Jetbrains tools another look.

Regards

Sent from my mobile device, please excuse typos and brevity. <http://www.9folders.com/>
________________________________

**Comment by philipto** [comment]
@jaydotsee Thank you for your reply. Feel free to get back at any time. You can also send an email to community-support@jetbrains.cm if you have any question with regard to technical details or licensing. Have a good week, stay safe!

I am closing the request for now.

**Pull request closed without merging**
