### PR TITLE
Create alqasimia.txt

### PR DESCRIPTION
**Pull request by engmabdulwahab**
Add Al Qasimia Universiy : https://www.alqasimia.ac.ae/en/

### CODE REVIEW

**Comment by philipto** [comment]
@engmabdulwahab First stage of verification passed, official domain is [alqasimia.ac.ae](https://alqasimia.ac.ae) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by engmabdulwahab** [comment]
Thanks. Is there an ETA?

**Comment by nataershova** [comment]
Hello @engmabdulwahab, could you please send us the URL of a page on the official website where the school offers an IT-related long-term (>1 year) course?

thank you!

**Comment by engmabdulwahab** [comment]
> Hello @engmabdulwahab, could you please send us the URL of a page on the official website where the school offers an IT-related long-term (>1 year) course?
> 
> 
> 
> thank you!

There is not IT course provided by my college, unfortunately.

I am using/will use PHP Storm to create an easy solutions for me and my colleagues to facilitate our learning of other subjects.

Thanks and I understand if it didn't get approved. But I am eager to use your service for learning.

**Pull request closed without merging**
