### PR TITLE
Add the "Institut la Segarra"

### PR DESCRIPTION
**Pull request by developingjan**
Institut La Segarra => @institutlasegarra.cat
Address: Av. Francesc Macià, 11, 25200 Cervera, Lleida

### CODE REVIEW

**Comment by developingjan** [comment]
jquer1@institutlasegarra.cat, parent domain: http://www.ieslasegarra.com/

**Comment by philipto** [comment]
@developingjan Thank you! I am sorry, your clarification did not make things clearer for me. Do you have any IT-related course, described at your website? Could you please give us a direct link to a page on the official website where an IT-related long-term (>1 year) course is offered to the students. I mean, a page with a course title, desciption and an indication of how long it takes.

**Comment by developingjan** [comment]
Okay, here is the link to the courses that they have: [http://www.ieslasegarra.com/estudis.php](http://www.ieslasegarra.com/estudis.php) & [http://www.ieslasegarra.com/novetats/cicles2017/cicles01.htm](http://www.ieslasegarra.com/novetats/cicles2017/cicles01.htm).
Is in catalan, you can translate with google, for example. Thanks.

**Comment by philipto** [comment]
@developingjan Thank you for the clarification. Pull request is now merged.

**Pull request merged**
