### PR TITLE
Create univmetiers

### PR DESCRIPTION
**Pull request by GoGaetan**
My School email is tselenkeufranck@univmetiers.ci

### CODE REVIEW

**Comment by philipto** [comment]
@GoGaetan Thank you for the details. Please:
1) rename lib/domains/ci/univmetiers to lib/domains/ci/univmetiers.txt
2) provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

Regrettably, many pages at your website www.pigierci.com are under construction, and I can not check if the domain univmetiers.ci belongs to your unviersity. Please clarify. Thank you.

**Comment by GoGaetan** [comment]
Dear Philip,
Thank you for your answer.

Kindly find as attached the email sent to me as acknowledge of the creation
of my school email by the support in charge of this.

Thanks and best rds



-- 
-- 
In Cote d'Ivoire (00225 77 55 54 95)
-- 
Franck Lionnel TSELENKEU T.

IT Eng.

(+237) 74 58 39 73
(+237) 99 88 51 87


2018-04-05 14:33 GMT+00:00 Philip Torchinsky <notifications@github.com>:

**Comment by GoGaetan** [comment]
Dear Philip,

I am sharing with you some snap as requested proof of the school domain name and email.

I'am writing from School Email, GoGaetan is my pseudo on Github.

Thank in advance for the great job and support.


best rds.


________________________________
De : Philip Torchinsky <notifications@github.com>
Envoyé : jeudi 5 avril 2018 14:33:52
À : JetBrains/swot
Cc : TSELENKEU TCHATCHEBEU FRANCK LIONNEL; Mention
Objet : Re: [JetBrains/swot] Create univmetiers (#4295)


@GoGaetan<https://github.com/GoGaetan> Thank you for the details. Please:

  1.  rename lib/domains/ci/univmetiers to lib/domains/ci/univmetiers.txt
  2.  provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

Regrettably, many pages at your website www.pigierci.com<http://www.pigierci.com> are under construction, and I can not check if the domain univmetiers.ci belongs to your unviersity. Please clarify. Thank you.

**Comment by philipto** [comment]
@GoGaetan Thank you for the message. Regrettably, the attachments were not enclosed, or missed in transit. I do not see any snapshots, screenshots, or any other documents attached. Please send them via GitHub interface or to support@jetbrains.com by email with subject "To: Philip Torchinsky Re: univmetiers.ci". Thank you.

**Comment by philipto** [comment]
@GoGaetan Thank you very much for the additional details you have provided by email! I am glad to merge your pull request. You and your students can request their free licenses at https://www.jetbrains.com/shop/eform/students/ from now on. Please let the updates to propagate through our system, and start requesting the licenses in half an hour. 

Feel free to email support@jetbrains.com if something went not as expected.

**Pull request merged**
