### PR TITLE
Add AUT NZ

### PR DESCRIPTION
**Pull request by razorRun**

### CODE REVIEW

**Comment by mamazhanov** [comment]
Add OshSU

**Comment by philipto** [comment]
@razorRun Please provide us with a proof, which shows that the school recognizes the domain autuni.onmicrosoft.com that you are submitting as an official email domain for the students.

@mamazhanov Please create a separate pull request. If you don't know how to do it, please send an email to community-support@jetbrains.com.

**Comment by philipto** [comment]
@razorRun You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@razorRun I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
