### PR TITLE
Added dgme.gov.bd

### PR DESCRIPTION
**Pull request by raihansikder**
DGME (Directorate Genral of Medical Education) is the organization that designs curriculumns and regulates activities of all the Medical and Dental Colleges in Bangladesh.

### CODE REVIEW

**Comment by philipto** [comment]
@raihansikder The first verification stage is complete: the official domain for  **Directorate General of Medical Education (Bangladesh)** is [dgme.teletalk.com.bd](https://dgme.teletalk.com.bd), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: http://dgme.teletalk.com.bd/bds/docs/circular_bds_nongov.pdf

**Comment by raihansikder** [comment]
Many thanks Philip.  Much appreciated.
You are correct, all these domains are government provisioned domains.

BR
Raihan

**Comment by philipto** [comment]
@raihansikder The first verification stage is complete: the official domain for  **Directorate General of Medical Education (Bangladesh)** is [dgme.teletalk.com.bd](https://dgme.teletalk.com.bd), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: http://dgme.teletalk.com.bd/bds/docs/circular_bds_nongov.pdf

**Comment by philipto** [comment]
@raihansikder Thank you for your request. The domain does not look eligible for this repository because:

1. This domain seems to represent an umbrella institution, not a specific single university or a college.
2. The organization is not educational, it's government organization. It does not teach students, in other words.
3. The organizations seems to have nothing in common with computer science fields of study. 

If you are a student there, and need to use JetBrains tools, please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

If I misunderstood the idea of adding this domain to the trusted list, please send an email to community-support@jetbrains.com and explain what the organization does, and why it needs educational subscription for JetBrains tools.

I have to close the request without merging.
Thank you for your understanding!

**Pull request closed without merging**
