### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MerakiNetworkGit**
add the file to approve school.

To ensure you this school exists this is the website of it:
https://www.itiscannizzaro.edu.it/

### CODE REVIEW

**Comment by philipto** [comment]
@MerakiNetworkGit First stage of verification passed, official domain is [itiscannizzaro.edu.it](https://itiscannizzaro.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by MerakiNetworkGit** [comment]
So I just need to wait, right?


Il giorno lun 29 mag 2023 alle ore 05:33 Philip Torchinsky <
***@***.***> ha scritto:

**Comment by georgekarlr** [comment]
Offical Domain sccpag.edu.ph                   School Website:    https://www.sccpag.edu.ph/

**Comment by MerakiNetworkGit** [comment]
??

Il giorno mer 31 mag 2023 alle ore 02:58 georgekarlr <
***@***.***> ha scritto:

**Comment by georgekarlr** [comment]
georgekarl.real@sccpag.edu.ph

**Pull request merged**
