### PR TITLE
Update dbg.txt for Freie-Georgenschule Reutlingen

### PR DESCRIPTION
**Pull request by juknoFGS**
Freie Georgenschule Reutlingen

### CODE REVIEW

**Comment by philipto** [comment]
@juknoFGS Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by juknoFGS** [comment]
Dear Mr. Torchinsky

thank You for Your fast response.

I will try to answer Your questions:

  * the school official website URL

        www. freie-georgenschule.de

  * an URL of a page on the official website where the school offers an
    IT-related long-term (>1 year) course

        unfortunately  our web page does not offer a separate item of
the IT related courses, but let me explain.

        The German Goverment supports the new campain for
"Digitalization" therfore  our school offers now further steps to
improve the IT knowledge:

        - Basic knowlegment - Introduction to work with Computers (Libre
Office, Excel etc. ) Basics of Coputer Language - we decide to use "GO-
Golang"

           which will occure in class 9 and 10

        -  in class 11 and 12 the knowledge of the Programming skills
will be expanded and improved. Here we introduce HTML and Web based
skills - with "Go" we can handle this as well. In addition we provide a
voluntary course in "GO" with the aim to improve / expand our own made
Web based "canteen order System".

        Our students will leave the school with the educational level
"Abitur" which qualifies the studens to go to an University.

        My role here  - I am one of the Teachers for IT and I am
responible for Teaching "Go" ...

  * a proof, which shows that the school recognizes the domain you are
    submitting as an official email domain for the students.

        Only the employees (Teacher, Administration) will get an email
address of the school in Form of <surmame>@freie-georgenschule.de or
<firstname>.<surname>@freie-georgenschule.de

    Please have a look at the web side.


I hope that I can answer Your questions - please feel free to contact me
for further questions.

With best regards

Juergen Knop

**Comment by philipto** [comment]
@juknoFGS Thank you very much for the clarification! Your school is eligible for being added to this repository, it's no doubt. One issue confuses me a bit: your request contains a file lib/domains/de/schule/bw/rt/dbg.txt that corresponds to a domain name "dbg.rt.bw.schule.de" which is a domain of Dietrich-Bonhoeffer-Gymnasiums Metzingen, and you say that "Only the employees (Teacher, Administration) will get an email address of the school in Form of <surmame>@freie-georgenschule.de or <firstname>.<surname>@freie-georgenschule.de".

Could you please confirm which domain would you like to add to this repository: freie-georgenschule.de or dbg.rt.bw.schule.de? Thank you!

**Comment by philipto** [comment]
@juknoFGS You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@juknoFGS I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Comment by juknoFGS** [comment]
Hello Mr.Torchinsky,

I had already answered at 12.9 and 12.10 two times to different email
adresses ..

Best regards

J.Knop



-------- Weitergeleitete Nachricht --------
Betreff: 	Re: [JetBrains/swot] Update dbg.txt for Freie-Georgenschule
Reutlingen (#10097)
Datum: 	Tue, 01 Dec 2020 09:04:09 -0800
Von: 	Philip Torchinsky <notifications@github.com>
Antwort an: 	JetBrains/swot
<reply@reply.github.com>
An: 	JetBrains/swot <swot@noreply.github.com>
Kopie (CC): 	juknoFGS <knop@freie-georgenschule.de>, Mention
<mention@noreply.github.com>



@juknoFGS <https://github.com/juknoFGS> Please provide us with:

  * the school official website URL
  * an URL of a page on the official website where the school offers an
    IT-related long-term (>1 year) course
  * a proof, which shows that the school recognizes the domain you are
    submitting as an official email domain for the students.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JetBrains/swot/pull/10097#issuecomment-736686580>,
or unsubscribe

**Comment by juknoFGS** [comment]
That was the message I have sent ...

> @juknoFGS You might miss my previous comment. Please react.

Dear Mr Torchinsky,

I have to apologize .. My thougths were as folows:

I saw the folder /de    => Germany

     /de/schule            => School

     /de/schule/bw/    = > State "Baden Wuerttemberg"

     /de/schule/bw/rt/ => City - Reutlingen

therefore I hve added our domain in that file ...  

I just want to add "freie-georgenschule.de"

Best regards

Juergen

**Pull request closed without merging**
