### PR TITLE
Create bk.txt

### PR DESCRIPTION
**Pull request by Kich-kichi-gai**

### CODE REVIEW

**Comment by philipto** [comment]
@Kich-kichi-gai bk.ru does not belong to any university or college, thus I close this request without merging. Thank you for the understanding.

**Comment by Kich-kichi-gai** [comment]
Good time of a day. bk.ru belong to Beloglinsky Agrarian Technical College. I can ask the college leadership to confirm this by email.22:00, 17 апреля 2017 г., Philip Torchinsky <notifications@github.com>:@Kich-kichi-gai bk.ru does not belong to any university or college, thus I close this request without merging. Thank you for the understanding.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by philipto** [comment]
@Kich-kichi-gai Are you kidding me or trolling me? Bk.ru is owned by Mail.Ru group:

domain:       BK.RU
nserver:      ns1.mail.ru.
nserver:      ns2.mail.ru.
state:        REGISTERED, DELEGATED
admin-contact:https://www.nic.ru/cgi/whois_webmail.cgi?domain=BK.RU
org:          MGL Mail.ru Internet Assets Limited
descr:        domain@corp.mail.ru
registrar:    RU-CENTER-RU
created:      1998.04.15
paid-till:    2017.05.01
source:       RU-CENTER

>>> Last update of WHOIS database: 2017.04.18T07:42:21Z <<<

The college you mentioned has a website in completely different domain and it looks like it does not have an own domain at all: https://gbou-pu33.jimdo.com

If you don't have an email other than @bk.ru, could you please use another option at https://www.jetbrains.com/shop/eform/students ("official document"). If you apply for free license with a photo of your student ID ("студенческий билет"), it will be much simpler.

Thank you!

**Comment by Kich-kichi-gai** [comment]
Sorry for my stupidness. I should have checked the domain. Thanks for your advice and replay!10:56, 18 апреля 2017 г., Philip Torchinsky <notifications@github.com>:@Kich-kichi-gai Are you kidding me or trolling me? Bk.ru is owned by Mail.Ru group:domain:       BK.RUnserver:      ns1.mail.ru.nserver:      ns2.mail.ru.state:        REGISTERED, DELEGATEDadmin-contact:https://www.nic.ru/cgi/whois_webmail.cgi?domain=BK.RUorg:          MGL Mail.ru Internet Assets Limiteddescr:        domain@corp.mail.ruregistrar:    RU-CENTER-RUcreated:      1998.04.15paid-till:    2017.05.01source:       RU-CENTERLast update of WHOIS database: 2017.04.18T07:42:21Z <<<The college you mentioned has a website in completely different domain and it looks like it does not have an own domain at all: https://gbou-pu33.jimdo.comIf you don't have an email other than @bk.ru, could you please use another option at https://www.jetbrains.com/shop/eform/students ("official document"). If you apply for free license with a photo of your student ID ("студенческий билет"), it will be much simpler.Thank you!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.    -- Отправлено из мобильного приложения Яндекс.Почты

**Pull request closed without merging**
