### PR TITLE
Create student/unitbv.txt

### PR DESCRIPTION
**Pull request by AlgiuA**
Add domain for students at Transilvania University of Brasov.

### CODE REVIEW

**Comment by AlgiuA** [comment]
URL for the site: http://unitbv.ro/
URL that confirms the domain for the students : https://student.unitbv.ro/

**Comment by philipto** [comment]
@AlgiuA If the emails of students end with @student.unitbv.ro, correct file path will be lib/domains/ro/unitbv/student.txt. Please rename or comment saying that the domain is different.

**Comment by AlgiuA** [comment]
@philipto I have changed the file path accordingly. Thank you for the correction!

**Comment by philipto** [comment]
@AlgiuA Pull request merged. Thank you!

**Pull request merged**
