### PR TITLE
Add Thadomal Shahani Engineering College

### PR DESCRIPTION
**Pull request by SainathPoojary**
College official website: https://tsec.edu/

### CODE REVIEW

**Comment by philipto** [comment]
@SainathPoojary Please provide us with a proof, which shows that the school recognizes the domain **tsecedu.org** that you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by SainathPoojary** [comment]
Will this work? We got the college id from the mail.

**Comment by SainathPoojary** [comment]
@philipto

**Comment by philipto** [comment]
@SainathPoojary Thank you so much! You probably send the attachment by email. Regrettably, GitHub strips out all the attachments if they are sent by email. Please use your browser to attach the document that you wanted to attach to your comment. Thank you!

**Comment by SainathPoojary** [comment]
Sorry @philipto, For the late response, I was a bit busy.
These are the documents that I had attached using mail

[DSE-Computer (1) (1).xlsx](https://github.com/JetBrains/swot/files/7909186/DSE-Computer.1.1.xlsx)
[CollegeId (1).pdf](https://github.com/JetBrains/swot/files/7909187/CollegeId.1.pdf)

image

image

**Comment by philipto** [comment]
@SainathPoojary Thank you for your message! Regrettably, the request seems to be odd now. There are the reasons:

1. The domain does not have A, MX, and CNAME records. Thus, it's unclear why to add it to the list of trusted email domains. It's technically impossible to send a message to this domain.
```
$ host -t a tsecedu.org
tsecedu.org has no A record
$ host -t mx tsecedu.org
tsecedu.org has no MX record
$ host -t cname tsecedu.org
tsecedu.org has no CNAME record
```

2. In the attached screenshots the message is sent by Sainath Poojary, but signed by Tanuja K Sarode, which is odd and suspicious.

3. You exposed passwords via the screenshot publicly, please remove the attachment now. We definitely do not need any private details of the accounts here.

If you are the student of this school now, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students). 

I have to close the request without merging. Thank you for your understanding.

**Pull request closed without merging**
