### PR TITLE
add domain for Sekolah Tinggi Filsafat Driyarkara student email addresses

### PR DESCRIPTION
**Pull request by aaronmurniadi**
https://driyarkara.ac.id/

### CODE REVIEW

**Comment by philipto** [comment]
@aaronmurniadi First stage of verification passed, official domain is [driyarkara.ac.id](https://driyarkara.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by aaronmurniadi** [comment]
@philipto 
Thank you so much for verifying. 
Please take your time, sir!

**Comment by philipto** [comment]
@aaronmurniadi Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by aaronmurniadi** [comment]
@philipto 

Thank you for your assistance. How long until I can apply using my university email address?

**Pull request merged**
