### PR TITLE
Adding Tri-Chandra Multiple Campus domain

### PR DESCRIPTION
**Pull request by alchemist8**
Course taught could be found at [Tri-Chandra Multiple Campus Website](https://trichandracampus.edu.np/programs/bachelor-of-science-and-technology/).

### CODE REVIEW

**Comment by philipto** [comment]
@alchemist8 First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/tmgpremtmg/photos/a.647115135722016/1283592705407586/

**Comment by philipto** [comment]
@alchemist8 Please explain the relationships between Tri-Chandra University and Tribhuvan University. The parent domain of trc.tu.edu.np, i.e. tu.edu.np, belongs to Tribhuvan University, as far as I understand.

**Comment by philipto** [comment]
@alchemist8 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@alchemist8 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by alchemist8** [comment]
Sorry to be late, Tri-Chandra is a college which is a part of Tribhuvan University.

**Pull request closed without merging**
