### PR TITLE
Add colegio moderno humanista college

### PR DESCRIPTION
**Pull request by BetoOrozco95**
Colegio Moderno Humanista is a Mexican college
https://colegiomodernohumanista.edu.mx

### CODE REVIEW

**Comment by philipto** [comment]
@BetoOrozco95 First stage of verification passed, official domain is [colegiomodernohumanista.edu.mx](https://colegiomodernohumanista.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@BetoOrozco95 Could you please tell us how old are the oldest students enrolled to your school? It looks like they are all younger than 13 of age, and for so young students we usually recommend IntelliJ IDEA Community or PyCharm Community Edition. Both of them are free for everyone and do not require any subscription at all.

**Comment by BetoOrozco95** [comment]
> @BetoOrozco95 Could you please tell us how old are the oldest students enrolled to your school? It looks like they are all younger than 13 of age, and for so young students we usually recommend IntelliJ IDEA Community or PyCharm Community Edition. Both of them are free for everyone and do not require any subscription at all.

   
Hello, we currently have students up to 15 years of age, since we recently included high school.
We also need to use some programs like webstorm and datagrid, as the systems department is working on an internal software for the school and we are training some teachers to teach basic programming.

**Comment by philipto** [comment]
@BetoOrozco95 Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

Please notice that the educational license is for educational use only. If the employees of the school, such as systems department working on an internal software for the school, **who are neither students nor teachers**, need the license, please send a message to [sales@jetbrains.com](mailto:sales@jetbrains.com) to get an academic discount for a paid license.

Educational license is for educational purpose only, i.e. for teachers and students only.

**Pull request merged**
