### PR TITLE
Create greenhills-school

### PR DESCRIPTION
**Pull request by ryanbabcock**

### CODE REVIEW

**Comment by philipto** [comment]
@ryanbabcock I am sorry for a delay with processing your request. Could you please provide some more info about your school, and also correct the file path? 

Website http://www.greenhills-school.org gives this page, and it means the web server may not be configured properly:
"Index of /

.ftpquota
cgi-bin/
Apache Server at www.greenhills-school.org Port 80"

The file path for this email domain has to be lib/domains/org/greenhills-school.txt (.txt extension is mandatory). 

Thank you!

**Comment by ryanbabcock** [comment]
greenhillsschool.org is the correct address.

**Comment by philipto** [comment]
@ryanbabcock If greenhillsschool.org is correct domain name of your school, please rename lib/domains/org/greenhills-school to lib/domains/org/greenhillsschool.txt. I'll merge the pull request as soon as you do it. Thank you!

**Comment by philipto** [comment]
@ryanbabcock Excuse me, correct path is lib/domains/org/greenhillsschool.txt, not lib/domains/org/greenhillsschool (.txt extension is important). I mentioned it in my comment above. However I merged the pull request and renamed the file myself to simplify the process. Pull request merged, thank you.

**Comment by ryanbabcock** [comment]
Thank you, I really appreciate you patience and time.
Best,
Ryan

**Pull request merged**
