### PR TITLE
Added school

### PR DESCRIPTION
**Pull request by Alancho7**

### CODE REVIEW

**Comment by Wicho84** [comment]
Por favor agregar a la Universidad ICEL:  https://e-learning.icel.edu.mx/ 
[file.zip](https://github.com/JetBrains/swot/files/9882713/file.zip)

**Comment by philipto** [comment]
@Alancho7 First stage of verification passed, official domain is [malachowianka.edu.pl](https://malachowianka.edu.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Alancho7 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by philipto** [comment]
@Wicho84 Please make a separate pull request or send an email to community-support@jetbrains.com.

**Pull request merged**
