### PR TITLE
Create covenantuni.txt

### PR DESCRIPTION
**Pull request by azueze**

### CODE REVIEW

**Comment by philipto** [comment]
@azueze According to #1689 email domain for students at Covenant university is stu.cu.edu.ng. Could you please clarify why you can not use the domain which previously declared as correct, and other students at Covenant University use it?

**Comment by azueze** [comment]
stu.cu.edu.ng and covenantuniversity.edu.ng are both official email domains of the university. Like reference earlier older students had the covenantuniversity.edu.ng domain while more recently student's email domain is stu.cu.edu.ng. However, the entire staff of the university uses the covenantuniversity.edu.ng email domain.

**Comment by philipto** [comment]
@azueze Thank you for the clarification. Could you please provide us with a document (or a link to an official web page) which confirms these rules for the students?

**Comment by philipto** [comment]
@azueze I am sorry, this request remains unanswered for a while, I close it without merging. Please reopen if you have an update regarding the university policy. We need some proof of the policy: a web page, a .pdf file with confirmed policy, etc.

**Pull request closed without merging**
