### PR TITLE
Castelo Branco University

### PR DESCRIPTION
**Pull request by danirotmeister**
Please add Brazilian university Castelo Branco.

### CODE REVIEW

**Comment by philipto** [comment]
@danirotmeister Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@danirotmeister You might miss my previous comment. Please react.

**Comment by danirotmeister** [comment]
Good afternoon, the university's official website is
http://www.castelobranco.br/, located in Realengo in Rio de Janeiro -
Brazil.



Em dom., 7 de mar. de 2021 às 15:11, Philip Torchinsky <
notifications@github.com> escreveu:

**Comment by danirotmeister** [comment]
Good afternoon, the university's official website is
http://www.castelobranco.br/, located in Realengo in Rio de Janeiro -
Brazil.
Thanks!

Em dom., 7 de mar. de 2021 às 15:11, Philip Torchinsky <
notifications@github.com> escreveu:

**Comment by philipto** [comment]
@danirotmeister Yes, thank you. Where can I find a proof that "castelobranco.edu.br" is the official domain for students?

**Comment by danirotmeister** [comment]
What document is needed to prove it?

Em qua., 10 de mar. de 2021 às 14:19, Philip Torchinsky <
notifications@github.com> escreveu:

**Comment by philipto** [comment]
@danirotmeister You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@danirotmeister I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
