### PR TITLE
Added school INALCO

### PR DESCRIPTION
**Pull request by Alandir02**
I added my school, INALCO (Institut national des langues et civilisations orientales) (https://www.wikiwand.com/en/Institut_national_des_langues_et_civilisations_orientales). I need to learn python for my classes because it's very important in automatic language processing. Thank you ! Our e-mail adresses are @inalco.fr

### CODE REVIEW

**Comment by BasharAbu-Diak** [comment]
[ptuk.txt](https://github.com/JetBrains/swot/files/6013335/ptuk.txt)

**Comment by Alandir02** [comment]
Website of my school : http://www.inalco.fr/

Contact page where you see everyone, from students to administration, uses @inalco.fr mail : http://www.inalco.fr/contact

Do you need anything else ? Thank you !

**Comment by Alandir02** [comment]
I have read in pull requests that you are asking for other informations, so here they are :

An IT related program : http://www.inalco.fr/en/study/master-degrees
On this page you will see that my school offers language processing master's degrees which has a very strong need for programming and python.

The contact page : http://www.inalco.fr/en/node/1433
Sorry though, the contact page does not seem to exist in english, but if you look at what "contacter le webmaster" (contact the webmaster) links to, you will see that it's a mailto:webmaster@inalco.fr as we all use @inalco.fr, be it administration or students or anything else.

**Comment by Alandir02** [comment]
@philipto is there an issue ? I see you are answering other pull requests but not mine ?

**Comment by philipto** [comment]
@Alandir02 I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Pull request merged**
