### PR TITLE
Adding R N Podar School

### PR DESCRIPTION
**Pull request by kairavsheth**

### CODE REVIEW

**Comment by philipto** [comment]
@kairavsheth First stage of verification passed, official domain is [rnpodarschool.com](https://rnpodarschool.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by kairavsheth** [comment]
@philipto thank you for the update. Hoping to receive the confirmation soon.

**Comment by philipto** [comment]
@kairavsheth First stage of verification passed, official domain is [rnpodarschool.com](https://rnpodarschool.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@kairavsheth Pull request merged. Thank you!

**Pull request merged**
