### PR TITLE
Create ihl.eu and liebenzell.org for Internationale Hochschule Bad Liebenzell

### PR DESCRIPTION
**Pull request by zocker22**
Students are registered with firstname.lastname@liebenzell.org.
Teachers are registerd with firstname.lastname@ihl.eu.

### CODE REVIEW

**Comment by zweizwei** [comment]
@zocker22 could you please somehow confirm that http://www.liebenzell.org/ is used for students' domains? It seems to belong to social organization rather than to school. Thanks in advance for your help.

**Comment by zocker22** [comment]
Mhh .. sure ... just let me know what you would like to have. Our IT department will give you what ever you need :-)
At liebenzell.org there is a entry, which lists all the different study-options for students at Liebenzell Mission: http://www.liebenzell.org/studieren-liebenzell/studieren-in-liebenzell/
Together with ihl.eu
I hope this helps you. Otherwise just let me know what you need and I'tt try to provide it.

**Comment by zweizwei** [comment]
@zocker22 Sorry for the delay - we've been launching rebranding and I hadn't time to check the repo for a while. By confirmation I mean any document or page where it is stated that @liebenzell.org emails are assigned to students. Thank you!

**Comment by zocker22** [comment]
@zweizwei 
Attached I have the document of our rector, that confirms the email pattern. I hope this helps you
ihl_email

**Comment by zweizwei** [comment]
@zocker22 thanks a lot, that's exactly what i needed - i'll add the domain now

**Pull request merged**
