### PR TITLE
THPT Yên Viên

### PR DESCRIPTION
**Pull request by ianTuG**

### CODE REVIEW

**Comment by philipto** [comment]
@ianTuG The domain registrant for **thptyenvien.edu.vn** is Trường THPT Yên Viên (Yen Vien High School). This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@ianTuG Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by ianTuG** [comment]
> @ianTuG Thank you for your patience while waiting for a review and processing your request. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

Hi, I have just read this notification for few mins, but I cannot enroll now. They still show me that :"Your email address does not belong to any university that we know. You can apply with another method (see tabs above) or [add your school](https://www.jetbrains.com/shop/eform/students/contributeUniversity?email=k570132973908%40thptyenvien.edu.vn) to JetBrains' list.". What should I do ?

**Comment by philipto** [comment]
Hi.

Please wait an hour, to let the changes to propagate through our system.

Thank you.

**Comment by ianTuG** [comment]
Hi, I have just got a message from Jetbrains's education enrollment
website. They say: "Thank you!. Please follow the instructions in the
verification email we've sent to ***@***.***", but I
have not received any email from them. Our school is using Outlook, and I
do not have any mistakes in typos. You can see some captures below.

Many thanks and best regards!

[image: image.png]
[image: image.png]
[image: image.png]

**Comment by philipto** [comment]
@ianTuG Please send me the email message with the screenshots to community-support@jetbrains.com. When you send an email message in reply to the comment on GitHub, GitHub strips out any attachments and hide all email  addresses. To review your specific case I need to see the screenshots and see your email address. Please send us an email to community-support@jetbrains.com, and mention this request URL `https://github.com/JetBrains/swot/pull/23808` in the message. Thank you.

**Comment by ianTuG** [comment]
Oh, sorry. I have some mistakes with our services. I have requested new
pull request with correct email suffix for student.

**Pull request merged**
