### PR TITLE
Create GD.innovation.txt

### PR DESCRIPTION
**Pull request by iyyann**
This is my college name

### CODE REVIEW

**Comment by philipto** [comment]
@iyyann Please let me know what is your actual email domain? What your email address end with? @innovation.gd.edu?

**Comment by iyyann** [comment]
I'm sorry, I'm a Chinese college student, but I don't have edu mailbox. At present, I have only one school number. The mailbox now being used is 1422476675@qq.com and a1422476675@163. com, I've been using phpStorm for more than a year), and I want to get help

**Comment by philipto** [comment]
@iyyann I am sorry, if you do not have an email address which is in your university email domain (such as, for example, username@gdut.edu.cn), and you do not have an ISIC card, the only way to apply for free JetBrains license for you is to provide us with an official document which proves that you are a student. Usually, a university gives to the students such a document with your name, photo and name of the university. You can apply at https://www.jetbrains.com/shop/eform/students, click on the tab "OFFICIAL DOCUMENT" and attach the photo of your document there. 

I have to close your request without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Comment by iyyann** [comment]
Thank you for doing something for me. I'll try it.

**Pull request closed without merging**
