### PR TITLE
Added "ISET Beja" located in Tunisia

### PR DESCRIPTION
**Pull request by HorrorBest**
Added "Higher Institute of Technological Studies Beja" located in Tunisia

### CODE REVIEW

**Comment by philipto** [comment]
@HorrorBest First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/1117178798308917/posts/offre-demploiliset-de-beja-en-collaboration-avec-efe-tunisie-organise-une-journe/4070019869691447/

**Comment by HorrorBest** [comment]
This is the Actual Facebook page of The Institute If you want to check it
out

https://www.facebook.com/ISET.BEJA.MESRS

**Comment by philipto** [comment]
@HorrorBest Thank you for the clarification. The issue is that I cannot find an actual web site of the Institute. Doesn't the school have a website?

**Comment by HorrorBest** [comment]
They do have a WordPress Website, But I don't know If you could call it a
"actual" website. It's not even maintained or up-to-date

**Comment by philipto** [comment]
> They do have a WordPress Website, But I don't know If you could call it a "actual" website. It's not even maintained or up-to-date

You are right, I already took a look at the website. Isn't it unusual for a school to have no up-to-date website at all?

Thus, I confirm that the school is verified with this sources of info: 
1) https://scholar.google.com/citations?user=S3oJB_wAAAAJ&hl=fr
2) https://www.researchgate.net/profile/Mouna-Belhaj

Pull request merged. Thank you.

**Comment by HorrorBest** [comment]
Thank you, Also can I now Get the Products ?

**Pull request merged**
