### PR TITLE
Add universidad villa de zacatecas

### PR DESCRIPTION
**Pull request by iscjiha**
Thanks in advance

### CODE REVIEW

**Comment by philipto** [comment]
@iscjiha First stage of verification passed, official domain is [universidadvilladezacatecas.edu.mx](https://universidadvilladezacatecas.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@iscjiha Something is wrong with the school website:
image
I will get back to the request later if the website will be operational. Thank you for your understanding.

**Comment by iscjiha** [comment]
> @iscjiha Something is wrong with the school website: image I will get back to the request later if the website will be operational. Thank you for your understanding.

**Comment by iscjiha** [comment]
> @iscjiha Something is wrong with the school website: image I will get back to the request later if the website will be operational. Thank you for your understanding.

UVZ

**Comment by philipto** [comment]
@iscjiha Thank you! Yes, the website is operational now. Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@iscjiha You might miss my previous comment. Please react.

**Comment by iscjiha** [comment]
They have NOT added the information to the website

**Comment by philipto** [comment]
@iscjiha Thank you for the clarification. Thus, we have to admit that it's impossible to verify whether the school offers courses that may require using professional software tools for the studies.

Many email subdomains of edu.mx were abused by third parties in the last months. Given the facts mentioned above, I have to reject the request and close it.

Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Pull request closed without merging**
