### PR TITLE
add unitec discovery

### PR DESCRIPTION
**Pull request by adminWeconnect**

### CODE REVIEW

**Comment by philipto** [comment]
@adminWeconnect First stage of verification passed, official domain is [unitecdiscovery.net](https://unitecdiscovery.net) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.unitecdiscovery.net/contacto

**Comment by philipto** [comment]
@adminWeconnect Could you please tell more about the school? Is it a high school for students in a particular city? How old are the students? Do you have any courses related to software development? How many students does this school have?

Thank you!

**Comment by philipto** [comment]
@adminWeconnect You might miss my previous comment. Please react.

**Comment by adminWeconnect** [comment]
Could you please tell more about the school?
Unitec Discovery is a private educational institution that aims to provide
the highest possible quality education, utilizing high-level tools in terms
of human talent, software, educational materials, etc.

Is it a high school for students in a particular city?
Yes, it is a high school located in the city of Cuenca, in the province of
Azuay in Ecuador.

How old are the students?
The average age of the students is 16 years old

Do you have any courses related to software development?
Several specialties in the institution involve programming courses,
especially the computer science specialization.

How many students does this school have?
There are around 300 students.

**Comment by philipto** [comment]
@adminWeconnect Thank you very much for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
