### PR TITLE
Create thecdm

### PR DESCRIPTION
**Pull request by takaf51**

### CODE REVIEW

**Comment by philipto** [comment]
@takaf51 Could you please:
1) provide us with a link to an IT-related long-term (>1 year) offered by your school described on your website, and
2) modify the file path to add your email domain to the repository, it has to be `lib/domains/ca/thecdm.txt`, .txt extension is mandatory.

If you do not have such a course, could you please explain what you would like to use JetBrains tools for?

Thank you!

**Comment by philipto** [comment]
@takaf51 Could you please answer my previous comment in order to proceed with adding the domain to this repository? Thank you!

**Comment by takaf51** [comment]
Sorry for my slow response.
1. You can find information about master program this link. https://thecdm.ca/program/mdm
2. I did that.
Regards,
Taka

**Comment by philipto** [comment]
@takaf51 Pull request merged. To be honest, it is still not clear from https://thecdm.ca/program/mdm what exactly you can use JetBrains tools for, but formally the institution fits the requirements, thus I added it to the repository. Please email support@jetbrains.com if you have any problems using the tools.

**Pull request merged**
