### PR TITLE
Adding USTTB file

### PR DESCRIPTION
**Pull request by elaykilla**
Bamako University

### CODE REVIEW

**Comment by elaykilla** [comment]
!!URGENT
We would really appreaciate if this could be merged quickly. Our school year has been highly disrupted by COVID and Military Coup. We are only beginning the year 2020 in March and would like to be able to provide efficient solution for students studying remotly.

**Comment by philipto** [comment]
@elaykilla I am sorry, this request cannot be merged due to lack of publicly available info about the school. I have to close it without merging. If you are a student of this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Comment by elaykilla** [comment]
Hello,

Which publicly available information is required?

Actually I’m a lecturer at the school and have all the official documents. Could you please advice on procedure to follow.

Thank you very much,

**Comment by elaykilla** [comment]
Please find attached the official documents for the USTTB.

We have just been validated by Microsoft as an éducationnel institute. It’s the public University of Bamako.

**Comment by philipto** [comment]
@elaykilla Thank you for the prompt response. Regrettably, GitHub strips out the attachments if you reply by email. If you wish to attach any documents to your request, please do it in your web browser in a comment at this page: https://github.com/JetBrains/swot/pull/11049

The official website of the university is http://www.usttb.edu.ml. You request to add a domain usttb.online, which is different from usttb.edu.ml. Therefore, please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative (on a letterhead, with the representative's signature) saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by elaykilla** [comment]
Hello, Thank you for reverting. 
Yes we have just recently put up the .online. The main reason is because the edu.ml is shared by all public universities in Mali. As a result we cannot have a single mail provider for all.
We have requested a change to the official website to put the usttb.online as contact and mention it as email for students.

**Comment by philipto** [comment]
@elaykilla To my great regret this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
