### PR TITLE
Create datapot.txt

### PR DESCRIPTION
**Pull request by Tracytran1510**
https://datapot.edu.vn/
Datapot is an educational institute that provides data science courses for Universities and Companies in Vietnam.

### CODE REVIEW

**Comment by ahadley1124** [comment]
@Tracytran1510 Is the domain for your emails @datapot.EDU.vn or @datapot.vn?

**Comment by Tracytran1510** [comment]
> 



> 

Both @datapot.EDU.vn and @datapot.vn are used now. Could you please add both domains ?

**Comment by ahadley1124** [comment]
You will need to add another file to lib/domains/vn/ for datapot.vn to be a domain.

**Comment by philipto** [comment]
@Tracytran1510 Are you a student of this school or a teacher? May I suggest you to contact the school administration and ask them to send an email to JetBrains to community-support@jetbrains.com? 

The school seems to be a little bit different from a classic university and even online training center. The school may be specifically interested in using DataSpell and PyCharm Professional, as well as Datalore. 

I need to talk to the school administration to better understand the potential of a co-operation. Thank you.

**Comment by Tracytran1510** [comment]
Thanks for your informaiton. I'm a staff there. I have asked school administration to email to community-support@jetbrains.com for further information. 
So it means that @datapot.EDU.vn is added ?

**Comment by philipto** [comment]
@Tracytran1510 Thank you! I did not add datapot.EDU.vn yet because we need to clarify several important details with the administration.

**Comment by philipto** [comment]
@Tracytran1510 I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by philipto** [comment]
@Tracytran1510 We received all the necessary information from the school administration. I reopened the request and merged it. Thank you for your patience while waiting for the request review!

**Pull request merged**
