### PR TITLE
Governo de Santa Catarina | Secretaria de Estado da Educação - Novos …

### PR DESCRIPTION
**Pull request by reneDuarte**
…Caminhos EAD

### CODE REVIEW

**Comment by reneDuarte** [comment]
Add 
Governo de Santa Catarina | Secretaria de Estado da Educação - Novos Caminhos EAD

**Comment by philipto** [comment]
@reneDuarte test/swot/SwotTest.kt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by reneDuarte** [comment]
Add
Governo de Santa Catarina | Secretaria de Estado da Educação - Novos Caminhos EAD

**Comment by philipto** [comment]
@reneDuarte Pull request merged. Thank you!

**Pull request merged**
