### PR TITLE
SAPP Academy

### PR DESCRIPTION
**Pull request by sapp-academy**
Request from SAPP Academy

### CODE REVIEW

**Comment by philipto** [comment]
@sapp-academy The domain registrant for **sapp.edu.vn** is CÔNG TY CỔ PHẦN GIÁO DỤC SAPP (SAPP Education Joint Stock Company). This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@sapp-academy Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school is recognized by the State of Vietnam as an educational organization.

Thank you!

**Comment by philipto** [comment]
@sapp-academy You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@sapp-academy I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by sapp-academy** [comment]
Hi philipto, So sorry. I will send it to you in the next few days

**Comment by sapp-academy** [comment]
the school official website URL: https://sapp.edu.vn/
the school street address, including city and country: SAPP Academy - 54 Lê Thanh Nghị - Bách Khoa - Hai Bà Trưng - Hà Nội - Việt Nam
an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: https://sapp.edu.vn/khoa-hoc-acca-online/
a proof, which shows that the school is recognized by the State of Vietnam as an educational organization: image attach
[SAPP_Giấy ĐKKD công ty lần 5 ngày 28082020.pdf](https://github.com/user-attachments/files/17288165/SAPP_Gi.y.DKKD.cong.ty.l.n.5.ngay.28082020.pdf)

**Pull request closed without merging**
