### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by npatelli**
Added 'Centre IFAPME de Charleroi' in lib/domains/be

### CODE REVIEW

**Comment by philipto** [comment]
@npatelli Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@npatelli You might miss my previous comment. Please react.

**Comment by npatelli** [comment]
Thanks for the reminder ✌🏻
Website : http://www.charleroi.ifapme.be
Designer course : http://www.charleroi.ifapme.be/formations-a-un-metier/trouver-une-formation-a-un-metier/catalogue-des-formations-a-un-metier/infographiste-chef-d-entreprise.html
I don't have any proof for the domain for now, it's a new thing and we only received the logins 2 weeks ago on a small piece of paper 😅

**Comment by philipto** [comment]
@npatelli Thank you for the update! Pull request merged.

**Pull request merged**
