### PR TITLE
Create isisdavinci.txt

### PR DESCRIPTION
**Pull request by ranalliloris**

### CODE REVIEW

**Comment by ranalliloris** [comment]
School official website URL: [https://www.isisdavinci.edu.it/](https://www.isisdavinci.edu.it/)

URL of a page on the official website where a long-term (3 year) IT related course is offered by the school: [https://www.isisdavinci.edu.it/pagine/informatica](https://www.isisdavinci.edu.it/pagine/informatica)

URL of a page  showing that the School recognizes the domain as an official email domain for the enrolled students: 
[https://www.isisdavinci.edu.it/servizi?id=1665&&source=servizi-personale#](https://www.isisdavinci.edu.it/servizi?id=1665&&source=servizi-personale#)

Screenshoot dominio

**Comment by philipto** [comment]
@ranalliloris The first verification stage is complete: the official domain for  **Istituto Statale Istruzione Superiore Leonardo Da Vinci - Firenze** is [www.isisdavinci.edu.it](https://www.isisdavinci.edu.it), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.isisdavinci.edu.it/servizi?id=1664&&source=servizi-personale

**Comment by ranalliloris** [comment]
I would like to point out that the email domain assigned to the student and teacher accounts is **isisdavinci.eu**, only the school official website is on the isisdavinci.edu.it domain.

**Comment by philipto** [comment]
@ranalliloris The first verification stage is complete: the official domain for  **Istituto Statale Istruzione Superiore Leonardo Da Vinci - Firenze** is [www.isisdavinci.edu.it](https://www.isisdavinci.edu.it), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.isisdavinci.edu.it/servizi?id=1664&&source=servizi-personale

**Comment by philipto** [comment]
@ranalliloris  Thank you for the clarifications and your patience. Pull request merged.

**Pull request merged**
