### PR TITLE
Create suntech.txt

### PR DESCRIPTION
**Pull request by STC-EDU**

### CODE REVIEW

**Comment by philipto** [comment]
@STC-EDU Please provide us with:
- the school official website URL, 
- an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by STC-EDU** [comment]
https://suntech.ac.jp/
(japanese)

https://suntech.ac.jp/en/index.html
(english)

https://campus.suntech.jp/
(not accessible from other domains)

**Comment by philipto** [comment]
@STC-EDU Could you please tell me how can we check that the university recognizes suntech.jp as an official domain for their students? Do you have any paper, .pdf., internal instruction or other data to prove that? Thank you.

**Comment by philipto** [comment]
@STC-EDU You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@STC-EDU Could you please answer the question about official document to prove the domain recognition by the university?

**Pull request closed without merging**
