### PR TITLE
Add Perins School

### PR DESCRIPTION
**Pull request by MyNameIs-Ben**

### CODE REVIEW

**Comment by philipto** [comment]
@MyNameIs-Ben The first verification stage is complete: the official domain for  **Perins School** is [www.perins.net](https://www.perins.net), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.perins.net/

**Comment by MyNameIs-Ben** [comment]
@philipto the domain for Perins School is www.perins.net and the student email domain is perins.hants.sch.uk

**Comment by philipto** [comment]
@MyNameIs-Ben The first verification stage is complete: the official domain for  **Perins School** is [www.perins.net](https://www.perins.net), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.perins.net/

**Comment by philipto** [comment]
@MyNameIs-Ben Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
