### PR TITLE
Create ittoluca

### PR DESCRIPTION
**Pull request by GarciHard**

### CODE REVIEW

**Comment by philipto** [comment]
@GarciHard http://toluca.tecnm.mx/contacto/ says that email domain for the university is @Ittoluca.Edu.Mx, not @ittoluca.mx. Could you please clarify what is the university email domain, and what page at the official website confirms that it is @ittoluca.mx. Thank you!

**Comment by philipto** [comment]
@GarciHard You might miss my previous comment. Please reply.

**Comment by GarciHard** [comment]
@philipto recently my university changed the email domain, now we got a Microsoft 365 account with an @toluca.tecnm.mx domain.

The other domains like @Ittoluca.Edu.Mx or @ittoluca.mx are deprecated

In the main page of [Instituto Tecnológico de Toluca newWebPage](http://toluca.tecnm.mx) or [Instituto Tecnológico de Toluca olderWebPage](http://www.ittoluca.edu.mx) you can find a section called _"Por un mejor tecnológico"_ you can see three email account with @toluca.tecnm.mx domain. (:

**Comment by philipto** [comment]
@GarciHard Thank you for the update. If the domain is @toluca.tecnm.mx, the file path in the request has to be lib/domains/mx/tecnm/toluca.txt. Please rename, and I merge the request as soon as possible. Thank you!

**Comment by philipto** [comment]
@GarciHard Pull request merged. Thank you!

**Comment by GarciHard** [comment]
@philipto thank you :)

**Pull request merged**
