### PR TITLE
Add inrae.fr following INRA renaming to INRAE

### PR DESCRIPTION
**Pull request by cpommier**
inrae.fr is the new name of inra.fr, see https://www.inrae.fr/en/about-us to get more information on the merger.

### CODE REVIEW

**Comment by philipto** [comment]
@cpommier lib/domains/fr/inrae.fr: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@cpommier lib/domains/fr/inrae.fr: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@cpommier lib/domains/fr/inrae.fr: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by cpommier** [comment]
Sorry for that mistake, @philipto , I have renamed the file from irnae.fr to inrae.txt. Thanks.

**Comment by philipto** [comment]
@cpommier Thank you for the correction. Could you please tell me does this Institute provide any students with any IT-related courses? I did not find an information about admission and the courses at the website. Am I mistaken?

**Comment by cpommier** [comment]
@philipto INRAE is a complicated institute which main fcous is on public research, but with some INRAE researchers involved in master including bioinformatics. See for instance http://www.master-bio-agro-bordeaux.com/plant-breeding-2.html. Those teacher have an @inrae.fr email rather than one from a university. Would that be sufficient in respect to your policy?

**Comment by philipto** [comment]
@cpommier Yes, thank you!

Pull request merged. 
Please notice that free educational subscription for JetBrains tools is for students and teachers only, and is valid for using the tools for educational purpose only. If employees of this Institute who are not students, nor teachers, also need a license for JetBrains tools, they are eligible for an academic discount for the tools. They can get the discount by email to sales@jetbrains.com.
Thank you!

**Pull request merged**
