### PR TITLE
My school

### PR DESCRIPTION
**Pull request by BasZalac**
Hi this is my school's IT site:
https://ipariszakkozep.hu/kepzeseink/technikum-szakkepzo/szoftverfejleszto-es-tesztelo

There is no english page, but it's a 5 year long secondary school course focused on a lot of aspects of IT, including software development with C#

### CODE REVIEW

**Comment by philipto** [comment]
@BasZalac The first verification stage is complete: the official domain for  **Veszprémi Szakképzési Centrum Ipari Technikum** is [ipariszakkozep.hu](https://ipariszakkozep.hu), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://ipariszakkozep.hu/p/linkek

**Comment by BasZalac** [comment]
@philipto That domain is only for school staff. For students it's ipari.vein.hu

**Comment by philipto** [comment]
@BasZalac The first verification stage is complete: the official domain for  **Veszprémi Szakképzési Centrum Ipari Technikum** is [ipariszakkozep.hu](https://ipariszakkozep.hu), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://ipariszakkozep.hu/p/linkek

**Comment by philipto** [comment]
@BasZalac Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
