### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Lennart-1337**

### CODE REVIEW

**Comment by qq315731904** [comment]
[file.zip](https://github.com/JetBrains/swot/files/7073762/file.zip)

**Comment by Lennart-1337** [comment]
https://filder-benden.de

**Comment by Lennart-1337** [comment]
https://filder-benden.de/2021/06/13/projektkurs-virtual-reality-findet-den-weg-du-auch/
https://filder-benden.de/2021/07/01/gymnasium-filder-benden-eroeffnet-fabelhaftes-digitales-labor/

**Comment by philipto** [comment]
@Lennart-1337 Pull request merged. Thank you!

**Pull request merged**
