### PR TITLE
Create lnam.txt

### PR DESCRIPTION
**Pull request by NikitaGedzhua**

### CODE REVIEW

**Comment by philipto** [comment]
@NikitaGedzhua First stage of verification passed, official domain is [lnam.edu.ua](https://lnam.edu.ua) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@NikitaGedzhua Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@NikitaGedzhua You might miss my previous comment. Please react.

**Comment by Trespassers-William** [comment]
Our students of educational program of Graphic design have Web technology (Git, HTML, CSS, JS) course as educational component in the 2 and 3 years:
https://lnam.edu.ua/files/Academy/navchannia/studentu/katalog%20OPP%20eng/bachelor/GD%20bak.pdf
Here are presented the third year studentsʼ projects:
https://lnam.edu.ua/files/Academy/faculty/design/graphic/web2021/index.html

**Pull request merged**
