### PR TITLE
Adding School Zespół Szkół Gastronomicznych i Hotelarskich w Chełmie

### PR DESCRIPTION
**Pull request by ScreamMaster1337**
[zsgihchelm.txt](https://github.com/JetBrains/swot/files/13648259/zsgihchelm.txt)

Website: http://www.zsgihchelm.pl/

### CODE REVIEW

**Comment by philipto** [comment]
@ScreamMaster1337 First stage of verification passed, official domain is [zsgihchelm.pl](https://zsgihchelm.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@ScreamMaster1337 Please provide us with the school official website URL. There is no website by the address zsgihchelm.pl as of today. Thank you.

**Comment by ScreamMaster1337** [comment]
Hello, as far as I know currently the school has a problem with the hosting services and on the phone it gives an error, on the computer now I tested and it should work at the address: http://www.zsgihchelm.pl/. I do not guarantee that it will work on the phone please check on the computer.

**Comment by philipto** [comment]
@ScreamMaster1337 Thank you for the update! The website is accessible now. However a list of courses at http://www.zsgihchelm.pl/kierunki.html shows that the school does not have any IT-related courses that may require any software development. 

Therefore, I cannot add the domain to the repository, it is [against the rules](https://github.com/JetBrains/swot#which-educational-institutions-can-be-added-to-the-repository). If you have some individual study plan that needs to be performed with professional software development tools, please apply for free educational license with an official document, which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
