### PR TITLE
Create polac.txt

### PR DESCRIPTION
**Pull request by Dacareux**

### CODE REVIEW

**Comment by philipto** [comment]
@Dacareux Do I understand right that the Academy uses polac.cz domain for the teachers, and pacr.eu for students?

Could you please give us a link to an official web page describing a long-term (> 1 year) IT-related course which the Academy offers to the students? If there is no such course, could  you please give us a bit more details on how the Academy (or you) plans to use JetBrains tools?

**Comment by Dacareux** [comment]
Hi,

you do understand absolutely correct. Domain pacr.eu is for students and
polac.cz is for teachers.
Unfortunately Police Academy doesn't have any IT program. We do have
several classes connected to IT, but nothing connected to software
development in particular. I am one of the few students with deeper
interest in IT, because I used to study it at another university. We do
have a student club called AFCEA which is connected to a non-profit
association bearing the same name (Armed Forces Communications and
Electronics Association), which is an organization supporting
development of IT skills among members of armed forces.
I can not speak for Police Academy as a whole, but from my experience I
am pretty confident to say that only a few students would use the
student licence that you offer. As far as I am concerned, I would like
to use your JetBrains tools to improve my programming skills and
possibly contribute to opensource project Spring RTS (game engine) in
some way.

**Comment by philipto** [comment]
@Dacareux Yes, it looks like a good reason to add the Police Academy to this repository. Thus, I just merged https://github.com/JetBrains/swot/pull/1770 and merge this PR as well, because you do have IT-related classes, and therefore you may wish to suggest the teachers to use JetBrains tools there as well. Thank you!

**Comment by Dacareux** [comment]
Thank you!

**Pull request merged**
