### PR TITLE
create bkukr

### PR DESCRIPTION
**Pull request by felixbiastoch**

### CODE REVIEW

**Comment by felixbiastoch** [comment]
create bkukr

**Comment by philipto** [comment]
@felixbiastoch could you please clarify which email addresses teachers and students of your school have? It is unclear from the two requests which you made, and the official website does not provide this information easily.

**Comment by felixbiastoch** [comment]
@philipto Oh Sorry! 
It's a Microsoft Office Mail. 
[ClassID]-[StudentName]@student.bkukr.de
IT42-febiastoch@student.bkukr.de

**Comment by philipto** [comment]
@felixbiastoch Thank you for the clarification. For the domain student.bkukr.de the correct file path in this repository would be lib/domains/de/bkukr/student.txt. Could you please change the file path? Please note that .txt extension is mandatory. Thank you.

**Comment by felixbiastoch** [comment]
@philipto now it is okay?

**Comment by philipto** [comment]
@felixbiastoch Yes, absolutely! Pull request merged. Thank you!

**Pull request merged**
