### PR TITLE
Create isg.txt

### PR DESCRIPTION
**Pull request by Kenx9**

### CODE REVIEW

**Comment by Kenx9** [comment]
Domain uvt.tn

**Comment by philipto** [comment]
@Kenx9 isg.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Kenx9 isg.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Kenx9 Could you please tell me what is an email address pattern for students in your university? Is it username@uvt.tn?

**Comment by philipto** [comment]
@Kenx9 I am sorry, I have to close the request without merging, because you request to add two different universities in a single request, and one of the files has an incorrect format. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot). Please send an email to community-support@jetbrains.com if you are not sure how to add your university email domain to this repository.

**Comment by Kenx9** [comment]
Sorry for the late reply, i forgot to remove the previous file before requesting the new pull.
I've created a new request
Thanks for your understanding.

**Pull request closed without merging**
