### PR TITLE
Create gimnaziya-dzr.txt

### PR DESCRIPTION
**Pull request by gfeser**

### CODE REVIEW

**Comment by gfeser** [comment]
Add Orthodox Gymnasium of Seraphim of Sarov

**Comment by philipto** [comment]
@gfeser Please provide us with:
* the school official website URL
* the school official name (in Russian)
* the school street address, including the city 
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you!

**Comment by wfeser** [comment]
URL: http://www.gimnaziya-dzr.ru/

_the school official name (in Russian):_ 
Православная гимназия им. Серафима Саровского г. Дзержинск

_the school street address, including the city:_ 
Нижегородская область, город Дзержинск, улица Строителей, дом 8

_a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students:_
The attached file contains a screenshot of the school website.
Снимок экрана от 2022-08-02 16-32-09

**Comment by philipto** [comment]
@gfeser  Thank you for the clarifications. Pull request merged.

**Pull request merged**
