### PR TITLE
Add Egressy

### PR DESCRIPTION
**Pull request by Vikhun15**
Create a file for the email domain "egressy.info" of the Hungarian Budapesti Műszaki Szakképzési Centrum Egressy Gábor Két Tanítási Nyelvű Technikum

### CODE REVIEW

**Comment by Vikhun15** [comment]
Here is the Home page of the school: [https://www.egressy.info/](https://www.egressy.info/)
On the right hand side (indicated by the blue arrow) you can see that this is the official domain used by the email address of the secretariat (titkarsag@egressy.info), "Titkárság" meaning secretariat in hungarian.

kép

**Comment by philipto** [comment]
@Vikhun15 First stage of verification passed, official domain is [egressy.info](https://egressy.info) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Vikhun15** [comment]
Feedback appreciated!

**Comment by philipto** [comment]
@Vikhun15 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
