### PR TITLE
Added Aptech Computer Education

### PR DESCRIPTION
**Pull request by haseebmallik**
This is the email domain for  S.I.T.E Branch inKarachi

### CODE REVIEW

**Comment by philipto** [comment]
@haseebmallik Please provide us with:
* the university official website URL, if different from the domain you are submitting
* an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
* an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by haseebmallik** [comment]
This is official website of aptech computer education
http://aptech-education.com.pk/.
Aptech has many branches in a city so they have separate domains for emails
in *@aptech{branch-code}.{TLD}*.
For example the email domain for Garden, Karachi area is *@aptechgdn.com
<http://aptechgdn.com>*, similarly my branch is S.I.T.E Karachi area so I
was given *@aptechsite.net <http://aptechsite.net>*

Attached is a snap of my email profile as a proof.

Regard
*Haseeb Malik*

   1.
   <http://webcache.googleusercontent.com/search?q=cache:M_nxEOY0ZIEJ:aptech-education.com.pk/+&cd=1&hl=en&ct=clnk&gl=pk>
   2.
   <https://www.google.com.pk/search?hl=en&q=related:aptech-education.com.pk/+aptech+computer+education&tbo=1&sa=X&ved=0ahUKEwiBi_PvsuXWAhXKmLQKHQz2BvUQHwgpMAA>

**Comment by philipto** [comment]
@haseebmallik Thank you for the details! Could you please provide us with the link to the long-term (> 1 year) courses? This page (http://aptech-education.com.pk/courses_includes/stc_javaI.aspx) says that Java course, for example, lasts for 48 hours, which is far less than usual 1-year-long courses which JetBrains tools are necessary for.

If there are just short-term courses at your school, it makes sense to use trial versions of the tools (they are valid for 30 days, and can be prolonged if necessary - you can email sales@jetbrains.com to get an extended trial.

**Comment by haseebmallik** [comment]
Please check this <http://aptech-education.com.pk/accp_ee.aspx>

Thanks,

Regard
*Haseeb Malik*

On Tue, Oct 10, 2017 at 2:28 PM, Philip Torchinsky <notifications@github.com

**Comment by philipto** [comment]
@haseebmallik Thank you very much for all the details! Pull request merged. Thank you!

**Comment by haseebmallik** [comment]
Thank you so much.

I have friends at other branches of Aptech who might be interested in this
so I want to make more pull requests for their branch domains as well.

Regards,

On Tue, Oct 10, 2017 at 3:18 PM, Philip Torchinsky <notifications@github.com

**Pull request merged**
