### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by quakeeteo**

### CODE REVIEW

**Comment by quakeeteo** [comment]
Hello our website is https://eteo.org 
Teacher email is [firstname.lastname]@eteo.org
Students email is [ student number]@alunos.eteo.org
Regards

**Comment by philipto** [comment]
@quakeeteo Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@quakeeteo You might miss my previous comment. Please react.

**Comment by quakeeteo** [comment]
Hello Philipto here is the information requested

- Official website URL: ETEO.ORG, and eteo-apepo.com but we only use eteo.org for the faculty staff, alunos.eteo.org is a subdomain created for the students email, print of student email in microsoft 365 is attached

- School street address, including city and country: 
Escola Técnica Empresarial do Oeste
Rua Cidade de Abrantes, nº 8
2500-146 Caldas da Rainha
Portugal
Phone: 262842247
email: geral@eteo-apepo.com

Screenshot 2024-11-03 at 19-43-25 Utilizadores ativos - centro de administração do Microsoft 365
Captura de ecrã de 2024-11-03 19-58-19

- URL of a page on the official website where the school offers an IT-related long-term (>1 year) course:
https://eteo-apepo.com/course/tecnico-multimedia-2/ ,  its 3 year course whit 3250 hours

Screenshot 2024-11-03 at 19-43-25 Utilizadores ativos - centro de administração do Microsoft 365
Captura de ecrã de 2024-11-03 19-58-19


Regards 
Carlos Querido

**Comment by philipto** [comment]
@quakeeteo Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
