### PR TITLE
Add OSMU

### PR DESCRIPTION
**Pull request by BrainRTP**

### CODE REVIEW

**Comment by philipto** [comment]
@BrainRTP I am sorry, this university has different domain, orgma.ru. If you think that you are submitting a correct domain, please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students. Thank you.

**Comment by philipto** [comment]
@BrainRTP You might miss my previous comment. Please react.

**Comment by BrainRTP** [comment]
> @BrainRTP I am sorry, this university has different domain, orgma.ru. If you think that you are submitting a correct domain, please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students. Thank you.

Снимок экрана 2019-08-14 в 22 31 58
Снимок экрана 2019-08-14 в 22 34 50

Снимок экрана 2019-08-14 в 22 34 02

**Comment by philipto** [comment]
@BrainRTP I am sorry, your comments really confuse me. What is this university email address pattern? username@orgma.ru? username@esoo.ru? username@osmu.ru? The filename  lib/domains/ru/osmu.txt  represents a domain osmu.ru, and this is why I am confused. Please clarify which domain you wish to add.

**Comment by BrainRTP** [comment]
The website was originally created when university had "Academy" status and got its "University" status later. So, the website was called orgma.ru (Orenburg Medical Academy) and after the status changing domain hasn't been changed. I named the file osmu.txt (Orenburg State Medical University), which was my mistake. Now the domain of my university is orgma.ru, but email is orgma@esoo.ru.

**Comment by philipto** [comment]
@BrainRTP Thank you for the clarification. What is typical email address of a student of this university? For example, students of Stanford University use email domains @stanford.edu, thus a student's email there looks like username@stanford.edu. Thus, the filename which corresponds to this domain in this repository is lib/domains/edu/stanford.txt. What is a typical email address of a student in your unversity? Thank you!

**Comment by BrainRTP** [comment]
There is no email for students at our university.

**Comment by philipto** [comment]
@BrainRTP I am sorry, this repository is for email domains where STUDENTS and TEACHERS have their email addresses in. What would you like me to add to the repository, if the students of OSMU do not have email addresses assigned to them by the university? If you wish to add a domain where teachers have their email addresses, what the typical email address of a teacher of the university is?

**Comment by philipto** [comment]
@BrainRTP You might miss my previous comment. Please react. If you experience any troubles, please send an email to support@jetbrains.com.

**Comment by philipto** [comment]
@BrainRTP I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. 

You also can send an email to community-support@jetbrains.com in English or in Russian if you need any further help with educational licenses.

Thank you for the understanding!

**Pull request closed without merging**
