### PR TITLE
https://eduk.org.uk/

### PR DESCRIPTION
**Pull request by nirzaf**
https://eduk.org.uk/information-technology/
https://eduk.org.uk/wp-content/uploads/eduk/information-technology/EDUK-Level-3-Diploma-in-e-commerce.pdf
https://eduk.org.uk/wp-content/uploads/eduk/information-technology/EDUK-Level-4-Diploma-in-Web-Design.pdf
https://eduk.org.uk/wp-content/uploads/eduk/information-technology/EDUK-Level-5-Diploma-in-Web-Design.pdf
https://eduk.org.uk/wp-content/uploads/eduk/EDUK-Student-Registration.pdf

### CODE REVIEW

**Comment by philipto** [comment]
@nirzaf First stage of verification passed, official domain is [eduk.org.uk](https://eduk.org.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@nirzaf Pull request merged. Thank you.

**Comment by nirzaf** [comment]
Thank you @philipto, May I know how long it will take to, allow our students to use their mail Id to claim their free JB license?

**Comment by nirzaf** [comment]
Thank you @philipto, May I know how long it will take to, allow our students to use their mail Id to claim their free JB license?

**Pull request merged**
