### PR TITLE
Added domain tiiamekb.uz

### PR DESCRIPTION
**Pull request by Erkinbek**

### CODE REVIEW

**Comment by philipto** [comment]
@Erkinbek Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Erkinbek You might miss my previous comment. Please react.

**Comment by Erkinbek** [comment]
@philipto 
URL: https://tiiamekb.uz/
It's a new branch of university, still doesn't work completely.

**Comment by philipto** [comment]
@Erkinbek Thank you for the clarification. Pull request merged.

**Comment by Erkinbek** [comment]
@philipto thank you too

**Comment by Mansur-9090** [comment]
[dtpi.txt](https://github.com/JetBrains/swot/files/6072711/dtpi.txt)

**Pull request merged**
