### PR TITLE
Create glnb.txt

### PR DESCRIPTION
**Pull request by vogll**
Secondary school

### CODE REVIEW

**Comment by philipto** [comment]
@vogll I am sorry but this repository does not include secondary schools. You may wish to check Readme to this repository for more details. For secondary schools we suggest to use Community Editions of JetBrains tools. This is why I close this request with no merging. Please add a comment if you need some more details on free community versions or need a specific tool which does not have such a version. Thank you for your understanding!

**Comment by vogll** [comment]
Our school is gymnasium (wiki https://en.wikipedia.org/wiki/Gymnasium_%28school%29). There is more gymnasium listed too. I compare our study program with another type of school listed  and then make request.  Can you reconsider your negative position ?

**Comment by philipto** [comment]
I am sorry for misunderstanding. Usually a school which prepares students for enrolling to a university is called "high school" (comparing to secondary school, previous step, and higher education in a university, next step).  If this is exactly what your gymnasium does, could you please provide a link to a web page on the official gymnasium website, where a long-term IT-related course offered by the gymnasium is described or mentioned? Thank you!

**Comment by philipto** [comment]
@vogll You may miss my previous comment. Could you please answer it? With no answer, I'll have to close the request again.

**Comment by philipto** [comment]
@vogll I am sorry, my previous comment remains unanswered for a while, and I have to close the request again, because I can not satisfy it without the information which I requested in my previous comment. Thank you for your understanding.

**Comment by vogll** [comment]
Hi, 
I send you reply email 8.4.2016  12:35, to address reply0115231ab9fdf32ee07154d172411b1af9b1bb134045397992cf00000001131e587592a169ce08a19a02@reply.github.com. With our study plan. Our study plan is there http://www.glnb.cz/Articles.php?Menu2ID=295&Menu1ID=116. Now I send reply from  github.com form . Email reply address probably doesn't work. Excuse me I haven't experience with github communication.

**Comment by philipto** [comment]
@vogll Thank you for the clarification! You pull request is now merged.

**Comment by vogll** [comment]
Excuse me, but  I still can't create request on your web pages https://www.jetbrains.com/shop/eform/students?_st=19bb7g2nff. Our domain glnb.cz is listed on github. Here is screenshot negative reply from form on your web pages.
jet

**Comment by philipto** [comment]
@vogll I am sorry, we have now a technical issue with a script which uses this repository for license request precessing. Our engineers are looking into it, and I will be back to you as soon as they resolve the issue. I am sorry for the trouble!

**Comment by philipto** [comment]
@vogll It works now. Please try again if you did not request the license successfully yet. Thank you for using the tools!

**Comment by vogll** [comment]
All working "like a (py)charm". Thank you. Licence is allowed to one year. How do I renew it ? Must I before expiry open new request ?

**Comment by philipto** [comment]
@vogll Thank you! You will receive an email message few days before the expiration date, and then you can follow a link in the message to renew the license, if you remain a student. If you are graduated, you can get a special discount after the graduation for recently graduated people.

Also, you can renew your license from your JetBrains account page.

**Pull request merged**
