### PR TITLE
Add Modesto Junior College

### PR DESCRIPTION
**Pull request by DarinDev1000**
Add both domain variants for Modesto Junior College

### CODE REVIEW

**Comment by philipto** [comment]
@DarinDev1000 Please let us know which variant is for what.

**Comment by DarinDev1000** [comment]
They are both for Modesto Junior College. The student.yosemite.edu is the old style (but it still works). They changed the new style to my.yosemite.edu.  They are both for students, I think faculty may be this also.

**Comment by DarinDev1000** [comment]
Would it be better to just do the whole yosemite.edu domain? They own the whole thing.
Do subdomains automatically get included?

**Comment by philipto** [comment]
@DarinDev1000 
> Would it be better to just do the whole yosemite.edu domain? 

No, if other folks share the domain with teachers and students. Otherwise, it does not matter.

> Do subdomains automatically get included?

Yes. Still, I merged your pull request and it added two separate, subdomains which is also fine.

Pull request merged. Thank you!

**Pull request merged**
