### PR TITLE
Create budapestschool.txt

### PR DESCRIPTION
**Pull request by bedomarci**

### CODE REVIEW

**Comment by philipto** [comment]
@bedomarci Please provide us with:
- the school official website URL
- the school street address
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

The school description is too general, thus we need all the details mentioned above. Thank you.

**Comment by bedomarci** [comment]
Hi!


   - http://budapestschool.org/
   - Its a chain, they have many schools. Im working at Budapest School
   P10. Address: Budapest, Pozsonyi út 10, 1137
   - Offering IT related program here:
   https://budapestschool.org/hu/helyszineink/bps_code/
   - Proof of domain: we use the same domain for mails as the official
   website.


*Bedő Marci*


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mentes
a vírusoktól. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by philipto** [comment]
@bedomarci I am sorry, we generally do not add umbrella institutions here. If this is a school network, and all students in the network receive email addresses in this domain, wouldn't you mind to send an email to community-support@jetrbrains.com. It makes sense to discuss special terms on which the students will get their free educational subscriptions. Looking forward to hearing from you. Thank you!

**Comment by philipto** [comment]
@bedomarci Thank you for the clarification made by email. Pull request is merged now.

**Pull request merged**
