### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Leroy-design**

### CODE REVIEW

**Comment by NianwenDan** [comment]
Could you please help me to add our school domain to your JetBrains?

Please see the attachment below. Thank you!

[file.zip](https://github.com/JetBrains/swot/files/5536222/file.zip)

**Comment by Leroy-design** [comment]
come to discord :), i will explain to you
swann#9381

**Comment by NianwenDan** [comment]
> come to discord :), i will explain to you
> swann#9381

OK, so what should I do?

**Comment by Leroy-design** [comment]
send me message on discord it will be more easy to speak, and to explain to you

**Comment by NianwenDan** [comment]
OK, I have sent a request via discord.
Thank you!

**Comment by philipto** [comment]
@Leroy-design I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host campus.academy.fr not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Pull request closed without merging**
