### PR TITLE
Added Pennsylvania Leadership Charter School

### PR DESCRIPTION
**Pull request by Aminsteir**
Added PALCS school

### CODE REVIEW

**Comment by Aminsteir** [comment]
Updated to the official name of the school instead of the abbreviated name.

**Comment by philipto** [comment]
@Aminsteir Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain **stu.palcsmail.org** which you are submitting as an official email domain for the students.

**Comment by Aminsteir** [comment]
The school webpage login for students is here: [www.palcschool.org](https://www.palcschool.org/)
The school information page is located here: [palcs](https://www.palcs.org/)
An image showing that this email is recognized is included below
That should confirm that PALCS uses the stu.palcsmail.org domain
Annotation 2019-04-12 100749

**Comment by philipto** [comment]
@Aminsteir Thank you for the clarification. Pull request merged. 
For the record: also, the proof is at https://support.palcs.org/hc/en-us/requests/new
Thank you!

**Pull request merged**
