### PR TITLE
liepu.edu.lv

### PR DESCRIPTION
**Pull request by kasparsj**

### CODE REVIEW

**Comment by philipto** [comment]
@kasparsj Please provide us with:
- the school official website URL
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@kasparsj You might miss my previous comment. Please react.

**Comment by kasparsj** [comment]
The official website URL is https://liepu.lv, and http://liepu.edu.lv is a redirect to liepu.lv, and all student emails are under liepu.edu.lv domain.

**Comment by philipto** [comment]
@kasparsj Please provide us with a link to a page at the official website which says that "all student emails are under liepu.edu.lv". If there is no such page, please upload a copy of the school internal instruction that confirms it to GitHub as a comment to this request.

**Comment by kasparsj** [comment]
Sorry, I can't find any reference whatsover, maybe because this is a relatively new thing, it was moved from lanet.lv to liepu.edu.lv when the pandemic started. I will just apply for an ISIC instead. Thanks.

**Comment by philipto** [comment]
@kasparsj Thank you very much for the clarification and renewal with your ISIC card. It's a very good and simple way to proceed. I am sorry, I have to close the request as for now. Thank you!

**Pull request closed without merging**
