### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by danielgomes92**
Upload the file, following the guidance, to include the name of the university.

### CODE REVIEW

**Comment by philipto** [comment]
@danielgomes92 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@danielgomes92 You might miss my previous comment. Please react.

**Comment by danielgomes92** [comment]
Hello @philipto ! How you doing ? i hope so.
My English are not good, but i will try to give you, what you need.
Sorry for the long time to answered back, I was involved in work projects and 
college exams and and didn't see your message.
Thank you for your feedback, now I can use and study along with the packages.

Below is proof that they really belong to Candido Mendes University, here in Brazil - Rio de Janeiro.

Screenshot_1

**Comment by danielgomes92** [comment]
This university is different, because I study at home, I don't need to go in person. This is the reason why there is not so much evidence, it is necessary to request a lot of information. So, I just access the portal, study, watch recorded classes and take tests.

basically (and unfortunately) it's everything that appears in the image.

image

**Comment by philipto** [comment]
@danielgomes92  Thank you for the clarifications. Pull request merged.

**Pull request merged**
