### PR TITLE
Create rudn.txt

### PR DESCRIPTION
**Pull request by AJIEKCEY**
RUDN University

### CODE REVIEW

**Comment by philipto** [comment]
@AJIEKCEY Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by AJIEKCEY** [comment]
Hello!
I hope these screens will help.

[image: Screenshot_32.png]
[image: Screenshot_33.png]

С уважением Сергей.


пт, 27 июл. 2018 г. в 1:15, Philip Torchinsky <notifications@github.com>:

**Comment by philipto** [comment]
@AJIEKCEY I am sorry, they will not: GitHub removes attachments sent by email as a comment. Thus, no screenshot are available in your comment text. Please give us a link to screenshots or upload them via the web interface. Thank you!

**Comment by AJIEKCEY** [comment]
Something like this?

https://drive.google.com/open?id=0B1VDZvFnLcFua3g4Z0FPVF9xcjRRaWp6NUNpZnBmTy1wMGdv
https://drive.google.com/file/d/0B1VDZvFnLcFuTUFMVzZvblFaSHQwVVVMZ0FyLWFWdHNuaHBj

Thank you for your time!

С уважением Сергей.


вт, 31 июл. 2018 г. в 21:00, Philip Torchinsky <notifications@github.com>:

**Comment by philipto** [comment]
@AJIEKCEY Yes, exactly, thank you! Pull request merged. Thank you!

**Pull request merged**
