### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Nexusqc**
https://phs.petalschools.com/departments/career-tech-education <= 2 year I.T program

### CODE REVIEW

**Comment by philipto** [comment]
@Nexusqc lib/domains/com/petalschools.group.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Nexusqc Please clarify what the students' school-assigned email addresses end with? Do they end with @petalschools.com? Thank you.

**Comment by Mr-Baguetter** [comment]
> @Nexusqc Please clarify what the students' school-assigned email addresses end with? Do they end with @petalschools.com? Thank you.

The student accounts end with @petalstudents.com

@petalschools.com is the teacher email

**Comment by Nexusqc** [comment]
> @Nexusqc Please clarify what the students' school-assigned email addresses end with? Do they end with @petalschools.com? Thank you.

Student accounts end with @petalstudents.com

@petalschools is the teacher domain

**Comment by philipto** [comment]
@Nexusqc lib/domains/com/petalschools.group.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Pull request closed without merging**
