### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by bobderf**
Blount County

### CODE REVIEW

**Comment by philipto** [comment]
@bobderf Please provide us with:
* the school official website URL
* the school street address, including city and country
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@bobderf You might miss my previous comment. Please react.

**Comment by bobderf** [comment]
SorryOn Sat, Dec 14, 2024 at 6:02 AM Philip Torchinsky ***@***.***> wrote:
@bobderf You might miss my previous comment. Please react.

**Comment by bobderf** [comment]
On Thu, Dec 12, 2024 at 5:37 AM Philip Torchinsky ***@***.***> wrote:
@bobderf Please provide us with:
the school official website URL = https://heritagehigh.blountk12.org/the school street address, including city and country = 3741 E Lamar Alexander Pkwy, Maryville, TN 37804a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. I’m not sure what you mean I am a student ?

**Comment by philipto** [comment]
@bobderf  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
