### PR TITLE
Create @student-sornas.fr

### PR DESCRIPTION
**Pull request by Arys02**
add email for student at EDTA Sornas

### CODE REVIEW

**Comment by philipto** [comment]
@Arys02 Please provide us with a proof, which shows that the school recognizes the domain etudiant-sornas.fr that you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Arys02 Please make sure that the filename is correct. The file lib/domains/fr/etudiant-sornas.txt  represents a domain etudiant-sornas.fr, which is different from student-sornas.fr. Please comment here which domain the students use.

**Comment by Arys02** [comment]
Oh my, sorry
the right demain is etudiant-sornas.fr, i just mixed up with english while writing the commit message.

**Comment by philipto** [comment]
@Arys02 Please provide us with a proof, which shows that the school recognizes the domain etudiant-sornas.fr that you are submitting as an official email domain for the students.

You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@Arys02 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please create a new request or reopen this one and comment if you have an update regarding the aforementioned issue. 

You can add both files to the same single request.

Thank you for your understanding!

**Pull request closed without merging**
