### PR TITLE
Trinity College Added

### PR DESCRIPTION
**Pull request by DipendraDLS**

### CODE REVIEW

**Comment by DipendraDLS** [comment]
Here is the proof for the college domain 
https://www.trinity.edu.np/ 
hope you will add this college as well. Thank You!

**Comment by philipto** [comment]
@DipendraDLS First stage of verification passed, official domain is [trinity.edu.np](https://trinity.edu.np) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by DipendraDLS** [comment]
Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by philipto** [comment]
@DipendraDLS Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
