### PR TITLE
Create jbnuu.txt

### PR DESCRIPTION
**Pull request by MirAhmad-dev**

### CODE REVIEW

**Comment by philipto** [comment]
@MirAhmad-dev I am sorry, the official website of the university says that there is only one department: a department of psychology. Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. It can be computer science, software engineering, math, physics, etc.

**Comment by philipto** [comment]
@MirAhmad-dev Please do not create many pull requests, it's not necessary. Your request will be processed within **three business days**.

**Comment by philipto** [comment]
@MirAhmad-dev You might miss my previous comment. Please reply.

**Comment by udev-21** [comment]
> @MirAhmad-dev I am sorry, the official website of the university says that there is only one department: a department of psychology. Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. It can be computer science, software engineering, math, physics, etc.

hi sir. There is so many faculties include "Information systems and security", "Applied Mathematics" etc in our University

**Comment by MirAhmad-dev** [comment]
There is so many faculties include "Information systems and security", "Applied Mathematics" etc in our University.http://jbnuu.uz/subcategory.php?id=8 From: Philip TorchinskySent: 23 ноября 2020 г. 17:18To: JetBrains/swotCc: MirAhmad-dev; MentionSubject: Re: [JetBrains/swot] Create jbnuu.txt (#9972) @MirAhmad-dev You might miss my previous comment. Please reply.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by philipto** [comment]
@MirAhmad-dev Thank you for the clarification! I found necessary information. The pull request is merged. You can start requesting your free licenses for JetBrains tools at https://www.jetbrains.com/shop/eform/students in about 30 minutes. Thank you!

**Comment by udev-21** [comment]
> @MirAhmad-dev Thank you for the clarification! I found necessary information. The pull request is merged. You can start requesting your free licenses for JetBrains tools at https://www.jetbrains.com/shop/eform/students in about 30 minutes. Thank you!

Thanks a lot sir 😃

**Pull request merged**
