### PR TITLE
added domains for Istituto Tecnico Tecnologico Alessandro Volta Perugia

### PR DESCRIPTION
**Pull request by amendola-scuola**
Hi, please add my Institute, this is the main domain:
www.avoltapg.edu.it
and this is the domain we use for email addresses:
www.risikamente.it
Here you can see the 5 years course in IT and Telecommunications:
https://www.avoltapg.edu.it/pagine/informatica-e-telecomunicazioni

Thank you for your time!

### CODE REVIEW

**Comment by philipto** [comment]
@amendola-scuola Thank you for the request. Could you please clarify the following:
1. Do you need to add the domain avoltapg.edu.it to the repository? If you don't use this domain for email addresses, you don't actually need to add it.
2. Please provide us with a proof, which shows that the school recognizes the domain **risikamente.it** that you are submitting as an official email domain for the students.

You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@amendola-scuola You might miss my previous comment. Please react.

**Comment by amendola-scuola** [comment]
> @amendola-scuola Thank you for the request. Could you please clarify the following:
> 
> 1. Do you need to add the domain avoltapg.edu.it to the repository? If you don't use this domain for email addresses, you don't actually need to add it.
> 2. Please provide us with a proof, which shows that the school recognizes the domain **risikamente.it** that you are submitting as an official email domain for the students.
> 
> You can provide us with any of the following:
> 
> * A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
> * An URL of a page at the official school website that says that students use this email domain
> * A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
> * A WHOIS data that link the email domain to the school somehow
> * A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
> * Anything else that can prove this fact in similar way, i.e. can be verified independently.

Hi, sorry for the delay, 
for n.1 it is possible that in the future we will switch email addresses on the main domain, if it's a problem to add it right away I'll remove it from the pull request,
for n.2 unfortunately all I can provide it's a whois record, from the screenshot you can see that the registrant organization and addresses are the same, I hope it's enough:

Screenshot_20231007-064118
Screenshot_20231007-064224

Thank you for your time, regards

**Comment by philipto** [comment]
@amendola-scuola  Thank you for the clarifications. Pull request merged.

**Pull request merged**
