### PR TITLE
Adding School Email Address to list of domains

### PR DESCRIPTION
**Pull request by Aryan-401**

### CODE REVIEW

**Comment by elisabettina** [comment]
[s.hakmistelbach.txt](https://github.com/JetBrains/swot/files/4812049/s.hakmistelbach.txt)

**Comment by elisabettina** [comment]
The domain students AND teachers use at our school for „official“ emails is      s.hakmistelbach.ac.at
This email-adress is used e.g. for Office 365 school-accounts.

Our official website url ist hakmistelbach.ac.at   WITHOUT the „s.“

**Comment by philipto** [comment]
@elisabettina Your request was answered by email, thank you!

**Comment by philipto** [comment]
@Aryan-401 Thank you for changes to #8521. I am closing #8521 as a duplicate to this request. However, we still need some more info from you. Please provide us with:
- the school official website URL, if different from the domain you are submitting
- the school physical address (which city and country the school is located in)
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

Thank you.

**Comment by elisabettina** [comment]
Hi Philip,

 

here are the requested informations:

 

 

www.hakmistelbach.ac.at <http://www.hakmistelbach.ac.at> 

 

Brennerweg 8

2130 Mistelbach

Austria

 

http://www.hakmistelbach.ac.at/ausbildung/hak_digbiz.asp            (5 years curriculum for HAK Digital Business = IT curriculum)

 

 

Screenshot of Microsoft 365 Admin Center where you can find some students and me with email-domain   s.hakmistelbach.ac.at

 



 

 

Thanks an best regards,

Bettina Haushofer

 

 

 

Von: Philip Torchinsky <notifications@github.com> 
Gesendet: Montag, 22. Juni 2020 13:49
An: JetBrains/swot <swot@noreply.github.com>
Cc: elisabettina <bettina.haushofer@gmail.com>; Mention mention@noreply.github.com <mailto:mention@noreply.github.com> 


Betreff: Re: [JetBrains/swot] Adding School Email Address to list of domains (#8531)

 

@Aryan-401 <https://github.com/Aryan-401>  Thank you for changes to #8521 <https://github.com/JetBrains/swot/pull/8521> . I am closing #8521 <https://github.com/JetBrains/swot/pull/8521>  as a duplicate to this request. However, we still need some more info from you. Please provide us with:

*	the school official website URL, if different from the domain you are submitting
*	the school physical address (which city and country the school is located in)
*	an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
*	an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

Thank you.

**Comment by Aryan-401** [comment]
Oh hey, Philip I just saw this mail after the closed case so sorry for the
reply on that email.

Anyway, here the details you requested:
School Website:
http://www.themillenniumschools.com/tmsnoida41/

School Physical Address:
D-108, Aghapur, Sector 41,
Noida, Uttar Pradesh
110032

URL of IT curriculum: Hey I couldn't find one of the School website, but
our school is a recognized CBSE School and provides all subjects which the
board (CBSE) allows. One of which is Informatics Practices (CBSE Subject
Code:#065) and have provided its Curriculum -
http://cbseacademic.nic.in/web_material/CurriculumMain21/SrSecondary/Informatics_Practices_Sr.Sec_2020-21.pdf
(This is only for Grade 11 and 12)

Proof of School recognition of Email domain:
Have attached two images, one is the Proof that me and my peers also use
the domain, and the second screenshot showing that our Senior Coordinator
uses the same domain.
Note: All the names without a title below them are students, also PGT
stands for Post Graduate Teacher.


I hope this helps!
-Aryan

**Comment by philipto** [comment]
@Aryan-401 Thank you for the details! Could you please attach the images directly via GitHub web interface, because GitHub strips it out if you send them by e-mail? Thank you!

**Comment by Aryan-401** [comment]
--- Copied text from earlier e-mail ---

Oh hey, Philip I just saw this mail after the closed case so sorry for the reply on that email.

Anyway, here the details you requested:
School Website:
http://www.themillenniumschools.com/tmsnoida41/

School Physical Address: 
D-108, Aghapur, Sector 41,
Noida, Uttar Pradesh, India
110032

URL of IT curriculum: Hey I couldn't find one of the School website, but our school is a recognized CBSE School and provides all subjects which the board (CBSE) allows. One of which is Informatics Practices (CBSE Subject Code:#065) and have provided its Curriculum -  http://cbseacademic.nic.in/web_material/CurriculumMain21/SrSecondary/Informatics_Practices_Sr.Sec_2020-21.pdf (This is only for Grade 11 and 12)

Proof of School recognition of Email domain:
Have attached two images, one is the Proof that me and my peers also use the domain, and the second screenshot showing that our Senior Coordinator uses the same domain.
Note: All the names without a title below them are students, also PGT stands for Post Graduate Teacher.


Hope this works for you
-Aryan
Image1
Image2

**Comment by Aryan-401** [comment]
Hey Philip,

Just wondering about the progress since no emails during thr lat 24 hours.
Has there been any issue?

- Aryan Garg

**Comment by philipto** [comment]
@Aryan-401 Thank you for the clarification. Pull request merged.

FTR: additional proof of the domain ownership and authenticity of the proofs above is at http://www.themillenniumschools.com/tmsnoida41/news/consilium-mun-2017

**Pull request merged**
