### PR TITLE
Create fh-campuswien

### PR DESCRIPTION
**Pull request by maia**
Adding the "FH Campus Wien - University of Applied Sciences"
Official website (english version): https://www.fh-campuswien.ac.at/en/

### CODE REVIEW

**Comment by philipto** [comment]
@maia Please rename lib/domains/at/ac/fh-campuswien to lib/domains/at/ac/fh-campuswien.txt
Thank you.

**Comment by maia** [comment]
@philipto I renamed the file as requested, thanks for the note!

**Comment by philipto** [comment]
@maia Thank you for the update! Pull request merged.

**Comment by maia** [comment]
@philipto much appreciated!

**Pull request merged**
