### PR TITLE
Adding a file to JetBrains SWOT for a student license request

### PR DESCRIPTION
**Pull request by cristianobattini**

### CODE REVIEW

**Comment by philipto** [comment]
@cristianobattini The first verification stage is complete: the official domain for  **ISIS E MATTEI** is [www.isismattei.edu.it](https://www.isismattei.edu.it), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.isismattei.edu.it/index.php/l-istituto/segreterie

**Comment by cristianobattini** [comment]
thanks!

**Comment by philipto** [comment]
@cristianobattini The first verification stage is complete: the official domain for  **ISIS E MATTEI** is [www.isismattei.edu.it](https://www.isismattei.edu.it), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.isismattei.edu.it/index.php/l-istituto/segreterie

**Comment by philipto** [comment]
@cristianobattini Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by cristianobattini** [comment]
Thanks!

**Pull request merged**
