### PR TITLE
Create educred.txt

### PR DESCRIPTION
**Pull request by valentinceaprazaru**
Added the CRED - Curriculum relevant, educație deschisă pentru toți

### CODE REVIEW

**Comment by valentinceaprazaru** [comment]
@philipto Should i do anything else on this Pull Request?

**Comment by philipto** [comment]
@valentinceaprazaru I am sorry, this organization seems to be more like online educational platform, rather than a university or a college. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and this organization is eligible. Please tell us more about the organization, and which eligibility criteria it fits.

Thank you.

**Comment by philipto** [comment]
@valentinceaprazaru You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@valentinceaprazaru I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
