### PR TITLE
Campus Digital FP

### PR DESCRIPTION
**Pull request by DanMarBar**

### CODE REVIEW

**Comment by DanMarBar** [comment]
Campus Digital FP

**Comment by philipto** [comment]
@DanMarBar First stage of verification passed, official domain for **Campus Digital FP** is [campusdigitalfp.com](https://campusdigitalfp.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by DanMarBar** [comment]
Ok, thank you for your patience and trust!

**Comment by philipto** [comment]
@DanMarBar Thank you for your patience while waiting for a review and processing your request. Pull request merged. Please start applying for JetBrains educational subscription at https://www.jetbrains.com/shop/eform/students **in an hour, to allow the changes to propagate through JetBrains systems**.

**Pull request merged**
