### PR TITLE
add domain ames.edu.vn

### PR DESCRIPTION
**Pull request by nhanames**

### CODE REVIEW

**Comment by philipto** [comment]
@nhanames AMES is a language school. I don't see any reason for it to use JetBrains tools for teaching, because it does not teach programming. Why do you wish to have this domain added to this repository?

**Comment by philipto** [comment]
@nhanames You might miss my previous comment. Please react.

**Comment by nhanames** [comment]
> @nhanames You might miss my previous comment. Please react.

Dear @philipto, You right ! AMES is a language school. i Submit domain ames.edu.vn because. AMES is Mother Company -  AMES Training Joint Stock Company. All web using this domain for email company.
Beside teach about language, we also teach about programing. You can see another website: [](https://www.aptech-danang.edu.vn). Softech is child of AMES.
I hope, you can approe ! Thanks so much !

**Comment by philipto** [comment]
@nhanames Thank you for the clarification. We'll consider this request, but I cannot approve it right away. The school does not provide long-term courses now, thus it does not qualify for this repository. Please feel free to request an extended trial version by email to sales@jetbrains.com, **or ask your teachers** to request suitable free subscriptions via https://www.jetbrains.com/community/education/#courses

Thank you for your understanding!

**Pull request closed without merging**
