### PR TITLE
Added leanderisd and roundrock isd

### PR DESCRIPTION
**Pull request by jspspike**

### CODE REVIEW

**Comment by jspspike** [comment]
Vandegrift High School Computer Science Program: https://csvhs.leanderisd.org/goodreau/

**Comment by jspspike** [comment]
@philipto Is this enough information?

**Comment by ChrisMcLain** [comment]
Round Rock ISD Comp Sci courses are listed in their official course catalog: which can be viewed at https://drive.google.com/file/d/0ByDbfMafTyNdeHo0V1FFVHhPcmM/view 

This course catalog can be accessed from any of the district's school websites. Here is an example (click course catalog) https://rrhs.roundrockisd.org/students/

**Comment by philipto** [comment]
@jspspike @ChrisMcLain Thank you for the details! Pull request merged.

**Pull request merged**
