### PR TITLE
Add github-action to build and release swot.txt

### PR DESCRIPTION
**Pull request by zhangt2333**
Hi, thanks to this repo, it saved my time collecting educational emails.

It's a lightweight and convenient library for developers, but I found it non-user-friendly to read or get the list of educational emails.

In this PR, I create a Github Action to build and run `src/swot/Compiler.kt` for each commit, and then release the output `out/artifacts/swot.txt` on Github Release.

Base on it, the user can conveniently download (or write code to download) the `swot.txt` file from the page of Github Release. (an example is the [following](https://github.com/zhangt2333/swot/releases))

Note that I name the release `latest` (The new one will overwrite the old one), because I have observed that your repo has a lot of commits and it's not a good idea to create releases for every commit (unless the old release will be deleted).

You can give me any feedback.

### CODE REVIEW

**Comment by philipto** [comment]
@zhangt2333 .github/workflows/release.yml: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by zhangt2333** [comment]
@philipto 

Hi, your reply looks like a robot. Can you read my PR description?

If this repo does not accept suggestions other than adding educational email, I will close this PR.

**Comment by philipto** [comment]
@zhangt2333 .github/workflows/release.yml: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@zhangt2333 Thank you for your suggestion. We usually do not accept any suggestions for the code here, just for the content of the email domains list. I will pass your suggestion to the respective team, and they will decide on the request. 

It may take a while because maintaining the email domains list for issuing free licenses for JetBrains tools is a priority.

Thank you for your understanding.

**Comment by zhangt2333** [comment]
@philipto ok. Thanks for your reply.

**Comment by philipto** [comment]
@zhangt2333 .github/workflows/release.yml: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@zhangt2333 .github/workflows/release.yml: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Pull request merged**
