### PR TITLE
Add Gewerbliche und Hauswirtschaftlich-Sozialpflegerische Schulen Emmendingen

### PR DESCRIPTION
**Pull request by FF03de**
## Name of School
Gewerbliche und Hauswirtschaftlich-Sozialpflegerische Schulen Emmendingen

## Domain
ghsede.onmicrosoft.com

## Users
The users will be students 

## Type of school
GHSE is a High School

[ghsede.txt](https://github.com/JetBrains/swot/files/7810231/ghsede.txt)

### CODE REVIEW

**Comment by philipto** [comment]
@FF03de lib/domains/de/GHSE: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@FF03de Your request had an extra item that is not representing a domain, because spaces cannot be part of a domain name.
I removed an incorrect item from the request. With regard to the email domain ghsede.onmicrosoft.com, please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you.

**Comment by FF03de** [comment]
image
image

Unfortunately the school can not give me more evidence. The evidence applies to the entire school. The secretariat will also be able to confirm this upon request.

- the school official website URL: https://www.ghse.de/

- the school street address, including city and country: Gewerbliche und Hauswirtschaftlich-Sozialpflegerische Schulen Emmendingen

Jahnstr. 12-14
79312 Emmendingen
Germany

- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: https://www.ghse.de/schularten/vollzeitschularten/technisches-gymnasium/tg-informationstechnik-2/

**Comment by philipto** [comment]
@FF03de Thank you very much for the clarification. Pull request merged.

**Comment by FF03de** [comment]
@philipto  Thank you for Merging

**Pull request merged**
