### PR TITLE
Stipendium

### PR DESCRIPTION
**Pull request by michal-drozd**

### CODE REVIEW

**Comment by michal-drozd** [comment]
Hi,

What is going on with our request ? Should we provide some additional informations ?

**Comment by philipto** [comment]
@michal-drozd I am sorry for a delay with processing your request. Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university.
The organization does not look like an educational institution, it looks more like research organization instead.

**Comment by philipto** [comment]
@michal-drozd You might miss my previous comment. Please reply.

**Comment by philipto** [comment]
@michal-drozd I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
