### PR TITLE
Create enspy-uy1.txt

### PR DESCRIPTION
**Pull request by menraromial**
ADD NATIONAL ADVANCED SCHOOL OF ENGINEERING

### CODE REVIEW

**Comment by menraromial** [comment]
ADD NATIONAL ADVANCED SCHOOL OF ENGINEERING

**Comment by philipto** [comment]
@menraromial Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by menraromial** [comment]
@philipto 

- **website** : [POLYTECHNIQUE YAOUNDE](https://polytechnique.cm/)
- **Address** : Pharmacie EMIA, Rte de Melen, Yaoundé
-  **website** : [POLYTECHNIQUE YAOUNDE](https://polytechnique.cm/)
-
Transcript

**Comment by philipto** [comment]
@menraromial Thank you for the additional information! Regrettably, it's impossible to add this domain to the repository. The problems are:
1) The address Pharmacie EMIA, Rte de Melen, Yaoundé does not seem to belong to a school, it belongs to a Pharmacy.
2) The URL https://polytechnique.cm/ leads to a fraudulent website working as a doorway to some fishing sites.
3) The document that you have attached to this request does not prove that the domain **enspy-uy1.cm** is recognized as official by the university.

Considering all the above, I have to close this request without merging.

Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

**Pull request closed without merging**
