### PR TITLE
Al Azhar University

### PR DESCRIPTION
**Pull request by AhmedHamdyAmeen**

### CODE REVIEW

**Comment by AhmedHamdyAmeen** [comment]
Al Azhar University

**Comment by AhmedHamdyAmeen** [comment]
#23721 add Al Azhar University

**Comment by philipto** [comment]
@AhmedHamdyAmeen Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.** Thank you.

**Comment by AhmedHamdyAmeen** [comment]
Hello @philipto, Thank you for your support.

**Pull request merged**
