### PR TITLE
Add i-fr domain

### PR DESCRIPTION
**Pull request by LeRouteur**

### CODE REVIEW

**Comment by philipto** [comment]
@LeRouteur Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by LeRouteur** [comment]
@philipto Hello,

- URL of the website : https://www.epai-ict.ch/new

- Well, I cannot provide you an URL for a course, because the school don't provide any course on his main page. Everything is located on moodle.fri-tic.ch, maybe you can check some courses here.

- I need to send a mail to one of my teacher, I'll be back to you asap.

Best regards.

**Comment by philipto** [comment]
@LeRouteur Thank you for your prompt reply. I am looking forward to seeing an update from you!

**Comment by philipto** [comment]
@LeRouteur I have to close this request without merging, because you requested to add a non-existent domain to this repository: `` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for understanding!

**Pull request closed without merging**
