### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by PepperEngineGit**
Adding the IPSF Belgium school.

### CODE REVIEW

**Comment by philipto** [comment]
@PepperEngineGit First stage of verification passed, official domain for **Institut Provincial de Formation Sociale** is [ipfs.province.namur.be](https://ipfs.province.namur.be) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@PepperEngineGit Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by PepperEngineGit** [comment]
Hi.

Here is. 

Coding help teachers to have bests tools by implementing.

https://www.ipfs.be/formations/bachelier-en-sciences-administratives-et-en-gestion-publique/

**Comment by philipto** [comment]
@PepperEngineGit  Thank you for the clarifications. Pull request merged.

**Pull request merged**
