### PR TITLE
add cloud campus academy

### PR DESCRIPTION
**Pull request by diawara24**
I add my training center to your repository to allow me and the student of my class to have a jetBrains license.
thank you

### CODE REVIEW

**Comment by philipto** [comment]
@diawara24 Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@diawara24 You might miss my previous comment. Please react.

**Comment by diawara24** [comment]
Hello @philipto, thank your for your replay.
I send you the informations that i have actualy. for the moment I don't have received the proof of email.

-  website URL: [](https://cloud-campus.fr/)
- Address: 27 Rue du Chemin Vert, 75011 Paris, France

**Comment by philipto** [comment]
@diawara24 Thank you very much for the clarification. Pull request merged.

**Comment by diawara24** [comment]
@philipto thanks to you too,
Good for you.

**Pull request merged**
