### PR TITLE
Add Flagler Palm Coast High School

### PR DESCRIPTION
**Pull request by c0r3yz**
Official Website: https://www.fpcbulldogs.com/
Computer Science Discoveries Course: https://www.fpcbulldogs.com/academics/course-descriptions

### CODE REVIEW

**Comment by philipto** [comment]
@c0r3yz First stage of verification passed, official domain is [twitter.com](https://twitter.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://twitter.com/rodneyhill2024

**Comment by philipto** [comment]
@c0r3yz Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by coreysherman-accesso** [comment]
I am working to see if I can find more direct proof, but I can show that the domain is registered to Flagler Schools (as seen in the nameservers) https://www.whois.com/whois/flaglercps.org

Flagler Schools is the county school district that Flagler Palm Coast High School belongs to: https://www.flaglerschools.com/

At the bottom of this page, you can see Flagler Palm Coast High School: https://www.flaglerschools.com/about-us/schools

Does that help with verification? If not, can you give an example of what more proof you are looking for?

**Comment by coreysherman-accesso** [comment]
Here is a link to an article for Flagler Palm Coast High School's hosted Virtual Teen Town Hall where registration is required and it lists the Student Liaison's emails: http://www.focusonflagleryouth.com/teen-town-hall.html

**Comment by coreysherman-accesso** [comment]
Here is a similar town hall announced by the official Flagler Palm Coast High School twitter account showing the student liaison contacts: https://twitter.com/FPCHS/status/1598358182707007492

**Comment by philipto** [comment]
@c0r3yz  Thank you for the clarifications. Pull request merged.

**Comment by coreysherman-accesso** [comment]
Thank you for your help!

**Pull request merged**
