### PR TITLE
Add CIFP A Carballeira

### PR DESCRIPTION
**Pull request by longui19**
Add CIFP A Carballeira domain

### CODE REVIEW

**Comment by philipto** [comment]
@longui19 Could you please:
1) rename lib/domains/es/acarballeira to lib/domains/es/acarballeira.txt
2) provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school.
Thank you.

**Comment by longui19** [comment]
Hello, 
I have just renamed the file (sorry for the mistake)
You can get the info about the course in the following link:
http://www.edu.xunta.es/fp/ciclo/SIFC03

It´s a 2 year course called "Desenvolvemento de aplicacións web" (Web applications development), at the bottom you can see the colleges that are offering the course, you'll see our school in the list "CIFP A Carballeira-Marcos Valcárcel"

Than you

**Comment by philipto** [comment]
@longui19 Thank you for the renaming! Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school.
Thank you.

**Comment by philipto** [comment]
@longui19 Pull request merged. Thank you!

**Pull request merged**
