### PR TITLE
Create bict-edu

### PR DESCRIPTION
**Pull request by buche2**
BiCT AG, Die Berufsbildner
New separate domain, especially for the apprentices

### CODE REVIEW

**Comment by philipto** [comment]
@buche2 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@buche2 You might miss my previous comment. Please react.

**Comment by buche2** [comment]
@philipto - hi Philip, 

image

I work for BiCT AG as a vocational trainer. About 2.5 years ago, I submitted the request for the domain bict.ch, which was also approved. For security reasons, we now want to let the learners run on a new domain - bict-edu.ch. So I will send you a screenshot for the domain as proof.

I hope this is enough proof for you.
Thanks for sharing and have a nice weekend.

Warm greetings
Enrico

**Comment by philipto** [comment]
@buche2  Thank you for the clarifications. Pull request merged.

**Comment by buche2** [comment]
@philipto 
Thank you for your release. By the way, our trainees and I think the IDEs are great. Have a nice day
Best regards
Enrico

**Pull request merged**
