### PR TITLE
Added my schools domain.

### PR DESCRIPTION
**Pull request by DudeTux42**

### CODE REVIEW

**Comment by philipto** [comment]
@DudeTux42 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by DudeTux42** [comment]
## Official Website
https://www.bbw-abensberg.de

## Address of my school
Regensburger Straße 60 93326 Abensberg Germany

## URL of the website with the IT Course
https://www.bbw-abensberg.de/informations-kommunikationstechnik

### Proof that the domain is recognized by the school
Is a document with the stamp of the school sufficiant? So i could make a document and go to my schools office and let them stamp it?

**Comment by philipto** [comment]
@DudeTux42 Thank you! Yes, any of the following is sufficient, including a paper you mentioned with a stamp:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@DudeTux42 test123.txt I am sorry, I have to close the request without merging, because you made a mistake in a request and did not specify any filepath. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and make a new correct request. Thank you for your understanding!

**Pull request closed without merging**
