### PR TITLE
Add Akademia Muzyczna im. Ignacego Jana Paderewskiego w Poznaniu

### PR DESCRIPTION
**Pull request by DanyloBobrivnyk**

### CODE REVIEW

**Comment by philipto** [comment]
@DanyloBobrivnyk First stage of verification passed, official domain for **Akademia Muzyczna im. Ignacego Jana Paderewskiego w Poznaniu** is [students.amuz.edu.pl](https://students.amuz.edu.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@DanyloBobrivnyk Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by DanyloBobrivnyk** [comment]
> @DanyloBobrivnyk Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

Hi! Under this link you may find a list of lectures:
https://amuz.edu.pl/wp-content/uploads/OGOLNOUCZELNIANA-LISTA-FAKULTETOW-2023-2024.pdf
For ex. 'Podstawy Programowania' and 'Muzyka algorytmiczma'.

**Comment by philipto** [comment]
@DanyloBobrivnyk Thank you for the clarification! The program you suggested to check says that, for example, a subject "Podstawy Programowania" takes 30 hours to study. It is clearly much less than a year.

Therefore, I must conclude that the email domain of this school does not qualify to be added to the repository, according [the rules](https://github.com/JetBrains/swot#which-educational-institutions-can-be-added-to-the-repository).

I have to close the request without merging. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Pull request closed without merging**
