### PR TITLE
Create tnw.txt

### PR DESCRIPTION
**Pull request by leimeiian**

### CODE REVIEW

**Comment by philipto** [comment]
@leimeiian First stage of verification passed, official domain is [tnw.ac.th](https://tnw.ac.th) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@leimeiian Regrettably, this request has signs of fraud. I have to close it without merging. If you are a student of this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by leimeiian** [comment]
@philipto Thank you for your reply sir !
our school website is http://www.tnw.ac.th and http://testtnw.tnw.in.th, but only @tnw.ac.th used as email address.
this is the domain's WHOIS data.

image

this is the contact details and address of our school, you can find them here http://testtnw.tnw.in.th/contact
image

**Comment by philipto** [comment]
@leimeiian Thank you very much for the clarification. Pull request merged.

**Pull request merged**
