### PR TITLE
Create crea-inseec.txt

### PR DESCRIPTION
**Pull request by gibtmirdas**
https://www.creageneve.com/en
https://www.creageneve.com/en/bachelor/web-and-app-development/

### CODE REVIEW

**Comment by philipto** [comment]
@gibtmirdas Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@gibtmirdas You might miss my previous comment. Please reply.

**Comment by philipto** [comment]
@gibtmirdas I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Comment by Khodl** [comment]
Hello @pavelsher,

Please find attached a screenshot of the intranet.

You can also see on the website of CREA (https://www.creageneve.com) that it's now part of the group INSEEC (https://www.inseec.com), which is why students have an address @crea-inseec.com

screen shot 2018-03-14 at 22 20 53

**Pull request closed without merging**
