### PR TITLE
Create ufzg.hr

### PR DESCRIPTION
**Pull request by mdumancic**

### CODE REVIEW

**Comment by mdumancic** [comment]
Welcome!

**Comment by philipto** [comment]
@mdumancic lib/domains/hr/ufzg.hr: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@mdumancic lib/domains/hr/ufzg.hr: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@mdumancic lib/domains/hr/ufzg.hr: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@mdumancic lib/domains/hr/ufzg.hr: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@mdumancic Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by MarioDumancic2020** [comment]
http://www.ufzg.hr
https://www.ufzg.unizg.hr/wp-content/uploads/2020/03/US903_INF.pdf
http://2co2.ufzg.hr

**Comment by philipto** [comment]
@mdumancic Thank you for the clarification. Pull request merged.

**Pull request merged**
