### PR TITLE
Added school name

### PR DESCRIPTION
**Pull request by flaxeneel2**
Hi, I wanted to apply for the Jetbrain educational license.

### CODE REVIEW

**Comment by philipto** [comment]
@flaxeneel2 Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by flaxeneel2** [comment]
1. https://www.cosmopolitanschool.de
2.

**Comment by flaxeneel2** [comment]
1. https://www.cosmopolitanschool.de
2. Rückerstraße 9, 10119 Berlin, Germany
3. Link: https://www.cosmopolitanschool.de/secondary-school/information-technology-it/
4. Sorry, if you would go to http://cosmopolitanschool.eu/ (the domain used for student emails) then it would say the site has moved, however it is still owned be the school, just that there are only student emails with that domain, all the teacher emails are with the .de domain. To provide proof i can show an email to me from a teacher who has the correct domain.
image

(My name is there in the licensing in one of my github repos which was made long ago so i believe that should be sufficient to show that that is my actual name. Two repos having it are haste-server-express and aio-java)

**Comment by philipto** [comment]
@flaxeneel2 Thank you for the clarification. Pull request merged.

**Pull request merged**
