### PR TITLE
added BWV-Aachen

### PR DESCRIPTION
**Pull request by marcelweitzel**

### CODE REVIEW

**Comment by ProgrammerPeter2** [comment]
Teszt

**Comment by philipto** [comment]
@marcelweitzel Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@marcelweitzel You might miss my previous comment. Please react.

**Comment by marcelweitzel** [comment]
Hi, i have notified my school for the proof and am waiting for their Response. I can provide the first 2 requests already, if you want

**Comment by marcelweitzel** [comment]
Denic Response
My Teacher has supplied me with this Screenshot. It contains his View of the DENIC-WhoIs request. Denic is the registry of the .de Top-Level-Domain.

**Comment by marcelweitzel** [comment]
the schools official homepage is this: https://bwv-aachen.de/home.html
here is a list of the it-courses the school offers: https://bwv-aachen.de/bildungsangebote/berufsschulen/it-berufe.html

**Comment by philipto** [comment]
@marcelweitzel Pull request merged. Thank you!

**Pull request merged**
