### PR TITLE
Create nsbm.lk

### PR DESCRIPTION
**Pull request by MRGitHub94**
NSBM Green University (National School of Business Management) has been added to the list

### CODE REVIEW

**Comment by philipto** [comment]
@MRGitHub94 Please rename lib/domains/lk/nsbm.lk to lib/domains/lk/nsbm.txt

**Comment by MRGitHub94** [comment]
Renamed.

**Comment by philipto** [comment]
@MRGitHub94 Please rename lib/domains/lk/nsbm.lk to lib/domains/lk/nsbm.txt -- NOT to lib/domains/lk/nsbm. The .txt extension is mandatory. Thank you.

**Comment by MRGitHub94** [comment]
oops! sorry for the mistake. I renamed nsbm to nsbm.txt 
Can you kindly review it? 
Thanks.

**Comment by philipto** [comment]
@MRGitHub94 Pull request merged. Thank you!

**Comment by MRGitHub94** [comment]
Thank you very much!

**Pull request merged**
