### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by timbob1**

### CODE REVIEW

**Comment by philipto** [comment]
@timbob1 First stage of verification passed, official domain is [abingdon-witney.ac.uk](https://abingdon-witney.ac.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@timbob1 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by timbob1** [comment]
As requested Thank you

 

https://abingdon-witney.ac.uk/courses/areas/digital-technologies

 

Tim

**Comment by philipto** [comment]
@timbob1 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
