### PR TITLE
request adding dulwich.org to the list

### PR DESCRIPTION
**Pull request by luweiyezi**
homepage : www.dulwich.org

### CODE REVIEW

**Comment by philipto** [comment]
@luweiyezi The first verification stage is complete: the official domain for  **Dulwich College Beijing** is [beijing.dulwich.org](https://beijing.dulwich.org), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://beijing.dulwich.org/university-representatives

**Comment by luweiyezi** [comment]
> @luweiyezi The first verification stage is complete: the official domain for **Dulwich College Beijing** is [beijing.dulwich.org](https://beijing.dulwich.org), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://beijing.dulwich.org/university-representatives

Thanks for the investigation 
Nowadays we use the dulwich.org email address suffix including the mentioned "Dulwich College Beijing"

**Comment by philipto** [comment]
@luweiyezi The first verification stage is complete: the official domain for  **Dulwich College Beijing** is [beijing.dulwich.org](https://beijing.dulwich.org), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://beijing.dulwich.org/university-representatives

**Comment by philipto** [comment]
@luweiyezi Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
