### PR TITLE
Create matgim.txt

### PR DESCRIPTION
**Pull request by aleksav013**
#### Institution/School Name 
Mathematical Grammar School, Belgrade

#### Instiution/School Website
https://www.mg.edu.rs/sr/

#### Email Users

*Please place an x between the square brackets if yes*
- [x] Students
- [x] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [ ] Graduate School
- [ ] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [x] High School or equivalent
- [ ] Elementary School or equivalent

### CODE REVIEW

**Comment by aleksav013** [comment]
This is proof from school that domain is used by students (school notifications students receive).
mail_proof

And this is about programming we are doing in school and courses students can attend. https://www.mg.edu.rs/sr/organizacija/strucna-veca/informatika

**Comment by aleksav013** [comment]
@philipto This pull request was submitted a week ago. Anything more need to be provided?

**Comment by philipto** [comment]
@aleksav013 I have sent an email to Jasmina Stosic mentioned at the screenshot which you have attached. However I received no response from her regarding my questions to her. The domain which you ask to add to this repository is not listed anywhere on the school website, and I was not able to locate any materials in the internet referring to this domain as an email domain for the students.

Please provide additional proof that the domain belongs to the school. The best proof is an instruction which the school gives to the students, saying that they can (or have to) use their emails in this domain.

Thank you.

**Comment by aleksav013** [comment]
@philipto I have contacted Jasmina and she told me that she has not received any mails regarding this subject because that mail you have seen on screenshot is not the mail she usually uses. Would you be kind to send mail to jasmina.stosic@mg.edu.rs as this appears to be her correct email adress. 

Best regards,

Aleksa

**Comment by aleksav013** [comment]
https://www.mg.edu.rs/en/organization/staff/deputy-headteacher

**Comment by philipto** [comment]
@aleksav013 I double checked it, and I found out that I actually sent the email to jasmina.stosic@mg.edu.rs already. However, I just resent it it to the same address. I hope Jasmina will find time to answer my question. Thank you.

**Comment by philipto** [comment]
@aleksav013 Pull request merged. Thank you!

**Pull request merged**
