### PR TITLE
add suptech tn

### PR DESCRIPTION
**Pull request by lamjar**

### CODE REVIEW

**Comment by philipto** [comment]
@lamjar Please provide us with:
- the school official website URL
- the school street address, including city and country

**Comment by philipto** [comment]
@lamjar You might miss my previous comment. Please react.

**Comment by lamjar** [comment]
Sorry for the late response, below is the school information:
Address : 22 Av. de Madrid, Tunis, Tunisie
Website : https://suptech.tn

**Comment by philipto** [comment]
@lamjar Thank you for the clarification. Pull request merged.

**Please wait about 45 minutes before applying for a free license at https://www.jetbrains.com/shop/eform/students to let the changes to propagate through JetBrains' systems.**

Thank you!

**Pull request merged**
