### PR TITLE
Create fshnstudent.txt

### PR DESCRIPTION
**Pull request by elephantsy**
Adding @fshnstudent.info email domain for the students of the Faculty of Natural Sciences at University of Tirana.

### CODE REVIEW

**Comment by zweizwei** [comment]
I see that the university domain is http://www.unitir.edu.al/ - please provide some proof, that fshnstudent.info also belongs to the university

**Comment by elephantsy** [comment]
http://ebills.fshn.edu.al/Profiles/signin.aspx

If you click on the link above and read  this section:

" Mirësevini në portalin e vetshërbimit për studentët të Fakultetit të Shkencave Natyrore 

Ju mund të identifikoheni nëpërmjet  Google duke përdorur adresën postës suaj elektronike @fshnstudent.info. "

you will see that the email domain is @fshnstudent.info

**Comment by zweizwei** [comment]
Thanks a lot! I'm adding the domain!

**Comment by elephantsy** [comment]
Thank you!

**Pull request merged**
