### PR TITLE
Added St-Martinus

### PR DESCRIPTION
**Pull request by RafVandelaer**

### CODE REVIEW

**Comment by philipto** [comment]
@RafVandelaer lib/domains/be/st-martinus.be: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by RafVandelaer** [comment]
Dear Jetbrains
I changed the files to the right file format. You can find our schools website on the same domain as the email addresses. www.st-martinus.be

**Comment by philipto** [comment]
@RafVandelaer I am sorry, I am a little bit confused now. What is your school email address pattern, username@st-martinus.be or username@sint-martinus.be?

**Comment by RafVandelaer** [comment]
@philipto

Sorry, it's username@st-martinus.be

**Comment by philipto** [comment]
@RafVandelaer Thank you for the update! I renamed the file for you accordingly. Pull request merged.

**Pull request merged**
