### PR TITLE
Create lgs-hu

### PR DESCRIPTION
**Pull request by derrobin154**

### CODE REVIEW

**Comment by derrobin154** [comment]
Before you ask for the Domain, lgs-hu.eu is the Domain to our iServ Panel, when you need a proof that the Domain is in Ownership from the School, you can look under  http://www.ludwig-geissler-schule.de then going to "E-Mail / iServ" in the left Sidebar and then click to "iDesk" and you come to the URL.

Greetings from Germany.

**Comment by philipto** [comment]
@derrobin154 Please rename lib/domains/eu/lgs-hu to lib/domains/eu/lgs-hu.txt and provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by derrobin154** [comment]
Hey,
The official Website is ludwig-geissler-schule.de, but, the school isn't a University but the School is a technical School / College, with for the apprenticed profession of computer technician.
However, I don't know how I can prove that the school provides students with the email address. I can only send you an e-mail from the e-mail address.

Greetings

**Comment by derrobin154** [comment]
@philipto 
Sorry, I forgot to mark you.

**Comment by philipto** [comment]
@derrobin154 Thank you for the details. I found the proof at http://ludwig-geissler-schule.de/index.php?id=583, it says that the school idesk is located in the domain which you requested to add. Pull request merged. Thank you!

**Pull request merged**
