### PR TITLE
added e-u.txt

### PR DESCRIPTION
**Pull request by Oleksandr-Demchenko**

### CODE REVIEW

**Comment by osben** [comment]
Приватний вищий навчальний заклад "Європейський університет"
Private Higher Education Establishment "European University"

**Comment by osben** [comment]
proof links:
https://registry.edbo.gov.ua/university/228/
https://e-u.edu.ua/ua/

**Comment by philipto** [comment]
@Oleksandr-Demchenko First stage of verification passed, official domain is [e-u.edu.ua](https://e-u.edu.ua) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Oleksandr-Demchenko Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
