### PR TITLE
add liis highschool

### PR DESCRIPTION
**Pull request by isamoila**

### CODE REVIEW

**Comment by philipto** [comment]
@isamoila Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by isamoila** [comment]
1. Official Url: https://www.liis.ro/
2. School address: Str. Petre Andrei nr. 9, Iasi, Romania
3. There is no official offer on the website (maybe this might come close: https://liis.ro/Pages/view/default/204 ), this is the IT highschool in town as the name suggests, basically all the levels 5-12th are studying informatics.
4. I need to obtain the proof from a system administrator, which might take some time, will attach it as soon as I get it

**Comment by philipto** [comment]
@isamoila  Thank you for the clarifications. 
>  need to obtain the proof from a system administrator, which might take some time, will attach it as soon as I get it

Yes, please.

**Comment by isamoila** [comment]
Since the Romanian public school system is currently on prolonged banking holidays until Monday, would a printscreen of a test emails exchange with a student be enough?
studentUsage

**Comment by philipto** [comment]
@isamoila Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
