### PR TITLE
Hainan University Domain Migration Request

### PR DESCRIPTION
**Pull request by littleplus**
Hi,

My university, Hainan University, which has migrated the domain from `hainu.edu.cn` to `hainanu.edu.cn`, please help me update it.
Thank you.

New website URL: [https://www.hainanu.edu.cn/](https://www.hainanu.edu.cn/)

Best regards,

### CODE REVIEW

**Comment by philipto** [comment]
@littleplus Would you please provide us with some proof of the migration? It can be a public announcement or a copy of a message sent to the students. Thank you.

**Comment by littleplus** [comment]
Hi philipto,

Here's the announcement link:
[https://its.hainanu.edu.cn/info/1060/1844.htm](https://its.hainanu.edu.cn/info/1060/1844.htm)

**Comment by philipto** [comment]
@littleplus I am sorry, the domain hainanu.edu.cn is removed from our trusted domains list because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Comment by 2841842190** [comment]
Hello, philipto. My university, Hainan University, which has migrated the domain from hainu.edu.cn to hainanu.edu.cn, please help me update it.
New website URL: https://www.hainanu.edu.cn/
Here's the announcement link: https://its.hainanu.edu.cn/info/1060/1844.htm
School email registration requires a staff number or student number, which is uniquely bound to the registered email. https://its.hainanu.edu.cn/info/1097/3243.htm

Thank you!

Best regards,

**Comment by 2841842190** [comment]
@philipto Hello, philipto. My university, Hainan University, which has migrated the domain from hainu.edu.cn to hainanu.edu.cn, please help me update it.
New website URL: https://www.hainanu.edu.cn/
Here's the announcement link: https://its.hainanu.edu.cn/info/1060/1844.htm
School email registration requires a staff number or student number, which is uniquely bound to the registered email. https://its.hainanu.edu.cn/info/1097/3243.htm

Thank you!

Best regards,

**Comment by philipto** [comment]
@littleplus I am sorry, the domain hainanu.edu.cn is removed from our trusted domains list because the school allows to register an email address there even if you are not a student of the school. If you are the student of this school, please apply with official document (OFFICIAL DOCUMENT tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
@littleplus I am sorry for the confusion. We reconsidered the request and removed the domain from the stoplist. Your pull request is now merged. Please notice that we monitor the domain usage closely, and if third parties will use the domain or sell the accounts anywhere, we'll block the domain again.

**Pull request merged**
