### PR TITLE
adding Misr higher institute of commerce and computers in Mansoura (MET Academy) domain

### PR DESCRIPTION
**Pull request by FahmiMoustafa**
official website
https://metmans.edu.eg/
official email
 info@metmans.edu.eg

### CODE REVIEW

**Comment by FahmiMoustafa** [comment]
@philipto is there any thing wrong with what i offered for my institute

**Comment by philipto** [comment]
@FahmiMoustafa Everything is fine. We have many different requests, thus I appreciate it if you can wait a little bit more before we process your request. In the meantime you can use a trial version of the tool or apply with official documents at https://www.jetbrains.com/shop/eform/students (OFFICIAL DOCUMENTS tab). Thank you!

**Comment by FahmiMoustafa** [comment]
@philipto thanks for your replay

**Comment by philipto** [comment]
@FahmiMoustafa Thank you for your patience while waiting for a review and processing your request. Pull request merged. Thank you!

**Pull request merged**
