### PR TITLE
Create labore.ru

### PR DESCRIPTION
**Pull request by moryakovvn**

### CODE REVIEW

**Comment by philipto** [comment]
@moryakovvn lib/domains/ru/udm/labore.ru: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@moryakovvn lib/domains/ru/udm/labore.ru: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@moryakovvn lib/domains/ru/udm/labore.ru: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@moryakovvn lib/domains/ru/udm/labore.ru: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@moryakovvn lib/domains/ru/udm/labore.ru: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@moryakovvn What is your school email address pattern? Is it username@labore.ru?

**Comment by philipto** [comment]
@moryakovvn lib/domains/ru/udm/labore.ru: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by moryakovvn** [comment]
Yes, it is.

  
>Среда, 18 марта 2020, 0:59 +04:00 от Philip Torchinsky <notifications@github.com>:
> 
> 
>@moryakovvn What is your school email address pattern? Is it  username@labore.ru ?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Виктор Николаевич Моряков

**Comment by philipto** [comment]
@moryakovvn Thank you for the update! I renamed the file in the request to reflect this repository rules. Pull request merged. You can start requesting free licenses at https://www.jetbrains.com/shop/eform/students in an hour. Thank you.

**Comment by moryakovvn** [comment]
Thank you for your support. Very appreciate it.

  
>Среда, 18 марта 2020, 21:33 +04:00 от Philip Torchinsky <notifications@github.com>:
> 
> 
>@moryakovvn Thank you for the update! I renamed the file in the request to reflect this repository rules. Pull request merged. You can start requesting free licenses at  https://www.jetbrains.com/shop/eform/students in an hour. Thank you.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Виктор Николаевич Моряков
Victor Moryakov

**Pull request merged**
