### PR TITLE
Ironi H email

### PR DESCRIPTION
**Pull request by ikoursh**
Note that this applies to all schools in Tel Aviv

### CODE REVIEW

**Comment by philipto** [comment]
@ikoursh I am sorry, this repository is for individual email domains for colleges and universities only. We generally do not add umbrella organizations and umbrella domains to it. Why would you like to add this domain to the list? Are there schools in Tel Aviv, which need to use JetBrains tools, but don't have their individual domains?

**Comment by ikoursh** [comment]
Yes, no high school in Tel Aviv has an individual domain, they all use the @tlvedu.org domain

**Comment by philipto** [comment]
@ikoursh Thank you for the clarification. Pull request merged.

**Comment by ikoursh** [comment]
Thanks

**Pull request merged**
