### PR TITLE
Create ufop.txt

### PR DESCRIPTION
**Pull request by augustohdias**
Computer Science department domain of Federal University of Ouro Preto, Brazil.

### CODE REVIEW

**Comment by philipto** [comment]
@augustohdias Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by augustohdias** [comment]
University official website: http://www.ufop.br/
Courses offered by the university, where "Ciência da Computação" is one of IT-related courses: http://www.prograd.ufop.br/index.php/cursos
Webmail screenshot (is this a valid proof of domain recognition?): image

**Comment by philipto** [comment]
@augustohdias lib/domains/br/decom/ufop.txt corresponds to a domain ufop.decom.br. As far as I see from the screenshot, the domain of your university is decom.ufop.br. Please rename the file in your request accordingly, to lib/domains/br/ufop/decom.txt
Thank you!

**Comment by augustohdias** [comment]
done!

**Comment by philipto** [comment]
@augustohdias Pull request merged. Thank you!

**Pull request merged**
