### PR TITLE
Add Kathford College

### PR DESCRIPTION
**Pull request by bhimrazy**
Add Kathford International College of Engineering and Management to the list.
Link for the college website: https://kathford.edu.np/

### CODE REVIEW

**Comment by philipto** [comment]
@bhimrazy First stage of verification passed, official domain is [collegesnepal.com](https://collegesnepal.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.collegesnepal.com/kamana-international-college/

**Comment by bhimrazy** [comment]
Kathford International College of Engineering and Management is an Engineering College located in Kathmandu, Nepal Affiliated with Tribhuvan University.

For more info: 
Here is the official domain of the college: https://kathford.edu.np

Listed on Institute of Engineering.
https://ioe.edu.np/colleges/affiliated-colleges/kathford-international-college/

Listed on Colleges Nepal Website.
https://www.collegesnepal.com/kathford-college-of-engineering-and-management

**Comment by philipto** [comment]
@bhimrazy There is an issue with the request. Please help us to resolve it.

You are submitting the file **lib/domains/np/edu/kic.txt**, which corresponds to **kic.edu.np** domain. According to https://www.collegesnepal.com/kamana-international-college/ this domain belongs to Kamana International College. However, you attribute the domain to Kathford International College, which has the domain **kathford.edu.np**.

Please explain the relations between the two domains. Thank you.

**Comment by bhimrazy** [comment]
@philipto I have renamed the file to `kathford.txt`.
I am really sorry for the inconvenience due to the file name. 
I hope it should work now.
Thank you.

**Comment by philipto** [comment]
@bhimrazy Thank you for the update. Pull request merged.

**Comment by bhimrazy** [comment]
@philipto 
Thank you.

**Pull request merged**
