### PR TITLE
added lls UTC

### PR DESCRIPTION
**Pull request by M4TE0FR**

### CODE REVIEW

**Comment by philipto** [comment]
@M4TE0FR The first verification stage is complete: the official domain for  **Liverpool Life sciences UTC** is [lifesciencesutc.co.uk](https://lifesciencesutc.co.uk), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://lifesciencesutc.co.uk/read-utc-students-launch-first-ever-baltic-science-journal/

**Comment by M4TE0FR** [comment]
yeah the school website domain and the email domain is different 

image

**Comment by philipto** [comment]
@M4TE0FR The first verification stage is complete: the official domain for  **Liverpool Life sciences UTC** is [lifesciencesutc.co.uk](https://lifesciencesutc.co.uk), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://lifesciencesutc.co.uk/read-utc-students-launch-first-ever-baltic-science-journal/

**Comment by philipto** [comment]
@M4TE0FR Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
