### PR TITLE
Added Olivarez College Tagaytay

### PR DESCRIPTION
**Pull request by tortendes**
Website: https://olivarezcollegetagaytay.edu.ph
Facebook Page: https://www.facebook.com/octagaytayofficial

### CODE REVIEW

**Comment by philipto** [comment]
@tortendes First stage of verification passed, official domain is [olivarezcollegetagaytay.edu.ph](https://olivarezcollegetagaytay.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by tenthreee** [comment]
@tortendes Please provide us with proof that shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by tortendes** [comment]
What proof can I show?

**Comment by philipto** [comment]
@tortendes Please ask the system administrator to fix the error and make the website working. Please refer to the attached screenshot to tell the administrator what happened. I will check the details on the website and verify the school's email domain eligibility for this repository. Thank you!

image

**Comment by philipto** [comment]
@tortendes You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@tortendes I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
