### PR TITLE
Added Aszódi Petőfi Lutheran Secondary School

### PR DESCRIPTION
**Pull request by Lyenus**

### CODE REVIEW

**Comment by Lyenus** [comment]
More information about the IT education on the facility's official website
https://info.aszevgim.hu/index.php/programozzunk

**Comment by philipto** [comment]
@Lyenus Please provide us with:
* the school official website URL
* the school street address, including city and country
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Lyenus You might miss my previous comment. Please react.

**Comment by Lyenus** [comment]
@philipto Your comment has been acknowledged, I will add the necessary information in another comment soon. Not too long now

**Comment by Lyenus** [comment]
- The official website URL: https://info.aszevgim.hu/

- The street address: Hungary, Aszód, Régész street 34 (Google Maps link: https://maps.app.goo.gl/cnPxhZNVgVTUffV77 )

I don't know what kind of proof I could provide that the school uses this domain for student emails. If you could suggest some options, that would be much appreciated.

**Comment by philipto** [comment]
@Lyenus Thank you for the details. The problem is that all independent sources assume that the official website is **http://www.egaaszod.hu**. It includes Google Maps, which you have suggested. 

In order to add **aszevgim.hu** I need to find a relationship between **egaaszod.hu** and **aszevgim.hu**. The proof confirming that the school recognizes the domain **aszevgim.hu** you are submitting as an official email domain for the students can be any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by Lyenus** [comment]
I can provide the public domain info for both.

This is aszevgim: https://info.domain.hu/webwhois/hu/domain/aszevgim.hu

And this is egaaszod: https://info.domain.hu/webwhois/hu/domain/egaaszod.hu

As you can see, they are both registered under the same street address and phone number. I hope this is enough proof, because I don't think I can provide anything better.

**Comment by philipto** [comment]
@Lyenus  Thank you for the clarifications. Pull request merged.

**Pull request merged**
