### PR TITLE
Add BMS Liechtenstein

### PR DESCRIPTION
**Pull request by NiciiA**
Berufsmaturitäts Schule Liechtenstein für Informatikzwecke

### CODE REVIEW

**Comment by philipto** [comment]
@NiciiA Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@NiciiA You might miss my previous comment. Please react.

**Comment by NiciiA** [comment]
Heyy, sry for the late response....

the school url is: https://www.berufsmittelschule.li/
it courses are here: https://www.berufsmittelschule.li/Ausbildungsangebot/Schwerpunktbereich.aspx
- we have tech (system) and information (web)
the school takes around 1 - 2 years: https://www.berufsmittelschule.li/Ausbildungsangebot/BerufsbegleitendUnterricht.aspx
and under contact you see the mail address from the rector: https://www.berufsmittelschule.li/Kontakt/Schulleitung.aspx

**Comment by philipto** [comment]
@NiciiA Thank you for the clarification. Pull request merged.

**Pull request merged**
