### PR TITLE
Add National Quemoy University

### PR DESCRIPTION
**Pull request by JustinLin-nqu**
Ple review the adding of National Quemoy University. Thanks

### CODE REVIEW

**Comment by JustinLin-nqu** [comment]
Official site is :  https://www.nqu.edu.tw/eng/index.php

**Comment by JustinLin-nqu** [comment]
Official school site is : https://www.nqu.edu.tw/eng/index.php

Email domain for student:
{{username}}@student.nqu.edu.tw

Email domain for teachers&staff:
{{username}}@nqu.edu.tw
{{username}}@email.nqu.edu.tw

**Comment by JustinLin-nqu** [comment]
Official school site is : https://www.nqu.edu.tw/eng/index.php
Site for computer science : https://www.nqu.edu.tw/eng/index.php?code=list&flag=detail&ids=2439&article_id=24011

Email domain for student:
{{username}}@student.nqu.edu.tw

Email domain for teachers&staff:
{{username}}@nqu.edu.tw
{{username}}@email.nqu.edu.tw

**Comment by philipto** [comment]
@JustinLin-nqu Pull request merged. 

I removed all subdomain under nqu.edu.tw, because all subdomains are considered automatically added.
The domain nqu.edu.tw is now in the repository.

Thank you!

**Pull request merged**
