### PR TITLE
Add Domain

### PR DESCRIPTION
**Pull request by CosineAA**
add onedu domain

### CODE REVIEW

**Comment by philipto** [comment]
@CosineAA Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@CosineAA You might miss my previous comment. Please react.

**Comment by CosineAA** [comment]
Sorry for late reply
https://namju.jje.hs.kr/ is my school website
My school email is onedu.jje.go.kr

**Comment by philipto** [comment]
@CosineAA  Thank you for the clarifications. Pull request merged.

**Pull request merged**
