### PR TITLE
Create EAFC

### PR DESCRIPTION
**Pull request by IbraYou**
[eafcevere.txt](https://github.com/JetBrains/swot/files/12774248/eafcevere.txt)

### CODE REVIEW

**Comment by IbraYou** [comment]
EAFC Evere
https://eafcevere.eu/

**Comment by philipto** [comment]
@IbraYou Excuse me, it's not clear what is a domain you wish to add? Is it `@eafcevere.eu`?

**Comment by IbraYou** [comment]
@philipto 
Yes, the domain that the school uses is :  @eafcevere.eu

**Comment by philipto** [comment]
@IbraYou lib/domains/eu/EAFC: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@IbraYou First stage of verification passed, official domain is [eafcevere.eu](https://eafcevere.eu) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@IbraYou Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
