### PR TITLE
Create ofppt-edu.ma

### PR DESCRIPTION
**Pull request by sorakannie**
[file.zip](https://github.com/JetBrains/swot/files/4024990/file.zip)

### CODE REVIEW

**Comment by philipto** [comment]
@sorakannie ofppt-edu.ma: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@sorakannie You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@sorakannie ofppt-edu.ma: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by sorakannie** [comment]
i uploaded the text file into the lib\domain... as said 
i dont know what to do else

**Comment by philipto** [comment]
@sorakannie I have to close this request as a duplicate to #7428.

**Pull request closed without merging**
