### PR TITLE
Login Berufsbildung AG added (2. try)

### PR DESCRIPTION
**Pull request by htg115**
After your comment regarding pull request #10007 I checked the domain "mylogin.org" again and according to ICANN, it is affiliated to my Vocational school. I also tried to ping it and the website itself and it worked completely fine, but the website/server was actually down for some time.

My own results below:

image

mylogin_icann

But you actually drew my attention to a mistake of mine. I really forgot to add the domain "login.org" as well, which now should be correct.

I hope everything's fine now and you are now able to check my request, I'm very sorry for the inconvenience!

### CODE REVIEW

**Comment by philipto** [comment]
@htg115 Thank you for the clarifications! Could you please tell us a bit more about the nature of this school? Is it a college? Is it a 100% online school? Also, please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@htg115 You might miss my previous comment. Please react.

**Comment by htg115** [comment]
Sorry for my late answer. 

It isn't a pure school or college per se, it's a certified training company offering vocational trainings in different areas, but focused around train transportation. Students go to school and also work in a company part time. Of course they also offer vocational training in IT (e.g. 2y vocational training: https://www.login.org/de/berufe/technik-und-informatik/informatikerin-efz-applikationsentwicklung-wayup ; All technical trainings: https://www.login.org/de/berufe/technik-und-informatik) and in other fields of study.

Also, the school part of the vocational training are provided physically and not online, but of course with homework and final exams with completion of apprenticeship in the chosen field.


I'm honestly not 100% sure, if this fully complies with the rules for the repo, but I'm sure you are able to assess that correctly. If it's not, I apologise for the inconvenience.

Thank you very much.

**Comment by philipto** [comment]
@htg115 I am really sorry, but this company does not seem to be eligible for being added to this repository. Please apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses

You may also wish to apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

I have to close the request without merging.

Thank you for the understanding!

**Pull request closed without merging**
