### PR TITLE
Semmelweis University new student email address

### PR DESCRIPTION
**Pull request by hegi25**
URL about the address validation: https://seka.semmelweis.hu/en/info/o365

### CODE REVIEW

**Review by hammaadmondal — COMMENTED** [review]
The Indian High School

**Comment by hegi25** [comment]
> The Indian High School

???
Hungarian university.

**Comment by philipto** [comment]
@hegi25 Please provide us with:
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@hegi25 You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@hegi25 @hammaadmondal I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
