### PR TITLE
Zimbabwe open university

### PR DESCRIPTION
**Pull request by mrsisk**
added zimbabwe open university

### CODE REVIEW

**Comment by philipto** [comment]
@mrsisk First stage of verification passed, official domain is [zou.ac.zw](https://zou.ac.zw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@mrsisk Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
* THE MOST IMPORTANT: A page at the official Ministry of Education of Zimbabwe website that recognizes the university as a national educational organization eligible to issue official diplomas. 

Please also describe who can apply for the study in the university. We need to understand which countries the university serves.

**Comment by philipto** [comment]
@mrsisk You might miss my previous comment. Please react.

**Comment by mrsisk** [comment]
Official URL is:
- https://www.zou.ac.zw

School is located in multiple regions. Main region address is: 
Corner House
Corner Samora Machel Avenue and Leopold Takawira Street
P.O.Box MP 1119 Mount Pleasant
Harare 
Zimbabwe

URL where they offer IT related courses: 
- https://www.zou.ac.zw/faculty-of-technology/

Proof:
The official general enquiries email is information@zou.ac.zw. for students its a subdomain with the format STUDENT_PIN@student.zou.ac.zw. a link from the official website which shows the format of email can be found on this document with instructions to students on how to login on the student's portal. the link to the document is https://web.myvista.zou.ac.zw/pluginfile.php/29/mod_forum/post/23266/ZOU%20Student%20Email.pdf

Zimbabwe Ministry of Higher and Tertiary education, science and technology development official universities list is found at 
- http://www.mhtestd.gov.zw/?page_id=3588
official goverment website that links to that Ministry is:
- http://www.zim.gov.zw/index.php/en/my-government/government-ministries/higher-and-tertiary-education,-science-and-technology-development
The university offers programs for both local and international students. so anybody in the world can apply for studying with the university.
Let me know if there is any missing or additional information that is required.

**Comment by philipto** [comment]
@mrsisk I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Pull request closed without merging**
