### PR TITLE
Create euroamericano.txt

### PR DESCRIPTION
**Pull request by Gabrielj95**
URL: https://www.euroamericano.edu.ec/
Correo personal: andres.jacome@euroamericano.edu.ec

### CODE REVIEW

**Comment by philipto** [comment]
@Gabrielj95 First stage of verification passed, official domain is [euroamericano.edu.ec](https://euroamericano.edu.ec) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Gabrielj95 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by Gabrielj95** [comment]
> 

URL Escuela: https://www.euroamericano.edu.ec/

Dirección: Guayaquil, Av Quisquis y Los Ríos. Ecuador

URL Carrera IT: https://www.euroamericano.edu.ec/index.php/redes

Mi Correo de Estudiante: andres.jacome@euroamericano.edu.ec

**Comment by philipto** [comment]
@Gabrielj95  Thank you for the clarifications. Pull request merged.

**Pull request merged**
