### PR TITLE
Riverside Unified School District

### PR DESCRIPTION
**Pull request by ritobanrc**
http://www.riversideunified.org/

### CODE REVIEW

**Comment by philipto** [comment]
@ritobanrc lib/domains/org/riversideunified: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by ritobanrc** [comment]
Ahh oops fixed it

**Comment by ritobanrc** [comment]
Also, course list: http://www.riversideunified.org/departments/instructional_services/secondary_7-12/high_school_course_catalog --  go to page 18-19, to see Technical Electives offered. 

> 
> g. Electives (continued)
> Computer Science A, Advanced Placement*
> Computer Science B, Advanced Placement*
> Computer Science Principles, Advanced Placement*
> Career Technical Education (CTE)
> Basic Programming 1A
> Basic Programming 1B
> Building Construction Tech B
> C++ Computer Programming
> CISCO IT Essentials
> Civil Engineering and Architecture
> Computer Integrated Manufacturing
> Computer Support Specialist
> Digital Electronics
> Digital Film Production I
> Digital Game Design
> Engineering Design and Development
> Exploring Computer Science
> Game Design 1
> Game Design 2
> Game Design Principles

Unfortunately, the only evidence I can find showing that students have a `riversideunified.org` email is the email that we were sent informing us of the change. 

image 

(RSA, or Riverside STEM Academy, is the school that I attend inside the Riverside Unified School District).

**Comment by philipto** [comment]
@ritobanrc Thank you for the update! Pull request merged.

**Pull request merged**
