### PR TITLE
Create cea.txt

### PR DESCRIPTION
**Pull request by dchapon**

### CODE REVIEW

**Comment by zweizwei** [comment]
Please provide the link to the page of long-term IT-related educational programs, that CEA provides - according to what i see (http://www.cea.fr/le-cea/presentation-generale) that's a research institute rather than educational institution. Thanks.

**Comment by dchapon** [comment]
Hi,

True, the CEA is only indirectly involved in educational programs throug 
its teaching institute (INSTN) and various partnerships with 
universities and engineer schools. On an administrative level, all this 
is about to change since CEA is a founding member of the brand new 
"Paris-Saclay university" (beginning of 2015). I guess the 
@univ-paris-saclay.fr mail adress will be the one to qualify...

Best regards,


Damien CHAPON

Le 04/03/2015 13:29, Elena Ganenkova a écrit :
>
> Please provide the link to the page of long-term IT-related 
> educational programs, that CEA provides - according to what i see 
> (http://www.cea.fr/le-cea/presentation-generale) that's a research 
> institute rather than educational institution. Thanks.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JetBrains/swot/pull/792#issuecomment-77149410>.
>

-- 
-------------------------
Damien CHAPON
CEA Saclay
DSM/IRFU/SEDI/LILAS
91191 Gif-sur-Yvette
tel. : 01 69 08 50 75
-------------------------

**Comment by zweizwei** [comment]
I'm sorry for the delay

In case you need a campus-wide license for teaching you can request a classroom license through classroom@jetbrains.com

as for the university entry - the domain seems to https://www.universite-paris-saclay.fr

Could you please somehow confirm that univ-paris-saclay.fr also belongs to the university? thanks!

**Comment by dchapon** [comment]
As of today, I cannot confirm that @univ-paris-saclay.fr mail adresses 
belong to the Paris-Saclay university, I don have one yet.


Damien CHAPON

Le 27/03/2015 13:22, Elena Ganenkova a écrit :
>
> I'm sorry for the delay
>
> In case you need a campus-wide license for teaching you can request a 
> classroom license through classroom@jetbrains.com 
> <mailto:classroom@jetbrains.com>
>
> as for the university entry - the domain seems to 
> https://www.universite-paris-saclay.fr
>
> Could you please somehow confirm that univ-paris-saclay.fr also 
> belongs to the university? thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JetBrains/swot/pull/792#issuecomment-86925631>.
>

-- 
-------------------------
Damien CHAPON
CEA Saclay
DSM/IRFU/SEDI/LILAS
91191 Gif-sur-Yvette
tel. : 01 69 08 50 75
-------------------------

**Comment by zweizwei** [comment]
If there's no official confirmation, i'm closing the request - please apply for a classroom license (see email above) instead.

**Pull request closed without merging**
