### PR TITLE
Add Charmo University to list of University

### PR DESCRIPTION
**Pull request by DiyarBakir**
**Location:** Peshawa Street & Chamchamal/Sulaimani Kurdistan region, F.R. Iraq.
**Website:** [http://charmouniversity.org](url)

### CODE REVIEW

**Comment by philipto** [comment]
@DiyarBakir Your website can not be open because it is possibly infected with CryptoMiner malware. Please tell your web server administrator that an anti-malware check can be necessary. I can not add this domain to the repository without seeing the official university website. Please comment here as soon as the website is back to normal work. Thank you.

**Comment by DiyarBakir** [comment]
@philipto Thanks for your support, the website works fine from our side, the link that I gave before not opened directly if you clicked it from Github.

you can check the website from: **www.charmouniversity.org** 

your right I check the website it look like effected with Malware , I will tell the Administrator to check their server as soon as possible. 

Thank you.

**Comment by philipto** [comment]
@DiyarBakir Pull request merged. Thank you!

**Comment by DiyarBakir** [comment]
@philipto  Thanks for your support.

**Pull request merged**
