### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by aldrin0408av**

### CODE REVIEW

**Comment by philipto** [comment]
@aldrin0408av Please provide us with:
* the school official full name (**not an abbreviation**)
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@aldrin0408av You might miss my previous comment. Please react.

**Comment by aldrin0408av** [comment]
System Plus College Foundation
https://www.spcf.edu.ph/
Sta. Isabel Bldg., Balibago, Angeles City, Pampanga, Philippines
https://www.spcf.edu.ph/academics/ccis
image

**Comment by philipto** [comment]
@aldrin0408av First stage of verification passed, official domain is [spcf.edu.ph](https://spcf.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@aldrin0408av I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by aldrin0408av** [comment]
Any updates on this?

**Pull request closed without merging**
