### PR TITLE
Create st-james.txt

### PR DESCRIPTION
**Pull request by EclecticCynic**
Trying to add St James Catholic High School that is located in Barnet, London so our Computer Science classes can use PyCharm.  The course we take has a textbook that consistently uses screenshots of PyCharm and Thonny, suggesting a preference to use PyCharm over other IDEs.

### CODE REVIEW

**Comment by philipto** [comment]
Please kindly provide the full name of your school on the first line of the file in your request

**Comment by philipto** [comment]
Please kindly provide the full name of your school on the first line of the file in your request

**Comment by EclecticCynic** [comment]
Should be done now.

**Comment by philipto** [comment]
@EclecticCynic First stage of verification passed, official domain is [st-james.barnet.sch.uk](https://st-james.barnet.sch.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@EclecticCynic Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
