### PR TITLE
Add dBs Institute

### PR DESCRIPTION
**Pull request by wsdevuid798**
https://www.dbsinstitute.ac.uk/all-courses/ba-hons-game-development-programming

### CODE REVIEW

**Comment by philipto** [comment]
Please kindly provide the full name of your school on the first line of the file in your request

**Comment by wsdevuid798** [comment]
Added.

**Comment by philipto** [comment]
@wsdevuid798 First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/grafikaudio/

**Comment by wsdevuid798** [comment]
> @wsdevuid798 First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/grafikaudio/

We are unaffiliated with Facebook.

**Comment by philipto** [comment]
@wsdevuid798 Thank you! You are quite right about affiliation, I agree with your comment. The problem is that I found no mentions of **dbsstudent.net** domain other than in some old post on Facebook. 

Please provide us with a proof, which shows that the school recognizes the domain **dbsstudent.net** you are submitting as an official email domain for the students.
You can provide us with any of the following:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

Thank you!

**Comment by wsdevuid798** [comment]
Thanks for your reply @philipto. Actually, I'd already filed a PR for the school's main domain that has been approved. That is sufficient for now, so I'll close this PR.

**Pull request closed without merging**
