### PR TITLE
Please add this university mailing name to your swot uinversity list

### PR DESCRIPTION
**Pull request by fahim9778**

### CODE REVIEW

**Comment by philipto** [comment]
@fahim9778 The official domain for the university is iutoic-dhaka.edu. Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting (iut-dhaka.edu) as an official email domain for the students.

**Comment by fahim9778** [comment]
Hi Philip,
To reply your query, I'm attaching  2 images.
The first one is from university student guide book. I've marked the email
point. and the second one is my student email confirmation paper from
university authority.
I hope this will help you to verify our student email domain and add our
email domain enlisted in your list.

Regards.

**Comment by fahim9778** [comment]
Hi, 
Did you got the email with those attachments?  If not kindly let me know. I will share a Google Drive link with the pictures.

**Comment by philipto** [comment]
@fahim9778 Regrettably, the attachment are not visible here at GitHub now. Please try to attach them again or share a link to them. Thank you!

**Comment by fahim9778** [comment]
[IUT Student Email Address.pdf](https://github.com/JetBrains/swot/files/2175315/IUT.Student.Email.Address.pdf)

Please Kindly check it and let me if it meets your requirement.

**Comment by philipto** [comment]
@fahim9778 Pull request merged. Thank you for the clarification!

**Pull request merged**
