### PR TITLE
Create lyceumgent.txt

### PR DESCRIPTION
**Pull request by Kiog-Aser**

### CODE REVIEW

**Comment by philipto** [comment]
@Kiog-Aser First stage of verification passed, official domain is [daltonlyceumgent.be](https://daltonlyceumgent.be) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://daltonlyceumgent.be/2de-graad

**Comment by philipto** [comment]
@Kiog-Aser Thank you! Could you please tell me what is the course that requires you to develop software with JetBrains tools?

**Comment by Kiog-Aser** [comment]
@philipto Thank you for the reply! We have a course named 'computationeel denken' in Dutch or computational thinking in English. In this course we learn how to use computers and software like Exel and word. We als learn basic programming like python and Javascript, for this we could use jetbrains. Have a nice day! Mil Hoornaert

**Comment by philipto** [comment]
@Kiog-Aser Thank you for the clarification.

> We als learn basic programming like python and Javascript,

Learning basic programming in Python and Javascript is available with a free version of PyCharm, PyCharm Community Edition. Please use it. It does not require any specific subscription, and it's free for everyone.

Thus, students and teachers of your school do not need educational subscriptions. This is why I close this request without merging. Please feel free to contact us at community-support@jetbrains.com if you need further help. Thank you!

**Pull request closed without merging**
