### PR TITLE
Update and rename vtmc.txt to techin.txt

### PR DESCRIPTION
**Pull request by vaclavzelenkevic**
After reorganization our training center changed domain and name to techin.lt.

### CODE REVIEW

**Comment by philipto** [comment]
@vaclavzelenkevic First stage of verification passed, official domain is [vtmc.lt](https://vtmc.lt) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.vtmc.lt/priemimas-i-9-klase/

**Comment by vaclavzelenkevic** [comment]
Currently, the old domain is still left for some time to full transition to the new domain. It may still take about half a year. Our new official domain is https://techin.lt or in english https://techin.lt/en/.

**Comment by philipto** [comment]
@vaclavzelenkevic Thank you for the update. I am not sure that the training center is eligible to be in this repository according to the [current repository rules](https://github.com/JetBrains/swot#which-educational-institutions-can-be-added-to-the-repository). Could you please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course?

Thank you!

**Comment by vaclavzelenkevic** [comment]
The all IT programs is here: [IT programmes](https://techin.lt/mokymo-programos/?cat=it). One of long-term course: [JavaScript](https://techin.lt/mokymo-programos/javascript-programuotojo-mokymai-2/). Today these pages are not yet translated into English. 
Thank you for your patience

**Comment by philipto** [comment]
@vaclavzelenkevic  Thank you for the clarifications. Pull request merged.

**Pull request merged**
