### PR TITLE
Adding William Angliss Institute

### PR DESCRIPTION
**Pull request by StefanBuchman**
https://www.angliss.edu.au/

### CODE REVIEW

**Comment by philipto** [comment]
@StefanBuchman Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@StefanBuchman You might miss my previous comment. Please react.

**Comment by StefanBuchman** [comment]
URL: https://www.angliss.edu.au/
Technology (including IT course): https://www.angliss.edu.au/courses/foods/food-science-and-technology/

**Comment by philipto** [comment]
@StefanBuchman Thank you for the clarification. Pull request merged.

**Comment by StefanBuchman** [comment]
Thanks, apologies needed to add the email domain as well, could you approve:
[https://github.com/JetBrains/swot/pull/10184](https://github.com/JetBrains/swot/pull/10184)

**Pull request merged**
