### PR TITLE
Add files via upload | Mountain House High School

### PR DESCRIPTION
**Pull request by TanishqTyagi**

### CODE REVIEW

**Comment by jim61103** [comment]
Add YunTech
[yuntech.txt](https://github.com/JetBrains/swot/files/5563736/yuntech.txt)

**Comment by philipto** [comment]
@TanishqTyagi lib/domains/net/lammersvilleusd.group.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@TanishqTyagi lib/domains/net/lammersvilleusd.group.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@TanishqTyagi lib/domains/net/lammersvilleusd.group.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@TanishqTyagi I corrected the pull request a little bit make it conforming the repository rules. Pull request merged. Thank you!

**Pull request merged**
