### PR TITLE
Add Fundacao Getulio Vargas as fgvmail.br

### PR DESCRIPTION
**Pull request by guibraz**
Add Fundacao Getulio Vargas as fgvmail.br, as is fgv.br

### CODE REVIEW

**Comment by guibraz** [comment]
Add Fundacao Getulio Vargas as fgvmail.br

**Comment by philipto** [comment]
@guibraz Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@guibraz You might miss my previous comment. Please react.

**Comment by guibraz** [comment]
Em qua., 15 de mar. de 2023 às 04:56, Philip Torchinsky <
***@***.***> escreveu:

> @guibraz <https://github.com/guibraz> Please provide us with:
>
>    - the school official website URL
>
> https://portal.fgv.br/

>
>    - the school street address, including city and country
>
>  Edifício Luiz Simões Lopes (Sede - Praia de Botafogo, 190 - Botafogo, Rio
de Janeiro - RJ, 22250-900 , Brazil

>
>    - an URL of a page on the official website where the school offers an
>    IT-related long-term (>1 year) course
>
>
https://vestibular.fgv.br/cursos/rio-de-janeiro/ciencia-de-dados-e-inteligencia-artificial

>
>    - a proof, which shows that the school recognizes the domain you are
>    submitting as an official email domain for the students.
>
>  https://epge.fgv.br/we/Email/RedirecionamentoAluno

Best regards
Guilherme

**Comment by philipto** [comment]
@guibraz  Thank you for the clarifications. Pull request merged.

Please notice that according https://epge.fgv.br/we/Email/RedirecionamentoAluno the email address may remain activated even for those who graduated the school already. 

Upon graduation, former students have a right for 40% graduation discount from JetBrains. The are not entitled for a free license after the graduation. Thus, if we find out that anyone uses the email domain to get free license without being eligible for it, we remove the domain from the trusted list immediately.

Thank you for your understanding.

**Pull request merged**
