### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Sainath-Poojary**

### CODE REVIEW

**Comment by philipto** [comment]
@Sainath-Poojary Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by Sainath-Poojary** [comment]
- the school official website URL -  https://www.vartakpolytechnic.org/
   - an URL of a page on the official website where the school offers an
   IT-related long-term (>1 year) course -
   https://www.vartakpolytechnic.org/courses/
   - a proof, which shows that the school recognizes the domain you are
   submitting as an official email domain for the students. -

**Comment by philipto** [comment]
@Sainath-Poojary You probably added a proof as an attachment to your email message. Regrettably, GitHub strips out all attachments. Please add the proof as a comment via GitHub web interface. Thank you.

**Comment by Sainath-Poojary** [comment]
- the school official website URL -  https://www.vartakpolytechnic.org/
   - an URL of a page on the official website where the school offers an
   IT-related long-term (>1 year) course -
   https://www.vartakpolytechnic.org/courses/
   - a proof, which shows that the school recognizes the domain you are
   submitting as an official email domain for the students. -
   https://github.com/Sainath-Poojary/proof
   <https://github.com/Sainath-Poojary/proof> ,
   https://drive.google.com/drive/folders/1z2obe4j8KNSHpAY73f0r1b8UBxXoVgl_?usp=sharing
   <https://drive.google.com/drive/folders/1z2obe4j8KNSHpAY73f0r1b8UBxXoVgl_?usp=sharing>

**Comment by philipto** [comment]
@Sainath-Poojary I am sorry, this proof is not enough. It confirms the fact that you have access to the account in this email domain. We need to ensure that the university recognizes this domain as belonging to students, and assign the addresses there to the students.

The proof can be an instruction to use this domain which you received at the enrollment time, or a page at the official website that indicates this domain as official.

**Comment by philipto** [comment]
@Sainath-Poojary I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
