### PR TITLE
Request to add iUniversity Prep to JetBrains

### PR DESCRIPTION
**Pull request by grace-sng7**

### CODE REVIEW

**Comment by philipto** [comment]
@grace-sng7 First stage of verification passed, official domain is [gcisd.net](https://gcisd.net) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.gcisd.net/departments/technology_services/free_microsoft_office_pro_plus_for_staff_and_stude

**Comment by grace-sng7** [comment]
@philipto Thank you for your help, looking forward to getting approval.

**Comment by philipto** [comment]
@grace-sng7 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by grace-sng7** [comment]
@philipto Thank you so much for your help. Quick question: according to the website, instructions will be sent to my school email but I have not received them. I think the reason why is that my high school blocks all external emails. Can I receive instructions directly on my personal email?

**Pull request merged**
