### PR TITLE
anasehir-k12-highschool added

### PR DESCRIPTION
**Pull request by tyaprak**
anasehir-k12-highschool added

### CODE REVIEW

**Comment by philipto** [comment]
@tyaprak Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by tyaprak** [comment]
Hi @philipto, please find necessary information below:
- https://www.anasehirkoleji.com/
- Bağlıca Mah. Etimesgut Bul. No:89 Etimesgut/ANKARA TÜRKİYE
- https://www.anasehirkoleji.com/bilisim-teknolojileri/
- Here is the Organisational Office 365 School account ownership:
anasehir-office365

**Comment by philipto** [comment]
@tyaprak  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by tyaprak** [comment]
Appreciated. @philipto

**Pull request merged**
