### PR TITLE
add sibs

### PR DESCRIPTION
**Pull request by hello-zhw**
add sibs.txt into lib/domain/

SINH, Shanghai Institute of Nutrition and Health, is an institute of Chinese Academy of Sciences, with many Master and Ph.D candidates students who major in computational biology and bioinformatics.

university official website: https://www.ucas.ac.cn/
institute official website: http://www.sinh.cas.cn/

### CODE REVIEW

**Comment by philipto** [comment]
@hello-zhw Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@hello-zhw You might miss my previous comment. Please react.

**Comment by hello-zhw** [comment]
@philipto Dir sir, we now use sibs.ac.cn because SINH was merged from some organizations of the SIBS, Shanghai Institutes of Biology Sciences, CAS. SIBS has completed institutional reform and our graduate students and staffs still use this domain and school surely recognize it.
http://english.sinh.cas.cn/aboutus/overview/
http://english.sinh.cas.cn/aboutus/contact/

**Comment by philipto** [comment]
@hello-zhw I am sorry, this organization is more like a research institution, not a school. Thus, I have to close the request without merging. 

If a particular student at this organization needs a free license for a JetBrains tool, it is always possible to apply apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students). Researchers can get their license for a fee but with academic discount. To get the discount, please send an email to sales@jetbrains.com.

Thank you for your understanding.

**Pull request closed without merging**
