### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by cuddIle**

### CODE REVIEW

**Comment by philipto** [comment]
@cuddIle Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@cuddIle You might miss my previous comment. Please react.

**Comment by cuddIle** [comment]
school website - https://masha.schooly.co.il/

School location - 
https://maps.app.goo.gl/cgthL1YJfSUWQJrU7?g_st=ic

School address - Israel, emek hefer, ein haoresh


It related program - apart from 3 years of computer Sienese lessons witch preper the students to their "bageut" exams witch are an important exams in Israel, the school offers a robotics program witch compit in the FLL (First Lego league) and also teaches other technology related subjects such as arduino, 3d printing, etc

the link to the team's facebook page appears on the menu on the official school site like shown in the image but I included the link here anyway

The link to the image - 
https://user-images.githubusercontent.com/54112779/212468239-24d0e8e0-4ad1-496f-a130-3b6d19cfb7cf.jpeg)

The link to the Facebook page - https://m.facebook.com/WingsOfDawnFLL

Now I'll be honest I don't know how to prove that the email is recognised by the school,I think that the ending "hityash" belong the the education department in the Israel government, the email address was given to my brother (witch attends the school and the robotics program) while the cornea virus as started and today it's uses mainly for google classroom and submitting homework 

If there is some sort of prof that I can the school for I will do so gladly, but for now I hope this is enough

**Comment by philipto** [comment]
@cuddIle First stage of verification passed, official domain is [m.facebook.com](https://m.facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/yavnek12/?locale2=de_DE

**Comment by philipto** [comment]
@cuddIle I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by cuddIle** [comment]
Hey I have answered you in the comment above @philipto

**Comment by cuddIle** [comment]
@philipto 

school website - https://masha.schooly.co.il/

School location -
https://maps.app.goo.gl/cgthL1YJfSUWQJrU7?g_st=ic

School address - Israel, emek hefer, ein haoresh

It related program - apart from 3 years of computer Sienese lessons witch preper the students to their "bageut" exams witch are an important exams in Israel, the school offers a robotics program witch compit in the FLL (First Lego league) and also teaches other technology related subjects such as arduino, 3d printing, etc

the link to the team's facebook page appears on the menu on the official school site like shown in the image but I included the link here anyway

The link to the image -
https://user-images.githubusercontent.com/54112779/212468239-24d0e8e0-4ad1-496f-a130-3b6d19cfb7cf.jpeg)

The link to the Facebook page - https://m.facebook.com/WingsOfDawnFLL

Now I'll be honest I don't know how to prove that the email is recognised by the school,I think that the ending "hityash" belong the the education department in the Israel government, the email address was given to my brother (witch attends the school and the robotics program) while the cornea virus as started and today it's uses mainly for google classroom and submitting homework

If there is some sort of prof that I can the school for I will do so gladly, but for now I hope this is enough

**Comment by cuddIle** [comment]
@philipto anyway I opened a new pull request

**Pull request closed without merging**
