### PR TITLE
add dhtm

### PR DESCRIPTION
**Pull request by hoangminh99vp**
add Thuongmai University

### CODE REVIEW

**Comment by philipto** [comment]
@hoangminh99vp Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by hoangminh99vp** [comment]
https://tmu.edu.vn/
https://vi.wikipedia.org/wiki/Tr%C6%B0%E1%BB%9Dng_%C4%90%E1%BA%A1i_h%E1%BB%8Dc_Th%C6%B0%C6%A1ng_m%E1%BA%A1i_(Vi%E1%BB%87t_Nam)
[image: image.png]

**Comment by philipto** [comment]
@hoangminh99vp I am sorry, could you please insert the image using GitHub web interface, otherwise it strips the image out of your comment?

**Comment by philipto** [comment]
@hoangminh99vp You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@hoangminh99vp I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
