### PR TITLE
Add The Stony Brook School to the list

### PR DESCRIPTION
**Pull request by MDNich**
Thank you so much for providing this program.

The website of my School is: https://sbs.org

It is a High School in Stony Brook, Long Island, NY, USA.

### CODE REVIEW

**Comment by philipto** [comment]
@MDNich First stage of verification passed, official domain is [sbs.org](https://sbs.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by MDNich** [comment]
Thank you very much! 
I truly appreciate the effort on the part of JetBrains for this opportunity.
:)

**Comment by philipto** [comment]
@MDNich Thank you for your patience while waiting for a review and processing your request. Pull request merged. Thank you!

**Comment by MDNich** [comment]
Thank you so much!

**Comment by MDNich** [comment]
I have a question @philipto, I tried to request the student license again but it would not let me, saying it was not in the list. How long do you think it would take for the database to update ? Thank you so much :)

**Comment by MDNich** [comment]
Captură de ecran din 2022-05-19 la 08 56 08

**Pull request merged**
