### PR TITLE
Added University College of Enterprise and Administration in Lublin

### PR DESCRIPTION
**Pull request by sebastianrozmus**
Added University College of Enterprise and Administration in Lublin

wspa.edu.pl

### CODE REVIEW

**Comment by sebastianrozmus** [comment]
https://wspa.pl/en/programs-bachelor-of-science/computer-science

**Comment by sebastianrozmus** [comment]
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

Do I have to provide this proof as the email domain is the same as website domain?

**Comment by philipto** [comment]
@sebastianrozmus The school website says that the contact emails in the school are in the domain @wspa.pl. You wish to add a domain @wspa.edu.pl. Thus, there has to be a page at the website, or another official instruction which says that the students have their email in @wspa.edu.pl domain. Please provide us with the URL of the page, or a .pdf of the instruction, or similar proof that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by sebastianrozmus** [comment]
Thank you for your comment. There is an instruction explaining how to login to @wspa.edu.pl mailbox but it is in polish: https://wspa.pl/pl/2017/10/10/bezplatny-microsoft-office-dla-wszystkich-studentow-wyzszej-szkoly-przedsiebiorczosci-i-administracji-w-lublinie-178


Is this enough or I need to find another proof?

**Comment by sebastianrozmus** [comment]
Also the domain of mailbox (http://wspa.edu.pl) redirects to the wspa.pl as well

**Comment by philipto** [comment]
@sebastianrozmus Yes, the instruction is exactly what we needed. Thank you for the update. Pull request merged.

**Pull request merged**
