### PR TITLE
 Add formation-cci12 

### PR DESCRIPTION
**Pull request by Mickap**
website : http://www.aveyron.cci.fr/
course : http://www.aveyron.cci.fr/formations/formations-alternance-apprentissage/formation-niveau-i-bac-5/3il/

### CODE REVIEW

**Comment by philipto** [comment]
@Mickap Please provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Mickap You might miss my previous comment. Please reply.

**Comment by Mickap** [comment]
@philipto I'm asking proof to my school.

**Comment by Mickap** [comment]
cci12

**Comment by philipto** [comment]
@Mickap I am sorry, let me explain my doubts to you honestly:
1) The whois data for formation-cci12.fr shows that the domain registered to an anonymous.
2) Google does not show any page where an address ending with "@formation-cci12.fr" is mentioned. It's not typical because usually students and teachers of a school publish some essays, articles, etc., with their email address mentioned, and I can not find any of them for your school.
3) The screenshot which you sent to us shows that you know someone who looks like an administrator of formation-cci12.fr account at Microsoft 365 Office, but there is no sign of any affiliation with your school, i.e. CCI Aveyron is not mentioned anywhere on the screenshot.
4) The official website http://www.aveyron.cci.fr/?s=formation-cci12.fr does not show a single page where the address ending with "@formation-cci12.fr" is mentioned. It is also not typical for a school to never mention their email address on the official website.

What could prove the affiliation between "@formation-cci12.fr" domain and your school well:
1) A document (.pdf or screenshot is OK) which tells the students that they are granted an email address in the domain @formation-cci12.fr as soon as they enrolled.
2) A document which explains some IT usage policy in the school, which tells the students that they can (or shall) use their email addresses in @formation-cci12.fr  domain.
3) An article, a conference proceedings, any kind of official document which includes a person's name and their @formation-cci12.fr address together with the name of your school. 

I really appreciate very much if you can provide us with any kind of the proof which shows the affiliation of your school and formation-cci12.fr  domain. Thank you!

**Comment by philipto** [comment]
@Mickap I am sorry, do you have any update on the matter? If not, can I contact someone from the university administration to check the validity and ownership of the domain? Who is the best contact? Thank you for the understanding.

**Comment by philipto** [comment]
@Mickap I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
