### PR TITLE
Create lyceedelasalle.txt

### PR DESCRIPTION
**Pull request by shobu13**

### CODE REVIEW

**Comment by shobu13** [comment]
add lyceedelasalle domain

**Comment by shobu13** [comment]
#### Institution/School Name 
lycee de La Salle

#### Instiution/School Website
http://www.lycee-delasalle.com/

#### Email Users
lelu.awen@hacari.org
lelu.a@lyceedelasalle.fr

*Please place an x between the square brackets if yes*
- [x] Students
- [ ] Academic/Teaching Staff
- [ ] Other/Support Staff
- [ ] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [x] Graduate School
- [ ] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [ ] High School or equivalent
- [ ] Elementary School or equivalent

**Comment by shobu13** [comment]
whois : https://image.noelshack.com/fichiers/2018/13/4/1522317955-whois.png
website :  https://image.noelshack.com/fichiers/2018/13/4/1522317955-adresse-lycee.png

**Comment by philipto** [comment]
@shobu13 Pull request merged. Thank you!

**Comment by shobu13** [comment]
thanks to you

**Pull request merged**
