### PR TITLE
Add European Humanities University

### PR DESCRIPTION
**Pull request by mikalai-karamach**
[Website](https://en.ehu.lt/)
[IT Bachelor's degree](https://en.ehu.lt/studies/computer-science/)
[Proof of using domain](https://en.ehu.lt/contacts/)

### CODE REVIEW

**Comment by philipto** [comment]
@mikalai-karamach First stage of verification passed, official domain is [en.ehu.lt](https://en.ehu.lt) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://en.ehu.lt/academics/bachelor/

**Comment by mikalai-karamach** [comment]
Hello @philipto ,
Thanks for bringing the update.

**Comment by mikalai-karamach** [comment]
@philipto do we have any updates?

**Comment by philipto** [comment]
@mikalai-karamach Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
