### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Matixo55**

### CODE REVIEW

**Comment by philipto** [comment]
@Matixo55 Please provide us with:
- the school official website URL, 
- an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Matixo55 You might miss my previous comment. Please react.

**Comment by Matixo55** [comment]
URL: https://lo160.edupage.org/ (its in Polish), Do you mean school's email or students personal email (the only proof would be Office account status)?

**Comment by philipto** [comment]
@Matixo55 Thank you! Yes, we need to see a copy of some official document which says that the school assigns the email addresses with a pattern username@160lo.pl to the students. It can be a webpage at the official website, or a paper on a school letterhead, or something similar.

WHOIS data says that the domain is registered to a private person, not to an organization. The data also do not disclose any name, thus we cannot check if the domain belongs to the school or not:

```
# whois 160lo.pl
DOMAIN NAME:           160lo.pl
registrant type:       individual
nameservers:           ns3.consultingservice.pl. [149.86.225.115]
                       ns4.consultingservice.pl. [149.86.224.103]
created:               2017.02.08 16:33:11
last modified:         2020.01.26 21:43:15
renewal date:          2021.02.08 16:33:11
dnssec:                Unsigned
REGISTRAR:
Consulting Service Sp. z o.o.
ul. Domaniewska 35A lok.1B
02-672 Warszawa
Polska/Poland
+48.221238080
domeny@ConsultingService.pl
```

**Comment by philipto** [comment]
@Matixo55 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
