### PR TITLE
Menedzerska Akademia Nauk Stosowanych w Warszawie

### PR DESCRIPTION
**Pull request by karwatka**

### CODE REVIEW

**Comment by philipto** [comment]
@karwatka First stage of verification passed, official domain is [mans.org.pl](https://mans.org.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@karwatka Thank you for your request. It was accidentally merged before the checks were performed, thus the merge was reverted. I am sorry for the inconvenience caused.

Please send an email to community-support@jetbrains.com and provide us with more details about the school:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

**Comment by karwatka** [comment]
the school official website URL is:  https://mans.org.pl/

the school street address, including city and country:  https://mans.org.pl/uczelnia/kontakt/ (ul. Kawęczyńska 36. 03-772 Warsaw, Poland)

IT-related long-term (>1 year) course:  https://www.mans.org.pl/en/programs/computer-engineering/

educational institution: a University

clarification: the institution promoted it's rank among Polish higher schools and changed it's name from Wyzsza Szkola Menedzerska (which already participated in the Program with domain wsm.warszawa.pl), but due to new name, students joining the University gains e-mail addresses in a new domain.

**Comment by karwatka** [comment]
@philipto Can we manage it? A new semester has just started and I wanted to let the students use Rider instead of other IDE's.

**Review by karwatka — COMMENTED** [review]
university name added

**Pull request merged**
