### PR TITLE
Create nscsd.txt

### PR DESCRIPTION
**Pull request by mjmalec**

### CODE REVIEW

**Comment by rtarson** [comment]
@mjmalec Wiered I just posted for my college cayuga and now you post a school i went to veryyyy  wierd!

Do you have harbinger as your teacher?

**Comment by mjmalec** [comment]
I'm actually still at the junior high and happen to be the only one who actually codes in the school :)
But I had Nadler this year. I'm in that 4D Productions that he runs.

**Comment by rtarson** [comment]
@mjmalec that is pretty cool. When you get to the high school your teacher most likely will be harbinger. He’s a pretty cool guy. I was looking at the pull request on github saw NSCSD and I was like waaiiitt a second hahaha. I just find it wierd with jet brains being for global to see a pull request with someone nearby haha. 

They give students nscsd emails now? I haven’t been in the district for 2 years now.

**Comment by mjmalec** [comment]
He definitely sounds cool! And yeah, they got Google Apps just a year or so ago. Completely got rid of the Office 365 solution. So all the kids have a funky 22mmalec@g.nscsd.org email (that's mine) with the 22 being the year I graduate.

**Comment by rtarson** [comment]
@mjmalec Wonder why they have to add the year. They must archive that shit. haha, wonder why they part ways with office365

**Comment by philipto** [comment]
@mjmalec Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by mjmalec** [comment]
Thank you @phillipto ! I appreciate the help!

**Pull request merged**
