### PR TITLE
add Toyo University INIAD

### PR DESCRIPTION
**Pull request by xrozl**

### CODE REVIEW

**Comment by xrozl** [comment]
HP: https://www.iniad.org/
Whois: https://who.is/whois/iniad.org

INIAD is a department of the Oriental University, but email address and domain are different.

**Comment by philipto** [comment]
@xrozl First stage of verification passed, official domain is [iniad.org](https://iniad.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by xrozl** [comment]
@philipto 
Thanks for reply.
If you need any assistance, please feel free to contact us.

**Comment by philipto** [comment]
@xrozl Pull request merged. Thank you.

**Pull request merged**
