### PR TITLE
colegiosperuanos.txt

### PR DESCRIPTION
**Pull request by jsaraviadrago**

### CODE REVIEW

**Comment by jsaraviadrago** [comment]
File for colegiosperuanos

**Comment by philipto** [comment]
@jsaraviadrago First stage of verification passed, official domain is [innovaschools.edu.pe](https://innovaschools.edu.pe) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.innovaschools.edu.pe/terminos-y-condiciones-coco/

**Comment by philipto** [comment]
@jsaraviadrago Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by jsaraviadrago** [comment]
Hi! 

Actually it’s a network of schools and inside the curricula their is IT throughout the scholarship (13 years). 

https://www.innovaschools.edu.pe/

Let me know if this helps.

Regards! 

Juan Carlos Saravia Drago
jsaraviadrago.com

**Comment by philipto** [comment]
Dear Juan Carlos Saravia Drago @jsaraviadrago!

Regrettably, this domain seems to represent an umbrella institution (a network of schools), not a specific single university or a college. Therefore, it is not eligible for being added to this repository. Please see the detailed repository rules at the bottom of [this page](https://github.com/JetBrains/swot).

Also, the website https://www.innovaschools.edu.pe/ does not describe the schools in details, and it's impossible to verify whether the schools need professional software development tools for their curriculum. The website makes possible to assume that the schools are elementary schools for children under 13 of age.

It is likely that the students' needs at the school can be satisfied with IntelliJ IDEA Community and PyCharm Community Edition, which are free for everyone.

If you think otherwise, please apply for free educational license with an official document which proves that you are a student or a teacher at the school. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
