### PR TITLE
add cpcc.txt

### PR DESCRIPTION
**Pull request by dinghongchao**
add cpcc.txt

### CODE REVIEW

**Comment by dinghongchao** [comment]
qzq h kqzm f5f_ 574f_f

School website:http://www.cpcc.edu/

**Comment by dinghongchao** [comment]
I like programming very much, hope to get jetbrains'tool to learn more knowledge. Thank you very much

**Comment by philipto** [comment]
@dinghongchao Pull request merged. Please notice that the free licenses we grant student with are for high and higher education students, and for educational purpose only. Thank you!

**Comment by dinghongchao** [comment]
thank you very much

**Comment by dinghongchao** [comment]
@philipto  Yes i do.Thank you very much

**Pull request merged**
