### PR TITLE
Create scilijas.txt

### PR DESCRIPTION
**Pull request by SpahoAP**

### CODE REVIEW

**Comment by philipto** [comment]
@SpahoAP First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.facebook.com/srednjoskolski/photos/a.2402188190037483/3087471204842508/?type=3

**Comment by SpahoAP** [comment]
Hello,
Sorry I reply now.

Here is the requested information:
the school official website URL: https://scilijas.com.ba/

the school full official name: JU Srednjoškolski centar "Nedžad Ibrišimović" Ilijaš
the school street address, including city and country: 
Kakanjska 16
Ilijaš
Bosnia and Herzegovina
an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: Our school uses google classroom platform for that. But on syllabus of curriculum we offer Programming 1, Programming 2, Programming 3, Programming 4 - that is long-term course: https://scilijas.com.ba/uploads/doc/Nastavni_plan_2022.pdf page 9 - Programiranje 

For domain https://mo.ks.gov.ba/node/62477 - official website of the competent Ministry of Education

Sincerely,
Alem Spaho

**Comment by philipto** [comment]
@SpahoAP First stage of verification passed, official domain is [scilijas.com.ba](https://scilijas.com.ba) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@SpahoAP You might miss my previous comment. Please react.

**Pull request closed without merging**
