### PR TITLE
Create rascol.txt

### PR DESCRIPTION
**Pull request by thomasbnt**
Lycée public général et professionnel dans l'Occitanie ( 81 ) 
Website : http://www.rascol.net

### CODE REVIEW

**Comment by philipto** [comment]
@thomasbnt Pull request merged. Shall we keep the domain @rascol.fr in the list as well?

**Comment by thomasbnt** [comment]
No , you can erase the domain .fr

**Comment by philipto** [comment]
@thomasbnt Yes, waiting period is about 30 minutes, thus it has to be over now. I am removing rascol.fr as per this request. Thank you!

**Comment by thomasbnt** [comment]
@philipto for ``e.rascol.net`` domain, I need to create ``e.rascol.txt`` or not?

**Comment by philipto** [comment]
@thomasbnt As soon as rascol.net is in the list, all subdomains are covered already. You don't need to do extra steps.

**Comment by thomasbnt** [comment]
Hoh it's fantastic! thank you !

**Pull request merged**
