### PR TITLE
[feature] add National Singang Senior High School of Arts, Taiwan

### PR DESCRIPTION
**Pull request by murphy0010**
I’d like to apply your account through my school’s mailbox with sgash.cyc.edut.tw. 
It would be appreciated if you approve my application.

### CODE REVIEW

**Comment by philipto** [comment]
@murphy0010 First stage of verification passed, official domain is [sgash.cyc.edu.tw](https://sgash.cyc.edu.tw) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@murphy0010 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@murphy0010 You might miss my previous comment. Please react.

**Comment by murphy0010** [comment]
1. the school official website URL
https://www.sgash.cyc.edu.tw/

2. the school street address, including city and country
a. english address
No. 1, Yigao Rd., Xingang Township, Chiayi County 616009 , Taiwan (R.O.C.)
b. chinese address
台灣嘉義縣新港鄉宮後村藝高路1號
c.Google Map link
https://goo.gl/maps/4CKViNZrAQHzc4Du7

3. an URL of a page on the official website where the school offers an
IT-related long-term (>1 year) course
https://www.sgash.cyc.edu.tw/ischool/publish_page/27/
http://140.130.169.22/podcasts/50?locale=zh_tw

4. a proof, which shows that the school recognizes the domain you are
submitting as an official email domain for the students.

attachment file[image: image.png]

Philip Torchinsky ***@***.***> 於 2023年5月17日 週三 上午11:34寫道：

**Comment by philipto** [comment]
@murphy0010 Thank you for the clarification. Regrettably, I did not found an evidence of offering any IT-related long-term courses at https://www.sgash.cyc.edu.tw/ischool/publish_page/27. Podcasts are also not an evidence. 

Therefore, I have to close the request without merging. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Pull request closed without merging**
