### PR TITLE
Create isartdigital

### PR DESCRIPTION
**Pull request by Vrashq**

### CODE REVIEW

**Comment by Vrashq** [comment]
Create a file for Covenant University, domain is @student.isartdigital.com

**Comment by philipto** [comment]
@Vrashq excuse me, why did you comment your pull request mentioning Covenant University? Is it somehow related to ISART Digital?

**Comment by Vrashq** [comment]
Ohw, I was so tired. I looked the other pull requests and copy paste like a dump.
It's for the Isart Digital school of coure ><

**Comment by philipto** [comment]
@Vrashq I am sorry for a delay with processing your request. The issue is now clear. Could you please rename lib/domains/com/isartdigital to lib/domains/com/isartdigital.txt in order to reflect this repository rules? As soon as you do it, I merge the pull request. Thank you!

**Comment by Vrashq** [comment]
Done :)

**Comment by philipto** [comment]
@Vrashq Pull request is now merged. Thank you!

**Pull request merged**
