### PR TITLE
Correct domain for Centrum Kształcenia Zawodowego

### PR DESCRIPTION
**Pull request by danokn**

### CODE REVIEW

**Comment by philipto** [comment]
@danokn Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@danokn You might miss my previous comment. Please react.

**Comment by danokn** [comment]
I am a teacher in this school Centrum Kształcenia Zawodowego (previous name Centrum Kształcenia Praktycznego): 
This is a technical high school in Siedlce.

- http://ckz.siedlce.pl/www/pl/strona/1/strona.glowna.html  - official webside

- Konarskiego 9, 08-110 Siedlce - address

- http://ckz.siedlce.pl/www/pl/strona/329/333/346/dzial.elektryczno-elektroniczny.html  - education offer from electronic area

**Comment by philipto** [comment]
@danokn Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
