### PR TITLE
Adding my Uni

### PR DESCRIPTION
**Pull request by SleeplessChallenger**

### CODE REVIEW

**Comment by philipto** [comment]
@SleeplessChallenger Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by SleeplessChallenger** [comment]
Hello!

Here are the links:
1. https://office365.urfu.ru/Documents/Regulation_russia.pdf official doc
from the dean of the University about office 365 where at the 4th page you
can read verbose descriptions about which email addresses can be used
2.  https://urfu.ru/ru/about/personal-pages/Personal/person/ksokhag/ it is
a professor from my university. You can view his publications in the
dedicated section

If it works, then OK. If not -> please, specify what's wrong

пт, 12 нояб. 2021 г. в 15:22, Philip Torchinsky ***@***.***>:

**Comment by philipto** [comment]
@SleeplessChallenger Hello! Thank you for the additional information. Regrettably, none of the documents and pages that you cited in your response mentions urfume.onmicrosoft.com as a recognized email domain for the students. 

However I found an independent proof of the domain ownership at https://scholar.google.com/citations?user=g8N-iuQAAAAJ&hl=ru

Therefore I successfully merged your request. Congratulations, and thank you!

**Comment by SleeplessChallenger** [comment]
Thanks! For now, is there a way to get PyCharm due to being a verified student or should I wait?

**Comment by SleeplessChallenger** [comment]
Hello! I wanted to ask: will you send code to my Uni address or somewhere? I've been checking it periodically and haven't stumbled upon your email. Thanks

**Pull request merged**
