### PR TITLE
Add Cedars Upper School

### PR DESCRIPTION
**Pull request by SamboyCoding**

### CODE REVIEW

**Comment by SamboyCoding** [comment]
School website: [http://www.cedarsupper.org.uk/](http://www.cedarsupper.org.uk/)

**Comment by SamboyCoding** [comment]
37c9e1f0df1614634440d49695583569

**Comment by philipto** [comment]
@SamboyCoding Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by SamboyCoding** [comment]
Thanks!

**Pull request merged**
