### PR TITLE
Adding Barnard (B.E.S.T) school

### PR DESCRIPTION
**Pull request by omarTheCode**

### CODE REVIEW

**Comment by philipto** [comment]
@omarTheCode 
Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@omarTheCode You might miss my previous comment. Please react.

**Comment by omarTheCode** [comment]
OK
Website: https://sites.google.com/nhps.net/barnard/home
Address: 170 Derby Ave. New Haven, CT 06511
Technology course: https://sites.google.com/nhps.net/technologyclass/home
And finally, the email that I sent was my personal School email that the school gave me, the school does not have an official email, though there is the Principles email which is stephanie.skiba@nhboe.net

**Comment by philipto** [comment]
@omarTheCode Thank you for your response.

I am sorry, I don't understand your comment. What is @nhps.net? Is it a domain that your school owns? If yes, how can we check it? Do you have any printed or electronic message from the school that says you are assigned with an email address @nhps.net? If yes, please upload it as a comment to this request using your browser. If not, we cannot add it to the trusted list.

I strongly recommend you using another option to get a free license:  enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

Thank you for your understanding!

**Comment by omarTheCode** [comment]
Yes, you are correct, the only problem Is I have been given that email address the day I enrolled into Barnard ( aka 1st grade) So that letter has most likely been lost to time. The only thing that I know is that @nhps means New Haven Public Schools, and all school email address are the students ids followed by @nhps.net (ex 123456@nhps.net)

**Comment by philipto** [comment]
@omarTheCode  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Comment by omarTheCode** [comment]
There is a problem, my school auto blocks any emails sent by people out of school.

**Comment by philipto** [comment]
@omarTheCode If your school auto blocks any emails sent by people out of school, it's absolutely impossible for you to get a free license based on email address provided by the school. You need to use another option. They are:

1. Enroll to GitHub Student Developer Program at https://education.github.com/discount_requests/application. Then apply for JetBrains educational subscription with your GitHub account (GitHub tab at https://www.jetbrains.com/shop/eform/students).

2. Get a paid ISIC card from your ISIC provider. You can find one for your country at https://www.isic.org. Then apply for your free license with your ISIC card at https://www.jetbrains.com/shop/eform/students.

3. Ask your teacher or school administration to apply for the classroom license here: https://www.jetbrains.com/shop/eform/classroom/faculty. Then the teacher gets licenses for the entire class, and assign the licenses to computers in the class or to individual students.

**Comment by omarTheCode** [comment]
Thank you @philipto for the help, I will probably try to get a git hub student License. Though they dont allow you yo upload pictures from my computer online. 

All the best - Omar

**Pull request merged**
