### PR TITLE
Added Northen University of Baia Mare

### PR DESCRIPTION
**Pull request by pauldan92**

### CODE REVIEW

**Comment by skate4life** [comment]
I'm sorry for my sloppiness as I am new with git. My email is actually @student.unbm.ro , and i don't know witch format is correct, the student.unbm.txt or the unbm.txt.

**Comment by krisavi** [comment]
Hi, for your help you should probably make file in this location: lib/domains/ro/unbm/student.txt
I think Philip can only confirm it.

**Comment by philipto** [comment]
@pauldan92 Your pull request seems to be a bit contradicting to  #1759. May I ask you to check that pull request first? Why don't UNBM students get their emais in utcluj.didatec.ro domain? Does Technical University of Cluj-Napoca have several domains? Which ones, along with utcluj.didatec.ro and student.unbm.ro? It may make sense to add all of them at once, to make things simpler.

As for the file path, for student.unbm.ro domain it has to be `lib/domains/ro/unmb/student.txt`. Thank you!

**Comment by pauldan92** [comment]
As you can see on the footer of the page, there are multiple extensions like "Centrul Universitar Nord Baia-Mare", for instance, and multiple mail domains. I don't know all of them, I only know our own. Since we merged with the University of Cluj-Napoca two years ago they kept different domains. So, they might be more for the other cities, but I don't know about those.

**Comment by krisavi** [comment]
I think he might have made a type about the path, but you should follow the "format" of it. 

The whole university branches are making the whitelisting quite a lot more difficult. In that matter it would be easier if someone from university IT support is explaining the domains and making the pull request.

In current case I see that yes, there are multiple domains used by same university.

**Comment by pauldan92** [comment]
Created a new pull request.

https://github.com/JetBrains/swot/pull/1799

**Pull request closed without merging**
