### PR TITLE
add gvsd wes

### PR DESCRIPTION
**Pull request by Kratos1top**

### CODE REVIEW

**Comment by philipto** [comment]
@Kratos1top First stage of verification passed, official domain is [wes.gvsd.ca](https://wes.gvsd.ca) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Kratos1top Could you please confirm that the school has students who are over 13 of age, and offer them a program, which is somehow related to software development?

**Comment by philipto** [comment]
@Kratos1top Could you please confirm that the school has students who are over 13 of age, and offer them a program, which is somehow related to software development?

**Comment by Kratos1top** [comment]
> @Kratos1top Could you please confirm that the school has students who are over 13 of age, and offer them a program, which is somehow related to software development?

**Pull request closed without merging**
