### PR TITLE
Adding Conservatoire National Supérieur de Musique et de Danse de Paris

### PR DESCRIPTION
**Pull request by deneiel**

### CODE REVIEW

**Comment by philipto** [comment]
@deneiel I am sorry for a delay with processing your pull request. Your university is formally eligible for inclusion into this repository, however I do not see any IT-related educational programs announced on the Conservatoire website. Could you please tell us a bit more about why would you like to add cnsmdp.fr to the repository?

**Comment by deneiel** [comment]
Hello, yes the CNSMDP do not offer any IT-related program, anyway, i'm student of movement notation Benesh, and as part of my professional research i'm developing a software for writing body  movement, this software will be able to translate scores from other notation sistems like Laban or Conte, and  to translate movement itself.

**Comment by deneiel** [comment]
Thank you

**Comment by philipto** [comment]
@deneiel Thank you for the clarification! Pull request merged.

**Pull request merged**
