### PR TITLE
Add SMK Negeri 4 Bogor

### PR DESCRIPTION
**Pull request by akbarsiddic**

### CODE REVIEW

**Comment by philipto** [comment]
@akbarsiddic First stage of verification passed, official domain is [smkn4bogor.sch.id](https://smkn4bogor.sch.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@akbarsiddic Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@akbarsiddic You might miss my previous comment. Please react.

**Comment by akbarsiddic** [comment]
Sorry for my late reply, SMK Negeri 4 Provide IT Related course for > 1
years, u can see it here

https://smkn4bogor.sch.id/tentang-kami/kompetensi-keahlian/ppl

**Comment by akbarsiddic** [comment]
sorry for the late reply, SMK NEGERI 4 Provide IT Related course for > 1
years
u can see it here
https://smkn4bogor.sch.id/tentang-kami/kompetensi-keahlian/pplg

**Comment by philipto** [comment]
@akbarsiddic  Thank you for the clarifications. Pull request merged.

**Pull request merged**
