### PR TITLE
Shanker dev campus added

### PR DESCRIPTION
**Pull request by bhandariprabin**
Shanker Dev Campus Added for the jetbrains licence

### CODE REVIEW

**Comment by philipto** [comment]
@bhandariprabin Please provide us with:
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you.

**Comment by philipto** [comment]
@bhandariprabin You might miss my previous comment. Please react.

**Comment by bhandariprabin** [comment]
Here is the URL of my college
https://www.shankerdevcampus.edu.np/

IT course being offered by college is Bachelor of Information Management BIM
Being offered since 2013.
It is the constituent's college of Tribhuvan University which is one of the leading government universities of Nepal.

I have attached the Course Detail image for your convenience. Please have a look.

________________________________

**Comment by philipto** [comment]
@bhandariprabin Please upload the image directly to https://github.com/JetBrains/swot/pull/17093 as a comment. Do not send it by email because GitHub strips out all attachments sent by email. Thank you.

**Comment by prabinvandary** [comment]
Url of college:https://www.shankerdevcampus.edu.np/

Shankerdev Campus is a constituents college of Tribhuvan University which is one of the leading government university of Nepal. 
Here is the attachment of proof of IT course being offered by my college.

**Comment by philipto** [comment]
@bhandariprabin  Thank you for the clarifications. Pull request merged.

**Comment by prabinvandary** [comment]
Thank you so much. It's great that Intellij is helping us, students from developing nations like Nepal. It will help to build our future.

**Pull request merged**
