### PR TITLE
Add 'Faculdade COTEMIG'

### PR DESCRIPTION
**Pull request by iagopiimenta**
University official website: [cotemig.com.br](http://cotemig.com.br/) - **Teachers** only(Already added)
This PR contains **students** domain.

### CODE REVIEW

**Comment by philipto** [comment]
@iagopiimenta Could you please give us a link to a page or a document which confirms that students in the university use @aluno.faculdadecotemig.br email domain?

**Comment by philipto** [comment]
@iagopiimenta You might miss my previous comment. Please comment on the issue described above. Thank you.

**Comment by iagopiimenta** [comment]
@philipto We do not have a page or official document confirming the use of the domain by the students. I'm checking somehow along with college.

**Comment by philipto** [comment]
@iagopiimenta No problem. University often publish some instructions for students where it can be seen. I found another proof, which is enough for us, a student address from your university is mentioned here: https://github.com/TuCaO96/condominio/blob/master/src/br/com/condominio/controllers/MoradorController.java, and I have an independent proof that he is the student of your university. Pull request merged. Thank you.

**Pull request merged**
