### PR TITLE
created school4games.txt

### PR DESCRIPTION
**Pull request by SradnickDev**
created school4games.txt

### CODE REVIEW

**Comment by SradnickDev** [comment]
https://www.school4games.net

**Comment by SradnickDev** [comment]
https://www.school4games.net/ # adress
https://www.school4games.net/game-engineering.html # education
https://www.school4games.net/infos.html#impressum # proof for the domain

**Comment by SradnickDev** [comment]
@philipto Hello, does it require anything else ?

**Comment by philipto** [comment]
@SradnickDev I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Comment by SradnickDev** [comment]
Thank you ! :)

**Pull request merged**
