### PR TITLE
Check for alumno.uned.es

### PR DESCRIPTION
**Pull request by emauricio**
alumno.uned.es is a valid university domain.

information about the email:
https://serviweb.uned.es/ciberuned/publico/correo-alumnos.asp

> Las direcciones de correo-e de alumno son de la forma xxxxxx@alumno.uned.es donde xxxxxx coincide con el identificador de usuario.
> Student email addresses are of the form xxxxxx@alumno.uned.es where xxxxxx coincides with the user identifier.

### CODE REVIEW

**Comment by philipto** [comment]
@emauricio lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by emauricio** [comment]
@philipto thank you for your reply, 
`lib/domains/stoplist.txt` seems to be the correct path, I did not change it.

In this PR, I just added the English name of the university and remove it from the block list. 

I guess it was added here with another domain
https://github.com/JetBrains/swot/commit/81fc413a976f6023a5318bd47ab7da798f51ccd3

perhaps a miss due to the similarity between `alumni` and `alumno`, but that is Spanish.

should I add this additional information to the uned.txt?

The English site of the university is here 
https://www.uned.es/universidad/inicio/en/

Additional page about email:
http://portal.uned.es/portal/page?_pageid=93,70613733&_dad=portal&_schema=PORTAL

a snip from the text.

>[es] Asociado a su identificador se ha activado su dirección de correo de alumno de la UNED (xxxxxxxx@alumno.uned.es) la cual será utilizada para cualquier tipo de COMUNICACIÓN DOCENTE Y ADMINISTRATIVA relacionada con sus estudios así como en sus Cursos Virtuales. Una vez autenticado podrá acceder a la información relacionada con su cuenta en la página del estudiante.
>[en] Associated with your identifier, your UNED student email address (xxxxxxxx@alumno.uned.es) has been activated, which will be used for any type of TEACHING AND ADMINISTRATIVE COMMUNICATION related to your studies as well as in your Virtual Courses. Once authenticated you will be able to access the information related to your account on the student page.

**Comment by philipto** [comment]
@emauricio lib/domains/stoplist.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@emauricio Thank you for your request. The file stoplist.txt is not for a customization. The repository rules do not encourage anyone to change it.

As for the root of the issue, this domain alumno.uned.es was removed from our trusted domains list because one of the following happened: 

1) the school allows to register an email address there even if you are not a student of the school. 
2) someone from the school shared their account details publicly, or sold it, and it lead to broad account misuse and license terms violation.

Therefore, we are not able to identify if the people with addresses in these email domain are actual students or not.

If you are the student of this school, please apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Pull request closed without merging**
