### PR TITLE
Add teacher domain - primocircoloquarto.edu.it 

### PR DESCRIPTION
**Pull request by gennarosdc**
Hi All,

I would like to add the domain of school "Direzione Didattica 1 Circolo Quarto" in order to let teachers use the JetBrains tool.

This is the website where teachers of school usually log in:
https://www.primocircoloquarto.edu.it/area-riservata/

Thanks
Gennaro

### CODE REVIEW

**Comment by philipto** [comment]
@gennarosdc First stage of verification passed, official domain for **Direzione Didattica 1 Circolo Quarto** is [primocircoloquarto.edu.it](https://primocircoloquarto.edu.it) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@gennarosdc Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@gennarosdc You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@gennarosdc Please explain what the organization that own the domain does. The name of the organization suggests that it is not a school, but a kind of government organization.

**Comment by gennarosdc** [comment]
Hi,

Sorry for the delay but is hard to me find all information you requested.

For the moment I can say the organization that owns the domains is a primary and secondary school located in Quarto Napoli Italy.

So is not a government organization.

The official website is https://www.primocircoloquarto.edu.it/

Actually I am not able to provide you other informations or certifications for deep investigation.

Thanks
Gennaro Schiano di Cola

Il giorno 24 set 2024, alle ore 09:24, Philip Torchinsky ***@***.***> ha scritto:

﻿

@gennarosdc<https://github.com/gennarosdc> Please explain what the organization that own the domain does. The name of the organization suggests that it is not a school, but a kind of government organization.

**Comment by philipto** [comment]
Dear @gennarosdc!
Thank you for the update. The problem is that the website of the school is not completed and looks like it may be a fake. Please see the screenshot below (translated to English with translator extension).

image

Due to security reasons we cannot approve an email domain for the trusted list here if we cannot verify it correctly.
I apologize for the inconvenience, but I have to close the request without merging.

What I suggest with regard to using JetBrains tool at school:
1. You can use IntelliJ IDEA Community and PyCharm Community Edition for any purpose without any subscription at all. They are free for everybody.
2. If you need another tool, please send us an email to community-support@jetbrains.com, and we'll discuss possible licensing options with you.
3. If it's OK for you to use JetBrains tools in your school's classrooms, please consider applying for classroom licenses here: https://www.jetbrains.com/shop/eform/classroom/faculty It will be necessary to prove your teacher's status and employment at the school when applying.

Thank you for your patience and understanding!

**Pull request closed without merging**
