### PR TITLE
add stellamarisdavao.txt

### PR DESCRIPTION
**Pull request by twocngdagz**
School official website URL: https://www.stellamarisdavao.edu.ph/

I understand that the school needs to offer an IT course, but my son is still in highschool 13 yrs old and he has a subject that has web development and like him to get familiar with using PHP Storm that is why I'm registering his school.

Thanks

### CODE REVIEW

**Comment by philipto** [comment]
@twocngdagz First stage of verification passed, official domain is [stellamarisdavao.edu.ph](https://stellamarisdavao.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@twocngdagz Regrettably, this request has signs of fraud. I have to close it without merging.

image

**Comment by twocngdagz** [comment]
Hi @philipto , can you clarify to me why is this request is fraud?

Thanks

**Comment by twocngdagz** [comment]
@philipto 

Can you please check this again.

Thank you very much for looking at this.

**Pull request closed without merging**
