### PR TITLE
por.gdst.net - Girls Day School Trust

### PR DESCRIPTION
**Pull request by salgieri**

### CODE REVIEW

**Comment by philipto** [comment]
@salgieri Could you please give us a reference to a page on the official website where the school(s) offer long-term (> 1 year) IT-related educational program?

Could you please also confirm with a reference to official page that emails in @por.gdst.net domain are available to students and teachers only, not to alumni?

**Comment by salgieri** [comment]
Hi Phillip

GDST makes up a collection of 18 schools in the UK from nursery to sixth form.

My wife works specifically for the Portsmouth High School for Girls (hence the por in por.gdst.net. Here's their webpage:

http://www.portsmouthhigh.co.uk/

ICT with Programming starts early in the Junior School and progress through into Senior School. Please see this page for the Junior school:

http://www.portsmouthhigh.co.uk/junior-school/curriculum

Alumni only use they're own emails when registering and are not provided with a por.gdst.net address, as per the sign up form here:

https://alumnae.gdst.net/portal/public/register/register.aspx

Hope that helps.

Thanks

**Comment by philipto** [comment]
@salgieri Thank you very much for the clarification! I am ready to merge your pull request. I have just one minor concern: don't you mind changing the description of the school to "Portsmouth High School for Girls", given that the email domain belongs to this institution? Could you please make the change?

**Comment by salgieri** [comment]
@philipto all done. Thanks.

**Comment by philipto** [comment]
@salgieri I reopened and merged the pull request. Thank you!

**Pull request merged**
