### PR TITLE
Add my school domain - zsoiz-krobia.edu.pl

### PR DESCRIPTION
**Pull request by ao-code-dev**
https://zsoiz-krobia.edu.pl/

### CODE REVIEW

**Comment by philipto** [comment]
@ao-code-dev First stage of verification passed, official domain for **Zespół Szkół Ogólnokształcących i Zawodowych w Krobi** is [zsoiz-krobia.edu.pl](https://zsoiz-krobia.edu.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by ao-code-dev** [comment]
Hi @philipto thanks for the information. What's next? When will my school domain be added?

**Comment by philipto** [comment]
@ao-code-dev Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by ao-code-dev** [comment]
@philipto Thank you for considering my pull request. I have one last question - did something go wrong or will the system recognize my school domain after some time?

image

**Comment by philipto** [comment]
It takes about 60 minutes to propagate the update through the systems. Please try again in an hour. Thank you!On 20. Mar 2024, at 18.04, ao-code-dev ***@***.***> wrote:﻿
@philipto Thank you for considering my pull request. I have one last question - did something go wrong or will the system recognize my school domain after some time?
image.png (view on web)

**Pull request merged**
