### PR TITLE
Create liceovolta.txt

### PR DESCRIPTION
**Pull request by gianlucapetito**
LICEO SCIENTIFICO STATALE "A. VOLTA"

### CODE REVIEW

**Comment by philipto** [comment]
@gianlucapetito Please provide us with:
- the school official website URL, 
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by gianlucapetito** [comment]
Hi,

in real the school have 3 official website urls: liceovolta.it,
liceovolta.edu.it and voltaweb.it
to students and teachers is assigned voltaweb.it because on that domain is
active g-suite for educational (maybe I should add voltaweb.it to the swot)

in the screenshot of our website, in the contacts, you can see that the
email address of the boss (dirigente scolastico) is voltaweb.it
(https://www.liceovolta.it/nuovo/la-scuola/contatti)
[image: Schermata 2020-03-18 alle 21.28.06.png]

Il giorno mer 18 mar 2020 alle ore 19:04 Philip Torchinsky <
notifications@github.com> ha scritto:

**Comment by philipto** [comment]
@gianlucapetito I am sorry, I a bit confused now. Which email domain you need to add now?
Shall I add all of the domains, or just one of them? 

You said that all of the domains are official for the school:
liceovolta.it
liceovolta.edu.it
voltaweb.it

Do you wish to add all of them?
Thank you!

**Comment by gianlucapetito** [comment]
yeah, you are right, I’m sorry.
What do you need to add, to swot, to let students and teachers get free
licenses of software?
If you need emails domain, we can just add voltaweb.it



Il giorno lun 23 mar 2020 alle ore 13:03 Philip Torchinsky <
notifications@github.com> ha scritto:

**Comment by philipto** [comment]
@gianlucapetito I am sorry for a delay with processing your request.
I already added voltaweb.it on your behalf, and close this request without merging.

**Comment by gianlucapetito** [comment]
thank you very much!

Il giorno lun 30 mar 2020 alle ore 18:43 Philip Torchinsky <
notifications@github.com> ha scritto:

**Pull request closed without merging**
