### PR TITLE
Create ksmenzingen.txt

### PR DESCRIPTION
**Pull request by triner-ksm**
Webpage: ksmenzingen.ch
Curriculum: https://www.zg.ch/behoerden/direktion-fur-bildung-und-kultur/ksm/unterricht/grundlegende-dokumente/downloads/hsgym-hochschule-und-gymnasium-hochschulreife-und-studierfaehigkeit-2009-langfassung/download
Mail: https://www.zg.ch/behoerden/direktion-fur-bildung-und-kultur/ksm/organisation/personen/lehrpersonen

### CODE REVIEW

**Comment by KiraBobyleva** [comment]
Hello @triner-ksm,

Thanks for your pull request. I can see that the contacts on the website of your school have @zg.ch domain, while you're requesting @ksmenzinge.ch to be added.

Could you please let me know with which domain you plan to apply for licenses?

**Comment by KiraBobyleva** [comment]
Hello @triner-ksm, thank you. Could you please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students?

**Comment by philipto** [comment]
@triner-ksm You might miss our previous comment. Please respond.

**Comment by triner-ksm** [comment]
[WLAN KSM.pdf](https://github.com/JetBrains/swot/files/9038948/WLAN.KSM.pdf)

i hope this is enough of proof

**Comment by philipto** [comment]
@triner-ksm  Thank you for the clarifications. Pull request merged.

**Pull request merged**
