### PR TITLE
Create mns.txt

### PR DESCRIPTION
**Pull request by alimoenes**
School website: https://mns.edu.eg/
I teach OL & AL Computer science for grades 11 & 12: https://mns.edu.eg/british/academics-british/key-stage-4/
Here is the syllabus: https://drive.google.com/file/d/1ITJl6rNh8yDJu5V3whDTZzwUkQgZXkN8/view?usp=drivesdk

### CODE REVIEW

**Comment by philipto** [comment]
@alimoenes First stage of verification passed, official domain is [mns.edu.eg](https://mns.edu.eg) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@alimoenes You might miss my previous comment. Please react.

**Comment by alimoenes** [comment]
It’s hosted at a service provider called A2 Hosting this is their website:
https://www.a2hosting.com

**Comment by philipto** [comment]
@alimoenes  Thank you for the clarifications. Pull request merged.

**Comment by alimoenes** [comment]
Thank you for your help!

**Pull request merged**
