### PR TITLE
I want to add www.elis.org

### PR DESCRIPTION
**Pull request by pbaca83**
we're an University (IT Engineering) : https://www.elis.org/education-training/corso-ingegneria-digitale/

### CODE REVIEW

**Comment by philipto** [comment]
@pbaca83 Please provide us with:
* Full official school name
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@pbaca83 You might miss my previous comment. Please react.

**Comment by pbaca83** [comment]
Hello,

  *   school name is: ELIS
  *   www.elis.org<http://www.elis.org/>
  *   Via Sandro Sandri 81, 00159 Roma, Italy
  *   This page describes the IT Engineering course: https://www.elis.org/education-training/corso-ingegneria-digitale/ (3 years)
  *   Employees domain is elis.org, student’s email domain is edu.elis.org
  *   Plus: we’re a no profit organization

Many thanks


-
--
Piero Bacarella
IT Operations Manager @ ELIS
Via Sandro Sandri 81 - 00159<tel:+398100159> ROMA
Mobile: +39-346-2372967<tel:+393462372967>
Desk: +39-06-4592-4396<tel:+390645924396>
Email: ***@***.******@***.***>

Da: Philip Torchinsky ***@***.***>
Data: lunedì, 15 maggio 2023, 11:17
A: JetBrains/swot ***@***.***>
Cc: Piero Bacarella (SIE) ***@***.***>, Mention ***@***.***>
Oggetto: Re: [JetBrains/swot] I want to add www.elis.org (PR #17463)

@pbaca83<https://github.com/pbaca83> Please provide us with:

  *   Full official school name
  *   the school official website URL
  *   the school street address, including city and country
  *   an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
  *   a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@pbaca83  Thank you for the clarifications. Pull request merged.

**Comment by pbaca83** [comment]
Many thanks, so can you confirm that the edu license request is approved?



--
Piero Bacarella
IT Operations Manager @ ELIS
Via Sandro Sandri 81 - 00159 ROMA
Mobile: +39-346-2372967
Desk: +39-06-4592-4396
Email: ***@***.***
________________________________

**Comment by philipto** [comment]
@pbaca83 The request to add the domain to the trusted list is approved. As for your individual license request, please fill in the form at https://www.jetbrains.com/shop/eform/students, using your email address ending with `@elis.org`, and the request will be approved automatically as soon as you submit the form. You will receive further instructions by email upon approval.

**Comment by pbaca83** [comment]
Great, many thanks

--
Piero Bacarella
IT Operations Manager @ ELIS
Via Sandro Sandri 81 - 00159<tel:+398100159> ROMA
Mobile: +39-346-2372967<tel:+393462372967>
Desk: +39-06-4592-4396<tel:+390645924396>
Email: ***@***.******@***.***>

Da: Philip Torchinsky ***@***.***>
Data: sabato, 20 maggio 2023, 12:40
A: JetBrains/swot ***@***.***>
Cc: Piero Bacarella (SIE) ***@***.***>, Mention ***@***.***>
Oggetto: Re: [JetBrains/swot] I want to add www.elis.org (PR #17463)

@pbaca83<https://github.com/pbaca83> The request to add the domain to the trusted list is approved. As for your individual license request, please fill in the form at https://www.jetbrains.com/shop/eform/students, using your email address ending with @elis.org, and the request will be approved automatically as soon as you submit the form. You will receive further instructions by email upon approval.

**Pull request merged**
