### PR TITLE
Create ilsanh.goe.go.kr.

### PR DESCRIPTION
**Pull request by LastDice**

### CODE REVIEW

**Comment by philipto** [comment]
@LastDice Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@LastDice You might miss my previous comment. Please react.

**Comment by LastDice** [comment]
1. https://ilsan.hs.kr/home/index.do
2. 133, Gobong-ro, Ilsanseo-gu, Goyang-si, Gyeonggi-do, Republic of Korea
3. https://ilsan.hs.kr/home/index.do ( There is an IT software department in the school. )
4-1. https://cloud.goe.go.kr/ ( It is a site where you can create an e-mail (ilsanh.goe.go.kr) officially provided by the Gyeonggi-do Office of Education, Korea. )
4-2. Image. (Microsoft Azure, Education account)
스크린샷 2023-03-24 오후 2 17 46

**Comment by philipto** [comment]
@LastDice  Thank you for the clarifications. Pull request merged.

**Comment by kms0219kms** [comment]
@LastDice There is a neater precedent here. You may also cite this link if you need to proceed with the verification process in the following cases:
https://github.com/JetBrains/swot/pull/12132#issuecomment-894088130

@philipto Thank you for your hard work, but I noticed that you're asked same question to Korean Student.
As I mentioned 2 years ago, the mail services are provided by our government, not school.
If you got some request from Korean students, please remember that the domain could be government's domain and approve it.

**Pull request merged**
