### PR TITLE
Adding Institute to the List

### PR DESCRIPTION
**Pull request by RaannaKasturi**

### CODE REVIEW

**Comment by philipto** [comment]
@RaannaKasturi Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@RaannaKasturi You might miss my previous comment. Please react.

**Comment by RaannaKasturi** [comment]
It's a new institute and so the website and rest things are still under development. I'll get back to you as soon as all things are done

**Comment by philipto** [comment]
@RaannaKasturi Thank you! Thus, I have to close the request as for now. 

Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct and complete information. 

In the meanwhile you can apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Pull request closed without merging**
