### PR TITLE
Added BSZ-Wiesau students domain

### PR DESCRIPTION
**Pull request by swop-bs**
#### Institution/School Name

Staatliches Berufliches Schulzentrum Wiesau
#### Instiution/School Website

[www.bsz-wiesau.de](http://www.bsz-wiesau.de)
#### Email Users

_Please place an x between the square brackets if yes_

* [x]  Students
* [ ]  Academic/Teaching Staff
* [ ]  Other/Support Staff
* [ ]  Alumni

#### Education Levels
_Please place an x between the square brackets if yes_
* [ ]  Post-graduate research
* [ ]  Graduate School
* [ ]  College (University) or Undergraduate School or equivalent
* [x]  Community College or equivalent
* [ ]  High School or equivalent
* [ ]  Elementary School or equivalent

### CODE REVIEW

**Comment by swop-bs** [comment]
I already did a PR (#19175) for this school but we have two different domains. One for teachers (@bsz-wiesau.de) and another one for students (@bswiesaude.onmicrosoft.com). Both are domains for the school.

**Comment by philipto** [comment]
@swop-bs lib/domains/com/onmicrosoft/bswiesaude: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@swop-bs The first verification stage is complete: the official domain for  **Staatliches Berufliches Schulzentrum Wiesau** is [www.bsz-wiesau.de](https://www.bsz-wiesau.de), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://www.bsz-wiesau.de/fileadmin/user_upload/Beruflicher_Bildungscampus/Downloads/Schuelerinfos/Leitfaden_Anmeldung_Schulnetz.pdf

**Comment by philipto** [comment]
@swop-bs Thank you for your patience while waiting for a review and processing your request. Pull request merged.
**Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
