### PR TITLE
fecap.br - Fundação Escola de Comércio Álvares Penteado (FECAP)

### PR DESCRIPTION
**Pull request by xudre**

### CODE REVIEW

**Comment by philipto** [comment]
@xudre edu.fecap.br domain is already in this repository. If you wish to add fecap.br domain, please explain why, and rename the file to lib/domains/br/fecap.txt. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting a new request or modifying your old one. Thank you.

**Comment by xudre** [comment]
@philipto {at}fecap.br is the domain for school teachers and students, the already added {at}edu.fecap.br it is used by the college teachers and students. There are these differences here at the institution. Mine, as school teacher, is pedro.xudre@fecap.br, for example.

**Comment by philipto** [comment]
@xudre Thank you for the clarification. Pull request merged.

**Comment by xudre** [comment]
@philipto I didn't rename the path of the file before you merged, how can I proceed now? Revert the merge and post a new one?

**Pull request merged**
