### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AlexRoar**
Added Moscow State Engineering School no. 1581

### CODE REVIEW

**Comment by AlexRoar** [comment]
Official site: [https://lycc1581.mskobr.ru/#/](https://lycc1581.mskobr.ru/#/) 
Can't have emails on it.

Unofficial school project site: [https://www.tr-vz.ru/lounge](https://www.tr-vz.ru/lounge)
Can create work group emails on this site, so we use this one.

**Comment by philipto** [comment]
@AlexRoar There is a problem with this request. Domain tr-vz.ru is owned by another organization, which may, certainly, provide you with the email addresses from their domain, but it does not belong to a university, a high school, or a college. If you do not have an email which your school provided you with, please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tag at https://www.jetbrains.com/shop/eform/students.
Thank you for the understanding!

Please comment if I misunderstand something. Thank you.

**Comment by philipto** [comment]
@AlexRoar You might miss my previous comment. Please react.

**Comment by AlexRoar** [comment]
Hello!

No, I have not. Thanks a lot for you for the answer.

I decided to request an official document from my education organization, it would be far easier.

Best regards, Sasha Dremov
Russia, Moscow

**Comment by philipto** [comment]
@AlexRoar I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. You also can make a new request with all the necessary information. Thank you for the understanding!

**Pull request closed without merging**
