### PR TITLE
add tw edu tnua

### PR DESCRIPTION
**Pull request by fredy0219**
Hi I'm a student of Taipei National University of Arts. I would like to use your awesome IDE for my development. Thanks!

### CODE REVIEW

**Comment by dharmendrasha** [comment]
Hi I'm a student of dotsquares. I would like to use your awesome IDE for my development. Thanks!

**Comment by philipto** [comment]
@fredy0219 Thank you for your request! Please provide us with an URL of a page on your official university website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@fredy0219 You might miss my previous comment. Please react.

**Comment by fredy0219** [comment]
@philipto Thanks for your reply

I major in New Media Art at TNUA. The below link is the map of our course. But unfortunately there is only Chinese version.🥲
https://nma.tnua.edu.tw/course/course-map/Baz9Rc7guY
We have fundamental program course, computer vision, Interactive Solution that are IT-related.

I usually build some computer vision, motion detection and sensor integration projects.
Hope those information is enough for you.

**Comment by philipto** [comment]
@fredy0219 Thank you for the clarification. Pull request merged.

**Pull request merged**
