### PR TITLE
Create gpohkk.txt

### PR DESCRIPTION
**Pull request by dannopek**

### CODE REVIEW

**Comment by zweizwei** [comment]
the website seems to be not working - could you please provide some proof, that the website belongs to the school? thanks!

**Comment by dannopek** [comment]
In my school we use system which is not the best. Original website of my
school is http://gympohkk.edupage.org/?. Although we use
gympohkk.edupage.org adress for our webpage, the email is at gpohkk.edu.sk
address. This webpage doesnt exist but I dont know why. The proof that my
email belong to my school can be find in contact page of my school:
http://gympohkk.edupage.org/contact/?  there is email adress which our
school use (in row Email školy: *skola@gpohkk.edu.sk <skola@gpohkk.edu.sk>*)
I hope that will be enough. Thanks!

PS: sorry for my english

2015-05-09 22:12 GMT+02:00 Elena Ganenkova <notifications@github.com>:

> the website seems to be not working - could you please provide some proof,
> that the website belongs to the school? thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JetBrains/swot/pull/1041#issuecomment-100540364>.
>



-- 
Daniel Pekarcik

**Comment by zweizwei** [comment]
Thanks, it's now all clear - i'm adding the domain

**Comment by dannopek** [comment]
Thank you.

**Pull request merged**
