### PR TITLE
Please add Mekif Alef

### PR DESCRIPTION
**Pull request by shanag1801**
Mekif Alef, Beer Sheva, Israel.
thank you!

### CODE REVIEW

**Comment by philipto** [comment]
@shanag1801 Could you please explain what **sisma.org.il** is? It looks like a broad platform where a lot of students can get a free email address. Too broad platforms not linked to a specific school can be a source of free license misuse, thus we have to understand better who is eligible to get an inbox there.

The website sisma.org.il says it provides service to 1,000,000 people, which is about 10% of the total Israeli population. Thus, it does not appear to qualify for inclusion in this repository.

**Comment by philipto** [comment]
@shanag1801 You might miss my previous comment. Please react.

**Comment by shanag1801** [comment]
Hi, thank you for reaching out to me. The Sisma website is a platform high
schools in Israel use to provide email addresses for their students. Most
schools in Israel don’t have their own website or personal domain and
instead most schools use Sisma.
I’d be more than happy if you could add it to your list.
Thanks a bunch 🙏🏻

**Comment by shanag1801** [comment]
Thank you so much 😊

**Pull request merged**
