### PR TITLE
Create sgfl

### PR DESCRIPTION
**Pull request by artman41**
Stoke Grid For Learning.

### CODE REVIEW

**Comment by artman41** [comment]
> -the university official website URL, if different from the domain you are submitting
http://www.trinity6.com
> -an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
http://www.trinity6.com/admissions-a-level-courses/
> -an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.
http://www.trinity6.com/schools/

**Comment by artman41** [comment]
@philipto Hi! Is there any issue with my submission? I noticed that you have commented on other posts, but not mine. Is there any other information I could provide?

**Comment by philipto** [comment]
@artman41 Yes, there are number of issues:
1) The school name which you have in the file, Stoke Grid For Learning, is different from the only name linked to @sgfl.org.uk domain at the [page, which you have referred to](http://www.trinity6.com/schools/): 
St Margaret Ward Catholic Academy
Email: smwadmin@sgfl.org.uk

2) The file name has to be lib/domains/uk/org/sgfl.txt instead of lib/domains/uk/org/sgfl (please notice .txt extension, it is compulsory)

3) In fact, the website and your clarification are a bit confusing for me: I see from the website that Trinity Sixth Form unites the following schools:
St Thomas More Catholic Academy, Longton;
St Margaret Ward Catholic Academy, Tunstall;
St John Fisher Catholic College,
Newcastle-under-Lyme.

Stoke Grid For Learning is not mentioned anywhere, I cannot understand why you do not have just "Trinity Sixth Form" in the description in the file in your request.

Could you please modify the file name and tell me how all these schools and Stoke Grid For Learning are related? Thank you!

**Comment by artman41** [comment]
@philipto ah, if that's the issue, I can clear that up easily.

There're 4 college's that have joined together. I'll rename the file if that helps. sgfl stands for "Stoke Grid For Learning", so that's what I named the file as. My Mistake.

**Comment by philipto** [comment]
@artman41 Thank you for the clarification! Pull request merged.

**Pull request merged**
