### PR TITLE
Create iaeste.sk

### PR DESCRIPTION
**Pull request by tomasfarkasovsky**

### CODE REVIEW

**Comment by csnewman** [comment]
You need to use the txt file extension

**Comment by philipto** [comment]
@tomasfarkasovsky Could you please rename lib/domains/sk/iaeste.sk to lib/domains/sk/iaeste.txt? Thank you.

**Comment by tomasfarkasovsky** [comment]
Dear Philip,

I will do it today as soon as possible.

Thank you for patience.

Tomas

2017-05-02 1:07 GMT+02:00 Philip Torchinsky <notifications@github.com>:

**Comment by philipto** [comment]
@tomasfarkasovsky Pull request merged. Thank you!

**Pull request merged**
