### PR TITLE
Create eursc.txt

### PR DESCRIPTION
**Pull request by mirena99**
[github_pull_request_explanation.txt](https://github.com/JetBrains/swot/files/1425169/github_pull_request_explanation.txt)
Initial creation

### CODE REVIEW

**Comment by philipto** [comment]
For the record: the file linked above contains this clarification:
**the university official website URL, if different from the domain you are submitting**
https://www.eursc.eu/ is the domain for all EU schools
**an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university**
https://www.eursc.eu/en/European-Schools/studies/syllabuses
ICT is offered in all primary cycles (P1-P5) and the first 5 of the secondary cycles(S1-S5)
**an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.**
https://www.eursc.eu/Documents/2017-02-D-20-en-3.pdf page 21/48


/lib/domains/eu/eursc.txt

European schools
Ecoles européennes
Europäische Schulen

**Comment by philipto** [comment]
@mirena99 I can not add this domain to this repository due to too broad scope of schools covered by this domain. I am not sure that it is the best solution, because many schools in the EU have their own email domains, and some of them are added to this repository already. 

Also, the report you are referring to does not shed a light on who and how provide people with an access to the email in this domain. You also may know that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age, and it's not easy to ensure that all the schools in the EU will comply with this term (and even be notified about it), because if we include this domain into the repository, ALL the students and teachers of the schools will be granted with the free license automatically, on the base of possessing an email in this domain.

Please let us know what do you think about it. You can make a public comment on Github, just browse to https://github.com/JetBrains/swot/pull/3627 and leave your comment there. We may need to consider another acceptable solution. It's unlikely that we are able to add such a domain to this repository.

**Comment by mirena99** [comment]
Hello,

I think there might be a slight misunderstanding. This domain represents the 15 schools which bear the name "European School" (see https://www.eursc.eu/en/European-Schools/locations). It does not at all mean that it includes ALL schools in the countries of the European Union.
Regarding the numbers, please refer to the report https://www.eursc.eu/Documents/2016-10-D-2-en-2.pdf:
page 11 - total number of students (26691),
page 15 - number of secondary students, i.e. age 12-18 (13943)
page 19 - number of staff (1401).
Staff and secondary students only get a personal email, so ~15000 is the max number of licences.
Please advise if this is an acceptable number to be covered. I understand completely your constrains and will be looking for another solution if needed.

Thanks a lot,
Mirena

**Comment by philipto** [comment]
@mirena99 I am sorry for a delay with processing your request. Thank you for the additional details. They have helped us to identify your email domain as similar to school district's ones, from the UK and the US, some of which are included into this repository. Thus, we decided to add the domain which you have suggested as well. Thank you for your explanation and the patience. Pull request is now merged.

**Pull request merged**
