### PR TITLE
Create CSMB

### PR DESCRIPTION
**Pull request by felixinx**
Add Commission scolaire Marguerite-Bourgeoys

### CODE REVIEW

**Comment by zweizwei** [comment]
The request should be made on behalf of educational institution - this seems to be a social entity, not an educational institution. In case i've missed something on the case, please let me know.

**Comment by felixinx** [comment]
This is a network of school with over 92 buildings around Montréal, Canada. You can see more here : http://www.csmb.qc.ca/fr-CA/csmb/coup-doeil.aspx (in french)

**Comment by zweizwei** [comment]
Sorry for the delay. could you let me know if anyone but staff / students can register the email in the provided domain?

**Comment by felixinx** [comment]
No worries. I have contact the support and they give me an student account.
All teachers/staffs have a `@csmb.qc.ca` email adress.
All students have a `@ped.csmb.qc.ca` email adress.
For having an account, you must be a student / or staff. No one can create a email adress except the administration.

**Comment by zweizwei** [comment]
Understood, thank you - i'm adding the domain.

**Pull request merged**
