### PR TITLE
HS Bund

### PR DESCRIPTION
**Pull request by stefanneuhaus**
- the university official website URL: [link](https://www.hsbund.de)
- a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: [link](https://www.hsbund.de/DE/02_Studium/10_Duale_Studiengaenge/53_DACS/DACS-node.html)
- a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: [link](https://github.com/stefanneuhaus/swot/blob/dacs-bund_email-proof/email-proof_dacs-bund.de.png)

### CODE REVIEW

**Comment by philipto** [comment]
@stefanneuhaus I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Comment by stefanneuhaus** [comment]
@philipto Thank you very much for merging!
Does it require some time to become effective? When [applying](https://www.jetbrains.com/shop/eform/students) for an Educational License using my Email address `<NAME>@dacs-bund.de` it failed saying "_Your email address does not belong to any university that we know. You can apply with another method (see tabs above) or add your school to JetBrains' list._".

**Comment by philipto** [comment]
Hi Stefan!

Yes, it takes some time. Usually the time does not exceed one hour. If the
problem persists, please send an email with a screenshot to
community-support@jetbrains.com. Thank you!

**Comment by stefanneuhaus** [comment]
Hi @philipto,
Great, it worked! :-)
Thank you!

**Pull request merged**
