### PR TITLE
Create pk.txt

### PR DESCRIPTION
**Pull request by dsalabaev**
About courses: https://pk.edu.kg/about/history
About courses detailed: https://pk.edu.kg/specialty

### CODE REVIEW

**Comment by philipto** [comment]
@dsalabaev I am sorry, the domain looks suspicious. In particular, [this official page](https://www.knu.kg/ru/index.php?option=com_content&view=article&id=7812:-19062020&catid=995:2020-06-19-04-06-34&Itemid=88) gives another address of the college official website. The page is unreachable.

**Comment by dsalabaev** [comment]
> @dsalabaev I am sorry, the domain looks suspicious. In particular, [this official page](https://www.knu.kg/ru/index.php?option=com_content&view=article&id=7812:-19062020&catid=995:2020-06-19-04-06-34&Itemid=88) gives another address of the college official website. The page is unreachable.

Yes, this is the old address of the site pk.bishkek. host, the college decided to change the address to a more appropriate one for the educational institution. At the moment, the domain bishkek.host is not used. We have already asked the IT department of the KNU to change, but did not wait 😅

**Comment by dsalabaev** [comment]
@philipto I will immediately make a redirect from http://pk.bishkek.host on https://pk.edu.kg

**Comment by philipto** [comment]
@dsalabaev I am sorry again. Neither me, nor JetBrains have any right to ask you to setup any redirects. I suppose that nobody from outside of the university has a right to ask the university administration to setup a new link to a new domain.

The domain remains suspicious to me. Please don't make any extra steps to prove the domain correctness and ownership. I have to close this request without merging according our rules. Please create a new request when the domain will be officially recognized by the university.

As for now, students of this school can apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students). Thank you for your understanding.

**Pull request closed without merging**
