### PR TITLE
Added Govt. Polytechnic College, Tikamgarh India

### PR DESCRIPTION
**Pull request by coderbond007**

### CODE REVIEW

**Comment by philipto** [comment]
@coderbond007 I am sorry for a delay with processing your request.
Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@coderbond007 You might miss my previous comment. Please react.

**Comment by coderbond007** [comment]
Hey @philipto 
sorry I forgot to update on this one. We do not have a dedicated college website. I think you can close this ticket. Thanks for the concern. Is there any other way out? I can try for that.

**Comment by philipto** [comment]
@coderbond007 Thank you! Yes, I have to close this request without merging. Certainly, you can get your free license without adding your school domain to this repository. Please apply with official document using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you!

**Pull request closed without merging**
