### PR TITLE
Create avonvalleyschool.txt

### PR DESCRIPTION
**Pull request by benfoster04**

### CODE REVIEW

**Comment by philipto** [comment]
@benfoster04 Could you please:
1) rename lib/domains/uk/avonvalleyschool to lib/domains/uk/avonvalleyschool.txt
2) provide us with an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.
Thank you.

**Comment by philipto** [comment]
@benfoster04 Thank you for renaming the file. Now please provide the information I have asked about above. Which document proves that this school student email addresses end with @avonvalleyschool.uk? Thank you.

**Comment by benfoster04** [comment]
@philipto As this is a new domain for my school, everyone's still transferring over.. I have a meeting with the technicians about finding a form of proof.. Would the bottom of an official letter from the school with e-mail address and headteacher information be enough? What kind of information would be needed?

**Comment by philipto** [comment]
@benfoster04 Yes, the bottom of an official letter from the school with e-mail address and headteacher information is enough. Thank you!

**Comment by benfoster04** [comment]
screen shot 2018-07-14 at 9 29 24 am
There we go, finally got it for you. Sorry for the wait!

**Comment by philipto** [comment]
@benfoster04 Thank you for the update! Pull request merged.

**Pull request merged**
