### PR TITLE
added school name

### PR DESCRIPTION
**Pull request by natanael-oliveira**
School name: EEEP Professora Luíza De Teodoro Vieira
School email: lteodoro@escola.ce.gov.br

### CODE REVIEW

**Comment by philipto** [comment]
@natanael-oliveira I am sorry, I cannot find a reliable information about your school. Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by natanael-oliveira** [comment]
I will look for another way to confirm the email. I will contact the school

**Comment by philipto** [comment]
@natanael-oliveira Thank you! I am looking forward to seeing the confirmation.

**Comment by natanael-oliveira** [comment]
Hello @philipto. I received a statement from the school confirming the domain of the email provided  [statement](https://github.com/natanael-oliveira/natanael-oliveira/blob/master/Declara%C3%A7%C3%A3o%20.pdf)

**Comment by philipto** [comment]
@natanael-oliveira Pull request merged. Thank you!

**Comment by natanael-oliveira** [comment]
Eu te agradeço tchau

**Comment by natanael-oliveira** [comment]
I thank you, bye

**Pull request merged**
