### PR TITLE
Create bbze.txt

### PR DESCRIPTION
**Pull request by wenksi**

### CODE REVIEW

**Comment by philipto** [comment]
@wenksi What is the URL of the official website of the university? If it is not bbze.educanet2.ch, could you please give us a proof (such as contact page on the website, etc.) which shows that students at Berufsbildungszentrum für Wirtschaft, Informatik und Technik Emmen use domain bbze.educanet2.ch as their email domain? Thank you!

**Comment by wenksi** [comment]
@philipto The website: https://beruf.lu.ch/berufsbildungszentren/bbzw

And here on this picture (only in german) I'm logged in to my educanet2 account. "Berufsbildungszentrum Emmen", the name of my university, is written on the header.
myeducanet2

**Comment by philipto** [comment]
@wenksi Pull request merged. Thank you for the clarification!

**Comment by wenksi** [comment]
@philipto Thank you very much!

**Pull request merged**
