### PR TITLE
Palisades School District

### PR DESCRIPTION
**Pull request by Mnenmenth**

### CODE REVIEW

**Comment by zweizwei** [comment]
palisadessd.net doesn't open - please somehow confirm it also belongs to the school

**Comment by Mnenmenth** [comment]
Its the domain used for student accounts, it doesn't link to an actual webpage. There's nothing I can really do to prove it other than saying that GitHub acknowledges it as a valid educational account. I understand the situation however and thank you for your time even it can't count as enough evidence

**Comment by zweizwei** [comment]
@Mnenmenth any official document, confirming this system, or a link to a relevant page should work as a confirmation. Thank you.

**Comment by Mnenmenth** [comment]
@zweizwei 
http://whois.domaintools.com/palisadessd.net 
This shows that the Palisades School District owns the domain palisadessd.net

**Comment by zweizwei** [comment]
@Mnenmenth thanks, i'll add the domain now

**Comment by Mnenmenth** [comment]
@zweizwei Thank you

**Pull request merged**
