### PR TITLE
Added swot/lib/domains/uk/co/nwhsmail.co.uk

### PR DESCRIPTION
**Pull request by wery22222**
Added a new school file

School Website: https://www.nunnerywood.worcs.sch.uk/
IT course: https://www.nunnerywood.worcs.sch.uk/115/subjects/subject/12/computing-business

### CODE REVIEW

**Comment by wery22222** [comment]
Address: Nunnery Wood High School, Spetchley Road, Worcester, WR5 2LT, England

**Comment by philipto** [comment]
@wery22222 Thank you!

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by wery22222** [comment]
Hi @philipto 
Would an Email from the school technician be enough?

**Comment by wery22222** [comment]
This is a letter from my school:
[scan_l.boniface_2023-09-27-08-10-04.pdf](https://github.com/JetBrains/swot/files/12738553/scan_l.boniface_2023-09-27-08-10-04.pdf)

**Comment by philipto** [comment]
@wery22222 Yes. You can upload the copy here, or they can send us an email to community-support@jetbrains.com (mentioning the URL of this request, `https://github.com/JetBrains/swot/pull/18599`. Thank you!

**Comment by philipto** [comment]
@wery22222 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by wery22222** [comment]
Thank you very much

**Pull request merged**
