### PR TITLE
add beckum.schule

### PR DESCRIPTION
**Pull request by mat345st**

### CODE REVIEW

**Comment by philipto** [comment]
@mat345st Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@mat345st You might miss my previous comment. Please react.

**Comment by mat345st** [comment]
Unfortunately, I can not confirm with one of the methods that the domain belongs to this school. We got our mail unofficially on a small note, the school website is no longer up-to-date and nobody has reported about the domain

**Comment by philipto** [comment]
@mat345st I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

Please apply for a free educational license with an official document that proves that you are a student. You can do it using the "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

**Pull request closed without merging**
