### PR TITLE
Great Neck South Public Schools

### PR DESCRIPTION
**Pull request by 32n**

### CODE REVIEW

**Comment by Needheg** [comment]
SIBSTRIN

**Comment by Husky-H** [comment]
昆明理工大学
Kunming University of Science and Technology

**Comment by philipto** [comment]
@32n  Great Neck South High School official website says that the school located at 341 Lakeville Road, Great Neck, NY 11020
uses a different official domain: greatneck.k12.ny.us. 

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

As for a comment made my @Husky-H, I kindly ask @Husky-H to submit a separate request.

Thank you!

**Comment by Husky-H** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JetBrains/swot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月10日(星期五) 下午2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JetBrains/swot] Great Neck South Public Schools (#12397)





 
@32n  Great Neck South High School official website says that the school located at 341 Lakeville Road, Great Neck, NY 11020
 uses a different official domain: greatneck.k12.ny.us.
 
Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
 You can provide us with any of the following:
  
A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
 
An URL of a page at the official school website that says that students use this email domain
 
A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
 
A WHOIS data that link the email domain to the school somehow
 
A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
 
Anything else that can prove this fact in similar way, i.e. can be verified independently.
  
As for a comment made my @Husky-H, I kindly ask @Husky-H to submit a separate request.
 
Thank you!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 32n** [comment]
After trying Clion's free trial, I've decided to use VScode instead, so I'll close this pull request.

**Pull request closed without merging**
