### PR TITLE
St Finians Community College

### PR DESCRIPTION
**Pull request by RyanForan19**

### CODE REVIEW

**Comment by philipto** [comment]
@RyanForan19 First stage of verification passed, official domain is [stfinianscc.ie](https://stfinianscc.ie) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by RyanForan19** [comment]
@philipto Thank you for the feedback, I hope to hear for the final decision soon. Would you require any other information about the school?

**Comment by KiraBobyleva** [comment]
Hello @RyanForan19,

I can see in the contact of the website a different domain — [stfinians@ddletb.ie](mailto:stfinians@ddletb.ie). So could you please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students?

**Comment by RyanForan19** [comment]
Hi @KiraBobyleva, the reason why the contact of the school is stfinians@ddletb.ie is because the school is ran by the Dublin and Dun Laoghaire Education and Training Board (DDLETB). One thing I wanted to note is, the schools email system is set up to receive emails on same-domain. I am unsure how I can relate the domain of ddletb.ie and stfinianscc.ie, but I have attached a screenshot of my school emails, and am hoping that suffices.
Screenshot 2022-06-30 at 15 30 52

**Comment by KiraBobyleva** [comment]
Hi @RyanForan19,

Thank you! Pull request merged.

**Pull request merged**
