### PR TITLE
Add gymnasia21.lutsk.ua to list

### PR DESCRIPTION
**Pull request by DukeOfCode**
Lutsk Gymnasium #  21 after Mikhail Kravchuk  is an elementary (grades 1-4), middle (grades 5-9) and high (grades 10-11) school with the specialization in some subjects, determined yearly according to the students' and parents' wishes, recommendations of senior teachers and a staff psychologist.

Even though I am graduating this year, I would like to add this domain to list for younger students and teachers
P.S Administration and programming teachers are informed

### CODE REVIEW

**Comment by philipto** [comment]
@DukeOfCode Thank you! Please tell me what is an email pattern in your school? Is it username@lutsk_gymnasium21.lutsk.ua or username@gymnasia21.lutsk.ua. If the latter is true, please rename  lib/domains/ua/lutsk/lutsk_gymnasium21 to lib/domains/ua/lutsk/gymnasia21.txt. Please notice that .txt extension is mandatory.

**Comment by DukeOfCode** [comment]
> @DukeOfCode Thank you! Please tell me what is an email pattern in your school? Is it [username@lutsk_gymnasium21.lutsk.ua](mailto:username@lutsk_gymnasium21.lutsk.ua) or [username@gymnasia21.lutsk.ua](mailto:username@gymnasia21.lutsk.ua). If the latter is true, please rename lib/domains/ua/lutsk/lutsk_gymnasium21 to lib/domains/ua/lutsk/gymnasia21.txt. Please notice that .txt extension is mandatory.

It is second version. I rename it into   lib/domains/ua/lutsk/gymnasia21.txt from lib/domains/ua/lutsk/lutsk_gymnasium21

**Comment by philipto** [comment]
@DukeOfCode Thank you for the update. Pull request merged.

**Comment by DukeOfCode** [comment]
> @DukeOfCode Thank you for the update. Pull request merged.

Thank you too)

**Comment by DukeOfCode** [comment]
> @DukeOfCode Thank you for the update. Pull request merged.

Sorry, but May I continue in the future this license?Thank you again

**Pull request merged**
