### PR TITLE
Adding Jesuit High School

### PR DESCRIPTION
**Pull request by slimshadeey1**
Jesuit High School of Sacramento California, Provides LastNameFirstInitialGradYear@student.jhs.net
Example: Bill Gates graduates in 2016 gatesb16@student.jhs.net

School website is jesuithighschool.org, but the club page can be accessed via jhs.net

### CODE REVIEW

**Comment by slimshadeey1** [comment]
Hey when can this be merged? I am about to run out on my trial and I love using this for school...

**Comment by zweizwei** [comment]
I'm sorry for the delay. http://www.jesuitportland.org/ - is the school address, while jsh.net is not registered. please reapply with the correct domain.

**Comment by slimshadeey1** [comment]
@zweizwei The high school is Jesuit High School of Sacramento California
This is the whois record, and the home website for Jesuit is Jesuithighschool.org

Domain Name: JHS.NET
Registry Domain ID: 5276248_DOMAIN_NET-VRSN
Registrar WHOIS Server: whois.networksolutions.com
Registrar URL: http://networksolutions.com
Updated Date: 2015-01-28T23:28:49Z
Creation Date: 1997-05-06T04:00:00Z
Registrar Registration Expiration Date: 2016-05-07T04:00:00Z
Registrar: NETWORK SOLUTIONS, LLC.
Registrar IANA ID: 2
Registrar Abuse Contact Email: 
Registrar Abuse Contact Phone: +1.8003337680
Reseller: 
Domain Status: 
Registry Registrant ID: 
Registrant Name: Jesuit High School
Registrant Organization: Jesuit High School
Registrant Street: 1200 Jacob lane
Registrant City: Carmichael
Registrant State/Province: CA
Registrant Postal Code: 95608
Registrant Country: US
Registrant Phone: +1.9164826060
Registrant Phone Ext: 
Registrant Fax: +1.231231234
Registrant Fax Ext: 
Registrant Email: 
Registry Admin ID: 
Admin Name: Jesuit High School
Admin Organization: Jesuit High School
Admin Street: 1200 Jacob lane
Admin City: Carmichael
Admin State/Province: CA
Admin Postal Code: 95608
Admin Country: US
Admin Phone: +1.9164826060
Admin Phone Ext: 
Admin Fax: +1.231231234
Admin Fax Ext: 
Admin Email: 
Registry Tech ID: 
Tech Name: Network Solutions, LLC.
Tech Organization: Network Solutions, LLC.
Tech Street: 13861 Sunrise Valley Drive
Tech City: Herndon
Tech State/Province: VA
Tech Postal Code: 20171
Tech Country: US
Tech Phone: +1.8886429675
Tech Phone Ext: 
Tech Fax: 
Tech Fax Ext: 
Tech Email: 
Name Server: NS37.SECURENET-SERVER.NET
Name Server: NS38.SECURENET-SERVER.NET
DNSSEC: Unsigned
URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/

**Comment by zweizwei** [comment]
Thanks for the additional info, adding the domain then.

**Pull request merged**
