### PR TITLE
Add acsp.ac.th

### PR DESCRIPTION
**Pull request by tinvv**

### CODE REVIEW

**Comment by philipto** [comment]
@tinvv Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by tinvv** [comment]
> @tinvv Please provide us with:
> 
> * the school official website URL
> * the school street address, including city and country
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

- http://www.acsp.ac.th/
- 419/1389 Theparak Road, Amphur Muang Samutprakarn, 10270, Thailand
- http://www.acsp.ac.th/NewStdALL/

**Comment by philipto** [comment]
@tinvv Could you please clarify how you use software development tools? The course description says that the school teaches the students in human languages, such as English, Japanese, etc. Why do you need JetBrains tools for education? 

Thank you for your patience and understanding!

**Comment by tinvv** [comment]
> @tinvv Could you please clarify how you use software development tools? The course description says that the school teaches the students in human languages, such as English, Japanese, etc. Why do you need JetBrains tools for education?
> 
> Thank you for your patience and understanding!

Thanks for replying,

Our school also offers computer science (or robots) course in Math and Science program. 
That also includes programming language such as Python, HTML, JavaScript, etc.
But because some students may not have their own IDE or code editor for learning,
Therefore, it would be great to let students use JetBrains products to develop a software for learning or education.

**Comment by philipto** [comment]
@tinvv Thank you for the clarification. Pull request merged.

**Pull request merged**
