### PR TITLE
caledonian.ac.uk is Glasgow Caledonian University

### PR DESCRIPTION
**Pull request by shuangg**
https://www.gcu.ac.uk/
https://www.gcu.ac.uk/study/postgraduate/courses/search/?t=Computer#CourseList
https://www.gcu.ac.uk/student/support/it/email/#:~:text=Your%20email%20address%20is%20in,into%20University%20PCs%20on%20campus.

### CODE REVIEW

**Comment by philipto** [comment]
@shuangg lib/domains/uk/ac/caledonian: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@shuangg lib/domains/uk/ac/caledonian: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by shuangg** [comment]
Can this be merged now?

**Comment by philipto** [comment]
@shuangg Yes. Pull request merged. Thank you!

**Comment by shuangg** [comment]
Thanks

**Comment by gcu13** [comment]
@philipto I'm trying to sign up as a GCU student but my `@caledonian.ac.uk` email address isn't being recognised. Can you please confirm this has been added correctly?

**Pull request merged**
