### PR TITLE
Adding The Cathedral School for school licenses

### PR DESCRIPTION
**Pull request by Intergalactic-Carpet**
Adding The Cathedral School to the school list for education licenses

Site can be found at: [https://ecat.cathedral.qld.edu.au/](https://ecat.cathedral.qld.edu.au/)

### CODE REVIEW

**Comment by philipto** [comment]
@Intergalactic-Carpet lib/domains/au/edu/qld/cathedral: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Intergalactic-Carpet** [comment]
@philipto I've updated it with the correct file format

**Comment by philipto** [comment]
@Intergalactic-Carpet First stage of verification passed, official domain is [facebook.com](https://facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://pt-br.facebook.com/TheCathedralSchoolPastStudentsAssociation/

**Comment by philipto** [comment]
@Intergalactic-Carpet Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
