### PR TITLE
add: tau domain

### PR DESCRIPTION
**Pull request by nnocsupnn**
Add tau.edu.ph domain for registration of student

### CODE REVIEW

**Comment by philipto** [comment]
@nnocsupnn First stage of verification passed, official domain is [tau.edu.ph](https://tau.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@nnocsupnn Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by nnocsupnn** [comment]
Hi Philip,



   - the school official website URL
   - http://www.tau.edu.ph/
   - the school street address, including city and country
   -  JCM7+VQ4, Camiling, Tarlac, Philippines
   - an URL of a page on the official website where the school offers an
   IT-related long-term (>1 year) course
   http://www.tau.edu.ph/cet/
   - a proof, which shows that the school recognizes the domain you are
   submitting as an official email domain for the students.
   [image: image.png]

   Thanks,

**Comment by philipto** [comment]
@nnocsupnn  Thank you for the clarifications. Pull request merged.

**Pull request merged**
