### PR TITLE
Create aspire2student.txt

### PR DESCRIPTION
**Pull request by Yelizar**
Aspire 2 International

### CODE REVIEW

**Comment by philipto** [comment]
@Yelizar Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Yelizar** [comment]
Hi there 

Official website URL https://www.aspire2international.ac.nz/
IT course https://www.aspire2international.ac.nz/programmes/it-computing/diploma-in-computing/
Sorry, I am not sure how to confirm the domain.


Thank you

Laz

**Comment by Yelizar** [comment]
Please see attached screenshot. 
Thanks

**Comment by philipto** [comment]
@Yelizar Pull request merged. 
For the record: the proof of the email domain ownership is the document at http://www.myntec.ac.nz/home/Instructions.pdf

The screenshots can not be uploaded to GitHub comments as an attachment to an email, thus I was not able to see the screenshot. Thank you anyway.

**Comment by Yelizar** [comment]
Thank you so much.

**Pull request merged**
