### PR TITLE
sempreung domain added.

### PR DESCRIPTION
**Pull request by weesftw**

### CODE REVIEW

**Comment by philipto** [comment]
@weesftw Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by weesftw** [comment]
> @weesftw Forneça-nos:
> 
> * o URL do site oficial da escola
> * um URL de uma página no site oficial onde a escola oferece um curso relacionado a TI de longo prazo (> 1 ano)
> * uma prova, que mostra que a escola reconhece o domínio que você está enviando como um domínio de e-mail oficial para os alunos.


1. http://ung,br
2. https://vestibular.ung.br/PS_Univeritas/curso/15/3884/3/ciencia-da-computacao/Guarulhos-SP
3. In anex my profile in office 365 which management by my university (i don't know if that helpful).



office365

**Comment by weesftw** [comment]
> @weesftw Please provide us with:
> 
> * the school official website URL
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

1. http://ung,br
2. https://vestibular.ung.br/PS_Univeritas/curso/15/3884/3/ciencia-da-computacao/Guarulhos-SP
3. In anex my profile in office 365 which management by my university (i don't know if that helpful).

office365

**Comment by philipto** [comment]
@weesftw Thank you for the clarification. Pull request merged.

**Pull request merged**
