### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AeneasTews**
School Website: https://comenius-deg.de
Description of a few IT-Related-Projects:
MINT - Project: https://comenius-deg.de/project/mint-konzept/
Jugend Forscht: A contest in which students work on STEM - Related Projects for a year: https://comenius-deg.de/project/jugend-forscht/
The subject IT and related offers: https://comenius-deg.de/project/informatik/

### CODE REVIEW

**Comment by philipto** [comment]
@AeneasTews Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@AeneasTews You might miss my previous comment. Please react.

**Comment by AeneasTews** [comment]
Hey Philip,

Please excuse my not replying so far. I am currently still working on getting the original memo telling us to use this e-mail domain.

Have a nice day,
Aeneas

**Comment by philipto** [comment]
@AeneasTews Do you have any update on the matter?

**Comment by AeneasTews** [comment]
overview
my account online
a screenshot of my social studies class as an example
list of different subjects
list of different chats with people from the school

sadly I wasn't able to get a copy of any official document telling us to use these e-mail addressees, however i have taken a few screenshots of microsoft teams with this account logged in. it is proof that we all have an account and that we use these at our school

**Comment by philipto** [comment]
@AeneasTews Thank you for the clarification. Pull request merged.
I removed the screenshots for data privacy reason.

**Pull request merged**
