### PR TITLE
School add

### PR DESCRIPTION
**Pull request by plmorpheus**
Please add my school so we can use educational licenses of phpStorm. 
URL: https://mateja.edu.pl

Thx in advance

### CODE REVIEW

**Comment by philipto** [comment]
@plmorpheus Pull request merged. Thank you!

**Comment by plmorpheus** [comment]
Thx but how can I receive edu license? I read that I must it thru my JetBrains account but registration/account page is not working.

**Comment by philipto** [comment]
@plmorpheus Please fill the form at https://www.jetbrains.com/shop/eform/students, receive an email confirmation and click a link in it. If you have any troubles in the process, please send an email with a screenshot of a error message to support@jetbrains.com. Thank you!

**Comment by plmorpheus** [comment]
OK, thanks for help :)

**Pull request merged**
