### PR TITLE
Carcavelos High School

### PR DESCRIPTION
**Pull request by 3faze**
Carcavelos High School or "Escola Secundária de Carcavelos"(in Portuguese) is a high school located in Carcavelos, Lisbon. It has around 2000 students and has 3 types of courses related to science, one being science and technologies(equivalent to computer science in english).

### CODE REVIEW

**Comment by philipto** [comment]
@3faze First stage of verification passed, official domain is [aecarcavelos.pt](https://aecarcavelos.pt) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.aecarcavelos.pt/contactos/

**Comment by 3faze** [comment]
The website domain is "aecarcavelos.pt" but the email domain is "studentid@aecarcavelos.com".
I didin't understand what you mean in the last sentence. Thanks for the note!

**Comment by philipto** [comment]
@3faze Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by 3faze** [comment]
Thanks!

**Pull request merged**
