### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by menonkrishna57**

### CODE REVIEW

**Comment by philipto** [comment]
@menonkrishna57 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@menonkrishna57 You might miss my previous comment. Please react.

**Comment by menonkrishna57** [comment]
I got access via GitHub. If you still need it though the website is https://engineering.nmims.edu

**Comment by philipto** [comment]
@menonkrishna57 No, we don't insist on adding the school to the trusted list, especially if the domain has been changed. I close this request without merging.

If you will need to update the info or repeat the request, please make a new one. Please make a comment with the requested information in a new request, if you decide to create it.

**Pull request closed without merging**
