### PR TITLE
Add Escola Superior de Enfermagem de Coimbra

### PR DESCRIPTION
**Pull request by lparede**

### CODE REVIEW

**Comment by lparede** [comment]
@philipto , thank you.

**Comment by philipto** [comment]
@lparede Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by lparede** [comment]
@philipto , we only have a very few curricular units and some short courses IT related. None of our long courses is IT related.

Maybe we cannot apply for this.

**Comment by philipto** [comment]
@lparede You are correct. This organization is not eligible for this repository. Please apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses
Thank you for your understanding!

**Pull request closed without merging**
