### PR TITLE
Please add "student.gsso.de"

### PR DESCRIPTION
**Pull request by Likqez**
# Request to add Grafenbergschule to swot
I already got accepted to githubs student developer programm, but it would be nice to have the scool on this list.
GSSO features a profile Subject "Information Technology", which you have to attend to till your A-Levels.

https://gsso.de/index.php/events/info/2020-21/TG/freiePlaetze

Screenshot that proves that "student.gsso.de" is on the same cert then gsso.de:

https://gsso.de/index.php/events/info/2020-21/TG/freiePlaetze

### CODE REVIEW

**Comment by philipto** [comment]
@Likqez Pull request merged. Thank you!

**Comment by bhanureddy2105** [comment]
@Likqez  After the pull request has been merged are you able to create an account with your university email id?

**Comment by philipto** [comment]
@bhanureddy2105 Normally, you are. If you are not, please send an email to community-support@jetbrains.com with a error message screenshot.

**Comment by Likqez** [comment]
I already have an registered student account by linking with github education. Still wanted to contribute for future applications :)

**Pull request merged**
