### PR TITLE
UMFST domain

### PR DESCRIPTION
**Pull request by Flavius890**

### CODE REVIEW

**Comment by Flavius890** [comment]
University official website url:   https://www.umfst.ro/home.html
Educational Offers:   https://www.umfst.ro/inginerie/oferta-educationala.html (bachelor's degree in informatics, 3 years)
Proof university recognizes the domain:   https://www.umfst.ro/EmailAccount/ (this tool is used by students to get their email adresses, go there and type some random info and you will see the domain)

**Comment by philipto** [comment]
@Flavius890 Pull request merged. Thank you!

**Comment by Flavius890** [comment]
@philipto Thanks! Students emails looks like this iusan.flaviu-lucian@stud18.umfst.ro (this is mine). So theoretically it should work, right? "umfst" is upper-level domain and stud18 is subdomain if i've understood correctly from FAQ. Just asking because it isn't working right now to register for student license with this my email.(or maybe it just takes some time to update before working?)

**Comment by Flavius890** [comment]
It works now!

**Pull request merged**
