### PR TITLE
International Programs School (IPS KSA)

### PR DESCRIPTION
**Pull request by Abruaheem**

### CODE REVIEW

**Comment by philipto** [comment]
@Abruaheem First stage of verification passed, official domain is [ipsksa.com](https://ipsksa.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Abruaheem Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by Abruaheem** [comment]
> @Abruaheem Please provide us with:
> 
> * the school official website URL
> * the school street address, including city and country
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

* https://ipsksa.com
* International Programs School, Prince Sultan Road, Qurtoba, Al Khobar 34236, Saudi Arabia
* The website does not have explicit course information, it does have information about the IB diploma (The source for high school it follows), and within the IB diploma the school offers computer science courses. [School's IB information page](https://ipsksa.com/academics-detail.php?id=7)
* I'm not sure how you want me to provide this proof, on the website the support email is admin@ipsksa.com where you can see that the domain is used for emails, this is also used for students with numbers in front (For example, 10101@ipsksa.com)

**Comment by philipto** [comment]
@Abruaheem  Thank you for the clarifications. Pull request merged.

**Comment by Abruaheem** [comment]
Great thank you!

**Pull request merged**
