### PR TITLE
neu: Schulen in Bremen, Deutschland

### PR DESCRIPTION
**Pull request by mondmann**
see also <http://www.schule.bremen.de>

### CODE REVIEW

**Comment by zweizwei** [comment]
@mondmann Sorry for the delay - we've been launching rebranding and I hadn't time to check the repo for a while. As for request - the page provided seems to point at some informational website for all  schools. Please provide some confirmation of the fact, that only teachers and students can register email addresses under the mentioned domain. Thank you!

**Comment by mondmann** [comment]
@zweizwei Hmm, how would you like me to prove this. Well, there is an other e-mail domain called bildung.bremen.de for non educational staff in schools of bremen. For the domain schule.bremen.de, all e-mail users are nightly updated from the list of pupils and teachers in public schools in the federal state of bremen. What do you want to get from me for approval?

**Comment by zweizwei** [comment]
@mondmann if there is any official document confirming this (for example instructions on how to register email address for students / teachers) or the page indicating this - this should suffice. Anyway untill we have such confirmation we can not add the domain - the addresses are accepted automatically once the domain is added so we need to make sure that the domain is used on purpose. Thank you!

**Comment by mondmann** [comment]
@zweizwei I asked the administrator of this e-mail domain and he added a TXT record to schule.bremen.de DNS entry:

$ host -t txt  schule.bremen.de
schule.bremen.de descriptive text "Mailboxes" "under" "the" "domain" "schule.bremen.de" "are" "exclusively" "provided" "to" "teachers" "and" "pupils" "of" "schools" "of" "the" "federal" "city" "state" "of" "Bremen," "Germany."

Is that sufficient?

**Comment by mondmann** [comment]
@zweizwei Are there any news on that, please?

**Comment by philipto** [comment]
@mondmann I am sorry for a delay with a resolving of the issue, but the problem is that this repository is to list particular colleges and universities. We are developing a common approach to situations when a large group of educational institutions share the same email domain for their students. I appreciate your patience, and I am sorry for taking one more week to resolve the situation.

In the meantime those teachers in your schools who wish to advise their students using JetBrains tools, can apply for a Classroom licenses: it's quicker and can be done online at jetbrains.com.

**Pull request closed without merging**
