### PR TITLE
Added Doga Koleji

### PR DESCRIPTION
**Pull request by obvMellow**

### CODE REVIEW

**Comment by philipto** [comment]
@obvMellow Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by obvMellow** [comment]
- The school website: https://www.dogakoleji.k12.tr/
- The school address: AddressOrdinaryus Profesor Doktor Fahrettin Kerim Gokay Cd. 74, 34696 Üsküdar Istanbul, Türkiye
- https://www.dogakoleji.k12.tr/doga-dan-haberler/dogatech-cevrim-ici-kurs-kayitlarimiz-basladi!-1-4846
- It's same as the official website URL so I think that's a proof

**Comment by philipto** [comment]
@obvMellow Thank you for the details! Could you please clarify your words:
> It's same as the official website URL so I think that's a proof

The file you are submitting is `lib/domains/tr/k12/dogaokullari.txt`, it corresponds the domain `dogaokullari.k12.tr`. The website is [www.dogakoleji.k12.tr](https://www.dogakoleji.k12.tr/). As far as I see, the words **dogaokullari** and **dogakoleji** are different. 

Please clarify the request. Thank you.

**Comment by obvMellow** [comment]
@philipto 

> As far as I see, the words `dogaokullari` and `dogakoleji` are different.

Oh yeah excuse my mistake. Both of the domains are registered by the school.

https://www.shopify.com/tools/whois/search?query=dogakoleji.k12.tr
image

https://www.shopify.com/tools/whois/search?query=dogaokullari.k12.tr
image

Both of these domains are registered by Doğa College.

**Pull request merged**
