### PR TITLE
suzhou high vocational school

### PR DESCRIPTION
**Pull request by jscslld**
suzhou high vocational school apply for JetBrains.
School Website Domain:http://cszx.site
a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university:http://cszx.site/Article/detail/id/42743/category/contact.html
image
As you can see in the picture,we recruit 70 electronic information engineering students, 40 communication technology students, 80 computer network technology students, 40 software technology students and 40 computer application students every year.

### CODE REVIEW

**Comment by jscslld** [comment]
If you need any further information,please contact me without hesitation.

**Comment by jscslld** [comment]
@philipto Is there any information i need to add?

**Comment by philipto** [comment]
@jscslld No, thank you. We usually review a request within three business days. Your request is now in review. Thank you for your patience.

**Comment by philipto** [comment]
@jscslld I am sorry, our investigation has indicated that this domain does not belong to a university, nor to a college. I have to close the request without merging. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting a new request.

**Pull request closed without merging**
