### PR TITLE
add email.ustc.edu.cn to ustc domains, please accept it

### PR DESCRIPTION
**Pull request by ch710798472**

### CODE REVIEW

**Comment by ch710798472** [comment]
hi, student in our school will get another email address, please check it.Here is ustc email login website, http://mail.ustc.edu.cn/, some student have to choose username@mail.ustc.edu.cn to login , plus here is our school website, http://www.ustc.edu.cn/. Thank you.

**Comment by xeu100** [comment]
You're supposed to do just the base domain name to ustc.edu.cn so the file name would be ustc.txt with the edu.cn part being the folder (cn/edu). It doesn't really matter on the email format either.

**Comment by ch710798472** [comment]
but we can't receive the confirmation email

**Comment by ch710798472** [comment]
thank you

**Comment by philipto** [comment]
@ch710798472 Pull request merged. Thank you!

**Pull request merged**
