### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by celishere**

### CODE REVIEW

**Comment by celishere** [comment]
Site: school.mosreg.ru

**Comment by MMMMMophy** [comment]
[file.zip](https://github.com/JetBrains/swot/files/7114100/file.zip)

**Comment by philipto** [comment]
@celishere Pull request merged. Thank you!

FTR: correct domain usage proof: https://www.youtube.com/watch?v=BdDocDuH9jM

**Comment by philipto** [comment]
@MMMMMophy Please make a separate request. Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with correct information. Thank you for your understanding!

**Comment by MMMMMophy** [comment]
Sorry, I can not understand the language of this video.&nbsp;


韩明芳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Philip ***@***.***&gt;; 
发送时间: 2021年9月6日(星期一) 下午4:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JetBrains/swot] Add files via upload (#12389)





 
@celishere Pull request merged. Thank you!
 
FTR: correct domain usage proof: https://www.youtube.com/watch?v=BdDocDuH9jM
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
