### PR TITLE
Add Universidade Tuiuti do Paraná

### PR DESCRIPTION
**Pull request by IsraelBoiko**
Official url of University: [https://www.tuiuti.edu.br](https://www.tuiuti.edu.br)
The Science Computer Course: [https://utp.br/graduacao/bacharelado/ciencia-da-computacao/](https://utp.br/graduacao/bacharelado/ciencia-da-computacao/)

### CODE REVIEW

**Comment by philipto** [comment]
@IsraelBoiko Please provide us with a proof, which shows that the school recognizes the domain utp.edu.br you are submitting as an official email domain for the students.

**Comment by IsraelBoiko** [comment]
Added [Add Universidade Tuiuti do Paraná #9229](https://github.com/JetBrains/swot/pull/9229)

**Comment by philipto** [comment]
@IsraelBoiko Please DO NOT make new pull requests. Please answer here in the comment: where I can read that this university gives its students email addresses in the domain utp.edu.br?

I see that the university owns the the domains utp.br and tuiuti.edu.br. Where I can see that it also owns utp.edu.br?

Thank you.

**Comment by IsraelBoiko** [comment]
Institutional website: [https://utp.br/?__hssc](https://utp.br/?__hssc)

image

Student's portal (Portal do Aluno): [http://alunos.utp.br/](http://alunos.utp.br/)

In the student portal in the External Url (**Urls Externas**) menu I has the option **Email Office 365**, where you transfer me to the link **[https://app.utp.br/informatica/office.php](https://app.utp.br/informatica/office.php?key=L\FF\09\28B\FDc\DF\A4\21s\14\E75\40\E6\034\F5e8Fw\1E1\00\BC\C5\F8\EF\CD\A2\08\CA\E2xt\19O\B3\21\A8\F1\FD\5E\40\E7\5E\BB\60\03\23\EE\FF\C4\15M\BBAn\A9\D1\7EU\81\FF\DF\83\D5\A3\D3\3C\FA\8D\0B\17\85YW\AEG\F8\29\A4\A9\1Da\AC\8F\D8\22\C5\B0\EA\82\FF\9F\C6\84\1D\10U\84\A8\EA\ACm\1C\9D\60\2D\3A\E0\FDJu\FBU\1A\84\27\89\97\5E\AB\1E\D4\10\9EnD\FB\E9\F7A\A5\85O\EES\E3\1A\D5\3D)**.

image

**Comment by philipto** [comment]
@IsraelBoiko Pull request merged. Thank you!

**Pull request merged**
