### PR TITLE
Create ucsmgy.txt

### PR DESCRIPTION
**Pull request by Naing-Lin-Htet**
Add my school to JetBrains list

### CODE REVIEW

**Comment by ShyGil** [comment]
Mobile County Public Schools: Homehttps://www.mcpss.com

**Comment by Naing-Lin-Htet** [comment]
What do you mean? I want my file to merge to JetBrains/swot and then I can access free education license
account and I can use JetBrains product. But you commented  like "Mobile County Public Schools: Homehttps://www.mcpss.com".What do you mean? I don't understand it.
________________________________

**Comment by philipto** [comment]
@Naing-Lin-Htet Do you have email addresses ending with @ucsmgy.edu.mm in the university? If yes, we need to rename the file to  lib/domains/mm/edu/ucsmgy.txt 

If not, please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.


@ShyGil Please create a separate pull request. Thank you.

**Comment by philipto** [comment]
@Naing-Lin-Htet I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host ucsmgy.edu not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Pull request closed without merging**
