### PR TITLE
Create ip-formation.txt

### PR DESCRIPTION
**Pull request by Furansujin**
https://www.ecole-ipssi.com/

### CODE REVIEW

**Comment by philipto** [comment]
@Furansujin Please provide us withan URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students. Also, please let us know if email addresses in  @ip-formation.com domain are for students and teachers, not a broad number of employees who are not involved into teaching and learning.

**Comment by Furansujin** [comment]
url School : https://www.ecole-ipssi.com/
screenshot  portal office account school :
capture d ecran 4

**Comment by Furansujin** [comment]
seconde url school : http://ip-formation.com
is domain "ip-formation" of email

**Comment by philipto** [comment]
@Furansujin Pull request merged. Thank you for the update!

**Pull request merged**
