### PR TITLE
Add Wesley College

### PR DESCRIPTION
**Pull request by MichaelK-F**
[wesley.wa.edu.au](https://wesley.wa.edu.au)

### CODE REVIEW

**Comment by philipto** [comment]
@MichaelK-F Please provide us with:
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by skybird23333** [comment]
1. Coode St &, Angelo St, South Perth WA 6151
2. For years 11 and 12, Wesley College [offers ATAR courses](https://www.wesley.wa.edu.au/our-school/) as part of the [WACE](https://www.education.wa.edu.au/career-development/wace), which includes [Computer Science ATAR](https://senior-secondary.scsa.wa.edu.au/syllabus-and-support-materials/technologies/computer-science).
3. What kind of proof do you require? Can you give some examples?

**Comment by skybird23333** [comment]
Sorry, missed the README. On the school's website, hover over "Current Students", click "Schoolbox Login", and you should see the email domain pop up as a placeholder.

**Comment by MichaelK-F** [comment]
@philipto The information required is above.

**Comment by philipto** [comment]
@MichaelK-F  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
