### PR TITLE
add bsd48.txt

### PR DESCRIPTION
**Pull request by hdt80**

### CODE REVIEW

**Comment by hdt80** [comment]
Official website here: https://www.beaverton.k12.or.us/

**Comment by zweizwei** [comment]
Could you please provide some proof, that the mentioned domain also belongs to the school? Thanks for your help!

**Comment by hdt80** [comment]
What kind of proof are you looking for? The only kind of proof I can think of is this picture of the BSD logo on the left with the domain on the right
https://i.imgur.com/Cpssz4D.png

**Comment by zweizwei** [comment]
works fine, thanks for the screenshot - i'm adding the domain

**Pull request merged**
