### PR TITLE
Request to add school to jetbrains

### PR DESCRIPTION
**Pull request by bidishaMondal7**

### CODE REVIEW

**Comment by AmayNaruto** [comment]
[file (3).zip](https://github.com/JetBrains/swot/files/4717500/file.3.zip)
this is my school

**Comment by AmayNaruto** [comment]
[file (2).zip](https://github.com/JetBrains/swot/files/4717505/file.2.zip)
sorry this is my school

**Comment by philipto** [comment]
@bidishaMondal7 rcciit.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@bidishaMondal7 rcciit.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@bidishaMondal7 rcciit.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@bidishaMondal7 I am sorry, I have to close the request without merging. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with correct information. 

Please do not upload file.zip. Please make a comment after you submitted a pull request, and write in the comment what is your school email address pattern, such as username@aim.com.

Thank you for the understanding!

**Pull request closed without merging**
