### PR TITLE
cmconnect.cmcc.edu

### PR DESCRIPTION
**Pull request by Spool009**
Added cmcc.edu email format username@cmconnect.cmcc.edu
Hopefully i did it right this  time. 
Thanks

### CODE REVIEW

**Comment by philipto** [comment]
@Spool009 First stage of verification passed, official domain for **Name: Central Maine Community College** is [cmconnect.cmcc.edu](https://cmconnect.cmcc.edu) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@Spool009 I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host student.cmcc.edu not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by Spool009** [comment]
Thank you very much for your hard work.

**Comment by Spool009** [comment]
> @Spool009 First stage of verification passed, official domain for **Name: Central Maine Community College** is [cmconnect.cmcc.edu](https://cmconnect.cmcc.edu) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Hello, I am unaware of the time it takes for these actions to be verified so I was inquiring about it after  6 weeks. Thanks

**Pull request closed without merging**
