### PR TITLE
Create daegu.txt

### PR DESCRIPTION
**Pull request by junog115**

### CODE REVIEW

**Comment by junog115** [comment]
create daegu.txt

**Comment by junog115** [comment]
This is my college department Homepage.

http://computer.daegu.ac.kr/hakgwa_home/computer/index.php

**Comment by philipto** [comment]
@junog115 Pull request merged. Thank you!

**Comment by junog115** [comment]
@philipto I applied for free product but can't receive mail. 
my mail is junog115@daegu.ac.kr, did I make a mistake?

**Pull request merged**
