### PR TITLE
Added Hyper Island

### PR DESCRIPTION
**Pull request by abergs**

### CODE REVIEW

**Comment by philipto** [comment]
@abergs Could you please clarify how online and offline education are separated in your school? We do not grant licenses for online schools, and offline school with physically existing classes is eligible for a free license on the base of an email domain if it offers long-term (> 1 year) IT-related courses to the students. I can merge your request if your school has at least one such long-term offline course. If you have the course description on a web page, please give us its URL. Thank you!

**Comment by abergs** [comment]
Sure @philipto, all programs are offline at Hyper Island. This is my program: https://www.hyperisland.com/programs-and-courses/digital-data-strategist

It's a 2 year program, located in Stockholm, Sweden.

**Comment by abergs** [comment]
I want to note: Hyper Island also has shorter master classes all over the world. However, that **won't** grant you a student email, which is "hyperisland.se" and the staff email is "hyperisland.com". My PR is for the student domain, hyperisland.se.

**Comment by philipto** [comment]
@abergs Thank you very much for the clarification! Pull request merged.

**Comment by abergs** [comment]
When does your website update @philipto. Just tried to order, but hyperisland is still not recognized :)

**Pull request merged**
