### PR TITLE
Create ortmontreuil.txt

### PR DESCRIPTION
**Pull request by kiksou**
Hello there i want if its possible to add my school in the project 

the name of the school is Ort Montreuil https://ort-france.fr/montreuil

the mails adresse are like this firstname.LASTNAME@ortmontreuil.fr

i want it for the use of the students

thanks to you !

### CODE REVIEW

**Comment by philipto** [comment]
@kiksou Thank you for the request. Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by kiksou** [comment]
Capture d’écran 2020-09-29 à 15 48 22

i hope that will be sufficient  its in french btw if you want the translation in english just ask me

**Comment by kiksou** [comment]
@philipto thanks for the time you take

**Comment by philipto** [comment]
@kiksou Thank you for the additional details. Could you please tell me what is the connection between your school and the email address in the domain `ecoledirecte.fr`, mentioned in the FROM field of the email at the screenshot?

**Comment by kiksou** [comment]
Ecole directe is a way for the student to verifying the grade and talk about some information in the school (like the school calendar and holidays.

**Comment by kiksou** [comment]
UP

**Comment by kiksou** [comment]
@philipto did i have to bring some other extra information ?

**Comment by philipto** [comment]
@kiksou We currently are investigating the matter. It would help if you give us an URL at https://ort-france.fr/montreuil website or attach a copy of printed document which clearly identify a connection between Ort Montreuil and ortmontreuil.fr domain. At the last resort, a clear connection between ORT DANIEL MAYER and the email domain ecoledirecte.fr and Ort Montreuil works.

As far as I can see, WHOIS data proves the connection between the two domains sufficiently:
https://whois.domaintools.com/ortmontreuil.fr

Thus, I merge the pull request. Thank you.

**Pull request merged**
