### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MiKeDoTCL**
C.F.T. Juan Bohon para estudiantes

### CODE REVIEW

**Comment by MiKeDoTCL** [comment]
please visit https://www.juanbohon.cl/alumnos.txt for to verify

**Comment by philipto** [comment]
@MiKeDoTCL First stage of verification passed, official domain is [juanbohon.cl](https://juanbohon.cl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@MiKeDoTCL Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by MiKeDoTCL** [comment]
Thank you @philipto for your management

**Pull request merged**
