### PR TITLE
My School in Germany

### PR DESCRIPTION
**Pull request by Darkstone245**
I would like to commit this school to the list, since it's my school, and Im currently working in the IT-Club there and use CLion to program my Arduinos. Since Im a student, im not able to pay the license and would like to use the school program.

I hope for the Best!
Alexander

### CODE REVIEW

**Comment by philipto** [comment]
@Darkstone245 The first verification stage is complete: the official domain for  **Werner-Heisenberg-Gymnasium Leverkusen** is [foursquare.com](https://foursquare.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://foursquare.com/v/werner-heisenberg-gymnasium-leverkusen/51120c73e4b08631780f588c

**Comment by Darkstone245** [comment]
The Website of my school is actually https://whg-lev.de, sorry for not saying that in the first place

**Comment by philipto** [comment]
@Darkstone245 The first verification stage is complete: the official domain for  **Werner-Heisenberg-Gymnasium Leverkusen** is [foursquare.com](https://foursquare.com), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://foursquare.com/v/werner-heisenberg-gymnasium-leverkusen/51120c73e4b08631780f588c

**Comment by philipto** [comment]
@Darkstone245 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
