### PR TITLE
Add HTL-Rankweil to domain list

### PR DESCRIPTION
**Pull request by briefkasten1988**

### CODE REVIEW

**Comment by briefkasten1988** [comment]
**the school official website URL:** 
https://www.htl-rankweil.at/

**the school street address, including city and country:**
Höhere Technische Bundeslehr- und Versuchsanstalt Rankweil
Negrellistraße 50
A-6830 Rankweil

an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: 
https://www.htl-rankweil.at/fileadmin/Stundentafeln/20210907_Stundentafel_IF.pdf
https://www.htl-rankweil.at/informatik/hoehere-lehranstalt-fuer-informatik/

**Comment by philipto** [comment]
@briefkasten1988 lib/domains/at/htl-rankweil.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@briefkasten1988 First stage of verification passed, official domain is [htl-rankweil.at](https://htl-rankweil.at) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@briefkasten1988 Pull request merged. Thank you.

**Pull request merged**
