### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by scalsin**
Add domain "Universidad Continental"

### CODE REVIEW

**Comment by philipto** [comment]
@scalsin Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@scalsin You might miss my previous comment. Please react.

**Comment by scalsin** [comment]
Hi, we just shared office web site.

https://www.continental.edu.pe/

and some places where it was mentioned.

https://ucontinental.edu.pe/politica-de-privacidad/
[image: image.png]


https://ucontinental.edu.pe/misdatos/
[image: image.png]

regards.

**Comment by philipto** [comment]
@scalsin The pages that you have mentioned above refers to a different email domain: @coninental.edu.pe.
It is already in the trusted list. The respective pull request #15095 was merged last week.

As for the email domain continental.pe, I did not find evidence that thus university supports it.

I close this request without merging. If you have an update, please:
1) Reopen this request or create a new one
2) Upload the images that you believe support your request directly to GitHub via browser. GitHub strips out all attachments when you send them by email.

As for now, I have to close this request.

**Pull request closed without merging**
