### PR TITLE
Create bzwu

### PR DESCRIPTION
**Pull request by ScrummerLP**
Please add this school that I can register myself for the students Version of the JetBrains IDE's. Lot's of thanks

### CODE REVIEW

**Comment by philipto** [comment]
@ScrummerLP Could you please provide us with a link to a page on the official website which shows that the school offers at least one long-term course (one year or longer), and the course is somehow related to IT (it is in computer science, software engineering, statistics, bioinformatics, etc.)

Also, please rename the file bzwu to bzwu.txt, because .txt extension is essential in this repository.

Thank you!

**Comment by ScrummerLP** [comment]
http://www.bzwu.ch/berufe/berufslehre/mediamatiker

It's the apprenticeship which I visit; in the USA/UK it should be called "Webdeveloper"

**Comment by philipto** [comment]
@ScrummerLP Thank you! For *@bzwu.educanet2.ch* file path has to be `lib/domains/ch/educanet2/bzwu.txt`. Please move the file to educanet2 folder, and then I'll merge the pull request. Thank you!

**Comment by ScrummerLP** [comment]
should be moved now.
Thank you a lot!

**Comment by philipto** [comment]
@ScrummerLP Thank you! Pull request merged.

**Comment by ScrummerLP** [comment]
@philipto One more question: I still can't apply for a students version of the JetBrains IDE's: http://puu.sh/ogJ5w/3c5a3bbd13.png

Does it just take a while until the system registers my university, or is there a mistake in the process?

**Comment by philipto** [comment]
@ScrummerLP We experience a technical problem now with the request processing. I'll comment here again, as soon as we resolve the issue. Sorry for the trouble.

**Comment by ScrummerLP** [comment]
@philipto Thank you for your fantastic support :+1:

**Comment by philipto** [comment]
@ScrummerLP It works now. Please try again if you did not request the license successfully yet. Thank you for using the tools!

**Pull request merged**
