### PR TITLE
Added Everest Engineering College name and domain urls

### PR DESCRIPTION
**Pull request by manojpudasaini**
Everest Engineering College was formerly recognized as Everest Engineering College. This institution is providing  IT and Computer related  Bachelors of Engineering degrees since 2001 A.D. I am applying so that i can get my student license and use these awesome IDEs.
https://www.eemc.edu.np/contact

### CODE REVIEW

**Comment by philipto** [comment]
@manojpudasaini First stage of verification passed, official domain is [eemc.edu.np](https://eemc.edu.np) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by manojpudasaini** [comment]
@philipto Thank you !

**Comment by philipto** [comment]
@manojpudasaini Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by manojpudasaini** [comment]
> @manojpudasaini Thank you for your patience while waiting for a review and processing your request. Pull request merged.

Thank you so much for your help!

**Pull request merged**
