### PR TITLE
Create univ-eiffel.fr

### PR DESCRIPTION
**Pull request by thanhlongdang**
Create université Gustave Eiffel

### CODE REVIEW

**Comment by philipto** [comment]
@thanhlongdang I am sorry, this university seems to have different official internet domain. 
Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@thanhlongdang You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@thanhlongdang I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Comment by thanhlongdang** [comment]
Hi Philip,

The officiel internet domain is https://www.univ-gustave-eiffel.fr/ but our mail adress our @univ-eiffel.fr.

IT long term course : https://formations.univ-gustave-eiffel.fr/index.php?id=1941&tx_agof_brochure%5Bbrochure%5D=565&tx_agof_brochure%5Bcontroller%5D=Brochure&tx_agof_brochure%5Baction%5D=show&cHash=bd329cb13b062727e2f7f71d261f0b9f
=> 2 years

Regards,
Thanh


________________________________
De : Philip Torchinsky <notifications@github.com>
Envoyé : lundi 27 avril 2020 20:34
À : JetBrains/swot <swot@noreply.github.com>
Cc : DANG Thanh-Long <thanhlong.dang@multidist.eu>; Mention <mention@noreply.github.com>
Objet : Re: [JetBrains/swot] Create univ-eiffel.fr (#8208)


@thanhlongdang<https://github.com/thanhlongdang> I am sorry, this university seems to have different official internet domain.
Please provide us with:

  *   the school official website URL, if different from the domain you are submitting
  *   an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
  *   an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Pull request closed without merging**
