### PR TITLE
Add Topica Edtech Group (Tổ hợp Công nghệ giáo dục Topica)

### PR DESCRIPTION
**Pull request by nighttiger1990**
Tổ hợp công nghệ giáo dục Topica
Domain: https://topica.edu.vn/

### CODE REVIEW

**Comment by philipto** [comment]
@nighttiger1990 Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@nighttiger1990 You might miss my previous comment. Please react.

**Comment by nighttiger1990** [comment]
@philipto Our school associate with universities in Vietnam (TNU, NEU, FTU...) and provide degree 2 with a 4-year roadmap with many IT-related-course. This is one (TOPICA-TNU) of them 
image
image
image

**Comment by philipto** [comment]
@nighttiger1990 Thank you for the clarification. I am sorry for a delay with processing your request.
It required an additional investigation to ensure that the domain is qualified to be added here. Pull request is now merged. Thank you!

**Pull request merged**
