### PR TITLE
Create inhatc.txt

### PR DESCRIPTION
**Pull request by immin0241**
College official website: https://eng.inhatc.ac.kr/sites/eng/index.do
Student email: @itc.ac.kr

### CODE REVIEW

**Comment by philipto** [comment]
@immin0241 The first verification stage is complete: the official domain for  **Inha Technical College** is [eng.inhatc.ac.kr](https://eng.inhatc.ac.kr), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://eng.inhatc.ac.kr/oia/1940/subview.do

**Comment by philipto** [comment]
@immin0241 Thank you for your request. You say that  student email is **@itc.ac.kr**, but you request to add another domain to the repository - **inhatc.ac.kr**. Is it correct?

**Comment by immin0241** [comment]
@philipto Sorry for the confusion. I've changed inhatc.txt to itc.txt, so kindly review this request. Thank you.

**Comment by philipto** [comment]
@immin0241 Thank you for the update and your patience while waiting for a review and processing your request. Pull request merged.

**Comment by immin0241** [comment]
@philipto thanks for your update, but I still can't apply to educational license. I think the file lib/domains/stoplist.txt includes my school's domain(itc.ac.kr), so your system is blocking me from applying.

**Comment by philipto** [comment]
@immin0241 Yes, it's regrettably the case. Regrettably, there is a solid reason for that. 

Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for the understanding!

**Pull request merged**
