### PR TITLE
Added Sorumsand VGS

### PR DESCRIPTION
**Pull request by MathiasT**

### CODE REVIEW

**Comment by MathiasT** [comment]
We used to use Akershus-fk.no but it changed to vgsa.no there is no current website for vgsa.no but if you check the registrar it should be Akershus which owns Sørumsand VGS

**Comment by zweizwei** [comment]
@MathiasT both domain you are mentioning belong to county administration as the school's domain seems to be www.sorumsand.vgs.no - could you tell me if anyone but teachers and students use vgsa.no for emails?

**Comment by MathiasT** [comment]
@zweizwei Students use vgsa.no and teachers use sorumsand.vgs.no I think it's VGSA for every school in Akershus but not sure.

**Comment by zweizwei** [comment]
@MathiasT I'd need an official reference for this information (for vgsa.no at least) - any confirmation page on a school website, desrcibing this system, or a letter from teacher, should be fine. Please provide!

**Comment by zweizwei** [comment]
Closing the request till the answer comes

**Pull request closed without merging**
