### PR TITLE
Added some institutuions in TamilNadu, India

### PR DESCRIPTION
**Pull request by johnhydenc**

### CODE REVIEW

**Comment by philipto** [comment]
@johnhydenc lib/domains/edu/psgtech: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by psyirius** [comment]
please close this pr.
i made an account transfer to this account.
i'm not able to make any changes to it.
I'll make a new PR.

**Comment by psyirius** [comment]
> @johnhydenc lib/domains/edu/psgtech: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.

Oops sorry. forgot the txt extension lol.
Fixed the issues. (Recently made an repo transfer tho, thus the new account)
Should be good now i guess.

**Comment by philipto** [comment]
@johnhydenc Thank you. Your request contains significantly more domains that a usual one. Therefore, it will be processed later, and it'll take more time than usual. I appreciate your patience and understanding.

**Comment by psyirius** [comment]
It's okay.
I just added the institutions those I've personally visited and has a Computer Science and or related courses.

**Comment by philipto** [comment]
@johnhydenc Thank you for your patience and the contribution!
I reviewed the schools, and had to remove two of them: Loyola Institute of Technology and Science, Thovalai and Marthandam College of Engineering and Technology, because their website do not provide enough up-to-date information about their IT-related courses.

All other schools are eligible for being added to this repository, thus I corrected and merged your pull request. 
Thank you!

**Pull request merged**
