### PR TITLE
Create wsinf.txt

### PR DESCRIPTION
**Pull request by DariuszKusiak**

### CODE REVIEW

**Comment by philipto** [comment]
@DariuszKusiak Could you please provide us with an official College of Computer Science in Lodz website URL, and a page where wsinf.eu is said to be a email domain for the College students? Thank you!

**Comment by DariuszKusiak** [comment]
Official website: http://wsinf.edu.pl/eng/

and

https://mensa.wsinf.edu.pl/gmail/


W dniu 2016-09-02 o 14:11, Philip Torchinsky pisze:

**Comment by philipto** [comment]
@DariuszKusiak Thank you! I looked through the webpages, and found that:
1) Full name of the university is "University of Computer Sciences and Skills in Łódź", not "College of Computer Science in Lodz". I'd suggest to correct it in the file in your request.
2) Email domain for the students is student.wsinf.eu, not wsinf.eu, and the file path for it has to be lib/domains/eu/wsinf/student.txt. Could you please change it, if you don't mind? Please comment if there are some issues with the modifications which I suggest. Thank you!

**Comment by philipto** [comment]
@DariuszKusiak Could you please comment on the issues above? We cannot proceed without your input. Thank you!

**Comment by DariuszKusiak** [comment]
I created a new request for the student.wsinf.eu e-mail domain and file path lib/domains/eu/wsinf/student.txt

Thank you.

**Pull request closed without merging**
