### PR TITLE
Add University dou.edu.ng. Add files via upload.

### PR DESCRIPTION
**Pull request by MsrEmmanuel**
Adding Dennis Osadebay University.

### CODE REVIEW

**Comment by philipto** [comment]
@MsrEmmanuel First stage of verification passed, official domain is [dou.edu.ng](https://dou.edu.ng) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by MsrEmmanuel** [comment]
Thanks

**Comment by philipto** [comment]
@MsrEmmanuel The domain looks legitimate, but the official website does not work. It seems to be hijacked or broken, because no links from the front page work. I will get back to this request later to try verifying the domain again.

**Comment by MsrEmmanuel** [comment]
I think that' happens for now because, it's probably under maintenance or it's being worked on or maybe as you say. I appreciate your work, thanks.

**Comment by MsrEmmanuel** [comment]
Thanks

**Comment by philipto** [comment]
@MsrEmmanuel The website still does not work properly. I will get back to the request later. Thank you for your understanding.

**Comment by MsrEmmanuel** [comment]
Hello

**Comment by philipto** [comment]
@MsrEmmanuel The website still does not work. I close the request without merging. Please reopen it or create a new one as soon as the website contains relevant information and works. Thank you.

**Pull request closed without merging**
