### PR TITLE
added MCCI Business School

### PR DESCRIPTION
**Pull request by mnnayeck**

### CODE REVIEW

**Comment by philipto** [comment]
@mnnayeck First stage of verification passed, official domain is [mccibusinessschool.org](https://mccibusinessschool.org) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.mccibusinessschool.org/contact/

**Comment by philipto** [comment]
@mnnayeck Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by philipto** [comment]
@mnnayeck You might miss my previous comment. Please react.

**Comment by mnnayeck** [comment]
Hello Philip,

Apologies for the delay.

Here you go: https://www.mccibusinessschool.org/formations/licence/


Regards,
Nadeem

**Comment by mnnayeck** [comment]
I sent the wrong link,

This is the right one:

https://www.mccibusinessschool.org/courses/bts-informatique/

**Comment by philipto** [comment]
@mnnayeck  Thank you very much for the clarifications. Pull request merged.

**Pull request merged**
