### PR TITLE
lib/domains/ua/in/mdu.txt

### PR DESCRIPTION
**Pull request by AndriiVasylenko-bit**
Screenshot 2023-12-14 205222

### CODE REVIEW

**Comment by philipto** [comment]
@AndriiVasylenko-bit First stage of verification passed, official domain is [en.mdu.in.ua](https://en.mdu.in.ua) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://en.mdu.in.ua/

**Comment by AndriiVasylenko-bit** [comment]
Our university updates domain name to [https://mu.edu.ua/](https://mu.edu.ua/)

**Comment by AndriiVasylenko-bit** [comment]
Hello @philipto! How to come confirmation of domain ownership?

**Comment by AndriiVasylenko-bit** [comment]
Hello @philipto this is my curse [https://mu.edu.ua/uk/educational-programs/sistemniy-analiz](https://mu.edu.ua/uk/educational-programs/sistemniy-analiz).

**Comment by philipto** [comment]
@AndriiVasylenko-bit It is not necessary to prove that Mariupol State University, now operating in Kyiv, owns a domain **mu.edu.ua**. However your request is to add a domain **mdu.in.ua**, which is registered to another organization. Therefore, I cannot merge the request. 

Please clarify in which domain students of the university have their email addresses assigned to them by the university. If it's **mdu.in.ua**, please provide us with a proof, which shows that the school recognizes the domain **mdu.in.ua** as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

Thank you!

**Comment by AndriiVasylenko-bit** [comment]
image
Good time of day! @philipto! it's enough?
And what you need to do to also add a domain: yourname@mu.edu.ua?

**Comment by philipto** [comment]
@AndriiVasylenko-bit Is it enough to add **mu.edu.ua** only? If yes, I add it immediately. Why do you wish to add also mdu.in.ua if it will no longer be used for students and teachers?

**Comment by AndriiVasylenko-bit** [comment]
Good afternoon, @philipto! yes, enough to add mu.edu.ua.

**Comment by philipto** [comment]
@AndriiVasylenko-bit  Thank you for the clarifications. Pull request merged.

**Pull request merged**
