### PR TITLE
Create ce.sharif.edu

### PR DESCRIPTION
**Pull request by EngNahidBehjati**

### CODE REVIEW

**Comment by Ajal88** [comment]
According to the [rule](https://github.com/JetBrains/swot#which-educational-institutions-can-be-added-to-the-repository) "The domain is used by an educational institution, which offers at least one long-term course (one year or longer), and the course is somehow related to IT (it is in computer science, software engineering, statistics, bioinformatics, etc.)", ce.sharif.edu maybe a better choice.

**Comment by Ajal88** [comment]
The university official website URL : [www.sharif.edu](www.sharif.edu)
An URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university : [ce.sharif.edu](ce.sharif.edu)
an URL of a page or another proof: [Associate Professor Shaahin Hessabi](http://sharif.edu/~hessabi/Home.html)

**Comment by philipto** [comment]
@EngNahidBehjati I am very sorry, but this organization can not be approved for this list due to legal restrictions. I have to close the request without merging. Thank you for the understanding.

**Comment by shervinkh** [comment]
@philipto
No one can "understand" your stupid legal restrictions!

**Comment by pi0** [comment]
Now only idiots use f***ing slow JetBrains products! Use VSCode ;)

https://code.visualstudio.com

**Comment by shervinkh** [comment]
I hate jetbrains and I never use their products. But this behaviour of theirs is very rude and irrational and should be opposed!

**Pull request closed without merging**
