### PR TITLE
Create itisdavinci

### PR DESCRIPTION
**Pull request by karandip98**

### CODE REVIEW

**Comment by philipto** [comment]
@karandip98 According to this page http://www.itis.pr.it/rete/ the official email domain for this institute is itis.pr.it. If you wish to add it to the list of domains known to JetBrains, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and rename lib/domains/it/itisdavinci to lib/domains/it/pr/itis.txt. 

Please reply with the comment.

**Comment by karandip98** [comment]
Yes we can rename it

**Comment by karandip98** [comment]
Yes, as there wasn't the domain pr.it we added the file in that way. Can we create a this domain? thanks

**Comment by philipto** [comment]
@karandip98 Yes, you can. I don't know which way you use to create the file in the repository. You can clone this repository and make a PR from your local computer, you can create a directory lib/domains/it/pr/ there, and file itis.txt in it.

If you have troubles with that you can familiaize with GitHub or comment here that you need help,

What is you email pattern for students in the university? username@itis.pr.it?

**Comment by karandip98** [comment]
@philipto Ok thanks. Email pattern is: name.surname@itis.pr.it

**Comment by karandip98** [comment]
@philipto We have created the domain pr

**Comment by philipto** [comment]
@karandip98 I created the necessary file for you, You can start requesting your free license in about an hour. As for this pull request, I am closing it because it does not contain a file with correct filepath. Thank you.

**Pull request closed without merging**
