### PR TITLE
Register Phoenix College of Management within jetbrain environment

### PR DESCRIPTION
**Pull request by ctalluitel101**

### CODE REVIEW

**Comment by philipto** [comment]
@ctalluitel101 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@ctalluitel101 You might miss my previous comment. Please react.

**Comment by ctalluitel101** [comment]
URL: https://phoenixcollege.edu.np/
Address: Maitidevi, Kathmandu, Nepal
Map: https://www.google.com/maps?ll=27.704138,85.332102&z=16&t=m&hl=en&gl=NP&mapclient=embed&cid=14864733395050658788
Course URL: https://phoenixcollege.edu.np/course/master-of-computer-studies-mcs

**Comment by ctalluitel101** [comment]
@philipto Is there any update for this one please

**Comment by philipto** [comment]
@ctalluitel101 Thank you for the clarifications!
Thank you also for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
