### PR TITLE
added new domain

### PR DESCRIPTION
**Pull request by seruymt**
https://polytech.cv.ua/about-us/viddilennya-programuvannya-ta-radiotehniki/
https://polytech.cv.ua/publichna-informaciya/dokumenti/

https://youcontrol.com.ua/en/catalog/company_details/03363140/

### CODE REVIEW

**Comment by philipto** [comment]
@seruymt First stage of verification passed, official domain is [polytech.cv.ua](https://polytech.cv.ua) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@seruymt There is another domain registered for this school: **chic.cv.ua**. Shall we remove chic.cv.ua and replace it with **polytech.cv.ua**?

**Comment by seruymt** [comment]
@philipto **chic.cv.ua** is another college in our city. We don't have any relations.

**Comment by philipto** [comment]
@seruymt  Thank you for the clarifications. Pull request merged.

**Pull request merged**
