### PR TITLE
Universidad Adventista de Centroamerica

### PR DESCRIPTION
**Pull request by MrEraba**
Universidad Adventista de Centroamerica (UNADECA)

### CODE REVIEW

**Comment by MrEraba** [comment]
UNADECA -> unadeca.ac.cr

**Comment by philipto** [comment]
@MrEraba I am sorry for a delay with processing your request. Could you please rename `lib/domains/net/unadeca` to `lib/domains/net/unadeca.txt` to reflect this repository rules? Thank you!

**Comment by MrEraba** [comment]
@philipto  I did the change, thanks

**Comment by philipto** [comment]
@MrEraba Pull request merged. Thank you!

**Pull request merged**
