### PR TITLE
JetBrains Products for Learning - Adding my school Information

### PR DESCRIPTION
**Pull request by Aryan-401**
My school Email ID

### CODE REVIEW

**Comment by philipto** [comment]
@Aryan-401 File/lib/domains/com/onmicrosoft/tmsnoida.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Aryan-401 File/lib/domains/com/onmicrosoft/tmsnoida.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Aryan-401 File/lib/domains/com/onmicrosoft/tmsnoida.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Aryan-401 You might miss my previous comment. Please react.

Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and correct your request: at least, remove "File" from the file path.

Also, please provide us with:
- the school official website URL, if different from the domain you are submitting
- the school physical address (where it is located: what is the city and the country?)
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Aryan-401** [comment]
Hey Philip,

Do I have to submit the  the school information via mail or in the
repository itself?

-Aryan

**Pull request closed without merging**
