### PR TITLE
Moroccan university added

### PR DESCRIPTION
**Pull request by xyriox**
The website of the university
http://www.emsi.ma/

### CODE REVIEW

**Comment by philipto** [comment]
@xyriox Could you please:
1) rename lib/domains/ma/emsi-edu to lib/domains/ma/emsi-edu.txt (please note that .txt extension is mandatory)
2) provide a link to a page on the official website or other similar proof saying that students have emails in   emsi-edu.ma domain (because it is different from the official website domain).
Thank you!

**Comment by philipto** [comment]
@xyriox Could you please comment the issue I commented about above?

**Comment by xyriox** [comment]
@philipto Yes, understood. there's no official proof but they told us that using these emails gives us free office 2016 which is true as shown in the picture below 
14138195_10208716852173620_4493886127421748781_o

**Comment by philipto** [comment]
@xyriox Thank you for the clarification. Pull request merged. Thank you!

**Comment by xyriox** [comment]
@philipto When would it be functional ?
I just tried right now it says : "Your email address does not belong to any university that we know. Contribute your university to our list."
Was it a mistake of mine in creating the file to enable this domain ? "email@emsi-edu.ma", right ?

**Comment by philipto** [comment]
@xyriox Please try again. Usually, it takes about 30 minutes to be
activated. Please let me know if something does not work still.

2016-09-05 16:55 GMT+03:00 xyriox <notifications@github.com>:

**Comment by xyriox** [comment]
@philipto Thanks it works :)

**Pull request merged**
