### PR TITLE
Adding PWSZ Leszno

### PR DESCRIPTION
**Pull request by 5pyk3r**
Jan Amos Komeński State School of Higher Vocational Education in Leszno, Poland
https://pwsz.edu.pl/index.php/en/
@m.student.pwsz.edu.pl

### CODE REVIEW

**Comment by philipto** [comment]
@5pyk3r To add m.student.pwsz.edu.pl email domain please rename lib/domains/pl/edu/m.txt to lib/domains/pl/edu/pwsz/student/m.txt

**Comment by philipto** [comment]
@5pyk3r You might miss my previous comment. Please react.

**Comment by 5pyk3r** [comment]
@philipto Yes, I missed first your comment, but finally I did this.

**Comment by philipto** [comment]
@5pyk3r Pull request merged. Thank you!

**Pull request merged**
