### PR TITLE
Add American Academy Larnaca

### PR DESCRIPTION
**Pull request by ds003723**

### CODE REVIEW

**Comment by philipto** [comment]
@ds003723 First stage of verification passed, official domain for **American Academy Larnaca** is [academy.ac.cy](https://academy.ac.cy) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by ds003723** [comment]
Hello. Could you inform me please, how long it can take, because I want to start my lessons and my teacher recommends me your product. Thank you in advance.

**Comment by ds003723** [comment]
@philipto Please caould you answer me? how long it will take? Thanks

**Comment by philipto** [comment]
@ds003723 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
