### PR TITLE
Create tksu

### PR DESCRIPTION
**Pull request by mihailovve**
website: https://tksu.ru/
course: https://tksu.ru/sveden/education/ 
about domain use: https://tksu.ru/upload/iblock/670/Pamyatka-o-polzovnii-uchetnoy-zapisyu-universiteta.pdf

### CODE REVIEW

**Comment by philipto** [comment]
@mihailovve lib/domains/ru/tksu: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@mihailovve lib/domains/ru/tksu: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@mihailovve lib/domains/ru/tksu: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by mihailovve** [comment]
Hello. I apologize. For some reason, I did not notice that the domain was already included in 2017.

**Pull request closed without merging**
