### PR TITLE
add University STMIK Pontianak

### PR DESCRIPTION
**Pull request by Ionichi**
stmikpontianak.ac.id

### CODE REVIEW

**Comment by philipto** [comment]
Please kindly provide the full name of your school on the first line of the file in your request

**Comment by Ionichi** [comment]
oke sir, already fix

**Comment by philipto** [comment]
@Ionichi First stage of verification passed, official domain for **STMIK Pontianak** is [stmikpontianak.ac.id](https://stmikpontianak.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Ionichi** [comment]
oke sir, thank you🔥

**Comment by philipto** [comment]
@Ionichi Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
