### PR TITLE
Add Dallas Independent School District (see description)

### PR DESCRIPTION
**Pull request by arjvik**
Dallas ISD contains schools such as the School of Science and Engineering Magnet and the School of the Talented and Gifted, which offer college-level Computer Science classes to their students. Students at the School of Science and Engineering Magnet take courses up to Data Structures, which necessitate a professional-level IDE.

### CODE REVIEW

**Comment by arjvik** [comment]
Proof that the School of Science and Engineering Magnet (my school) offers AP Computer Science (college-level CS course):
https://www.semagnet.org/academics/courses/

**Comment by arjvik** [comment]
Proof that student emails are of the form `0000000@dallasisd.org`, where `0000000` represents the 7-digit student ID number:
https://www.dallasisd.org/site/default.aspx?PageType=3&ModuleInstanceID=48986&ViewID=C9E0416E-F0E7-4626-AA7B-C14D59F72F85&RenderLoc=0&FlexDataID=56718&PageID=36587&Comments=true

**Comment by philipto** [comment]
@arjvik lib/domains/org/dallasisd: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by arjvik** [comment]
@philipto I fixed the format of the filename, and added more lines corresponding to individual school names and aliases

**Comment by philipto** [comment]
@arjvik Pull request merged. Thank you for the details and the contribution!

**Pull request merged**
