### PR TITLE
Create inuka.txt

### PR DESCRIPTION
**Pull request by killerbestshoot**
https://inuka.edu.ht/

### CODE REVIEW

**Comment by philipto** [comment]
@killerbestshoot bibliothèque/domaines/ht/édu/inuka.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by killerbestshoot** [comment]
@philipto cher Philip je vois que vous avez fait une modification est ce maintenant correcte merci pour ton aide

**Comment by philipto** [comment]
@killerbestshoot First stage of verification passed, official domain is [inuka.edu.ht](https://inuka.edu.ht) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@killerbestshoot Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
