### PR TITLE
JetBrains Products for Learning, csrc

### PR DESCRIPTION
**Pull request by pcmagic**
beijing computational science research center

### CODE REVIEW

**Comment by shore2511** [comment]
Holy Cross School Bokaro Jharkhand 
Holy Cross School Bokaro Jharkhand

**Comment by philipto** [comment]
@pcmagic First stage of verification passed, official domain is [csrc.ac.cn](https://csrc.ac.cn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@pcmagic Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

Please notice that this repository is for domains of schools that teach students. If the center does not teach students, it is not eligible for this repository. Please let me know how many students does the center have.

**Comment by philipto** [comment]
@shore2511 Please make a separate request. Mentioned your school in a comment to a third party request does not follow the repository rules. Thank you!

**Comment by philipto** [comment]
@pcmagic You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@pcmagic I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
