### PR TITLE
Added Digital School of Paris

### PR DESCRIPTION
**Pull request by qvtran2020**
https://www.digitalschool.paris/

### CODE REVIEW

**Comment by philipto** [comment]
@qvtran2020 Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@qvtran2020 You might miss my previous comment. Please react.

**Comment by qvtran2020** [comment]
> @qvtran2020 You might miss my previous comment. Please react.

mail2
mail3
mail

**Comment by philipto** [comment]
@qvtran2020 Thank you for the clarification. Pull request merged.

FTR: WHOIS data suggests that the Registrant Organization for this domain is IEF2I, which confirms that it's educational.

**Pull request merged**
