### PR TITLE
Add KPEDU school.

### PR DESCRIPTION
**Pull request by kumina-dev**

### CODE REVIEW

**Comment by kumina-dev** [comment]
https://www.kpedu.fi
https://www.kpedu.fi/hakijalle/koulutustarjonta/koulutus/tieto--ja-viestintätekniikan-perustutkinto_(l6846)

**Comment by philipto** [comment]
@kumina-dev First stage of verification passed, official domain is [kpedu.fi](https://kpedu.fi) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by kumina-dev** [comment]
Yeah kpedu.fi is the official, but student.kpedu is the subdomain which is used for the emails

**Comment by philipto** [comment]
@kumina-dev Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
