### PR TITLE
Create upaep.txt

### PR DESCRIPTION
**Pull request by DennisIvanPM**
Hi, I would like to add this txt file, to add my university or obtain your assistance to add the mentioned file

### CODE REVIEW

**Comment by DennisIvanPM** [comment]
I´m studying mechatronics engineering, but I'm into machine learning and robotics, so I use to create code frequently. Software, systems engineering, and other careers are also offered at my university and my colleagues could use your software to improve their skills.

this is the main website of my university:
https://upaep.mx/?gclid=EAIaIQobChMIs7qzop_y_QIV-hqtBh2TsQRfEAAYASAAEgJrrfD_BwE

**Comment by philipto** [comment]
@DennisIvanPM First stage of verification passed, official domain is [upaep.mx](https://upaep.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://upaep.mx/estudiantes/vida-estudiantil

**Comment by DennisIvanPM** [comment]
@philipto Yeah, the official domain is upaep.mx but is only for employees and teachers, for students it changes to upaep.edu.mx which is also official 
Proof of domain differences:
Contacto: Lic. Bianca Sánchez Camacho
bianca.sanchez@upaep.mx 
(Employee) 
Contacto: Montserrat Lázaro
montserrat.lazaro@upaep.edu.mx
(Student)
Reference: https://upaep.mx/estudiantes/vida-estudiantil

**Comment by philipto** [comment]
@DennisIvanPM Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
