### PR TITLE
Add domain angergymnasium.jena.de

### PR DESCRIPTION
**Pull request by callypo**
Add Staatliches Angergymnasium Jena
http://www.angergymnasium.jena.de/

### CODE REVIEW

**Comment by philipto** [comment]
@callypo could you please rename lib/domains/de/jena/angergymnasium to lib/domains/de/jena/angergymnasium.txt. Thank you!

**Comment by callypo** [comment]
@philipto done

**Comment by callypo** [comment]
A moment ago I read that you just take university emails. I added a secondary school, so you can close the pull request. I'm sorry for the circumstances!

**Comment by philipto** [comment]
@callypo No problem. The pull request merged anyway. "Secondary school" means different things in different countries, and it's fine if there are students who are over 13 of age in your school. Just notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Pull request merged**
