### PR TITLE
add a new school

### PR DESCRIPTION
**Pull request by kurakigo**

### CODE REVIEW

**Comment by PaulJScript** [comment]
[file.zip](https://github.com/JetBrains/swot/files/12228586/file.zip)

**Comment by PaulJScript** [comment]
Please add the school :)

**Comment by kurakigo** [comment]
the school is ESADD. The official domain is esadd.fr

**Comment by philipto** [comment]
@kurakigo First stage of verification passed, official domain is [esadd.fr](https://esadd.fr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Pull request merged**
