### PR TITLE
Create GcsLahore.txt

### PR DESCRIPTION
**Pull request by gcs-abdulwahab**
I though it is in process

Instead of forking  I   just added the file   and creating PULL Request

### CODE REVIEW

**Comment by gcs-abdulwahab** [comment]
What is the time for confirmation ?

**Comment by gcs-abdulwahab** [comment]
website :  https://www.gcslahore.edu.pk
1000 plus students 
Offering BS Computer Science 4 years  among many BS Programs

**Comment by gcs-abdulwahab** [comment]
You see   all the educational institutes in pakistan  get the  edu.pk domain after a thorough process   
there is an organization in pakistan   https://www.pknic.net.pk/   which after thorough process assigns the    edu.pk   to an organization . It is only issued  on the official letter head from the head of institute.
 We have purchased this domain around 2012   and recently it is forwared to  google sites  till we finalize a proper wordpress site .
you can also verify all the educational institutes in pakistan   have   .edu.pk 

I pull the request a month ago as well  but  it was closed due to same concerns by you 

what I want is that after registering  gcslahore  which is Govt Graduate College of Science Wahdat Road Lahore 
all the students do not have to go through the lengthy process 

Please do let me know if you need any proof from the College Administration .

**Comment by gcs-abdulwahab** [comment]
> https://www.facebook.com/gcswrlahore/
> 
> This is the facebook account you can verify from the post it is been running since long time it has more than 27K followers the website name is also mentioned there

facebook proof

**Comment by philipto** [comment]
@gcs-abdulwahab Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
