### PR TITLE
Added Maiden Erlegh school

### PR DESCRIPTION
**Pull request by subeenregmi**
Link to school page - https://www.maidenerleghschool.co.uk 
Link to the computing department - https://www.maidenerleghschool.co.uk/page/?title=Computer+Science&pid=329 
Link to sixth form page - https://www.maidenerleghschool.co.uk/page/?title=Computer+Science&pid=401

### CODE REVIEW

**Comment by philipto** [comment]
@subeenregmi Could you please check if there is a typo in the filename in your request? It is lib/domains/uk/co/maidenerleghschools.txt, and it represents the domain [maidenerleghschools.co.uk](https://www.maidenerleghschools.co.uk/), while your school owns the domain [maidenerleghschool.co.uk](https://www.maidenerleghschool.co.uk/) (without "s" at the end of maidenerleghschool.)

**Comment by subeenregmi** [comment]
Hi, our school emails are all user@maidenerleghschools.co.uk with the s, it seems like the website isn't the same domain name. Thanks, Subeen.

**Comment by philipto** [comment]
@subeenregmi Thank you. Could you please provide us with a proof, which shows that the school recognizes the domain maidenerleghschools.co.uk as an official email domain for the students?

You can provide us with any of the following as the proof:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@subeenregmi You might miss my previous comment. Please react.

**Comment by subeenregmi** [comment]
oh sorry, ill get this today thanks!

**Comment by subeenregmi** [comment]
Currently I am in process of getting all an email from my computer science teacher but currently this is all I have: the computer science website hosted on the google domain @maidenerleghschools.co.uk :  https://sites.google.com/maidenerleghschools.co.uk/computingdepartment/home?authuser=0

**Comment by subeenregmi** [comment]
@philipto Can you please check this?

**Comment by philipto** [comment]
@subeenregmi  Thank you for the clarifications. The message above does not qualify as a proof because it's not a verifiable screenshot, but I found an independent proof. **Pull request merged.**

FTR: domain ownership proof is https://www.maidenerleghschool.co.uk/attachments/download.asp?file=1228&type=pdf

**Pull request merged**
