### PR TITLE
Add ibaraki high school and junior high school

### PR DESCRIPTION
**Pull request by wolwolf**
https://www.ibaraki-jsh.ed.jp/

### CODE REVIEW

**Comment by philipto** [comment]
@wolwolf Please provide us with:
* the school official website URL
* the school official full name, both in Japanese and English (or just in English, it's up to you).
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you!

**Comment by philipto** [comment]
@wolwolf You might miss my previous comment. Please react.

**Comment by wolwolf** [comment]
Sorry for the late reply.

・URL:https://www.ibaraki-jsh.ed.jp/
・name:Ibaraki high school,Ibaraki junior high school(We use the same domain)
・address:16-1 Hachiman-cho, Mito-city, Ibaraki, Japan

I could not find any certificate indicating that the URL and domain of the page on the official website of the school offering IT-related long-term courses is recognized by the school as the official email domain for students.

**Comment by philipto** [comment]
@wolwolf  Thank you for the clarifications. Regrettably, it's not enough proof that the school uses this email domain as official one for the students. Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
