### PR TITLE
Added Elizabeth Seton School domain

### PR DESCRIPTION
**Pull request by rudym02**
Added Elizabeth Seton School domain

### CODE REVIEW

**Review by rudym02 — COMMENTED** [review]
Added Elizabeth Seton School domain

**Comment by philipto** [comment]
@rudym02 First stage of verification passed, official domain is [ess.edu.ph](https://ess.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@rudym02 Please provide us with a correct link to high school description. This one at the website does not work: https://www.ess.edu.ph/programs-high-school/

Thus, I cannot verify the school eligibility for the trusted list right now. Thank you.

**Comment by philipto** [comment]
image

**Comment by rudym02** [comment]
Hi Philips,

These are the links referring to senior/high school programs.
https://www.ess.edu.ph/programs-others/
https://www.ess.edu.ph/about-us-mission-vision/

I used the IntelliJ tool for my Computer ed and robotics subjects.
The student portal is not accessible publicly, provided a screenshot for
reference
[image: image.png]

I'm hoping you could provide me with an IntelliJ license for my personal
use because I can't afford to buy it. Thank you for your consideration.

Cheers,
rudym

**Comment by philipto** [comment]
@rudym02 Regrettably, I just found out that this request has signs of fraud. I have to close it without merging.

If you need the license for yourself only, please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

If you are Delivery Lead/Technical Architect in Manila as one could suggest, please take a look at the page https://www.jetbrains.com/store/#personal. You may find that IntelliJ IDEA Ultimate is more affordable for **individual users** than you might think.

**Pull request closed without merging**
