### PR TITLE
Create kkc

### PR DESCRIPTION
**Pull request by butsasha**

### CODE REVIEW

**Comment by butsasha** [comment]
We are have one more problems. 
Domain named on ukranian as KKZ "Kiivsky koledj zviazky"
But on Engnish it would be "KKC". So, i'm confusedly

**Comment by alihusnainarshad** [comment]
Please Tell Your Institute Web URL

**Comment by butsasha** [comment]
Kkz.net.ua

чт, 2 авг. 2018 г., 21:14 Ali Husnain Arshad <notifications@github.com>:

**Comment by alihusnainarshad** [comment]
@butsasha you should delete this commit because it's wrong.

**Comment by butsasha** [comment]
@alihusnainarshad here is ok? 
https://github.com/JetBrains/swot/pull/5039

**Comment by alihusnainarshad** [comment]
Yes , #5039 is correct
But you should add the requirements there...

**Comment by butsasha** [comment]
@alihusnainarshad what requirements exactly?

**Comment by alihusnainarshad** [comment]
https://github.com/JetBrains/swot/blob/master/README.md

Please Have a Look on this page.

**Comment by butsasha** [comment]
@alihusnainarshad now everything seems ok. Thx so much

**Pull request closed without merging**
