### PR TITLE
add etu.iad-arts.be

### PR DESCRIPTION
**Pull request by acroweb**

### CODE REVIEW

**Comment by philipto** [comment]
@acroweb Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school

**Comment by acroweb** [comment]
The website of the school is www.iad-arts.be

**Comment by philipto** [comment]
@acroweb I am sorry, it looks like I was not clear enough asking the question. 
Please, give me an URL of **an IT-related long-term (>1 year) course offered by the school**
In other words: what you need JetBrains tools for? 

I did not find any course at this school website which requires programming. That is why I need to understand which course JetBrains tools can be useful for. 

JetBrains grants educational licenses to students who need the tools. Students who do not need the tools may mistakenly think that they can take the tool for free and pass it to someone else, which is against the terms and conditions.

**Comment by philipto** [comment]
@acroweb You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@acroweb I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Comment by acroweb** [comment]
Here is the link for the it part of our school : http://www.iad-arts.be/fr/baccalaureat-multimedia-180-ects
You can also see here all the program for these courses : https://intranet.iad-intra.be/sites/default/files/users/michel.wouters/iad-presentation-du-cursus-de-baccalaureat-multimedia-septembre-2018.html

**Pull request closed without merging**
