### PR TITLE
Add SMK Bina Essa

### PR DESCRIPTION
**Pull request by imansmkbinaessa**
SMK Bina Essa is Vocational High School in Indonesia that provide education majoring in: Teknik Bisnis Sepeda Motor (Motorcycle System and Business) and Otomatisasi Tata Kelola Perkantoran (Office Administration and Automation)

### CODE REVIEW

**Comment by philipto** [comment]
@imansmkbinaessa First stage of verification passed, official domain is [smkbinaessa.sch.id](https://smkbinaessa.sch.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@imansmkbinaessa Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by imansmkbinaessa** [comment]
https://smkbinaessa.sch.id/read/12/detail-jurusan-otkp

Office Automation & Governance or commonly abbreviated as OTKP, formerly known as Office Administration or AP is one of the branches of the field of Business and Management expertise studying Typing of scripts or documents, Telephone handling, Arrangement and management of letters or documents, Arranging and managing archives, Handling business trips , Handling petty cash funds, Preparing meetings or meetings, Handling applications, and Handling information via the internet.

**Comment by imansmkbinaessa** [comment]
_Jurusan OTKP_ is a major that focuses on Office administration such as: document management, office automation, spreadsheet, introduction to programming language (python, javascript). The programme itself consists of three years study in vocational highschool.

**Comment by philipto** [comment]
@imansmkbinaessa  Thank you for the clarifications. Pull request merged.

**Pull request merged**
