### PR TITLE
Added txt file for Liberty High School, domain basdschools.org

### PR DESCRIPTION
**Pull request by Jaiming724**

### CODE REVIEW

**Comment by philipto** [comment]
@Jaiming724 Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@Jaiming724 You might miss my previous comment. Please react.

**Comment by Jaiming724** [comment]
Sorry I must have missed the notification. 
Official school url- https://basdwpweb.beth.k12.pa.us/liberty/
Address-1115 Linden St, Bethlehem, PA 18018 United States
Course- https://basdwpweb.beth.k12.pa.us/liberty/wp-content/uploads/sites/7/2017/11/BASD_POS-2018-19.pdf **Page 54**
image

**Comment by philipto** [comment]
@Jaiming724 Thank you for the clarification. Pull request merged.

**Pull request merged**
