### PR TITLE
Add Academia Militar

### PR DESCRIPTION
**Pull request by HBRebelo**
[Academia Militar](https://academiamilitar.pt/internacional/welcome.html)

### CODE REVIEW

**Comment by philipto** [comment]
@HBRebelo lib/domains/pt/academiamilitar: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by HBRebelo** [comment]
Dear @philipto,

Is there any additional change required to the file? Or did you already changed the file to the correct format?

Thank you very much.

Best regards,
H Rebelo

**Comment by philipto** [comment]
@HBRebelo First stage of verification passed, official domain for **Academia Militar** is [academiamilitar.pt](https://academiamilitar.pt) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@HBRebelo Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
