### PR TITLE
Update on files to add domain

### PR DESCRIPTION
**Pull request by karkim7**
https://my.carolinau.edu/ICS/Students/

### CODE REVIEW

**Comment by karkim7** [comment]
https://my.carolinau.edu/ICS/Students/

**Comment by philipto** [comment]
@karkim7 Carolina I am sorry, I have to close the request without merging, because you made a mistake in a request and did not specify any filepath. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and make a new correct request. Thank you for your understanding!

**Comment by philipto** [comment]
@karkim7 I reopened the request, corrected the filenames. The request will be reviewed again a bit later today. Thank you.

**Comment by philipto** [comment]
@karkim7 Thank you for your patience while waiting for a review and processing your request. Pull request merged. Please start applying for JetBrains educational subscription at https://www.jetbrains.com/shop/eform/students **in an hour, to allow the changes to propagate through JetBrains systems**.

**Pull request closed without merging**
