### PR TITLE
Added afpa.fr

### PR DESCRIPTION
**Pull request by Oliv-**
Added "AFPA, Association Nationale pour la Formation Professionnelle des Adultes" : Public, first training organization in France.

### CODE REVIEW

**Comment by philipto** [comment]
@Oliv- I am sorry for a delay with processing your request. This repository contains records of universities and colleges offering some long-term IT-related courses (> 1 year). Could you please give us a reference to such courses on your website?

**Comment by philipto** [comment]
@Oliv- You may not receive the previous message from us. This repository contains records of universities and colleges offering some long-term IT-related courses (> 1 year). Could you please give us a reference to such courses on AFPA website?

**Comment by Oliv-** [comment]
@philipto : Ok. Afpa does not provide more than 1 year training.

**Comment by philipto** [comment]
@Oliv- Thank you for the clarification! I feel I need some more information about the training organization to decide whether it can fit this repository requirements, or is it better to use Classroom license. Two questions:
1) who has an email from @afpa.fr domain? Are they just AFPA teachers and students who attend the classes in person, or they also can be online students (who never appear physically in the university)? Can AFPA alumni use their email addresses in the domain after the graduation?
2) How many people take the course in software development or other IT-related courses? If there are few of them (like 20-30 people annually), it make more sense to give Classroom license to the course(s) teacher and the teacher distributes the license among the students.

Thank you!

**Comment by philipto** [comment]
@Oliv- This request remains unanswered for a while. According to our comments above, I close it without merging. Could you please request a Classroom licenses by email to classroom@jetbrains.com? It is also free and looks more appropriate in case of your institution. Thank you for your understanding!

**Pull request closed without merging**
