### PR TITLE
Add Campus Varberg

### PR DESCRIPTION
**Pull request by OscarKarlsson**
Add the school Campus Varberg

### CODE REVIEW

**Comment by m2adel** [comment]
[azharonline.txt](https://github.com/JetBrains/swot/files/6705347/azharonline.txt)

**Comment by OscarKarlsson** [comment]
URL to website with course(in swedish): https://campus.varberg.se/yrkeshogskola/systemutvecklare-net

**Comment by OscarKarlsson** [comment]
Student email: @edu.varberg.se

**Comment by philipto** [comment]
@OscarKarlsson I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Pull request merged**
