### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by FarukOzturks**
https://gaib.meb.k12.tr
xxx@gaib.web.tr

### CODE REVIEW

**Comment by philipto** [comment]
@FarukOzturks lib/domains/tr/proof.PNG: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
The picture below was mistakenly added as a file in the request. Moving it to the comment.
proof

**Comment by philipto** [comment]
@FarukOzturks Thank you for your request. Regrettably, the attached proof is not enough to confirm that the school recognizes the email domain gaib.web.tr as the official email domain. 

Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by FarukOzturks** [comment]
This e-mail address is not given to everyone in the school. Is the paper signed by the teacher sufficient to give it to the students in the computer department of the school?

**Comment by FarukOzturks** [comment]
I used the translation, sorry if it's wrong

**Comment by philipto** [comment]
> Is the paper signed by the teacher sufficient to give it to the students in the computer department of the school?

Yes. Please upload the photo or a scan of the paper here, using your browser as a comment to this request at https://github.com/JetBrains/swot/pull/13821. Please do not send it as attachment by email because GitHub strips out all email attachments. Thank you.

**Comment by FarukOzturks** [comment]
WhatsApp Image 2022-03-24 at 16 14 35
g)

**Comment by FarukOzturks** [comment]
[0592_001.pdf](https://github.com/JetBrains/swot/files/8341747/0592_001.pdf)
WhatsApp Image 2022-03-24 at 16 14 35

**Comment by philipto** [comment]
@FarukOzturks lib/domains/tr/proof.PNG: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by FarukOzturks** [comment]
I removed

**Pull request closed without merging**
