### PR TITLE
edu.rocmn.nl added

### PR DESCRIPTION
**Pull request by Crecket**
Domain for Roc Midden Nederland added

https://www.rocmn.nl/ is the main website. 
All students have a email using <student id>@edu.rocmn.nl

### CODE REVIEW

**Comment by philipto** [comment]
@Crecket Could you please give us more details about the school? If I am not mistaken, the web site says it is the organization, which is an umbrella for many colleges. We almost never add such organizations to this repository, and do it exclusively if the colleges under the umbrella do not have their own email domains at all.

We encourage individual colleges to register in this repository instead of adding an umbrella domain, where anybody can have an email, not only students and teachers.

Also please let us know whether your students can be purely online students (i.e., have no classes to attend offline, in a classroom). We DO NOT grant free licenses to students who are studying in online universities.

As for the formal side, please change the file path: for edu.rocmn.nl it has to be `lib/domains/nl/rocmn/edu.txt`. Thank you!

**Comment by Crecket** [comment]
[ROCMN](https://www.rocmn.nl/) is only a part of [ROC](http://www.roc.nl). I wouldn't be surprised if other parts of the ROC network offer online colleges but the ROCMN does not offer any online classes.

Only students and teachers from the ROCMN locations have access to this email domain by using their teacher or student id, for example 123456@edu.rocmn.nl

That does mean that the IT part of the ROCMN organisation doesn't have a separate email domain. I'm only a student so I could try and ask one of my teachers if they could arrange something but I highly doubt that they're willing to spend any time/money on setting up a new domain. 

Personally I don't think the other students who follow non-IT classes are even interested in Jetbrain's software anyways and if the domain does get added I'll ask one of the teachers to notify only the IT students.

**Comment by philipto** [comment]
@Crecket Thank you for the details. Don't worry about the separate domain for IT students. When we add a domain into this repository, we have to ensure that (1) the email domain is used by teachers and students, not alumni or third-party staff, and (2) the university or college can be identified by the domain. ROCMN does not have many IT colleges, thus I think both conditions are met. Pull request merged. I am sorry for the delay.

**Comment by Crecket** [comment]
No problem, thanks for adding the domain

**Pull request merged**
