### PR TITLE
Create spdarea.txt

### PR DESCRIPTION
**Pull request by ferile8**

### CODE REVIEW

**Comment by ferile8** [comment]
i added a different file before by mistake with a wrong name, please refere to this one for the domani of scuola politecnica di design - spdarea.it

**Comment by philipto** [comment]
@ferile8 I am sorry, I have to close this request without merging, because you requested to add a non-existent domain(s) to this repository:
```
~$ host spdarea.it
Host spdarea.it not found: 3(NXDOMAIN)
~$ host spdarea.edu
Host spdarea.edu not found: 3(NXDOMAIN)
```
Please ensure you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with correct information. Thank you for the understanding!

**Comment by ferile8** [comment]
i'm sorry, the correct domain is spdarea.com
my mail is triolo@spdarea.com
the website https://spdweb2016.scuoladesign.com/showPage.php?template=menu_valutazioni_studenti&id=2&masterPage=login-studenti.html

**Comment by philipto** [comment]
@ferile8 I am sorry, you still did not give me the information which I need to satisfy your request. We need:
- the university official website URL, if different from the domain you are submitting, I assume that it is http://www.scuoladesign.com
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students. In particular, the official website says that the school's email domain is @scuoladesign.com, and there shall be some document which proves that the students use @spdarea.com.

**Comment by philipto** [comment]
@ferile8 You might miss my previous comment. Please reply.

**Comment by philipto** [comment]
@ferile8 I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the abovementioned issue. Thank you for the understanding!

**Pull request closed without merging**
