### PR TITLE
Add Escuela de Organización Industrial

### PR DESCRIPTION
**Pull request by dcanones**

### CODE REVIEW

**Comment by TerryTran** [comment]
University website: http://www.eoi.es/portal/en

**Comment by philipto** [comment]
@dcanones Please provide us with an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university

**Comment by philipto** [comment]
@dcanones You might miss my previous comment. Please reply.

**Comment by dcanones** [comment]
Hi! And sorry for my late answer, these are the two programes EOI is offering right now, both related to Big Data Technologies:

- https://www.eoi.es/es/cursos/17256/master-en-business-intelligence-y-big-data-online
- https://www.eoi.es/es/cursos/23401/master-en-big-data-madrid

**Comment by philipto** [comment]
@dcanones Thank you for the clarification. Please rename lib/domains/es/eoi.es to lib/domains/es/eoi.txt, and I merge the request as soon as possible. Thank you!

**Comment by philipto** [comment]
@dcanones You might miss my previous comment. Please reply.

**Comment by philipto** [comment]
@dcanones You might miss my previous comment. Please reply.

**Comment by philipto** [comment]
@dcanones Pull request merged. Thank you! However you did not make changes to the name as I asked you, thus I'll do it for you in about two hours. Please wait at least two hours after this message is sent, before start requesting the licenses at https://jetbrains.com/student.

**Pull request merged**
