### PR TITLE
adding new subdomain for uai.ac.id

### PR DESCRIPTION
**Pull request by tioube**

### CODE REVIEW

**Comment by tioube** [comment]
please help to approve @philipto

**Comment by philipto** [comment]
@tioube First stage of verification passed, official domain for **Universitas Al-Azhar Indonesia** is [student.uai.ac.id](https://student.uai.ac.id) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by tioube** [comment]
@philipto thankyou

**Comment by philipto** [comment]
@tioube Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by tioube** [comment]
thanks a lot @philipto

**Pull request merged**
