### PR TITLE
Add International Language Business Center (ILBC)

### PR DESCRIPTION
**Pull request by shinthantkg**
Added the official domain of International Language Business Center (ILBC).

ILBC is an IGCSE & A-Level school in Myanmar.

### CODE REVIEW

**Comment by philipto** [comment]
@shinthantkg First stage of verification passed, official domain is [ilbc.edu.mm](https://ilbc.edu.mm) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@shinthantkg Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by shinthantkg** [comment]
I believe there isn't a page of the course listings, however, ILBC does offer IGCSE Computer Science, IGCSE ICT and A-Level IT.

As proof, here is the examination timetable for 10th grade that offers the IGCSE CS & ICT courses.
image

And yes, all three courses are two-semesters long, so that equates to a year.

**Comment by shinthantkg** [comment]
image
A-Level Information Technology.

**Comment by philipto** [comment]
@shinthantkg Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
