### PR TITLE
Create niec.txt

### PR DESCRIPTION
**Pull request by akashraj9828**

### CODE REVIEW

**Comment by akashraj9828** [comment]
here is a link to my college official site : http://www.niecdelhi.ac.in/

**Comment by philipto** [comment]
@akashraj9828 Could you please provide us with a link to a page or document which proves that niec.ac.in belongs to your university? The official website says that university email domain is niecdelhi.ac.in. Thank you.

**Comment by akashraj9828** [comment]
sorry niec.ac.in domain does not belong to my university, niecdelhi.ac.in is the official domain of my college
.My college comes under  GURU GOBIND SINGH INDRAPRASTHA UNIVERSITY ( http://www.ipu.ac.in/ )

**Comment by philipto** [comment]
@akashraj9828 Pull request merged. Thank you!

**Pull request merged**
