### PR TITLE
Create yznu.txt

### PR DESCRIPTION
**Pull request by Xuyu1997**
add Yangtze Normal University

url: http://www.yznu.cn/

### CODE REVIEW

**Comment by Xuyu1997** [comment]
r d1 ml td 2 6a5xfjmev
the Personal information has been coded

**Comment by philipto** [comment]
@Xuyu1997 Pull request merged. Thank you!

**Comment by Xuyu1997** [comment]
@philipto it not work, our email is username@stu.yznu.cn ,is that request not right?

**Comment by Xuyu1997** [comment]
the eamail address is username@stu.yznu.cn, does I must create the yznu.txt at `lib/domains/cn/yznu/stu/yznu.txt`?

**Comment by Xuyu1997** [comment]
@philipto I see the rule again , in principle the email is work ,the address is username@stu.yznu.cn, but I go to apply the lince it alert the `Your email address does not belong to any university that we know. Contribute your university to our list.`  please hlep me , thank you

**Comment by Xuyu1997** [comment]
it's worked thank you very much , it must the network latency

**Pull request merged**
