### PR TITLE
Add UGMIT

### PR DESCRIPTION
**Pull request by UGMIT**
The [UGMIT](https://ugmit.org/) is a Govt. Polytechnic (Co-education) functioning since 1979 at district headquarter of Rayagada, under the Administrative control of the Director of Technical Education & Training, Odisha, Cuttack and at Government level under the control of Skill Development & Technical Education and Training Department, Govt. of Odisha, Bhubaneswar.
Diploma courses in Civil, Electrical, Mechanical and Electronics & Tele-Communication Engineering are offered at this institute. All the courses offered in this institute are approved by the All India Council of Technical Education, New Delhi and affiliated to the State Council for Technical Education & Vocational Training, Odisha, Bhubaneswar. The Course duration is of 3 years comprising 6 semesters. Diploma is awarded after passing the final examination by the SCTE & VT, Odisha.

### CODE REVIEW

**Comment by philipto** [comment]
@UGMIT Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@UGMIT You might miss my previous comment. Please react.

**Comment by UGMIT** [comment]
Hello, @philipto

Thank you for your response.

In some school notices and social platforms, it is observable that the school is employing the domain name I have submitted. I am hopeful that the following links can aid in the verification process.

School Twitter: https://www.twitter.com/UGMIT79?s=08
School Facebook: https://www.facebook.com/ugmit1979/
Some school notice links:
https://ugmit.org.in/2022/08/09/quotation-call-notice-for-reapir-and-maintenance-of-mechanical-engg-lab-and-workahop/
https://ugmit.org.in/2023/07/12/quotation-call-notice-of-library/

**Comment by philipto** [comment]
@UGMIT Thank you very much for clarifications and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
