### PR TITLE
Create kcu.txt

### PR DESCRIPTION
**Pull request by sorieil**
Hello. I am a student majoring in computing in Republic of Korea. I'm attending Soongsil Cyber University. Our university also possible domain? Our domain of school "www.kcu.ac". And my email is "sorieil@kcu.ac".

### CODE REVIEW

**Comment by sorieil** [comment]
Hello. I am a student majoring in telecommunications and in Korea. I'm attending Soongsil Cyber University. Our university also possible domain? Our domain of school "www.kcu.ac"

**Comment by sorieil** [comment]
Hello. I am a student majoring in computing in Republic of Korea. I'm attending Soongsil Cyber University. Our university also possible domain? Our domain of school "www.kcu.ac". And my email is "sorieil@kcu.ac".

**Comment by zweizwei** [comment]
@sorieil we only provide access for educational domains of educational institutions with official status and on-site classrooms. On-line academies are not covered by this program unfortunately. If i missed something on your case please let me know.

**Comment by sorieil** [comment]
That's sad news for me.:( Thank you for answer.

**Pull request closed without merging**
