### PR TITLE
Create pwsz-kalisz.txt

### PR DESCRIPTION
**Pull request by ciekals11**

### CODE REVIEW

**Comment by philipto** [comment]
@ciekals11 Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by ciekals11** [comment]
official wesite: http://informatyka.pwsz.kalisz.pl/
I don't know if this proof is enough: https://imgur.com/a/BfMTECb

**Comment by ciekals11** [comment]
another proof image

**Comment by philipto** [comment]
@ciekals11 Thank you for the details! However, it;s all about pwsz.kalisz.pl domain, not pwsz-kalisz.edu.pl. If your school email pattern is username@pwsz.kalisz.pl, please rename lib/domains/pl/edu/pwsz-kalisz.txt to lib/domains/pl/kalisz/pwsz.txt

**Comment by ciekals11** [comment]
But for some reason email is username@pwsz-kalisz.edu.pl.
There is "-" instead of ".", dunno why.

**Comment by ciekals11** [comment]
image

**Comment by philipto** [comment]
@ciekals11 Thank you for the update! Pull request merged.

**Pull request merged**
