### PR TITLE
add flying dove institute, nigeria

### PR DESCRIPTION
**Pull request by freewayz**

### CODE REVIEW

**Comment by philipto** [comment]
@freewayz Could you please:
1) rename the path from `lib/domains/edu/ng/flyingdoveinstitute.txt` to `lib/domains/ng/edu/flyingdoveinstitute.txt` (to reflect flyingdoveinstitute.edu.ng domain in correct order)
2) give us an URL at the official website where any of your IT courses are described? We need to ensure that the institute offers long-term courses (> 1 year).
Thank you!

**Comment by freewayz** [comment]
OK have rename the school name to the right path
[URL](http://flyingdoveinstitute.edu.ng/index.php/colleges-departments) for school course

**Comment by philipto** [comment]
@freewayz Thank you for the renaming. As for the course, the URL you have mentioned is for a list of diplomas available. In order to include an institute to this repository, we have to see that the institute offers long-terms courses. How long the courses are, to get diplomas listed there? Where can we take a look at such information? Thank you!

**Comment by philipto** [comment]
@freewayz Could you please resolve the issue described above? Thank you!

**Comment by freewayz** [comment]
The full detail of the information is not on the site but note that the diploma course last for two years with one year entrepreneurship training, to make it 3 years.

**Comment by philipto** [comment]
@freewayz Thank you for the clarification. Pull request merged.

**Pull request merged**
