### PR TITLE
Create edu.txt

### PR DESCRIPTION
**Pull request by Anana7**

### CODE REVIEW

**Comment by philipto** [comment]
@Anana7 I am sorry, this email domain seems to be not related to the university. 
Please provide us with:
- the school official website URL, 
- an URL of a page or another proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Anana7** [comment]
Here's the official school website: http://www.elektronik.rzeszow.pl/

Here's a URL containing information about email accounts for students (blue button leads to the domain included in my commit):
http://www.elektronik.rzeszow.pl/page?name=materialy-office

It is possible though, that more schools in my city use the edu.erzeszow.pl domain. I'm not sure how to include that in the commit. Should the .txt file contain a list of all schools using that top domain?

**Comment by philipto** [comment]
@Anana7 As you say,

> It is possible though, that more schools in my city use the edu.erzeszow.pl domain. 

This is a problem, actually. According to this repository rules, umbrella domains which covers more than one school are not generally accepted to this repository. Depending on how many schools use the domain, it may be an issue.

If there are not many students in your school who need professional developer tools (and can not use Community Edition, which is free for everybody), I would recommend you to apply with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students) instead of adding your school domain to this repository.

Please comment, if you feel otherwise.

**Comment by Anana7** [comment]
I think I have no other option at this point.
Thank you for your help, anyways.

**Pull request closed without merging**
