### PR TITLE
Add CXXII Liceum Ogólnokształcące Warsaw

### PR DESCRIPTION
**Pull request by pam-param-pam**
School domain:
https://domeyko.edu.pl/ 
Student's school emails follow prefix.surname@domeyko.pl format
https://domeyko.edu.pl/kontakt page has contact email. By writing to this email you can hopefully verify that student's emails follow the format given above.

### CODE REVIEW

**Comment by philipto** [comment]
@pam-param-pam First stage of verification passed, official domain is [domeyko.edu.pl](https://domeyko.edu.pl) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://domeyko.edu.pl/wp-content/uploads/2022/09/specjalisci.pdf

**Comment by philipto** [comment]
@pam-param-pam Pull request merged. Thank you.

**Comment by pam-param-pam** [comment]
Thanks

**Comment by pam-param-pam** [comment]
@philipto Sorry to mention you but i still cannot apply. 
image
Have i done something wrong?

**Pull request merged**
