### PR TITLE
Create saltashcloud.txt

### PR DESCRIPTION
**Pull request by kblanks**
School site is http://saltash.net/ but emails are @saltashcloud.net

### CODE REVIEW

**Comment by zweizwei** [comment]
@kblanks Sorry for the delay - we've been launching rebranding and I hadn't time to check the repo for a while. As for the request - the page seems to be a personal one, please provide some confirmation of the fact that the page belongs to the school. Thank you.

**Comment by kblanks** [comment]
> the page seems to be a personal one

In what way?

**Comment by zweizwei** [comment]
@kblanks any page or official document, confirming that the domain is used for students' and teachers' domains (instructions page or log-in page) should suffice. Thank you!

**Comment by kblanks** [comment]
If you go to the last page of the prospectus at http://saltash.net/wp-content/uploads/2012/12/rev3_saltashnet-community-school_prospectus_web.pdf you will see the head's email listed as head@saltashcloud.net

**Comment by zweizwei** [comment]
@kblanks thanks a lot - that's exactly what i needed. I'll add the domain now.

**Pull request closed without merging**
