### PR TITLE
Added wwgsk.de

### PR DESCRIPTION
**Pull request by Chesterfield**

### CODE REVIEW

**Comment by philipto** [comment]
@Chesterfield What is actual domain which you wish to add? wwgsk.sl.schule.de does not exist. If you need to add wwgsk.de, the file path has to be lib/domains/de/wwgsk.txt. 
```
$ host wwgsk.sl.schule.de
Host wwgsk.sl.schule.de not found: 3(NXDOMAIN)
```

**Comment by Chesterfield** [comment]
i wanted to add wwgsk.de and actually found a folder inside /de called schule ("school" in english) and inside there was another folder called bw which refers to a state in germany. that's why i thought that it would be no problem to add a folder to specify which state the school is located in for future commits

**Comment by philipto** [comment]
@Chesterfield Thank you for sharing the reason you did that because of. Please read instructions on how to add domains to this repository at the bottom of this page: https://github.com/JetBrains/swot
There is naming convention explained, please follow it. Unfortunately, I can not merge a request which does not follow the convention. Thank you for your understanding.

**Comment by Chesterfield** [comment]
i think i got it right this time

**Comment by Chesterfield** [comment]
it should be right now

**Comment by philipto** [comment]
@Chesterfield Thank you! Pull request merged.

**Pull request merged**
