### PR TITLE
ADD Architecture Association School of Architecture

### PR DESCRIPTION
**Pull request by TicoCh1**
school webpage https://www.aaschool.ac.uk/

### CODE REVIEW

**Comment by philipto** [comment]
@TicoCh1 First stage of verification passed, official domain is [aaschool.ac.uk](https://aaschool.ac.uk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@TicoCh1 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by philipto** [comment]
@TicoCh1 You might miss my previous comment. Please react.

**Comment by TicoCh1** [comment]
> 

sorry for late response, as far as I know, this would be a IT related course
https://drl.aaschool.ac.uk/

**Comment by TicoCh1** [comment]
> @TicoCh1 You might miss my previous comment. Please react.

For some reason, the prev link might not work, this should work 
I believe its it related as coding is definitely involved in the course
https://www.aaschool.ac.uk/academicprogrammes/postgraduate/architecture-and-urbanism

**Comment by philipto** [comment]
@TicoCh1  Thank you for the clarifications. Pull request merged.

**Pull request merged**
