### PR TITLE
Create bellsuniversity.txt

### PR DESCRIPTION
**Pull request by toluadesina**

### CODE REVIEW

**Comment by toluadesina** [comment]
I created a new file. Couldn't figure out how to make the change

**Comment by philipto** [comment]
@toluadesina No, you actually did not. I don't see any new file in the request. You can press "Edit" button (which looks like a pencil and a paper note, as far as I see it) in GitHub web interface to edit the file, and see that the filename is also editable. Add ".txt" to the filename and press "Save" button at the bottom of the page. 

You also can close this request and create a new one, with correct filename, if you cannot do the steps desribed above.

**Comment by toluadesina** [comment]
Thank you, Philip for your patience. I figured I didn't log in initially. It's done now

**Comment by philipto** [comment]
@toluadesina Thank you! Pull request merged.

**Pull request merged**
