### PR TITLE
Added Ringwood Training domain text file.

### PR DESCRIPTION
**Pull request by nwhitert**
read more about us: http://ringwood.training

### CODE REVIEW

**Comment by philipto** [comment]
@nwhitert The first verification stage is complete: the official domain for  **Ringwood Training** is [ringwood.training](https://ringwood.training), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://ringwood.training/

**Comment by nwhitert** [comment]
Hello @philipto Thanks for your comments, just to clarify https://ringwood.training/ is our business site which is public. Our emails are handled by rt.vic.edu.au domain, which is what my students will be using to register with to use the Jetbrains suite. This domain is the one I have added to the repository. Is this okay?

**Comment by philipto** [comment]
@nwhitert Yes, absolutely. It's OK. Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by nwhitert** [comment]
@philipto Thanks 😃

**Pull request merged**
