### PR TITLE
Add one more school please

### PR DESCRIPTION
**Pull request by FedorChestnov**

### CODE REVIEW

**Comment by philipto** [comment]
@FedorChestnov Please provide us with:
* the school official full name (no abbreviations, please)
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by FedorChestnov** [comment]
Hello.

- The school official full name: BERKELEY ACADEMY FOR MULTICULTURAL STUDIES

- The school official website URL: https://www.berkeleycr.com/

- The school street address: De la Cruz Roja, 150 Metros Oeste, 350 Metros Sur

Santa Ana, Costa Rica.

- An URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: Unfortunately I can't to give it. I asked for a license for my son, who studies in mentioned school, for to learn Java at home.

- A proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students: I can only to give an address of my son in schools domain ***@***.***).

Best regards:

Отправлено с помощью защищённой почты [Proton Mail](https://proton.me/).

------- Original Message -------
вторник, 4 июля 2023 г., 9:38, Philip Torchinsky ***@***.***> написал:

**Comment by philipto** [comment]
@FedorChestnov  Thank you for the clarifications. I corrected the file content to have the school name there. Pull request merged. Please notice that IntelliJ IDEA Community that does not need any subscription, even free, may be more suitable for your son's needs. He can now try both (IntelliJ IDEA Community and IntelliJ IDEA Ultimate) and choose whatever fits better.

**Comment by FedorChestnov** [comment]
Thank you very nuch.
And thanks for mentioned about Community Edition. Unfortunately we didn't notice it on the site at first time.
-------- Исходное сообщение --------
4 июл. 2023 г., 12:28, Philip Torchinsky написал:

**Pull request merged**
