### PR TITLE
Add Oslo by Steinerskole

### PR DESCRIPTION
**Pull request by afrojezus**
See more info about Oslo by Steinerskole [here](https://oslo-bysteinerskole.no/)

### CODE REVIEW

**Comment by philipto** [comment]
@afrojezus Could you please provide us with a link to a page on the official school website where a long-term (> 1 year) IT-related course is offered to the students? Thank you!

**Comment by philipto** [comment]
@afrojezus I am sorry it looks like you missed my previous question. Could you please take a look at it above, and comment? I will have to close the request without merging if you decide not to answer. Thank you for the understanding.

**Comment by afrojezus** [comment]
[here](https://oslo-bysteinerskole.no/media/), the school doesn't provide directly IT courses but provides web development/design as subject.

**Comment by philipto** [comment]
@afrojezus Thank you for the update. The problem is that I cannot find out from the materials on the website how long the courses take. If they are shorter than a year, the school is not eligible for adding to this repository.

However, you still can apply for  a free license for JetBrains tools using "official document" option at https://jetbrains.com/student, or use free trial version of the tools.

Please let me know how long the courses take.

**Comment by afrojezus** [comment]
the school provides subjects over a span of 4 weeks, so in total, IT-related courses are sadly shorter than a year.

**Comment by philipto** [comment]
@afrojezus I am sorry, in this case I am unable to add the school to this repository. I still suggest the school's students to use free trial version of JetBrains tools, and if 30 days trial is not enough for them to take the course, please feel free to email **sales@jetbrains.com** and ask for an extended trial - it's possible to extend the trial for several more weeks, to allow the students to complete the course. 

I am closing this request without merging. Thank you for the understanding!

**Pull request closed without merging**
