### PR TITLE
Create icsd.txt

### PR DESCRIPTION
**Pull request by theProgrammerJack**
Added Ithaca City School District

### CODE REVIEW

**Comment by theProgrammerJack** [comment]
Website: http://www.ithacacityschools.org/

Proof of courses: https://cdn.flipsnack.com/widget/flipsnackwidget.html?hash=fdp8g3icg&bgcolor=EEEEEE&t=1486921298
Programming courses are in the math section on page 55, and other IT related courses are scattered throughout, but are mainly in the Technology section. I couldn't find this pdf on the district website, but it is linked to on the sidebar of the high school page (http://www.ithacacityschools.org/highschool) under "Ithaca High School Program of Studies".

Proof that this this email domain is used and recognized by the district: http://www.ithacacityschools.org/districtpage.cfm?pageid=509

**Comment by philipto** [comment]
@theProgrammerJack You website is unavailable from Europe due to your F5 balancer configuration. I will check the website as soon as I can get rid of this issue. Thank you for the understanding.

**Comment by theProgrammerJack** [comment]
@philipto No problem. I would be happy to attach some screenshots of the relevant pages if you like. Would that be acceptable for your verification process?

**Comment by philipto** [comment]
@theProgrammerJack Thank you, I resolved the issue. Pull request merged. Please notice that free educational license for JetBrains tools is for high and higher schools students, i.e. those who are over 13 of age. Thank you!

**Comment by theProgrammerJack** [comment]
@philipto Thank you very much!

**Pull request merged**
