### PR TITLE
Create zig

### PR DESCRIPTION
**Pull request by sndour3960**

### CODE REVIEW

**Comment by sndour3960** [comment]
https://uasz.sn/

**Comment by sndour3960** [comment]
http://foad.uasz.gouv.sn/ufrst/course/index.php?categoryid=32

**Comment by sndour3960** [comment]
https://groups.google.com/a/zig.univ.sn/d/msgid/masterinfo_2019.2020/CAKc3ehRgCCi3ugRtBeA-FE_0ivd%3DYcniS0n5tqj4WQt96c7WmQ%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by philipto** [comment]
@sndour3960 First stage of verification passed, official domain is [uasz.sn](https://uasz.sn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://rivieresdusud.uasz.sn/bitstream/handle/123456789/118/70-216-1-PB.pdf?sequence=1&isAllowed=y

**Comment by philipto** [comment]
@sndour3960 There is a problem with the information verification: the official website does not answer. If the problem persists, I'll have to close the request without merging. In the meantime please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

**Comment by philipto** [comment]
@sndour3960 Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
