### PR TITLE
Add Liceo Monti (Chieri, TO, Italy)

### PR DESCRIPTION
**Pull request by BaldEagleX02**

### CODE REVIEW

**Comment by BaldEagleX02** [comment]
[liceomonti.edu.it](liceomonti.edu.it)

**Comment by BaldEagleX02** [comment]
Screenshot 2019-09-06 at 12 03 46

**Comment by BaldEagleX02** [comment]
From https://liceomonti.edu.it/pagina/174/google-suite-per-il-liceo-monti

**Comment by BaldEagleX02** [comment]
@philipto Do you need anything else?

**Comment by BaldEagleX02** [comment]
@philipto ?

**Comment by philipto** [comment]
@BaldEagleX02 I am sorry for a delay with processing your request.
Pull request merged. Thank you!

**Pull request merged**
