### PR TITLE
feat: added support for zambeze university

### PR DESCRIPTION
**Pull request by ReneMuala**

### CODE REVIEW

**Comment by philipto** [comment]
@ReneMuala The first verification stage is complete: the official domain for  **Universidade Zambeze** is [unizambeze.ac.mz](https://unizambeze.ac.mz), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://unizambeze.ac.mz/

**Comment by ReneMuala** [comment]
Greetings @philipto .
You are correct. The domain for Univerisdade Zambeze is unizambeze.ac.mz, but the domain used for email is uzambeze. The email addresses are created in the following format:

name.surname@uzambeze.ac.mz

Apologies for any inconvenience.

**Comment by philipto** [comment]
@ReneMuala The first verification stage is complete: the official domain for  **Universidade Zambeze** is [unizambeze.ac.mz](https://unizambeze.ac.mz), to the best of my knowledge. This is just an informational note. The pull request is still under review. The review may take some more time. I greatly appreciate your patience. Here is the proof of domain ownership: https://unizambeze.ac.mz/

**Comment by philipto** [comment]
@ReneMuala Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
