### PR TITLE
@regi.rovno.ua

### PR DESCRIPTION
**Pull request by forever-Agriculture**
_our university url_: http://www.regi.rovno.ua/en/university/contacts/
screenshot at dec 21 16-29-19

### CODE REVIEW

**Comment by philipto** [comment]
@forever-Agriculture for @regi.rovno.ua the file name shall be lib/domains/ua/rovno/regi.txt
Please rename the file in your request appropriately. Thank you!

**Comment by forever-Agriculture** [comment]
the corrections were made, thanks 4 helping me @philipto

**Comment by philipto** [comment]
@forever-Agriculture Pull request merged. Thank you! I corrected a minor typo for you, there should not be trailing "." in "regi.txt."

**Comment by forever-Agriculture** [comment]
thanks:)

**Pull request merged**
