### PR TITLE
Adding iaen institute

### PR DESCRIPTION
**Pull request by gustavo-belduma**
Add file of educational institute

### CODE REVIEW

**Comment by philipto** [comment]
@gustavo-belduma First stage of verification passed, official domain is [iaen.edu.ec](https://iaen.edu.ec) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@gustavo-belduma Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by gustavo-belduma** [comment]
There is no study program longer than one year.
But if there are subjects in which data processing, statistics, etc. are required.

The link is: https://www.iaen.edu.ec/maestria-en-gestion-publica/

**Comment by philipto** [comment]
@gustavo-belduma  Thank you for the clarifications. Pull request merged.

**Pull request merged**
