### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by gustavodiazs**

### CODE REVIEW

**Comment by philipto** [comment]
@gustavodiazs First stage of verification passed, official domain is [ict.edu.mx](https://ict.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@gustavodiazs Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by gustavodiazs** [comment]
[ict.edu.mx](https://www.ict.edu.mx/)

**Comment by philipto** [comment]
@gustavodiazs I have to close this request without merging, because you requested to add a non-existent domain to this repository: `;; connection timed out; no servers could be reached` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Pull request closed without merging**
