### PR TITLE
Create groupe-esigelec.txt

### PR DESCRIPTION
**Pull request by CptMedo**
student mail for esigelec school (please add us :D)

### CODE REVIEW

**Comment by zweizwei** [comment]
@CptMedo the website doesn't seem to open (http://www.groupe-esigelec.fr/) and the school's main website http://www.esigelec.fr/ - therefore could you please provide some proof of the fact, that the added domain does belong to the school? Thank you!

**Comment by CptMedo** [comment]
Hello! What kind of proof do you need? Groupe-esigelec.fr ils actually the
Google mail adresse for all thé student of the school  and  the teachers
use esigelec .fr
Le 10 juin 2015 15:40, "Elena Ganenkova" <notifications@github.com> a
écrit :

**Comment by CptMedo** [comment]
Please find enclosed a screenshot of my student Dreamspark page wich is only available for students. Please note that the validation specifies "added by admin".
capture d ecran 2015-06-19 a 14 56 18

**Comment by zweizwei** [comment]
@CptMedo thanks for the clarification - i'm adding the domain!

**Pull request merged**
