### PR TITLE
Revert "Create hibb.txt"

### PR DESCRIPTION
**Pull request by heshamahrabi**
Reverts JetBrains/swot#6845

### CODE REVIEW

**Comment by heshamahrabi** [comment]
git

**Comment by philipto** [comment]
@heshamahrabi I am sorry, what is the reason of reverting the record for this domain?

**Comment by heshamahrabi** [comment]
I'm sorry, it was my mistake

**Comment by philipto** [comment]
@heshamahrabi OK, no problem. Thus, I close this request as no longer applicable. Shall you have any concerns or comments, you can reopen the request or send an email to support@jetbrains.com. Thank you.

**Comment by heshamahrabi** [comment]
hello mr . Torchinsky ,

i am sorry  for my  mistake  , i dont know how to solve it , becouse i have
used revert instead of pull commend .


l,g

Am Mi., 25. Sept. 2019 um 11:20 Uhr schrieb Philip Torchinsky <
notifications@github.com>:

**Pull request closed without merging**
