### PR TITLE
Add ESAD to fr domains

### PR DESCRIPTION
**Pull request by lucdems**
Add ESAD to the french domains

ESAD (Ecole supérieur d'art et de design des Pyrénées => Pyrenees College of Art and Design) is a public institution of higher artistic education whose studies lead to national diplomas.

The school's curriculum includes courses in design and web-design in particular, with students developing web and programming projects.

Here is the school's [website](https://esad-pyrenees.fr/) and the [Wikipedia page](https://fr.wikipedia.org/wiki/%C3%89cole_sup%C3%A9rieure_d'art_et_de_design_des_Pyr%C3%A9n%C3%A9es), both in French

### CODE REVIEW

**Comment by philipto** [comment]
@lucdems First stage of verification passed, official domain is [esad-pyrenees.fr](https://esad-pyrenees.fr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@lucdems Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by lucdems** [comment]
Yes, here it is [the page of the "DNA DESIGN - multimedia graphic design mention"](https://esad-pyrenees.fr/enseignement-superieur/cursus/dna-design-mention-design-graphique-multimedia).

It includes web-design and programming courses.

**Comment by philipto** [comment]
@lucdems  Thank you for the clarifications. Pull request merged.

**Pull request merged**
