### PR TITLE
Added codeline.rihal.om as domain

### PR DESCRIPTION
**Pull request by CodelineGitHub**

### CODE REVIEW

**Comment by CodelineGitHub** [comment]
https://codeline.om/
https://www.linkedin.com/company/codeline-om/
https://www.linkedin.com/groups/9501436/

**Comment by nataershova** [comment]
Hello @CodelineGitHub, 

I am sorry, I have to close the request without merging, because this organization is a training center, not a college, nor a university. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot). 

Please apply for an appropriate licensing option (which may also be free) at  https://www.jetbrains.com/community/education/#courses

**Comment by CodelineGitHub** [comment]
Hi @nataershova, We offer free of cost Bootcamps for students who are job seekers and help them placed on jobs. We are non-commercial and are doing this with the support of many software companies. It would have been great if you have given us a chance of clarification on this matter before closing out PR.

**Comment by nataershova** [comment]
Hi @CodelineGitHub, 

Thanks for getting back to us. Usually, we add to the swot domains of the official educational institutions like high schools and universities with courses more than 1 year long. Unfortunately, we can't add schools with short-term courses. 

For such schools and training centers, we have a [special program](https://www.jetbrains.com/community/education/#courses). Within this program, we provide coupons for courses up to 6  months. You may apply for the coupons via this [form](https://www.jetbrains.com/shop/eform/training)

Please let me know if I'm mistaken and if you have 1-year courses. Please send us a link to such a course.

**Comment by ALGHALIAALRASBI** [comment]
def show_menu():
    print("--- Welcome to the Menu-Based Program! ---")
    print("Please select an option:")
    print("1. Print Pattern")
    print("2. Rotate Array")
    print("3. Help")
    print("4. Exit")

def print_pattern(n):
    for i in range(n, 0, -1):
        print('*' * i)

def rotate_array(arr, k):
    return arr[-k:] + arr[:-k]

def display_help():
    print("--- Help ---")
    print("Option 1: Print a pattern with 'n' rows of decreasing asterisks.")
    print("Option 2: Rotate an array of 'n' elements to the right by 'k' steps.")
    print("Option 3: Display this help message.")
    print("Option 4: Exit the program.")

# Main program
while True:
    show_menu()
    choice = int(input("Option: "))
    
    if choice == 1:
        n = int(input("Enter the number of rows for the pattern: "))
        print("Output:")
        print_pattern(n)
    elif choice == 2:
        n = int(input("Enter the number of elements (n): "))
        k = int(input("Enter the number of steps (k): "))
        elements = input("Enter the array elements separated by spaces: ").split()
        arr = [int(num) for num in elements]
        rotated_array = rotate_array(arr, k)
        print("Output:", rotated_array)
    elif choice == 3:
        display_help()
    elif choice == 4:
        print("Exiting the program. Goodbye!")
        break
    else:
        print("Invalid option. Please try again.\n")

**Pull request closed without merging**
