### PR TITLE
Add South Valley National University via upload

### PR DESCRIPTION
**Pull request by mokhtar0v**
Just requested to add my uni to and followed the given steps. Hopefully my request can be accepted

### CODE REVIEW

**Comment by philipto** [comment]
@mokhtar0v Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@mokhtar0v You might miss my previous comment. Please react.

**Comment by philipto** [comment]
@mokhtar0v I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Comment by mokhtar0v** [comment]
I'm so sorry for not answering the requested questions due to my exams for the next two weeks.


________________________________

**Pull request closed without merging**
