### PR TITLE
Create emines.um6p.txt

### PR DESCRIPTION
**Pull request by EppManager**
Université Mohammed VI Polytechnique

### CODE REVIEW

**Comment by philipto** [comment]
@EppManager Please let us know which email domain your university students use. Also, please ensure that you have read the rules of submitting pull request to this repository at the bottom of [this page](https://github.com/JetBrains/swot).

**Comment by EppManager** [comment]
@philipto 
The domain of my school (emines) is : emines.um6p.ma which belongs to mohamed 6 polytechnic university (UM6P)

**Comment by philipto** [comment]
@EppManager For emines.um6p.ma domain the file name in your request has to be lib/domains/ma/um6p/emines.txt. Please rename the file and have the following description in the file:
```
EMINES-Mohammed VI Polytechnic University
Université Mohammed VI Polytechnique (UM6P)
```
Thank you!

**Comment by EppManager** [comment]
@philipto 
I created another pull request (#3266) which contains your remarks.
Thank you!

**Pull request closed without merging**
