### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by surikata11**
please review and confirm. I have added my school to the list and added the requested file as requested.

### CODE REVIEW

**Comment by philipto** [comment]
@surikata11 Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@surikata11 You might miss my previous comment. Please react.

**Comment by surikata11** [comment]
Hello,

I am providing the requested information as follows:

  *   Official website: https://www.b2.eu/
  *   Official address and name: B2 d.o.o., Tržaška cesta 42, 1000 Ljubljana
  *   Official website of my study program, where the goal is to complete my studies: https://www.vspv.si/sl/studijski-programi (I am currently enrolled in: https://www.vspv.si/sl/poslovna-informatika)
  *   Official email (from which I am writing to you): https://e-studij.eu/show.aspx?xid=WBT:X<https://e-studij.eu/show.aspx?xid=WBT:X:Home>

If you need anything else, please feel free to let me know.

________________________________

**Comment by philipto** [comment]
@surikata11  Thank you for the clarifications. Pull request merged. **Please start requesting the licenses in about an hour, to let the changes to propagate through our system.**

**Pull request merged**
