### PR TITLE
Add Brueggli

### PR DESCRIPTION
**Pull request by mnboos**
Dear JetBrains

Regarding your requirements for an application of a new domain I can provide the following information:

- Main Domain: [Brüggli](https://www.brueggli.ch)
- Link to long term IT course/education: [https://berufe.brueggli.ch/informatik/informatikerin-efz/](https://berufe.brueggli.ch/informatik/informatikerin-efz/)
- Each enrolled student/apprentice will get an email address from the @brueggli.ch domain

In case you require additional information, please do not hesitate to contact me.

Thank you and best regards
Martin Boos

### CODE REVIEW

**Comment by philipto** [comment]
@mnboos First stage of verification passed, official domain is [brueggli.ch](https://brueggli.ch) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by mnboos** [comment]
@philipto Thanks for the update, appreciate it.

**Comment by philipto** [comment]
@mnboos Pull request merged. Thank you!

**Comment by mnboos** [comment]
@philipto Wow this was fast! Amazing! Thank you!!

**Pull request merged**
