### PR TITLE
Create rnsit.onmicrosoft domain

### PR DESCRIPTION
**Pull request by sonalsortizy**

### CODE REVIEW

**Comment by philipto** [comment]
@sonalsortizy lib/domains/onmicrost/rnsit: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@sonalsortizy Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@sonalsortizy You might miss my previous comment. Please react.

**Comment by sonalsortizy** [comment]
I have sent an email to jetBrains support with the relevant proof

**Comment by philipto** [comment]
@sonalsortizy I am really sorry, but the proof does not seem relevant. It does not have even a URL which you have used to see what you get at that screenshot. An instruction that you have received from the university would be the best proof. An email from a person responsible for the domain would work too. 

Please notice that an email has to end with a signature of a person who sends it, and a position of the person. It can be something like
```
Alexander Smith
Computer Science Department Head
RNS Institute of Technology
Bangalore, India
```

**Comment by philipto** [comment]
@sonalsortizy I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for your understanding!

**Pull request closed without merging**
