### PR TITLE
Create iit.txt

### PR DESCRIPTION
**Pull request by joaobimbo**
Istituto Italiano di Tecnologia - public research institution

### CODE REVIEW

**Comment by philipto** [comment]
@joaobimbo Could you please give us a link to a page on the official institute website where an IT-related long-term (>1 year) course is offered by the institute?

**Comment by philipto** [comment]
@joaobimbo You might miss my previous comment. Please reply.

**Comment by joaobimbo** [comment]
Hi,
https://iit.it/institute-header/facts-and-figures
On the bottom there's the percentage of phd students (it's a 3-year programme in Italy). There are, among others, programmes in robotics, computer vision and machine learning.

**Comment by philipto** [comment]
@joaobimbo Thank you for the clarification! Pull request merged.

**Pull request merged**
