### PR TITLE
Create wilder.txt

### PR DESCRIPTION
**Pull request by damien-hl**
Add the Wild Code School, a web development school in Europe.

### CODE REVIEW

**Comment by philipto** [comment]
@damien-hl Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@damien-hl You might miss my previous comment. Please react.

**Comment by damien-hl** [comment]
> @damien-hl You might miss my previous comment. Please react.

Hi, sorry for the late, here the informations you asked.

- the university official website URL, if different from the domain you are submitting : 
http://innoveduc.fr/
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university :
(1 year courses)
https://wildcodeschool.fr/prepa-numerique/  
https://wildcodeschool.fr/formation-developpeur-applications-alternance/
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the students : https://www.grandeecolenumerique.fr/wp-content/uploads/2018/12/Laureats_AAP2018.pdf
3275 Formation développeur web Innov'Educ

**Comment by philipto** [comment]
@damien-hl Thank you for the update! I am afraid my question might be not clear to you. The questions is: where can I read that wilder.school email domain belongs to this school? The website of the school is https://wildcodeschool.fr. The page of https://wildcodeschool.fr/contact/ has a lot of emails ending with @wildcodeschool.fr, not @wilder.school. Where can I find a proof that wilder.school is the domain of this school?

**Comment by damien-hl** [comment]
I took a screenshot of the mail that the school (Florian Grandjean, Teachers Coordinator) sent me : 
https://imgur.com/yGXHeVz

I was able to get a GitHub Student Pack with this email.

**Comment by damien-hl** [comment]
I can't find a place on the website where you can read that wilder.school blongs to wildcodeschool.fr.

**Comment by philipto** [comment]
@damien-hl Thank you for the update! Pull request merged. 
By the way, you also can get JetBrains educational subscription for free if you already have GitHub Student Pack, feel free to use GitHub tab at https://www.jetbrains.com/shop/eform/students in order to do that.

**Pull request merged**
