### PR TITLE
pull request of seohyeon middle school

### PR DESCRIPTION
**Pull request by roylee-lab**
lib/domain/kr/goesn/seohyeon middle school.txt

### CODE REVIEW

**Comment by philipto** [comment]
@roylee-lab First stage of verification passed, official domain is [seohyeon-m.goesn.kr](https://seohyeon-m.goesn.kr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by roylee-lab** [comment]
> @roylee-lab First stage of verification passed, official domain is [seohyeon-m.goesn.kr](https://seohyeon-m.goesn.kr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Thanks

**Comment by philipto** [comment]
@roylee-lab Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by roylee-lab** [comment]
> @roylee-lab Thank you for your patience while waiting for a review and processing your request. Pull request merged.

thank you

**Pull request merged**
