### PR TITLE
update domain edu vn for university of transport and communication

### PR DESCRIPTION
**Pull request by hoc-anms**

### CODE REVIEW

**Comment by emranhss** [comment]
Pls add this domain in ur list dipti.com.bd
[dipti.txt](https://github.com/JetBrains/swot/files/4316270/dipti.txt)

**Comment by hoc-anms** [comment]
> Pls add this domain in ur list dipti.com.bd
> [dipti.txt](https://github.com/JetBrains/swot/files/4316270/dipti.txt)

thank so, i will do it

**Comment by philipto** [comment]
@hoc-anms @emranhss Pull request merged.
As for dipti.com.bd, it requires a separate pull request because it's a completely different university in another country.
Thank you.

**Comment by hoc-anms** [comment]
@philipto @emranhss thank you.

**Pull request merged**
