### PR TITLE
Added High School

### PR DESCRIPTION
**Pull request by berkaybeyaz1**
I have been added my school

### CODE REVIEW

**Comment by zweizwei** [comment]
@berkaybeyaz1 unfortunately http://www.turgutalpanatolian.k12.tr/ doesn't open - could you please somehow confirm that the website is alive? thank you!

**Comment by berkaybeyaz1** [comment]
http://ital.meb.k12.tr/ thats it. We are Ministry of Education is disallow use another For example http://{school name }.meb,k12.tr thank you..

**Comment by zweizwei** [comment]
@berkaybeyaz1 but you have added http://www.turgutalpanatolian.k12.tr/ - so i need the confirmation of this domain. Thank you!

**Comment by philipto** [comment]
@berkaybeyaz1  According http://whois.marcaria.com/domain-whois/middle-east/turkey-domain-tr?q=turgutalpanatolian.k12.tr the domain **turgutalpanatolian.k12.tr is not registered**. Could you please prove that Turgutalp Anatolian High School owns turgutalpanatolian.k12.tr e-mail domain?

**Comment by zweizwei** [comment]
I'll close the request due to being obsolete, @berkaybeyaz1 please reply to reopen

**Pull request closed without merging**
