### PR TITLE
Create a new file adcet.txt

### PR DESCRIPTION
**Pull request by vivek8097**
Please add this file into your repository.My College website is www.adcet.in

### CODE REVIEW

**Comment by philipto** [comment]
@vivek8097 Thank you. This request is correct, but I still need to know which email domain you actually would like to add. If adcet.edu, could you please give me a link to a page or a document which confirms that your university uses adcet.edu domain for student emails, not adcet.in. Thank you!

**Comment by vivek8097** [comment]
As you suggest  me i was added adcet.txt in lib/domain/in and college email id is end with adcet.in.My<http://adcet.in.My> college email id is viveksingh@adcet.in<mailto:viveksingh@adcet.in>.

On 19-Apr-2017 2:02 am, "Philip Torchinsky" <notifications@github.com<mailto:notifications@github.com>> wrote:

@vivek8097<https://github.com/vivek8097> Thank you. This request is correct, but I still need to know which email domain you actually would like to add. If adcet.edu<http://adcet.edu>, could you please give me a link to a page or a document which confirms that your university uses adcet.edu<http://adcet.edu> domain for student emails, not adcet.in<http://adcet.in>. Thank you!

**Comment by vivek8097** [comment]
As you suggest me i was added my adcet.txt inside lib/domains/in.And college email id ends with adcet.in and my college email id is viveksingh@adcet.in.

Sent from my HTC

----- Reply message -----
From: "vivek pratap singh" <singhvivekp@live.com>
To: "JetBrains/swot" <reply@reply.github.com>
Subject: [JetBrains/swot] Create a new file adcet.txt (#2958)
Date: Wed, Apr 19, 2017 11:53 AM

As you suggest  me i was added adcet.txt in lib/domain/in and college email id is end with adcet.in.My<http://adcet.in.My> college email id is viveksingh@adcet.in<mailto:viveksingh@adcet.in>.

On 19-Apr-2017 2:02 am, "Philip Torchinsky" <notifications@github.com<mailto:notifications@github.com>> wrote:

@vivek8097<https://github.com/vivek8097> Thank you. This request is correct, but I still need to know which email domain you actually would like to add. If adcet.edu<http://adcet.edu>, could you please give me a link to a page or a document which confirms that your university uses adcet.edu<http://adcet.edu> domain for student emails, not adcet.in<http://adcet.in>. Thank you!

**Comment by vivek8097** [comment]
As you suggest me i was added my adcet.txt inside lib/domains/in.And college email id ends with adcet.in and my college email id is viveksingh@adcet.in.

----- Reply message -----
From: "vivek pratap singh" <singhvivekp@live.com>
To: "JetBrains/swot" <reply@reply.github.com>
Subject: [JetBrains/swot] Create a new file adcet.txt (#2958)
Date: Wed, Apr 19, 2017 11:53 AM

As you suggest  me i was added adcet.txt in lib/domain/in and college email id is end with adcet.in.My<http://adcet.in.My> college email id is viveksingh@adcet.in<mailto:viveksingh@adcet.in>.

On 19-Apr-2017 2:02 am, "Philip Torchinsky" <notifications@github.com<mailto:notifications@github.com>> wrote:

@vivek8097<https://github.com/vivek8097> Thank you. This request is correct, but I still need to know which email domain you actually would like to add. If adcet.edu<http://adcet.edu>, could you please give me a link to a page or a document which confirms that your university uses adcet.edu<http://adcet.edu> domain for student emails, not adcet.in<http://adcet.in>. Thank you!

**Comment by philipto** [comment]
@vivek8097 No, you did not. This request is to add a file with the path lib/domains/edu/adcet.txt, not lib/domains/in/adcet.txt. Please take a look at "Files changed" tab in your pull request at GitHub website.
Please rename.

**Comment by vivek8097** [comment]
Sir my college email id is viveksingh@adcet.in which is ends with adcet.in so i need to add adcet.txt inside lib/domain/in for registration of my email id.So please delete my file from/lib/domain/edu and approve my pull request for lib/domain/in.

**Comment by philipto** [comment]
@vivek8097 I am closing this request, because correct one was merged successfully. Thank you.

**Pull request closed without merging**
