### PR TITLE
Added IES s'Arenal and IES Llucmajor

### PR DESCRIPTION
**Pull request by xRoier**
https://iesllucmajor.org/
http://iessarenal.net/

### CODE REVIEW

**Comment by philipto** [comment]
@xRoier lib/domains/org/iesllucmajor: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by xRoier** [comment]
I forgot the .txt, my fault.

**Comment by philipto** [comment]
@xRoier No problem :) Pull request merged. Thank you!

**Comment by philipto** [comment]
It should take about an hour before you can start requesting licenses. It is due to a system needing to propagate the changes.

**Pull request merged**
