### PR TITLE
Adding Accra Business School

### PR DESCRIPTION
**Pull request by yassine-hamadou**
I added the Accra Business School domain name to JetBrain swot in order for students and lecturers with their school email to be granted free licenses for JetBrains tools.

### CODE REVIEW

**Comment by philipto** [comment]
@yassine-hamadou lib/domains/gh/edu/abs: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by yassine-hamadou** [comment]
Thank you for your reply @philipto, I will review it and send another PR with the right format.

**Comment by philipto** [comment]
@yassine-hamadou lib/domains/gh/edu/abs: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@yassine-hamadou Thank you for your patience while waiting for a review and processing your request. Pull request corrected and merged.

**Pull request merged**
