### PR TITLE
Add CatólicaSC (Brasil)

### PR DESCRIPTION
**Pull request by VitorPetri**
Website URL:
https://www.catolicasc.org.br/

Software engineering course (4 years)
https://www.catolicasc.org.br/cursos/graduacao/engenharia-de-software/?unidade=joinville

Student page with the domain
https://prnt.sc/17icred

### CODE REVIEW

**Comment by Asmaagamall** [comment]
[
[file.zip](https://github.com/JetBrains/swot/files/6736419/file.zip)
](url)

**Comment by DakshRocks21** [comment]
[ssts.txt](https://github.com/JetBrains/swot/files/6738326/ssts.txt)
https://www.sst.edu.sg/

**Comment by DakshRocks21** [comment]
> [ssts.txt](https://github.com/JetBrains/swot/files/6738326/ssts.txt)
> https://www.sst.edu.sg/

pls add this

**Comment by Douglas-Strey** [comment]
Waiting for this domain....

**Comment by DakshRocks21** [comment]
The thing is that I don't know how to add

**Comment by philipto** [comment]
@VitorPetri I am sorry, I cannot add this domain. The reasons are:
1) You seem to graduate from the university already. If you did not, please apply with official document at https://www.jetbrains.com/shop/eform/students (OFFICIAL DOCUMENT tab).
2) The official university website does not mention this domain at all.
3) I am not sure if the university withdraw the access to the email domain when the students graduate. If it does not, we'd refrain from adding the domain to this repository.

Thank you for your understanding!

**Comment by philipto** [comment]
@Asmaagamall @DakshRocks21 @Douglas-Strey Please send an email to community-support@jetbrains.com about the domain that you wish to add. You can also familiarize with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new separate request with correct information. Thank you for the understanding!

**Pull request closed without merging**
