### PR TITLE
create pune university

### PR DESCRIPTION
**Pull request by vishal-biradar**
I am adding pune university

### CODE REVIEW

**Comment by philipto** [comment]
@vishal-biradar Could you please rename the file in your request? This university has a domain of mmit.edu.in, as far as I can see, and if you wish to add this domain, the file which represents it has to have a name lib/domains/in/edu/mmit.txt. Thank you.

**Comment by vishal-biradar** [comment]
Hi Philip Torchinsky,


*Because of this error in github edu tag i am unable to rename it.*

Sorry, we had to truncate this directory to 1,000 files. 915 entries were
omitted from the list.


  but i have created lib/domains/in/edu/mmit.txt.

Thanks for your reply.
And please delete lib/domains/edu/pune university tag


Thanks.

**Comment by philipto** [comment]
@vishal-biradar Regrettably, I did not find your new request. Please make sure that you have made it in this repository. As per your request, I close this issue without merging. Thank you.

**Comment by vishal-biradar** [comment]
Hi,
Yes I forgot to request for pull.
Again I have created and requested for pull.

Thnaks

On Mon, Jun 12, 2017 at 9:48 PM, Philip Torchinsky <notifications@github.com

**Pull request closed without merging**
