### PR TITLE
University add: UniNorte

### PR DESCRIPTION
**Pull request by BearusuMyo**
Another domain owned by UniNorte
Centro Universitário do Norte - UniNorte is a part from Ser Educational Group

### CODE REVIEW

**Comment by philipto** [comment]
@BearusuMyo Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

You can provide us with any of the following as the proof:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@BearusuMyo You might miss my previous comment. Please react.

**Comment by BearusuMyo** [comment]
[Official website](https://www.uninorte.com.br)
Rua 10 de Julho, 873 – Centro, Manaus, Amazonas State, Brazil
[Computer engineering Bachelor course overview](https://www.uninorte.com.br/graduacao/cursos/escola-de-exatas/engenharia-da-computacao#sobre-o-curso)

The following lines are the WHOIS transcription
`% Copyright (c) Nic.br
%  The use of the data below is only permitted as described in
%  full by the terms of use at https://registro.br/termo/en.html ,
%  being prohibited its distribution, commercialization or
%  reproduction, in particular, to use it for advertising or
%  any similar purpose.
%  2021-11-22T07:09:30-03:00 - IP: ***.***.***.188

domain:      sempreuninorte.com.br
owner:       SER EDUCACIONAL S/A
owner-c:     ESJ120
tech-c:      ACV75
nserver:     e.sec.dns.br
nsstat:      20211120 AA
nslastaa:    20211120
nserver:     f.sec.dns.br
nsstat:      20211120 AA
nslastaa:    20211120
dsrecord:    59050 ECDSA-SHA-256 65AAAEB325BA9DB33E3AFC542E0C5407034498E4BD7CF8B16B72B572B148A26A
dsstatus:    20211120 DSOK
dslastok:    20211120
saci:        yes
created:     20200120 #20569889
changed:     20210123
expires:     20230120
status:      published

nic-hdl-br:  ESJ120
person:      ESBJ-Ensino Superior Bureau Jur?dico
created:     20030530
changed:     20191113

nic-hdl-br:  ACV75
person:      André C. Vasconcelos
created:     20010412
changed:     20180530

% Security and mail abuse issues should also be addressed to
% cert.br, http://www.cert.br/ , respectivelly to 
% and 
%
% whois.registro.br accepts only direct match queries. Types
% of queries are: domain (.br), registrant (tax ID), ticket,
% provider, CIDR block, IP and ASN.

Information Updated: 2021-11-22 10:09:30`

**Comment by philipto** [comment]
@BearusuMyo Thank you for the clarification. Pull request merged.

**Pull request merged**
