### PR TITLE
Added Jamia Banuri to Jetbranins

### PR DESCRIPTION
**Pull request by zianomi**
Please add  a well known education organization to Jetbrains

### CODE REVIEW

**Comment by philipto** [comment]
@zianomi First stage of verification passed, official domain is [banuri.edu.pk](https://banuri.edu.pk) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@zianomi You might miss my previous comment. Please react.

**Comment by zianomi** [comment]
Please check:
https://www.banuri.edu.pk/en/page/banuri-education-it-courses

**Comment by philipto** [comment]
@zianomi  Thank you for the clarifications. Regrettably, I have to close the request without merging, because the courses do not meet the requirements described in the repository rules. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot).

Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Pull request closed without merging**
