### PR TITLE
Create holbertonschool.txt

### PR DESCRIPTION
**Pull request by ZAKosma**
Adding Holberton School (includes all locations across various countries)

https://www.holbertonschool.com/

### CODE REVIEW

**Comment by philipto** [comment]
@ZAKosma First stage of verification passed, official domain is [holbertonschool.com](https://holbertonschool.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@ZAKosma Regrettably, I have to close the request without merging, because this organization is a training center, not a college, nor a university. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot).

Please apply for an appropriate licensing option (which may also be free) at https://www.jetbrains.com/community/education/#courses.

Thank you for your understanding!

**Comment by ZAKosma** [comment]
Hi @philipto,

Thank you for your response.

It is not accurate to label us as a training center, we are a vocational school, or vocational university, and from reading the rules in the repository I believe we meet the provided criteria. (Please see the next paragraph).

We are an educational institution based out of Tulsa Oklahoma in the United States. Students enroll in our 20-month (2 year) program to study and learn software engineering. We are one of a franchise of physical schools and we provide dedicated email addresses to our students.

Our alternate domain (holbertonstudents.com) is already included in this Jetbrains/swot repo and was changed when we split our staff and student domains. Previously I registered with my staff domain (holbertonschool.com) and was able to successfully sign up. I believe when the domain split happened, there was a request to rename the holbertonschool entry from this repo to holbertonstudents.

Please let me know if you can reopen this request or if I should contact Jetbrains sales.

Kind regards,
Zachary

**Comment by philipto** [comment]
Dear Zachary @ZAKosma,

**Comment by philipto** [comment]
Dear Zachary @ZAKosma,

I reviewed the request again, and while the school's website does not mention explicitly a two-year program, we checked it with you in an email correspondence. As a result, I reopened and merged the pull request. 

Please start requesting your free licenses in an hour to allow the update to propagate through the systems. Thank you.

**Pull request merged**
