### PR TITLE
Add Weingmok Wittaya School 

### PR DESCRIPTION
**Pull request by worakarn27**

### CODE REVIEW

**Comment by G1nd3kk** [comment]
[gimnazjum-krobia.txt](https://github.com/JetBrains/swot/files/9000571/gimnazjum-krobia.txt)

**Comment by philipto** [comment]
@worakarn27 First stage of verification passed, official domain is [wmws.ac.th](https://wmws.ac.th) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by worakarn27** [comment]
> @worakarn27 First stage of verification passed, official domain is [wmws.ac.th](https://wmws.ac.th) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.
Thank you for verification this is [certificate of my school](https://drive.google.com/file/d/1H0wWyHe93e7dZqO32JBCFT9FqG-AKWMl/view?usp=sharing)  and website http://www.wmws.ac.th

Thank

**Comment by KiraBobyleva** [comment]
@worakarn27 Pull request merged, thanks!

**Pull request merged**
