### PR TITLE
Added Kenya Institute of Supplies Management

### PR DESCRIPTION
**Pull request by kinare**
https://kism.or.ke
https://kiseb.or.ke

### CODE REVIEW

**Comment by vungocdiep10** [comment]
[st.txt](https://github.com/JetBrains/swot/files/6136490/st.txt)

**Comment by philipto** [comment]
@kinare Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by kinare** [comment]
We have some of the Business course taken having units with IT. 
https://kiseb.or.ke

**Comment by philipto** [comment]
@kinare Thank you for the clarification. Pull request merged.

**Pull request merged**
