### PR TITLE
Add Dhanbad Public School To JetBrains Schools List

### PR DESCRIPTION
**Pull request by Ujjawal-Kumar-Chouhan**

### CODE REVIEW

**Comment by Ujjawal-Kumar-Chouhan** [comment]
Changed details

**Comment by philipto** [comment]
@Ujjawal-Kumar-Chouhan Please provide us with:
- the school official website URL
- the school full name
- the school street address, including the city and the country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Thank you!

**Comment by philipto** [comment]
@Ujjawal-Kumar-Chouhan You might miss my previous comment. Please react.

**Comment by Ujjawal-Kumar-Chouhan** [comment]
Where to provide all this details the file was autogenerated

**Comment by philipto** [comment]
@Ujjawal-Kumar-Chouhan Please just add your comment at https://github.com/JetBrains/swot/pull/11180. Open this page in your browser and add the comment. Thank you!

**Pull request closed without merging**
