### PR TITLE
Mapua University

### PR DESCRIPTION
**Pull request by ddchristiantan**
Please add Mapua University

### CODE REVIEW

**Comment by philipto** [comment]
@ddchristiantan First stage of verification passed, official domain is [mapua.edu.ph](https://mapua.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by ddchristiantan** [comment]
> @ddchristiantan First stage of verification passed, official domain is [mapua.edu.ph](https://mapua.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

Hi @philipto , please also consider the domain mymapua.edu.ph as this is used by our students. Thank you in advance!

**Comment by philipto** [comment]
@ddchristiantan Thank you for your patience while waiting for a review and processing your request. Pull request merged.

As for mymapua.edu.ph, please make a separate pull request. Please also provide us with a proof, which shows that the school recognizes the domain mymapua.edu.ph as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by ddchristiantan** [comment]
> @ddchristiantan Thank you for your patience while waiting for a review and processing your request. Pull request merged.
> 
> As for mymapua.edu.ph, please make a separate pull request. Please also provide us with a proof, which shows that the school recognizes the domain mymapua.edu.ph as an official email domain for the students. You can provide us with any of the following:
> 
> * A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
> * An URL of a page at the official school website that says that students use this email domain
> * A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
> * A WHOIS data that link the email domain to the school somehow
> * A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
> * Anything else that can prove this fact in similar way, i.e. can be verified independently.

This is noted. Thank you, @philipto!

**Pull request merged**
