### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by benwang124**

### CODE REVIEW

**Comment by philipto** [comment]
@benwang124 Please provide us with:
- the school official website URL
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@benwang124 You might miss my previous comment. Please react.

**Comment by benwang124** [comment]
@philipto 

- This is the URL to [NYU Langone](https://nyulangone.org/) and our [medical school ](https://med.nyu.edu/).
- Please see the curriculum for our masters in biomedical informatics for documentation of long-term IT-related education: https://med.nyu.edu/research/vilcek-institute-graduate-biomedical-sciences/ms-biomedical-informatics/academics
- Can you use the email addresses for education team for the Biomedical Informatics Masters Program as proof of the domain?: https://med.nyu.edu/research/vilcek-institute-graduate-biomedical-sciences/ms-biomedical-informatics.

**Comment by philipto** [comment]
@benwang124 Thank you for the clarification. Pull request merged.

**Pull request merged**
