### PR TITLE
add kcu.txt

### PR DESCRIPTION
**Pull request by bluehyun**
add kcu.txt

### CODE REVIEW

**Comment by philipto** [comment]
@bluehyun I am sorry for a delay with processing your request. Do I understand right that KCU gives an access to emails in @kcu.ac domain to the students, not to alumni or other people somehow related to the university? I am asking the question because it can be harder to control who actually uses an email in an online university, if the students do not come in person to the university.

**Comment by philipto** [comment]
@bluehyun Do you have online courses only at KCU?

**Comment by bluehyun** [comment]
@philipto yes.
kcu (Korea Soongsil Cyber University) uses the @kcu.ac email address to students

**Comment by philipto** [comment]
@bluehyun I am sorry to learn that this university is purely online university. We do not add online universities in this repository. According to our rules we only provide the access to our student pack to students / teachers at accredited educational institutions with on-site classrooms https://www.jetbrains.com/student/license_educational.html - we do not accept on-line students to the program. If you have additional questions please let us know.

Thank you.

**Pull request closed without merging**
