### PR TITLE
CPNF

### PR DESCRIPTION
**Pull request by FantomeKill**
add school cpnf

### CODE REVIEW

**Comment by philipto** [comment]
@FantomeKill Please provide us with a proof, which shows that the school recognizes the domain cpnf.org that you are submitting as an official email domain for the students.

**Comment by FantomeKill** [comment]
Where I send you the proof

**Comment by philipto** [comment]
@FantomeKill Please upload it to GitHub via GitHub web interface as a comment to #9774. Alternatively, you can send a confidential information which cannot be uploaded to a public page to community-support@jetbrains.com with a subject: "ATTN: Philip Torchinsky". Thank you.

**Comment by FantomeKill** [comment]
Hi, just to clarify, I'm not actually the owner of this domain. I'm just a student there that would want to benefit the education features. If you ever need a contact there(possibly to the owner), you can send an email at support@cpnf.org.

**Comment by philipto** [comment]
@FantomeKill I am sorry, the official website of the  Collège Nouvelles Frontières is different from cpnf.org. If you wish to add this domain to this repository, please find document or a link to a page which says that the college recognizes this domain as an official one. 

If you don't have any instruction from the college which says that students can (or have to) use this domain, I will close this request without merging. You will be able to get a free license anyway if applying with official document ("OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students).

**Comment by philipto** [comment]
@FantomeKill I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
