### PR TITLE
Create mtp.by

### PR DESCRIPTION
**Pull request by LitvinenkoMan**

### CODE REVIEW

**Comment by philipto** [comment]
@LitvinenkoMan Please provide us with:
- the school official website URL
- the school street address, including city and country
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@LitvinenkoMan You might miss my previous comment. Please react.

**Comment by LitvinenkoMan** [comment]
1. http://www.mcb.by
2. Uruchskaya 21v, Minsk, Belarus.
3. http://www.mcb.by/specialnosti/it
4. Our College uses Google services, @mtp.by is officially registered with our college, and ordinary students cannot create such mail, only the administration of our college can create such a mail, and its name depends on the number of the college admission agreement, for example, I have a number of the contract upon receipt of 1183782, respectively, my mail will be 1183782@mtp.by a photo of my contract will be attached below.

image
 
In the window with authorization @gmail.com mail you will need to enter 1183782@mtp.by after you find yourself on the official MCB authorization page (this is specifically my account mail) below are screenshots for confirmation. 
image
image

If I have not mention something, please let me know.

**Comment by LitvinenkoMan** [comment]
> @LitvinenkoMan You might miss my previous comment. Please react.

Check the comment i wrote above this one.

**Comment by philipto** [comment]
@LitvinenkoMan Pull request merged. Thank you!

**Pull request merged**
