### PR TITLE
Create dlnii

### PR DESCRIPTION
**Pull request by sansroman**
the university official website URL: http://www.neusoft.edu.cn/
IT URL：http://news.neusoft.edu.cn/
pdf  URL  ：http://roccat.top/blog/wp-content/uploads/2016/07/QQ截图20160708235756.png

### CODE REVIEW

**Comment by philipto** [comment]
@sansroman Could you please provide a link to a page on the official website where I can see that students use dlnii.edu.cn domain? http://mail.nou.com.cn/extmail/cgi/index.cgi says that students use another domain, nou.com.cn. Thank you!

**Comment by sansroman** [comment]
The students in our school are generally use nou.com.cn domain，Only teachers and students can use the application neusoft.edu.cn domain, This is the link in our school [http://mail.neusoft.edu.cn/extmail/cgi/index.cgi](url)

**Comment by philipto** [comment]
@sansroman Excuse me, I do not understand you. You submit the file `lib/domains/cn/edu/dlnii` in this request, and at the same you say that the students in your university use nou.com.cn and neusoft.edu.cn. A file name lib/domains/cn/edu/dlnii suggests that you wish to add a domain dlnii.edu.cn. Why do you wish to do it, if students use other domains?

**Comment by sansroman** [comment]
I'm sorry I wasted your time,My English is not very good. I just started misunderstood what you mean，now ,I have modified this file, last, thank you for your help

**Comment by philipto** [comment]
@sansroman Please rename lib/domains/cn/edu/neusoft to lib/domains/cn/edu/neusoft.txt. The extension .txt is mandatory. After you do it, I accept this request, and you will be able to get free license using any email address at @neusoft.edu.cn domain. Is it OK for you?

**Comment by sansroman** [comment]
it's ok

**Comment by philipto** [comment]
@sansroman Pull request merged. Thank you!

**Pull request merged**
