### PR TITLE
Create glion.txt

### PR DESCRIPTION
**Pull request by jasonheesanglee**

### CODE REVIEW

**Comment by philipto** [comment]
@jasonheesanglee First stage of verification passed, official domain is [glion.edu](https://glion.edu) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.glion.edu/magazine/tips-for-recruitment-after-covid-19/

**Comment by philipto** [comment]
@jasonheesanglee Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by jasonheesanglee** [comment]
Hi, Thanks for your help here.
Below are the relevant courses to IT, Statistics and Data Analytics.
As the school itself is a hotel school, Glion has some courses interacting with the field of IT.

Please kindly review and revert back.
Thanks

-------------------------------------------------------------------------------------------------------------------------

For BBA International Hospitality Business, Glion offers "Corporate Finance" and "Revenue Management" courses that deals with statics. (semester 6 & 7 = 1 year).

For BBA Luxury Business, Glion offers "Data Analysis for Decision Makers", "Corporate Finance" courses in semester 4 (6 months) and "International Markets and Finance" course in semester 6 (6 months).

Both Bachelor's stream has "IT Business Tools" course in semester 3.


For MSc International Hospitality Business (1.5 years), Glion offers "Digital Transformation and Data Analytics" course in semester 1 (6 months) and "Hospitality Corporate Finance" in semester 2 (6 months).

For MSc Hospitality, Entrepreneurship and Innovation, Glion offers "Marketing, Branding and Big Data in Hospitality", "Revenue Management and Digital Distribution Strategy", "Digital Technologies and Big Data Management" courses in semester 2 (6 months).

For MSc Luxury Management and Guest Experiences, Glion offers "Digital Transformation and Data Analytics" course in semester 1 (6 months), "Blockchain in the Luxury and Hospitality Industries" and "Corporate Finance and Value Creation" courses in semester 2 (6 months).

For MSc Real Estate, Finance and Hotel Development, Glion offers "Hospitality Financial Analysis and Performance" course in semester 1 (6 months).

For Executive Masters Luxury Management and Guest Experience, Glion offers "Digital Transformation and Data Analytics", "Blockchain and Luxury Digital Products and Experiences", "Corporate Finance and Value Creation" for 6 months

**Comment by philipto** [comment]
@jasonheesanglee  Thank you for the clarifications. Pull request merged.

**Pull request merged**
