### PR TITLE
feat: adicionar fundação Liberato

### PR DESCRIPTION
**Pull request by gabrielmusskopf**

### CODE REVIEW

**Comment by philipto** [comment]
@gabrielmusskopf Please provide us with a proof, which shows that the school recognizes the domain `liberato.com` that you are submitting as an official email domain for the students.

You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@gabrielmusskopf You might miss my previous comment. Please react.

**Comment by gabrielmusskopf** [comment]
Hello, @philipto, here's a site that proof the recognition from the domain.

https://sites.google.com/liberato.com.br/sae/pagina-inicial

Below the header: "(Para alunos: número da matrícula+@liberato.com.br  para servidores: nome+@liberato.com.br)"

Is this a valid proof?

**Comment by philipto** [comment]
@gabrielmusskopf Your request is regarding a domain `liberato.com`: lib/domains/com/liberato.txt
Shall I rename your file to lib/domains/br/com/liberato.txt to add a domain liberato.com.br?

**Comment by gabrielmusskopf** [comment]
@philipto Yes, please. I wrote the wrong domain, my mistake.

**Comment by philipto** [comment]
@gabrielmusskopf liberato.com.be is already in our trusted list. Thus, I close this request as a duplicate. You can request your free license at https://www.jetbrains.com/shop/eform/students at any time. If you see any error message while requesting your license, please send a screenshot of the error to community-support@jetbrains.com. 

Please ensure that you do not have leading or trailing spaces when you fill in your email address in the form. Thank you!

**Pull request closed without merging**
