### PR TITLE
Adding a french academy

### PR DESCRIPTION
**Pull request by Waryle**

### CODE REVIEW

**Comment by philipto** [comment]
@Waryle Could you please tell a bit more about the academy? Who are the students? How many of them are enrolled? What are IT-related courses that the academy offers? Which degrees the students are to get?

**Comment by Waryle** [comment]
Hello !

So netocentre.fr is the "Environnement Numérique de Travail" (which can be roughly translated to "Digital work environment") of the "Centre" region in France.

This is a platform which host plenty of services for the different high-schools and CFAs (Centre de Formation d'Apprentis = Apprentices Training Center) in our academy (known as "Académie d'Orléans-Tours", because it mainly regroups both Orléans and Tours and their areas).

It is different from univ-orleans.fr and ac-orleans-tours.fr you already have registered, and do not aim to the same type of schools/students.

The students which have a mail address *@netocentre.fr are studying in highschools or CFA, which means they either study for the BAC (the diploma you study for generally when you're between 15 and 18 years old), or for a BTS/DUT/Licence... (BAC +2 years, +3...).

I don't know exactly how many students use this platform, I would say more than a thousand.

There are several diplomas concerning programming/IT, in my case I am actually studying for a BTS SIO (Two-year Technical Degree, IT services to organizations). We study Algorithms, SQL/Databases, HTML/CSS, PHP, Java, C#.

If you need more information, I would be happy to answer you

**Comment by philipto** [comment]
@Waryle Thank you for the clarification. Your institution is not typical for this repository, thus it may take a bit more time to decide on the case. Thank you for your patience!

**Comment by philipto** [comment]
@Waryle Pull request merged. Thank you!

**Pull request merged**
