### PR TITLE
Add ucpparana domain

### PR DESCRIPTION
**Pull request by Eduardo-Silva-Rodrigues**
Add ucpparana domain

### CODE REVIEW

**Comment by Eduardo-Silva-Rodrigues** [comment]
Add ucpparana

**Comment by philipto** [comment]
@Eduardo-Silva-Rodrigues First stage of verification passed, official domain for **Univale - Faculdade Integradas do Vale do Ivaí** is [ucpparana.edu.br](https://ucpparana.edu.br) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by Eduardo-Silva-Rodrigues** [comment]
@philipto Ok, thank you very much for your attention

**Comment by philipto** [comment]
@Eduardo-Silva-Rodrigues Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
