### PR TITLE
Adding the Computer Science academy at ITESZ

### PR DESCRIPTION
**Pull request by web2bruno**
Adding the Computer Science academy at Instituto Tecnologico de Estudios Superiores de Zamora (accitesz.com)

### CODE REVIEW

**Comment by web2bruno** [comment]
Hello, sorry for the late reply, I just saw the message, I currently have this document (issued back in 2016) in which the Principal at the university acknowledges me and allows me to speak on behalf of the Computer Sciences Academy at the University. I used this to register the domain accitesz.com for Google Apps for Education back then. Still if you need something more recent and/or specifying the use of the domain let me know and I'll ask for them, I have no problem doing so :) Thanks for the reply.
[Accitesz - ITESZ.pdf](https://github.com/JetBrains/swot/files/4095392/Accitesz.-.ITESZ.pdf)

**Comment by web2bruno** [comment]
By the way, it's worth mentioning that the official address for the university is teczamora.mx but the CS academy has their own domain ( accitesz.com ) in order to take advantage of the Google Apps for Education and since the rest of the university doesn't use it we had to separate our emails to a separate domain.

**Comment by philipto** [comment]
@web2bruno Thank you for the clarification. Pull request merged.

**Comment by web2bruno** [comment]
Thank you very much, I tried creating an account and it is working now :D

**Pull request merged**
