### PR TITLE
Added Nueva Vizcaya State University

### PR DESCRIPTION
**Pull request by daeyeonnn**
lib/domains/ph/edu/nvsu.txt

### CODE REVIEW

**Comment by daeyeonnn** [comment]
Here are some proofs that Nueva Vizcaya State University is a recognized institution here in the Philippines:
1. The University's Official Website: https://www.nvsu.edu.ph/
2. The University's Offered Programs (Including Information Technology and Computer Science): https://www.nvsu.edu.ph/programs (Note: It is under College of Arts and Sciences)
3. The University uses Microsoft as its email domain provider through Outlook and also I am enrolled as a student in the said institution. [(Here is the log in link where students here access our own institution account.) ](cloud.nvsu.edu.ph)

**Comment by daeyeonnn** [comment]
Here are some proofs that Nueva Vizcaya State University is a recognized institution here in the Philippines:
1. The University's Official Website: https://www.nvsu.edu.ph/
2. The University's Offered Programs (Including Information Technology and Computer Science): https://www.nvsu.edu.ph/programs (Note: It is under College of Arts and Sciences)
3. The University uses Microsoft as its email domain provider through Outlook and also I am enrolled as a student in the said institution. (Shown in the image below) 
4. Also Here is the log in link where students here access our own institution account: https://cloud.nvsu.edu.ph/ 

Screenshot (4)

**Comment by philipto** [comment]
@daeyeonnn First stage of verification passed, official domain is [nvsu.edu.ph](https://nvsu.edu.ph) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@daeyeonnn Pull request merged. Thank you.

**Pull request merged**
