### PR TITLE
deleted wbsedu

### PR DESCRIPTION
**Pull request by javaman-22**

### CODE REVIEW

**Comment by philipto** [comment]
@javaman-22 Thank you for your patience while waiting for a review and processing your request. Could you please explain why did you name your pull request "deleted wbsedu"?

By default, your pull request would be considered as a request to add a domain "wbstraining.de" to the trusted list of domains. 

Also, you name your school "wbs training AG in Berlin,Germany" starting with an abbreviation in lower case letters. It seems to not be typical in German. Would you like to keep the name as it is, or wish to change it?

Thank you.

**Comment by javaman-22** [comment]
Hi Philip,

I named "deleted wbsedu" the pull request because I deleted it from the
domain "edu" which wasn't correct as you mentioned it before.

By the way, the lower case letters, I didn't make a lot of attention to it.
If that causes an issue, I can rename it if you want. Normally the school
name is WBS TRAINING AG

Thank you

**Comment by philipto** [comment]
@javaman-22  Thank you for the clarifications. Pull request merged.

**Comment by javaman-22** [comment]
Thank you also, Philip.

Is my school now verified and registered in the domain?

**Comment by philipto** [comment]
@javaman-22 Yes. It might be a technical issue prevented the merge two days ago, but the pull request must be merged now for sure. I am sorry for the trouble.

**Comment by javaman-22** [comment]
No problem Philip.

I tried to access the free license for the students, but it still says that my email address doesn't belong to any school or University.
Screenshot (2)

**Pull request merged**
