### PR TITLE
Added bssdstd (official domain is bssd)

### PR DESCRIPTION
**Pull request by William-Schroeder**
Added bssdstd (Blue springs school district student)

### CODE REVIEW

**Comment by philipto** [comment]
@William-Schroeder First stage of verification passed, official domain is [bssd.net](https://bssd.net) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.bssd.net/p_a_r_e_n_t_r_e_s_o_u_r_c_e_s/parent_tools/parent_portal_information

**Comment by William-Schroeder** [comment]
> @William-Schroeder First stage of verification passed, official domain is [bssd.net](https://bssd.net) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.bssd.net/p_a_r_e_n_t_r_e_s_o_u_r_c_e_s/parent_tools/parent_portal_information

I do not own this domain. I use an email distributed through my school district my school district owns the domain not me.

**Comment by William-Schroeder** [comment]
@philipto If you want verification that I have the email and go to bssd,imageI hope this will help

**Comment by philipto** [comment]
@William-Schroeder Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
