### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Lich555**
https://www.kwspz.pl/

### CODE REVIEW

**Comment by philipto** [comment]
@Lich555 kwspz.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Lich555 kwspz.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Lich555 kwspz.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Lich555 I renamed the file in the request on your behalf to have a correct path. The pull request merged. Thank you.

**Comment by Lich555** [comment]
Thank you for help :) Now can I buy this product with student's discount?Od: "Philip Torchinsky" &lt;notifications@github.com&gt;Do: "JetBrains/swot" &lt;swot@noreply.github.com&gt;; Wysłane: 10:20 Czwartek 2020-04-16Temat: Re: [JetBrains/swot] Add files via upload (#8114)
@Lich555 I renamed the file in the request on your behalf to have a correct path. The pull request merged. Thank you.

**Pull request merged**
