### PR TITLE
Create colegiomaanaim.txt

### PR DESCRIPTION
**Pull request by HollowFlame**

### CODE REVIEW

**Comment by philipto** [comment]
@HollowFlame Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by HollowFlame** [comment]
The school has different domains, one of the website, that is https://colegiomaanaim.com.br and the colegiomaanaim.net, that one is registered by Google and is used for the institutional mail. "aluno.colegiomaanaim.net" is a subdomain.

Here is the document with their instructions for the use of the mail: https://drive.google.com/file/d/1s9T-QqLlg7b6Wdx2xmkfexD7KqlKHP_Y/view?usp=drivesdk

School address: R. Waldemar Falcão, 29/31 - Brotas, Salvador - BA, 40301-110

**Comment by HollowFlame** [comment]
Just forgot to let it public, just saw today your permission request and granted it.

**Comment by HollowFlame** [comment]
Screenshot_20210330-121320

**Comment by HollowFlame** [comment]
Pull request closed. Applied to the Student Program using other way. Thank you.

**Pull request closed without merging**
