### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by synth-tenor**
Added name of school

### CODE REVIEW

**Comment by philipto** [comment]
@synth-tenor Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course

**Comment by philipto** [comment]
@synth-tenor I am sorry, I have a bad feeling that you are kidding me. Which course at the homepage of https://www.nycmuseumschool.org/ is long-term IT-related one? IT-related courses, where you may need some of JetBrains tools include, but not limit to, math, physics, computer science, software engineering, bioinformatics, statistics, etc. The homepage of NYC Museum School does not offer any of them. 

JetBrains' goal is to provide people who need JetBrains tools with free access to the tools. However, the idea is not to provide the access to people who do not need the tools. Please comment here why students or teachers in NYC Museum School need the tools. Please do not attach new files to your request, just open a page https://github.com/JetBrains/swot/pull/9764 and leave your comment there. Thank you.

**Comment by synth-tenor** [comment]
I apologise for wasting your time, I don't believe my school offers any sort of IT course, I was hoping that that wasn't a requirement. As it seems it is, then I'll just take down the fork, since atleast in my year, there is no course that would fit that criteria. Thank you for your time

**Comment by philipto** [comment]
@synth-tenor Thank you for the clarification. Yes, it is a requirement for adding the domain to this repository. However, if you personally need a free license, and you are the student or a teacher, please feel free to apply with your student ID (or anything that proves that you are a student or teacher) using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students. **You are eligible regardless of which course do you take.**

As for now, I have to close this request without merging.

**Pull request closed without merging**
