### PR TITLE
Create poloagoindustriale.txt

### PR DESCRIPTION
**Pull request by beppevoto**
Changed the school address from gov to edu

### CODE REVIEW

**Comment by philipto** [comment]
@beppevoto Please provide us with:
- the school official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
- an URL of a page or another proof (.pdf or a screenshot are OK) showing that the school recognizes the domain which you are submitting as an official email domain for the students.

**Comment by beppevoto** [comment]
I’ll ask to someone that has those data to reopen the pull request

**Comment by beppevoto** [comment]
I have the document you asked for, how can i send it?

**Comment by beppevoto** [comment]
@philipto i’ve created another pull request since i cannot reopen this anymore

**Pull request closed without merging**
