### PR TITLE
Add Toulouse Lautrec Institute Domain

### PR DESCRIPTION
**Pull request by joelibaceta**
Add support for talento.tls.edu.pe domain

### CODE REVIEW

**Comment by philipto** [comment]
@joelibaceta First stage of verification passed, official domain is [toulouselautrec.edu.pe](https://toulouselautrec.edu.pe) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://www.toulouselautrec.edu.pe/sites/default/files/2023-02/23-1_Lineamientos_de_pago_TLS.pdf

**Comment by joelibaceta** [comment]
@philipto It is correct, as you can see in Title 13 of the document, it is indicated that the domain assigned to the student's email is "@talento.tls.edu.pe." The literal translation from Spanish says:

"All undergraduate students have an active institutional email account. This account is composed of the student's code followed by the extension "@talento.tls.edu.pe." The access password is the same one provided by Toulouse Lautrec to access the academic system."

**Comment by joelibaceta** [comment]
Sure @philipto, I'll share the link to the [video game design career](https://www.toulouselautrec.edu.pe/carreras-profesionales-tecnicas/diseno-videojuegos-entretenimiento-digital) where programming topic is taught in the second and third years. Additionally, there are often short complementary courses offered, such as [Python](https://www.toulouselautrec.edu.pe/cursos/python-pro), [data science + IA](https://www.toulouselautrec.edu.pe/cursos/data-science-machine-learning), and [mobile application development](https://www.toulouselautrec.edu.pe/cursos/diseno-desarrollo-apps).

**Comment by philipto** [comment]
@joelibaceta Thank you for the clarification and your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
