### PR TITLE
Tomyo school of Ulaanbaatar

### PR DESCRIPTION
**Pull request by ganbaatar**

### CODE REVIEW

**Comment by philipto** [comment]
@ganbaatar First stage of verification passed, official domain is [m.facebook.com](https://m.facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/tomyoschool/photos/a.204242475057068/351830316964949/

**Comment by philipto** [comment]
@ganbaatar Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
* a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by ganbaatar** [comment]
@philipto 
Official website of Tomyo school of Ulaanbaatar: https://tomyo.edu.mn/
The school's official name: ТомЁ Улаанбаатар сургууль
Address: ХУД 4р хороо, Яармаг Арцатын ам, Мандала Гардэн хотхон, Улаанбаатар хот, Монгол улс
IT course URL: https://tomyo.edu.mn/training (Python, Java, PHP, Javascript, HTML, CSS, etc)
https://www.facebook.com/tomyoschool/photos/a.191902219624427/350614550419859/
Email domain: *******@tomyo.edu.mn

**Comment by philipto** [comment]
@ganbaatar First stage of verification passed, official domain is [m.facebook.com](https://m.facebook.com) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://m.facebook.com/tomyoschool/photos/a.204242475057068/351830316964949/

**Comment by philipto** [comment]
@ganbaatar You might miss my previous comment. Please react.

**Comment by ganbaatar** [comment]
> @ganbaatar Please provide us with:
> 
> * the school official website URL
> * the school official name in Mongolian language
> * the school street address, including city and country
> * an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
> * a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

Official website of Tomyo school of Ulaanbaatar: https://tomyo.edu.mn/
The school's official name: ТомЁ Улаанбаатар сургууль
Address: ХУД 4р хороо, Яармаг Арцатын ам, Мандала Гардэн хотхон, Улаанбаатар хот, Монгол улс
IT course URL: https://tomyo.edu.mn/training (Python, Java, PHP, Javascript, HTML, CSS, etc)
https://www.facebook.com/tomyoschool/photos/a.191902219624427/350614550419859/
Email domain: *******@tomyo.edu.mn

**Comment by ganbaatar** [comment]
> @ganbaatar You might miss my previous comment. Please react.
@philipto 
Please let me know which comment I missed.

**Comment by philipto** [comment]
@ganbaatar Thank you! We are checking some final details, and I expect to approve the request very soon. Thank you!

**Comment by philipto** [comment]
@ganbaatar Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
