### PR TITLE
Add irss file

### PR DESCRIPTION
**Pull request by marie29820**
Add irss

### CODE REVIEW

**Comment by philipto** [comment]
@marie29820 First stage of verification passed, official domain is [irss.fr](https://irss.fr) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@marie29820 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

**Comment by marie29820** [comment]
This training is available for a period of 12 months. it includes a computer tool learning module. https://www.irss.fr/formation-sante/formation-secretaire-medicale

**Comment by marie29820** [comment]
> @marie29820 Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you.

This training is available for a period of 12 months. it includes a computer tool learning module. https://www.irss.fr/formation-sante/formation-secretaire-medicale

**Comment by philipto** [comment]
@marie29820 Thank you for the clarification. As far as I see, the course curriculum is what I quote below, using https://www.irss.fr/sante-social/formations/formation-secretaire-medicale as a source:

```
Communication, production of documents 
Office module
French language module
English module
Specific medical skills  
Pathophysiology and medical terminology module
Work management and organization 
Administrative module
Accounting module 
Organization module
Individual training / work independently
(work given by teachers in administration, organization, accounting, English)
 Final exam training
Search for an internship / personal work 
(course,  internship report, etc.)
``` 

I don't see "computer tool learning module" there. Also, common sense suggests that a medical secretary has to have a lot of different extensive knowledge, but why software development can be a part of them?

I cannot add this domain to the trusted list because it's unlikely that many students from this school need to learn software development professionaly.

You can, however, apply for your individual license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
