### PR TITLE
Create unirv.txt

### PR DESCRIPTION
**Pull request by Peronbombom**
Register of Universidade de Rio Verde

http://www.unirv.edu.br/
http://www.unirv.edu.br/graduacao_curso.php?id=42

### CODE REVIEW

**Comment by philipto** [comment]
@Peronbombom unirv.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Peronbombom unirv.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Peronbombom unirv.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Peronbombom unirv.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@Peronbombom Pull request merged. Thank you! You did not name the file in the request correctly, thus I  did it for you. Please wait at least two hours after this message is sent, before start requesting the licenses at https://jetbrains.com/student.

**Comment by Peronbombom** [comment]
OK! Thank you for correcting the name for me! I'm already waiting for the acception of my studant license request.
Thank you again!

________________________________
De: Philip Torchinsky <notifications@github.com>
Enviado: segunda-feira, 11 de maio de 2020 08:01
Para: JetBrains/swot <swot@noreply.github.com>
Cc: Peronbombom <viniciusmirandaperon@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [JetBrains/swot] Create unirv.txt (#8255)


@Peronbombom<https://github.com/Peronbombom> Pull request merged. Thank you! You did not name the file in the request correctly, thus I did it for you. Please wait at least two hours after this message is sent, before start requesting the licenses at https://jetbrains.com/student.

**Pull request merged**
