### PR TITLE
Add AIAC university

### PR DESCRIPTION
**Pull request by m-yassine-kun**

### CODE REVIEW

**Comment by philipto** [comment]
@m-yassine-kun Please provide us with a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
You can provide us with any of the following:

* A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
* An URL of a page at the official school website that says that students use this email domain
* A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
* A WHOIS data that link the email domain to the school somehow
* A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
* Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@m-yassine-kun You might miss my previous comment. Please react.

**Comment by m-yassine-kun** [comment]
@philipto Sorry for being late! In fact, I couldn't get any proof from the university. I'm at my end year, and the university has moved to another domain aiac.ma. I just have a screenshot of details accounts on outlook you can find it using this google drive link: _**[shorturl.at/ahWZ3](https://drive.google.com/drive/folders/1d2O_qq6A_hPtPvbGPKCCLVYPpQV7Y6Zt)**_
thanks for you consideration!

**Comment by philipto** [comment]
@m-yassine-kun  Thank you for the clarifications. Given that the university moved to another domain, it is not a good idea to add the old one to the trusted list.

Please apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

I have to close the request without merging.

Thank you for your understanding!

**Pull request closed without merging**
