### PR TITLE
add ecnu email domian

### PR DESCRIPTION
**Pull request by zybing**
I have added East China Normal University email domain

### CODE REVIEW

**Comment by zybing** [comment]
This is the main page about ecnu.
http://www.ecnu.edu.cn/
but the email domain is *****@ecnu.cn, so I need add another ecnu email domain.

**Comment by philipto** [comment]
@zybing Could you please confirm with a link to an official website page that students at the unversity use @ecnu.cn as their email domain? This page (http://faculty.ecnu.edu.cn/s/3318/main.jspy), for example, lists another domain as an email domain for the university teacher.

**Comment by zybing** [comment]
@philipto I am sorry that I don't find page about student email account. This is my email screenshot。you can see email address from it.
student domain

**Comment by philipto** [comment]
@zybing Thank you. Actually, I found some articles in the internet which were published by ECNU students and/or teachers, for example http://alt.qcri.org/semeval2015/cdrom/pdf/SemEval021.pdf. The author emails in the articles confirm that at least some students and teachers at ECNU have the emails in the domain ecnu.cn, while others have emails in other domains. Pull request merged.

**Pull request merged**
