### PR TITLE
Re-Add "BSZ Bietigheim-Bissingen"

### PR DESCRIPTION
**Pull request by TheLegendaryMarc**
Mail: @bszbb.onmicrosoft.com
Homepage: https://www.bsz-bietigheim.de/
Country: Germany

### CODE REVIEW

**Comment by philipto** [comment]
@TheLegendaryMarc Could you please provide us with a proof showing that the school recognizes the domain which you are submitting as an official email domain for the students? I did not find any mentions of bszbb.onmicrosoft.com at the official website. 
Thank you.

**Comment by philipto** [comment]
@TheLegendaryMarc You might miss my previous comment. Please react.

**Comment by TheLegendaryMarc** [comment]
We are currently working on the possibility to activate the domain bszbb.de for students.
Currently only the temporary domain bszbb.onmicrosoft.com is valid and usable

**Comment by philipto** [comment]
@TheLegendaryMarc I am sorry, this request remains unanswered for a while. I have to close it without merging. Please reopen and comment if you have an update regarding the aforementioned issue. Thank you for the understanding!

**Pull request closed without merging**
