### PR TITLE
Dover High School

### PR DESCRIPTION
**Pull request by Unexpextxd**
I am applying on behalf of Dover High School to your Products for Learning program.

### CODE REVIEW

**Comment by philipto** [comment]
@Unexpextxd file/lib/domains/us/nh/k12/dover.txt: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by Unexpextxd** [comment]
I don't see the problem. The domain is dover.k12.nh.us, I have all the
required information in the text file, and the structure is correct.

**Comment by philipto** [comment]
Please don’t worry; it’s a little issue, and I’ll correct it for you. The file path has to start with lib/, instead of file/lib/.

Thank you!

**Comment by Unexpextxd** [comment]
Thank you! Does this mean my class has access to the suite now?

**Pull request merged**
