### PR TITLE
Add ENIM

### PR DESCRIPTION
**Pull request by Rafik-BEN-YEDDER**
ENIM - Ecole Nationale d'Ingénieurs de Monastir
National School of Engineers of Monastir

### CODE REVIEW

**Comment by Rafik-BEN-YEDDER** [comment]
ENIM - Ecole Nationale d'Ingénieurs de Monastir
National School of Engineers of Monastir

**Comment by philipto** [comment]
@Rafik-BEN-YEDDER First stage of verification passed, official domain is [enim.rnu.tn](https://enim.rnu.tn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://enim.rnu.tn/fra/articles/384/compte-academique--compte-teams--

**Comment by philipto** [comment]
@Rafik-BEN-YEDDER Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Comment by Rafik-BEN-YEDDER** [comment]
Thank you

**Pull request merged**
