### PR TITLE
osvukkaradzic-knjazevac

### PR DESCRIPTION
**Pull request by viktorciric**
The school's official website:_ https://www.osvukknjazevac.edu.rs/
Student email: @osvukknjazevac.edu.rs

Hi, I would like to request that you add my school.
 If you need any additional information, please feel free to contact me.

### CODE REVIEW

**Comment by philipto** [comment]
@viktorciric lib/domains/rs/edu/OS: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@viktorciric To add `osvukknjazevac.edu.rs` to the repository, you need to add a single file: `lib/domains/rs/edu/osvukknjazevac.txt`. Do you need to add this domain or something else?

**Comment by viktorciric** [comment]
@philipto Yes, that’s right. I want to add the domain, and I hope I did it correctly. If you need anything else, feel free to let me know, and I’ll take care of it promptly.

**Comment by viktorciric** [comment]
@philipto Yes, that’s what I want. Please add my domain. If you need any assistance, feel free to reach out.

**Comment by philipto** [comment]
@viktorciric lib/domains/rs/edu/OS: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Pull request closed without merging**
