### PR TITLE
NMSU

### PR DESCRIPTION
**Pull request by Fratorhe**
Added New Mexico State University (NMSU) 
https://www.nmsu.edu/

### CODE REVIEW

**Comment by philipto** [comment]
@Fratorhe I am sorry, the domain nmsu.edu is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Comment by Fratorhe** [comment]
Dear Philip,

I am a professor at NMSU in aerospace engineering.
How should I proceed in this case?

Best,
Francisco

**Comment by cweska** [comment]
@Fratorhe 

Like Philip said your students can get this for free by signing up for the GitHub student developer program.

I'm just a fellow NM educator (not affiliated with JetBrains) but for what it's worth, it looks like the fraud was detected last years around September 1st 2023. https://github.com/JetBrains/swot/commit/7421dbe687651edb0548e7762219258c0a587da4

Reading other closed PRs it seems like you're the 4th person to try to re-add NMSU since it got on the naughty list. You could try reaching out to Philip by @ing him, though I would highly recommend trying to figure out what happened and what you can do to prevent any further miss-use since Philip seems to be running this whole thing as a 1-person show. I'm not even sure if they can grant second chances.

I would point you in the direction of the person who added NMSU as maybe they would know the context/how the abuse happened but it seems like NMSU was part of a mass-add of US universities about 12 years ago.
https://github.com/JetBrains/swot/commit/9d06b6bf7f8a8c7c3202d5b29d655e3ee9102a45

**Comment by Fratorhe** [comment]
Thanks for the information Carter. Can I get it as well as an educator?
Cause I saw it needed to be in this list...

**Pull request closed without merging**
