### PR TITLE
Trương Công Giai Highschool

### PR DESCRIPTION
**Pull request by cvnsoftware**
please, add my school: Trương Công Giai Highschool
Thank you

### CODE REVIEW

**Comment by philipto** [comment]
@cvnsoftware First stage of verification passed, official domain for **THCS Trương Công Giai** is [caugiay.edu.vn](https://caugiay.edu.vn) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@cvnsoftware Regrettably, I cannot connect the official website of the school for prolonged time. I cannot verify the domain eligibility without taking look at the website. I'll get back to this request later.

**Comment by khangcodt** [comment]
http://thcstruongconggiai.edu.vn/ this is the official website of the school. This school is belong to CauGiay District so this domain email is caugiay.edu.vn. That is the way of organization for education in our country.
Please take a look the website and help me to register for this school.

thanks,

**Comment by cvnsoftware** [comment]
http://thcstruongconggiai.edu.vn/ this is the official website of the school. This school is belong to CauGiay District so this domain email is caugiay.edu.vn. That is the way of organization for education in our country.
Please take a look the website and help me to register for this school.

thanks,

**Comment by cvnsoftware** [comment]
@philipto please take a look at our school at the offcial website: http://thcstruongconggiai.edu.vn/ and review for registration of our school.

Thanks & Best regards,

**Comment by philipto** [comment]
@cvnsoftware Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
