### PR TITLE
Create itsos-mariecurie.it

### PR DESCRIPTION
**Pull request by vlahovp**
Itsos Marie Curie is a technical school in Milan area , Cernusco sul Naviglio
Students are involved in Information Technology studies including dynamic web sites development,
we are using XAMP suite until now.

the institutional email is info@itsos-mariecurie.it
the site is : http://www.itsos-mariecurie.gov.it/

### CODE REVIEW

**Comment by vlahovp** [comment]
Hi, I'm not sure I've done the correct steps to join the list of recognized school.
I 'm trying to apply to have the "student licence", but my institutional email address is not recognized.
Thank you !

**Comment by vlahovp** [comment]
my email is paola.vlahov@itsos-mariecurie.it

**Comment by philipto** [comment]
@vlahovp I am sorry for a delay with processing your request. Please rename the file from lib/domains/it/itsos-mariecurie.it to lib/domains/it/itsos-mariecurie.txt, and I'll merge the request momentarily. Thank you!

**Comment by vlahovp** [comment]
Thank you for the suggestion,
so, if I understand, my students who have  an istitutional email of the type : "name@itsos-mariecurie.it", will be able to make the student licence request?

thank you!

**Comment by philipto** [comment]
@vlahovp Yes, they will. Thank you for the update! Pull request merged and takes effect in about 60 minutes from now.

**Pull request merged**
