### PR TITLE
zsimbn.txt

### PR DESCRIPTION
**Pull request by Burkot-Marek**

### CODE REVIEW

**Comment by philipto** [comment]
@Burkot-Marek Please provide us with:
- the university official website URL, if different from the domain you are submitting
- an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university
- an URL of a page or another proof showing that the university recognizes the domain which you are submitting as an official email domain for the students.

**Comment by Burkot-Marek** [comment]
Okay, 
So this is our school: [https://narwik.edu.pl/](url)
It's technical school, if u need to know.
I don't know how to show you the second point, i'm from IT Specialist class ("Informatyk" means IT Specialist), actually i'm in the third class so >1 year ofc
I hope, this screan will be some kind of proof [https://ibb.co/NnzLchV](url)

**Comment by philipto** [comment]
@Burkot-Marek Thank you for the clarification. Pull request merged.

**Comment by Burkot-Marek** [comment]
Could i ask when i will be able to create a account with this link? https://www.jetbrains.com/shop/eform/students?_st=4cbl0gslzz

**Pull request merged**
