### PR TITLE
Added University of Minnesota

### PR DESCRIPTION
**Pull request by JEck05**
--I had to delete an invalid file (d.txt)

### CODE REVIEW

**Comment by Dounutsubtly** [comment]
Joined GitHub on September 6, 2023, 
with only one pull request in two years. 
Are you attempting an infinite clone jutsu to game the jetbrains?

**Comment by JEck05** [comment]
Umm im unsure what that means lol I'm just usually inactive and for some reason my school email doesn't work for free jetbrains any more

**Comment by Dounutsubtly** [comment]
https://github.com/JetBrains/swot/blob/995915be472e98f90808bb123b9d0524b43f7c73/lib/domains/abused.txt#L1125

**Comment by Dounutsubtly** [comment]
> https://github.com/JetBrains/swot/blob/995915be472e98f90808bb123b9d0524b43f7c73/lib/domains/abused.txt#L1125

You need to remove this.

**Comment by JEck05** [comment]
Ohh so I just remove it then do another pull request??

**Comment by philipto** [comment]
@JEck05 I am sorry, the domain umn.edu is removed from our trusted domains list because it was abused in the past. If you are the student of this school, please enroll to [GitHub Student Developer Program](https://education.github.com/discount_requests/application). Then apply for JetBrains educational subscription with your GitHub account (**GitHub** tab at https://www.jetbrains.com/shop/eform/students).

**Comment by Dounutsubtly** [comment]
Stop abusing, please! 
We're not running a social experiment!

**Comment by JEck05** [comment]
@philipto Thank you so much I appreciate it:)

**Comment by Dounutsubtly** [comment]
Hey Philipto, @philipto 

I just wanted to give you a heads-up—this university can change their email address as many times as they want, without any restrictions. Also, I’ve noticed that the guy you're dealing with is from a Chinese forum, and it looks like he’s getting ready to sell JetBrains activation codes for just $1. Please be careful, it doesn’t feel right, and I wouldn’t want you to get caught up in something shady.

Take care!

**Pull request merged**
