### PR TITLE
Salem High School

### PR DESCRIPTION
**Pull request by Jenit-Patel**
Salem High School in Rockdale County School District

Google Maps Link to the district
Rockdale County School District: https://www.google.com/maps/place/Rockdale+County+School+District,+GA/@33.6808979,-84.1197578,11z/

### CODE REVIEW

**Comment by Jenit-Patel** [comment]
How long will it usually take to do this?

**Comment by hmawla** [comment]
Currently, they are having delays due to COVID-19, so it may take a little while since there is no accurate estimation of time...

**Comment by Jenit-Patel** [comment]
Ok thank you for the notice, I just hope it gets added soon also the student email is “students.rockdale.k12.ga.us” if that info is needed.

**Comment by hmawla** [comment]
> Ok thank you for the notice, I just hope it gets added soon also the student email is “students.rockdale.k12.ga.us” if that info is needed.

No problem at all, also, I believe that the institute you are trying to add is a Secondary Grade School, since if that so and if the school doesn't offer Higher Education Curreculum then it won't be eligible in SWOT as per the conditions mentioned in their [README.md](https://github.com/JetBrains/swot/blob/master/README.md)

**Comment by philipto** [comment]
@Jenit-Patel Pull request merged. Thank you!

**Pull request merged**
