### PR TITLE
Create novauniversitas.txt

### PR DESCRIPTION
**Pull request by EricGuendu**
Im trying to add a University called NovaUniversitas

### CODE REVIEW

**Comment by EricGuendu** [comment]
NovaUniversitas has no conflicts with the base branch and was added

**Comment by kivandres** [comment]
How do I add a new University?

**Comment by kivandres** [comment]
I want to add my university, please anybody help me

**Comment by philipto** [comment]
@EricGuendu First stage of verification passed, official domain is [novauniversitas.edu.mx](https://novauniversitas.edu.mx) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@EricGuendu Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
