### PR TITLE
add umma university kenya

### PR DESCRIPTION
**Pull request by wycliffemwimali**
https://umma.ac.ke/

### CODE REVIEW

**Comment by philipto** [comment]
@wycliffemwimali First stage of verification passed, official domain is [umma.ac.ke](https://umma.ac.ke) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by wycliffemwimali** [comment]
@philipto yes thank you but the email format is admission number@students.umma.ac.ke

**Comment by philipto** [comment]
@wycliffemwimali Pull request merged. Thank you.

**Comment by wycliffemwimali** [comment]
Thank you @philipto

**Pull request merged**
