### PR TITLE
Add a new school request

### PR DESCRIPTION
**Pull request by blackBusterH**

### CODE REVIEW

**Comment by philipto** [comment]
@blackBusterH lib/domains/se/lugnet: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@blackBusterH lib/domains/se/lugnet: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@blackBusterH lib/domains/se/lugnet: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@blackBusterH lib/domains/se/lugnet: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@blackBusterH lib/domains/se/lugnet: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@blackBusterH I am sorry, could you please clarify:
1) lugnet.se domain seems to belong to a sport center in Falun commune, isn't it?
2) I found no indication that lugnet.se is used exclusively by students and teachers, doesn't the school have a dedicated email domain?

Also, please add .txt extension to the filename in your request, it's missed. Thank you.

**Comment by blackBusterH** [comment]
We do have a mail domain but all schools in falun use the same:
skola.falun.se, I can mail you from my school account if needed.
https://www.falun.se/utbildning--barnomsorg/gymnasium/kommunala-gymnasieskolor/lugnetgymnasiet.html

Here is my school

**Comment by philipto** [comment]
@blackBusterH I am sorry, do I understand right that all teachers and students in your school have email address pattern username@lugnet.se? If not, what is their email pattern?

**Comment by philipto** [comment]
@blackBusterH lib/domains/se/lugnet: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@blackBusterH lib/domains/se/lugnet: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@blackBusterH lib/domains/se/lugnet: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@blackBusterH I am sorry, my comment remains unanswered for a while. It is still unclear what is your school email pattern. I have to close the request without merging. Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) before submitting a new request.

**Comment by blackBusterH** [comment]
I mailed you before that all students have skola.falun.se and teachers have
falun.se

**Pull request closed without merging**
