### PR TITLE
THPT LQD KH

### PR DESCRIPTION
**Pull request by MinhTXGENZ**

### CODE REVIEW

**Comment by ruadoVn** [comment]
vietnam?

**Comment by MinhTXGENZ** [comment]
Yes, I'm From Vietnam

**Comment by ruadoVn** [comment]
same lol

**Comment by philipto** [comment]
@MinhTXGENZ I am sorry, I am not sure what are your actual needs.

You submitted a domain c3lqdon-khanhhoa.edu.vn to add to the repository. However, the domain is not mentioned at http://lqdon.khanhhoa.edu.vn/ website, which is the official website of the school. 

The school staff have email in the similar domain, but different, as I can read at http://lqdon.khanhhoa.edu.vn/gioi-thieu/so-do-to-chuc/to-chuyen-mon.html.

I would suggest to add the domain khanhhoa.edu.vn, but it seems not belonging to a particular school. What organization owns khanhhoa.edu.vn domain? 

Please reply. Thank you.

**Comment by MinhTXGENZ** [comment]
The khanhhoa.edu.vn domain is for whole all School in my Province but I just want to Submit only my school's Domain.

**Comment by philipto** [comment]
@MinhTXGENZ Thank you for the clarification. Is there any instruction that you have from your school that confirms that your school uses domain c3lqdon-khanhhoa.edu.vn? Do I understand you right that all students in your school have email addresses with a pattern username@c3lqdon-khanhhoa.edu.vn? 

I appreciate it very much if you upload a proof, which shows that the school recognizes the domain c3lqdon-khanhhoa.edu.vn as an official email domain for the students.
You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by MinhTXGENZ** [comment]
Hmmmmm, I just have a announce from my school that the student will use the c3lqdon-khanhhoa.edu.vn domain.
Here is the link: http://lqdon.khanhhoa.edu.vn/tin-tuc/tin-tuc-truong/thong-bao-hoc-truc-tuyen.html
You can see in the Excel Files that stored all the Account (Microsoft Office) for student to Learning with the Microsoft Teams.
You can also see my account in that files (My name is Bùi Quang Minh Tâm) in the "1a-Taikhoan K10.xlsx". And I promise all Users in that file are the Student in the grade 10 with me.

**Comment by philipto** [comment]
@MinhTXGENZ Thank you very much for your patience and the clarification!
Pull request merged. Thank you!

**Comment by MinhTXGENZ** [comment]
> @MinhTXGENZ Thank you very much for your patience and the clarification!
> Pull request merged. Thank you!
> 

Thank you to merged our Domain.

**Pull request merged**
