### PR TITLE
Create VJC

### PR DESCRIPTION
**Pull request by btjm123**
#### Institution/School Name 
Victoria Junior College

#### Instiution/School Website
https://victoriajc.moe.edu.sg

#### Email Users
@vjc.sg

*Please place an x between the square brackets if yes*
- [x] Students
- [x] Academic/Teaching Staff
- [x] Other/Support Staff
- [x] Alumni

#### Education Levels

*Please place an x between the square brackets if yes*

- [ ] Post-graduate research
- [ ] Graduate School
- [ ] College (University) or Undergraduate School or equivalent
- [ ] Community College or equivalent
- [x] High School or equivalent
- [ ] Elementary School or equivalent

Benn Tan Jia Ming ~ Class of 2019

### CODE REVIEW

**Comment by philipto** [comment]
@btjm123 lib/domains/sg/vjc: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@btjm123 Please provide us with:
- the school official website URL
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.

**Comment by philipto** [comment]
@btjm123 What is an email pattern for the users of this school? Is username@vjc.sg?

**Comment by btjm123** [comment]
@philipto yes

**Comment by philipto** [comment]
@btjm123 Pull request merged. Thank you!

**Pull request merged**
