### PR TITLE
Create Garnet Valley

### PR DESCRIPTION
**Pull request by ben60501**

### CODE REVIEW

**Comment by ben60501** [comment]
Added Garnet Valley

**Comment by philipto** [comment]
@ben60501 Could you please:
1) Rename lib/domains/us/pa/k12/garnetvalley to lib/domains/us/pa/k12/garnetvalley.txt
2) Clarify if you wish to add a domain of @garnetvalley.k12.pa.us to this repository? All teachers at the school website contact page http://www.garnetvalleyschools.com/site/Default.aspx?PageType=1&SiteID=452&ChannelID=501&DirectoryType=6  have their emails in another domain -
 @garnetvalley.org
Thank you!

**Comment by ben60501** [comment]
@philipto I have renamed the file. But on your number two all of the school emails (teachers and students) end in @garnetvalley.org so is garnetvalley.txt all I need to add?

**Comment by philipto** [comment]
@ben60501 In that case you need to rename the file again, the name which represents @garnetvalley.org is  lib/domains/org/garnetvalley.txt. Thank you for clarification. Please rename.

**Pull request closed without merging**
