### PR TITLE
Added school of commerce of lisbon

### PR DESCRIPTION
**Pull request by MCFDev**

### CODE REVIEW

**Comment by philipto** [comment]
@MCFDev First stage of verification passed, official domain is [escolacomerciolisboa.pt](https://escolacomerciolisboa.pt) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision. Proof of domain ownership: https://escolacomerciolisboa.pt/escola-profissional/learning-navigators/

**Comment by MCFDev** [comment]
yes but the school emails are hosted at eclisboa.net

**Comment by philipto** [comment]
@MCFDev Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

**Comment by MCFDev** [comment]
> @MCFDev Please provide us with an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course. Thank you!

https://escolacomerciolisboa.pt/escola-profissional/cursos-profissionais/tecnico-de-informatica-sistemas/

**Comment by MCFDev** [comment]
it is in portuguese

**Comment by MCFDev** [comment]
it is also a 3 year course

**Comment by philipto** [comment]
@MCFDev Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
