### PR TITLE
Promotion Sociale Arlon

### PR DESCRIPTION
**Pull request by ofries**
Bachelor in IT (4 years course)

### CODE REVIEW

**Comment by philipto** [comment]
@ofries lib/domains/be/promsoc-arlon/staff: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@ofries lib/domains/be/promsoc-arlon/staff: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by ofries** [comment]
> @ofries lib/domains/be/promsoc-arlon/staff: this request has an incorrect file path format, please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change your request accordingly. If you don't know how to change request, close it and open a new one. If you are not able to make the pull request according the instructions, please send us an email to [support@jetbrains.com](mailto:support@jetbrains.com). Please mention this request URL in the message.

@philipto : I think the path request can not be different. My professional Email in the organisation is "olivier.fries@staff.promsoc-arlon.be". A student in the organisation have a Email  such "name.forname@student.promsoc-arlon.be".
Could you confirm that my analyse is right?

**Comment by philipto** [comment]
@ofries lib/domains/be/promsoc-arlon/staff: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@ofries lib/domains/be/promsoc-arlon/staff: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@ofries lib/domains/be/promsoc-arlon/staff: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@ofries lib/domains/be/promsoc-arlon/staff: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by philipto** [comment]
@ofries Thank you for your request! The error message was due to the file name, it has to end with ".txt" extension. I renamed the file for you and merged the request.

Please feel free to start requesting your free licenses in an hour. Thank you!

**Comment by ofries** [comment]
> @ofries Thank you for your request! The error message was due to the file name, it has to end with ".txt" extension. I renamed the file for you and merged the request.
> 
> Please feel free to start requesting your free licenses in an hour. Thank you!

@philipto Thank you for your intervention. I'm sorry for the mistake.
Best regards.

**Pull request merged**
