### PR TITLE
Adding Rtu domain

### PR DESCRIPTION
**Pull request by EmilBabazade**
There was a mistake in domain name, its edu.rtu.lv not rtu.edu.lv, i fixed that

### CODE REVIEW

**Comment by philipto** [comment]
@EmilBabazade I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host edu.edu.lv not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by EmilBabazade** [comment]
hello i added the domeain, edu.rtu.lv not edu.edu.lv

**Comment by philipto** [comment]
@EmilBabazade I am sorry, your request is not editable. Please clarify what is a correct domain - edu.rtu.lv? Simply saying, what you email address is like - username@edu.rtu.lv?

**Comment by EmilBabazade** [comment]
yes it is ***@***.***

**Comment by philipto** [comment]
@EmilBabazade I have to close this request without merging, because you requested to add a non-existent domain to this repository: `Host edu.edu.lv not found: 3(NXDOMAIN)` Please ensure that you are familiar with this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and submit a new request with the correct information. Thank you for your understanding!

**Comment by philipto** [comment]
@EmilBabazade You don't need to add edu.rtu.lv because the parent domain, rtu.lv, is already in this repository.
If you see any error message while applying for free license, please send a screenshot of the error to community-support@jetbrains.com. Please ensure that you do not enter leading or trailing spaces filling in the form at https://www.jetbrains.com/shop/eform/students.

I am closing this request as a duplicate. Thank you.

**Pull request closed without merging**
