### PR TITLE
Create eastwest.txt

### PR DESCRIPTION
**Pull request by arathycyril**
This is to add students of East West university Georgia.

### CODE REVIEW

**Comment by philipto** [comment]
@arathycyril Please provide us with:
* the school official website URL
* the school street address, including city and country
* an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course.

Thank you!

**Comment by philipto** [comment]
@arathycyril You might miss my previous comment. Please react.

**Comment by arathycyril** [comment]
- https://www.east-westuniversity.com/
- St. Tbilisi, Vakhtang Gorgasali st. 9, Tbilisi, street 0105, Georgia 
- https://www.east-westuniversity.com/academic-programs/
Eastwest university has research and development in Biomedical informatics which focus on IT training in clinical decisions in medical support systems. This university is tied up to many other universities to conduct research and analysis to solve problems in biological and medical science.

**Comment by philipto** [comment]
@arathycyril Regrettably, this request has signs of fraud. I have to close it without merging.

It does not mean that something is wrong with the school. The issue is related to a combination of many suspicious factors related to the domain and the request.

Please feel free to apply for free educational license with an official document which proves that you are a student. You can do it using "OFFICIAL DOCUMENT" tab at https://www.jetbrains.com/shop/eform/students.

Thank you for your understanding!

**Pull request closed without merging**
