### PR TITLE
National Academy of the Security Service of Ukraine

### PR DESCRIPTION
**Pull request by cybercenter-nasbu**
University official website URL: https://nasbu.edu.ua
URL of a page on the official website where a long-term (>1 year) IT related course is offered:  https://nasbu.edu.ua/ua/79-osvitni-programi-studentam

### CODE REVIEW

**Comment by samuel-edmund-morgan** [comment]
Any updates?

**Comment by cybercenter-nasbu** [comment]
Any updates?

**Comment by cybercenter-nasbu** [comment]
Everything ok? Why still no message about “first stage passed” as other pull requests have such a message which were AFTER our pull request?

**Comment by philipto** [comment]
@cybercenter-nasbu First stage of verification passed, official domain for **Національна академія Служби безпеки України** is [nasbu.edu.ua](https://nasbu.edu.ua) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Pull request merged**
