### PR TITLE
Add André Malraux Highschool (located in Bethune, France)

### PR DESCRIPTION
**Pull request by Zoeille**
Hi, here is the addition of André Malraux high-school located in Bethune. (:

### CODE REVIEW

**Comment by Zoeille** [comment]
Note: This website is only used by the development section of our high school (and is owned by our school), the official website of our highschool is: https://andre-malraux-bethune.enthdf.fr/

**Comment by philipto** [comment]
@Zoeille Thank you for your request!
Would you please provide us with a proof, which shows that the school recognizes the domain **malrauxbethune.fr** that you are submitting as an official email domain for the students?

You can provide us with any of the following:
1. A copy of instruction (a hard-copy or electronic one) given to you by the school that tells you to use an email address in this email domain
2. An URL of a page at the official school website that says that students use this email domain
3. A reference to a recognized journal where an article was published by someone from the school, with explicit affiliation to the school, and e-mail address from the email domain
4. A WHOIS data that link the email domain to the school somehow
5. A copy of official letter from the school representative saying that the school provides e-mail addresses in this domain to the students
6. Anything else that can prove this fact in similar way, i.e. can be verified independently.

**Comment by philipto** [comment]
@Zoeille You might miss my previous comment. Please react.

**Comment by Zoeille** [comment]
> @Zoeille You might miss my previous comment. Please react.

Yep I saw your last message, I will ask one of teacher to send me a message that confirm it's a domain used by my school
All was done by voice only so I don't have written proof right now

The website is a default webpage from 1&1 but we have subdomains that are used by our teachers
easystage.malrauxbethune.fr
sio.malrauxbethune.fr/ApplicationSuiviSIO/

Also my school is already listed on Github Student schools
image

**Comment by Zoeille** [comment]
@philipto Here is the whois for the domain malrauxbethune.fr

`domain: malrauxbethune.fr
status: ACTIVE
hold: NO
holder-c: LGET140-FRNIC
admin-c: LGET246-FRNIC
tech-c: UIS153-FRNIC
zone-c: NFC1-FRNIC
nsl-id: NSL67999-FRNIC
registrar: IONOS SE
Expiry Date: 2022-10-05T15:57:11Z
created: 2012-10-05T15:57:11Z
last-update: 2021-10-05T17:08:31Z
source: FRNIC

ns-list: NSL67999-FRNIC
nserver: ns1050.ui-dns.de
nserver: ns1050.ui-dns.biz
nserver: ns1050.ui-dns.com
nserver: ns1050.ui-dns.org
source: FRNIC

registrar: IONOS SE
type: Isp Option 1
address: Ernst-Frey Strasse 9
address: 76135 KARLSRUHE
country: DE
phone: +49 721 91374 50
fax-no: +49 721 91374 215
e-mail: hostmaster@1und1.de
website: https://ionos.com
anonymous: NO
registered: 2001-01-17T12:00:00Z
source: FRNIC

nic-hdl: LGET140-FRNIC
type: ORGANIZATION
contact: LYCEE GENERAL ET TECHNOLOGIQUE MALRAUX
address: rue de schwerte
address: 62400 Bethune
country: FR
phone: +33 3 21 63 12 43
fax-no: +33 3 21 63 12 40
e-mail: bruno.marais@ac-lille.fr
registrar: IONOS SE
changed: 2012-10-05T15:56:05Z nic@nic.fr
anonymous: NO
obsoleted: NO
eligstatus: pending
eligsource: REGISTRY
reachstatus: pending
reachsource: REGISTRY
source: FRNIC

nic-hdl: LGET246-FRNIC
type: ORGANIZATION
contact: LYCEE GENERAL ET TECHNOLOGIQUE MALRAUX
address: LYCEE GENERAL ET TECHNOLOGIQUE MALRAUX
address: 314, rue Jules Massenet
address: B.P. 90817
address: 62408 Bethune cedex
country: FR
phone: +33 3 21 64 61 62
fax-no: +33 3 21 64 64 61
e-mail: jean-francois.renaut@ac-lille.fr
registrar: IONOS SE
changed: 2016-11-10T17:55:57Z nic@nic.fr
anonymous: NO
obsoleted: NO
eligstatus: not identified
reachstatus: not identified
source: FRNIC

nic-hdl: UIS153-FRNIC
type: ORGANIZATION
contact: 1&1 Internet SARL
address: 1&1 Internet SARL
address: 7, place de la Gare
address: 57200 Sarreguemines
country: FR
phone: +33 9 70 80 89 11
fax-no: +33 3 87 95 99 74
e-mail: hostmaster@1and1.fr
registrar: IONOS SE
changed: 2015-06-30T07:14:37Z nic@nic.fr
anonymous: NO
obsoleted: NO
eligstatus: not identified
reachstatus: not identified
source: FRNIC`

**Comment by philipto** [comment]
@Zoeille Thank you for the clarification. Pull request merged.

**Pull request merged**
