### PR TITLE
Create utcportsmouth.txt

### PR DESCRIPTION
**Pull request by critical58**

### CODE REVIEW

**Comment by critical58** [comment]
School URL: https://www.utcportsmouth.org/
School Address: UTC Portsmouth, London Road, Portsmouth, Hampshire, PO2 9DU, United Kingdom
Proof of Computer Science Course: https://www.utcportsmouth.org/year-10-curriculum (Scroll to subheading OPTIONS)
Proof of student email: 
image

**Comment by philipto** [comment]
@critical58 First stage of verification passed, official domain is utcportsmouth.org as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by philipto** [comment]
@critical58 Pull request merged. Thank you!

**Comment by critical58** [comment]
@philipto Thanks!

**Pull request merged**
