### PR TITLE
Adds FS Pionir

### PR DESCRIPTION
**Pull request by marxo**
This commit adds the "Pionir free school" to the repo. 
Pionir is a technology school, while the programme combines ethics, communication, free and open software and hardware, and production of commons. The programmes offered are 4 years long and the school operates as a post-secondary educational organization.

Website: https://pionir.org

Concept pages states the program is 4 years with 1 year increments. https://pionir.org/koncept/

Verified domain screenshot pionir.org

### CODE REVIEW

**Comment by philipto** [comment]
@marxo Thank you for the request! This school seems to be a totally online school, thus we need to ensure that it is accredited by the respective government regulator. Could you please tell me how can we check that the school is an accreditation? It has to be a recognized online school in the country, not a training center nor an online educational platform.

**Comment by marxo** [comment]
@philipto Thanks for the prompt reply. Actually, we are an offline-only school. We do not offer online courses or programmes. We have a physical location in Kikinda, Serbia with student attendance. Some sparse info is provided on the contact page: https://pionir.org/kontakt/

Also, we're an educational organization incorporated in Serbia, registry number 28203519.

**Comment by philipto** [comment]
@marxo Thank you for correcting me, I was mistaken. The problem is that this school seems to have no IT courses announced at the website. According to the rules of this repository, 

> Your pull request for adding a new email domain to the repository will be satisfied if all of the conditions below are met:
> - The domain is used by an educational institution, which offers at least one long-term course (one year or longer), and the course is somehow related to IT (it is in computer science, software engineering, statistics, bioinformatics, etc.)
> - The educational institution is a physical entity with student attendance and recognized as providing a learning curriculum for the educational system, [...]

Does this school publish its curriculum? If yes, where can one read the courses description and schedule?

**Comment by marxo** [comment]
@philipto No worries, the site is indeed often times perceived as too simple. Yes, here's a link to our Core Competencies Programme for 2020, it's a 1 year programme. https://pionir.org/files/core2020.pdf

**Comment by philipto** [comment]
@marxo Thank you very much for a further clarification. I am sorry, I am a little bit confused now. The educational program which you mentioned is very very basic. I do not understand what your students need JetBrains tools for. 

If I were you, I'd probably use PyCharm Community Edition or IntelliJ IDEA Community to teach them how to make a webpage. 

Formally speaking, you have a year-long educational program, but the subject which is somehow (even remotely) related to software development takes just 14 hours of it. Please consider using a trial version or a Community edition. 

I'll get back to this request in a day or two. I cannot approve it right now.

**Comment by marxo** [comment]
@philipto Thank you for looking this over. I understand your reluctance while looking at the core programme specifically, and I wish to mitigate it as best as possible and demonstrate our eligibility not only formally but practically.

As you have already said, we are formally eligible for an educational status, but what is more important practically, after our Core Programme all our students proceed to attain very technical skills, most prominently in software and hardware engineering, namely Javascript and C, which is also demonstrated on our Github organization profile (https://github.com/pioniredu) where our students started releasing npm packages of their own code, others build sophisticated open-source hardware solutions, one of which is also available on our organization page, while another good example would be our effort to build open source black boxes, more info on that project here: https://kiwitcms.eu/blog/kiwi-tcms-team/2020/05/26/kiwi-tcms-is-partnering-up-with-pionir/

Lastly, our effort to find a suitable C IDE has led us to CLion, which is awesome, but unattainable to our students, as well as to the school which is free both as in freedom and as in beer.

I hope that this information will shed some light on our activities and how deeply technical and practical we are as a school, and would use JetBrains software to a great extent and to joy of many of our students. What ever your decision might be, my best and thank you for all the time you've taken to help me with this application.

**Comment by philipto** [comment]
@marxo Thank you very much for the details! It is now clear that your school is eligible for being added to this repository. 
Your pull request is merged. 

I am very glad to learn more about your school, and wish you a lot of success with JetBrains tools!

**Pull request merged**
