### PR TITLE
Create stud.vassboskovice.txt

### PR DESCRIPTION
**Pull request by danielvitek**

### CODE REVIEW

**Comment by zweizwei** [comment]
the school's domain is http://www.vassboskovice.cz/ - so the path should be cz/vassboskovice.txt - please fix the path accordingly

**Comment by danielvitek** [comment]
Yes that is, but students have emails on @stud.vassboskovice.eu.

2015-05-08 16:47 GMT+02:00 Elena Ganenkova <notifications@github.com>:

**Comment by zweizwei** [comment]
could you please add the link to the page / document, confirming this information?

**Comment by danielvitek** [comment]
I have PDF document with confirmation but i don't know how upload it here.

**Comment by danielvitek** [comment]
Here is it https://www.dropbox.com/s/n1biyv5tm7tk0n8/Confirmation.pdf

**Comment by zweizwei** [comment]
Thank you, i'm adding the domain!

**Comment by danielvitek** [comment]
Thank you.

**Pull request merged**
