### PR TITLE
Add Victoria Hochschule

### PR DESCRIPTION
**Pull request by MxMartin**

### CODE REVIEW

**Comment by philipto** [comment]
@MxMartin lib/domains/de/victoria-hochschule: this request has an incorrect file path format, please ensure that you are familiar with     this repository rules located at the bottom of [this page](https://github.com/JetBrains/swot) and change     your request accordingly. If you don't know how to change request, close it and open a new one.     If you are not able to make the pull request according the instructions, please send us an email to support@jetbrains.com. Please mention this request URL in the message.

**Comment by MxMartin** [comment]
@philipto Ah, dang, thanks for pointing that out! I updated the pull request

**Comment by philipto** [comment]
@MxMartin First stage of verification passed, official domain is [victoria-hochschule.de](https://victoria-hochschule.de) as far as I verified. This is just an informational note. Pull request is still in the review. I appreciate your patience while waiting for the final decision.

**Comment by MxMartin** [comment]
@philipto  If that helps: The university changed its name from hwtk to Victoria in 2020 and there is an approved domain from the old name here: https://github.com/JetBrains/swot/tree/master/lib/domains/de/hwtk

You can find the official announcement here: https://www.victoria-hochschule.de/umbenennung-aus-der-hwtk-wird-victoria/

**Comment by philipto** [comment]
@MxMartin Thank you for your patience while waiting for a review and processing your request. Pull request merged.

**Pull request merged**
