### PR TITLE
Create btk

### PR DESCRIPTION
**Pull request by DewanWK**

### CODE REVIEW

**Comment by DewanWK** [comment]
http://www.btk.fi/ is the official website

**Comment by philipto** [comment]
@DewanWK I am sorry, the website suggests that Turku Centre for Biotechnology is primarily a research institutiuon, not educational one. This repository lists colleges and universities in order to provide free licenses to students and teachers. 

If there is a number of researchers in Turku Centre for Biotechnology who in fact are students and wish to use JetBrains tools for educational purposes, there are no objections to include the domain into the repository. 

However, we would like to ensure that people in the Centre know that free student licenses which JetBrains grants via this repository are for educational purposes only, not for performing paid research work.

Please let us know if the Centre has educational programs and students enrolled into them.

**Comment by philipto** [comment]
@DewanWK You may miss the previous comment. Please give us some update on the issue, otherwise I have to close the request without merging. You also can contact sales@jetbrains.com even if the Centre does not have educational programs, JetBrains sales team will try and help in getting the licenses in the way which is most appropriate for you. Thank you for your understanding!

**Comment by philipto** [comment]
@DewanWK I am really sorry that you do not have any updates. As I mentioned before, I close this request. I really hope that you can send your request to JetBrains sales team if researchers need the licenses, and to classroom@jetbrains.com if you have some classes which the professors and the students need the licenses for. This repository rules do not allow to include research institutions domains if there is no regular educational courses offered  by the institution. Thank you for your understanding!

**Pull request closed without merging**
